{
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "version": "v5",
  "servicePath": "dfareporting/v5/",
  "basePath": "/dfareporting/v5/",
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "revision": "20260213",
  "id": "dfareporting:v5",
  "ownerName": "Google",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v5/",
  "fullyEncodeReservedExpansion": true,
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "title": "Campaign Manager 360 API",
  "protocol": "rest",
  "name": "dfareporting",
  "kind": "discovery#restDescription",
  "resources": {
    "languages": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of languages.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/languages",
          "id": "dfareporting.languages.list",
          "flatPath": "userprofiles/{userprofilesId}/languages"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "id": "dfareporting.mobileApps.get",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one mobile app by ID."
        },
        "list": {
          "id": "dfareporting.mobileApps.list",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "path": "userprofiles/{+profileId}/mobileApps",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves list of available mobile apps."
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.delete",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.patch",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field value. This method supports patch semantics."
        },
        "list": {
          "id": "dfareporting.creativeFieldValues.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "GET",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one creative field value by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "id": "dfareporting.creativeFieldValues.get"
        },
        "insert": {
          "id": "dfareporting.creativeFieldValues.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new creative field value."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing creative field value.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/files",
          "id": "dfareporting.files.list",
          "httpMethod": "GET",
          "description": "Lists files for a user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/files"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "supportsMediaDownload": true,
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "reports/{reportId}/files/{fileId}",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "id": "dfareporting.files.get"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one user role permission group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "id": "dfareporting.userRolePermissionGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "id": "dfareporting.userRolePermissionGroups.list",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "description": "Gets a list of all supported user role permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "get": {
          "id": "dfareporting.advertiserLandingPages.get",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "httpMethod": "GET",
          "description": "Gets one landing page by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new landing page.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.insert"
        },
        "update": {
          "id": "dfareporting.advertiserLandingPages.update",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing landing page.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "list": {
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "GET",
          "description": "Retrieves a list of landing pages.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.list"
        }
      }
    },
    "placements": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.patch"
        },
        "generatetags": {
          "id": "dfareporting.placements.generatetags",
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "httpMethod": "POST",
          "description": "Generates tags for a placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/generatetags"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one placement by ID.",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "id": "dfareporting.placements.get"
        },
        "insert": {
          "id": "dfareporting.placements.insert",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new placement.",
          "path": "userprofiles/{+profileId}/placements"
        },
        "update": {
          "id": "dfareporting.placements.update",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing placement."
        },
        "list": {
          "id": "dfareporting.placements.list",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging."
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one creative group by ID.",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "id": "dfareporting.creativeGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}"
        },
        "insert": {
          "id": "dfareporting.creativeGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new creative group.",
          "path": "userprofiles/{+profileId}/creativeGroups"
        },
        "update": {
          "path": "userprofiles/{+profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing creative group.",
          "id": "dfareporting.creativeGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "list": {
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list"
        },
        "patch": {
          "id": "dfareporting.creativeGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/creativeGroups"
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "id": "dfareporting.studioCreativeAssets.insert",
          "flatPath": "studio/creativeAssets",
          "supportsMediaUpload": true,
          "path": "studio/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new studio creative asset."
        }
      }
    },
    "directorySites": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "id": "dfareporting.directorySites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/directorySites"
        },
        "get": {
          "id": "dfareporting.directorySites.get",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one directory site by ID."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "id": "dfareporting.directorySites.insert",
          "httpMethod": "POST",
          "description": "Inserts a new directory site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "id": "dfareporting.billingProfiles.get",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one billing profile by ID.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "id": "dfareporting.billingProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing billing profile.",
          "path": "userprofiles/{+profileId}/billingProfiles"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "id": "dfareporting.billingProfiles.list",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging."
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "PATCH",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.patch",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        },
        "list": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "GET",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.list"
        },
        "get": {
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "httpMethod": "GET",
          "description": "Gets one targeting template by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "id": "dfareporting.targetingTemplates.get"
        },
        "insert": {
          "id": "dfareporting.targetingTemplates.insert",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "POST",
          "description": "Inserts a new targeting template.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates"
        },
        "update": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing targeting template.",
          "id": "dfareporting.targetingTemplates.update",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/browsers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of browsers.",
          "id": "dfareporting.browsers.list",
          "flatPath": "userprofiles/{userprofilesId}/browsers"
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "id": "dfareporting.countries.get",
          "httpMethod": "GET",
          "description": "Gets one country by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/countries/{+dartId}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/countries",
          "httpMethod": "GET",
          "description": "Retrieves a list of countries.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.list",
          "flatPath": "userprofiles/{userprofilesId}/countries"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one user role permission by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "id": "dfareporting.userRolePermissions.get"
        },
        "list": {
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "httpMethod": "GET",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "id": "dfareporting.floodlightActivityGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity group.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.update",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight activity group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups"
        },
        "list": {
          "id": "dfareporting.floodlightActivityGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.floodlightActivityGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "httpMethod": "GET",
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "id": "dfareporting.billingRates.list"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.list",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight configurations, possibly filtered."
        },
        "patch": {
          "id": "dfareporting.floodlightConfigurations.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "id": "dfareporting.floodlightConfigurations.get",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one floodlight configuration by ID."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight configuration.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.update"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "id": "dfareporting.advertiserInvoices.list"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "httpMethod": "PATCH",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.patch",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "id": "dfareporting.remarketingListShares.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list share.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "id": "dfareporting.postalCodes.list",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "httpMethod": "GET",
          "description": "Retrieves a list of postal codes.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/postalCodes"
        },
        "get": {
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "httpMethod": "GET",
          "description": "Gets one postal code by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.get",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one advertiser group by ID.",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "id": "dfareporting.advertiserGroups.get"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.update",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser group."
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.patch"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.delete",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "id": "dfareporting.targetableRemarketingLists.get",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "id": "dfareporting.targetableRemarketingLists.list"
        }
      }
    },
    "sizes": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "id": "dfareporting.sizes.list",
          "flatPath": "userprofiles/{userprofilesId}/sizes"
        },
        "get": {
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "httpMethod": "GET",
          "description": "Gets one size by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.get",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new size.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes",
          "id": "dfareporting.sizes.insert",
          "flatPath": "userprofiles/{userprofilesId}/sizes"
        }
      }
    },
    "advertisers": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one advertiser by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "id": "dfareporting.advertisers.get"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.insert"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser.",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.update"
        },
        "list": {
          "id": "dfareporting.advertisers.list",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.advertisers.patch",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/advertisers"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new creative asset.",
          "id": "dfareporting.creativeAssets.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "supportsMediaUpload": true
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "get": {
          "id": "dfareporting.dynamicProfiles.get",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets a dynamic profile by ID."
        },
        "insert": {
          "flatPath": "studio/dynamicProfiles",
          "id": "dfareporting.dynamicProfiles.insert",
          "httpMethod": "POST",
          "description": "Inserts a new dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles"
        },
        "update": {
          "flatPath": "studio/dynamicProfiles",
          "id": "dfareporting.dynamicProfiles.update",
          "path": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing dynamic profile."
        },
        "generateCode": {
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "id": "dfareporting.dynamicProfiles.generateCode"
        },
        "publish": {
          "httpMethod": "POST",
          "description": "Publish for a dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.publish",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish"
        }
      }
    },
    "eventTags": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.patch",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing event tag. This method supports patch semantics."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes an existing event tag.",
          "id": "dfareporting.eventTags.delete",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "id": "dfareporting.eventTags.get",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one event tag by ID."
        },
        "insert": {
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new event tag.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.insert"
        },
        "update": {
          "id": "dfareporting.eventTags.update",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing event tag.",
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.list"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets the account's active ad summary by account ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "get": {
          "id": "dfareporting.subaccounts.get",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one subaccount by ID.",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new subaccount.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "id": "dfareporting.subaccounts.insert"
        },
        "update": {
          "id": "dfareporting.subaccounts.update",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing subaccount."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "id": "dfareporting.subaccounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/subaccounts"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "id": "dfareporting.subaccounts.patch",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing subaccount. This method supports patch semantics."
        }
      }
    },
    "campaigns": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "id": "dfareporting.campaigns.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/campaigns"
        },
        "list": {
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "GET",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.list",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        },
        "get": {
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one campaign by ID.",
          "id": "dfareporting.campaigns.get",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new campaign.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "id": "dfareporting.campaigns.insert",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        },
        "update": {
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "PUT",
          "description": "Updates an existing campaign.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.update",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "id": "dfareporting.tvCampaignDetails.get",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one TvCampaignDetail by ID."
        }
      }
    },
    "reports": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "GET",
          "description": "Retrieves a report by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.get"
        },
        "insert": {
          "flatPath": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.insert",
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "description": "Creates a report."
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.update",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.list",
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "description": "Retrieves list of reports."
        },
        "run": {
          "id": "dfareporting.reports.run",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "description": "Runs a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}/run"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes a report by its ID.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.delete",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        }
      },
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "httpMethod": "POST",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "id": "dfareporting.reports.compatibleFields.query",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        },
        "files": {
          "methods": {
            "get": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "GET",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "supportsMediaDownload": true,
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "id": "dfareporting.reports.files.get"
            },
            "list": {
              "httpMethod": "GET",
              "description": "Lists files for a report.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "id": "dfareporting.reports.files.list"
            }
          }
        }
      }
    },
    "sites": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "id": "dfareporting.sites.patch",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PATCH",
          "description": "Updates an existing site. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.sites.get",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one site by ID.",
          "path": "userprofiles/{+profileId}/sites/{+id}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "id": "dfareporting.sites.insert",
          "httpMethod": "POST",
          "description": "Inserts a new site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites"
        },
        "update": {
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing site.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "id": "dfareporting.sites.update"
        },
        "list": {
          "id": "dfareporting.sites.list",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "generatetag": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "id": "dfareporting.floodlightActivities.generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Generates a tag for a floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "id": "dfareporting.floodlightActivities.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one floodlight activity by ID.",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}"
        },
        "insert": {
          "id": "dfareporting.floodlightActivities.insert",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.update",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.floodlightActivities.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities"
        },
        "delete": {
          "id": "dfareporting.floodlightActivities.delete",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes an existing floodlight activity."
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "httpMethod": "POST",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "id": "dfareporting.dimensionValues.query"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.list",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one account user profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "id": "dfareporting.accountUserProfiles.get",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}"
        },
        "insert": {
          "id": "dfareporting.accountUserProfiles.insert",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new account user profile.",
          "path": "userprofiles/{+profileId}/accountUserProfiles"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing account user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.update",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.patch"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "httpMethod": "GET",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations"
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one account by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "id": "dfareporting.accounts.get"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing account.",
          "path": "userprofiles/{+profileId}/accounts",
          "id": "dfareporting.accounts.update",
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        },
        "patch": {
          "id": "dfareporting.accounts.patch",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing account. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/accounts"
        },
        "list": {
          "id": "dfareporting.accounts.list",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "path": "userprofiles/{+profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging."
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "id": "dfareporting.mobileCarriers.get",
          "httpMethod": "GET",
          "description": "Gets one mobile carrier by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}"
        },
        "list": {
          "id": "dfareporting.mobileCarriers.list",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of mobile carriers.",
          "path": "userprofiles/{+profileId}/mobileCarriers"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/videoFormats",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Lists available video formats.",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "id": "dfareporting.videoFormats.list"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one video format by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "id": "dfareporting.videoFormats.get",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "list": {
          "id": "dfareporting.accountPermissions.list",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "httpMethod": "GET",
          "description": "Retrieves the list of account permissions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one account permission by ID.",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "id": "dfareporting.accountPermissions.get"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "id": "dfareporting.cities.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of cities, possibly filtered.",
          "path": "userprofiles/{+profileId}/cities"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "id": "dfareporting.creativeFields.delete",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "id": "dfareporting.creativeFields.patch",
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "id": "dfareporting.creativeFields.get",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "GET",
          "description": "Gets one creative field by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new creative field.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "id": "dfareporting.creativeFields.insert"
        },
        "update": {
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing creative field.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "id": "dfareporting.creativeFields.update"
        },
        "list": {
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "GET",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "id": "dfareporting.placementGroups.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "id": "dfareporting.placementGroups.get",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one placement group by ID."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "id": "dfareporting.placementGroups.insert",
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "POST",
          "description": "Inserts a new placement group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "id": "dfareporting.placementGroups.update",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing placement group."
        },
        "list": {
          "id": "dfareporting.placementGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys"
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes an existing dynamic targeting key.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of dynamic targeting keys.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.list"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of regions.",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "id": "dfareporting.regions.list"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "id": "dfareporting.operatingSystemVersions.list",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "httpMethod": "GET",
          "description": "Retrieves a list of operating system versions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one operating system version by ID.",
          "id": "dfareporting.operatingSystemVersions.get",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}"
        }
      }
    },
    "userRoles": {
      "methods": {
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "id": "dfareporting.userRoles.patch",
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.list",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "GET",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "id": "dfareporting.userRoles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one user role by ID.",
          "path": "userprofiles/{+profileId}/userRoles/{+id}"
        },
        "insert": {
          "id": "dfareporting.userRoles.insert",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new user role."
        },
        "update": {
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.update"
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "publish": {
          "flatPath": "studio/creatives/{creativesId}/publish",
          "id": "dfareporting.studioCreatives.publish",
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "httpMethod": "POST",
          "description": "Publish for a studio creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "studio/creatives/{creativesId}",
          "id": "dfareporting.studioCreatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets a studio creative by ID.",
          "path": "studio/creatives/{+studioCreativeId}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new studio creative.",
          "path": "studio/creatives",
          "id": "dfareporting.studioCreatives.insert",
          "flatPath": "studio/creatives"
        }
      }
    },
    "creatives": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.patch",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing creative. This method supports patch semantics."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one creative by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "id": "dfareporting.creatives.get",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.insert",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new creative."
        },
        "update": {
          "id": "dfareporting.creatives.update",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PUT",
          "description": "Updates an existing creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "id": "dfareporting.conversions.batchinsert",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST",
          "description": "Inserts conversions.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ]
        },
        "batchupdate": {
          "httpMethod": "POST",
          "description": "Updates existing conversions.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "id": "dfareporting.conversions.batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}",
          "id": "dfareporting.userProfiles.get",
          "httpMethod": "GET",
          "description": "Gets one user profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}"
        },
        "list": {
          "id": "dfareporting.userProfiles.list",
          "flatPath": "userprofiles",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves list of user profiles for a user.",
          "path": "userprofiles"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "id": "dfareporting.metros.list",
          "path": "userprofiles/{+profileId}/metros",
          "httpMethod": "GET",
          "description": "Retrieves a list of metros.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "id": "dfareporting.placementStrategies.list",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one placement strategy by ID.",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "id": "dfareporting.placementStrategies.get"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "id": "dfareporting.placementStrategies.insert",
          "httpMethod": "POST",
          "description": "Inserts a new placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "id": "dfareporting.placementStrategies.update"
        },
        "patch": {
          "id": "dfareporting.placementStrategies.patch",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placementStrategies"
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "id": "dfareporting.placementStrategies.delete",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}"
        }
      }
    },
    "ads": {
      "methods": {
        "get": {
          "id": "dfareporting.ads.get",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "httpMethod": "GET",
          "description": "Gets one ad by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads/{+id}"
        },
        "insert": {
          "id": "dfareporting.ads.insert",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new ad.",
          "path": "userprofiles/{+profileId}/ads"
        },
        "update": {
          "id": "dfareporting.ads.update",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing ad.",
          "path": "userprofiles/{+profileId}/ads"
        },
        "list": {
          "id": "dfareporting.ads.list",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "GET",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "id": "dfareporting.ads.patch",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "get": {
          "id": "dfareporting.dynamicFeeds.get",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets a dynamic feed by ID."
        },
        "insert": {
          "flatPath": "studio/dynamicFeeds",
          "id": "dfareporting.dynamicFeeds.insert",
          "path": "studio/dynamicFeeds",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new dynamic feed."
        },
        "update": {
          "id": "dfareporting.dynamicFeeds.update",
          "flatPath": "studio/dynamicFeeds",
          "path": "studio/dynamicFeeds",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored."
        },
        "retransform": {
          "id": "dfareporting.dynamicFeeds.retransform",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "httpMethod": "POST",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one connection type by ID.",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "id": "dfareporting.connectionTypes.get"
        },
        "list": {
          "path": "userprofiles/{+profileId}/connectionTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of connection types.",
          "id": "dfareporting.connectionTypes.list",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "id": "dfareporting.remarketingLists.get"
        },
        "insert": {
          "id": "dfareporting.remarketingLists.insert",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "POST",
          "description": "Inserts a new remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.update"
        },
        "list": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.remarketingLists.list",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "PATCH",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.patch",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "list": {
          "id": "dfareporting.contentCategories.list",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "GET",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one content category by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "id": "dfareporting.contentCategories.get",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new content category.",
          "id": "dfareporting.contentCategories.insert",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "id": "dfareporting.contentCategories.update",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "id": "dfareporting.contentCategories.patch"
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.delete",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "id": "dfareporting.platformTypes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one platform type by ID.",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}"
        },
        "list": {
          "id": "dfareporting.platformTypes.list",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "path": "userprofiles/{+profileId}/platformTypes",
          "httpMethod": "GET",
          "description": "Retrieves a list of platform types.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of TV campaign summaries.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "id": "dfareporting.tvCampaignSummaries.list"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "id": "dfareporting.billingAssignments.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of billing assignments.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "id": "dfareporting.billingAssignments.insert"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "id": "dfareporting.changeLogs.list",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "path": "userprofiles/{+profileId}/changeLogs",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of change logs. This method supports paging."
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "id": "dfareporting.changeLogs.get",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one change log by ID."
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "list": {
          "id": "dfareporting.operatingSystems.list",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "httpMethod": "GET",
          "description": "Retrieves a list of operating systems.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystems"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one operating system by DART ID.",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "id": "dfareporting.operatingSystems.get",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "id": "dfareporting.accountPermissionGroups.list",
          "httpMethod": "GET",
          "description": "Retrieves the list of account permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissionGroups"
        },
        "get": {
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "httpMethod": "GET",
          "description": "Gets one account permission group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissionGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}"
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        }
      }
    }
  },
  "canonicalName": "Dfareporting",
  "batchPath": "batch",
  "rootUrl": "https://dfareporting.googleapis.com/"
}