{
  "id": "admin:datatransfer_v1",
  "protocol": "rest",
  "servicePath": "",
  "name": "admin",
  "batchPath": "batch",
  "canonicalName": "DataTransfer",
  "revision": "20260407",
  "baseUrl": "https://admin.googleapis.com/",
  "mtlsRootUrl": "https://admin.mtls.googleapis.com/",
  "packagePath": "admin",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/admin.datatransfer": {
          "description": "View and manage data transfers between users in your organization"
        },
        "https://www.googleapis.com/auth/admin.datatransfer.readonly": {
          "description": "View data transfers between users in your organization"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "description": "Admin SDK lets administrators of enterprise domains to view and manage resources like user, groups etc. It also provides audit and usage reports of domain.",
  "ownerName": "Google",
  "title": "Admin SDK API",
  "discoveryVersion": "v1",
  "ownerDomain": "google.com",
  "resources": {
    "applications": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/admin.datatransfer",
            "https://www.googleapis.com/auth/admin.datatransfer.readonly"
          ],
          "httpMethod": "GET",
          "path": "admin/datatransfer/v1/applications/{applicationId}",
          "id": "datatransfer.applications.get",
          "flatPath": "admin/datatransfer/v1/applications/{applicationId}",
          "description": "Retrieves information about an application for the given application ID."
        },
        "list": {
          "path": "admin/datatransfer/v1/applications",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/admin.datatransfer",
            "https://www.googleapis.com/auth/admin.datatransfer.readonly"
          ],
          "flatPath": "admin/datatransfer/v1/applications",
          "description": "Lists the applications available for data transfer for a customer.",
          "id": "datatransfer.applications.list"
        }
      }
    },
    "transfers": {
      "methods": {
        "insert": {
          "id": "datatransfer.transfers.insert",
          "flatPath": "admin/datatransfer/v1/transfers",
          "description": "Inserts a data transfer request. See the [Transfer parameters](https://developers.google.com/workspace/admin/data-transfer/v1/parameters) reference for specific application requirements.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.datatransfer"
          ],
          "path": "admin/datatransfer/v1/transfers",
          "httpMethod": "POST"
        },
        "list": {
          "id": "datatransfer.transfers.list",
          "flatPath": "admin/datatransfer/v1/transfers",
          "description": "Lists the transfers for a customer by source user, destination user, or status.",
          "scopes": [
            "https://www.googleapis.com/auth/admin.datatransfer",
            "https://www.googleapis.com/auth/admin.datatransfer.readonly"
          ],
          "httpMethod": "GET",
          "path": "admin/datatransfer/v1/transfers"
        },
        "get": {
          "path": "admin/datatransfer/v1/transfers/{dataTransferId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/admin.datatransfer",
            "https://www.googleapis.com/auth/admin.datatransfer.readonly"
          ],
          "flatPath": "admin/datatransfer/v1/transfers/{dataTransferId}",
          "description": "Retrieves a data transfer request by its resource ID.",
          "id": "datatransfer.transfers.get"
        }
      }
    }
  },
  "version": "datatransfer_v1",
  "rootUrl": "https://admin.googleapis.com/",
  "basePath": "",
  "documentationLink": "https://developers.google.com/workspace/admin/",
  "kind": "discovery#restDescription"
}