{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/admob.readonly": {
          "description": "See your AdMob data"
        },
        "https://www.googleapis.com/auth/admob.report": {
          "description": "See your AdMob data"
        }
      }
    }
  },
  "version": "v1beta",
  "fullyEncodeReservedExpansion": true,
  "id": "admob:v1beta",
  "version_module": true,
  "servicePath": "",
  "protocol": "rest",
  "baseUrl": "https://admob.googleapis.com/",
  "name": "admob",
  "discoveryVersion": "v1",
  "mtlsRootUrl": "https://admob.mtls.googleapis.com/",
  "batchPath": "batch",
  "ownerName": "Google",
  "revision": "20260312",
  "basePath": "",
  "ownerDomain": "google.com",
  "canonicalName": "AdMob",
  "description": "The AdMob API allows publishers to programmatically get information about their AdMob account. ",
  "title": "AdMob API",
  "resources": {
    "accounts": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/admob.readonly",
            "https://www.googleapis.com/auth/admob.report"
          ],
          "httpMethod": "GET",
          "description": "Gets information about the specified AdMob publisher account.",
          "id": "admob.accounts.get",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}",
          "streamingType": "NONE"
        },
        "list": {
          "streamingType": "NONE",
          "flatPath": "v1beta/accounts",
          "id": "admob.accounts.list",
          "path": "v1beta/accounts",
          "description": "Lists the AdMob publisher account that was most recently signed in to from the AdMob UI. For more information, see https://support.google.com/admob/answer/10243672.",
          "scopes": [
            "https://www.googleapis.com/auth/admob.readonly",
            "https://www.googleapis.com/auth/admob.report"
          ],
          "httpMethod": "GET"
        }
      },
      "resources": {
        "networkReport": {
          "methods": {
            "generate": {
              "id": "admob.accounts.networkReport.generate",
              "path": "v1beta/{+parent}/networkReport:generate",
              "streamingType": "SERVER_SIDE",
              "flatPath": "v1beta/accounts/{accountsId}/networkReport:generate",
              "description": "Generates an AdMob Network report based on the provided report specification. Returns result of a server-side streaming RPC. The result is returned in a sequence of responses.",
              "scopes": [
                "https://www.googleapis.com/auth/admob.readonly",
                "https://www.googleapis.com/auth/admob.report"
              ],
              "httpMethod": "POST"
            }
          }
        },
        "adSources": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/admob.readonly",
                "https://www.googleapis.com/auth/admob.report"
              ],
              "description": "List the ad sources.",
              "id": "admob.accounts.adSources.list",
              "path": "v1beta/{+parent}/adSources",
              "flatPath": "v1beta/accounts/{accountsId}/adSources",
              "streamingType": "NONE"
            }
          },
          "resources": {
            "adapters": {
              "methods": {
                "list": {
                  "id": "admob.accounts.adSources.adapters.list",
                  "path": "v1beta/{+parent}/adapters",
                  "flatPath": "v1beta/accounts/{accountsId}/adSources/{adSourcesId}/adapters",
                  "streamingType": "NONE",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/admob.readonly"
                  ],
                  "description": "List the adapters of the ad source."
                }
              }
            }
          }
        },
        "mediationReport": {
          "methods": {
            "generate": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/admob.readonly",
                "https://www.googleapis.com/auth/admob.report"
              ],
              "description": "Generates an AdMob Mediation report based on the provided report specification. Returns result of a server-side streaming RPC. The result is returned in a sequence of responses.",
              "id": "admob.accounts.mediationReport.generate",
              "path": "v1beta/{+parent}/mediationReport:generate",
              "flatPath": "v1beta/accounts/{accountsId}/mediationReport:generate",
              "streamingType": "SERVER_SIDE"
            }
          }
        },
        "adUnitMappings": {
          "methods": {
            "batchCreate": {
              "id": "admob.accounts.adUnitMappings.batchCreate",
              "path": "v1beta/{+parent}/adUnitMappings:batchCreate",
              "flatPath": "v1beta/accounts/{accountsId}/adUnitMappings:batchCreate",
              "streamingType": "NONE",
              "httpMethod": "POST",
              "description": "Batch create the ad unit mappings under the specific AdMob account. The maximum allowed batch size is 100. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access."
            }
          }
        },
        "campaignReport": {
          "methods": {
            "generate": {
              "flatPath": "v1beta/accounts/{accountsId}/campaignReport:generate",
              "streamingType": "NONE",
              "id": "admob.accounts.campaignReport.generate",
              "path": "v1beta/{+parent}/campaignReport:generate",
              "scopes": [
                "https://www.googleapis.com/auth/admob.readonly",
                "https://www.googleapis.com/auth/admob.report"
              ],
              "httpMethod": "POST",
              "description": "Generates Campaign Report based on provided specifications."
            }
          }
        },
        "adUnits": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates an ad unit under the specified AdMob account. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.",
              "flatPath": "v1beta/accounts/{accountsId}/adUnits",
              "streamingType": "NONE",
              "id": "admob.accounts.adUnits.create",
              "path": "v1beta/{+parent}/adUnits"
            },
            "list": {
              "description": "List the ad units under the specified AdMob account.",
              "scopes": [
                "https://www.googleapis.com/auth/admob.readonly"
              ],
              "httpMethod": "GET",
              "id": "admob.accounts.adUnits.list",
              "path": "v1beta/{+parent}/adUnits",
              "streamingType": "NONE",
              "flatPath": "v1beta/accounts/{accountsId}/adUnits"
            }
          },
          "resources": {
            "adUnitMappings": {
              "methods": {
                "list": {
                  "id": "admob.accounts.adUnits.adUnitMappings.list",
                  "path": "v1beta/{+parent}/adUnitMappings",
                  "streamingType": "NONE",
                  "flatPath": "v1beta/accounts/{accountsId}/adUnits/{adUnitsId}/adUnitMappings",
                  "description": "List ad unit mappings under the specified AdMob account and ad unit. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/admob.readonly"
                  ]
                },
                "create": {
                  "flatPath": "v1beta/accounts/{accountsId}/adUnits/{adUnitsId}/adUnitMappings",
                  "streamingType": "NONE",
                  "id": "admob.accounts.adUnits.adUnitMappings.create",
                  "path": "v1beta/{+parent}/adUnitMappings",
                  "httpMethod": "POST",
                  "description": "Create an ad unit mapping under the specific AdMob account and ad unit. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access."
                }
              }
            }
          }
        },
        "mediationGroups": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Create a mediation group under the specific AdMob account. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.",
              "id": "admob.accounts.mediationGroups.create",
              "path": "v1beta/{+parent}/mediationGroups",
              "flatPath": "v1beta/accounts/{accountsId}/mediationGroups",
              "streamingType": "NONE"
            },
            "list": {
              "description": "List mediation groups under the specified AdMob account. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/admob.readonly"
              ],
              "streamingType": "NONE",
              "flatPath": "v1beta/accounts/{accountsId}/mediationGroups",
              "id": "admob.accounts.mediationGroups.list",
              "path": "v1beta/{+parent}/mediationGroups"
            },
            "patch": {
              "id": "admob.accounts.mediationGroups.patch",
              "path": "v1beta/{+name}",
              "streamingType": "NONE",
              "flatPath": "v1beta/accounts/{accountsId}/mediationGroups/{mediationGroupsId}",
              "description": "Update the specified mediation group under the specified AdMob account. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.",
              "httpMethod": "PATCH"
            }
          },
          "resources": {
            "mediationAbExperiments": {
              "methods": {
                "create": {
                  "httpMethod": "POST",
                  "description": "Create an A/B testing experiment for a specified AdMob account and a mediation group. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.",
                  "id": "admob.accounts.mediationGroups.mediationAbExperiments.create",
                  "path": "v1beta/{+parent}/mediationAbExperiments",
                  "flatPath": "v1beta/accounts/{accountsId}/mediationGroups/{mediationGroupsId}/mediationAbExperiments",
                  "streamingType": "NONE"
                },
                "stop": {
                  "id": "admob.accounts.mediationGroups.mediationAbExperiments.stop",
                  "path": "v1beta/{+name}:stop",
                  "flatPath": "v1beta/accounts/{accountsId}/mediationGroups/{mediationGroupsId}/mediationAbExperiments:stop",
                  "streamingType": "NONE",
                  "httpMethod": "POST",
                  "description": "Stop the mediation A/B experiment and choose a variant. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access."
                }
              }
            }
          }
        },
        "apps": {
          "methods": {
            "create": {
              "description": "Creates an app under the specified AdMob account. This method has limited access. If you see a 403 permission denied error, please reach out to your account manager for access.",
              "httpMethod": "POST",
              "streamingType": "NONE",
              "flatPath": "v1beta/accounts/{accountsId}/apps",
              "id": "admob.accounts.apps.create",
              "path": "v1beta/{+parent}/apps"
            },
            "list": {
              "description": "List the apps under the specified AdMob account.",
              "scopes": [
                "https://www.googleapis.com/auth/admob.readonly"
              ],
              "httpMethod": "GET",
              "id": "admob.accounts.apps.list",
              "path": "v1beta/{+parent}/apps",
              "streamingType": "NONE",
              "flatPath": "v1beta/accounts/{accountsId}/apps"
            }
          }
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "documentationLink": "https://developers.google.com/admob/api/",
  "rootUrl": "https://admob.googleapis.com/"
}