{
  "mtlsRootUrl": "https://adsense.mtls.googleapis.com/",
  "ownerName": "Google",
  "servicePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/adsense": {
          "description": "View and manage your AdSense data"
        },
        "https://www.googleapis.com/auth/adsense.readonly": {
          "description": "View your AdSense data"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "rootUrl": "https://adsense.googleapis.com/",
  "title": "AdSense Management API",
  "protocol": "rest",
  "batchPath": "batch",
  "documentationLink": "https://developers.google.com/adsense/management/",
  "name": "adsense",
  "fullyEncodeReservedExpansion": true,
  "id": "adsense:v2",
  "version_module": true,
  "revision": "20260409",
  "baseUrl": "https://adsense.googleapis.com/",
  "basePath": "",
  "ownerDomain": "google.com",
  "version": "v2",
  "kind": "discovery#restDescription",
  "resources": {
    "accounts": {
      "methods": {
        "list": {
          "flatPath": "v2/accounts",
          "description": "Lists all accounts available to this user.",
          "path": "v2/accounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "id": "adsense.accounts.list"
        },
        "getAdBlockingRecoveryTag": {
          "path": "v2/{+name}/adBlockingRecoveryTag",
          "id": "adsense.accounts.getAdBlockingRecoveryTag",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "flatPath": "v2/accounts/{accountsId}/adBlockingRecoveryTag",
          "description": "Gets the ad blocking recovery tag of an account."
        },
        "listChildAccounts": {
          "flatPath": "v2/accounts/{accountsId}:listChildAccounts",
          "description": "Lists all accounts directly managed by the given AdSense account.",
          "path": "v2/{+parent}:listChildAccounts",
          "id": "adsense.accounts.listChildAccounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ]
        },
        "get": {
          "id": "adsense.accounts.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "path": "v2/{+name}",
          "description": "Gets information about the selected AdSense account.",
          "flatPath": "v2/accounts/{accountsId}"
        }
      },
      "resources": {
        "sites": {
          "methods": {
            "list": {
              "flatPath": "v2/accounts/{accountsId}/sites",
              "description": "Lists all the sites available in an account.",
              "path": "v2/{+parent}/sites",
              "id": "adsense.accounts.sites.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            },
            "get": {
              "id": "adsense.accounts.sites.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "path": "v2/{+name}",
              "description": "Gets information about the selected site.",
              "flatPath": "v2/accounts/{accountsId}/sites/{sitesId}"
            }
          }
        },
        "alerts": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.alerts.list",
              "path": "v2/{+parent}/alerts",
              "description": "Lists all the alerts available in an account.",
              "flatPath": "v2/accounts/{accountsId}/alerts"
            }
          }
        },
        "policyIssues": {
          "methods": {
            "get": {
              "path": "v2/{+name}",
              "id": "adsense.accounts.policyIssues.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "flatPath": "v2/accounts/{accountsId}/policyIssues/{policyIssuesId}",
              "description": "Gets information about the selected policy issue."
            },
            "list": {
              "flatPath": "v2/accounts/{accountsId}/policyIssues",
              "description": "Lists all the policy issues where the specified account is involved, both directly and through any AFP child accounts.",
              "path": "v2/{+parent}/policyIssues",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.policyIssues.list"
            }
          }
        },
        "reports": {
          "methods": {
            "generateCsv": {
              "flatPath": "v2/accounts/{accountsId}/reports:generateCsv",
              "description": "Generates a csv formatted ad hoc report.",
              "path": "v2/{+account}/reports:generateCsv",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.reports.generateCsv"
            },
            "generate": {
              "flatPath": "v2/accounts/{accountsId}/reports:generate",
              "description": "Generates an ad hoc report.",
              "path": "v2/{+account}/reports:generate",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.reports.generate"
            },
            "getSaved": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.reports.getSaved",
              "path": "v2/{+name}/saved",
              "description": "Gets the saved report from the given resource name.",
              "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved"
            }
          },
          "resources": {
            "saved": {
              "methods": {
                "list": {
                  "path": "v2/{+parent}/reports/saved",
                  "id": "adsense.accounts.reports.saved.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "flatPath": "v2/accounts/{accountsId}/reports/saved",
                  "description": "Lists saved reports."
                },
                "generate": {
                  "path": "v2/{+name}/saved:generate",
                  "id": "adsense.accounts.reports.saved.generate",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved:generate",
                  "description": "Generates a saved report."
                },
                "generateCsv": {
                  "path": "v2/{+name}/saved:generateCsv",
                  "id": "adsense.accounts.reports.saved.generateCsv",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved:generateCsv",
                  "description": "Generates a csv formatted saved report."
                }
              }
            }
          }
        },
        "adclients": {
          "methods": {
            "get": {
              "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}",
              "description": "Gets the ad client from the given resource name.",
              "path": "v2/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.adclients.get"
            },
            "getAdcode": {
              "path": "v2/{+name}/adcode",
              "id": "adsense.accounts.adclients.getAdcode",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adcode",
              "description": "Gets the AdSense code for a given ad client. This returns what was previously known as the 'auto ad code'. This is only supported for ad clients with a product_code of AFC. For more information, see [About the AdSense code](https://support.google.com/adsense/answer/9274634)."
            },
            "list": {
              "description": "Lists all the ad clients available in an account.",
              "flatPath": "v2/accounts/{accountsId}/adclients",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.adclients.list",
              "path": "v2/{+parent}/adclients"
            }
          },
          "resources": {
            "customchannels": {
              "methods": {
                "get": {
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}",
                  "description": "Gets information about the selected custom channel.",
                  "path": "v2/{+name}",
                  "id": "adsense.accounts.adclients.customchannels.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "delete": {
                  "id": "adsense.accounts.adclients.customchannels.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "path": "v2/{+name}",
                  "description": "Deletes a custom channel. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}"
                },
                "create": {
                  "path": "v2/{+parent}/customchannels",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "id": "adsense.accounts.adclients.customchannels.create",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels",
                  "description": "Creates a custom channel. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method."
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.adclients.customchannels.list",
                  "path": "v2/{+parent}/customchannels",
                  "description": "Lists all the custom channels available in an ad client.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels"
                },
                "patch": {
                  "description": "Updates a custom channel. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}",
                  "id": "adsense.accounts.adclients.customchannels.patch",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "path": "v2/{+name}"
                },
                "listLinkedAdUnits": {
                  "description": "Lists all the ad units available for a custom channel.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}:listLinkedAdUnits",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.adclients.customchannels.listLinkedAdUnits",
                  "path": "v2/{+parent}:listLinkedAdUnits"
                }
              }
            },
            "adunits": {
              "methods": {
                "getAdcode": {
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}/adcode",
                  "description": "Gets the ad unit code for a given ad unit. For more information, see [About the AdSense code](https://support.google.com/adsense/answer/9274634) and [Where to place the ad code in your HTML](https://support.google.com/adsense/answer/9190028).",
                  "path": "v2/{+name}/adcode",
                  "id": "adsense.accounts.adclients.adunits.getAdcode",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "patch": {
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}",
                  "description": "Updates an ad unit. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method. For now, this method can only be used to update `DISPLAY` ad units. See: https://support.google.com/adsense/answer/9183566",
                  "path": "v2/{+name}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "id": "adsense.accounts.adclients.adunits.patch"
                },
                "get": {
                  "description": "Gets an ad unit from a specified account and ad client.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}",
                  "id": "adsense.accounts.adclients.adunits.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "path": "v2/{+name}"
                },
                "list": {
                  "description": "Lists all ad units under a specified account and ad client.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.adclients.adunits.list",
                  "path": "v2/{+parent}/adunits"
                },
                "listLinkedCustomChannels": {
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}:listLinkedCustomChannels",
                  "description": "Lists all the custom channels available for an ad unit.",
                  "path": "v2/{+parent}:listLinkedCustomChannels",
                  "id": "adsense.accounts.adclients.adunits.listLinkedCustomChannels",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "id": "adsense.accounts.adclients.adunits.create",
                  "path": "v2/{+parent}/adunits",
                  "description": "Creates an ad unit. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method. Note that ad units can only be created for ad clients with an \"AFC\" product code. For more info see the [AdClient resource](/adsense/management/reference/rest/v2/accounts.adclients). For now, this method ca[...]",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits"
                }
              }
            },
            "urlchannels": {
              "methods": {
                "get": {
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels/{urlchannelsId}",
                  "description": "Gets information about the selected url channel.",
                  "path": "v2/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.adclients.urlchannels.get"
                },
                "list": {
                  "description": "Lists active url channels.",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.adclients.urlchannels.list",
                  "path": "v2/{+parent}/urlchannels"
                }
              }
            }
          }
        },
        "payments": {
          "methods": {
            "list": {
              "id": "adsense.accounts.payments.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "path": "v2/{+parent}/payments",
              "description": "Lists all the payments available for an account.",
              "flatPath": "v2/accounts/{accountsId}/payments"
            }
          }
        }
      }
    }
  },
  "description": "The AdSense Management API allows publishers to access their inventory and run earnings and performance reports."
}