{
  "ownerName": "Google",
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://adsenseplatform.googleapis.com/",
  "title": "AdSense Platform API",
  "basePath": "",
  "mtlsRootUrl": "https://adsenseplatform.mtls.googleapis.com/",
  "id": "adsenseplatform:v1alpha",
  "resources": {
    "accounts": {
      "resources": {
        "platforms": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/platforms/{platformsId}",
              "id": "adsenseplatform.accounts.platforms.get",
              "httpMethod": "GET",
              "description": "Gets a platform."
            },
            "list": {
              "id": "adsenseplatform.accounts.platforms.list",
              "httpMethod": "GET",
              "description": "Lists platforms for a specified account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/platforms",
              "path": "v1alpha/{+parent}/platforms"
            }
          },
          "resources": {
            "childAccounts": {
              "resources": {
                "sites": {
                  "methods": {
                    "patch": {
                      "httpMethod": "PATCH",
                      "id": "adsenseplatform.accounts.platforms.childAccounts.sites.patch",
                      "description": "Update a Platform Child Site.",
                      "scopes": [
                        "https://www.googleapis.com/auth/adsense"
                      ],
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/accounts/{accountsId}/platforms/{platformsId}/childAccounts/{childAccountsId}/sites/{sitesId}"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/adsense",
                        "https://www.googleapis.com/auth/adsense.readonly"
                      ],
                      "flatPath": "v1alpha/accounts/{accountsId}/platforms/{platformsId}/childAccounts/{childAccountsId}/sites",
                      "path": "v1alpha/{+parent}/sites",
                      "id": "adsenseplatform.accounts.platforms.childAccounts.sites.list",
                      "httpMethod": "GET",
                      "description": "Lists Platform Child Sites for a specified Platform Child Account."
                    },
                    "get": {
                      "flatPath": "v1alpha/accounts/{accountsId}/platforms/{platformsId}/childAccounts/{childAccountsId}/sites/{sitesId}",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/adsense",
                        "https://www.googleapis.com/auth/adsense.readonly"
                      ],
                      "description": "Gets a Platform Child Site for a specified Platform Child Account and site.",
                      "httpMethod": "GET",
                      "id": "adsenseplatform.accounts.platforms.childAccounts.sites.get"
                    }
                  }
                }
              }
            },
            "groups": {
              "methods": {
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "flatPath": "v1alpha/accounts/{accountsId}/platforms/{platformsId}/groups/{groupsId}",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "id": "adsenseplatform.accounts.platforms.groups.patch",
                  "description": "Update a Platform Group."
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "path": "v1alpha/{+parent}/groups",
                  "flatPath": "v1alpha/accounts/{accountsId}/platforms/{platformsId}/groups",
                  "id": "adsenseplatform.accounts.platforms.groups.list",
                  "httpMethod": "GET",
                  "description": "Lists Platform Groups for a specified Platform."
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "adsenseplatform.accounts.platforms.groups.get",
                  "description": "Gets a Platform Group for a specified Platform and group.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "flatPath": "v1alpha/accounts/{accountsId}/platforms/{platformsId}/groups/{groupsId}",
                  "path": "v1alpha/{+name}"
                }
              }
            }
          }
        }
      }
    },
    "platforms": {
      "resources": {
        "accounts": {
          "methods": {
            "lookup": {
              "description": "Looks up information about a sub-account for a specified creation_request_id. If no account exists for the given creation_request_id, returns 404.",
              "httpMethod": "GET",
              "id": "adsenseplatform.platforms.accounts.lookup",
              "flatPath": "v1alpha/platforms/{platformsId}/accounts:lookup",
              "path": "v1alpha/{+parent}/accounts:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            },
            "get": {
              "id": "adsenseplatform.platforms.accounts.get",
              "httpMethod": "GET",
              "description": "Gets information about the selected sub-account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "flatPath": "v1alpha/platforms/{platformsId}/accounts/{accountsId}",
              "path": "v1alpha/{+name}"
            },
            "close": {
              "description": "Closes a sub-account.",
              "httpMethod": "POST",
              "id": "adsenseplatform.platforms.accounts.close",
              "path": "v1alpha/{+name}:close",
              "flatPath": "v1alpha/platforms/{platformsId}/accounts/{accountsId}:close",
              "scopes": [
                "https://www.googleapis.com/auth/adsense"
              ]
            },
            "list": {
              "path": "v1alpha/{+parent}/accounts",
              "flatPath": "v1alpha/platforms/{platformsId}/accounts",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Lists a partial view of sub-accounts for a specific parent account.",
              "id": "adsenseplatform.platforms.accounts.list",
              "httpMethod": "GET"
            },
            "create": {
              "description": "Creates a sub-account.",
              "httpMethod": "POST",
              "id": "adsenseplatform.platforms.accounts.create",
              "path": "v1alpha/{+parent}/accounts",
              "flatPath": "v1alpha/platforms/{platformsId}/accounts",
              "scopes": [
                "https://www.googleapis.com/auth/adsense"
              ]
            }
          },
          "resources": {
            "events": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "path": "v1alpha/{+parent}/events",
                  "flatPath": "v1alpha/platforms/{platformsId}/accounts/{accountsId}/events",
                  "httpMethod": "POST",
                  "id": "adsenseplatform.platforms.accounts.events.create",
                  "description": "Creates an account event."
                }
              }
            },
            "sites": {
              "methods": {
                "list": {
                  "flatPath": "v1alpha/platforms/{platformsId}/accounts/{accountsId}/sites",
                  "path": "v1alpha/{+parent}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists sites for a specific account.",
                  "httpMethod": "GET",
                  "id": "adsenseplatform.platforms.accounts.sites.list"
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "adsenseplatform.platforms.accounts.sites.create",
                  "description": "Creates a site for a specified account.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "flatPath": "v1alpha/platforms/{platformsId}/accounts/{accountsId}/sites",
                  "path": "v1alpha/{+parent}/sites"
                },
                "delete": {
                  "flatPath": "v1alpha/platforms/{platformsId}/accounts/{accountsId}/sites/{sitesId}",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "description": "Deletes a site from a specified account.",
                  "httpMethod": "DELETE",
                  "id": "adsenseplatform.platforms.accounts.sites.delete"
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "adsenseplatform.platforms.accounts.sites.get",
                  "description": "Gets a site from a specified sub-account.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "flatPath": "v1alpha/platforms/{platformsId}/accounts/{accountsId}/sites/{sitesId}",
                  "path": "v1alpha/{+name}"
                },
                "requestReview": {
                  "httpMethod": "POST",
                  "id": "adsenseplatform.platforms.accounts.sites.requestReview",
                  "description": "Requests the review of a site. The site should be in REQUIRES_REVIEW or NEEDS_ATTENTION state. Note: Make sure you place an [ad tag](https://developers.google.com/adsense/platforms/direct/ad-tags) on your site before requesting a review.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "path": "v1alpha/{+name}:requestReview",
                  "flatPath": "v1alpha/platforms/{platformsId}/accounts/{accountsId}/sites/{sitesId}:requestReview"
                }
              }
            }
          }
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/adsense/platforms/",
  "canonicalName": "AdSense Platform",
  "servicePath": "",
  "revision": "20260401",
  "description": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/adsense.readonly": {
          "description": "View your AdSense data"
        },
        "https://www.googleapis.com/auth/adsense": {
          "description": "View and manage your AdSense data"
        }
      }
    }
  },
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "protocol": "rest",
  "name": "adsenseplatform",
  "version_module": true,
  "version": "v1alpha",
  "baseUrl": "https://adsenseplatform.googleapis.com/",
  "ownerDomain": "google.com"
}