{
  "description": "",
  "name": "adsenseplatform",
  "baseUrl": "https://adsenseplatform.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/adsense.readonly": {
          "description": "View your AdSense data"
        },
        "https://www.googleapis.com/auth/adsense": {
          "description": "View and manage your AdSense data"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "canonicalName": "AdSense Platform",
  "revision": "20260312",
  "servicePath": "",
  "mtlsRootUrl": "https://adsenseplatform.mtls.googleapis.com/",
  "protocol": "rest",
  "basePath": "",
  "version_module": true,
  "documentationLink": "https://developers.google.com/adsense/platforms/",
  "fullyEncodeReservedExpansion": true,
  "id": "adsenseplatform:v1",
  "kind": "discovery#restDescription",
  "resources": {
    "platforms": {
      "resources": {
        "accounts": {
          "methods": {
            "list": {
              "path": "v1/{+parent}/accounts",
              "id": "adsenseplatform.platforms.accounts.list",
              "flatPath": "v1/platforms/{platformsId}/accounts",
              "description": "Lists a partial view of sub-accounts for a specific parent account.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            },
            "close": {
              "path": "v1/{+name}:close",
              "id": "adsenseplatform.platforms.accounts.close",
              "flatPath": "v1/platforms/{platformsId}/accounts/{accountsId}:close",
              "description": "Closes a sub-account.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/adsense"
              ]
            },
            "lookup": {
              "flatPath": "v1/platforms/{platformsId}/accounts:lookup",
              "description": "Looks up information about a sub-account for a specified creation_request_id. If no account exists for the given creation_request_id, returns 404.",
              "path": "v1/{+parent}/accounts:lookup",
              "id": "adsenseplatform.platforms.accounts.lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            },
            "create": {
              "flatPath": "v1/platforms/{platformsId}/accounts",
              "description": "Creates a sub-account.",
              "path": "v1/{+parent}/accounts",
              "id": "adsenseplatform.platforms.accounts.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/adsense"
              ]
            },
            "get": {
              "path": "v1/{+name}",
              "id": "adsenseplatform.platforms.accounts.get",
              "flatPath": "v1/platforms/{platformsId}/accounts/{accountsId}",
              "description": "Gets information about the selected sub-account.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            }
          },
          "resources": {
            "events": {
              "methods": {
                "create": {
                  "id": "adsenseplatform.platforms.accounts.events.create",
                  "path": "v1/{+parent}/events",
                  "flatPath": "v1/platforms/{platformsId}/accounts/{accountsId}/events",
                  "description": "Creates an account event.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "httpMethod": "POST"
                }
              }
            },
            "sites": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "flatPath": "v1/platforms/{platformsId}/accounts/{accountsId}/sites",
                  "description": "Lists sites for a specific account.",
                  "path": "v1/{+parent}/sites",
                  "id": "adsenseplatform.platforms.accounts.sites.list"
                },
                "delete": {
                  "flatPath": "v1/platforms/{platformsId}/accounts/{accountsId}/sites/{sitesId}",
                  "description": "Deletes a site from a specified account.",
                  "path": "v1/{+name}",
                  "id": "adsenseplatform.platforms.accounts.sites.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ]
                },
                "create": {
                  "path": "v1/{+parent}/sites",
                  "id": "adsenseplatform.platforms.accounts.sites.create",
                  "flatPath": "v1/platforms/{platformsId}/accounts/{accountsId}/sites",
                  "description": "Creates a site for a specified account.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ]
                },
                "get": {
                  "flatPath": "v1/platforms/{platformsId}/accounts/{accountsId}/sites/{sitesId}",
                  "description": "Gets a site from a specified sub-account.",
                  "path": "v1/{+name}",
                  "id": "adsenseplatform.platforms.accounts.sites.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "requestReview": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "httpMethod": "POST",
                  "id": "adsenseplatform.platforms.accounts.sites.requestReview",
                  "path": "v1/{+name}:requestReview",
                  "flatPath": "v1/platforms/{platformsId}/accounts/{accountsId}/sites/{sitesId}:requestReview",
                  "description": "Requests the review of a site. The site should be in REQUIRES_REVIEW or NEEDS_ATTENTION state. Note: Make sure you place an [ad tag](https://developers.google.com/adsense/platforms/direct/ad-tags) on your site before requesting a review."
                }
              }
            }
          }
        }
      }
    }
  },
  "version": "v1",
  "rootUrl": "https://adsenseplatform.googleapis.com/",
  "title": "AdSense Platform API"
}