{
  "title": "AdSense Management API",
  "id": "adsense:v2",
  "servicePath": "",
  "ownerName": "Google",
  "version_module": true,
  "basePath": "",
  "discoveryVersion": "v1",
  "version": "v2",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://adsense.googleapis.com/",
  "documentationLink": "https://developers.google.com/adsense/management/",
  "name": "adsense",
  "baseUrl": "https://adsense.googleapis.com/",
  "description": "The AdSense Management API allows publishers to access their inventory and run earnings and performance reports.",
  "batchPath": "batch",
  "protocol": "rest",
  "mtlsRootUrl": "https://adsense.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/adsense": {
          "description": "View and manage your AdSense data"
        },
        "https://www.googleapis.com/auth/adsense.readonly": {
          "description": "View your AdSense data"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "revision": "20260423",
  "resources": {
    "accounts": {
      "methods": {
        "get": {
          "path": "v2/{+name}",
          "flatPath": "v2/accounts/{accountsId}",
          "description": "Gets information about the selected AdSense account.",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "httpMethod": "GET",
          "id": "adsense.accounts.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "httpMethod": "GET",
          "id": "adsense.accounts.list",
          "path": "v2/accounts",
          "flatPath": "v2/accounts",
          "description": "Lists all accounts available to this user."
        },
        "getAdBlockingRecoveryTag": {
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "id": "adsense.accounts.getAdBlockingRecoveryTag",
          "httpMethod": "GET",
          "path": "v2/{+name}/adBlockingRecoveryTag",
          "flatPath": "v2/accounts/{accountsId}/adBlockingRecoveryTag",
          "description": "Gets the ad blocking recovery tag of an account."
        },
        "listChildAccounts": {
          "id": "adsense.accounts.listChildAccounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/adsense",
            "https://www.googleapis.com/auth/adsense.readonly"
          ],
          "description": "Lists all accounts directly managed by the given AdSense account.",
          "path": "v2/{+parent}:listChildAccounts",
          "flatPath": "v2/accounts/{accountsId}:listChildAccounts"
        }
      },
      "resources": {
        "alerts": {
          "methods": {
            "list": {
              "path": "v2/{+parent}/alerts",
              "flatPath": "v2/accounts/{accountsId}/alerts",
              "description": "Lists all the alerts available in an account.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.alerts.list",
              "httpMethod": "GET"
            }
          }
        },
        "adclients": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "httpMethod": "GET",
              "id": "adsense.accounts.adclients.list",
              "path": "v2/{+parent}/adclients",
              "flatPath": "v2/accounts/{accountsId}/adclients",
              "description": "Lists all the ad clients available in an account."
            },
            "get": {
              "path": "v2/{+name}",
              "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}",
              "description": "Gets the ad client from the given resource name.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.adclients.get",
              "httpMethod": "GET"
            },
            "getAdcode": {
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "httpMethod": "GET",
              "id": "adsense.accounts.adclients.getAdcode",
              "path": "v2/{+name}/adcode",
              "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adcode",
              "description": "Gets the AdSense code for a given ad client. This returns what was previously known as the 'auto ad code'. This is only supported for ad clients with a product_code of AFC. For more information, see [About the AdSense code](https://support.google.com/adsense/answer/9274634)."
            }
          },
          "resources": {
            "urlchannels": {
              "methods": {
                "get": {
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels/{urlchannelsId}",
                  "description": "Gets information about the selected url channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "adsense.accounts.adclients.urlchannels.get"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.adclients.urlchannels.list",
                  "httpMethod": "GET",
                  "path": "v2/{+parent}/urlchannels",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/urlchannels",
                  "description": "Lists active url channels."
                }
              }
            },
            "adunits": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "httpMethod": "POST",
                  "id": "adsense.accounts.adclients.adunits.create",
                  "path": "v2/{+parent}/adunits",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits",
                  "description": "Creates an ad unit. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method. Note that ad units can only be created for ad clients with an \"AFC\" product code. For more info see the [AdClient resource](/adsense/management/reference/rest/v2/accounts.adclients). For now, this method ca[...]"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.adclients.adunits.list",
                  "httpMethod": "GET",
                  "path": "v2/{+parent}/adunits",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits",
                  "description": "Lists all ad units under a specified account and ad client."
                },
                "patch": {
                  "description": "Updates an ad unit. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method. For now, this method can only be used to update `DISPLAY` ad units. See: https://support.google.com/adsense/answer/9183566",
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}",
                  "id": "adsense.accounts.adclients.adunits.patch",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ]
                },
                "getAdcode": {
                  "path": "v2/{+name}/adcode",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}/adcode",
                  "description": "Gets the ad unit code for a given ad unit. For more information, see [About the AdSense code](https://support.google.com/adsense/answer/9274634) and [Where to place the ad code in your HTML](https://support.google.com/adsense/answer/9190028).",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "adsense.accounts.adclients.adunits.getAdcode"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "adsense.accounts.adclients.adunits.get",
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}",
                  "description": "Gets an ad unit from a specified account and ad client."
                },
                "listLinkedCustomChannels": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "adsense.accounts.adclients.adunits.listLinkedCustomChannels",
                  "path": "v2/{+parent}:listLinkedCustomChannels",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/adunits/{adunitsId}:listLinkedCustomChannels",
                  "description": "Lists all the custom channels available for an ad unit."
                }
              }
            },
            "customchannels": {
              "methods": {
                "get": {
                  "description": "Gets information about the selected custom channel.",
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}",
                  "id": "adsense.accounts.adclients.customchannels.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "adsense.accounts.adclients.customchannels.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ],
                  "description": "Deletes a custom channel. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method.",
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}"
                },
                "listLinkedAdUnits": {
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.adclients.customchannels.listLinkedAdUnits",
                  "httpMethod": "GET",
                  "path": "v2/{+parent}:listLinkedAdUnits",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}:listLinkedAdUnits",
                  "description": "Lists all the ad units available for a custom channel."
                },
                "list": {
                  "httpMethod": "GET",
                  "id": "adsense.accounts.adclients.customchannels.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists all the custom channels available in an ad client.",
                  "path": "v2/{+parent}/customchannels",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels"
                },
                "patch": {
                  "description": "Updates a custom channel. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method.",
                  "path": "v2/{+name}",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels/{customchannelsId}",
                  "id": "adsense.accounts.adclients.customchannels.patch",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ]
                },
                "create": {
                  "description": "Creates a custom channel. This method can be called only by a restricted set of projects, which are usually owned by [AdSense for Platforms](https://developers.google.com/adsense/platforms/) publishers. Contact your account manager if you need to use this method.",
                  "path": "v2/{+parent}/customchannels",
                  "flatPath": "v2/accounts/{accountsId}/adclients/{adclientsId}/customchannels",
                  "httpMethod": "POST",
                  "id": "adsense.accounts.adclients.customchannels.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense"
                  ]
                }
              }
            }
          }
        },
        "policyIssues": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "httpMethod": "GET",
              "id": "adsense.accounts.policyIssues.get",
              "path": "v2/{+name}",
              "flatPath": "v2/accounts/{accountsId}/policyIssues/{policyIssuesId}",
              "description": "Gets information about the selected policy issue."
            },
            "list": {
              "description": "Lists all the policy issues where the specified account is involved, both directly and through any AFP child accounts.",
              "path": "v2/{+parent}/policyIssues",
              "flatPath": "v2/accounts/{accountsId}/policyIssues",
              "httpMethod": "GET",
              "id": "adsense.accounts.policyIssues.list",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            }
          }
        },
        "reports": {
          "methods": {
            "getSaved": {
              "description": "Gets the saved report from the given resource name.",
              "path": "v2/{+name}/saved",
              "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved",
              "httpMethod": "GET",
              "id": "adsense.accounts.reports.getSaved",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            },
            "generateCsv": {
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "id": "adsense.accounts.reports.generateCsv",
              "httpMethod": "GET",
              "path": "v2/{+account}/reports:generateCsv",
              "flatPath": "v2/accounts/{accountsId}/reports:generateCsv",
              "description": "Generates a csv formatted ad hoc report."
            },
            "generate": {
              "httpMethod": "GET",
              "id": "adsense.accounts.reports.generate",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "description": "Generates an ad hoc report.",
              "path": "v2/{+account}/reports:generate",
              "flatPath": "v2/accounts/{accountsId}/reports:generate"
            }
          },
          "resources": {
            "saved": {
              "methods": {
                "generateCsv": {
                  "description": "Generates a csv formatted saved report.",
                  "path": "v2/{+name}/saved:generateCsv",
                  "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved:generateCsv",
                  "httpMethod": "GET",
                  "id": "adsense.accounts.reports.saved.generateCsv",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ]
                },
                "generate": {
                  "path": "v2/{+name}/saved:generate",
                  "flatPath": "v2/accounts/{accountsId}/reports/{reportsId}/saved:generate",
                  "description": "Generates a saved report.",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "id": "adsense.accounts.reports.saved.generate",
                  "httpMethod": "GET"
                },
                "list": {
                  "httpMethod": "GET",
                  "id": "adsense.accounts.reports.saved.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/adsense",
                    "https://www.googleapis.com/auth/adsense.readonly"
                  ],
                  "description": "Lists saved reports.",
                  "path": "v2/{+parent}/reports/saved",
                  "flatPath": "v2/accounts/{accountsId}/reports/saved"
                }
              }
            }
          }
        },
        "sites": {
          "methods": {
            "get": {
              "path": "v2/{+name}",
              "flatPath": "v2/accounts/{accountsId}/sites/{sitesId}",
              "description": "Gets information about the selected site.",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "httpMethod": "GET",
              "id": "adsense.accounts.sites.get"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ],
              "httpMethod": "GET",
              "id": "adsense.accounts.sites.list",
              "path": "v2/{+parent}/sites",
              "flatPath": "v2/accounts/{accountsId}/sites",
              "description": "Lists all the sites available in an account."
            }
          }
        },
        "payments": {
          "methods": {
            "list": {
              "description": "Lists all the payments available for an account.",
              "path": "v2/{+parent}/payments",
              "flatPath": "v2/accounts/{accountsId}/payments",
              "id": "adsense.accounts.payments.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/adsense",
                "https://www.googleapis.com/auth/adsense.readonly"
              ]
            }
          }
        }
      }
    }
  },
  "ownerDomain": "google.com"
}