{
  "name": "agentregistry",
  "baseUrl": "https://agentregistry.googleapis.com/",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "documentationLink": "https://docs.cloud.google.com/agent-registry/overview",
  "id": "agentregistry:v1alpha",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/agentregistry.read-only": {
          "description": "See your Google Cloud Agent Registry data and the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/agentregistry.read-write": {
          "description": "See, edit, configure, and delete your Google Cloud Agent Registry data and see the email address for your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud services and see the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        }
      }
    }
  },
  "resources": {
    "projects": {
      "resources": {
        "locations": {
          "resources": {
            "operations": {
              "methods": {
                "list": {
                  "path": "v1alpha/{+name}/operations",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "agentregistry.projects.locations.operations.list",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "agentregistry.projects.locations.operations.get",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "agentregistry.projects.locations.operations.delete",
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`."
                },
                "cancel": {
                  "path": "v1alpha/{+name}:cancel",
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it be[...]",
                  "id": "agentregistry.projects.locations.operations.cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}:cancel",
                  "httpMethod": "POST"
                }
              }
            },
            "mcpServers": {
              "methods": {
                "list": {
                  "description": "Lists McpServers in a given project and location.",
                  "id": "agentregistry.projects.locations.mcpServers.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+parent}/mcpServers"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers/{mcpServersId}",
                  "httpMethod": "GET",
                  "description": "Gets details of a single McpServer.",
                  "id": "agentregistry.projects.locations.mcpServers.get",
                  "path": "v1alpha/{+name}"
                },
                "search": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers:search",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "agentregistry.projects.locations.mcpServers.search",
                  "description": "Searches McpServers in a given project and location.",
                  "path": "v1alpha/{+parent}/mcpServers:search"
                }
              }
            },
            "agents": {
              "methods": {
                "list": {
                  "path": "v1alpha/{+parent}/agents",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/agents",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "agentregistry.projects.locations.agents.list",
                  "description": "Lists Agents in a given project and location."
                },
                "get": {
                  "id": "agentregistry.projects.locations.agents.get",
                  "description": "Gets details of a single Agent.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/agents/{agentsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "path": "v1alpha/{+name}"
                },
                "search": {
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/agents:search",
                  "httpMethod": "POST",
                  "description": "Searches Agents in a given project and location.",
                  "id": "agentregistry.projects.locations.agents.search",
                  "path": "v1alpha/{+parent}/agents:search"
                }
              }
            },
            "endpoints": {
              "methods": {
                "list": {
                  "id": "agentregistry.projects.locations.endpoints.list",
                  "description": "Lists Endpoints in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/endpoints",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "path": "v1alpha/{+parent}/endpoints"
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "description": "Gets details of a single Endpoint.",
                  "id": "agentregistry.projects.locations.endpoints.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/endpoints/{endpointsId}",
                  "httpMethod": "GET"
                }
              }
            },
            "bindings": {
              "methods": {
                "list": {
                  "id": "agentregistry.projects.locations.bindings.list",
                  "description": "Lists Bindings in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "path": "v1alpha/{+parent}/bindings"
                },
                "fetchAvailable": {
                  "path": "v1alpha/{+parent}/bindings:fetchAvailable",
                  "description": "Fetches available Bindings.",
                  "id": "agentregistry.projects.locations.bindings.fetchAvailable",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings:fetchAvailable",
                  "httpMethod": "GET"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings/{bindingsId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a single Binding.",
                  "id": "agentregistry.projects.locations.bindings.delete",
                  "path": "v1alpha/{+name}"
                },
                "get": {
                  "description": "Gets details of a single Binding.",
                  "id": "agentregistry.projects.locations.bindings.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings/{bindingsId}",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}"
                },
                "create": {
                  "path": "v1alpha/{+parent}/bindings",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "agentregistry.projects.locations.bindings.create",
                  "description": "Creates a new Binding in a given project and location."
                },
                "patch": {
                  "id": "agentregistry.projects.locations.bindings.patch",
                  "description": "Updates the parameters of a single Binding.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings/{bindingsId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "path": "v1alpha/{+name}"
                }
              }
            },
            "services": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services",
                  "httpMethod": "GET",
                  "description": "Lists Services in a given project and location.",
                  "id": "agentregistry.projects.locations.services.list",
                  "path": "v1alpha/{+parent}/services"
                },
                "delete": {
                  "description": "Deletes a single Service.",
                  "id": "agentregistry.projects.locations.services.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services/{servicesId}",
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}"
                },
                "get": {
                  "id": "agentregistry.projects.locations.services.get",
                  "description": "Gets details of a single Service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services/{servicesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "path": "v1alpha/{+name}"
                },
                "create": {
                  "path": "v1alpha/{+parent}/services",
                  "id": "agentregistry.projects.locations.services.create",
                  "description": "Creates a new Service in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services/{servicesId}",
                  "httpMethod": "PATCH",
                  "description": "Updates the parameters of a single Service.",
                  "id": "agentregistry.projects.locations.services.patch"
                }
              }
            }
          },
          "methods": {
            "list": {
              "path": "v1alpha/{+name}/locations",
              "scopes": [
                "https://www.googleapis.com/auth/agentregistry.read-write",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1alpha/projects/{projectsId}/locations",
              "httpMethod": "GET",
              "description": "Lists information about the supported locations for this service. This method lists locations based on the resource scope provided in the ListLocationsRequest.name field: * **Global locations**: If `name` is empty, the method lists the public locations available to all projects. * **Project-specific locations**: If `name` follows the format `projects/{project}`, the method lists locations visible to that specific project. This includes public, private, or other proj[...]",
              "id": "agentregistry.projects.locations.list"
            },
            "get": {
              "id": "agentregistry.projects.locations.get",
              "description": "Gets information about a location.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/agentregistry.read-write",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1alpha/{+name}"
            }
          }
        }
      }
    }
  },
  "revision": "20260430",
  "ownerName": "Google",
  "basePath": "",
  "batchPath": "batch",
  "mtlsRootUrl": "https://agentregistry.mtls.googleapis.com/",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "version": "v1alpha",
  "version_module": true,
  "rootUrl": "https://agentregistry.googleapis.com/",
  "ownerDomain": "google.com",
  "canonicalName": "Agent Registry",
  "description": "Agent Registry is a centralized, unified catalog that lets you store, discover, and govern Model Context Protocol (MCP) servers, tools, and AI agents within Google Cloud.",
  "title": "Agent Registry API",
  "servicePath": ""
}