{
  "baseUrl": "https://agentregistry.googleapis.com/",
  "documentationLink": "https://docs.cloud.google.com/agent-registry/overview",
  "mtlsRootUrl": "https://agentregistry.mtls.googleapis.com/",
  "kind": "discovery#restDescription",
  "servicePath": "",
  "description": "Agent Registry is a centralized, unified catalog that lets you store, discover, and govern Model Context Protocol (MCP) servers, tools, and AI agents within Google Cloud.",
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "rootUrl": "https://agentregistry.googleapis.com/",
  "version_module": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/agentregistry.read-only": {
          "description": "See your Google Cloud Agent Registry data and the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud services and see the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/agentregistry.read-write": {
          "description": "See, edit, configure, and delete your Google Cloud Agent Registry data and see the email address for your Google Account"
        }
      }
    }
  },
  "version": "v1alpha",
  "name": "agentregistry",
  "basePath": "",
  "id": "agentregistry:v1alpha",
  "ownerDomain": "google.com",
  "title": "Agent Registry API",
  "revision": "20260430",
  "canonicalName": "Agent Registry",
  "resources": {
    "projects": {
      "resources": {
        "locations": {
          "resources": {
            "endpoints": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/endpoints/{endpointsId}",
                  "id": "agentregistry.projects.locations.endpoints.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets details of a single Endpoint."
                },
                "list": {
                  "path": "v1alpha/{+parent}/endpoints",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.endpoints.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists Endpoints in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/endpoints"
                }
              }
            },
            "mcpServers": {
              "methods": {
                "search": {
                  "httpMethod": "POST",
                  "path": "v1alpha/{+parent}/mcpServers:search",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers:search",
                  "id": "agentregistry.projects.locations.mcpServers.search",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Searches McpServers in a given project and location."
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers/{mcpServersId}",
                  "id": "agentregistry.projects.locations.mcpServers.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets details of a single McpServer."
                },
                "list": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers",
                  "id": "agentregistry.projects.locations.mcpServers.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists McpServers in a given project and location.",
                  "path": "v1alpha/{+parent}/mcpServers",
                  "httpMethod": "GET"
                }
              }
            },
            "services": {
              "methods": {
                "patch": {
                  "id": "agentregistry.projects.locations.services.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Updates the parameters of a single Service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services/{servicesId}",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH"
                },
                "get": {
                  "id": "agentregistry.projects.locations.services.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets details of a single Service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services/{servicesId}",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}"
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "id": "agentregistry.projects.locations.services.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Deletes a single Service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services/{servicesId}"
                },
                "list": {
                  "id": "agentregistry.projects.locations.services.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists Services in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services",
                  "path": "v1alpha/{+parent}/services",
                  "httpMethod": "GET"
                },
                "create": {
                  "path": "v1alpha/{+parent}/services",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services",
                  "id": "agentregistry.projects.locations.services.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Creates a new Service in a given project and location."
                }
              }
            },
            "operations": {
              "methods": {
                "get": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.operations.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}"
                },
                "delete": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "id": "agentregistry.projects.locations.operations.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "path": "v1alpha/{+name}/operations",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations",
                  "id": "agentregistry.projects.locations.operations.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                },
                "cancel": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}:cancel",
                  "id": "agentregistry.projects.locations.operations.cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it be[...]",
                  "path": "v1alpha/{+name}:cancel",
                  "httpMethod": "POST"
                }
              }
            },
            "bindings": {
              "methods": {
                "patch": {
                  "id": "agentregistry.projects.locations.bindings.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Updates the parameters of a single Binding.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings/{bindingsId}",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH"
                },
                "fetchAvailable": {
                  "path": "v1alpha/{+parent}/bindings:fetchAvailable",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.bindings.fetchAvailable",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Fetches available Bindings.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings:fetchAvailable"
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings/{bindingsId}",
                  "id": "agentregistry.projects.locations.bindings.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets details of a single Binding."
                },
                "delete": {
                  "id": "agentregistry.projects.locations.bindings.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Deletes a single Binding.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings/{bindingsId}",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "path": "v1alpha/{+parent}/bindings",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.bindings.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists Bindings in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings"
                },
                "create": {
                  "id": "agentregistry.projects.locations.bindings.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Creates a new Binding in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings",
                  "path": "v1alpha/{+parent}/bindings",
                  "httpMethod": "POST"
                }
              }
            },
            "agents": {
              "methods": {
                "search": {
                  "path": "v1alpha/{+parent}/agents:search",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/agents:search",
                  "id": "agentregistry.projects.locations.agents.search",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Searches Agents in a given project and location."
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/agents/{agentsId}",
                  "id": "agentregistry.projects.locations.agents.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets details of a single Agent."
                },
                "list": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/agents",
                  "id": "agentregistry.projects.locations.agents.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists Agents in a given project and location.",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+parent}/agents"
                }
              }
            }
          },
          "methods": {
            "list": {
              "flatPath": "v1alpha/projects/{projectsId}/locations",
              "id": "agentregistry.projects.locations.list",
              "scopes": [
                "https://www.googleapis.com/auth/agentregistry.read-write",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Lists information about the supported locations for this service. This method lists locations based on the resource scope provided in the ListLocationsRequest.name field: * **Global locations**: If `name` is empty, the method lists the public locations available to all projects. * **Project-specific locations**: If `name` follows the format `projects/{project}`, the method lists locations visible to that specific project. This includes public, private, or other proj[...]",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}/locations"
            },
            "get": {
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "id": "agentregistry.projects.locations.get",
              "scopes": [
                "https://www.googleapis.com/auth/agentregistry.read-write",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Gets information about a location.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}"
            }
          }
        }
      }
    }
  },
  "protocol": "rest",
  "ownerName": "Google"
}