{
  "ownerName": "Google",
  "batchPath": "batch",
  "title": "Agent Registry API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/agentregistry.read-write": {
          "description": "See, edit, configure, and delete your Google Cloud Agent Registry data and see the email address for your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud services and see the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/agentregistry.read-only": {
          "description": "See your Google Cloud Agent Registry data and the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "servicePath": "",
  "description": "Agent Registry is a centralized, unified catalog that lets you store, discover, and govern Model Context Protocol (MCP) servers, tools, and AI agents within Google Cloud.",
  "version": "v1alpha",
  "basePath": "",
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "id": "agentregistry:v1alpha",
  "protocol": "rest",
  "name": "agentregistry",
  "documentationLink": "https://docs.cloud.google.com/agent-registry/overview",
  "resources": {
    "projects": {
      "resources": {
        "locations": {
          "methods": {
            "list": {
              "description": "Lists information about the supported locations for this service. This method lists locations based on the resource scope provided in the ListLocationsRequest.name field: * **Global locations**: If `name` is empty, the method lists the public locations available to all projects. * **Project-specific locations**: If `name` follows the format `projects/{project}`, the method lists locations visible to that specific project. This includes public, private, or other proj[...]",
              "flatPath": "v1alpha/projects/{projectsId}/locations",
              "scopes": [
                "https://www.googleapis.com/auth/agentregistry.read-write",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "agentregistry.projects.locations.list",
              "path": "v1alpha/{+name}/locations",
              "httpMethod": "GET"
            },
            "get": {
              "description": "Gets information about a location.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}",
              "scopes": [
                "https://www.googleapis.com/auth/agentregistry.read-write",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "agentregistry.projects.locations.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "endpoints": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists Endpoints in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/endpoints",
                  "path": "v1alpha/{+parent}/endpoints",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.endpoints.list"
                },
                "get": {
                  "description": "Gets details of a single Endpoint.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/endpoints/{endpointsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "agentregistry.projects.locations.endpoints.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET"
                }
              }
            },
            "bindings": {
              "methods": {
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings/{bindingsId}",
                  "description": "Updates the parameters of a single Binding.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "id": "agentregistry.projects.locations.bindings.patch"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists Bindings in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings",
                  "path": "v1alpha/{+parent}/bindings",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.bindings.list"
                },
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings/{bindingsId}",
                  "description": "Gets details of a single Binding.",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "agentregistry.projects.locations.bindings.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET"
                },
                "fetchAvailable": {
                  "description": "Fetches available Bindings.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings:fetchAvailable",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "agentregistry.projects.locations.bindings.fetchAvailable",
                  "path": "v1alpha/{+parent}/bindings:fetchAvailable",
                  "httpMethod": "GET"
                },
                "create": {
                  "path": "v1alpha/{+parent}/bindings",
                  "httpMethod": "POST",
                  "id": "agentregistry.projects.locations.bindings.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings",
                  "description": "Creates a new Binding in a given project and location."
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Deletes a single Binding.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/bindings/{bindingsId}",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "id": "agentregistry.projects.locations.bindings.delete"
                }
              }
            },
            "mcpServers": {
              "methods": {
                "search": {
                  "path": "v1alpha/{+parent}/mcpServers:search",
                  "httpMethod": "POST",
                  "id": "agentregistry.projects.locations.mcpServers.search",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers:search",
                  "description": "Searches McpServers in a given project and location."
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists McpServers in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers",
                  "path": "v1alpha/{+parent}/mcpServers",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.mcpServers.list"
                },
                "get": {
                  "description": "Gets details of a single McpServer.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/mcpServers/{mcpServersId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "agentregistry.projects.locations.mcpServers.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET"
                }
              }
            },
            "operations": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations",
                  "path": "v1alpha/{+name}/operations",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.operations.list"
                },
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "agentregistry.projects.locations.operations.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET"
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "id": "agentregistry.projects.locations.operations.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`."
                },
                "cancel": {
                  "path": "v1alpha/{+name}:cancel",
                  "httpMethod": "POST",
                  "id": "agentregistry.projects.locations.operations.cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}:cancel",
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it be[...]"
                }
              }
            },
            "agents": {
              "methods": {
                "search": {
                  "id": "agentregistry.projects.locations.agents.search",
                  "path": "v1alpha/{+parent}/agents:search",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/agents:search",
                  "description": "Searches Agents in a given project and location.",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ]
                },
                "list": {
                  "description": "Lists Agents in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/agents",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "agentregistry.projects.locations.agents.list",
                  "path": "v1alpha/{+parent}/agents",
                  "httpMethod": "GET"
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "agentregistry.projects.locations.agents.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets details of a single Agent.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/agents/{agentsId}"
                }
              }
            },
            "services": {
              "methods": {
                "delete": {
                  "description": "Deletes a single Service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services/{servicesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "agentregistry.projects.locations.services.delete",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE"
                },
                "create": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services",
                  "description": "Creates a new Service in a given project and location.",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "agentregistry.projects.locations.services.create",
                  "path": "v1alpha/{+parent}/services",
                  "httpMethod": "POST"
                },
                "patch": {
                  "id": "agentregistry.projects.locations.services.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "description": "Updates the parameters of a single Service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services/{servicesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "list": {
                  "id": "agentregistry.projects.locations.services.list",
                  "path": "v1alpha/{+parent}/services",
                  "httpMethod": "GET",
                  "description": "Lists Services in a given project and location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ]
                },
                "get": {
                  "description": "Gets details of a single Service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/services/{servicesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/agentregistry.read-only",
                    "https://www.googleapis.com/auth/agentregistry.read-write",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "agentregistry.projects.locations.services.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET"
                }
              }
            }
          }
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "mtlsRootUrl": "https://agentregistry.mtls.googleapis.com/",
  "baseUrl": "https://agentregistry.googleapis.com/",
  "revision": "20260430",
  "canonicalName": "Agent Registry",
  "version_module": true,
  "rootUrl": "https://agentregistry.googleapis.com/"
}