{
  "canonicalName": "Google Analytics Admin",
  "protocol": "rest",
  "revision": "20260406",
  "title": "Google Analytics Admin API",
  "ownerName": "Google",
  "ownerDomain": "google.com",
  "version_module": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "discoveryVersion": "v1",
  "name": "analyticsadmin",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "version": "v1alpha",
  "resources": {
    "accounts": {
      "resources": {
        "accessBindings": {
          "methods": {
            "list": {
              "id": "analyticsadmin.accounts.accessBindings.list",
              "description": "Lists all access bindings on an account or property.",
              "path": "v1alpha/{+parent}/accessBindings",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings"
            },
            "batchCreate": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate",
              "id": "analyticsadmin.accounts.accessBindings.batchCreate",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created."
            },
            "batchGet": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet",
              "id": "analyticsadmin.accounts.accessBindings.batchGet",
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about multiple access bindings to an account or property."
            },
            "batchDelete": {
              "id": "analyticsadmin.accounts.accessBindings.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete"
            },
            "patch": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "description": "Updates an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.accessBindings.patch"
            },
            "get": {
              "id": "analyticsadmin.accounts.accessBindings.get",
              "description": "Gets information about an access binding.",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}"
            },
            "create": {
              "id": "analyticsadmin.accounts.accessBindings.create",
              "path": "v1alpha/{+parent}/accessBindings",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates an access binding on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings"
            },
            "delete": {
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "description": "Deletes an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}"
            },
            "batchUpdate": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate",
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            }
          }
        }
      },
      "methods": {
        "provisionAccountTicket": {
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Requests a ticket for creating an account."
        },
        "runAccessReport": {
          "id": "analyticsadmin.accounts.runAccessReport",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport"
        },
        "get": {
          "id": "analyticsadmin.accounts.get",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single Account.",
          "flatPath": "v1alpha/accounts/{accountsId}"
        },
        "getDataSharingSettings": {
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons."
        },
        "searchChangeHistoryEvents": {
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters. Only returns the subset of changes supported by the API. The UI may return additional changes.",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "delete": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.delete",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}"
        },
        "list": {
          "id": "analyticsadmin.accounts.list",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/accounts",
          "flatPath": "v1alpha/accounts"
        },
        "patch": {
          "description": "Updates an account.",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.patch",
          "flatPath": "v1alpha/accounts/{accountsId}"
        }
      }
    },
    "properties": {
      "methods": {
        "createRollupProperty": {
          "description": "Create a roll-up property and all roll-up property source links.",
          "path": "v1alpha/properties:createRollupProperty",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.createRollupProperty",
          "flatPath": "v1alpha/properties:createRollupProperty"
        },
        "getReportingIdentitySettings": {
          "description": "Returns the reporting identity settings for this property.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.getReportingIdentitySettings",
          "flatPath": "v1alpha/properties/{propertiesId}/reportingIdentitySettings"
        },
        "acknowledgeUserDataCollection": {
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created."
        },
        "submitUserDeletion": {
          "description": "Submits a request for user deletion for a property.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}:submitUserDeletion",
          "id": "analyticsadmin.properties.submitUserDeletion",
          "flatPath": "v1alpha/properties/{propertiesId}:submitUserDeletion"
        },
        "list": {
          "id": "analyticsadmin.properties.list",
          "description": "Returns child Properties under the specified parent Account. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "path": "v1alpha/properties",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties"
        },
        "create": {
          "id": "analyticsadmin.properties.create",
          "description": "Creates a Google Analytics property with the specified location and attributes.",
          "path": "v1alpha/properties",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties"
        },
        "updateDataRetentionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates the singleton data retention settings for this property."
        },
        "runAccessReport": {
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "id": "analyticsadmin.properties.runAccessReport",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]"
        },
        "get": {
          "description": "Lookup for a single GA Property.",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.get",
          "flatPath": "v1alpha/properties/{propertiesId}"
        },
        "provisionSubproperty": {
          "id": "analyticsadmin.properties.provisionSubproperty",
          "path": "v1alpha/properties:provisionSubproperty",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Create a subproperty and a subproperty event filter that applies to the created subproperty.",
          "flatPath": "v1alpha/properties:provisionSubproperty"
        },
        "updateGoogleSignalsSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "description": "Updates Google Signals settings for a property."
        },
        "updateAttributionSettings": {
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "description": "Updates attribution settings on a property.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings"
        },
        "getGoogleSignalsSettings": {
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for Google Signals settings for a property.",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings"
        },
        "getAttributionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "description": "Lookup for a AttributionSettings singleton.",
          "id": "analyticsadmin.properties.getAttributionSettings"
        },
        "delete": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "path": "v1alpha/{+name}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.delete"
        },
        "getDataRetentionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "patch": {
          "flatPath": "v1alpha/properties/{propertiesId}",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates a property.",
          "id": "analyticsadmin.properties.patch"
        }
      },
      "resources": {
        "dataStreams": {
          "methods": {
            "getGlobalSiteTag": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons."
            },
            "updateEnhancedMeasurementSettings": {
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "description": "Lists DataStreams on a property.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.list"
            },
            "getDataRedactionSettings": {
              "id": "analyticsadmin.properties.dataStreams.getDataRedactionSettings",
              "description": "Lookup for a single DataRedactionSettings.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings"
            },
            "get": {
              "id": "analyticsadmin.properties.dataStreams.get",
              "description": "Lookup for a single DataStream.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/dataStreams",
              "description": "Creates a DataStream."
            },
            "delete": {
              "id": "analyticsadmin.properties.dataStreams.delete",
              "description": "Deletes a DataStream on a property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}"
            },
            "getEnhancedMeasurementSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect."
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Updates a DataStream on a property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.patch"
            },
            "updateDataRedactionSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "id": "analyticsadmin.properties.dataStreams.updateDataRedactionSettings",
              "description": "Updates a DataRedactionSettings on a property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "get": {
                  "description": "Lookup for a single MeasurementProtocolSecret.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "patch": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "description": "Updates a measurement protocol secret."
                },
                "list": {
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets"
                }
              }
            },
            "sKAdNetworkConversionValueSchema": {
              "methods": {
                "patch": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Updates a SKAdNetworkConversionValueSchema."
                },
                "list": {
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.list",
                  "description": "Lists SKAdNetworkConversionValueSchema on a stream. Properties can have at most one SKAdNetworkConversionValueSchema.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema"
                },
                "create": {
                  "description": "Creates a SKAdNetworkConversionValueSchema.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.create",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema"
                },
                "delete": {
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.delete",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Deletes target SKAdNetworkConversionValueSchema.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}"
                },
                "get": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.get",
                  "description": "Looks up a single SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                }
              }
            },
            "eventCreateRules": {
              "methods": {
                "create": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create",
                  "description": "Creates an EventCreateRule.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/eventCreateRules"
                },
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Deletes an EventCreateRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete"
                },
                "get": {
                  "description": "Lookup for a single EventCreateRule.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}"
                },
                "patch": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch",
                  "description": "Updates an EventCreateRule.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "list": {
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lists EventCreateRules on a web data stream.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules"
                }
              }
            },
            "eventEditRules": {
              "methods": {
                "get": {
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lookup for a single EventEditRule.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}"
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.create",
                  "description": "Creates an EventEditRule.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/eventEditRules",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules"
                },
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.delete",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Deletes an EventEditRule."
                },
                "list": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules",
                  "description": "Lists EventEditRules on a web data stream.",
                  "path": "v1alpha/{+parent}/eventEditRules",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.list"
                },
                "reorder": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules:reorder",
                  "description": "Changes the processing order of event edit rules on the specified stream.",
                  "path": "v1alpha/{+parent}/eventEditRules:reorder",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.reorder"
                },
                "patch": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Updates an EventEditRule."
                }
              }
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks"
            },
            "delete": {
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a GoogleAdsLink on a property"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "id": "analyticsadmin.properties.googleAdsLinks.list"
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get"
            },
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.list"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/firebaseLinks",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink."
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "description": "Deletes a FirebaseLink on a property",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "customMetrics": {
          "methods": {
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "description": "Lists CustomMetrics on a property.",
              "path": "v1alpha/{+parent}/customMetrics",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customMetrics.list"
            },
            "patch": {
              "id": "analyticsadmin.properties.customMetrics.patch",
              "description": "Updates a CustomMetric on a property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}"
            },
            "get": {
              "id": "analyticsadmin.properties.customMetrics.get",
              "description": "Lookup for a single CustomMetric.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.create",
              "description": "Creates a CustomMetric.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/customMetrics"
            },
            "archive": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:archive",
              "description": "Archives a CustomMetric on a property."
            }
          }
        },
        "accessBindings": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/accessBindings",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all access bindings on an account or property.",
              "id": "analyticsadmin.properties.accessBindings.list",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings"
            },
            "batchCreate": {
              "id": "analyticsadmin.properties.accessBindings.batchCreate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate"
            },
            "batchGet": {
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "description": "Gets information about multiple access bindings to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet"
            },
            "batchDelete": {
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete"
            },
            "patch": {
              "id": "analyticsadmin.properties.accessBindings.patch",
              "description": "Updates an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Gets information about an access binding.",
              "id": "analyticsadmin.properties.accessBindings.get",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}"
            },
            "create": {
              "id": "analyticsadmin.properties.accessBindings.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings",
              "description": "Creates an access binding on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "description": "Deletes an access binding on an account or property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.accessBindings.delete"
            },
            "batchUpdate": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.accessBindings.batchUpdate"
            }
          }
        },
        "conversionEvents": {
          "deprecated": true,
          "methods": {
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "description": "Deprecated: Use `UpdateKeyEvent` instead. Updates a conversion event with the specified attributes.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.list",
              "path": "v1alpha/{+parent}/conversionEvents",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Deprecated: Use `ListKeyEvents` instead. Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found."
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "description": "Deprecated: Use `CreateKeyEvent` instead. Creates a conversion event with the specified attributes."
            },
            "delete": {
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "description": "Deprecated: Use `DeleteKeyEvent` instead. Deletes a conversion event in a property.",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "deprecated": true
            },
            "get": {
              "deprecated": true,
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Deprecated: Use `GetKeyEvent` instead. Retrieve a single conversion event.",
              "id": "analyticsadmin.properties.conversionEvents.get"
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}"
            },
            "approve": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:approve",
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve"
            },
            "list": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals"
            },
            "cancel": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "path": "v1alpha/{+name}:cancel",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel"
            }
          }
        },
        "rollupPropertySourceLinks": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single roll-up property source Link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties."
            },
            "list": {
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.list",
              "description": "Lists roll-up property source Links on a property. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "description": "Creates a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.create"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.delete"
            }
          }
        },
        "adSenseLinks": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.adSenseLinks.create",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates an AdSenseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks"
            },
            "delete": {
              "description": "Deletes an AdSenseLink.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.adSenseLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}"
            },
            "get": {
              "description": "Looks up a single AdSenseLink.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.adSenseLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}"
            },
            "list": {
              "id": "analyticsadmin.properties.adSenseLinks.list",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists AdSenseLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks"
            }
          }
        },
        "subpropertySyncConfigs": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/subpropertySyncConfigs",
              "description": "List all `SubpropertySyncConfig` resources for a property.",
              "id": "analyticsadmin.properties.subpropertySyncConfigs.list",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs"
            },
            "get": {
              "id": "analyticsadmin.properties.subpropertySyncConfigs.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single `SubpropertySyncConfig`.",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs/{subpropertySyncConfigsId}"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs/{subpropertySyncConfigsId}",
              "description": "Updates a `SubpropertySyncConfig`.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.subpropertySyncConfigs.patch"
            }
          }
        },
        "audiences": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.audiences.create",
              "path": "v1alpha/{+parent}/audiences",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates an Audience.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences"
            },
            "archive": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:archive",
              "description": "Archives an Audience on a property.",
              "id": "analyticsadmin.properties.audiences.archive",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive"
            },
            "get": {
              "id": "analyticsadmin.properties.audiences.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "id": "analyticsadmin.properties.audiences.patch",
              "description": "Updates an Audience on a property.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/audiences",
              "id": "analyticsadmin.properties.audiences.list"
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "description": "Lists all SearchAds360Links on a property.",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Updates a SearchAds360Link on a property."
            },
            "get": {
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "description": "Look up a single SearchAds360Link",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}"
            },
            "create": {
              "description": "Creates a SearchAds360Link.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/searchAds360Links",
              "id": "analyticsadmin.properties.searchAds360Links.create",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links"
            },
            "delete": {
              "description": "Deletes a SearchAds360Link on a property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}"
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/expandedDataSets",
              "description": "Lists ExpandedDataSets on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets"
            },
            "patch": {
              "id": "analyticsadmin.properties.expandedDataSets.patch",
              "description": "Updates a ExpandedDataSet on a property.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "description": "Lookup for a single ExpandedDataSet.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/expandedDataSets",
              "description": "Creates a ExpandedDataSet.",
              "id": "analyticsadmin.properties.expandedDataSets.create"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a ExpandedDataSet on a property.",
              "id": "analyticsadmin.properties.expandedDataSets.delete"
            }
          }
        },
        "calculatedMetrics": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.calculatedMetrics.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "description": "Lists CalculatedMetrics on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics"
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Updates a CalculatedMetric on a property.",
              "id": "analyticsadmin.properties.calculatedMetrics.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}"
            },
            "get": {
              "id": "analyticsadmin.properties.calculatedMetrics.get",
              "description": "Lookup for a single CalculatedMetric.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}"
            },
            "create": {
              "id": "analyticsadmin.properties.calculatedMetrics.create",
              "description": "Creates a CalculatedMetric.",
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "id": "analyticsadmin.properties.calculatedMetrics.delete",
              "description": "Deletes a CalculatedMetric on a property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            }
          }
        },
        "subpropertyEventFilters": {
          "methods": {
            "create": {
              "description": "Creates a subproperty Event Filter.",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.subpropertyEventFilters.create",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "description": "Deletes a subproperty event filter.",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.subpropertyEventFilters.delete"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "id": "analyticsadmin.properties.subpropertyEventFilters.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single subproperty Event Filter."
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Updates a subproperty Event Filter.",
              "id": "analyticsadmin.properties.subpropertyEventFilters.patch"
            },
            "list": {
              "id": "analyticsadmin.properties.subpropertyEventFilters.list",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "List all subproperty Event Filters on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomDimension on a property."
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "path": "v1alpha/{+parent}/customDimensions",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomDimensions on a property.",
              "id": "analyticsadmin.properties.customDimensions.list"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.create",
              "description": "Creates a CustomDimension.",
              "path": "v1alpha/{+parent}/customDimensions",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "archive": {
              "id": "analyticsadmin.properties.customDimensions.archive",
              "path": "v1alpha/{+name}:archive",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Archives a CustomDimension on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive"
            },
            "get": {
              "id": "analyticsadmin.properties.customDimensions.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single CustomDimension.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}"
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "id": "analyticsadmin.properties.bigQueryLinks.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Updates a BigQueryLink."
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "id": "analyticsadmin.properties.bigQueryLinks.list",
              "description": "Lists BigQuery Links on a property.",
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "description": "Creates a BigQueryLink.",
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.bigQueryLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "description": "Deletes a BigQueryLink on a property.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.bigQueryLinks.delete"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single BigQuery Link.",
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}"
            }
          }
        },
        "keyEvents": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.keyEvents.get",
              "description": "Retrieve a single Key Event.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}"
            },
            "create": {
              "id": "analyticsadmin.properties.keyEvents.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/keyEvents",
              "description": "Creates a Key Event.",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents"
            },
            "delete": {
              "id": "analyticsadmin.properties.keyEvents.delete",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a Key Event.",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents",
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/keyEvents",
              "id": "analyticsadmin.properties.keyEvents.list"
            },
            "patch": {
              "description": "Updates a Key Event.",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.keyEvents.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}"
            }
          }
        },
        "channelGroups": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "id": "analyticsadmin.properties.channelGroups.get",
              "description": "Lookup for a single ChannelGroup.",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/channelGroups",
              "description": "Creates a ChannelGroup.",
              "id": "analyticsadmin.properties.channelGroups.create"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a ChannelGroup on a property.",
              "id": "analyticsadmin.properties.channelGroups.delete"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "id": "analyticsadmin.properties.channelGroups.list",
              "path": "v1alpha/{+parent}/channelGroups",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists ChannelGroups on a property."
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "id": "analyticsadmin.properties.channelGroups.patch",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a ChannelGroup."
            }
          }
        },
        "reportingDataAnnotations": {
          "methods": {
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations",
              "id": "analyticsadmin.properties.reportingDataAnnotations.create",
              "path": "v1alpha/{+parent}/reportingDataAnnotations",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a Reporting Data Annotation."
            },
            "delete": {
              "id": "analyticsadmin.properties.reportingDataAnnotations.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a Reporting Data Annotation.",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup a single Reporting Data Annotation.",
              "id": "analyticsadmin.properties.reportingDataAnnotations.get"
            },
            "patch": {
              "id": "analyticsadmin.properties.reportingDataAnnotations.patch",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a Reporting Data Annotation.",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}"
            },
            "list": {
              "path": "v1alpha/{+parent}/reportingDataAnnotations",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "List all Reporting Data Annotations on a property.",
              "id": "analyticsadmin.properties.reportingDataAnnotations.list",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations"
            }
          }
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "id": "analyticsadmin.accountSummaries.list",
          "path": "v1alpha/accountSummaries",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns summaries of all accounts accessible by the caller.",
          "flatPath": "v1alpha/accountSummaries"
        }
      }
    }
  },
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "servicePath": "",
  "id": "analyticsadmin:v1alpha",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "basePath": "",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning."
}