{
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "version_module": true,
  "servicePath": "",
  "ownerName": "Google",
  "fullyEncodeReservedExpansion": true,
  "version": "v1alpha",
  "ownerDomain": "google.com",
  "basePath": "",
  "id": "analyticsadmin:v1alpha",
  "title": "Google Analytics Admin API",
  "protocol": "rest",
  "canonicalName": "Google Analytics Admin",
  "discoveryVersion": "v1",
  "revision": "20260311",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "kind": "discovery#restDescription",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "resources": {
    "accounts": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.delete",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found."
        },
        "searchChangeHistoryEvents": {
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Searches through all changes to an account or its children given the specified set of filters. Only returns the subset of changes supported by the API. The UI may return additional changes.",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents"
        },
        "list": {
          "id": "analyticsadmin.accounts.list",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "flatPath": "v1alpha/accounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/accounts"
        },
        "runAccessReport": {
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "id": "analyticsadmin.accounts.runAccessReport",
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "httpMethod": "POST",
          "path": "v1alpha/{+entity}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates an account.",
          "id": "analyticsadmin.accounts.patch"
        },
        "getDataSharingSettings": {
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings"
        },
        "get": {
          "description": "Lookup for a single Account.",
          "id": "analyticsadmin.accounts.get",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts/{accountsId}"
        },
        "provisionAccountTicket": {
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/accounts:provisionAccountTicket",
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts:provisionAccountTicket"
        }
      },
      "resources": {
        "accessBindings": {
          "methods": {
            "list": {
              "description": "Lists all access bindings on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.list",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "batchCreate": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "id": "analyticsadmin.accounts.accessBindings.batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created."
            },
            "create": {
              "description": "Creates an access binding on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.create",
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "path": "v1alpha/{+parent}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "get": {
              "description": "Gets information about an access binding.",
              "id": "analyticsadmin.accounts.accessBindings.get",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "httpMethod": "GET"
            },
            "batchGet": {
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet",
              "description": "Gets information about multiple access bindings to an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.batchGet"
            },
            "batchUpdate": {
              "description": "Updates information about multiple access bindings to an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate"
            },
            "patch": {
              "id": "analyticsadmin.accounts.accessBindings.patch",
              "description": "Updates an access binding on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}"
            },
            "batchDelete": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "id": "analyticsadmin.accounts.accessBindings.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property."
            },
            "delete": {
              "description": "Deletes an access binding on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            }
          }
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "description": "Returns summaries of all accounts accessible by the caller.",
          "id": "analyticsadmin.accountSummaries.list",
          "httpMethod": "GET",
          "flatPath": "v1alpha/accountSummaries",
          "path": "v1alpha/accountSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    },
    "properties": {
      "methods": {
        "createRollupProperty": {
          "description": "Create a roll-up property and all roll-up property source links.",
          "id": "analyticsadmin.properties.createRollupProperty",
          "flatPath": "v1alpha/properties:createRollupProperty",
          "httpMethod": "POST",
          "path": "v1alpha/properties:createRollupProperty",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "provisionSubproperty": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties:provisionSubproperty",
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties:provisionSubproperty",
          "id": "analyticsadmin.properties.provisionSubproperty",
          "description": "Create a subproperty and a subproperty event filter that applies to the created subproperty."
        },
        "runAccessReport": {
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "id": "analyticsadmin.properties.runAccessReport",
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "httpMethod": "POST",
          "path": "v1alpha/{+entity}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "patch": {
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "PATCH",
          "description": "Updates a property.",
          "id": "analyticsadmin.properties.patch"
        },
        "acknowledgeUserDataCollection": {
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "httpMethod": "POST"
        },
        "updateAttributionSettings": {
          "description": "Updates attribution settings on a property.",
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "getDataRetentionSettings": {
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.get",
          "description": "Lookup for a single GA Property."
        },
        "delete": {
          "id": "analyticsadmin.properties.delete",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "DELETE"
        },
        "submitUserDeletion": {
          "id": "analyticsadmin.properties.submitUserDeletion",
          "description": "Submits a request for user deletion for a property.",
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties/{propertiesId}:submitUserDeletion",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}:submitUserDeletion"
        },
        "updateGoogleSignalsSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "description": "Updates Google Signals settings for a property."
        },
        "getGoogleSignalsSettings": {
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "description": "Lookup for Google Signals settings for a property."
        },
        "getAttributionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "id": "analyticsadmin.properties.getAttributionSettings",
          "description": "Lookup for a AttributionSettings singleton."
        },
        "getReportingIdentitySettings": {
          "id": "analyticsadmin.properties.getReportingIdentitySettings",
          "description": "Returns the reporting identity settings for this property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/reportingIdentitySettings",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "v1alpha/properties",
          "httpMethod": "GET",
          "path": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns child Properties under the specified parent Account. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "id": "analyticsadmin.properties.list"
        },
        "updateDataRetentionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "description": "Updates the singleton data retention settings for this property."
        },
        "create": {
          "id": "analyticsadmin.properties.create",
          "description": "Creates a Google Analytics property with the specified location and attributes.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties",
          "flatPath": "v1alpha/properties",
          "httpMethod": "POST"
        }
      },
      "resources": {
        "firebaseLinks": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.list"
            },
            "create": {
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/firebaseLinks",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "description": "Deletes a FirebaseLink on a property"
            }
          }
        },
        "audiences": {
          "methods": {
            "archive": {
              "path": "v1alpha/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "httpMethod": "POST",
              "description": "Archives an Audience on a property.",
              "id": "analyticsadmin.properties.audiences.archive"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/audiences",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.audiences.list",
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions."
            },
            "create": {
              "id": "analyticsadmin.properties.audiences.create",
              "description": "Creates an Audience.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/audiences",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "httpMethod": "POST"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.audiences.patch",
              "description": "Updates an Audience on a property."
            },
            "get": {
              "id": "analyticsadmin.properties.audiences.get",
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "delete": {
              "description": "Deletes a ExpandedDataSet on a property.",
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "id": "analyticsadmin.properties.expandedDataSets.create",
              "description": "Creates a ExpandedDataSet.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/expandedDataSets",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.expandedDataSets.patch",
              "description": "Updates a ExpandedDataSet on a property."
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "description": "Lookup for a single ExpandedDataSet."
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/expandedDataSets",
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "description": "Lists ExpandedDataSets on a property."
            }
          }
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "id": "analyticsadmin.properties.customMetrics.archive",
              "description": "Archives a CustomMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:archive",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "httpMethod": "POST"
            },
            "list": {
              "id": "analyticsadmin.properties.customMetrics.list",
              "description": "Lists CustomMetrics on a property.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/customMetrics"
            },
            "create": {
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "httpMethod": "POST",
              "description": "Creates a CustomMetric.",
              "id": "analyticsadmin.properties.customMetrics.create"
            },
            "patch": {
              "id": "analyticsadmin.properties.customMetrics.patch",
              "description": "Updates a CustomMetric on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "GET",
              "description": "Lookup for a single CustomMetric.",
              "id": "analyticsadmin.properties.customMetrics.get"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "list": {
              "description": "Deprecated: Use `ListKeyEvents` instead. Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "deprecated": true,
              "path": "v1alpha/{+parent}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "get": {
              "description": "Deprecated: Use `GetKeyEvent` instead. Retrieve a single conversion event.",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "deprecated": true,
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "deprecated": true,
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "description": "Deprecated: Use `CreateKeyEvent` instead. Creates a conversion event with the specified attributes."
            },
            "patch": {
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "description": "Deprecated: Use `UpdateKeyEvent` instead. Updates a conversion event with the specified attributes.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true,
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "deprecated": true,
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "DELETE",
              "description": "Deprecated: Use `DeleteKeyEvent` instead. Deletes a conversion event in a property.",
              "id": "analyticsadmin.properties.conversionEvents.delete"
            }
          },
          "deprecated": true
        },
        "adSenseLinks": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/adSenseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "description": "Lists AdSenseLinks on a property.",
              "id": "analyticsadmin.properties.adSenseLinks.list"
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Looks up a single AdSenseLink.",
              "id": "analyticsadmin.properties.adSenseLinks.get"
            },
            "create": {
              "description": "Creates an AdSenseLink.",
              "id": "analyticsadmin.properties.adSenseLinks.create",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes an AdSenseLink.",
              "id": "analyticsadmin.properties.adSenseLinks.delete"
            }
          }
        },
        "dataStreams": {
          "methods": {
            "updateDataRedactionSettings": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "id": "analyticsadmin.properties.dataStreams.updateDataRedactionSettings",
              "description": "Updates a DataRedactionSettings on a property."
            },
            "getGlobalSiteTag": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag"
            },
            "getDataRedactionSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single DataRedactionSettings.",
              "id": "analyticsadmin.properties.dataStreams.getDataRedactionSettings"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.delete",
              "description": "Deletes a DataStream on a property."
            },
            "patch": {
              "description": "Updates a DataStream on a property.",
              "id": "analyticsadmin.properties.dataStreams.patch",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}"
            },
            "updateEnhancedMeasurementSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings",
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect."
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists DataStreams on a property.",
              "id": "analyticsadmin.properties.dataStreams.list"
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single DataStream.",
              "id": "analyticsadmin.properties.dataStreams.get"
            },
            "getEnhancedMeasurementSettings": {
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "httpMethod": "GET"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a DataStream.",
              "id": "analyticsadmin.properties.dataStreams.create"
            }
          },
          "resources": {
            "eventCreateRules": {
              "methods": {
                "list": {
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list",
                  "description": "Lists EventCreateRules on a web data stream.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "httpMethod": "GET"
                },
                "get": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get",
                  "description": "Lookup for a single EventCreateRule."
                },
                "create": {
                  "description": "Creates an EventCreateRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules"
                },
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch",
                  "description": "Updates an EventCreateRule.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "httpMethod": "PATCH"
                },
                "delete": {
                  "description": "Deletes an EventCreateRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                }
              }
            },
            "sKAdNetworkConversionValueSchema": {
              "methods": {
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Deletes target SKAdNetworkConversionValueSchema.",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.delete"
                },
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lists SKAdNetworkConversionValueSchema on a stream. Properties can have at most one SKAdNetworkConversionValueSchema.",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.list"
                },
                "get": {
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.get",
                  "description": "Looks up a single SKAdNetworkConversionValueSchema.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+name}"
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.create",
                  "description": "Creates a SKAdNetworkConversionValueSchema.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "httpMethod": "POST"
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "httpMethod": "PATCH",
                  "description": "Updates a SKAdNetworkConversionValueSchema.",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.patch"
                }
              }
            },
            "eventEditRules": {
              "methods": {
                "reorder": {
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.reorder",
                  "description": "Changes the processing order of event edit rules on the specified stream.",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules:reorder",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/eventEditRules:reorder"
                },
                "delete": {
                  "description": "Deletes an EventEditRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.delete",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "description": "Lookup for a single EventEditRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.get"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/eventEditRules",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.create",
                  "description": "Creates an EventEditRule."
                },
                "patch": {
                  "description": "Updates an EventEditRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.patch",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "httpMethod": "PATCH"
                },
                "list": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+parent}/eventEditRules",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.list",
                  "description": "Lists EventEditRules on a web data stream."
                }
              }
            },
            "measurementProtocolSecrets": {
              "methods": {
                "delete": {
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "list": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list"
                },
                "create": {
                  "description": "Creates a measurement protocol secret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "description": "Updates a measurement protocol secret."
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "description": "Lookup for a single MeasurementProtocolSecret."
                }
              }
            }
          }
        },
        "calculatedMetrics": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a CalculatedMetric on a property.",
              "id": "analyticsadmin.properties.calculatedMetrics.delete"
            },
            "get": {
              "id": "analyticsadmin.properties.calculatedMetrics.get",
              "description": "Lookup for a single CalculatedMetric.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CalculatedMetric.",
              "id": "analyticsadmin.properties.calculatedMetrics.create"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "httpMethod": "PATCH",
              "description": "Updates a CalculatedMetric on a property.",
              "id": "analyticsadmin.properties.calculatedMetrics.patch"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CalculatedMetrics on a property.",
              "id": "analyticsadmin.properties.calculatedMetrics.list"
            }
          }
        },
        "subpropertyEventFilters": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.subpropertyEventFilters.delete",
              "description": "Deletes a subproperty event filter.",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "list": {
              "description": "List all subproperty Event Filters on a property.",
              "id": "analyticsadmin.properties.subpropertyEventFilters.list",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "description": "Creates a subproperty Event Filter.",
              "id": "analyticsadmin.properties.subpropertyEventFilters.create",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters"
            },
            "patch": {
              "description": "Updates a subproperty Event Filter.",
              "id": "analyticsadmin.properties.subpropertyEventFilters.patch",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}"
            },
            "get": {
              "description": "Lookup for a single subproperty Event Filter.",
              "id": "analyticsadmin.properties.subpropertyEventFilters.get",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "rollupPropertySourceLinks": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "httpMethod": "GET",
              "description": "Lists roll-up property source Links on a property. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.list"
            },
            "create": {
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "httpMethod": "POST",
              "description": "Creates a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.create"
            },
            "delete": {
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.delete",
              "description": "Deletes a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single roll-up property source Link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.get"
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a SearchAds360Link on a property.",
              "id": "analyticsadmin.properties.searchAds360Links.delete"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/searchAds360Links",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "description": "Lists all SearchAds360Links on a property."
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a SearchAds360Link.",
              "id": "analyticsadmin.properties.searchAds360Links.create"
            },
            "patch": {
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "description": "Updates a SearchAds360Link on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "get": {
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "description": "Look up a single SearchAds360Link",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "create": {
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create"
            },
            "get": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "cancel": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:cancel"
            },
            "list": {
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals."
            },
            "approve": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:approve",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "create": {
              "path": "v1alpha/{+parent}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "httpMethod": "POST",
              "description": "Creates a CustomDimension.",
              "id": "analyticsadmin.properties.customDimensions.create"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "description": "Updates a CustomDimension on a property."
            },
            "get": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "description": "Lookup for a single CustomDimension.",
              "id": "analyticsadmin.properties.customDimensions.get"
            },
            "archive": {
              "id": "analyticsadmin.properties.customDimensions.archive",
              "description": "Archives a CustomDimension on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:archive"
            },
            "list": {
              "description": "Lists CustomDimensions on a property.",
              "id": "analyticsadmin.properties.customDimensions.list",
              "path": "v1alpha/{+parent}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "httpMethod": "GET"
            }
          }
        },
        "reportingDataAnnotations": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a Reporting Data Annotation.",
              "id": "analyticsadmin.properties.reportingDataAnnotations.delete"
            },
            "list": {
              "id": "analyticsadmin.properties.reportingDataAnnotations.list",
              "description": "List all Reporting Data Annotations on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/reportingDataAnnotations",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations"
            },
            "get": {
              "description": "Lookup a single Reporting Data Annotation.",
              "id": "analyticsadmin.properties.reportingDataAnnotations.get",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}"
            },
            "create": {
              "id": "analyticsadmin.properties.reportingDataAnnotations.create",
              "description": "Creates a Reporting Data Annotation.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/reportingDataAnnotations"
            },
            "patch": {
              "description": "Updates a Reporting Data Annotation.",
              "id": "analyticsadmin.properties.reportingDataAnnotations.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "accessBindings": {
          "methods": {
            "batchGet": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about multiple access bindings to an account or property.",
              "id": "analyticsadmin.properties.accessBindings.batchGet"
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate",
              "httpMethod": "POST",
              "description": "Updates information about multiple access bindings to an account or property.",
              "id": "analyticsadmin.properties.accessBindings.batchUpdate"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "httpMethod": "PATCH",
              "description": "Updates an access binding on an account or property.",
              "id": "analyticsadmin.properties.accessBindings.patch"
            },
            "batchDelete": {
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "id": "analyticsadmin.properties.accessBindings.delete",
              "description": "Deletes an access binding on an account or property."
            },
            "list": {
              "id": "analyticsadmin.properties.accessBindings.list",
              "description": "Lists all access bindings on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "httpMethod": "GET"
            },
            "batchCreate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate",
              "id": "analyticsadmin.properties.accessBindings.batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created."
            },
            "create": {
              "path": "v1alpha/{+parent}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "httpMethod": "POST",
              "description": "Creates an access binding on an account or property.",
              "id": "analyticsadmin.properties.accessBindings.create"
            },
            "get": {
              "description": "Gets information about an access binding.",
              "id": "analyticsadmin.properties.accessBindings.get",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "create": {
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks"
            },
            "patch": {
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property."
            },
            "get": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get"
            },
            "list": {
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "httpMethod": "GET"
            },
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property."
            }
          }
        },
        "subpropertySyncConfigs": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.subpropertySyncConfigs.list",
              "description": "List all `SubpropertySyncConfig` resources for a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/subpropertySyncConfigs"
            },
            "get": {
              "id": "analyticsadmin.properties.subpropertySyncConfigs.get",
              "description": "Lookup for a single `SubpropertySyncConfig`.",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs/{subpropertySyncConfigsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs/{subpropertySyncConfigsId}",
              "id": "analyticsadmin.properties.subpropertySyncConfigs.patch",
              "description": "Updates a `SubpropertySyncConfig`."
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "description": "Creates a GoogleAdsLink."
            },
            "patch": {
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "description": "Updates a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "description": "Deletes a GoogleAdsLink on a property"
            },
            "list": {
              "description": "Lists GoogleAdsLinks on a property.",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks"
            }
          }
        },
        "channelGroups": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.channelGroups.create",
              "description": "Creates a ChannelGroup.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/channelGroups",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups"
            },
            "patch": {
              "id": "analyticsadmin.properties.channelGroups.patch",
              "description": "Updates a ChannelGroup.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "httpMethod": "PATCH"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "description": "Lookup for a single ChannelGroup.",
              "id": "analyticsadmin.properties.channelGroups.get"
            },
            "list": {
              "description": "Lists ChannelGroups on a property.",
              "id": "analyticsadmin.properties.channelGroups.list",
              "path": "v1alpha/{+parent}/channelGroups",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "httpMethod": "GET"
            },
            "delete": {
              "id": "analyticsadmin.properties.channelGroups.delete",
              "description": "Deletes a ChannelGroup on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "httpMethod": "DELETE"
            }
          }
        },
        "keyEvents": {
          "methods": {
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a Key Event.",
              "id": "analyticsadmin.properties.keyEvents.delete"
            },
            "list": {
              "id": "analyticsadmin.properties.keyEvents.list",
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/keyEvents",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents",
              "httpMethod": "GET"
            },
            "create": {
              "path": "v1alpha/{+parent}/keyEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents",
              "httpMethod": "POST",
              "description": "Creates a Key Event.",
              "id": "analyticsadmin.properties.keyEvents.create"
            },
            "patch": {
              "id": "analyticsadmin.properties.keyEvents.patch",
              "description": "Updates a Key Event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "id": "analyticsadmin.properties.keyEvents.get",
              "description": "Retrieve a single Key Event."
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.bigQueryLinks.delete",
              "description": "Deletes a BigQueryLink on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "httpMethod": "DELETE"
            },
            "list": {
              "id": "analyticsadmin.properties.bigQueryLinks.list",
              "description": "Lists BigQuery Links on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "httpMethod": "GET"
            },
            "get": {
              "description": "Lookup for a single BigQuery Link.",
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "httpMethod": "POST",
              "description": "Creates a BigQueryLink.",
              "id": "analyticsadmin.properties.bigQueryLinks.create"
            },
            "patch": {
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a BigQueryLink.",
              "id": "analyticsadmin.properties.bigQueryLinks.patch"
            }
          }
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        }
      }
    }
  },
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "name": "analyticsadmin",
  "batchPath": "batch"
}