{
  "canonicalName": "Google Analytics Admin",
  "servicePath": "",
  "basePath": "",
  "protocol": "rest",
  "id": "analyticsadmin:v1beta",
  "version": "v1beta",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "revision": "20260421",
  "discoveryVersion": "v1",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "title": "Google Analytics Admin API",
  "ownerName": "Google",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "resources": {
    "accounts": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.list",
          "path": "v1beta/accounts",
          "flatPath": "v1beta/accounts",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "provisionAccountTicket": {
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "httpMethod": "POST",
          "flatPath": "v1beta/accounts:provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/accounts:provisionAccountTicket"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "analyticsadmin.accounts.delete",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "getDataSharingSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/accounts/{accountsId}/dataSharingSettings",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/accounts/{accountsId}",
          "description": "Lookup for a single Account.",
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.accounts.get",
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1beta/accounts/{accountsId}",
          "description": "Updates an account.",
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.accounts.patch",
          "httpMethod": "PATCH"
        },
        "searchChangeHistoryEvents": {
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "path": "v1beta/{+account}:searchChangeHistoryEvents",
          "flatPath": "v1beta/accounts/{accountsId}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters. Only returns the subset of changes supported by the API. The UI may return additional changes.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "runAccessReport": {
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.runAccessReport",
          "path": "v1beta/{+entity}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/accounts/{accountsId}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]"
        }
      }
    },
    "properties": {
      "methods": {
        "create": {
          "id": "analyticsadmin.properties.create",
          "httpMethod": "POST",
          "flatPath": "v1beta/properties",
          "description": "Creates a Google Analytics property with the specified location and attributes.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/properties"
        },
        "updateDataRetentionSettings": {
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "description": "Updates the singleton data retention settings for this property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "patch": {
          "flatPath": "v1beta/properties/{propertiesId}",
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.properties.patch",
          "httpMethod": "PATCH"
        },
        "getDataRetentionSettings": {
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "path": "v1beta/{+name}"
        },
        "acknowledgeUserDataCollection": {
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "httpMethod": "POST",
          "flatPath": "v1beta/properties/{propertiesId}:acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+property}:acknowledgeUserDataCollection"
        },
        "delete": {
          "flatPath": "v1beta/properties/{propertiesId}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.properties.delete",
          "httpMethod": "DELETE"
        },
        "list": {
          "id": "analyticsadmin.properties.list",
          "httpMethod": "GET",
          "flatPath": "v1beta/properties",
          "description": "Returns child Properties under the specified parent Account. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/properties"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/properties/{propertiesId}",
          "description": "Lookup for a single GA Property.",
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.properties.get",
          "httpMethod": "GET"
        },
        "runAccessReport": {
          "path": "v1beta/{+entity}:runAccessReport",
          "flatPath": "v1beta/properties/{propertiesId}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.runAccessReport"
        }
      },
      "resources": {
        "googleAdsLinks": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "httpMethod": "POST"
            },
            "delete": {
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "description": "Deletes a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}"
            },
            "patch": {
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "description": "Updates a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "httpMethod": "PATCH"
            },
            "list": {
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "httpMethod": "GET",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+parent}/googleAdsLinks"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "patch": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Deprecated: Use `UpdateKeyEvent` instead. Updates a conversion event with the specified attributes.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true,
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.conversionEvents.patch"
            },
            "get": {
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Deprecated: Use `GetKeyEvent` instead. Retrieve a single conversion event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "deprecated": true,
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "httpMethod": "GET"
            },
            "create": {
              "id": "analyticsadmin.properties.conversionEvents.create",
              "httpMethod": "POST",
              "deprecated": true,
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "description": "Deprecated: Use `CreateKeyEvent` instead. Creates a conversion event with the specified attributes.",
              "path": "v1beta/{+parent}/conversionEvents"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true,
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Deprecated: Use `DeleteKeyEvent` instead. Deletes a conversion event in a property.",
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "httpMethod": "DELETE"
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "path": "v1beta/{+parent}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "deprecated": true,
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "description": "Deprecated: Use `ListKeyEvents` instead. Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found."
            }
          },
          "deprecated": true
        },
        "customMetrics": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Updates a CustomMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "archive": {
              "id": "analyticsadmin.properties.customMetrics.archive",
              "httpMethod": "POST",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "description": "Archives a CustomMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}:archive"
            },
            "get": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Lookup for a single CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customMetrics.get"
            },
            "list": {
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "description": "Lists CustomMetrics on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+parent}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.list",
              "httpMethod": "GET"
            },
            "create": {
              "id": "analyticsadmin.properties.customMetrics.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "description": "Creates a CustomMetric.",
              "path": "v1beta/{+parent}/customMetrics"
            }
          }
        },
        "keyEvents": {
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.keyEvents.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "description": "Updates a Key Event.",
              "path": "v1beta/{+name}"
            },
            "get": {
              "id": "analyticsadmin.properties.keyEvents.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "description": "Retrieve a single Key Event.",
              "path": "v1beta/{+name}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents",
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found.",
              "path": "v1beta/{+parent}/keyEvents",
              "id": "analyticsadmin.properties.keyEvents.list",
              "httpMethod": "GET"
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents",
              "description": "Creates a Key Event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/keyEvents",
              "id": "analyticsadmin.properties.keyEvents.create",
              "httpMethod": "POST"
            },
            "delete": {
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "description": "Deletes a Key Event.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.keyEvents.delete"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "description": "Updates a CustomDimension on a property.",
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "httpMethod": "PATCH"
            },
            "archive": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "description": "Archives a CustomDimension on a property.",
              "path": "v1beta/{+name}:archive",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "httpMethod": "POST"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "description": "Lookup for a single CustomDimension.",
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.customDimensions.get",
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.create",
              "path": "v1beta/{+parent}/customDimensions",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "description": "Creates a CustomDimension.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "id": "analyticsadmin.properties.customDimensions.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "description": "Lists CustomDimensions on a property.",
              "path": "v1beta/{+parent}/customDimensions"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "path": "v1beta/{+parent}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink."
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "path": "v1beta/{+parent}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink."
            },
            "delete": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "description": "Deletes a FirebaseLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.firebaseLinks.delete"
            }
          }
        },
        "dataStreams": {
          "methods": {
            "patch": {
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Updates a DataStream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.dataStreams.patch",
              "httpMethod": "PATCH"
            },
            "get": {
              "id": "analyticsadmin.properties.dataStreams.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Lookup for a single DataStream.",
              "path": "v1beta/{+name}"
            },
            "list": {
              "id": "analyticsadmin.properties.dataStreams.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "description": "Lists DataStreams on a property.",
              "path": "v1beta/{+parent}/dataStreams"
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.dataStreams.create",
              "path": "v1beta/{+parent}/dataStreams",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "description": "Creates a DataStream.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.dataStreams.delete",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Deletes a DataStream on a property."
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "list": {
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list"
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "delete": {
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1beta/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "path": "v1beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Lookup for a single MeasurementProtocolSecret."
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Updates a measurement protocol secret.",
                  "path": "v1beta/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "httpMethod": "PATCH"
                }
              }
            }
          }
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "id": "analyticsadmin.accountSummaries.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/accountSummaries",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "path": "v1beta/accountSummaries"
        }
      }
    }
  },
  "name": "analyticsadmin",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "version_module": true,
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        }
      }
    }
  }
}