{
  "discoveryVersion": "v1",
  "name": "analyticsadmin",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "version": "v1beta",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        }
      }
    }
  },
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "title": "Google Analytics Admin API",
  "protocol": "rest",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "ownerName": "Google",
  "basePath": "",
  "canonicalName": "Google Analytics Admin",
  "servicePath": "",
  "id": "analyticsadmin:v1beta",
  "version_module": true,
  "revision": "20260412",
  "ownerDomain": "google.com",
  "resources": {
    "accounts": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.delete",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}",
          "httpMethod": "DELETE"
        },
        "searchChangeHistoryEvents": {
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters. Only returns the subset of changes supported by the API. The UI may return additional changes.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+account}:searchChangeHistoryEvents",
          "flatPath": "v1beta/accounts/{accountsId}:searchChangeHistoryEvents",
          "httpMethod": "POST"
        },
        "list": {
          "path": "v1beta/accounts",
          "flatPath": "v1beta/accounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.list",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found."
        },
        "getDataSharingSettings": {
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}/dataSharingSettings",
          "httpMethod": "GET",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "provisionAccountTicket": {
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/accounts:provisionAccountTicket",
          "flatPath": "v1beta/accounts:provisionAccountTicket",
          "httpMethod": "POST"
        },
        "runAccessReport": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "path": "v1beta/{+entity}:runAccessReport",
          "flatPath": "v1beta/accounts/{accountsId}:runAccessReport",
          "httpMethod": "POST"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.get",
          "description": "Lookup for a single Account.",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}",
          "httpMethod": "GET"
        },
        "patch": {
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.accounts.patch",
          "description": "Updates an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "path": "v1beta/accountSummaries",
          "flatPath": "v1beta/accountSummaries",
          "httpMethod": "GET",
          "id": "analyticsadmin.accountSummaries.list",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    },
    "properties": {
      "methods": {
        "runAccessReport": {
          "path": "v1beta/{+entity}:runAccessReport",
          "flatPath": "v1beta/properties/{propertiesId}:runAccessReport",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]"
        },
        "getDataRetentionSettings": {
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property."
        },
        "create": {
          "path": "v1beta/properties",
          "flatPath": "v1beta/properties",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.create",
          "description": "Creates a Google Analytics property with the specified location and attributes."
        },
        "delete": {
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.delete",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found."
        },
        "acknowledgeUserDataCollection": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "path": "v1beta/{+property}:acknowledgeUserDataCollection",
          "flatPath": "v1beta/properties/{propertiesId}:acknowledgeUserDataCollection",
          "httpMethod": "POST"
        },
        "updateDataRetentionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "description": "Updates the singleton data retention settings for this property.",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "httpMethod": "PATCH"
        },
        "list": {
          "path": "v1beta/properties",
          "flatPath": "v1beta/properties",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.list",
          "description": "Returns child Properties under the specified parent Account. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found."
        },
        "patch": {
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.patch",
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.get",
          "description": "Lookup for a single GA Property.",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "conversionEvents": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.conversionEvents.list",
              "description": "Deprecated: Use `ListKeyEvents` instead. Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+parent}/conversionEvents",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "httpMethod": "GET",
              "deprecated": true
            },
            "delete": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "DELETE",
              "deprecated": true,
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "description": "Deprecated: Use `DeleteKeyEvent` instead. Deletes a conversion event in a property."
            },
            "create": {
              "id": "analyticsadmin.properties.conversionEvents.create",
              "description": "Deprecated: Use `CreateKeyEvent` instead. Creates a conversion event with the specified attributes.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/conversionEvents",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "httpMethod": "POST",
              "deprecated": true
            },
            "get": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "GET",
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.get",
              "description": "Deprecated: Use `GetKeyEvent` instead. Retrieve a single conversion event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "deprecated": true,
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "description": "Deprecated: Use `UpdateKeyEvent` instead. Updates a conversion event with the specified attributes.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          },
          "deprecated": true
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "path": "v1beta/{+name}:archive",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "description": "Archives a CustomMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "path": "v1beta/{+parent}/customMetrics",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customMetrics.list",
              "description": "Lists CustomMetrics on a property."
            },
            "patch": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "description": "Updates a CustomMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "path": "v1beta/{+parent}/customMetrics",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.create",
              "description": "Creates a CustomMetric."
            },
            "get": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customMetrics.get",
              "description": "Lookup for a single CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "patch": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "description": "Updates a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "description": "Creates a GoogleAdsLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/googleAdsLinks",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "httpMethod": "POST"
            },
            "list": {
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "description": "Lists GoogleAdsLinks on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+parent}/googleAdsLinks",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "httpMethod": "GET"
            },
            "delete": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "description": "Deletes a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "keyEvents": {
          "methods": {
            "patch": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.keyEvents.patch",
              "description": "Updates a Key Event."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.keyEvents.create",
              "description": "Creates a Key Event.",
              "path": "v1beta/{+parent}/keyEvents",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents",
              "httpMethod": "POST"
            },
            "get": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.keyEvents.get",
              "description": "Retrieve a single Key Event."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.keyEvents.list",
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found.",
              "path": "v1beta/{+parent}/keyEvents",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents",
              "httpMethod": "GET"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.keyEvents.delete",
              "description": "Deletes a Key Event.",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "httpMethod": "DELETE"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "description": "Deletes a FirebaseLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "path": "v1beta/{+parent}/firebaseLinks",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+parent}/firebaseLinks",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "httpMethod": "GET"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.customDimensions.create",
              "description": "Creates a CustomDimension.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/customDimensions",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "httpMethod": "POST"
            },
            "get": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.get",
              "description": "Lookup for a single CustomDimension."
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.patch",
              "description": "Updates a CustomDimension on a property.",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "PATCH"
            },
            "list": {
              "id": "analyticsadmin.properties.customDimensions.list",
              "description": "Lists CustomDimensions on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+parent}/customDimensions",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "httpMethod": "GET"
            },
            "archive": {
              "id": "analyticsadmin.properties.customDimensions.archive",
              "description": "Archives a CustomDimension on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}:archive",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "httpMethod": "POST"
            }
          }
        },
        "dataStreams": {
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "GET"
                },
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "description": "Updates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "PATCH"
                },
                "get": {
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "description": "Lookup for a single MeasurementProtocolSecret."
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "description": "Creates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "POST"
                }
              }
            }
          },
          "methods": {
            "list": {
              "path": "v1beta/{+parent}/dataStreams",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.list",
              "description": "Lists DataStreams on a property."
            },
            "delete": {
              "id": "analyticsadmin.properties.dataStreams.delete",
              "description": "Deletes a DataStream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "DELETE"
            },
            "create": {
              "path": "v1beta/{+parent}/dataStreams",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.create",
              "description": "Creates a DataStream."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.get",
              "description": "Lookup for a single DataStream.",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "GET"
            },
            "patch": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.patch",
              "description": "Updates a DataStream on a property."
            }
          }
        }
      }
    }
  }
}