{
  "servicePath": "",
  "protocol": "rest",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "canonicalName": "Google Analytics Admin",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "id": "analyticsadmin:v1alpha",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "version_module": true,
  "batchPath": "batch",
  "discoveryVersion": "v1",
  "version": "v1alpha",
  "basePath": "",
  "name": "analyticsadmin",
  "resources": {
    "accountSummaries": {
      "methods": {
        "list": {
          "path": "v1alpha/accountSummaries",
          "flatPath": "v1alpha/accountSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns summaries of all accounts accessible by the caller.",
          "httpMethod": "GET",
          "id": "analyticsadmin.accountSummaries.list"
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "path": "v1alpha/{+name}",
          "description": "Lookup for a single Account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.get",
          "httpMethod": "GET"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "analyticsadmin.accounts.delete",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}"
        },
        "searchChangeHistoryEvents": {
          "description": "Searches through all changes to an account or its children given the specified set of filters. Only returns the subset of changes supported by the API. The UI may return additional changes.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "httpMethod": "POST"
        },
        "runAccessReport": {
          "id": "analyticsadmin.accounts.runAccessReport",
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "path": "v1alpha/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "patch": {
          "id": "analyticsadmin.accounts.patch",
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "path": "v1alpha/{+name}",
          "description": "Updates an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "provisionAccountTicket": {
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Requests a ticket for creating an account."
        },
        "list": {
          "id": "analyticsadmin.accounts.list",
          "httpMethod": "GET",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accounts",
          "path": "v1alpha/accounts"
        },
        "getDataSharingSettings": {
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "accessBindings": {
          "methods": {
            "list": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "path": "v1alpha/{+parent}/accessBindings",
              "description": "Lists all access bindings on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.accessBindings.list",
              "httpMethod": "GET"
            },
            "batchCreate": {
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.accessBindings.batchCreate"
            },
            "batchDelete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.accessBindings.batchDelete"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}"
            },
            "batchUpdate": {
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "httpMethod": "POST",
              "description": "Updates information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate"
            },
            "create": {
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates an access binding on an account or property.",
              "httpMethod": "POST",
              "id": "analyticsadmin.accounts.accessBindings.create"
            },
            "get": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "description": "Gets information about an access binding.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.accessBindings.get",
              "httpMethod": "GET"
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.accounts.accessBindings.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}"
            },
            "batchGet": {
              "description": "Gets information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet",
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "id": "analyticsadmin.accounts.accessBindings.batchGet",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "properties": {
      "methods": {
        "createRollupProperty": {
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.createRollupProperty",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Create a roll-up property and all roll-up property source links.",
          "path": "v1alpha/properties:createRollupProperty",
          "flatPath": "v1alpha/properties:createRollupProperty"
        },
        "getDataRetentionSettings": {
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns the singleton data retention settings for this property."
        },
        "getAttributionSettings": {
          "description": "Lookup for a AttributionSettings singleton.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.getAttributionSettings",
          "httpMethod": "GET"
        },
        "submitUserDeletion": {
          "id": "analyticsadmin.properties.submitUserDeletion",
          "httpMethod": "POST",
          "description": "Submits a request for user deletion for a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}:submitUserDeletion",
          "path": "v1alpha/{+name}:submitUserDeletion"
        },
        "runAccessReport": {
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "path": "v1alpha/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.runAccessReport",
          "httpMethod": "POST"
        },
        "acknowledgeUserDataCollection": {
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created."
        },
        "updateDataRetentionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "path": "v1alpha/{+name}",
          "description": "Updates the singleton data retention settings for this property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "httpMethod": "PATCH"
        },
        "provisionSubproperty": {
          "flatPath": "v1alpha/properties:provisionSubproperty",
          "path": "v1alpha/properties:provisionSubproperty",
          "description": "Create a subproperty and a subproperty event filter that applies to the created subproperty.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.provisionSubproperty",
          "httpMethod": "POST"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates a property.",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.patch"
        },
        "updateAttributionSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates attribution settings on a property.",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.updateAttributionSettings"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns child Properties under the specified parent Account. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "path": "v1alpha/properties",
          "flatPath": "v1alpha/properties",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.list"
        },
        "getGoogleSignalsSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for Google Signals settings for a property.",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings"
        },
        "getUserProvidedDataSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Looks up settings related to user-provided data for a property.",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/userProvidedDataSettings",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getUserProvidedDataSettings"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single GA Property.",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.get"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Creates a Google Analytics property with the specified location and attributes.",
          "path": "v1alpha/properties",
          "flatPath": "v1alpha/properties",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.create"
        },
        "delete": {
          "id": "analyticsadmin.properties.delete",
          "httpMethod": "DELETE",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}",
          "path": "v1alpha/{+name}"
        },
        "updateGoogleSignalsSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "path": "v1alpha/{+name}",
          "description": "Updates Google Signals settings for a property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "httpMethod": "PATCH"
        },
        "getReportingIdentitySettings": {
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getReportingIdentitySettings",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/reportingIdentitySettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns the reporting identity settings for this property."
        }
      },
      "resources": {
        "firebaseLinks": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "httpMethod": "POST",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "path": "v1alpha/{+parent}/firebaseLinks"
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a FirebaseLink on a property"
            }
          }
        },
        "dataStreams": {
          "methods": {
            "updateEnhancedMeasurementSettings": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings"
            },
            "getGlobalSiteTag": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag"
            },
            "list": {
              "id": "analyticsadmin.properties.dataStreams.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "path": "v1alpha/{+parent}/dataStreams",
              "description": "Lists DataStreams on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "description": "Creates a DataStream.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "path": "v1alpha/{+parent}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.create",
              "httpMethod": "POST"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single DataStream.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.get"
            },
            "delete": {
              "id": "analyticsadmin.properties.dataStreams.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes a DataStream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "updateDataRedactionSettings": {
              "id": "analyticsadmin.properties.dataStreams.updateDataRedactionSettings",
              "httpMethod": "PATCH",
              "description": "Updates a DataRedactionSettings on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "path": "v1alpha/{+name}"
            },
            "getEnhancedMeasurementSettings": {
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "getDataRedactionSettings": {
              "id": "analyticsadmin.properties.dataStreams.getDataRedactionSettings",
              "httpMethod": "GET",
              "description": "Lookup for a single DataRedactionSettings.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a DataStream on a property.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.dataStreams.patch"
            }
          },
          "resources": {
            "eventEditRules": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lists EventEditRules on a web data stream.",
                  "path": "v1alpha/{+parent}/eventEditRules",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.list"
                },
                "get": {
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.get",
                  "httpMethod": "GET",
                  "description": "Lookup for a single EventEditRule.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "path": "v1alpha/{+name}"
                },
                "create": {
                  "path": "v1alpha/{+parent}/eventEditRules",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Creates an EventEditRule.",
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.create"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Deletes an EventEditRule.",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "httpMethod": "DELETE",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.delete"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Updates an EventEditRule.",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}"
                },
                "reorder": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules:reorder",
                  "path": "v1alpha/{+parent}/eventEditRules:reorder",
                  "description": "Changes the processing order of event edit rules on the specified stream.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.reorder",
                  "httpMethod": "POST"
                }
              }
            },
            "measurementProtocolSecrets": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list"
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lookup for a single MeasurementProtocolSecret."
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "httpMethod": "POST",
                  "description": "Creates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Updates a measurement protocol secret.",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "httpMethod": "DELETE"
                }
              }
            },
            "sKAdNetworkConversionValueSchema": {
              "methods": {
                "get": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "path": "v1alpha/{+name}",
                  "description": "Looks up a single SKAdNetworkConversionValueSchema.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.get",
                  "httpMethod": "GET"
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.create",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "description": "Creates a SKAdNetworkConversionValueSchema.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Updates a SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Deletes target SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}"
                },
                "list": {
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.list",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lists SKAdNetworkConversionValueSchema on a stream. Properties can have at most one SKAdNetworkConversionValueSchema."
                }
              }
            },
            "eventCreateRules": {
              "methods": {
                "get": {
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lookup for a single EventCreateRule.",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get"
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Creates an EventCreateRule.",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules"
                },
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "path": "v1alpha/{+name}",
                  "description": "Deletes an EventCreateRule.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete",
                  "httpMethod": "DELETE"
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Updates an EventCreateRule.",
                  "httpMethod": "PATCH",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lists EventCreateRules on a web data stream.",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list"
                }
              }
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes a ExpandedDataSet on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a ExpandedDataSet on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.expandedDataSets.patch"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single ExpandedDataSet.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "httpMethod": "GET"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "description": "Creates a ExpandedDataSet.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.expandedDataSets.create",
              "httpMethod": "POST"
            },
            "list": {
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "description": "Lists ExpandedDataSets on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "rollupPropertySourceLinks": {
          "methods": {
            "delete": {
              "description": "Deletes a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.delete",
              "httpMethod": "DELETE"
            },
            "get": {
              "description": "Lookup for a single roll-up property source Link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.get",
              "httpMethod": "GET"
            },
            "list": {
              "description": "Lists roll-up property source Links on a property. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.list",
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks"
            }
          }
        },
        "keyEvents": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.keyEvents.list",
              "httpMethod": "GET",
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents",
              "path": "v1alpha/{+parent}/keyEvents"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes a Key Event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.keyEvents.delete",
              "httpMethod": "DELETE"
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.keyEvents.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a Key Event.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}"
            },
            "create": {
              "id": "analyticsadmin.properties.keyEvents.create",
              "httpMethod": "POST",
              "description": "Creates a Key Event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents",
              "path": "v1alpha/{+parent}/keyEvents"
            },
            "get": {
              "id": "analyticsadmin.properties.keyEvents.get",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "path": "v1alpha/{+name}",
              "description": "Retrieve a single Key Event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "httpMethod": "POST",
              "description": "Creates a GoogleAdsLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "path": "v1alpha/{+parent}/googleAdsLinks"
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists GoogleAdsLinks on a property.",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a GoogleAdsLink on a property",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a GoogleAdsLink on a property",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "httpMethod": "PATCH"
            }
          }
        },
        "accessBindings": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.accessBindings.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}"
            },
            "batchGet": {
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "httpMethod": "GET",
              "description": "Gets information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet",
              "path": "v1alpha/{+parent}/accessBindings:batchGet"
            },
            "list": {
              "id": "analyticsadmin.properties.accessBindings.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "path": "v1alpha/{+parent}/accessBindings",
              "description": "Lists all access bindings on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "batchCreate": {
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "id": "analyticsadmin.properties.accessBindings.batchCreate",
              "httpMethod": "POST"
            },
            "batchDelete": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "httpMethod": "POST"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.accessBindings.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Deletes an access binding on an account or property."
            },
            "batchUpdate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Updates information about multiple access bindings to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.accessBindings.batchUpdate"
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.accessBindings.create",
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates an access binding on an account or property."
            },
            "get": {
              "description": "Gets information about an access binding.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.accessBindings.get",
              "httpMethod": "GET"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "list": {
              "description": "Deprecated: Use `ListKeyEvents` instead. Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "deprecated": true,
              "path": "v1alpha/{+parent}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "httpMethod": "GET"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "deprecated": true,
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deprecated: Use `UpdateKeyEvent` instead. Updates a conversion event with the specified attributes.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.conversionEvents.patch"
            },
            "delete": {
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "deprecated": true,
              "path": "v1alpha/{+name}",
              "description": "Deprecated: Use `DeleteKeyEvent` instead. Deletes a conversion event in a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "path": "v1alpha/{+parent}/conversionEvents",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "deprecated": true,
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deprecated: Use `CreateKeyEvent` instead. Creates a conversion event with the specified attributes."
            },
            "get": {
              "id": "analyticsadmin.properties.conversionEvents.get",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "deprecated": true,
              "path": "v1alpha/{+name}",
              "description": "Deprecated: Use `GetKeyEvent` instead. Retrieve a single conversion event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          },
          "deprecated": true
        },
        "adSenseLinks": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Looks up a single AdSenseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.adSenseLinks.get",
              "httpMethod": "GET"
            },
            "create": {
              "id": "analyticsadmin.properties.adSenseLinks.create",
              "httpMethod": "POST",
              "description": "Creates an AdSenseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "path": "v1alpha/{+parent}/adSenseLinks"
            },
            "list": {
              "path": "v1alpha/{+parent}/adSenseLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists AdSenseLinks on a property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.adSenseLinks.list"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes an AdSenseLink.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.adSenseLinks.delete"
            }
          }
        },
        "subpropertyEventFilters": {
          "methods": {
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "description": "List all subproperty Event Filters on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.subpropertyEventFilters.list",
              "httpMethod": "GET"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.subpropertyEventFilters.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a subproperty event filter."
            },
            "patch": {
              "id": "analyticsadmin.properties.subpropertyEventFilters.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a subproperty Event Filter.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.subpropertyEventFilters.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a subproperty Event Filter.",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters"
            },
            "get": {
              "id": "analyticsadmin.properties.subpropertyEventFilters.get",
              "httpMethod": "GET",
              "description": "Lookup for a single subproperty Event Filter.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "subpropertySyncConfigs": {
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.subpropertySyncConfigs.patch",
              "httpMethod": "PATCH",
              "description": "Updates a `SubpropertySyncConfig`.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs/{subpropertySyncConfigsId}",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "id": "analyticsadmin.properties.subpropertySyncConfigs.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs",
              "path": "v1alpha/{+parent}/subpropertySyncConfigs",
              "description": "List all `SubpropertySyncConfig` resources for a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs/{subpropertySyncConfigsId}",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single `SubpropertySyncConfig`.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.subpropertySyncConfigs.get",
              "httpMethod": "GET"
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "httpMethod": "DELETE"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch"
            },
            "get": {
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "httpMethod": "GET"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "httpMethod": "POST"
            },
            "list": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "httpMethod": "GET",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "list": {
              "description": "Lists CustomDimensions on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "path": "v1alpha/{+parent}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.list",
              "httpMethod": "GET"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomDimension on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customDimensions.patch"
            },
            "archive": {
              "id": "analyticsadmin.properties.customDimensions.archive",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "path": "v1alpha/{+name}:archive",
              "description": "Archives a CustomDimension on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.create",
              "path": "v1alpha/{+parent}/customDimensions",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomDimension."
            },
            "get": {
              "id": "analyticsadmin.properties.customDimensions.get",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single CustomDimension.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a SearchAds360Link on a property.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.searchAds360Links.delete"
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a SearchAds360Link on a property."
            },
            "get": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Look up a single SearchAds360Link",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}"
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.searchAds360Links.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a SearchAds360Link.",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links"
            },
            "list": {
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "description": "Lists all SearchAds360Links on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "approve": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "path": "v1alpha/{+name}:approve",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve"
            },
            "delete": {
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "httpMethod": "DELETE"
            },
            "get": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "httpMethod": "POST"
            },
            "cancel": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "path": "v1alpha/{+name}:cancel",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically."
            },
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals"
            }
          }
        },
        "calculatedMetrics": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.calculatedMetrics.list",
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CalculatedMetrics on a property."
            },
            "delete": {
              "id": "analyticsadmin.properties.calculatedMetrics.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a CalculatedMetric on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.calculatedMetrics.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CalculatedMetric on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}"
            },
            "get": {
              "id": "analyticsadmin.properties.calculatedMetrics.get",
              "httpMethod": "GET",
              "description": "Lookup for a single CalculatedMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "id": "analyticsadmin.properties.calculatedMetrics.create",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "description": "Creates a CalculatedMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "channelGroups": {
          "methods": {
            "list": {
              "description": "Lists ChannelGroups on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "path": "v1alpha/{+parent}/channelGroups",
              "id": "analyticsadmin.properties.channelGroups.list",
              "httpMethod": "GET"
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.channelGroups.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a ChannelGroup.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.channelGroups.delete",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a ChannelGroup on a property."
            },
            "get": {
              "description": "Lookup for a single ChannelGroup.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.channelGroups.get",
              "httpMethod": "GET"
            },
            "create": {
              "id": "analyticsadmin.properties.channelGroups.create",
              "httpMethod": "POST",
              "description": "Creates a ChannelGroup.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "path": "v1alpha/{+parent}/channelGroups"
            }
          }
        },
        "reportingDataAnnotations": {
          "methods": {
            "list": {
              "description": "List all Reporting Data Annotations on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations",
              "path": "v1alpha/{+parent}/reportingDataAnnotations",
              "id": "analyticsadmin.properties.reportingDataAnnotations.list",
              "httpMethod": "GET"
            },
            "patch": {
              "id": "analyticsadmin.properties.reportingDataAnnotations.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a Reporting Data Annotation.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "description": "Deletes a Reporting Data Annotation.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.reportingDataAnnotations.delete",
              "httpMethod": "DELETE"
            },
            "create": {
              "id": "analyticsadmin.properties.reportingDataAnnotations.create",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations",
              "path": "v1alpha/{+parent}/reportingDataAnnotations",
              "description": "Creates a Reporting Data Annotation.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "id": "analyticsadmin.properties.reportingDataAnnotations.get",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "path": "v1alpha/{+name}",
              "description": "Lookup a single Reporting Data Annotation.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "customMetrics": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a CustomMetric on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customMetrics.patch"
            },
            "archive": {
              "path": "v1alpha/{+name}:archive",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Archives a CustomMetric on a property.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.archive"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "path": "v1alpha/{+parent}/customMetrics",
              "description": "Creates a CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.create",
              "httpMethod": "POST"
            },
            "get": {
              "id": "analyticsadmin.properties.customMetrics.get",
              "httpMethod": "GET",
              "description": "Lookup for a single CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "path": "v1alpha/{+parent}/customMetrics",
              "description": "Lists CustomMetrics on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customMetrics.list",
              "httpMethod": "GET"
            }
          }
        },
        "audiences": {
          "methods": {
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.audiences.get"
            },
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.audiences.create",
              "path": "v1alpha/{+parent}/audiences",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates an Audience."
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.audiences.patch",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates an Audience on a property."
            },
            "archive": {
              "path": "v1alpha/{+name}:archive",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Archives an Audience on a property.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.audiences.archive"
            },
            "list": {
              "path": "v1alpha/{+parent}/audiences",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.audiences.list"
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.bigQueryLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a BigQueryLink.",
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single BigQuery Link.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "httpMethod": "GET"
            },
            "patch": {
              "id": "analyticsadmin.properties.bigQueryLinks.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Updates a BigQueryLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a BigQueryLink on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.bigQueryLinks.delete"
            },
            "list": {
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists BigQuery Links on a property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.bigQueryLinks.list"
            }
          }
        }
      }
    }
  },
  "revision": "20260429",
  "title": "Google Analytics Admin API",
  "ownerName": "Google"
}