{
  "ownerDomain": "google.com",
  "servicePath": "",
  "basePath": "",
  "discoveryVersion": "v1",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "name": "analyticsadmin",
  "kind": "discovery#restDescription",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "id": "analyticsadmin:v1beta",
  "revision": "20260429",
  "protocol": "rest",
  "batchPath": "batch",
  "title": "Google Analytics Admin API",
  "ownerName": "Google",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "canonicalName": "Google Analytics Admin",
  "fullyEncodeReservedExpansion": true,
  "resources": {
    "accountSummaries": {
      "methods": {
        "list": {
          "id": "analyticsadmin.accountSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/accountSummaries",
          "path": "v1beta/accountSummaries",
          "httpMethod": "GET",
          "description": "Returns summaries of all accounts accessible by the caller."
        }
      }
    },
    "properties": {
      "methods": {
        "get": {
          "flatPath": "v1beta/properties/{propertiesId}",
          "id": "analyticsadmin.properties.get",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single GA Property.",
          "httpMethod": "GET",
          "path": "v1beta/{+name}"
        },
        "acknowledgeUserDataCollection": {
          "httpMethod": "POST",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "path": "v1beta/{+property}:acknowledgeUserDataCollection",
          "flatPath": "v1beta/properties/{propertiesId}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection"
        },
        "runAccessReport": {
          "path": "v1beta/{+entity}:runAccessReport",
          "httpMethod": "POST",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "id": "analyticsadmin.properties.runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/properties/{propertiesId}:runAccessReport"
        },
        "patch": {
          "flatPath": "v1beta/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.patch",
          "description": "Updates a property.",
          "httpMethod": "PATCH",
          "path": "v1beta/{+name}"
        },
        "getDataRetentionSettings": {
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "path": "v1beta/{+name}",
          "httpMethod": "GET",
          "description": "Returns the singleton data retention settings for this property."
        },
        "create": {
          "id": "analyticsadmin.properties.create",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1beta/properties",
          "path": "v1beta/properties",
          "httpMethod": "POST",
          "description": "Creates a Google Analytics property with the specified location and attributes."
        },
        "updateDataRetentionSettings": {
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "httpMethod": "PATCH",
          "description": "Updates the singleton data retention settings for this property.",
          "path": "v1beta/{+name}"
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}",
          "id": "analyticsadmin.properties.delete",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "description": "Returns child Properties under the specified parent Account. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "path": "v1beta/properties",
          "flatPath": "v1beta/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.list"
        }
      },
      "resources": {
        "firebaseLinks": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "path": "v1beta/{+parent}/firebaseLinks",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes a FirebaseLink on a property",
              "path": "v1beta/{+name}"
            },
            "list": {
              "path": "v1beta/{+parent}/firebaseLinks",
              "httpMethod": "GET",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "patch": {
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "httpMethod": "PATCH",
              "description": "Updates a GoogleAdsLink on a property",
              "path": "v1beta/{+name}"
            },
            "create": {
              "description": "Creates a GoogleAdsLink.",
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.create"
            },
            "delete": {
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a GoogleAdsLink on a property",
              "path": "v1beta/{+name}"
            },
            "list": {
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "httpMethod": "GET"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "delete": {
              "description": "Deprecated: Use `DeleteKeyEvent` instead. Deletes a conversion event in a property.",
              "httpMethod": "DELETE",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.delete"
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true,
              "httpMethod": "POST",
              "description": "Deprecated: Use `CreateKeyEvent` instead. Creates a conversion event with the specified attributes.",
              "path": "v1beta/{+parent}/conversionEvents"
            },
            "get": {
              "path": "v1beta/{+name}",
              "httpMethod": "GET",
              "description": "Deprecated: Use `GetKeyEvent` instead. Retrieve a single conversion event.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.get",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "list": {
              "path": "v1beta/{+parent}/conversionEvents",
              "description": "Deprecated: Use `ListKeyEvents` instead. Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.list",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents"
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Deprecated: Use `UpdateKeyEvent` instead. Updates a conversion event with the specified attributes.",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true
            }
          },
          "deprecated": true
        },
        "customDimensions": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.list",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "path": "v1beta/{+parent}/customDimensions",
              "description": "Lists CustomDimensions on a property.",
              "httpMethod": "GET"
            },
            "archive": {
              "path": "v1beta/{+name}:archive",
              "description": "Archives a CustomDimension on a property.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.archive",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.patch",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates a CustomDimension on a property."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.create",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "path": "v1beta/{+parent}/customDimensions",
              "description": "Creates a CustomDimension.",
              "httpMethod": "POST"
            },
            "get": {
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.get",
              "description": "Lookup for a single CustomDimension.",
              "httpMethod": "GET",
              "path": "v1beta/{+name}"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a CustomMetric.",
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/customMetrics"
            },
            "get": {
              "description": "Lookup for a single CustomMetric.",
              "httpMethod": "GET",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "id": "analyticsadmin.properties.customMetrics.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a CustomMetric on a property.",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "path": "v1beta/{+parent}/customMetrics",
              "httpMethod": "GET",
              "description": "Lists CustomMetrics on a property.",
              "id": "analyticsadmin.properties.customMetrics.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics"
            },
            "archive": {
              "path": "v1beta/{+name}:archive",
              "description": "Archives a CustomMetric on a property.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive"
            }
          }
        },
        "dataStreams": {
          "methods": {
            "patch": {
              "description": "Updates a DataStream on a property.",
              "httpMethod": "PATCH",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Lists DataStreams on a property.",
              "httpMethod": "GET",
              "path": "v1beta/{+parent}/dataStreams",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.list"
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.create",
              "description": "Creates a DataStream.",
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/dataStreams"
            },
            "get": {
              "description": "Lookup for a single DataStream.",
              "httpMethod": "GET",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "id": "analyticsadmin.properties.dataStreams.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a DataStream on a property.",
              "path": "v1beta/{+name}"
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "delete": {
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "httpMethod": "DELETE",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete"
                },
                "get": {
                  "path": "v1beta/{+name}",
                  "httpMethod": "GET",
                  "description": "Lookup for a single MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "create": {
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "description": "Creates a measurement protocol secret.",
                  "httpMethod": "POST",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "httpMethod": "GET"
                },
                "patch": {
                  "path": "v1beta/{+name}",
                  "httpMethod": "PATCH",
                  "description": "Updates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                }
              }
            }
          }
        },
        "keyEvents": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates a Key Event.",
              "path": "v1beta/{+parent}/keyEvents",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents",
              "id": "analyticsadmin.properties.keyEvents.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "id": "analyticsadmin.properties.keyEvents.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Retrieve a single Key Event.",
              "path": "v1beta/{+name}"
            },
            "delete": {
              "id": "analyticsadmin.properties.keyEvents.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "path": "v1beta/{+name}",
              "httpMethod": "DELETE",
              "description": "Deletes a Key Event."
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a Key Event.",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.keyEvents.patch"
            },
            "list": {
              "id": "analyticsadmin.properties.keyEvents.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents",
              "path": "v1beta/{+parent}/keyEvents",
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found.",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "accounts": {
      "methods": {
        "searchChangeHistoryEvents": {
          "httpMethod": "POST",
          "description": "Searches through all changes to an account or its children given the specified set of filters. Only returns the subset of changes supported by the API. The UI may return additional changes.",
          "path": "v1beta/{+account}:searchChangeHistoryEvents",
          "flatPath": "v1beta/accounts/{accountsId}:searchChangeHistoryEvents",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "runAccessReport": {
          "httpMethod": "POST",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "path": "v1beta/{+entity}:runAccessReport",
          "flatPath": "v1beta/accounts/{accountsId}:runAccessReport",
          "id": "analyticsadmin.accounts.runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.delete",
          "flatPath": "v1beta/accounts/{accountsId}",
          "path": "v1beta/{+name}",
          "httpMethod": "DELETE",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.get",
          "flatPath": "v1beta/accounts/{accountsId}",
          "path": "v1beta/{+name}",
          "description": "Lookup for a single Account.",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.list",
          "flatPath": "v1beta/accounts",
          "path": "v1beta/accounts",
          "httpMethod": "GET",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found."
        },
        "patch": {
          "description": "Updates an account.",
          "httpMethod": "PATCH",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}",
          "id": "analyticsadmin.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "provisionAccountTicket": {
          "flatPath": "v1beta/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "httpMethod": "POST",
          "description": "Requests a ticket for creating an account.",
          "path": "v1beta/accounts:provisionAccountTicket"
        },
        "getDataSharingSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "flatPath": "v1beta/accounts/{accountsId}/dataSharingSettings",
          "path": "v1beta/{+name}",
          "httpMethod": "GET",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons."
        }
      }
    }
  },
  "version_module": true,
  "version": "v1beta",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html"
}