{
  "version": "v1alpha",
  "title": "Google Analytics Admin API",
  "discoveryVersion": "v1",
  "resources": {
    "accounts": {
      "methods": {
        "getDataSharingSettings": {
          "httpMethod": "GET",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings"
        },
        "list": {
          "id": "analyticsadmin.accounts.list",
          "flatPath": "v1alpha/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/accounts",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.patch",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "PATCH",
          "description": "Updates an account."
        },
        "delete": {
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.delete",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "DELETE",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found."
        },
        "runAccessReport": {
          "id": "analyticsadmin.accounts.runAccessReport",
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "httpMethod": "POST"
        },
        "get": {
          "id": "analyticsadmin.accounts.get",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single Account.",
          "httpMethod": "GET"
        },
        "provisionAccountTicket": {
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "path": "v1alpha/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Requests a ticket for creating an account.",
          "httpMethod": "POST"
        },
        "searchChangeHistoryEvents": {
          "httpMethod": "POST",
          "description": "Searches through all changes to an account or its children given the specified set of filters. Only returns the subset of changes supported by the API. The UI may return additional changes.",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents"
        }
      },
      "resources": {
        "accessBindings": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings",
              "id": "analyticsadmin.accounts.accessBindings.list",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "httpMethod": "GET",
              "description": "Lists all access bindings on an account or property."
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.accessBindings.patch",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "httpMethod": "PATCH",
              "description": "Updates an access binding on an account or property."
            },
            "batchCreate": {
              "httpMethod": "POST",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "id": "analyticsadmin.accounts.accessBindings.batchCreate",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate"
            },
            "batchGet": {
              "description": "Gets information about multiple access bindings to an account or property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.accounts.accessBindings.batchGet",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchGet"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates an access binding on an account or property.",
              "path": "v1alpha/{+parent}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.accessBindings.create",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings"
            },
            "batchDelete": {
              "httpMethod": "POST",
              "description": "Deletes information about multiple users' links to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "id": "analyticsadmin.accounts.accessBindings.batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete"
            },
            "delete": {
              "description": "Deletes an access binding on an account or property.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchUpdate": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate",
              "httpMethod": "POST",
              "description": "Updates information about multiple access bindings to an account or property."
            },
            "get": {
              "id": "analyticsadmin.accounts.accessBindings.get",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about an access binding.",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "description": "Returns summaries of all accounts accessible by the caller.",
          "httpMethod": "GET",
          "id": "analyticsadmin.accountSummaries.list",
          "flatPath": "v1alpha/accountSummaries",
          "path": "v1alpha/accountSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    },
    "properties": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.delete",
          "flatPath": "v1alpha/properties/{propertiesId}"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Lookup for a single GA Property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.get",
          "flatPath": "v1alpha/properties/{propertiesId}"
        },
        "submitUserDeletion": {
          "id": "analyticsadmin.properties.submitUserDeletion",
          "flatPath": "v1alpha/properties/{propertiesId}:submitUserDeletion",
          "path": "v1alpha/{+name}:submitUserDeletion",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Submits a request for user deletion for a property.",
          "httpMethod": "POST"
        },
        "getReportingIdentitySettings": {
          "httpMethod": "GET",
          "description": "Returns the reporting identity settings for this property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.getReportingIdentitySettings",
          "flatPath": "v1alpha/properties/{propertiesId}/reportingIdentitySettings"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.patch",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "httpMethod": "PATCH",
          "description": "Updates a property."
        },
        "runAccessReport": {
          "httpMethod": "POST",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+entity}:runAccessReport",
          "id": "analyticsadmin.properties.runAccessReport",
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport"
        },
        "provisionSubproperty": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties:provisionSubproperty",
          "id": "analyticsadmin.properties.provisionSubproperty",
          "flatPath": "v1alpha/properties:provisionSubproperty",
          "httpMethod": "POST",
          "description": "Create a subproperty and a subproperty event filter that applies to the created subproperty."
        },
        "updateDataRetentionSettings": {
          "httpMethod": "PATCH",
          "description": "Updates the singleton data retention settings for this property.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings"
        },
        "updateGoogleSignalsSettings": {
          "httpMethod": "PATCH",
          "description": "Updates Google Signals settings for a property.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings"
        },
        "getAttributionSettings": {
          "id": "analyticsadmin.properties.getAttributionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "description": "Lookup for a AttributionSettings singleton.",
          "httpMethod": "GET"
        },
        "create": {
          "path": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.create",
          "flatPath": "v1alpha/properties",
          "httpMethod": "POST",
          "description": "Creates a Google Analytics property with the specified location and attributes."
        },
        "createRollupProperty": {
          "id": "analyticsadmin.properties.createRollupProperty",
          "flatPath": "v1alpha/properties:createRollupProperty",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/properties:createRollupProperty",
          "description": "Create a roll-up property and all roll-up property source links.",
          "httpMethod": "POST"
        },
        "acknowledgeUserDataCollection": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "httpMethod": "POST",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created."
        },
        "updateAttributionSettings": {
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1alpha/{+name}",
          "description": "Updates attribution settings on a property.",
          "httpMethod": "PATCH"
        },
        "getGoogleSignalsSettings": {
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "description": "Lookup for Google Signals settings for a property.",
          "httpMethod": "GET"
        },
        "getDataRetentionSettings": {
          "description": "Returns the singleton data retention settings for this property.",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "list": {
          "id": "analyticsadmin.properties.list",
          "flatPath": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/properties",
          "description": "Returns child Properties under the specified parent Account. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "conversionEvents": {
          "methods": {
            "get": {
              "description": "Deprecated: Use `GetKeyEvent` instead. Retrieve a single conversion event.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.conversionEvents.get",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "deprecated": true,
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deprecated: Use `DeleteKeyEvent` instead. Deletes a conversion event in a property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "deprecated": true
            },
            "create": {
              "id": "analyticsadmin.properties.conversionEvents.create",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "deprecated": true,
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "description": "Deprecated: Use `CreateKeyEvent` instead. Creates a conversion event with the specified attributes.",
              "httpMethod": "POST"
            },
            "patch": {
              "description": "Deprecated: Use `UpdateKeyEvent` instead. Updates a conversion event with the specified attributes.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "deprecated": true,
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.list",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "deprecated": true,
              "httpMethod": "GET",
              "description": "Deprecated: Use `ListKeyEvents` instead. Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found."
            }
          },
          "deprecated": true
        },
        "calculatedMetrics": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.calculatedMetrics.get",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single CalculatedMetric.",
              "httpMethod": "GET"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.calculatedMetrics.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a CalculatedMetric on a property."
            },
            "create": {
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.calculatedMetrics.create",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "httpMethod": "POST",
              "description": "Creates a CalculatedMetric."
            },
            "list": {
              "description": "Lists CalculatedMetrics on a property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.calculatedMetrics.list",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/calculatedMetrics"
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a CalculatedMetric on a property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.calculatedMetrics.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}"
            }
          }
        },
        "accessBindings": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.accessBindings.list",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "httpMethod": "GET",
              "description": "Lists all access bindings on an account or property."
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates an access binding on an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.accessBindings.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}"
            },
            "batchCreate": {
              "id": "analyticsadmin.properties.accessBindings.batchCreate",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "httpMethod": "POST"
            },
            "batchGet": {
              "description": "Gets information about multiple access bindings to an account or property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchGet"
            },
            "create": {
              "description": "Creates an access binding on an account or property.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.accessBindings.create",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings"
            },
            "batchDelete": {
              "description": "Deletes information about multiple users' links to an account or property.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchDelete"
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.accessBindings.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}"
            },
            "batchUpdate": {
              "httpMethod": "POST",
              "description": "Updates information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "id": "analyticsadmin.properties.accessBindings.batchUpdate",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate"
            },
            "get": {
              "id": "analyticsadmin.properties.accessBindings.get",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Gets information about an access binding.",
              "httpMethod": "GET"
            }
          }
        },
        "subpropertySyncConfigs": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "description": "Lookup for a single `SubpropertySyncConfig`.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.subpropertySyncConfigs.get",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs/{subpropertySyncConfigsId}"
            },
            "list": {
              "httpMethod": "GET",
              "description": "List all `SubpropertySyncConfig` resources for a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/subpropertySyncConfigs",
              "id": "analyticsadmin.properties.subpropertySyncConfigs.list",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs"
            },
            "patch": {
              "description": "Updates a `SubpropertySyncConfig`.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.subpropertySyncConfigs.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs/{subpropertySyncConfigsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "create": {
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.create",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "httpMethod": "POST",
              "description": "Creates a CustomMetric."
            },
            "patch": {
              "description": "Updates a CustomMetric on a property.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "list": {
              "path": "v1alpha/{+parent}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customMetrics.list",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "httpMethod": "GET",
              "description": "Lists CustomMetrics on a property."
            },
            "archive": {
              "id": "analyticsadmin.properties.customMetrics.archive",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "path": "v1alpha/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Archives a CustomMetric on a property.",
              "httpMethod": "POST"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Lookup for a single CustomMetric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.customMetrics.get",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}"
            }
          }
        },
        "keyEvents": {
          "methods": {
            "get": {
              "description": "Retrieve a single Key Event.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.keyEvents.get",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "id": "analyticsadmin.properties.keyEvents.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a Key Event.",
              "httpMethod": "DELETE"
            },
            "create": {
              "id": "analyticsadmin.properties.keyEvents.create",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents",
              "path": "v1alpha/{+parent}/keyEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a Key Event.",
              "httpMethod": "POST"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.keyEvents.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "httpMethod": "PATCH",
              "description": "Updates a Key Event."
            },
            "list": {
              "path": "v1alpha/{+parent}/keyEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.keyEvents.list",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents",
              "httpMethod": "GET",
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found."
            }
          }
        },
        "adSenseLinks": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "description": "Looks up a single AdSenseLink.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.adSenseLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}"
            },
            "create": {
              "id": "analyticsadmin.properties.adSenseLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates an AdSenseLink.",
              "httpMethod": "POST"
            },
            "delete": {
              "description": "Deletes an AdSenseLink.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.adSenseLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "description": "Lists AdSenseLinks on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/adSenseLinks",
              "id": "analyticsadmin.properties.adSenseLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks"
            }
          }
        },
        "subpropertyEventFilters": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.subpropertyEventFilters.list",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "List all subproperty Event Filters on a property.",
              "httpMethod": "GET"
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a subproperty Event Filter.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.subpropertyEventFilters.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}"
            },
            "create": {
              "description": "Creates a subproperty Event Filter.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.subpropertyEventFilters.create",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/subpropertyEventFilters"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Lookup for a single subproperty Event Filter.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.subpropertyEventFilters.get",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}"
            },
            "delete": {
              "id": "analyticsadmin.properties.subpropertyEventFilters.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a subproperty event filter.",
              "httpMethod": "DELETE"
            }
          }
        },
        "audiences": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/audiences",
              "id": "analyticsadmin.properties.audiences.create",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "httpMethod": "POST",
              "description": "Creates an Audience."
            },
            "list": {
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.audiences.list",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "path": "v1alpha/{+parent}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "id": "analyticsadmin.properties.audiences.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Updates an Audience on a property.",
              "httpMethod": "PATCH"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.audiences.get",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}"
            },
            "archive": {
              "path": "v1alpha/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.audiences.archive",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "httpMethod": "POST",
              "description": "Archives an Audience on a property."
            }
          }
        },
        "channelGroups": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "description": "Lists ChannelGroups on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/channelGroups",
              "id": "analyticsadmin.properties.channelGroups.list",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups"
            },
            "patch": {
              "description": "Updates a ChannelGroup.",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.channelGroups.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "create": {
              "description": "Creates a ChannelGroup.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.channelGroups.create",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "path": "v1alpha/{+parent}/channelGroups",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a ChannelGroup on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.channelGroups.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.channelGroups.get",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "httpMethod": "GET",
              "description": "Lookup for a single ChannelGroup."
            }
          }
        },
        "rollupPropertySourceLinks": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "httpMethod": "GET",
              "description": "Lists roll-up property source Links on a property. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "httpMethod": "DELETE",
              "description": "Deletes a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties."
            },
            "get": {
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single roll-up property source Link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks"
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "delete": {
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "GET",
              "description": "Look up a single DisplayVideo360AdvertiserLink"
            },
            "create": {
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "httpMethod": "GET",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property."
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}"
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals"
            },
            "approve": {
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "path": "v1alpha/{+name}:approve",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "httpMethod": "GET"
            },
            "cancel": {
              "path": "v1alpha/{+name}:cancel",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "httpMethod": "POST",
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically."
            },
            "get": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "httpMethod": "GET",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals."
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "description": "Look up a single SearchAds360Link",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}"
            },
            "delete": {
              "description": "Deletes a SearchAds360Link on a property.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            },
            "list": {
              "httpMethod": "GET",
              "description": "Lists all SearchAds360Links on a property.",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links"
            },
            "patch": {
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a SearchAds360Link on a property.",
              "httpMethod": "PATCH"
            },
            "create": {
              "id": "analyticsadmin.properties.searchAds360Links.create",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/searchAds360Links",
              "description": "Creates a SearchAds360Link.",
              "httpMethod": "POST"
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates a BigQueryLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "id": "analyticsadmin.properties.bigQueryLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks"
            },
            "list": {
              "id": "analyticsadmin.properties.bigQueryLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "description": "Lists BigQuery Links on a property.",
              "httpMethod": "GET"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.bigQueryLinks.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "httpMethod": "PATCH",
              "description": "Updates a BigQueryLink."
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a BigQueryLink on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.bigQueryLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}"
            },
            "get": {
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single BigQuery Link.",
              "httpMethod": "GET"
            }
          }
        },
        "dataStreams": {
          "methods": {
            "updateDataRedactionSettings": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.updateDataRedactionSettings",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "httpMethod": "PATCH",
              "description": "Updates a DataRedactionSettings on a property."
            },
            "get": {
              "description": "Lookup for a single DataStream.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.get",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a DataStream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}"
            },
            "patch": {
              "id": "analyticsadmin.properties.dataStreams.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a DataStream on a property.",
              "httpMethod": "PATCH"
            },
            "getEnhancedMeasurementSettings": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "httpMethod": "GET",
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect."
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a DataStream.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.create",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams"
            },
            "updateEnhancedMeasurementSettings": {
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "httpMethod": "PATCH"
            },
            "getGlobalSiteTag": {
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "description": "Lists DataStreams on a property.",
              "path": "v1alpha/{+parent}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.list",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams"
            },
            "getDataRedactionSettings": {
              "description": "Lookup for a single DataRedactionSettings.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.getDataRedactionSettings",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            }
          },
          "resources": {
            "sKAdNetworkConversionValueSchema": {
              "methods": {
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes target SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.delete",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}"
                },
                "get": {
                  "httpMethod": "GET",
                  "description": "Looks up a single SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.get",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}"
                },
                "create": {
                  "description": "Creates a SKAdNetworkConversionValueSchema.",
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.create",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "description": "Updates a SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.patch",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}"
                },
                "list": {
                  "description": "Lists SKAdNetworkConversionValueSchema on a stream. Properties can have at most one SKAdNetworkConversionValueSchema.",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.list",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                }
              }
            },
            "measurementProtocolSecrets": {
              "methods": {
                "get": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lookup for a single MeasurementProtocolSecret.",
                  "httpMethod": "GET"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes target MeasurementProtocolSecret."
                },
                "list": {
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "httpMethod": "PATCH",
                  "description": "Updates a measurement protocol secret."
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Creates a measurement protocol secret.",
                  "httpMethod": "POST"
                }
              }
            },
            "eventCreateRules": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "httpMethod": "GET",
                  "description": "Lists EventCreateRules on a web data stream."
                },
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "description": "Updates an EventCreateRule.",
                  "httpMethod": "PATCH"
                },
                "create": {
                  "httpMethod": "POST",
                  "description": "Creates an EventCreateRule.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes an EventCreateRule.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}"
                },
                "get": {
                  "httpMethod": "GET",
                  "description": "Lookup for a single EventCreateRule.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}"
                }
              }
            },
            "eventEditRules": {
              "methods": {
                "get": {
                  "description": "Lookup for a single EventEditRule.",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.get",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes an EventEditRule.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.delete",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}"
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.create",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/eventEditRules",
                  "description": "Creates an EventEditRule.",
                  "httpMethod": "POST"
                },
                "list": {
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.list",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules",
                  "path": "v1alpha/{+parent}/eventEditRules",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lists EventEditRules on a web data stream.",
                  "httpMethod": "GET"
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.patch",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "httpMethod": "PATCH",
                  "description": "Updates an EventEditRule."
                },
                "reorder": {
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.reorder",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules:reorder",
                  "path": "v1alpha/{+parent}/eventEditRules:reorder",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Changes the processing order of event edit rules on the specified stream.",
                  "httpMethod": "POST"
                }
              }
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "httpMethod": "POST"
            },
            "delete": {
              "description": "Deletes a FirebaseLink on a property",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/firebaseLinks",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks"
            }
          }
        },
        "reportingDataAnnotations": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/reportingDataAnnotations",
              "id": "analyticsadmin.properties.reportingDataAnnotations.create",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations",
              "httpMethod": "POST",
              "description": "Creates a Reporting Data Annotation."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/reportingDataAnnotations",
              "id": "analyticsadmin.properties.reportingDataAnnotations.list",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations",
              "httpMethod": "GET",
              "description": "List all Reporting Data Annotations on a property."
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a Reporting Data Annotation.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.reportingDataAnnotations.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}"
            },
            "get": {
              "description": "Lookup a single Reporting Data Annotation.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.reportingDataAnnotations.get",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "description": "Deletes a Reporting Data Annotation.",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.reportingDataAnnotations.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}"
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "create": {
              "description": "Creates a ExpandedDataSet.",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.expandedDataSets.create",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+parent}/expandedDataSets",
              "description": "Lists ExpandedDataSets on a property.",
              "httpMethod": "GET"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.expandedDataSets.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "httpMethod": "PATCH",
              "description": "Updates a ExpandedDataSet on a property."
            },
            "delete": {
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a ExpandedDataSet on a property.",
              "httpMethod": "DELETE"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "httpMethod": "GET",
              "description": "Lookup for a single ExpandedDataSet."
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates a GoogleAdsLink.",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks"
            },
            "delete": {
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Deletes a GoogleAdsLink on a property",
              "httpMethod": "DELETE"
            },
            "patch": {
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Updates a GoogleAdsLink on a property",
              "httpMethod": "PATCH"
            },
            "list": {
              "description": "Lists GoogleAdsLinks on a property.",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "customDimensions": {
          "methods": {
            "archive": {
              "httpMethod": "POST",
              "description": "Archives a CustomDimension on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:archive",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive"
            },
            "get": {
              "id": "analyticsadmin.properties.customDimensions.get",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single CustomDimension.",
              "httpMethod": "GET"
            },
            "create": {
              "id": "analyticsadmin.properties.customDimensions.create",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/customDimensions",
              "description": "Creates a CustomDimension.",
              "httpMethod": "POST"
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a CustomDimension on a property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.patch",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}"
            },
            "list": {
              "httpMethod": "GET",
              "description": "Lists CustomDimensions on a property.",
              "path": "v1alpha/{+parent}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.list",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions"
            }
          }
        }
      }
    }
  },
  "canonicalName": "Google Analytics Admin",
  "batchPath": "batch",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "revision": "20260408",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "ownerName": "Google",
  "name": "analyticsadmin",
  "servicePath": "",
  "basePath": "",
  "id": "analyticsadmin:v1alpha",
  "kind": "discovery#restDescription",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "version_module": true,
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "protocol": "rest",
  "rootUrl": "https://analyticsadmin.googleapis.com/"
}