{
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "version": "v1alpha",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "basePath": "",
  "canonicalName": "Google Analytics Admin",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "ownerName": "Google",
  "name": "analyticsadmin",
  "id": "analyticsadmin:v1alpha",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "servicePath": "",
  "resources": {
    "accountSummaries": {
      "methods": {
        "list": {
          "flatPath": "v1alpha/accountSummaries",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "path": "v1alpha/accountSummaries",
          "id": "analyticsadmin.accountSummaries.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    },
    "properties": {
      "resources": {
        "reportingDataAnnotations": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.reportingDataAnnotations.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "List all Reporting Data Annotations on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations",
              "path": "v1alpha/{+parent}/reportingDataAnnotations"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.reportingDataAnnotations.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a Reporting Data Annotation.",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "id": "analyticsadmin.properties.reportingDataAnnotations.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "description": "Updates a Reporting Data Annotation."
            },
            "create": {
              "path": "v1alpha/{+parent}/reportingDataAnnotations",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations",
              "description": "Creates a Reporting Data Annotation.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.reportingDataAnnotations.create",
              "httpMethod": "POST"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.reportingDataAnnotations.get",
              "httpMethod": "GET",
              "description": "Lookup a single Reporting Data Annotation.",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "create": {
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "httpMethod": "POST"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "description": "Updates a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "httpMethod": "PATCH"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "description": "Deletes a GoogleAdsLink on a property",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "httpMethod": "DELETE"
            },
            "list": {
              "description": "Lists GoogleAdsLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "httpMethod": "GET"
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.bigQueryLinks.create",
              "httpMethod": "POST",
              "description": "Creates a BigQueryLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "path": "v1alpha/{+parent}/bigQueryLinks"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "description": "Lookup for a single BigQuery Link.",
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "description": "Updates a BigQueryLink.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.bigQueryLinks.patch",
              "httpMethod": "PATCH"
            },
            "list": {
              "description": "Lists BigQuery Links on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "id": "analyticsadmin.properties.bigQueryLinks.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "description": "Deletes a BigQueryLink on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.bigQueryLinks.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "conversionEvents": {
          "deprecated": true,
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true,
              "path": "v1alpha/{+name}",
              "description": "Deprecated: Use `DeleteKeyEvent` instead. Deletes a conversion event in a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "list": {
              "id": "analyticsadmin.properties.conversionEvents.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "deprecated": true,
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "description": "Deprecated: Use `ListKeyEvents` instead. Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "path": "v1alpha/{+parent}/conversionEvents"
            },
            "create": {
              "path": "v1alpha/{+parent}/conversionEvents",
              "description": "Deprecated: Use `CreateKeyEvent` instead. Creates a conversion event with the specified attributes.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true
            },
            "get": {
              "id": "analyticsadmin.properties.conversionEvents.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "deprecated": true,
              "path": "v1alpha/{+name}",
              "description": "Deprecated: Use `GetKeyEvent` instead. Retrieve a single conversion event.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "patch": {
              "description": "Deprecated: Use `UpdateKeyEvent` instead. Updates a conversion event with the specified attributes.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "httpMethod": "PATCH"
            }
          }
        },
        "accessBindings": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes an access binding on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.accessBindings.delete",
              "httpMethod": "DELETE"
            },
            "batchGet": {
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet",
              "description": "Gets information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "httpMethod": "GET"
            },
            "batchDelete": {
              "description": "Deletes information about multiple users' links to an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "create": {
              "id": "analyticsadmin.properties.accessBindings.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "description": "Creates an access binding on an account or property."
            },
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Gets information about an access binding.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.accessBindings.get",
              "httpMethod": "GET"
            },
            "batchCreate": {
              "id": "analyticsadmin.properties.accessBindings.batchCreate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.accessBindings.list",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/accessBindings",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "description": "Lists all access bindings on an account or property."
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.accessBindings.batchUpdate",
              "httpMethod": "POST"
            },
            "patch": {
              "id": "analyticsadmin.properties.accessBindings.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "description": "Updates an access binding on an account or property."
            }
          }
        },
        "channelGroups": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.channelGroups.patch",
              "httpMethod": "PATCH",
              "description": "Updates a ChannelGroup.",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "path": "v1alpha/{+name}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.channelGroups.get",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single ChannelGroup.",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}"
            },
            "create": {
              "path": "v1alpha/{+parent}/channelGroups",
              "description": "Creates a ChannelGroup.",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "id": "analyticsadmin.properties.channelGroups.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "description": "Lists ChannelGroups on a property.",
              "path": "v1alpha/{+parent}/channelGroups",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.channelGroups.list",
              "httpMethod": "GET"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.channelGroups.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a ChannelGroup on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "audiences": {
          "methods": {
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.audiences.get",
              "httpMethod": "GET"
            },
            "create": {
              "id": "analyticsadmin.properties.audiences.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+parent}/audiences",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "description": "Creates an Audience."
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.audiences.patch",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "description": "Updates an Audience on a property."
            },
            "archive": {
              "id": "analyticsadmin.properties.audiences.archive",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}:archive",
              "description": "Archives an Audience on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "path": "v1alpha/{+parent}/audiences",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.audiences.list",
              "httpMethod": "GET"
            }
          }
        },
        "adSenseLinks": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "description": "Deletes an AdSenseLink.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.adSenseLinks.delete",
              "httpMethod": "DELETE"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.adSenseLinks.list",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "description": "Lists AdSenseLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks"
            },
            "get": {
              "description": "Looks up a single AdSenseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.adSenseLinks.get",
              "httpMethod": "GET"
            },
            "create": {
              "id": "analyticsadmin.properties.adSenseLinks.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates an AdSenseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "path": "v1alpha/{+parent}/adSenseLinks"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "description": "Deletes a FirebaseLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "httpMethod": "DELETE"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "httpMethod": "GET",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "path": "v1alpha/{+parent}/firebaseLinks"
            },
            "create": {
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "path": "v1alpha/{+parent}/firebaseLinks"
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "httpMethod": "GET"
            },
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property."
            },
            "list": {
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/expandedDataSets",
              "description": "Lists ExpandedDataSets on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "description": "Deletes a ExpandedDataSet on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "description": "Lookup for a single ExpandedDataSet.",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "description": "Creates a ExpandedDataSet.",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.expandedDataSets.create",
              "httpMethod": "POST"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "description": "Updates a ExpandedDataSet on a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.expandedDataSets.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "dataStreams": {
          "methods": {
            "updateDataRedactionSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "description": "Updates a DataRedactionSettings on a property.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.updateDataRedactionSettings",
              "httpMethod": "PATCH"
            },
            "delete": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Deletes a DataStream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.delete",
              "httpMethod": "DELETE"
            },
            "updateEnhancedMeasurementSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings",
              "httpMethod": "PATCH"
            },
            "getDataRedactionSettings": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.getDataRedactionSettings",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single DataRedactionSettings.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings"
            },
            "create": {
              "path": "v1alpha/{+parent}/dataStreams",
              "description": "Creates a DataStream.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.create",
              "httpMethod": "POST"
            },
            "get": {
              "description": "Lookup for a single DataStream.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.get",
              "httpMethod": "GET"
            },
            "getEnhancedMeasurementSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings",
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings",
              "httpMethod": "GET"
            },
            "list": {
              "description": "Lists DataStreams on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "path": "v1alpha/{+parent}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "getGlobalSiteTag": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons."
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "description": "Updates a DataStream on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.patch",
              "httpMethod": "PATCH"
            }
          },
          "resources": {
            "sKAdNetworkConversionValueSchema": {
              "methods": {
                "patch": {
                  "path": "v1alpha/{+name}",
                  "description": "Updates a SKAdNetworkConversionValueSchema.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.patch",
                  "httpMethod": "PATCH"
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "description": "Looks up a single SKAdNetworkConversionValueSchema.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.get",
                  "httpMethod": "GET"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.create",
                  "httpMethod": "POST",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "description": "Creates a SKAdNetworkConversionValueSchema.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema"
                },
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "description": "Deletes target SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.delete",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.list",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "description": "Lists SKAdNetworkConversionValueSchema on a stream. Properties can have at most one SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema"
                }
              }
            },
            "measurementProtocolSecrets": {
              "methods": {
                "list": {
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "delete": {
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "get": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Lookup for a single MeasurementProtocolSecret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}"
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets"
                },
                "patch": {
                  "description": "Updates a measurement protocol secret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "httpMethod": "PATCH"
                }
              }
            },
            "eventCreateRules": {
              "methods": {
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1alpha/{+name}",
                  "description": "Updates an EventCreateRule.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "description": "Lookup for a single EventCreateRule.",
                  "path": "v1alpha/{+name}"
                },
                "create": {
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "description": "Creates an EventCreateRule.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create",
                  "httpMethod": "POST"
                },
                "list": {
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "description": "Lists EventCreateRules on a web data stream.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "description": "Deletes an EventCreateRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                }
              }
            },
            "eventEditRules": {
              "methods": {
                "patch": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "description": "Updates an EventEditRule.",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.patch",
                  "httpMethod": "PATCH"
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "description": "Lookup for a single EventEditRule.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.get",
                  "httpMethod": "GET"
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.create",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Creates an EventEditRule.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules",
                  "path": "v1alpha/{+parent}/eventEditRules"
                },
                "list": {
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules",
                  "description": "Lists EventEditRules on a web data stream.",
                  "path": "v1alpha/{+parent}/eventEditRules"
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "description": "Deletes an EventEditRule.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "reorder": {
                  "path": "v1alpha/{+parent}/eventEditRules:reorder",
                  "description": "Changes the processing order of event edit rules on the specified stream.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules:reorder",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.reorder",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                }
              }
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "description": "Lists all SearchAds360Links on a property."
            },
            "delete": {
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a SearchAds360Link on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "path": "v1alpha/{+name}"
            },
            "patch": {
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "description": "Updates a SearchAds360Link on a property."
            },
            "get": {
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Look up a single SearchAds360Link",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.searchAds360Links.create",
              "httpMethod": "POST",
              "description": "Creates a SearchAds360Link.",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "path": "v1alpha/{+parent}/searchAds360Links"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customMetrics.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "description": "Lists CustomMetrics on a property.",
              "path": "v1alpha/{+parent}/customMetrics"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.create",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/customMetrics",
              "description": "Creates a CustomMetric.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics"
            },
            "get": {
              "id": "analyticsadmin.properties.customMetrics.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single CustomMetric.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.patch",
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "description": "Updates a CustomMetric on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}"
            },
            "archive": {
              "description": "Archives a CustomMetric on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "path": "v1alpha/{+name}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.archive",
              "httpMethod": "POST"
            }
          }
        },
        "subpropertyEventFilters": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.subpropertyEventFilters.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a subproperty Event Filter.",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "path": "v1alpha/{+parent}/subpropertyEventFilters"
            },
            "get": {
              "description": "Lookup for a single subproperty Event Filter.",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.subpropertyEventFilters.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "description": "Updates a subproperty Event Filter.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.subpropertyEventFilters.patch",
              "httpMethod": "PATCH"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "description": "List all subproperty Event Filters on a property.",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.subpropertyEventFilters.list",
              "httpMethod": "GET"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.subpropertyEventFilters.delete",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "description": "Deletes a subproperty event filter."
            }
          }
        },
        "keyEvents": {
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.keyEvents.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Updates a Key Event.",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.keyEvents.create",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}/keyEvents",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents",
              "description": "Creates a Key Event."
            },
            "get": {
              "id": "analyticsadmin.properties.keyEvents.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "description": "Retrieve a single Key Event."
            },
            "delete": {
              "id": "analyticsadmin.properties.keyEvents.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a Key Event.",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.keyEvents.list",
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents",
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found.",
              "path": "v1alpha/{+parent}/keyEvents"
            }
          }
        },
        "subpropertySyncConfigs": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs/{subpropertySyncConfigsId}",
              "description": "Lookup for a single `SubpropertySyncConfig`.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.subpropertySyncConfigs.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs",
              "description": "List all `SubpropertySyncConfig` resources for a property.",
              "path": "v1alpha/{+parent}/subpropertySyncConfigs",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.subpropertySyncConfigs.list",
              "httpMethod": "GET"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs/{subpropertySyncConfigsId}",
              "description": "Updates a `SubpropertySyncConfig`.",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.subpropertySyncConfigs.patch",
              "httpMethod": "PATCH"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/customDimensions",
              "description": "Lists CustomDimensions on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.create",
              "httpMethod": "POST",
              "description": "Creates a CustomDimension.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "path": "v1alpha/{+parent}/customDimensions"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "description": "Lookup for a single CustomDimension.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.customDimensions.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "id": "analyticsadmin.properties.customDimensions.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1alpha/{+name}",
              "description": "Updates a CustomDimension on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}"
            },
            "archive": {
              "id": "analyticsadmin.properties.customDimensions.archive",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Archives a CustomDimension on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "path": "v1alpha/{+name}:archive"
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal."
            },
            "create": {
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "cancel": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel",
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "path": "v1alpha/{+name}:cancel"
            },
            "list": {
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list",
              "httpMethod": "GET"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "approve": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "path": "v1alpha/{+name}:approve",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "rollupPropertySourceLinks": {
          "methods": {
            "list": {
              "description": "Lists roll-up property source Links on a property. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.delete",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "description": "Deletes a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}"
            },
            "get": {
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single roll-up property source Link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}"
            },
            "create": {
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "description": "Creates a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.create",
              "httpMethod": "POST"
            }
          }
        },
        "calculatedMetrics": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.calculatedMetrics.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "description": "Lookup for a single CalculatedMetric.",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "description": "Creates a CalculatedMetric.",
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.calculatedMetrics.create",
              "httpMethod": "POST"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "description": "Updates a CalculatedMetric on a property.",
              "id": "analyticsadmin.properties.calculatedMetrics.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Lists CalculatedMetrics on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.calculatedMetrics.list",
              "httpMethod": "GET"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.calculatedMetrics.delete",
              "httpMethod": "DELETE",
              "path": "v1alpha/{+name}",
              "description": "Deletes a CalculatedMetric on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}"
            }
          }
        }
      },
      "methods": {
        "updateDataRetentionSettings": {
          "path": "v1alpha/{+name}",
          "description": "Updates the singleton data retention settings for this property.",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "httpMethod": "PATCH"
        },
        "updateAttributionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "description": "Updates attribution settings on a property.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "httpMethod": "PATCH"
        },
        "getDataRetentionSettings": {
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Returns the singleton data retention settings for this property.",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "path": "v1alpha/{+name}"
        },
        "getGoogleSignalsSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "description": "Lookup for Google Signals settings for a property.",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.delete",
          "httpMethod": "DELETE",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "path": "v1alpha/{+name}"
        },
        "createRollupProperty": {
          "id": "analyticsadmin.properties.createRollupProperty",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties:createRollupProperty",
          "description": "Create a roll-up property and all roll-up property source links.",
          "path": "v1alpha/properties:createRollupProperty"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.get",
          "httpMethod": "GET",
          "path": "v1alpha/{+name}",
          "description": "Lookup for a single GA Property.",
          "flatPath": "v1alpha/properties/{propertiesId}"
        },
        "provisionSubproperty": {
          "path": "v1alpha/properties:provisionSubproperty",
          "description": "Create a subproperty and a subproperty event filter that applies to the created subproperty.",
          "flatPath": "v1alpha/properties:provisionSubproperty",
          "id": "analyticsadmin.properties.provisionSubproperty",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "submitUserDeletion": {
          "description": "Submits a request for user deletion for a property.",
          "flatPath": "v1alpha/properties/{propertiesId}:submitUserDeletion",
          "path": "v1alpha/{+name}:submitUserDeletion",
          "id": "analyticsadmin.properties.submitUserDeletion",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "acknowledgeUserDataCollection": {
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "httpMethod": "POST"
        },
        "list": {
          "id": "analyticsadmin.properties.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/properties",
          "flatPath": "v1alpha/properties",
          "description": "Returns child Properties under the specified parent Account. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.patch",
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Updates a property."
        },
        "runAccessReport": {
          "path": "v1alpha/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "id": "analyticsadmin.properties.runAccessReport",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "create": {
          "description": "Creates a Google Analytics property with the specified location and attributes.",
          "flatPath": "v1alpha/properties",
          "path": "v1alpha/properties",
          "id": "analyticsadmin.properties.create",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "updateGoogleSignalsSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "description": "Updates Google Signals settings for a property."
        },
        "getAttributionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "description": "Lookup for a AttributionSettings singleton.",
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.getAttributionSettings",
          "httpMethod": "GET"
        },
        "getUserProvidedDataSettings": {
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/properties/{propertiesId}/userProvidedDataSettings",
          "description": "Looks up settings related to user-provided data for a property.",
          "id": "analyticsadmin.properties.getUserProvidedDataSettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "getReportingIdentitySettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.getReportingIdentitySettings",
          "httpMethod": "GET",
          "description": "Returns the reporting identity settings for this property.",
          "flatPath": "v1alpha/properties/{propertiesId}/reportingIdentitySettings",
          "path": "v1alpha/{+name}"
        }
      }
    },
    "accounts": {
      "resources": {
        "accessBindings": {
          "methods": {
            "batchUpdate": {
              "description": "Updates information about multiple access bindings to an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "httpMethod": "POST"
            },
            "list": {
              "id": "analyticsadmin.accounts.accessBindings.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists all access bindings on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "path": "v1alpha/{+parent}/accessBindings"
            },
            "patch": {
              "description": "Updates an access binding on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.accessBindings.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "batchGet": {
              "id": "analyticsadmin.accounts.accessBindings.batchGet",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet",
              "description": "Gets information about multiple access bindings to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchGet"
            },
            "delete": {
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "description": "Deletes an access binding on an account or property.",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "description": "Creates an access binding on an account or property.",
              "path": "v1alpha/{+parent}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.accounts.accessBindings.create",
              "httpMethod": "POST"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Gets information about an access binding.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.accounts.accessBindings.get",
              "httpMethod": "GET"
            },
            "batchCreate": {
              "id": "analyticsadmin.accounts.accessBindings.batchCreate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created."
            },
            "batchDelete": {
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "id": "analyticsadmin.accounts.accessBindings.batchDelete",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            }
          }
        }
      },
      "methods": {
        "provisionAccountTicket": {
          "path": "v1alpha/accounts:provisionAccountTicket",
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "httpMethod": "POST"
        },
        "get": {
          "id": "analyticsadmin.accounts.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Lookup for a single Account."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.patch",
          "httpMethod": "PATCH",
          "path": "v1alpha/{+name}",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Updates an account."
        },
        "runAccessReport": {
          "path": "v1alpha/{+entity}:runAccessReport",
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "id": "analyticsadmin.accounts.runAccessReport",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "list": {
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "flatPath": "v1alpha/accounts",
          "path": "v1alpha/accounts",
          "id": "analyticsadmin.accounts.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.delete",
          "httpMethod": "DELETE",
          "path": "v1alpha/{+name}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "flatPath": "v1alpha/accounts/{accountsId}"
        },
        "getDataSharingSettings": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "httpMethod": "GET",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings",
          "path": "v1alpha/{+name}"
        },
        "searchChangeHistoryEvents": {
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters. Only returns the subset of changes supported by the API. The UI may return additional changes.",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents"
        }
      }
    }
  },
  "version_module": true,
  "protocol": "rest",
  "title": "Google Analytics Admin API",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "ownerDomain": "google.com",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "revision": "20260420"
}