{
  "revision": "20260415",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "fullyEncodeReservedExpansion": true,
  "title": "Google Analytics Admin API",
  "version_module": true,
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "version": "v1beta",
  "resources": {
    "accounts": {
      "methods": {
        "list": {
          "flatPath": "v1beta/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.list",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "httpMethod": "GET",
          "path": "v1beta/accounts"
        },
        "getDataSharingSettings": {
          "flatPath": "v1beta/accounts/{accountsId}/dataSharingSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "httpMethod": "GET",
          "path": "v1beta/{+name}"
        },
        "get": {
          "httpMethod": "GET",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single Account.",
          "id": "analyticsadmin.accounts.get"
        },
        "delete": {
          "id": "analyticsadmin.accounts.delete",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "flatPath": "v1beta/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+name}",
          "httpMethod": "DELETE"
        },
        "patch": {
          "path": "v1beta/{+name}",
          "httpMethod": "PATCH",
          "description": "Updates an account.",
          "id": "analyticsadmin.accounts.patch",
          "flatPath": "v1beta/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "provisionAccountTicket": {
          "path": "v1beta/accounts:provisionAccountTicket",
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "flatPath": "v1beta/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "searchChangeHistoryEvents": {
          "path": "v1beta/{+account}:searchChangeHistoryEvents",
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters. Only returns the subset of changes supported by the API. The UI may return additional changes.",
          "flatPath": "v1beta/accounts/{accountsId}:searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "runAccessReport": {
          "flatPath": "v1beta/accounts/{accountsId}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "httpMethod": "POST",
          "path": "v1beta/{+entity}:runAccessReport"
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "description": "Returns summaries of all accounts accessible by the caller.",
          "id": "analyticsadmin.accountSummaries.list",
          "flatPath": "v1beta/accountSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/accountSummaries",
          "httpMethod": "GET"
        }
      }
    },
    "properties": {
      "methods": {
        "create": {
          "path": "v1beta/properties",
          "httpMethod": "POST",
          "description": "Creates a Google Analytics property with the specified location and attributes.",
          "id": "analyticsadmin.properties.create",
          "flatPath": "v1beta/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.patch",
          "description": "Updates a property."
        },
        "list": {
          "description": "Returns child Properties under the specified parent Account. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "id": "analyticsadmin.properties.list",
          "flatPath": "v1beta/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/properties",
          "httpMethod": "GET"
        },
        "delete": {
          "flatPath": "v1beta/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "id": "analyticsadmin.properties.delete",
          "httpMethod": "DELETE",
          "path": "v1beta/{+name}"
        },
        "acknowledgeUserDataCollection": {
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "flatPath": "v1beta/properties/{propertiesId}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+property}:acknowledgeUserDataCollection",
          "httpMethod": "POST"
        },
        "updateDataRetentionSettings": {
          "httpMethod": "PATCH",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates the singleton data retention settings for this property.",
          "id": "analyticsadmin.properties.updateDataRetentionSettings"
        },
        "runAccessReport": {
          "path": "v1beta/{+entity}:runAccessReport",
          "httpMethod": "POST",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "id": "analyticsadmin.properties.runAccessReport",
          "flatPath": "v1beta/properties/{propertiesId}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "getDataRetentionSettings": {
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/{+name}",
          "httpMethod": "GET"
        },
        "get": {
          "description": "Lookup for a single GA Property.",
          "id": "analyticsadmin.properties.get",
          "flatPath": "v1beta/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/{+name}",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "conversionEvents": {
          "deprecated": true,
          "methods": {
            "get": {
              "path": "v1beta/{+name}",
              "httpMethod": "GET",
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.get",
              "description": "Deprecated: Use `GetKeyEvent` instead. Retrieve a single conversion event.",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "deprecated": true,
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "description": "Deprecated: Use `DeleteKeyEvent` instead. Deletes a conversion event in a property."
            },
            "list": {
              "id": "analyticsadmin.properties.conversionEvents.list",
              "description": "Deprecated: Use `ListKeyEvents` instead. Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+parent}/conversionEvents",
              "httpMethod": "GET",
              "deprecated": true
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.create",
              "description": "Deprecated: Use `CreateKeyEvent` instead. Creates a conversion event with the specified attributes.",
              "httpMethod": "POST",
              "deprecated": true,
              "path": "v1beta/{+parent}/conversionEvents"
            },
            "patch": {
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deprecated: Use `UpdateKeyEvent` instead. Updates a conversion event with the specified attributes.",
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "httpMethod": "PATCH",
              "deprecated": true,
              "path": "v1beta/{+name}"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "create": {
              "id": "analyticsadmin.properties.customDimensions.create",
              "description": "Creates a CustomDimension.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/customDimensions",
              "httpMethod": "POST"
            },
            "patch": {
              "description": "Updates a CustomDimension on a property.",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH"
            },
            "list": {
              "path": "v1beta/{+parent}/customDimensions",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customDimensions.list",
              "description": "Lists CustomDimensions on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "archive": {
              "path": "v1beta/{+name}:archive",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "description": "Archives a CustomDimension on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.get",
              "description": "Lookup for a single CustomDimension.",
              "httpMethod": "GET",
              "path": "v1beta/{+name}"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "list": {
              "description": "Lists CustomMetrics on a property.",
              "id": "analyticsadmin.properties.customMetrics.list",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "path": "v1beta/{+parent}/customMetrics",
              "httpMethod": "GET"
            },
            "archive": {
              "httpMethod": "POST",
              "path": "v1beta/{+name}:archive",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.archive",
              "description": "Archives a CustomMetric on a property."
            },
            "get": {
              "httpMethod": "GET",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single CustomMetric.",
              "id": "analyticsadmin.properties.customMetrics.get"
            },
            "create": {
              "id": "analyticsadmin.properties.customMetrics.create",
              "description": "Creates a CustomMetric.",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/customMetrics",
              "httpMethod": "POST"
            },
            "patch": {
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.patch",
              "description": "Updates a CustomMetric on a property.",
              "httpMethod": "PATCH",
              "path": "v1beta/{+name}"
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "delete": {
              "description": "Deletes a GoogleAdsLink on a property",
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "httpMethod": "DELETE"
            },
            "list": {
              "path": "v1beta/{+parent}/googleAdsLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "description": "Lists GoogleAdsLinks on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "path": "v1beta/{+parent}/googleAdsLinks",
              "httpMethod": "POST",
              "description": "Creates a GoogleAdsLink.",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a GoogleAdsLink on a property",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "httpMethod": "PATCH",
              "path": "v1beta/{+name}"
            }
          }
        },
        "keyEvents": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.keyEvents.delete",
              "description": "Deletes a Key Event.",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "httpMethod": "DELETE"
            },
            "get": {
              "httpMethod": "GET",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Retrieve a single Key Event.",
              "id": "analyticsadmin.properties.keyEvents.get"
            },
            "list": {
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found.",
              "id": "analyticsadmin.properties.keyEvents.list",
              "httpMethod": "GET",
              "path": "v1beta/{+parent}/keyEvents"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/keyEvents",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.keyEvents.create",
              "description": "Creates a Key Event."
            },
            "patch": {
              "description": "Updates a Key Event.",
              "id": "analyticsadmin.properties.keyEvents.patch",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "path": "v1beta/{+name}",
              "httpMethod": "DELETE",
              "description": "Deletes a FirebaseLink on a property",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1beta/{+parent}/firebaseLinks",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink."
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/firebaseLinks"
            }
          }
        },
        "dataStreams": {
          "methods": {
            "create": {
              "path": "v1beta/{+parent}/dataStreams",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.dataStreams.create",
              "description": "Creates a DataStream.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "id": "analyticsadmin.properties.dataStreams.patch",
              "description": "Updates a DataStream on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1beta/{+parent}/dataStreams",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists DataStreams on a property.",
              "id": "analyticsadmin.properties.dataStreams.list"
            },
            "get": {
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.get",
              "description": "Lookup for a single DataStream.",
              "httpMethod": "GET",
              "path": "v1beta/{+name}"
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.delete",
              "description": "Deletes a DataStream on a property."
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "create": {
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Creates a measurement protocol secret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "httpMethod": "POST",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets"
                },
                "patch": {
                  "description": "Updates a measurement protocol secret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1beta/{+name}",
                  "httpMethod": "PATCH"
                },
                "list": {
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "httpMethod": "GET",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets"
                },
                "get": {
                  "httpMethod": "GET",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "description": "Lookup for a single MeasurementProtocolSecret."
                },
                "delete": {
                  "path": "v1beta/{+name}",
                  "httpMethod": "DELETE",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "name": "analyticsadmin",
  "protocol": "rest",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "ownerName": "Google",
  "canonicalName": "Google Analytics Admin",
  "basePath": "",
  "id": "analyticsadmin:v1beta",
  "ownerDomain": "google.com",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html"
}