{
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "version_module": true,
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "id": "analyticsadmin:v1alpha",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        }
      }
    }
  },
  "revision": "20260415",
  "title": "Google Analytics Admin API",
  "ownerName": "Google",
  "version": "v1alpha",
  "servicePath": "",
  "canonicalName": "Google Analytics Admin",
  "batchPath": "batch",
  "resources": {
    "accountSummaries": {
      "methods": {
        "list": {
          "flatPath": "v1alpha/accountSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "analyticsadmin.accountSummaries.list",
          "path": "v1alpha/accountSummaries",
          "description": "Returns summaries of all accounts accessible by the caller."
        }
      }
    },
    "accounts": {
      "resources": {
        "accessBindings": {
          "methods": {
            "batchGet": {
              "path": "v1alpha/{+parent}/accessBindings:batchGet",
              "description": "Gets information about multiple access bindings to an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.batchGet",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchGet"
            },
            "batchUpdate": {
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchUpdate"
            },
            "list": {
              "path": "v1alpha/{+parent}/accessBindings",
              "description": "Lists all access bindings on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings"
            },
            "delete": {
              "description": "Deletes an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.accounts.accessBindings.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}"
            },
            "batchCreate": {
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created.",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "id": "analyticsadmin.accounts.accessBindings.batchCreate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchCreate"
            },
            "batchDelete": {
              "id": "analyticsadmin.accounts.accessBindings.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings:batchDelete",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "create": {
              "id": "analyticsadmin.accounts.accessBindings.create",
              "path": "v1alpha/{+parent}/accessBindings",
              "description": "Creates an access binding on an account or property.",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "description": "Updates an access binding on an account or property.",
              "id": "analyticsadmin.accounts.accessBindings.patch"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/accounts/{accountsId}/accessBindings/{accessBindingsId}",
              "path": "v1alpha/{+name}",
              "description": "Gets information about an access binding.",
              "id": "analyticsadmin.accounts.accessBindings.get"
            }
          }
        }
      },
      "methods": {
        "getDataSharingSettings": {
          "path": "v1alpha/{+name}",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts/{accountsId}/dataSharingSettings"
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/accounts/{accountsId}",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.accounts.delete"
        },
        "provisionAccountTicket": {
          "flatPath": "v1alpha/accounts:provisionAccountTicket",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "description": "Requests a ticket for creating an account.",
          "path": "v1alpha/accounts:provisionAccountTicket"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts/{accountsId}",
          "path": "v1alpha/{+name}",
          "description": "Lookup for a single Account.",
          "id": "analyticsadmin.accounts.get"
        },
        "list": {
          "path": "v1alpha/accounts",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "id": "analyticsadmin.accounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1alpha/accounts"
        },
        "patch": {
          "flatPath": "v1alpha/accounts/{accountsId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.patch",
          "description": "Updates an account.",
          "path": "v1alpha/{+name}"
        },
        "searchChangeHistoryEvents": {
          "flatPath": "v1alpha/accounts/{accountsId}:searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "path": "v1alpha/{+account}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters. Only returns the subset of changes supported by the API. The UI may return additional changes."
        },
        "runAccessReport": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "POST",
          "flatPath": "v1alpha/accounts/{accountsId}:runAccessReport",
          "path": "v1alpha/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "id": "analyticsadmin.accounts.runAccessReport"
        }
      }
    },
    "properties": {
      "resources": {
        "customMetrics": {
          "methods": {
            "archive": {
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.customMetrics.archive",
              "path": "v1alpha/{+name}:archive",
              "description": "Archives a CustomMetric on a property."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics",
              "path": "v1alpha/{+parent}/customMetrics",
              "description": "Creates a CustomMetric.",
              "id": "analyticsadmin.properties.customMetrics.create"
            },
            "patch": {
              "description": "Updates a CustomMetric on a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}"
            },
            "list": {
              "description": "Lists CustomMetrics on a property.",
              "path": "v1alpha/{+parent}/customMetrics",
              "id": "analyticsadmin.properties.customMetrics.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single CustomMetric.",
              "id": "analyticsadmin.properties.customMetrics.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/customMetrics/{customMetricsId}"
            }
          }
        },
        "accessBindings": {
          "methods": {
            "batchDelete": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchDelete",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analyticsadmin.properties.accessBindings.batchDelete",
              "description": "Deletes information about multiple users' links to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchDelete"
            },
            "batchCreate": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchCreate",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.accessBindings.batchCreate",
              "path": "v1alpha/{+parent}/accessBindings:batchCreate",
              "description": "Creates information about multiple access bindings to an account or property. This method is transactional. If any AccessBinding cannot be created, none of the AccessBindings will be created."
            },
            "get": {
              "id": "analyticsadmin.properties.accessBindings.get",
              "description": "Gets information about an access binding.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "create": {
              "description": "Creates an access binding on an account or property.",
              "path": "v1alpha/{+parent}/accessBindings",
              "id": "analyticsadmin.properties.accessBindings.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings"
            },
            "patch": {
              "id": "analyticsadmin.properties.accessBindings.patch",
              "path": "v1alpha/{+name}",
              "description": "Updates an access binding on an account or property.",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "httpMethod": "PATCH"
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings/{accessBindingsId}",
              "description": "Deletes an access binding on an account or property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.accessBindings.delete"
            },
            "batchGet": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchGet",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.accessBindings.batchGet",
              "description": "Gets information about multiple access bindings to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchGet"
            },
            "batchUpdate": {
              "id": "analyticsadmin.properties.accessBindings.batchUpdate",
              "description": "Updates information about multiple access bindings to an account or property.",
              "path": "v1alpha/{+parent}/accessBindings:batchUpdate",
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings:batchUpdate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/accessBindings",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analyticsadmin.properties.accessBindings.list",
              "description": "Lists all access bindings on an account or property.",
              "path": "v1alpha/{+parent}/accessBindings"
            }
          }
        },
        "channelGroups": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single ChannelGroup.",
              "id": "analyticsadmin.properties.channelGroups.get"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.channelGroups.list",
              "path": "v1alpha/{+parent}/channelGroups",
              "description": "Lists ChannelGroups on a property."
            },
            "create": {
              "id": "analyticsadmin.properties.channelGroups.create",
              "path": "v1alpha/{+parent}/channelGroups",
              "description": "Creates a ChannelGroup.",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "patch": {
              "id": "analyticsadmin.properties.channelGroups.patch",
              "description": "Updates a ChannelGroup.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/channelGroups/{channelGroupsId}",
              "description": "Deletes a ChannelGroup on a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.channelGroups.delete"
            }
          }
        },
        "subpropertyEventFilters": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "description": "Deletes a subproperty event filter.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.subpropertyEventFilters.delete"
            },
            "create": {
              "id": "analyticsadmin.properties.subpropertyEventFilters.create",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "description": "Creates a subproperty Event Filter.",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.subpropertyEventFilters.patch",
              "description": "Updates a subproperty Event Filter.",
              "path": "v1alpha/{+name}"
            },
            "get": {
              "id": "analyticsadmin.properties.subpropertyEventFilters.get",
              "description": "Lookup for a single subproperty Event Filter.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters/{subpropertyEventFiltersId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertyEventFilters",
              "description": "List all subproperty Event Filters on a property.",
              "path": "v1alpha/{+parent}/subpropertyEventFilters",
              "id": "analyticsadmin.properties.subpropertyEventFilters.list"
            }
          }
        },
        "displayVideo360AdvertiserLinks": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.get",
              "path": "v1alpha/{+name}",
              "description": "Look up a single DisplayVideo360AdvertiserLink",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "list": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.list",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "description": "Lists all DisplayVideo360AdvertiserLinks on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.create",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinks",
              "description": "Creates a DisplayVideo360AdvertiserLink. This can only be utilized by users who have proper authorization both on the Google Analytics property and on the Display & Video 360 advertiser. Users who do not have access to the Display & Video 360 advertiser should instead seek to create a DisplayVideo360LinkProposal.",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.patch",
              "path": "v1alpha/{+name}",
              "description": "Updates a DisplayVideo360AdvertiserLink on a property."
            },
            "delete": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinks.delete",
              "description": "Deletes a DisplayVideo360AdvertiserLink on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinks/{displayVideo360AdvertiserLinksId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "bigQueryLinks": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.bigQueryLinks.get",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single BigQuery Link.",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET"
            },
            "list": {
              "id": "analyticsadmin.properties.bigQueryLinks.list",
              "description": "Lists BigQuery Links on a property.",
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.bigQueryLinks.create",
              "path": "v1alpha/{+parent}/bigQueryLinks",
              "description": "Creates a BigQueryLink."
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.bigQueryLinks.patch",
              "description": "Updates a BigQueryLink.",
              "path": "v1alpha/{+name}"
            },
            "delete": {
              "id": "analyticsadmin.properties.bigQueryLinks.delete",
              "path": "v1alpha/{+name}",
              "description": "Deletes a BigQueryLink on a property.",
              "flatPath": "v1alpha/properties/{propertiesId}/bigQueryLinks/{bigQueryLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE"
            }
          }
        },
        "adSenseLinks": {
          "methods": {
            "get": {
              "description": "Looks up a single AdSenseLink.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.adSenseLinks.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}"
            },
            "list": {
              "description": "Lists AdSenseLinks on a property.",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "id": "analyticsadmin.properties.adSenseLinks.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks",
              "path": "v1alpha/{+parent}/adSenseLinks",
              "description": "Creates an AdSenseLink.",
              "id": "analyticsadmin.properties.adSenseLinks.create"
            },
            "delete": {
              "id": "analyticsadmin.properties.adSenseLinks.delete",
              "path": "v1alpha/{+name}",
              "description": "Deletes an AdSenseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/adSenseLinks/{adSenseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE"
            }
          }
        },
        "searchAds360Links": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deletes a SearchAds360Link on a property.",
              "id": "analyticsadmin.properties.searchAds360Links.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}"
            },
            "get": {
              "path": "v1alpha/{+name}",
              "description": "Look up a single SearchAds360Link",
              "id": "analyticsadmin.properties.searchAds360Links.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.searchAds360Links.list",
              "description": "Lists all SearchAds360Links on a property.",
              "path": "v1alpha/{+parent}/searchAds360Links"
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links",
              "description": "Creates a SearchAds360Link.",
              "path": "v1alpha/{+parent}/searchAds360Links",
              "id": "analyticsadmin.properties.searchAds360Links.create"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "description": "Updates a SearchAds360Link on a property.",
              "id": "analyticsadmin.properties.searchAds360Links.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/searchAds360Links/{searchAds360LinksId}"
            }
          }
        },
        "calculatedMetrics": {
          "methods": {
            "get": {
              "description": "Lookup for a single CalculatedMetric.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.calculatedMetrics.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}"
            },
            "list": {
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "description": "Lists CalculatedMetrics on a property.",
              "id": "analyticsadmin.properties.calculatedMetrics.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics"
            },
            "create": {
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.calculatedMetrics.create",
              "path": "v1alpha/{+parent}/calculatedMetrics",
              "description": "Creates a CalculatedMetric."
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.calculatedMetrics.patch",
              "path": "v1alpha/{+name}",
              "description": "Updates a CalculatedMetric on a property."
            },
            "delete": {
              "id": "analyticsadmin.properties.calculatedMetrics.delete",
              "description": "Deletes a CalculatedMetric on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/calculatedMetrics/{calculatedMetricsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks",
              "path": "v1alpha/{+parent}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "id": "analyticsadmin.properties.googleAdsLinks.create"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "description": "Updates a GoogleAdsLink on a property",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}"
            },
            "delete": {
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "path": "v1alpha/{+name}",
              "description": "Deletes a GoogleAdsLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE"
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "list": {
              "path": "v1alpha/{+parent}/firebaseLinks",
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks"
            },
            "create": {
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "path": "v1alpha/{+parent}/firebaseLinks",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "delete": {
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "path": "v1alpha/{+name}",
              "description": "Deletes a FirebaseLink on a property",
              "flatPath": "v1alpha/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE"
            }
          }
        },
        "dataStreams": {
          "resources": {
            "eventCreateRules": {
              "methods": {
                "get": {
                  "description": "Lookup for a single EventCreateRule.",
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}"
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "description": "Lists EventCreateRules on a web data stream.",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.list"
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules",
                  "description": "Creates an EventCreateRule.",
                  "path": "v1alpha/{+parent}/eventCreateRules",
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.create"
                },
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.patch",
                  "description": "Updates an EventCreateRule.",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventCreateRules/{eventCreateRulesId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventCreateRules.delete",
                  "description": "Deletes an EventCreateRule.",
                  "path": "v1alpha/{+name}"
                }
              }
            },
            "eventEditRules": {
              "methods": {
                "delete": {
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "description": "Deletes an EventEditRule.",
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.delete"
                },
                "get": {
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.get",
                  "path": "v1alpha/{+name}",
                  "description": "Lookup for a single EventEditRule.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "httpMethod": "GET"
                },
                "list": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.list",
                  "description": "Lists EventEditRules on a web data stream.",
                  "path": "v1alpha/{+parent}/eventEditRules"
                },
                "reorder": {
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.reorder",
                  "description": "Changes the processing order of event edit rules on the specified stream.",
                  "path": "v1alpha/{+parent}/eventEditRules:reorder",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules:reorder",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules",
                  "path": "v1alpha/{+parent}/eventEditRules",
                  "description": "Creates an EventEditRule.",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.create"
                },
                "patch": {
                  "description": "Updates an EventEditRule.",
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.eventEditRules.patch",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/eventEditRules/{eventEditRulesId}"
                }
              }
            },
            "sKAdNetworkConversionValueSchema": {
              "methods": {
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "path": "v1alpha/{+name}",
                  "description": "Deletes target SKAdNetworkConversionValueSchema.",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.delete"
                },
                "create": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "POST",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.create",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "description": "Creates a SKAdNetworkConversionValueSchema."
                },
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.patch",
                  "description": "Updates a SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                },
                "get": {
                  "description": "Looks up a single SKAdNetworkConversionValueSchema.",
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema/{sKAdNetworkConversionValueSchemaId}"
                },
                "list": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/sKAdNetworkConversionValueSchema",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.sKAdNetworkConversionValueSchema.list",
                  "path": "v1alpha/{+parent}/sKAdNetworkConversionValueSchema",
                  "description": "Lists SKAdNetworkConversionValueSchema on a stream. Properties can have at most one SKAdNetworkConversionValueSchema."
                }
              }
            },
            "measurementProtocolSecrets": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "path": "v1alpha/{+name}",
                  "description": "Lookup for a single MeasurementProtocolSecret.",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get"
                },
                "list": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "httpMethod": "GET"
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "path": "v1alpha/{+parent}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret.",
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "POST"
                },
                "patch": {
                  "description": "Updates a measurement protocol secret.",
                  "path": "v1alpha/{+name}",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                },
                "delete": {
                  "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "httpMethod": "DELETE",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "path": "v1alpha/{+name}",
                  "description": "Deletes target MeasurementProtocolSecret."
                }
              }
            }
          },
          "methods": {
            "updateEnhancedMeasurementSettings": {
              "description": "Updates the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.updateEnhancedMeasurementSettings",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.list",
              "description": "Lists DataStreams on a property.",
              "path": "v1alpha/{+parent}/dataStreams"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes a DataStream on a property.",
              "id": "analyticsadmin.properties.dataStreams.delete"
            },
            "updateDataRedactionSettings": {
              "description": "Updates a DataRedactionSettings on a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.updateDataRedactionSettings",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings"
            },
            "getGlobalSiteTag": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/globalSiteTag",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.getGlobalSiteTag",
              "description": "Returns the Site Tag for the specified web stream. Site Tags are immutable singletons.",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams",
              "path": "v1alpha/{+parent}/dataStreams",
              "description": "Creates a DataStream.",
              "id": "analyticsadmin.properties.dataStreams.create"
            },
            "patch": {
              "path": "v1alpha/{+name}",
              "description": "Updates a DataStream on a property.",
              "id": "analyticsadmin.properties.dataStreams.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}"
            },
            "getEnhancedMeasurementSettings": {
              "path": "v1alpha/{+name}",
              "description": "Returns the enhanced measurement settings for this data stream. Note that the stream must enable enhanced measurement for these settings to take effect.",
              "id": "analyticsadmin.properties.dataStreams.getEnhancedMeasurementSettings",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/enhancedMeasurementSettings"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Lookup for a single DataStream.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.dataStreams.get"
            },
            "getDataRedactionSettings": {
              "flatPath": "v1alpha/properties/{propertiesId}/dataStreams/{dataStreamsId}/dataRedactionSettings",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.getDataRedactionSettings",
              "description": "Lookup for a single DataRedactionSettings.",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "audiences": {
          "methods": {
            "archive": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}:archive",
              "description": "Archives an Audience on a property.",
              "path": "v1alpha/{+name}:archive",
              "id": "analyticsadmin.properties.audiences.archive"
            },
            "create": {
              "path": "v1alpha/{+parent}/audiences",
              "description": "Creates an Audience.",
              "id": "analyticsadmin.properties.audiences.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences"
            },
            "patch": {
              "id": "analyticsadmin.properties.audiences.patch",
              "description": "Updates an Audience on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/audiences/{audiencesId}",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single Audience. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "id": "analyticsadmin.properties.audiences.get"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/audiences",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.audiences.list",
              "description": "Lists Audiences on a property. Audiences created before 2020 may not be supported. Default audiences will not show filter definitions.",
              "path": "v1alpha/{+parent}/audiences"
            }
          }
        },
        "expandedDataSets": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.expandedDataSets.get",
              "description": "Lookup for a single ExpandedDataSet.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "description": "Lists ExpandedDataSets on a property.",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "id": "analyticsadmin.properties.expandedDataSets.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets"
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets",
              "description": "Creates a ExpandedDataSet.",
              "path": "v1alpha/{+parent}/expandedDataSets",
              "id": "analyticsadmin.properties.expandedDataSets.create"
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "description": "Updates a ExpandedDataSet on a property.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.expandedDataSets.patch"
            },
            "delete": {
              "flatPath": "v1alpha/properties/{propertiesId}/expandedDataSets/{expandedDataSetsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.expandedDataSets.delete",
              "description": "Deletes a ExpandedDataSet on a property.",
              "path": "v1alpha/{+name}"
            }
          }
        },
        "customDimensions": {
          "methods": {
            "archive": {
              "description": "Archives a CustomDimension on a property.",
              "path": "v1alpha/{+name}:archive",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customDimensions.list",
              "path": "v1alpha/{+parent}/customDimensions",
              "description": "Lists CustomDimensions on a property."
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customDimensions.get",
              "description": "Lookup for a single CustomDimension.",
              "path": "v1alpha/{+name}"
            },
            "create": {
              "description": "Creates a CustomDimension.",
              "path": "v1alpha/{+parent}/customDimensions",
              "id": "analyticsadmin.properties.customDimensions.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions"
            },
            "patch": {
              "id": "analyticsadmin.properties.customDimensions.patch",
              "description": "Updates a CustomDimension on a property.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "rollupPropertySourceLinks": {
          "methods": {
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.get",
              "description": "Lookup for a single roll-up property source Link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.list",
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "description": "Lists roll-up property source Links on a property. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties."
            },
            "create": {
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.create",
              "path": "v1alpha/{+parent}/rollupPropertySourceLinks",
              "description": "Creates a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/rollupPropertySourceLinks/{rollupPropertySourceLinksId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes a roll-up property source link. Only roll-up properties can have source links, so this method will throw an error if used on other types of properties.",
              "id": "analyticsadmin.properties.rollupPropertySourceLinks.delete"
            }
          }
        },
        "keyEvents": {
          "methods": {
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "path": "v1alpha/{+name}",
              "description": "Deletes a Key Event.",
              "id": "analyticsadmin.properties.keyEvents.delete"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.keyEvents.get",
              "description": "Retrieve a single Key Event.",
              "path": "v1alpha/{+name}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents",
              "path": "v1alpha/{+parent}/keyEvents",
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found.",
              "id": "analyticsadmin.properties.keyEvents.list"
            },
            "create": {
              "path": "v1alpha/{+parent}/keyEvents",
              "description": "Creates a Key Event.",
              "id": "analyticsadmin.properties.keyEvents.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents"
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "description": "Updates a Key Event.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.keyEvents.patch"
            }
          }
        },
        "displayVideo360AdvertiserLinkProposals": {
          "methods": {
            "delete": {
              "description": "Deletes a DisplayVideo360AdvertiserLinkProposal on a property. This can only be used on cancelled proposals.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}"
            },
            "approve": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.approve",
              "description": "Approves a DisplayVideo360AdvertiserLinkProposal. The DisplayVideo360AdvertiserLinkProposal will be deleted and a new DisplayVideo360AdvertiserLink will be created.",
              "path": "v1alpha/{+name}:approve",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:approve",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "cancel": {
              "description": "Cancels a DisplayVideo360AdvertiserLinkProposal. Cancelling can mean either: - Declining a proposal initiated from Display & Video 360 - Withdrawing a proposal initiated from Google Analytics After being cancelled, a proposal will eventually be deleted automatically.",
              "path": "v1alpha/{+name}:cancel",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.cancel",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}:cancel"
            },
            "get": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.get",
              "description": "Lookup for a single DisplayVideo360AdvertiserLinkProposal.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals/{displayVideo360AdvertiserLinkProposalsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "description": "Lists DisplayVideo360AdvertiserLinkProposals on a property.",
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.list"
            },
            "create": {
              "id": "analyticsadmin.properties.displayVideo360AdvertiserLinkProposals.create",
              "description": "Creates a DisplayVideo360AdvertiserLinkProposal.",
              "path": "v1alpha/{+parent}/displayVideo360AdvertiserLinkProposals",
              "flatPath": "v1alpha/properties/{propertiesId}/displayVideo360AdvertiserLinkProposals",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "reportingDataAnnotations": {
          "methods": {
            "create": {
              "path": "v1alpha/{+parent}/reportingDataAnnotations",
              "description": "Creates a Reporting Data Annotation.",
              "id": "analyticsadmin.properties.reportingDataAnnotations.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations"
            },
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.reportingDataAnnotations.patch",
              "path": "v1alpha/{+name}",
              "description": "Updates a Reporting Data Annotation."
            },
            "get": {
              "description": "Lookup a single Reporting Data Annotation.",
              "path": "v1alpha/{+name}",
              "id": "analyticsadmin.properties.reportingDataAnnotations.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}"
            },
            "list": {
              "id": "analyticsadmin.properties.reportingDataAnnotations.list",
              "description": "List all Reporting Data Annotations on a property.",
              "path": "v1alpha/{+parent}/reportingDataAnnotations",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "id": "analyticsadmin.properties.reportingDataAnnotations.delete",
              "path": "v1alpha/{+name}",
              "description": "Deletes a Reporting Data Annotation.",
              "flatPath": "v1alpha/properties/{propertiesId}/reportingDataAnnotations/{reportingDataAnnotationsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "delete": {
              "path": "v1alpha/{+name}",
              "description": "Deprecated: Use `DeleteKeyEvent` instead. Deletes a conversion event in a property.",
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "DELETE",
              "deprecated": true,
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}"
            },
            "create": {
              "description": "Deprecated: Use `CreateKeyEvent` instead. Creates a conversion event with the specified attributes.",
              "path": "v1alpha/{+parent}/conversionEvents",
              "id": "analyticsadmin.properties.conversionEvents.create",
              "httpMethod": "POST",
              "deprecated": true,
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true,
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1alpha/{+name}",
              "description": "Deprecated: Use `UpdateKeyEvent` instead. Updates a conversion event with the specified attributes.",
              "id": "analyticsadmin.properties.conversionEvents.patch"
            },
            "get": {
              "id": "analyticsadmin.properties.conversionEvents.get",
              "path": "v1alpha/{+name}",
              "description": "Deprecated: Use `GetKeyEvent` instead. Retrieve a single conversion event.",
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "deprecated": true
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "deprecated": true,
              "flatPath": "v1alpha/properties/{propertiesId}/conversionEvents",
              "path": "v1alpha/{+parent}/conversionEvents",
              "description": "Deprecated: Use `ListKeyEvents` instead. Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "id": "analyticsadmin.properties.conversionEvents.list"
            }
          },
          "deprecated": true
        },
        "subpropertySyncConfigs": {
          "methods": {
            "patch": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs/{subpropertySyncConfigsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.subpropertySyncConfigs.patch",
              "path": "v1alpha/{+name}",
              "description": "Updates a `SubpropertySyncConfig`."
            },
            "list": {
              "path": "v1alpha/{+parent}/subpropertySyncConfigs",
              "description": "List all `SubpropertySyncConfig` resources for a property.",
              "id": "analyticsadmin.properties.subpropertySyncConfigs.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs"
            },
            "get": {
              "flatPath": "v1alpha/properties/{propertiesId}/subpropertySyncConfigs/{subpropertySyncConfigsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.subpropertySyncConfigs.get",
              "path": "v1alpha/{+name}",
              "description": "Lookup for a single `SubpropertySyncConfig`."
            }
          }
        }
      },
      "methods": {
        "runAccessReport": {
          "id": "analyticsadmin.properties.runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "path": "v1alpha/{+entity}:runAccessReport",
          "flatPath": "v1alpha/properties/{propertiesId}:runAccessReport",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "updateDataRetentionSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "path": "v1alpha/{+name}",
          "description": "Updates the singleton data retention settings for this property."
        },
        "provisionSubproperty": {
          "path": "v1alpha/properties:provisionSubproperty",
          "description": "Create a subproperty and a subproperty event filter that applies to the created subproperty.",
          "id": "analyticsadmin.properties.provisionSubproperty",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties:provisionSubproperty"
        },
        "getAttributionSettings": {
          "id": "analyticsadmin.properties.getAttributionSettings",
          "path": "v1alpha/{+name}",
          "description": "Lookup for a AttributionSettings singleton.",
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET"
        },
        "getReportingIdentitySettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/reportingIdentitySettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.getReportingIdentitySettings",
          "description": "Returns the reporting identity settings for this property.",
          "path": "v1alpha/{+name}"
        },
        "patch": {
          "path": "v1alpha/{+name}",
          "description": "Updates a property.",
          "id": "analyticsadmin.properties.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/properties/{propertiesId}"
        },
        "acknowledgeUserDataCollection": {
          "flatPath": "v1alpha/properties/{propertiesId}:acknowledgeUserDataCollection",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created.",
          "path": "v1alpha/{+property}:acknowledgeUserDataCollection"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1alpha/properties/{propertiesId}",
          "path": "v1alpha/{+name}",
          "description": "Lookup for a single GA Property.",
          "id": "analyticsadmin.properties.get"
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.delete"
        },
        "submitUserDeletion": {
          "flatPath": "v1alpha/properties/{propertiesId}:submitUserDeletion",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.submitUserDeletion",
          "description": "Submits a request for user deletion for a property.",
          "path": "v1alpha/{+name}:submitUserDeletion"
        },
        "getUserProvidedDataSettings": {
          "flatPath": "v1alpha/properties/{propertiesId}/userProvidedDataSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.getUserProvidedDataSettings",
          "path": "v1alpha/{+name}",
          "description": "Looks up settings related to user-provided data for a property."
        },
        "list": {
          "flatPath": "v1alpha/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.list",
          "path": "v1alpha/properties",
          "description": "Returns child Properties under the specified parent Account. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found."
        },
        "getDataRetentionSettings": {
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "path": "v1alpha/{+name}",
          "description": "Returns the singleton data retention settings for this property.",
          "flatPath": "v1alpha/properties/{propertiesId}/dataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET"
        },
        "createRollupProperty": {
          "flatPath": "v1alpha/properties:createRollupProperty",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.createRollupProperty",
          "description": "Create a roll-up property and all roll-up property source links.",
          "path": "v1alpha/properties:createRollupProperty"
        },
        "create": {
          "path": "v1alpha/properties",
          "description": "Creates a Google Analytics property with the specified location and attributes.",
          "id": "analyticsadmin.properties.create",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "POST",
          "flatPath": "v1alpha/properties"
        },
        "updateGoogleSignalsSettings": {
          "id": "analyticsadmin.properties.updateGoogleSignalsSettings",
          "path": "v1alpha/{+name}",
          "description": "Updates Google Signals settings for a property.",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH"
        },
        "getGoogleSignalsSettings": {
          "id": "analyticsadmin.properties.getGoogleSignalsSettings",
          "path": "v1alpha/{+name}",
          "description": "Lookup for Google Signals settings for a property.",
          "flatPath": "v1alpha/properties/{propertiesId}/googleSignalsSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET"
        },
        "updateAttributionSettings": {
          "description": "Updates attribution settings on a property.",
          "path": "v1alpha/{+name}",
          "id": "analyticsadmin.properties.updateAttributionSettings",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1alpha/properties/{propertiesId}/attributionSettings"
        }
      }
    }
  },
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "ownerDomain": "google.com",
  "protocol": "rest",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "basePath": "",
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "kind": "discovery#restDescription",
  "name": "analyticsadmin",
  "rootUrl": "https://analyticsadmin.googleapis.com/"
}