{
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "baseUrl": "https://www.googleapis.com/analytics/v3/",
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.user.deletion": {
          "description": "Manage Google Analytics user deletion requests"
        },
        "https://www.googleapis.com/auth/analytics": {
          "description": "View and manage your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "View your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.manage.users": {
          "description": "Manage Google Analytics Account users by email address"
        },
        "https://www.googleapis.com/auth/analytics.provision": {
          "description": "Create a new Google Analytics account along with its default property and view"
        },
        "https://www.googleapis.com/auth/analytics.manage.users.readonly": {
          "description": "View Google Analytics user permissions"
        }
      }
    }
  },
  "title": "Google Analytics API",
  "servicePath": "analytics/v3/",
  "resources": {
    "metadata": {
      "resources": {
        "columns": {
          "methods": {
            "list": {
              "description": "Lists all columns for a report type",
              "path": "metadata/{reportType}/columns",
              "id": "analytics.metadata.columns.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        }
      }
    },
    "data": {
      "resources": {
        "ga": {
          "methods": {
            "get": {
              "id": "analytics.data.ga.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns Analytics data for a view (profile).",
              "path": "data/ga"
            }
          }
        },
        "realtime": {
          "methods": {
            "get": {
              "id": "analytics.data.realtime.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns real time data for a view (profile).",
              "path": "data/realtime"
            }
          }
        },
        "mcf": {
          "methods": {
            "get": {
              "id": "analytics.data.mcf.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns Analytics Multi-Channel Funnels data for a view (profile).",
              "path": "data/mcf"
            }
          }
        }
      }
    },
    "management": {
      "resources": {
        "unsampledReports": {
          "methods": {
            "get": {
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports/{unsampledReportId}",
              "description": "Returns a single unsampled report.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.unsampledReports.get",
              "httpMethod": "GET"
            },
            "list": {
              "description": "Lists unsampled reports to which the user has access.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports",
              "id": "analytics.management.unsampledReports.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "delete": {
              "id": "analytics.management.unsampledReports.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes an unsampled report.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports/{unsampledReportId}"
            },
            "insert": {
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/unsampledReports",
              "description": "Create a new unsampled report.",
              "id": "analytics.management.unsampledReports.insert",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "customDimensions": {
          "methods": {
            "insert": {
              "description": "Create a new custom dimension.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions",
              "id": "analytics.management.customDimensions.insert",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "update": {
              "id": "analytics.management.customDimensions.update",
              "httpMethod": "PUT",
              "description": "Updates an existing custom dimension.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions/{customDimensionId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions/{customDimensionId}",
              "description": "Updates an existing custom dimension. This method supports patch semantics.",
              "id": "analytics.management.customDimensions.patch",
              "httpMethod": "PATCH"
            },
            "list": {
              "id": "analytics.management.customDimensions.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists custom dimensions to which the user has access.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.customDimensions.get",
              "httpMethod": "GET",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDimensions/{customDimensionId}",
              "description": "Get a custom dimension to which the user has access."
            }
          }
        },
        "accountSummaries": {
          "methods": {
            "list": {
              "id": "analytics.management.accountSummaries.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists account summaries (lightweight tree comprised of accounts/properties/profiles) to which the user has access.",
              "path": "management/accountSummaries"
            }
          }
        },
        "accountUserLinks": {
          "methods": {
            "delete": {
              "path": "management/accounts/{accountId}/entityUserLinks/{linkId}",
              "description": "Removes a user from the given account.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analytics.management.accountUserLinks.delete",
              "httpMethod": "DELETE"
            },
            "insert": {
              "id": "analytics.management.accountUserLinks.insert",
              "httpMethod": "POST",
              "description": "Adds a new user to the given account.",
              "path": "management/accounts/{accountId}/entityUserLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "id": "analytics.management.accountUserLinks.list",
              "httpMethod": "GET",
              "path": "management/accounts/{accountId}/entityUserLinks",
              "description": "Lists account-user links for a given account."
            },
            "update": {
              "path": "management/accounts/{accountId}/entityUserLinks/{linkId}",
              "description": "Updates permissions for an existing user on the given account.",
              "id": "analytics.management.accountUserLinks.update",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            }
          }
        },
        "profiles": {
          "methods": {
            "patch": {
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
              "description": "Updates an existing view (profile). This method supports patch semantics.",
              "id": "analytics.management.profiles.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "description": "Deletes a view (profile).",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}",
              "id": "analytics.management.profiles.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "insert": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Create a new view (profile).",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles",
              "id": "analytics.management.profiles.insert",
              "httpMethod": "POST"
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analytics.management.profiles.update",
              "httpMethod": "PUT",
              "description": "Updates an existing view (profile).",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}"
            },
            "get": {
              "id": "analytics.management.profiles.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Gets a view (profile) to which the user has access.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}"
            },
            "list": {
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles",
              "description": "Lists views (profiles) to which the user has access.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.profiles.list",
              "httpMethod": "GET"
            }
          }
        },
        "customMetrics": {
          "methods": {
            "get": {
              "id": "analytics.management.customMetrics.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Get a custom metric to which the user has access.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics/{customMetricId}"
            },
            "list": {
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics",
              "description": "Lists custom metrics to which the user has access.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.customMetrics.list",
              "httpMethod": "GET"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates an existing custom metric. This method supports patch semantics.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics/{customMetricId}",
              "id": "analytics.management.customMetrics.patch",
              "httpMethod": "PATCH"
            },
            "insert": {
              "id": "analytics.management.customMetrics.insert",
              "httpMethod": "POST",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics",
              "description": "Create a new custom metric.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "update": {
              "description": "Updates an existing custom metric.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customMetrics/{customMetricId}",
              "id": "analytics.management.customMetrics.update",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "remarketingAudience": {
          "methods": {
            "delete": {
              "description": "Delete a remarketing audience.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}",
              "id": "analytics.management.remarketingAudience.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "insert": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a new remarketing audience.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences",
              "id": "analytics.management.remarketingAudience.insert",
              "httpMethod": "POST"
            },
            "update": {
              "description": "Updates an existing remarketing audience.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}",
              "id": "analytics.management.remarketingAudience.update",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "id": "analytics.management.remarketingAudience.patch",
              "httpMethod": "PATCH",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}",
              "description": "Updates an existing remarketing audience. This method supports patch semantics.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.remarketingAudience.list",
              "httpMethod": "GET",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences",
              "description": "Lists remarketing audiences to which the user has access."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.remarketingAudience.get",
              "httpMethod": "GET",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/remarketingAudiences/{remarketingAudienceId}",
              "description": "Gets a remarketing audience to which the user has access."
            }
          }
        },
        "accounts": {
          "methods": {
            "list": {
              "path": "management/accounts",
              "description": "Lists all accounts to which the user has access.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.accounts.list",
              "httpMethod": "GET"
            }
          }
        },
        "webpropertyUserLinks": {
          "methods": {
            "list": {
              "id": "analytics.management.webpropertyUserLinks.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ],
              "description": "Lists webProperty-user links for a given web property.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks"
            },
            "update": {
              "id": "analytics.management.webpropertyUserLinks.update",
              "httpMethod": "PUT",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks/{linkId}",
              "description": "Updates permissions for an existing user on the given web property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            },
            "delete": {
              "id": "analytics.management.webpropertyUserLinks.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "description": "Removes a user from the given web property.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks/{linkId}"
            },
            "insert": {
              "description": "Adds a new user to the given web property.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityUserLinks",
              "id": "analytics.management.webpropertyUserLinks.insert",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ]
            }
          }
        },
        "goals": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.goals.list",
              "httpMethod": "GET",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals",
              "description": "Lists goals to which the user has access."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.goals.get",
              "httpMethod": "GET",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}",
              "description": "Gets a goal to which the user has access."
            },
            "insert": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analytics.management.goals.insert",
              "httpMethod": "POST",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals",
              "description": "Create a new goal."
            },
            "update": {
              "id": "analytics.management.goals.update",
              "httpMethod": "PUT",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}",
              "description": "Updates an existing goal.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "id": "analytics.management.goals.patch",
              "httpMethod": "PATCH",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/goals/{goalId}",
              "description": "Updates an existing goal. This method supports patch semantics.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            }
          }
        },
        "profileFilterLinks": {
          "methods": {
            "get": {
              "id": "analytics.management.profileFilterLinks.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns a single profile filter link.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}"
            },
            "list": {
              "description": "Lists all profile filter links for a profile.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks",
              "id": "analytics.management.profileFilterLinks.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analytics.management.profileFilterLinks.patch",
              "httpMethod": "PATCH",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}",
              "description": "Update an existing profile filter link. This method supports patch semantics."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analytics.management.profileFilterLinks.delete",
              "httpMethod": "DELETE",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}",
              "description": "Delete a profile filter link."
            },
            "insert": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analytics.management.profileFilterLinks.insert",
              "httpMethod": "POST",
              "description": "Create a new profile filter link.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks"
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analytics.management.profileFilterLinks.update",
              "httpMethod": "PUT",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/profileFilterLinks/{linkId}",
              "description": "Update an existing profile filter link."
            }
          }
        },
        "webPropertyAdWordsLinks": {
          "methods": {
            "patch": {
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}",
              "description": "Updates an existing webProperty-Google Ads link. This method supports patch semantics.",
              "id": "analytics.management.webPropertyAdWordsLinks.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analytics.management.webPropertyAdWordsLinks.update",
              "httpMethod": "PUT",
              "description": "Updates an existing webProperty-Google Ads link.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}"
            },
            "delete": {
              "id": "analytics.management.webPropertyAdWordsLinks.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a web property-Google Ads link.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}"
            },
            "insert": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Creates a webProperty-Google Ads link.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks",
              "id": "analytics.management.webPropertyAdWordsLinks.insert",
              "httpMethod": "POST"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.webPropertyAdWordsLinks.get",
              "httpMethod": "GET",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks/{webPropertyAdWordsLinkId}",
              "description": "Returns a web property-Google Ads link to which the user has access."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.webPropertyAdWordsLinks.list",
              "httpMethod": "GET",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/entityAdWordsLinks",
              "description": "Lists webProperty-Google Ads links for a given web property."
            }
          }
        },
        "clientId": {
          "methods": {
            "hashClientId": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.clientId.hashClientId",
              "httpMethod": "POST",
              "path": "management/clientId:hashClientId",
              "description": "Hashes the given Client ID."
            }
          }
        },
        "profileUserLinks": {
          "methods": {
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analytics.management.profileUserLinks.delete",
              "httpMethod": "DELETE",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks/{linkId}",
              "description": "Removes a user from the given view (profile)."
            },
            "insert": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analytics.management.profileUserLinks.insert",
              "httpMethod": "POST",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks",
              "description": "Adds a new user to the given view (profile)."
            },
            "list": {
              "description": "Lists profile-user links for a given view (profile).",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks",
              "id": "analytics.management.profileUserLinks.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users",
                "https://www.googleapis.com/auth/analytics.manage.users.readonly"
              ]
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.manage.users"
              ],
              "id": "analytics.management.profileUserLinks.update",
              "httpMethod": "PUT",
              "description": "Updates permissions for an existing user on the given view (profile).",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/entityUserLinks/{linkId}"
            }
          }
        },
        "filters": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "management/accounts/{accountId}/filters/{filterId}",
              "description": "Updates an existing filter. This method supports patch semantics.",
              "id": "analytics.management.filters.patch",
              "httpMethod": "PATCH"
            },
            "delete": {
              "path": "management/accounts/{accountId}/filters/{filterId}",
              "description": "Delete a filter.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analytics.management.filters.delete",
              "httpMethod": "DELETE"
            },
            "insert": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Create a new filter.",
              "path": "management/accounts/{accountId}/filters",
              "id": "analytics.management.filters.insert",
              "httpMethod": "POST"
            },
            "update": {
              "id": "analytics.management.filters.update",
              "httpMethod": "PUT",
              "path": "management/accounts/{accountId}/filters/{filterId}",
              "description": "Updates an existing filter.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "id": "analytics.management.filters.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns filters to which the user has access.",
              "path": "management/accounts/{accountId}/filters/{filterId}"
            },
            "list": {
              "description": "Lists all filters for an account",
              "path": "management/accounts/{accountId}/filters",
              "id": "analytics.management.filters.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "experiments": {
          "methods": {
            "patch": {
              "description": "Update an existing experiment. This method supports patch semantics.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
              "id": "analytics.management.experiments.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analytics.management.experiments.delete",
              "httpMethod": "DELETE",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
              "description": "Delete an experiment."
            },
            "insert": {
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments",
              "description": "Create a new experiment.",
              "id": "analytics.management.experiments.insert",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}",
              "description": "Update an existing experiment.",
              "id": "analytics.management.experiments.update",
              "httpMethod": "PUT"
            },
            "get": {
              "id": "analytics.management.experiments.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Returns an experiment to which the user has access.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments/{experimentId}"
            },
            "list": {
              "description": "Lists experiments to which the user has access.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/profiles/{profileId}/experiments",
              "id": "analytics.management.experiments.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "uploads": {
          "methods": {
            "uploadData": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads",
              "description": "Upload data for a custom data source.",
              "id": "analytics.management.uploads.uploadData",
              "httpMethod": "POST",
              "supportsMediaUpload": true
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.uploads.get",
              "httpMethod": "GET",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads/{uploadId}",
              "description": "List uploads to which the user has access."
            },
            "deleteUploadData": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analytics.management.uploads.deleteUploadData",
              "httpMethod": "POST",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/deleteUploadData",
              "description": "Delete data associated with a previous upload."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.uploads.list",
              "httpMethod": "GET",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources/{customDataSourceId}/uploads",
              "description": "List uploads to which the user has access."
            }
          }
        },
        "segments": {
          "methods": {
            "list": {
              "description": "Lists segments to which the user has access.",
              "path": "management/segments",
              "id": "analytics.management.segments.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "customDataSources": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.customDataSources.list",
              "httpMethod": "GET",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}/customDataSources",
              "description": "List custom data sources to which the user has access."
            }
          }
        },
        "webproperties": {
          "methods": {
            "list": {
              "description": "Lists web properties to which the user has access.",
              "path": "management/accounts/{accountId}/webproperties",
              "id": "analytics.management.webproperties.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics",
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analytics.management.webproperties.get",
              "httpMethod": "GET",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}",
              "description": "Gets a web property to which the user has access."
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analytics.management.webproperties.update",
              "httpMethod": "PUT",
              "description": "Updates an existing web property.",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}"
            },
            "insert": {
              "description": "Create a new property if the account has fewer than 20 properties. Web properties are visible in the Google Analytics interface only if they have at least one profile.",
              "path": "management/accounts/{accountId}/webproperties",
              "id": "analytics.management.webproperties.insert",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analytics.management.webproperties.patch",
              "httpMethod": "PATCH",
              "path": "management/accounts/{accountId}/webproperties/{webPropertyId}",
              "description": "Updates an existing web property. This method supports patch semantics."
            }
          }
        }
      }
    },
    "provisioning": {
      "methods": {
        "createAccountTicket": {
          "description": "Creates an account ticket.",
          "path": "provisioning/createAccountTicket",
          "id": "analytics.provisioning.createAccountTicket",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.provision"
          ]
        },
        "createAccountTree": {
          "description": "Provision account.",
          "path": "provisioning/createAccountTree",
          "id": "analytics.provisioning.createAccountTree",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.provision"
          ]
        }
      }
    },
    "userDeletion": {
      "resources": {
        "userDeletionRequest": {
          "methods": {
            "upsert": {
              "path": "userDeletion/userDeletionRequests:upsert",
              "description": "Insert or update a user deletion requests.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.user.deletion"
              ],
              "id": "analytics.userDeletion.userDeletionRequest.upsert",
              "httpMethod": "POST"
            }
          }
        }
      }
    }
  },
  "batchPath": "batch/analytics/v3",
  "protocol": "rest",
  "etag": "\"9eZ1uxVRThTDhLJCZHhqs3eQWz4/o_TVyaWurnALX6ZIQ952-U5m22Y\"",
  "documentationLink": "https://developers.google.com/analytics/",
  "name": "analytics",
  "ownerName": "Google",
  "rootUrl": "https://analytics.googleapis.com/",
  "id": "analytics:v3",
  "revision": "20190807",
  "version": "v3",
  "description": "Views and manages your Google Analytics data.",
  "basePath": "/analytics/v3/"
}