{
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "id": "analyticsadmin:v1beta",
  "basePath": "",
  "title": "Google Analytics Admin API",
  "version": "v1beta",
  "discoveryVersion": "v1",
  "ownerDomain": "google.com",
  "protocol": "rest",
  "batchPath": "batch",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "name": "analyticsadmin",
  "ownerName": "Google",
  "servicePath": "",
  "version_module": true,
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "revision": "20260406",
  "canonicalName": "Google Analytics Admin",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        },
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        }
      }
    }
  },
  "resources": {
    "accountSummaries": {
      "methods": {
        "list": {
          "description": "Returns summaries of all accounts accessible by the caller.",
          "path": "v1beta/accountSummaries",
          "httpMethod": "GET",
          "id": "analyticsadmin.accountSummaries.list",
          "flatPath": "v1beta/accountSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        }
      }
    },
    "properties": {
      "resources": {
        "conversionEvents": {
          "methods": {
            "patch": {
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH",
              "description": "Deprecated: Use `UpdateKeyEvent` instead. Updates a conversion event with the specified attributes."
            },
            "get": {
              "path": "v1beta/{+name}",
              "httpMethod": "GET",
              "description": "Deprecated: Use `GetKeyEvent` instead. Retrieve a single conversion event.",
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.get",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "list": {
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.list",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Deprecated: Use `ListKeyEvents` instead. Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "path": "v1beta/{+parent}/conversionEvents",
              "httpMethod": "GET"
            },
            "create": {
              "description": "Deprecated: Use `CreateKeyEvent` instead. Creates a conversion event with the specified attributes.",
              "path": "v1beta/{+parent}/conversionEvents",
              "httpMethod": "POST",
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.create",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "id": "analyticsadmin.properties.conversionEvents.delete",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true,
              "description": "Deprecated: Use `DeleteKeyEvent` instead. Deletes a conversion event in a property.",
              "path": "v1beta/{+name}",
              "httpMethod": "DELETE"
            }
          },
          "deprecated": true
        },
        "keyEvents": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.keyEvents.get",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Retrieve a single Key Event.",
              "path": "v1beta/{+name}",
              "httpMethod": "GET"
            },
            "list": {
              "path": "v1beta/{+parent}/keyEvents",
              "httpMethod": "GET",
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found.",
              "id": "analyticsadmin.properties.keyEvents.list",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "description": "Updates a Key Event.",
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.keyEvents.patch",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "id": "analyticsadmin.properties.keyEvents.create",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/keyEvents",
              "httpMethod": "POST",
              "description": "Creates a Key Event."
            },
            "delete": {
              "id": "analyticsadmin.properties.keyEvents.delete",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "httpMethod": "DELETE",
              "description": "Deletes a Key Event."
            }
          }
        },
        "customDimensions": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.customDimensions.list",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomDimensions on a property.",
              "path": "v1beta/{+parent}/customDimensions",
              "httpMethod": "GET"
            },
            "get": {
              "id": "analyticsadmin.properties.customDimensions.get",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lookup for a single CustomDimension.",
              "path": "v1beta/{+name}",
              "httpMethod": "GET"
            },
            "patch": {
              "description": "Updates a CustomDimension on a property.",
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.customDimensions.patch",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "id": "analyticsadmin.properties.customDimensions.create",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/customDimensions",
              "httpMethod": "POST",
              "description": "Creates a CustomDimension."
            },
            "archive": {
              "id": "analyticsadmin.properties.customDimensions.archive",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}:archive",
              "httpMethod": "POST",
              "description": "Archives a CustomDimension on a property."
            }
          }
        },
        "customMetrics": {
          "methods": {
            "archive": {
              "id": "analyticsadmin.properties.customMetrics.archive",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}:archive",
              "httpMethod": "POST",
              "description": "Archives a CustomMetric on a property."
            },
            "create": {
              "id": "analyticsadmin.properties.customMetrics.create",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+parent}/customMetrics",
              "httpMethod": "POST",
              "description": "Creates a CustomMetric."
            },
            "patch": {
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH",
              "description": "Updates a CustomMetric on a property.",
              "id": "analyticsadmin.properties.customMetrics.patch",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "id": "analyticsadmin.properties.customMetrics.list",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomMetrics on a property.",
              "path": "v1beta/{+parent}/customMetrics",
              "httpMethod": "GET"
            },
            "get": {
              "description": "Lookup for a single CustomMetric.",
              "path": "v1beta/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.customMetrics.get",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "dataStreams": {
          "methods": {
            "create": {
              "path": "v1beta/{+parent}/dataStreams",
              "httpMethod": "POST",
              "description": "Creates a DataStream.",
              "id": "analyticsadmin.properties.dataStreams.create",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "id": "analyticsadmin.properties.dataStreams.delete",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "path": "v1beta/{+name}",
              "httpMethod": "DELETE",
              "description": "Deletes a DataStream on a property."
            },
            "list": {
              "path": "v1beta/{+parent}/dataStreams",
              "httpMethod": "GET",
              "description": "Lists DataStreams on a property.",
              "id": "analyticsadmin.properties.dataStreams.list",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "get": {
              "description": "Lookup for a single DataStream.",
              "path": "v1beta/{+name}",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.dataStreams.get",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            },
            "patch": {
              "id": "analyticsadmin.properties.dataStreams.patch",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a DataStream on a property.",
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH"
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "delete": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "path": "v1beta/{+name}",
                  "httpMethod": "DELETE"
                },
                "create": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "POST",
                  "description": "Creates a measurement protocol secret."
                },
                "get": {
                  "description": "Lookup for a single MeasurementProtocolSecret.",
                  "path": "v1beta/{+name}",
                  "httpMethod": "GET",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ]
                },
                "list": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "httpMethod": "GET",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property."
                },
                "patch": {
                  "description": "Updates a measurement protocol secret.",
                  "path": "v1beta/{+name}",
                  "httpMethod": "PATCH",
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ]
                }
              }
            }
          }
        },
        "googleAdsLinks": {
          "methods": {
            "delete": {
              "id": "analyticsadmin.properties.googleAdsLinks.delete",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Deletes a GoogleAdsLink on a property",
              "path": "v1beta/{+name}",
              "httpMethod": "DELETE"
            },
            "patch": {
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "description": "Updates a GoogleAdsLink on a property",
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH"
            },
            "create": {
              "path": "v1beta/{+parent}/googleAdsLinks",
              "httpMethod": "POST",
              "description": "Creates a GoogleAdsLink.",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Lists GoogleAdsLinks on a property.",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "delete": {
              "description": "Deletes a FirebaseLink on a property",
              "path": "v1beta/{+name}",
              "httpMethod": "DELETE",
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "create": {
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "path": "v1beta/{+parent}/firebaseLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "path": "v1beta/{+parent}/firebaseLinks",
              "httpMethod": "GET",
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        }
      },
      "methods": {
        "runAccessReport": {
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "path": "v1beta/{+entity}:runAccessReport",
          "httpMethod": "POST",
          "id": "analyticsadmin.properties.runAccessReport",
          "flatPath": "v1beta/properties/{propertiesId}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "get": {
          "id": "analyticsadmin.properties.get",
          "flatPath": "v1beta/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Lookup for a single GA Property.",
          "path": "v1beta/{+name}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Returns child Properties under the specified parent Account. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "path": "v1beta/properties",
          "httpMethod": "GET",
          "id": "analyticsadmin.properties.list",
          "flatPath": "v1beta/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "delete": {
          "id": "analyticsadmin.properties.delete",
          "flatPath": "v1beta/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+name}",
          "httpMethod": "DELETE",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found."
        },
        "create": {
          "path": "v1beta/properties",
          "httpMethod": "POST",
          "description": "Creates a Google Analytics property with the specified location and attributes.",
          "id": "analyticsadmin.properties.create",
          "flatPath": "v1beta/properties",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "patch": {
          "id": "analyticsadmin.properties.patch",
          "flatPath": "v1beta/properties/{propertiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Updates a property.",
          "path": "v1beta/{+name}",
          "httpMethod": "PATCH"
        },
        "getDataRetentionSettings": {
          "id": "analyticsadmin.properties.getDataRetentionSettings",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/{+name}",
          "httpMethod": "GET",
          "description": "Returns the singleton data retention settings for this property."
        },
        "acknowledgeUserDataCollection": {
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "flatPath": "v1beta/properties/{propertiesId}:acknowledgeUserDataCollection",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+property}:acknowledgeUserDataCollection",
          "httpMethod": "POST",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created."
        },
        "updateDataRetentionSettings": {
          "path": "v1beta/{+name}",
          "httpMethod": "PATCH",
          "description": "Updates the singleton data retention settings for this property.",
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        }
      }
    },
    "accounts": {
      "methods": {
        "patch": {
          "id": "analyticsadmin.accounts.patch",
          "flatPath": "v1beta/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "path": "v1beta/{+name}",
          "httpMethod": "PATCH",
          "description": "Updates an account."
        },
        "get": {
          "path": "v1beta/{+name}",
          "httpMethod": "GET",
          "description": "Lookup for a single Account.",
          "id": "analyticsadmin.accounts.get",
          "flatPath": "v1beta/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "list": {
          "id": "analyticsadmin.accounts.list",
          "flatPath": "v1beta/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/accounts",
          "httpMethod": "GET",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found."
        },
        "runAccessReport": {
          "id": "analyticsadmin.accounts.runAccessReport",
          "flatPath": "v1beta/accounts/{accountsId}:runAccessReport",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "path": "v1beta/{+entity}:runAccessReport",
          "httpMethod": "POST",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]"
        },
        "getDataSharingSettings": {
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "flatPath": "v1beta/accounts/{accountsId}/dataSharingSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "path": "v1beta/{+name}",
          "httpMethod": "GET"
        },
        "delete": {
          "path": "v1beta/{+name}",
          "httpMethod": "DELETE",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "id": "analyticsadmin.accounts.delete",
          "flatPath": "v1beta/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "provisionAccountTicket": {
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "flatPath": "v1beta/accounts:provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Requests a ticket for creating an account.",
          "path": "v1beta/accounts:provisionAccountTicket",
          "httpMethod": "POST"
        },
        "searchChangeHistoryEvents": {
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents",
          "flatPath": "v1beta/accounts/{accountsId}:searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Searches through all changes to an account or its children given the specified set of filters. Only returns the subset of changes supported by the API. The UI may return additional changes.",
          "path": "v1beta/{+account}:searchChangeHistoryEvents",
          "httpMethod": "POST"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "kind": "discovery#restDescription"
}