{
  "discoveryVersion": "v1",
  "revision": "20260303",
  "rootUrl": "https://analyticsadmin.googleapis.com/",
  "batchPath": "batch",
  "basePath": "",
  "name": "analyticsadmin",
  "id": "analyticsadmin:v1beta",
  "mtlsRootUrl": "https://analyticsadmin.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/analytics.readonly": {
          "description": "See and download your Google Analytics data"
        },
        "https://www.googleapis.com/auth/analytics.edit": {
          "description": "Edit Google Analytics management entities"
        }
      }
    }
  },
  "description": "Manage properties in Google Analytics. Warning: Creating multiple Customer Applications, Accounts, or Projects to simulate or act as a single Customer Application, Account, or Project (respectively) or to circumvent Service-specific usage limits or quotas is a direct violation of Google Cloud Platform Terms of Service as well as Google APIs Terms of Service. These actions can result in immediate termination of your GCP project(s) without any warning.",
  "version_module": true,
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "baseUrl": "https://analyticsadmin.googleapis.com/",
  "version": "v1beta",
  "fullyEncodeReservedExpansion": true,
  "title": "Google Analytics Admin API",
  "servicePath": "",
  "ownerName": "Google",
  "canonicalName": "Google Analytics Admin",
  "documentationLink": "http://code.google.com/apis/analytics/docs/mgmt/home.html",
  "resources": {
    "properties": {
      "methods": {
        "getDataRetentionSettings": {
          "httpMethod": "GET",
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "description": "Returns the singleton data retention settings for this property.",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.getDataRetentionSettings"
        },
        "updateDataRetentionSettings": {
          "id": "analyticsadmin.properties.updateDataRetentionSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v1beta/properties/{propertiesId}/dataRetentionSettings",
          "description": "Updates the singleton data retention settings for this property.",
          "path": "v1beta/{+name}"
        },
        "delete": {
          "flatPath": "v1beta/properties/{propertiesId}",
          "description": "Marks target Property as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted properties. However, they can be restored using the Trash Can UI. If the properties are not restored before the expiration time, the Property and all child resources (eg: GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "path": "v1beta/{+name}",
          "httpMethod": "DELETE",
          "id": "analyticsadmin.properties.delete",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        },
        "create": {
          "id": "analyticsadmin.properties.create",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "flatPath": "v1beta/properties",
          "description": "Creates a Google Analytics property with the specified location and attributes.",
          "path": "v1beta/properties",
          "httpMethod": "POST"
        },
        "list": {
          "path": "v1beta/properties",
          "description": "Returns child Properties under the specified parent Account. Properties will be excluded if the caller does not have access. Soft-deleted (ie: \"trashed\") properties are excluded by default. Returns an empty list if no relevant properties are found.",
          "flatPath": "v1beta/properties",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.list"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Lookup for a single GA Property.",
          "flatPath": "v1beta/properties/{propertiesId}",
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.properties.get",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "runAccessReport": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.properties.runAccessReport",
          "path": "v1beta/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "flatPath": "v1beta/properties/{propertiesId}:runAccessReport",
          "httpMethod": "POST"
        },
        "patch": {
          "path": "v1beta/{+name}",
          "flatPath": "v1beta/properties/{propertiesId}",
          "description": "Updates a property.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.patch"
        },
        "acknowledgeUserDataCollection": {
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.properties.acknowledgeUserDataCollection",
          "httpMethod": "POST",
          "path": "v1beta/{+property}:acknowledgeUserDataCollection",
          "flatPath": "v1beta/properties/{propertiesId}:acknowledgeUserDataCollection",
          "description": "Acknowledges the terms of user data collection for the specified property. This acknowledgement must be completed (either in the Google Analytics UI or through this API) before MeasurementProtocolSecret resources may be created."
        }
      },
      "resources": {
        "googleAdsLinks": {
          "methods": {
            "delete": {
              "path": "v1beta/{+name}",
              "description": "Deletes a GoogleAdsLink on a property",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.googleAdsLinks.delete"
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "description": "Creates a GoogleAdsLink.",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.googleAdsLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "description": "Updates a GoogleAdsLink on a property",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks/{googleAdsLinksId}",
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH",
              "id": "analyticsadmin.properties.googleAdsLinks.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1beta/properties/{propertiesId}/googleAdsLinks",
              "description": "Lists GoogleAdsLinks on a property.",
              "path": "v1beta/{+parent}/googleAdsLinks",
              "id": "analyticsadmin.properties.googleAdsLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ]
            }
          }
        },
        "firebaseLinks": {
          "methods": {
            "list": {
              "id": "analyticsadmin.properties.firebaseLinks.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists FirebaseLinks on a property. Properties can have at most one FirebaseLink.",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks",
              "path": "v1beta/{+parent}/firebaseLinks",
              "httpMethod": "GET"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.create",
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/firebaseLinks",
              "description": "Creates a FirebaseLink. Properties can have at most one FirebaseLink.",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.firebaseLinks.delete",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/firebaseLinks/{firebaseLinksId}",
              "description": "Deletes a FirebaseLink on a property",
              "httpMethod": "DELETE"
            }
          }
        },
        "conversionEvents": {
          "methods": {
            "patch": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "description": "Deprecated: Use `UpdateKeyEvent` instead. Updates a conversion event with the specified attributes.",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.patch",
              "deprecated": true
            },
            "get": {
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Deprecated: Use `GetKeyEvent` instead. Retrieve a single conversion event.",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "path": "v1beta/{+name}",
              "httpMethod": "GET"
            },
            "list": {
              "id": "analyticsadmin.properties.conversionEvents.list",
              "deprecated": true,
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "description": "Deprecated: Use `ListKeyEvents` instead. Returns a list of conversion events in the specified parent property. Returns an empty list if no conversion events are found.",
              "path": "v1beta/{+parent}/conversionEvents",
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/conversionEvents",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents",
              "description": "Deprecated: Use `CreateKeyEvent` instead. Creates a conversion event with the specified attributes.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.conversionEvents.create",
              "deprecated": true
            },
            "delete": {
              "path": "v1beta/{+name}",
              "description": "Deprecated: Use `DeleteKeyEvent` instead. Deletes a conversion event in a property.",
              "flatPath": "v1beta/properties/{propertiesId}/conversionEvents/{conversionEventsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "deprecated": true,
              "id": "analyticsadmin.properties.conversionEvents.delete"
            }
          },
          "deprecated": true
        },
        "customDimensions": {
          "methods": {
            "get": {
              "id": "analyticsadmin.properties.customDimensions.get",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "description": "Lookup for a single CustomDimension.",
              "path": "v1beta/{+name}",
              "httpMethod": "GET"
            },
            "list": {
              "id": "analyticsadmin.properties.customDimensions.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomDimensions on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions",
              "path": "v1beta/{+parent}/customDimensions",
              "httpMethod": "GET"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.create",
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/customDimensions",
              "description": "Creates a CustomDimension.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions"
            },
            "archive": {
              "httpMethod": "POST",
              "description": "Archives a CustomDimension on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}:archive",
              "path": "v1beta/{+name}:archive",
              "id": "analyticsadmin.properties.customDimensions.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customDimensions.patch",
              "httpMethod": "PATCH",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customDimensions/{customDimensionsId}",
              "description": "Updates a CustomDimension on a property."
            }
          }
        },
        "customMetrics": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.patch",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Updates a CustomMetric on a property.",
              "httpMethod": "PATCH"
            },
            "list": {
              "id": "analyticsadmin.properties.customMetrics.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "description": "Lists CustomMetrics on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "path": "v1beta/{+parent}/customMetrics",
              "httpMethod": "GET"
            },
            "get": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}",
              "description": "Lookup for a single CustomMetric.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.customMetrics.get"
            },
            "archive": {
              "id": "analyticsadmin.properties.customMetrics.archive",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics/{customMetricsId}:archive",
              "description": "Archives a CustomMetric on a property.",
              "path": "v1beta/{+name}:archive",
              "httpMethod": "POST"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.customMetrics.create",
              "httpMethod": "POST",
              "path": "v1beta/{+parent}/customMetrics",
              "flatPath": "v1beta/properties/{propertiesId}/customMetrics",
              "description": "Creates a CustomMetric."
            }
          }
        },
        "dataStreams": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "description": "Creates a DataStream.",
              "path": "v1beta/{+parent}/dataStreams",
              "id": "analyticsadmin.properties.dataStreams.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a DataStream on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "path": "v1beta/{+name}",
              "id": "analyticsadmin.properties.dataStreams.delete",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "get": {
              "path": "v1beta/{+name}",
              "description": "Lookup for a single DataStream.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.dataStreams.get"
            },
            "list": {
              "id": "analyticsadmin.properties.dataStreams.list",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lists DataStreams on a property.",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams",
              "path": "v1beta/{+parent}/dataStreams"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}",
              "description": "Updates a DataStream on a property.",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.dataStreams.patch"
            }
          },
          "resources": {
            "measurementProtocolSecrets": {
              "methods": {
                "patch": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Updates a measurement protocol secret.",
                  "path": "v1beta/{+name}",
                  "httpMethod": "PATCH"
                },
                "delete": {
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}",
                  "description": "Deletes target MeasurementProtocolSecret.",
                  "path": "v1beta/{+name}",
                  "httpMethod": "DELETE"
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "description": "Creates a measurement protocol secret.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.create"
                },
                "list": {
                  "httpMethod": "GET",
                  "path": "v1beta/{+parent}/measurementProtocolSecrets",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets",
                  "description": "Returns child MeasurementProtocolSecrets under the specified parent Property.",
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.list"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/analytics.edit",
                    "https://www.googleapis.com/auth/analytics.readonly"
                  ],
                  "id": "analyticsadmin.properties.dataStreams.measurementProtocolSecrets.get",
                  "httpMethod": "GET",
                  "path": "v1beta/{+name}",
                  "description": "Lookup for a single MeasurementProtocolSecret.",
                  "flatPath": "v1beta/properties/{propertiesId}/dataStreams/{dataStreamsId}/measurementProtocolSecrets/{measurementProtocolSecretsId}"
                }
              }
            }
          }
        },
        "keyEvents": {
          "methods": {
            "patch": {
              "id": "analyticsadmin.properties.keyEvents.patch",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "description": "Updates a Key Event.",
              "path": "v1beta/{+name}",
              "httpMethod": "PATCH"
            },
            "get": {
              "path": "v1beta/{+name}",
              "description": "Retrieve a single Key Event.",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.keyEvents.get"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit",
                "https://www.googleapis.com/auth/analytics.readonly"
              ],
              "id": "analyticsadmin.properties.keyEvents.list",
              "path": "v1beta/{+parent}/keyEvents",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents",
              "description": "Returns a list of Key Events in the specified parent property. Returns an empty list if no Key Events are found.",
              "httpMethod": "GET"
            },
            "create": {
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents",
              "description": "Creates a Key Event.",
              "path": "v1beta/{+parent}/keyEvents",
              "httpMethod": "POST",
              "id": "analyticsadmin.properties.keyEvents.create",
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/analytics.edit"
              ],
              "id": "analyticsadmin.properties.keyEvents.delete",
              "path": "v1beta/{+name}",
              "description": "Deletes a Key Event.",
              "flatPath": "v1beta/properties/{propertiesId}/keyEvents/{keyEventsId}",
              "httpMethod": "DELETE"
            }
          }
        }
      }
    },
    "accountSummaries": {
      "methods": {
        "list": {
          "id": "analyticsadmin.accountSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1beta/accountSummaries",
          "description": "Returns summaries of all accounts accessible by the caller.",
          "path": "v1beta/accountSummaries"
        }
      }
    },
    "accounts": {
      "methods": {
        "list": {
          "id": "analyticsadmin.accounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v1beta/accounts",
          "description": "Returns all accounts accessible by the caller. Note that these accounts might not currently have GA properties. Soft-deleted (ie: \"trashed\") accounts are excluded by default. Returns an empty list if no relevant accounts are found.",
          "path": "v1beta/accounts"
        },
        "get": {
          "httpMethod": "GET",
          "path": "v1beta/{+name}",
          "description": "Lookup for a single Account.",
          "flatPath": "v1beta/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.get"
        },
        "getDataSharingSettings": {
          "httpMethod": "GET",
          "description": "Get data sharing settings on an account. Data sharing settings are singletons.",
          "flatPath": "v1beta/accounts/{accountsId}/dataSharingSettings",
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.accounts.getDataSharingSettings",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ]
        },
        "runAccessReport": {
          "path": "v1beta/{+entity}:runAccessReport",
          "description": "Returns a customized report of data access records. The report provides records of each time a user reads Google Analytics reporting data. Access records are retained for up to 2 years. Data Access Reports can be requested for a property. Reports may be requested for any property, but dimensions that aren't related to quota can only be requested on Google Analytics 360 properties. This method is only available to Administrators. These data access records include GA UI R[...]",
          "flatPath": "v1beta/accounts/{accountsId}:runAccessReport",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit",
            "https://www.googleapis.com/auth/analytics.readonly"
          ],
          "id": "analyticsadmin.accounts.runAccessReport"
        },
        "delete": {
          "id": "analyticsadmin.accounts.delete",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "httpMethod": "DELETE",
          "description": "Marks target Account as soft-deleted (ie: \"trashed\") and returns it. This API does not have a method to restore soft-deleted accounts. However, they can be restored using the Trash Can UI. If the accounts are not restored before the expiration time, the account and all child resources (eg: Properties, GoogleAdsLinks, Streams, AccessBindings) will be permanently purged. https://support.google.com/analytics/answer/6154772 Returns an error if the target is not found.",
          "flatPath": "v1beta/accounts/{accountsId}",
          "path": "v1beta/{+name}"
        },
        "provisionAccountTicket": {
          "id": "analyticsadmin.accounts.provisionAccountTicket",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "description": "Requests a ticket for creating an account.",
          "flatPath": "v1beta/accounts:provisionAccountTicket",
          "path": "v1beta/accounts:provisionAccountTicket",
          "httpMethod": "POST"
        },
        "searchChangeHistoryEvents": {
          "httpMethod": "POST",
          "path": "v1beta/{+account}:searchChangeHistoryEvents",
          "description": "Searches through all changes to an account or its children given the specified set of filters. Only returns the subset of changes supported by the API. The UI may return additional changes.",
          "flatPath": "v1beta/accounts/{accountsId}:searchChangeHistoryEvents",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ],
          "id": "analyticsadmin.accounts.searchChangeHistoryEvents"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an account.",
          "flatPath": "v1beta/accounts/{accountsId}",
          "path": "v1beta/{+name}",
          "id": "analyticsadmin.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/analytics.edit"
          ]
        }
      }
    }
  },
  "protocol": "rest"
}