{
  "baseUrl": "https://bigtableadmin.googleapis.com/",
  "basePath": "",
  "description": "Administer your Cloud Bigtable tables and instances.",
  "ownerDomain": "google.com",
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "name": "bigtableadmin",
  "documentationLink": "https://cloud.google.com/bigtable/",
  "canonicalName": "Bigtable Admin",
  "servicePath": "",
  "batchPath": "batch",
  "id": "bigtableadmin:v2",
  "version_module": true,
  "ownerName": "Google",
  "revision": "20260425",
  "protocol": "rest",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-bigtable.admin.table": {
          "description": "Administer your Cloud Bigtable tables"
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-bigtable.admin": {
          "description": "Administer your Cloud Bigtable tables and clusters"
        },
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud services and see the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/bigtable.admin": {
          "description": "Administer your Cloud Bigtable tables and clusters"
        },
        "https://www.googleapis.com/auth/bigtable.admin.instance": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/bigtable.admin.cluster": {
          "description": "Administer your Cloud Bigtable clusters"
        },
        "https://www.googleapis.com/auth/bigtable.admin.table": {
          "description": "Administer your Cloud Bigtable tables"
        }
      }
    }
  },
  "title": "Cloud Bigtable Admin API",
  "kind": "discovery#restDescription",
  "version": "v2",
  "resources": {
    "operations": {
      "methods": {
        "get": {
          "flatPath": "v2/operations/{operationsId}",
          "httpMethod": "GET",
          "path": "v2/{+name}",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "scopes": [
            "https://www.googleapis.com/auth/bigtable.admin",
            "https://www.googleapis.com/auth/bigtable.admin.cluster",
            "https://www.googleapis.com/auth/bigtable.admin.instance",
            "https://www.googleapis.com/auth/cloud-bigtable.admin",
            "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/cloud-platform.read-only"
          ],
          "id": "bigtableadmin.operations.get"
        }
      },
      "resources": {
        "projects": {
          "resources": {
            "operations": {
              "methods": {
                "list": {
                  "id": "bigtableadmin.operations.projects.operations.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                  "path": "v2/{+name}/operations",
                  "flatPath": "v2/operations/projects/{projectsId}/operations",
                  "httpMethod": "GET"
                }
              }
            }
          }
        }
      }
    },
    "projects": {
      "resources": {
        "instances": {
          "methods": {
            "update": {
              "description": "Updates an instance within a project. This method updates only the display name and type for an Instance. To update other Instance properties, such as labels, use PartialUpdateInstance.",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "bigtableadmin.projects.instances.update",
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "httpMethod": "PUT"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "bigtableadmin.projects.instances.delete",
              "description": "Delete an instance from a project.",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "httpMethod": "DELETE",
              "path": "v2/{+name}"
            },
            "partialUpdateInstance": {
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "httpMethod": "PATCH",
              "description": "Partially updates an instance within a project. This method can modify all fields of an Instance and is the preferred way to update an Instance.",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "bigtableadmin.projects.instances.partialUpdateInstance"
            },
            "list": {
              "flatPath": "v2/projects/{projectsId}/instances",
              "httpMethod": "GET",
              "path": "v2/{+parent}/instances",
              "description": "Lists information about instances in a project.",
              "id": "bigtableadmin.projects.instances.list",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ]
            },
            "setIamPolicy": {
              "description": "Sets the access control policy on an instance resource. Replaces any existing policy.",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "bigtableadmin.projects.instances.setIamPolicy",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:setIamPolicy",
              "httpMethod": "POST",
              "path": "v2/{+resource}:setIamPolicy"
            },
            "get": {
              "path": "v2/{+name}",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}",
              "httpMethod": "GET",
              "description": "Gets information about an instance.",
              "id": "bigtableadmin.projects.instances.get",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ]
            },
            "getIamPolicy": {
              "path": "v2/{+resource}:getIamPolicy",
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:getIamPolicy",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "bigtableadmin.projects.instances.getIamPolicy",
              "description": "Gets the access control policy for an instance resource. Returns an empty policy if an instance exists but does not have a policy set."
            },
            "testIamPermissions": {
              "description": "Returns permissions that the caller has on the specified instance resource.",
              "id": "bigtableadmin.projects.instances.testIamPermissions",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v2/projects/{projectsId}/instances/{instancesId}:testIamPermissions",
              "httpMethod": "POST",
              "path": "v2/{+resource}:testIamPermissions"
            },
            "create": {
              "path": "v2/{+parent}/instances",
              "flatPath": "v2/projects/{projectsId}/instances",
              "httpMethod": "POST",
              "description": "Create an instance within a project. Note that exactly one of Cluster.serve_nodes and Cluster.cluster_config.cluster_autoscaling_config can be set. If serve_nodes is set to non-zero, then the cluster is manually scaled. If cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is enabled.",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "bigtableadmin.projects.instances.create"
            }
          },
          "resources": {
            "appProfiles": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.appProfiles.create",
                  "description": "Creates an app profile within an instance.",
                  "path": "v2/{+parent}/appProfiles",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles",
                  "httpMethod": "POST"
                },
                "list": {
                  "id": "bigtableadmin.projects.instances.appProfiles.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Lists information about app profiles in an instance.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles",
                  "httpMethod": "GET",
                  "path": "v2/{+parent}/appProfiles"
                },
                "delete": {
                  "id": "bigtableadmin.projects.instances.appProfiles.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Deletes an app profile from an instance.",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "description": "Gets information about an app profile.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "bigtableadmin.projects.instances.appProfiles.get",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "httpMethod": "GET"
                },
                "patch": {
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/appProfiles/{appProfilesId}",
                  "httpMethod": "PATCH",
                  "description": "Updates an app profile within an instance.",
                  "id": "bigtableadmin.projects.instances.appProfiles.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                }
              }
            },
            "logicalViews": {
              "methods": {
                "setIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.logicalViews.setIamPolicy",
                  "description": "Sets the access control policy on an instance resource. Replaces any existing policy.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/logicalViews/{logicalViewsId}:setIamPolicy",
                  "httpMethod": "POST",
                  "path": "v2/{+resource}:setIamPolicy"
                },
                "create": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/logicalViews",
                  "httpMethod": "POST",
                  "path": "v2/{+parent}/logicalViews",
                  "id": "bigtableadmin.projects.instances.logicalViews.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Creates a logical view within an instance."
                },
                "testIamPermissions": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/logicalViews/{logicalViewsId}:testIamPermissions",
                  "httpMethod": "POST",
                  "path": "v2/{+resource}:testIamPermissions",
                  "id": "bigtableadmin.projects.instances.logicalViews.testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Returns permissions that the caller has on the specified instance resource."
                },
                "list": {
                  "description": "Lists information about logical views in an instance.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.logicalViews.list",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/logicalViews",
                  "httpMethod": "GET",
                  "path": "v2/{+parent}/logicalViews"
                },
                "getIamPolicy": {
                  "path": "v2/{+resource}:getIamPolicy",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/logicalViews/{logicalViewsId}:getIamPolicy",
                  "httpMethod": "POST",
                  "description": "Gets the access control policy for an instance resource. Returns an empty policy if an instance exists but does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.logicalViews.getIamPolicy"
                },
                "delete": {
                  "description": "Deletes a logical view from an instance.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.logicalViews.delete",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/logicalViews/{logicalViewsId}",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "description": "Gets information about a logical view.",
                  "id": "bigtableadmin.projects.instances.logicalViews.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/logicalViews/{logicalViewsId}",
                  "httpMethod": "GET",
                  "path": "v2/{+name}"
                },
                "patch": {
                  "description": "Updates a logical view within an instance.",
                  "id": "bigtableadmin.projects.instances.logicalViews.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/logicalViews/{logicalViewsId}",
                  "httpMethod": "PATCH"
                }
              }
            },
            "materializedViews": {
              "methods": {
                "create": {
                  "path": "v2/{+parent}/materializedViews",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/materializedViews",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.materializedViews.create",
                  "description": "Creates a materialized view within an instance."
                },
                "testIamPermissions": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/materializedViews/{materializedViewsId}:testIamPermissions",
                  "httpMethod": "POST",
                  "path": "v2/{+resource}:testIamPermissions",
                  "description": "Returns permissions that the caller has on the specified instance resource.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.materializedViews.testIamPermissions"
                },
                "list": {
                  "path": "v2/{+parent}/materializedViews",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/materializedViews",
                  "httpMethod": "GET",
                  "id": "bigtableadmin.projects.instances.materializedViews.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Lists information about materialized views in an instance."
                },
                "setIamPolicy": {
                  "id": "bigtableadmin.projects.instances.materializedViews.setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Sets the access control policy on an instance resource. Replaces any existing policy.",
                  "path": "v2/{+resource}:setIamPolicy",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/materializedViews/{materializedViewsId}:setIamPolicy",
                  "httpMethod": "POST"
                },
                "get": {
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/materializedViews/{materializedViewsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.materializedViews.get",
                  "description": "Gets information about a materialized view."
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.materializedViews.patch",
                  "description": "Updates a materialized view within an instance.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/materializedViews/{materializedViewsId}",
                  "httpMethod": "PATCH",
                  "path": "v2/{+name}"
                },
                "getIamPolicy": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/materializedViews/{materializedViewsId}:getIamPolicy",
                  "httpMethod": "POST",
                  "path": "v2/{+resource}:getIamPolicy",
                  "description": "Gets the access control policy for an instance resource. Returns an empty policy if an instance exists but does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.materializedViews.getIamPolicy"
                },
                "delete": {
                  "id": "bigtableadmin.projects.instances.materializedViews.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Deletes a materialized view from an instance.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/materializedViews/{materializedViewsId}",
                  "httpMethod": "DELETE",
                  "path": "v2/{+name}"
                }
              }
            },
            "clusters": {
              "methods": {
                "get": {
                  "description": "Gets information about a cluster.",
                  "id": "bigtableadmin.projects.instances.clusters.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "httpMethod": "GET"
                },
                "update": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "httpMethod": "PUT",
                  "path": "v2/{+name}",
                  "description": "Updates a cluster within an instance. Note that UpdateCluster does not support updating cluster_config.cluster_autoscaling_config. In order to update it, you must use PartialUpdateCluster.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.clusters.update"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.clusters.delete",
                  "description": "Deletes a cluster from an instance.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "httpMethod": "DELETE",
                  "path": "v2/{+name}"
                },
                "getMemoryLayer": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/memoryLayer",
                  "httpMethod": "GET",
                  "path": "v2/{+name}",
                  "id": "bigtableadmin.projects.instances.clusters.getMemoryLayer",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets information about the memory layer of a cluster."
                },
                "create": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters",
                  "httpMethod": "POST",
                  "path": "v2/{+parent}/clusters",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.clusters.create",
                  "description": "Creates a cluster within an instance. Note that exactly one of Cluster.serve_nodes and Cluster.cluster_config.cluster_autoscaling_config can be set. If serve_nodes is set to non-zero, then the cluster is manually scaled. If cluster_config.cluster_autoscaling_config is non-empty, then autoscaling is enabled."
                },
                "list": {
                  "description": "Lists information about clusters in an instance.",
                  "id": "bigtableadmin.projects.instances.clusters.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "path": "v2/{+parent}/clusters",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters",
                  "httpMethod": "GET"
                },
                "partialUpdateCluster": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}",
                  "httpMethod": "PATCH",
                  "path": "v2/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/bigtable.admin.instance",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.clusters.partialUpdateCluster",
                  "description": "Partially updates a cluster within a project. This method is the preferred way to update a Cluster. To enable and update autoscaling, set cluster_config.cluster_autoscaling_config. When autoscaling is enabled, serve_nodes is treated as an OUTPUT_ONLY field, meaning that updates to it are ignored. Note that an update cannot simultaneously set serve_nodes to non-zero and cluster_config.cluster_autoscaling_config to non-empty, and also specify both in the update_ma[...]"
                }
              },
              "resources": {
                "backups": {
                  "methods": {
                    "testIamPermissions": {
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.clusters.backups.testIamPermissions",
                      "description": "Returns permissions that the caller has on the specified Bigtable resource.",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:testIamPermissions",
                      "httpMethod": "POST",
                      "path": "v2/{+resource}:testIamPermissions"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.clusters.backups.create",
                      "description": "Starts creating a new Cloud Bigtable Backup. The returned backup long-running operation can be used to track creation of the backup. The metadata field type is CreateBackupMetadata. The response field type is Backup, if successful. Cancelling the returned operation will stop the creation and delete the backup.",
                      "path": "v2/{+parent}/backups",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups",
                      "httpMethod": "POST"
                    },
                    "getIamPolicy": {
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.clusters.backups.getIamPolicy",
                      "description": "Gets the access control policy for a Bigtable resource. Returns an empty policy if the resource exists but does not have a policy set.",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:getIamPolicy",
                      "httpMethod": "POST",
                      "path": "v2/{+resource}:getIamPolicy"
                    },
                    "get": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Gets metadata on a pending or completed Cloud Bigtable Backup.",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                      "httpMethod": "GET",
                      "path": "v2/{+name}"
                    },
                    "setIamPolicy": {
                      "path": "v2/{+resource}:setIamPolicy",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}:setIamPolicy",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.clusters.backups.setIamPolicy",
                      "description": "Sets the access control policy on a Bigtable resource. Replaces any existing policy."
                    },
                    "list": {
                      "path": "v2/{+parent}/backups",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups",
                      "httpMethod": "GET",
                      "description": "Lists Cloud Bigtable backups. Returns both completed and pending backups.",
                      "id": "bigtableadmin.projects.instances.clusters.backups.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ]
                    },
                    "delete": {
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                      "httpMethod": "DELETE",
                      "path": "v2/{+name}",
                      "description": "Deletes a pending or completed Cloud Bigtable backup.",
                      "id": "bigtableadmin.projects.instances.clusters.backups.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ]
                    },
                    "patch": {
                      "description": "Updates a pending or completed Cloud Bigtable Backup.",
                      "id": "bigtableadmin.projects.instances.clusters.backups.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "path": "v2/{+name}",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups/{backupsId}",
                      "httpMethod": "PATCH"
                    },
                    "copy": {
                      "id": "bigtableadmin.projects.instances.clusters.backups.copy",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Copy a Cloud Bigtable backup to a new backup in the destination cluster located in the destination instance and project.",
                      "path": "v2/{+parent}/backups:copy",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/backups:copy",
                      "httpMethod": "POST"
                    }
                  }
                },
                "hotTablets": {
                  "methods": {
                    "list": {
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/hotTablets",
                      "httpMethod": "GET",
                      "path": "v2/{+parent}/hotTablets",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.clusters.hotTablets.list",
                      "description": "Lists hot tablets in a cluster, within the time range provided. Hot tablets are ordered based on CPU usage."
                    }
                  }
                },
                "memoryLayers": {
                  "methods": {
                    "list": {
                      "path": "v2/{+parent}/memoryLayers",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/clusters/{clustersId}/memoryLayers",
                      "httpMethod": "GET",
                      "description": "Lists information about memory layers.",
                      "id": "bigtableadmin.projects.instances.clusters.memoryLayers.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/bigtable.admin.instance",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ]
                    }
                  }
                }
              }
            },
            "tables": {
              "methods": {
                "delete": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "httpMethod": "DELETE",
                  "path": "v2/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.tables.delete",
                  "description": "Permanently deletes a specified table and all of its data."
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "id": "bigtableadmin.projects.instances.tables.list",
                  "description": "Lists all tables served from a specified instance.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables",
                  "httpMethod": "GET",
                  "path": "v2/{+parent}/tables"
                },
                "generateConsistencyToken": {
                  "path": "v2/{+name}:generateConsistencyToken",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:generateConsistencyToken",
                  "httpMethod": "POST",
                  "id": "bigtableadmin.projects.instances.tables.generateConsistencyToken",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Generates a consistency token for a Table, which can be used in CheckConsistency to check whether mutations to the table that finished before this call started have been replicated. The tokens will be available for 90 days."
                },
                "restore": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables:restore",
                  "httpMethod": "POST",
                  "path": "v2/{+parent}/tables:restore",
                  "id": "bigtableadmin.projects.instances.tables.restore",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Create a new table by restoring from a completed backup. The returned table long-running operation can be used to track the progress of the operation, and to cancel it. The metadata field type is RestoreTableMetadata. The response type is Table, if successful."
                },
                "undelete": {
                  "description": "Restores a specified table which was accidentally deleted.",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.tables.undelete",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:undelete",
                  "httpMethod": "POST",
                  "path": "v2/{+name}:undelete"
                },
                "create": {
                  "description": "Creates a new table in the specified instance. The table can be created with a full set of initial column families, specified in the request.",
                  "id": "bigtableadmin.projects.instances.tables.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "path": "v2/{+parent}/tables",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables",
                  "httpMethod": "POST"
                },
                "checkConsistency": {
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:checkConsistency",
                  "httpMethod": "POST",
                  "path": "v2/{+name}:checkConsistency",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.tables.checkConsistency",
                  "description": "Checks replication consistency based on a consistency token, that is, if replication has caught up based on the conditions specified in the token and the check request."
                },
                "patch": {
                  "description": "Updates a specified table.",
                  "id": "bigtableadmin.projects.instances.tables.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "httpMethod": "PATCH",
                  "path": "v2/{+name}"
                },
                "modifyColumnFamilies": {
                  "path": "v2/{+name}:modifyColumnFamilies",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:modifyColumnFamilies",
                  "httpMethod": "POST",
                  "description": "Performs a series of column family modifications on the specified table. Either all or none of the modifications will occur before this method returns, but data requests received prior to that point may see a table where only some modifications have taken effect.",
                  "id": "bigtableadmin.projects.instances.tables.modifyColumnFamilies",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                },
                "setIamPolicy": {
                  "id": "bigtableadmin.projects.instances.tables.setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Sets the access control policy on a Bigtable resource. Replaces any existing policy.",
                  "path": "v2/{+resource}:setIamPolicy",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:setIamPolicy",
                  "httpMethod": "POST"
                },
                "get": {
                  "id": "bigtableadmin.projects.instances.tables.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only"
                  ],
                  "description": "Gets metadata information about the specified table.",
                  "path": "v2/{+name}",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}",
                  "httpMethod": "GET"
                },
                "dropRowRange": {
                  "description": "Permanently drop/delete a row range from a specified table. The request can specify whether to delete all rows in a table, or only those that match a particular prefix. Note that row key prefixes used here are treated as service data. For more information about how service data is handled, see the [Google Cloud Privacy Notice](https://cloud.google.com/terms/cloud-privacy-notice).",
                  "id": "bigtableadmin.projects.instances.tables.dropRowRange",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:dropRowRange",
                  "httpMethod": "POST",
                  "path": "v2/{+name}:dropRowRange"
                },
                "getIamPolicy": {
                  "id": "bigtableadmin.projects.instances.tables.getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "description": "Gets the access control policy for a Bigtable resource. Returns an empty policy if the resource exists but does not have a policy set.",
                  "path": "v2/{+resource}:getIamPolicy",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:getIamPolicy",
                  "httpMethod": "POST"
                },
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/bigtable.admin",
                    "https://www.googleapis.com/auth/bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin",
                    "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "bigtableadmin.projects.instances.tables.testIamPermissions",
                  "description": "Returns permissions that the caller has on the specified Bigtable resource.",
                  "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}:testIamPermissions",
                  "httpMethod": "POST",
                  "path": "v2/{+resource}:testIamPermissions"
                }
              },
              "resources": {
                "schemaBundles": {
                  "methods": {
                    "setIamPolicy": {
                      "description": "Sets the access control policy on a Bigtable resource. Replaces any existing policy.",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.tables.schemaBundles.setIamPolicy",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/schemaBundles/{schemaBundlesId}:setIamPolicy",
                      "httpMethod": "POST",
                      "path": "v2/{+resource}:setIamPolicy"
                    },
                    "testIamPermissions": {
                      "path": "v2/{+resource}:testIamPermissions",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/schemaBundles/{schemaBundlesId}:testIamPermissions",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.tables.schemaBundles.testIamPermissions",
                      "description": "Returns permissions that the caller has on the specified Bigtable resource."
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.tables.schemaBundles.list",
                      "description": "Lists all schema bundles associated with the specified table.",
                      "path": "v2/{+parent}/schemaBundles",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/schemaBundles",
                      "httpMethod": "GET"
                    },
                    "create": {
                      "description": "Creates a new schema bundle in the specified table.",
                      "id": "bigtableadmin.projects.instances.tables.schemaBundles.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "path": "v2/{+parent}/schemaBundles",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/schemaBundles",
                      "httpMethod": "POST"
                    },
                    "getIamPolicy": {
                      "description": "Gets the access control policy for a Bigtable resource. Returns an empty policy if the resource exists but does not have a policy set.",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.tables.schemaBundles.getIamPolicy",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/schemaBundles/{schemaBundlesId}:getIamPolicy",
                      "httpMethod": "POST",
                      "path": "v2/{+resource}:getIamPolicy"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.tables.schemaBundles.delete",
                      "description": "Deletes a schema bundle in the specified table.",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/schemaBundles/{schemaBundlesId}",
                      "httpMethod": "DELETE",
                      "path": "v2/{+name}"
                    },
                    "patch": {
                      "path": "v2/{+name}",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/schemaBundles/{schemaBundlesId}",
                      "httpMethod": "PATCH",
                      "id": "bigtableadmin.projects.instances.tables.schemaBundles.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Updates a schema bundle in the specified table."
                    },
                    "get": {
                      "id": "bigtableadmin.projects.instances.tables.schemaBundles.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Gets metadata information about the specified schema bundle.",
                      "path": "v2/{+name}",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/schemaBundles/{schemaBundlesId}",
                      "httpMethod": "GET"
                    }
                  }
                },
                "authorizedViews": {
                  "methods": {
                    "get": {
                      "path": "v2/{+name}",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/authorizedViews/{authorizedViewsId}",
                      "httpMethod": "GET",
                      "description": "Gets information from a specified AuthorizedView.",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.tables.authorizedViews.get"
                    },
                    "patch": {
                      "description": "Updates an AuthorizedView in a table.",
                      "id": "bigtableadmin.projects.instances.tables.authorizedViews.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "path": "v2/{+name}",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/authorizedViews/{authorizedViewsId}",
                      "httpMethod": "PATCH"
                    },
                    "delete": {
                      "path": "v2/{+name}",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/authorizedViews/{authorizedViewsId}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.tables.authorizedViews.delete",
                      "description": "Permanently deletes a specified AuthorizedView."
                    },
                    "getIamPolicy": {
                      "description": "Gets the access control policy for a Bigtable resource. Returns an empty policy if the resource exists but does not have a policy set.",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.tables.authorizedViews.getIamPolicy",
                      "path": "v2/{+resource}:getIamPolicy",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/authorizedViews/{authorizedViewsId}:getIamPolicy",
                      "httpMethod": "POST"
                    },
                    "create": {
                      "id": "bigtableadmin.projects.instances.tables.authorizedViews.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "description": "Creates a new AuthorizedView in a table.",
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/authorizedViews",
                      "httpMethod": "POST",
                      "path": "v2/{+parent}/authorizedViews"
                    },
                    "list": {
                      "description": "Lists all AuthorizedViews from a specific table.",
                      "id": "bigtableadmin.projects.instances.tables.authorizedViews.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/authorizedViews",
                      "httpMethod": "GET",
                      "path": "v2/{+parent}/authorizedViews"
                    },
                    "testIamPermissions": {
                      "description": "Returns permissions that the caller has on the specified Bigtable resource.",
                      "id": "bigtableadmin.projects.instances.tables.authorizedViews.testIamPermissions",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/authorizedViews/{authorizedViewsId}:testIamPermissions",
                      "httpMethod": "POST",
                      "path": "v2/{+resource}:testIamPermissions"
                    },
                    "setIamPolicy": {
                      "flatPath": "v2/projects/{projectsId}/instances/{instancesId}/tables/{tablesId}/authorizedViews/{authorizedViewsId}:setIamPolicy",
                      "httpMethod": "POST",
                      "path": "v2/{+resource}:setIamPolicy",
                      "description": "Sets the access control policy on a Bigtable resource. Replaces any existing policy.",
                      "scopes": [
                        "https://www.googleapis.com/auth/bigtable.admin",
                        "https://www.googleapis.com/auth/bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin",
                        "https://www.googleapis.com/auth/cloud-bigtable.admin.table",
                        "https://www.googleapis.com/auth/cloud-platform"
                      ],
                      "id": "bigtableadmin.projects.instances.tables.authorizedViews.setIamPolicy"
                    }
                  }
                }
              }
            }
          }
        },
        "locations": {
          "methods": {
            "list": {
              "id": "bigtableadmin.projects.locations.list",
              "scopes": [
                "https://www.googleapis.com/auth/bigtable.admin",
                "https://www.googleapis.com/auth/bigtable.admin.cluster",
                "https://www.googleapis.com/auth/bigtable.admin.instance",
                "https://www.googleapis.com/auth/cloud-bigtable.admin",
                "https://www.googleapis.com/auth/cloud-bigtable.admin.cluster",
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only"
              ],
              "description": "Lists information about the supported locations for this service. This method lists locations based on the resource scope provided in the ListLocationsRequest.name field: * **Global locations**: If `name` is empty, the method lists the public locations available to all projects. * **Project-specific locations**: If `name` follows the format `projects/{project}`, the method lists locations visible to that specific project. This includes public, private, or other proj[...]",
              "flatPath": "v2/projects/{projectsId}/locations",
              "httpMethod": "GET",
              "path": "v2/{+name}/locations"
            }
          }
        }
      }
    }
  },
  "rootUrl": "https://bigtableadmin.googleapis.com/",
  "mtlsRootUrl": "https://bigtableadmin.mtls.googleapis.com/"
}