{
  "basePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/blogger": {
          "description": "Manage your Blogger account"
        },
        "https://www.googleapis.com/auth/blogger.readonly": {
          "description": "View your Blogger account"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "discoveryVersion": "v1",
  "canonicalName": "Blogger",
  "kind": "discovery#restDescription",
  "resources": {
    "pageViews": {
      "methods": {
        "get": {
          "id": "blogger.pageViews.get",
          "httpMethod": "GET",
          "flatPath": "v3/blogs/{blogId}/pageviews",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "description": "Gets page views by blog id.",
          "path": "v3/blogs/{blogId}/pageviews"
        }
      }
    },
    "comments": {
      "methods": {
        "delete": {
          "id": "blogger.comments.delete",
          "httpMethod": "DELETE",
          "flatPath": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "description": "Deletes a comment by blog id, post id and comment id.",
          "path": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}"
        },
        "get": {
          "httpMethod": "GET",
          "path": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}",
          "description": "Gets a comment by id.",
          "flatPath": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "id": "blogger.comments.get"
        },
        "list": {
          "id": "blogger.comments.list",
          "httpMethod": "GET",
          "flatPath": "v3/blogs/{blogId}/posts/{postId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "path": "v3/blogs/{blogId}/posts/{postId}/comments",
          "description": "Lists comments."
        },
        "markAsSpam": {
          "httpMethod": "POST",
          "flatPath": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/spam",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "path": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/spam",
          "description": "Marks a comment as spam by blog id, post id and comment id.",
          "id": "blogger.comments.markAsSpam"
        },
        "removeContent": {
          "id": "blogger.comments.removeContent",
          "flatPath": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/removecontent",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "description": "Removes the content of a comment by blog id, post id and comment id.",
          "path": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/removecontent",
          "httpMethod": "POST"
        },
        "approve": {
          "httpMethod": "POST",
          "description": "Marks a comment as not spam by blog id, post id and comment id.",
          "path": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/approve",
          "flatPath": "v3/blogs/{blogId}/posts/{postId}/comments/{commentId}/approve",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "id": "blogger.comments.approve"
        },
        "listByBlog": {
          "id": "blogger.comments.listByBlog",
          "flatPath": "v3/blogs/{blogId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "description": "Lists comments by blog.",
          "path": "v3/blogs/{blogId}/comments",
          "httpMethod": "GET"
        }
      }
    },
    "posts": {
      "methods": {
        "getByPath": {
          "flatPath": "v3/blogs/{blogId}/posts/bypath",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "path": "v3/blogs/{blogId}/posts/bypath",
          "description": "Gets a post by path.",
          "httpMethod": "GET",
          "id": "blogger.posts.getByPath"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "v3/blogs/{blogId}/posts",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "description": "Lists posts.",
          "path": "v3/blogs/{blogId}/posts",
          "id": "blogger.posts.list"
        },
        "insert": {
          "description": "Inserts a post.",
          "path": "v3/blogs/{blogId}/posts",
          "flatPath": "v3/blogs/{blogId}/posts",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "httpMethod": "POST",
          "id": "blogger.posts.insert"
        },
        "patch": {
          "description": "Patches a post.",
          "path": "v3/blogs/{blogId}/posts/{postId}",
          "flatPath": "v3/blogs/{blogId}/posts/{postId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "httpMethod": "PATCH",
          "id": "blogger.posts.patch"
        },
        "search": {
          "id": "blogger.posts.search",
          "description": "Searches for posts matching given query terms in the specified blog.",
          "path": "v3/blogs/{blogId}/posts/search",
          "flatPath": "v3/blogs/{blogId}/posts/search",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "id": "blogger.posts.update",
          "description": "Updates a post by blog id and post id.",
          "path": "v3/blogs/{blogId}/posts/{postId}",
          "flatPath": "v3/blogs/{blogId}/posts/{postId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "httpMethod": "PUT"
        },
        "delete": {
          "description": "Deletes a post by blog id and post id.",
          "path": "v3/blogs/{blogId}/posts/{postId}",
          "flatPath": "v3/blogs/{blogId}/posts/{postId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "httpMethod": "DELETE",
          "id": "blogger.posts.delete"
        },
        "revert": {
          "httpMethod": "POST",
          "description": "Reverts a published or scheduled post to draft state.",
          "path": "v3/blogs/{blogId}/posts/{postId}/revert",
          "flatPath": "v3/blogs/{blogId}/posts/{postId}/revert",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "id": "blogger.posts.revert"
        },
        "get": {
          "id": "blogger.posts.get",
          "flatPath": "v3/blogs/{blogId}/posts/{postId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "path": "v3/blogs/{blogId}/posts/{postId}",
          "description": "Gets a post by blog id and post id",
          "httpMethod": "GET"
        },
        "publish": {
          "id": "blogger.posts.publish",
          "httpMethod": "POST",
          "path": "v3/blogs/{blogId}/posts/{postId}/publish",
          "description": "Publishes a post.",
          "flatPath": "v3/blogs/{blogId}/posts/{postId}/publish",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ]
        }
      }
    },
    "blogUserInfos": {
      "methods": {
        "get": {
          "path": "v3/users/{userId}/blogs/{blogId}",
          "description": "Gets one blog and user info pair by blog id and user id.",
          "flatPath": "v3/users/{userId}/blogs/{blogId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "httpMethod": "GET",
          "id": "blogger.blogUserInfos.get"
        }
      }
    },
    "postUserInfos": {
      "methods": {
        "list": {
          "id": "blogger.postUserInfos.list",
          "description": "Lists post and user info pairs.",
          "path": "v3/users/{userId}/blogs/{blogId}/posts",
          "flatPath": "v3/users/{userId}/blogs/{blogId}/posts",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "httpMethod": "GET"
        },
        "get": {
          "id": "blogger.postUserInfos.get",
          "flatPath": "v3/users/{userId}/blogs/{blogId}/posts/{postId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "description": "Gets one post and user info pair, by post_id and user_id.",
          "path": "v3/users/{userId}/blogs/{blogId}/posts/{postId}",
          "httpMethod": "GET"
        }
      }
    },
    "blogs": {
      "methods": {
        "listByUser": {
          "httpMethod": "GET",
          "flatPath": "v3/users/{userId}/blogs",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "description": "Lists blogs by user.",
          "path": "v3/users/{userId}/blogs",
          "id": "blogger.blogs.listByUser"
        },
        "getByUrl": {
          "description": "Gets a blog by url.",
          "path": "v3/blogs/byurl",
          "flatPath": "v3/blogs/byurl",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "httpMethod": "GET",
          "id": "blogger.blogs.getByUrl"
        },
        "get": {
          "flatPath": "v3/blogs/{blogId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "path": "v3/blogs/{blogId}",
          "description": "Gets a blog by id.",
          "httpMethod": "GET",
          "id": "blogger.blogs.get"
        }
      }
    },
    "pages": {
      "methods": {
        "delete": {
          "id": "blogger.pages.delete",
          "httpMethod": "DELETE",
          "flatPath": "v3/blogs/{blogId}/pages/{pageId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "path": "v3/blogs/{blogId}/pages/{pageId}",
          "description": "Deletes a page by blog id and page id."
        },
        "revert": {
          "flatPath": "v3/blogs/{blogId}/pages/{pageId}/revert",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "description": "Reverts a published or scheduled page to draft state.",
          "path": "v3/blogs/{blogId}/pages/{pageId}/revert",
          "httpMethod": "POST",
          "id": "blogger.pages.revert"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a page by blog id and page id.",
          "path": "v3/blogs/{blogId}/pages/{pageId}",
          "flatPath": "v3/blogs/{blogId}/pages/{pageId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "id": "blogger.pages.get"
        },
        "update": {
          "id": "blogger.pages.update",
          "path": "v3/blogs/{blogId}/pages/{pageId}",
          "description": "Updates a page by blog id and page id.",
          "flatPath": "v3/blogs/{blogId}/pages/{pageId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "httpMethod": "PUT"
        },
        "list": {
          "id": "blogger.pages.list",
          "flatPath": "v3/blogs/{blogId}/pages",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "description": "Lists pages.",
          "path": "v3/blogs/{blogId}/pages",
          "httpMethod": "GET"
        },
        "publish": {
          "flatPath": "v3/blogs/{blogId}/pages/{pageId}/publish",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "path": "v3/blogs/{blogId}/pages/{pageId}/publish",
          "description": "Publishes a page.",
          "httpMethod": "POST",
          "id": "blogger.pages.publish"
        },
        "insert": {
          "id": "blogger.pages.insert",
          "flatPath": "v3/blogs/{blogId}/pages",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "path": "v3/blogs/{blogId}/pages",
          "description": "Inserts a page.",
          "httpMethod": "POST"
        },
        "patch": {
          "path": "v3/blogs/{blogId}/pages/{pageId}",
          "description": "Patches a page.",
          "flatPath": "v3/blogs/{blogId}/pages/{pageId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger"
          ],
          "httpMethod": "PATCH",
          "id": "blogger.pages.patch"
        }
      }
    },
    "users": {
      "methods": {
        "get": {
          "id": "blogger.users.get",
          "path": "v3/users/{userId}",
          "description": "Gets one user by user_id.",
          "flatPath": "v3/users/{userId}",
          "scopes": [
            "https://www.googleapis.com/auth/blogger",
            "https://www.googleapis.com/auth/blogger.readonly"
          ],
          "httpMethod": "GET"
        }
      }
    }
  },
  "revision": "20260401",
  "baseUrl": "https://blogger.googleapis.com/",
  "ownerDomain": "google.com",
  "version": "v3",
  "servicePath": "",
  "rootUrl": "https://blogger.googleapis.com/",
  "description": "The Blogger API provides access to posts, comments and pages of a Blogger blog.",
  "ownerName": "Google",
  "protocol": "rest",
  "name": "blogger",
  "documentationLink": "https://developers.google.com/blogger/docs/3.0/getting_started",
  "batchPath": "batch",
  "mtlsRootUrl": "https://blogger.mtls.googleapis.com/",
  "id": "blogger:v3",
  "title": "Blogger API"
}