{
  "name": "chromemanagement",
  "revision": "20260424",
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "protocol": "rest",
  "canonicalName": "Chrome Management",
  "version_module": true,
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "servicePath": "",
  "id": "chromemanagement:v1",
  "basePath": "",
  "documentationLink": "https://developers.google.com/chrome/management/",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "title": "Chrome Management API",
  "version": "v1",
  "batchPath": "batch",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        }
      }
    }
  },
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "ownerName": "Google",
  "resources": {
    "customers": {
      "resources": {
        "certificateProvisioningProcesses": {
          "methods": {
            "claim": {
              "httpMethod": "POST",
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim",
              "path": "v1/{+name}:claim"
            },
            "get": {
              "path": "v1/{+name}",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}",
              "httpMethod": "GET",
              "description": "Retrieves a certificate provisioning process."
            },
            "setFailure": {
              "path": "v1/{+name}:setFailure",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "httpMethod": "POST",
              "description": "Marks a certificate provisioning process as failed.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure"
            },
            "signData": {
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "httpMethod": "POST",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed.",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "path": "v1/{+name}:signData"
            },
            "uploadCertificate": {
              "path": "v1/{+name}:uploadCertificate",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate",
              "httpMethod": "POST",
              "description": "Uploads a successfully issued certificate for a certificate provisioning process.",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate"
            }
          },
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}",
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "path": "v1/{+name}"
                }
              }
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "httpMethod": "POST",
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU.",
              "path": "v1/{+name}:move"
            }
          }
        },
        "telemetry": {
          "resources": {
            "notificationConfigs": {
              "methods": {
                "delete": {
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "description": "Delete a telemetry notification config.",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete"
                },
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "httpMethod": "GET",
                  "description": "List all telemetry notification configs.",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/notificationConfigs"
                },
                "create": {
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "httpMethod": "POST",
                  "description": "Create a telemetry notification config."
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "description": "List all telemetry users.",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/users"
                },
                "get": {
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "httpMethod": "GET",
                  "description": "Get telemetry user.",
                  "path": "v1/{+name}"
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/telemetry/events",
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "httpMethod": "GET",
                  "description": "List telemetry events.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.events.list"
                }
              }
            },
            "devices": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/telemetry/devices",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "httpMethod": "GET",
                  "description": "List all telemetry devices."
                },
                "get": {
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "description": "Get telemetry device.",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                }
              }
            }
          }
        },
        "apps": {
          "methods": {
            "countChromeAppRequests": {
              "httpMethod": "GET",
              "description": "Generate summary of app installation requests.",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "path": "v1/{+customer}/apps:countChromeAppRequests"
            },
            "fetchDevicesRequestingExtension": {
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "httpMethod": "GET",
              "description": "Get a list of devices that have requested to install an extension."
            },
            "fetchUsersRequestingExtension": {
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "httpMethod": "GET",
              "description": "Get a list of users that have requested to install an extension."
            }
          },
          "resources": {
            "chrome": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "path": "v1/{+name}"
                }
              }
            },
            "android": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "id": "chromemanagement.customers.apps.android.get",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "path": "v1/{+name}"
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "id": "chromemanagement.customers.apps.web.get",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            }
          }
        },
        "profiles": {
          "resources": {
            "commands": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "description": "Lists remote commands of a Chrome browser profile.",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "path": "v1/{+parent}/commands"
                },
                "get": {
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}",
                  "httpMethod": "GET",
                  "description": "Gets a Chrome browser profile remote command.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "path": "v1/{+name}"
                },
                "create": {
                  "path": "v1/{+parent}/commands",
                  "httpMethod": "POST",
                  "description": "Creates a Chrome browser profile remote command.",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "id": "chromemanagement.customers.profiles.commands.create"
                }
              }
            }
          },
          "methods": {
            "get": {
              "path": "v1/{+name}",
              "id": "chromemanagement.customers.profiles.get",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "httpMethod": "GET",
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID.",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}"
            },
            "delete": {
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "id": "chromemanagement.customers.profiles.delete",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "httpMethod": "DELETE",
              "description": "Deletes the data collected from a Chrome browser profile."
            },
            "list": {
              "id": "chromemanagement.customers.profiles.list",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria.",
              "flatPath": "v1/customers/{customersId}/profiles",
              "path": "v1/{+parent}/profiles"
            }
          }
        },
        "reports": {
          "methods": {
            "enumeratePrintJobs": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "httpMethod": "GET",
              "description": "Get a list of print jobs.",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "path": "v1/{+customer}/reports:enumeratePrintJobs"
            },
            "countChromeBrowsersNeedingAttention": {
              "httpMethod": "GET",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention"
            },
            "countChromeCrashEvents": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents",
              "httpMethod": "GET",
              "description": "Get a count of Chrome crash events.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "path": "v1/{+customer}/reports:countChromeCrashEvents"
            },
            "countChromeHardwareFleetDevices": {
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "httpMethod": "GET",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countPrintJobsByPrinter": {
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Get a summary of printing done by each printer.",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter"
            },
            "countPrintJobsByUser": {
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "httpMethod": "GET",
              "description": "Get a summary of printing done by each user.",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countDevicesPerReleaseChannel": {
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "httpMethod": "GET",
              "description": "Get a count of devices per channel.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel"
            },
            "countChromeVersions": {
              "httpMethod": "GET",
              "description": "Generate report of installed Chrome versions.",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "path": "v1/{+customer}/reports:countChromeVersions"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "httpMethod": "GET",
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate"
            },
            "countActiveDevices": {
              "httpMethod": "GET",
              "description": "Get a count of active devices per set time frames.",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "path": "v1/{+customer}/reports:countActiveDevices"
            },
            "countChromeDevicesThatNeedAttention": {
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "httpMethod": "GET",
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947"
            },
            "findInstalledAppDevices": {
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "httpMethod": "GET",
              "description": "Generate report of managed Chrome browser devices that have a specified app installed."
            },
            "countInstalledApps": {
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "httpMethod": "GET",
              "description": "Generate report of app installations.",
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countInstalledApps"
            },
            "countDevicesPerBootType": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "httpMethod": "GET",
              "description": "Get a count of devices per boot type.",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType",
              "path": "v1/{+customer}/reports:countDevicesPerBootType"
            }
          }
        },
        "connectorConfigs": {
          "methods": {
            "delete": {
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a connector config.",
              "id": "chromemanagement.customers.connectorConfigs.delete",
              "path": "v1/{+name}"
            },
            "create": {
              "path": "v1/{+parent}/connectorConfigs",
              "httpMethod": "POST",
              "description": "Creates a connector config.",
              "flatPath": "v1/customers/{customersId}/connectorConfigs",
              "id": "chromemanagement.customers.connectorConfigs.create"
            },
            "get": {
              "id": "chromemanagement.customers.connectorConfigs.get",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "httpMethod": "GET",
              "description": "Gets a connector config with customer ID and config ID."
            },
            "patch": {
              "id": "chromemanagement.customers.connectorConfigs.patch",
              "httpMethod": "PATCH",
              "description": "Updates a connector config.",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "path": "v1/{+name}"
            },
            "list": {
              "path": "v1/{+parent}/connectorConfigs",
              "id": "chromemanagement.customers.connectorConfigs.list",
              "flatPath": "v1/customers/{customersId}/connectorConfigs",
              "httpMethod": "GET",
              "description": "Lists connector configs of a customer."
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "flatPath": "v1/operations/{operationsId}",
          "id": "chromemanagement.operations.delete",
          "path": "v1/{+name}"
        },
        "cancel": {
          "httpMethod": "POST",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "id": "chromemanagement.operations.cancel",
          "path": "v1/{+name}:cancel"
        },
        "list": {
          "flatPath": "v1/operations",
          "httpMethod": "GET",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "id": "chromemanagement.operations.list",
          "path": "v1/{+name}"
        }
      }
    }
  }
}