{
  "name": "chromemanagement",
  "title": "Chrome Management API",
  "servicePath": "",
  "version": "v1",
  "discoveryVersion": "v1",
  "basePath": "",
  "version_module": true,
  "revision": "20260310",
  "canonicalName": "Chrome Management",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "kind": "discovery#restDescription",
  "documentationLink": "https://developers.google.com/chrome/management/",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "id": "chromemanagement:v1",
  "protocol": "rest",
  "ownerName": "Google",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "resources": {
    "customers": {
      "resources": {
        "reports": {
          "methods": {
            "findInstalledAppDevices": {
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate"
            },
            "countActiveDevices": {
              "description": "Get a count of active devices per set time frames.",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countActiveDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices"
            },
            "countPrintJobsByUser": {
              "description": "Get a summary of printing done by each user.",
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser"
            },
            "countChromeBrowsersNeedingAttention": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "httpMethod": "GET",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity."
            },
            "countDevicesPerBootType": {
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType",
              "description": "Get a count of devices per boot type."
            },
            "countChromeDevicesThatNeedAttention": {
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention"
            },
            "countPrintJobsByPrinter": {
              "description": "Get a summary of printing done by each printer.",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter"
            },
            "countInstalledApps": {
              "description": "Generate report of app installations.",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps"
            },
            "countChromeVersions": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "description": "Generate report of installed Chrome versions."
            },
            "countChromeCrashEvents": {
              "description": "Get a count of Chrome crash events.",
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents",
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeCrashEvents"
            },
            "countChromeHardwareFleetDevices": {
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947"
            },
            "enumeratePrintJobs": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "description": "Get a list of print jobs."
            },
            "countDevicesPerReleaseChannel": {
              "description": "Get a count of devices per channel.",
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "path": "v1/{+name}:move",
              "httpMethod": "POST",
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU."
            }
          }
        },
        "apps": {
          "resources": {
            "android": {
              "methods": {
                "get": {
                  "description": "Get a specific app for a customer by its resource name.",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "id": "chromemanagement.customers.apps.android.get",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}"
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "description": "Get a specific app for a customer by its resource name.",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ]
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.web.get",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            }
          },
          "methods": {
            "fetchUsersRequestingExtension": {
              "description": "Get a list of users that have requested to install an extension.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension"
            },
            "countChromeAppRequests": {
              "description": "Generate summary of app installation requests.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "id": "chromemanagement.customers.apps.countChromeAppRequests"
            },
            "fetchDevicesRequestingExtension": {
              "description": "Get a list of devices that have requested to install an extension.",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "httpMethod": "GET"
            }
          }
        },
        "telemetry": {
          "resources": {
            "events": {
              "methods": {
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/telemetry/events",
                  "description": "List telemetry events."
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "path": "v1/{+parent}/telemetry/users",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry users."
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "description": "Get telemetry user."
                }
              }
            },
            "notificationConfigs": {
              "methods": {
                "create": {
                  "description": "Create a telemetry notification config.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "httpMethod": "POST",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create"
                },
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "description": "List all telemetry notification configs."
                },
                "delete": {
                  "description": "Delete a telemetry notification config.",
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}"
                }
              }
            },
            "devices": {
              "methods": {
                "list": {
                  "description": "List all telemetry devices.",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "path": "v1/{+parent}/telemetry/devices",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "get": {
                  "description": "Get telemetry device.",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}"
                }
              }
            }
          }
        },
        "profiles": {
          "resources": {
            "commands": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}",
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "description": "Gets a Chrome browser profile remote command."
                },
                "list": {
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "path": "v1/{+parent}/commands",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "description": "Lists remote commands of a Chrome browser profile."
                },
                "create": {
                  "description": "Creates a Chrome browser profile remote command.",
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/commands",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ]
                }
              }
            }
          },
          "methods": {
            "get": {
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID.",
              "id": "chromemanagement.customers.profiles.get",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ]
            },
            "list": {
              "id": "chromemanagement.customers.profiles.list",
              "flatPath": "v1/customers/{customersId}/profiles",
              "httpMethod": "GET",
              "path": "v1/{+parent}/profiles",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria."
            },
            "delete": {
              "description": "Deletes the data collected from a Chrome browser profile.",
              "path": "v1/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "id": "chromemanagement.customers.profiles.delete",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}"
            }
          }
        },
        "certificateProvisioningProcesses": {
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}",
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                }
              }
            }
          },
          "methods": {
            "claim": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim",
              "httpMethod": "POST",
              "path": "v1/{+name}:claim",
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`."
            },
            "signData": {
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed.",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "path": "v1/{+name}:signData",
              "httpMethod": "POST"
            },
            "get": {
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "description": "Retrieves a certificate provisioning process."
            },
            "setFailure": {
              "path": "v1/{+name}:setFailure",
              "httpMethod": "POST",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure",
              "description": "Marks a certificate provisioning process as failed."
            },
            "uploadCertificate": {
              "path": "v1/{+name}:uploadCertificate",
              "httpMethod": "POST",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate",
              "description": "Uploads a successfully issued certificate for a certificate provisioning process."
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "id": "chromemanagement.operations.cancel",
          "path": "v1/{+name}:cancel",
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "v1/operations",
          "id": "chromemanagement.operations.list",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "httpMethod": "GET",
          "path": "v1/{+name}"
        },
        "delete": {
          "flatPath": "v1/operations/{operationsId}",
          "id": "chromemanagement.operations.delete",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "path": "v1/{+name}",
          "httpMethod": "DELETE"
        }
      }
    }
  }
}