{
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "batchPath": "batch",
  "id": "chromemanagement:v1",
  "resources": {
    "operations": {
      "methods": {
        "delete": {
          "flatPath": "v1/operations/{operationsId}",
          "id": "chromemanagement.operations.delete",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "path": "v1/{+name}",
          "httpMethod": "DELETE"
        },
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "httpMethod": "POST",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "id": "chromemanagement.operations.cancel",
          "path": "v1/{+name}:cancel"
        },
        "list": {
          "flatPath": "v1/operations",
          "id": "chromemanagement.operations.list",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "path": "v1/{+name}",
          "httpMethod": "GET"
        }
      }
    },
    "customers": {
      "resources": {
        "profiles": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria.",
              "flatPath": "v1/customers/{customersId}/profiles",
              "id": "chromemanagement.customers.profiles.list",
              "path": "v1/{+parent}/profiles"
            },
            "get": {
              "path": "v1/{+name}",
              "id": "chromemanagement.customers.profiles.get",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "description": "Deletes the data collected from a Chrome browser profile.",
              "httpMethod": "DELETE",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "id": "chromemanagement.customers.profiles.delete",
              "path": "v1/{+name}"
            }
          },
          "resources": {
            "commands": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "description": "Lists remote commands of a Chrome browser profile.",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "path": "v1/{+parent}/commands"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates a Chrome browser profile remote command.",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "path": "v1/{+parent}/commands",
                  "id": "chromemanagement.customers.profiles.commands.create"
                },
                "get": {
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}",
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Gets a Chrome browser profile remote command."
                }
              }
            }
          }
        },
        "telemetry": {
          "resources": {
            "devices": {
              "methods": {
                "get": {
                  "description": "Get telemetry device.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}"
                },
                "list": {
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "path": "v1/{+parent}/telemetry/devices",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "httpMethod": "GET",
                  "description": "List all telemetry devices.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                }
              }
            },
            "users": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Get telemetry user.",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "path": "v1/{+name}"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "List all telemetry users.",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "path": "v1/{+parent}/telemetry/users",
                  "id": "chromemanagement.customers.telemetry.users.list"
                }
              }
            },
            "notificationConfigs": {
              "methods": {
                "delete": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "httpMethod": "DELETE",
                  "description": "Delete a telemetry notification config.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "create": {
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "Create a telemetry notification config.",
                  "httpMethod": "POST"
                },
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "List all telemetry notification configs."
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "List telemetry events.",
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "path": "v1/{+parent}/telemetry/events",
                  "id": "chromemanagement.customers.telemetry.events.list"
                }
              }
            }
          }
        },
        "connectorConfigs": {
          "methods": {
            "list": {
              "flatPath": "v1/customers/{customersId}/connectorConfigs",
              "id": "chromemanagement.customers.connectorConfigs.list",
              "description": "Lists connector configs of a customer.",
              "path": "v1/{+parent}/connectorConfigs",
              "httpMethod": "GET"
            },
            "patch": {
              "description": "Updates a connector config.",
              "httpMethod": "PATCH",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "id": "chromemanagement.customers.connectorConfigs.patch",
              "path": "v1/{+name}"
            },
            "get": {
              "id": "chromemanagement.customers.connectorConfigs.get",
              "description": "Gets a connector config with customer ID and config ID.",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}"
            },
            "create": {
              "flatPath": "v1/customers/{customersId}/connectorConfigs",
              "id": "chromemanagement.customers.connectorConfigs.create",
              "path": "v1/{+parent}/connectorConfigs",
              "httpMethod": "POST",
              "description": "Creates a connector config."
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v1/{+name}",
              "id": "chromemanagement.customers.connectorConfigs.delete",
              "description": "Deletes a connector config.",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}"
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "path": "v1/{+name}:move",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "httpMethod": "POST",
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU."
            }
          }
        },
        "apps": {
          "methods": {
            "countChromeAppRequests": {
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "httpMethod": "GET",
              "description": "Generate summary of app installation requests."
            },
            "fetchDevicesRequestingExtension": {
              "httpMethod": "GET",
              "description": "Get a list of devices that have requested to install an extension.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension"
            },
            "fetchUsersRequestingExtension": {
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "description": "Get a list of users that have requested to install an extension.",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "chrome": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "android": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.apps.android.get",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}"
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "description": "Get a specific app for a customer by its resource name.",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.apps.web.get"
                }
              }
            }
          }
        },
        "reports": {
          "methods": {
            "countChromeBrowsersNeedingAttention": {
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention"
            },
            "countInstalledApps": {
              "path": "v1/{+customer}/reports:countInstalledApps",
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "httpMethod": "GET",
              "description": "Generate report of app installations.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countPrintJobsByPrinter": {
              "httpMethod": "GET",
              "description": "Get a summary of printing done by each printer.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter"
            },
            "countDevicesPerBootType": {
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType",
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a count of devices per boot type.",
              "httpMethod": "GET"
            },
            "countDevicesPerReleaseChannel": {
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Get a count of devices per channel."
            },
            "countChromeDevicesThatNeedAttention": {
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeHardwareFleetDevices": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices"
            },
            "enumeratePrintJobs": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Get a list of print jobs.",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "id": "chromemanagement.customers.reports.enumeratePrintJobs"
            },
            "countChromeVersions": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Generate report of installed Chrome versions."
            },
            "countActiveDevices": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Get a count of active devices per set time frames.",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices",
              "path": "v1/{+customer}/reports:countActiveDevices",
              "id": "chromemanagement.customers.reports.countActiveDevices"
            },
            "countChromeCrashEvents": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents",
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "path": "v1/{+customer}/reports:countChromeCrashEvents",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a count of Chrome crash events.",
              "httpMethod": "GET"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate"
            },
            "findInstalledAppDevices": {
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "httpMethod": "GET"
            },
            "countPrintJobsByUser": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a summary of printing done by each user.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "path": "v1/{+customer}/reports:countPrintJobsByUser"
            }
          }
        },
        "certificateProvisioningProcesses": {
          "methods": {
            "claim": {
              "path": "v1/{+name}:claim",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim",
              "httpMethod": "POST",
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`."
            },
            "get": {
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}",
              "httpMethod": "GET",
              "path": "v1/{+name}",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "description": "Retrieves a certificate provisioning process."
            },
            "uploadCertificate": {
              "description": "Uploads a successfully issued certificate for a certificate provisioning process.",
              "httpMethod": "POST",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate",
              "path": "v1/{+name}:uploadCertificate",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate"
            },
            "setFailure": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "path": "v1/{+name}:setFailure",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure",
              "description": "Marks a certificate provisioning process as failed.",
              "httpMethod": "POST"
            },
            "signData": {
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "path": "v1/{+name}:signData",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed.",
              "httpMethod": "POST"
            }
          },
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}"
                }
              }
            }
          }
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        }
      }
    }
  },
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "canonicalName": "Chrome Management",
  "version_module": true,
  "ownerName": "Google",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "basePath": "",
  "version": "v1",
  "fullyEncodeReservedExpansion": true,
  "protocol": "rest",
  "documentationLink": "https://developers.google.com/chrome/management/",
  "name": "chromemanagement",
  "title": "Chrome Management API",
  "ownerDomain": "google.com",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "revision": "20260501",
  "servicePath": ""
}