{
  "id": "chromemanagement:v1",
  "canonicalName": "Chrome Management",
  "servicePath": "",
  "fullyEncodeReservedExpansion": true,
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "version_module": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        }
      }
    }
  },
  "basePath": "",
  "version": "v1",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "revision": "20260421",
  "documentationLink": "https://developers.google.com/chrome/management/",
  "batchPath": "batch",
  "protocol": "rest",
  "ownerDomain": "google.com",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "discoveryVersion": "v1",
  "resources": {
    "operations": {
      "methods": {
        "delete": {
          "flatPath": "v1/operations/{operationsId}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "id": "chromemanagement.operations.delete",
          "path": "v1/{+name}",
          "httpMethod": "DELETE"
        },
        "cancel": {
          "flatPath": "v1/operations/{operationsId}:cancel",
          "httpMethod": "POST",
          "id": "chromemanagement.operations.cancel",
          "path": "v1/{+name}:cancel",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]"
        },
        "list": {
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "id": "chromemanagement.operations.list",
          "path": "v1/{+name}",
          "httpMethod": "GET",
          "flatPath": "v1/operations"
        }
      }
    },
    "customers": {
      "resources": {
        "telemetry": {
          "resources": {
            "events": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "path": "v1/{+parent}/telemetry/events",
                  "description": "List telemetry events."
                }
              }
            },
            "devices": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "path": "v1/{+name}",
                  "description": "Get telemetry device.",
                  "httpMethod": "GET"
                },
                "list": {
                  "httpMethod": "GET",
                  "description": "List all telemetry devices.",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "path": "v1/{+parent}/telemetry/devices",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/devices"
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "description": "List all telemetry users.",
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "path": "v1/{+parent}/telemetry/users",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "get": {
                  "description": "Get telemetry user.",
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                }
              }
            },
            "notificationConfigs": {
              "methods": {
                "create": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "description": "Create a telemetry notification config.",
                  "httpMethod": "POST",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "delete": {
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "path": "v1/{+name}",
                  "description": "Delete a telemetry notification config.",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "description": "List all telemetry notification configs.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs"
                }
              }
            }
          }
        },
        "reports": {
          "methods": {
            "enumeratePrintJobs": {
              "description": "Get a list of print jobs.",
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeCrashEvents": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "path": "v1/{+customer}/reports:countChromeCrashEvents",
              "description": "Get a count of Chrome crash events.",
              "httpMethod": "GET"
            },
            "countChromeHardwareFleetDevices": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947"
            },
            "countDevicesPerReleaseChannel": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "httpMethod": "GET",
              "description": "Get a count of devices per channel.",
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel"
            },
            "countChromeBrowsersNeedingAttention": {
              "httpMethod": "GET",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.",
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention"
            },
            "countPrintJobsByUser": {
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "description": "Get a summary of printing done by each user.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser"
            },
            "countInstalledApps": {
              "httpMethod": "GET",
              "description": "Generate report of app installations.",
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps"
            },
            "findInstalledAppDevices": {
              "httpMethod": "GET",
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices"
            },
            "countActiveDevices": {
              "httpMethod": "GET",
              "description": "Get a count of active devices per set time frames.",
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "path": "v1/{+customer}/reports:countActiveDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices"
            },
            "countChromeDevicesThatNeedAttention": {
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countPrintJobsByPrinter": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "httpMethod": "GET",
              "description": "Get a summary of printing done by each printer.",
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter"
            },
            "countDevicesPerBootType": {
              "httpMethod": "GET",
              "description": "Get a count of devices per boot type.",
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType"
            },
            "countChromeVersions": {
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "description": "Generate report of installed Chrome versions.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "httpMethod": "GET",
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate"
            }
          }
        },
        "connectorConfigs": {
          "methods": {
            "delete": {
              "id": "chromemanagement.customers.connectorConfigs.delete",
              "path": "v1/{+name}",
              "description": "Deletes a connector config.",
              "httpMethod": "DELETE",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}"
            },
            "create": {
              "httpMethod": "POST",
              "id": "chromemanagement.customers.connectorConfigs.create",
              "path": "v1/{+parent}/connectorConfigs",
              "description": "Creates a connector config.",
              "flatPath": "v1/customers/{customersId}/connectorConfigs"
            },
            "get": {
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "id": "chromemanagement.customers.connectorConfigs.get",
              "path": "v1/{+name}",
              "description": "Gets a connector config with customer ID and config ID.",
              "httpMethod": "GET"
            },
            "list": {
              "flatPath": "v1/customers/{customersId}/connectorConfigs",
              "httpMethod": "GET",
              "description": "Lists connector configs of a customer.",
              "id": "chromemanagement.customers.connectorConfigs.list",
              "path": "v1/{+parent}/connectorConfigs"
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "httpMethod": "POST",
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "path": "v1/{+name}:move",
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move"
            }
          }
        },
        "profiles": {
          "resources": {
            "commands": {
              "methods": {
                "get": {
                  "description": "Gets a Chrome browser profile remote command.",
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ]
                },
                "list": {
                  "description": "Lists remote commands of a Chrome browser profile.",
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "path": "v1/{+parent}/commands",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ]
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "path": "v1/{+parent}/commands",
                  "description": "Creates a Chrome browser profile remote command.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands"
                }
              }
            }
          },
          "methods": {
            "list": {
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria.",
              "id": "chromemanagement.customers.profiles.list",
              "path": "v1/{+parent}/profiles",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/profiles",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.profiles.get",
              "path": "v1/{+name}",
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID."
            },
            "delete": {
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "id": "chromemanagement.customers.profiles.delete",
              "path": "v1/{+name}",
              "description": "Deletes the data collected from a Chrome browser profile.",
              "httpMethod": "DELETE"
            }
          }
        },
        "certificateProvisioningProcesses": {
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "path": "v1/{+name}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                }
              }
            }
          },
          "methods": {
            "get": {
              "httpMethod": "GET",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "path": "v1/{+name}",
              "description": "Retrieves a certificate provisioning process.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}"
            },
            "signData": {
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "httpMethod": "POST",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "path": "v1/{+name}:signData",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed."
            },
            "claim": {
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`.",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim",
              "path": "v1/{+name}:claim",
              "httpMethod": "POST",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim"
            },
            "uploadCertificate": {
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate",
              "description": "Uploads a successfully issued certificate for a certificate provisioning process.",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate",
              "path": "v1/{+name}:uploadCertificate",
              "httpMethod": "POST"
            },
            "setFailure": {
              "httpMethod": "POST",
              "description": "Marks a certificate provisioning process as failed.",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "path": "v1/{+name}:setFailure",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure"
            }
          }
        },
        "apps": {
          "methods": {
            "fetchDevicesRequestingExtension": {
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "description": "Get a list of devices that have requested to install an extension.",
              "httpMethod": "GET"
            },
            "countChromeAppRequests": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "httpMethod": "GET",
              "description": "Generate summary of app installation requests.",
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "path": "v1/{+customer}/apps:countChromeAppRequests"
            },
            "fetchUsersRequestingExtension": {
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "description": "Get a list of users that have requested to install an extension.",
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "web": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.apps.web.get",
                  "path": "v1/{+name}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}"
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "path": "v1/{+name}",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "android": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.apps.android.get",
                  "path": "v1/{+name}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}"
                }
              }
            }
          }
        }
      }
    }
  },
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "title": "Chrome Management API",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "name": "chromemanagement"
}