{
  "fullyEncodeReservedExpansion": true,
  "title": "Chrome Management API",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "revision": "20260413",
  "discoveryVersion": "v1",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "id": "chromemanagement:v1",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "documentationLink": "https://developers.google.com/chrome/management/",
  "ownerName": "Google",
  "canonicalName": "Chrome Management",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        }
      }
    }
  },
  "basePath": "",
  "kind": "discovery#restDescription",
  "name": "chromemanagement",
  "batchPath": "batch",
  "version_module": true,
  "resources": {
    "customers": {
      "resources": {
        "reports": {
          "methods": {
            "countDevicesPerBootType": {
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "description": "Get a count of devices per boot type.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType"
            },
            "countDevicesPerReleaseChannel": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a count of devices per channel.",
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "httpMethod": "GET"
            },
            "countInstalledApps": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of app installations.",
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "path": "v1/{+customer}/reports:countInstalledApps"
            },
            "countChromeBrowsersNeedingAttention": {
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention"
            },
            "countChromeVersions": {
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of installed Chrome versions.",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions"
            },
            "countChromeDevicesThatNeedAttention": {
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "httpMethod": "GET"
            },
            "countChromeCrashEvents": {
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a count of Chrome crash events.",
              "path": "v1/{+customer}/reports:countChromeCrashEvents",
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents",
              "httpMethod": "GET"
            },
            "countPrintJobsByUser": {
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "description": "Get a summary of printing done by each user.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "httpMethod": "GET"
            },
            "countActiveDevices": {
              "path": "v1/{+customer}/reports:countActiveDevices",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a count of active devices per set time frames."
            },
            "enumeratePrintJobs": {
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a list of print jobs.",
              "id": "chromemanagement.customers.reports.enumeratePrintJobs"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "httpMethod": "GET"
            },
            "countPrintJobsByPrinter": {
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a summary of printing done by each printer."
            },
            "findInstalledAppDevices": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "httpMethod": "GET"
            },
            "countChromeHardwareFleetDevices": {
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices"
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "path": "v1/{+name}:move",
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "httpMethod": "POST",
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ]
            }
          }
        },
        "certificateProvisioningProcesses": {
          "methods": {
            "get": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}",
              "description": "Retrieves a certificate provisioning process.",
              "httpMethod": "GET"
            },
            "signData": {
              "httpMethod": "POST",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "path": "v1/{+name}:signData",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed.",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData"
            },
            "setFailure": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "description": "Marks a certificate provisioning process as failed.",
              "path": "v1/{+name}:setFailure",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure",
              "httpMethod": "POST"
            },
            "claim": {
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim",
              "path": "v1/{+name}:claim",
              "httpMethod": "POST",
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`.",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim"
            },
            "uploadCertificate": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate",
              "description": "Uploads a successfully issued certificate for a certificate provisioning process.",
              "httpMethod": "POST",
              "path": "v1/{+name}:uploadCertificate",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate"
            }
          },
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "telemetry": {
          "resources": {
            "notificationConfigs": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry notification configs.",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "httpMethod": "GET"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "Delete a telemetry notification config.",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "path": "v1/{+name}"
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "description": "Create a telemetry notification config.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                }
              }
            },
            "devices": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/telemetry/devices",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry devices."
                },
                "get": {
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "description": "Get telemetry device.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/telemetry/events",
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "description": "List telemetry events.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "path": "v1/{+parent}/telemetry/users",
                  "httpMethod": "GET",
                  "description": "List all telemetry users.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.users.list"
                },
                "get": {
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "path": "v1/{+name}",
                  "description": "Get telemetry user.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.users.get"
                }
              }
            }
          }
        },
        "apps": {
          "resources": {
            "android": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.android.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "description": "Get a specific app for a customer by its resource name.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "httpMethod": "GET"
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ]
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.web.get",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "httpMethod": "GET"
                }
              }
            }
          },
          "methods": {
            "fetchDevicesRequestingExtension": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "description": "Get a list of devices that have requested to install an extension.",
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension"
            },
            "countChromeAppRequests": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "description": "Generate summary of app installation requests.",
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "httpMethod": "GET"
            },
            "fetchUsersRequestingExtension": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "description": "Get a list of users that have requested to install an extension.",
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "httpMethod": "GET"
            }
          }
        },
        "profiles": {
          "resources": {
            "commands": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "description": "Gets a Chrome browser profile remote command.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}"
                },
                "list": {
                  "description": "Lists remote commands of a Chrome browser profile.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "path": "v1/{+parent}/commands"
                },
                "create": {
                  "description": "Creates a Chrome browser profile remote command.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "httpMethod": "POST",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "path": "v1/{+parent}/commands"
                }
              }
            }
          },
          "methods": {
            "delete": {
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "httpMethod": "DELETE",
              "id": "chromemanagement.customers.profiles.delete",
              "description": "Deletes the data collected from a Chrome browser profile.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ]
            },
            "get": {
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "id": "chromemanagement.customers.profiles.get",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "path": "v1/{+name}"
            },
            "list": {
              "path": "v1/{+parent}/profiles",
              "flatPath": "v1/customers/{customersId}/profiles",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.profiles.list",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria."
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "delete": {
          "flatPath": "v1/operations/{operationsId}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "id": "chromemanagement.operations.delete",
          "path": "v1/{+name}",
          "httpMethod": "DELETE"
        },
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "id": "chromemanagement.operations.cancel",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "path": "v1/{+name}:cancel",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "id": "chromemanagement.operations.list",
          "path": "v1/{+name}",
          "flatPath": "v1/operations",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
        }
      }
    }
  },
  "servicePath": "",
  "version": "v1",
  "protocol": "rest"
}