{
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "ownerName": "Google",
  "servicePath": "",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "batchPath": "batch",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "ownerDomain": "google.com",
  "canonicalName": "Chrome Management",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "protocol": "rest",
  "version": "v1",
  "documentationLink": "https://developers.google.com/chrome/management/",
  "name": "chromemanagement",
  "discoveryVersion": "v1",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        }
      }
    }
  },
  "title": "Chrome Management API",
  "kind": "discovery#restDescription",
  "basePath": "",
  "resources": {
    "customers": {
      "resources": {
        "apps": {
          "methods": {
            "countChromeAppRequests": {
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "description": "Generate summary of app installation requests."
            },
            "fetchDevicesRequestingExtension": {
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "description": "Get a list of devices that have requested to install an extension."
            },
            "fetchUsersRequestingExtension": {
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "description": "Get a list of users that have requested to install an extension."
            }
          },
          "resources": {
            "chrome": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "android": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.android.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.web.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            }
          }
        },
        "reports": {
          "methods": {
            "countChromeDevicesReachingAutoExpirationDate": {
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947)."
            },
            "countChromeDevicesThatNeedAttention": {
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947"
            },
            "countChromeBrowsersNeedingAttention": {
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity."
            },
            "countChromeHardwareFleetDevices": {
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947"
            },
            "countInstalledApps": {
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of app installations."
            },
            "findInstalledAppDevices": {
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of managed Chrome browser devices that have a specified app installed."
            },
            "countChromeVersions": {
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of installed Chrome versions."
            },
            "countPrintJobsByUser": {
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a summary of printing done by each user."
            },
            "countPrintJobsByPrinter": {
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a summary of printing done by each printer."
            },
            "enumeratePrintJobs": {
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a list of print jobs."
            },
            "countChromeCrashEvents": {
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "path": "v1/{+customer}/reports:countChromeCrashEvents",
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a count of Chrome crash events."
            },
            "countActiveDevices": {
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "path": "v1/{+customer}/reports:countActiveDevices",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a count of active devices per set time frames."
            },
            "countDevicesPerReleaseChannel": {
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a count of devices per channel."
            },
            "countDevicesPerBootType": {
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a count of devices per boot type."
            }
          }
        },
        "telemetry": {
          "resources": {
            "devices": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "path": "v1/{+parent}/telemetry/devices",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry devices."
                },
                "get": {
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "Get telemetry device."
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "path": "v1/{+parent}/telemetry/events",
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List telemetry events."
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "path": "v1/{+parent}/telemetry/users",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry users."
                },
                "get": {
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "Get telemetry user."
                }
              }
            },
            "notificationConfigs": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry notification configs."
                },
                "create": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "Create a telemetry notification config."
                },
                "delete": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "Delete a telemetry notification config."
                }
              }
            }
          }
        },
        "profiles": {
          "methods": {
            "get": {
              "id": "chromemanagement.customers.profiles.get",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID."
            },
            "list": {
              "id": "chromemanagement.customers.profiles.list",
              "path": "v1/{+parent}/profiles",
              "flatPath": "v1/customers/{customersId}/profiles",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria."
            },
            "delete": {
              "id": "chromemanagement.customers.profiles.delete",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "description": "Deletes the data collected from a Chrome browser profile."
            }
          },
          "resources": {
            "commands": {
              "methods": {
                "create": {
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "path": "v1/{+parent}/commands",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "description": "Creates a Chrome browser profile remote command."
                },
                "get": {
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "description": "Gets a Chrome browser profile remote command."
                },
                "list": {
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "path": "v1/{+parent}/commands",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "description": "Lists remote commands of a Chrome browser profile."
                }
              }
            }
          }
        },
        "certificateProvisioningProcesses": {
          "methods": {
            "claim": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim",
              "path": "v1/{+name}:claim",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim",
              "httpMethod": "POST",
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`."
            },
            "get": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}",
              "httpMethod": "GET",
              "description": "Retrieves a certificate provisioning process."
            },
            "signData": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "path": "v1/{+name}:signData",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "httpMethod": "POST",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed."
            },
            "uploadCertificate": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate",
              "path": "v1/{+name}:uploadCertificate",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate",
              "httpMethod": "POST",
              "description": "Uploads a successfully issued certificate for a certificate provisioning process."
            },
            "setFailure": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "path": "v1/{+name}:setFailure",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure",
              "httpMethod": "POST",
              "description": "Marks a certificate provisioning process as failed."
            }
          },
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}",
                  "httpMethod": "GET",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                }
              }
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "path": "v1/{+name}:move",
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU."
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "list": {
          "id": "chromemanagement.operations.list",
          "path": "v1/{+name}",
          "flatPath": "v1/operations",
          "httpMethod": "GET",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
        },
        "delete": {
          "id": "chromemanagement.operations.delete",
          "path": "v1/{+name}",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "DELETE",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`."
        },
        "cancel": {
          "id": "chromemanagement.operations.cancel",
          "path": "v1/{+name}:cancel",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "httpMethod": "POST",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]"
        }
      }
    }
  },
  "revision": "20260329",
  "id": "chromemanagement:v1"
}