{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        }
      }
    }
  },
  "protocol": "rest",
  "discoveryVersion": "v1",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "servicePath": "",
  "batchPath": "batch",
  "version": "v1",
  "id": "chromemanagement:v1",
  "documentationLink": "https://developers.google.com/chrome/management/",
  "canonicalName": "Chrome Management",
  "kind": "discovery#restDescription",
  "resources": {
    "customers": {
      "resources": {
        "telemetry": {
          "resources": {
            "events": {
              "methods": {
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List telemetry events.",
                  "path": "v1/{+parent}/telemetry/events"
                }
              }
            },
            "devices": {
              "methods": {
                "list": {
                  "description": "List all telemetry devices.",
                  "path": "v1/{+parent}/telemetry/devices",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "id": "chromemanagement.customers.telemetry.devices.list"
                },
                "get": {
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Get telemetry device.",
                  "path": "v1/{+name}"
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "description": "List all telemetry users.",
                  "path": "v1/{+parent}/telemetry/users",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "flatPath": "v1/customers/{customersId}/telemetry/users"
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "Get telemetry user.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "id": "chromemanagement.customers.telemetry.users.get"
                }
              }
            },
            "notificationConfigs": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "List all telemetry notification configs.",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "description": "Create a telemetry notification config.",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs"
                },
                "delete": {
                  "description": "Delete a telemetry notification config.",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "DELETE",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}"
                }
              }
            }
          }
        },
        "profiles": {
          "methods": {
            "list": {
              "id": "chromemanagement.customers.profiles.list",
              "flatPath": "v1/customers/{customersId}/profiles",
              "path": "v1/{+parent}/profiles",
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "httpMethod": "GET"
            },
            "get": {
              "path": "v1/{+name}",
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "httpMethod": "GET",
              "id": "chromemanagement.customers.profiles.get",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}"
            },
            "delete": {
              "description": "Deletes the data collected from a Chrome browser profile.",
              "path": "v1/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "id": "chromemanagement.customers.profiles.delete"
            }
          },
          "resources": {
            "commands": {
              "methods": {
                "create": {
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "path": "v1/{+parent}/commands",
                  "description": "Creates a Chrome browser profile remote command.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ]
                },
                "get": {
                  "path": "v1/{+name}",
                  "description": "Gets a Chrome browser profile remote command.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}"
                },
                "list": {
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "path": "v1/{+parent}/commands",
                  "description": "Lists remote commands of a Chrome browser profile."
                }
              }
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "httpMethod": "POST",
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU.",
              "path": "v1/{+name}:move"
            }
          }
        },
        "apps": {
          "resources": {
            "android": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "id": "chromemanagement.customers.apps.android.get",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}"
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "description": "Get a specific app for a customer by its resource name.",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ]
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.web.get",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET"
                }
              }
            }
          },
          "methods": {
            "countChromeAppRequests": {
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "description": "Generate summary of app installation requests.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "id": "chromemanagement.customers.apps.countChromeAppRequests"
            },
            "fetchDevicesRequestingExtension": {
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "description": "Get a list of devices that have requested to install an extension."
            },
            "fetchUsersRequestingExtension": {
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "description": "Get a list of users that have requested to install an extension.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "httpMethod": "GET"
            }
          }
        },
        "reports": {
          "methods": {
            "countChromeDevicesReachingAutoExpirationDate": {
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate"
            },
            "enumeratePrintJobs": {
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "description": "Get a list of print jobs.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs"
            },
            "countPrintJobsByPrinter": {
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Get a summary of printing done by each printer.",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter"
            },
            "countPrintJobsByUser": {
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "description": "Get a summary of printing done by each user.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET"
            },
            "countActiveDevices": {
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countActiveDevices",
              "description": "Get a count of active devices per set time frames."
            },
            "findInstalledAppDevices": {
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices"
            },
            "countChromeCrashEvents": {
              "path": "v1/{+customer}/reports:countChromeCrashEvents",
              "description": "Get a count of Chrome crash events.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents"
            },
            "countChromeHardwareFleetDevices": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices"
            },
            "countDevicesPerBootType": {
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "description": "Get a count of devices per boot type.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType"
            },
            "countChromeVersions": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of installed Chrome versions.",
              "path": "v1/{+customer}/reports:countChromeVersions"
            },
            "countDevicesPerReleaseChannel": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "description": "Get a count of devices per channel.",
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel"
            },
            "countChromeBrowsersNeedingAttention": {
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.",
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET"
            },
            "countChromeDevicesThatNeedAttention": {
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention"
            },
            "countInstalledApps": {
              "description": "Generate report of app installations.",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "id": "chromemanagement.customers.reports.countInstalledApps"
            }
          }
        },
        "certificateProvisioningProcesses": {
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}",
                  "httpMethod": "GET",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "path": "v1/{+name}"
                }
              }
            }
          },
          "methods": {
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "path": "v1/{+name}",
              "description": "Retrieves a certificate provisioning process."
            },
            "uploadCertificate": {
              "description": "Uploads a successfully issued certificate for a certificate provisioning process.",
              "path": "v1/{+name}:uploadCertificate",
              "httpMethod": "POST",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate"
            },
            "signData": {
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "path": "v1/{+name}:signData",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed.",
              "httpMethod": "POST"
            },
            "setFailure": {
              "httpMethod": "POST",
              "path": "v1/{+name}:setFailure",
              "description": "Marks a certificate provisioning process as failed.",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure"
            },
            "claim": {
              "path": "v1/{+name}:claim",
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`.",
              "httpMethod": "POST",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim"
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "list": {
          "flatPath": "v1/operations",
          "httpMethod": "GET",
          "id": "chromemanagement.operations.list",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "path": "v1/{+name}"
        },
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "path": "v1/{+name}:cancel",
          "httpMethod": "POST",
          "id": "chromemanagement.operations.cancel",
          "flatPath": "v1/operations/{operationsId}:cancel"
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "v1/operations/{operationsId}",
          "id": "chromemanagement.operations.delete",
          "path": "v1/{+name}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`."
        }
      }
    }
  },
  "version_module": true,
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "basePath": "",
  "ownerName": "Google",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "revision": "20260409",
  "ownerDomain": "google.com",
  "title": "Chrome Management API",
  "name": "chromemanagement"
}