{
  "title": "Chrome Management API",
  "servicePath": "",
  "basePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/chrome/management/",
  "fullyEncodeReservedExpansion": true,
  "ownerDomain": "google.com",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "discoveryVersion": "v1",
  "canonicalName": "Chrome Management",
  "version": "v1",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "version_module": true,
  "batchPath": "batch",
  "resources": {
    "customers": {
      "resources": {
        "apps": {
          "methods": {
            "fetchDevicesRequestingExtension": {
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "httpMethod": "GET",
              "description": "Get a list of devices that have requested to install an extension.",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ]
            },
            "countChromeAppRequests": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "description": "Generate summary of app installation requests.",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "httpMethod": "GET"
            },
            "fetchUsersRequestingExtension": {
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "description": "Get a list of users that have requested to install an extension.",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ]
            }
          },
          "resources": {
            "android": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.apps.android.get",
                  "path": "v1/{+name}"
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.web.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ]
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "path": "v1/{+name}"
                }
              }
            }
          }
        },
        "reports": {
          "methods": {
            "countPrintJobsByPrinter": {
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "httpMethod": "GET",
              "description": "Get a summary of printing done by each printer.",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countDevicesPerReleaseChannel": {
              "description": "Get a count of devices per channel.",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeHardwareFleetDevices": {
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "httpMethod": "GET",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeDevicesThatNeedAttention": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countPrintJobsByUser": {
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "httpMethod": "GET",
              "description": "Get a summary of printing done by each user.",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countInstalledApps": {
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "httpMethod": "GET",
              "description": "Generate report of app installations.",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "httpMethod": "GET"
            },
            "countDevicesPerBootType": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "httpMethod": "GET",
              "description": "Get a count of devices per boot type.",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType"
            },
            "countChromeVersions": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of installed Chrome versions.",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "httpMethod": "GET"
            },
            "countChromeCrashEvents": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "path": "v1/{+customer}/reports:countChromeCrashEvents",
              "httpMethod": "GET",
              "description": "Get a count of Chrome crash events.",
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents"
            },
            "enumeratePrintJobs": {
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "description": "Get a list of print jobs.",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "findInstalledAppDevices": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "httpMethod": "GET",
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices"
            },
            "countActiveDevices": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "path": "v1/{+customer}/reports:countActiveDevices",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices",
              "description": "Get a count of active devices per set time frames."
            },
            "countChromeBrowsersNeedingAttention": {
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            }
          }
        },
        "certificateProvisioningProcesses": {
          "methods": {
            "signData": {
              "httpMethod": "POST",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "path": "v1/{+name}:signData",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed."
            },
            "setFailure": {
              "description": "Marks a certificate provisioning process as failed.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "path": "v1/{+name}:setFailure",
              "httpMethod": "POST"
            },
            "claim": {
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim",
              "path": "v1/{+name}:claim",
              "httpMethod": "POST"
            },
            "get": {
              "description": "Retrieves a certificate provisioning process.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "path": "v1/{+name}",
              "httpMethod": "GET"
            },
            "uploadCertificate": {
              "description": "Uploads a successfully issued certificate for a certificate provisioning process.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate",
              "path": "v1/{+name}:uploadCertificate",
              "httpMethod": "POST"
            }
          },
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}"
                }
              }
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU.",
              "httpMethod": "POST",
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "path": "v1/{+name}:move",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ]
            }
          }
        },
        "profiles": {
          "methods": {
            "get": {
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID.",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "id": "chromemanagement.customers.profiles.get",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ]
            },
            "list": {
              "id": "chromemanagement.customers.profiles.list",
              "path": "v1/{+parent}/profiles",
              "httpMethod": "GET",
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria.",
              "flatPath": "v1/customers/{customersId}/profiles",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ]
            },
            "delete": {
              "description": "Deletes the data collected from a Chrome browser profile.",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "id": "chromemanagement.customers.profiles.delete",
              "path": "v1/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ]
            }
          },
          "resources": {
            "commands": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}",
                  "description": "Gets a Chrome browser profile remote command.",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "path": "v1/{+name}"
                },
                "list": {
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "description": "Lists remote commands of a Chrome browser profile.",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "path": "v1/{+parent}/commands",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ]
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "description": "Creates a Chrome browser profile remote command.",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "path": "v1/{+parent}/commands",
                  "httpMethod": "POST"
                }
              }
            }
          }
        },
        "telemetry": {
          "resources": {
            "devices": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry devices.",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "path": "v1/{+parent}/telemetry/devices",
                  "httpMethod": "GET"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "Get telemetry device.",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET"
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List telemetry events.",
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "path": "v1/{+parent}/telemetry/events",
                  "httpMethod": "GET"
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "description": "List all telemetry users.",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "path": "v1/{+parent}/telemetry/users",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "description": "Get telemetry user.",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "path": "v1/{+name}"
                }
              }
            },
            "notificationConfigs": {
              "methods": {
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "DELETE",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "description": "Delete a telemetry notification config."
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "description": "Create a telemetry notification config.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "list": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "httpMethod": "GET",
                  "description": "List all telemetry notification configs.",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "id": "chromemanagement.operations.delete",
          "path": "v1/{+name}",
          "flatPath": "v1/operations/{operationsId}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`."
        },
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "id": "chromemanagement.operations.cancel",
          "path": "v1/{+name}:cancel",
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "v1/operations",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "httpMethod": "GET",
          "id": "chromemanagement.operations.list",
          "path": "v1/{+name}"
        }
      }
    }
  },
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "revision": "20260310",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "id": "chromemanagement:v1",
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "protocol": "rest",
  "name": "chromemanagement"
}