{
  "ownerDomain": "google.com",
  "basePath": "",
  "documentationLink": "https://developers.google.com/chrome/management/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "version_module": true,
  "ownerName": "Google",
  "kind": "discovery#restDescription",
  "name": "chromemanagement",
  "servicePath": "",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "resources": {
    "customers": {
      "resources": {
        "certificateProvisioningProcesses": {
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}",
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                }
              }
            }
          },
          "methods": {
            "signData": {
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "path": "v1/{+name}:signData",
              "httpMethod": "POST"
            },
            "setFailure": {
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "path": "v1/{+name}:setFailure",
              "description": "Marks a certificate provisioning process as failed.",
              "httpMethod": "POST"
            },
            "claim": {
              "httpMethod": "POST",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim",
              "path": "v1/{+name}:claim",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim",
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`."
            },
            "uploadCertificate": {
              "description": "Uploads a successfully issued certificate for a certificate provisioning process.",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate",
              "path": "v1/{+name}:uploadCertificate",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate",
              "httpMethod": "POST"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Retrieves a certificate provisioning process.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "path": "v1/{+name}"
            }
          }
        },
        "reports": {
          "methods": {
            "countChromeDevicesReachingAutoExpirationDate": {
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeDevicesThatNeedAttention": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countPrintJobsByPrinter": {
              "description": "Get a summary of printing done by each printer.",
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET"
            },
            "countDevicesPerBootType": {
              "description": "Get a count of devices per boot type.",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType",
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "findInstalledAppDevices": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "path": "v1/{+customer}/reports:findInstalledAppDevices"
            },
            "countChromeVersions": {
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "description": "Generate report of installed Chrome versions.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET"
            },
            "countPrintJobsByUser": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a summary of printing done by each user.",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "path": "v1/{+customer}/reports:countPrintJobsByUser"
            },
            "countChromeBrowsersNeedingAttention": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity."
            },
            "countChromeCrashEvents": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Get a count of Chrome crash events.",
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "path": "v1/{+customer}/reports:countChromeCrashEvents",
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents"
            },
            "countInstalledApps": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Generate report of app installations.",
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps"
            },
            "countDevicesPerReleaseChannel": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "description": "Get a count of devices per channel."
            },
            "countActiveDevices": {
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "path": "v1/{+customer}/reports:countActiveDevices",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices",
              "description": "Get a count of active devices per set time frames.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET"
            },
            "countChromeHardwareFleetDevices": {
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET"
            },
            "enumeratePrintJobs": {
              "description": "Get a list of print jobs.",
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET"
            }
          }
        },
        "apps": {
          "resources": {
            "android": {
              "methods": {
                "get": {
                  "description": "Get a specific app for a customer by its resource name.",
                  "id": "chromemanagement.customers.apps.android.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET"
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.apps.web.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            }
          },
          "methods": {
            "countChromeAppRequests": {
              "description": "Generate summary of app installation requests.",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ]
            },
            "fetchUsersRequestingExtension": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "httpMethod": "GET",
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "description": "Get a list of users that have requested to install an extension."
            },
            "fetchDevicesRequestingExtension": {
              "description": "Get a list of devices that have requested to install an extension.",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ]
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU.",
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "path": "v1/{+name}:move"
            }
          }
        },
        "telemetry": {
          "resources": {
            "notificationConfigs": {
              "methods": {
                "delete": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "description": "Delete a telemetry notification config.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "DELETE"
                },
                "create": {
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "description": "Create a telemetry notification config.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "description": "List all telemetry notification configs."
                }
              }
            },
            "devices": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "path": "v1/{+parent}/telemetry/devices",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "description": "List all telemetry devices.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET"
                },
                "get": {
                  "description": "Get telemetry device.",
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET"
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "path": "v1/{+parent}/telemetry/events",
                  "description": "List telemetry events."
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry users.",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "path": "v1/{+parent}/telemetry/users"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "description": "Get telemetry user."
                }
              }
            }
          }
        },
        "profiles": {
          "methods": {
            "delete": {
              "id": "chromemanagement.customers.profiles.delete",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "description": "Deletes the data collected from a Chrome browser profile.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "httpMethod": "DELETE"
            },
            "get": {
              "id": "chromemanagement.customers.profiles.get",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/profiles",
              "id": "chromemanagement.customers.profiles.list",
              "path": "v1/{+parent}/profiles",
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria."
            }
          },
          "resources": {
            "commands": {
              "methods": {
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "description": "Creates a Chrome browser profile remote command.",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "path": "v1/{+parent}/commands"
                },
                "get": {
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}",
                  "description": "Gets a Chrome browser profile remote command.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "httpMethod": "GET"
                },
                "list": {
                  "description": "Lists remote commands of a Chrome browser profile.",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "path": "v1/{+parent}/commands",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "flatPath": "v1/operations/{operationsId}",
          "id": "chromemanagement.operations.delete",
          "path": "v1/{+name}"
        },
        "list": {
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "httpMethod": "GET",
          "id": "chromemanagement.operations.list",
          "path": "v1/{+name}",
          "flatPath": "v1/operations"
        },
        "cancel": {
          "httpMethod": "POST",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "id": "chromemanagement.operations.cancel",
          "path": "v1/{+name}:cancel",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]"
        }
      }
    }
  },
  "id": "chromemanagement:v1",
  "title": "Chrome Management API",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "batchPath": "batch",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "canonicalName": "Chrome Management",
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true,
  "revision": "20260415",
  "version": "v1"
}