{
  "ownerName": "Google",
  "batchPath": "batch",
  "version": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        }
      }
    }
  },
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "version_module": true,
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "basePath": "",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "discoveryVersion": "v1",
  "protocol": "rest",
  "resources": {
    "customers": {
      "resources": {
        "reports": {
          "methods": {
            "countDevicesPerBootType": {
              "description": "Get a count of devices per boot type.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "httpMethod": "GET"
            },
            "countChromeDevicesThatNeedAttention": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947"
            },
            "countPrintJobsByUser": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a summary of printing done by each user.",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countPrintJobsByUser"
            },
            "findInstalledAppDevices": {
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices"
            },
            "enumeratePrintJobs": {
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "description": "Get a list of print jobs.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeCrashEvents": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a count of Chrome crash events.",
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents",
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeCrashEvents"
            },
            "countDevicesPerReleaseChannel": {
              "description": "Get a count of devices per channel.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel"
            },
            "countInstalledApps": {
              "description": "Generate report of app installations.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps"
            },
            "countActiveDevices": {
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices",
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countActiveDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a count of active devices per set time frames."
            },
            "countChromeHardwareFleetDevices": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947"
            },
            "countPrintJobsByPrinter": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a summary of printing done by each printer.",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "httpMethod": "GET"
            },
            "countChromeBrowsersNeedingAttention": {
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeVersions": {
              "description": "Generate report of installed Chrome versions.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeVersions",
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions"
            }
          }
        },
        "connectorConfigs": {
          "methods": {
            "get": {
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "id": "chromemanagement.customers.connectorConfigs.get",
              "httpMethod": "GET",
              "description": "Gets a connector config with customer ID and config ID.",
              "path": "v1/{+name}"
            },
            "patch": {
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "id": "chromemanagement.customers.connectorConfigs.patch",
              "httpMethod": "PATCH",
              "path": "v1/{+name}",
              "description": "Updates a connector config."
            },
            "create": {
              "flatPath": "v1/customers/{customersId}/connectorConfigs",
              "id": "chromemanagement.customers.connectorConfigs.create",
              "httpMethod": "POST",
              "path": "v1/{+parent}/connectorConfigs",
              "description": "Creates a connector config."
            },
            "delete": {
              "path": "v1/{+name}",
              "id": "chromemanagement.customers.connectorConfigs.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a connector config.",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}"
            },
            "list": {
              "flatPath": "v1/customers/{customersId}/connectorConfigs",
              "path": "v1/{+parent}/connectorConfigs",
              "id": "chromemanagement.customers.connectorConfigs.list",
              "httpMethod": "GET",
              "description": "Lists connector configs of a customer."
            }
          }
        },
        "telemetry": {
          "resources": {
            "devices": {
              "methods": {
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "path": "v1/{+parent}/telemetry/devices",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry devices."
                },
                "get": {
                  "description": "Get telemetry device.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}"
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "description": "List all telemetry users.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/telemetry/users",
                  "flatPath": "v1/customers/{customersId}/telemetry/users"
                },
                "get": {
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "description": "Get telemetry user.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                }
              }
            },
            "notificationConfigs": {
              "methods": {
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List all telemetry notification configs."
                },
                "create": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "description": "Create a telemetry notification config.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "delete": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "httpMethod": "DELETE",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "description": "Delete a telemetry notification config.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "path": "v1/{+parent}/telemetry/events",
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List telemetry events."
                }
              }
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "path": "v1/{+name}:move",
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU."
            }
          }
        },
        "apps": {
          "methods": {
            "fetchDevicesRequestingExtension": {
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "description": "Get a list of devices that have requested to install an extension.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ]
            },
            "fetchUsersRequestingExtension": {
              "description": "Get a list of users that have requested to install an extension.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "httpMethod": "GET",
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension"
            },
            "countChromeAppRequests": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "description": "Generate summary of app installation requests.",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "android": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.apps.android.get",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ]
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "description": "Get a specific app for a customer by its resource name.",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "httpMethod": "GET"
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "id": "chromemanagement.customers.apps.web.get",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            }
          }
        },
        "certificateProvisioningProcesses": {
          "methods": {
            "setFailure": {
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "httpMethod": "POST",
              "path": "v1/{+name}:setFailure",
              "description": "Marks a certificate provisioning process as failed."
            },
            "claim": {
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`.",
              "path": "v1/{+name}:claim",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim",
              "httpMethod": "POST",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim"
            },
            "get": {
              "path": "v1/{+name}",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "httpMethod": "GET",
              "description": "Retrieves a certificate provisioning process.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}"
            },
            "signData": {
              "path": "v1/{+name}:signData",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "httpMethod": "POST",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed."
            },
            "uploadCertificate": {
              "description": "Uploads a successfully issued certificate for a certificate provisioning process.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate",
              "path": "v1/{+name}:uploadCertificate",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate",
              "httpMethod": "POST"
            }
          },
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}",
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "httpMethod": "GET",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "path": "v1/{+name}"
                }
              }
            }
          }
        },
        "profiles": {
          "methods": {
            "get": {
              "id": "chromemanagement.customers.profiles.get",
              "httpMethod": "GET",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ]
            },
            "list": {
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "id": "chromemanagement.customers.profiles.list",
              "httpMethod": "GET",
              "path": "v1/{+parent}/profiles",
              "flatPath": "v1/customers/{customersId}/profiles"
            },
            "delete": {
              "description": "Deletes the data collected from a Chrome browser profile.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "path": "v1/{+name}",
              "id": "chromemanagement.customers.profiles.delete",
              "httpMethod": "DELETE",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}"
            }
          },
          "resources": {
            "commands": {
              "methods": {
                "create": {
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "path": "v1/{+parent}/commands",
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "description": "Creates a Chrome browser profile remote command."
                },
                "get": {
                  "description": "Gets a Chrome browser profile remote command.",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "description": "Lists remote commands of a Chrome browser profile.",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/commands"
                }
              }
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "list": {
          "path": "v1/{+name}",
          "id": "chromemanagement.operations.list",
          "httpMethod": "GET",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "flatPath": "v1/operations"
        },
        "delete": {
          "flatPath": "v1/operations/{operationsId}",
          "id": "chromemanagement.operations.delete",
          "httpMethod": "DELETE",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "path": "v1/{+name}"
        },
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "id": "chromemanagement.operations.cancel",
          "httpMethod": "POST",
          "path": "v1/{+name}:cancel"
        }
      }
    }
  },
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "documentationLink": "https://developers.google.com/chrome/management/",
  "servicePath": "",
  "revision": "20260424",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "name": "chromemanagement",
  "ownerDomain": "google.com",
  "title": "Chrome Management API",
  "id": "chromemanagement:v1",
  "canonicalName": "Chrome Management"
}