{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        }
      }
    }
  },
  "name": "chromemanagement",
  "revision": "20260505",
  "ownerName": "Google",
  "ownerDomain": "google.com",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "title": "Chrome Management API",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "version": "v1",
  "basePath": "",
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "documentationLink": "https://developers.google.com/chrome/management/",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "kind": "discovery#restDescription",
  "protocol": "rest",
  "resources": {
    "customers": {
      "resources": {
        "profiles": {
          "resources": {
            "commands": {
              "methods": {
                "create": {
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/commands",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "description": "Creates a Chrome browser profile remote command."
                },
                "get": {
                  "description": "Gets a Chrome browser profile remote command.",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.profiles.commands.get"
                },
                "list": {
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/commands",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "description": "Lists remote commands of a Chrome browser profile."
                }
              }
            }
          },
          "methods": {
            "delete": {
              "description": "Deletes the data collected from a Chrome browser profile.",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "httpMethod": "DELETE",
              "id": "chromemanagement.customers.profiles.delete",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "path": "v1/{+name}"
            },
            "get": {
              "httpMethod": "GET",
              "id": "chromemanagement.customers.profiles.get",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "path": "v1/{+name}",
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID.",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}"
            },
            "list": {
              "httpMethod": "GET",
              "id": "chromemanagement.customers.profiles.list",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "path": "v1/{+parent}/profiles",
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria.",
              "flatPath": "v1/customers/{customersId}/profiles"
            }
          }
        },
        "connectorConfigs": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "id": "chromemanagement.customers.connectorConfigs.list",
              "description": "Lists connector configs of a customer.",
              "path": "v1/{+parent}/connectorConfigs",
              "flatPath": "v1/customers/{customersId}/connectorConfigs"
            },
            "create": {
              "path": "v1/{+parent}/connectorConfigs",
              "httpMethod": "POST",
              "id": "chromemanagement.customers.connectorConfigs.create",
              "description": "Creates a connector config.",
              "flatPath": "v1/customers/{customersId}/connectorConfigs"
            },
            "delete": {
              "id": "chromemanagement.customers.connectorConfigs.delete",
              "httpMethod": "DELETE",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "description": "Deletes a connector config."
            },
            "get": {
              "httpMethod": "GET",
              "id": "chromemanagement.customers.connectorConfigs.get",
              "description": "Gets a connector config with customer ID and config ID.",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}"
            },
            "patch": {
              "path": "v1/{+name}",
              "id": "chromemanagement.customers.connectorConfigs.patch",
              "httpMethod": "PATCH",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "description": "Updates a connector config."
            }
          }
        },
        "certificateProvisioningProcesses": {
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}"
                }
              }
            }
          },
          "methods": {
            "uploadCertificate": {
              "httpMethod": "POST",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate",
              "path": "v1/{+name}:uploadCertificate",
              "description": "Uploads a successfully issued certificate for a certificate provisioning process.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate"
            },
            "signData": {
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed.",
              "path": "v1/{+name}:signData",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "httpMethod": "POST"
            },
            "get": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "httpMethod": "GET",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}",
              "description": "Retrieves a certificate provisioning process."
            },
            "claim": {
              "httpMethod": "POST",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim",
              "path": "v1/{+name}:claim",
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim"
            },
            "setFailure": {
              "description": "Marks a certificate provisioning process as failed.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure",
              "path": "v1/{+name}:setFailure",
              "httpMethod": "POST",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure"
            }
          }
        },
        "apps": {
          "methods": {
            "fetchDevicesRequestingExtension": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "description": "Get a list of devices that have requested to install an extension.",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension"
            },
            "fetchUsersRequestingExtension": {
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "description": "Get a list of users that have requested to install an extension.",
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "httpMethod": "GET"
            },
            "countChromeAppRequests": {
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "httpMethod": "GET",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "description": "Generate summary of app installation requests."
            }
          },
          "resources": {
            "chrome": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "description": "Get a specific app for a customer by its resource name.",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}"
                }
              }
            },
            "android": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "id": "chromemanagement.customers.apps.android.get",
                  "httpMethod": "GET"
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "id": "chromemanagement.customers.apps.web.get",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "httpMethod": "POST",
              "path": "v1/{+name}:move",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU."
            }
          }
        },
        "reports": {
          "methods": {
            "countDevicesPerReleaseChannel": {
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "description": "Get a count of devices per channel.",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "httpMethod": "GET"
            },
            "findInstalledAppDevices": {
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices"
            },
            "countChromeBrowsersNeedingAttention": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity.",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention"
            },
            "countInstalledApps": {
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "description": "Generate report of app installations.",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "httpMethod": "GET"
            },
            "enumeratePrintJobs": {
              "description": "Get a list of print jobs.",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:enumeratePrintJobs"
            },
            "countPrintJobsByPrinter": {
              "description": "Get a summary of printing done by each printer.",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter"
            },
            "countActiveDevices": {
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countActiveDevices",
              "description": "Get a count of active devices per set time frames.",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices"
            },
            "countChromeDevicesThatNeedAttention": {
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention"
            },
            "findInstalledAppProfiles": {
              "description": "Generate report of managed Chrome profiles that have a specified app installed.",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppProfiles",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.findInstalledAppProfiles",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:findInstalledAppProfiles"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "httpMethod": "GET"
            },
            "countChromeHardwareFleetDevices": {
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947"
            },
            "countPrintJobsByUser": {
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "description": "Get a summary of printing done by each user.",
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "httpMethod": "GET"
            },
            "countChromeVersions": {
              "path": "v1/{+customer}/reports:countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "description": "Generate report of installed Chrome versions."
            },
            "countChromeCrashEvents": {
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeCrashEvents",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents",
              "description": "Get a count of Chrome crash events."
            },
            "countDevicesPerBootType": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "description": "Get a count of devices per boot type.",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType"
            }
          }
        },
        "telemetry": {
          "resources": {
            "devices": {
              "methods": {
                "list": {
                  "description": "List all telemetry devices.",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/devices"
                },
                "get": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "description": "Get telemetry device."
                }
              }
            },
            "notificationConfigs": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "description": "List all telemetry notification configs.",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs"
                },
                "create": {
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "description": "Create a telemetry notification config.",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+name}",
                  "description": "Delete a telemetry notification config.",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}"
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "description": "List telemetry events.",
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/events",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.events.list"
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "description": "List all telemetry users.",
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/telemetry/users",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "get": {
                  "description": "Get telemetry user.",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "httpMethod": "GET",
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+name}"
                }
              }
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "delete": {
          "id": "chromemanagement.operations.delete",
          "httpMethod": "DELETE",
          "path": "v1/{+name}",
          "flatPath": "v1/operations/{operationsId}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`."
        },
        "list": {
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "path": "v1/{+name}",
          "flatPath": "v1/operations",
          "httpMethod": "GET",
          "id": "chromemanagement.operations.list"
        },
        "cancel": {
          "flatPath": "v1/operations/{operationsId}:cancel",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "id": "chromemanagement.operations.cancel",
          "httpMethod": "POST",
          "path": "v1/{+name}:cancel"
        }
      }
    }
  },
  "canonicalName": "Chrome Management",
  "id": "chromemanagement:v1",
  "servicePath": ""
}