{
  "id": "chromemanagement:v1",
  "version_module": true,
  "batchPath": "batch",
  "title": "Chrome Management API",
  "protocol": "rest",
  "name": "chromemanagement",
  "version": "v1",
  "fullyEncodeReservedExpansion": true,
  "documentationLink": "https://developers.google.com/chrome/management/",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "basePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        }
      }
    }
  },
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "resources": {
    "customers": {
      "resources": {
        "reports": {
          "methods": {
            "countActiveDevices": {
              "description": "Get a count of active devices per set time frames.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices",
              "path": "v1/{+customer}/reports:countActiveDevices",
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeVersions": {
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeVersions",
              "description": "Generate report of installed Chrome versions.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions"
            },
            "countChromeHardwareFleetDevices": {
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices"
            },
            "countPrintJobsByPrinter": {
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "description": "Get a summary of printing done by each printer.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate"
            },
            "enumeratePrintJobs": {
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "description": "Get a list of print jobs."
            },
            "countInstalledApps": {
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of app installations.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "path": "v1/{+customer}/reports:countInstalledApps"
            },
            "countDevicesPerReleaseChannel": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "httpMethod": "GET",
              "description": "Get a count of devices per channel.",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel"
            },
            "findInstalledAppDevices": {
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countPrintJobsByUser": {
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a summary of printing done by each user.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "path": "v1/{+customer}/reports:countPrintJobsByUser"
            },
            "countChromeCrashEvents": {
              "description": "Get a count of Chrome crash events.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents",
              "path": "v1/{+customer}/reports:countChromeCrashEvents",
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeDevicesThatNeedAttention": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "httpMethod": "GET"
            },
            "countDevicesPerBootType": {
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "description": "Get a count of devices per boot type.",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countDevicesPerBootType"
            },
            "countChromeBrowsersNeedingAttention": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "httpMethod": "GET",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity."
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "httpMethod": "POST",
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU.",
              "path": "v1/{+name}:move",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move"
            }
          }
        },
        "apps": {
          "methods": {
            "fetchUsersRequestingExtension": {
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "description": "Get a list of users that have requested to install an extension.",
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ]
            },
            "countChromeAppRequests": {
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "description": "Generate summary of app installation requests."
            },
            "fetchDevicesRequestingExtension": {
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "httpMethod": "GET",
              "description": "Get a list of devices that have requested to install an extension.",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension"
            }
          },
          "resources": {
            "chrome": {
              "methods": {
                "get": {
                  "description": "Get a specific app for a customer by its resource name.",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "id": "chromemanagement.customers.apps.chrome.get"
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "id": "chromemanagement.customers.apps.web.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ]
                }
              }
            },
            "android": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "id": "chromemanagement.customers.apps.android.get",
                  "path": "v1/{+name}",
                  "description": "Get a specific app for a customer by its resource name.",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "telemetry": {
          "resources": {
            "notificationConfigs": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "description": "List all telemetry notification configs.",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs"
                },
                "delete": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "description": "Delete a telemetry notification config."
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "description": "Create a telemetry notification config.",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/telemetry/notificationConfigs"
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "description": "List all telemetry users.",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "path": "v1/{+parent}/telemetry/users",
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "get": {
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "description": "Get telemetry user.",
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                }
              }
            },
            "devices": {
              "methods": {
                "get": {
                  "description": "Get telemetry device.",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "list": {
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "description": "List all telemetry devices.",
                  "path": "v1/{+parent}/telemetry/devices"
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/events",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "description": "List telemetry events."
                }
              }
            }
          }
        },
        "profiles": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "id": "chromemanagement.customers.profiles.get",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "httpMethod": "GET",
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID."
            },
            "delete": {
              "path": "v1/{+name}",
              "description": "Deletes the data collected from a Chrome browser profile.",
              "httpMethod": "DELETE",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "id": "chromemanagement.customers.profiles.delete",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ]
            },
            "list": {
              "path": "v1/{+parent}/profiles",
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria.",
              "flatPath": "v1/customers/{customersId}/profiles",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "id": "chromemanagement.customers.profiles.list"
            }
          },
          "resources": {
            "commands": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/commands",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "description": "Lists remote commands of a Chrome browser profile.",
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ]
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "path": "v1/{+name}",
                  "description": "Gets a Chrome browser profile remote command.",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}",
                  "httpMethod": "GET"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "description": "Creates a Chrome browser profile remote command.",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/commands"
                }
              }
            }
          }
        },
        "certificateProvisioningProcesses": {
          "methods": {
            "setFailure": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "path": "v1/{+name}:setFailure",
              "httpMethod": "POST",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure",
              "description": "Marks a certificate provisioning process as failed."
            },
            "signData": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed.",
              "httpMethod": "POST",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "path": "v1/{+name}:signData"
            },
            "uploadCertificate": {
              "path": "v1/{+name}:uploadCertificate",
              "description": "Uploads a successfully issued certificate for a certificate provisioning process.",
              "httpMethod": "POST",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate"
            },
            "get": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "path": "v1/{+name}",
              "description": "Retrieves a certificate provisioning process.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}",
              "httpMethod": "GET"
            },
            "claim": {
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim",
              "httpMethod": "POST",
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`.",
              "path": "v1/{+name}:claim",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim"
            }
          },
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}",
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "path": "v1/{+name}"
                }
              }
            }
          }
        },
        "connectorConfigs": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/connectorConfigs",
              "description": "Lists connector configs of a customer.",
              "path": "v1/{+parent}/connectorConfigs",
              "id": "chromemanagement.customers.connectorConfigs.list"
            },
            "delete": {
              "description": "Deletes a connector config.",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "httpMethod": "DELETE",
              "id": "chromemanagement.customers.connectorConfigs.delete",
              "path": "v1/{+name}"
            },
            "create": {
              "description": "Creates a connector config.",
              "flatPath": "v1/customers/{customersId}/connectorConfigs",
              "httpMethod": "POST",
              "path": "v1/{+parent}/connectorConfigs",
              "id": "chromemanagement.customers.connectorConfigs.create"
            },
            "get": {
              "path": "v1/{+name}",
              "id": "chromemanagement.customers.connectorConfigs.get",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "description": "Gets a connector config with customer ID and config ID."
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "list": {
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "flatPath": "v1/operations",
          "httpMethod": "GET",
          "id": "chromemanagement.operations.list",
          "path": "v1/{+name}"
        },
        "cancel": {
          "id": "chromemanagement.operations.cancel",
          "path": "v1/{+name}:cancel",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "httpMethod": "POST"
        },
        "delete": {
          "id": "chromemanagement.operations.delete",
          "path": "v1/{+name}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "httpMethod": "DELETE",
          "flatPath": "v1/operations/{operationsId}"
        }
      }
    }
  },
  "servicePath": "",
  "canonicalName": "Chrome Management",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "ownerName": "Google",
  "ownerDomain": "google.com",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "revision": "20260421"
}