{
  "documentationLink": "https://developers.google.com/chrome/management/",
  "id": "chromemanagement:v1",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        }
      }
    }
  },
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "resources": {
    "customers": {
      "resources": {
        "apps": {
          "methods": {
            "countChromeAppRequests": {
              "description": "Generate summary of app installation requests.",
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "httpMethod": "GET",
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ]
            },
            "fetchUsersRequestingExtension": {
              "httpMethod": "GET",
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "description": "Get a list of users that have requested to install an extension."
            },
            "fetchDevicesRequestingExtension": {
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "httpMethod": "GET",
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "description": "Get a list of devices that have requested to install an extension."
            }
          },
          "resources": {
            "chrome": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "id": "chromemanagement.customers.apps.web.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "android": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "id": "chromemanagement.customers.apps.android.get",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            }
          }
        },
        "reports": {
          "methods": {
            "countChromeBrowsersNeedingAttention": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity."
            },
            "countPrintJobsByPrinter": {
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "description": "Get a summary of printing done by each printer."
            },
            "countDevicesPerBootType": {
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType",
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Get a count of devices per boot type."
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947)."
            },
            "enumeratePrintJobs": {
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Get a list of print jobs."
            },
            "countActiveDevices": {
              "path": "v1/{+customer}/reports:countActiveDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices",
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "description": "Get a count of active devices per set time frames."
            },
            "countDevicesPerReleaseChannel": {
              "description": "Get a count of devices per channel.",
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countChromeCrashEvents": {
              "description": "Get a count of Chrome crash events.",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeCrashEvents",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents"
            },
            "countChromeDevicesThatNeedAttention": {
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947"
            },
            "countChromeHardwareFleetDevices": {
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947"
            },
            "countInstalledApps": {
              "description": "Generate report of app installations.",
              "path": "v1/{+customer}/reports:countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "id": "chromemanagement.customers.reports.countInstalledApps"
            },
            "countChromeVersions": {
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "description": "Generate report of installed Chrome versions."
            },
            "findInstalledAppDevices": {
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "id": "chromemanagement.customers.reports.findInstalledAppDevices"
            },
            "countPrintJobsByUser": {
              "description": "Get a summary of printing done by each user.",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            }
          }
        },
        "profiles": {
          "resources": {
            "commands": {
              "methods": {
                "create": {
                  "path": "v1/{+parent}/commands",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "description": "Creates a Chrome browser profile remote command."
                },
                "get": {
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}",
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "description": "Gets a Chrome browser profile remote command."
                },
                "list": {
                  "description": "Lists remote commands of a Chrome browser profile.",
                  "path": "v1/{+parent}/commands",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "id": "chromemanagement.customers.profiles.commands.list"
                }
              }
            }
          },
          "methods": {
            "get": {
              "httpMethod": "GET",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "id": "chromemanagement.customers.profiles.get",
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID."
            },
            "list": {
              "path": "v1/{+parent}/profiles",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/profiles",
              "id": "chromemanagement.customers.profiles.list",
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria."
            },
            "delete": {
              "description": "Deletes the data collected from a Chrome browser profile.",
              "httpMethod": "DELETE",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "id": "chromemanagement.customers.profiles.delete",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}"
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU.",
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "path": "v1/{+name}:move",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "httpMethod": "POST"
            }
          }
        },
        "certificateProvisioningProcesses": {
          "methods": {
            "get": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}",
              "description": "Retrieves a certificate provisioning process.",
              "httpMethod": "GET",
              "path": "v1/{+name}"
            },
            "setFailure": {
              "description": "Marks a certificate provisioning process as failed.",
              "httpMethod": "POST",
              "path": "v1/{+name}:setFailure",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure"
            },
            "claim": {
              "httpMethod": "POST",
              "path": "v1/{+name}:claim",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim",
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`."
            },
            "signData": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "httpMethod": "POST",
              "path": "v1/{+name}:signData",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed."
            },
            "uploadCertificate": {
              "path": "v1/{+name}:uploadCertificate",
              "httpMethod": "POST",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate",
              "description": "Uploads a successfully issued certificate for a certificate provisioning process."
            }
          },
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "path": "v1/{+name}",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "telemetry": {
          "resources": {
            "notificationConfigs": {
              "methods": {
                "delete": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Delete a telemetry notification config."
                },
                "list": {
                  "description": "List all telemetry notification configs.",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET"
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "description": "Create a telemetry notification config."
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/telemetry/events",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "description": "List telemetry events."
                }
              }
            },
            "users": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/telemetry/users",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "description": "List all telemetry users."
                },
                "get": {
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "description": "Get telemetry user."
                }
              }
            },
            "devices": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/telemetry/devices",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "description": "List all telemetry devices."
                },
                "get": {
                  "description": "Get telemetry device.",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "id": "chromemanagement.customers.telemetry.devices.get"
                }
              }
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "httpMethod": "POST",
          "path": "v1/{+name}:cancel",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "id": "chromemanagement.operations.cancel"
        },
        "list": {
          "id": "chromemanagement.operations.list",
          "flatPath": "v1/operations",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "path": "v1/{+name}",
          "httpMethod": "GET"
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "v1/{+name}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "flatPath": "v1/operations/{operationsId}",
          "id": "chromemanagement.operations.delete"
        }
      }
    }
  },
  "name": "chromemanagement",
  "servicePath": "",
  "canonicalName": "Chrome Management",
  "title": "Chrome Management API",
  "ownerDomain": "google.com",
  "basePath": "",
  "revision": "20260405",
  "ownerName": "Google",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "batchPath": "batch",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "version": "v1",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "version_module": true
}