{
  "version_module": true,
  "servicePath": "",
  "id": "chromemanagement:v1",
  "version": "v1",
  "fullyEncodeReservedExpansion": true,
  "discoveryVersion": "v1",
  "title": "Chrome Management API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        }
      }
    }
  },
  "name": "chromemanagement",
  "rootUrl": "https://chromemanagement.googleapis.com/",
  "canonicalName": "Chrome Management",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "revision": "20260424",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "documentationLink": "https://developers.google.com/chrome/management/",
  "protocol": "rest",
  "resources": {
    "customers": {
      "resources": {
        "certificateProvisioningProcesses": {
          "methods": {
            "get": {
              "path": "v1/{+name}",
              "description": "Retrieves a certificate provisioning process.",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}"
            },
            "setFailure": {
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure",
              "path": "v1/{+name}:setFailure",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "description": "Marks a certificate provisioning process as failed.",
              "httpMethod": "POST"
            },
            "uploadCertificate": {
              "httpMethod": "POST",
              "description": "Uploads a successfully issued certificate for a certificate provisioning process.",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate",
              "path": "v1/{+name}:uploadCertificate"
            },
            "signData": {
              "httpMethod": "POST",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed.",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData",
              "path": "v1/{+name}:signData",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData"
            },
            "claim": {
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`.",
              "httpMethod": "POST",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim",
              "path": "v1/{+name}:claim",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim"
            }
          },
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get",
                  "httpMethod": "GET",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}"
                }
              }
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "path": "v1/{+name}:move",
              "httpMethod": "POST",
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU."
            }
          }
        },
        "reports": {
          "methods": {
            "countChromeDevicesReachingAutoExpirationDate": {
              "httpMethod": "GET",
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate"
            },
            "countActiveDevices": {
              "description": "Get a count of active devices per set time frames.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countActiveDevices",
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices"
            },
            "countChromeBrowsersNeedingAttention": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "httpMethod": "GET",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity."
            },
            "findInstalledAppDevices": {
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "path": "v1/{+customer}/reports:findInstalledAppDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.findInstalledAppDevices"
            },
            "countPrintJobsByPrinter": {
              "description": "Get a summary of printing done by each printer.",
              "httpMethod": "GET",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter"
            },
            "countChromeDevicesThatNeedAttention": {
              "httpMethod": "GET",
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention"
            },
            "countPrintJobsByUser": {
              "description": "Get a summary of printing done by each user.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countPrintJobsByUser"
            },
            "enumeratePrintJobs": {
              "description": "Get a list of print jobs.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "id": "chromemanagement.customers.reports.enumeratePrintJobs"
            },
            "countDevicesPerReleaseChannel": {
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Get a count of devices per channel."
            },
            "countChromeCrashEvents": {
              "httpMethod": "GET",
              "description": "Get a count of Chrome crash events.",
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeCrashEvents",
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents"
            },
            "countChromeHardwareFleetDevices": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947"
            },
            "countInstalledApps": {
              "description": "Generate report of app installations.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countInstalledApps",
              "id": "chromemanagement.customers.reports.countInstalledApps"
            },
            "countChromeVersions": {
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeVersions",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "httpMethod": "GET",
              "description": "Generate report of installed Chrome versions."
            },
            "countDevicesPerBootType": {
              "description": "Get a count of devices per boot type.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType",
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countDevicesPerBootType"
            }
          }
        },
        "connectorConfigs": {
          "methods": {
            "list": {
              "id": "chromemanagement.customers.connectorConfigs.list",
              "httpMethod": "GET",
              "path": "v1/{+parent}/connectorConfigs",
              "description": "Lists connector configs of a customer.",
              "flatPath": "v1/customers/{customersId}/connectorConfigs"
            },
            "get": {
              "path": "v1/{+name}",
              "description": "Gets a connector config with customer ID and config ID.",
              "id": "chromemanagement.customers.connectorConfigs.get",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}"
            },
            "create": {
              "flatPath": "v1/customers/{customersId}/connectorConfigs",
              "path": "v1/{+parent}/connectorConfigs",
              "id": "chromemanagement.customers.connectorConfigs.create",
              "description": "Creates a connector config.",
              "httpMethod": "POST"
            },
            "patch": {
              "description": "Updates a connector config.",
              "httpMethod": "PATCH",
              "path": "v1/{+name}",
              "id": "chromemanagement.customers.connectorConfigs.patch",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}"
            },
            "delete": {
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "id": "chromemanagement.customers.connectorConfigs.delete",
              "httpMethod": "DELETE",
              "path": "v1/{+name}",
              "description": "Deletes a connector config."
            }
          }
        },
        "apps": {
          "methods": {
            "fetchUsersRequestingExtension": {
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "httpMethod": "GET",
              "description": "Get a list of users that have requested to install an extension."
            },
            "fetchDevicesRequestingExtension": {
              "description": "Get a list of devices that have requested to install an extension.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension",
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension"
            },
            "countChromeAppRequests": {
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "description": "Generate summary of app installation requests.",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "android": {
              "methods": {
                "get": {
                  "description": "Get a specific app for a customer by its resource name.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.apps.android.get",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}"
                }
              }
            },
            "chrome": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ]
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "id": "chromemanagement.customers.apps.web.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            }
          }
        },
        "telemetry": {
          "resources": {
            "users": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.telemetry.users.get",
                  "description": "Get telemetry user.",
                  "httpMethod": "GET"
                },
                "list": {
                  "httpMethod": "GET",
                  "description": "List all telemetry users.",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/users"
                }
              }
            },
            "devices": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "description": "Get telemetry device.",
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}"
                },
                "list": {
                  "path": "v1/{+parent}/telemetry/devices",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "description": "List all telemetry devices.",
                  "httpMethod": "GET"
                }
              }
            },
            "notificationConfigs": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "httpMethod": "GET",
                  "description": "List all telemetry notification configs."
                },
                "create": {
                  "httpMethod": "POST",
                  "description": "Create a telemetry notification config.",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/notificationConfigs"
                },
                "delete": {
                  "description": "Delete a telemetry notification config.",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+name}",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}"
                }
              }
            },
            "events": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "path": "v1/{+parent}/telemetry/events",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "httpMethod": "GET",
                  "description": "List telemetry events."
                }
              }
            }
          }
        },
        "profiles": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes the data collected from a Chrome browser profile.",
              "id": "chromemanagement.customers.profiles.delete",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}"
            },
            "list": {
              "path": "v1/{+parent}/profiles",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "id": "chromemanagement.customers.profiles.list",
              "flatPath": "v1/customers/{customersId}/profiles",
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria.",
              "httpMethod": "GET"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID.",
              "id": "chromemanagement.customers.profiles.get",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}"
            }
          },
          "resources": {
            "commands": {
              "methods": {
                "create": {
                  "httpMethod": "POST",
                  "description": "Creates a Chrome browser profile remote command.",
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "path": "v1/{+parent}/commands",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands"
                },
                "get": {
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "description": "Gets a Chrome browser profile remote command.",
                  "httpMethod": "GET"
                },
                "list": {
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "path": "v1/{+parent}/commands",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "httpMethod": "GET",
                  "description": "Lists remote commands of a Chrome browser profile."
                }
              }
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "delete": {
          "flatPath": "v1/operations/{operationsId}",
          "path": "v1/{+name}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "id": "chromemanagement.operations.delete",
          "httpMethod": "DELETE"
        },
        "list": {
          "flatPath": "v1/operations",
          "path": "v1/{+name}",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "id": "chromemanagement.operations.list",
          "httpMethod": "GET"
        },
        "cancel": {
          "path": "v1/{+name}:cancel",
          "id": "chromemanagement.operations.cancel",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "httpMethod": "POST"
        }
      }
    }
  },
  "ownerName": "Google",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "basePath": "",
  "kind": "discovery#restDescription"
}