{
  "fullyEncodeReservedExpansion": true,
  "ownerDomain": "google.com",
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/chrome.management.appdetails.readonly": {
          "description": "See detailed information about apps installed on Chrome browsers and devices managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.telemetry.readonly": {
          "description": "See basic device and telemetry information collected from ChromeOS devices or users managed within your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles": {
          "description": "See, edit, delete, and take other necessary actions on Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.profiles.readonly": {
          "description": "See Chrome browser profiles managed by your organization"
        },
        "https://www.googleapis.com/auth/chrome.management.reports.readonly": {
          "description": "See reports about devices and Chrome browsers managed within your organization"
        }
      }
    }
  },
  "name": "chromemanagement",
  "title": "Chrome Management API",
  "resources": {
    "customers": {
      "resources": {
        "reports": {
          "methods": {
            "countChromeBrowsersNeedingAttention": {
              "flatPath": "v1/customers/{customersId}/reports:countChromeBrowsersNeedingAttention",
              "path": "v1/{+customer}/reports:countChromeBrowsersNeedingAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeBrowsersNeedingAttention",
              "httpMethod": "GET",
              "description": "Count of Chrome Browsers that have been recently enrolled, have new policy to be synced, or have no recent activity."
            },
            "countPrintJobsByUser": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countPrintJobsByUser",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByUser",
              "path": "v1/{+customer}/reports:countPrintJobsByUser",
              "description": "Get a summary of printing done by each user.",
              "httpMethod": "GET"
            },
            "countPrintJobsByPrinter": {
              "description": "Get a summary of printing done by each printer.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countPrintJobsByPrinter",
              "flatPath": "v1/customers/{customersId}/reports:countPrintJobsByPrinter",
              "path": "v1/{+customer}/reports:countPrintJobsByPrinter"
            },
            "countChromeHardwareFleetDevices": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countChromeHardwareFleetDevices",
              "flatPath": "v1/customers/{customersId}/reports:countChromeHardwareFleetDevices",
              "path": "v1/{+customer}/reports:countChromeHardwareFleetDevices",
              "description": "Counts of devices with a specific hardware specification from the requested hardware type (for example model name, processor type). Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "httpMethod": "GET"
            },
            "countChromeCrashEvents": {
              "description": "Get a count of Chrome crash events.",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeCrashEvents",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeCrashEvents",
              "flatPath": "v1/customers/{customersId}/reports:countChromeCrashEvents"
            },
            "findInstalledAppDevices": {
              "description": "Generate report of managed Chrome browser devices that have a specified app installed.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.findInstalledAppDevices",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppDevices",
              "path": "v1/{+customer}/reports:findInstalledAppDevices"
            },
            "countInstalledApps": {
              "description": "Generate report of app installations.",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countInstalledApps",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countInstalledApps",
              "flatPath": "v1/customers/{customersId}/reports:countInstalledApps"
            },
            "findInstalledAppProfiles": {
              "description": "Generate report of managed Chrome profiles that have a specified app installed.",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.findInstalledAppProfiles",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:findInstalledAppProfiles",
              "flatPath": "v1/customers/{customersId}/reports:findInstalledAppProfiles"
            },
            "countChromeVersions": {
              "id": "chromemanagement.customers.reports.countChromeVersions",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeVersions",
              "flatPath": "v1/customers/{customersId}/reports:countChromeVersions",
              "description": "Generate report of installed Chrome versions.",
              "httpMethod": "GET"
            },
            "countDevicesPerBootType": {
              "id": "chromemanagement.customers.reports.countDevicesPerBootType",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countDevicesPerBootType",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerBootType",
              "description": "Get a count of devices per boot type.",
              "httpMethod": "GET"
            },
            "countChromeDevicesReachingAutoExpirationDate": {
              "description": "Generate report of the number of devices expiring in each month of the selected time frame. Devices are grouped by auto update expiration date and model. Further information can be found [here](https://support.google.com/chrome/a/answer/10564947).",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.reports.countChromeDevicesReachingAutoExpirationDate",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "path": "v1/{+customer}/reports:countChromeDevicesReachingAutoExpirationDate",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesReachingAutoExpirationDate"
            },
            "enumeratePrintJobs": {
              "httpMethod": "GET",
              "description": "Get a list of print jobs.",
              "path": "v1/{+customer}/reports:enumeratePrintJobs",
              "flatPath": "v1/customers/{customersId}/reports:enumeratePrintJobs",
              "id": "chromemanagement.customers.reports.enumeratePrintJobs",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countDevicesPerReleaseChannel": {
              "path": "v1/{+customer}/reports:countDevicesPerReleaseChannel",
              "flatPath": "v1/customers/{customersId}/reports:countDevicesPerReleaseChannel",
              "id": "chromemanagement.customers.reports.countDevicesPerReleaseChannel",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "httpMethod": "GET",
              "description": "Get a count of devices per channel."
            },
            "countChromeDevicesThatNeedAttention": {
              "httpMethod": "GET",
              "description": "Counts of ChromeOS devices that have not synced policies or have lacked user activity in the past 28 days, are out of date, or are not complaint. Further information can be found here https://support.google.com/chrome/a/answer/10564947",
              "path": "v1/{+customer}/reports:countChromeDevicesThatNeedAttention",
              "flatPath": "v1/customers/{customersId}/reports:countChromeDevicesThatNeedAttention",
              "id": "chromemanagement.customers.reports.countChromeDevicesThatNeedAttention",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ]
            },
            "countActiveDevices": {
              "description": "Get a count of active devices per set time frames.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.reports.readonly"
              ],
              "id": "chromemanagement.customers.reports.countActiveDevices",
              "flatPath": "v1/customers/{customersId}/reports:countActiveDevices",
              "path": "v1/{+customer}/reports:countActiveDevices"
            }
          }
        },
        "thirdPartyProfileUsers": {
          "methods": {
            "move": {
              "id": "chromemanagement.customers.thirdPartyProfileUsers.move",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "path": "v1/{+name}:move",
              "flatPath": "v1/customers/{customersId}/thirdPartyProfileUsers/{thirdPartyProfileUsersId}:move",
              "description": "Moves a third party chrome profile user to a destination OU. All profiles associated to that user will be moved to the destination OU.",
              "httpMethod": "POST"
            }
          }
        },
        "telemetry": {
          "resources": {
            "events": {
              "methods": {
                "list": {
                  "id": "chromemanagement.customers.telemetry.events.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/events",
                  "flatPath": "v1/customers/{customersId}/telemetry/events",
                  "description": "List telemetry events.",
                  "httpMethod": "GET"
                }
              }
            },
            "devices": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/telemetry/devices",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices",
                  "id": "chromemanagement.customers.telemetry.devices.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "List all telemetry devices."
                },
                "get": {
                  "description": "Get telemetry device.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.devices.get",
                  "flatPath": "v1/customers/{customersId}/telemetry/devices/{devicesId}",
                  "path": "v1/{+name}"
                }
              }
            },
            "notificationConfigs": {
              "methods": {
                "create": {
                  "httpMethod": "POST",
                  "description": "Create a telemetry notification config.",
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ]
                },
                "list": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/notificationConfigs",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs",
                  "description": "List all telemetry notification configs.",
                  "httpMethod": "GET"
                },
                "delete": {
                  "id": "chromemanagement.customers.telemetry.notificationConfigs.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/telemetry/notificationConfigs/{notificationConfigsId}",
                  "description": "Delete a telemetry notification config.",
                  "httpMethod": "DELETE"
                }
              }
            },
            "users": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "description": "Get telemetry user.",
                  "flatPath": "v1/customers/{customersId}/telemetry/users/{usersId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "id": "chromemanagement.customers.telemetry.users.get"
                },
                "list": {
                  "id": "chromemanagement.customers.telemetry.users.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.telemetry.readonly"
                  ],
                  "path": "v1/{+parent}/telemetry/users",
                  "flatPath": "v1/customers/{customersId}/telemetry/users",
                  "description": "List all telemetry users.",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "connectorConfigs": {
          "methods": {
            "create": {
              "description": "Creates a connector config.",
              "httpMethod": "POST",
              "id": "chromemanagement.customers.connectorConfigs.create",
              "path": "v1/{+parent}/connectorConfigs",
              "flatPath": "v1/customers/{customersId}/connectorConfigs"
            },
            "list": {
              "path": "v1/{+parent}/connectorConfigs",
              "flatPath": "v1/customers/{customersId}/connectorConfigs",
              "httpMethod": "GET",
              "id": "chromemanagement.customers.connectorConfigs.list",
              "description": "Lists connector configs of a customer."
            },
            "patch": {
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "id": "chromemanagement.customers.connectorConfigs.patch",
              "httpMethod": "PATCH",
              "description": "Updates a connector config."
            },
            "delete": {
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "httpMethod": "DELETE",
              "id": "chromemanagement.customers.connectorConfigs.delete",
              "description": "Deletes a connector config."
            },
            "get": {
              "flatPath": "v1/customers/{customersId}/connectorConfigs/{connectorConfigsId}",
              "httpMethod": "GET",
              "path": "v1/{+name}",
              "description": "Gets a connector config with customer ID and config ID.",
              "id": "chromemanagement.customers.connectorConfigs.get"
            }
          }
        },
        "certificateProvisioningProcesses": {
          "methods": {
            "get": {
              "id": "chromemanagement.customers.certificateProvisioningProcesses.get",
              "description": "Retrieves a certificate provisioning process.",
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}",
              "httpMethod": "GET"
            },
            "claim": {
              "description": "Claims a certificate provisioning process. For each certificate provisioning process, this operation can succeed only for one `caller_instance_id`.",
              "httpMethod": "POST",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.claim",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:claim",
              "path": "v1/{+name}:claim"
            },
            "uploadCertificate": {
              "httpMethod": "POST",
              "description": "Uploads a successfully issued certificate for a certificate provisioning process.",
              "path": "v1/{+name}:uploadCertificate",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:uploadCertificate",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.uploadCertificate"
            },
            "signData": {
              "httpMethod": "POST",
              "description": "Requests the client that initiated a certificate provisioning process to sign data. This should only be called after `ClaimCertificateProvisioningProcess` has been successfully executed.",
              "path": "v1/{+name}:signData",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:signData",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.signData"
            },
            "setFailure": {
              "path": "v1/{+name}:setFailure",
              "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}:setFailure",
              "id": "chromemanagement.customers.certificateProvisioningProcesses.setFailure",
              "httpMethod": "POST",
              "description": "Marks a certificate provisioning process as failed."
            }
          },
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "flatPath": "v1/customers/{customersId}/certificateProvisioningProcesses/{certificateProvisioningProcessesId}/operations/{operationsId}",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "id": "chromemanagement.customers.certificateProvisioningProcesses.operations.get"
                }
              }
            }
          }
        },
        "profiles": {
          "methods": {
            "list": {
              "description": "Lists Chrome browser profiles of a customer based on the given search and sorting criteria.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "id": "chromemanagement.customers.profiles.list",
              "flatPath": "v1/customers/{customersId}/profiles",
              "path": "v1/{+parent}/profiles"
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes the data collected from a Chrome browser profile.",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles"
              ],
              "id": "chromemanagement.customers.profiles.delete"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.profiles",
                "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
              ],
              "id": "chromemanagement.customers.profiles.get",
              "flatPath": "v1/customers/{customersId}/profiles/{profilesId}",
              "path": "v1/{+name}",
              "description": "Gets a Chrome browser profile with customer ID and profile permanent ID.",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "commands": {
              "methods": {
                "create": {
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "path": "v1/{+parent}/commands",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles"
                  ],
                  "id": "chromemanagement.customers.profiles.commands.create",
                  "httpMethod": "POST",
                  "description": "Creates a Chrome browser profile remote command."
                },
                "get": {
                  "httpMethod": "GET",
                  "description": "Gets a Chrome browser profile remote command.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands/{commandsId}",
                  "id": "chromemanagement.customers.profiles.commands.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ]
                },
                "list": {
                  "description": "Lists remote commands of a Chrome browser profile.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.profiles",
                    "https://www.googleapis.com/auth/chrome.management.profiles.readonly"
                  ],
                  "id": "chromemanagement.customers.profiles.commands.list",
                  "flatPath": "v1/customers/{customersId}/profiles/{profilesId}/commands",
                  "path": "v1/{+parent}/commands"
                }
              }
            }
          }
        },
        "apps": {
          "methods": {
            "countChromeAppRequests": {
              "id": "chromemanagement.customers.apps.countChromeAppRequests",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "path": "v1/{+customer}/apps:countChromeAppRequests",
              "flatPath": "v1/customers/{customersId}/apps:countChromeAppRequests",
              "description": "Generate summary of app installation requests.",
              "httpMethod": "GET"
            },
            "fetchDevicesRequestingExtension": {
              "description": "Get a list of devices that have requested to install an extension.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "id": "chromemanagement.customers.apps.fetchDevicesRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchDevicesRequestingExtension",
              "path": "v1/{+customer}/apps:fetchDevicesRequestingExtension"
            },
            "fetchUsersRequestingExtension": {
              "description": "Get a list of users that have requested to install an extension.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
              ],
              "id": "chromemanagement.customers.apps.fetchUsersRequestingExtension",
              "flatPath": "v1/customers/{customersId}/apps:fetchUsersRequestingExtension",
              "path": "v1/{+customer}/apps:fetchUsersRequestingExtension"
            }
          },
          "resources": {
            "chrome": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/chrome/{chromeId}",
                  "id": "chromemanagement.customers.apps.chrome.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "web": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/customers/{customersId}/apps/web/{webId}",
                  "id": "chromemanagement.customers.apps.web.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name."
                }
              }
            },
            "android": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "description": "Get a specific app for a customer by its resource name.",
                  "flatPath": "v1/customers/{customersId}/apps/android/{androidId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/chrome.management.appdetails.readonly"
                  ],
                  "id": "chromemanagement.customers.apps.android.get"
                }
              }
            }
          }
        }
      }
    },
    "operations": {
      "methods": {
        "list": {
          "id": "chromemanagement.operations.list",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "path": "v1/{+name}",
          "flatPath": "v1/operations",
          "httpMethod": "GET"
        },
        "delete": {
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "id": "chromemanagement.operations.delete",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "DELETE",
          "path": "v1/{+name}"
        },
        "cancel": {
          "id": "chromemanagement.operations.cancel",
          "path": "v1/{+name}:cancel",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "httpMethod": "POST"
        }
      }
    }
  },
  "batchPath": "batch",
  "canonicalName": "Chrome Management",
  "mtlsRootUrl": "https://chromemanagement.mtls.googleapis.com/",
  "documentationLink": "https://developers.google.com/chrome/management/",
  "protocol": "rest",
  "revision": "20260507",
  "id": "chromemanagement:v1",
  "description": "The Chrome Management API is a suite of services that allows Chrome administrators to view, manage and gain insights on their Chrome OS and Chrome Browser devices.",
  "version": "v1",
  "baseUrl": "https://chromemanagement.googleapis.com/",
  "servicePath": "",
  "basePath": "",
  "ownerName": "Google",
  "version_module": true,
  "kind": "discovery#restDescription",
  "rootUrl": "https://chromemanagement.googleapis.com/"
}