{
  "id": "classroom:v1",
  "basePath": "",
  "title": "Google Classroom API",
  "servicePath": "",
  "protocol": "rest",
  "name": "classroom",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/classroom.courses": {
          "description": "See, edit, create, and permanently delete your Google Classroom classes"
        },
        "https://www.googleapis.com/auth/classroom.announcements.readonly": {
          "description": "View announcements in Google Classroom"
        },
        "https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly": {
          "description": "View your Google Classroom guardians"
        },
        "https://www.googleapis.com/auth/classroom.rosters": {
          "description": "Manage your Google Classroom class rosters"
        },
        "https://www.googleapis.com/auth/classroom.addons.teacher": {
          "description": "See, create, and update its own attachments to posts in classes you teach in Google Classroom"
        },
        "https://www.googleapis.com/auth/classroom.courseworkmaterials": {
          "description": "See, edit, and create classwork materials in Google Classroom"
        },
        "https://www.googleapis.com/auth/classroom.topics.readonly": {
          "description": "View topics in Google Classroom"
        },
        "https://www.googleapis.com/auth/classroom.topics": {
          "description": "See, create, and edit topics in Google Classroom"
        },
        "https://www.googleapis.com/auth/classroom.coursework.me.readonly": {
          "description": "View your course work and grades in Google Classroom"
        },
        "https://www.googleapis.com/auth/classroom.announcements": {
          "description": "View and manage announcements in Google Classroom"
        },
        "https://www.googleapis.com/auth/classroom.push-notifications": {
          "description": "Receive notifications about your Google Classroom data"
        },
        "https://www.googleapis.com/auth/classroom.coursework.me": {
          "description": "See, create and edit coursework items including assignments, questions, and grades"
        },
        "https://www.googleapis.com/auth/classroom.rosters.readonly": {
          "description": "View your Google Classroom class rosters"
        },
        "https://www.googleapis.com/auth/classroom.student-submissions.me.readonly": {
          "description": "View your course work and grades in Google Classroom"
        },
        "https://www.googleapis.com/auth/classroom.student-submissions.students.readonly": {
          "description": "View course work and grades for students in the Google Classroom classes you teach or administer"
        },
        "https://www.googleapis.com/auth/classroom.courses.readonly": {
          "description": "View your Google Classroom classes"
        },
        "https://www.googleapis.com/auth/classroom.coursework.students": {
          "description": "Manage course work and grades for students in the Google Classroom classes you teach and view the course work and grades for classes you administer"
        },
        "https://www.googleapis.com/auth/classroom.courseworkmaterials.readonly": {
          "description": "See all classwork materials for your Google Classroom classes"
        },
        "https://www.googleapis.com/auth/classroom.profile.emails": {
          "description": "View the email addresses of people in your classes"
        },
        "https://www.googleapis.com/auth/classroom.profile.photos": {
          "description": "View the profile photos of people in your classes"
        },
        "https://www.googleapis.com/auth/classroom.coursework.students.readonly": {
          "description": "View course work and grades for students in the Google Classroom classes you teach or administer"
        },
        "https://www.googleapis.com/auth/classroom.guardianlinks.students": {
          "description": "View and manage guardians for students in your Google Classroom classes"
        },
        "https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly": {
          "description": "View guardians for students in your Google Classroom classes"
        },
        "https://www.googleapis.com/auth/classroom.addons.student": {
          "description": "See and update its own attachments to posts in Google Classroom"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/workspace/classroom/",
  "fullyEncodeReservedExpansion": true,
  "discoveryVersion": "v1",
  "revision": "20260303",
  "baseUrl": "https://classroom.googleapis.com/",
  "version": "v1",
  "rootUrl": "https://classroom.googleapis.com/",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "description": "Manages classes, rosters, and invitations in Google Classroom.",
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://classroom.mtls.googleapis.com/",
  "resources": {
    "invitations": {
      "methods": {
        "list": {
          "description": "Returns a list of invitations that the requesting user is permitted to view, restricted to those that match the list request. *Note:* At least one of `user_id` or `course_id` must be supplied. Both fields can be supplied. This method returns the following error codes: * `PERMISSION_DENIED` for access errors.",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.rosters",
            "https://www.googleapis.com/auth/classroom.rosters.readonly"
          ],
          "id": "classroom.invitations.list",
          "path": "v1/invitations",
          "flatPath": "v1/invitations",
          "httpMethod": "GET"
        },
        "create": {
          "flatPath": "v1/invitations",
          "httpMethod": "POST",
          "id": "classroom.invitations.create",
          "path": "v1/invitations",
          "description": "Creates an invitation. Only one invitation for a user and course may exist at a time. Delete and re-create an invitation to make changes. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create invitations for this course or for access errors. * `NOT_FOUND` if the course or the user does not exist. * `FAILED_PRECONDITION`: * if the requested user's account is disabled. * if the user already has this role or [...]",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.rosters"
          ]
        },
        "accept": {
          "flatPath": "v1/invitations/{id}:accept",
          "httpMethod": "POST",
          "id": "classroom.invitations.accept",
          "path": "v1/invitations/{id}:accept",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.rosters"
          ],
          "description": "Accepts an invitation, removing it and adding the invited user to the teachers or students (as appropriate) of the specified course. Only the invited user may accept an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to accept the requested invitation or for access errors. * `FAILED_PRECONDITION` for the following request errors: * CourseMemberLimitReached * CourseNotModifiable * CourseTeacherLimit[...]"
        },
        "delete": {
          "id": "classroom.invitations.delete",
          "path": "v1/invitations/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.rosters"
          ],
          "description": "Deletes an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested invitation or for access errors. * `NOT_FOUND` if no invitation exists with the requested ID.",
          "flatPath": "v1/invitations/{id}",
          "httpMethod": "DELETE"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "v1/invitations/{id}",
          "description": "Returns an invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view the requested invitation or for access errors. * `NOT_FOUND` if no invitation exists with the requested ID.",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.rosters",
            "https://www.googleapis.com/auth/classroom.rosters.readonly"
          ],
          "id": "classroom.invitations.get",
          "path": "v1/invitations/{id}"
        }
      }
    },
    "courses": {
      "methods": {
        "list": {
          "id": "classroom.courses.list",
          "path": "v1/courses",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.courses",
            "https://www.googleapis.com/auth/classroom.courses.readonly"
          ],
          "description": "Returns a list of courses that the requesting user is permitted to view, restricted to those that match the request. Returned courses are ordered by creation time, with the most recently created coming first. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the query argument is malformed. * `NOT_FOUND` if any users specified in the query arguments do not exist.",
          "flatPath": "v1/courses",
          "httpMethod": "GET"
        },
        "getGradingPeriodSettings": {
          "flatPath": "v1/courses/{courseId}/gradingPeriodSettings",
          "httpMethod": "GET",
          "description": "Returns the grading period settings in a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user isn't permitted to access the grading period settings in the requested course or for access errors. * `NOT_FOUND` if the requested course does not exist.",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.courses",
            "https://www.googleapis.com/auth/classroom.courses.readonly"
          ],
          "id": "classroom.courses.getGradingPeriodSettings",
          "path": "v1/courses/{courseId}/gradingPeriodSettings"
        },
        "get": {
          "id": "classroom.courses.get",
          "path": "v1/courses/{id}",
          "description": "Returns a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID.",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.courses",
            "https://www.googleapis.com/auth/classroom.courses.readonly"
          ],
          "flatPath": "v1/courses/{id}",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "v1/courses/{id}",
          "id": "classroom.courses.update",
          "path": "v1/courses/{id}",
          "description": "Updates a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID. * `FAILED_PRECONDITION` for the following request errors: * CourseNotModifiable * CourseTitleCannotContainUrl",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.courses"
          ]
        },
        "patch": {
          "description": "Updates one or more fields in a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID. * `INVALID_ARGUMENT` if invalid fields are specified in the update mask or if no update mask is supplied. * `FAILED_PRECONDITION` for the following request errors: * CourseNotModifiable * InactiveCourseOwner * Ineli[...]",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.courses"
          ],
          "id": "classroom.courses.patch",
          "path": "v1/courses/{id}",
          "httpMethod": "PATCH",
          "flatPath": "v1/courses/{id}"
        },
        "delete": {
          "flatPath": "v1/courses/{id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.courses"
          ],
          "description": "Deletes a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested course or for access errors. * `NOT_FOUND` if no course exists with the requested ID.",
          "id": "classroom.courses.delete",
          "path": "v1/courses/{id}"
        },
        "updateGradingPeriodSettings": {
          "id": "classroom.courses.updateGradingPeriodSettings",
          "path": "v1/courses/{courseId}/gradingPeriodSettings",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.courses"
          ],
          "description": "Updates grading period settings of a course. Individual grading periods can be added, removed, or modified using this method. The requesting user and course owner must be eligible to modify Grading Periods. For details, see [licensing requirements](https://developers.google.com/workspace/classroom/grading-periods/manage-grading-periods#licensing_requirements). This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to[...]",
          "httpMethod": "PATCH",
          "flatPath": "v1/courses/{courseId}/gradingPeriodSettings"
        },
        "create": {
          "id": "classroom.courses.create",
          "path": "v1/courses",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.courses"
          ],
          "description": "Creates a course. The user specified in `ownerId` is the owner of the created course and added as a teacher. A non-admin requesting user can only create a course with themselves as the owner. Domain admins can create courses owned by any user within their domain. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create courses or for access errors. * `NOT_FOUND` if the primary teacher is not a valid user. * `[...]",
          "flatPath": "v1/courses",
          "httpMethod": "POST"
        }
      },
      "resources": {
        "courseWorkMaterials": {
          "methods": {
            "create": {
              "description": "Creates a course work material. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course, create course work material in the requested course, share a Drive attachment, or for access errors. * `INVALID_ARGUMENT` if the request is malformed or if more than 20 * materials are provided. * `NOT_FOUND` if the requested course does not exist. * `FAILED_PRECONDITION` for the following reques[...]",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.courseworkmaterials"
              ],
              "id": "classroom.courses.courseWorkMaterials.create",
              "path": "v1/courses/{courseId}/courseWorkMaterials",
              "flatPath": "v1/courses/{courseId}/courseWorkMaterials",
              "httpMethod": "POST"
            },
            "getAddOnContext": {
              "flatPath": "v1/courses/{courseId}/courseWorkMaterials/{itemId}/addOnContext",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.addons.student",
                "https://www.googleapis.com/auth/classroom.addons.teacher"
              ],
              "description": "Gets metadata for Classroom add-ons in the context of a specific post. To maintain the integrity of its own data and permissions model, an add-on should call this to validate query parameters and the requesting user's role whenever the add-on is opened in an [iframe](https://developers.google.com/workspace/classroom/add-ons/get-started/iframes/iframes-overview). This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUME[...]",
              "id": "classroom.courses.courseWorkMaterials.getAddOnContext",
              "path": "v1/courses/{courseId}/courseWorkMaterials/{itemId}/addOnContext"
            },
            "patch": {
              "id": "classroom.courses.courseWorkMaterials.patch",
              "path": "v1/courses/{courseId}/courseWorkMaterials/{id}",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.courseworkmaterials"
              ],
              "description": "Updates one or more fields of a course work material. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting developer project for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `FAILED_PRECONDITION` if the requested course work material has already been deleted. * `NOT_FOUND` if the requested course or course work material does not exist",
              "flatPath": "v1/courses/{courseId}/courseWorkMaterials/{id}",
              "httpMethod": "PATCH"
            },
            "delete": {
              "description": "Deletes a course work material. This request must be made by the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to create the corresponding course work material item. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting developer project did not create the corresponding course work material, if the requesting user is not permitted to delete the requested course or for access [...]",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.courseworkmaterials"
              ],
              "id": "classroom.courses.courseWorkMaterials.delete",
              "path": "v1/courses/{courseId}/courseWorkMaterials/{id}",
              "httpMethod": "DELETE",
              "flatPath": "v1/courses/{courseId}/courseWorkMaterials/{id}"
            },
            "get": {
              "description": "Returns a course work material. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or course work material, or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course or course work material does not exist.",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.courseworkmaterials",
                "https://www.googleapis.com/auth/classroom.courseworkmaterials.readonly"
              ],
              "id": "classroom.courses.courseWorkMaterials.get",
              "path": "v1/courses/{courseId}/courseWorkMaterials/{id}",
              "httpMethod": "GET",
              "flatPath": "v1/courses/{courseId}/courseWorkMaterials/{id}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/classroom.courseworkmaterials",
                "https://www.googleapis.com/auth/classroom.courseworkmaterials.readonly"
              ],
              "description": "Returns a list of course work material that the requester is permitted to view. Course students may only view `PUBLISHED` course work material. Course teachers and domain administrators may view all course work material. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course[...]",
              "id": "classroom.courses.courseWorkMaterials.list",
              "path": "v1/courses/{courseId}/courseWorkMaterials",
              "flatPath": "v1/courses/{courseId}/courseWorkMaterials",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "addOnAttachments": {
              "methods": {
                "list": {
                  "description": "Returns all attachments created by an add-on under the post. Requires the add-on to have active attachments on the post or have permission to create new attachments on the post. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.student",
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "id": "classroom.courses.courseWorkMaterials.addOnAttachments.list",
                  "path": "v1/courses/{courseId}/courseWorkMaterials/{itemId}/addOnAttachments",
                  "httpMethod": "GET",
                  "flatPath": "v1/courses/{courseId}/courseWorkMaterials/{itemId}/addOnAttachments"
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v1/courses/{courseId}/courseWorkMaterials/{itemId}/addOnAttachments",
                  "description": "Creates an add-on attachment under a post. Requires the add-on to have permission to create new attachments on the post. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "id": "classroom.courses.courseWorkMaterials.addOnAttachments.create",
                  "path": "v1/courses/{courseId}/courseWorkMaterials/{itemId}/addOnAttachments"
                },
                "patch": {
                  "id": "classroom.courses.courseWorkMaterials.addOnAttachments.patch",
                  "path": "v1/courses/{courseId}/courseWorkMaterials/{itemId}/addOnAttachments/{attachmentId}",
                  "description": "Updates an add-on attachment. Requires the add-on to have been the original creator of the attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "flatPath": "v1/courses/{courseId}/courseWorkMaterials/{itemId}/addOnAttachments/{attachmentId}",
                  "httpMethod": "PATCH"
                },
                "delete": {
                  "flatPath": "v1/courses/{courseId}/courseWorkMaterials/{itemId}/addOnAttachments/{attachmentId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes an add-on attachment. Requires the add-on to have been the original creator of the attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "id": "classroom.courses.courseWorkMaterials.addOnAttachments.delete",
                  "path": "v1/courses/{courseId}/courseWorkMaterials/{itemId}/addOnAttachments/{attachmentId}"
                },
                "get": {
                  "id": "classroom.courses.courseWorkMaterials.addOnAttachments.get",
                  "path": "v1/courses/{courseId}/courseWorkMaterials/{itemId}/addOnAttachments/{attachmentId}",
                  "description": "Returns an add-on attachment. Requires the add-on requesting the attachment to be the original creator of the attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.student",
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/courses/{courseId}/courseWorkMaterials/{itemId}/addOnAttachments/{attachmentId}"
                }
              }
            }
          }
        },
        "topics": {
          "methods": {
            "create": {
              "id": "classroom.courses.topics.create",
              "path": "v1/courses/{courseId}/topics",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.topics"
              ],
              "description": "Creates a topic. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course, create a topic in the requested course, or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `ALREADY_EXISTS` if there exists a topic in the course with the same name. * `FAILED_PRECONDITION` for the following request error: * CourseTopicLimitReached * `NOT_FOUND` if the requested course do[...]",
              "httpMethod": "POST",
              "flatPath": "v1/courses/{courseId}/topics"
            },
            "patch": {
              "description": "Updates one or more fields of a topic. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting developer project did not create the corresponding topic or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `FAILED_PRECONDITION` if there exists a topic in the course with the same name. * `NOT_FOUND` if the requested course or topic does not exist",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.topics"
              ],
              "id": "classroom.courses.topics.patch",
              "path": "v1/courses/{courseId}/topics/{id}",
              "flatPath": "v1/courses/{courseId}/topics/{id}",
              "httpMethod": "PATCH"
            },
            "delete": {
              "flatPath": "v1/courses/{courseId}/topics/{id}",
              "httpMethod": "DELETE",
              "id": "classroom.courses.topics.delete",
              "path": "v1/courses/{courseId}/topics/{id}",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.topics"
              ],
              "description": "Deletes a topic. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not allowed to delete the requested topic or for access errors. * `FAILED_PRECONDITION` if the requested topic has already been deleted. * `NOT_FOUND` if no course or topic exists with the requested ID."
            },
            "get": {
              "flatPath": "v1/courses/{courseId}/topics/{id}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.topics",
                "https://www.googleapis.com/auth/classroom.topics.readonly"
              ],
              "description": "Returns a topic. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or topic, or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course or topic does not exist.",
              "id": "classroom.courses.topics.get",
              "path": "v1/courses/{courseId}/topics/{id}"
            },
            "list": {
              "description": "Returns the list of topics that the requester is permitted to view. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course does not exist.",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.topics",
                "https://www.googleapis.com/auth/classroom.topics.readonly"
              ],
              "id": "classroom.courses.topics.list",
              "path": "v1/courses/{courseId}/topics",
              "httpMethod": "GET",
              "flatPath": "v1/courses/{courseId}/topics"
            }
          }
        },
        "posts": {
          "methods": {
            "getAddOnContext": {
              "httpMethod": "GET",
              "flatPath": "v1/courses/{courseId}/posts/{postId}/addOnContext",
              "description": "Gets metadata for Classroom add-ons in the context of a specific post. To maintain the integrity of its own data and permissions model, an add-on should call this to validate query parameters and the requesting user's role whenever the add-on is opened in an [iframe](https://developers.google.com/workspace/classroom/add-ons/get-started/iframes/iframes-overview). This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUME[...]",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.addons.student",
                "https://www.googleapis.com/auth/classroom.addons.teacher"
              ],
              "id": "classroom.courses.posts.getAddOnContext",
              "path": "v1/courses/{courseId}/posts/{postId}/addOnContext"
            }
          },
          "resources": {
            "addOnAttachments": {
              "methods": {
                "list": {
                  "description": "Returns all attachments created by an add-on under the post. Requires the add-on to have active attachments on the post or have permission to create new attachments on the post. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.student",
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "id": "classroom.courses.posts.addOnAttachments.list",
                  "path": "v1/courses/{courseId}/posts/{postId}/addOnAttachments",
                  "httpMethod": "GET",
                  "flatPath": "v1/courses/{courseId}/posts/{postId}/addOnAttachments"
                },
                "patch": {
                  "description": "Updates an add-on attachment. Requires the add-on to have been the original creator of the attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "id": "classroom.courses.posts.addOnAttachments.patch",
                  "path": "v1/courses/{courseId}/posts/{postId}/addOnAttachments/{attachmentId}",
                  "flatPath": "v1/courses/{courseId}/posts/{postId}/addOnAttachments/{attachmentId}",
                  "httpMethod": "PATCH"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "description": "Deletes an add-on attachment. Requires the add-on to have been the original creator of the attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "id": "classroom.courses.posts.addOnAttachments.delete",
                  "path": "v1/courses/{courseId}/posts/{postId}/addOnAttachments/{attachmentId}",
                  "flatPath": "v1/courses/{courseId}/posts/{postId}/addOnAttachments/{attachmentId}",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "description": "Returns an add-on attachment. Requires the add-on requesting the attachment to be the original creator of the attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.student",
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "id": "classroom.courses.posts.addOnAttachments.get",
                  "path": "v1/courses/{courseId}/posts/{postId}/addOnAttachments/{attachmentId}",
                  "httpMethod": "GET",
                  "flatPath": "v1/courses/{courseId}/posts/{postId}/addOnAttachments/{attachmentId}"
                },
                "create": {
                  "description": "Creates an add-on attachment under a post. Requires the add-on to have permission to create new attachments on the post. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "id": "classroom.courses.posts.addOnAttachments.create",
                  "path": "v1/courses/{courseId}/posts/{postId}/addOnAttachments",
                  "flatPath": "v1/courses/{courseId}/posts/{postId}/addOnAttachments",
                  "httpMethod": "POST"
                }
              },
              "resources": {
                "studentSubmissions": {
                  "methods": {
                    "patch": {
                      "flatPath": "v1/courses/{courseId}/posts/{postId}/addOnAttachments/{attachmentId}/studentSubmissions/{submissionId}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/classroom.addons.teacher"
                      ],
                      "description": "Updates data associated with an add-on attachment submission. Requires the add-on to have been the original creator of the attachment and the attachment to have a positive `max_points` value set. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                      "id": "classroom.courses.posts.addOnAttachments.studentSubmissions.patch",
                      "path": "v1/courses/{courseId}/posts/{postId}/addOnAttachments/{attachmentId}/studentSubmissions/{submissionId}"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/classroom.addons.student",
                        "https://www.googleapis.com/auth/classroom.addons.teacher",
                        "https://www.googleapis.com/auth/classroom.student-submissions.students.readonly"
                      ],
                      "description": "Returns a student submission for an add-on attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                      "id": "classroom.courses.posts.addOnAttachments.studentSubmissions.get",
                      "path": "v1/courses/{courseId}/posts/{postId}/addOnAttachments/{attachmentId}/studentSubmissions/{submissionId}",
                      "httpMethod": "GET",
                      "flatPath": "v1/courses/{courseId}/posts/{postId}/addOnAttachments/{attachmentId}/studentSubmissions/{submissionId}"
                    }
                  }
                }
              }
            }
          }
        },
        "courseWork": {
          "methods": {
            "create": {
              "flatPath": "v1/courses/{courseId}/courseWork",
              "httpMethod": "POST",
              "id": "classroom.courses.courseWork.create",
              "path": "v1/courses/{courseId}/courseWork",
              "description": "Creates course work. The resulting course work (and corresponding student submissions) are associated with the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to make the request. Classroom API requests to modify course work and student submissions must be made with an OAuth client ID from the associated Developer Console project. This method returns the following error codes: * `PERMISSION_DENIED` if the requ[...]",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.coursework.students"
              ]
            },
            "getAddOnContext": {
              "scopes": [
                "https://www.googleapis.com/auth/classroom.addons.student",
                "https://www.googleapis.com/auth/classroom.addons.teacher"
              ],
              "description": "Gets metadata for Classroom add-ons in the context of a specific post. To maintain the integrity of its own data and permissions model, an add-on should call this to validate query parameters and the requesting user's role whenever the add-on is opened in an [iframe](https://developers.google.com/workspace/classroom/add-ons/get-started/iframes/iframes-overview). This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUME[...]",
              "id": "classroom.courses.courseWork.getAddOnContext",
              "path": "v1/courses/{courseId}/courseWork/{itemId}/addOnContext",
              "httpMethod": "GET",
              "flatPath": "v1/courses/{courseId}/courseWork/{itemId}/addOnContext"
            },
            "patch": {
              "httpMethod": "PATCH",
              "flatPath": "v1/courses/{courseId}/courseWork/{id}",
              "id": "classroom.courses.courseWork.patch",
              "path": "v1/courses/{courseId}/courseWork/{id}",
              "description": "Updates one or more fields of a course work. See google.classroom.v1.CourseWork for details of which fields may be updated and who may change them. This request must be made by the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to create the corresponding course work item. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting developer project did not create the corresponding [...]",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.coursework.students"
              ]
            },
            "delete": {
              "description": "Deletes a course work. This request must be made by the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to create the corresponding course work item. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting developer project did not create the corresponding course work, if the requesting user is not permitted to delete the requested course or for access errors. * `FAILED_PRECONDIT[...]",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.coursework.students"
              ],
              "id": "classroom.courses.courseWork.delete",
              "path": "v1/courses/{courseId}/courseWork/{id}",
              "flatPath": "v1/courses/{courseId}/courseWork/{id}",
              "httpMethod": "DELETE"
            },
            "get": {
              "description": "Returns course work. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or course work, or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course or course work does not exist.",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.coursework.me",
                "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
                "https://www.googleapis.com/auth/classroom.coursework.students",
                "https://www.googleapis.com/auth/classroom.coursework.students.readonly"
              ],
              "id": "classroom.courses.courseWork.get",
              "path": "v1/courses/{courseId}/courseWork/{id}",
              "flatPath": "v1/courses/{courseId}/courseWork/{id}",
              "httpMethod": "GET"
            },
            "modifyAssignees": {
              "flatPath": "v1/courses/{courseId}/courseWork/{id}:modifyAssignees",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.coursework.students"
              ],
              "description": "Modifies assignee mode and options of a coursework. Only a teacher of the course that contains the coursework may call this method. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or course work or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course or course work does not exist. * `FAILED_PRECONDITION` for the following [...]",
              "id": "classroom.courses.courseWork.modifyAssignees",
              "path": "v1/courses/{courseId}/courseWork/{id}:modifyAssignees"
            },
            "list": {
              "flatPath": "v1/courses/{courseId}/courseWork",
              "httpMethod": "GET",
              "description": "Returns a list of course work that the requester is permitted to view. Course students may only view `PUBLISHED` course work. Course teachers and domain administrators may view all course work. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course does not exist.",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.coursework.me",
                "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
                "https://www.googleapis.com/auth/classroom.coursework.students",
                "https://www.googleapis.com/auth/classroom.coursework.students.readonly"
              ],
              "id": "classroom.courses.courseWork.list",
              "path": "v1/courses/{courseId}/courseWork"
            },
            "updateRubric": {
              "scopes": [
                "https://www.googleapis.com/auth/classroom.coursework.students"
              ],
              "description": "Updates a rubric. See google.classroom.v1.Rubric for details of which fields can be updated. Rubric update capabilities are [limited](/classroom/rubrics/limitations) once grading has started. The requesting user and course owner must have rubrics creation capabilities. For details, see [licensing requirements](https://developers.google.com/workspace/classroom/rubrics/limitations#license-requirements). This request must be made by the Google Cloud console of the [OAu[...]",
              "id": "classroom.courses.courseWork.updateRubric",
              "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/rubric",
              "httpMethod": "PATCH",
              "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/rubric"
            }
          },
          "resources": {
            "studentSubmissions": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.coursework.me",
                    "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
                    "https://www.googleapis.com/auth/classroom.coursework.students",
                    "https://www.googleapis.com/auth/classroom.coursework.students.readonly",
                    "https://www.googleapis.com/auth/classroom.student-submissions.me.readonly",
                    "https://www.googleapis.com/auth/classroom.student-submissions.students.readonly"
                  ],
                  "description": "Returns a list of student submissions that the requester is permitted to view, factoring in the OAuth scopes of the request. A hyphen (`-`) may be specified as the `course_work_id` to include student submissions for multiple course work items. Course students may only view their own work. Course teachers and domain administrators may view all student submissions. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not p[...]",
                  "id": "classroom.courses.courseWork.studentSubmissions.list",
                  "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions",
                  "httpMethod": "GET",
                  "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions"
                },
                "return": {
                  "httpMethod": "POST",
                  "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:return",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.coursework.students"
                  ],
                  "description": "Returns a student submission. Returning a student submission transfers ownership of attached Drive files to the student and may also update the submission state. Unlike the Classroom application, returning a student submission does not set assignedGrade to the draftGrade value. Only a teacher of the course that contains the requested student submission may call this method. This request must be made by the Developer Console project of the [OAuth client ID](https[...]",
                  "id": "classroom.courses.courseWork.studentSubmissions.return",
                  "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:return"
                },
                "patch": {
                  "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.coursework.me",
                    "https://www.googleapis.com/auth/classroom.coursework.students"
                  ],
                  "description": "Updates one or more fields of a student submission. See google.classroom.v1.StudentSubmission for details of which fields may be updated and who may change them. This request must be made by the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to create the corresponding course work item. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting developer project did not create [...]",
                  "id": "classroom.courses.courseWork.studentSubmissions.patch",
                  "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}"
                },
                "get": {
                  "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.coursework.me",
                    "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
                    "https://www.googleapis.com/auth/classroom.coursework.students",
                    "https://www.googleapis.com/auth/classroom.coursework.students.readonly",
                    "https://www.googleapis.com/auth/classroom.student-submissions.me.readonly",
                    "https://www.googleapis.com/auth/classroom.student-submissions.students.readonly"
                  ],
                  "description": "Returns a student submission. * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course, course work, or student submission or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course, course work, or student submission does not exist.",
                  "id": "classroom.courses.courseWork.studentSubmissions.get",
                  "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}"
                },
                "reclaim": {
                  "httpMethod": "POST",
                  "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:reclaim",
                  "id": "classroom.courses.courseWork.studentSubmissions.reclaim",
                  "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:reclaim",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.coursework.me"
                  ],
                  "description": "Reclaims a student submission on behalf of the student that owns it. Reclaiming a student submission transfers ownership of attached Drive files to the student and updates the submission state. Only the student that owns the requested student submission may call this method, and only for a student submission that has been turned in. This request must be made by the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849[...]"
                },
                "modifyAttachments": {
                  "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:modifyAttachments",
                  "httpMethod": "POST",
                  "description": "Modifies attachments of student submission. Attachments may only be added to student submissions belonging to course work objects with a `workType` of `ASSIGNMENT`. This request must be made by the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to create the corresponding course work item. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to acces[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.coursework.me",
                    "https://www.googleapis.com/auth/classroom.coursework.students"
                  ],
                  "id": "classroom.courses.courseWork.studentSubmissions.modifyAttachments",
                  "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:modifyAttachments"
                },
                "turnIn": {
                  "id": "classroom.courses.courseWork.studentSubmissions.turnIn",
                  "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:turnIn",
                  "description": "Turns in a student submission. Turning in a student submission transfers ownership of attached Drive files to the teacher and may also update the submission state. This may only be called by the student that owns the specified student submission. This request must be made by the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to create the corresponding course work item. This method returns the following e[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.coursework.me"
                  ],
                  "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/studentSubmissions/{id}:turnIn",
                  "httpMethod": "POST"
                }
              }
            },
            "rubrics": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/rubrics",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.coursework.me",
                    "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
                    "https://www.googleapis.com/auth/classroom.coursework.students",
                    "https://www.googleapis.com/auth/classroom.coursework.students.readonly"
                  ],
                  "description": "Returns a list of rubrics that the requester is permitted to view. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course or course work doesn't exist or if the user doesn't have access to the corresponding course work.",
                  "id": "classroom.courses.courseWork.rubrics.list",
                  "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/rubrics"
                },
                "get": {
                  "description": "Returns a rubric. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course, course work, or rubric doesn't exist or if the user doesn't have access to the corresponding course work.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.coursework.me",
                    "https://www.googleapis.com/auth/classroom.coursework.me.readonly",
                    "https://www.googleapis.com/auth/classroom.coursework.students",
                    "https://www.googleapis.com/auth/classroom.coursework.students.readonly"
                  ],
                  "id": "classroom.courses.courseWork.rubrics.get",
                  "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/rubrics/{id}",
                  "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/rubrics/{id}",
                  "httpMethod": "GET"
                },
                "patch": {
                  "id": "classroom.courses.courseWork.rubrics.patch",
                  "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/rubrics/{id}",
                  "description": "Updates a rubric. See google.classroom.v1.Rubric for details of which fields can be updated. Rubric update capabilities are [limited](/classroom/rubrics/limitations) once grading has started. The requesting user and course owner must have rubrics creation capabilities. For details, see [licensing requirements](https://developers.google.com/workspace/classroom/rubrics/limitations#license-requirements). This request must be made by the Google Cloud console of the [...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.coursework.students"
                  ],
                  "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/rubrics/{id}",
                  "httpMethod": "PATCH"
                },
                "delete": {
                  "description": "Deletes a rubric. The requesting user and course owner must have rubrics creation capabilities. For details, see [licensing requirements](https://developers.google.com/workspace/classroom/rubrics/limitations#license-requirements). This request must be made by the Google Cloud console of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to create the corresponding rubric. This method returns the following error codes: * `PERMISSION_DENIE[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.coursework.students"
                  ],
                  "id": "classroom.courses.courseWork.rubrics.delete",
                  "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/rubrics/{id}",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/rubrics/{id}"
                },
                "create": {
                  "id": "classroom.courses.courseWork.rubrics.create",
                  "path": "v1/courses/{courseId}/courseWork/{courseWorkId}/rubrics",
                  "description": "Creates a rubric. The requesting user and course owner must have rubrics creation capabilities. For details, see [licensing requirements](https://developers.google.com/workspace/classroom/rubrics/limitations#license-requirements). For further details, see [Rubrics structure and known limitations](/classroom/rubrics/limitations). This request must be made by the Google Cloud console of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.coursework.students"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/courses/{courseId}/courseWork/{courseWorkId}/rubrics"
                }
              }
            },
            "addOnAttachments": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.student",
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "description": "Returns all attachments created by an add-on under the post. Requires the add-on to have active attachments on the post or have permission to create new attachments on the post. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "id": "classroom.courses.courseWork.addOnAttachments.list",
                  "path": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments"
                },
                "get": {
                  "id": "classroom.courses.courseWork.addOnAttachments.get",
                  "path": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments/{attachmentId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.student",
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "description": "Returns an add-on attachment. Requires the add-on requesting the attachment to be the original creator of the attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "flatPath": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments/{attachmentId}",
                  "httpMethod": "GET"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "flatPath": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments/{attachmentId}",
                  "description": "Updates an add-on attachment. Requires the add-on to have been the original creator of the attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "id": "classroom.courses.courseWork.addOnAttachments.patch",
                  "path": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments/{attachmentId}"
                },
                "delete": {
                  "id": "classroom.courses.courseWork.addOnAttachments.delete",
                  "path": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments/{attachmentId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "description": "Deletes an add-on attachment. Requires the add-on to have been the original creator of the attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "flatPath": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments/{attachmentId}",
                  "httpMethod": "DELETE"
                },
                "create": {
                  "flatPath": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "description": "Creates an add-on attachment under a post. Requires the add-on to have permission to create new attachments on the post. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "id": "classroom.courses.courseWork.addOnAttachments.create",
                  "path": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments"
                }
              },
              "resources": {
                "studentSubmissions": {
                  "methods": {
                    "patch": {
                      "httpMethod": "PATCH",
                      "flatPath": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments/{attachmentId}/studentSubmissions/{submissionId}",
                      "id": "classroom.courses.courseWork.addOnAttachments.studentSubmissions.patch",
                      "path": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments/{attachmentId}/studentSubmissions/{submissionId}",
                      "description": "Updates data associated with an add-on attachment submission. Requires the add-on to have been the original creator of the attachment and the attachment to have a positive `max_points` value set. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                      "scopes": [
                        "https://www.googleapis.com/auth/classroom.addons.teacher"
                      ]
                    },
                    "get": {
                      "flatPath": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments/{attachmentId}/studentSubmissions/{submissionId}",
                      "httpMethod": "GET",
                      "description": "Returns a student submission for an add-on attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                      "scopes": [
                        "https://www.googleapis.com/auth/classroom.addons.student",
                        "https://www.googleapis.com/auth/classroom.addons.teacher",
                        "https://www.googleapis.com/auth/classroom.student-submissions.students.readonly"
                      ],
                      "id": "classroom.courses.courseWork.addOnAttachments.studentSubmissions.get",
                      "path": "v1/courses/{courseId}/courseWork/{itemId}/addOnAttachments/{attachmentId}/studentSubmissions/{submissionId}"
                    }
                  }
                }
              }
            }
          }
        },
        "studentGroups": {
          "methods": {
            "create": {
              "flatPath": "v1/courses/{courseId}/studentGroups",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.rosters"
              ],
              "description": "Creates a student group for a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create the student group or for access errors. * `NOT_FOUND` if the course does not exist or the requesting user doesn't have access to the course. * `FAILED_PRECONDITION` if creating the student group would exceed the maximum number of student groups per course.",
              "id": "classroom.courses.studentGroups.create",
              "path": "v1/courses/{courseId}/studentGroups"
            },
            "delete": {
              "id": "classroom.courses.studentGroups.delete",
              "path": "v1/courses/{courseId}/studentGroups/{id}",
              "description": "Deletes a student group. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested student group or for access errors. * `NOT_FOUND` if the student group does not exist or the user does not have access to the student group.",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.rosters"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1/courses/{courseId}/studentGroups/{id}"
            },
            "patch": {
              "flatPath": "v1/courses/{courseId}/studentGroups/{id}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.rosters"
              ],
              "description": "Updates one or more fields in a student group. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to modify the requested student group or for access errors. * `NOT_FOUND` if the student group does not exist or the user does not have access to the student group. * `INVALID_ARGUMENT` if invalid fields are specified in the update mask or if no update mask is supplied.",
              "id": "classroom.courses.studentGroups.patch",
              "path": "v1/courses/{courseId}/studentGroups/{id}"
            },
            "list": {
              "flatPath": "v1/courses/{courseId}/studentGroups",
              "httpMethod": "GET",
              "description": "Returns a list of groups in a course. This method returns the following error codes: * `NOT_FOUND` if the course does not exist.",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.rosters",
                "https://www.googleapis.com/auth/classroom.rosters.readonly"
              ],
              "id": "classroom.courses.studentGroups.list",
              "path": "v1/courses/{courseId}/studentGroups"
            }
          },
          "resources": {
            "studentGroupMembers": {
              "methods": {
                "list": {
                  "flatPath": "v1/courses/{courseId}/studentGroups/{studentGroupId}/studentGroupMembers",
                  "httpMethod": "GET",
                  "id": "classroom.courses.studentGroups.studentGroupMembers.list",
                  "path": "v1/courses/{courseId}/studentGroups/{studentGroupId}/studentGroupMembers",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.rosters",
                    "https://www.googleapis.com/auth/classroom.rosters.readonly"
                  ],
                  "description": "Returns a list of students in a group. This method returns the following error codes: * `NOT_FOUND` if the course or student group does not exist."
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v1/courses/{courseId}/studentGroups/{studentGroupId}/studentGroupMembers/{userId}",
                  "id": "classroom.courses.studentGroups.studentGroupMembers.delete",
                  "path": "v1/courses/{courseId}/studentGroups/{studentGroupId}/studentGroupMembers/{userId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.rosters"
                  ],
                  "description": "Deletes a student group member. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete the requested student group member or for access errors. * `NOT_FOUND` if the student group member does not exist or the user does not have access to the student group."
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v1/courses/{courseId}/studentGroups/{studentGroupId}/studentGroupMembers",
                  "id": "classroom.courses.studentGroups.studentGroupMembers.create",
                  "path": "v1/courses/{courseId}/studentGroups/{studentGroupId}/studentGroupMembers",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.rosters"
                  ],
                  "description": "Creates a student group member for a student group. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create the student group or member for access errors. * `NOT_FOUND` if the student group does not exist or the user does not have access to the student group. * `ALREADY_EXISTS` if the student group member already exists. * `FAILED_PRECONDITION` if attempting to add a member to a student group that ha[...]"
                }
              }
            }
          }
        },
        "aliases": {
          "methods": {
            "list": {
              "id": "classroom.courses.aliases.list",
              "path": "v1/courses/{courseId}/aliases",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.courses",
                "https://www.googleapis.com/auth/classroom.courses.readonly"
              ],
              "description": "Returns a list of aliases for a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the course or for access errors. * `NOT_FOUND` if the course does not exist.",
              "httpMethod": "GET",
              "flatPath": "v1/courses/{courseId}/aliases"
            },
            "delete": {
              "description": "Deletes an alias of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to remove the alias or for access errors. * `NOT_FOUND` if the alias does not exist. * `FAILED_PRECONDITION` if the alias requested does not make sense for the requesting user or course (for example, if a user not in a domain attempts to delete a domain-scoped alias).",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.courses"
              ],
              "id": "classroom.courses.aliases.delete",
              "path": "v1/courses/{courseId}/aliases/{alias}",
              "flatPath": "v1/courses/{courseId}/aliases/{alias}",
              "httpMethod": "DELETE"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1/courses/{courseId}/aliases",
              "id": "classroom.courses.aliases.create",
              "path": "v1/courses/{courseId}/aliases",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.courses"
              ],
              "description": "Creates an alias for a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create the alias or for access errors. * `NOT_FOUND` if the course does not exist. * `ALREADY_EXISTS` if the alias already exists. * `FAILED_PRECONDITION` if the alias requested does not make sense for the requesting user or course (for example, if a user not in a domain attempts to access a domain-scoped alias)."
            }
          }
        },
        "students": {
          "methods": {
            "create": {
              "description": "Adds a user as a student of a course. Domain administrators are permitted to [directly add](https://developers.google.com/workspace/classroom/guides/manage-users) users within their domain as students to courses within their domain. Students are permitted to add themselves to a course using an enrollment code. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create students in this course or for access e[...]",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.profile.emails",
                "https://www.googleapis.com/auth/classroom.profile.photos",
                "https://www.googleapis.com/auth/classroom.rosters"
              ],
              "id": "classroom.courses.students.create",
              "path": "v1/courses/{courseId}/students",
              "httpMethod": "POST",
              "flatPath": "v1/courses/{courseId}/students"
            },
            "delete": {
              "flatPath": "v1/courses/{courseId}/students/{userId}",
              "httpMethod": "DELETE",
              "id": "classroom.courses.students.delete",
              "path": "v1/courses/{courseId}/students/{userId}",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.rosters"
              ],
              "description": "Deletes a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete students of this course or for access errors. * `NOT_FOUND` if no student of this course has the requested ID or if the course does not exist."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/classroom.profile.emails",
                "https://www.googleapis.com/auth/classroom.profile.photos",
                "https://www.googleapis.com/auth/classroom.rosters",
                "https://www.googleapis.com/auth/classroom.rosters.readonly"
              ],
              "description": "Returns a student of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view students of this course or for access errors. * `NOT_FOUND` if no student of this course has the requested ID or if the course does not exist.",
              "id": "classroom.courses.students.get",
              "path": "v1/courses/{courseId}/students/{userId}",
              "httpMethod": "GET",
              "flatPath": "v1/courses/{courseId}/students/{userId}"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1/courses/{courseId}/students",
              "id": "classroom.courses.students.list",
              "path": "v1/courses/{courseId}/students",
              "description": "Returns a list of students of this course that the requester is permitted to view. This method returns the following error codes: * `NOT_FOUND` if the course does not exist. * `PERMISSION_DENIED` for access errors.",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.profile.emails",
                "https://www.googleapis.com/auth/classroom.profile.photos",
                "https://www.googleapis.com/auth/classroom.rosters",
                "https://www.googleapis.com/auth/classroom.rosters.readonly"
              ]
            }
          }
        },
        "announcements": {
          "methods": {
            "modifyAssignees": {
              "description": "Modifies assignee mode and options of an announcement. Only a teacher of the course that contains the announcement may call this method. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or course work or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course or course work does not exist. * `FAILED_PRECONDITION` for the follo[...]",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.announcements"
              ],
              "id": "classroom.courses.announcements.modifyAssignees",
              "path": "v1/courses/{courseId}/announcements/{id}:modifyAssignees",
              "httpMethod": "POST",
              "flatPath": "v1/courses/{courseId}/announcements/{id}:modifyAssignees"
            },
            "list": {
              "flatPath": "v1/courses/{courseId}/announcements",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.announcements",
                "https://www.googleapis.com/auth/classroom.announcements.readonly"
              ],
              "description": "Returns a list of announcements that the requester is permitted to view. Course students may only view `PUBLISHED` announcements. Course teachers and domain administrators may view all announcements. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course does not exist.",
              "id": "classroom.courses.announcements.list",
              "path": "v1/courses/{courseId}/announcements"
            },
            "getAddOnContext": {
              "httpMethod": "GET",
              "flatPath": "v1/courses/{courseId}/announcements/{itemId}/addOnContext",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.addons.student",
                "https://www.googleapis.com/auth/classroom.addons.teacher"
              ],
              "description": "Gets metadata for Classroom add-ons in the context of a specific post. To maintain the integrity of its own data and permissions model, an add-on should call this to validate query parameters and the requesting user's role whenever the add-on is opened in an [iframe](https://developers.google.com/workspace/classroom/add-ons/get-started/iframes/iframes-overview). This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUME[...]",
              "id": "classroom.courses.announcements.getAddOnContext",
              "path": "v1/courses/{courseId}/announcements/{itemId}/addOnContext"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/classroom.announcements"
              ],
              "description": "Creates an announcement. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course, create announcements in the requested course, share a Drive attachment, or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course does not exist. * `FAILED_PRECONDITION` for the following request error: * AttachmentNotVisible",
              "id": "classroom.courses.announcements.create",
              "path": "v1/courses/{courseId}/announcements",
              "flatPath": "v1/courses/{courseId}/announcements",
              "httpMethod": "POST"
            },
            "get": {
              "flatPath": "v1/courses/{courseId}/announcements/{id}",
              "httpMethod": "GET",
              "description": "Returns an announcement. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access the requested course or announcement, or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if the requested course or announcement does not exist.",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.announcements",
                "https://www.googleapis.com/auth/classroom.announcements.readonly"
              ],
              "id": "classroom.courses.announcements.get",
              "path": "v1/courses/{courseId}/announcements/{id}"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/classroom.announcements"
              ],
              "description": "Deletes an announcement. This request must be made by the Developer Console project of the [OAuth client ID](https://support.google.com/cloud/answer/6158849) used to create the corresponding announcement item. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting developer project did not create the corresponding announcement, if the requesting user is not permitted to delete the requested course or for access errors. * `FAILED_PRECO[...]",
              "id": "classroom.courses.announcements.delete",
              "path": "v1/courses/{courseId}/announcements/{id}",
              "httpMethod": "DELETE",
              "flatPath": "v1/courses/{courseId}/announcements/{id}"
            },
            "patch": {
              "httpMethod": "PATCH",
              "flatPath": "v1/courses/{courseId}/announcements/{id}",
              "id": "classroom.courses.announcements.patch",
              "path": "v1/courses/{courseId}/announcements/{id}",
              "description": "Updates one or more fields of an announcement. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting developer project did not create the corresponding announcement or for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `FAILED_PRECONDITION` if the requested announcement has already been deleted. * `NOT_FOUND` if the requested course or announcement does not exist",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.announcements"
              ]
            }
          },
          "resources": {
            "addOnAttachments": {
              "methods": {
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v1/courses/{courseId}/announcements/{itemId}/addOnAttachments",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "description": "Creates an add-on attachment under a post. Requires the add-on to have permission to create new attachments on the post. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "id": "classroom.courses.announcements.addOnAttachments.create",
                  "path": "v1/courses/{courseId}/announcements/{itemId}/addOnAttachments"
                },
                "patch": {
                  "id": "classroom.courses.announcements.addOnAttachments.patch",
                  "path": "v1/courses/{courseId}/announcements/{itemId}/addOnAttachments/{attachmentId}",
                  "description": "Updates an add-on attachment. Requires the add-on to have been the original creator of the attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "flatPath": "v1/courses/{courseId}/announcements/{itemId}/addOnAttachments/{attachmentId}",
                  "httpMethod": "PATCH"
                },
                "delete": {
                  "id": "classroom.courses.announcements.addOnAttachments.delete",
                  "path": "v1/courses/{courseId}/announcements/{itemId}/addOnAttachments/{attachmentId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "description": "Deletes an add-on attachment. Requires the add-on to have been the original creator of the attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "flatPath": "v1/courses/{courseId}/announcements/{itemId}/addOnAttachments/{attachmentId}",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "flatPath": "v1/courses/{courseId}/announcements/{itemId}/addOnAttachments/{attachmentId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.student",
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "description": "Returns an add-on attachment. Requires the add-on requesting the attachment to be the original creator of the attachment. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "id": "classroom.courses.announcements.addOnAttachments.get",
                  "path": "v1/courses/{courseId}/announcements/{itemId}/addOnAttachments/{attachmentId}"
                },
                "list": {
                  "description": "Returns all attachments created by an add-on under the post. Requires the add-on to have active attachments on the post or have permission to create new attachments on the post. This method returns the following error codes: * `PERMISSION_DENIED` for access errors. * `INVALID_ARGUMENT` if the request is malformed. * `NOT_FOUND` if one of the identified resources does not exist.",
                  "scopes": [
                    "https://www.googleapis.com/auth/classroom.addons.student",
                    "https://www.googleapis.com/auth/classroom.addons.teacher"
                  ],
                  "id": "classroom.courses.announcements.addOnAttachments.list",
                  "path": "v1/courses/{courseId}/announcements/{itemId}/addOnAttachments",
                  "httpMethod": "GET",
                  "flatPath": "v1/courses/{courseId}/announcements/{itemId}/addOnAttachments"
                }
              }
            }
          }
        },
        "teachers": {
          "methods": {
            "delete": {
              "flatPath": "v1/courses/{courseId}/teachers/{userId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.rosters"
              ],
              "description": "Removes the specified teacher from the specified course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to delete teachers of this course or for access errors. * `NOT_FOUND` if no teacher of this course has the requested ID or if the course does not exist. * `FAILED_PRECONDITION` if the requested ID belongs to the primary teacher of this course. * `FAILED_PRECONDITION` if the requested ID belongs to the o[...]",
              "id": "classroom.courses.teachers.delete",
              "path": "v1/courses/{courseId}/teachers/{userId}"
            },
            "get": {
              "description": "Returns a teacher of a course. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view teachers of this course or for access errors. * `NOT_FOUND` if no teacher of this course has the requested ID or if the course does not exist.",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.profile.emails",
                "https://www.googleapis.com/auth/classroom.profile.photos",
                "https://www.googleapis.com/auth/classroom.rosters",
                "https://www.googleapis.com/auth/classroom.rosters.readonly"
              ],
              "id": "classroom.courses.teachers.get",
              "path": "v1/courses/{courseId}/teachers/{userId}",
              "httpMethod": "GET",
              "flatPath": "v1/courses/{courseId}/teachers/{userId}"
            },
            "list": {
              "flatPath": "v1/courses/{courseId}/teachers",
              "httpMethod": "GET",
              "id": "classroom.courses.teachers.list",
              "path": "v1/courses/{courseId}/teachers",
              "description": "Returns a list of teachers of this course that the requester is permitted to view. This method returns the following error codes: * `NOT_FOUND` if the course does not exist. * `PERMISSION_DENIED` for access errors.",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.profile.emails",
                "https://www.googleapis.com/auth/classroom.profile.photos",
                "https://www.googleapis.com/auth/classroom.rosters",
                "https://www.googleapis.com/auth/classroom.rosters.readonly"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/classroom.profile.emails",
                "https://www.googleapis.com/auth/classroom.profile.photos",
                "https://www.googleapis.com/auth/classroom.rosters"
              ],
              "description": "Creates a teacher of a course. Domain administrators are permitted to [directly add](https://developers.google.com/workspace/classroom/guides/manage-users) users within their domain as teachers to courses within their domain. Non-admin users should send an Invitation instead. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to create teachers in this course or for access errors. * `NOT_FOUND` if the request[...]",
              "id": "classroom.courses.teachers.create",
              "path": "v1/courses/{courseId}/teachers",
              "httpMethod": "POST",
              "flatPath": "v1/courses/{courseId}/teachers"
            }
          }
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "description": "Returns a user profile. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to access this user profile, if no profile exists with the requested ID, or for access errors.",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.profile.emails",
            "https://www.googleapis.com/auth/classroom.profile.photos",
            "https://www.googleapis.com/auth/classroom.rosters",
            "https://www.googleapis.com/auth/classroom.rosters.readonly"
          ],
          "id": "classroom.userProfiles.get",
          "path": "v1/userProfiles/{userId}",
          "httpMethod": "GET",
          "flatPath": "v1/userProfiles/{userId}"
        }
      },
      "resources": {
        "guardians": {
          "methods": {
            "delete": {
              "flatPath": "v1/userProfiles/{studentId}/guardians/{guardianId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.guardianlinks.students"
              ],
              "description": "Deletes a guardian. The guardian will no longer receive guardian notifications and the guardian will no longer be accessible via the API. This method returns the following error codes: * `PERMISSION_DENIED` if no user that matches the provided `student_id` is visible to the requesting user, if the requesting user is not permitted to manage guardians for the student identified by the `student_id`, if guardians are not enabled for the domain in question, or for other [...]",
              "id": "classroom.userProfiles.guardians.delete",
              "path": "v1/userProfiles/{studentId}/guardians/{guardianId}"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v1/userProfiles/{studentId}/guardians",
              "description": "Returns a list of guardians that the requesting user is permitted to view, restricted to those that match the request. To list guardians for any student that the requesting user may view guardians for, use the literal character `-` for the student ID. This method returns the following error codes: * `PERMISSION_DENIED` if a `student_id` is specified, and the requesting user is not permitted to view guardian information for that student, if `\"-\"` is specified as th[...]",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly",
                "https://www.googleapis.com/auth/classroom.guardianlinks.students",
                "https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly"
              ],
              "id": "classroom.userProfiles.guardians.list",
              "path": "v1/userProfiles/{studentId}/guardians"
            },
            "get": {
              "flatPath": "v1/userProfiles/{studentId}/guardians/{guardianId}",
              "httpMethod": "GET",
              "id": "classroom.userProfiles.guardians.get",
              "path": "v1/userProfiles/{studentId}/guardians/{guardianId}",
              "description": "Returns a specific guardian. This method returns the following error codes: * `PERMISSION_DENIED` if no user that matches the provided `student_id` is visible to the requesting user, if the requesting user is not permitted to view guardian information for the student identified by the `student_id`, if guardians are not enabled for the domain in question, or for other access errors. * `INVALID_ARGUMENT` if a `student_id` is specified, but its format cannot be recogni[...]",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly",
                "https://www.googleapis.com/auth/classroom.guardianlinks.students",
                "https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly"
              ]
            }
          }
        },
        "guardianInvitations": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/classroom.guardianlinks.students"
              ],
              "description": "Creates a guardian invitation, and sends an email to the guardian asking them to confirm that they are the student's guardian. Once the guardian accepts the invitation, their `state` will change to `COMPLETED` and they will start receiving guardian notifications. A `Guardian` resource will also be created to represent the active guardian. The request object must have the `student_id` and `invited_email_address` fields set. Failing to set these fields, or setting any[...]",
              "id": "classroom.userProfiles.guardianInvitations.create",
              "path": "v1/userProfiles/{studentId}/guardianInvitations",
              "httpMethod": "POST",
              "flatPath": "v1/userProfiles/{studentId}/guardianInvitations"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/classroom.guardianlinks.students",
                "https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly"
              ],
              "description": "Returns a list of guardian invitations that the requesting user is permitted to view, filtered by the parameters provided. This method returns the following error codes: * `PERMISSION_DENIED` if a `student_id` is specified, and the requesting user is not permitted to view guardian invitations for that student, if `\"-\"` is specified as the `student_id` and the user is not a domain administrator, if guardians are not enabled for the domain in question, or for other [...]",
              "id": "classroom.userProfiles.guardianInvitations.list",
              "path": "v1/userProfiles/{studentId}/guardianInvitations",
              "httpMethod": "GET",
              "flatPath": "v1/userProfiles/{studentId}/guardianInvitations"
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1/userProfiles/{studentId}/guardianInvitations/{invitationId}",
              "id": "classroom.userProfiles.guardianInvitations.get",
              "path": "v1/userProfiles/{studentId}/guardianInvitations/{invitationId}",
              "description": "Returns a specific guardian invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the requesting user is not permitted to view guardian invitations for the student identified by the `student_id`, if guardians are not enabled for the domain in question, or for other access errors. * `INVALID_ARGUMENT` if a `student_id` is specified, but its format cannot be recognized (it is not an email address, nor a `student_id` from the API, nor the [...]",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.guardianlinks.students",
                "https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly"
              ]
            },
            "patch": {
              "httpMethod": "PATCH",
              "flatPath": "v1/userProfiles/{studentId}/guardianInvitations/{invitationId}",
              "id": "classroom.userProfiles.guardianInvitations.patch",
              "path": "v1/userProfiles/{studentId}/guardianInvitations/{invitationId}",
              "description": "Modifies a guardian invitation. Currently, the only valid modification is to change the `state` from `PENDING` to `COMPLETE`. This has the effect of withdrawing the invitation. This method returns the following error codes: * `PERMISSION_DENIED` if the current user does not have permission to manage guardians, if guardians are not enabled for the domain in question or for other access errors. * `FAILED_PRECONDITION` if the guardian link is not in the `PENDING` state[...]",
              "scopes": [
                "https://www.googleapis.com/auth/classroom.guardianlinks.students"
              ]
            }
          }
        }
      }
    },
    "registrations": {
      "methods": {
        "create": {
          "id": "classroom.registrations.create",
          "path": "v1/registrations",
          "description": "Creates a `Registration`, causing Classroom to start sending notifications from the provided `feed` to the destination provided in `cloudPubSubTopic`. Returns the created `Registration`. Currently, this will be the same as the argument, but with server-assigned fields such as `expiry_time` and `id` filled in. Note that any value specified for the `expiry_time` or `id` fields will be ignored. While Classroom may validate the `cloudPubSubTopic` and return errors on a best[...]",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.push-notifications"
          ],
          "httpMethod": "POST",
          "flatPath": "v1/registrations"
        },
        "delete": {
          "description": "Deletes a `Registration`, causing Classroom to stop sending notifications for that `Registration`.",
          "scopes": [
            "https://www.googleapis.com/auth/classroom.push-notifications"
          ],
          "id": "classroom.registrations.delete",
          "path": "v1/registrations/{registrationId}",
          "httpMethod": "DELETE",
          "flatPath": "v1/registrations/{registrationId}"
        }
      }
    }
  }
}