{
  "mtlsRootUrl": "https://cloudchannel.mtls.googleapis.com/",
  "name": "cloudchannel",
  "baseUrl": "https://cloudchannel.googleapis.com/",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "kind": "discovery#restDescription",
  "servicePath": "",
  "rootUrl": "https://cloudchannel.googleapis.com/",
  "title": "Cloud Channel API",
  "ownerName": "Google",
  "documentationLink": "https://cloud.google.com/channel",
  "batchPath": "batch",
  "version": "v1",
  "id": "cloudchannel:v1",
  "description": "The Cloud Channel API enables Google Cloud partners to have a single unified resale platform and APIs across all of Google Cloud including GCP, Workspace, Maps and Chrome.",
  "discoveryVersion": "v1",
  "canonicalName": "Cloudchannel",
  "resources": {
    "integrators": {
      "methods": {
        "registerSubscriber": {
          "path": "v1/{+integrator}:registerSubscriber",
          "flatPath": "v1/integrators/{integratorsId}:registerSubscriber",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Registers a service account with subscriber privileges on the Pub/Sub topic for this Channel Services account or integrator. After you create a subscriber, you get the events through SubscriberEvent Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different, or the impersonated user is not a super admin. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * INTERNAL: Any non-user[...]",
          "httpMethod": "POST",
          "id": "cloudchannel.integrators.registerSubscriber"
        },
        "listSubscribers": {
          "httpMethod": "GET",
          "id": "cloudchannel.integrators.listSubscribers",
          "flatPath": "v1/integrators/{integratorsId}:listSubscribers",
          "path": "v1/{+integrator}:listSubscribers",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Lists service accounts with subscriber privileges on the Pub/Sub topic created for this Channel Services account or integrator. Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different, or the impersonated user is not a super admin. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The topic resource doesn't exist. * INTERNAL: Any non-user error related to a tech[...]"
        },
        "unregisterSubscriber": {
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Unregisters a service account with subscriber privileges on the Pub/Sub topic created for this Channel Services account or integrator. If there are no service accounts left with subscriber privileges, this deletes the topic. You can call ListSubscribers to check for these accounts. Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different, or the impersonated user is not a super admin. * INVALID_AR[...]",
          "path": "v1/{+integrator}:unregisterSubscriber",
          "flatPath": "v1/integrators/{integratorsId}:unregisterSubscriber",
          "httpMethod": "POST",
          "id": "cloudchannel.integrators.unregisterSubscriber"
        }
      }
    },
    "operations": {
      "methods": {
        "delete": {
          "id": "cloudchannel.operations.delete",
          "httpMethod": "DELETE",
          "flatPath": "v1/operations/{operationsId}",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`."
        },
        "get": {
          "id": "cloudchannel.operations.get",
          "httpMethod": "GET",
          "flatPath": "v1/operations/{operationsId}",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
        },
        "cancel": {
          "flatPath": "v1/operations/{operationsId}:cancel",
          "path": "v1/{+name}:cancel",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "id": "cloudchannel.operations.cancel",
          "httpMethod": "POST"
        },
        "list": {
          "path": "v1/{+name}",
          "flatPath": "v1/operations",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "httpMethod": "GET",
          "id": "cloudchannel.operations.list"
        }
      }
    },
    "accounts": {
      "methods": {
        "checkCloudIdentityAccountsExist": {
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Confirms the existence of Cloud Identity accounts based on the domain and if the Cloud Identity accounts are owned by the reseller. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * INVALID_VALUE: Invalid domain value in the request. Return value: A list of CloudIdentityCustomerAccount resources for the dom[...]",
          "path": "v1/{+parent}:checkCloudIdentityAccountsExist",
          "flatPath": "v1/accounts/{accountsId}:checkCloudIdentityAccountsExist",
          "id": "cloudchannel.accounts.checkCloudIdentityAccountsExist",
          "httpMethod": "POST"
        },
        "listTransferableOffers": {
          "httpMethod": "POST",
          "id": "cloudchannel.accounts.listTransferableOffers",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "List TransferableOffers of a customer based on Cloud Identity ID or Customer Name in the request. Use this method when a reseller gets the entitlement information of an unowned customer. The reseller should provide the customer's Cloud Identity ID or Customer Name. Possible error codes: * PERMISSION_DENIED: * The customer doesn't belong to the reseller and has no auth token. * The customer provided incorrect reseller information when generating auth token. * The reselle[...]",
          "path": "v1/{+parent}:listTransferableOffers",
          "flatPath": "v1/accounts/{accountsId}:listTransferableOffers"
        },
        "register": {
          "path": "v1/{+account}:register",
          "flatPath": "v1/accounts/{accountsId}:register",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Registers a service account with subscriber privileges on the Pub/Sub topic for this Channel Services account or integrator. After you create a subscriber, you get the events through SubscriberEvent Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different, or the impersonated user is not a super admin. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * INTERNAL: Any non-user[...]",
          "httpMethod": "POST",
          "id": "cloudchannel.accounts.register"
        },
        "unregister": {
          "id": "cloudchannel.accounts.unregister",
          "httpMethod": "POST",
          "path": "v1/{+account}:unregister",
          "flatPath": "v1/accounts/{accountsId}:unregister",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Unregisters a service account with subscriber privileges on the Pub/Sub topic created for this Channel Services account or integrator. If there are no service accounts left with subscriber privileges, this deletes the topic. You can call ListSubscribers to check for these accounts. Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different, or the impersonated user is not a super admin. * INVALID_AR[...]"
        },
        "listSubscribers": {
          "httpMethod": "GET",
          "id": "cloudchannel.accounts.listSubscribers",
          "flatPath": "v1/accounts/{accountsId}:listSubscribers",
          "path": "v1/{+account}:listSubscribers",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Lists service accounts with subscriber privileges on the Pub/Sub topic created for this Channel Services account or integrator. Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different, or the impersonated user is not a super admin. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The topic resource doesn't exist. * INTERNAL: Any non-user error related to a tech[...]"
        },
        "listTransferableSkus": {
          "flatPath": "v1/accounts/{accountsId}:listTransferableSkus",
          "path": "v1/{+parent}:listTransferableSkus",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "List TransferableSkus of a customer based on the Cloud Identity ID or Customer Name in the request. Use this method to list the entitlements information of an unowned customer. You should provide the customer's Cloud Identity ID or Customer Name. Possible error codes: * PERMISSION_DENIED: * The customer doesn't belong to the reseller and has no auth token. * The supplied auth token is invalid. * The reseller account making the request is different from the reseller acco[...]",
          "id": "cloudchannel.accounts.listTransferableSkus",
          "httpMethod": "POST"
        }
      },
      "resources": {
        "reports": {
          "methods": {
            "run": {
              "deprecated": true,
              "id": "cloudchannel.accounts.reports.run",
              "httpMethod": "POST",
              "flatPath": "v1/accounts/{accountsId}/reports/{reportsId}:run",
              "path": "v1/{+name}:run",
              "scopes": [
                "https://www.googleapis.com/auth/apps.reports.usage.readonly"
              ],
              "description": "Begins generation of data for a given report. The report identifier is a UID (for example, `613bf59q`). Possible error codes: * PERMISSION_DENIED: The user doesn't have access to this report. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The report identifier was not found. * INTERNAL: Any non-user error related to a technical issue in the backend. Contact Cloud Channel support. * UNKNOWN: Any non-user error related to a techni[...]"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/apps.reports.usage.readonly"
              ],
              "description": "Lists the reports that RunReportJob can run. These reports include an ID, a description, and the list of columns that will be in the result. Deprecated: Please use [Export Channel Services data to BigQuery](https://cloud.google.com/channel/docs/rebilling/export-data-to-bigquery) instead.",
              "flatPath": "v1/accounts/{accountsId}/reports",
              "path": "v1/{+parent}/reports",
              "deprecated": true,
              "httpMethod": "GET",
              "id": "cloudchannel.accounts.reports.list"
            }
          },
          "deprecated": true
        },
        "customers": {
          "resources": {
            "entitlements": {
              "methods": {
                "list": {
                  "id": "cloudchannel.accounts.customers.entitlements.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/entitlements",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Lists Entitlements belonging to a customer. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. Return value: A list of the customer's Entitlements."
                },
                "changeOffer": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Updates the Offer for an existing customer entitlement. An entitlement update is a long-running operation and it updates the entitlement as a result of fulfillment. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Offer or Entitlement resource not found. * INTERNAL: Any non-user error related to a technical issue in the backend. Contact Clo[...]",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:changeOffer",
                  "path": "v1/{+name}:changeOffer",
                  "httpMethod": "POST",
                  "id": "cloudchannel.accounts.customers.entitlements.changeOffer"
                },
                "get": {
                  "id": "cloudchannel.accounts.customers.entitlements.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Returns the requested Entitlement resource. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer entitlement was not found. Return value: The requested Entitlement resource.",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}",
                  "path": "v1/{+name}"
                },
                "changeParameters": {
                  "id": "cloudchannel.accounts.customers.entitlements.changeParameters",
                  "httpMethod": "POST",
                  "path": "v1/{+name}:changeParameters",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:changeParameters",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Change parameters of the entitlement. An entitlement update is a long-running operation and it updates the entitlement as a result of fulfillment. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. For example, the number of seats being changed is greater than the allowed number of max seats, or decreasing seats for a commitment based plan. * NOT_FOUND: E[...]"
                },
                "activate": {
                  "id": "cloudchannel.accounts.customers.entitlements.activate",
                  "httpMethod": "POST",
                  "path": "v1/{+name}:activate",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:activate",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Activates a previously suspended entitlement. Entitlements suspended for pending ToS acceptance can't be activated using this method. An entitlement activation is a long-running operation and it updates the state of the customer entitlement. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUN[...]"
                },
                "changeRenewalSettings": {
                  "id": "cloudchannel.accounts.customers.entitlements.changeRenewalSettings",
                  "httpMethod": "POST",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:changeRenewalSettings",
                  "path": "v1/{+name}:changeRenewalSettings",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Updates the renewal settings for an existing customer entitlement. An entitlement update is a long-running operation and it updates the entitlement as a result of fulfillment. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement resource not found. * NOT_COMMITMENT_PLAN: Renewal Settings are only applicable for a commitment plan. Ca[...]"
                },
                "suspend": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Suspends a previously fulfilled entitlement. An entitlement suspension is a long-running operation. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement resource not found. * NOT_ACTIVE: Entitlement is not active. * INTERNAL: Any non-user error related to a technical issue in the backend. Contact Cloud Channel support. * UNKNOWN: An[...]",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:suspend",
                  "path": "v1/{+name}:suspend",
                  "httpMethod": "POST",
                  "id": "cloudchannel.accounts.customers.entitlements.suspend"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Creates an entitlement for a customer. Possible error codes: * PERMISSION_DENIED: * The customer doesn't belong to the reseller. * The reseller is not authorized to transact on this Product. See https://support.google.com/channelservices/answer/9759265 * INVALID_ARGUMENT: * Required request parameters are missing or invalid. * There is already a customer entitlement for a SKU from the same product family. * INVALID_VALUE: Make sure the OfferId is valid. If it is[...]",
                  "path": "v1/{+parent}/entitlements",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements",
                  "httpMethod": "POST",
                  "id": "cloudchannel.accounts.customers.entitlements.create"
                },
                "listEntitlementChanges": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "List entitlement history. Possible error codes: * PERMISSION_DENIED: The reseller account making the request and the provided reseller account are different. * INVALID_ARGUMENT: Missing or invalid required fields in the request. * NOT_FOUND: The parent resource doesn't exist. Usually the result of an invalid name parameter. * INTERNAL: Any non-user error related to a technical issue in the backend. In this case, contact CloudChannel support. * UNKNOWN: Any non-u[...]",
                  "path": "v1/{+parent}:listEntitlementChanges",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:listEntitlementChanges",
                  "id": "cloudchannel.accounts.customers.entitlements.listEntitlementChanges",
                  "httpMethod": "GET"
                },
                "lookupOffer": {
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:lookupOffer",
                  "path": "v1/{+entitlement}:lookupOffer",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Returns the requested Offer resource. Possible error codes: * PERMISSION_DENIED: The entitlement doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement or offer was not found. Return value: The Offer resource.",
                  "httpMethod": "GET",
                  "id": "cloudchannel.accounts.customers.entitlements.lookupOffer"
                },
                "startPaidService": {
                  "httpMethod": "POST",
                  "id": "cloudchannel.accounts.customers.entitlements.startPaidService",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Starts paid service for a trial entitlement. Starts paid service for a trial entitlement immediately. This method is only applicable if a plan is set up for a trial entitlement but has some trial days remaining. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement resource not found. * FAILED_PRECONDITION/NOT_IN_TRIAL: This method o[...]",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:startPaidService",
                  "path": "v1/{+name}:startPaidService"
                },
                "cancel": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Cancels a previously fulfilled entitlement. An entitlement cancellation is a long-running operation. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * FAILED_PRECONDITION: There are Google Cloud projects linked to the Google Cloud entitlement's Cloud Billing subaccount. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: Entitlement reso[...]",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/entitlements/{entitlementsId}:cancel",
                  "path": "v1/{+name}:cancel",
                  "id": "cloudchannel.accounts.customers.entitlements.cancel",
                  "httpMethod": "POST"
                }
              }
            },
            "customerRepricingConfigs": {
              "methods": {
                "patch": {
                  "httpMethod": "PATCH",
                  "id": "cloudchannel.accounts.customers.customerRepricingConfigs.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Updates a CustomerRepricingConfig. Call this method to set modifications for a specific customer's bill. This method overwrites the existing CustomerRepricingConfig. You can only update configs if the RepricingConfig.effective_invoice_month is a future month. To make changes to configs for the current month, use CreateCustomerRepricingConfig, taking note of its restrictions. You cannot update the RepricingConfig.effective_invoice_month. When updating a config in[...]",
                  "path": "v1/{+name}",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/customerRepricingConfigs/{customerRepricingConfigsId}"
                },
                "get": {
                  "id": "cloudchannel.accounts.customers.customerRepricingConfigs.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Gets information about how a Reseller modifies their bill before sending it to a Customer. Possible Error Codes: * PERMISSION_DENIED: If the account making the request and the account being queried are different. * NOT_FOUND: The CustomerRepricingConfig was not found. * INTERNAL: Any non-user error related to technical issues in the backend. In this case, contact Cloud Channel support. Return Value: If successful, the CustomerRepricingConfig resource, otherwise [...]",
                  "path": "v1/{+name}",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/customerRepricingConfigs/{customerRepricingConfigsId}"
                },
                "create": {
                  "id": "cloudchannel.accounts.customers.customerRepricingConfigs.create",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Creates a CustomerRepricingConfig. Call this method to set modifications for a specific customer's bill. You can only create configs if the RepricingConfig.effective_invoice_month is a future month. If needed, you can create a config for the current month, with some restrictions. When creating a config for a future month, make sure there are no existing configs for that RepricingConfig.effective_invoice_month. The following restrictions are for creating configs [...]",
                  "path": "v1/{+parent}/customerRepricingConfigs",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/customerRepricingConfigs"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Deletes the given CustomerRepricingConfig permanently. You can only delete configs if their RepricingConfig.effective_invoice_month is set to a date after the current month. Possible error codes: * PERMISSION_DENIED: The account making the request does not own this customer. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * FAILED_PRECONDITION: The CustomerRepricingConfig is active or in the past. * NOT_FOUND: No CustomerRepricingConfig f[...]",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/customerRepricingConfigs/{customerRepricingConfigsId}",
                  "path": "v1/{+name}",
                  "id": "cloudchannel.accounts.customers.customerRepricingConfigs.delete",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "path": "v1/{+parent}/customerRepricingConfigs",
                  "flatPath": "v1/accounts/{accountsId}/customers/{customersId}/customerRepricingConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Lists information about how a Reseller modifies their bill before sending it to a Customer. Possible Error Codes: * PERMISSION_DENIED: If the account making the request and the account being queried are different. * NOT_FOUND: The CustomerRepricingConfig specified does not exist or is not associated with the given account. * INTERNAL: Any non-user error related to technical issues in the backend. In this case, contact Cloud Channel support. Return Value: If succ[...]",
                  "id": "cloudchannel.accounts.customers.customerRepricingConfigs.list",
                  "httpMethod": "GET"
                }
              }
            }
          },
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Creates a new Customer resource under the reseller or distributor account. Possible error codes: * PERMISSION_DENIED: * The reseller account making the request is different from the reseller account in the API request. * You are not authorized to create a customer. See https://support.google.com/channelservices/answer/9759265 * INVALID_ARGUMENT: * Required request parameters are missing or invalid. * Domain field value doesn't match the primary email domain. Return [...]",
              "flatPath": "v1/accounts/{accountsId}/customers",
              "path": "v1/{+parent}/customers",
              "httpMethod": "POST",
              "id": "cloudchannel.accounts.customers.create"
            },
            "transferEntitlementsToGoogle": {
              "httpMethod": "POST",
              "id": "cloudchannel.accounts.customers.transferEntitlementsToGoogle",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}:transferEntitlementsToGoogle",
              "path": "v1/{+parent}:transferEntitlementsToGoogle",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Transfers customer entitlements from their current reseller to Google. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer or offer resource was not found. * ALREADY_EXISTS: The SKU was already transferred for the customer. * CONDITION_NOT_MET or FAILED_PRECONDITION: * The SKU requires domain verification to transfer, but the domain i[...]"
            },
            "listPurchasableSkus": {
              "id": "cloudchannel.accounts.customers.listPurchasableSkus",
              "httpMethod": "GET",
              "path": "v1/{+customer}:listPurchasableSkus",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}:listPurchasableSkus",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Lists the following: * SKUs that you can purchase for a customer * SKUs that you can upgrade or downgrade for an entitlement. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid."
            },
            "patch": {
              "path": "v1/{+name}",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Updates an existing Customer resource for the reseller or distributor. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: No Customer resource found for the name in the request. Return value: The updated Customer resource.",
              "id": "cloudchannel.accounts.customers.patch",
              "httpMethod": "PATCH"
            },
            "get": {
              "path": "v1/{+name}",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Returns the requested Customer resource. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer resource doesn't exist. Usually the result of an invalid name parameter. Return value: The Customer resource.",
              "id": "cloudchannel.accounts.customers.get",
              "httpMethod": "GET"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "cloudchannel.accounts.customers.delete",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Deletes the given Customer permanently. Possible error codes: * PERMISSION_DENIED: The account making the request does not own this customer. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * FAILED_PRECONDITION: The customer has existing entitlements. * NOT_FOUND: No Customer resource found for the name in the request.",
              "path": "v1/{+name}",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}"
            },
            "list": {
              "path": "v1/{+parent}/customers",
              "flatPath": "v1/accounts/{accountsId}/customers",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "List Customers. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. Return value: List of Customers, or an empty list if there are no customers.",
              "httpMethod": "GET",
              "id": "cloudchannel.accounts.customers.list"
            },
            "provisionCloudIdentity": {
              "httpMethod": "POST",
              "id": "cloudchannel.accounts.customers.provisionCloudIdentity",
              "path": "v1/{+customer}:provisionCloudIdentity",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}:provisionCloudIdentity",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Creates a Cloud Identity for the given customer using the customer's information, or the information provided here. Possible error codes: * PERMISSION_DENIED: * The customer doesn't belong to the reseller. * You are not authorized to provision cloud identity id. See https://support.google.com/channelservices/answer/9759265 * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer was not found. * ALREADY_EXISTS: The customer's[...]"
            },
            "listPurchasableOffers": {
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Lists the following: * Offers that you can purchase for a customer. * Offers that you can change for an entitlement. Possible error codes: * PERMISSION_DENIED: * The customer doesn't belong to the reseller * The reseller is not authorized to transact on this Product. See https://support.google.com/channelservices/answer/9759265 * INVALID_ARGUMENT: Required request parameters are missing or invalid.",
              "path": "v1/{+customer}:listPurchasableOffers",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}:listPurchasableOffers",
              "httpMethod": "GET",
              "id": "cloudchannel.accounts.customers.listPurchasableOffers"
            },
            "import": {
              "id": "cloudchannel.accounts.customers.import",
              "httpMethod": "POST",
              "path": "v1/{+parent}/customers:import",
              "flatPath": "v1/accounts/{accountsId}/customers:import",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Imports a Customer from the Cloud Identity associated with the provided Cloud Identity ID or domain before a TransferEntitlements call. If a linked Customer already exists and overwrite_if_exists is true, it will update that Customer's data. Possible error codes: * PERMISSION_DENIED: * The reseller account making the request is different from the reseller account in the API request. * You are not authorized to import the customer. See https://support.google.com/chan[...]"
            },
            "queryEligibleBillingAccounts": {
              "id": "cloudchannel.accounts.customers.queryEligibleBillingAccounts",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Lists the billing accounts that are eligible to purchase particular SKUs for a given customer. Possible error codes: * PERMISSION_DENIED: The customer doesn't belong to the reseller. * INVALID_ARGUMENT: Required request parameters are missing or invalid. Return value: Based on the provided list of SKUs, returns a list of SKU groups that must be purchased using the same billing account and the billing accounts eligible to purchase each SKU group.",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}:queryEligibleBillingAccounts",
              "path": "v1/{+customer}:queryEligibleBillingAccounts"
            },
            "transferEntitlements": {
              "path": "v1/{+parent}:transferEntitlements",
              "flatPath": "v1/accounts/{accountsId}/customers/{customersId}:transferEntitlements",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Transfers customer entitlements to new reseller. Possible error codes: * PERMISSION_DENIED: * The customer doesn't belong to the reseller. * The reseller is not authorized to transact on this Product. See https://support.google.com/channelservices/answer/9759265 * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer or offer resource was not found. * ALREADY_EXISTS: The SKU was already transferred for the customer. * CONDIT[...]",
              "httpMethod": "POST",
              "id": "cloudchannel.accounts.customers.transferEntitlements"
            }
          }
        },
        "channelPartnerLinks": {
          "resources": {
            "customers": {
              "methods": {
                "import": {
                  "httpMethod": "POST",
                  "id": "cloudchannel.accounts.channelPartnerLinks.customers.import",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Imports a Customer from the Cloud Identity associated with the provided Cloud Identity ID or domain before a TransferEntitlements call. If a linked Customer already exists and overwrite_if_exists is true, it will update that Customer's data. Possible error codes: * PERMISSION_DENIED: * The reseller account making the request is different from the reseller account in the API request. * You are not authorized to import the customer. See https://support.google.com/[...]",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers:import",
                  "path": "v1/{+parent}/customers:import"
                },
                "patch": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers/{customersId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Updates an existing Customer resource for the reseller or distributor. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: No Customer resource found for the name in the request. Return value: The updated Customer resource.",
                  "httpMethod": "PATCH",
                  "id": "cloudchannel.accounts.channelPartnerLinks.customers.patch"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Creates a new Customer resource under the reseller or distributor account. Possible error codes: * PERMISSION_DENIED: * The reseller account making the request is different from the reseller account in the API request. * You are not authorized to create a customer. See https://support.google.com/channelservices/answer/9759265 * INVALID_ARGUMENT: * Required request parameters are missing or invalid. * Domain field value doesn't match the primary email domain. Ret[...]",
                  "path": "v1/{+parent}/customers",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers",
                  "httpMethod": "POST",
                  "id": "cloudchannel.accounts.channelPartnerLinks.customers.create"
                },
                "delete": {
                  "id": "cloudchannel.accounts.channelPartnerLinks.customers.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Deletes the given Customer permanently. Possible error codes: * PERMISSION_DENIED: The account making the request does not own this customer. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * FAILED_PRECONDITION: The customer has existing entitlements. * NOT_FOUND: No Customer resource found for the name in the request.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers/{customersId}"
                },
                "get": {
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers/{customersId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Returns the requested Customer resource. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: The customer resource doesn't exist. Usually the result of an invalid name parameter. Return value: The Customer resource.",
                  "id": "cloudchannel.accounts.channelPartnerLinks.customers.get",
                  "httpMethod": "GET"
                },
                "list": {
                  "id": "cloudchannel.accounts.channelPartnerLinks.customers.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "List Customers. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. Return value: List of Customers, or an empty list if there are no customers.",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/customers",
                  "path": "v1/{+parent}/customers"
                }
              }
            },
            "channelPartnerRepricingConfigs": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "id": "cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Lists information about how a Reseller modifies their bill before sending it to a ChannelPartner. Possible Error Codes: * PERMISSION_DENIED: If the account making the request and the account being queried are different. * NOT_FOUND: The ChannelPartnerRepricingConfig specified does not exist or is not associated with the given account. * INTERNAL: Any non-user error related to technical issues in the backend. In this case, contact Cloud Channel support. Return Va[...]",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/channelPartnerRepricingConfigs",
                  "path": "v1/{+parent}/channelPartnerRepricingConfigs"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Creates a ChannelPartnerRepricingConfig. Call this method to set modifications for a specific ChannelPartner's bill. You can only create configs if the RepricingConfig.effective_invoice_month is a future month. If needed, you can create a config for the current month, with some restrictions. When creating a config for a future month, make sure there are no existing configs for that RepricingConfig.effective_invoice_month. The following restrictions are for creat[...]",
                  "path": "v1/{+parent}/channelPartnerRepricingConfigs",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/channelPartnerRepricingConfigs",
                  "id": "cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.create",
                  "httpMethod": "POST"
                },
                "delete": {
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/channelPartnerRepricingConfigs/{channelPartnerRepricingConfigsId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Deletes the given ChannelPartnerRepricingConfig permanently. You can only delete configs if their RepricingConfig.effective_invoice_month is set to a date after the current month. Possible error codes: * PERMISSION_DENIED: The account making the request does not own this customer. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * FAILED_PRECONDITION: The ChannelPartnerRepricingConfig is active or in the past. * NOT_FOUND: No ChannelPartne[...]",
                  "id": "cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.delete",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/channelPartnerRepricingConfigs/{channelPartnerRepricingConfigsId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Gets information about how a Distributor modifies their bill before sending it to a ChannelPartner. Possible Error Codes: * PERMISSION_DENIED: If the account making the request and the account being queried are different. * NOT_FOUND: The ChannelPartnerRepricingConfig was not found. * INTERNAL: Any non-user error related to technical issues in the backend. In this case, contact Cloud Channel support. Return Value: If successful, the ChannelPartnerRepricingConfig[...]",
                  "httpMethod": "GET",
                  "id": "cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.get"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "id": "cloudchannel.accounts.channelPartnerLinks.channelPartnerRepricingConfigs.patch",
                  "path": "v1/{+name}",
                  "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}/channelPartnerRepricingConfigs/{channelPartnerRepricingConfigsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Updates a ChannelPartnerRepricingConfig. Call this method to set modifications for a specific ChannelPartner's bill. This method overwrites the existing CustomerRepricingConfig. You can only update configs if the RepricingConfig.effective_invoice_month is a future month. To make changes to configs for the current month, use CreateChannelPartnerRepricingConfig, taking note of its restrictions. You cannot update the RepricingConfig.effective_invoice_month. When up[...]"
                }
              }
            }
          },
          "methods": {
            "create": {
              "httpMethod": "POST",
              "id": "cloudchannel.accounts.channelPartnerLinks.create",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Initiates a channel partner link between a distributor and a reseller, or between resellers in an n-tier reseller channel. Invited partners need to follow the invite_link_uri provided in the response to accept. After accepting the invitation, a link is set up between the two parties. You must be a distributor to call this method. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API reque[...]",
              "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks",
              "path": "v1/{+parent}/channelPartnerLinks"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Returns the requested ChannelPartnerLink resource. You must be a distributor to call this method. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. * NOT_FOUND: ChannelPartnerLink resource not found because of an invalid channel partner link name. Return value: The ChannelPartnerLink resource.",
              "path": "v1/{+name}",
              "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}",
              "id": "cloudchannel.accounts.channelPartnerLinks.get",
              "httpMethod": "GET"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Updates a channel partner link. Distributors call this method to change a link's status. For example, to suspend a partner link. You must be a distributor to call this method. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: * Required request parameters are missing or invalid. * Link state cannot change from invited to active or suspended. * Cannot send [...]",
              "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks/{channelPartnerLinksId}",
              "path": "v1/{+name}",
              "id": "cloudchannel.accounts.channelPartnerLinks.patch",
              "httpMethod": "PATCH"
            },
            "list": {
              "id": "cloudchannel.accounts.channelPartnerLinks.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "List ChannelPartnerLinks belonging to a distributor. You must be a distributor to call this method. Possible error codes: * PERMISSION_DENIED: The reseller account making the request is different from the reseller account in the API request. * INVALID_ARGUMENT: Required request parameters are missing or invalid. Return value: The list of the distributor account's ChannelPartnerLink resources.",
              "flatPath": "v1/accounts/{accountsId}/channelPartnerLinks",
              "path": "v1/{+parent}/channelPartnerLinks"
            }
          }
        },
        "skuGroups": {
          "resources": {
            "billableSkus": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/billableSkus",
                  "flatPath": "v1/accounts/{accountsId}/skuGroups/{skuGroupsId}/billableSkus",
                  "scopes": [
                    "https://www.googleapis.com/auth/apps.order"
                  ],
                  "description": "Lists the Billable SKUs in a given SKU group. Possible error codes: PERMISSION_DENIED: If the account making the request and the account being queried for are different, or the account doesn't exist. INVALID_ARGUMENT: Missing or invalid required parameters in the request. INTERNAL: Any non-user error related to technical issue in the backend. In this case, contact cloud channel support. Return Value: If successful, the BillableSku resources. The data for each re[...]",
                  "id": "cloudchannel.accounts.skuGroups.billableSkus.list",
                  "httpMethod": "GET"
                }
              }
            }
          },
          "methods": {
            "list": {
              "httpMethod": "GET",
              "id": "cloudchannel.accounts.skuGroups.list",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Lists the Rebilling supported SKU groups the account is authorized to sell. Reference: https://cloud.google.com/skus/sku-groups Possible Error Codes: * PERMISSION_DENIED: If the account making the request and the account being queried are different, or the account doesn't exist. * INTERNAL: Any non-user error related to technical issues in the backend. In this case, contact Cloud Channel support. Return Value: If successful, the SkuGroup resources. The data for each[...]",
              "path": "v1/{+parent}/skuGroups",
              "flatPath": "v1/accounts/{accountsId}/skuGroups"
            }
          }
        },
        "reportJobs": {
          "methods": {
            "fetchReportResults": {
              "deprecated": true,
              "httpMethod": "POST",
              "id": "cloudchannel.accounts.reportJobs.fetchReportResults",
              "flatPath": "v1/accounts/{accountsId}/reportJobs/{reportJobsId}:fetchReportResults",
              "path": "v1/{+reportJob}:fetchReportResults",
              "scopes": [
                "https://www.googleapis.com/auth/apps.reports.usage.readonly"
              ],
              "description": "Retrieves data generated by CloudChannelReportsService.RunReportJob. Deprecated: Please use [Export Channel Services data to BigQuery](https://cloud.google.com/channel/docs/rebilling/export-data-to-bigquery) instead."
            }
          },
          "deprecated": true
        },
        "offers": {
          "methods": {
            "list": {
              "flatPath": "v1/accounts/{accountsId}/offers",
              "path": "v1/{+parent}/offers",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Lists the Offers the reseller can sell. Possible error codes: * INVALID_ARGUMENT: Required request parameters are missing or invalid.",
              "httpMethod": "GET",
              "id": "cloudchannel.accounts.offers.list"
            }
          }
        }
      }
    },
    "products": {
      "resources": {
        "skus": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "id": "cloudchannel.products.skus.list",
              "path": "v1/{+parent}/skus",
              "flatPath": "v1/products/{productsId}/skus",
              "scopes": [
                "https://www.googleapis.com/auth/apps.order"
              ],
              "description": "Lists the SKUs for a product the reseller is authorized to sell. Possible error codes: * INVALID_ARGUMENT: Required request parameters are missing or invalid."
            }
          }
        }
      },
      "methods": {
        "list": {
          "path": "v1/products",
          "flatPath": "v1/products",
          "scopes": [
            "https://www.googleapis.com/auth/apps.order"
          ],
          "description": "Lists the Products the reseller is authorized to sell. Possible error codes: * INVALID_ARGUMENT: Required request parameters are missing or invalid.",
          "id": "cloudchannel.products.list",
          "httpMethod": "GET"
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/apps.reports.usage.readonly": {
          "description": "View usage reports for your Google Workspace domain"
        },
        "https://www.googleapis.com/auth/apps.order": {
          "description": "Manage users on your domain"
        }
      }
    }
  },
  "protocol": "rest",
  "basePath": "",
  "ownerDomain": "google.com",
  "revision": "20260412"
}