{
  "version_module": true,
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "id": "cloudidentity:v1",
  "protocol": "rest",
  "resources": {
    "inboundSamlSsoProfiles": {
      "methods": {
        "delete": {
          "id": "cloudidentity.inboundSamlSsoProfiles.delete",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "path": "v1/{+name}",
          "description": "Deletes an InboundSamlSsoProfile.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "get": {
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSamlSsoProfiles.get",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Gets an InboundSamlSsoProfile."
        },
        "patch": {
          "description": "Updates an InboundSamlSsoProfile. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSamlSsoProfiles.patch",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "path": "v1/{+name}"
        },
        "create": {
          "description": "Creates an InboundSamlSsoProfile for a customer. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "POST",
          "flatPath": "v1/inboundSamlSsoProfiles",
          "id": "cloudidentity.inboundSamlSsoProfiles.create",
          "path": "v1/inboundSamlSsoProfiles"
        },
        "list": {
          "path": "v1/inboundSamlSsoProfiles",
          "id": "cloudidentity.inboundSamlSsoProfiles.list",
          "flatPath": "v1/inboundSamlSsoProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists InboundSamlSsoProfiles for a customer."
        }
      },
      "resources": {
        "idpCredentials": {
          "methods": {
            "delete": {
              "description": "Deletes an IdpCredential.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.delete",
              "path": "v1/{+name}"
            },
            "add": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Adds an IdpCredential. Up to 2 credentials are allowed. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
              "path": "v1/{+parent}/idpCredentials:add",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.add",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials:add"
            },
            "list": {
              "path": "v1/{+parent}/idpCredentials",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.list",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "description": "Returns a list of IdpCredentials in an InboundSamlSsoProfile."
            },
            "get": {
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.get",
              "path": "v1/{+name}",
              "description": "Gets an IdpCredential.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "devices": {
      "methods": {
        "create": {
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "httpMethod": "POST",
          "flatPath": "v1/devices",
          "id": "cloudidentity.devices.create",
          "path": "v1/devices"
        },
        "list": {
          "flatPath": "v1/devices",
          "id": "cloudidentity.devices.list",
          "path": "v1/devices",
          "description": "Lists/Searches devices.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "httpMethod": "GET"
        },
        "wipe": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "httpMethod": "POST",
          "description": "Wipes all data on the specified device.",
          "path": "v1/{+name}:wipe",
          "flatPath": "v1/devices/{devicesId}:wipe",
          "id": "cloudidentity.devices.wipe"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "httpMethod": "GET",
          "description": "Retrieves the specified device.",
          "path": "v1/{+name}",
          "flatPath": "v1/devices/{devicesId}",
          "id": "cloudidentity.devices.get"
        },
        "cancelWipe": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device.",
          "path": "v1/{+name}:cancelWipe",
          "id": "cloudidentity.devices.cancelWipe",
          "flatPath": "v1/devices/{devicesId}:cancelWipe"
        },
        "delete": {
          "description": "Deletes the specified device.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "httpMethod": "DELETE",
          "flatPath": "v1/devices/{devicesId}",
          "id": "cloudidentity.devices.delete",
          "path": "v1/{+name}"
        }
      },
      "resources": {
        "deviceUsers": {
          "methods": {
            "list": {
              "description": "Lists/Searches DeviceUsers.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "id": "cloudidentity.devices.deviceUsers.list",
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "path": "v1/{+parent}/deviceUsers"
            },
            "wipe": {
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "path": "v1/{+name}:wipe"
            },
            "approve": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Approves device to access user data.",
              "path": "v1/{+name}:approve",
              "id": "cloudidentity.devices.deviceUsers.approve",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve"
            },
            "block": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Blocks device from accessing user data",
              "path": "v1/{+name}:block",
              "id": "cloudidentity.devices.deviceUsers.block",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block"
            },
            "delete": {
              "id": "cloudidentity.devices.deviceUsers.delete",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "path": "v1/{+name}",
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "httpMethod": "GET",
              "description": "Retrieves the specified DeviceUser",
              "path": "v1/{+name}",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "id": "cloudidentity.devices.deviceUsers.get"
            },
            "lookup": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "path": "v1/{+parent}:lookup",
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup"
            },
            "cancelWipe": {
              "path": "v1/{+name}:cancelWipe",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped."
            }
          },
          "resources": {
            "clientStates": {
              "methods": {
                "patch": {
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices"
                  ],
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "path": "v1/{+name}",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}"
                },
                "get": {
                  "description": "Gets the client state for the device user",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "path": "v1/{+name}"
                },
                "list": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "path": "v1/{+parent}/clientStates",
                  "description": "Lists the client states for the given search query.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "inboundOidcSsoProfiles": {
      "methods": {
        "create": {
          "description": "Creates an InboundOidcSsoProfile for a customer. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundOidcSsoProfiles.create",
          "flatPath": "v1/inboundOidcSsoProfiles",
          "path": "v1/inboundOidcSsoProfiles"
        },
        "list": {
          "description": "Lists InboundOidcSsoProfile objects for a Google enterprise customer.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundOidcSsoProfiles.list",
          "flatPath": "v1/inboundOidcSsoProfiles",
          "path": "v1/inboundOidcSsoProfiles"
        },
        "patch": {
          "description": "Updates an InboundOidcSsoProfile. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "id": "cloudidentity.inboundOidcSsoProfiles.patch",
          "path": "v1/{+name}"
        },
        "get": {
          "description": "Gets an InboundOidcSsoProfile.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "id": "cloudidentity.inboundOidcSsoProfiles.get",
          "path": "v1/{+name}"
        },
        "delete": {
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "id": "cloudidentity.inboundOidcSsoProfiles.delete",
          "path": "v1/{+name}",
          "description": "Deletes an InboundOidcSsoProfile.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "DELETE"
        }
      }
    },
    "policies": {
      "methods": {
        "list": {
          "id": "cloudidentity.policies.list",
          "flatPath": "v1/policies",
          "path": "v1/policies",
          "description": "List policies.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies",
            "https://www.googleapis.com/auth/cloud-identity.policies.readonly"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies",
            "https://www.googleapis.com/auth/cloud-identity.policies.readonly"
          ],
          "httpMethod": "GET",
          "description": "Get a policy.",
          "path": "v1/{+name}",
          "flatPath": "v1/policies/{policiesId}",
          "id": "cloudidentity.policies.get"
        }
      }
    },
    "inboundSsoAssignments": {
      "methods": {
        "get": {
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSsoAssignments.get",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Gets an InboundSsoAssignment."
        },
        "delete": {
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "id": "cloudidentity.inboundSsoAssignments.delete",
          "path": "v1/{+name}",
          "description": "Deletes an InboundSsoAssignment. To disable SSO, Create (or Update) an assignment that has `sso_mode` == `SSO_OFF`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "DELETE"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "POST",
          "description": "Creates an InboundSsoAssignment for users and devices in a `Customer` under a given `Group` or `OrgUnit`.",
          "path": "v1/inboundSsoAssignments",
          "flatPath": "v1/inboundSsoAssignments",
          "id": "cloudidentity.inboundSsoAssignments.create"
        },
        "list": {
          "id": "cloudidentity.inboundSsoAssignments.list",
          "flatPath": "v1/inboundSsoAssignments",
          "path": "v1/inboundSsoAssignments",
          "description": "Lists the InboundSsoAssignments for a `Customer`.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "patch": {
          "path": "v1/{+name}",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "id": "cloudidentity.inboundSsoAssignments.patch",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an InboundSsoAssignment. The body of this request is the `inbound_sso_assignment` field and the `update_mask` is relative to that. For example: a PATCH to `/v1/inboundSsoAssignments/0abcdefg1234567&update_mask=rank` with a body of `{ \"rank\": 1 }` moves that (presumably group-targeted) SSO assignment to the highest priority and shifts any other group-targeted assignments down in priority."
        }
      }
    },
    "customers": {
      "resources": {
        "userinvitations": {
          "methods": {
            "send": {
              "id": "cloudidentity.customers.userinvitations.send",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:send",
              "path": "v1/{+name}:send",
              "description": "Sends a UserInvitation to email. If the `UserInvitation` does not exist for this request and it is a valid request, the request creates a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour delay where newly-created consumer accounts will not appear in the results. You can still send a `UserInvitation` to those accounts if you know the unmanaged email address and IsInvitableUser==True.",
              "httpMethod": "POST"
            },
            "cancel": {
              "description": "Cancels a UserInvitation that was already sent.",
              "httpMethod": "POST",
              "id": "cloudidentity.customers.userinvitations.cancel",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel",
              "path": "v1/{+name}:cancel"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1/{+parent}/userinvitations",
              "description": "Retrieves a list of UserInvitation resources. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "flatPath": "v1/customers/{customersId}/userinvitations",
              "id": "cloudidentity.customers.userinvitations.list"
            },
            "isInvitableUser": {
              "path": "v1/{+name}:isInvitableUser",
              "httpMethod": "GET",
              "id": "cloudidentity.customers.userinvitations.isInvitableUser",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser",
              "description": "Verifies whether a user account is eligible to receive a UserInvitation (is an unmanaged account). Eligibility is based on the following criteria: * the email address is a consumer account and it's the primary email address of the account, and * the domain of the email address matches an existing verified Google Workspace or Cloud Identity domain If both conditions are met, the user is eligible. **Note:** This method is not supported for Workspace Essentials custome[...]"
            },
            "get": {
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}",
              "description": "Retrieves a UserInvitation resource. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "id": "cloudidentity.customers.userinvitations.get",
              "path": "v1/{+name}",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "groups": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists the `Group` resources under a customer or namespace.",
          "path": "v1/groups",
          "id": "cloudidentity.groups.list",
          "flatPath": "v1/groups"
        },
        "create": {
          "flatPath": "v1/groups",
          "id": "cloudidentity.groups.create",
          "path": "v1/groups",
          "description": "Creates a Group.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "POST"
        },
        "delete": {
          "description": "Deletes a `Group`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "DELETE",
          "flatPath": "v1/groups/{groupsId}",
          "id": "cloudidentity.groups.delete",
          "path": "v1/{+name}"
        },
        "getSecuritySettings": {
          "description": "Get Security Settings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.getSecuritySettings",
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "path": "v1/{+name}"
        },
        "get": {
          "description": "Retrieves a `Group`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "flatPath": "v1/groups/{groupsId}",
          "id": "cloudidentity.groups.get",
          "path": "v1/{+name}"
        },
        "updateSecuritySettings": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "PATCH",
          "description": "Update Security Settings",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "id": "cloudidentity.groups.updateSecuritySettings"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "PATCH",
          "description": "Updates a `Group`.",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}",
          "id": "cloudidentity.groups.patch"
        },
        "search": {
          "flatPath": "v1/groups:search",
          "id": "cloudidentity.groups.search",
          "path": "v1/groups:search",
          "description": "Searches for `Group` resources matching a specified query.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET"
        },
        "lookup": {
          "path": "v1/groups:lookup",
          "id": "cloudidentity.groups.lookup",
          "flatPath": "v1/groups:lookup",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`."
        }
      },
      "resources": {
        "memberships": {
          "methods": {
            "lookup": {
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "id": "cloudidentity.groups.memberships.lookup",
              "path": "v1/{+parent}/memberships:lookup"
            },
            "searchDirectGroups": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "description": "Searches direct groups of a member.",
              "path": "v1/{+parent}/memberships:searchDirectGroups",
              "flatPath": "v1/groups/{groupsId}/memberships:searchDirectGroups",
              "id": "cloudidentity.groups.memberships.searchDirectGroups"
            },
            "checkTransitiveMembership": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor mu[...]",
              "path": "v1/{+parent}/memberships:checkTransitiveMembership",
              "flatPath": "v1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership"
            },
            "getMembershipGraph": {
              "path": "v1/{+parent}/memberships:getMembershipGraph",
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "flatPath": "v1/groups/{groupsId}/memberships:getMembershipGraph",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the respon[...]"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Retrieves a `Membership`.",
              "path": "v1/{+name}",
              "id": "cloudidentity.groups.memberships.get",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes a `Membership`.",
              "path": "v1/{+name}",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "id": "cloudidentity.groups.memberships.delete"
            },
            "searchTransitiveGroups": {
              "path": "v1/{+parent}/memberships:searchTransitiveGroups",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups."
            },
            "create": {
              "description": "Creates a `Membership`.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.create",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "path": "v1/{+parent}/memberships"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "description": "Lists the `Membership`s within a `Group`.",
              "path": "v1/{+parent}/memberships",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "id": "cloudidentity.groups.memberships.list"
            },
            "searchTransitiveMemberships": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "path": "v1/{+parent}/memberships:searchTransitiveMemberships",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships"
            },
            "modifyMembershipRoles": {
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "path": "v1/{+name}:modifyMembershipRoles"
            }
          }
        }
      }
    }
  },
  "title": "Cloud Identity API",
  "revision": "20260429",
  "kind": "discovery#restDescription",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "canonicalName": "Cloud Identity",
  "description": "API for provisioning and managing identity resources.",
  "batchPath": "batch",
  "basePath": "",
  "servicePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.inboundsso": {
          "description": "See and edit all of the Inbound SSO profiles and their assignments to any Org Units or Google Groups in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.policies.readonly": {
          "description": "See policies in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.devices": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices"
        },
        "https://www.googleapis.com/auth/cloud-identity.policies": {
          "description": "See and edit policies in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.readonly": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly": {
          "description": "See all of the Inbound SSO profiles and their assignments to any Org Units or Google Groups in your Cloud Identity Organization."
        }
      }
    }
  },
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "name": "cloudidentity",
  "documentationLink": "https://cloud.google.com/identity/",
  "fullyEncodeReservedExpansion": true,
  "ownerName": "Google",
  "ownerDomain": "google.com",
  "version": "v1"
}