{
  "protocol": "rest",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "servicePath": "",
  "description": "API for provisioning and managing identity resources.",
  "basePath": "",
  "revision": "20260414",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "kind": "discovery#restDescription",
  "version": "v1",
  "ownerName": "Google",
  "title": "Cloud Identity API",
  "version_module": true,
  "documentationLink": "https://cloud.google.com/identity/",
  "batchPath": "batch",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "name": "cloudidentity",
  "ownerDomain": "google.com",
  "resources": {
    "inboundSamlSsoProfiles": {
      "resources": {
        "idpCredentials": {
          "methods": {
            "list": {
              "path": "v1/{+parent}/idpCredentials",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.list",
              "description": "Returns a list of IdpCredentials in an InboundSamlSsoProfile."
            },
            "add": {
              "httpMethod": "POST",
              "path": "v1/{+parent}/idpCredentials:add",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials:add",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.add",
              "description": "Adds an IdpCredential. Up to 2 credentials are allowed. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`."
            },
            "delete": {
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.delete",
              "description": "Deletes an IdpCredential.",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "DELETE",
              "path": "v1/{+name}"
            },
            "get": {
              "description": "Gets an IdpCredential.",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.get",
              "httpMethod": "GET",
              "path": "v1/{+name}",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            }
          }
        }
      },
      "methods": {
        "patch": {
          "path": "v1/{+name}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "id": "cloudidentity.inboundSamlSsoProfiles.patch",
          "description": "Updates an InboundSamlSsoProfile. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`."
        },
        "list": {
          "id": "cloudidentity.inboundSamlSsoProfiles.list",
          "description": "Lists InboundSamlSsoProfiles for a customer.",
          "flatPath": "v1/inboundSamlSsoProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "path": "v1/inboundSamlSsoProfiles"
        },
        "delete": {
          "description": "Deletes an InboundSamlSsoProfile.",
          "id": "cloudidentity.inboundSamlSsoProfiles.delete",
          "httpMethod": "DELETE",
          "path": "v1/{+name}",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "create": {
          "description": "Creates an InboundSamlSsoProfile for a customer. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "id": "cloudidentity.inboundSamlSsoProfiles.create",
          "path": "v1/inboundSamlSsoProfiles",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundSamlSsoProfiles"
        },
        "get": {
          "id": "cloudidentity.inboundSamlSsoProfiles.get",
          "description": "Gets an InboundSamlSsoProfile.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "path": "v1/{+name}",
          "httpMethod": "GET"
        }
      }
    },
    "inboundSsoAssignments": {
      "methods": {
        "patch": {
          "path": "v1/{+name}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "id": "cloudidentity.inboundSsoAssignments.patch",
          "description": "Updates an InboundSsoAssignment. The body of this request is the `inbound_sso_assignment` field and the `update_mask` is relative to that. For example: a PATCH to `/v1/inboundSsoAssignments/0abcdefg1234567&update_mask=rank` with a body of `{ \"rank\": 1 }` moves that (presumably group-targeted) SSO assignment to the highest priority and shifts any other group-targeted assignments down in priority."
        },
        "list": {
          "httpMethod": "GET",
          "path": "v1/inboundSsoAssignments",
          "flatPath": "v1/inboundSsoAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSsoAssignments.list",
          "description": "Lists the InboundSsoAssignments for a `Customer`."
        },
        "delete": {
          "id": "cloudidentity.inboundSsoAssignments.delete",
          "description": "Deletes an InboundSsoAssignment. To disable SSO, Create (or Update) an assignment that has `sso_mode` == `SSO_OFF`.",
          "path": "v1/{+name}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}"
        },
        "get": {
          "id": "cloudidentity.inboundSsoAssignments.get",
          "description": "Gets an InboundSsoAssignment.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "path": "v1/{+name}",
          "httpMethod": "GET"
        },
        "create": {
          "path": "v1/inboundSsoAssignments",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundSsoAssignments",
          "description": "Creates an InboundSsoAssignment for users and devices in a `Customer` under a given `Group` or `OrgUnit`.",
          "id": "cloudidentity.inboundSsoAssignments.create"
        }
      }
    },
    "groups": {
      "resources": {
        "memberships": {
          "methods": {
            "searchDirectGroups": {
              "flatPath": "v1/groups/{groupsId}/memberships:searchDirectGroups",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:searchDirectGroups",
              "description": "Searches direct groups of a member.",
              "id": "cloudidentity.groups.memberships.searchDirectGroups"
            },
            "searchTransitiveMemberships": {
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships",
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:searchTransitiveMemberships",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "searchTransitiveGroups": {
              "path": "v1/{+parent}/memberships:searchTransitiveGroups",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups."
            },
            "getMembershipGraph": {
              "path": "v1/{+parent}/memberships:getMembershipGraph",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships:getMembershipGraph",
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the respon[...]",
              "id": "cloudidentity.groups.memberships.getMembershipGraph"
            },
            "modifyMembershipRoles": {
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "httpMethod": "POST",
              "path": "v1/{+name}:modifyMembershipRoles",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "list": {
              "id": "cloudidentity.groups.memberships.list",
              "description": "Lists the `Membership`s within a `Group`.",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships"
            },
            "delete": {
              "path": "v1/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "id": "cloudidentity.groups.memberships.delete",
              "description": "Deletes a `Membership`."
            },
            "lookup": {
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:lookup",
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "id": "cloudidentity.groups.memberships.lookup"
            },
            "checkTransitiveMembership": {
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:checkTransitiveMembership",
              "flatPath": "v1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor mu[...]"
            },
            "create": {
              "description": "Creates a `Membership`.",
              "id": "cloudidentity.groups.memberships.create",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "POST",
              "path": "v1/{+parent}/memberships"
            },
            "get": {
              "description": "Retrieves a `Membership`.",
              "id": "cloudidentity.groups.memberships.get",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "path": "v1/{+name}"
            }
          }
        }
      },
      "methods": {
        "patch": {
          "flatPath": "v1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "PATCH",
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.patch",
          "description": "Updates a `Group`."
        },
        "updateSecuritySettings": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "path": "v1/{+name}",
          "httpMethod": "PATCH",
          "id": "cloudidentity.groups.updateSecuritySettings",
          "description": "Update Security Settings"
        },
        "getSecuritySettings": {
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "description": "Get Security Settings",
          "id": "cloudidentity.groups.getSecuritySettings"
        },
        "list": {
          "httpMethod": "GET",
          "path": "v1/groups",
          "flatPath": "v1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists the `Group` resources under a customer or namespace.",
          "id": "cloudidentity.groups.list"
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes a `Group`.",
          "id": "cloudidentity.groups.delete"
        },
        "lookup": {
          "id": "cloudidentity.groups.lookup",
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "flatPath": "v1/groups:lookup",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "path": "v1/groups:lookup"
        },
        "search": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups:search",
          "path": "v1/groups:search",
          "httpMethod": "GET",
          "description": "Searches for `Group` resources matching a specified query.",
          "id": "cloudidentity.groups.search"
        },
        "create": {
          "httpMethod": "POST",
          "path": "v1/groups",
          "flatPath": "v1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates a Group.",
          "id": "cloudidentity.groups.create"
        },
        "get": {
          "description": "Retrieves a `Group`.",
          "id": "cloudidentity.groups.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/groups/{groupsId}",
          "path": "v1/{+name}",
          "httpMethod": "GET"
        }
      }
    },
    "inboundOidcSsoProfiles": {
      "methods": {
        "patch": {
          "id": "cloudidentity.inboundOidcSsoProfiles.patch",
          "description": "Updates an InboundOidcSsoProfile. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "path": "v1/{+name}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}"
        },
        "list": {
          "id": "cloudidentity.inboundOidcSsoProfiles.list",
          "description": "Lists InboundOidcSsoProfile objects for a Google enterprise customer.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundOidcSsoProfiles",
          "path": "v1/inboundOidcSsoProfiles",
          "httpMethod": "GET"
        },
        "delete": {
          "description": "Deletes an InboundOidcSsoProfile.",
          "id": "cloudidentity.inboundOidcSsoProfiles.delete",
          "httpMethod": "DELETE",
          "path": "v1/{+name}",
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "get": {
          "path": "v1/{+name}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "description": "Gets an InboundOidcSsoProfile.",
          "id": "cloudidentity.inboundOidcSsoProfiles.get"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundOidcSsoProfiles",
          "path": "v1/inboundOidcSsoProfiles",
          "httpMethod": "POST",
          "id": "cloudidentity.inboundOidcSsoProfiles.create",
          "description": "Creates an InboundOidcSsoProfile for a customer. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`."
        }
      }
    },
    "devices": {
      "resources": {
        "deviceUsers": {
          "methods": {
            "get": {
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "description": "Retrieves the specified DeviceUser",
              "id": "cloudidentity.devices.deviceUsers.get"
            },
            "block": {
              "description": "Blocks device from accessing user data",
              "id": "cloudidentity.devices.deviceUsers.block",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "path": "v1/{+name}:block",
              "httpMethod": "POST"
            },
            "delete": {
              "id": "cloudidentity.devices.deviceUsers.delete",
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "path": "v1/{+name}",
              "httpMethod": "DELETE"
            },
            "lookup": {
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "httpMethod": "GET",
              "path": "v1/{+parent}:lookup"
            },
            "cancelWipe": {
              "path": "v1/{+name}:cancelWipe",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe"
            },
            "list": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "httpMethod": "GET",
              "path": "v1/{+parent}/deviceUsers",
              "description": "Lists/Searches DeviceUsers.",
              "id": "cloudidentity.devices.deviceUsers.list"
            },
            "approve": {
              "id": "cloudidentity.devices.deviceUsers.approve",
              "description": "Approves device to access user data.",
              "httpMethod": "POST",
              "path": "v1/{+name}:approve",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ]
            },
            "wipe": {
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "httpMethod": "POST",
              "path": "v1/{+name}:wipe"
            }
          },
          "resources": {
            "clientStates": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "description": "Gets the client state for the device user"
                },
                "list": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "description": "Lists the client states for the given search query.",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/clientStates",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ]
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "path": "v1/{+name}",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices"
                  ],
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium"
                }
              }
            }
          }
        }
      },
      "methods": {
        "delete": {
          "id": "cloudidentity.devices.delete",
          "description": "Deletes the specified device.",
          "httpMethod": "DELETE",
          "path": "v1/{+name}",
          "flatPath": "v1/devices/{devicesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ]
        },
        "cancelWipe": {
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device.",
          "id": "cloudidentity.devices.cancelWipe",
          "httpMethod": "POST",
          "path": "v1/{+name}:cancelWipe",
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "path": "v1/devices",
          "flatPath": "v1/devices",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "description": "Lists/Searches devices.",
          "id": "cloudidentity.devices.list"
        },
        "wipe": {
          "description": "Wipes all data on the specified device.",
          "id": "cloudidentity.devices.wipe",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "flatPath": "v1/devices/{devicesId}:wipe",
          "path": "v1/{+name}:wipe",
          "httpMethod": "POST"
        },
        "get": {
          "description": "Retrieves the specified device.",
          "id": "cloudidentity.devices.get",
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "flatPath": "v1/devices/{devicesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ]
        },
        "create": {
          "id": "cloudidentity.devices.create",
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
          "flatPath": "v1/devices",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "httpMethod": "POST",
          "path": "v1/devices"
        }
      }
    },
    "customers": {
      "resources": {
        "userinvitations": {
          "methods": {
            "send": {
              "path": "v1/{+name}:send",
              "httpMethod": "POST",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:send",
              "description": "Sends a UserInvitation to email. If the `UserInvitation` does not exist for this request and it is a valid request, the request creates a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour delay where newly-created consumer accounts will not appear in the results. You can still send a `UserInvitation` to those accounts if you know the unmanaged email address and IsInvitableUser==True.",
              "id": "cloudidentity.customers.userinvitations.send"
            },
            "get": {
              "id": "cloudidentity.customers.userinvitations.get",
              "path": "v1/{+name}",
              "description": "Retrieves a UserInvitation resource. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}"
            },
            "cancel": {
              "description": "Cancels a UserInvitation that was already sent.",
              "id": "cloudidentity.customers.userinvitations.cancel",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel",
              "httpMethod": "POST",
              "path": "v1/{+name}:cancel"
            },
            "isInvitableUser": {
              "path": "v1/{+name}:isInvitableUser",
              "description": "Verifies whether a user account is eligible to receive a UserInvitation (is an unmanaged account). Eligibility is based on the following criteria: * the email address is a consumer account and it's the primary email address of the account, and * the domain of the email address matches an existing verified Google Workspace or Cloud Identity domain If both conditions are met, the user is eligible. **Note:** This method is not supported for Workspace Essentials custome[...]",
              "id": "cloudidentity.customers.userinvitations.isInvitableUser",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser"
            },
            "list": {
              "path": "v1/{+parent}/userinvitations",
              "description": "Retrieves a list of UserInvitation resources. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "id": "cloudidentity.customers.userinvitations.list",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/userinvitations"
            }
          }
        }
      }
    },
    "policies": {
      "methods": {
        "get": {
          "flatPath": "v1/policies/{policiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies",
            "https://www.googleapis.com/auth/cloud-identity.policies.readonly"
          ],
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "description": "Get a policy.",
          "id": "cloudidentity.policies.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies",
            "https://www.googleapis.com/auth/cloud-identity.policies.readonly"
          ],
          "flatPath": "v1/policies",
          "path": "v1/policies",
          "httpMethod": "GET",
          "description": "List policies.",
          "id": "cloudidentity.policies.list"
        }
      }
    }
  },
  "id": "cloudidentity:v1",
  "canonicalName": "Cloud Identity",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.devices": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices"
        },
        "https://www.googleapis.com/auth/cloud-identity.policies.readonly": {
          "description": "See policies in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity.inboundsso": {
          "description": "See and edit all of the Inbound SSO profiles and their assignments to any Org Units or Google Groups in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.readonly": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
        },
        "https://www.googleapis.com/auth/cloud-identity.policies": {
          "description": "See and edit policies in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly": {
          "description": "See all of the Inbound SSO profiles and their assignments to any Org Units or Google Groups in your Cloud Identity Organization."
        }
      }
    }
  }
}