{
  "id": "cloudidentity:v1",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "batchPath": "batch",
  "canonicalName": "Cloud Identity",
  "description": "API for provisioning and managing identity resources.",
  "protocol": "rest",
  "version": "v1",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "name": "cloudidentity",
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "revision": "20260506",
  "fullyEncodeReservedExpansion": true,
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "version_module": true,
  "basePath": "",
  "resources": {
    "inboundSamlSsoProfiles": {
      "resources": {
        "idpCredentials": {
          "methods": {
            "add": {
              "description": "Adds an IdpCredential. Up to 2 credentials are allowed. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials:add",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.add",
              "httpMethod": "POST",
              "path": "v1/{+parent}/idpCredentials:add"
            },
            "list": {
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.list",
              "httpMethod": "GET",
              "path": "v1/{+parent}/idpCredentials",
              "description": "Returns a list of IdpCredentials in an InboundSamlSsoProfile.",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "delete": {
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Deletes an IdpCredential.",
              "path": "v1/{+name}",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.delete",
              "httpMethod": "DELETE"
            },
            "get": {
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Gets an IdpCredential.",
              "path": "v1/{+name}",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.get",
              "httpMethod": "GET"
            }
          }
        }
      },
      "methods": {
        "delete": {
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSamlSsoProfiles.delete",
          "httpMethod": "DELETE",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes an InboundSamlSsoProfile."
        },
        "get": {
          "description": "Gets an InboundSamlSsoProfile.",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSamlSsoProfiles.get",
          "httpMethod": "GET"
        },
        "patch": {
          "id": "cloudidentity.inboundSamlSsoProfiles.patch",
          "httpMethod": "PATCH",
          "path": "v1/{+name}",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates an InboundSamlSsoProfile. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`."
        },
        "create": {
          "id": "cloudidentity.inboundSamlSsoProfiles.create",
          "httpMethod": "POST",
          "path": "v1/inboundSamlSsoProfiles",
          "flatPath": "v1/inboundSamlSsoProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates an InboundSamlSsoProfile for a customer. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`."
        },
        "list": {
          "id": "cloudidentity.inboundSamlSsoProfiles.list",
          "httpMethod": "GET",
          "path": "v1/inboundSamlSsoProfiles",
          "flatPath": "v1/inboundSamlSsoProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists InboundSamlSsoProfiles for a customer."
        }
      }
    },
    "devices": {
      "methods": {
        "cancelWipe": {
          "path": "v1/{+name}:cancelWipe",
          "id": "cloudidentity.devices.cancelWipe",
          "httpMethod": "POST",
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device."
        },
        "get": {
          "description": "Retrieves the specified device.",
          "flatPath": "v1/devices/{devicesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "id": "cloudidentity.devices.get",
          "httpMethod": "GET",
          "path": "v1/{+name}"
        },
        "delete": {
          "description": "Deletes the specified device.",
          "flatPath": "v1/devices/{devicesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "path": "v1/{+name}",
          "id": "cloudidentity.devices.delete",
          "httpMethod": "DELETE"
        },
        "create": {
          "id": "cloudidentity.devices.create",
          "httpMethod": "POST",
          "path": "v1/devices",
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
          "flatPath": "v1/devices",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ]
        },
        "wipe": {
          "flatPath": "v1/devices/{devicesId}:wipe",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Wipes all data on the specified device.",
          "id": "cloudidentity.devices.wipe",
          "httpMethod": "POST",
          "path": "v1/{+name}:wipe"
        },
        "list": {
          "path": "v1/devices",
          "id": "cloudidentity.devices.list",
          "httpMethod": "GET",
          "flatPath": "v1/devices",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "description": "Lists/Searches devices."
        }
      },
      "resources": {
        "deviceUsers": {
          "methods": {
            "approve": {
              "id": "cloudidentity.devices.deviceUsers.approve",
              "httpMethod": "POST",
              "path": "v1/{+name}:approve",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Approves device to access user data."
            },
            "cancelWipe": {
              "path": "v1/{+name}:cancelWipe",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "httpMethod": "POST",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped."
            },
            "get": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "description": "Retrieves the specified DeviceUser",
              "path": "v1/{+name}",
              "id": "cloudidentity.devices.deviceUsers.get",
              "httpMethod": "GET"
            },
            "delete": {
              "id": "cloudidentity.devices.deviceUsers.delete",
              "httpMethod": "DELETE",
              "path": "v1/{+name}",
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ]
            },
            "block": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Blocks device from accessing user data",
              "path": "v1/{+name}:block",
              "id": "cloudidentity.devices.deviceUsers.block",
              "httpMethod": "POST"
            },
            "wipe": {
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "path": "v1/{+name}:wipe",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "description": "Lists/Searches DeviceUsers.",
              "path": "v1/{+parent}/deviceUsers",
              "id": "cloudidentity.devices.deviceUsers.list",
              "httpMethod": "GET"
            },
            "lookup": {
              "path": "v1/{+parent}:lookup",
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "httpMethod": "GET",
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]"
            }
          },
          "resources": {
            "clientStates": {
              "methods": {
                "get": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "description": "Gets the client state for the device user",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ]
                },
                "list": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/clientStates",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "description": "Lists the client states for the given search query."
                },
                "patch": {
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices"
                  ],
                  "path": "v1/{+name}",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "httpMethod": "PATCH"
                }
              }
            }
          }
        }
      }
    },
    "inboundOidcSsoProfiles": {
      "methods": {
        "create": {
          "id": "cloudidentity.inboundOidcSsoProfiles.create",
          "httpMethod": "POST",
          "path": "v1/inboundOidcSsoProfiles",
          "description": "Creates an InboundOidcSsoProfile for a customer. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "flatPath": "v1/inboundOidcSsoProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "list": {
          "flatPath": "v1/inboundOidcSsoProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists InboundOidcSsoProfile objects for a Google enterprise customer.",
          "id": "cloudidentity.inboundOidcSsoProfiles.list",
          "httpMethod": "GET",
          "path": "v1/inboundOidcSsoProfiles"
        },
        "delete": {
          "id": "cloudidentity.inboundOidcSsoProfiles.delete",
          "httpMethod": "DELETE",
          "path": "v1/{+name}",
          "description": "Deletes an InboundOidcSsoProfile.",
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "get": {
          "id": "cloudidentity.inboundOidcSsoProfiles.get",
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "description": "Gets an InboundOidcSsoProfile.",
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "patch": {
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundOidcSsoProfiles.patch",
          "httpMethod": "PATCH",
          "description": "Updates an InboundOidcSsoProfile. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        }
      }
    },
    "inboundSsoAssignments": {
      "methods": {
        "list": {
          "description": "Lists the InboundSsoAssignments for a `Customer`.",
          "flatPath": "v1/inboundSsoAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/inboundSsoAssignments",
          "id": "cloudidentity.inboundSsoAssignments.list",
          "httpMethod": "GET"
        },
        "create": {
          "flatPath": "v1/inboundSsoAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates an InboundSsoAssignment for users and devices in a `Customer` under a given `Group` or `OrgUnit`.",
          "path": "v1/inboundSsoAssignments",
          "id": "cloudidentity.inboundSsoAssignments.create",
          "httpMethod": "POST"
        },
        "patch": {
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates an InboundSsoAssignment. The body of this request is the `inbound_sso_assignment` field and the `update_mask` is relative to that. For example: a PATCH to `/v1/inboundSsoAssignments/0abcdefg1234567&update_mask=rank` with a body of `{ \"rank\": 1 }` moves that (presumably group-targeted) SSO assignment to the highest priority and shifts any other group-targeted assignments down in priority.",
          "id": "cloudidentity.inboundSsoAssignments.patch",
          "httpMethod": "PATCH",
          "path": "v1/{+name}"
        },
        "get": {
          "description": "Gets an InboundSsoAssignment.",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSsoAssignments.get",
          "httpMethod": "GET"
        },
        "delete": {
          "description": "Deletes an InboundSsoAssignment. To disable SSO, Create (or Update) an assignment that has `sso_mode` == `SSO_OFF`.",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSsoAssignments.delete",
          "httpMethod": "DELETE"
        }
      }
    },
    "policies": {
      "methods": {
        "get": {
          "flatPath": "v1/policies/{policiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies",
            "https://www.googleapis.com/auth/cloud-identity.policies.readonly"
          ],
          "description": "Get a policy.",
          "path": "v1/{+name}",
          "id": "cloudidentity.policies.get",
          "httpMethod": "GET"
        },
        "list": {
          "id": "cloudidentity.policies.list",
          "httpMethod": "GET",
          "path": "v1/policies",
          "description": "List policies.",
          "flatPath": "v1/policies",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies",
            "https://www.googleapis.com/auth/cloud-identity.policies.readonly"
          ]
        }
      }
    },
    "customers": {
      "resources": {
        "userinvitations": {
          "methods": {
            "get": {
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}",
              "id": "cloudidentity.customers.userinvitations.get",
              "httpMethod": "GET",
              "description": "Retrieves a UserInvitation resource. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains."
            },
            "cancel": {
              "description": "Cancels a UserInvitation that was already sent.",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel",
              "path": "v1/{+name}:cancel",
              "id": "cloudidentity.customers.userinvitations.cancel",
              "httpMethod": "POST"
            },
            "isInvitableUser": {
              "description": "Verifies whether a user account is eligible to receive a UserInvitation (is an unmanaged account). Eligibility is based on the following criteria: * the email address is a consumer account and it's the primary email address of the account, and * the domain of the email address matches an existing verified Google Workspace or Cloud Identity domain If both conditions are met, the user is eligible. **Note:** This method is not supported for Workspace Essentials custome[...]",
              "id": "cloudidentity.customers.userinvitations.isInvitableUser",
              "httpMethod": "GET",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser",
              "path": "v1/{+name}:isInvitableUser"
            },
            "send": {
              "id": "cloudidentity.customers.userinvitations.send",
              "httpMethod": "POST",
              "path": "v1/{+name}:send",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:send",
              "description": "Sends a UserInvitation to email. If the `UserInvitation` does not exist for this request and it is a valid request, the request creates a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour delay where newly-created consumer accounts will not appear in the results. You can still send a `UserInvitation` to those accounts if you know the unmanaged email address and IsInvitableUser==True."
            },
            "list": {
              "path": "v1/{+parent}/userinvitations",
              "flatPath": "v1/customers/{customersId}/userinvitations",
              "id": "cloudidentity.customers.userinvitations.list",
              "httpMethod": "GET",
              "description": "Retrieves a list of UserInvitation resources. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains."
            }
          }
        }
      }
    },
    "groups": {
      "resources": {
        "memberships": {
          "methods": {
            "get": {
              "path": "v1/{+name}",
              "id": "cloudidentity.groups.memberships.get",
              "httpMethod": "GET",
              "description": "Retrieves a `Membership`.",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "delete": {
              "description": "Deletes a `Membership`.",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.delete",
              "httpMethod": "DELETE",
              "path": "v1/{+name}"
            },
            "checkTransitiveMembership": {
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:checkTransitiveMembership",
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor mu[...]",
              "flatPath": "v1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "searchTransitiveGroups": {
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups.",
              "path": "v1/{+parent}/memberships:searchTransitiveGroups",
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "httpMethod": "GET"
            },
            "create": {
              "id": "cloudidentity.groups.memberships.create",
              "httpMethod": "POST",
              "path": "v1/{+parent}/memberships",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Creates a `Membership`."
            },
            "lookup": {
              "path": "v1/{+parent}/memberships:lookup",
              "id": "cloudidentity.groups.memberships.lookup",
              "httpMethod": "GET",
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "list": {
              "description": "Lists the `Membership`s within a `Group`.",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships",
              "id": "cloudidentity.groups.memberships.list",
              "httpMethod": "GET"
            },
            "searchDirectGroups": {
              "id": "cloudidentity.groups.memberships.searchDirectGroups",
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:searchDirectGroups",
              "flatPath": "v1/groups/{groupsId}/memberships:searchDirectGroups",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Searches direct groups of a member."
            },
            "getMembershipGraph": {
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:getMembershipGraph",
              "flatPath": "v1/groups/{groupsId}/memberships:getMembershipGraph",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the respon[...]"
            },
            "modifyMembershipRoles": {
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "path": "v1/{+name}:modifyMembershipRoles",
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "httpMethod": "POST"
            },
            "searchTransitiveMemberships": {
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:searchTransitiveMemberships",
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships",
              "httpMethod": "GET"
            }
          }
        }
      },
      "methods": {
        "updateSecuritySettings": {
          "id": "cloudidentity.groups.updateSecuritySettings",
          "httpMethod": "PATCH",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Update Security Settings"
        },
        "lookup": {
          "path": "v1/groups:lookup",
          "id": "cloudidentity.groups.lookup",
          "httpMethod": "GET",
          "flatPath": "v1/groups:lookup",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`."
        },
        "list": {
          "description": "Lists the `Group` resources under a customer or namespace.",
          "flatPath": "v1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.list",
          "httpMethod": "GET",
          "path": "v1/groups"
        },
        "create": {
          "flatPath": "v1/groups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates a Group.",
          "path": "v1/groups",
          "id": "cloudidentity.groups.create",
          "httpMethod": "POST"
        },
        "patch": {
          "flatPath": "v1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates a `Group`.",
          "id": "cloudidentity.groups.patch",
          "httpMethod": "PATCH",
          "path": "v1/{+name}"
        },
        "search": {
          "description": "Searches for `Group` resources matching a specified query.",
          "flatPath": "v1/groups:search",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/groups:search",
          "id": "cloudidentity.groups.search",
          "httpMethod": "GET"
        },
        "get": {
          "description": "Retrieves a `Group`.",
          "flatPath": "v1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.get",
          "httpMethod": "GET",
          "path": "v1/{+name}"
        },
        "delete": {
          "description": "Deletes a `Group`.",
          "flatPath": "v1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.delete",
          "httpMethod": "DELETE"
        },
        "getSecuritySettings": {
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.getSecuritySettings",
          "httpMethod": "GET",
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Get Security Settings"
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly": {
          "description": "See all of the Inbound SSO profiles and their assignments to any Org Units or Google Groups in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.policies": {
          "description": "See and edit policies in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.devices": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.readonly": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
        },
        "https://www.googleapis.com/auth/cloud-identity.inboundsso": {
          "description": "See and edit all of the Inbound SSO profiles and their assignments to any Org Units or Google Groups in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-identity.policies.readonly": {
          "description": "See policies in your Cloud Identity Organization."
        }
      }
    }
  },
  "documentationLink": "https://cloud.google.com/identity/",
  "servicePath": "",
  "ownerDomain": "google.com",
  "title": "Cloud Identity API"
}