{
  "revision": "20260429",
  "version_module": true,
  "id": "cloudsearch:v1",
  "baseUrl": "https://cloudsearch.googleapis.com/",
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "protocol": "rest",
  "version": "v1",
  "basePath": "",
  "mtlsRootUrl": "https://cloudsearch.mtls.googleapis.com/",
  "rootUrl": "https://cloudsearch.googleapis.com/",
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "documentationLink": "https://developers.google.com/workspace/cloud-search/docs/guides/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.debug": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.stats.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.query": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.settings.indexing": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.stats": {
          "description": "Index and serve your organization's data with Cloud Search"
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/cloud_search.settings": {
          "description": "Index and serve your organization's data with Cloud Search"
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "servicePath": "",
  "resources": {
    "operations": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.debug",
            "https://www.googleapis.com/auth/cloud_search.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing",
            "https://www.googleapis.com/auth/cloud_search.settings.query"
          ],
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "GET",
          "id": "cloudsearch.operations.get",
          "path": "v1/{+name}"
        }
      },
      "resources": {
        "lro": {
          "methods": {
            "list": {
              "id": "cloudsearch.operations.lro.list",
              "path": "v1/{+name}/lro",
              "flatPath": "v1/operations/{operationsId}/lro",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.debug",
                "https://www.googleapis.com/auth/cloud_search.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
            }
          }
        }
      }
    },
    "debug": {
      "resources": {
        "datasources": {
          "resources": {
            "items": {
              "methods": {
                "checkAccess": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "description": "Checks whether an item is accessible by specified principal. Principal must be a user; groups and domain values aren't supported. **Note:** This API requires an admin account to execute.",
                  "id": "cloudsearch.debug.datasources.items.checkAccess",
                  "path": "v1/debug/{+name}:checkAccess",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}:checkAccess",
                  "httpMethod": "POST"
                },
                "searchByViewUrl": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "description": "Fetches the item whose viewUrl exactly matches that of the URL provided in the request. **Note:** This API requires an admin account to execute.",
                  "httpMethod": "POST",
                  "flatPath": "v1/debug/datasources/{datasourcesId}/items:searchByViewUrl",
                  "path": "v1/debug/{+name}/items:searchByViewUrl",
                  "id": "cloudsearch.debug.datasources.items.searchByViewUrl"
                }
              },
              "resources": {
                "unmappedids": {
                  "methods": {
                    "list": {
                      "path": "v1/debug/{+parent}/unmappedids",
                      "id": "cloudsearch.debug.datasources.items.unmappedids.list",
                      "httpMethod": "GET",
                      "flatPath": "v1/debug/datasources/{datasourcesId}/items/{itemsId}/unmappedids",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud_search",
                        "https://www.googleapis.com/auth/cloud_search.debug"
                      ],
                      "description": "List all unmapped identities for a specific item. **Note:** This API requires an admin account to execute."
                    }
                  }
                }
              }
            }
          }
        },
        "identitysources": {
          "resources": {
            "unmappedids": {
              "methods": {
                "list": {
                  "path": "v1/debug/{+parent}/unmappedids",
                  "id": "cloudsearch.debug.identitysources.unmappedids.list",
                  "httpMethod": "GET",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/unmappedids",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "description": "Lists unmapped user identities for an identity source. **Note:** This API requires an admin account to execute."
                }
              }
            },
            "items": {
              "methods": {
                "listForunmappedidentity": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.debug"
                  ],
                  "description": "Lists names of items associated with an unmapped identity. **Note:** This API requires an admin account to execute.",
                  "httpMethod": "GET",
                  "flatPath": "v1/debug/identitysources/{identitysourcesId}/items:forunmappedidentity",
                  "path": "v1/debug/{+parent}/items:forunmappedidentity",
                  "id": "cloudsearch.debug.identitysources.items.listForunmappedidentity"
                }
              }
            }
          }
        }
      }
    },
    "query": {
      "resources": {
        "sources": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.query"
              ],
              "description": "Returns list of sources that user can use for Search and Suggest APIs. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/workspace/cloud-search/docs/guides/delegation/).",
              "flatPath": "v1/query/sources",
              "httpMethod": "GET",
              "id": "cloudsearch.query.sources.list",
              "path": "v1/query/sources"
            }
          }
        }
      },
      "methods": {
        "search": {
          "id": "cloudsearch.query.search",
          "path": "v1/query/search",
          "flatPath": "v1/query/search",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "description": "The Cloud Search Query API provides the search method, which returns the most relevant results from a user query. The results can come from Google Workspace apps, such as Gmail or Google Drive, or they can come from data that you have indexed from a third party. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide [...]"
        },
        "removeActivity": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "description": "Provides functionality to remove logged activity for a user. Currently to be used only for Chat 1p clients **Note:** This API requires a standard end user account to execute. A service account can't perform Remove Activity requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/workspace/cloud-search/docs/guides/delegation/).",
          "path": "v1/query:removeActivity",
          "id": "cloudsearch.query.removeActivity",
          "httpMethod": "POST",
          "flatPath": "v1/query:removeActivity"
        },
        "suggest": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.query"
          ],
          "description": "Provides suggestions for autocompleting the query. **Note:** This API requires a standard end user account to execute. A service account can't perform Query API requests directly; to use a service account to perform queries, set up [Google Workspace domain-wide delegation of authority](https://developers.google.com/workspace/cloud-search/docs/guides/delegation/).",
          "id": "cloudsearch.query.suggest",
          "path": "v1/query/suggest",
          "flatPath": "v1/query/suggest",
          "httpMethod": "POST"
        }
      }
    },
    "stats": {
      "resources": {
        "user": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "description": "Get the users statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "httpMethod": "GET",
                  "flatPath": "v1/stats/user/searchapplications/{searchapplicationsId}",
                  "path": "v1/stats/user/{+name}",
                  "id": "cloudsearch.stats.user.searchapplications.get"
                }
              }
            }
          }
        },
        "index": {
          "resources": {
            "datasources": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "description": "Gets indexed item statistics for a single data source. **Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/index/datasources/{datasourcesId}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.index.datasources.get",
                  "path": "v1/stats/index/{+name}"
                }
              }
            }
          }
        },
        "query": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "description": "Get the query statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "httpMethod": "GET",
                  "flatPath": "v1/stats/query/searchapplications/{searchapplicationsId}",
                  "path": "v1/stats/query/{+name}",
                  "id": "cloudsearch.stats.query.searchapplications.get"
                }
              }
            }
          }
        },
        "session": {
          "resources": {
            "searchapplications": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.stats",
                    "https://www.googleapis.com/auth/cloud_search.stats.indexing"
                  ],
                  "description": "Get the # of search sessions, % of successful sessions with a click query statistics for search application. **Note:** This API requires a standard end user account to execute.",
                  "flatPath": "v1/stats/session/searchapplications/{searchapplicationsId}",
                  "httpMethod": "GET",
                  "id": "cloudsearch.stats.session.searchapplications.get",
                  "path": "v1/stats/session/{+name}"
                }
              }
            }
          }
        }
      },
      "methods": {
        "getUser": {
          "path": "v1/stats/user",
          "id": "cloudsearch.stats.getUser",
          "httpMethod": "GET",
          "flatPath": "v1/stats/user",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "description": "Get the users statistics for customer. **Note:** This API requires a standard end user account to execute."
        },
        "getSearchapplication": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "description": "Get search application stats for customer. **Note:** This API requires a standard end user account to execute.",
          "httpMethod": "GET",
          "flatPath": "v1/stats/searchapplication",
          "path": "v1/stats/searchapplication",
          "id": "cloudsearch.stats.getSearchapplication"
        },
        "getSession": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "description": "Get the # of search sessions, % of successful sessions with a click query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "httpMethod": "GET",
          "flatPath": "v1/stats/session",
          "path": "v1/stats/session",
          "id": "cloudsearch.stats.getSession"
        },
        "getQuery": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "description": "Get the query statistics for customer. **Note:** This API requires a standard end user account to execute.",
          "id": "cloudsearch.stats.getQuery",
          "path": "v1/stats/query",
          "flatPath": "v1/stats/query",
          "httpMethod": "GET"
        },
        "getIndex": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.stats",
            "https://www.googleapis.com/auth/cloud_search.stats.indexing"
          ],
          "description": "Gets indexed item statistics aggreggated across all data sources. This API only returns statistics for previous dates; it doesn't return statistics for the current day. **Note:** This API requires a standard end user account to execute.",
          "flatPath": "v1/stats/index",
          "httpMethod": "GET",
          "id": "cloudsearch.stats.getIndex",
          "path": "v1/stats/index"
        }
      }
    },
    "v1": {
      "methods": {
        "initializeCustomer": {
          "id": "cloudsearch.initializeCustomer",
          "path": "v1:initializeCustomer",
          "flatPath": "v1:initializeCustomer",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "description": "Enables `third party` support in Google Cloud Search. **Note:** This API requires an admin account to execute."
        }
      }
    },
    "indexing": {
      "resources": {
        "datasources": {
          "methods": {
            "updateSchema": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "description": "Updates the schema of a data source. This method does not perform incremental updates to the schema. Instead, this method updates the schema by overwriting the entire schema. **Note:** This API requires an admin or service account to execute.",
              "httpMethod": "PUT",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "path": "v1/indexing/{+name}/schema",
              "id": "cloudsearch.indexing.datasources.updateSchema"
            },
            "getSchema": {
              "path": "v1/indexing/{+name}/schema",
              "id": "cloudsearch.indexing.datasources.getSchema",
              "httpMethod": "GET",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "description": "Gets the schema of a data source. **Note:** This API requires an admin or service account to execute."
            },
            "deleteSchema": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "description": "Deletes the schema of a data source. **Note:** This API requires an admin or service account to execute.",
              "id": "cloudsearch.indexing.datasources.deleteSchema",
              "path": "v1/indexing/{+name}/schema",
              "flatPath": "v1/indexing/datasources/{datasourcesId}/schema",
              "httpMethod": "DELETE"
            }
          },
          "resources": {
            "items": {
              "methods": {
                "index": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Updates Item ACL, metadata, and content. It will insert the Item if it does not exist. This method does not support partial updates. Fields with no provided values are cleared out in the Cloud Search index. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:index",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.index",
                  "path": "v1/indexing/{+name}:index"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Lists all or a subset of Item resources. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items",
                  "httpMethod": "GET",
                  "id": "cloudsearch.indexing.datasources.items.list",
                  "path": "v1/indexing/{+name}/items"
                },
                "upload": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Creates an upload session for uploading item content. For items smaller than 100 KB, it's easier to embed the content inline within an index request. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "path": "v1/indexing/{+name}:upload",
                  "id": "cloudsearch.indexing.datasources.items.upload",
                  "httpMethod": "POST",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:upload"
                },
                "unreserve": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Unreserves all items from a queue, making them all eligible to be polled. This method is useful for resetting the indexing queue after a connector has been restarted. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:unreserve",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.unreserve",
                  "path": "v1/indexing/{+name}/items:unreserve"
                },
                "delete": {
                  "path": "v1/indexing/{+name}",
                  "id": "cloudsearch.indexing.datasources.items.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Deletes Item resource for the specified resource name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source."
                },
                "poll": {
                  "id": "cloudsearch.indexing.datasources.items.poll",
                  "path": "v1/indexing/{+name}/items:poll",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:poll",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Polls for unreserved items from the indexing queue and marks a set as reserved, starting with items that have the oldest timestamp from the highest priority ItemStatus. The priority order is as follows: ERROR MODIFIED NEW_ITEM ACCEPTED Reserving items ensures that polling from other threads cannot create overlapping sets. After handling the reserved items, the client should put items back into the unreserved state, either by calling index, or by calling push wit[...]"
                },
                "push": {
                  "id": "cloudsearch.indexing.datasources.items.push",
                  "path": "v1/indexing/{+name}:push",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}:push",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Pushes an item onto a queue for later polling and updating. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source."
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Gets Item resource by item name. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "httpMethod": "GET",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items/{itemsId}",
                  "path": "v1/indexing/{+name}",
                  "id": "cloudsearch.indexing.datasources.items.get"
                },
                "deleteQueueItems": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud_search",
                    "https://www.googleapis.com/auth/cloud_search.indexing"
                  ],
                  "description": "Deletes all items in a queue. This method is useful for deleting stale items. This API requires an admin or service account to execute. The service account used is the one whitelisted in the corresponding data source.",
                  "flatPath": "v1/indexing/datasources/{datasourcesId}/items:deleteQueueItems",
                  "httpMethod": "POST",
                  "id": "cloudsearch.indexing.datasources.items.deleteQueueItems",
                  "path": "v1/indexing/{+name}/items:deleteQueueItems"
                }
              }
            }
          }
        }
      }
    },
    "settings": {
      "resources": {
        "searchapplications": {
          "methods": {
            "update": {
              "httpMethod": "PUT",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.searchapplications.update",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Updates a search application. **Note:** This API requires an admin account to execute."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Deletes a search application. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "DELETE",
              "id": "cloudsearch.settings.searchapplications.delete",
              "path": "v1/settings/{+name}"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Updates a search application. **Note:** This API requires an admin account to execute.",
              "id": "cloudsearch.settings.searchapplications.patch",
              "path": "v1/settings/{+name}",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "PATCH"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Gets the specified search application. **Note:** This API requires an admin account to execute.",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}",
              "httpMethod": "GET",
              "id": "cloudsearch.settings.searchapplications.get",
              "path": "v1/settings/{+name}"
            },
            "reset": {
              "httpMethod": "POST",
              "flatPath": "v1/settings/searchapplications/{searchapplicationsId}:reset",
              "path": "v1/settings/{+name}:reset",
              "id": "cloudsearch.settings.searchapplications.reset",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Resets a search application to default settings. This will return an empty response. **Note:** This API requires an admin account to execute."
            },
            "create": {
              "id": "cloudsearch.settings.searchapplications.create",
              "path": "v1/settings/searchapplications",
              "flatPath": "v1/settings/searchapplications",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Creates a search application. **Note:** This API requires an admin account to execute."
            },
            "list": {
              "flatPath": "v1/settings/searchapplications",
              "httpMethod": "GET",
              "id": "cloudsearch.settings.searchapplications.list",
              "path": "v1/settings/searchapplications",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.query"
              ],
              "description": "Lists all search applications. **Note:** This API requires an admin account to execute."
            }
          }
        },
        "datasources": {
          "methods": {
            "patch": {
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "httpMethod": "PATCH",
              "id": "cloudsearch.settings.datasources.patch",
              "path": "v1/settings/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "description": "Updates a datasource. **Note:** This API requires an admin account to execute."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "description": "Gets a datasource. **Note:** This API requires an admin account to execute.",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.datasources.get",
              "httpMethod": "GET",
              "flatPath": "v1/settings/datasources/{datasourcesId}"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "description": "Deletes a datasource. **Note:** This API requires an admin account to execute.",
              "httpMethod": "DELETE",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.datasources.delete"
            },
            "update": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "description": "Updates a datasource. **Note:** This API requires an admin account to execute.",
              "httpMethod": "PUT",
              "flatPath": "v1/settings/datasources/{datasourcesId}",
              "path": "v1/settings/{+name}",
              "id": "cloudsearch.settings.datasources.update"
            },
            "list": {
              "id": "cloudsearch.settings.datasources.list",
              "path": "v1/settings/datasources",
              "flatPath": "v1/settings/datasources",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "description": "Lists datasources. **Note:** This API requires an admin account to execute."
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v1/settings/datasources",
              "path": "v1/settings/datasources",
              "id": "cloudsearch.settings.datasources.create",
              "scopes": [
                "https://www.googleapis.com/auth/cloud_search",
                "https://www.googleapis.com/auth/cloud_search.settings",
                "https://www.googleapis.com/auth/cloud_search.settings.indexing"
              ],
              "description": "Creates a datasource. **Note:** This API requires an admin account to execute."
            }
          }
        }
      },
      "methods": {
        "getCustomer": {
          "flatPath": "v1/settings/customer",
          "httpMethod": "GET",
          "id": "cloudsearch.settings.getCustomer",
          "path": "v1/settings/customer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "description": "Get customer settings. **Note:** This API requires an admin account to execute."
        },
        "updateCustomer": {
          "path": "v1/settings/customer",
          "id": "cloudsearch.settings.updateCustomer",
          "httpMethod": "PATCH",
          "flatPath": "v1/settings/customer",
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.settings",
            "https://www.googleapis.com/auth/cloud_search.settings.indexing"
          ],
          "description": "Update customer settings. **Note:** This API requires an admin account to execute."
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "id": "cloudsearch.media.upload",
          "path": "v1/media/{+resourceName}",
          "flatPath": "v1/media/{mediaId}",
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/cloud_search",
            "https://www.googleapis.com/auth/cloud_search.indexing"
          ],
          "description": "Uploads media for indexing. The upload endpoint supports direct and resumable upload protocols and is intended for large items that can not be [inlined during index requests](https://developers.google.com/workspace/cloud-search/docs/reference/rest/v1/indexing.datasources.items#itemcontent). To index large content: 1. Call indexing.datasources.items.upload with the item name to begin an upload session and retrieve the UploadItemRef. 1. Call media.upload to upload the con[...]"
        }
      }
    }
  },
  "description": "Cloud Search provides cloud-based search capabilities over Google Workspace data. The Cloud Search API allows indexing of non-Google Workspace data into Cloud Search.",
  "title": "Cloud Search API",
  "name": "cloudsearch",
  "fullyEncodeReservedExpansion": true,
  "schemas": {
    "RepositoryError": {
      "id": "RepositoryError",
      "properties": {
        "httpStatusCode": {
          "type": "integer",
          "description": "Error codes. Matches the definition of HTTP status codes.",
          "format": "int32"
        },
        "errorMessage": {
          "type": "string",
          "description": "Message that describes the error. The maximum allowable length of the message is 8192 characters."
        },
        "type": {
          "description": "The type of error.",
          "enum": [
            "UNKNOWN",
            "NETWORK_ERROR",
            "DNS_ERROR",
            "CONNECTION_ERROR",
            "AUTHENTICATION_ERROR",
            "AUTHORIZATION_ERROR",
            "SERVER_ERROR",
            "QUOTA_EXCEEDED",
            "SERVICE_UNAVAILABLE",
            "CLIENT_ERROR"
          ],
          "type": "string",
          "enumDescriptions": [
            "Unknown error.",
            "Unknown or unreachable host.",
            "DNS problem, such as the DNS server is not responding.",
            "Cannot connect to the repository server.",
            "Failed authentication due to incorrect credentials.",
            "Service account is not authorized for the repository.",
            "Repository server error.",
            "Quota exceeded.",
            "Server temporarily unavailable.",
            "Client-related error, such as an invalid request from the connector to the repository server."
          ]
        }
      },
      "type": "object",
      "description": "Errors when the connector is communicating to the source repository."
    },
    "GetCustomerUserStatsResponse": {
      "id": "GetCustomerUserStatsResponse",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "CustomerUserStats"
          }
        }
      },
      "type": "object"
    },
    "IntegerPropertyOptions": {
      "description": "The options for integer properties.",
      "type": "object",
      "id": "IntegerPropertyOptions",
      "properties": {
        "maximumValue": {
          "type": "string",
          "description": "The maximum value of the property. The minimum and maximum values for the property are used to rank results according to the ordered ranking. Indexing requests with values greater than the maximum are accepted and ranked with the same weight as items indexed with the maximum value.",
          "format": "int64"
        },
        "minimumValue": {
          "type": "string",
          "description": "The minimum value of the property. The minimum and maximum values for the property are used to rank results according to the ordered ranking. Indexing requests with values less than the minimum are accepted and ranked with the same weight as items indexed with the minimum value.",
          "format": "int64"
        },
        "operatorOptions": {
          "description": "If set, describes how the integer should be used as a search operator.",
          "$ref": "IntegerOperatorOptions"
        },
        "integerFacetingOptions": {
          "$ref": "IntegerFacetingOptions",
          "description": "If set, describes integer faceting options for the given integer property. The corresponding integer property should be marked isFacetable."
        },
        "orderedRanking": {
          "type": "string",
          "enumDescriptions": [
            "There is no ranking order for the property. Results are not adjusted by this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower ranking.",
            "This property is ranked in descending order. Lower values indicate higher ranking."
          ],
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "description": "Used to specify the ordered ranking for the integer. Can only be used if isRepeatable is false."
        }
      }
    },
    "Date": {
      "description": "Represents a whole calendar date, for example a date of birth. The time of day and time zone are either specified elsewhere or are not significant. The date is relative to the [Proleptic Gregorian Calendar](https://en.wikipedia.org/wiki/Proleptic_Gregorian_calendar). The date must be a valid calendar date between the year 1 and 9999.",
      "id": "Date",
      "properties": {
        "month": {
          "type": "integer",
          "description": "Month of date. Must be from 1 to 12.",
          "format": "int32"
        },
        "year": {
          "description": "Year of date. Must be from 1 to 9999.",
          "format": "int32",
          "type": "integer"
        },
        "day": {
          "description": "Day of month. Must be from 1 to 31 and valid for the year and month.",
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickCommonDocumentDriveDocumentMetadata": {
      "id": "EnterpriseTopazSidekickCommonDocumentDriveDocumentMetadata",
      "properties": {
        "documentId": {
          "description": "The drive document cosmo id. Client could use the id to build a URL to open a document. Please use Document.document_id.",
          "deprecated": true,
          "type": "string"
        },
        "isPrivate": {
          "type": "boolean",
          "description": "Additional field to identify whether a document is private since scope set to LIMITED can mean both that the doc is private or that it's shared with others. is_private indicates whether the doc is not shared with anyone except for the owner."
        },
        "lastUpdatedTimeMs": {
          "description": "Timestamp of the last updated time of the document in milliseconds since epoch.",
          "format": "uint64",
          "type": "string"
        },
        "lastEditTimeMs": {
          "description": "Timestamp of the most recent edit from the current user in milliseconds since epoch.",
          "format": "uint64",
          "type": "string"
        },
        "lastModificationTimeMillis": {
          "type": "string",
          "description": "Last modification time of the document (independent of the user that modified it).",
          "format": "int64"
        },
        "scope": {
          "description": "ACL scope of the document which identifies the sharing status of the doc (e.g., limited, shared with link, team drive, ...).",
          "enum": [
            "UNKNOWN_DOCUMENT_SCOPE",
            "LIMITED",
            "DASHER_DOMAIN_WITH_LINK",
            "DASHER_DOMAIN",
            "PUBLIC_WITH_LINK",
            "PUBLIC",
            "TEAM_DRIVE"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ]
        },
        "lastViewTimeMs": {
          "type": "string",
          "description": "Timestamp of the most recent view from the current user in milliseconds since epoch.",
          "format": "uint64"
        },
        "lastCommentTimeMs": {
          "type": "string",
          "description": "Timestamp of the most recent comment added to the document in milliseconds since epoch.",
          "format": "uint64"
        },
        "owner": {
          "$ref": "EnterpriseTopazSidekickCommonPerson",
          "description": "The owner of the document."
        }
      },
      "type": "object",
      "description": "Meta data for drive documents."
    },
    "TextValues": {
      "type": "object",
      "id": "TextValues",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "The maximum allowable length for text values is 2048 characters."
        }
      },
      "description": "List of text values."
    },
    "MapInfo": {
      "type": "object",
      "id": "MapInfo",
      "properties": {
        "long": {
          "description": "Longitude in degrees",
          "format": "double",
          "type": "number"
        },
        "zoom": {
          "description": "The zoom level of the map. A constant zoom value of 18 is used for now to match the zoom of the map shown on a Moma Teams Profile page",
          "format": "int32",
          "type": "integer"
        },
        "lat": {
          "type": "number",
          "description": "Latitude in degrees",
          "format": "double"
        },
        "locationUrl": {
          "$ref": "SafeUrlProto",
          "description": "URL to a view of a map centered on the user's work location in Campus Maps (for google.com) or Google Maps (external)."
        },
        "mapTile": {
          "type": "array",
          "description": "MapTiles for the area around a user's work location",
          "items": {
            "$ref": "MapTile"
          }
        }
      },
      "description": "Geo information used for rendering a map that shows the user's work location."
    },
    "DoubleValues": {
      "description": "List of double values.",
      "type": "object",
      "id": "DoubleValues",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        }
      }
    },
    "SuggestResult": {
      "id": "SuggestResult",
      "properties": {
        "suggestedQuery": {
          "description": "The suggested query that will be used for search, when the user clicks on the suggestion",
          "type": "string"
        },
        "source": {
          "description": "The source of the suggestion.",
          "$ref": "Source"
        },
        "querySuggestion": {
          "$ref": "QuerySuggestion",
          "description": "This field will be present if the suggested query is a word/phrase completion."
        },
        "peopleSuggestion": {
          "description": "This is present when the suggestion indicates a person. It contains more information about the person - like their email ID, name etc.",
          "$ref": "PeopleSuggestion"
        }
      },
      "type": "object",
      "description": "One suggestion result."
    },
    "EnterpriseTopazSidekickShareMeetingDocsCardProto": {
      "type": "object",
      "id": "EnterpriseTopazSidekickShareMeetingDocsCardProto",
      "properties": {
        "event": {
          "description": "Event.",
          "$ref": "EnterpriseTopazSidekickAgendaEntry"
        },
        "document": {
          "type": "array",
          "description": "Documents to share for the given meeting.",
          "items": {
            "$ref": "EnterpriseTopazSidekickCommonDocument"
          }
        }
      },
      "description": "Share meeting docs card proto."
    },
    "RemoveActivityResponse": {
      "description": "Remove Logged Activity Response. will return an empty response for now. Will be revisited in later phases.",
      "type": "object",
      "id": "RemoveActivityResponse",
      "properties": {}
    },
    "Context": {
      "id": "Context",
      "properties": {
        "type": {
          "type": "array",
          "items": {
            "type": "string",
            "enumDescriptions": [
              "",
              "",
              "",
              ""
            ],
            "enum": [
              "UNKNOWN_CARD_TYPE",
              "HOMEPAGE_CARD",
              "ANSWER_CARD",
              "RHS_CARD"
            ]
          },
          "description": "[Required] Type of the card (homepage, Answer or RHS)."
        },
        "locale": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "[Optional] The locales for which the card should be triggered (e.g., en_US and en_CA). If missing, the card is going to show to clients regardless of their locale."
        },
        "query": {
          "items": {
            "type": "string"
          },
          "description": "[Required only for Answer and RHS cards - will be ignored for Homepage] cards. It's the exact case-insensitive queries that will trigger the Answer or RHS card.",
          "type": "array"
        },
        "startDateSec": {
          "type": "string",
          "description": "[Optional] Date (in seconds since epoch) when the card should start being shown. If missing, start_date_sec will be Jan 1st, 1970 UTC.",
          "format": "int64"
        },
        "dayOfWeek": {
          "items": {
            "type": "integer",
            "format": "int32"
          },
          "description": "[Optional] Day of week when the card should be shown, where 0 is Monday.",
          "type": "array"
        },
        "location": {
          "description": "[Optional] Text-free locations where the card should be shown. This is expected to match the user's location in focus. If no location is specified, the card will be shown for any location.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "endDateSec": {
          "description": "[Optional] Date (in seconds since epoch) when the card should stop being shown. If missing, end_date_sec will be set to Jan 1st, 2100.",
          "format": "int64",
          "type": "string"
        },
        "surface": {
          "type": "array",
          "items": {
            "enum": [
              "UNKNOWN_SURFACE",
              "DESKTOP",
              "ANDROID",
              "IOS",
              "MOBILE",
              "ANY"
            ],
            "type": "string",
            "enumDescriptions": [
              "",
              "",
              "",
              "",
              "Any mobile device.",
              ""
            ]
          },
          "description": "[Optional] Surface where the card should be shown in. If missing, the card will be shown in any surface."
        },
        "endDayOffsetSec": {
          "type": "string",
          "description": "[Optional] End time in seconds, within a day, when the card should stop being shown if it's within [start_date_sec, end_date_sec]. If missing, this is set to 86400 (24 hours x 3600 sec/hour), i.e., midnight next day.",
          "format": "int64"
        },
        "app": {
          "items": {
            "type": "string",
            "enumDescriptions": [
              "",
              "",
              ""
            ],
            "enum": [
              "UNKNOWN_APP",
              "TOPAZ",
              "MOMA"
            ]
          },
          "description": "[Optional] App where the card should be shown. If missing, the card will be shown in TOPAZ.",
          "type": "array"
        },
        "startDayOffsetSec": {
          "type": "string",
          "description": "[Optional] Start time in seconds, within a day, when the card should be shown if it's within [start_date_sec, end_date_sec]. If 0, the card will be shown from 12:00am on.",
          "format": "int64"
        }
      },
      "type": "object"
    },
    "SearchApplication": {
      "description": "SearchApplication",
      "id": "SearchApplication",
      "properties": {
        "dataSourceRestrictions": {
          "type": "array",
          "description": "Retrictions applied to the configurations. The maximum number of elements is 10.",
          "items": {
            "$ref": "DataSourceRestriction"
          }
        },
        "returnResultThumbnailUrls": {
          "type": "boolean",
          "description": "With each result we should return the URI for its thumbnail (when applicable)"
        },
        "scoringConfig": {
          "$ref": "ScoringConfig",
          "description": "Configuration for ranking results."
        },
        "name": {
          "description": "The name of the Search Application. Format: searchapplications/{application_id}.",
          "type": "string"
        },
        "defaultFacetOptions": {
          "description": "The default fields for returning facet results. The sources specified here also have been included in data_source_restrictions above.",
          "items": {
            "$ref": "FacetOptions"
          },
          "type": "array"
        },
        "sourceConfig": {
          "type": "array",
          "description": "Configuration for a sources specified in data_source_restrictions.",
          "items": {
            "$ref": "SourceConfig"
          }
        },
        "displayName": {
          "description": "Display name of the Search Application. The maximum length is 300 characters.",
          "type": "string"
        },
        "defaultSortOptions": {
          "description": "The default options for sorting the search results",
          "$ref": "SortOptions"
        },
        "operationIds": {
          "description": "Output only. IDs of the Long Running Operations (LROs) currently running for this schema. Output only field.",
          "readOnly": true,
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "enableAuditLog": {
          "description": "Indicates whether audit logging is on/off for requests made for the search application in query APIs.",
          "type": "boolean"
        },
        "queryInterpretationConfig": {
          "$ref": "QueryInterpretationConfig",
          "description": "The default options for query interpretation"
        }
      },
      "type": "object"
    },
    "EnumValuePair": {
      "description": "The enumeration value pair defines two things: a required string value and an optional integer value. The string value defines the necessary query term required to retrieve that item, such as *p0* for a priority item. The integer value determines the ranking of that string value relative to other enumerated values for the same property. For example, you might associate *p0* with *0* and define another enum pair such as *p1* and *1*. You must use the integer value in combina[...]",
      "type": "object",
      "id": "EnumValuePair",
      "properties": {
        "integerValue": {
          "type": "integer",
          "description": "The integer value of the EnumValuePair which must be non-negative. Optional.",
          "format": "int32"
        },
        "stringValue": {
          "description": "The string value of the EnumValuePair. The maximum length is 32 characters.",
          "type": "string"
        }
      }
    },
    "EnterpriseTopazSidekickAssistCardProto": {
      "description": "Wrapper proto for the Assist cards.",
      "id": "EnterpriseTopazSidekickAssistCardProto",
      "properties": {
        "personalizedDocsCard": {
          "$ref": "EnterpriseTopazSidekickPersonalizedDocsCardProto",
          "description": "Card with recommended documents for the user.",
          "deprecated": true
        },
        "peopleDisambiguationCard": {
          "description": "The people disambiguation card.",
          "$ref": "EnterpriseTopazSidekickPeopleDisambiguationCard"
        },
        "personProfileCard": {
          "$ref": "EnterpriseTopazSidekickPersonProfileCard",
          "description": "Full profile card."
        },
        "cardType": {
          "type": "string",
          "description": "Card type.",
          "enumDescriptions": [
            "The default type, an unknown card type.",
            "The user's agenda for the day.",
            "Changelists.",
            "Any group of meetings for the day that are overlapping.",
            "Create notes for a meeting specified in the request.",
            "Create notes for meeting query.",
            "News about your SFDC customers.",
            "Find a time for two people to meet.",
            "The user's next non-declined meeting.",
            "Important documents for you since you have viewed them in the last month and there's some action going on.",
            "Documents that are trending in your company. A TRENDING_DOCS card can be of two types: TRENDING_IN_COLLABORATORS (i.e., Stay in the Loop) and TRENDING_IN_DOMAIN (i.e., Popular Content). Use DOMAIN_TRENDING_DOCS/TEAM_TRENDING_DOCS instead.",
            "An upcoming trip with all trip information along with calendar events in the destination timezone.",
            "The Morning/Evening Summary Card for the next working day.",
            "A meeting. When requesting meetings, the service will return a MEETING card for each meeting the user has in his agenda.",
            "All cards related to the homepage (agenda, conflicting-meetings, summary, etc...). This type should no longer be used. Use HOMEPAGE_V3 instead.",
            "A card to with specifics to share meeting documents with all attendees.",
            "Represents a set of users that the requesting user has low affinity with.",
            "All cards related to the homepage-v3 (agenda-group, WIP, etc...)",
            "A group of agenda-events (meeting, conflicts)",
            "The documents that you were recently working on.",
            "(v3) The \"get and keep ahead\" card for today and tomorrow",
            "Generic answer card.",
            "Third party answer card.",
            "Documents that are trending in your company/domain (i.e., Popular Content).",
            "Documents that are trending in your team (i.e., Stay in the Loop).",
            "Documents that match the user's query (e.g. sheets shared with me).",
            "A help card that provides examples of queries the user can ask.",
            "Answer card for a single person (e.g. what is x's phone number).",
            "Answer card for a list of people related to the person that is the subject of the query (e.g. who reports to x).",
            "Knowledge card for a single person and their related people.",
            "People Search promotion card."
          ],
          "enumDeprecated": [
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            true,
            true,
            false,
            false,
            false,
            false,
            false,
            false
          ],
          "enum": [
            "UNKNOWN_TYPE",
            "AGENDA",
            "CHANGELISTS",
            "CONFLICTING_MEETINGS",
            "CREATE_NOTES_FOR_MEETING",
            "CREATE_NOTES_FOR_MEETING_REQUEST",
            "CUSTOMER_NEWS",
            "FIND_MEETING_TIME",
            "NEXT_MEETING",
            "PERSONALIZED_DOCS",
            "TRENDING_DOCS",
            "UPCOMING_TRIP",
            "SUMMARY",
            "MEETINGS",
            "HOMEPAGE",
            "SHARE_MEETING_DOCS",
            "DISCOVER_PEOPLE",
            "HOMEPAGE_V3",
            "AGENDA_GROUP",
            "WORK_IN_PROGRESS",
            "GET_AND_KEEP_AHEAD",
            "GENERIC_ANSWER_CARD",
            "THIRD_PARTY_ANSWER_CARD",
            "DOMAIN_TRENDING_DOCS",
            "TEAM_TRENDING_DOCS",
            "DOCUMENT_LIST_ANSWER_CARD",
            "SUGGESTED_QUERY_ANSWER_CARD",
            "PERSON_ANSWER_CARD",
            "RELATED_PEOPLE_ANSWER_CARD",
            "PERSON_KNOWLEDGE_CARD",
            "PEOPLE_SEARCH_PROMOTION_CARD"
          ]
        },
        "sharedDocuments": {
          "description": "Shared documents.",
          "deprecated": true,
          "$ref": "EnterpriseTopazSidekickDocumentPerCategoryList"
        },
        "peoplePromotionCard": {
          "description": "People Search promotion card.",
          "$ref": "PeoplePromotionCard"
        },
        "personAnswerCard": {
          "description": "Answer card that represents a single person.",
          "$ref": "EnterpriseTopazSidekickPeopleAnswerPersonAnswerCard"
        },
        "meetingNotesCard": {
          "description": "Meeting notes card.",
          "$ref": "EnterpriseTopazSidekickMeetingNotesCardProto"
        },
        "suggestedQueryAnswerCard": {
          "description": "Answer card for what natural language queries the user can ask.",
          "$ref": "EnterpriseTopazSidekickAnswerSuggestedQueryAnswerCard"
        },
        "conflictingMeetingsCard": {
          "$ref": "EnterpriseTopazSidekickConflictingEventsCardProto",
          "description": "Conflicting events card.",
          "deprecated": true
        },
        "findMeetingTimeCard": {
          "$ref": "EnterpriseTopazSidekickFindMeetingTimeCardProto",
          "description": "Find meeting time card."
        },
        "meetingNotesCardRequest": {
          "$ref": "EnterpriseTopazSidekickMeetingNotesCardRequest",
          "description": "Request for meeting notes card."
        },
        "agendaGroupCardProto": {
          "$ref": "EnterpriseTopazSidekickAgendaGroupCardProto",
          "description": "Agenda group card."
        },
        "workInProgressCardProto": {
          "description": "Work In Progress card.",
          "$ref": "EnterpriseTopazSidekickRecentDocumentsCardProto"
        },
        "relatedPeopleAnswerCard": {
          "$ref": "EnterpriseTopazSidekickPeopleAnswerRelatedPeopleAnswerCard",
          "description": "Answer card that represents a list of people related to a person."
        },
        "documentListCard": {
          "description": "Answer card for documents that are applicable to the current query.",
          "$ref": "EnterpriseTopazSidekickDocumentPerCategoryList"
        },
        "genericAnswerCard": {
          "$ref": "EnterpriseTopazSidekickGenericAnswerCard",
          "description": "Generic answer card."
        },
        "meeting": {
          "description": "Meeting card.",
          "deprecated": true,
          "$ref": "EnterpriseTopazSidekickAgendaEntry"
        },
        "thirdPartyAnswerCard": {
          "$ref": "ThirdPartyGenericCard",
          "description": "Third party answer cards."
        },
        "cardMetadata": {
          "$ref": "EnterpriseTopazSidekickCardMetadata",
          "description": "Card metadata such as chronology and render mode of the card."
        },
        "shareMeetingDocsCard": {
          "$ref": "EnterpriseTopazSidekickShareMeetingDocsCardProto",
          "description": "Sahre meeting docs card.",
          "deprecated": true
        },
        "documentsWithMentions": {
          "description": "Documents with mentions.",
          "deprecated": true,
          "$ref": "EnterpriseTopazSidekickDocumentPerCategoryList"
        },
        "getAndKeepAheadCard": {
          "$ref": "EnterpriseTopazSidekickGetAndKeepAheadCardProto",
          "description": "Get and keep ahead card."
        }
      },
      "type": "object"
    },
    "DatePropertyOptions": {
      "description": "The options for date properties.",
      "type": "object",
      "id": "DatePropertyOptions",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the date should be used as a search operator.",
          "$ref": "DateOperatorOptions"
        }
      }
    },
    "SafeUrlProto": {
      "description": "Message containing a string that is safe to use in URL contexts in DOM APIs and HTML documents, where the URL context does not refer to a resource that loads code.",
      "id": "SafeUrlProto",
      "properties": {
        "privateDoNotAccessOrElseSafeUrlWrappedValue": {
          "type": "string",
          "description": "IMPORTANT: Never set or read this field, even from tests, it is private. See documentation at the top of .proto file for programming language packages with which to create or read this message."
        }
      },
      "type": "object"
    },
    "CompositeFilter": {
      "type": "object",
      "id": "CompositeFilter",
      "properties": {
        "subFilters": {
          "description": "Sub filters.",
          "items": {
            "$ref": "Filter"
          },
          "type": "array"
        },
        "logicOperator": {
          "description": "The logic operator of the sub filter.",
          "enum": [
            "AND",
            "OR",
            "NOT"
          ],
          "type": "string",
          "enumDescriptions": [
            "Logical operators, which can only be applied to sub filters.",
            "",
            "NOT can only be applied on a single sub filter."
          ]
        }
      }
    },
    "ObjectDefinition": {
      "description": "The definition for an object within a data source.",
      "type": "object",
      "id": "ObjectDefinition",
      "properties": {
        "name": {
          "description": "The name for the object, which then defines its type. Item indexing requests should set the objectType field equal to this value. For example, if *name* is *Document*, then indexing requests for items of type Document should set objectType equal to *Document*. Each object definition must be uniquely named within a schema. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The maximum length is 256 characters.",
          "type": "string"
        },
        "options": {
          "description": "The optional object-specific options.",
          "$ref": "ObjectOptions"
        },
        "propertyDefinitions": {
          "type": "array",
          "description": "The property definitions for the object. The maximum number of elements is 1000.",
          "items": {
            "$ref": "PropertyDefinition"
          }
        }
      }
    },
    "EnterpriseTopazSidekickPerson": {
      "id": "EnterpriseTopazSidekickPerson",
      "properties": {
        "gaiaId": {
          "type": "string",
          "description": "Gaia id.",
          "deprecated": true,
          "format": "int64"
        },
        "isGroup": {
          "description": "Whether the invitee is a group.",
          "type": "boolean"
        },
        "name": {
          "description": "Name.",
          "type": "string"
        },
        "email": {
          "description": "Email.",
          "type": "string"
        },
        "attendingStatus": {
          "enum": [
            "AWAITING",
            "YES",
            "NO",
            "MAYBE"
          ],
          "type": "string",
          "enumDescriptions": [
            "Awaiting for the user to set the status.",
            "Attending.",
            "Not attending.",
            "Tentatively attending."
          ],
          "description": "Attendance status of the person when included in a meeting event."
        },
        "photoUrl": {
          "type": "string",
          "description": "Absolute URL to the profile photo of the person."
        },
        "affinityLevel": {
          "description": "The level of affinity this person has with the requesting user.",
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "",
            ""
          ],
          "enum": [
            "UNKNOWN",
            "LOW",
            "MEDIUM",
            "HIGH"
          ]
        },
        "obfuscatedGaiaId": {
          "description": "Obfuscated Gaia id.",
          "type": "string"
        }
      },
      "type": "object",
      "description": "Person."
    },
    "EnterpriseTopazSidekickAnswerAnswerListLabeledAnswer": {
      "description": "An answer with a corresponding label.",
      "type": "object",
      "id": "EnterpriseTopazSidekickAnswerAnswerListLabeledAnswer",
      "properties": {
        "label": {
          "type": "string",
          "description": "A localized label for the answer (e.g. \"Cell phone\" vs \"Desk phone\")."
        },
        "answer": {
          "description": "The free text answer.",
          "type": "string"
        }
      }
    },
    "ObjectDisplayOptions": {
      "description": "The display options for an object.",
      "type": "object",
      "id": "ObjectDisplayOptions",
      "properties": {
        "objectDisplayLabel": {
          "description": "The user friendly label to display in the search result to indicate the type of the item. This is OPTIONAL; if not provided, an object label isn't displayed on the context line of the search results. The maximum length is 64 characters.",
          "type": "string"
        },
        "metalines": {
          "items": {
            "$ref": "Metaline"
          },
          "description": "Defines the properties that are displayed in the metalines of the search results. The property values are displayed in the order given here. If a property holds multiple values, all of the values are displayed before the next properties. For this reason, it is a good practice to specify singular properties before repeated properties in this list. All of the properties must set is_returnable to true. The maximum number of metalines is 3.",
          "type": "array"
        }
      }
    },
    "PropertyDefinition": {
      "id": "PropertyDefinition",
      "properties": {
        "isSortable": {
          "description": "Indicates that the property can be used for sorting. Cannot be true for properties that are repeatable. Cannot be true for properties whose type is object. IsReturnable must be true to set this option. Only supported for boolean, date, double, integer, and timestamp properties.",
          "type": "boolean"
        },
        "isRepeatable": {
          "description": "Indicates that multiple values are allowed for the property. For example, a document only has one description but can have multiple comments. Cannot be true for properties whose type is a boolean. If set to false, properties that contain more than one value cause the indexing request for that item to be rejected.",
          "type": "boolean"
        },
        "booleanPropertyOptions": {
          "$ref": "BooleanPropertyOptions"
        },
        "objectPropertyOptions": {
          "$ref": "ObjectPropertyOptions"
        },
        "isSuggestable": {
          "type": "boolean",
          "description": "Indicates that the property can be used for generating query suggestions."
        },
        "textPropertyOptions": {
          "$ref": "TextPropertyOptions"
        },
        "doublePropertyOptions": {
          "$ref": "DoublePropertyOptions"
        },
        "enumPropertyOptions": {
          "$ref": "EnumPropertyOptions"
        },
        "datePropertyOptions": {
          "$ref": "DatePropertyOptions"
        },
        "displayOptions": {
          "$ref": "PropertyDisplayOptions",
          "description": "The options that determine how the property is displayed in the Cloud Search results page if it's specified to be displayed in the object's display options."
        },
        "isWildcardSearchable": {
          "description": "Indicates that users can perform wildcard search for this property. Only supported for Text properties. IsReturnable must be true to set this option. In a given datasource maximum of 5 properties can be marked as is_wildcard_searchable. For more details, see [Define object properties](https://developers.google.com/workspace/cloud-search/docs/guides/schema-guide#properties)",
          "type": "boolean"
        },
        "name": {
          "type": "string",
          "description": "The name of the property. Item indexing requests sent to the Indexing API should set the property name equal to this value. For example, if name is *subject_line*, then indexing requests for document items with subject fields should set the name for that field equal to *subject_line*. Use the name as the identifier for the object property. Once registered as a property for an object, you cannot re-use this name for another property within that object. The name must star[...]"
        },
        "isFacetable": {
          "description": "Indicates that the property can be used for generating facets. Cannot be true for properties whose type is object. IsReturnable must be true to set this option. Only supported for boolean, enum, integer, and text properties.",
          "type": "boolean"
        },
        "integerPropertyOptions": {
          "$ref": "IntegerPropertyOptions"
        },
        "timestampPropertyOptions": {
          "$ref": "TimestampPropertyOptions"
        },
        "isReturnable": {
          "description": "Indicates that the property identifies data that should be returned in search results via the Query API. If set to *true*, indicates that Query API users can use matching property fields in results. However, storing fields requires more space allocation and uses more bandwidth for search queries, which impacts performance over large datasets. Set to *true* here only if the field is needed for search results. Cannot be true for properties whose type is an object.",
          "type": "boolean"
        },
        "htmlPropertyOptions": {
          "$ref": "HtmlPropertyOptions"
        }
      },
      "type": "object",
      "description": "The definition of a property within an object."
    },
    "Operation": {
      "id": "Operation",
      "properties": {
        "name": {
          "description": "The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the `name` should be a resource name ending with `operations/{unique_id}`.",
          "type": "string"
        },
        "done": {
          "type": "boolean",
          "description": "If the value is `false`, it means the operation is still in progress. If `true`, the operation is completed, and either `error` or `response` is available."
        },
        "metadata": {
          "type": "object",
          "additionalProperties": {
            "type": "any",
            "description": "Properties of the object. Contains field @type with type URL."
          },
          "description": "Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any."
        },
        "error": {
          "$ref": "Status",
          "description": "The error result of the operation in case of failure or cancellation."
        }
      },
      "type": "object",
      "description": "This resource represents a long-running operation that is the result of a network API call."
    },
    "EnterpriseTopazSidekickMeetingNotesCardProto": {
      "description": "Information about the meeting notes created.",
      "id": "EnterpriseTopazSidekickMeetingNotesCardProto",
      "properties": {
        "url": {
          "type": "string",
          "description": "New URL."
        },
        "event": {
          "description": "The event to request meeting notes creation.",
          "$ref": "EnterpriseTopazSidekickAgendaEntry"
        },
        "title": {
          "type": "string",
          "description": "Title we want to show for meeting notes in the answer card"
        },
        "fileId": {
          "type": "string",
          "description": "Google Drive ID (a.k.a. resource ID) of the file."
        }
      },
      "type": "object"
    },
    "GetSearchApplicationUserStatsResponse": {
      "type": "object",
      "id": "GetSearchApplicationUserStatsResponse",
      "properties": {
        "stats": {
          "type": "array",
          "items": {
            "$ref": "SearchApplicationUserStats"
          }
        }
      }
    },
    "ResultDisplayField": {
      "type": "object",
      "id": "ResultDisplayField",
      "properties": {
        "label": {
          "type": "string",
          "description": "The display label for the property."
        },
        "property": {
          "description": "The name value pair for the property.",
          "$ref": "NamedProperty"
        },
        "operatorName": {
          "description": "The operator name of the property.",
          "type": "string"
        }
      },
      "description": "Display Fields for Search Results"
    },
    "Action": {
      "type": "object",
      "id": "Action",
      "properties": {
        "title": {
          "description": "[Required] Title of the action.",
          "type": "string"
        },
        "url": {
          "description": "[Optional] Url of the action.",
          "type": "string"
        }
      }
    },
    "ResponseDebugInfo": {
      "description": "Debugging information about the response.",
      "id": "ResponseDebugInfo",
      "properties": {
        "formattedDebugInfo": {
          "type": "string",
          "description": "General debug info formatted for display."
        }
      },
      "type": "object"
    },
    "ScoringConfig": {
      "type": "object",
      "id": "ScoringConfig",
      "properties": {
        "disableFreshness": {
          "description": "Whether to use freshness as a ranking signal. By default, freshness is used as a ranking signal. Note that this setting is not available in the Admin UI.",
          "type": "boolean"
        },
        "disablePersonalization": {
          "type": "boolean",
          "description": "Whether to personalize the results. By default, personal signals will be used to boost results."
        }
      },
      "description": "Scoring configurations for a source while processing a Search or Suggest request."
    },
    "DeleteQueueItemsRequest": {
      "id": "DeleteQueueItemsRequest",
      "properties": {
        "connectorName": {
          "type": "string",
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "queue": {
          "type": "string",
          "description": "The name of a queue to delete items from."
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      },
      "type": "object"
    },
    "Value": {
      "id": "Value",
      "properties": {
        "timestampValue": {
          "format": "google-datetime",
          "type": "string"
        },
        "integerValue": {
          "type": "string",
          "format": "int64"
        },
        "dateValue": {
          "$ref": "Date"
        },
        "doubleValue": {
          "format": "double",
          "type": "number"
        },
        "booleanValue": {
          "type": "boolean"
        },
        "stringValue": {
          "type": "string"
        }
      },
      "type": "object",
      "description": "Definition of a single value with generic type."
    },
    "SpellResult": {
      "id": "SpellResult",
      "properties": {
        "suggestedQuery": {
          "type": "string",
          "description": "The suggested spelling of the query."
        },
        "suggestionType": {
          "description": "Suggestion triggered for the current query.",
          "enum": [
            "SUGGESTION_TYPE_UNSPECIFIED",
            "NON_EMPTY_RESULTS_SPELL_SUGGESTION",
            "ZERO_RESULTS_FULL_PAGE_REPLACEMENT"
          ],
          "type": "string",
          "enumDescriptions": [
            "Default spell check type",
            "Spell suggestion without any results changed. The results are still shown for the original query (which has non zero / results) with a suggestion for spelling that would have results.",
            "Spell suggestion triggered when original query has no results. When the original query has no results, and spell suggestion has results we trigger results for the spell corrected query."
          ]
        },
        "suggestedQueryHtml": {
          "$ref": "SafeHtmlProto",
          "description": "The sanitized HTML representing the spell corrected query that can be used in the UI. This usually has language-specific tags to mark up parts of the query that are spell checked."
        }
      },
      "type": "object"
    },
    "SearchResult": {
      "description": "Results containing indexed information for a document. Next ID: 16",
      "type": "object",
      "id": "SearchResult",
      "properties": {
        "title": {
          "description": "Title of the search result.",
          "type": "string"
        },
        "debugInfo": {
          "description": "Debugging information about this search result.",
          "$ref": "ResultDebugInfo"
        },
        "url": {
          "description": "The URL of the search result. The URL contains a Google redirect to the actual item. This URL is signed and shouldn't be changed.",
          "type": "string"
        },
        "clusteredResults": {
          "type": "array",
          "items": {
            "$ref": "SearchResult"
          },
          "description": "If source is clustered, provide list of clustered results. There will only be one level of clustered results. If current source is not enabled for clustering, this field will be empty."
        },
        "snippet": {
          "description": "The concatenation of all snippets (summaries) available for this result.",
          "$ref": "Snippet"
        },
        "metadata": {
          "$ref": "Metadata",
          "description": "Metadata of the search result."
        }
      }
    },
    "DateOperatorOptions": {
      "description": "Optional. Provides a search operator for date properties. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "DateOperatorOptions",
      "properties": {
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the date property using the less-than operator. For example, if lessThanOperatorName is *closedbefore* and the property's name is *closeDate*, then queries like *closedbefore:<value>* show results only where the value of the property named *closeDate* is earlier than *<value>*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        },
        "operatorName": {
          "type": "string",
          "description": "Indicates the actual string required in the query in order to isolate the date property. For example, suppose an issue tracking schema object has a property named *closeDate* that specifies an operator with an operatorName of *closedon*. For searches on that data, queries like *closedon:<value>* show results only where the value of the *closeDate* property matches *<value>*. By contrast, a search that uses the same *<value>* without an operator returns all items where *[...]"
        },
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the date property using the greater-than operator. For example, if greaterThanOperatorName is *closedafter* and the property's name is *closeDate*, then queries like *closedafter:<value>* show results only where the value of the property named *closeDate* is later than *<value>*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickNlpMetadata": {
      "description": "Metadata about the NLP interpretation of the query.",
      "type": "object",
      "id": "EnterpriseTopazSidekickNlpMetadata",
      "properties": {
        "confidence": {
          "type": "number",
          "description": "Confidence of the interpretation that generated this card.",
          "format": "float"
        }
      }
    },
    "SourceCrowdingConfig": {
      "type": "object",
      "id": "SourceCrowdingConfig",
      "properties": {
        "numResults": {
          "type": "integer",
          "description": "Maximum number of results allowed from a datasource in a result page as long as results from other sources are not exhausted. Value specified must not be negative. A default value is used if this value is equal to 0. To disable crowding, set the value greater than 100.",
          "format": "int32"
        },
        "numSuggestions": {
          "type": "integer",
          "description": "Maximum number of suggestions allowed from a source. No limits will be set on results if this value is less than or equal to 0.",
          "format": "int32"
        }
      },
      "description": "Set search results crowding limits. Crowding is a situation in which multiple results from the same source or host \"crowd out\" other results, diminishing the quality of search for users. To foster better search quality and source diversity in search results, you can set a condition to reduce repetitive results by source."
    },
    "ListItemNamesForUnmappedIdentityResponse": {
      "type": "object",
      "id": "ListItemNamesForUnmappedIdentityResponse",
      "properties": {
        "itemNames": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "nextPageToken": {
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list.",
          "type": "string"
        }
      }
    },
    "ErrorMessage": {
      "id": "ErrorMessage",
      "properties": {
        "errorMessage": {
          "type": "string"
        },
        "source": {
          "$ref": "Source"
        }
      },
      "type": "object",
      "description": "Error message per source response."
    },
    "UpdateSchemaRequest": {
      "type": "object",
      "id": "UpdateSchemaRequest",
      "properties": {
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "schema": {
          "$ref": "Schema",
          "description": "The new schema for the source."
        },
        "validateOnly": {
          "description": "If true, the schema will be checked for validity, but will not be registered with the data source, even if valid.",
          "type": "boolean"
        }
      }
    },
    "EnterpriseTopazSidekickPeopleAnswerDisambiguationInfoDisambiguationPerson": {
      "description": "A person that also matches the query, but was not selected due to a lower affinity with the requesting user.",
      "id": "EnterpriseTopazSidekickPeopleAnswerDisambiguationInfoDisambiguationPerson",
      "properties": {
        "person": {
          "$ref": "EnterpriseTopazSidekickCommonPerson",
          "description": "The profile of this person."
        },
        "query": {
          "type": "string",
          "description": "The query that can be used to produce an answer card with the same attribute, but for this person."
        }
      },
      "type": "object"
    },
    "ItemMetadata": {
      "type": "object",
      "id": "ItemMetadata",
      "properties": {
        "updateTime": {
          "type": "string",
          "description": "The time when the item was last modified in the source repository.",
          "format": "google-datetime"
        },
        "contentLanguage": {
          "description": "The BCP-47 language code for the item, such as \"en-US\" or \"sr-Latn\". For more information, see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier. The maximum length is 32 characters.",
          "type": "string"
        },
        "title": {
          "type": "string",
          "description": "The title of the item. If given, this will be the displayed title of the Search result. The maximum length is 2048 characters."
        },
        "interactions": {
          "description": "A list of interactions for the item. Interactions are used to improve Search quality, but are not exposed to end users. The maximum number of elements is 1000.",
          "items": {
            "$ref": "Interaction"
          },
          "type": "array"
        },
        "mimeType": {
          "type": "string",
          "description": "The original mime-type of ItemContent.content in the source repository. The maximum length is 256 characters."
        },
        "sourceRepositoryUrl": {
          "description": "Link to the source repository serving the data. Seach results apply this link to the title. Whitespace or special characters may cause Cloud Seach result links to trigger a redirect notice; to avoid this, encode the URL. The maximum length is 2048 characters.",
          "type": "string"
        },
        "searchQualityMetadata": {
          "description": "Additional search quality metadata of the item",
          "$ref": "SearchQualityMetadata"
        },
        "containerName": {
          "description": "The name of the container for this item. Deletion of the container item leads to automatic deletion of this item. Note: ACLs are not inherited from a container item. To provide ACL inheritance for an item, use the inheritAclFrom field. The maximum length is 1536 characters.",
          "type": "string"
        },
        "contextAttributes": {
          "type": "array",
          "description": "A set of named attributes associated with the item. This can be used for influencing the ranking of the item based on the context in the request. The maximum number of elements is 10.",
          "items": {
            "$ref": "ContextAttribute"
          }
        },
        "objectType": {
          "description": "The type of the item. This should correspond to the name of an object definition in the schema registered for the data source. For example, if the schema for the data source contains an object definition with name 'document', then item indexing requests for objects of that type should set objectType to 'document'. The maximum length is 256 characters.",
          "type": "string"
        },
        "hash": {
          "type": "string",
          "description": "Hashing value provided by the API caller. This can be used with the items.push method to calculate modified state. The maximum length is 2048 characters."
        },
        "createTime": {
          "type": "string",
          "description": "The time when the item was created in the source repository.",
          "format": "google-datetime"
        },
        "keywords": {
          "description": "Additional keywords or phrases that should match the item. Used internally for user generated content. The maximum number of elements is 100. The maximum length is 8192 characters.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "description": "Available metadata fields for the item."
    },
    "EnterpriseTopazSidekickPeopleDisambiguationCard": {
      "type": "object",
      "id": "EnterpriseTopazSidekickPeopleDisambiguationCard",
      "properties": {
        "person": {
          "items": {
            "$ref": "EnterpriseTopazSidekickCommonPerson"
          },
          "description": "Candidate persons for the query.",
          "type": "array"
        }
      }
    },
    "ResultCounts": {
      "description": "Result count information",
      "type": "object",
      "id": "ResultCounts",
      "properties": {
        "sourceResultCounts": {
          "description": "Result count information for each source with results.",
          "items": {
            "$ref": "SourceResultCount"
          },
          "type": "array"
        }
      }
    },
    "DataSourceRestriction": {
      "description": "Restriction on Datasource.",
      "id": "DataSourceRestriction",
      "properties": {
        "source": {
          "description": "The source of restriction.",
          "$ref": "Source"
        },
        "filterOptions": {
          "type": "array",
          "description": "Filter options restricting the results. If multiple filters are present, they are grouped by object type before joining. Filters with the same object type are joined conjunctively, then the resulting expressions are joined disjunctively. The maximum number of elements is 20. NOTE: Suggest API supports only few filters at the moment: \"objecttype\", \"type\" and \"mimetype\". For now, schema specific filters cannot be used to filter suggestions.",
          "items": {
            "$ref": "FilterOptions"
          }
        }
      },
      "type": "object"
    },
    "ListDataSourceResponse": {
      "id": "ListDataSourceResponse",
      "properties": {
        "sources": {
          "type": "array",
          "items": {
            "$ref": "DataSource"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        }
      },
      "type": "object"
    },
    "DoublePropertyOptions": {
      "description": "The options for double properties.",
      "id": "DoublePropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "DoubleOperatorOptions",
          "description": "If set, describes how the double should be used as a search operator."
        }
      },
      "type": "object"
    },
    "RemoveActivityRequest": {
      "type": "object",
      "id": "RemoveActivityRequest",
      "properties": {
        "userActivity": {
          "description": "User Activity containing the data to be deleted.",
          "$ref": "UserActivity"
        },
        "requestOptions": {
          "description": "Request options, such as the search application and clientId.",
          "$ref": "RequestOptions"
        }
      },
      "description": "Remove Logged Activity Request."
    },
    "EnterpriseTopazSidekickPeopleAnswerRelatedPeopleAnswerCard": {
      "description": "An answer card for a list of people that are related to the subject of the query.",
      "type": "object",
      "id": "EnterpriseTopazSidekickPeopleAnswerRelatedPeopleAnswerCard",
      "properties": {
        "relatedPeople": {
          "items": {
            "$ref": "EnterpriseTopazSidekickCommonPerson"
          },
          "description": "A list of people that are related to the query subject.",
          "type": "array"
        },
        "header": {
          "description": "The header to display for the card.",
          "$ref": "EnterpriseTopazSidekickPeopleAnswerPeopleAnswerCardHeader"
        },
        "statusMessage": {
          "description": "Localized user friendly message to display to the user in the case of missing data or an error.",
          "type": "string"
        },
        "disambiguationInfo": {
          "$ref": "EnterpriseTopazSidekickPeopleAnswerDisambiguationInfo",
          "description": "Disambiguation information."
        },
        "relationType": {
          "type": "string",
          "enumDescriptions": [
            "Unknown.",
            "Direct reports.",
            "The manager.",
            "The teammates/peers of the subject."
          ],
          "enum": [
            "UNKNOWN",
            "DIRECT_REPORTS",
            "MANAGER",
            "PEERS"
          ],
          "description": "Defines the type of relation the list of people have with the subject of the card."
        },
        "responseStatus": {
          "description": "The response status.",
          "type": "string",
          "enumDescriptions": [
            "Unknown.",
            "Success.",
            "No such person was found in the user's domain.",
            "A person was found to match the query, but an answer could not be obtained."
          ],
          "enum": [
            "UNKNOWN",
            "SUCCESS",
            "MISSING_PERSON",
            "MISSING_DATA"
          ]
        },
        "subject": {
          "description": "The profile of the person that was the subject of the query.",
          "$ref": "EnterpriseTopazSidekickCommonPerson"
        }
      }
    },
    "ResultDebugInfo": {
      "type": "object",
      "id": "ResultDebugInfo",
      "properties": {
        "formattedDebugInfo": {
          "type": "string",
          "description": "General debug info formatted for display."
        }
      },
      "description": "Debugging information about the result."
    },
    "EnterpriseTopazSidekickCommonDebugInfo": {
      "description": "Container of debugging information in all object levels. Extend as needed.",
      "id": "EnterpriseTopazSidekickCommonDebugInfo",
      "properties": {
        "message": {
          "type": "string",
          "description": "Debug message."
        }
      },
      "type": "object"
    },
    "PeopleSuggestion": {
      "description": "This field contains information about the person being suggested.",
      "id": "PeopleSuggestion",
      "properties": {
        "person": {
          "$ref": "Person",
          "description": "Suggested person. All fields of the person object might not be populated."
        }
      },
      "type": "object"
    },
    "FreshnessOptions": {
      "description": "Indicates which freshness property to use when adjusting search ranking for an item. Fresher, more recent dates indicate higher quality. Use the freshness option property that best works with your data. For fileshare documents, last modified time is most relevant. For calendar event data, the time when the event occurs is a more relevant freshness indicator. In this way, calendar events that occur closer to the time of the search query are considered higher quality and rank[...]",
      "type": "object",
      "id": "FreshnessOptions",
      "properties": {
        "freshnessProperty": {
          "type": "string",
          "description": "This property indicates the freshness level of the object in the index. If set, this property must be a top-level property within the property definitions and it must be a timestamp type or date type. Otherwise, the Indexing API uses updateTime as the freshness indicator. The maximum length is 256 characters. When a property is used to calculate freshness, the value defaults to 2 years from the current time."
        },
        "freshnessDuration": {
          "type": "string",
          "description": "The duration after which an object should be considered stale. The default value is 180 days (in seconds).",
          "format": "google-duration"
        }
      }
    },
    "ListOperationsResponse": {
      "id": "ListOperationsResponse",
      "properties": {
        "operations": {
          "type": "array",
          "items": {
            "$ref": "Operation"
          },
          "description": "A list of operations that matches the specified filter in the request."
        },
        "nextPageToken": {
          "type": "string",
          "description": "The standard List next-page token."
        },
        "unreachable": {
          "description": "Unordered list. Unreachable resources. Populated when the request sets `ListOperationsRequest.return_partial_success` and reads across collections. For example, when attempting to list all resources across all supported locations.",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object",
      "description": "The response message for Operations.ListOperations."
    },
    "Metaline": {
      "description": "A metaline is a list of properties that are displayed along with the search result to provide context.",
      "id": "Metaline",
      "properties": {
        "properties": {
          "type": "array",
          "description": "The list of displayed properties for the metaline. The maximum number of properties is 5.",
          "items": {
            "$ref": "DisplayedProperty"
          }
        }
      },
      "type": "object"
    },
    "UnreserveItemsRequest": {
      "id": "UnreserveItemsRequest",
      "properties": {
        "queue": {
          "type": "string",
          "description": "The name of a queue to unreserve items from."
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "connectorName": {
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnumPropertyOptions": {
      "description": "The options for enum properties, which allow you to define a restricted set of strings to match user queries, set rankings for those string values, and define an operator name to be paired with those strings so that users can narrow results to only items with a specific value. For example, for items in a request tracking system with priority information, you could define *p0* as an allowable enum value and tie this enum to the operator name *priority* so that search users c[...]",
      "id": "EnumPropertyOptions",
      "properties": {
        "operatorOptions": {
          "$ref": "EnumOperatorOptions",
          "description": "If set, describes how the enum should be used as a search operator."
        },
        "possibleValues": {
          "description": "The list of possible values for the enumeration property. All EnumValuePairs must provide a string value. If you specify an integer value for one EnumValuePair, then all possible EnumValuePairs must provide an integer value. Both the string value and integer value must be unique over all possible values. Once set, possible values cannot be removed or modified. If you supply an ordered ranking and think you might insert additional enum values in the future, leave gaps in[...]",
          "items": {
            "$ref": "EnumValuePair"
          },
          "type": "array"
        },
        "orderedRanking": {
          "description": "Used to specify the ordered ranking for the enumeration that determines how the integer values provided in the possible EnumValuePairs are used to rank results. If specified, integer values must be provided for all possible EnumValuePair values given for this property. Can only be used if isRepeatable is false.",
          "enum": [
            "NO_ORDER",
            "ASCENDING",
            "DESCENDING"
          ],
          "type": "string",
          "enumDescriptions": [
            "There is no ranking order for the property. Results aren't adjusted by this property's value.",
            "This property is ranked in ascending order. Lower values indicate lower ranking.",
            "This property is ranked in descending order. Lower values indicate higher ranking."
          ]
        }
      },
      "type": "object"
    },
    "Status": {
      "id": "Status",
      "properties": {
        "message": {
          "type": "string",
          "description": "A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client."
        },
        "details": {
          "description": "A list of messages that carry the error details. There is a common set of message types for APIs to use.",
          "items": {
            "type": "object",
            "additionalProperties": {
              "description": "Properties of the object. Contains field @type with type URL.",
              "type": "any"
            }
          },
          "type": "array"
        },
        "code": {
          "type": "integer",
          "description": "The status code, which should be an enum value of google.rpc.Code.",
          "format": "int32"
        }
      },
      "type": "object",
      "description": "The `Status` type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by [gRPC](https://github.com/grpc). Each `Status` message contains three pieces of data: error code, error message, and error details. You can find out more about this error model and how to work with it in the [API Design Guide](https://cloud.google.com/apis/design/errors)."
    },
    "EnterpriseTopazSidekickRecentDocumentsCardProto": {
      "id": "EnterpriseTopazSidekickRecentDocumentsCardProto",
      "properties": {
        "document": {
          "type": "array",
          "items": {
            "$ref": "EnterpriseTopazSidekickCommonDocument"
          }
        }
      },
      "type": "object"
    },
    "Source": {
      "description": "Defines sources for the suggest/search APIs.",
      "id": "Source",
      "properties": {
        "name": {
          "type": "string",
          "description": "Source name for content indexed by the Indexing API."
        },
        "predefinedSource": {
          "enum": [
            "NONE",
            "QUERY_HISTORY",
            "PERSON",
            "GOOGLE_DRIVE",
            "GOOGLE_GMAIL",
            "GOOGLE_SITES",
            "GOOGLE_GROUPS",
            "GOOGLE_CALENDAR",
            "GOOGLE_KEEP"
          ],
          "type": "string",
          "enumDescriptions": [
            "",
            "Suggests queries issued by the user in the past. Only valid when used with the suggest API. Ignored when used in the query API.",
            "Suggests people in the organization. Only valid when used with the suggest API. Results in an error when used in the query API.",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "description": "Predefined content source for Google Apps."
        }
      },
      "type": "object"
    },
    "PersonCore": {
      "id": "PersonCore",
      "properties": {
        "mission": {
          "type": "string",
          "description": "Custom mission statement the profile owner has added."
        },
        "jobTitle": {
          "type": "string",
          "description": "Profile owner's job title (e.g. \"Software Engineer\"). For google.com this is the Workday preferred job title."
        },
        "officeLocation": {
          "type": "string",
          "description": "Office/building identifier within the company. For google.com this is the office code (e.g. \"DE-MUC-ARP\")."
        },
        "photoUrl": {
          "$ref": "SafeUrlProto",
          "description": "Person photo."
        },
        "phoneNumbers": {
          "type": "array",
          "items": {
            "$ref": "EnterpriseTopazFrontendTeamsPersonCorePhoneNumber"
          }
        },
        "geoLocation": {
          "$ref": "MapInfo"
        },
        "totalDlrCount": {
          "type": "integer",
          "description": "Total count of the profile owner's dotted-line reports.",
          "format": "int32"
        },
        "gmailUrl": {
          "type": "string"
        },
        "postalAddress": {
          "type": "string",
          "description": "Postal address of office/building."
        },
        "chatUrl": {
          "description": "The URL to start a chat conversation with the profile owner. For google.com this is a Hangouts URL.",
          "$ref": "SafeUrlProto"
        },
        "dottedLineReports": {
          "description": "A subset of the profile owner's dotted-line reports. The number of entities here may be less than total_dlr_count. Note that not all fields of these PersonCores will be set, in particular, relationships will be empty.",
          "items": {
            "$ref": "PersonCore"
          },
          "type": "array"
        },
        "department": {
          "type": "string",
          "description": "The person's Organization department, e.g. \"People Operations\". For google.com this is usually called \"area\"."
        },
        "addressMeAs": {
          "description": "Instructions for how to address this person (e.g. custom pronouns). For google.com this is a set of pronouns from a defined list of options.",
          "type": "string"
        },
        "managers": {
          "description": "The profile owner's management chain from top to bottom, where managers[0] is the CEO, manager[N-2] is the person's manager's manager and managers[N-1] is the person's direct manager. Note that not all fields of these PersonCores will be set, in particular, relationships will be empty.",
          "items": {
            "$ref": "PersonCore"
          },
          "type": "array"
        },
        "emails": {
          "items": {
            "type": "string"
          },
          "description": "E-mail addresses of the person. The primary or preferred email should be first.",
          "type": "array"
        },
        "birthday": {
          "$ref": "Date",
          "description": "Person birthday."
        },
        "waldoComeBackTime": {
          "format": "google-datetime",
          "type": "string"
        },
        "admins": {
          "items": {
            "$ref": "PersonCore"
          },
          "description": "The profile owner's admins in no particular order. Note that not all fields of these PersonCores will be set, in particular, relationships will be empty.",
          "type": "array"
        },
        "name": {
          "description": "Human-readable Unicode display name.",
          "type": "string"
        },
        "keywordTypes": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "List of keys to use from the map 'keywords'."
        },
        "directReports": {
          "items": {
            "$ref": "PersonCore"
          },
          "description": "A subset of the profile owner's direct reports. The number of entities here may be less than total_direct_reports_count, because typically ProfileResponse does not include all the person's reports, if there are too many to retrieve efficiently. Note that not all fields of these PersonCores will be set, in particular, relationships will be empty.",
          "type": "array"
        },
        "ftePermille": {
          "type": "string",
          "description": "Full-time equivalent (in ‰) (e.g. 800 for a person who's working 80%).",
          "format": "int64"
        },
        "adminTo": {
          "items": {
            "$ref": "PersonCore"
          },
          "description": "People the profile owner is an admin to. Note that not all fields of these PersonCores will be set, in particular, relationships will be empty.",
          "type": "array"
        },
        "personId": {
          "description": "The person's obfuscated Gaia ID.",
          "type": "string"
        },
        "keywords": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Custom keywords the domain admin has added."
        },
        "availabilityStatus": {
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "",
            ""
          ],
          "enum": [
            "UNKNOWN",
            "OUT_OF_OFFICE",
            "OUTSIDE_WORKING_HOURS",
            "AVAILABLE"
          ]
        },
        "username": {
          "description": "External ID of type \"login_id\" for the profile. For google.com this is the username/LDAP.",
          "type": "string"
        },
        "dottedLineManagers": {
          "type": "array",
          "description": "The profile owner's direct dotted line managers in no particular order. Note that not all fields of these PersonCores will be set, in particular, relationships will be empty.",
          "items": {
            "$ref": "PersonCore"
          }
        },
        "location": {
          "type": "string",
          "description": "Detailed desk location within the company. For google.com this is the desk location code (e.g. \"DE-MUC-ARP-6T2-6T2C0C\") if the person has a desk."
        },
        "employeeId": {
          "description": "Person's employee number (external ID of type \"organization\") For google.com this is the badge number (e.g. 2 for Larry Page).",
          "type": "string"
        },
        "costCenter": {
          "type": "string",
          "description": "Person's cost center as a string, e.g. \"926: Googler Apps\"."
        },
        "totalFteCount": {
          "type": "string",
          "description": "The sum of all profile owner's reports and their own full-time-equivalents in ‰ (e.g. 1800 if one report is working 80% and profile owner 100%).",
          "format": "int64"
        },
        "calendarUrl": {
          "description": "The URL to open the profile owner's primary calendar.",
          "$ref": "SafeUrlProto"
        },
        "totalDirectReportsCount": {
          "type": "integer",
          "description": "Total count of the profile owner's direct reports.",
          "format": "int32"
        },
        "fingerprint": {
          "type": "string",
          "description": "A fingerprint used by PAPI to reliably determine if a resource has changed Externally it is used as part of the etag."
        }
      },
      "type": "object",
      "description": "Information for rendering a person. NEXT ID: 37"
    },
    "PropertyDisplayOptions": {
      "id": "PropertyDisplayOptions",
      "properties": {
        "displayLabel": {
          "type": "string",
          "description": "The user friendly label for the property that is used if the property is specified to be displayed in ObjectDisplayOptions. If provided, the display label is shown in front of the property values when the property is part of the object display options. For example, if the property value is '1', the value by itself may not be useful context for the user. If the display name given was 'priority', then the user sees 'priority : 1' in the search results which provides clear[...]"
        }
      },
      "type": "object",
      "description": "The display options for a property."
    },
    "StructuredResult": {
      "description": "Structured results that are returned as part of search request.",
      "id": "StructuredResult",
      "properties": {
        "person": {
          "$ref": "Person",
          "description": "Representation of a person"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickCommonDocumentJustification": {
      "type": "object",
      "id": "EnterpriseTopazSidekickCommonDocumentJustification",
      "properties": {
        "justification": {
          "description": "A locale aware message that explains why this document was selected.",
          "type": "string"
        },
        "reason": {
          "description": "Reason on why the document is selected. Populate for trending documents.",
          "type": "string",
          "enumDescriptions": [
            "Unknown justification.",
            "Popular documents within collaborators.",
            "Popular documents within the domain.",
            "Documents being reviewed frequently by the current user .",
            "Documents being edited frequently by the current user .",
            "Documents updated since user's last visit.",
            "Documents that receive comments since user's last visit.",
            "Documents in the calendar event description.",
            "Documents in the calendar event attachments section.",
            "Documents attached in calendar event metadata instead of the attachment section. Event metadata is not visible to the final user. Enterprise assist uses this metadata to store auto-generated documents such as meeting notes.",
            "Documents mined, and so, probably related to the request context. For example, this category includes documents related to a meeting.",
            "Documents that contains mentions of the user.",
            "Documents that are shared with the user."
          ],
          "enum": [
            "UNKNOWN",
            "TRENDING_IN_COLLABORATORS",
            "TRENDING_IN_DOMAIN",
            "FREQUENTLY_VIEWED",
            "FREQUENTLY_EDITED",
            "NEW_UPDATES",
            "NEW_COMMENTS",
            "EVENT_DESCRIPTION",
            "EVENT_ATTACHMENT",
            "EVENT_METADATA_ATTACHMENT",
            "MINED_DOCUMENT",
            "NEW_MENTIONS",
            "NEW_SHARES"
          ]
        }
      },
      "description": "Justification of why we are reporting the document."
    },
    "ProcessingError": {
      "id": "ProcessingError",
      "properties": {
        "code": {
          "description": "Error code indicating the nature of the error.",
          "enum": [
            "PROCESSING_ERROR_CODE_UNSPECIFIED",
            "MALFORMED_REQUEST",
            "UNSUPPORTED_CONTENT_FORMAT",
            "INDIRECT_BROKEN_ACL",
            "ACL_CYCLE"
          ],
          "type": "string",
          "enumDescriptions": [
            "Input only value. Use this value in Items.",
            "Item's ACL, metadata, or content is malformed or in invalid state. FieldViolations contains more details on where the problem is.",
            "Countent format is unsupported.",
            "Items with incomplete ACL information due to inheriting other items with broken ACL or having groups with unmapped descendants.",
            "ACL inheritance graph formed a cycle."
          ]
        },
        "errorMessage": {
          "type": "string",
          "description": "The description of the error."
        },
        "fieldViolations": {
          "description": "In case the item fields are invalid, this field contains the details about the validation errors.",
          "items": {
            "$ref": "FieldViolation"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "ItemStructuredData": {
      "description": "Available structured data fields for the item.",
      "type": "object",
      "id": "ItemStructuredData",
      "properties": {
        "object": {
          "$ref": "StructuredDataObject",
          "description": "The structured data object that should conform to a registered object definition in the schema for the data source."
        },
        "hash": {
          "description": "Hashing value provided by the API caller. This can be used with the items.push method to calculate modified state. The maximum length is 2048 characters.",
          "type": "string"
        }
      }
    },
    "PushItem": {
      "description": "Represents an item to be pushed to the indexing queue.",
      "type": "object",
      "id": "PushItem",
      "properties": {
        "type": {
          "enum": [
            "UNSPECIFIED",
            "MODIFIED",
            "NOT_MODIFIED",
            "REPOSITORY_ERROR",
            "REQUEUE"
          ],
          "type": "string",
          "enumDescriptions": [
            "Default UNSPECIFIED. Specifies that the push operation should not modify ItemStatus",
            "Indicates that the repository document has been modified or updated since the previous update call. This changes status to MODIFIED state for an existing item. If this is called on a non existing item, the status is changed to NEW_ITEM.",
            "Item in the repository has not been modified since the last update call. This push operation will set status to ACCEPTED state.",
            "Connector is facing a repository error regarding this item. Change status to REPOSITORY_ERROR state. Item is unreserved and rescheduled at a future time determined by exponential backoff.",
            "Call push with REQUEUE only for items that have been reserved. This action unreserves the item and resets its available time to the wall clock time."
          ],
          "description": "The type of the push operation that defines the push behavior."
        },
        "queue": {
          "type": "string",
          "description": "Queue to which this item belongs. The `default` queue is chosen if this field is not specified. The maximum length is 512 characters."
        },
        "metadataHash": {
          "description": "The metadata hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters.",
          "type": "string"
        },
        "structuredDataHash": {
          "description": "Structured data hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters.",
          "type": "string"
        },
        "payload": {
          "description": "Provides additional document state information for the connector, such as an alternate repository ID and other metadata. The maximum length is 8192 bytes.",
          "format": "byte",
          "type": "string"
        },
        "repositoryError": {
          "$ref": "RepositoryError",
          "description": "Populate this field to store Connector or repository error details. This information is displayed in the Admin Console. This field may only be populated when the Type is REPOSITORY_ERROR."
        },
        "contentHash": {
          "type": "string",
          "description": "Content hash of the item according to the repository. If specified, this is used to determine how to modify this item's status. Setting this field and the type field results in argument error. The maximum length is 2048 characters."
        }
      }
    },
    "ObjectOptions": {
      "id": "ObjectOptions",
      "properties": {
        "freshnessOptions": {
          "description": "The freshness options for an object.",
          "$ref": "FreshnessOptions"
        },
        "displayOptions": {
          "description": "The options that determine how the object is displayed in the Cloud Search results page.",
          "$ref": "ObjectDisplayOptions"
        },
        "suggestionFilteringOperators": {
          "type": "array",
          "description": "Operators that can be used to filter suggestions. For Suggest API, only operators mentioned here will be honored in the FilterOptions. Only TEXT and ENUM operators are supported. NOTE: \"objecttype\", \"type\" and \"mimetype\" are already supported. This property is to configure schema specific operators. Even though this is an array, only one operator can be specified. This is an array for future extensibility. Operators mapping to multiple properties within the same o[...]",
          "items": {
            "type": "string"
          }
        }
      },
      "type": "object",
      "description": "The options for an object."
    },
    "TimestampPropertyOptions": {
      "id": "TimestampPropertyOptions",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the timestamp should be used as a search operator.",
          "$ref": "TimestampOperatorOptions"
        }
      },
      "type": "object",
      "description": "The options for timestamp properties."
    },
    "QuerySuggestion": {
      "id": "QuerySuggestion",
      "properties": {
        "lastQueryTime": {
          "type": "string",
          "description": "Last query time of the suggestion for query history suggestions.",
          "format": "google-datetime"
        },
        "sourceCorpus": {
          "enum": [
            "SOURCE_CORPUS_UNSPECIFIED",
            "GMAIL",
            "DRIVE",
            "CHAT",
            "CALENDAR"
          ],
          "type": "string",
          "enumDescriptions": [
            "Source corpus is unspecified.",
            "Source corpus is Gmail.",
            "Source corpus is Drive.",
            "Source corpus is Chat.",
            "Source corpus is Calendar."
          ],
          "description": "Source corpus of the suggestion."
        }
      },
      "type": "object"
    },
    "EnterpriseTopazFrontendTeamsPersonCorePhoneNumber": {
      "id": "EnterpriseTopazFrontendTeamsPersonCorePhoneNumber",
      "properties": {
        "phoneUrl": {
          "description": "Phone number URL",
          "$ref": "SafeUrlProto"
        },
        "type": {
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "",
            ""
          ],
          "enum": [
            "UNKNOWN",
            "MOBILE",
            "OFFICE",
            "OTHER"
          ]
        },
        "phoneNumber": {
          "description": "Phone number in no particular format (as comes from the Focus profile).",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickAgendaGroupCardProto": {
      "type": "object",
      "id": "EnterpriseTopazSidekickAgendaGroupCardProto",
      "properties": {
        "currentAgendaItem": {
          "$ref": "EnterpriseTopazSidekickAgendaItem"
        },
        "context": {
          "$ref": "EnterpriseTopazSidekickAgendaGroupCardProtoContext"
        },
        "agendaItem": {
          "type": "array",
          "items": {
            "$ref": "EnterpriseTopazSidekickAgendaItem"
          }
        }
      }
    },
    "Schema": {
      "description": "The schema definition for a data source.",
      "type": "object",
      "id": "Schema",
      "properties": {
        "objectDefinitions": {
          "items": {
            "$ref": "ObjectDefinition"
          },
          "description": "The list of top-level objects for the data source. The maximum number of elements is 10.",
          "type": "array"
        },
        "operationIds": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "IDs of the Long Running Operations (LROs) currently running for this schema. After modifying the schema, wait for operations to complete before indexing additional content."
        }
      }
    },
    "UserActivity": {
      "id": "UserActivity",
      "properties": {
        "queryActivity": {
          "description": "Contains data which needs to be logged/removed.",
          "$ref": "QueryActivity"
        }
      },
      "type": "object",
      "description": "User's single or bulk query activity. This can be a logging query or deletion query."
    },
    "SafeHtmlProto": {
      "id": "SafeHtmlProto",
      "properties": {
        "privateDoNotAccessOrElseSafeHtmlWrappedValue": {
          "description": "IMPORTANT: Never set or read this field, even from tests, it is private. See documentation at the top of .proto file for programming language packages with which to create or read this message.",
          "type": "string"
        }
      },
      "type": "object",
      "description": "IMPORTANT: It is unsafe to accept this message from an untrusted source, since it's trivial for an attacker to forge serialized messages that don't fulfill the type's safety contract -- for example, it could contain attacker controlled script. A system which receives a SafeHtmlProto implicitly trusts the producer of the SafeHtmlProto. So, it's generally safe to return this message in RPC responses, but generally unsafe to accept it in RPC requests."
    },
    "FacetOptions": {
      "description": "Specifies operators to return facet results for. There will be one FacetResult for every source_name/object_type/operator_name combination.",
      "id": "FacetOptions",
      "properties": {
        "operatorName": {
          "description": "The name of the operator chosen for faceting. @see cloudsearch.SchemaPropertyOptions",
          "type": "string"
        },
        "sourceName": {
          "description": "Source name to facet on. Format: datasources/{source_id} If empty, all data sources will be used.",
          "type": "string"
        },
        "objectType": {
          "description": "If object_type is set, only those objects of that type will be used to compute facets. If empty, then all objects will be used to compute facets.",
          "type": "string"
        },
        "numFacetBuckets": {
          "description": "Maximum number of facet buckets that should be returned for this facet. Defaults to 10. Maximum value is 100.",
          "format": "int32",
          "type": "integer"
        },
        "integerFacetingOptions": {
          "description": "If set, describes integer faceting options for the given integer property. The corresponding integer property in the schema should be marked isFacetable. The number of buckets returned would be minimum of this and num_facet_buckets.",
          "$ref": "IntegerFacetingOptions"
        }
      },
      "type": "object"
    },
    "ValueFilter": {
      "type": "object",
      "id": "ValueFilter",
      "properties": {
        "operatorName": {
          "description": "The `operator_name` applied to the query, such as *price_greater_than*. The filter can work against both types of filters defined in the schema for your data source: 1. `operator_name`, where the query filters results by the property that matches the value. 2. `greater_than_operator_name` or `less_than_operator_name` in your schema. The query filters the results for the property values that are greater than or less than the supplied value in the query.",
          "type": "string"
        },
        "value": {
          "$ref": "Value",
          "description": "The value to be compared with."
        }
      }
    },
    "DataSource": {
      "type": "object",
      "id": "DataSource",
      "properties": {
        "indexingServiceAccounts": {
          "items": {
            "type": "string"
          },
          "description": "List of service accounts that have indexing access.",
          "type": "array"
        },
        "returnThumbnailUrls": {
          "description": "Can a user request to get thumbnail URI for Items indexed in this data source.",
          "type": "boolean"
        },
        "shortName": {
          "type": "string",
          "description": "A short name or alias for the source. This value will be used to match the 'source' operator. For example, if the short name is *<value>* then queries like *source:<value>* will only return results for this source. The value must be unique across all datasources. The value must only contain alphanumeric characters (a-zA-Z0-9). The value cannot start with 'google' and cannot be one of the following: mail, gmail, docs, drive, groups, sites, calendar, hangouts, gplus, keep[...]"
        },
        "itemsVisibility": {
          "items": {
            "$ref": "GSuitePrincipal"
          },
          "description": "This field restricts visibility to items at the datasource level. Items within the datasource are restricted to the union of users and groups included in this field. Note that, this does not ensure access to a specific item, as users need to have ACL permissions on the contained items. This ensures a high level access on the entire datasource, and that the individual items are not shared outside this visibility.",
          "type": "array"
        },
        "disableServing": {
          "description": "Disable serving any search or assist results.",
          "type": "boolean"
        },
        "displayName": {
          "description": "Required. Display name of the datasource The maximum length is 300 characters.",
          "type": "string"
        },
        "operationIds": {
          "description": "IDs of the Long Running Operations (LROs) currently running for this schema.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "disableModifications": {
          "type": "boolean",
          "description": "If true, sets the datasource to read-only mode. In read-only mode, the Indexing API rejects any requests to index or delete items in this source. Enabling read-only mode does not stop the processing of previously accepted data."
        },
        "name": {
          "description": "The name of the datasource resource. Format: datasources/{source_id}. The name is ignored when creating a datasource.",
          "type": "string"
        }
      },
      "description": "Datasource is a logical namespace for items to be indexed. All items must belong to a datasource. This is the prerequisite before items can be indexed into Cloud Search. "
    },
    "DisplayedProperty": {
      "id": "DisplayedProperty",
      "properties": {
        "propertyName": {
          "description": "The name of the top-level property as defined in a property definition for the object. If the name is not a defined property in the schema, an error is given when attempting to update the schema.",
          "type": "string"
        }
      },
      "type": "object",
      "description": "A reference to a top-level property within the object that should be displayed in search results. The values of the chosen properties is displayed in the search results along with the display label for that property if one is specified. If a display label is not specified, only the values is shown."
    },
    "ResetSearchApplicationRequest": {
      "type": "object",
      "id": "ResetSearchApplicationRequest",
      "properties": {
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      }
    },
    "ListSearchApplicationsResponse": {
      "id": "ListSearchApplicationsResponse",
      "properties": {
        "searchApplications": {
          "type": "array",
          "items": {
            "$ref": "SearchApplication"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        }
      },
      "type": "object"
    },
    "UpdateDataSourceRequest": {
      "id": "UpdateDataSourceRequest",
      "properties": {
        "source": {
          "$ref": "DataSource"
        },
        "updateMask": {
          "description": "Only applies to [`settings.datasources.patch`](https://developers.google.com/workspace/cloud-search/docs/reference/rest/v1/settings.datasources/patch). Update mask to control which fields to update. Example field paths: `name`, `displayName`. * If `update_mask` is non-empty, then only the fields specified in the `update_mask` are updated. * If you specify a field in the `update_mask`, but don't specify its value in the source, that field is cleared. * If the `update_mas[...]",
          "format": "google-fieldmask",
          "type": "string"
        },
        "debugOptions": {
          "$ref": "DebugOptions",
          "description": "Common debug options."
        }
      },
      "type": "object"
    },
    "DriveLocationRestrict": {
      "type": "object",
      "id": "DriveLocationRestrict",
      "properties": {
        "type": {
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "enum": [
            "UNSPECIFIED",
            "TRASHED",
            "STARRED"
          ]
        }
      },
      "description": "Drive location search restricts (e.g. \"is:starred\")."
    },
    "MapTile": {
      "type": "object",
      "id": "MapTile",
      "properties": {
        "tileY": {
          "description": "Map tile y coordinate",
          "format": "double",
          "type": "number"
        },
        "tileX": {
          "description": "Map tile x coordinate",
          "format": "double",
          "type": "number"
        },
        "imageUrl": {
          "$ref": "SafeUrlProto",
          "description": "URL to an image file containing an office layout of the user's location for their organization, if one is available. For google.com, this image is from Corp Campus Maps."
        }
      },
      "description": "Information used to render a map tile image in the proper location on a map."
    },
    "Item": {
      "id": "Item",
      "properties": {
        "content": {
          "$ref": "ItemContent",
          "description": "Item content to be indexed and made text searchable."
        },
        "status": {
          "description": "Status of the item. Output only field.",
          "$ref": "ItemStatus"
        },
        "structuredData": {
          "description": "The structured data for the item that should conform to a registered object definition in the schema for the data source.",
          "$ref": "ItemStructuredData"
        },
        "version": {
          "description": "Required. The indexing system stores the version from the datasource as a byte string and compares the Item version in the index to the version of the queued Item using lexical ordering. Cloud Search Indexing won't index or delete any queued item with a version value that is less than or equal to the version of the currently indexed item. The maximum length for this field is 1024 bytes. For information on how item version affects the deletion process, refer to [Handle r[...]",
          "format": "byte",
          "type": "string"
        },
        "payload": {
          "description": "Additional state connector can store for this item. The maximum length is 10000 bytes.",
          "format": "byte",
          "type": "string"
        },
        "itemType": {
          "type": "string",
          "enumDescriptions": [
            "",
            "An item that is indexed for the only purpose of serving information. These items cannot be referred in containerName or inheritAclFrom fields.",
            "An item that gets indexed and whose purpose is to supply other items with ACLs and/or contain other items.",
            "An item that does not get indexed, but otherwise has the same purpose as CONTAINER_ITEM."
          ],
          "enum": [
            "UNSPECIFIED",
            "CONTENT_ITEM",
            "CONTAINER_ITEM",
            "VIRTUAL_CONTAINER_ITEM"
          ],
          "description": "The type for this item."
        },
        "metadata": {
          "$ref": "ItemMetadata",
          "description": "The metadata information."
        },
        "acl": {
          "description": "Access control list for this item.",
          "$ref": "ItemAcl"
        },
        "queue": {
          "description": "Queue this item belongs to. The maximum length is 100 characters.",
          "type": "string"
        },
        "name": {
          "description": "The name of the Item. Format: datasources/{source_id}/items/{item_id} This is a required field. The maximum length is 1536 characters.",
          "type": "string"
        }
      },
      "type": "object",
      "description": "Represents a single object that is an item in the search index, such as a file, folder, or a database record."
    },
    "StructuredDataObject": {
      "description": "A structured data object consisting of named properties.",
      "id": "StructuredDataObject",
      "properties": {
        "properties": {
          "type": "array",
          "items": {
            "$ref": "NamedProperty"
          },
          "description": "The properties for the object. The maximum number of elements is 1000."
        }
      },
      "type": "object"
    },
    "DriveMimeTypeRestrict": {
      "description": "Drive mime-type search restricts (e.g. \"type:pdf\").",
      "type": "object",
      "id": "DriveMimeTypeRestrict",
      "properties": {
        "type": {
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            ""
          ],
          "enum": [
            "UNSPECIFIED",
            "PDF",
            "DOCUMENT",
            "PRESENTATION",
            "SPREADSHEET",
            "FORM",
            "DRAWING",
            "SCRIPT",
            "MAP",
            "IMAGE",
            "AUDIO",
            "VIDEO",
            "FOLDER",
            "ARCHIVE",
            "SITE"
          ]
        }
      }
    },
    "CustomerSearchApplicationStats": {
      "description": "Search application stats for a customer for the given date.",
      "type": "object",
      "id": "CustomerSearchApplicationStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "The date for which search application stats were calculated."
        },
        "count": {
          "description": "The count of search applications for the date.",
          "format": "int64",
          "type": "string"
        }
      }
    },
    "CustomerIndexStats": {
      "description": "Aggregation of items by status code as of the specified date.",
      "id": "CustomerIndexStats",
      "properties": {
        "date": {
          "description": "The date for which statistics were calculated.",
          "$ref": "Date"
        },
        "itemCountByStatus": {
          "type": "array",
          "items": {
            "$ref": "ItemCountByStatus"
          },
          "description": "Number of items aggregrated by status code."
        }
      },
      "type": "object"
    },
    "SuggestRequest": {
      "description": "Request of suggest API.",
      "id": "SuggestRequest",
      "properties": {
        "requestOptions": {
          "description": "Request options, such as the search application and user timezone.",
          "$ref": "RequestOptions"
        },
        "query": {
          "type": "string",
          "description": "Partial query for which autocomplete suggestions will be shown. For example, if the query is \"sea\", then the server might return \"season\", \"search\", \"seagull\" and so on."
        },
        "dataSourceRestrictions": {
          "description": "The sources to use for suggestions. If not specified, the data sources are taken from the current search application. NOTE: Suggestions are only supported for the following sources: * Third-party data sources * PredefinedSource.PERSON * PredefinedSource.GOOGLE_DRIVE",
          "items": {
            "$ref": "DataSourceRestriction"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "DateValues": {
      "type": "object",
      "id": "DateValues",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "$ref": "Date"
          }
        }
      },
      "description": "List of date values."
    },
    "IndexItemOptions": {
      "type": "object",
      "id": "IndexItemOptions",
      "properties": {
        "allowUnknownGsuitePrincipals": {
          "description": "Specifies if the index request should allow Google Workspace principals that do not exist or are deleted.",
          "type": "boolean"
        }
      }
    },
    "InitializeCustomerRequest": {
      "description": "Request message for `InitializeCustomer` method.",
      "type": "object",
      "id": "InitializeCustomerRequest",
      "properties": {}
    },
    "UnmappedIdentity": {
      "id": "UnmappedIdentity",
      "properties": {
        "externalIdentity": {
          "description": "The resource name for an external user.",
          "$ref": "Principal"
        },
        "resolutionStatusCode": {
          "enum": [
            "CODE_UNSPECIFIED",
            "NOT_FOUND",
            "IDENTITY_SOURCE_NOT_FOUND",
            "IDENTITY_SOURCE_MISCONFIGURED",
            "TOO_MANY_MAPPINGS_FOUND",
            "INTERNAL_ERROR"
          ],
          "type": "string",
          "enumDescriptions": [
            "Input-only value. Used to list all unmapped identities regardless of status.",
            "The unmapped identity was not found in IDaaS, and needs to be provided by the user.",
            "The identity source associated with the identity was either not found or deleted.",
            "IDaaS does not understand the identity source, probably because the schema was modified in a non compatible way.",
            "The number of users associated with the external identity is too large.",
            "Internal error."
          ],
          "description": "The resolution status for the external identity."
        }
      },
      "type": "object"
    },
    "PushItemRequest": {
      "id": "PushItemRequest",
      "properties": {
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "item": {
          "$ref": "PushItem",
          "description": "Item to push onto the queue."
        },
        "connectorName": {
          "type": "string",
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        }
      },
      "type": "object"
    },
    "Person": {
      "type": "object",
      "id": "Person",
      "properties": {
        "name": {
          "type": "string",
          "description": "The resource name of the person to provide information about. See [`People.get`](https://developers.google.com/people/api/rest/v1/people/get) from the Google People API."
        },
        "phoneNumbers": {
          "description": "The person's phone numbers",
          "items": {
            "$ref": "PhoneNumber"
          },
          "type": "array"
        },
        "emailAddresses": {
          "type": "array",
          "description": "The person's email addresses",
          "items": {
            "$ref": "EmailAddress"
          }
        },
        "personNames": {
          "type": "array",
          "description": "The person's name",
          "items": {
            "$ref": "Name"
          }
        },
        "obfuscatedId": {
          "type": "string",
          "description": "Obfuscated ID of a person."
        },
        "photos": {
          "description": "A person's read-only photo. A picture shown next to the person's name to help others recognize the person in search results.",
          "items": {
            "$ref": "Photo"
          },
          "type": "array"
        }
      },
      "description": "Object to represent a person."
    },
    "RestrictItem": {
      "description": "Information relevant only to a restrict entry. NextId: 12",
      "type": "object",
      "id": "RestrictItem",
      "properties": {
        "driveLocationRestrict": {
          "$ref": "DriveLocationRestrict"
        },
        "searchOperator": {
          "type": "string",
          "description": "The search restrict (e.g. \"after:2017-09-11 before:2017-09-12\")."
        },
        "driveTimeSpanRestrict": {
          "$ref": "DriveTimeSpanRestrict"
        },
        "driveMimeTypeRestrict": {
          "$ref": "DriveMimeTypeRestrict",
          "description": "Drive Types."
        },
        "driveFollowUpRestrict": {
          "$ref": "DriveFollowUpRestrict"
        }
      }
    },
    "QueryItem": {
      "id": "QueryItem",
      "properties": {
        "isSynthetic": {
          "type": "boolean",
          "description": "True if the text was generated by means other than a previous user search."
        }
      },
      "type": "object",
      "description": "Information relevant only to a query entry."
    },
    "QueryCountByStatus": {
      "id": "QueryCountByStatus",
      "properties": {
        "statusCode": {
          "description": "This represents the http status code.",
          "format": "int32",
          "type": "integer"
        },
        "count": {
          "type": "string",
          "format": "int64"
        }
      },
      "type": "object"
    },
    "Metadata": {
      "type": "object",
      "id": "Metadata",
      "properties": {
        "source": {
          "$ref": "Source",
          "description": "The named source for the result, such as Gmail."
        },
        "createTime": {
          "description": "The creation time for this document or object in the search result.",
          "format": "google-datetime",
          "type": "string"
        },
        "displayOptions": {
          "$ref": "ResultDisplayMetadata",
          "description": "Options that specify how to display a structured data search result."
        },
        "owner": {
          "description": "Owner (usually creator) of the document or object of the search result.",
          "$ref": "Person"
        },
        "objectType": {
          "description": "Object type of the search result.",
          "type": "string"
        },
        "updateTime": {
          "description": "The last modified date for the object in the search result. If not set in the item, the value returned here is empty. When `updateTime` is used for calculating freshness and is not set, this value defaults to 2 years from the current time.",
          "format": "google-datetime",
          "type": "string"
        },
        "fields": {
          "type": "array",
          "description": "Indexed fields in structured data, returned as a generic named property.",
          "items": {
            "$ref": "NamedProperty"
          }
        },
        "mimeType": {
          "type": "string",
          "description": "Mime type of the search result."
        },
        "thumbnailUrl": {
          "description": "The thumbnail URL of the result.",
          "type": "string"
        }
      },
      "description": "Metadata of a matched search result."
    },
    "PeoplePromotionCard": {
      "type": "object",
      "id": "PeoplePromotionCard",
      "properties": {
        "people": {
          "type": "array",
          "items": {
            "$ref": "PersonCore"
          }
        }
      }
    },
    "CustomerSettings": {
      "type": "object",
      "id": "CustomerSettings",
      "properties": {
        "vpcSettings": {
          "description": "VPC SC settings for the customer. If update_mask is empty then this field will be updated based on UpdateCustomerSettings request.",
          "$ref": "VPCSettings"
        },
        "auditLoggingSettings": {
          "description": "Audit Logging settings for the customer. If update_mask is empty then this field will be updated based on UpdateCustomerSettings request.",
          "$ref": "AuditLoggingSettings"
        }
      },
      "description": "Represents settings at a customer level."
    },
    "SearchResponse": {
      "id": "SearchResponse",
      "properties": {
        "resultCountEstimate": {
          "description": "The estimated result count for this query.",
          "format": "int64",
          "type": "string"
        },
        "debugInfo": {
          "$ref": "ResponseDebugInfo",
          "description": "Debugging information about the response."
        },
        "structuredResults": {
          "items": {
            "$ref": "StructuredResult"
          },
          "description": "Structured results for the user query. These results are not counted against the page_size.",
          "type": "array"
        },
        "queryInterpretation": {
          "$ref": "QueryInterpretation",
          "description": "Query interpretation result for user query. Empty if query interpretation is disabled."
        },
        "facetResults": {
          "items": {
            "$ref": "FacetResult"
          },
          "description": "Repeated facet results.",
          "type": "array"
        },
        "results": {
          "description": "Results from a search query.",
          "items": {
            "$ref": "SearchResult"
          },
          "type": "array"
        },
        "resultCounts": {
          "description": "Expanded result count information.",
          "$ref": "ResultCounts"
        },
        "hasMoreResults": {
          "description": "Whether there are more search results matching the query.",
          "type": "boolean"
        },
        "resultCountExact": {
          "type": "string",
          "description": "The exact result count for this query.",
          "format": "int64"
        },
        "errorInfo": {
          "$ref": "ErrorInfo",
          "description": "Error information about the response."
        },
        "spellResults": {
          "items": {
            "$ref": "SpellResult"
          },
          "description": "Suggested spelling for the query.",
          "type": "array"
        }
      },
      "type": "object",
      "description": "The search API response. NEXT ID: 19"
    },
    "SearchApplicationUserStats": {
      "type": "object",
      "id": "SearchApplicationUserStats",
      "properties": {
        "oneDayActiveUsersCount": {
          "type": "string",
          "description": "The count of unique active users in the past one day",
          "format": "int64"
        },
        "date": {
          "$ref": "Date",
          "description": "The date for which session stats were calculated. Stats calculated on the next day close to midnight are returned."
        },
        "sevenDaysActiveUsersCount": {
          "type": "string",
          "description": "The count of unique active users in the past seven days",
          "format": "int64"
        },
        "thirtyDaysActiveUsersCount": {
          "type": "string",
          "description": "The count of unique active users in the past thirty days",
          "format": "int64"
        }
      }
    },
    "EnterpriseTopazSidekickRankingParams": {
      "description": "Ranking params.",
      "type": "object",
      "id": "EnterpriseTopazSidekickRankingParams",
      "properties": {
        "endTimeMs": {
          "description": "The end-time that this object will expect to occur. If the type is marked as FIXED, then this end-time will persist after bidding. If the type is marked as FLEXIBLE, this field is NOT expected to be filled and will be filled in after it has won a bid. Expected to be set when type is set to FIXED.",
          "format": "uint64",
          "type": "string"
        },
        "spanMs": {
          "type": "string",
          "description": "The span that this card will take in the stream Expected to be set when type is set to FLEXIBLE.",
          "format": "uint64"
        },
        "startTimeMs": {
          "type": "string",
          "description": "The start-time that this object will bid-for If the type is marked as FIXED, then this start-time will persist after bidding. If the type is marked as FLEXIBLE, then it will occur at the given time or sometime after the requested time. Expected to be set for all types.",
          "format": "uint64"
        },
        "score": {
          "type": "number",
          "description": "The score of the card to be used to break priority-ties",
          "format": "float"
        },
        "type": {
          "description": "The packing type of this object.",
          "type": "string",
          "enumDescriptions": [
            "Fixed, i.e., the card is time sensitive.",
            "Flexible, i.e., the card is not time sensitive."
          ],
          "enum": [
            "FIXED",
            "FLEXIBLE"
          ]
        },
        "priority": {
          "type": "string",
          "enumDescriptions": [
            "Unknown (default).",
            "Critical.",
            "Important.",
            "High.",
            "Normal.",
            "Best effort."
          ],
          "enum": [
            "UNKNOWN",
            "CRITICAL",
            "IMPORTANT",
            "HIGH",
            "NORMAL",
            "BEST_EFFORT"
          ],
          "description": "The priority to determine between objects that have the same start_time_ms The lower-value of priority == ranked higher. Max-priority = 0. Expected to be set for all types."
        }
      }
    },
    "ItemStatus": {
      "description": "This contains item's status and any errors.",
      "id": "ItemStatus",
      "properties": {
        "code": {
          "type": "string",
          "enumDescriptions": [
            "Input-only value. Used with Items.list to list all items in the queue, regardless of status.",
            "Error encountered by Cloud Search while processing this item. Details of the error are in repositoryError.",
            "Item has been modified in the repository, and is out of date with the version previously accepted into Cloud Search.",
            "Item is known to exist in the repository, but is not yet accepted by Cloud Search. An item can be in this state when Items.push has been called for an item of this name that did not exist previously.",
            "API has accepted the up-to-date data of this item."
          ],
          "enum": [
            "CODE_UNSPECIFIED",
            "ERROR",
            "MODIFIED",
            "NEW_ITEM",
            "ACCEPTED"
          ],
          "description": "Status code."
        },
        "processingErrors": {
          "type": "array",
          "description": "Error details in case the item is in ERROR state.",
          "items": {
            "$ref": "ProcessingError"
          }
        },
        "repositoryErrors": {
          "description": "Repository error reported by connector.",
          "items": {
            "$ref": "RepositoryError"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "PollItemsResponse": {
      "id": "PollItemsResponse",
      "properties": {
        "items": {
          "items": {
            "$ref": "Item"
          },
          "description": "Set of items from the queue available for connector to process. These items have the following subset of fields populated: version metadata.hash structured_data.hash content.hash payload status queue",
          "type": "array"
        }
      },
      "type": "object"
    },
    "IntegerValues": {
      "description": "List of integer values.",
      "id": "IntegerValues",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "format": "int64",
            "type": "string"
          }
        }
      },
      "type": "object"
    },
    "QueryActivity": {
      "description": "Details about a user's query activity.",
      "id": "QueryActivity",
      "properties": {
        "query": {
          "type": "string",
          "description": "User input query to be logged/removed."
        }
      },
      "type": "object"
    },
    "DriveFollowUpRestrict": {
      "id": "DriveFollowUpRestrict",
      "properties": {
        "type": {
          "type": "string",
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "enum": [
            "UNSPECIFIED",
            "FOLLOWUP_SUGGESTIONS",
            "FOLLOWUP_ACTION_ITEMS"
          ]
        }
      },
      "type": "object",
      "description": "Drive follow-up search restricts (e.g. \"followup:suggestions\")."
    },
    "FacetBucket": {
      "description": "A bucket in a facet is the basic unit of operation. A bucket can comprise either a single value OR a contiguous range of values, depending on the type of the field bucketed. FacetBucket is currently used only for returning the response object.",
      "type": "object",
      "id": "FacetBucket",
      "properties": {
        "count": {
          "description": "Number of results that match the bucket value. Counts are only returned for searches when count accuracy is ensured. Cloud Search does not guarantee facet counts for any query and facet counts might be present only intermittently, even for identical queries. Do not build dependencies on facet count existence; instead use facet ount percentages which are always returned.",
          "format": "int32",
          "type": "integer"
        },
        "value": {
          "$ref": "Value"
        },
        "percentage": {
          "type": "integer",
          "description": "Percent of results that match the bucket value. The returned value is between (0-100], and is rounded down to an integer if fractional. If the value is not explicitly returned, it represents a percentage value that rounds to 0. Percentages are returned for all searches, but are an estimate. Because percentages are always returned, you should render percentages instead of counts.",
          "format": "int32"
        },
        "filter": {
          "description": "Filter to be passed in the search request if the corresponding bucket is selected.",
          "$ref": "Filter"
        }
      }
    },
    "ResultDisplayLine": {
      "type": "object",
      "id": "ResultDisplayLine",
      "properties": {
        "fields": {
          "type": "array",
          "items": {
            "$ref": "ResultDisplayField"
          }
        }
      },
      "description": "The collection of fields that make up a displayed line"
    },
    "ThirdPartyGenericCard": {
      "id": "ThirdPartyGenericCard",
      "properties": {
        "isDismissible": {
          "description": "Whether the card can be dismissed.",
          "type": "boolean"
        },
        "context": {
          "description": "[Required] Context where the card should be triggered.",
          "$ref": "Context"
        },
        "category": {
          "description": "Category that the card belongs to.",
          "type": "string"
        },
        "cardId": {
          "type": "string",
          "description": "Unique identifier for the card."
        },
        "priority": {
          "type": "integer",
          "description": "Priority of the card, where 0 is the highest priority.",
          "format": "int32"
        },
        "content": {
          "$ref": "Content",
          "description": "[Required] Card content."
        }
      },
      "type": "object"
    },
    "EmailAddress": {
      "description": "A person's email address.",
      "id": "EmailAddress",
      "properties": {
        "primary": {
          "description": "Indicates if this is the user's primary email. Only one entry can be marked as primary.",
          "type": "boolean"
        },
        "customType": {
          "type": "string",
          "description": "If the value of type is custom, this property contains the custom type string."
        },
        "type": {
          "type": "string",
          "description": "The type of the email account. Acceptable values are: \"custom\", \"home\", \"other\", \"work\"."
        },
        "emailAddress": {
          "description": "The email address.",
          "type": "string"
        },
        "emailUrl": {
          "type": "string",
          "description": "The URL to send email."
        }
      },
      "type": "object"
    },
    "Photo": {
      "description": "A person's photo.",
      "id": "Photo",
      "properties": {
        "url": {
          "description": "The URL of the photo.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickGap": {
      "type": "object",
      "id": "EnterpriseTopazSidekickGap",
      "properties": {
        "startTime": {
          "type": "string",
          "description": "Localized time string in the format:(Locale CZ) 8:30 odp."
        },
        "startTimeMs": {
          "format": "uint64",
          "type": "string"
        },
        "displayRemainingTime": {
          "description": "Localized time string in the format: 1 hour 15 minutes",
          "type": "string"
        },
        "endTimeMs": {
          "format": "uint64",
          "type": "string"
        },
        "remainingTime": {
          "format": "google-duration",
          "type": "string"
        },
        "endTime": {
          "type": "string",
          "description": "Localized time string in the format:(Locale CZ) 8:30 odp."
        }
      }
    },
    "BooleanPropertyOptions": {
      "type": "object",
      "id": "BooleanPropertyOptions",
      "properties": {
        "operatorOptions": {
          "description": "If set, describes how the boolean should be used as a search operator.",
          "$ref": "BooleanOperatorOptions"
        }
      },
      "description": "The options for boolean properties."
    },
    "TextPropertyOptions": {
      "id": "TextPropertyOptions",
      "properties": {
        "retrievalImportance": {
          "$ref": "RetrievalImportance",
          "description": "Indicates the search quality importance of the tokens within the field when used for retrieval."
        },
        "operatorOptions": {
          "description": "If set, describes how the property should be used as a search operator.",
          "$ref": "TextOperatorOptions"
        }
      },
      "type": "object",
      "description": "The options for text properties."
    },
    "EnterpriseTopazSidekickGetAndKeepAheadCardProto": {
      "id": "EnterpriseTopazSidekickGetAndKeepAheadCardProto",
      "properties": {
        "mentionedDocuments": {
          "$ref": "EnterpriseTopazSidekickDocumentPerCategoryList"
        },
        "sharedDocuments": {
          "$ref": "EnterpriseTopazSidekickDocumentPerCategoryList"
        },
        "declinedEvents": {
          "$ref": "EnterpriseTopazSidekickGetAndKeepAheadCardProtoDeclinedEvents"
        }
      },
      "type": "object",
      "description": "Get and keep ahead card"
    },
    "EnterpriseTopazSidekickCardMetadata": {
      "type": "object",
      "id": "EnterpriseTopazSidekickCardMetadata",
      "properties": {
        "chronology": {
          "description": "Chronology.",
          "type": "string",
          "enumDescriptions": [
            "Unknown chronology (default).",
            "Past.",
            "Recently past.",
            "Present.",
            "Near future.",
            "Future."
          ],
          "enum": [
            "UNKNOWN",
            "PAST",
            "RECENTLY_PAST",
            "PRESENT",
            "NEAR_FUTURE",
            "FUTURE"
          ]
        },
        "renderMode": {
          "description": "Render mode.",
          "enum": [
            "UNKNOWN_RENDER",
            "COLLAPSED",
            "EXPANDED"
          ],
          "type": "string",
          "enumDescriptions": [
            "Unknown mode (default).",
            "Collapsed.",
            "Expanded."
          ]
        },
        "cardId": {
          "type": "string",
          "description": "An ID to identify the card and match actions to it. Be thoughtful of new card IDs since actions will be associated to that ID. E.g., if two card IDs collide, the system will think that the actions have been applied to the same card. Similarly, if EAS can return multiple cards of the same type (e.g., Meetings), ensure that the card_id identifies a given instance of the card so that, e.g., dismissals only affect the dismissed card as opposed to affecting all meeting cards[...]"
        },
        "debugInfo": {
          "type": "string",
          "description": "Debug info (only reported if request's debug_level > 0)."
        },
        "cardCategory": {
          "type": "string",
          "enumDescriptions": [
            "Let MSCR decide how this card should be packed. Most cards should choose this type. This type should largely be considered equivalent to ANSWER. However, this is not guaranteed to be the case as the request to MSCR may override the static configuration.",
            "This card should be rendered as an answer card.",
            "This card should be rendered as a knowledge card (a non-organic result).",
            "This card should be rendered in the Homepage."
          ],
          "enum": [
            "DEFAULT",
            "ANSWER",
            "KNOWLEDGE",
            "HOMEPAGE"
          ],
          "description": "Declares a preference for how this card should be packed in MSCR. All cards in a response must correspond to a single category. As a result, cards may be dropped from the response if this field is set. Any card that does not match the category of the card with the highest priority in the response will be dropped."
        },
        "nlpMetadata": {
          "$ref": "EnterpriseTopazSidekickNlpMetadata",
          "description": "Information about the NLP done to get the card."
        },
        "rankingParams": {
          "description": "Ranking params.",
          "$ref": "EnterpriseTopazSidekickRankingParams"
        }
      },
      "description": "Card metadata."
    },
    "ContextAttribute": {
      "description": "A named attribute associated with an item which can be used for influencing the ranking of the item based on the context in the request.",
      "type": "object",
      "id": "ContextAttribute",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the attribute. It should not be empty. The maximum length is 32 characters. The name must start with a letter and can only contain letters (A-Z, a-z) or numbers (0-9). The name will be normalized (lower-cased) before being matched."
        },
        "values": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Text values of the attribute. The maximum number of elements is 10. The maximum length of an element in the array is 32 characters. The value will be normalized (lower-cased) before being matched."
        }
      }
    },
    "GetSearchApplicationQueryStatsResponse": {
      "id": "GetSearchApplicationQueryStatsResponse",
      "properties": {
        "stats": {
          "type": "array",
          "description": "Query stats per date for a search application.",
          "items": {
            "$ref": "SearchApplicationQueryStats"
          }
        },
        "totalQueryCount": {
          "type": "string",
          "description": "Total successful query count (status code 200) for the given date range.",
          "format": "int64"
        }
      },
      "type": "object",
      "description": "Response format for getting query stats for a search application between given dates."
    },
    "EnterpriseTopazSidekickFindMeetingTimeCardProto": {
      "description": "Response to find meeting time among a set of people.",
      "id": "EnterpriseTopazSidekickFindMeetingTimeCardProto",
      "properties": {
        "skippedInvitees": {
          "description": "Invitees that have been skipped in the computation, most likely because they are groups.",
          "items": {
            "$ref": "EnterpriseTopazSidekickPerson"
          },
          "type": "array"
        },
        "scheduledMeeting": {
          "$ref": "EnterpriseTopazSidekickScheduledMeeting",
          "description": "Details about the scheduled meeting, if one exists."
        },
        "commonAvailableTimeSlots": {
          "type": "array",
          "description": "Slots when all attendees have availability.",
          "items": {
            "$ref": "EnterpriseTopazSidekickTimeSlot"
          }
        },
        "requester": {
          "description": "Requester.",
          "$ref": "EnterpriseTopazSidekickPerson"
        },
        "invitees": {
          "type": "array",
          "description": "Invitees to the event.",
          "items": {
            "$ref": "EnterpriseTopazSidekickPerson"
          }
        },
        "timezoneId": {
          "description": "Timezone ID.",
          "type": "string"
        },
        "timeBoundaries": {
          "description": "Min and max timestamp used to find a common available timeslot.",
          "$ref": "EnterpriseTopazSidekickTimeSlot"
        }
      },
      "type": "object"
    },
    "TextOperatorOptions": {
      "description": "Used to provide a search operator for text properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "type": "object",
      "id": "TextOperatorOptions",
      "properties": {
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the text property. For example, if operatorName is *subject* and the property's name is *subjectLine*, then queries like *subject:<value>* show results only where the value of the property named *subjectLine* matches *<value>*. By contrast, a search that uses the same *<value>* without an operator returns all items where *<value>* matches the value of any text properties or text within the content fie[...]",
          "type": "string"
        },
        "exactMatchWithOperator": {
          "type": "boolean",
          "description": "If true, the text value is tokenized as one atomic value in operator searches and facet matches. For example, if the operator name is \"genre\" and the value is \"science-fiction\" the query restrictions \"genre:science\" and \"genre:fiction\" doesn't match the item; \"genre:science-fiction\" does. Text value matching is case-sensitive and does not remove special characters. If false, the text is tokenized. For example, if the value is \"science-fiction\" the queries \"[...]"
        }
      }
    },
    "SearchApplicationSessionStats": {
      "id": "SearchApplicationSessionStats",
      "properties": {
        "date": {
          "$ref": "Date",
          "description": "The date for which session stats were calculated. Stats are calculated on the following day, close to midnight PST, and then returned."
        },
        "searchSessionsCount": {
          "description": "The count of search sessions on the day",
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickScheduledMeeting": {
      "description": "Details about scheduled meetings.",
      "id": "EnterpriseTopazSidekickScheduledMeeting",
      "properties": {
        "meetingTitle": {
          "description": "The meeting title.",
          "type": "string"
        },
        "meetingTime": {
          "description": "The meeting time slot.",
          "$ref": "EnterpriseTopazSidekickTimeSlot"
        },
        "meetingLocation": {
          "description": "The meeting location.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "RetrievalImportance": {
      "id": "RetrievalImportance",
      "properties": {
        "importance": {
          "description": "Indicates the ranking importance given to property when it is matched during retrieval. Once set, the token importance of a property cannot be changed.",
          "enum": [
            "DEFAULT",
            "HIGHEST",
            "HIGH",
            "LOW",
            "NONE"
          ],
          "type": "string",
          "enumDescriptions": [
            "Treat the match like a body text match.",
            "Treat the match like a match against title of the item.",
            "Treat the match with higher importance than body text.",
            "Treat the match with lower importance than body text.",
            "Do not match against this field during retrieval. The property can still be used for operator matching, faceting, and suggest if desired."
          ]
        }
      },
      "type": "object"
    },
    "QueryInterpretationOptions": {
      "id": "QueryInterpretationOptions",
      "properties": {
        "enableVerbatimMode": {
          "description": "Enable this flag to turn off all internal optimizations like natural language (NL) interpretation of queries, supplemental result retrieval, and usage of synonyms including custom ones. Nl interpretation will be disabled if either one of the two flags is true.",
          "type": "boolean"
        },
        "disableSupplementalResults": {
          "description": "Use this flag to disable supplemental results for a query. Supplemental results setting chosen at SearchApplication level will take precedence if set to True.",
          "type": "boolean"
        },
        "disableNlInterpretation": {
          "type": "boolean",
          "description": "Flag to disable natural language (NL) interpretation of queries. Default is false, Set to true to disable natural language interpretation. NL interpretation only applies to predefined datasources."
        }
      },
      "type": "object",
      "description": "Options to interpret user query."
    },
    "Content": {
      "id": "Content",
      "properties": {
        "actions": {
          "description": "[Optional] Actions for this card.",
          "items": {
            "$ref": "Action"
          },
          "type": "array"
        },
        "title": {
          "description": "[Optional] Title of the card.",
          "$ref": "BackgroundColoredText"
        },
        "subtitle": {
          "description": "[Optional] Subtitle of the card.",
          "$ref": "BackgroundColoredText"
        },
        "description": {
          "$ref": "SafeHtmlProto",
          "description": "[Optional] Description of the card."
        }
      },
      "type": "object"
    },
    "StartUploadItemRequest": {
      "id": "StartUploadItemRequest",
      "properties": {
        "connectorName": {
          "type": "string",
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}"
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        }
      },
      "type": "object",
      "description": "Start upload file request."
    },
    "EnterpriseTopazSidekickPersonProfileCard": {
      "id": "EnterpriseTopazSidekickPersonProfileCard",
      "properties": {
        "subject": {
          "description": "The subject of the card.",
          "$ref": "EnterpriseTopazSidekickCommonPerson"
        },
        "relatedPeople": {
          "type": "array",
          "items": {
            "$ref": "EnterpriseTopazSidekickPersonProfileCardRelatedPeople"
          }
        }
      },
      "type": "object"
    },
    "ObjectValues": {
      "description": "List of object values.",
      "id": "ObjectValues",
      "properties": {
        "values": {
          "type": "array",
          "items": {
            "$ref": "StructuredDataObject"
          }
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickPeopleAnswerPersonAnswerCard": {
      "type": "object",
      "id": "EnterpriseTopazSidekickPeopleAnswerPersonAnswerCard",
      "properties": {
        "answer": {
          "description": "List of answers.",
          "deprecated": true,
          "items": {
            "$ref": "SafeHtmlProto"
          },
          "type": "array"
        },
        "header": {
          "$ref": "EnterpriseTopazSidekickPeopleAnswerPeopleAnswerCardHeader",
          "description": "The header to display for the card."
        },
        "statusMessage": {
          "description": "Localized user friendly message to display to the user in the case of missing data or an error.",
          "type": "string"
        },
        "disambiguationInfo": {
          "description": "Disambiguation information.",
          "$ref": "EnterpriseTopazSidekickPeopleAnswerDisambiguationInfo"
        },
        "answerText": {
          "$ref": "EnterpriseTopazSidekickAnswerAnswerList",
          "description": "List of answers."
        },
        "responseStatus": {
          "description": "The response status.",
          "enum": [
            "UNKNOWN",
            "SUCCESS",
            "MISSING_PERSON",
            "MISSING_DATA"
          ],
          "type": "string",
          "enumDescriptions": [
            "Unknown.",
            "Success.",
            "No such person was found in the user's domain.",
            "A person was found to match the query, but an answer could not be obtained."
          ]
        },
        "subject": {
          "$ref": "EnterpriseTopazSidekickCommonPerson",
          "description": "The profile of the person that was the subject of the query."
        }
      },
      "description": "An answer card for a single person."
    },
    "DebugOptions": {
      "id": "DebugOptions",
      "properties": {
        "enableDebugging": {
          "description": "If you are asked by Google to help with debugging, set this field. Otherwise, ignore this field.",
          "type": "boolean"
        }
      },
      "type": "object",
      "description": "Shared request debug options for all cloudsearch RPC methods."
    },
    "CustomerSessionStats": {
      "id": "CustomerSessionStats",
      "properties": {
        "date": {
          "description": "The date for which session stats were calculated. Stats are calculated on the following day, close to midnight PST, and then returned.",
          "$ref": "Date"
        },
        "searchSessionsCount": {
          "type": "string",
          "description": "The count of search sessions on the day",
          "format": "int64"
        }
      },
      "type": "object"
    },
    "ListItemsResponse": {
      "id": "ListItemsResponse",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "Item"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        }
      },
      "type": "object"
    },
    "EnterpriseTopazSidekickCommonPersonBirthday": {
      "id": "EnterpriseTopazSidekickCommonPersonBirthday",
      "properties": {
        "value": {
          "type": "string",
          "description": "Unstructured birthday."
        }
      },
      "type": "object"
    },
    "SearchItemsByViewUrlResponse": {
      "id": "SearchItemsByViewUrlResponse",
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "Item"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "Token to retrieve the next page of results, or empty if there are no more results in the list."
        }
      },
      "type": "object"
    },
    "IndexItemRequest": {
      "type": "object",
      "id": "IndexItemRequest",
      "properties": {
        "connectorName": {
          "description": "The name of connector making this call. Format: datasources/{source_id}/connectors/{ID}",
          "type": "string"
        },
        "indexItemOptions": {
          "$ref": "IndexItemOptions"
        },
        "mode": {
          "type": "string",
          "enumDescriptions": [
            "The priority is not specified in the update request. Leaving priority unspecified results in an update failure.",
            "For real-time updates.",
            "For changes that are executed after the response is sent back to the caller."
          ],
          "enum": [
            "UNSPECIFIED",
            "SYNCHRONOUS",
            "ASYNCHRONOUS"
          ],
          "description": "Required. The RequestMode for this request."
        },
        "debugOptions": {
          "description": "Common debug options.",
          "$ref": "DebugOptions"
        },
        "item": {
          "description": "The name of the item. Format: datasources/{source_id}/items/{item_id}",
          "$ref": "Item"
        }
      }
    },
    "ItemAcl": {
      "description": "Access control list information for the item. For more information see [Map ACLs](https://developers.google.com/workspace/cloud-search/docs/guides/acls).",
      "id": "ItemAcl",
      "properties": {
        "aclInheritanceType": {
          "description": "Sets the type of access rules to apply when an item inherits its ACL from a parent. This should always be set in tandem with the inheritAclFrom field. Also, when the inheritAclFrom field is set, this field should be set to a valid AclInheritanceType.",
          "enum": [
            "NOT_APPLICABLE",
            "CHILD_OVERRIDE",
            "PARENT_OVERRIDE",
            "BOTH_PERMIT"
          ],
          "type": "string",
          "enumDescriptions": [
            "The default value when this item does not inherit an ACL. Use NOT_APPLICABLE when inheritAclFrom is empty. An item without ACL inheritance can still have ACLs supplied by its own readers and deniedReaders fields.",
            "During an authorization conflict, the ACL of the child item determines its read access.",
            "During an authorization conflict, the ACL of the parent item specified in the inheritAclFrom field determines read access.",
            "Access is granted only if this item and the parent item specified in the inheritAclFrom field both permit read access."
          ]
        },
        "deniedReaders": {
          "type": "array",
          "items": {
            "$ref": "Principal"
          },
          "description": "List of principals who are explicitly denied access to the item in search results. While principals are denied access by default, use denied readers to handle exceptions and override the list allowed readers. The maximum number of elements is 100."
        },
        "readers": {
          "description": "List of principals who are allowed to see the item in search results. Optional if inheriting permissions from another item or if the item is not intended to be visible, such as virtual containers. The maximum number of elements is 1000.",
          "items": {
            "$ref": "Principal"
          },
          "type": "array"
        },
        "owners": {
          "type": "array",
          "description": "Optional. List of owners for the item. This field has no bearing on document access permissions. It does, however, offer a slight ranking boosts items where the querying user is an owner. The maximum number of elements is 5.",
          "items": {
            "$ref": "Principal"
          }
        },
        "inheritAclFrom": {
          "type": "string",
          "description": "The name of the item to inherit the Access Permission List (ACL) from. Note: ACL inheritance *only* provides access permissions to child items and does not define structural relationships, nor does it provide convenient ways to delete large groups of items. Deleting an ACL parent from the index only alters the access permissions of child items that reference the parent in the inheritAclFrom field. The item is still in the index, but may not visible in search results. By[...]"
        }
      },
      "type": "object"
    },
    "IntegerOperatorOptions": {
      "description": "Used to provide a search operator for integer properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched.",
      "id": "IntegerOperatorOptions",
      "properties": {
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the integer property using the less-than operator. For example, if lessThanOperatorName is *prioritybelow* and the property's name is *priorityVal*, then queries like *prioritybelow:<value>* show results only where the value of the property named *priorityVal* is less than *<value>*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        },
        "greaterThanOperatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the integer property using the greater-than operator. For example, if greaterThanOperatorName is *priorityabove* and the property's name is *priorityVal*, then queries like *priorityabove:<value>* show results only where the value of the property named *priorityVal* is greater than *<value>*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters."
        },
        "operatorName": {
          "type": "string",
          "description": "Indicates the operator name required in the query in order to isolate the integer property. For example, if operatorName is *priority* and the property's name is *priorityVal*, then queries like *priority:<value>* show results only where the value of the property named *priorityVal* matches *<value>*. By contrast, a search that uses the same *<value>* without an operator returns all items where *<value>* matches the value of any String properties or text within the cont[...]"
        }
      },
      "type": "object"
    },
    "Name": {
      "description": "A person's name.",
      "type": "object",
      "id": "Name",
      "properties": {
        "displayName": {
          "description": "The read-only display name formatted according to the locale specified by the viewer's account or the `Accept-Language` HTTP header.",
          "type": "string"
        }
      }
    },
    "EnterpriseTopazSidekickAgendaItem": {
      "type": "object",
      "id": "EnterpriseTopazSidekickAgendaItem",
      "properties": {
        "meeting": {
          "$ref": "EnterpriseTopazSidekickAgendaEntry"
        },
        "conflictedGroup": {
          "$ref": "EnterpriseTopazSidekickConflictingEventsCardProto"
        },
        "gapBefore": {
          "$ref": "EnterpriseTopazSidekickGap"
        }
      }
    },
    "QuerySource": {
      "description": "List of sources that the user can search using the query API.",
      "type": "object",
      "id": "QuerySource",
      "properties": {
        "shortName": {
          "description": "A short name or alias for the source. This value can be used with the 'source' operator.",
          "type": "string"
        },
        "displayName": {
          "type": "string",
          "description": "Display name of the data source."
        },
        "operators": {
          "items": {
            "$ref": "QueryOperator"
          },
          "description": "List of all operators applicable for this source.",
          "type": "array"
        },
        "source": {
          "description": "The name of the source",
          "$ref": "Source"
        }
      }
    },
    "NamedProperty": {
      "description": "A typed name-value pair for structured data. The type of the value should be the same as the registered type for the `name` property in the object definition of `objectType`.",
      "id": "NamedProperty",
      "properties": {
        "textValues": {
          "$ref": "TextValues"
        },
        "htmlValues": {
          "$ref": "HtmlValues"
        },
        "booleanValue": {
          "type": "boolean"
        },
        "enumValues": {
          "$ref": "EnumValues"
        },
        "objectValues": {
          "$ref": "ObjectValues"
        },
        "dateValues": {
          "$ref": "DateValues"
        },
        "name": {
          "type": "string",
          "description": "The name of the property. This name should correspond to the name of the property that was registered for object definition in the schema. The maximum allowable length for this property is 256 characters."
        },
        "doubleValues": {
          "$ref": "DoubleValues"
        },
        "timestampValues": {
          "$ref": "TimestampValues"
        },
        "integerValues": {
          "$ref": "IntegerValues"
        }
      },
      "type": "object"
    },
    "EnumValues": {
      "type": "object",
      "id": "EnumValues",
      "properties": {
        "values": {
          "type": "array",
          "description": "The maximum allowable length for string values is 32 characters.",
          "items": {
            "type": "string"
          }
        }
      },
      "description": "List of enum values."
    },
    "TimestampOperatorOptions": {
      "id": "TimestampOperatorOptions",
      "properties": {
        "greaterThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property using the greater-than operator. For example, if greaterThanOperatorName is *closedafter* and the property's name is *closeDate*, then queries like *closedafter:<value>* show results only where the value of the property named *closeDate* is later than *<value>*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        },
        "operatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property. For example, if operatorName is *closedon* and the property's name is *closeDate*, then queries like *closedon:<value>* show results only where the value of the property named *closeDate* matches *<value>*. By contrast, a search that uses the same *<value>* without an operator returns all items where *<value>* matches the value of any String properties or text within the conten[...]",
          "type": "string"
        },
        "lessThanOperatorName": {
          "description": "Indicates the operator name required in the query in order to isolate the timestamp property using the less-than operator. For example, if lessThanOperatorName is *closedbefore* and the property's name is *closeDate*, then queries like *closedbefore:<value>* show results only where the value of the property named *closeDate* is earlier than *<value>*. The operator name can only contain lowercase letters (a-z). The maximum length is 32 characters.",
          "type": "string"
        }
      },
      "type": "object",
      "description": "Used to provide a search operator for timestamp properties. This is optional. Search operators let users restrict the query to specific fields relevant to the type of item being searched."
    },
    "SourceConfig": {
      "id": "SourceConfig",
      "properties": {
        "scoringConfig": {
          "description": "The scoring configuration for the source.",
          "$ref": "SourceScoringConfig"
        },
        "crowdingConfig": {
          "description": "The crowding configuration for the source.",
          "$ref": "SourceCrowdingConfig"
        },
        "source": {
          "description": "The source for which this configuration is to be used.",
          "$ref": "Source"
        }
      },
      "type": "object",
      "description": "Configurations for a source while processing a Search or Suggest request."
    },
    "EnterpriseTopazSidekickAgendaEntry": {
      "description": "An AgendaEntry, e.g., a Calendar Event.",
      "type": "object",
      "id": "EnterpriseTopazSidekickAgendaEntry",
      "properties": {
        "notifyToUser": {
          "description": "Whether this should be notified to the user.",
          "type": "boolean"
        },
        "currentUserAttendingStatus": {
          "description": "Attendance status for the current user making the request. This is a convenience data member in order to avoid figuring out the same by iterating the invitee list above on the caller side.",
          "enum": [
            "AWAITING",
            "YES",
            "NO",
            "MAYBE"
          ],
          "type": "string",
          "enumDescriptions": [
            "Awaiting for the user to set the status.",
            "Attending.",
            "Not attending.",
            "Tentatively attending."
          ]
        },
        "guestsCanInviteOthers": {
          "type": "boolean",
          "description": "Whether the guests can invite other guests."
        },
        "timeZone": {
          "description": "User's calendar timezone;",
          "type": "string"
        },
        "document": {
          "type": "array",
          "items": {
            "$ref": "EnterpriseTopazSidekickCommonDocument"
          },
          "description": "Items related to the current AgendaEntry. E.g., related drive/mail/groups documents."
        },
        "guestsCanModify": {
          "description": "Whether the guests can modify the event.",
          "type": "boolean"
        },
        "endTimeMs": {
          "type": "string",
          "description": "End time in milliseconds",
          "format": "int64"
        },
        "agendaItemUrl": {
          "type": "string",
          "description": "URL of the agenda item."
        },
        "otherAttendeesExcluded": {
          "description": "Whether guest list is not returned because number of attendees is too large.",
          "type": "boolean"
        },
        "invitee": {
          "items": {
            "$ref": "EnterpriseTopazSidekickPerson"
          },
          "description": "People attending the meeting.",
          "type": "array"
        },
        "location": {
          "description": "Agenda item location.",
          "type": "string"
        },
        "hangoutId": {
          "type": "string",
          "description": "Hangout meeting identifier."
[...]
