{
  "version": "v1",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "description": "API for provisioning and managing identity resources.",
  "name": "cloudidentity",
  "title": "Cloud Identity API",
  "version_module": true,
  "documentationLink": "https://cloud.google.com/identity/",
  "basePath": "",
  "id": "cloudidentity:v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.policies.readonly": {
          "description": "See policies in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.inboundsso": {
          "description": "See and edit all of the Inbound SSO profiles and their assignments to any Org Units or Google Groups in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices"
        },
        "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly": {
          "description": "See all of the Inbound SSO profiles and their assignments to any Org Units or Google Groups in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.policies": {
          "description": "See and edit policies in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.readonly": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        }
      }
    }
  },
  "canonicalName": "Cloud Identity",
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "kind": "discovery#restDescription",
  "servicePath": "",
  "resources": {
    "devices": {
      "resources": {
        "deviceUsers": {
          "methods": {
            "cancelWipe": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped.",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "httpMethod": "POST",
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "path": "v1/{+name}:cancelWipe"
            },
            "get": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "GET",
              "description": "Retrieves the specified DeviceUser",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "path": "v1/{+name}",
              "id": "cloudidentity.devices.deviceUsers.get"
            },
            "approve": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve",
              "httpMethod": "POST",
              "description": "Approves device to access user data.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "id": "cloudidentity.devices.deviceUsers.approve",
              "path": "v1/{+name}:approve"
            },
            "wipe": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "path": "v1/{+name}:wipe",
              "id": "cloudidentity.devices.deviceUsers.wipe"
            },
            "list": {
              "flatPath": "v1/devices/{devicesId}/deviceUsers",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "description": "Lists/Searches DeviceUsers.",
              "id": "cloudidentity.devices.deviceUsers.list",
              "path": "v1/{+parent}/deviceUsers"
            },
            "block": {
              "id": "cloudidentity.devices.deviceUsers.block",
              "path": "v1/{+name}:block",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Blocks device from accessing user data"
            },
            "lookup": {
              "path": "v1/{+parent}:lookup",
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "httpMethod": "DELETE",
              "id": "cloudidentity.devices.deviceUsers.delete",
              "path": "v1/{+name}"
            }
          },
          "resources": {
            "clientStates": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/clientStates",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "description": "Lists the client states for the given search query."
                },
                "get": {
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "description": "Gets the client state for the device user",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "path": "v1/{+name}"
                },
                "patch": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices"
                  ],
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "httpMethod": "PATCH"
                }
              }
            }
          }
        }
      },
      "methods": {
        "get": {
          "id": "cloudidentity.devices.get",
          "path": "v1/{+name}",
          "description": "Retrieves the specified device.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "flatPath": "v1/devices/{devicesId}",
          "httpMethod": "GET"
        },
        "cancelWipe": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device.",
          "flatPath": "v1/devices/{devicesId}:cancelWipe",
          "httpMethod": "POST",
          "id": "cloudidentity.devices.cancelWipe",
          "path": "v1/{+name}:cancelWipe"
        },
        "delete": {
          "id": "cloudidentity.devices.delete",
          "path": "v1/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Deletes the specified device.",
          "flatPath": "v1/devices/{devicesId}",
          "httpMethod": "DELETE"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "description": "Lists/Searches devices.",
          "flatPath": "v1/devices",
          "httpMethod": "GET",
          "path": "v1/devices",
          "id": "cloudidentity.devices.list"
        },
        "create": {
          "path": "v1/devices",
          "id": "cloudidentity.devices.create",
          "flatPath": "v1/devices",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium"
        },
        "wipe": {
          "description": "Wipes all data on the specified device.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "flatPath": "v1/devices/{devicesId}:wipe",
          "httpMethod": "POST",
          "id": "cloudidentity.devices.wipe",
          "path": "v1/{+name}:wipe"
        }
      }
    },
    "groups": {
      "methods": {
        "list": {
          "id": "cloudidentity.groups.list",
          "path": "v1/groups",
          "flatPath": "v1/groups",
          "httpMethod": "GET",
          "description": "Lists the `Group` resources under a customer or namespace.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "updateSecuritySettings": {
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.updateSecuritySettings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Update Security Settings",
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "httpMethod": "PATCH"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes a `Group`.",
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "DELETE",
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.delete"
        },
        "create": {
          "id": "cloudidentity.groups.create",
          "path": "v1/groups",
          "flatPath": "v1/groups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates a Group."
        },
        "getSecuritySettings": {
          "id": "cloudidentity.groups.getSecuritySettings",
          "path": "v1/{+name}",
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Get Security Settings"
        },
        "patch": {
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates a `Group`.",
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.patch"
        },
        "lookup": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "flatPath": "v1/groups:lookup",
          "httpMethod": "GET",
          "id": "cloudidentity.groups.lookup",
          "path": "v1/groups:lookup"
        },
        "search": {
          "flatPath": "v1/groups:search",
          "httpMethod": "GET",
          "description": "Searches for `Group` resources matching a specified query.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/groups:search",
          "id": "cloudidentity.groups.search"
        },
        "get": {
          "flatPath": "v1/groups/{groupsId}",
          "httpMethod": "GET",
          "description": "Retrieves a `Group`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "path": "v1/{+name}",
          "id": "cloudidentity.groups.get"
        }
      },
      "resources": {
        "memberships": {
          "methods": {
            "searchTransitiveGroups": {
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "path": "v1/{+parent}/memberships:searchTransitiveGroups",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "httpMethod": "GET"
            },
            "get": {
              "path": "v1/{+name}",
              "id": "cloudidentity.groups.memberships.get",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Retrieves a `Membership`.",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "GET"
            },
            "searchTransitiveMemberships": {
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "httpMethod": "GET",
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1/{+parent}/memberships:searchTransitiveMemberships",
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships"
            },
            "create": {
              "path": "v1/{+parent}/memberships",
              "id": "cloudidentity.groups.memberships.create",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Creates a `Membership`."
            },
            "lookup": {
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`.",
              "id": "cloudidentity.groups.memberships.lookup",
              "path": "v1/{+parent}/memberships:lookup"
            },
            "modifyMembershipRoles": {
              "description": "Modifies the `MembershipRole`s of a `Membership`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "httpMethod": "POST",
              "path": "v1/{+name}:modifyMembershipRoles",
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles"
            },
            "list": {
              "id": "cloudidentity.groups.memberships.list",
              "path": "v1/{+parent}/memberships",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "httpMethod": "GET",
              "description": "Lists the `Membership`s within a `Group`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "checkTransitiveMembership": {
              "flatPath": "v1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor mu[...]",
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "path": "v1/{+parent}/memberships:checkTransitiveMembership"
            },
            "getMembershipGraph": {
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the respon[...]",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships:getMembershipGraph",
              "httpMethod": "GET",
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "path": "v1/{+parent}/memberships:getMembershipGraph"
            },
            "searchDirectGroups": {
              "id": "cloudidentity.groups.memberships.searchDirectGroups",
              "path": "v1/{+parent}/memberships:searchDirectGroups",
              "description": "Searches direct groups of a member.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/groups/{groupsId}/memberships:searchDirectGroups",
              "httpMethod": "GET"
            },
            "delete": {
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a `Membership`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudidentity.groups.memberships.delete",
              "path": "v1/{+name}"
            }
          }
        }
      }
    },
    "inboundSamlSsoProfiles": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates an InboundSamlSsoProfile. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "httpMethod": "PATCH",
          "id": "cloudidentity.inboundSamlSsoProfiles.patch",
          "path": "v1/{+name}"
        },
        "delete": {
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes an InboundSamlSsoProfile.",
          "id": "cloudidentity.inboundSamlSsoProfiles.delete",
          "path": "v1/{+name}"
        },
        "create": {
          "id": "cloudidentity.inboundSamlSsoProfiles.create",
          "path": "v1/inboundSamlSsoProfiles",
          "description": "Creates an InboundSamlSsoProfile for a customer. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundSamlSsoProfiles",
          "httpMethod": "POST"
        },
        "list": {
          "path": "v1/inboundSamlSsoProfiles",
          "id": "cloudidentity.inboundSamlSsoProfiles.list",
          "flatPath": "v1/inboundSamlSsoProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists InboundSamlSsoProfiles for a customer."
        },
        "get": {
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSamlSsoProfiles.get",
          "description": "Gets an InboundSamlSsoProfile.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "idpCredentials": {
          "methods": {
            "delete": {
              "path": "v1/{+name}",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.delete",
              "description": "Deletes an IdpCredential.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "httpMethod": "DELETE"
            },
            "get": {
              "path": "v1/{+name}",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.get",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Gets an IdpCredential."
            },
            "list": {
              "path": "v1/{+parent}/idpCredentials",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.list",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Returns a list of IdpCredentials in an InboundSamlSsoProfile."
            },
            "add": {
              "description": "Adds an IdpCredential. Up to 2 credentials are allowed. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials:add",
              "httpMethod": "POST",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.add",
              "path": "v1/{+parent}/idpCredentials:add"
            }
          }
        }
      }
    },
    "inboundOidcSsoProfiles": {
      "methods": {
        "get": {
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Gets an InboundOidcSsoProfile.",
          "id": "cloudidentity.inboundOidcSsoProfiles.get",
          "path": "v1/{+name}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates an InboundOidcSsoProfile. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "httpMethod": "PATCH",
          "id": "cloudidentity.inboundOidcSsoProfiles.patch",
          "path": "v1/{+name}"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes an InboundOidcSsoProfile.",
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "httpMethod": "DELETE",
          "id": "cloudidentity.inboundOidcSsoProfiles.delete",
          "path": "v1/{+name}"
        },
        "create": {
          "id": "cloudidentity.inboundOidcSsoProfiles.create",
          "path": "v1/inboundOidcSsoProfiles",
          "flatPath": "v1/inboundOidcSsoProfiles",
          "httpMethod": "POST",
          "description": "Creates an InboundOidcSsoProfile for a customer. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "list": {
          "path": "v1/inboundOidcSsoProfiles",
          "id": "cloudidentity.inboundOidcSsoProfiles.list",
          "flatPath": "v1/inboundOidcSsoProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists InboundOidcSsoProfile objects for a Google enterprise customer."
        }
      }
    },
    "inboundSsoAssignments": {
      "methods": {
        "get": {
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Gets an InboundSsoAssignment.",
          "path": "v1/{+name}",
          "id": "cloudidentity.inboundSsoAssignments.get"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates an InboundSsoAssignment. The body of this request is the `inbound_sso_assignment` field and the `update_mask` is relative to that. For example: a PATCH to `/v1/inboundSsoAssignments/0abcdefg1234567&update_mask=rank` with a body of `{ \"rank\": 1 }` moves that (presumably group-targeted) SSO assignment to the highest priority and shifts any other group-targeted assignments down in priority.",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "httpMethod": "PATCH",
          "id": "cloudidentity.inboundSsoAssignments.patch",
          "path": "v1/{+name}"
        },
        "delete": {
          "id": "cloudidentity.inboundSsoAssignments.delete",
          "path": "v1/{+name}",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes an InboundSsoAssignment. To disable SSO, Create (or Update) an assignment that has `sso_mode` == `SSO_OFF`."
        },
        "list": {
          "flatPath": "v1/inboundSsoAssignments",
          "httpMethod": "GET",
          "description": "Lists the InboundSsoAssignments for a `Customer`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSsoAssignments.list",
          "path": "v1/inboundSsoAssignments"
        },
        "create": {
          "id": "cloudidentity.inboundSsoAssignments.create",
          "path": "v1/inboundSsoAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates an InboundSsoAssignment for users and devices in a `Customer` under a given `Group` or `OrgUnit`.",
          "flatPath": "v1/inboundSsoAssignments",
          "httpMethod": "POST"
        }
      }
    },
    "policies": {
      "methods": {
        "get": {
          "flatPath": "v1/policies/{policiesId}",
          "httpMethod": "GET",
          "description": "Get a policy.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies",
            "https://www.googleapis.com/auth/cloud-identity.policies.readonly"
          ],
          "path": "v1/{+name}",
          "id": "cloudidentity.policies.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies",
            "https://www.googleapis.com/auth/cloud-identity.policies.readonly"
          ],
          "description": "List policies.",
          "flatPath": "v1/policies",
          "httpMethod": "GET",
          "path": "v1/policies",
          "id": "cloudidentity.policies.list"
        }
      }
    },
    "customers": {
      "resources": {
        "userinvitations": {
          "methods": {
            "get": {
              "path": "v1/{+name}",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}",
              "httpMethod": "GET",
              "id": "cloudidentity.customers.userinvitations.get",
              "description": "Retrieves a UserInvitation resource. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains."
            },
            "list": {
              "path": "v1/{+parent}/userinvitations",
              "flatPath": "v1/customers/{customersId}/userinvitations",
              "httpMethod": "GET",
              "description": "Retrieves a list of UserInvitation resources. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "id": "cloudidentity.customers.userinvitations.list"
            },
            "cancel": {
              "description": "Cancels a UserInvitation that was already sent.",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel",
              "httpMethod": "POST",
              "id": "cloudidentity.customers.userinvitations.cancel",
              "path": "v1/{+name}:cancel"
            },
            "send": {
              "path": "v1/{+name}:send",
              "id": "cloudidentity.customers.userinvitations.send",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:send",
              "httpMethod": "POST",
              "description": "Sends a UserInvitation to email. If the `UserInvitation` does not exist for this request and it is a valid request, the request creates a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour delay where newly-created consumer accounts will not appear in the results. You can still send a `UserInvitation` to those accounts if you know the unmanaged email address and IsInvitableUser==True."
            },
            "isInvitableUser": {
              "description": "Verifies whether a user account is eligible to receive a UserInvitation (is an unmanaged account). Eligibility is based on the following criteria: * the email address is a consumer account and it's the primary email address of the account, and * the domain of the email address matches an existing verified Google Workspace or Cloud Identity domain If both conditions are met, the user is eligible. **Note:** This method is not supported for Workspace Essentials custome[...]",
              "id": "cloudidentity.customers.userinvitations.isInvitableUser",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser",
              "httpMethod": "GET",
              "path": "v1/{+name}:isInvitableUser"
            }
          }
        }
      }
    }
  },
  "revision": "20260427",
  "ownerName": "Google",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "ownerDomain": "google.com",
  "protocol": "rest",
  "batchPath": "batch"
}