{
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "ownerName": "Google",
  "documentationLink": "https://cloud.google.com/identity/",
  "basePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-identity.groups.readonly": {
          "description": "See any Cloud Identity Groups that you can access, including group members and their emails"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-identity.policies": {
          "description": "See and edit policies in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.inboundsso": {
          "description": "See and edit all of the Inbound SSO profiles and their assignments to any Org Units or Google Groups in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly": {
          "description": "See all of the Inbound SSO profiles and their assignments to any Org Units or Google Groups in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.devices": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.lookup": {
          "description": "See your device details"
        },
        "https://www.googleapis.com/auth/cloud-identity.devices.readonly": {
          "description": "Private Service: https://www.googleapis.com/auth/cloud-identity.devices.readonly"
        },
        "https://www.googleapis.com/auth/cloud-identity.policies.readonly": {
          "description": "See policies in your Cloud Identity Organization."
        },
        "https://www.googleapis.com/auth/cloud-identity.groups": {
          "description": "See, change, create, and delete any of the Cloud Identity Groups that you can access, including the members of each group"
        }
      }
    }
  },
  "protocol": "rest",
  "canonicalName": "Cloud Identity",
  "baseUrl": "https://cloudidentity.googleapis.com/",
  "version_module": true,
  "id": "cloudidentity:v1",
  "mtlsRootUrl": "https://cloudidentity.mtls.googleapis.com/",
  "ownerDomain": "google.com",
  "rootUrl": "https://cloudidentity.googleapis.com/",
  "kind": "discovery#restDescription",
  "name": "cloudidentity",
  "description": "API for provisioning and managing identity resources.",
  "resources": {
    "policies": {
      "methods": {
        "list": {
          "description": "List policies.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies",
            "https://www.googleapis.com/auth/cloud-identity.policies.readonly"
          ],
          "httpMethod": "GET",
          "path": "v1/policies",
          "id": "cloudidentity.policies.list",
          "flatPath": "v1/policies"
        },
        "get": {
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "description": "Get a policy.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.policies",
            "https://www.googleapis.com/auth/cloud-identity.policies.readonly"
          ],
          "id": "cloudidentity.policies.get",
          "flatPath": "v1/policies/{policiesId}"
        }
      }
    },
    "groups": {
      "methods": {
        "patch": {
          "id": "cloudidentity.groups.patch",
          "flatPath": "v1/groups/{groupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates a `Group`.",
          "path": "v1/{+name}",
          "httpMethod": "PATCH"
        },
        "updateSecuritySettings": {
          "id": "cloudidentity.groups.updateSecuritySettings",
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Update Security Settings",
          "path": "v1/{+name}",
          "httpMethod": "PATCH"
        },
        "create": {
          "httpMethod": "POST",
          "path": "v1/groups",
          "description": "Creates a Group.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.create",
          "flatPath": "v1/groups"
        },
        "lookup": {
          "httpMethod": "GET",
          "path": "v1/groups:lookup",
          "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Group` by its `EntityKey`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.lookup",
          "flatPath": "v1/groups:lookup"
        },
        "get": {
          "path": "v1/{+name}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Retrieves a `Group`.",
          "id": "cloudidentity.groups.get",
          "flatPath": "v1/groups/{groupsId}"
        },
        "delete": {
          "id": "cloudidentity.groups.delete",
          "flatPath": "v1/groups/{groupsId}",
          "path": "v1/{+name}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes a `Group`."
        },
        "getSecuritySettings": {
          "id": "cloudidentity.groups.getSecuritySettings",
          "flatPath": "v1/groups/{groupsId}/securitySettings",
          "description": "Get Security Settings",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "path": "v1/{+name}"
        },
        "search": {
          "description": "Searches for `Group` resources matching a specified query.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "GET",
          "path": "v1/groups:search",
          "id": "cloudidentity.groups.search",
          "flatPath": "v1/groups:search"
        },
        "list": {
          "httpMethod": "GET",
          "path": "v1/groups",
          "description": "Lists the `Group` resources under a customer or namespace.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.groups",
            "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.groups.list",
          "flatPath": "v1/groups"
        }
      },
      "resources": {
        "memberships": {
          "methods": {
            "searchTransitiveMemberships": {
              "id": "cloudidentity.groups.memberships.searchTransitiveMemberships",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveMemberships",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Search transitive memberships of a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the group is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive membership is any direct or indirect membership of a group. Actor must have view permissions to all transitive memberships.",
              "path": "v1/{+parent}/memberships:searchTransitiveMemberships",
              "httpMethod": "GET"
            },
            "modifyMembershipRoles": {
              "id": "cloudidentity.groups.memberships.modifyMembershipRoles",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}:modifyMembershipRoles",
              "path": "v1/{+name}:modifyMembershipRoles",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Modifies the `MembershipRole`s of a `Membership`."
            },
            "searchDirectGroups": {
              "id": "cloudidentity.groups.memberships.searchDirectGroups",
              "flatPath": "v1/groups/{groupsId}/memberships:searchDirectGroups",
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:searchDirectGroups",
              "description": "Searches direct groups of a member.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "create": {
              "id": "cloudidentity.groups.memberships.create",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "path": "v1/{+parent}/memberships",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Creates a `Membership`."
            },
            "lookup": {
              "id": "cloudidentity.groups.memberships.lookup",
              "flatPath": "v1/groups/{groupsId}/memberships:lookup",
              "path": "v1/{+parent}/memberships:lookup",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Looks up the [resource name](https://cloud.google.com/apis/design/resource_names) of a `Membership` by its `EntityKey`."
            },
            "searchTransitiveGroups": {
              "id": "cloudidentity.groups.memberships.searchTransitiveGroups",
              "flatPath": "v1/groups/{groupsId}/memberships:searchTransitiveGroups",
              "description": "Search transitive groups of a member. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A transitive group is any group that has a direct or indirect membership to the member. Actor must have view permissions all transitive groups.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:searchTransitiveGroups"
            },
            "get": {
              "id": "cloudidentity.groups.memberships.get",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "httpMethod": "GET",
              "path": "v1/{+name}",
              "description": "Retrieves a `Membership`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "delete": {
              "id": "cloudidentity.groups.memberships.delete",
              "flatPath": "v1/groups/{groupsId}/memberships/{membershipsId}",
              "description": "Deletes a `Membership`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "DELETE",
              "path": "v1/{+name}"
            },
            "getMembershipGraph": {
              "id": "cloudidentity.groups.memberships.getMembershipGraph",
              "flatPath": "v1/groups/{groupsId}/memberships:getMembershipGraph",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Get a membership graph of just a member or both a member and a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. Given a member, the response will contain all membership paths from the member. Given both a group and a member, the respon[...]",
              "path": "v1/{+parent}/memberships:getMembershipGraph",
              "httpMethod": "GET"
            },
            "list": {
              "id": "cloudidentity.groups.memberships.list",
              "flatPath": "v1/groups/{groupsId}/memberships",
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships",
              "description": "Lists the `Membership`s within a `Group`.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "checkTransitiveMembership": {
              "id": "cloudidentity.groups.memberships.checkTransitiveMembership",
              "flatPath": "v1/groups/{groupsId}/memberships:checkTransitiveMembership",
              "description": "Check a potential member for membership in a group. **Note:** This feature is only available to Google Workspace Enterprise Standard, Enterprise Plus, and Enterprise for Education; and Cloud Identity Premium accounts. If the account of the member is not one of these, a 403 (PERMISSION_DENIED) HTTP status code will be returned. A member has membership to a group as long as there is a single viewable transitive membership between the group and the member. The actor mu[...]",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.groups",
                "https://www.googleapis.com/auth/cloud-identity.groups.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "GET",
              "path": "v1/{+parent}/memberships:checkTransitiveMembership"
            }
          }
        }
      }
    },
    "inboundSamlSsoProfiles": {
      "resources": {
        "idpCredentials": {
          "methods": {
            "list": {
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.list",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials",
              "httpMethod": "GET",
              "path": "v1/{+parent}/idpCredentials",
              "description": "Returns a list of IdpCredentials in an InboundSamlSsoProfile.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "delete": {
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.delete",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}",
              "description": "Deletes an IdpCredential.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "httpMethod": "DELETE",
              "path": "v1/{+name}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Gets an IdpCredential.",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.get",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials/{idpCredentialsId}"
            },
            "add": {
              "id": "cloudidentity.inboundSamlSsoProfiles.idpCredentials.add",
              "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}/idpCredentials:add",
              "path": "v1/{+parent}/idpCredentials:add",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.inboundsso",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "description": "Adds an IdpCredential. Up to 2 credentials are allowed. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`."
            }
          }
        }
      },
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "path": "v1/{+name}",
          "description": "Updates an InboundSamlSsoProfile. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSamlSsoProfiles.patch",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}"
        },
        "delete": {
          "id": "cloudidentity.inboundSamlSsoProfiles.delete",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}",
          "description": "Deletes an InboundSamlSsoProfile.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "httpMethod": "DELETE",
          "path": "v1/{+name}"
        },
        "get": {
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "description": "Gets an InboundSamlSsoProfile.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSamlSsoProfiles.get",
          "flatPath": "v1/inboundSamlSsoProfiles/{inboundSamlSsoProfilesId}"
        },
        "create": {
          "httpMethod": "POST",
          "path": "v1/inboundSamlSsoProfiles",
          "description": "Creates an InboundSamlSsoProfile for a customer. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundSamlSsoProfiles.create",
          "flatPath": "v1/inboundSamlSsoProfiles"
        },
        "list": {
          "path": "v1/inboundSamlSsoProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists InboundSamlSsoProfiles for a customer.",
          "id": "cloudidentity.inboundSamlSsoProfiles.list",
          "flatPath": "v1/inboundSamlSsoProfiles"
        }
      }
    },
    "customers": {
      "resources": {
        "userinvitations": {
          "methods": {
            "send": {
              "id": "cloudidentity.customers.userinvitations.send",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:send",
              "description": "Sends a UserInvitation to email. If the `UserInvitation` does not exist for this request and it is a valid request, the request creates a `UserInvitation`. **Note:** The `get` and `list` methods have a 48-hour delay where newly-created consumer accounts will not appear in the results. You can still send a `UserInvitation` to those accounts if you know the unmanaged email address and IsInvitableUser==True.",
              "httpMethod": "POST",
              "path": "v1/{+name}:send"
            },
            "list": {
              "id": "cloudidentity.customers.userinvitations.list",
              "flatPath": "v1/customers/{customersId}/userinvitations",
              "description": "Retrieves a list of UserInvitation resources. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "httpMethod": "GET",
              "path": "v1/{+parent}/userinvitations"
            },
            "cancel": {
              "httpMethod": "POST",
              "path": "v1/{+name}:cancel",
              "description": "Cancels a UserInvitation that was already sent.",
              "id": "cloudidentity.customers.userinvitations.cancel",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:cancel"
            },
            "isInvitableUser": {
              "httpMethod": "GET",
              "path": "v1/{+name}:isInvitableUser",
              "id": "cloudidentity.customers.userinvitations.isInvitableUser",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}:isInvitableUser",
              "description": "Verifies whether a user account is eligible to receive a UserInvitation (is an unmanaged account). Eligibility is based on the following criteria: * the email address is a consumer account and it's the primary email address of the account, and * the domain of the email address matches an existing verified Google Workspace or Cloud Identity domain If both conditions are met, the user is eligible. **Note:** This method is not supported for Workspace Essentials custome[...]"
            },
            "get": {
              "id": "cloudidentity.customers.userinvitations.get",
              "flatPath": "v1/customers/{customersId}/userinvitations/{userinvitationsId}",
              "description": "Retrieves a UserInvitation resource. **Note:** New consumer accounts with the customer's verified domain created within the previous 48 hours will not appear in the result. This delay also applies to newly-verified domains.",
              "httpMethod": "GET",
              "path": "v1/{+name}"
            }
          }
        }
      }
    },
    "devices": {
      "resources": {
        "deviceUsers": {
          "methods": {
            "get": {
              "id": "cloudidentity.devices.deviceUsers.get",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "description": "Retrieves the specified DeviceUser",
              "path": "v1/{+name}",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Deletes the specified DeviceUser. This also revokes the user's access to device data.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "httpMethod": "DELETE",
              "path": "v1/{+name}",
              "id": "cloudidentity.devices.deviceUsers.delete",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}"
            },
            "approve": {
              "path": "v1/{+name}:approve",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Approves device to access user data.",
              "id": "cloudidentity.devices.deviceUsers.approve",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:approve"
            },
            "wipe": {
              "path": "v1/{+name}:wipe",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Wipes the user's account on a device. Other data on the device that is not associated with the user's work account is not affected. For example, if a Gmail app is installed on a device that is used for personal and work purposes, and the user is logged in to the Gmail app with their personal account as well as their work account, wiping the \"deviceUser\" by their work administrator will not affect their personal account within Gmail or other apps such as Photos.",
              "id": "cloudidentity.devices.deviceUsers.wipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:wipe"
            },
            "cancelWipe": {
              "id": "cloudidentity.devices.deviceUsers.cancelWipe",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:cancelWipe",
              "path": "v1/{+name}:cancelWipe",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "description": "Cancels an unfinished user account wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped."
            },
            "lookup": {
              "id": "cloudidentity.devices.deviceUsers.lookup",
              "flatPath": "v1/devices/{devicesId}/deviceUsers:lookup",
              "description": "Looks up resource names of the DeviceUsers associated with the caller's credentials, as well as the properties provided in the request. This method must be called with end-user credentials with the scope: https://www.googleapis.com/auth/cloud-identity.devices.lookup If multiple properties are provided, only DeviceUsers having all of these properties are considered as matches - i.e. the query behaves like an AND. Different platforms require different amounts of infor[...]",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices.lookup"
              ],
              "httpMethod": "GET",
              "path": "v1/{+parent}:lookup"
            },
            "block": {
              "id": "cloudidentity.devices.deviceUsers.block",
              "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}:block",
              "description": "Blocks device from accessing user data",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices"
              ],
              "httpMethod": "POST",
              "path": "v1/{+name}:block"
            },
            "list": {
              "path": "v1/{+parent}/deviceUsers",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-identity.devices",
                "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
              ],
              "description": "Lists/Searches DeviceUsers.",
              "id": "cloudidentity.devices.deviceUsers.list",
              "flatPath": "v1/devices/{devicesId}/deviceUsers"
            }
          },
          "resources": {
            "clientStates": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "description": "Gets the client state for the device user",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "id": "cloudidentity.devices.deviceUsers.clientStates.get",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}"
                },
                "patch": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.patch",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates/{clientStatesId}",
                  "description": "Updates the client state for the device user **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices"
                  ],
                  "httpMethod": "PATCH",
                  "path": "v1/{+name}"
                },
                "list": {
                  "id": "cloudidentity.devices.deviceUsers.clientStates.list",
                  "flatPath": "v1/devices/{devicesId}/deviceUsers/{deviceUsersId}/clientStates",
                  "description": "Lists the client states for the given search query.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-identity.devices",
                    "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/clientStates"
                }
              }
            }
          }
        }
      },
      "methods": {
        "wipe": {
          "path": "v1/{+name}:wipe",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Wipes all data on the specified device.",
          "id": "cloudidentity.devices.wipe",
          "flatPath": "v1/devices/{devicesId}:wipe"
        },
        "get": {
          "id": "cloudidentity.devices.get",
          "flatPath": "v1/devices/{devicesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "description": "Retrieves the specified device.",
          "path": "v1/{+name}",
          "httpMethod": "GET"
        },
        "delete": {
          "id": "cloudidentity.devices.delete",
          "flatPath": "v1/devices/{devicesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Deletes the specified device.",
          "path": "v1/{+name}",
          "httpMethod": "DELETE"
        },
        "list": {
          "id": "cloudidentity.devices.list",
          "flatPath": "v1/devices",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices",
            "https://www.googleapis.com/auth/cloud-identity.devices.readonly"
          ],
          "description": "Lists/Searches devices.",
          "path": "v1/devices",
          "httpMethod": "GET"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "description": "Creates a device. Only company-owned device may be created. **Note**: This method is available only to customers who have one of the following SKUs: Enterprise Standard, Enterprise Plus, Enterprise for Education, and Cloud Identity Premium",
          "path": "v1/devices",
          "httpMethod": "POST",
          "id": "cloudidentity.devices.create",
          "flatPath": "v1/devices"
        },
        "cancelWipe": {
          "description": "Cancels an unfinished device wipe. This operation can be used to cancel device wipe in the gap between the wipe operation returning success and the device being wiped. This operation is possible when the device is in a \"pending wipe\" state. The device enters the \"pending wipe\" state when a wipe device command is issued, but has not yet been sent to the device. The cancel wipe will fail if the wipe command has already been issued to the device.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.devices"
          ],
          "httpMethod": "POST",
          "path": "v1/{+name}:cancelWipe",
          "id": "cloudidentity.devices.cancelWipe",
          "flatPath": "v1/devices/{devicesId}:cancelWipe"
        }
      }
    },
    "inboundOidcSsoProfiles": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "path": "v1/{+name}",
          "description": "Updates an InboundOidcSsoProfile. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudidentity.inboundOidcSsoProfiles.patch",
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}"
        },
        "delete": {
          "id": "cloudidentity.inboundOidcSsoProfiles.delete",
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes an InboundOidcSsoProfile.",
          "path": "v1/{+name}",
          "httpMethod": "DELETE"
        },
        "get": {
          "id": "cloudidentity.inboundOidcSsoProfiles.get",
          "flatPath": "v1/inboundOidcSsoProfiles/{inboundOidcSsoProfilesId}",
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "description": "Gets an InboundOidcSsoProfile.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "create": {
          "path": "v1/inboundOidcSsoProfiles",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates an InboundOidcSsoProfile for a customer. When the target customer has enabled [Multi-party approval for sensitive actions](https://support.google.com/a/answer/13790448), the `Operation` in the response will have `\"done\": false`, it will not have a response, and the metadata will have `\"state\": \"awaiting-multi-party-approval\"`.",
          "id": "cloudidentity.inboundOidcSsoProfiles.create",
          "flatPath": "v1/inboundOidcSsoProfiles"
        },
        "list": {
          "path": "v1/inboundOidcSsoProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists InboundOidcSsoProfile objects for a Google enterprise customer.",
          "id": "cloudidentity.inboundOidcSsoProfiles.list",
          "flatPath": "v1/inboundOidcSsoProfiles"
        }
      }
    },
    "inboundSsoAssignments": {
      "methods": {
        "get": {
          "id": "cloudidentity.inboundSsoAssignments.get",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Gets an InboundSsoAssignment.",
          "path": "v1/{+name}",
          "httpMethod": "GET"
        },
        "patch": {
          "id": "cloudidentity.inboundSsoAssignments.patch",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}",
          "path": "v1/{+name}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Updates an InboundSsoAssignment. The body of this request is the `inbound_sso_assignment` field and the `update_mask` is relative to that. For example: a PATCH to `/v1/inboundSsoAssignments/0abcdefg1234567&update_mask=rank` with a body of `{ \"rank\": 1 }` moves that (presumably group-targeted) SSO assignment to the highest priority and shifts any other group-targeted assignments down in priority."
        },
        "delete": {
          "path": "v1/{+name}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Deletes an InboundSsoAssignment. To disable SSO, Create (or Update) an assignment that has `sso_mode` == `SSO_OFF`.",
          "id": "cloudidentity.inboundSsoAssignments.delete",
          "flatPath": "v1/inboundSsoAssignments/{inboundSsoAssignmentsId}"
        },
        "list": {
          "id": "cloudidentity.inboundSsoAssignments.list",
          "flatPath": "v1/inboundSsoAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-identity.inboundsso.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Lists the InboundSsoAssignments for a `Customer`.",
          "path": "v1/inboundSsoAssignments",
          "httpMethod": "GET"
        },
        "create": {
          "id": "cloudidentity.inboundSsoAssignments.create",
          "flatPath": "v1/inboundSsoAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-identity.inboundsso",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "description": "Creates an InboundSsoAssignment for users and devices in a `Customer` under a given `Group` or `OrgUnit`.",
          "path": "v1/inboundSsoAssignments",
          "httpMethod": "POST"
        }
      }
    }
  },
  "version": "v1",
  "servicePath": "",
  "revision": "20260310",
  "fullyEncodeReservedExpansion": true,
  "title": "Cloud Identity API"
}