{
  "mtlsRootUrl": "https://cloudbilling.mtls.googleapis.com/",
  "canonicalName": "Cloudbilling",
  "batchPath": "batch",
  "revision": "20260507",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-billing": {
          "description": "View and manage your Google Cloud Platform billing accounts"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-billing.readonly": {
          "description": "View your Google Cloud Platform billing accounts"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "baseUrl": "https://cloudbilling.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://cloudbilling.googleapis.com/",
  "description": "Allows developers to manage billing for their Google Cloud Platform projects programmatically.",
  "basePath": "",
  "protocol": "rest",
  "ownerDomain": "google.com",
  "id": "cloudbilling:v1beta",
  "name": "cloudbilling",
  "ownerName": "Google",
  "servicePath": "",
  "resources": {
    "v1beta": {
      "methods": {
        "generateInsights": {
          "flatPath": "v1beta:generateInsights",
          "httpMethod": "POST",
          "path": "v1beta:generateInsights",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "id": "cloudbilling.generateInsights",
          "description": "Analyzes cost data for a billing account and/or specific projects. Returns a natural language summary and supporting datasets."
        }
      }
    },
    "skus": {
      "resources": {
        "price": {
          "methods": {
            "get": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/skus/{skusId}/price",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudbilling.skus.price.get",
              "description": "Gets the latest price for the given SKU."
            }
          }
        },
        "prices": {
          "methods": {
            "list": {
              "description": "Lists the latest prices for all SKUs.",
              "id": "cloudbilling.skus.prices.list",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "path": "v1beta/{+parent}/prices",
              "flatPath": "v1beta/skus/{skusId}/prices",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "skuGroups": {
      "resources": {
        "skus": {
          "methods": {
            "get": {
              "path": "v1beta/{+name}",
              "flatPath": "v1beta/skuGroups/{skuGroupsId}/skus/{skusId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudbilling.skuGroups.skus.get",
              "description": "Gets a publicly listed SKU that is part of a publicly listed SKU group."
            },
            "list": {
              "description": "Lists all publicly listed SKUs contained by a publicly listed SKU group.",
              "id": "cloudbilling.skuGroups.skus.list",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta/skuGroups/{skuGroupsId}/skus",
              "httpMethod": "GET",
              "path": "v1beta/{+parent}/skus"
            }
          }
        }
      },
      "methods": {
        "list": {
          "id": "cloudbilling.skuGroups.list",
          "description": "Lists all publicly listed SKU groups.",
          "flatPath": "v1beta/skuGroups",
          "httpMethod": "GET",
          "path": "v1beta/skuGroups",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ]
        },
        "get": {
          "description": "Gets a publicly listed SKU group.",
          "id": "cloudbilling.skuGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-billing",
            "https://www.googleapis.com/auth/cloud-billing.readonly",
            "https://www.googleapis.com/auth/cloud-platform"
          ],
          "flatPath": "v1beta/skuGroups/{skuGroupsId}",
          "httpMethod": "GET",
          "path": "v1beta/{+name}"
        }
      }
    },
    "billingAccounts": {
      "resources": {
        "skus": {
          "methods": {
            "list": {
              "id": "cloudbilling.billingAccounts.skus.list",
              "description": "Lists SKUs visible to a billing account.",
              "path": "v1beta/{+parent}/skus",
              "flatPath": "v1beta/billingAccounts/{billingAccountsId}/skus",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "get": {
              "description": "Gets a SKU visible to a billing account.",
              "id": "cloudbilling.billingAccounts.skus.get",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "flatPath": "v1beta/billingAccounts/{billingAccountsId}/skus/{skusId}",
              "httpMethod": "GET",
              "path": "v1beta/{+name}"
            }
          },
          "resources": {
            "price": {
              "methods": {
                "get": {
                  "id": "cloudbilling.billingAccounts.skus.price.get",
                  "description": "Gets the latest price for SKUs available to your Cloud Billing account.",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/billingAccounts/{billingAccountsId}/skus/{skusId}/price",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-billing",
                    "https://www.googleapis.com/auth/cloud-billing.readonly",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ]
                }
              }
            },
            "prices": {
              "methods": {
                "list": {
                  "path": "v1beta/{+parent}/prices",
                  "flatPath": "v1beta/billingAccounts/{billingAccountsId}/skus/{skusId}/prices",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-billing",
                    "https://www.googleapis.com/auth/cloud-billing.readonly",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "id": "cloudbilling.billingAccounts.skus.prices.list",
                  "description": "Lists the latest prices for SKUs available to your Cloud Billing account."
                }
              }
            }
          }
        },
        "services": {
          "methods": {
            "get": {
              "id": "cloudbilling.billingAccounts.services.get",
              "description": "Gets a Google Cloud service visible to a billing account.",
              "flatPath": "v1beta/billingAccounts/{billingAccountsId}/services/{servicesId}",
              "httpMethod": "GET",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            },
            "list": {
              "path": "v1beta/{+parent}/services",
              "flatPath": "v1beta/billingAccounts/{billingAccountsId}/services",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudbilling.billingAccounts.services.list",
              "description": "Lists services visible to a billing account."
            }
          }
        },
        "skuGroups": {
          "methods": {
            "get": {
              "flatPath": "v1beta/billingAccounts/{billingAccountsId}/skuGroups/{skuGroupsId}",
              "httpMethod": "GET",
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ],
              "id": "cloudbilling.billingAccounts.skuGroups.get",
              "description": "Gets a SKU group visible to a billing account."
            },
            "list": {
              "id": "cloudbilling.billingAccounts.skuGroups.list",
              "description": "Lists SKU groups visible to a billing account.",
              "path": "v1beta/{+parent}/skuGroups",
              "flatPath": "v1beta/billingAccounts/{billingAccountsId}/skuGroups",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-billing",
                "https://www.googleapis.com/auth/cloud-billing.readonly",
                "https://www.googleapis.com/auth/cloud-platform"
              ]
            }
          },
          "resources": {
            "skus": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-billing",
                    "https://www.googleapis.com/auth/cloud-billing.readonly",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "flatPath": "v1beta/billingAccounts/{billingAccountsId}/skuGroups/{skuGroupsId}/skus/{skusId}",
                  "httpMethod": "GET",
                  "path": "v1beta/{+name}",
                  "description": "Gets a SKU that is part of a billing account SKU group.",
                  "id": "cloudbilling.billingAccounts.skuGroups.skus.get"
                },
                "list": {
                  "description": "Lists SKUs that is part of billing account SKU groups.",
                  "id": "cloudbilling.billingAccounts.skuGroups.skus.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-billing",
                    "https://www.googleapis.com/auth/cloud-billing.readonly",
                    "https://www.googleapis.com/auth/cloud-platform"
                  ],
                  "path": "v1beta/{+parent}/skus",
                  "flatPath": "v1beta/billingAccounts/{billingAccountsId}/skuGroups/{skuGroupsId}/skus",
                  "httpMethod": "GET"
                }
              }
            }
          }
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "version_module": true,
  "documentationLink": "https://cloud.google.com/billing/docs/apis",
  "version": "v1beta",
  "title": "Cloud Billing API"
}