{
  "kind": "discovery#restDescription",
  "version_module": true,
  "baseUrl": "https://composer.googleapis.com/",
  "canonicalName": "Cloud Composer",
  "title": "Cloud Composer API",
  "discoveryVersion": "v1",
  "resources": {
    "projects": {
      "resources": {
        "locations": {
          "resources": {
            "imageVersions": {
              "methods": {
                "list": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/imageVersions",
                  "description": "List ImageVersions for provided location.",
                  "id": "composer.projects.locations.imageVersions.list",
                  "path": "v1/{+parent}/imageVersions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer",
                    "https://www.googleapis.com/auth/cloudcomposer.readonly"
                  ],
                  "httpMethod": "GET"
                }
              }
            },
            "environments": {
              "methods": {
                "restartWebServer": {
                  "httpMethod": "POST",
                  "description": "Restart Airflow web server.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}:restartWebServer",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer"
                  ],
                  "id": "composer.projects.locations.environments.restartWebServer",
                  "path": "v1/{+name}:restartWebServer"
                },
                "pollAirflowCommand": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer",
                    "https://www.googleapis.com/auth/cloudcomposer.readonly"
                  ],
                  "id": "composer.projects.locations.environments.pollAirflowCommand",
                  "path": "v1/{+environment}:pollAirflowCommand",
                  "description": "Polls Airflow CLI command execution and fetches logs.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}:pollAirflowCommand",
                  "httpMethod": "POST"
                },
                "create": {
                  "httpMethod": "POST",
                  "description": "Create a new environment.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer"
                  ],
                  "id": "composer.projects.locations.environments.create",
                  "path": "v1/{+parent}/environments"
                },
                "list": {
                  "httpMethod": "GET",
                  "description": "List environments.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer",
                    "https://www.googleapis.com/auth/cloudcomposer.readonly"
                  ],
                  "id": "composer.projects.locations.environments.list",
                  "path": "v1/{+parent}/environments"
                },
                "stopAirflowCommand": {
                  "description": "Stops Airflow CLI command execution.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}:stopAirflowCommand",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer"
                  ],
                  "id": "composer.projects.locations.environments.stopAirflowCommand",
                  "path": "v1/{+environment}:stopAirflowCommand",
                  "httpMethod": "POST"
                },
                "loadSnapshot": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer"
                  ],
                  "id": "composer.projects.locations.environments.loadSnapshot",
                  "path": "v1/{+environment}:loadSnapshot",
                  "description": "Loads a snapshot of a Cloud Composer environment. As a result of this operation, a snapshot of environment's specified in LoadSnapshotRequest is loaded into the environment.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}:loadSnapshot",
                  "httpMethod": "POST"
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer",
                    "https://www.googleapis.com/auth/cloudcomposer.readonly"
                  ],
                  "id": "composer.projects.locations.environments.get",
                  "path": "v1/{+name}",
                  "description": "Get an existing environment.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Delete an environment.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer"
                  ],
                  "id": "composer.projects.locations.environments.delete",
                  "path": "v1/{+name}"
                },
                "databaseFailover": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}:databaseFailover",
                  "description": "Triggers database failover (only for highly resilient environments).",
                  "id": "composer.projects.locations.environments.databaseFailover",
                  "path": "v1/{+environment}:databaseFailover",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer"
                  ]
                },
                "fetchDatabaseProperties": {
                  "httpMethod": "GET",
                  "id": "composer.projects.locations.environments.fetchDatabaseProperties",
                  "path": "v1/{+environment}:fetchDatabaseProperties",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer",
                    "https://www.googleapis.com/auth/cloudcomposer.readonly"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}:fetchDatabaseProperties",
                  "description": "Fetches database properties."
                },
                "executeAirflowCommand": {
                  "description": "Executes Airflow CLI command.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}:executeAirflowCommand",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer"
                  ],
                  "id": "composer.projects.locations.environments.executeAirflowCommand",
                  "path": "v1/{+environment}:executeAirflowCommand",
                  "httpMethod": "POST"
                },
                "checkUpgrade": {
                  "httpMethod": "POST",
                  "description": "Check if an upgrade operation on the environment will succeed. In case of problems detailed info can be found in the returned Operation.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}:checkUpgrade",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer"
                  ],
                  "id": "composer.projects.locations.environments.checkUpgrade",
                  "path": "v1/{+environment}:checkUpgrade"
                },
                "patch": {
                  "id": "composer.projects.locations.environments.patch",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}",
                  "description": "Update an environment.",
                  "httpMethod": "PATCH"
                },
                "saveSnapshot": {
                  "description": "Creates a snapshots of a Cloud Composer environment. As a result of this operation, snapshot of environment's state is stored in a location specified in the SaveSnapshotRequest.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}:saveSnapshot",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer"
                  ],
                  "id": "composer.projects.locations.environments.saveSnapshot",
                  "path": "v1/{+environment}:saveSnapshot",
                  "httpMethod": "POST"
                }
              },
              "resources": {
                "userWorkloadsSecrets": {
                  "methods": {
                    "get": {
                      "description": "Gets an existing user workloads Secret. Values of the \"data\" field in the response are cleared. This method is supported for Cloud Composer environments in versions composer-3-airflow-*.*.*-build.* and newer.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}/userWorkloadsSecrets/{userWorkloadsSecretsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloudcomposer",
                        "https://www.googleapis.com/auth/cloudcomposer.readonly"
                      ],
                      "id": "composer.projects.locations.environments.userWorkloadsSecrets.get",
                      "path": "v1/{+name}",
                      "httpMethod": "GET"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "id": "composer.projects.locations.environments.userWorkloadsSecrets.delete",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloudcomposer"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}/userWorkloadsSecrets/{userWorkloadsSecretsId}",
                      "description": "Deletes a user workloads Secret. This method is supported for Cloud Composer environments in versions composer-3-airflow-*.*.*-build.* and newer."
                    },
                    "list": {
                      "id": "composer.projects.locations.environments.userWorkloadsSecrets.list",
                      "path": "v1/{+parent}/userWorkloadsSecrets",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloudcomposer",
                        "https://www.googleapis.com/auth/cloudcomposer.readonly"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}/userWorkloadsSecrets",
                      "description": "Lists user workloads Secrets. This method is supported for Cloud Composer environments in versions composer-3-airflow-*.*.*-build.* and newer.",
                      "httpMethod": "GET"
                    },
                    "update": {
                      "httpMethod": "PUT",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}/userWorkloadsSecrets/{userWorkloadsSecretsId}",
                      "description": "Updates a user workloads Secret. This method is supported for Cloud Composer environments in versions composer-3-airflow-*.*.*-build.* and newer.",
                      "id": "composer.projects.locations.environments.userWorkloadsSecrets.update",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloudcomposer"
                      ]
                    },
                    "create": {
                      "description": "Creates a user workloads Secret. This method is supported for Cloud Composer environments in versions composer-3-airflow-*.*.*-build.* and newer.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}/userWorkloadsSecrets",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloudcomposer"
                      ],
                      "id": "composer.projects.locations.environments.userWorkloadsSecrets.create",
                      "path": "v1/{+parent}/userWorkloadsSecrets",
                      "httpMethod": "POST"
                    }
                  }
                },
                "userWorkloadsConfigMaps": {
                  "methods": {
                    "get": {
                      "id": "composer.projects.locations.environments.userWorkloadsConfigMaps.get",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloudcomposer",
                        "https://www.googleapis.com/auth/cloudcomposer.readonly"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}/userWorkloadsConfigMaps/{userWorkloadsConfigMapsId}",
                      "description": "Gets an existing user workloads ConfigMap. This method is supported for Cloud Composer environments in versions composer-3-airflow-*.*.*-build.* and newer.",
                      "httpMethod": "GET"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloudcomposer"
                      ],
                      "id": "composer.projects.locations.environments.userWorkloadsConfigMaps.delete",
                      "path": "v1/{+name}",
                      "description": "Deletes a user workloads ConfigMap. This method is supported for Cloud Composer environments in versions composer-3-airflow-*.*.*-build.* and newer.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}/userWorkloadsConfigMaps/{userWorkloadsConfigMapsId}",
                      "httpMethod": "DELETE"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "id": "composer.projects.locations.environments.userWorkloadsConfigMaps.list",
                      "path": "v1/{+parent}/userWorkloadsConfigMaps",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloudcomposer",
                        "https://www.googleapis.com/auth/cloudcomposer.readonly"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}/userWorkloadsConfigMaps",
                      "description": "Lists user workloads ConfigMaps. This method is supported for Cloud Composer environments in versions composer-3-airflow-*.*.*-build.* and newer."
                    },
                    "update": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloudcomposer"
                      ],
                      "id": "composer.projects.locations.environments.userWorkloadsConfigMaps.update",
                      "path": "v1/{+name}",
                      "description": "Updates a user workloads ConfigMap. This method is supported for Cloud Composer environments in versions composer-3-airflow-*.*.*-build.* and newer.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}/userWorkloadsConfigMaps/{userWorkloadsConfigMapsId}",
                      "httpMethod": "PUT"
                    },
                    "create": {
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}/userWorkloadsConfigMaps",
                      "description": "Creates a user workloads ConfigMap. This method is supported for Cloud Composer environments in versions composer-3-airflow-*.*.*-build.* and newer.",
                      "id": "composer.projects.locations.environments.userWorkloadsConfigMaps.create",
                      "path": "v1/{+parent}/userWorkloadsConfigMaps",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloudcomposer"
                      ]
                    }
                  }
                },
                "workloads": {
                  "methods": {
                    "list": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/environments/{environmentsId}/workloads",
                      "description": "Lists workloads in a Cloud Composer environment. Workload is a unit that runs a single Composer component. This method is supported for Cloud Composer environments in versions composer-2.*.*-airflow-*.*.* and newer.",
                      "id": "composer.projects.locations.environments.workloads.list",
                      "path": "v1/{+parent}/workloads",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloudcomposer",
                        "https://www.googleapis.com/auth/cloudcomposer.readonly"
                      ],
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            },
            "operations": {
              "methods": {
                "list": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                  "id": "composer.projects.locations.operations.list",
                  "path": "v1/{+name}/operations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer",
                    "https://www.googleapis.com/auth/cloudcomposer.readonly"
                  ],
                  "httpMethod": "GET"
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "composer.projects.locations.operations.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer",
                    "https://www.googleapis.com/auth/cloudcomposer.readonly"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloudcomposer"
                  ],
                  "id": "composer.projects.locations.operations.delete",
                  "path": "v1/{+name}",
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "httpMethod": "DELETE"
                }
              }
            }
          }
        }
      }
    }
  },
  "description": "Manages Apache Airflow environments on Google Cloud Platform.",
  "documentationLink": "https://cloud.google.com/composer/",
  "protocol": "rest",
  "rootUrl": "https://composer.googleapis.com/",
  "mtlsRootUrl": "https://composer.mtls.googleapis.com/",
  "name": "composer",
  "id": "composer:v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloudcomposer.readonly": {
          "description": "See your Google Cloud Composer data and the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/cloudcomposer": {
          "description": "See, edit, configure, and delete your Google Cloud Composer data and see the email address for your Google Account"
        }
      }
    }
  },
  "revision": "20260408",
  "ownerName": "Google",
  "version": "v1",
  "fullyEncodeReservedExpansion": true,
  "basePath": "",
  "servicePath": "",
  "ownerDomain": "google.com",
  "batchPath": "batch"
}