{
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "description": "A unified, intelligent governance solution for data and AI assets.",
  "version": "v1",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "rootUrl": "https://dataplex.googleapis.com/",
  "mtlsRootUrl": "https://dataplex.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud services and see the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/dataplex.read-write": {
          "description": "See, edit, configure, and delete your Google Cloud Dataplex data and see the email address for your Google Account"
        },
        "https://www.googleapis.com/auth/dataplex.readonly": {
          "description": "See your Google Cloud Dataplex data and the email address of your Google Account"
        }
      }
    }
  },
  "title": "Cloud Dataplex API",
  "revision": "20260402",
  "name": "dataplex",
  "batchPath": "batch",
  "basePath": "",
  "fullyEncodeReservedExpansion": true,
  "id": "dataplex:v1",
  "documentationLink": "https://cloud.google.com/dataplex/docs",
  "resources": {
    "organizations": {
      "resources": {
        "locations": {
          "resources": {
            "operations": {
              "methods": {
                "list": {
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/operations",
                  "httpMethod": "GET",
                  "id": "dataplex.organizations.locations.operations.list",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns UNIMPLEMENTED.",
                  "path": "v1/{+name}/operations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "delete": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/operations/{operationsId}",
                  "httpMethod": "DELETE",
                  "id": "dataplex.organizations.locations.operations.delete",
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED."
                },
                "get": {
                  "httpMethod": "GET",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/operations/{operationsId}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "id": "dataplex.organizations.locations.operations.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "cancel": {
                  "id": "dataplex.organizations.locations.operations.cancel",
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it beco[...]",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/operations/{operationsId}:cancel",
                  "httpMethod": "POST",
                  "path": "v1/{+name}:cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            },
            "encryptionConfigs": {
              "methods": {
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}",
                  "description": "Delete an EncryptionConfig.",
                  "id": "dataplex.organizations.locations.encryptionConfigs.delete",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "getIamPolicy": {
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}:getIamPolicy",
                  "httpMethod": "GET",
                  "id": "dataplex.organizations.locations.encryptionConfigs.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "testIamPermissions": {
                  "id": "dataplex.organizations.locations.encryptionConfigs.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}:testIamPermissions",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "patch": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Update an EncryptionConfig.",
                  "id": "dataplex.organizations.locations.encryptionConfigs.patch",
                  "httpMethod": "PATCH",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}"
                },
                "list": {
                  "path": "v1/{+parent}/encryptionConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "List EncryptionConfigs.",
                  "id": "dataplex.organizations.locations.encryptionConfigs.list",
                  "httpMethod": "GET",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs"
                },
                "create": {
                  "path": "v1/{+parent}/encryptionConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs",
                  "httpMethod": "POST",
                  "id": "dataplex.organizations.locations.encryptionConfigs.create",
                  "description": "Create an EncryptionConfig."
                },
                "get": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}",
                  "description": "Get an EncryptionConfig.",
                  "id": "dataplex.organizations.locations.encryptionConfigs.get"
                },
                "setIamPolicy": {
                  "id": "dataplex.organizations.locations.encryptionConfigs.setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}:setIamPolicy",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "projects": {
      "resources": {
        "locations": {
          "resources": {
            "dataScans": {
              "methods": {
                "patch": {
                  "id": "dataplex.projects.locations.dataScans.patch",
                  "description": "Updates a DataScan resource.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}",
                  "httpMethod": "PATCH",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "generateDataQualityRules": {
                  "description": "Generates recommended data quality rules based on the results of a data profiling scan.Use the recommendations to build rules for a data quality scan.",
                  "id": "dataplex.projects.locations.dataScans.generateDataQualityRules",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:generateDataQualityRules",
                  "path": "v1/{+name}:generateDataQualityRules",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:testIamPermissions",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.dataScans.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                },
                "delete": {
                  "id": "dataplex.projects.locations.dataScans.delete",
                  "description": "Deletes a DataScan resource.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}",
                  "httpMethod": "DELETE",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "get": {
                  "description": "Gets a DataScan resource.",
                  "id": "dataplex.projects.locations.dataScans.get",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ]
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:setIamPolicy",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.dataScans.setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                },
                "list": {
                  "path": "v1/{+parent}/dataScans",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans",
                  "description": "Lists DataScans.",
                  "id": "dataplex.projects.locations.dataScans.list"
                },
                "getIamPolicy": {
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataplex.projects.locations.dataScans.getIamPolicy",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "create": {
                  "path": "v1/{+parent}/dataScans",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.dataScans.create",
                  "description": "Creates a DataScan resource.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans",
                  "httpMethod": "POST"
                },
                "run": {
                  "id": "dataplex.projects.locations.dataScans.run",
                  "description": "Runs an on-demand execution of a DataScan",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:run",
                  "httpMethod": "POST",
                  "path": "v1/{+name}:run",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              },
              "resources": {
                "jobs": {
                  "methods": {
                    "get": {
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}/jobs/{jobsId}",
                      "description": "Gets a DataScanJob resource.",
                      "id": "dataplex.projects.locations.dataScans.jobs.get",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "list": {
                      "description": "Lists DataScanJobs under the given DataScan.",
                      "id": "dataplex.projects.locations.dataScans.jobs.list",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}/jobs",
                      "path": "v1/{+parent}/jobs",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "generateDataQualityRules": {
                      "id": "dataplex.projects.locations.dataScans.jobs.generateDataQualityRules",
                      "description": "Generates recommended data quality rules based on the results of a data profiling scan.Use the recommendations to build rules for a data quality scan.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}/jobs/{jobsId}:generateDataQualityRules",
                      "httpMethod": "POST",
                      "path": "v1/{+name}:generateDataQualityRules",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    }
                  }
                }
              }
            },
            "metadataFeeds": {
              "methods": {
                "delete": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.metadataFeeds.delete",
                  "description": "Deletes a MetadataFeed.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds/{metadataFeedsId}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.metadataFeeds.list",
                  "description": "Retrieve a list of MetadataFeeds.",
                  "path": "v1/{+parent}/metadataFeeds",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "patch": {
                  "id": "dataplex.projects.locations.metadataFeeds.patch",
                  "description": "Updates a MetadataFeed.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds/{metadataFeedsId}",
                  "httpMethod": "PATCH",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "create": {
                  "path": "v1/{+parent}/metadataFeeds",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.metadataFeeds.create",
                  "description": "Creates a MetadataFeed."
                },
                "get": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds/{metadataFeedsId}",
                  "description": "Gets a MetadataFeed.",
                  "id": "dataplex.projects.locations.metadataFeeds.get"
                }
              }
            },
            "policyIntents": {
              "methods": {
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/policyIntents/{policyIntentsId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataplex.projects.locations.policyIntents.getIamPolicy"
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/policyIntents/{policyIntentsId}:testIamPermissions",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.policyIntents.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.policyIntents.setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/policyIntents/{policyIntentsId}:setIamPolicy",
                  "httpMethod": "POST"
                }
              }
            },
            "operations": {
              "methods": {
                "get": {
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "id": "dataplex.projects.locations.operations.get",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "cancel": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}:cancel",
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it beco[...]",
                  "id": "dataplex.projects.locations.operations.cancel",
                  "path": "v1/{+name}:cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "delete": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED.",
                  "id": "dataplex.projects.locations.operations.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}"
                },
                "list": {
                  "path": "v1/{+name}/operations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.operations.list",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns UNIMPLEMENTED."
                }
              }
            },
            "aspectTypes": {
              "methods": {
                "setIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}:setIamPolicy",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.aspectTypes.setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "patch": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}",
                  "httpMethod": "PATCH",
                  "id": "dataplex.projects.locations.aspectTypes.patch",
                  "description": "Updates an AspectType.",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes",
                  "description": "Lists AspectType resources in a project and location.",
                  "id": "dataplex.projects.locations.aspectTypes.list",
                  "path": "v1/{+parent}/aspectTypes",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ]
                },
                "delete": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}",
                  "description": "Deletes an AspectType.",
                  "id": "dataplex.projects.locations.aspectTypes.delete"
                },
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataplex.projects.locations.aspectTypes.getIamPolicy",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}:getIamPolicy"
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.aspectTypes.testIamPermissions"
                },
                "create": {
                  "path": "v1/{+parent}/aspectTypes",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.aspectTypes.create",
                  "description": "Creates an AspectType."
                },
                "get": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.aspectTypes.get",
                  "description": "Gets an AspectType."
                }
              }
            },
            "changeRequests": {
              "methods": {
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.changeRequests.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/changeRequests/{changeRequestsId}:getIamPolicy",
                  "httpMethod": "GET"
                },
                "testIamPermissions": {
                  "id": "dataplex.projects.locations.changeRequests.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/changeRequests/{changeRequestsId}:testIamPermissions",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "setIamPolicy": {
                  "id": "dataplex.projects.locations.changeRequests.setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/changeRequests/{changeRequestsId}:setIamPolicy",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            },
            "dataTaxonomies": {
              "resources": {
                "attributes": {
                  "methods": {
                    "patch": {
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}",
                      "httpMethod": "PATCH",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.patch",
                      "deprecated": true,
                      "description": "Updates a DataAttribute resource."
                    },
                    "list": {
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.list",
                      "deprecated": true,
                      "description": "Lists Data Attribute resources in a DataTaxonomy.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes",
                      "httpMethod": "GET",
                      "path": "v1/{+parent}/attributes",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "getIamPolicy": {
                      "path": "v1/{+resource}:getIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}:getIamPolicy",
                      "httpMethod": "GET"
                    },
                    "testIamPermissions": {
                      "path": "v1/{+resource}:testIamPermissions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}:testIamPermissions",
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.testIamPermissions"
                    },
                    "delete": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}",
                      "httpMethod": "DELETE",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.delete",
                      "deprecated": true,
                      "description": "Deletes a Data Attribute resource.",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "create": {
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.create",
                      "deprecated": true,
                      "description": "Create a DataAttribute resource.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes",
                      "httpMethod": "POST",
                      "path": "v1/{+parent}/attributes",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "get": {
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.get",
                      "deprecated": true,
                      "description": "Retrieves a Data Attribute resource.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}",
                      "httpMethod": "GET"
                    },
                    "setIamPolicy": {
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.setIamPolicy",
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}:setIamPolicy",
                      "httpMethod": "POST",
                      "path": "v1/{+resource}:setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    }
                  }
                }
              },
              "methods": {
                "create": {
                  "path": "v1/{+parent}/dataTaxonomies",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies",
                  "description": "Create a DataTaxonomy resource.",
                  "id": "dataplex.projects.locations.dataTaxonomies.create",
                  "deprecated": true
                },
                "get": {
                  "id": "dataplex.projects.locations.dataTaxonomies.get",
                  "deprecated": true,
                  "description": "Retrieves a DataTaxonomy resource.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "getIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}:getIamPolicy",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.dataTaxonomies.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "testIamPermissions": {
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.dataTaxonomies.testIamPermissions",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}:testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "delete": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}",
                  "description": "Deletes a DataTaxonomy resource. All attributes within the DataTaxonomy must be deleted before the DataTaxonomy can be deleted.",
                  "id": "dataplex.projects.locations.dataTaxonomies.delete",
                  "deprecated": true
                },
                "patch": {
                  "id": "dataplex.projects.locations.dataTaxonomies.patch",
                  "deprecated": true,
                  "description": "Updates a DataTaxonomy resource.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}",
                  "httpMethod": "PATCH",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "list": {
                  "description": "Lists DataTaxonomy resources in a project and location.",
                  "id": "dataplex.projects.locations.dataTaxonomies.list",
                  "deprecated": true,
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies",
                  "path": "v1/{+parent}/dataTaxonomies",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}:setIamPolicy",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.dataTaxonomies.setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                }
              }
            },
            "dataProducts": {
              "resources": {
                "dataAssets": {
                  "methods": {
                    "create": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets",
                      "httpMethod": "POST",
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.create",
                      "description": "Creates a data asset.",
                      "path": "v1/{+parent}/dataAssets",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "get": {
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "description": "Gets a data asset.",
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.get",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets/{dataAssetsId}"
                    },
                    "patch": {
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets/{dataAssetsId}",
                      "httpMethod": "PATCH",
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.patch",
                      "description": "Updates a data asset."
                    },
                    "list": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.list",
                      "description": "Lists data assets for a given data product.",
                      "path": "v1/{+parent}/dataAssets",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "delete": {
                      "description": "Deletes a data asset.",
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.delete",
                      "httpMethod": "DELETE",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets/{dataAssetsId}",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    }
                  }
                }
              },
              "methods": {
                "list": {
                  "path": "v1/{+parent}/dataProducts",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.dataProducts.list",
                  "description": "Lists data products for a given project."
                },
                "patch": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Updates a data product.",
                  "id": "dataplex.projects.locations.dataProducts.patch",
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}"
                },
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}:getIamPolicy",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.dataProducts.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                },
                "testIamPermissions": {
                  "id": "dataplex.projects.locations.dataProducts.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}:testIamPermissions",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "delete": {
                  "description": "Deletes a data product. The deletion will fail if the data product is not empty (i.e. contains at least one data asset).",
                  "id": "dataplex.projects.locations.dataProducts.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts",
                  "description": "Creates a data product.",
                  "id": "dataplex.projects.locations.dataProducts.create",
                  "path": "v1/{+parent}/dataProducts",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "get": {
                  "id": "dataplex.projects.locations.dataProducts.get",
                  "description": "Gets a data product.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ]
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataplex.projects.locations.dataProducts.setIamPolicy"
                }
              }
            },
            "entryGroups": {
              "methods": {
                "create": {
                  "path": "v1/{+parent}/entryGroups",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups",
                  "description": "Creates an EntryGroup.",
                  "id": "dataplex.projects.locations.entryGroups.create"
                },
                "get": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.entryGroups.get",
                  "description": "Gets an EntryGroup."
                },
                "delete": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}",
                  "httpMethod": "DELETE",
                  "id": "dataplex.projects.locations.entryGroups.delete",
                  "description": "Deletes an EntryGroup.",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "getIamPolicy": {
                  "id": "dataplex.projects.locations.entryGroups.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}:getIamPolicy",
                  "httpMethod": "GET",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.entryGroups.testIamPermissions",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}:testIamPermissions"
                },
                "patch": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}",
                  "httpMethod": "PATCH",
                  "id": "dataplex.projects.locations.entryGroups.patch",
                  "description": "Updates an EntryGroup."
                },
                "list": {
                  "path": "v1/{+parent}/entryGroups",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups",
                  "description": "Lists EntryGroup resources in a project and location.",
                  "id": "dataplex.projects.locations.entryGroups.list"
                },
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataplex.projects.locations.entryGroups.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              },
              "resources": {
                "entryLinks": {
                  "methods": {
                    "delete": {
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.entryGroups.entryLinks.delete",
                      "description": "Deletes an Entry Link.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entryLinks/{entryLinksId}",
                      "httpMethod": "DELETE"
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entryLinks/{entryLinksId}",
                      "description": "Updates an Entry Link.",
                      "id": "dataplex.projects.locations.entryGroups.entryLinks.patch",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "create": {
                      "description": "Creates an Entry Link.",
                      "id": "dataplex.projects.locations.entryGroups.entryLinks.create",
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entryLinks",
                      "path": "v1/{+parent}/entryLinks",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "get": {
                      "description": "Gets an Entry Link.",
                      "id": "dataplex.projects.locations.entryGroups.entryLinks.get",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entryLinks/{entryLinksId}",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    }
                  }
                },
                "entries": {
                  "methods": {
                    "create": {
                      "path": "v1/{+parent}/entries",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.entryGroups.entries.create",
                      "description": "Creates an Entry.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries",
                      "httpMethod": "POST"
                    },
                    "get": {
                      "description": "Gets an Entry.",
                      "id": "dataplex.projects.locations.entryGroups.entries.get",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries/{entriesId}",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries/{entriesId}",
                      "description": "Deletes an Entry.",
                      "id": "dataplex.projects.locations.entryGroups.entries.delete",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "patch": {
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries/{entriesId}",
                      "httpMethod": "PATCH",
                      "id": "dataplex.projects.locations.entryGroups.entries.patch",
                      "description": "Updates an Entry."
                    },
                    "list": {
                      "path": "v1/{+parent}/entries",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "description": "Lists Entries within an EntryGroup.",
                      "id": "dataplex.projects.locations.entryGroups.entries.list",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries"
                    }
                  }
                }
              }
            },
            "lakes": {
              "resources": {
                "zones": {
                  "resources": {
                    "assets": {
                      "methods": {
                        "setIamPolicy": {
                          "httpMethod": "POST",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}:setIamPolicy",
                          "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                          "id": "dataplex.projects.locations.lakes.zones.assets.setIamPolicy",
                          "path": "v1/{+resource}:setIamPolicy",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ]
                        },
                        "create": {
                          "path": "v1/{+parent}/assets",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "id": "dataplex.projects.locations.lakes.zones.assets.create",
                          "description": "Creates an asset resource.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets",
                          "httpMethod": "POST"
                        },
                        "get": {
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ],
                          "id": "dataplex.projects.locations.lakes.zones.assets.get",
                          "description": "Retrieves an asset resource.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}",
                          "httpMethod": "GET"
                        },
                        "patch": {
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "description": "Updates an asset resource.",
                          "id": "dataplex.projects.locations.lakes.zones.assets.patch",
                          "httpMethod": "PATCH",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}"
                        },
                        "list": {
                          "path": "v1/{+parent}/assets",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ],
                          "id": "dataplex.projects.locations.lakes.zones.assets.list",
                          "description": "Lists asset resources in a zone.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets",
                          "httpMethod": "GET"
                        },
                        "getIamPolicy": {
                          "httpMethod": "GET",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}:getIamPolicy",
                          "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                          "id": "dataplex.projects.locations.lakes.zones.assets.getIamPolicy",
                          "path": "v1/{+resource}:getIamPolicy",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ]
                        },
                        "testIamPermissions": {
                          "id": "dataplex.projects.locations.lakes.zones.assets.testIamPermissions",
                          "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}:testIamPermissions",
                          "httpMethod": "POST",
                          "path": "v1/{+resource}:testIamPermissions",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ]
                        },
                        "delete": {
                          "httpMethod": "DELETE",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}",
                          "description": "Deletes an asset resource. The referenced storage resource is detached (default) or deleted based on the associated Lifecycle policy.",
                          "id": "dataplex.projects.locations.lakes.zones.assets.delete",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ]
                        }
                      },
                      "resources": {
                        "actions": {
                          "methods": {
                            "list": {
                              "path": "v1/{+parent}/actions",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/cloud-platform.read-only",
                                "https://www.googleapis.com/auth/dataplex.read-write",
                                "https://www.googleapis.com/auth/dataplex.readonly"
                              ],
                              "description": "Lists action resources in an asset.",
                              "id": "dataplex.projects.locations.lakes.zones.assets.actions.list",
                              "httpMethod": "GET",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}/actions"
                            }
                          }
                        }
                      }
                    },
                    "actions": {
                      "methods": {
                        "list": {
                          "path": "v1/{+parent}/actions",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ],
                          "description": "Lists action resources in a zone.",
                          "id": "dataplex.projects.locations.lakes.zones.actions.list",
                          "httpMethod": "GET",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/actions"
                        }
                      }
                    },
                    "entities": {
                      "resources": {
                        "partitions": {
                          "methods": {
                            "list": {
                              "id": "dataplex.projects.locations.lakes.zones.entities.partitions.list",
                              "description": "List metadata partitions of an entity.",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}/partitions",
                              "httpMethod": "GET",
                              "path": "v1/{+parent}/partitions",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/dataplex.read-write"
                              ]
                            },
                            "delete": {
                              "id": "dataplex.projects.locations.lakes.zones.entities.partitions.delete",
                              "description": "Delete a metadata partition.",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}/partitions/{partitionsId}",
                              "httpMethod": "DELETE",
                              "path": "v1/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/dataplex.read-write"
                              ]
                            },
                            "create": {
                              "path": "v1/{+parent}/partitions",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/dataplex.read-write"
                              ],
                              "description": "Create a metadata partition.",
                              "id": "dataplex.projects.locations.lakes.zones.entities.partitions.create",
                              "httpMethod": "POST",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}/partitions"
                            },
                            "get": {
                              "path": "v1/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/dataplex.read-write"
                              ],
                              "httpMethod": "GET",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}/partitions/{partitionsId}",
                              "description": "Get a metadata partition of an entity.",
                              "id": "dataplex.projects.locations.lakes.zones.entities.partitions.get"
                            }
                          }
                        }
                      },
                      "methods": {
                        "create": {
                          "path": "v1/{+parent}/entities",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities",
                          "httpMethod": "POST",
                          "id": "dataplex.projects.locations.lakes.zones.entities.create",
                          "description": "Create a metadata entity."
                        },
                        "get": {
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "id": "dataplex.projects.locations.lakes.zones.entities.get",
                          "description": "Get a metadata entity.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}",
                          "httpMethod": "GET"
                        },
                        "delete": {
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "id": "dataplex.projects.locations.lakes.zones.entities.delete",
                          "description": "Delete a metadata entity.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}",
                          "httpMethod": "DELETE"
                        },
                        "list": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities",
                          "httpMethod": "GET",
                          "id": "dataplex.projects.locations.lakes.zones.entities.list",
                          "description": "List metadata entities in a zone.",
                          "path": "v1/{+parent}/entities",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ]
                        },
                        "update": {
                          "id": "dataplex.projects.locations.lakes.zones.entities.update",
                          "description": "Update a metadata entity. Only supports full resource update.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}",
                          "httpMethod": "PUT",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ]
                        }
                      }
                    }
                  },
                  "methods": {
                    "create": {
                      "description": "Creates a zone resource within a lake.",
                      "id": "dataplex.projects.locations.lakes.zones.create",
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones",
                      "path": "v1/{+parent}/zones",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "get": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.lakes.zones.get",
                      "description": "Retrieves a zone resource.",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "patch": {
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.lakes.zones.patch",
                      "description": "Updates a zone resource.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}",
                      "httpMethod": "PATCH"
                    },
                    "list": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.lakes.zones.list",
                      "description": "Lists zone resources in a lake.",
                      "path": "v1/{+parent}/zones",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "getIamPolicy": {
                      "path": "v1/{+resource}:getIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.lakes.zones.getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}:getIamPolicy",
                      "httpMethod": "GET"
                    },
                    "testIamPermissions": {
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                      "id": "dataplex.projects.locations.lakes.zones.testIamPermissions",
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}:testIamPermissions",
                      "path": "v1/{+resource}:testIamPermissions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "delete": {
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Deletes a zone resource. All assets within a zone must be deleted before the zone can be deleted.",
                      "id": "dataplex.projects.locations.lakes.zones.delete",
                      "httpMethod": "DELETE",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}"
                    },
                    "setIamPolicy": {
                      "path": "v1/{+resource}:setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}:setIamPolicy",
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "id": "dataplex.projects.locations.lakes.zones.setIamPolicy"
                    }
                  }
                },
                "tasks": {
                  "resources": {
                    "jobs": {
                      "methods": {
                        "list": {
                          "description": "Lists Jobs under the given task.",
                          "id": "dataplex.projects.locations.lakes.tasks.jobs.list",
                          "httpMethod": "GET",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}/jobs",
                          "path": "v1/{+parent}/jobs",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ]
                        },
                        "get": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}/jobs/{jobsId}",
                          "httpMethod": "GET",
                          "id": "dataplex.projects.locations.lakes.tasks.jobs.get",
                          "description": "Get job resource.",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ]
                        },
                        "cancel": {
                          "path": "v1/{+name}:cancel",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}/jobs/{jobsId}:cancel",
                          "httpMethod": "POST",
                          "id": "dataplex.projects.locations.lakes.tasks.jobs.cancel",
                          "description": "Cancel jobs running for the task resource."
                        }
                      }
                    }
                  },
                  "methods": {
                    "list": {
                      "path": "v1/{+parent}/tasks",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "id": "dataplex.projects.locations.lakes.tasks.list",
                      "description": "Lists tasks under the given lake.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks",
                      "httpMethod": "GET"
                    },
                    "getIamPolicy": {
                      "path": "v1/{+resource}:getIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}:getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "id": "dataplex.projects.locations.lakes.tasks.getIamPolicy"
                    },
                    "create": {
                      "path": "v1/{+parent}/tasks",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks",
                      "description": "Creates a task resource within a lake.",
                      "id": "dataplex.projects.locations.lakes.tasks.create"
                    },
                    "run": {
                      "id": "dataplex.projects.locations.lakes.tasks.run",
                      "description": "Run an on demand execution of a Task.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}:run",
                      "httpMethod": "POST",
                      "path": "v1/{+name}:run",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}",
                      "description": "Update the task resource.",
                      "id": "dataplex.projects.locations.lakes.tasks.patch",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "testIamPermissions": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}:testIamPermissions",
                      "httpMethod": "POST",
                      "id": "dataplex.projects.locations.lakes.tasks.testIamPermissions",
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                      "path": "v1/{+resource}:testIamPermissions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "delete": {
                      "description": "Delete the task resource.",
                      "id": "dataplex.projects.locations.lakes.tasks.delete",
                      "httpMethod": "DELETE",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "get": {
                      "id": "dataplex.projects.locations.lakes.tasks.get",
                      "description": "Get task resource.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}",
                      "httpMethod": "GET",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "setIamPolicy": {
                      "id": "dataplex.projects.locations.lakes.tasks.setIamPolicy",
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}:setIamPolicy",
                      "httpMethod": "POST",
                      "path": "v1/{+resource}:setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    }
                  }
                },
                "actions": {
                  "methods": {
                    "list": {
                      "description": "Lists action resources in a lake.",
                      "id": "dataplex.projects.locations.lakes.actions.list",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/actions",
                      "path": "v1/{+parent}/actions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    }
                  }
                }
              },
              "methods": {
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataplex.projects.locations.lakes.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "create": {
                  "description": "Creates a lake resource.",
                  "id": "dataplex.projects.locations.lakes.create",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes",
                  "path": "v1/{+parent}/lakes",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "get": {
                  "description": "Retrieves a lake resource.",
                  "id": "dataplex.projects.locations.lakes.get",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ]
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}",
                  "description": "Updates a lake resource.",
                  "id": "dataplex.projects.locations.lakes.patch",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes",
                  "description": "Lists lake resources in a project and location.",
                  "id": "dataplex.projects.locations.lakes.list",
                  "path": "v1/{+parent}/lakes",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ]
                },
                "getIamPolicy": {
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataplex.projects.locations.lakes.getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.lakes.testIamPermissions"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.lakes.delete",
                  "description": "Deletes a lake resource. All zones within the lake must be deleted before the lake can be deleted.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}",
                  "httpMethod": "DELETE"
                }
              }
            },
            "metadataJobs": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/metadataJobs",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.metadataJobs.list",
                  "description": "Lists metadata jobs.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataJobs",
                  "httpMethod": "GET"
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataJobs",
                  "description": "Creates a metadata job. For example, use a metadata job to import metadata from a third-party system into Dataplex Universal Catalog.",
                  "id": "dataplex.projects.locations.metadataJobs.create",
                  "path": "v1/{+parent}/metadataJobs",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "get": {
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataJobs/{metadataJobsId}",
                  "description": "Gets a metadata job.",
                  "id": "dataplex.projects.locations.metadataJobs.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "cancel": {
                  "id": "dataplex.projects.locations.metadataJobs.cancel",
                  "description": "Cancels a metadata job.If you cancel a metadata import job that is in progress, the changes in the job might be partially applied. We recommend that you reset the state of the entry groups in your project by running another metadata job that reverts the changes from the canceled job.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataJobs/{metadataJobsId}:cancel",
                  "httpMethod": "POST",
                  "path": "v1/{+name}:cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            },
            "entryLinkTypes": {
              "methods": {
                "getIamPolicy": {
                  "id": "dataplex.projects.locations.entryLinkTypes.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryLinkTypes/{entryLinkTypesId}:getIamPolicy",
                  "httpMethod": "GET",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "testIamPermissions": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryLinkTypes/{entryLinkTypesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.entryLinkTypes.testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryLinkTypes/{entryLinkTypesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataplex.projects.locations.entryLinkTypes.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            },
            "governanceRules": {
              "methods": {
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/governanceRules/{governanceRulesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataplex.projects.locations.governanceRules.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.governanceRules.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/governanceRules/{governanceRulesId}:getIamPolicy",
                  "httpMethod": "GET"
                },
                "testIamPermissions": {
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.governanceRules.testIamPermissions",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/governanceRules/{governanceRulesId}:testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            },
            "entryTypes": {
              "methods": {
                "patch": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}",
                  "description": "Updates an EntryType.",
                  "id": "dataplex.projects.locations.entryTypes.patch"
                },
                "list": {
                  "path": "v1/{+parent}/entryTypes",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "id": "dataplex.projects.locations.entryTypes.list",
                  "description": "Lists EntryType resources in a project and location.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes",
                  "httpMethod": "GET"
                },
                "delete": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}",
                  "httpMethod": "DELETE",
                  "id": "dataplex.projects.locations.entryTypes.delete",
                  "description": "Deletes an EntryType.",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.entryTypes.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}:getIamPolicy",
                  "httpMethod": "GET"
                },
                "testIamPermissions": {
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.entryTypes.testIamPermissions",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}:testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes",
                  "description": "Creates an EntryType.",
                  "id": "dataplex.projects.locations.entryTypes.create",
                  "path": "v1/{+parent}/entryTypes",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "get": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "id": "dataplex.projects.locations.entryTypes.get",
                  "description": "Gets an EntryType.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}",
                  "httpMethod": "GET"
                },
                "setIamPolicy": {
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataplex.projects.locations.entryTypes.setIamPolicy",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}:setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            },
            "glossaries": {
              "methods": {
                "setIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}:setIamPolicy",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.glossaries.setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "delete": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}",
                  "httpMethod": "DELETE",
                  "id": "dataplex.projects.locations.glossaries.delete",
                  "description": "Deletes a Glossary resource. All the categories and terms within the Glossary must be deleted before the Glossary can be deleted.",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "getIamPolicy": {
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataplex.projects.locations.glossaries.getIamPolicy",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}:getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "testIamPermissions": {
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.glossaries.testIamPermissions",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}:testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "patch": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}",
                  "httpMethod": "PATCH",
                  "id": "dataplex.projects.locations.glossaries.patch",
                  "description": "Updates a Glossary resource.",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "list": {
                  "path": "v1/{+parent}/glossaries",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "id": "dataplex.projects.locations.glossaries.list",
                  "description": "Lists Glossary resources in a project and location.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries",
                  "httpMethod": "GET"
                },
                "create": {
                  "description": "Creates a new Glossary resource.",
                  "id": "dataplex.projects.locations.glossaries.create",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries",
                  "path": "v1/{+parent}/glossaries",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "get": {
                  "description": "Gets a Glossary resource.",
                  "id": "dataplex.projects.locations.glossaries.get",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ]
                }
              },
              "resources": {
                "categories": {
                  "methods": {
                    "create": {
                      "path": "v1/{+parent}/categories",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Creates a new GlossaryCategory resource.",
                      "id": "dataplex.projects.locations.glossaries.categories.create",
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories"
                    },
                    "get": {
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.glossaries.categories.get",
                      "description": "Gets a GlossaryCategory resource."
                    },
                    "delete": {
                      "id": "dataplex.projects.locations.glossaries.categories.delete",
                      "description": "Deletes a GlossaryCategory resource. All the GlossaryCategories and GlossaryTerms nested directly under the specified GlossaryCategory will be moved one level up to the parent in the hierarchy.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}",
                      "httpMethod": "DELETE",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "getIamPolicy": {
                      "path": "v1/{+resource}:getIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}:getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "id": "dataplex.projects.locations.glossaries.categories.getIamPolicy"
                    },
                    "testIamPermissions": {
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                      "id": "dataplex.projects.locations.glossaries.categories.testIamPermissions",
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}:testIamPermissions",
                      "path": "v1/{+resource}:testIamPermissions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "patch": {
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "PATCH",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}",
                      "description": "Updates a GlossaryCategory resource.",
                      "id": "dataplex.projects.locations.glossaries.categories.patch"
                    },
                    "list": {
                      "path": "v1/{+parent}/categories",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.glossaries.categories.list",
                      "description": "Lists GlossaryCategory resources in a Glossary."
                    },
                    "setIamPolicy": {
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "id": "dataplex.projects.locations.glossaries.categories.setIamPolicy",
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}:setIamPolicy",
                      "path": "v1/{+resource}:setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    }
                  }
                },
                "terms": {
                  "methods": {
                    "create": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms",
                      "httpMethod": "POST",
                      "id": "dataplex.projects.locations.glossaries.terms.create",
                      "description": "Creates a new GlossaryTerm resource.",
                      "path": "v1/{+parent}/terms",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "get": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.glossaries.terms.get",
                      "description": "Gets a GlossaryTerm resource.",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "delete": {
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Deletes a GlossaryTerm resource.",
                      "id": "dataplex.projects.locations.glossaries.terms.delete",
                      "httpMethod": "DELETE",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}"
                    },
                    "getIamPolicy": {
                      "path": "v1/{+resource}:getIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "id": "dataplex.projects.locations.glossaries.terms.getIamPolicy",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}:getIamPolicy"
                    },
                    "testIamPermissions": {
                      "path": "v1/{+resource}:testIamPermissions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}:testIamPermissions",
                      "httpMethod": "POST",
                      "id": "dataplex.projects.locations.glossaries.terms.testIamPermissions",
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                    },
                    "patch": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}",
                      "httpMethod": "PATCH",
                      "id": "dataplex.projects.locations.glossaries.terms.patch",
                      "description": "Updates a GlossaryTerm resource.",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "list": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.glossaries.terms.list",
                      "description": "Lists GlossaryTerm resources in a Glossary.",
                      "path": "v1/{+parent}/terms",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "setIamPolicy": {
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}:setIamPolicy",
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "id": "dataplex.projects.locations.glossaries.terms.setIamPolicy",
                      "path": "v1/{+resource}:setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    }
                  }
                }
              }
            },
            "dataDomains": {
              "methods": {
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.dataDomains.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataDomains/{dataDomainsId}:getIamPolicy",
                  "httpMethod": "GET"
                },
                "testIamPermissions": {
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.dataDomains.testIamPermissions",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataDomains/{dataDomainsId}:testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataDomains/{dataDomainsId}:setIamPolicy",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.dataDomains.setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                }
              }
            },
            "dataAttributeBindings": {
              "methods": {
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataplex.projects.locations.dataAttributeBindings.setIamPolicy"
                },
                "patch": {
                  "description": "Updates a DataAttributeBinding resource.",
                  "id": "dataplex.projects.locations.dataAttributeBindings.patch",
                  "deprecated": true,
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "list": {
                  "path": "v1/{+parent}/dataAttributeBindings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.dataAttributeBindings.list",
                  "deprecated": true,
                  "description": "Lists DataAttributeBinding resources in a project and location."
                },
                "getIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}:getIamPolicy",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.dataAttributeBindings.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "testIamPermissions": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}:testIamPermissions",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.dataAttributeBindings.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "delete": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}",
                  "httpMethod": "DELETE",
                  "id": "dataplex.projects.locations.dataAttributeBindings.delete",
                  "deprecated": true,
                  "description": "Deletes a DataAttributeBinding resource. All attributes within the DataAttributeBinding must be deleted before the DataAttributeBinding can be deleted."
                },
                "create": {
                  "path": "v1/{+parent}/dataAttributeBindings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Create a DataAttributeBinding resource.",
                  "id": "dataplex.projects.locations.dataAttributeBindings.create",
                  "deprecated": true,
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings"
                },
                "get": {
                  "id": "dataplex.projects.locations.dataAttributeBindings.get",
                  "deprecated": true,
                  "description": "Retrieves a DataAttributeBinding resource.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            }
          },
          "methods": {
            "modifyEntry": {
              "path": "v1/{+name}:modifyEntry",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/dataplex.read-write"
              ],
              "description": "Modifies an entry using the permission on the source system.",
              "id": "dataplex.projects.locations.modifyEntry",
              "httpMethod": "POST",
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:modifyEntry"
            },
            "lookupEntry": {
              "description": "Looks up an entry by name using the permission on the source system.",
              "id": "dataplex.projects.locations.lookupEntry",
              "httpMethod": "GET",
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:lookupEntry",
              "path": "v1/{+name}:lookupEntry",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only",
                "https://www.googleapis.com/auth/dataplex.read-write",
                "https://www.googleapis.com/auth/dataplex.readonly"
              ]
            },
            "lookupEntryLinks": {
              "path": "v1/{+name}:lookupEntryLinks",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/dataplex.read-write"
              ],
              "id": "dataplex.projects.locations.lookupEntryLinks",
              "description": "Looks up Entry Links referencing the specified Entry.",
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:lookupEntryLinks",
              "httpMethod": "GET"
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}",
              "description": "Gets information about a location.",
              "id": "dataplex.projects.locations.get",
              "path": "v1/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/dataplex.read-write"
              ]
            },
            "list": {
              "path": "v1/{+name}/locations",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/dataplex.read-write"
              ],
              "id": "dataplex.projects.locations.list",
              "description": "Lists information about the supported locations for this service.This method lists locations based on the resource scope provided in the ListLocationsRequest.name field: Global locations: If name is empty, the method lists the public locations available to all projects. Project-specific locations: If name follows the format projects/{project}, the method lists locations visible to that specific project. This includes public, private, or other project-specific locati[...]",
              "flatPath": "v1/projects/{projectsId}/locations",
              "httpMethod": "GET"
            },
            "searchEntries": {
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:searchEntries",
              "httpMethod": "POST",
              "id": "dataplex.projects.locations.searchEntries",
              "description": "Searches for Entries matching the given query and scope.",
              "path": "v1/{+name}:searchEntries",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only",
                "https://www.googleapis.com/auth/dataplex.read-write",
                "https://www.googleapis.com/auth/dataplex.readonly"
              ]
            },
            "lookupContext": {
              "path": "v1/{+name}:lookupContext",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only",
                "https://www.googleapis.com/auth/dataplex.read-write",
                "https://www.googleapis.com/auth/dataplex.readonly"
              ],
              "description": "Looks up LLM Context for the specified resources.",
              "id": "dataplex.projects.locations.lookupContext",
              "httpMethod": "POST",
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:lookupContext"
            }
          }
        }
      }
    }
  },
  "protocol": "rest",
  "baseUrl": "https://dataplex.googleapis.com/",
  "canonicalName": "Cloud Dataplex",
  "version_module": true,
  "servicePath": ""
}