{
  "id": "dataproc:v1",
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "title": "Cloud Dataproc API",
  "servicePath": "",
  "ownerName": "Google",
  "canonicalName": "Dataproc",
  "baseUrl": "https://dataproc.googleapis.com/",
  "rootUrl": "https://dataproc.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dataproc": {
          "description": "See, edit, configure, and delete your Google Cloud Dataproc data and see the email address for your Google Account"
        },
        "https://www.googleapis.com/auth/dataproc.read-only": {
          "description": "See your Google Cloud Dataproc data and the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        }
      }
    }
  },
  "protocol": "rest",
  "resources": {
    "projects": {
      "resources": {
        "locations": {
          "resources": {
            "autoscalingPolicies": {
              "methods": {
                "getIamPolicy": {
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.autoscalingPolicies.getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}:getIamPolicy"
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.autoscalingPolicies.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Creates new autoscaling policy.",
                  "path": "v1/{+parent}/autoscalingPolicies",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies"
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}:setIamPolicy",
                  "id": "dataproc.projects.locations.autoscalingPolicies.setIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                },
                "list": {
                  "path": "v1/{+parent}/autoscalingPolicies",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Lists autoscaling policies in the project.",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.locations.autoscalingPolicies.list"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "dataproc.projects.locations.autoscalingPolicies.delete",
                  "description": "Deletes an autoscaling policy. It is an error to delete an autoscaling policy that is in use by one or more clusters.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}"
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}:testIamPermissions",
                  "id": "dataproc.projects.locations.autoscalingPolicies.testIamPermissions",
                  "httpMethod": "POST",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "update": {
                  "description": "Updates (replaces) autoscaling policy.Disabled check for update_mask, because all updates will be full replacements.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.locations.autoscalingPolicies.update",
                  "httpMethod": "PUT",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}"
                },
                "get": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Retrieves autoscaling policy.",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.locations.autoscalingPolicies.get"
                }
              }
            },
            "sessions": {
              "resources": {
                "sparkApplications": {
                  "methods": {
                    "accessStageAttempt": {
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessStageAttempt",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to a spark stage attempt for a Spark Application.",
                      "path": "v1/{+name}:accessStageAttempt",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessStageAttempt"
                    },
                    "searchExecutors": {
                      "path": "v1/{+name}:searchExecutors",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchExecutors",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchExecutors",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to executors for a Spark Application."
                    },
                    "summarizeStageAttemptTasks": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain summary of Tasks for a Spark Application Stage Attempt",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.summarizeStageAttemptTasks",
                      "httpMethod": "GET",
                      "path": "v1/{+name}:summarizeStageAttemptTasks",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:summarizeStageAttemptTasks"
                    },
                    "searchSqlQueries": {
                      "path": "v1/{+name}:searchSqlQueries",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchSqlQueries",
                      "parameters": {
                        "parent": {
                          "type": "string",
                          "location": "query",
                          "description": "Required. Parent (Session) resource reference."
                        },
                        "details": {
                          "type": "boolean",
                          "location": "query",
                          "description": "Optional. Lists/ hides details of Spark plan nodes. True is set to list and false to hide."
                        },
                        "planDescription": {
                          "type": "boolean",
                          "description": "Optional. Enables/ disables physical plan description on demand",
                          "location": "query"
                        },
                        "name": {
                          "location": "path",
                          "required": true,
                          "type": "string",
                          "description": "Required. The fully qualified name of the session to retrieve in the format \"projects/PROJECT_ID/locations/DATAPROC_REGION/sessions/SESSION_ID/sparkApplications/APPLICATION_ID\"",
                          "pattern": "^projects/[^/]+/locations/[^/]+/sessions/[^/]+/sparkApplications/[^/]+$"
                        },
                        "pageSize": {
                          "description": "Optional. Maximum number of queries to return in each response. The service may return fewer than this. The default page size is 10; the maximum page size is 100.",
                          "location": "query",
                          "format": "int32",
                          "type": "integer"
                        },
                        "pageToken": {
                          "description": "Optional. A page token received from a previous SearchSessionSparkApplicationSqlQueries call. Provide this token to retrieve the subsequent page.",
                          "location": "query",
                          "type": "string"
                        },
                        "operationIds": {
                          "type": "string",
                          "description": "Optional. List of Spark Connect operation IDs to filter by if provided.",
                          "location": "query",
                          "repeated": true
                        }
                      },
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to SQL Queries for a Spark Application.",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchSqlQueries"
                    },
                    "accessEnvironmentInfo": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain environment details for a Spark Application",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessEnvironmentInfo",
                      "path": "v1/{+name}:accessEnvironmentInfo",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessEnvironmentInfo"
                    },
                    "search": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain high level information and list of Spark Applications corresponding to a batch",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.search",
                      "httpMethod": "GET",
                      "path": "v1/{+parent}/sparkApplications:search",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications:search"
                    },
                    "searchStageAttemptTasks": {
                      "path": "v1/{+name}:searchStageAttemptTasks",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchStageAttemptTasks",
                      "description": "Obtain data corresponding to tasks for a spark stage attempt for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchStageAttemptTasks"
                    },
                    "searchJobs": {
                      "path": "v1/{+name}:searchJobs",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchJobs",
                      "description": "Obtain list of spark jobs corresponding to a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchJobs"
                    },
                    "summarizeExecutors": {
                      "path": "v1/{+name}:summarizeExecutors",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:summarizeExecutors",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.summarizeExecutors",
                      "description": "Obtain summary of Executor Summary for a Spark Application",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "searchStageAttempts": {
                      "path": "v1/{+name}:searchStageAttempts",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchStageAttempts",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to a spark stage attempts for a Spark Application.",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchStageAttempts"
                    },
                    "accessJob": {
                      "path": "v1/{+name}:accessJob",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessJob",
                      "description": "Obtain data corresponding to a spark job for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessJob",
                      "httpMethod": "GET"
                    },
                    "summarizeStages": {
                      "path": "v1/{+name}:summarizeStages",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:summarizeStages",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain summary of Stages for a Spark Application",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.summarizeStages",
                      "httpMethod": "GET"
                    },
                    "access": {
                      "path": "v1/{+name}:access",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:access",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.access",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain high level information corresponding to a single Spark Application."
                    },
                    "searchExecutorStageSummary": {
                      "path": "v1/{+name}:searchExecutorStageSummary",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchExecutorStageSummary",
                      "description": "Obtain executor summary with respect to a spark stage attempt.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchExecutorStageSummary",
                      "httpMethod": "GET"
                    },
                    "write": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "description": "Write wrapper objects from dataplane to spanner",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.write",
                      "httpMethod": "POST",
                      "path": "v1/{+name}:write",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:write"
                    },
                    "searchStages": {
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchStages",
                      "description": "Obtain data corresponding to stages for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "path": "v1/{+name}:searchStages",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchStages"
                    },
                    "accessSqlQuery": {
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessSqlQuery",
                      "description": "Obtain data corresponding to a particular SQL Query for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "path": "v1/{+name}:accessSqlQuery",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessSqlQuery"
                    },
                    "accessSqlPlan": {
                      "path": "v1/{+name}:accessSqlPlan",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessSqlPlan",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessSqlPlan",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain Spark Plan Graph for a Spark Application SQL execution. Limits the number of clusters returned as part of the graph to 10000."
                    },
                    "accessStageRddGraph": {
                      "description": "Obtain RDD operation graph for a Spark Application Stage. Limits the number of clusters returned as part of the graph to 10000.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessStageRddGraph",
                      "path": "v1/{+name}:accessStageRddGraph",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessStageRddGraph"
                    },
                    "summarizeJobs": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain summary of Jobs for a Spark Application",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.summarizeJobs",
                      "path": "v1/{+name}:summarizeJobs",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:summarizeJobs"
                    }
                  }
                }
              },
              "methods": {
                "terminate": {
                  "path": "v1/{+name}:terminate",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}:terminate",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Terminates the interactive session.",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.sessions.terminate"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Deletes the interactive session resource. If the session is not in terminal state, it is terminated, and then deleted.",
                  "id": "dataproc.projects.locations.sessions.delete",
                  "httpMethod": "DELETE",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}"
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "dataproc.projects.locations.sessions.get",
                  "description": "Gets the resource representation for an interactive session.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}"
                },
                "create": {
                  "path": "v1/{+parent}/sessions",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Create an interactive session asynchronously.",
                  "id": "dataproc.projects.locations.sessions.create",
                  "httpMethod": "POST"
                },
                "list": {
                  "description": "Lists interactive sessions.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "httpMethod": "GET",
                  "id": "dataproc.projects.locations.sessions.list",
                  "path": "v1/{+parent}/sessions",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions"
                }
              }
            },
            "workflowTemplates": {
              "methods": {
                "instantiate": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.workflowTemplates.instantiate",
                  "description": "Instantiates a template and begins execution.The returned Operation can be used to track execution of workflow by polling operations.get. The Operation will complete when entire workflow is finished.The running workflow can be aborted via operations.cancel. This will cause any inflight jobs to be cancelled and workflow-owned clusters to be deleted.The Operation.metadata will be WorkflowMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.d[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+name}:instantiate",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}:instantiate"
                },
                "getIamPolicy": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.workflowTemplates.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}:getIamPolicy"
                },
                "list": {
                  "path": "v1/{+parent}/workflowTemplates",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.locations.workflowTemplates.list",
                  "description": "Lists workflows that match the specified filter in the request.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ]
                },
                "testIamPermissions": {
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.workflowTemplates.testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}:testIamPermissions"
                },
                "instantiateInline": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Instantiates a template and begins execution.This method is equivalent to executing the sequence CreateWorkflowTemplate, InstantiateWorkflowTemplate, DeleteWorkflowTemplate.The returned Operation can be used to track execution of workflow by polling operations.get. The Operation will complete when entire workflow is finished.The running workflow can be aborted via operations.cancel. This will cause any inflight jobs to be cancelled and workflow-owned clusters to[...]",
                  "id": "dataproc.projects.locations.workflowTemplates.instantiateInline",
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/workflowTemplates:instantiateInline",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates:instantiateInline"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Deletes a workflow template. It does not cancel in-progress workflows.",
                  "httpMethod": "DELETE",
                  "id": "dataproc.projects.locations.workflowTemplates.delete",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Retrieves the latest workflow template.Can retrieve previously instantiated template by specifying optional version parameter.",
                  "id": "dataproc.projects.locations.workflowTemplates.get",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}"
                },
                "update": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Updates (replaces) workflow template. The updated template must contain version that matches the current server version.",
                  "httpMethod": "PUT",
                  "id": "dataproc.projects.locations.workflowTemplates.update"
                },
                "create": {
                  "id": "dataproc.projects.locations.workflowTemplates.create",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Creates new workflow template.",
                  "path": "v1/{+parent}/workflowTemplates",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates"
                },
                "setIamPolicy": {
                  "id": "dataproc.projects.locations.workflowTemplates.setIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}:setIamPolicy"
                }
              }
            },
            "operations": {
              "methods": {
                "delete": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "id": "dataproc.projects.locations.operations.delete",
                  "httpMethod": "DELETE",
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "list": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.locations.operations.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns UNIMPLEMENTED."
                },
                "get": {
                  "id": "dataproc.projects.locations.operations.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}"
                },
                "cancel": {
                  "path": "v1/{+name}:cancel",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}:cancel",
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it beco[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.locations.operations.cancel",
                  "httpMethod": "POST"
                }
              }
            },
            "sessionTemplates": {
              "methods": {
                "patch": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates/{sessionTemplatesId}",
                  "description": "Updates the session template synchronously.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "PATCH",
                  "id": "dataproc.projects.locations.sessionTemplates.patch"
                },
                "create": {
                  "description": "Create a session template synchronously.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.sessionTemplates.create",
                  "path": "v1/{+parent}/sessionTemplates",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates"
                },
                "list": {
                  "id": "dataproc.projects.locations.sessionTemplates.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Lists session templates.",
                  "path": "v1/{+parent}/sessionTemplates",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "dataproc.projects.locations.sessionTemplates.delete",
                  "description": "Deletes a session template.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates/{sessionTemplatesId}"
                },
                "get": {
                  "id": "dataproc.projects.locations.sessionTemplates.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Gets the resource representation for a session template.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates/{sessionTemplatesId}"
                }
              }
            },
            "batches": {
              "methods": {
                "delete": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}",
                  "id": "dataproc.projects.locations.batches.delete",
                  "httpMethod": "DELETE",
                  "description": "Deletes the batch workload resource. If the batch is not in a CANCELLED, SUCCEEDED or FAILED State, the delete operation fails and the response returns FAILED_PRECONDITION.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "analyze": {
                  "path": "v1/{+name}:analyze",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}:analyze",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Analyze a Batch for possible recommendations and insights.",
                  "id": "dataproc.projects.locations.batches.analyze",
                  "httpMethod": "POST"
                },
                "get": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.locations.batches.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Gets the batch workload resource representation."
                },
                "create": {
                  "path": "v1/{+parent}/batches",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches",
                  "description": "Creates a batch workload that executes asynchronously.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.batches.create"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Lists batch workloads.",
                  "id": "dataproc.projects.locations.batches.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/batches",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches"
                }
              },
              "resources": {
                "sparkApplications": {
                  "methods": {
                    "access": {
                      "path": "v1/{+name}:access",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:access",
                      "id": "dataproc.projects.locations.batches.sparkApplications.access",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain high level information corresponding to a single Spark Application."
                    },
                    "searchStageAttempts": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to a spark stage attempts for a Spark Application.",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchStageAttempts",
                      "path": "v1/{+name}:searchStageAttempts",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchStageAttempts"
                    },
                    "accessJob": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to a spark job for a Spark Application.",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessJob",
                      "path": "v1/{+name}:accessJob",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessJob"
                    },
                    "summarizeStages": {
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.summarizeStages",
                      "description": "Obtain summary of Stages for a Spark Application",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "path": "v1/{+name}:summarizeStages",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:summarizeStages"
                    },
                    "searchExecutorStageSummary": {
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchExecutorStageSummary",
                      "httpMethod": "GET",
                      "description": "Obtain executor summary with respect to a spark stage attempt.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "path": "v1/{+name}:searchExecutorStageSummary",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchExecutorStageSummary"
                    },
                    "write": {
                      "httpMethod": "POST",
                      "id": "dataproc.projects.locations.batches.sparkApplications.write",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "description": "Write wrapper objects from dataplane to spanner",
                      "path": "v1/{+name}:write",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:write"
                    },
                    "searchStages": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to stages for a Spark Application.",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchStages",
                      "path": "v1/{+name}:searchStages",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchStages"
                    },
                    "accessStageRddGraph": {
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessStageRddGraph",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain RDD operation graph for a Spark Application Stage. Limits the number of clusters returned as part of the graph to 10000.",
                      "path": "v1/{+name}:accessStageRddGraph",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessStageRddGraph"
                    },
                    "accessSqlQuery": {
                      "path": "v1/{+name}:accessSqlQuery",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessSqlQuery",
                      "description": "Obtain data corresponding to a particular SQL Query for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessSqlQuery"
                    },
                    "accessSqlPlan": {
                      "path": "v1/{+name}:accessSqlPlan",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessSqlPlan",
                      "description": "Obtain Spark Plan Graph for a Spark Application SQL execution. Limits the number of clusters returned as part of the graph to 10000.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessSqlPlan",
                      "httpMethod": "GET"
                    },
                    "summarizeJobs": {
                      "path": "v1/{+name}:summarizeJobs",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:summarizeJobs",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain summary of Jobs for a Spark Application",
                      "id": "dataproc.projects.locations.batches.sparkApplications.summarizeJobs",
                      "httpMethod": "GET"
                    },
                    "accessStageAttempt": {
                      "path": "v1/{+name}:accessStageAttempt",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessStageAttempt",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessStageAttempt",
                      "description": "Obtain data corresponding to a spark stage attempt for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "searchExecutors": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to executors for a Spark Application.",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchExecutors",
                      "path": "v1/{+name}:searchExecutors",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchExecutors"
                    },
                    "summarizeStageAttemptTasks": {
                      "path": "v1/{+name}:summarizeStageAttemptTasks",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:summarizeStageAttemptTasks",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.summarizeStageAttemptTasks",
                      "description": "Obtain summary of Tasks for a Spark Application Stage Attempt",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "search": {
                      "path": "v1/{+parent}/sparkApplications:search",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications:search",
                      "description": "Obtain high level information and list of Spark Applications corresponding to a batch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.search"
                    },
                    "searchStageAttemptTasks": {
                      "description": "Obtain data corresponding to tasks for a spark stage attempt for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchStageAttemptTasks",
                      "path": "v1/{+name}:searchStageAttemptTasks",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchStageAttemptTasks"
                    },
                    "searchSqlQueries": {
                      "path": "v1/{+name}:searchSqlQueries",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchSqlQueries",
                      "description": "Obtain data corresponding to SQL Queries for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchSqlQueries"
                    },
                    "accessEnvironmentInfo": {
                      "path": "v1/{+name}:accessEnvironmentInfo",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessEnvironmentInfo",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessEnvironmentInfo",
                      "description": "Obtain environment details for a Spark Application",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "searchJobs": {
                      "path": "v1/{+name}:searchJobs",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchJobs",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchJobs",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain list of spark jobs corresponding to a Spark Application."
                    },
                    "summarizeExecutors": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain summary of Executor Summary for a Spark Application",
                      "id": "dataproc.projects.locations.batches.sparkApplications.summarizeExecutors",
                      "httpMethod": "GET",
                      "path": "v1/{+name}:summarizeExecutors",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:summarizeExecutors"
                    }
                  }
                }
              }
            }
          }
        },
        "regions": {
          "resources": {
            "jobs": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "id": "dataproc.projects.regions.jobs.get",
                  "description": "Gets the resource representation for a job in a project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "path": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}"
                },
                "submit": {
                  "id": "dataproc.projects.regions.jobs.submit",
                  "httpMethod": "POST",
                  "description": "Submits a job to a cluster.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/projects/{projectId}/regions/{region}/jobs:submit",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs:submit"
                },
                "delete": {
                  "path": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "description": "Deletes the job from the project. If the job is active, the delete fails, and the response returns FAILED_PRECONDITION.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "DELETE",
                  "id": "dataproc.projects.regions.jobs.delete"
                },
                "testIamPermissions": {
                  "id": "dataproc.projects.regions.jobs.testIamPermissions",
                  "httpMethod": "POST",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/jobs/{jobsId}:testIamPermissions"
                },
                "list": {
                  "description": "Lists regions/{region}/jobs in a project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "httpMethod": "GET",
                  "id": "dataproc.projects.regions.jobs.list",
                  "path": "v1/projects/{projectId}/regions/{region}/jobs",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs"
                },
                "patch": {
                  "path": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "httpMethod": "PATCH",
                  "id": "dataproc.projects.regions.jobs.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Updates a job in a project."
                },
                "getIamPolicy": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.jobs.getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/jobs/{jobsId}:getIamPolicy"
                },
                "submitAsOperation": {
                  "description": "Submits job to a cluster.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.regions.jobs.submitAsOperation",
                  "httpMethod": "POST",
                  "path": "v1/projects/{projectId}/regions/{region}/jobs:submitAsOperation",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs:submitAsOperation"
                },
                "cancel": {
                  "path": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}:cancel",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}:cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Starts a job cancellation request. To access the job resource after cancellation, call regions/{region}/jobs.list (https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.jobs/list) or regions/{region}/jobs.get (https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.jobs/get).",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.jobs.cancel"
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/jobs/{jobsId}:setIamPolicy",
                  "id": "dataproc.projects.regions.jobs.setIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                }
              }
            },
            "clusters": {
              "resources": {
                "nodeGroups": {
                  "methods": {
                    "resize": {
                      "path": "v1/{+name}:resize",
                      "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}/nodeGroups/{nodeGroupsId}:resize",
                      "httpMethod": "POST",
                      "id": "dataproc.projects.regions.clusters.nodeGroups.resize",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "description": "Resizes a node group in a cluster. The returned Operation.metadata is NodeGroupOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#nodegroupoperationmetadata)."
                    },
                    "repair": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "description": "Repair nodes in a node group.",
                      "httpMethod": "POST",
                      "id": "dataproc.projects.regions.clusters.nodeGroups.repair",
                      "path": "v1/{+name}:repair",
                      "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}/nodeGroups/{nodeGroupsId}:repair"
                    },
                    "get": {
                      "path": "v1/{+name}",
                      "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}/nodeGroups/{nodeGroupsId}",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.regions.clusters.nodeGroups.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Gets the resource representation for a node group in a cluster."
                    },
                    "create": {
                      "httpMethod": "POST",
                      "id": "dataproc.projects.regions.clusters.nodeGroups.create",
                      "description": "Creates a node group in a cluster. The returned Operation.metadata is NodeGroupOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#nodegroupoperationmetadata).",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "path": "v1/{+parent}/nodeGroups",
                      "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}/nodeGroups"
                    }
                  }
                }
              },
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Lists all regions/{region}/clusters in a project alphabetically.",
                  "id": "dataproc.projects.regions.clusters.list",
                  "httpMethod": "GET",
                  "path": "v1/projects/{projectId}/regions/{region}/clusters",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Updates a cluster in a project. The returned Operation.metadata will be ClusterOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#clusteroperationmetadata). The cluster must be in a RUNNING state or an error is returned.",
                  "httpMethod": "PATCH",
                  "id": "dataproc.projects.regions.clusters.patch",
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}"
                },
                "repair": {
                  "id": "dataproc.projects.regions.clusters.repair",
                  "httpMethod": "POST",
                  "description": "Repairs a cluster.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:repair",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:repair"
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "dataproc.projects.regions.clusters.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Gets the resource representation for a cluster in a project.",
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}"
                },
                "start": {
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:start",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:start",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Starts a cluster in a project.",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.clusters.start"
                },
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataproc.projects.regions.clusters.testIamPermissions",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}:testIamPermissions"
                },
                "setIamPolicy": {
                  "id": "dataproc.projects.regions.clusters.setIamPolicy",
                  "httpMethod": "POST",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}:setIamPolicy"
                },
                "injectCredentials": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.clusters.injectCredentials",
                  "description": "Inject encrypted credentials into all of the VMs in a cluster.The target cluster must be a personal auth cluster assigned to the user who is issuing the RPC.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+project}/{+region}/{+cluster}:injectCredentials",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}:injectCredentials"
                },
                "stop": {
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:stop",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:stop",
                  "description": "Stops a cluster in a project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.clusters.stop"
                },
                "diagnose": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.clusters.diagnose",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Gets cluster diagnostic information. The returned Operation.metadata will be ClusterOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#clusteroperationmetadata). After the operation completes, Operation.response contains DiagnoseClusterResults (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#diagnoseclusterresults).",
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:diagnose",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:diagnose"
                },
                "getIamPolicy": {
                  "id": "dataproc.projects.regions.clusters.getIamPolicy",
                  "httpMethod": "POST",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}:getIamPolicy"
                },
                "delete": {
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Deletes a cluster in a project. The returned Operation.metadata will be ClusterOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#clusteroperationmetadata).",
                  "id": "dataproc.projects.regions.clusters.delete",
                  "httpMethod": "DELETE"
                },
                "create": {
                  "description": "Creates a cluster in a project. The returned Operation.metadata will be ClusterOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#clusteroperationmetadata).",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.regions.clusters.create",
                  "httpMethod": "POST",
                  "path": "v1/projects/{projectId}/regions/{region}/clusters",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters"
                }
              }
            },
            "autoscalingPolicies": {
              "methods": {
                "update": {
                  "httpMethod": "PUT",
                  "id": "dataproc.projects.regions.autoscalingPolicies.update",
                  "description": "Updates (replaces) autoscaling policy.Disabled check for update_mask, because all updates will be full replacements.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}"
                },
                "get": {
                  "id": "dataproc.projects.regions.autoscalingPolicies.get",
                  "httpMethod": "GET",
                  "description": "Retrieves autoscaling policy.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}",
                  "id": "dataproc.projects.regions.autoscalingPolicies.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Deletes an autoscaling policy. It is an error to delete an autoscaling policy that is in use by one or more clusters."
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.autoscalingPolicies.testIamPermissions"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Lists autoscaling policies in the project.",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.regions.autoscalingPolicies.list",
                  "path": "v1/{+parent}/autoscalingPolicies",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies"
                },
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.autoscalingPolicies.getIamPolicy"
                },
                "create": {
                  "path": "v1/{+parent}/autoscalingPolicies",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Creates new autoscaling policy.",
                  "id": "dataproc.projects.regions.autoscalingPolicies.create",
                  "httpMethod": "POST"
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}:setIamPolicy",
                  "id": "dataproc.projects.regions.autoscalingPolicies.setIamPolicy",
                  "httpMethod": "POST",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                }
              }
            },
            "workflowTemplates": {
              "methods": {
                "list": {
                  "id": "dataproc.projects.regions.workflowTemplates.list",
                  "httpMethod": "GET",
                  "description": "Lists workflows that match the specified filter in the request.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "path": "v1/{+parent}/workflowTemplates",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates"
                },
                "instantiate": {
                  "path": "v1/{+name}:instantiate",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}:instantiate",
                  "description": "Instantiates a template and begins execution.The returned Operation can be used to track execution of workflow by polling operations.get. The Operation will complete when entire workflow is finished.The running workflow can be aborted via operations.cancel. This will cause any inflight jobs to be cancelled and workflow-owned clusters to be deleted.The Operation.metadata will be WorkflowMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.d[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.workflowTemplates.instantiate"
                },
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}:getIamPolicy",
                  "id": "dataproc.projects.regions.workflowTemplates.getIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "dataproc.projects.regions.workflowTemplates.get",
                  "description": "Retrieves the latest workflow template.Can retrieve previously instantiated template by specifying optional version parameter.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}"
                },
                "update": {
                  "httpMethod": "PUT",
                  "id": "dataproc.projects.regions.workflowTemplates.update",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Updates (replaces) workflow template. The updated template must contain version that matches the current server version.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}"
                },
                "testIamPermissions": {
                  "id": "dataproc.projects.regions.workflowTemplates.testIamPermissions",
                  "httpMethod": "POST",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}:testIamPermissions"
                },
                "instantiateInline": {
                  "path": "v1/{+parent}/workflowTemplates:instantiateInline",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates:instantiateInline",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Instantiates a template and begins execution.This method is equivalent to executing the sequence CreateWorkflowTemplate, InstantiateWorkflowTemplate, DeleteWorkflowTemplate.The returned Operation can be used to track execution of workflow by polling operations.get. The Operation will complete when entire workflow is finished.The running workflow can be aborted via operations.cancel. This will cause any inflight jobs to be cancelled and workflow-owned clusters to[...]",
                  "id": "dataproc.projects.regions.workflowTemplates.instantiateInline",
                  "httpMethod": "POST"
                },
                "delete": {
                  "description": "Deletes a workflow template. It does not cancel in-progress workflows.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.regions.workflowTemplates.delete",
                  "httpMethod": "DELETE",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}"
                },
                "create": {
                  "path": "v1/{+parent}/workflowTemplates",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates",
                  "description": "Creates new workflow template.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.workflowTemplates.create"
                },
                "setIamPolicy": {
                  "id": "dataproc.projects.regions.workflowTemplates.setIamPolicy",
                  "httpMethod": "POST",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}:setIamPolicy"
                }
              }
            },
            "operations": {
              "methods": {
                "getIamPolicy": {
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.regions.operations.getIamPolicy",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}:getIamPolicy"
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataproc.projects.regions.operations.setIamPolicy",
                  "httpMethod": "POST"
                },
                "cancel": {
                  "path": "v1/{+name}:cancel",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}:cancel",
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it beco[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.regions.operations.cancel",
                  "httpMethod": "POST"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns UNIMPLEMENTED.",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.regions.operations.list",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}",
                  "id": "dataproc.projects.regions.operations.delete",
                  "httpMethod": "DELETE",
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataproc.projects.regions.operations.testIamPermissions",
                  "httpMethod": "POST"
                },
                "get": {
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "id": "dataproc.projects.regions.operations.get",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}"
                }
              }
            }
          }
        }
      }
    }
  },
  "revision": "20260501",
  "description": "Manages Hadoop-based clusters and jobs on Google Cloud Platform.",
  "documentationLink": "https://cloud.google.com/dataproc/",
  "kind": "discovery#restDescription",
  "schemas": {
    "ShuffleReadQuantileMetrics": {
      "properties": {
        "localBlocksFetched": {
          "$ref": "Quantiles"
        },
        "remoteBytesReadToDisk": {
          "$ref": "Quantiles"
        },
        "remoteBytesRead": {
          "$ref": "Quantiles"
        },
        "readBytes": {
          "$ref": "Quantiles"
        },
        "fetchWaitTimeMillis": {
          "$ref": "Quantiles"
        },
        "readRecords": {
          "$ref": "Quantiles"
        },
        "shufflePushReadMetrics": {
          "$ref": "ShufflePushReadQuantileMetrics"
        },
        "remoteReqsDuration": {
          "$ref": "Quantiles"
        },
        "remoteBlocksFetched": {
          "$ref": "Quantiles"
        },
        "totalBlocksFetched": {
          "$ref": "Quantiles"
        }
      },
      "id": "ShuffleReadQuantileMetrics",
      "type": "object"
    },
    "AccessSparkApplicationStageAttemptResponse": {
      "id": "AccessSparkApplicationStageAttemptResponse",
      "description": "Stage Attempt for a Stage of a Spark Application",
      "properties": {
        "stageData": {
          "description": "Output only. Data corresponding to a stage.",
          "readOnly": true,
          "$ref": "StageData"
        }
      },
      "type": "object"
    },
    "TerminateSessionRequest": {
      "description": "A request to terminate an interactive session.",
      "properties": {
        "requestId": {
          "type": "string",
          "description": "Optional. A unique ID used to identify the request. If the service receives two TerminateSessionRequest (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.TerminateSessionRequest)s with the same ID, the second request is ignored.Recommendation: Set this value to a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier).The value must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), and hyphe[...]"
        }
      },
      "id": "TerminateSessionRequest",
      "type": "object"
    },
    "PySparkJob": {
      "id": "PySparkJob",
      "description": "A Dataproc job for running Apache PySpark (https://spark.apache.org/docs/latest/api/python/index.html#pyspark-overview) applications on YARN.",
      "properties": {
        "archiveUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of archives to be extracted into the working directory of each executor. Supported file types: .jar, .tar, .tar.gz, .tgz, and .zip.Note: Spark applications must be deployed in cluster mode (https://spark.apache.org/docs/latest/cluster-overview.html) for correct environment propagation."
        },
        "loggingConfig": {
          "description": "Optional. The runtime log config for job execution.",
          "$ref": "LoggingConfig"
        },
        "mainPythonFileUri": {
          "type": "string",
          "description": "Required. The HCFS URI of the main Python file to use as the driver. Must be a .py file."
        },
        "pythonFileUris": {
          "description": "Optional. HCFS file URIs of Python files to pass to the PySpark framework. Supported file types: .py, .egg, and .zip.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "jarFileUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of jar files to add to the CLASSPATHs of the Python driver and tasks."
        },
        "fileUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of files to be placed in the working directory of each executor. Useful for naively parallel tasks."
        },
        "properties": {
          "type": "object",
          "description": "Optional. A mapping of property names to values, used to configure PySpark. Properties that conflict with values set by the Dataproc API might be overwritten. Can include properties set in /etc/spark/conf/spark-defaults.conf and classes in user code.",
          "additionalProperties": {
            "type": "string"
          }
        },
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. The arguments to pass to the driver. Do not include arguments, such as --conf, that can be set as job properties, since a collision may occur that causes an incorrect job submission."
        }
      },
      "type": "object"
    },
    "SqlExecutionUiData": {
      "description": "SQL Execution Data",
      "properties": {
        "executionId": {
          "type": "string",
          "format": "int64"
        },
        "rootExecutionId": {
          "type": "string",
          "format": "int64"
        },
        "modifiedConfigs": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "metrics": {
          "type": "array",
          "items": {
            "$ref": "SqlPlanMetric"
          }
        },
        "completionTime": {
          "format": "google-datetime",
          "type": "string"
        },
        "errorMessage": {
          "type": "string"
        },
        "metricValuesIsNull": {
          "type": "boolean"
        },
        "metricValues": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "description": {
          "type": "string"
        },
        "submissionTime": {
          "type": "string",
          "format": "google-datetime"
        },
        "stages": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "int64"
          }
        },
        "details": {
          "type": "string"
        },
        "jobs": {
          "type": "object",
          "additionalProperties": {
            "enumDescriptions": [
              "",
              "",
              "",
              "",
              ""
            ],
            "type": "string",
            "enum": [
              "JOB_EXECUTION_STATUS_UNSPECIFIED",
              "JOB_EXECUTION_STATUS_RUNNING",
              "JOB_EXECUTION_STATUS_SUCCEEDED",
              "JOB_EXECUTION_STATUS_FAILED",
              "JOB_EXECUTION_STATUS_UNKNOWN"
            ]
          }
        },
        "physicalPlanDescription": {
          "type": "string"
        }
      },
      "id": "SqlExecutionUiData",
      "type": "object"
    },
    "Interval": {
      "description": "Represents a time interval, encoded as a Timestamp start (inclusive) and a Timestamp end (exclusive).The start must be less than or equal to the end. When the start equals the end, the interval is empty (matches no time). When both start and end are unspecified, the interval matches any time.",
      "properties": {
        "startTime": {
          "description": "Optional. Inclusive start of the interval.If specified, a Timestamp matching this interval will have to be the same or after the start.",
          "format": "google-datetime",
          "type": "string"
        },
        "endTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "Optional. Exclusive end of the interval.If specified, a Timestamp matching this interval will have to be before the end."
        }
      },
      "id": "Interval",
      "type": "object"
    },
    "StateOperatorProgress": {
      "type": "object",
      "properties": {
        "numRowsDroppedByWatermark": {
          "type": "string",
          "format": "int64"
        },
        "numRowsUpdated": {
          "format": "int64",
          "type": "string"
        },
        "allRemovalsTimeMs": {
          "type": "string",
          "format": "int64"
        },
        "numRowsRemoved": {
          "type": "string",
          "format": "int64"
        },
        "memoryUsedBytes": {
          "type": "string",
          "format": "int64"
        },
        "numStateStoreInstances": {
          "format": "int64",
          "type": "string"
        },
        "numRowsTotal": {
          "format": "int64",
          "type": "string"
        },
        "commitTimeMs": {
          "type": "string",
          "format": "int64"
        },
        "numShufflePartitions": {
          "format": "int64",
          "type": "string"
        },
        "allUpdatesTimeMs": {
          "format": "int64",
          "type": "string"
        },
        "customMetrics": {
          "type": "object",
          "additionalProperties": {
            "type": "string",
            "format": "int64"
          }
        },
        "operatorName": {
          "type": "string"
        }
      },
      "id": "StateOperatorProgress"
    },
    "ProvisioningModelMix": {
      "description": "Defines how Dataproc should create VMs with a mixture of provisioning models.",
      "properties": {
        "standardCapacityBase": {
          "description": "Optional. The base capacity that will always use Standard VMs to avoid risk of more preemption than the minimum capacity you need. Dataproc will create only standard VMs until it reaches standard_capacity_base, then it will start using standard_capacity_percent_above_base to mix Spot with Standard VMs. eg. If 15 instances are requested and standard_capacity_base is 5, Dataproc will create 5 standard VMs and then start mixing spot and standard VMs for remaining 10 instan[...]",
          "type": "integer",
          "format": "int32"
        },
        "standardCapacityPercentAboveBase": {
          "description": "Optional. The percentage of target capacity that should use Standard VM. The remaining percentage will use Spot VMs. The percentage applies only to the capacity above standard_capacity_base. eg. If 15 instances are requested and standard_capacity_base is 5 and standard_capacity_percent_above_base is 30, Dataproc will create 5 standard VMs and then start mixing spot and standard VMs for remaining 10 instances. The mix will be 30% standard and 70% spot.",
          "format": "int32",
          "type": "integer"
        }
      },
      "id": "ProvisioningModelMix",
      "type": "object"
    },
    "DiagnoseClusterResults": {
      "type": "object",
      "id": "DiagnoseClusterResults",
      "description": "The location of diagnostic output.",
      "properties": {
        "outputUri": {
          "description": "Output only. The Cloud Storage URI of the diagnostic output. The output report is a plain text file with a summary of collected diagnostics.",
          "readOnly": true,
          "type": "string"
        }
      }
    },
    "StageAttemptTasksSummary": {
      "id": "StageAttemptTasksSummary",
      "description": "Data related to tasks summary for a Spark Stage Attempt",
      "properties": {
        "numKilledTasks": {
          "type": "integer",
          "format": "int32"
        },
        "stageId": {
          "format": "int64",
          "type": "string"
        },
        "stageAttemptId": {
          "format": "int32",
          "type": "integer"
        },
        "numTasks": {
          "format": "int32",
          "type": "integer"
        },
        "numSuccessTasks": {
          "type": "integer",
          "format": "int32"
        },
        "applicationId": {
          "type": "string"
        },
        "numFailedTasks": {
          "format": "int32",
          "type": "integer"
        },
        "numPendingTasks": {
          "format": "int32",
          "type": "integer"
        },
        "numRunningTasks": {
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "ListBatchesResponse": {
      "type": "object",
      "description": "A list of batch workloads.",
      "properties": {
        "batches": {
          "type": "array",
          "items": {
            "$ref": "Batch"
          },
          "description": "Output only. The batches from the specified collection.",
          "readOnly": true
        },
        "nextPageToken": {
          "type": "string",
          "description": "A token, which can be sent as page_token to retrieve the next page. If this field is omitted, there are no subsequent pages."
        },
        "unreachable": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "readOnly": true,
          "description": "Output only. List of Batches that could not be included in the response. Attempting to get one of these resources may indicate why it was not included in the list response."
        }
      },
      "id": "ListBatchesResponse"
    },
    "PySparkBatch": {
      "type": "object",
      "description": "A configuration for running an Apache PySpark (https://spark.apache.org/docs/latest/api/python/getting_started/quickstart.html) batch workload.",
      "properties": {
        "archiveUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of archives to be extracted into the working directory of each executor. Supported file types: .jar, .tar, .tar.gz, .tgz, and .zip."
        },
        "mainPythonFileUri": {
          "description": "Required. The HCFS URI of the main Python file to use as the Spark driver. Must be a .py file.",
          "type": "string"
        },
        "pythonFileUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS file URIs of Python files to pass to the PySpark framework. Supported file types: .py, .egg, and .zip."
        },
        "jarFileUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of jar files to add to the classpath of the Spark driver and tasks."
        },
        "fileUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of files to be placed in the working directory of each executor."
        },
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. The arguments to pass to the driver. Do not include arguments that can be set as batch properties, such as --conf, since a collision can occur that causes an incorrect batch submission."
        }
      },
      "id": "PySparkBatch"
    },
    "NodeGroup": {
      "description": "Dataproc Node Group. The Dataproc NodeGroup resource is not related to the Dataproc NodeGroupAffinity resource.",
      "properties": {
        "nodeGroupConfig": {
          "description": "Optional. The node group instance group configuration.",
          "$ref": "InstanceGroupConfig"
        },
        "labels": {
          "description": "Optional. Node group labels. Label keys must consist of from 1 to 63 characters and conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). Label values can be empty. If specified, they must consist of from 1 to 63 characters and conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). The node group must have no more than 32 labels.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "name": {
          "type": "string",
          "description": "The Node group resource name (https://aip.dev/122)."
        },
        "roles": {
          "description": "Required. Node group roles.",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "ROLE_UNSPECIFIED",
              "DRIVER"
            ],
            "enumDescriptions": [
              "Required unspecified role.",
              "Job drivers run on the node pool."
            ]
          }
        }
      },
      "id": "NodeGroup",
      "type": "object"
    },
    "SummarizeSessionSparkApplicationStagesResponse": {
      "id": "SummarizeSessionSparkApplicationStagesResponse",
      "description": "Summary of a Spark Application stages.",
      "properties": {
        "stagesSummary": {
          "description": "Summary of a Spark Application Stages",
          "$ref": "StagesSummary"
        }
      },
      "type": "object"
    },
    "SessionStateHistory": {
      "description": "Historical state information.",
      "properties": {
        "state": {
          "type": "string",
          "enum": [
            "STATE_UNSPECIFIED",
            "CREATING",
            "ACTIVE",
            "TERMINATING",
            "TERMINATED",
            "FAILED"
          ],
          "readOnly": true,
          "enumDescriptions": [
            "The session state is unknown.",
            "The session is created prior to running.",
            "The session is running.",
            "The session is terminating.",
            "The session is terminated successfully.",
            "The session is no longer running due to an error."
          ],
          "description": "Output only. The state of the session at this point in the session history."
        },
        "stateStartTime": {
          "description": "Output only. The time when the session entered the historical state.",
          "readOnly": true,
          "format": "google-datetime",
          "type": "string"
        },
        "stateMessage": {
          "readOnly": true,
          "description": "Output only. Details about the state at this point in the session history.",
          "type": "string"
        }
      },
      "id": "SessionStateHistory",
      "type": "object"
    },
    "SearchSparkApplicationStagesResponse": {
      "type": "object",
      "id": "SearchSparkApplicationStagesResponse",
      "description": "A list of stages associated with a Spark Application.",
      "properties": {
        "sparkApplicationStages": {
          "description": "Output only. Data corresponding to a stage.",
          "readOnly": true,
          "type": "array",
          "items": {
            "$ref": "StageData"
          }
        },
        "nextPageToken": {
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSparkApplicationStages.",
          "type": "string"
        }
      }
    },
    "SparkConnectExecutionInfo": {
      "id": "SparkConnectExecutionInfo",
      "description": "Represents the lifecycle and details of an Execution via Spark Connect",
      "properties": {
        "closeTimestamp": {
          "type": "string",
          "format": "int64",
          "description": "Timestamp when the execution was closed."
        },
        "jobIds": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. List of job ids associated with the execution."
        },
        "userId": {
          "type": "string",
          "description": "User ID of the user who started the execution."
        },
        "startTimestamp": {
          "description": "Timestamp when the execution started.",
          "format": "int64",
          "type": "string"
        },
        "detail": {
          "description": "Detailed information about the execution.",
          "type": "string"
        },
        "sessionId": {
          "description": "Required. Session ID, ties the execution to a specific Spark Connect session.",
          "type": "string"
        },
        "jobTag": {
          "type": "string",
          "description": "Required. Job tag of the execution."
        },
        "finishTimestamp": {
          "type": "string",
          "format": "int64",
          "description": "Timestamp when the execution finished."
        },
        "operationId": {
          "description": "Unique identifier for the operation.",
          "type": "string"
        },
        "sqlExecIds": {
          "description": "Optional. List of sql execution ids associated with the execution.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "sparkSessionTags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. Tags associated with the Spark session."
        },
        "state": {
          "type": "string",
          "enum": [
            "EXECUTION_STATE_UNKNOWN",
            "EXECUTION_STATE_STARTED",
            "EXECUTION_STATE_COMPILED",
            "EXECUTION_STATE_READY",
            "EXECUTION_STATE_CANCELED",
            "EXECUTION_STATE_FAILED",
            "EXECUTION_STATE_FINISHED",
            "EXECUTION_STATE_CLOSED"
          ],
          "readOnly": true,
          "enumDescriptions": [
            "Execution state is unknown.",
            "Execution state is started.",
            "Execution state is compiled.",
            "Execution state is ready.",
            "Execution state is canceled.",
            "Execution state is failed.",
            "Execution state is finished.",
            "Execution state is closed."
          ],
          "description": "Output only. Current state of the execution."
        },
        "statement": {
          "type": "string",
          "description": "statement of the execution."
        }
      },
      "type": "object"
    },
    "NamespacedGkeDeploymentTarget": {
      "deprecated": true,
      "type": "object",
      "id": "NamespacedGkeDeploymentTarget",
      "description": "Deprecated. Used only for the deprecated beta. A full, namespace-isolated deployment target for an existing GKE cluster.",
      "properties": {
        "clusterNamespace": {
          "description": "Optional. A namespace within the GKE cluster to deploy into.",
          "type": "string"
        },
        "targetGkeCluster": {
          "type": "string",
          "description": "Optional. The target GKE cluster to deploy to. Format: 'projects/{project}/locations/{location}/clusters/{cluster_id}'"
        }
      }
    },
    "StreamingQueryData": {
      "id": "StreamingQueryData",
      "description": "Streaming",
      "properties": {
        "runId": {
          "type": "string"
        },
        "exception": {
          "type": "string"
        },
        "streamingQueryId": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "endTimestamp": {
          "format": "int64",
          "type": "string"
        },
        "startTimestamp": {
          "format": "int64",
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "SparkRJob": {
      "description": "A Dataproc job for running Apache SparkR (https://spark.apache.org/docs/latest/sparkr.html) applications on YARN.",
      "properties": {
        "mainRFileUri": {
          "type": "string",
          "description": "Required. The HCFS URI of the main R file to use as the driver. Must be a .R file."
        },
        "archiveUris": {
          "description": "Optional. HCFS URIs of archives to be extracted into the working directory of each executor. Supported file types: .jar, .tar, .tar.gz, .tgz, and .zip.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "loggingConfig": {
          "description": "Optional. The runtime log config for job execution.",
          "$ref": "LoggingConfig"
        },
        "fileUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of files to be placed in the working directory of each executor. Useful for naively parallel tasks."
        },
        "properties": {
          "type": "object",
          "description": "Optional. A mapping of property names to values, used to configure SparkR. Properties that conflict with values set by the Dataproc API might be overwritten. Can include properties set in /etc/spark/conf/spark-defaults.conf and classes in user code.",
          "additionalProperties": {
            "type": "string"
          }
        },
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. The arguments to pass to the driver. Do not include arguments, such as --conf, that can be set as job properties, since a collision may occur that causes an incorrect job submission."
        }
      },
      "id": "SparkRJob",
      "type": "object"
    },
    "AccessSessionSparkApplicationResponse": {
      "type": "object",
      "id": "AccessSessionSparkApplicationResponse",
      "description": "A summary of Spark Application",
      "properties": {
        "application": {
          "$ref": "ApplicationInfo",
          "description": "Output only. High level information corresponding to an application.",
          "readOnly": true
        }
      }
    },
    "SqlPlanMetric": {
      "type": "object",
      "description": "Metrics related to SQL execution.",
      "properties": {
        "metricType": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "accumulatorId": {
          "format": "int64",
          "type": "string"
        }
      },
      "id": "SqlPlanMetric"
    },
    "AcceleratorConfig": {
      "description": "Specifies the type and number of accelerator cards attached to the instances of an instance. See GPUs on Compute Engine (https://cloud.google.com/compute/docs/gpus/).",
      "properties": {
        "acceleratorTypeUri": {
          "description": "Full URL, partial URI, or short name of the accelerator type resource to expose to this instance. See Compute Engine AcceleratorTypes (https://cloud.google.com/compute/docs/reference/v1/acceleratorTypes).Examples: https://www.googleapis.com/compute/v1/projects/[project_id]/zones/[zone]/acceleratorTypes/nvidia-tesla-t4 projects/[project_id]/zones/[zone]/acceleratorTypes/nvidia-tesla-t4 nvidia-tesla-t4Auto Zone Exception: If you are using the Dataproc Auto Zone Placement [...]",
          "type": "string"
        },
        "acceleratorCount": {
          "type": "integer",
          "format": "int32",
          "description": "The number of the accelerator cards of this type exposed to this instance."
        }
      },
      "id": "AcceleratorConfig",
      "type": "object"
    },
    "RddOperationGraph": {
      "id": "RddOperationGraph",
      "description": "Graph representing RDD dependencies. Consists of edges and a root cluster.",
      "properties": {
        "incomingEdges": {
          "type": "array",
          "items": {
            "$ref": "RddOperationEdge"
          }
        },
        "edges": {
          "type": "array",
          "items": {
            "$ref": "RddOperationEdge"
          }
        },
        "stageId": {
          "format": "int64",
          "type": "string"
        },
        "rootCluster": {
          "$ref": "RddOperationCluster"
        },
        "outgoingEdges": {
          "type": "array",
          "items": {
            "$ref": "RddOperationEdge"
          }
        }
      },
      "type": "object"
    },
    "NativeSqlExecutionUiData": {
      "description": "Native SQL Execution Data",
      "properties": {
        "executionId": {
          "description": "Required. Execution ID of the Native SQL Execution.",
          "type": "string",
          "format": "int64"
        },
        "numNativeNodes": {
          "description": "Optional. Number of nodes in Native.",
          "type": "integer",
          "format": "int32"
        },
        "numFallbackNodes": {
          "format": "int32",
          "type": "integer",
          "description": "Optional. Number of nodes fallen back to Spark."
        },
        "fallbackNodeToReason": {
          "type": "array",
          "items": {
            "$ref": "FallbackReason"
          },
          "description": "Optional. Fallback node to reason."
        },
        "description": {
          "type": "string",
          "description": "Optional. Description of the execution."
        },
        "fallbackDescription": {
          "description": "Optional. Description of the fallback.",
          "type": "string"
        }
      },
      "id": "NativeSqlExecutionUiData",
      "type": "object"
    },
    "AutoscalingConfig": {
      "id": "AutoscalingConfig",
      "description": "Autoscaling Policy config associated with the cluster.",
      "properties": {
        "policyUri": {
          "description": "Optional. The autoscaling policy used by the cluster.Only resource names including projectid and location (region) are valid. Examples: https://www.googleapis.com/compute/v1/projects/[project_id]/locations/[dataproc_region]/autoscalingPolicies/[policy_id] projects/[project_id]/locations/[dataproc_region]/autoscalingPolicies/[policy_id]Note that the policy must be in the same project and Dataproc region.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "QueryList": {
      "type": "object",
      "id": "QueryList",
      "description": "A list of queries to run on a cluster.",
      "properties": {
        "queries": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Required. The queries to execute. You do not need to end a query expression with a semicolon. Multiple queries can be specified in one string by separating each with a semicolon. Here is an example of a Dataproc API snippet that uses a QueryList to specify a HiveJob: \"hiveJob\": { \"queryList\": { \"queries\": [ \"query1\", \"query2\", \"query3;query4\", ] } } "
        }
      }
    },
    "BatchOperationMetadata": {
      "type": "object",
      "id": "BatchOperationMetadata",
      "description": "Metadata describing the Batch operation.",
      "properties": {
        "operationType": {
          "description": "The operation type.",
          "enumDescriptions": [
            "Batch operation type is unknown.",
            "Batch operation type."
          ],
          "type": "string",
          "enum": [
            "BATCH_OPERATION_TYPE_UNSPECIFIED",
            "BATCH"
          ]
        },
        "description": {
          "type": "string",
          "description": "Short description of the operation."
        },
        "batchUuid": {
          "type": "string",
          "description": "Batch UUID for the operation."
        },
        "batch": {
          "description": "Name of the batch for the operation.",
          "type": "string"
        },
        "createTime": {
          "description": "The time when the operation was created.",
          "format": "google-datetime",
          "type": "string"
        },
        "doneTime": {
          "description": "The time when the operation finished.",
          "type": "string",
          "format": "google-datetime"
        },
        "warnings": {
          "description": "Warnings encountered during operation execution.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "labels": {
          "description": "Labels associated with the operation.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      }
    },
    "JobStatus": {
      "description": "Dataproc job status.",
      "properties": {
        "details": {
          "readOnly": true,
          "description": "Optional. Output only. Job state details, such as an error description if the state is ERROR.",
          "type": "string"
        },
        "stateStartTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "Output only. The time when this state was entered.",
          "readOnly": true
        },
        "state": {
          "description": "Output only. A state message specifying the overall job state.",
          "type": "string",
          "enum": [
            "STATE_UNSPECIFIED",
            "PENDING",
            "SETUP_DONE",
            "RUNNING",
            "CANCEL_PENDING",
            "CANCEL_STARTED",
            "CANCELLED",
            "DONE",
            "ERROR",
            "ATTEMPT_FAILURE"
          ],
          "enumDescriptions": [
            "The job state is unknown.",
            "The job is pending; it has been submitted, but is not yet running.",
            "Job has been received by the service and completed initial setup; it will soon be submitted to the cluster.",
            "The job is running on the cluster.",
            "A CancelJob request has been received, but is pending.",
            "Transient in-flight resources have been canceled, and the request to cancel the running job has been issued to the cluster.",
            "The job cancellation was successful.",
            "The job has completed successfully.",
            "The job has completed, but encountered an error.",
            "Job attempt has failed. The detail field contains failure details for this attempt.Applies to restartable jobs only."
          ],
          "readOnly": true
        },
        "substate": {
          "readOnly": true,
          "enumDescriptions": [
            "The job substate is unknown.",
            "The Job is submitted to the agent.Applies to RUNNING state.",
            "The Job has been received and is awaiting execution (it might be waiting for a condition to be met). See the \"details\" field for the reason for the delay.Applies to RUNNING state.",
            "The agent-reported status is out of date, which can be caused by a loss of communication between the agent and Dataproc. If the agent does not send a timely update, the job will fail.Applies to RUNNING state."
          ],
          "type": "string",
          "enum": [
            "UNSPECIFIED",
            "SUBMITTED",
            "QUEUED",
            "STALE_STATUS"
          ],
          "description": "Output only. Additional state information, which includes status reported by the agent."
        }
      },
      "id": "JobStatus",
      "type": "object"
    },
    "HadoopJob": {
      "type": "object",
      "description": "A Dataproc job for running Apache Hadoop MapReduce (https://hadoop.apache.org/docs/current/hadoop-mapreduce-client/hadoop-mapreduce-client-core/MapReduceTutorial.html) jobs on Apache Hadoop YARN (https://hadoop.apache.org/docs/r2.7.1/hadoop-yarn/hadoop-yarn-site/YARN.html).",
      "properties": {
        "archiveUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of archives to be extracted in the working directory of Hadoop drivers and tasks. Supported file types: .jar, .tar, .tar.gz, .tgz, or .zip."
        },
        "loggingConfig": {
          "description": "Optional. The runtime log config for job execution.",
          "$ref": "LoggingConfig"
        },
        "jarFileUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. Jar file URIs to add to the CLASSPATHs of the Hadoop driver and tasks."
        },
        "mainJarFileUri": {
          "description": "The HCFS URI of the jar file containing the main class. Examples: 'gs://foo-bucket/analytics-binaries/extract-useful-metrics-mr.jar' 'hdfs:/tmp/test-samples/custom-wordcount.jar' 'file:///home/usr/lib/hadoop-mapreduce/hadoop-mapreduce-examples.jar'",
          "type": "string"
        },
        "fileUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS (Hadoop Compatible Filesystem) URIs of files to be copied to the working directory of Hadoop drivers and distributed tasks. Useful for naively parallel tasks."
        },
        "properties": {
          "description": "Optional. A mapping of property names to values, used to configure Hadoop. Properties that conflict with values set by the Dataproc API might be overwritten. Can include properties set in /etc/hadoop/conf/*-site and classes in user code.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "mainClass": {
          "description": "The name of the driver's main class. The jar file containing the class must be in the default CLASSPATH or specified in jar_file_uris.",
          "type": "string"
        },
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. The arguments to pass to the driver. Do not include arguments, such as -libjars or -Dfoo=bar, that can be set as job properties, since a collision might occur that causes an incorrect job submission."
        }
      },
      "id": "HadoopJob"
    },
    "PrestoJob": {
      "description": "A Dataproc job for running Presto (https://prestosql.io/) queries. IMPORTANT: The Dataproc Presto Optional Component (https://cloud.google.com/dataproc/docs/concepts/components/presto) must be enabled when the cluster is created to submit a Presto job to the cluster.",
      "properties": {
        "properties": {
          "description": "Optional. A mapping of property names to values. Used to set Presto session properties (https://prestodb.io/docs/current/sql/set-session.html) Equivalent to using the --session flag in the Presto CLI",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "queryList": {
          "description": "A list of queries.",
          "$ref": "QueryList"
        },
        "outputFormat": {
          "description": "Optional. The format in which query output will be displayed. See the Presto documentation for supported output formats",
          "type": "string"
        },
        "clientTags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. Presto client tags to attach to this query"
        },
        "queryFileUri": {
          "type": "string",
          "description": "The HCFS URI of the script that contains SQL queries."
        },
        "loggingConfig": {
          "description": "Optional. The runtime log config for job execution.",
          "$ref": "LoggingConfig"
        },
        "continueOnFailure": {
          "description": "Optional. Whether to continue executing queries if a query fails. The default value is false. Setting to true can be useful when executing independent parallel queries.",
          "type": "boolean"
        }
      },
      "id": "PrestoJob",
      "type": "object"
    },
    "Policy": {
      "description": "An Identity and Access Management (IAM) policy, which specifies access controls for Google Cloud resources.A Policy is a collection of bindings. A binding binds one or more members, or principals, to a single role. Principals can be user accounts, service accounts, Google groups, and domains (such as G Suite). A role is a named list of permissions; each role can be an IAM predefined role or a user-created custom role.For some types of Google Cloud resources, a binding can a[...]",
      "properties": {
        "version": {
          "description": "Specifies the format of the policy.Valid values are 0, 1, and 3. Requests that specify an invalid value are rejected.Any operation that affects conditional role bindings must specify version 3. This requirement applies to the following operations: Getting a policy that includes a conditional role binding Adding a conditional role binding to a policy Changing a conditional role binding in a policy Removing any role binding, with or without a condition, from a policy that[...]",
          "format": "int32",
          "type": "integer"
        },
        "etag": {
          "description": "etag is used for optimistic concurrency control as a way to help prevent simultaneous updates of a policy from overwriting each other. It is strongly suggested that systems make use of the etag in the read-modify-write cycle to perform policy updates in order to avoid race conditions: An etag is returned in the response to getIamPolicy, and systems are expected to put that etag in the request to setIamPolicy to ensure that their change will be applied to the same versio[...]",
          "type": "string",
          "format": "byte"
        },
        "bindings": {
          "type": "array",
          "items": {
            "$ref": "Binding"
          },
          "description": "Associates a list of members, or principals, with a role. Optionally, may specify a condition that determines how and when the bindings are applied. Each of the bindings must contain at least one principal.The bindings in a Policy can refer to up to 1,500 principals; up to 250 of these principals can be Google groups. Each occurrence of a principal counts towards these limits. For example, if the bindings grant 50 different roles to user:alice@example.com, and not to an[...]"
        }
      },
      "id": "Policy",
      "type": "object"
    },
    "SessionOperationMetadata": {
      "type": "object",
      "description": "Metadata describing the Session operation.",
      "properties": {
        "labels": {
          "type": "object",
          "description": "Labels associated with the operation.",
          "additionalProperties": {
            "type": "string"
          }
        },
        "createTime": {
          "type": "string",
          "format": "google-datetime",
          "description": "The time when the operation was created."
        },
        "doneTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "The time when the operation was finished."
        },
        "warnings": {
          "description": "Warnings encountered during operation execution.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "sessionUuid": {
          "type": "string",
          "description": "Session UUID for the operation."
        },
        "operationType": {
          "description": "The operation type.",
          "enumDescriptions": [
            "Session operation type is unknown.",
            "Create Session operation type.",
            "Terminate Session operation type.",
            "Delete Session operation type."
          ],
          "type": "string",
          "enum": [
            "SESSION_OPERATION_TYPE_UNSPECIFIED",
            "CREATE",
            "TERMINATE",
            "DELETE"
          ]
        },
        "session": {
          "description": "Name of the session for the operation.",
          "type": "string"
        },
        "description": {
          "type": "string",
          "description": "Short description of the operation."
        }
      },
      "id": "SessionOperationMetadata"
    },
    "SparkHistoryServerConfig": {
      "id": "SparkHistoryServerConfig",
      "description": "Spark History Server configuration for the workload.",
      "properties": {
        "dataprocCluster": {
          "description": "Optional. Resource name of an existing Dataproc Cluster to act as a Spark History Server for the workload.Example: projects/[project_id]/regions/[region]/clusters/[cluster_name]",
          "type": "string"
        }
      },
      "type": "object"
    },
    "SparkPlanGraphNode": {
      "id": "SparkPlanGraphNode",
      "description": "Represents a node in the spark plan tree.",
      "properties": {
        "sparkPlanGraphNodeId": {
          "type": "string",
          "format": "int64"
        },
        "desc": {
          "type": "string"
        },
        "metrics": {
          "type": "array",
          "items": {
            "$ref": "SqlPlanMetric"
          }
        },
        "metadata": {
          "description": "Optional. Additional metadata for the spark plan graph cluster.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "name": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "PeripheralsConfig": {
      "type": "object",
      "description": "Auxiliary services configuration for a workload.",
      "properties": {
        "sparkHistoryServerConfig": {
          "description": "Optional. The Spark History Server configuration for the workload.",
          "$ref": "SparkHistoryServerConfig"
        },
        "metastoreService": {
          "type": "string",
          "description": "Optional. Resource name of an existing Dataproc Metastore service.Example: projects/[project_id]/locations/[region]/services/[service_id]"
        }
      },
      "id": "PeripheralsConfig"
    },
    "EndpointConfig": {
      "id": "EndpointConfig",
      "description": "Endpoint config for this cluster",
      "properties": {
        "httpPorts": {
          "description": "Output only. The map of port descriptions to URLs. Will only be populated if enable_http_port_access is true.",
          "additionalProperties": {
            "type": "string"
          },
          "readOnly": true,
          "type": "object"
        },
        "enableHttpPortAccess": {
          "description": "Optional. If true, enable http access to specific ports on the cluster from external sources. Defaults to false.",
          "type": "boolean"
        }
      },
      "type": "object"
    },
    "FlinkJob": {
      "description": "A Dataproc job for running Apache Flink applications on YARN.",
      "properties": {
        "properties": {
          "description": "Optional. A mapping of property names to values, used to configure Flink. Properties that conflict with values set by the Dataproc API might be overwritten. Can include properties set in /etc/flink/conf/flink-defaults.conf and classes in user code.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "mainJarFileUri": {
          "description": "The HCFS URI of the jar file that contains the main class.",
          "type": "string"
        },
        "args": {
          "description": "Optional. The arguments to pass to the driver. Do not include arguments, such as --conf, that can be set as job properties, since a collision might occur that causes an incorrect job submission.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "mainClass": {
          "description": "The name of the driver's main class. The jar file that contains the class must be in the default CLASSPATH or specified in jarFileUris.",
          "type": "string"
        },
        "loggingConfig": {
          "description": "Optional. The runtime log config for job execution.",
          "$ref": "LoggingConfig"
        },
        "savepointUri": {
          "description": "Optional. HCFS URI of the savepoint, which contains the last saved progress for starting the current job.",
          "type": "string"
        },
        "jarFileUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of jar files to add to the CLASSPATHs of the Flink driver and tasks."
        }
      },
      "id": "FlinkJob",
      "type": "object"
    },
    "ReservationAffinity": {
      "id": "ReservationAffinity",
      "description": "Reservation Affinity for consuming Zonal reservation.",
      "properties": {
        "key": {
          "type": "string",
          "description": "Optional. Corresponds to the label key of reservation resource."
        },
        "consumeReservationType": {
          "description": "Optional. Type of reservation to consume",
          "enumDescriptions": [
            "",
            "Do not consume from any allocated capacity.",
            "Consume any reservation available.",
            "Must consume from a specific reservation. Must specify key value fields for specifying the reservations."
          ],
          "type": "string",
          "enum": [
            "TYPE_UNSPECIFIED",
            "NO_RESERVATION",
            "ANY_RESERVATION",
            "SPECIFIC_RESERVATION"
          ]
        },
        "values": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. Corresponds to the label values of reservation resource."
        }
      },
      "type": "object"
    },
    "WorkflowTemplate": {
      "id": "WorkflowTemplate",
      "description": "A Dataproc workflow template resource.",
      "properties": {
        "placement": {
          "description": "Required. WorkflowTemplate scheduling information.",
          "$ref": "WorkflowTemplatePlacement"
        },
        "dagTimeout": {
          "description": "Optional. Timeout duration for the DAG of jobs, expressed in seconds (see JSON representation of duration (https://developers.google.com/protocol-buffers/docs/proto3#json)). The timeout duration must be from 10 minutes (\"600s\") to 24 hours (\"86400s\"). The timer begins when the first job is submitted. If the workflow is running at the end of the timeout period, any remaining jobs are cancelled, the workflow is ended, and if the workflow was running on a managed clust[...]",
          "type": "string",
          "format": "google-duration"
        },
        "encryptionConfig": {
          "description": "Optional. Encryption settings for encrypting workflow template job arguments.",
          "$ref": "GoogleCloudDataprocV1WorkflowTemplateEncryptionConfig"
        },
        "id": {
          "type": "string"
        },
        "updateTime": {
          "readOnly": true,
          "description": "Output only. The time template was last updated.",
          "type": "string",
          "format": "google-datetime"
        },
        "jobs": {
          "description": "Required. The Directed Acyclic Graph of Jobs to submit.",
          "type": "array",
          "items": {
            "$ref": "OrderedJob"
          }
        },
        "version": {
          "description": "Optional. Used to perform a consistent read-modify-write.This field should be left blank for a CreateWorkflowTemplate request. It is required for an UpdateWorkflowTemplate request, and must match the current server version. A typical update template flow would fetch the current template with a GetWorkflowTemplate request, which will return the current template with the version field filled in with the current server version. The user updates other fields in the template[...]",
          "type": "integer",
          "format": "int32"
        },
        "labels": {
          "description": "Optional. The labels to associate with this template. These labels will be propagated to all jobs and clusters created by the workflow instance.Label keys must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt).Label values may be empty, but, if present, must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt).No more than 32 labels can be associated with a template.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "createTime": {
          "type": "string",
          "format": "google-datetime",
          "readOnly": true,
          "description": "Output only. The time template was created."
        },
        "name": {
          "description": "Output only. The resource name of the workflow template, as described in https://cloud.google.com/apis/design/resource_names. For projects.regions.workflowTemplates, the resource name of the template has the following format: projects/{project_id}/regions/{region}/workflowTemplates/{template_id} For projects.locations.workflowTemplates, the resource name of the template has the following format: projects/{project_id}/locations/{location}/workflowTemplates/{template_id}"[...]",
          "readOnly": true,
          "type": "string"
        }
      },
      "type": "object"
    },
    "ManagedGroupConfig": {
      "description": "Specifies the resources used to actively manage an instance group.",
      "properties": {
        "instanceTemplateName": {
          "readOnly": true,
          "description": "Output only. The name of the Instance Template used for the Managed Instance Group.",
          "type": "string"
        },
        "instanceGroupManagerName": {
          "readOnly": true,
          "description": "Output only. The name of the Instance Group Manager for this group.",
          "type": "string"
        },
        "instanceGroupManagerUri": {
          "description": "Output only. The partial URI to the instance group manager for this group. E.g. projects/my-project/regions/us-central1/instanceGroupManagers/my-igm.",
          "readOnly": true,
          "type": "string"
        }
      },
      "id": "ManagedGroupConfig",
      "type": "object"
    },
    "AuxiliaryNodeGroup": {
      "description": "Node group identification and configuration information.",
      "properties": {
        "nodeGroupId": {
          "type": "string",
          "description": "Optional. A node group ID. Generated if not specified.The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), and hyphens (-). Cannot begin or end with underscore or hyphen. Must consist of from 3 to 33 characters."
        },
        "nodeGroup": {
          "description": "Required. Node group configuration.",
          "$ref": "NodeGroup"
        }
      },
      "id": "AuxiliaryNodeGroup",
      "type": "object"
    },
    "TaskResourceRequest": {
      "id": "TaskResourceRequest",
      "description": "Resources used per task created by the application.",
      "properties": {
        "amount": {
          "format": "double",
          "type": "number"
        },
        "resourceName": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "IdentityConfig": {
      "id": "IdentityConfig",
      "description": "Identity related configuration, including service account based secure multi-tenancy user mappings.",
      "properties": {
        "userServiceAccountMapping": {
          "type": "object",
          "description": "Required. Map of user to service account.",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "type": "object"
    },
    "GkeClusterConfig": {
      "type": "object",
      "id": "GkeClusterConfig",
      "description": "The cluster's GKE config.",
      "properties": {
        "namespacedGkeDeploymentTarget": {
          "description": "Optional. Deprecated. Use gkeClusterTarget. Used only for the deprecated beta. A target for the deployment.",
          "deprecated": true,
          "$ref": "NamespacedGkeDeploymentTarget"
        },
        "nodePoolTarget": {
          "type": "array",
          "items": {
            "$ref": "GkeNodePoolTarget"
          },
          "description": "Optional. GKE node pools where workloads will be scheduled. At least one node pool must be assigned the DEFAULT GkeNodePoolTarget.Role. If a GkeNodePoolTarget is not specified, Dataproc constructs a DEFAULT GkeNodePoolTarget. Each role can be given to only one GkeNodePoolTarget. All node pools must have the same location settings."
        },
        "gkeClusterTarget": {
          "description": "Optional. A target GKE cluster to deploy to. It must be in the same project and region as the Dataproc cluster (the GKE cluster can be zonal or regional). Format: 'projects/{project}/locations/{location}/clusters/{cluster_id}'",
          "type": "string"
        }
      }
    },
    "AccessSessionSparkApplicationJobResponse": {
      "type": "object",
      "description": "Details of a particular job associated with Spark Application",
      "properties": {
        "jobData": {
          "readOnly": true,
          "description": "Output only. Data corresponding to a spark job.",
          "$ref": "JobData"
        }
      },
      "id": "AccessSessionSparkApplicationJobResponse"
    },
    "SparkJob": {
      "id": "SparkJob",
      "description": "A Dataproc job for running Apache Spark (https://spark.apache.org/) applications on YARN.",
      "properties": {
        "jarFileUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of jar files to add to the CLASSPATHs of the Spark driver and tasks."
        },
        "archiveUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of archives to be extracted into the working directory of each executor. Supported file types: .jar, .tar, .tar.gz, .tgz, and .zip."
        },
        "loggingConfig": {
          "description": "Optional. The runtime log config for job execution.",
          "$ref": "LoggingConfig"
        },
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. The arguments to pass to the driver. Do not include arguments, such as --conf, that can be set as job properties, since a collision may occur that causes an incorrect job submission."
        },
        "mainClass": {
          "description": "The name of the driver's main class. The jar file that contains the class must be in the default CLASSPATH or specified in SparkJob.jar_file_uris.",
          "type": "string"
        },
        "fileUris": {
          "description": "Optional. HCFS URIs of files to be placed in the working directory of each executor. Useful for naively parallel tasks.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "properties": {
          "type": "object",
          "description": "Optional. A mapping of property names to values, used to configure Spark. Properties that conflict with values set by the Dataproc API might be overwritten. Can include properties set in /etc/spark/conf/spark-defaults.conf and classes in user code.",
          "additionalProperties": {
            "type": "string"
          }
        },
        "mainJarFileUri": {
          "description": "The HCFS URI of the jar file that contains the main class.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "SearchSparkApplicationsResponse": {
      "description": "A list of summary of Spark Applications",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSparkApplicationsRequest."
        },
        "sparkApplications": {
          "type": "array",
          "items": {
            "$ref": "SparkApplication"
          },
          "readOnly": true,
          "description": "Output only. High level information corresponding to an application."
        }
      },
      "id": "SearchSparkApplicationsResponse",
      "type": "object"
    },
    "Expr": {
      "id": "Expr",
      "description": "Represents a textual expression in the Common Expression Language (CEL) syntax. CEL is a C-like expression language. The syntax and semantics of CEL are documented at https://github.com/google/cel-spec.Example (Comparison): title: \"Summary size limit\" description: \"Determines if a summary is less than 100 chars\" expression: \"document.summary.size() < 100\" Example (Equality): title: \"Requestor is owner\" description: \"Determines if requestor is the document owner\" e[...]",
      "properties": {
        "title": {
          "type": "string",
          "description": "Optional. Title for the expression, i.e. a short string describing its purpose. This can be used e.g. in UIs which allow to enter the expression."
        },
        "expression": {
          "type": "string",
          "description": "Textual representation of an expression in Common Expression Language syntax."
        },
        "location": {
          "description": "Optional. String indicating the location of the expression for error reporting, e.g. a file name and a position in the file.",
          "type": "string"
        },
        "description": {
          "description": "Optional. Description of the expression. This is a longer text which describes the expression, e.g. when hovered over it in a UI.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "BasicYarnAutoscalingConfig": {
      "id": "BasicYarnAutoscalingConfig",
      "description": "Basic autoscaling configurations for YARN.",
      "properties": {
        "scaleDownMinWorkerFraction": {
          "format": "double",
          "type": "number",
          "description": "Optional. Minimum scale-down threshold as a fraction of total cluster size before scaling occurs. For example, in a 20-worker cluster, a threshold of 0.1 means the autoscaler must recommend at least a 2 worker scale-down for the cluster to scale. A threshold of 0 means the autoscaler will scale down on any recommended change.Bounds: 0.0, 1.0. Default: 0.0."
        },
        "scaleDownFactor": {
          "format": "double",
          "type": "number",
          "description": "Required. Fraction of average YARN pending memory in the last cooldown period for which to remove workers. A scale-down factor of 1 will result in scaling down so that there is no available memory remaining after the update (more aggressive scaling). A scale-down factor of 0 disables removing workers, which can be beneficial for autoscaling a single job. See How autoscaling works (https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/autoscaling#how_autos[...]"
        },
        "scaleUpFactor": {
          "format": "double",
          "type": "number",
          "description": "Required. Fraction of average YARN pending memory in the last cooldown period for which to add workers. A scale-up factor of 1.0 will result in scaling up so that there is no pending memory remaining after the update (more aggressive scaling). A scale-up factor closer to 0 will result in a smaller magnitude of scaling up (less aggressive scaling). See How autoscaling works (https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/autoscaling#how_autoscaling_[...]"
        },
        "gracefulDecommissionTimeout": {
          "type": "string",
          "format": "google-duration",
          "description": "Required. Timeout for YARN graceful decommissioning of Node Managers. Specifies the duration to wait for jobs to complete before forcefully removing workers (and potentially interrupting jobs). Only applicable to downscaling operations.Bounds: 0s, 1d."
        },
        "scaleUpMinWorkerFraction": {
          "description": "Optional. Minimum scale-up threshold as a fraction of total cluster size before scaling occurs. For example, in a 20-worker cluster, a threshold of 0.1 means the autoscaler must recommend at least a 2-worker scale-up for the cluster to scale. A threshold of 0 means the autoscaler will scale up on any recommended change.Bounds: 0.0, 1.0. Default: 0.0.",
          "format": "double",
          "type": "number"
        }
      },
      "type": "object"
    },
    "WorkflowGraph": {
      "description": "The workflow graph.",
      "properties": {
        "nodes": {
          "description": "Output only. The workflow nodes.",
          "readOnly": true,
          "type": "array",
          "items": {
            "$ref": "WorkflowNode"
          }
        }
      },
      "id": "WorkflowGraph",
      "type": "object"
    },
    "SearchSparkApplicationStageAttemptsResponse": {
      "id": "SearchSparkApplicationStageAttemptsResponse",
      "description": "A list of Stage Attempts for a Stage of a Spark Application.",
      "properties": {
        "sparkApplicationStageAttempts": {
          "description": "Output only. Data corresponding to a stage attempts",
          "readOnly": true,
          "type": "array",
          "items": {
            "$ref": "StageData"
          }
        },
        "nextPageToken": {
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent ListSparkApplicationStageAttemptsRequest.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "NodeGroupAffinity": {
      "description": "Node Group Affinity for clusters using sole-tenant node groups. The Dataproc NodeGroupAffinity resource is not related to the Dataproc NodeGroup resource.",
      "properties": {
        "nodeGroupUri": {
          "type": "string",
          "description": "Required. The URI of a sole-tenant node group resource (https://cloud.google.com/compute/docs/reference/rest/v1/nodeGroups) that the cluster will be created on.A full URL, partial URI, or node group name are valid. Examples: https://www.googleapis.com/compute/v1/projects/[project_id]/zones/[zone]/nodeGroups/node-group-1 projects/[project_id]/zones/[zone]/nodeGroups/node-group-1 node-group-1"
        }
      },
      "id": "NodeGroupAffinity",
      "type": "object"
    },
    "AccessSessionSparkApplicationStageAttemptResponse": {
      "type": "object",
      "description": "Stage Attempt for a Stage of a Spark Application",
      "properties": {
        "stageData": {
          "$ref": "StageData",
          "description": "Output only. Data corresponding to a stage.",
          "readOnly": true
        }
      },
      "id": "AccessSessionSparkApplicationStageAttemptResponse"
    },
    "JobMetadata": {
      "description": "Job Operation metadata.",
      "properties": {
        "operationType": {
          "type": "string",
          "description": "Output only. Operation type.",
          "readOnly": true
        },
        "jobId": {
          "description": "Output only. The job id.",
          "readOnly": true,
          "type": "string"
        },
        "status": {
          "$ref": "JobStatus",
          "description": "Output only. Most recent job status.",
          "readOnly": true
        },
        "startTime": {
          "readOnly": true,
          "description": "Output only. Job submission time.",
          "type": "string",
          "format": "google-datetime"
        }
      },
      "id": "JobMetadata",
      "type": "object"
    },
    "InstanceReference": {
      "id": "InstanceReference",
      "description": "A reference to a Compute Engine instance.",
      "properties": {
        "publicKey": {
          "description": "The public RSA key used for sharing data with this instance.",
          "type": "string"
        },
        "instanceId": {
          "description": "The unique identifier of the Compute Engine instance.",
          "type": "string"
        },
        "publicEciesKey": {
          "description": "The public ECIES key used for sharing data with this instance.",
          "type": "string"
        },
        "instanceName": {
          "description": "The user-friendly name of the Compute Engine instance.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "RddOperationNode": {
      "type": "object",
      "id": "RddOperationNode",
      "description": "A node in the RDD operation graph. Corresponds to a single RDD.",
      "properties": {
        "cached": {
          "type": "boolean"
        },
        "callsite": {
          "type": "string"
        },
        "nodeId": {
          "format": "int32",
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "barrier": {
          "type": "boolean"
        },
        "outputDeterministicLevel": {
          "enumDescriptions": [
            "",
            "",
            "",
            ""
          ],
          "type": "string",
          "enum": [
            "DETERMINISTIC_LEVEL_UNSPECIFIED",
            "DETERMINISTIC_LEVEL_DETERMINATE",
            "DETERMINISTIC_LEVEL_UNORDERED",
            "DETERMINISTIC_LEVEL_INDETERMINATE"
          ]
        }
      }
    },
    "ConfidentialInstanceConfig": {
      "type": "object",
      "description": "Confidential Instance Config for clusters using Confidential VMs (https://cloud.google.com/compute/confidential-vm/docs)",
      "properties": {
        "enableConfidentialCompute": {
          "description": "Optional. Deprecated: Use 'confidential_instance_type' instead. Defines whether the instance should have confidential compute enabled.",
          "type": "boolean",
          "deprecated": true
        }
      },
      "id": "ConfidentialInstanceConfig"
    },
    "SearchSparkApplicationExecutorsResponse": {
      "type": "object",
      "id": "SearchSparkApplicationExecutorsResponse",
      "description": "List of Executors associated with a Spark Application.",
      "properties": {
        "sparkApplicationExecutors": {
          "type": "array",
          "items": {
            "$ref": "ExecutorSummary"
          },
          "description": "Details about executors used by the application."
        },
        "nextPageToken": {
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSparkApplicationExecutorsListRequest.",
          "type": "string"
        }
      }
    },
    "SearchSessionSparkApplicationExecutorStageSummaryResponse": {
      "description": "List of Executors associated with a Spark Application Stage.",
      "properties": {
        "nextPageToken": {
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSessionSparkApplicationExecutorStageSummaryRequest.",
          "type": "string"
        },
        "sparkApplicationStageExecutors": {
          "type": "array",
          "items": {
            "$ref": "ExecutorStageSummary"
          },
          "description": "Details about executors used by the application stage."
        }
      },
      "id": "SearchSessionSparkApplicationExecutorStageSummaryResponse",
      "type": "object"
    },
    "ClusterOperationStatus": {
      "description": "The status of the operation.",
      "properties": {
        "innerState": {
          "type": "string",
          "description": "Output only. A message containing the detailed operation state.",
          "readOnly": true
        },
        "details": {
          "type": "string",
          "readOnly": true,
          "description": "Output only. A message containing any operation metadata details."
        },
        "stateStartTime": {
          "description": "Output only. The time this state was entered.",
          "readOnly": true,
          "format": "google-datetime",
          "type": "string"
        },
        "state": {
          "description": "Output only. A message containing the operation state.",
          "readOnly": true,
          "enumDescriptions": [
            "Unused.",
            "The operation has been created.",
            "The operation is running.",
            "The operation is done; either cancelled or completed."
          ],
          "type": "string",
          "enum": [
            "UNKNOWN",
            "PENDING",
            "RUNNING",
            "DONE"
          ]
        }
      },
      "id": "ClusterOperationStatus",
      "type": "object"
    },
    "SparkSqlJob": {
      "type": "object",
      "id": "SparkSqlJob",
      "description": "A Dataproc job for running Apache Spark SQL (https://spark.apache.org/sql/) queries.",
      "properties": {
        "properties": {
          "description": "Optional. A mapping of property names to values, used to configure Spark SQL's SparkConf. Properties that conflict with values set by the Dataproc API might be overwritten.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "queryList": {
          "description": "A list of queries.",
          "$ref": "QueryList"
        },
        "queryFileUri": {
          "type": "string",
          "description": "The HCFS URI of the script that contains SQL queries."
        },
        "scriptVariables": {
          "type": "object",
          "description": "Optional. Mapping of query variable names to values (equivalent to the Spark SQL command: SET name=\"value\";).",
          "additionalProperties": {
            "type": "string"
          }
        },
        "loggingConfig": {
          "description": "Optional. The runtime log config for job execution.",
          "$ref": "LoggingConfig"
        },
        "jarFileUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of jar files to be added to the Spark CLASSPATH."
        }
      }
    },
    "StageShuffleWriteMetrics": {
      "type": "object",
      "description": "Shuffle data written for the stage.",
      "properties": {
        "bytesWritten": {
          "type": "string",
          "format": "int64"
        },
        "recordsWritten": {
          "format": "int64",
          "type": "string"
        },
        "writeTimeNanos": {
          "type": "string",
          "format": "int64"
        }
      },
      "id": "StageShuffleWriteMetrics"
    },
    "PigJob": {
      "id": "PigJob",
      "description": "A Dataproc job for running Apache Pig (https://pig.apache.org/) queries on YARN.",
      "properties": {
        "queryFileUri": {
          "description": "The HCFS URI of the script that contains the Pig queries.",
          "type": "string"
        },
        "scriptVariables": {
          "type": "object",
          "description": "Optional. Mapping of query variable names to values (equivalent to the Pig command: name=[value]).",
          "additionalProperties": {
            "type": "string"
          }
        },
        "loggingConfig": {
          "description": "Optional. The runtime log config for job execution.",
          "$ref": "LoggingConfig"
        },
        "jarFileUris": {
          "description": "Optional. HCFS URIs of jar files to add to the CLASSPATH of the Pig Client and Hadoop MapReduce (MR) tasks. Can contain Pig UDFs.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "continueOnFailure": {
          "type": "boolean",
          "description": "Optional. Whether to continue executing queries if a query fails. The default value is false. Setting to true can be useful when executing independent parallel queries."
        },
        "properties": {
          "type": "object",
          "description": "Optional. A mapping of property names to values, used to configure Pig. Properties that conflict with values set by the Dataproc API might be overwritten. Can include properties set in /etc/hadoop/conf/*-site.xml, /etc/pig/conf/pig.properties, and classes in user code.",
          "additionalProperties": {
            "type": "string"
          }
        },
        "queryList": {
          "description": "A list of queries.",
          "$ref": "QueryList"
        }
      },
      "type": "object"
    },
    "JobScheduling": {
      "type": "object",
      "description": "Job scheduling options.",
      "properties": {
        "maxFailuresTotal": {
          "description": "Optional. Maximum total number of times a driver can be restarted as a result of the driver exiting with a non-zero code. After the maximum number is reached, the job will be reported as failed.Maximum value is 240.Note: Currently, this restartable job option is not supported in Dataproc workflow templates (https://cloud.google.com/dataproc/docs/concepts/workflows/using-workflows#adding_jobs_to_a_template).",
          "type": "integer",
          "format": "int32"
        },
        "maxFailuresPerHour": {
          "type": "integer",
          "format": "int32",
          "description": "Optional. Maximum number of times per hour a driver can be restarted as a result of driver exiting with non-zero code before job is reported failed.A job might be reported as thrashing if the driver exits with a non-zero code four times within a 10-minute window.Maximum value is 10.Note: This restartable job option is not supported in Dataproc workflow templates (https://cloud.google.com/dataproc/docs/concepts/workflows/using-workflows#adding_jobs_to_a_template)."
        }
      },
      "id": "JobScheduling"
    },
    "GoogleCloudDataprocV1WorkflowTemplateEncryptionConfig": {
      "type": "object",
      "id": "GoogleCloudDataprocV1WorkflowTemplateEncryptionConfig",
      "description": "Encryption settings for encrypting workflow template job arguments.",
      "properties": {
        "kmsKey": {
          "type": "string",
          "description": "Optional. The Cloud KMS key name to use for encrypting workflow template job arguments.When this this key is provided, the following workflow template job arguments (https://cloud.google.com/dataproc/docs/concepts/workflows/use-workflows#adding_jobs_to_a_template), if present, are CMEK encrypted (https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/customer-managed-encryption#use_cmek_with_workflow_template_data): FlinkJob args (https://cloud.google.com/[...]"
        }
      }
    },
    "AccessSparkApplicationSqlQueryResponse": {
      "description": "Details of a query for a Spark Application",
      "properties": {
        "executionData": {
          "description": "SQL Execution Data",
          "$ref": "SqlExecutionUiData"
        }
      },
      "id": "AccessSparkApplicationSqlQueryResponse",
      "type": "object"
    },
    "JobData": {
      "type": "object",
      "id": "JobData",
      "description": "Data corresponding to a spark job.",
      "properties": {
        "jobGroup": {
          "type": "string"
        },
        "completionTime": {
          "type": "string",
          "format": "google-datetime"
        },
        "numCompletedIndices": {
          "format": "int32",
          "type": "integer"
        },
        "numCompletedTasks": {
          "format": "int32",
          "type": "integer"
        },
        "skippedStages": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          }
        },
        "numSkippedStages": {
          "type": "integer",
          "format": "int32"
        },
        "numFailedStages": {
          "type": "integer",
          "format": "int32"
        },
        "sqlExecutionId": {
          "type": "string",
          "format": "int64"
        },
        "name": {
          "type": "string"
        },
        "numFailedTasks": {
          "type": "integer",
          "format": "int32"
        },
        "killTasksSummary": {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int32"
          }
        },
        "status": {
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            ""
          ],
          "type": "string",
          "enum": [
            "JOB_EXECUTION_STATUS_UNSPECIFIED",
            "JOB_EXECUTION_STATUS_RUNNING",
            "JOB_EXECUTION_STATUS_SUCCEEDED",
            "JOB_EXECUTION_STATUS_FAILED",
            "JOB_EXECUTION_STATUS_UNKNOWN"
          ]
        },
        "numActiveStages": {
          "type": "integer",
          "format": "int32"
        },
        "submissionTime": {
          "type": "string",
          "format": "google-datetime"
        },
        "numKilledTasks": {
          "type": "integer",
          "format": "int32"
        },
        "jobId": {
          "type": "string",
          "format": "int64"
        },
        "numActiveTasks": {
          "type": "integer",
          "format": "int32"
        },
        "numCompletedStages": {
          "format": "int32",
          "type": "integer"
        },
        "stageIds": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "int64"
          }
        },
        "description": {
          "type": "string"
        },
        "numTasks": {
          "format": "int32",
          "type": "integer"
        },
        "numSkippedTasks": {
          "format": "int32",
          "type": "integer"
        }
      }
    },
    "SparkSqlBatch": {
      "type": "object",
      "description": "A configuration for running Apache Spark SQL (https://spark.apache.org/sql/) queries as a batch workload.",
      "properties": {
        "queryFileUri": {
          "type": "string",
          "description": "Required. The HCFS URI of the script that contains Spark SQL queries to execute."
        },
        "jarFileUris": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. HCFS URIs of jar files to be added to the Spark CLASSPATH."
        },
        "queryVariables": {
          "description": "Optional. Mapping of query variable names to values (equivalent to the Spark SQL command: SET name=\"value\";).",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "id": "SparkSqlBatch"
    },
    "ExecutorMetricsDistributions": {
      "type": "object",
      "properties": {
        "taskTimeMillis": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        },
        "diskBytesSpilled": {
          "type": "array",
          "items": {
            "format": "double",
            "type": "number"
          }
        },
        "killedTasks": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        },
        "shuffleReadRecords": {
          "type": "array",
          "items": {
            "format": "double",
            "type": "number"
          }
        },
        "inputBytes": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        },
        "inputRecords": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        },
        "shuffleWriteRecords": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        },
        "shuffleRead": {
          "type": "array",
          "items": {
            "format": "double",
            "type": "number"
          }
        },
        "succeededTasks": {
          "type": "array",
          "items": {
            "format": "double",
            "type": "number"
          }
        },
        "outputRecords": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        },
        "failedTasks": {
          "type": "array",
          "items": {
            "format": "double",
            "type": "number"
          }
        },
        "outputBytes": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        },
        "memoryBytesSpilled": {
          "type": "array",
          "items": {
            "format": "double",
            "type": "number"
          }
        },
        "quantiles": {
          "type": "array",
          "items": {
            "format": "double",
            "type": "number"
          }
        },
        "peakMemoryMetrics": {
          "$ref": "ExecutorPeakMetricsDistributions"
        },
        "shuffleWrite": {
          "type": "array",
          "items": {
            "type": "number",
            "format": "double"
          }
        }
      },
      "id": "ExecutorMetricsDistributions"
    },
    "GkeNodePoolConfig": {
      "type": "object",
      "description": "The configuration of a GKE node pool used by a Dataproc-on-GKE cluster (https://cloud.google.com/dataproc/docs/concepts/jobs/dataproc-gke#create-a-dataproc-on-gke-cluster).",
      "properties": {
        "autoscaling": {
          "description": "Optional. The autoscaler configuration for this node pool. The autoscaler is enabled only when a valid configuration is present.",
          "$ref": "GkeNodePoolAutoscalingConfig"
        },
        "locations": {
          "description": "Optional. The list of Compute Engine zones (https://cloud.google.com/compute/docs/zones#available) where node pool nodes associated with a Dataproc on GKE virtual cluster will be located.Note: All node pools associated with a virtual cluster must be located in the same region as the virtual cluster, and they must be located in the same zone within that region.If a location is not specified during node pool creation, Dataproc on GKE will choose the zone.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "config": {
          "description": "Optional. The node pool configuration.",
          "$ref": "GkeNodeConfig"
        }
      },
      "id": "GkeNodePoolConfig"
    },
    "GkeNodePoolTarget": {
      "id": "GkeNodePoolTarget",
      "description": "GKE node pools that Dataproc workloads run on.",
      "properties": {
        "nodePoolConfig": {
          "description": "Input only. The configuration for the GKE node pool.If specified, Dataproc attempts to create a node pool with the specified shape. If one with the same name already exists, it is verified against all specified fields. If a field differs, the virtual cluster creation will fail.If omitted, any node pool with the specified name is used. If a node pool with the specified name does not exist, Dataproc create a node pool with default values.This is an input only field. It wi[...]",
          "$ref": "GkeNodePoolConfig"
        },
        "roles": {
          "description": "Required. The roles associated with the GKE node pool.",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "ROLE_UNSPECIFIED",
              "DEFAULT",
              "CONTROLLER",
              "SPARK_DRIVER",
              "SPARK_EXECUTOR"
            ],
            "enumDescriptions": [
              "Role is unspecified.",
              "At least one node pool must have the DEFAULT role. Work assigned to a role that is not associated with a node pool is assigned to the node pool with the DEFAULT role. For example, work assigned to the CONTROLLER role will be assigned to the node pool with the DEFAULT role if no node pool has the CONTROLLER role.",
              "Run work associated with the Dataproc control plane (for example, controllers and webhooks). Very low resource requirements.",
              "Run work associated with a Spark driver of a job.",
              "Run work associated with a Spark executor of a job."
            ]
          }
        },
        "nodePool": {
          "description": "Required. The target GKE node pool. Format: 'projects/{project}/locations/{location}/clusters/{cluster}/nodePools/{node_pool}'",
          "type": "string"
        }
      },
      "type": "object"
    },
    "SinkProgress": {
      "type": "object",
      "properties": {
        "numOutputRows": {
          "format": "int64",
          "type": "string"
        },
        "metrics": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "description": {
          "type": "string"
        }
      },
      "id": "SinkProgress"
    },
    "Job": {
      "description": "A Dataproc job resource.",
      "properties": {
        "sparkRJob": {
          "description": "Optional. Job is a SparkR job.",
          "$ref": "SparkRJob"
        },
        "sparkJob": {
          "description": "Optional. Job is a Spark job.",
          "$ref": "SparkJob"
        },
        "pysparkJob": {
          "description": "Optional. Job is a PySpark job.",
          "$ref": "PySparkJob"
        },
        "status": {
          "description": "Output only. The job status. Additional application-specific status information might be contained in the type_job and yarn_applications fields.",
          "readOnly": true,
          "$ref": "JobStatus"
        },
        "driverSchedulingConfig": {
          "description": "Optional. Driver scheduling configuration.",
          "$ref": "DriverSchedulingConfig"
        },
        "prestoJob": {
          "description": "Optional. Job is a Presto job.",
          "$ref": "PrestoJob"
        },
        "driverControlFilesUri": {
          "type": "string",
          "description": "Output only. If present, the location of miscellaneous control files which can be used as part of job setup and handling. If not present, control files might be placed in the same location as driver_output_uri.",
          "readOnly": true
        },
        "trinoJob": {
          "description": "Optional. Job is a Trino job.",
          "$ref": "TrinoJob"
        },
        "yarnApplications": {
          "type": "array",
          "items": {
            "$ref": "YarnApplication"
          },
          "description": "Output only. The collection of YARN applications spun up by this job.Beta Feature: This report is available for testing purposes only. It might be changed before final release.",
          "readOnly": true
        },
        "hadoopJob": {
          "description": "Optional. Job is a Hadoop job.",
          "$ref": "HadoopJob"
        },
        "statusHistory": {
          "description": "Output only. The previous job status.",
          "readOnly": true,
          "type": "array",
          "items": {
            "$ref": "JobStatus"
          }
        },
        "driverOutputResourceUri": {
          "type": "string",
          "description": "Output only. A URI pointing to the location of the stdout of the job's driver program.",
          "readOnly": true
        },
        "reference": {
          "description": "Optional. The fully qualified reference to the job, which can be used to obtain the equivalent REST path of the job resource. If this property is not specified when a job is created, the server generates a job_id.",
          "$ref": "JobReference"
        },
        "hiveJob": {
          "description": "Optional. Job is a Hive job.",
          "$ref": "HiveJob"
        },
        "jobUuid": {
          "type": "string",
          "readOnly": true,
          "description": "Output only. A UUID that uniquely identifies a job within the project over time. This is in contrast to a user-settable reference.job_id that might be reused over time."
        },
        "labels": {
          "type": "object",
          "description": "Optional. The labels to associate with this job. Label keys must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). Label values can be empty, but, if present, must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). No more than 32 labels can be associated with a job.",
          "additionalProperties": {
            "type": "string"
          }
        },
        "scheduling": {
          "description": "Optional. Job scheduling configuration.",
          "$ref": "JobScheduling"
        },
        "placement": {
          "description": "Required. Job information, including how, when, and where to run the job.",
          "$ref": "JobPlacement"
        },
        "pigJob": {
          "description": "Optional. Job is a Pig job.",
          "$ref": "PigJob"
        },
        "done": {
          "readOnly": true,
          "description": "Output only. Indicates whether the job is completed. If the value is false, the job is still in progress. If true, the job is completed, and status.state field will indicate if it was successful, failed, or cancelled.",
          "type": "boolean"
        },
        "sparkSqlJob": {
          "description": "Optional. Job is a SparkSql job.",
          "$ref": "SparkSqlJob"
        },
        "flinkJob": {
          "description": "Optional. Job is a Flink job.",
          "$ref": "FlinkJob"
        }
      },
      "id": "Job",
      "type": "object"
    },
    "ClusterOperationMetadata": {
      "id": "ClusterOperationMetadata",
      "description": "Metadata describing the operation.",
      "properties": {
        "description": {
          "description": "Output only. Short description of operation.",
          "readOnly": true,
          "type": "string"
        },
        "childOperationIds": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "readOnly": true,
          "description": "Output only. Child operation ids"
        },
        "statusHistory": {
          "type": "array",
          "items": {
            "$ref": "ClusterOperationStatus"
          },
          "description": "Output only. The previous operation status.",
          "readOnly": true
        },
        "clusterName": {
          "type": "string",
          "description": "Output only. Name of the cluster for the operation.",
          "readOnly": true
        },
        "warnings": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "readOnly": true,
          "description": "Output only. Errors encountered during operation execution."
        },
        "operationType": {
          "type": "string",
          "description": "Output only. The operation type.",
          "readOnly": true
        },
        "clusterUuid": {
          "type": "string",
          "readOnly": true,
          "description": "Output only. Cluster UUID for the operation."
        },
        "status": {
          "readOnly": true,
          "description": "Output only. Current operation status.",
          "$ref": "ClusterOperationStatus"
        },
        "labels": {
          "type": "object",
          "description": "Output only. Labels associated with the operation",
          "additionalProperties": {
            "type": "string"
          },
          "readOnly": true
        }
      },
      "type": "object"
    },
    "AccumulableInfo": {
      "type": "object",
      "properties": {
        "accumullableInfoId": {
          "type": "string",
          "format": "int64"
        },
        "value": {
          "type": "string"
        },
        "update": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "id": "AccumulableInfo"
    },
    "StateHistory": {
      "id": "StateHistory",
      "description": "Historical state information.",
      "properties": {
        "stateMessage": {
          "type": "string",
          "readOnly": true,
          "description": "Output only. Details about the state at this point in history."
        },
        "stateStartTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "Output only. The time when the batch entered the historical state.",
          "readOnly": true
        },
        "state": {
          "description": "Output only. The state of the batch at this point in history.",
          "enumDescriptions": [
            "The batch state is unknown.",
            "The batch is created before running.",
            "The batch is running.",
            "The batch is cancelling.",
            "The batch cancellation was successful.",
            "The batch completed successfully.",
            "The batch is no longer running due to an error."
          ],
          "readOnly": true,
          "type": "string",
          "enum": [
            "STATE_UNSPECIFIED",
            "PENDING",
            "RUNNING",
            "CANCELLING",
            "CANCELLED",
            "SUCCEEDED",
            "FAILED"
          ]
        }
      },
      "type": "object"
    },
    "LifecycleConfig": {
      "description": "Specifies the cluster auto-delete schedule configuration.",
      "properties": {
        "autoDeleteTtl": {
          "type": "string",
          "format": "google-duration",
          "description": "Optional. The lifetime duration of cluster. The cluster will be auto-deleted at the end of this period. Minimum value is 10 minutes; maximum value is 14 days (see JSON representation of Duration (https://developers.google.com/protocol-buffers/docs/proto3#json))."
        },
        "autoStopTime": {
          "description": "Optional. The time when cluster will be auto-stopped (see JSON representation of Timestamp (https://developers.google.com/protocol-buffers/docs/proto3#json)).",
          "type": "string",
[...]
