{
  "kind": "discovery#restDescription",
  "rootUrl": "https://dataplex.googleapis.com/",
  "version": "v1",
  "servicePath": "",
  "baseUrl": "https://dataplex.googleapis.com/",
  "discoveryVersion": "v1",
  "id": "dataplex:v1",
  "description": "A unified, intelligent governance solution for data and AI assets.",
  "revision": "20260429",
  "name": "dataplex",
  "protocol": "rest",
  "canonicalName": "Cloud Dataplex",
  "mtlsRootUrl": "https://dataplex.mtls.googleapis.com/",
  "basePath": "",
  "ownerName": "Google",
  "ownerDomain": "google.com",
  "title": "Cloud Dataplex API",
  "batchPath": "batch",
  "version_module": true,
  "resources": {
    "projects": {
      "resources": {
        "locations": {
          "methods": {
            "lookupEntryLinks": {
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:lookupEntryLinks",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/dataplex.read-write"
              ],
              "id": "dataplex.projects.locations.lookupEntryLinks",
              "path": "v1/{+name}:lookupEntryLinks",
              "description": "Looks up Entry Links referencing the specified Entry."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/dataplex.read-write"
              ],
              "id": "dataplex.projects.locations.list",
              "path": "v1/{+name}/locations",
              "description": "Lists information about the supported locations for this service.This method lists locations based on the resource scope provided in the ListLocationsRequest.name field: Global locations: If name is empty, the method lists the public locations available to all projects. Project-specific locations: If name follows the format projects/{project}, the method lists locations visible to that specific project. This includes public, private, or other project-specific locati[...]",
              "flatPath": "v1/projects/{projectsId}/locations",
              "httpMethod": "GET"
            },
            "lookupEntry": {
              "description": "Looks up an entry by name using the permission on the source system.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only",
                "https://www.googleapis.com/auth/dataplex.read-write",
                "https://www.googleapis.com/auth/dataplex.readonly"
              ],
              "id": "dataplex.projects.locations.lookupEntry",
              "path": "v1/{+name}:lookupEntry",
              "httpMethod": "GET",
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:lookupEntry"
            },
            "searchEntries": {
              "path": "v1/{+name}:searchEntries",
              "id": "dataplex.projects.locations.searchEntries",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only",
                "https://www.googleapis.com/auth/dataplex.read-write",
                "https://www.googleapis.com/auth/dataplex.readonly"
              ],
              "description": "Searches for Entries matching the given query and scope.",
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:searchEntries",
              "httpMethod": "POST"
            },
            "get": {
              "description": "Gets information about a location.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/dataplex.read-write"
              ],
              "path": "v1/{+name}",
              "id": "dataplex.projects.locations.get",
              "httpMethod": "GET",
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}"
            },
            "lookupContext": {
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:lookupContext",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only",
                "https://www.googleapis.com/auth/dataplex.read-write",
                "https://www.googleapis.com/auth/dataplex.readonly"
              ],
              "path": "v1/{+name}:lookupContext",
              "id": "dataplex.projects.locations.lookupContext",
              "description": "Looks up LLM Context for the specified resources."
            },
            "modifyEntry": {
              "httpMethod": "POST",
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:modifyEntry",
              "description": "Modifies an entry using the permission on the source system.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/dataplex.read-write"
              ],
              "id": "dataplex.projects.locations.modifyEntry",
              "path": "v1/{+name}:modifyEntry"
            }
          },
          "resources": {
            "entryGroups": {
              "resources": {
                "entries": {
                  "methods": {
                    "create": {
                      "description": "Creates an Entry.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.entryGroups.entries.create",
                      "path": "v1/{+parent}/entries",
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries"
                    },
                    "get": {
                      "id": "dataplex.projects.locations.entryGroups.entries.get",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "description": "Gets an Entry.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries/{entriesId}",
                      "httpMethod": "GET"
                    },
                    "patch": {
                      "id": "dataplex.projects.locations.entryGroups.entries.patch",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Updates an Entry.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries/{entriesId}",
                      "httpMethod": "PATCH"
                    },
                    "delete": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries/{entriesId}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.entryGroups.entries.delete",
                      "description": "Deletes an Entry."
                    },
                    "list": {
                      "description": "Lists Entries within an EntryGroup.",
                      "id": "dataplex.projects.locations.entryGroups.entries.list",
                      "path": "v1/{+parent}/entries",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries"
                    }
                  }
                },
                "entryLinks": {
                  "methods": {
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.entryGroups.entryLinks.patch",
                      "path": "v1/{+name}",
                      "description": "Updates an Entry Link.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entryLinks/{entryLinksId}",
                      "httpMethod": "PATCH"
                    },
                    "delete": {
                      "description": "Deletes an Entry Link.",
                      "id": "dataplex.projects.locations.entryGroups.entryLinks.delete",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "DELETE",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entryLinks/{entryLinksId}"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+parent}/entryLinks",
                      "id": "dataplex.projects.locations.entryGroups.entryLinks.create",
                      "description": "Creates an Entry Link.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entryLinks",
                      "httpMethod": "POST"
                    },
                    "get": {
                      "id": "dataplex.projects.locations.entryGroups.entryLinks.get",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Gets an Entry Link.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entryLinks/{entryLinksId}",
                      "httpMethod": "GET"
                    }
                  }
                }
              },
              "methods": {
                "create": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.entryGroups.create",
                  "path": "v1/{+parent}/entryGroups",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Creates an EntryGroup."
                },
                "get": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "id": "dataplex.projects.locations.entryGroups.get",
                  "path": "v1/{+name}",
                  "description": "Gets an EntryGroup."
                },
                "getIamPolicy": {
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:getIamPolicy",
                  "id": "dataplex.projects.locations.entryGroups.getIamPolicy",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}:getIamPolicy"
                },
                "testIamPermissions": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.entryGroups.testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.entryGroups.patch",
                  "description": "Updates an EntryGroup.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}",
                  "httpMethod": "PATCH"
                },
                "delete": {
                  "description": "Deletes an EntryGroup.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.entryGroups.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}"
                },
                "list": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "id": "dataplex.projects.locations.entryGroups.list",
                  "path": "v1/{+parent}/entryGroups",
                  "description": "Lists EntryGroup resources in a project and location."
                },
                "setIamPolicy": {
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataplex.projects.locations.entryGroups.setIamPolicy",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}:setIamPolicy"
                }
              }
            },
            "entryLinkTypes": {
              "methods": {
                "getIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.entryLinkTypes.getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryLinkTypes/{entryLinkTypesId}:getIamPolicy",
                  "httpMethod": "GET"
                },
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.entryLinkTypes.testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryLinkTypes/{entryLinkTypesId}:testIamPermissions",
                  "httpMethod": "POST"
                },
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryLinkTypes/{entryLinkTypesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.entryLinkTypes.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy"
                }
              }
            },
            "dataTaxonomies": {
              "resources": {
                "attributes": {
                  "methods": {
                    "create": {
                      "description": "Create a DataAttribute resource.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+parent}/attributes",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.create",
                      "httpMethod": "POST",
                      "deprecated": true,
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.get",
                      "description": "Retrieves a Data Attribute resource.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}",
                      "httpMethod": "GET",
                      "deprecated": true
                    },
                    "testIamPermissions": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}:testIamPermissions",
                      "httpMethod": "POST",
                      "path": "v1/{+resource}:testIamPermissions",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.testIamPermissions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                    },
                    "getIamPolicy": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+resource}:getIamPolicy",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}:getIamPolicy",
                      "httpMethod": "GET"
                    },
                    "setIamPolicy": {
                      "path": "v1/{+resource}:setIamPolicy",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}:setIamPolicy",
                      "httpMethod": "POST"
                    },
                    "patch": {
                      "description": "Updates a DataAttribute resource.",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.patch",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "deprecated": true,
                      "httpMethod": "PATCH",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "deprecated": true,
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}",
                      "description": "Deletes a Data Attribute resource.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.delete"
                    },
                    "list": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes",
                      "httpMethod": "GET",
                      "deprecated": true,
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+parent}/attributes",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.list",
                      "description": "Lists Data Attribute resources in a DataTaxonomy."
                    }
                  }
                }
              },
              "methods": {
                "patch": {
                  "description": "Updates a DataTaxonomy resource.",
                  "id": "dataplex.projects.locations.dataTaxonomies.patch",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "deprecated": true,
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}"
                },
                "delete": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}",
                  "httpMethod": "DELETE",
                  "deprecated": true,
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.dataTaxonomies.delete",
                  "description": "Deletes a DataTaxonomy resource. All attributes within the DataTaxonomy must be deleted before the DataTaxonomy can be deleted."
                },
                "list": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies",
                  "httpMethod": "GET",
                  "deprecated": true,
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+parent}/dataTaxonomies",
                  "id": "dataplex.projects.locations.dataTaxonomies.list",
                  "description": "Lists DataTaxonomy resources in a project and location."
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataplex.projects.locations.dataTaxonomies.setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}:setIamPolicy",
                  "httpMethod": "POST"
                },
                "getIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.dataTaxonomies.getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}:getIamPolicy",
                  "httpMethod": "GET"
                },
                "testIamPermissions": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.dataTaxonomies.testIamPermissions"
                },
                "create": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies",
                  "httpMethod": "POST",
                  "deprecated": true,
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+parent}/dataTaxonomies",
                  "id": "dataplex.projects.locations.dataTaxonomies.create",
                  "description": "Create a DataTaxonomy resource."
                },
                "get": {
                  "description": "Retrieves a DataTaxonomy resource.",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.dataTaxonomies.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "GET",
                  "deprecated": true,
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}"
                }
              }
            },
            "changeRequests": {
              "methods": {
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.changeRequests.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/changeRequests/{changeRequestsId}:testIamPermissions",
                  "httpMethod": "POST"
                },
                "getIamPolicy": {
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:getIamPolicy",
                  "id": "dataplex.projects.locations.changeRequests.getIamPolicy",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/changeRequests/{changeRequestsId}:getIamPolicy"
                },
                "setIamPolicy": {
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataplex.projects.locations.changeRequests.setIamPolicy",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/changeRequests/{changeRequestsId}:setIamPolicy"
                }
              }
            },
            "dataDomains": {
              "methods": {
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataDomains/{dataDomainsId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataplex.projects.locations.dataDomains.setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "testIamPermissions": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataDomains/{dataDomainsId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.dataDomains.testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "getIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataDomains/{dataDomainsId}:getIamPolicy",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.dataDomains.getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                }
              }
            },
            "governanceRules": {
              "methods": {
                "setIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/governanceRules/{governanceRulesId}:setIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.governanceRules.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.governanceRules.testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/governanceRules/{governanceRulesId}:testIamPermissions",
                  "httpMethod": "POST"
                },
                "getIamPolicy": {
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/governanceRules/{governanceRulesId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "path": "v1/{+resource}:getIamPolicy",
                  "id": "dataplex.projects.locations.governanceRules.getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            },
            "metadataFeeds": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds",
                  "description": "Retrieve a list of MetadataFeeds.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+parent}/metadataFeeds",
                  "id": "dataplex.projects.locations.metadataFeeds.list"
                },
                "delete": {
                  "description": "Deletes a MetadataFeed.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.metadataFeeds.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds/{metadataFeedsId}"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds/{metadataFeedsId}",
                  "description": "Updates a MetadataFeed.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.metadataFeeds.patch",
                  "path": "v1/{+name}"
                },
                "create": {
                  "id": "dataplex.projects.locations.metadataFeeds.create",
                  "path": "v1/{+parent}/metadataFeeds",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Creates a MetadataFeed.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds",
                  "httpMethod": "POST"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.metadataFeeds.get",
                  "path": "v1/{+name}",
                  "description": "Gets a MetadataFeed.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds/{metadataFeedsId}",
                  "httpMethod": "GET"
                }
              }
            },
            "entryTypes": {
              "methods": {
                "create": {
                  "path": "v1/{+parent}/entryTypes",
                  "id": "dataplex.projects.locations.entryTypes.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Creates an EntryType.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes",
                  "httpMethod": "POST"
                },
                "get": {
                  "description": "Gets an EntryType.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.entryTypes.get",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}"
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.entryTypes.testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}:testIamPermissions",
                  "httpMethod": "POST"
                },
                "getIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}:getIamPolicy",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:getIamPolicy",
                  "id": "dataplex.projects.locations.entryTypes.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                },
                "setIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}:setIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataplex.projects.locations.entryTypes.setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                },
                "patch": {
                  "description": "Updates an EntryType.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.entryTypes.patch",
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}",
                  "description": "Deletes an EntryType.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.entryTypes.delete",
                  "path": "v1/{+name}"
                },
                "list": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/entryTypes",
                  "id": "dataplex.projects.locations.entryTypes.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "description": "Lists EntryType resources in a project and location."
                }
              }
            },
            "glossaries": {
              "methods": {
                "testIamPermissions": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.glossaries.testIamPermissions"
                },
                "getIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}:getIamPolicy",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.glossaries.getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                },
                "setIamPolicy": {
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataplex.projects.locations.glossaries.setIamPolicy",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}:setIamPolicy"
                },
                "patch": {
                  "description": "Updates a Glossary resource.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.glossaries.patch",
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}",
                  "description": "Deletes a Glossary resource. All the categories and terms within the Glossary must be deleted before the Glossary can be deleted.",
                  "id": "dataplex.projects.locations.glossaries.delete",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries",
                  "description": "Lists Glossary resources in a project and location.",
                  "id": "dataplex.projects.locations.glossaries.list",
                  "path": "v1/{+parent}/glossaries",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ]
                },
                "create": {
                  "description": "Creates a new Glossary resource.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.glossaries.create",
                  "path": "v1/{+parent}/glossaries",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries"
                },
                "get": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.glossaries.get",
                  "description": "Gets a Glossary resource."
                }
              },
              "resources": {
                "categories": {
                  "methods": {
                    "create": {
                      "description": "Creates a new GlossaryCategory resource.",
                      "path": "v1/{+parent}/categories",
                      "id": "dataplex.projects.locations.glossaries.categories.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories"
                    },
                    "get": {
                      "description": "Gets a GlossaryCategory resource.",
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.glossaries.categories.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}"
                    },
                    "setIamPolicy": {
                      "id": "dataplex.projects.locations.glossaries.categories.setIamPolicy",
                      "path": "v1/{+resource}:setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}:setIamPolicy",
                      "httpMethod": "POST"
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.glossaries.categories.patch",
                      "description": "Updates a GlossaryCategory resource.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}",
                      "httpMethod": "PATCH"
                    },
                    "delete": {
                      "id": "dataplex.projects.locations.glossaries.categories.delete",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Deletes a GlossaryCategory resource. All the GlossaryCategories and GlossaryTerms nested directly under the specified GlossaryCategory will be moved one level up to the parent in the hierarchy.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}",
                      "httpMethod": "DELETE"
                    },
                    "list": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories",
                      "httpMethod": "GET",
                      "path": "v1/{+parent}/categories",
                      "id": "dataplex.projects.locations.glossaries.categories.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "description": "Lists GlossaryCategory resources in a Glossary."
                    },
                    "testIamPermissions": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}:testIamPermissions",
                      "httpMethod": "POST",
                      "path": "v1/{+resource}:testIamPermissions",
                      "id": "dataplex.projects.locations.glossaries.categories.testIamPermissions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                    },
                    "getIamPolicy": {
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.glossaries.categories.getIamPolicy",
                      "path": "v1/{+resource}:getIamPolicy",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}:getIamPolicy"
                    }
                  }
                },
                "terms": {
                  "methods": {
                    "getIamPolicy": {
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}:getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+resource}:getIamPolicy",
                      "id": "dataplex.projects.locations.glossaries.terms.getIamPolicy"
                    },
                    "testIamPermissions": {
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}:testIamPermissions",
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.glossaries.terms.testIamPermissions",
                      "path": "v1/{+resource}:testIamPermissions"
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}",
                      "description": "Updates a GlossaryTerm resource.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.glossaries.terms.patch"
                    },
                    "delete": {
                      "description": "Deletes a GlossaryTerm resource.",
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.glossaries.terms.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "DELETE",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}"
                    },
                    "list": {
                      "description": "Lists GlossaryTerm resources in a Glossary.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "id": "dataplex.projects.locations.glossaries.terms.list",
                      "path": "v1/{+parent}/terms",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms"
                    },
                    "setIamPolicy": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}:setIamPolicy",
                      "httpMethod": "POST",
                      "id": "dataplex.projects.locations.glossaries.terms.setIamPolicy",
                      "path": "v1/{+resource}:setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                    },
                    "create": {
                      "path": "v1/{+parent}/terms",
                      "id": "dataplex.projects.locations.glossaries.terms.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Creates a new GlossaryTerm resource.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms",
                      "httpMethod": "POST"
                    },
                    "get": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.glossaries.terms.get",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "description": "Gets a GlossaryTerm resource."
                    }
                  }
                }
              }
            },
            "dataProducts": {
              "methods": {
                "delete": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.dataProducts.delete",
                  "description": "Deletes a data product. The deletion will fail if the data product is not empty (i.e. contains at least one data asset)."
                },
                "list": {
                  "description": "Lists data products for a given project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "path": "v1/{+parent}/dataProducts",
                  "id": "dataplex.projects.locations.dataProducts.list",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}",
                  "description": "Updates a data product.",
                  "id": "dataplex.projects.locations.dataProducts.patch",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "setIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}:setIamPolicy",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.dataProducts.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                },
                "getIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}:getIamPolicy",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.dataProducts.getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                },
                "testIamPermissions": {
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.dataProducts.testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}:testIamPermissions"
                },
                "create": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+parent}/dataProducts",
                  "id": "dataplex.projects.locations.dataProducts.create",
                  "description": "Creates a data product."
                },
                "get": {
                  "id": "dataplex.projects.locations.dataProducts.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "description": "Gets a data product.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}",
                  "httpMethod": "GET"
                }
              },
              "resources": {
                "dataAssets": {
                  "methods": {
                    "create": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.create",
                      "path": "v1/{+parent}/dataAssets",
                      "description": "Creates a data asset."
                    },
                    "get": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets/{dataAssetsId}",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.get",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "description": "Gets a data asset."
                    },
                    "patch": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets/{dataAssetsId}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.patch",
                      "description": "Updates a data asset."
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets/{dataAssetsId}",
                      "description": "Deletes a data asset.",
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "list": {
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets",
                      "description": "Lists data assets for a given data product.",
                      "path": "v1/{+parent}/dataAssets",
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    }
                  }
                }
              }
            },
            "aspectTypes": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.aspectTypes.create",
                  "path": "v1/{+parent}/aspectTypes",
                  "description": "Creates an AspectType.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes",
                  "httpMethod": "POST"
                },
                "get": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.aspectTypes.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "description": "Gets an AspectType."
                },
                "setIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}:setIamPolicy",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.aspectTypes.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}",
                  "description": "Updates an AspectType.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.aspectTypes.patch",
                  "path": "v1/{+name}"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.aspectTypes.delete",
                  "description": "Deletes an AspectType.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "path": "v1/{+parent}/aspectTypes",
                  "id": "dataplex.projects.locations.aspectTypes.list",
                  "description": "Lists AspectType resources in a project and location.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes",
                  "httpMethod": "GET"
                },
                "testIamPermissions": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}:testIamPermissions",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.aspectTypes.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                },
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "id": "dataplex.projects.locations.aspectTypes.getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}:getIamPolicy",
                  "httpMethod": "GET"
                }
              }
            },
            "dataScans": {
              "methods": {
                "setIamPolicy": {
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.dataScans.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:setIamPolicy"
                },
                "patch": {
                  "description": "Updates a DataScan resource.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.dataScans.patch",
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}",
                  "description": "Deletes a DataScan resource.",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.dataScans.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "generateDataQualityRules": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:generateDataQualityRules",
                  "description": "Generates recommended data quality rules based on the results of a data profiling scan.Use the recommendations to build rules for a data quality scan.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}:generateDataQualityRules",
                  "id": "dataplex.projects.locations.dataScans.generateDataQualityRules"
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans",
                  "description": "Creates a DataScan resource.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+parent}/dataScans",
                  "id": "dataplex.projects.locations.dataScans.create"
                },
                "get": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.dataScans.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "description": "Gets a DataScan resource."
                },
                "list": {
                  "path": "v1/{+parent}/dataScans",
                  "id": "dataplex.projects.locations.dataScans.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "description": "Lists DataScans.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans",
                  "httpMethod": "GET"
                },
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.dataScans.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:testIamPermissions",
                  "httpMethod": "POST"
                },
                "getIamPolicy": {
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.dataScans.getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy"
                },
                "run": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:run",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.dataScans.run",
                  "path": "v1/{+name}:run",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Runs an on-demand execution of a DataScan"
                }
              },
              "resources": {
                "jobs": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "path": "v1/{+parent}/jobs",
                      "id": "dataplex.projects.locations.dataScans.jobs.list",
                      "description": "Lists DataScanJobs under the given DataScan.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}/jobs",
                      "httpMethod": "GET"
                    },
                    "get": {
                      "description": "Gets a DataScanJob resource.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.dataScans.jobs.get",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}/jobs/{jobsId}"
                    },
                    "cancel": {
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}/jobs/{jobsId}:cancel",
                      "description": "Cancels a running/pending DataScan job.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.dataScans.jobs.cancel",
                      "path": "v1/{+name}:cancel"
                    },
                    "generateDataQualityRules": {
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}/jobs/{jobsId}:generateDataQualityRules",
                      "description": "Generates recommended data quality rules based on the results of a data profiling scan.Use the recommendations to build rules for a data quality scan.",
                      "path": "v1/{+name}:generateDataQualityRules",
                      "id": "dataplex.projects.locations.dataScans.jobs.generateDataQualityRules",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    }
                  }
                }
              }
            },
            "operations": {
              "methods": {
                "list": {
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns UNIMPLEMENTED.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.operations.list",
                  "path": "v1/{+name}/operations",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations"
                },
                "delete": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "httpMethod": "DELETE",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.operations.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED."
                },
                "get": {
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.operations.get"
                },
                "cancel": {
                  "path": "v1/{+name}:cancel",
                  "id": "dataplex.projects.locations.operations.cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it beco[...]",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}:cancel",
                  "httpMethod": "POST"
                }
              }
            },
            "metadataJobs": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.metadataJobs.create",
                  "path": "v1/{+parent}/metadataJobs",
                  "description": "Creates a metadata job. For example, use a metadata job to import metadata from a third-party system into Dataplex Universal Catalog.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataJobs",
                  "httpMethod": "POST"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.metadataJobs.get",
                  "path": "v1/{+name}",
                  "description": "Gets a metadata job.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataJobs/{metadataJobsId}",
                  "httpMethod": "GET"
                },
                "cancel": {
                  "description": "Cancels a metadata job.If you cancel a metadata import job that is in progress, the changes in the job might be partially applied. We recommend that you reset the state of the entry groups in your project by running another metadata job that reverts the changes from the canceled job.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.metadataJobs.cancel",
                  "path": "v1/{+name}:cancel",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataJobs/{metadataJobsId}:cancel"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+parent}/metadataJobs",
                  "id": "dataplex.projects.locations.metadataJobs.list",
                  "description": "Lists metadata jobs.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataJobs",
                  "httpMethod": "GET"
                }
              }
            },
            "lakes": {
              "methods": {
                "create": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.lakes.create",
                  "path": "v1/{+parent}/lakes",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Creates a lake resource."
                },
                "get": {
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.lakes.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "description": "Retrieves a lake resource.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}",
                  "httpMethod": "GET"
                },
                "setIamPolicy": {
                  "id": "dataplex.projects.locations.lakes.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}:setIamPolicy",
                  "httpMethod": "POST"
                },
                "patch": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.lakes.patch",
                  "path": "v1/{+name}",
                  "description": "Updates a lake resource."
                },
                "delete": {
                  "id": "dataplex.projects.locations.lakes.delete",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Deletes a lake resource. All zones within the lake must be deleted before the lake can be deleted.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "id": "dataplex.projects.locations.lakes.list",
                  "path": "v1/{+parent}/lakes",
                  "description": "Lists lake resources in a project and location."
                },
                "testIamPermissions": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}:testIamPermissions",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.lakes.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                },
                "getIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:getIamPolicy",
                  "id": "dataplex.projects.locations.lakes.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}:getIamPolicy",
                  "httpMethod": "GET"
                }
              },
              "resources": {
                "tasks": {
                  "methods": {
                    "setIamPolicy": {
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}:setIamPolicy",
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "path": "v1/{+resource}:setIamPolicy",
                      "id": "dataplex.projects.locations.lakes.tasks.setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}",
                      "description": "Update the task resource.",
                      "id": "dataplex.projects.locations.lakes.tasks.patch",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "delete": {
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.lakes.tasks.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Delete the task resource.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}",
                      "httpMethod": "DELETE"
                    },
                    "list": {
                      "description": "Lists tasks under the given lake.",
                      "id": "dataplex.projects.locations.lakes.tasks.list",
                      "path": "v1/{+parent}/tasks",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks"
                    },
                    "testIamPermissions": {
                      "id": "dataplex.projects.locations.lakes.tasks.testIamPermissions",
                      "path": "v1/{+resource}:testIamPermissions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}:testIamPermissions",
                      "httpMethod": "POST"
                    },
                    "getIamPolicy": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.lakes.tasks.getIamPolicy",
                      "path": "v1/{+resource}:getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}:getIamPolicy",
                      "httpMethod": "GET"
                    },
                    "run": {
                      "description": "Run an on demand execution of a Task.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+name}:run",
                      "id": "dataplex.projects.locations.lakes.tasks.run",
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}:run"
                    },
                    "create": {
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks",
                      "description": "Creates a task resource within a lake.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.lakes.tasks.create",
                      "path": "v1/{+parent}/tasks"
                    },
                    "get": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.lakes.tasks.get",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "description": "Get task resource."
                    }
                  },
                  "resources": {
                    "jobs": {
                      "methods": {
                        "get": {
                          "httpMethod": "GET",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}/jobs/{jobsId}",
                          "description": "Get job resource.",
                          "path": "v1/{+name}",
                          "id": "dataplex.projects.locations.lakes.tasks.jobs.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ]
                        },
                        "cancel": {
                          "httpMethod": "POST",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}/jobs/{jobsId}:cancel",
                          "description": "Cancel jobs running for the task resource.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "id": "dataplex.projects.locations.lakes.tasks.jobs.cancel",
                          "path": "v1/{+name}:cancel"
                        },
                        "list": {
                          "description": "Lists Jobs under the given task.",
                          "id": "dataplex.projects.locations.lakes.tasks.jobs.list",
                          "path": "v1/{+parent}/jobs",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ],
                          "httpMethod": "GET",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}/jobs"
                        }
                      }
                    }
                  }
                },
                "actions": {
                  "methods": {
                    "list": {
                      "description": "Lists action resources in a lake.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "id": "dataplex.projects.locations.lakes.actions.list",
                      "path": "v1/{+parent}/actions",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/actions"
                    }
                  }
                },
                "zones": {
                  "resources": {
                    "actions": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ],
                          "path": "v1/{+parent}/actions",
                          "id": "dataplex.projects.locations.lakes.zones.actions.list",
                          "description": "Lists action resources in a zone.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/actions",
                          "httpMethod": "GET"
                        }
                      }
                    },
                    "assets": {
                      "resources": {
                        "actions": {
                          "methods": {
                            "list": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/cloud-platform.read-only",
                                "https://www.googleapis.com/auth/dataplex.read-write",
                                "https://www.googleapis.com/auth/dataplex.readonly"
                              ],
                              "path": "v1/{+parent}/actions",
                              "id": "dataplex.projects.locations.lakes.zones.assets.actions.list",
                              "description": "Lists action resources in an asset.",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}/actions",
                              "httpMethod": "GET"
                            }
                          }
                        }
                      },
                      "methods": {
                        "getIamPolicy": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}:getIamPolicy",
                          "httpMethod": "GET",
                          "path": "v1/{+resource}:getIamPolicy",
                          "id": "dataplex.projects.locations.lakes.zones.assets.getIamPolicy",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                        },
                        "testIamPermissions": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "id": "dataplex.projects.locations.lakes.zones.assets.testIamPermissions",
                          "path": "v1/{+resource}:testIamPermissions",
                          "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}:testIamPermissions",
                          "httpMethod": "POST"
                        },
                        "patch": {
                          "httpMethod": "PATCH",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}",
                          "description": "Updates an asset resource.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "path": "v1/{+name}",
                          "id": "dataplex.projects.locations.lakes.zones.assets.patch"
                        },
                        "delete": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "id": "dataplex.projects.locations.lakes.zones.assets.delete",
                          "path": "v1/{+name}",
                          "description": "Deletes an asset resource. The referenced storage resource is detached (default) or deleted based on the associated Lifecycle policy."
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ],
                          "id": "dataplex.projects.locations.lakes.zones.assets.list",
                          "path": "v1/{+parent}/assets",
                          "description": "Lists asset resources in a zone.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets",
                          "httpMethod": "GET"
                        },
                        "setIamPolicy": {
                          "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                          "id": "dataplex.projects.locations.lakes.zones.assets.setIamPolicy",
                          "path": "v1/{+resource}:setIamPolicy",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "httpMethod": "POST",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}:setIamPolicy"
                        },
                        "create": {
                          "description": "Creates an asset resource.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "path": "v1/{+parent}/assets",
                          "id": "dataplex.projects.locations.lakes.zones.assets.create",
                          "httpMethod": "POST",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}",
                          "description": "Retrieves an asset resource.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ],
                          "id": "dataplex.projects.locations.lakes.zones.assets.get",
                          "path": "v1/{+name}"
                        }
                      }
                    },
                    "entities": {
                      "methods": {
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "path": "v1/{+name}",
                          "id": "dataplex.projects.locations.lakes.zones.entities.delete",
                          "description": "Delete a metadata entity.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}",
                          "httpMethod": "DELETE"
                        },
                        "list": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities",
                          "httpMethod": "GET",
                          "path": "v1/{+parent}/entities",
                          "id": "dataplex.projects.locations.lakes.zones.entities.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "description": "List metadata entities in a zone."
                        },
                        "update": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "id": "dataplex.projects.locations.lakes.zones.entities.update",
                          "path": "v1/{+name}",
                          "description": "Update a metadata entity. Only supports full resource update.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}",
                          "httpMethod": "PUT"
                        },
                        "create": {
                          "httpMethod": "POST",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities",
                          "description": "Create a metadata entity.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "id": "dataplex.projects.locations.lakes.zones.entities.create",
                          "path": "v1/{+parent}/entities"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}",
                          "description": "Get a metadata entity.",
                          "id": "dataplex.projects.locations.lakes.zones.entities.get",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ]
                        }
                      },
                      "resources": {
                        "partitions": {
                          "methods": {
                            "create": {
                              "description": "Create a metadata partition.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/dataplex.read-write"
                              ],
                              "path": "v1/{+parent}/partitions",
                              "id": "dataplex.projects.locations.lakes.zones.entities.partitions.create",
                              "httpMethod": "POST",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}/partitions"
                            },
                            "get": {
                              "httpMethod": "GET",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}/partitions/{partitionsId}",
                              "description": "Get a metadata partition of an entity.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/dataplex.read-write"
                              ],
                              "path": "v1/{+name}",
                              "id": "dataplex.projects.locations.lakes.zones.entities.partitions.get"
                            },
                            "delete": {
                              "httpMethod": "DELETE",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}/partitions/{partitionsId}",
                              "description": "Delete a metadata partition.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/dataplex.read-write"
                              ],
                              "path": "v1/{+name}",
                              "id": "dataplex.projects.locations.lakes.zones.entities.partitions.delete"
                            },
                            "list": {
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}/partitions",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/dataplex.read-write"
                              ],
                              "id": "dataplex.projects.locations.lakes.zones.entities.partitions.list",
                              "path": "v1/{+parent}/partitions",
                              "description": "List metadata partitions of an entity."
                            }
                          }
                        }
                      }
                    }
                  },
                  "methods": {
                    "create": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones",
                      "httpMethod": "POST",
                      "id": "dataplex.projects.locations.lakes.zones.create",
                      "path": "v1/{+parent}/zones",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "description": "Creates a zone resource within a lake."
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.lakes.zones.get",
                      "description": "Retrieves a zone resource.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}",
                      "httpMethod": "GET"
                    },
                    "getIamPolicy": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.lakes.zones.getIamPolicy",
                      "path": "v1/{+resource}:getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}:getIamPolicy",
                      "httpMethod": "GET"
                    },
                    "testIamPermissions": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+resource}:testIamPermissions",
                      "id": "dataplex.projects.locations.lakes.zones.testIamPermissions",
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}:testIamPermissions",
                      "httpMethod": "POST"
                    },
                    "patch": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.lakes.zones.patch",
                      "path": "v1/{+name}",
                      "description": "Updates a zone resource."
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "id": "dataplex.projects.locations.lakes.zones.delete",
                      "path": "v1/{+name}",
                      "description": "Deletes a zone resource. All assets within a zone must be deleted before the zone can be deleted.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}",
                      "httpMethod": "DELETE"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones",
                      "description": "Lists zone resources in a lake.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "path": "v1/{+parent}/zones",
                      "id": "dataplex.projects.locations.lakes.zones.list"
                    },
                    "setIamPolicy": {
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+resource}:setIamPolicy",
                      "id": "dataplex.projects.locations.lakes.zones.setIamPolicy",
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}:setIamPolicy"
                    }
                  }
                }
              }
            },
            "dataAttributeBindings": {
              "methods": {
                "patch": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}",
                  "deprecated": true,
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.projects.locations.dataAttributeBindings.patch",
                  "path": "v1/{+name}",
                  "description": "Updates a DataAttributeBinding resource."
                },
                "delete": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}",
                  "httpMethod": "DELETE",
                  "deprecated": true,
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.dataAttributeBindings.delete",
                  "description": "Deletes a DataAttributeBinding resource. All attributes within the DataAttributeBinding must be deleted before the DataAttributeBinding can be deleted."
                },
                "list": {
                  "path": "v1/{+parent}/dataAttributeBindings",
                  "id": "dataplex.projects.locations.dataAttributeBindings.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Lists DataAttributeBinding resources in a project and location.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings",
                  "httpMethod": "GET",
                  "deprecated": true
                },
                "setIamPolicy": {
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataplex.projects.locations.dataAttributeBindings.setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}:setIamPolicy"
                },
                "getIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:getIamPolicy",
                  "id": "dataplex.projects.locations.dataAttributeBindings.getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}:getIamPolicy",
                  "httpMethod": "GET"
                },
                "testIamPermissions": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}:testIamPermissions",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.dataAttributeBindings.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                },
                "create": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings",
                  "httpMethod": "POST",
                  "deprecated": true,
                  "path": "v1/{+parent}/dataAttributeBindings",
                  "id": "dataplex.projects.locations.dataAttributeBindings.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Create a DataAttributeBinding resource."
                },
                "get": {
                  "deprecated": true,
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}",
                  "description": "Retrieves a DataAttributeBinding resource.",
                  "id": "dataplex.projects.locations.dataAttributeBindings.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "organizations": {
      "resources": {
        "locations": {
          "resources": {
            "encryptionConfigs": {
              "methods": {
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.organizations.locations.encryptionConfigs.patch",
                  "path": "v1/{+name}",
                  "description": "Update an EncryptionConfig.",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}",
                  "httpMethod": "PATCH"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.organizations.locations.encryptionConfigs.delete",
                  "path": "v1/{+name}",
                  "description": "Delete an EncryptionConfig.",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.organizations.locations.encryptionConfigs.list",
                  "path": "v1/{+parent}/encryptionConfigs",
                  "description": "List EncryptionConfigs."
                },
                "setIamPolicy": {
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataplex.organizations.locations.encryptionConfigs.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}:setIamPolicy"
                },
                "getIamPolicy": {
                  "httpMethod": "GET",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:getIamPolicy",
                  "id": "dataplex.organizations.locations.encryptionConfigs.getIamPolicy"
                },
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.organizations.locations.encryptionConfigs.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}:testIamPermissions",
                  "httpMethod": "POST"
                },
                "create": {
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+parent}/encryptionConfigs",
                  "id": "dataplex.organizations.locations.encryptionConfigs.create",
                  "description": "Create an EncryptionConfig."
                },
                "get": {
                  "description": "Get an EncryptionConfig.",
                  "id": "dataplex.organizations.locations.encryptionConfigs.get",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}"
                }
              }
            },
            "operations": {
              "methods": {
                "get": {
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/operations/{operationsId}",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "id": "dataplex.organizations.locations.operations.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                },
                "cancel": {
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it beco[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}:cancel",
                  "id": "dataplex.organizations.locations.operations.cancel",
                  "httpMethod": "POST",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/operations/{operationsId}:cancel"
                },
                "list": {
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns UNIMPLEMENTED.",
                  "id": "dataplex.organizations.locations.operations.list",
                  "path": "v1/{+name}/operations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/operations"
                },
                "delete": {
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/operations/{operationsId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "id": "dataplex.organizations.locations.operations.delete",
                  "path": "v1/{+name}",
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED."
                }
              }
            }
          }
        }
      }
    }
  },
  "documentationLink": "https://cloud.google.com/dataplex/docs",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dataplex.read-write": {
          "description": "See, edit, configure, and delete your Google Cloud Dataplex data and see the email address for your Google Account"
        },
        "https://www.googleapis.com/auth/dataplex.readonly": {
          "description": "See your Google Cloud Dataplex data and the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud services and see the email address of your Google Account"
        }
      }
    }
  }
}