{
  "id": "dataproc:v1",
  "title": "Cloud Dataproc API",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "servicePath": "",
  "rootUrl": "https://dataproc.googleapis.com/",
  "canonicalName": "Dataproc",
  "baseUrl": "https://dataproc.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dataproc": {
          "description": "See, edit, configure, and delete your Google Cloud Dataproc data and see the email address for your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/dataproc.read-only": {
          "description": "See your Google Cloud Dataproc data and the email address of your Google Account"
        }
      }
    }
  },
  "resources": {
    "projects": {
      "resources": {
        "locations": {
          "resources": {
            "operations": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "id": "dataproc.projects.locations.operations.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                },
                "cancel": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.operations.cancel",
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it beco[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+name}:cancel",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}:cancel"
                },
                "list": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns UNIMPLEMENTED.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "id": "dataproc.projects.locations.operations.list",
                  "httpMethod": "GET"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED.",
                  "httpMethod": "DELETE",
                  "id": "dataproc.projects.locations.operations.delete"
                }
              }
            },
            "sessionTemplates": {
              "methods": {
                "get": {
                  "description": "Gets the resource representation for a session template.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "id": "dataproc.projects.locations.sessionTemplates.get",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates/{sessionTemplatesId}"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "dataproc.projects.locations.sessionTemplates.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Deletes a session template.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates/{sessionTemplatesId}"
                },
                "list": {
                  "httpMethod": "GET",
                  "id": "dataproc.projects.locations.sessionTemplates.list",
                  "description": "Lists session templates.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "path": "v1/{+parent}/sessionTemplates",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates"
                },
                "create": {
                  "path": "v1/{+parent}/sessionTemplates",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Create a session template synchronously.",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.sessionTemplates.create"
                },
                "patch": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates/{sessionTemplatesId}",
                  "httpMethod": "PATCH",
                  "id": "dataproc.projects.locations.sessionTemplates.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Updates the session template synchronously."
                }
              }
            },
            "autoscalingPolicies": {
              "methods": {
                "list": {
                  "path": "v1/{+parent}/autoscalingPolicies",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.locations.autoscalingPolicies.list",
                  "description": "Lists autoscaling policies in the project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "getIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataproc.projects.locations.autoscalingPolicies.getIamPolicy",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}:getIamPolicy"
                },
                "create": {
                  "path": "v1/{+parent}/autoscalingPolicies",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies",
                  "description": "Creates new autoscaling policy.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.locations.autoscalingPolicies.create",
                  "httpMethod": "POST"
                },
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.autoscalingPolicies.setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}:setIamPolicy"
                },
                "update": {
                  "description": "Updates (replaces) autoscaling policy.Disabled check for update_mask, because all updates will be full replacements.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.locations.autoscalingPolicies.update",
                  "httpMethod": "PUT",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}"
                },
                "get": {
                  "id": "dataproc.projects.locations.autoscalingPolicies.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Retrieves autoscaling policy.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Deletes an autoscaling policy. It is an error to delete an autoscaling policy that is in use by one or more clusters.",
                  "httpMethod": "DELETE",
                  "id": "dataproc.projects.locations.autoscalingPolicies.delete",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}"
                },
                "testIamPermissions": {
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.autoscalingPolicies.testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}:testIamPermissions"
                }
              }
            },
            "sessions": {
              "resources": {
                "sparkApplications": {
                  "methods": {
                    "summarizeExecutors": {
                      "id": "dataproc.projects.locations.sessions.sparkApplications.summarizeExecutors",
                      "httpMethod": "GET",
                      "description": "Obtain summary of Executor Summary for a Spark Application",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "path": "v1/{+name}:summarizeExecutors",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:summarizeExecutors"
                    },
                    "searchJobs": {
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchJobs",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain list of spark jobs corresponding to a Spark Application.",
                      "path": "v1/{+name}:searchJobs",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchJobs"
                    },
                    "accessEnvironmentInfo": {
                      "path": "v1/{+name}:accessEnvironmentInfo",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessEnvironmentInfo",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain environment details for a Spark Application",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessEnvironmentInfo"
                    },
                    "searchSqlQueries": {
                      "path": "v1/{+name}:searchSqlQueries",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchSqlQueries",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchSqlQueries",
                      "parameters": {
                        "parent": {
                          "description": "Required. Parent (Session) resource reference.",
                          "location": "query",
                          "type": "string"
                        },
                        "details": {
                          "location": "query",
                          "description": "Optional. Lists/ hides details of Spark plan nodes. True is set to list and false to hide.",
                          "type": "boolean"
                        },
                        "planDescription": {
                          "description": "Optional. Enables/ disables physical plan description on demand",
                          "location": "query",
                          "type": "boolean"
                        },
                        "name": {
                          "type": "string",
                          "location": "path",
                          "required": true,
                          "pattern": "^projects/[^/]+/locations/[^/]+/sessions/[^/]+/sparkApplications/[^/]+$",
                          "description": "Required. The fully qualified name of the session to retrieve in the format \"projects/PROJECT_ID/locations/DATAPROC_REGION/sessions/SESSION_ID/sparkApplications/APPLICATION_ID\""
                        },
                        "pageSize": {
                          "location": "query",
                          "description": "Optional. Maximum number of queries to return in each response. The service may return fewer than this. The default page size is 10; the maximum page size is 100.",
                          "type": "integer",
                          "format": "int32"
                        },
                        "pageToken": {
                          "description": "Optional. A page token received from a previous SearchSessionSparkApplicationSqlQueries call. Provide this token to retrieve the subsequent page.",
                          "location": "query",
                          "type": "string"
                        },
                        "operationIds": {
                          "location": "query",
                          "repeated": true,
                          "description": "Optional. List of Spark Connect operation IDs to filter by if provided.",
                          "type": "string"
                        }
                      },
                      "description": "Obtain data corresponding to SQL Queries for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "search": {
                      "path": "v1/{+parent}/sparkApplications:search",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications:search",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain high level information and list of Spark Applications corresponding to a batch",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.search"
                    },
                    "searchStageAttemptTasks": {
                      "path": "v1/{+name}:searchStageAttemptTasks",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchStageAttemptTasks",
                      "description": "Obtain data corresponding to tasks for a spark stage attempt for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchStageAttemptTasks",
                      "httpMethod": "GET"
                    },
                    "searchExecutors": {
                      "path": "v1/{+name}:searchExecutors",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchExecutors",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to executors for a Spark Application.",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchExecutors"
                    },
                    "summarizeStageAttemptTasks": {
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.summarizeStageAttemptTasks",
                      "description": "Obtain summary of Tasks for a Spark Application Stage Attempt",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "path": "v1/{+name}:summarizeStageAttemptTasks",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:summarizeStageAttemptTasks"
                    },
                    "accessStageAttempt": {
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessStageAttempt",
                      "httpMethod": "GET",
                      "description": "Obtain data corresponding to a spark stage attempt for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "path": "v1/{+name}:accessStageAttempt",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessStageAttempt"
                    },
                    "summarizeJobs": {
                      "path": "v1/{+name}:summarizeJobs",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:summarizeJobs",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.summarizeJobs",
                      "description": "Obtain summary of Jobs for a Spark Application",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "accessSqlPlan": {
                      "path": "v1/{+name}:accessSqlPlan",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessSqlPlan",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessSqlPlan",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain Spark Plan Graph for a Spark Application SQL execution. Limits the number of clusters returned as part of the graph to 10000."
                    },
                    "accessSqlQuery": {
                      "path": "v1/{+name}:accessSqlQuery",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessSqlQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to a particular SQL Query for a Spark Application.",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessSqlQuery",
                      "httpMethod": "GET"
                    },
                    "accessStageRddGraph": {
                      "path": "v1/{+name}:accessStageRddGraph",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessStageRddGraph",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessStageRddGraph",
                      "httpMethod": "GET",
                      "description": "Obtain RDD operation graph for a Spark Application Stage. Limits the number of clusters returned as part of the graph to 10000.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "write": {
                      "path": "v1/{+name}:write",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:write",
                      "description": "Write wrapper objects from dataplane to spanner",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "httpMethod": "POST",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.write"
                    },
                    "searchStages": {
                      "path": "v1/{+name}:searchStages",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchStages",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchStages",
                      "description": "Obtain data corresponding to stages for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "searchExecutorStageSummary": {
                      "path": "v1/{+name}:searchExecutorStageSummary",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchExecutorStageSummary",
                      "description": "Obtain executor summary with respect to a spark stage attempt.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchExecutorStageSummary"
                    },
                    "accessJob": {
                      "path": "v1/{+name}:accessJob",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessJob",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessJob",
                      "description": "Obtain data corresponding to a spark job for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "summarizeStages": {
                      "path": "v1/{+name}:summarizeStages",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:summarizeStages",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain summary of Stages for a Spark Application",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.summarizeStages"
                    },
                    "searchStageAttempts": {
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchStageAttempts",
                      "httpMethod": "GET",
                      "description": "Obtain data corresponding to a spark stage attempts for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "path": "v1/{+name}:searchStageAttempts",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchStageAttempts"
                    },
                    "access": {
                      "path": "v1/{+name}:access",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:access",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain high level information corresponding to a single Spark Application.",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.access"
                    }
                  }
                }
              },
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}",
                  "id": "dataproc.projects.locations.sessions.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Gets the resource representation for an interactive session."
                },
                "terminate": {
                  "id": "dataproc.projects.locations.sessions.terminate",
                  "httpMethod": "POST",
                  "description": "Terminates the interactive session.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+name}:terminate",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}:terminate"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}",
                  "id": "dataproc.projects.locations.sessions.delete",
                  "httpMethod": "DELETE",
                  "description": "Deletes the interactive session resource. If the session is not in terminal state, it is terminated, and then deleted.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "list": {
                  "path": "v1/{+parent}/sessions",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.locations.sessions.list",
                  "description": "Lists interactive sessions.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ]
                },
                "create": {
                  "path": "v1/{+parent}/sessions",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Create an interactive session asynchronously.",
                  "id": "dataproc.projects.locations.sessions.create",
                  "httpMethod": "POST"
                }
              }
            },
            "workflowTemplates": {
              "methods": {
                "get": {
                  "description": "Retrieves the latest workflow template.Can retrieve previously instantiated template by specifying optional version parameter.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "httpMethod": "GET",
                  "id": "dataproc.projects.locations.workflowTemplates.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}"
                },
                "update": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Updates (replaces) workflow template. The updated template must contain version that matches the current server version.",
                  "httpMethod": "PUT",
                  "id": "dataproc.projects.locations.workflowTemplates.update"
                },
                "instantiateInline": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Instantiates a template and begins execution.This method is equivalent to executing the sequence CreateWorkflowTemplate, InstantiateWorkflowTemplate, DeleteWorkflowTemplate.The returned Operation can be used to track execution of workflow by polling operations.get. The Operation will complete when entire workflow is finished.The running workflow can be aborted via operations.cancel. This will cause any inflight jobs to be cancelled and workflow-owned clusters to[...]",
                  "id": "dataproc.projects.locations.workflowTemplates.instantiateInline",
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/workflowTemplates:instantiateInline",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates:instantiateInline"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}",
                  "description": "Deletes a workflow template. It does not cancel in-progress workflows.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.locations.workflowTemplates.delete",
                  "httpMethod": "DELETE"
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}:testIamPermissions",
                  "id": "dataproc.projects.locations.workflowTemplates.testIamPermissions",
                  "httpMethod": "POST",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Lists workflows that match the specified filter in the request.",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.locations.workflowTemplates.list",
                  "path": "v1/{+parent}/workflowTemplates",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates"
                },
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataproc.projects.locations.workflowTemplates.getIamPolicy",
                  "httpMethod": "POST"
                },
                "instantiate": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.workflowTemplates.instantiate",
                  "description": "Instantiates a template and begins execution.The returned Operation can be used to track execution of workflow by polling operations.get. The Operation will complete when entire workflow is finished.The running workflow can be aborted via operations.cancel. This will cause any inflight jobs to be cancelled and workflow-owned clusters to be deleted.The Operation.metadata will be WorkflowMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.d[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+name}:instantiate",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}:instantiate"
                },
                "create": {
                  "description": "Creates new workflow template.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.locations.workflowTemplates.create",
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/workflowTemplates",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates"
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.locations.workflowTemplates.setIamPolicy",
                  "httpMethod": "POST"
                }
              }
            },
            "batches": {
              "resources": {
                "sparkApplications": {
                  "methods": {
                    "write": {
                      "description": "Write wrapper objects from dataplane to spanner",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "httpMethod": "POST",
                      "id": "dataproc.projects.locations.batches.sparkApplications.write",
                      "path": "v1/{+name}:write",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:write"
                    },
                    "searchStages": {
                      "path": "v1/{+name}:searchStages",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchStages",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchStages",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to stages for a Spark Application."
                    },
                    "searchExecutorStageSummary": {
                      "path": "v1/{+name}:searchExecutorStageSummary",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchExecutorStageSummary",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain executor summary with respect to a spark stage attempt.",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchExecutorStageSummary"
                    },
                    "accessJob": {
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessJob",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to a spark job for a Spark Application.",
                      "path": "v1/{+name}:accessJob",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessJob"
                    },
                    "summarizeStages": {
                      "path": "v1/{+name}:summarizeStages",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:summarizeStages",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.summarizeStages",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain summary of Stages for a Spark Application"
                    },
                    "searchStageAttempts": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to a spark stage attempts for a Spark Application.",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchStageAttempts",
                      "path": "v1/{+name}:searchStageAttempts",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchStageAttempts"
                    },
                    "access": {
                      "id": "dataproc.projects.locations.batches.sparkApplications.access",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain high level information corresponding to a single Spark Application.",
                      "path": "v1/{+name}:access",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:access"
                    },
                    "summarizeJobs": {
                      "path": "v1/{+name}:summarizeJobs",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:summarizeJobs",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain summary of Jobs for a Spark Application",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.summarizeJobs"
                    },
                    "accessSqlPlan": {
                      "path": "v1/{+name}:accessSqlPlan",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessSqlPlan",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessSqlPlan",
                      "httpMethod": "GET",
                      "description": "Obtain Spark Plan Graph for a Spark Application SQL execution. Limits the number of clusters returned as part of the graph to 10000.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "accessSqlQuery": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to a particular SQL Query for a Spark Application.",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessSqlQuery",
                      "httpMethod": "GET",
                      "path": "v1/{+name}:accessSqlQuery",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessSqlQuery"
                    },
                    "accessStageRddGraph": {
                      "path": "v1/{+name}:accessStageRddGraph",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessStageRddGraph",
                      "description": "Obtain RDD operation graph for a Spark Application Stage. Limits the number of clusters returned as part of the graph to 10000.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessStageRddGraph"
                    },
                    "searchExecutors": {
                      "path": "v1/{+name}:searchExecutors",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchExecutors",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to executors for a Spark Application.",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchExecutors",
                      "httpMethod": "GET"
                    },
                    "summarizeStageAttemptTasks": {
                      "path": "v1/{+name}:summarizeStageAttemptTasks",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:summarizeStageAttemptTasks",
                      "description": "Obtain summary of Tasks for a Spark Application Stage Attempt",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "id": "dataproc.projects.locations.batches.sparkApplications.summarizeStageAttemptTasks",
                      "httpMethod": "GET"
                    },
                    "accessStageAttempt": {
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessStageAttempt",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to a spark stage attempt for a Spark Application.",
                      "path": "v1/{+name}:accessStageAttempt",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessStageAttempt"
                    },
                    "summarizeExecutors": {
                      "id": "dataproc.projects.locations.batches.sparkApplications.summarizeExecutors",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain summary of Executor Summary for a Spark Application",
                      "path": "v1/{+name}:summarizeExecutors",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:summarizeExecutors"
                    },
                    "searchJobs": {
                      "path": "v1/{+name}:searchJobs",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchJobs",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchJobs",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain list of spark jobs corresponding to a Spark Application."
                    },
                    "accessEnvironmentInfo": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain environment details for a Spark Application",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessEnvironmentInfo",
                      "httpMethod": "GET",
                      "path": "v1/{+name}:accessEnvironmentInfo",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessEnvironmentInfo"
                    },
                    "searchSqlQueries": {
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchSqlQueries",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to SQL Queries for a Spark Application.",
                      "path": "v1/{+name}:searchSqlQueries",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchSqlQueries"
                    },
                    "search": {
                      "path": "v1/{+parent}/sparkApplications:search",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications:search",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain high level information and list of Spark Applications corresponding to a batch",
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.search"
                    },
                    "searchStageAttemptTasks": {
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchStageAttemptTasks",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to tasks for a spark stage attempt for a Spark Application.",
                      "path": "v1/{+name}:searchStageAttemptTasks",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchStageAttemptTasks"
                    }
                  }
                }
              },
              "methods": {
                "create": {
                  "path": "v1/{+parent}/batches",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.locations.batches.create",
                  "description": "Creates a batch workload that executes asynchronously.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "list": {
                  "description": "Lists batch workloads.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "id": "dataproc.projects.locations.batches.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/batches",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}",
                  "id": "dataproc.projects.locations.batches.delete",
                  "httpMethod": "DELETE",
                  "description": "Deletes the batch workload resource. If the batch is not in a CANCELLED, SUCCEEDED or FAILED State, the delete operation fails and the response returns FAILED_PRECONDITION.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "analyze": {
                  "path": "v1/{+name}:analyze",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}:analyze",
                  "description": "Analyze a Batch for possible recommendations and insights.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.locations.batches.analyze",
                  "httpMethod": "POST"
                },
                "get": {
                  "id": "dataproc.projects.locations.batches.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Gets the batch workload resource representation.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}"
                }
              }
            }
          }
        },
        "regions": {
          "resources": {
            "autoscalingPolicies": {
              "methods": {
                "create": {
                  "id": "dataproc.projects.regions.autoscalingPolicies.create",
                  "httpMethod": "POST",
                  "description": "Creates new autoscaling policy.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+parent}/autoscalingPolicies",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies"
                },
                "setIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataproc.projects.regions.autoscalingPolicies.setIamPolicy",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}:setIamPolicy"
                },
                "getIamPolicy": {
                  "id": "dataproc.projects.regions.autoscalingPolicies.getIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}:getIamPolicy"
                },
                "list": {
                  "id": "dataproc.projects.regions.autoscalingPolicies.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Lists autoscaling policies in the project.",
                  "path": "v1/{+parent}/autoscalingPolicies",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies"
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}:testIamPermissions",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.autoscalingPolicies.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "dataproc.projects.regions.autoscalingPolicies.delete",
                  "description": "Deletes an autoscaling policy. It is an error to delete an autoscaling policy that is in use by one or more clusters.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}"
                },
                "update": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}",
                  "id": "dataproc.projects.regions.autoscalingPolicies.update",
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Updates (replaces) autoscaling policy.Disabled check for update_mask, because all updates will be full replacements."
                },
                "get": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.regions.autoscalingPolicies.get",
                  "description": "Retrieves autoscaling policy.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                }
              }
            },
            "workflowTemplates": {
              "methods": {
                "create": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.workflowTemplates.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Creates new workflow template.",
                  "path": "v1/{+parent}/workflowTemplates",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates"
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.workflowTemplates.setIamPolicy"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Retrieves the latest workflow template.Can retrieve previously instantiated template by specifying optional version parameter.",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.regions.workflowTemplates.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}"
                },
                "update": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Updates (replaces) workflow template. The updated template must contain version that matches the current server version.",
                  "id": "dataproc.projects.regions.workflowTemplates.update",
                  "httpMethod": "PUT",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}"
                },
                "instantiateInline": {
                  "id": "dataproc.projects.regions.workflowTemplates.instantiateInline",
                  "httpMethod": "POST",
                  "description": "Instantiates a template and begins execution.This method is equivalent to executing the sequence CreateWorkflowTemplate, InstantiateWorkflowTemplate, DeleteWorkflowTemplate.The returned Operation can be used to track execution of workflow by polling operations.get. The Operation will complete when entire workflow is finished.The running workflow can be aborted via operations.cancel. This will cause any inflight jobs to be cancelled and workflow-owned clusters to[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+parent}/workflowTemplates:instantiateInline",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates:instantiateInline"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}",
                  "description": "Deletes a workflow template. It does not cancel in-progress workflows.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "DELETE",
                  "id": "dataproc.projects.regions.workflowTemplates.delete"
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}:testIamPermissions",
                  "id": "dataproc.projects.regions.workflowTemplates.testIamPermissions",
                  "httpMethod": "POST",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "list": {
                  "path": "v1/{+parent}/workflowTemplates",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Lists workflows that match the specified filter in the request.",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.regions.workflowTemplates.list"
                },
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.workflowTemplates.getIamPolicy"
                },
                "instantiate": {
                  "path": "v1/{+name}:instantiate",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}:instantiate",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Instantiates a template and begins execution.The returned Operation can be used to track execution of workflow by polling operations.get. The Operation will complete when entire workflow is finished.The running workflow can be aborted via operations.cancel. This will cause any inflight jobs to be cancelled and workflow-owned clusters to be deleted.The Operation.metadata will be WorkflowMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.d[...]",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.workflowTemplates.instantiate"
                }
              }
            },
            "operations": {
              "methods": {
                "delete": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}",
                  "id": "dataproc.projects.regions.operations.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED."
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}:testIamPermissions",
                  "id": "dataproc.projects.regions.operations.testIamPermissions",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                },
                "get": {
                  "id": "dataproc.projects.regions.operations.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}"
                },
                "getIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataproc.projects.regions.operations.getIamPolicy",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}:getIamPolicy"
                },
                "setIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.operations.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}:setIamPolicy"
                },
                "cancel": {
                  "path": "v1/{+name}:cancel",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}:cancel",
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it beco[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.operations.cancel"
                },
                "list": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns UNIMPLEMENTED.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "id": "dataproc.projects.regions.operations.list",
                  "httpMethod": "GET"
                }
              }
            },
            "jobs": {
              "methods": {
                "submitAsOperation": {
                  "id": "dataproc.projects.regions.jobs.submitAsOperation",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Submits job to a cluster.",
                  "path": "v1/projects/{projectId}/regions/{region}/jobs:submitAsOperation",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs:submitAsOperation"
                },
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.jobs.setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/jobs/{jobsId}:setIamPolicy"
                },
                "cancel": {
                  "path": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}:cancel",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}:cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Starts a job cancellation request. To access the job resource after cancellation, call regions/{region}/jobs.list (https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.jobs/list) or regions/{region}/jobs.get (https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.jobs/get).",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.jobs.cancel"
                },
                "testIamPermissions": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.jobs.testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/jobs/{jobsId}:testIamPermissions"
                },
                "submit": {
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.jobs.submit",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Submits a job to a cluster.",
                  "path": "v1/projects/{projectId}/regions/{region}/jobs:submit",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs:submit"
                },
                "delete": {
                  "path": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Deletes the job from the project. If the job is active, the delete fails, and the response returns FAILED_PRECONDITION.",
                  "id": "dataproc.projects.regions.jobs.delete",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Gets the resource representation for a job in a project.",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.regions.jobs.get",
                  "path": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}"
                },
                "patch": {
                  "id": "dataproc.projects.regions.jobs.patch",
                  "httpMethod": "PATCH",
                  "description": "Updates a job in a project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}"
                },
                "getIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataproc.projects.regions.jobs.getIamPolicy",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/jobs/{jobsId}:getIamPolicy"
                },
                "list": {
                  "path": "v1/projects/{projectId}/regions/{region}/jobs",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs",
                  "httpMethod": "GET",
                  "id": "dataproc.projects.regions.jobs.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Lists regions/{region}/jobs in a project."
                }
              }
            },
            "clusters": {
              "methods": {
                "create": {
                  "path": "v1/projects/{projectId}/regions/{region}/clusters",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.clusters.create",
                  "description": "Creates a cluster in a project. The returned Operation.metadata will be ClusterOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#clusteroperationmetadata).",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "delete": {
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Deletes a cluster in a project. The returned Operation.metadata will be ClusterOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#clusteroperationmetadata).",
                  "id": "dataproc.projects.regions.clusters.delete",
                  "httpMethod": "DELETE"
                },
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.clusters.getIamPolicy"
                },
                "stop": {
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:stop",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:stop",
                  "description": "Stops a cluster in a project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.clusters.stop"
                },
                "diagnose": {
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:diagnose",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:diagnose",
                  "description": "Gets cluster diagnostic information. The returned Operation.metadata will be ClusterOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#clusteroperationmetadata). After the operation completes, Operation.response contains DiagnoseClusterResults (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#diagnoseclusterresults).",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.clusters.diagnose"
                },
                "injectCredentials": {
                  "path": "v1/{+project}/{+region}/{+cluster}:injectCredentials",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}:injectCredentials",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Inject encrypted credentials into all of the VMs in a cluster.The target cluster must be a personal auth cluster assigned to the user who is issuing the RPC.",
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.clusters.injectCredentials"
                },
                "setIamPolicy": {
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.regions.clusters.setIamPolicy",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}:setIamPolicy"
                },
                "start": {
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:start",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:start",
                  "description": "Starts a cluster in a project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.clusters.start"
                },
                "repair": {
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:repair",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:repair",
                  "description": "Repairs a cluster.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.regions.clusters.repair",
                  "httpMethod": "POST"
                },
                "get": {
                  "id": "dataproc.projects.regions.clusters.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Gets the resource representation for a cluster in a project.",
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}"
                },
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "id": "dataproc.projects.regions.clusters.testIamPermissions"
                },
                "list": {
                  "id": "dataproc.projects.regions.clusters.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "description": "Lists all regions/{region}/clusters in a project alphabetically.",
                  "path": "v1/projects/{projectId}/regions/{region}/clusters",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters"
                },
                "patch": {
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "id": "dataproc.projects.regions.clusters.patch",
                  "httpMethod": "PATCH",
                  "description": "Updates a cluster in a project. The returned Operation.metadata will be ClusterOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#clusteroperationmetadata). The cluster must be in a RUNNING state or an error is returned.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                }
              },
              "resources": {
                "nodeGroups": {
                  "methods": {
                    "repair": {
                      "description": "Repair nodes in a node group.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "id": "dataproc.projects.regions.clusters.nodeGroups.repair",
                      "httpMethod": "POST",
                      "path": "v1/{+name}:repair",
                      "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}/nodeGroups/{nodeGroupsId}:repair"
                    },
                    "get": {
                      "id": "dataproc.projects.regions.clusters.nodeGroups.get",
                      "httpMethod": "GET",
                      "description": "Gets the resource representation for a node group in a cluster.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "path": "v1/{+name}",
                      "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}/nodeGroups/{nodeGroupsId}"
                    },
                    "resize": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "description": "Resizes a node group in a cluster. The returned Operation.metadata is NodeGroupOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#nodegroupoperationmetadata).",
                      "httpMethod": "POST",
                      "id": "dataproc.projects.regions.clusters.nodeGroups.resize",
                      "path": "v1/{+name}:resize",
                      "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}/nodeGroups/{nodeGroupsId}:resize"
                    },
                    "create": {
                      "path": "v1/{+parent}/nodeGroups",
                      "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}/nodeGroups",
                      "httpMethod": "POST",
                      "id": "dataproc.projects.regions.clusters.nodeGroups.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "description": "Creates a node group in a cluster. The returned Operation.metadata is NodeGroupOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#nodegroupoperationmetadata)."
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "revision": "20260501",
  "protocol": "rest",
  "kind": "discovery#restDescription",
  "description": "Manages Hadoop-based clusters and jobs on Google Cloud Platform.",
  "documentationLink": "https://cloud.google.com/dataproc/",
  "version": "v1",
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://dataproc.mtls.googleapis.com/",
  "basePath": "",
  "name": "dataproc",
  "schemas": {
    "AnalyzeBatchRequest": {
      "type": "object",
      "description": "A request to analyze a batch workload.",
      "properties": {
        "requestorId": {
          "description": "Optional. The requestor ID is used to identify if the request comes from a GCA investigation or the old Ask Gemini Experience. ",
          "type": "string",
          "deprecated": true
        },
        "requestId": {
          "description": "Optional. A unique ID used to identify the request. If the service receives two AnalyzeBatchRequest (http://cloud/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.AnalyzeBatchRequest)s with the same request_id, the second request is ignored and the Operation that corresponds to the first request created and stored in the backend is returned.Recommendation: Set this value to a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier)[...]",
          "type": "string"
        }
      },
      "id": "AnalyzeBatchRequest"
    },
    "ResizeNodeGroupRequest": {
      "type": "object",
      "id": "ResizeNodeGroupRequest",
      "description": "A request to resize a node group.",
      "properties": {
        "size": {
          "type": "integer",
          "format": "int32",
          "description": "Required. The number of running instances for the node group to maintain. The group adds or removes instances to maintain the number of instances specified by this parameter."
        },
        "requestId": {
          "description": "Optional. A unique ID used to identify the request. If the server receives two ResizeNodeGroupRequest (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.ResizeNodeGroupRequests) with the same ID, the second request is ignored and the first google.longrunning.Operation created and stored in the backend is returned.Recommendation: Set this value to a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier).The[...]",
          "type": "string"
        },
        "parentOperationId": {
          "type": "string",
          "description": "Optional. operation id of the parent operation sending the resize request"
        },
        "gracefulDecommissionTimeout": {
          "description": "Optional. Timeout for graceful YARN decommissioning. Graceful decommissioning (https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/scaling-clusters#graceful_decommissioning) allows the removal of nodes from the Compute Engine node group without interrupting jobs in progress. This timeout specifies how long to wait for jobs in progress to finish before forcefully removing nodes (and potentially interrupting jobs). Default timeout is 0 (for forceful decom[...]",
          "type": "string",
          "format": "google-duration"
        }
      }
    },
    "ProcessSummary": {
      "type": "object",
      "id": "ProcessSummary",
      "description": "Process Summary",
      "properties": {
        "hostPort": {
          "type": "string"
        },
        "isActive": {
          "type": "boolean"
        },
        "totalCores": {
          "type": "integer",
          "format": "int32"
        },
        "processLogs": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "processId": {
          "type": "string"
        },
        "addTime": {
          "type": "string",
          "format": "google-datetime"
        },
        "removeTime": {
          "type": "string",
          "format": "google-datetime"
        }
      }
    },
    "AutotuningConfig": {
      "type": "object",
      "description": "Autotuning configuration of the workload.",
      "properties": {
        "scenarios": {
          "type": "array",
          "items": {
            "enumDescriptions": [
              "Default value.",
              "Scaling recommendations such as initialExecutors.",
              "Adding hints for potential relation broadcasts.",
              "Memory management for workloads.",
              "No autotuning.",
              "Automatic selection of scenarios."
            ],
            "type": "string",
            "enum": [
              "SCENARIO_UNSPECIFIED",
              "SCALING",
              "BROADCAST_HASH_JOIN",
              "MEMORY",
              "NONE",
              "AUTO"
            ]
          },
          "description": "Optional. Scenarios for which tunings are applied."
        }
      },
      "id": "AutotuningConfig"
    },
    "SpeculationStageSummary": {
      "type": "object",
      "id": "SpeculationStageSummary",
      "description": "Details of the speculation task when speculative execution is enabled.",
      "properties": {
        "stageAttemptId": {
          "format": "int32",
          "type": "integer"
        },
        "numTasks": {
          "type": "integer",
          "format": "int32"
        },
        "stageId": {
          "format": "int64",
          "type": "string"
        },
        "numActiveTasks": {
          "type": "integer",
          "format": "int32"
        },
        "numFailedTasks": {
          "format": "int32",
          "type": "integer"
        },
        "numCompletedTasks": {
          "type": "integer",
          "format": "int32"
        },
        "numKilledTasks": {
          "format": "int32",
          "type": "integer"
        }
      }
    },
    "StartupConfig": {
      "description": "Configuration to handle the startup of instances during cluster create and update process.",
      "properties": {
        "requiredRegistrationFraction": {
          "description": "Optional. The config setting to enable cluster creation/ updation to be successful only after required_registration_fraction of instances are up and running. This configuration is applicable to only secondary workers for now. The cluster will fail if required_registration_fraction of instances are not available. This will include instance creation, agent registration, and service registration (if enabled).",
          "type": "number",
          "format": "double"
        }
      },
      "id": "StartupConfig",
      "type": "object"
    },
    "InjectCredentialsRequest": {
      "description": "A request to inject credentials into a cluster.",
      "properties": {
        "credentialsCiphertext": {
          "description": "Required. The encrypted credentials being injected in to the cluster.The client is responsible for encrypting the credentials in a way that is supported by the cluster.A wrapped value is used here so that the actual contents of the encrypted credentials are not written to audit logs.",
          "type": "string"
        },
        "clusterUuid": {
          "description": "Required. The cluster UUID.",
          "type": "string"
        }
      },
      "id": "InjectCredentialsRequest",
      "type": "object"
    },
    "PropertiesInfo": {
      "type": "object",
      "id": "PropertiesInfo",
      "description": "Properties of the workload organized by origin.",
      "properties": {
        "autotuningProperties": {
          "description": "Output only. Properties set by autotuning engine.",
          "additionalProperties": {
            "$ref": "ValueInfo"
          },
          "readOnly": true,
          "type": "object"
        }
      }
    },
    "InstanceFlexibilityPolicy": {
      "description": "Instance flexibility Policy allowing a mixture of VM shapes and provisioning models.",
      "properties": {
        "instanceSelectionResults": {
          "type": "array",
          "items": {
            "$ref": "InstanceSelectionResult"
          },
          "readOnly": true,
          "description": "Output only. A list of instance selection results in the group."
        },
        "instanceMachineTypes": {
          "readOnly": true,
          "description": "Output only. A map of instance short name to machine type. The key is the short name of the Compute Engine instance, and the value is the full machine-type name (e.g., 'n1-standard-16'). See Machine types for more information on valid machine type strings.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "provisioningModelMix": {
          "description": "Optional. Defines how the Group selects the provisioning model to ensure required reliability.",
          "$ref": "ProvisioningModelMix"
        },
        "instanceSelectionList": {
          "type": "array",
          "items": {
            "$ref": "InstanceSelection"
          },
          "description": "Optional. List of instance selection options that the group will use when creating new VMs."
        }
      },
      "id": "InstanceFlexibilityPolicy",
      "type": "object"
    },
    "ApplicationInfo": {
      "description": "High level information corresponding to an application.",
      "properties": {
        "quantileDataStatus": {
          "enumDescriptions": [
            "",
            "",
            ""
          ],
          "type": "string",
          "enum": [
            "QUANTILE_DATA_STATUS_UNSPECIFIED",
            "QUANTILE_DATA_STATUS_COMPLETED",
            "QUANTILE_DATA_STATUS_FAILED"
          ]
        },
        "memoryPerExecutorMb": {
          "type": "integer",
          "format": "int32"
        },
        "applicationContextIngestionStatus": {
          "enumDescriptions": [
            "",
            ""
          ],
          "type": "string",
          "enum": [
            "APPLICATION_CONTEXT_INGESTION_STATUS_UNSPECIFIED",
            "APPLICATION_CONTEXT_INGESTION_STATUS_COMPLETED"
          ]
        },
        "coresPerExecutor": {
          "type": "integer",
          "format": "int32"
        },
        "maxCores": {
          "type": "integer",
          "format": "int32"
        },
        "coresGranted": {
          "type": "integer",
          "format": "int32"
        },
        "applicationId": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "attempts": {
          "type": "array",
          "items": {
            "$ref": "ApplicationAttemptInfo"
          }
        }
      },
      "id": "ApplicationInfo",
      "type": "object"
    },
    "GkeNodePoolAutoscalingConfig": {
      "type": "object",
      "id": "GkeNodePoolAutoscalingConfig",
      "description": "GkeNodePoolAutoscaling contains information the cluster autoscaler needs to adjust the size of the node pool to the current cluster usage.",
      "properties": {
        "minNodeCount": {
          "description": "The minimum number of nodes in the node pool. Must be >= 0 and <= max_node_count.",
          "format": "int32",
          "type": "integer"
        },
        "maxNodeCount": {
          "description": "The maximum number of nodes in the node pool. Must be >= min_node_count, and must be > 0. Note: Quota must be sufficient to scale up the cluster.",
          "format": "int32",
          "type": "integer"
        }
      }
    },
    "StreamBlockData": {
      "type": "object",
      "id": "StreamBlockData",
      "description": "Stream Block Data.",
      "properties": {
        "name": {
          "type": "string"
        },
        "executorId": {
          "type": "string"
        },
        "storageLevel": {
          "type": "string"
        },
        "useMemory": {
          "type": "boolean"
        },
        "useDisk": {
          "type": "boolean"
        },
        "diskSize": {
          "format": "int64",
          "type": "string"
        },
        "memSize": {
          "format": "int64",
          "type": "string"
        },
        "hostPort": {
          "type": "string"
        },
        "deserialized": {
          "type": "boolean"
        }
      }
    },
    "ShufflePushReadQuantileMetrics": {
      "type": "object",
      "id": "ShufflePushReadQuantileMetrics",
      "properties": {
        "corruptMergedBlockChunks": {
          "$ref": "Quantiles"
        },
        "localMergedBytesRead": {
          "$ref": "Quantiles"
        },
        "remoteMergedBlocksFetched": {
          "$ref": "Quantiles"
        },
        "remoteMergedBytesRead": {
          "$ref": "Quantiles"
        },
        "remoteMergedReqsDuration": {
          "$ref": "Quantiles"
        },
        "remoteMergedChunksFetched": {
          "$ref": "Quantiles"
        },
        "localMergedChunksFetched": {
          "$ref": "Quantiles"
        },
        "mergedFetchFallbackCount": {
          "$ref": "Quantiles"
        },
        "localMergedBlocksFetched": {
          "$ref": "Quantiles"
        }
      }
    },
    "Status": {
      "type": "object",
      "id": "Status",
      "description": "The Status type defines a logical error model that is suitable for different programming environments, including REST APIs and RPC APIs. It is used by gRPC (https://github.com/grpc). Each Status message contains three pieces of data: error code, error message, and error details.You can find out more about this error model and how to work with it in the API Design Guide (https://cloud.google.com/apis/design/errors).",
      "properties": {
        "message": {
          "type": "string",
          "description": "A developer-facing error message, which should be in English. Any user-facing error message should be localized and sent in the google.rpc.Status.details field, or localized by the client."
        },
        "details": {
          "type": "array",
          "items": {
            "type": "object",
            "additionalProperties": {
              "type": "any",
              "description": "Properties of the object. Contains field @type with type URL."
            }
          },
          "description": "A list of messages that carry the error details. There is a common set of message types for APIs to use."
        },
        "code": {
          "type": "integer",
          "format": "int32",
          "description": "The status code, which should be an enum value of google.rpc.Code."
        }
      }
    },
    "AttachedDiskConfig": {
      "type": "object",
      "id": "AttachedDiskConfig",
      "description": "Specifies the config of attached disk options for single VM instance.",
      "properties": {
        "diskSizeGb": {
          "description": "Optional. Disk size in GB.",
          "type": "integer",
          "format": "int32"
        },
        "provisionedThroughput": {
          "description": "Optional. Indicates how much throughput to provision for the attached disk. This sets the number of throughput mb per second that the disk can handle. See https://cloud.google.com/compute/docs/disks/hyperdisks#hyperdisk-features",
          "type": "string",
          "format": "int64"
        },
        "diskType": {
          "description": "Optional. Disk type.",
          "enumDescriptions": [
            "Required unspecified disk type.",
            "Hyperdisk Balanced disk type.",
            "Hyperdisk Extreme disk type.",
            "Hyperdisk ML disk type.",
            "Hyperdisk Throughput disk type."
          ],
          "type": "string",
          "enum": [
            "DISK_TYPE_UNSPECIFIED",
            "HYPERDISK_BALANCED",
            "HYPERDISK_EXTREME",
            "HYPERDISK_ML",
            "HYPERDISK_THROUGHPUT"
          ]
        },
        "provisionedIops": {
          "format": "int64",
          "type": "string",
          "description": "Optional. Indicates how many IOPS to provision for the attached disk. This sets the number of I/O operations per second that the disk can handle. See https://cloud.google.com/compute/docs/disks/hyperdisks#hyperdisk-features"
        }
      }
    },
    "TaskQuantileMetrics": {
      "type": "object",
      "id": "TaskQuantileMetrics",
      "properties": {
        "gettingResultTimeMillis": {
          "$ref": "Quantiles"
        },
        "executorDeserializeCpuTimeNanos": {
          "$ref": "Quantiles"
        },
        "jvmGcTimeMillis": {
          "$ref": "Quantiles"
        },
        "resultSerializationTimeMillis": {
          "$ref": "Quantiles"
        },
        "resultSize": {
          "$ref": "Quantiles"
        },
        "memoryBytesSpilled": {
          "$ref": "Quantiles"
        },
        "durationMillis": {
          "$ref": "Quantiles"
        },
        "executorRunTimeMillis": {
          "$ref": "Quantiles"
        },
        "executorCpuTimeNanos": {
          "$ref": "Quantiles"
        },
        "schedulerDelayMillis": {
          "$ref": "Quantiles"
        },
        "executorDeserializeTimeMillis": {
          "$ref": "Quantiles"
        },
        "diskBytesSpilled": {
          "$ref": "Quantiles"
        },
        "shuffleReadMetrics": {
          "$ref": "ShuffleReadQuantileMetrics"
        },
        "inputMetrics": {
          "$ref": "InputQuantileMetrics"
        },
        "shuffleWriteMetrics": {
          "$ref": "ShuffleWriteQuantileMetrics"
        },
        "peakExecutionMemoryBytes": {
          "$ref": "Quantiles"
        },
        "outputMetrics": {
          "$ref": "OutputQuantileMetrics"
        }
      }
    },
    "SessionTemplate": {
      "type": "object",
      "description": "A representation of a session template.",
      "properties": {
        "creator": {
          "type": "string",
          "readOnly": true,
          "description": "Output only. The email address of the user who created the template."
        },
        "sparkConnectSession": {
          "description": "Optional. Spark connect session config.",
          "$ref": "SparkConnectConfig"
        },
        "updateTime": {
          "type": "string",
          "format": "google-datetime",
          "readOnly": true,
          "description": "Output only. The time the template was last updated."
        },
        "description": {
          "description": "Optional. Brief description of the template.",
          "type": "string"
        },
        "runtimeConfig": {
          "description": "Optional. Runtime configuration for session execution.",
          "$ref": "RuntimeConfig"
        },
        "createTime": {
          "readOnly": true,
          "description": "Output only. The time when the template was created.",
          "type": "string",
          "format": "google-datetime"
        },
        "labels": {
          "description": "Optional. Labels to associate with sessions created using this template. Label keys must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). Label values can be empty, but, if present, must contain 1 to 63 characters and conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). No more than 32 labels can be associated with a session.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "name": {
          "description": "Required. Identifier. The resource name of the session template.",
          "type": "string"
        },
        "jupyterSession": {
          "description": "Optional. Jupyter session config.",
          "$ref": "JupyterConfig"
        },
        "environmentConfig": {
          "description": "Optional. Environment configuration for session execution.",
          "$ref": "EnvironmentConfig"
        },
        "uuid": {
          "type": "string",
          "readOnly": true,
          "description": "Output only. A session template UUID (Unique Universal Identifier). The service generates this value when it creates the session template."
        }
      },
      "id": "SessionTemplate"
    },
    "EncryptionConfig": {
      "id": "EncryptionConfig",
      "description": "Encryption settings for the cluster.",
      "properties": {
        "kmsKey": {
          "description": "Optional. The Cloud KMS key resource name to use for cluster persistent disk and job argument encryption. See Use CMEK with cluster data (https://cloud.google.com//dataproc/docs/concepts/configuring-clusters/customer-managed-encryption#use_cmek_with_cluster_data) for more information.When this key resource name is provided, the following job arguments of the following job types submitted to the cluster are encrypted using CMEK: FlinkJob args (https://cloud.google.com/da[...]",
          "type": "string"
        },
        "gcePdKmsKeyName": {
          "description": "Optional. The Cloud KMS key resource name to use for persistent disk encryption for all instances in the cluster. See Use CMEK with cluster data (https://cloud.google.com//dataproc/docs/concepts/configuring-clusters/customer-managed-encryption#use_cmek_with_cluster_data) for more information.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "TestIamPermissionsResponse": {
      "type": "object",
      "description": "Response message for TestIamPermissions method.",
      "properties": {
        "permissions": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "A subset of TestPermissionsRequest.permissions that the caller is allowed."
        }
      },
      "id": "TestIamPermissionsResponse"
    },
    "OutputMetrics": {
      "type": "object",
      "description": "Metrics about the data written by the task.",
      "properties": {
        "recordsWritten": {
          "type": "string",
          "format": "int64"
        },
        "bytesWritten": {
          "format": "int64",
          "type": "string"
        }
      },
      "id": "OutputMetrics"
    },
    "AccessSparkApplicationSqlSparkPlanGraphResponse": {
      "id": "AccessSparkApplicationSqlSparkPlanGraphResponse",
      "description": "SparkPlanGraph for a Spark Application execution limited to maximum 10000 clusters.",
      "properties": {
        "sparkPlanGraph": {
          "description": "SparkPlanGraph for a Spark Application execution.",
          "$ref": "SparkPlanGraph"
        }
      },
      "type": "object"
    },
    "SubmitJobRequest": {
      "type": "object",
      "description": "A request to submit a job.",
      "properties": {
        "job": {
          "description": "Required. The job resource.",
          "$ref": "Job"
        },
        "requestId": {
          "type": "string",
          "description": "Optional. A unique id used to identify the request. If the server receives two SubmitJobRequest (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.SubmitJobRequest)s with the same id, then the second request will be ignored and the first Job created and stored in the backend is returned.It is recommended to always set this value to a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier).The id must contai[...]"
        }
      },
      "id": "SubmitJobRequest"
    },
    "ExecutorStageSummary": {
      "id": "ExecutorStageSummary",
      "description": "Executor resources consumed by a stage.",
      "properties": {
        "shuffleReadRecords": {
          "format": "int64",
          "type": "string"
        },
        "isExcludedForStage": {
          "type": "boolean"
        },
        "inputBytes": {
          "format": "int64",
          "type": "string"
        },
        "stageAttemptId": {
          "type": "integer",
          "format": "int32"
        },
        "inputRecords": {
          "type": "string",
          "format": "int64"
        },
        "shuffleWriteRecords": {
          "type": "string",
          "format": "int64"
        },
        "diskBytesSpilled": {
          "type": "string",
          "format": "int64"
        },
        "taskTimeMillis": {
          "type": "string",
          "format": "int64"
        },
        "killedTasks": {
          "type": "integer",
          "format": "int32"
        },
        "stageId": {
          "type": "string",
          "format": "int64"
        },
        "failedTasks": {
          "type": "integer",
          "format": "int32"
        },
        "memoryBytesSpilled": {
          "type": "string",
          "format": "int64"
        },
        "outputBytes": {
          "format": "int64",
          "type": "string"
        },
        "peakMemoryMetrics": {
          "$ref": "ExecutorMetrics"
        },
        "shuffleWrite": {
          "type": "string",
          "format": "int64"
        },
        "shuffleRead": {
          "type": "string",
          "format": "int64"
        },
        "executorId": {
          "type": "string"
        },
        "succeededTasks": {
          "type": "integer",
          "format": "int32"
        },
        "outputRecords": {
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object"
    },
    "StageOutputMetrics": {
      "description": "Metrics about the output written by the stage.",
      "properties": {
        "bytesWritten": {
          "format": "int64",
          "type": "string"
        },
        "recordsWritten": {
          "format": "int64",
          "type": "string"
        }
      },
      "id": "StageOutputMetrics",
      "type": "object"
    },
    "SearchSparkApplicationJobsResponse": {
      "description": "A list of Jobs associated with a Spark Application.",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSparkApplicationJobsRequest."
        },
        "sparkApplicationJobs": {
          "type": "array",
          "items": {
            "$ref": "JobData"
          },
          "readOnly": true,
          "description": "Output only. Data corresponding to a spark job."
        }
      },
      "id": "SearchSparkApplicationJobsResponse",
      "type": "object"
    },
    "Binding": {
      "type": "object",
      "id": "Binding",
      "description": "Associates members, or principals, with a role.",
      "properties": {
        "members": {
          "description": "Specifies the principals requesting access for a Google Cloud resource. members can have the following values: allUsers: A special identifier that represents anyone who is on the internet; with or without a Google account. allAuthenticatedUsers: A special identifier that represents anyone who is authenticated with a Google account or a service account. Does not include identities that come from external identity providers (IdPs) through identity federation. user:{emaili[...]",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "condition": {
          "description": "The condition that is associated with this binding.If the condition evaluates to true, then this binding applies to the current request.If the condition evaluates to false, then this binding does not apply to the current request. However, a different role binding might grant the same role to one or more of the principals in this binding.To learn which resources support conditions in their IAM policies, see the IAM documentation (https://cloud.google.com/iam/help/conditi[...]",
          "$ref": "Expr"
        },
        "role": {
          "description": "Role that is assigned to the list of members, or principals. For example, roles/viewer, roles/editor, or roles/owner.For an overview of the IAM roles and permissions, see the IAM documentation (https://cloud.google.com/iam/docs/roles-overview). For a list of the available pre-defined roles, see here (https://cloud.google.com/iam/docs/understanding-roles).",
          "type": "string"
        }
      }
    },
    "InstanceSelection": {
      "id": "InstanceSelection",
      "description": "Defines machines types and a rank to which the machines types belong.",
      "properties": {
        "machineTypes": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. Full machine-type names, e.g. \"n1-standard-16\"."
        },
        "rank": {
          "description": "Optional. Preference of this instance selection. Lower number means higher preference. Dataproc will first try to create a VM based on the machine-type with priority rank and fallback to next rank based on availability. Machine types and instance selections with the same priority have the same preference.",
          "format": "int32",
          "type": "integer"
        }
      },
      "type": "object"
    },
    "RepairNodeGroupRequest": {
      "id": "RepairNodeGroupRequest",
      "properties": {
        "repairAction": {
          "type": "string",
          "enum": [
            "REPAIR_ACTION_UNSPECIFIED",
            "REPLACE"
          ],
          "description": "Required. Repair action to take on specified resources of the node pool.",
          "enumDescriptions": [
            "No action will be taken by default.",
            "replace the specified list of nodes."
          ]
        },
        "requestId": {
          "type": "string",
          "description": "Optional. A unique ID used to identify the request. If the server receives two RepairNodeGroupRequest with the same ID, the second request is ignored and the first google.longrunning.Operation created and stored in the backend is returned.Recommendation: Set this value to a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier).The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), and hyphens (-). The maximum length is 40 characters."
        },
        "instanceNames": {
          "description": "Required. Name of instances to be repaired. These instances must belong to specified node pool.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "type": "object"
    },
    "WorkflowNode": {
      "id": "WorkflowNode",
      "description": "The workflow node.",
      "properties": {
        "state": {
          "type": "string",
          "enum": [
            "NODE_STATE_UNSPECIFIED",
            "BLOCKED",
            "RUNNABLE",
            "RUNNING",
            "COMPLETED",
            "FAILED"
          ],
          "readOnly": true,
          "enumDescriptions": [
            "State is unspecified.",
            "The node is awaiting prerequisite node to finish.",
            "The node is runnable but not running.",
            "The node is running.",
            "The node completed successfully.",
            "The node failed. A node can be marked FAILED because its ancestor or peer failed."
          ],
          "description": "Output only. The node state."
        },
        "stepId": {
          "readOnly": true,
          "description": "Output only. The name of the node.",
          "type": "string"
        },
        "jobId": {
          "type": "string",
          "description": "Output only. The job id; populated after the node enters RUNNING state.",
          "readOnly": true
        },
        "error": {
          "description": "Output only. The error detail.",
          "readOnly": true,
          "type": "string"
        },
        "prerequisiteStepIds": {
          "description": "Output only. Node's prerequisite nodes.",
          "readOnly": true,
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "type": "object"
    },
    "SearchSessionSparkApplicationSqlQueriesResponse": {
      "type": "object",
      "id": "SearchSessionSparkApplicationSqlQueriesResponse",
      "description": "List of all queries for a Spark Application.",
      "properties": {
        "sparkApplicationSqlQueries": {
          "description": "Output only. SQL Execution Data",
          "readOnly": true,
          "type": "array",
          "items": {
            "$ref": "SqlExecutionUiData"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSessionSparkApplicationSqlQueriesRequest."
        }
      }
    },
    "PoolData": {
      "id": "PoolData",
      "description": "Pool Data",
      "properties": {
        "name": {
          "type": "string"
        },
        "stageIds": {
          "type": "array",
          "items": {
            "format": "int64",
            "type": "string"
          }
        }
      },
      "type": "object"
    },
    "ConsolidatedExecutorSummary": {
      "type": "object",
      "id": "ConsolidatedExecutorSummary",
      "description": "Consolidated summary about executors used by the application.",
      "properties": {
        "maxMemory": {
          "format": "int64",
          "type": "string"
        },
        "count": {
          "format": "int32",
          "type": "integer"
        },
        "failedTasks": {
          "format": "int32",
          "type": "integer"
        },
        "isExcluded": {
          "type": "integer",
          "format": "int32"
        },
        "totalGcTimeMillis": {
          "type": "string",
          "format": "int64"
        },
        "totalCores": {
          "format": "int32",
          "type": "integer"
        },
        "completedTasks": {
          "format": "int32",
          "type": "integer"
        },
        "totalDurationMillis": {
          "type": "string",
          "format": "int64"
        },
        "totalTasks": {
          "format": "int32",
          "type": "integer"
        },
        "memoryMetrics": {
          "$ref": "MemoryMetrics"
        },
        "activeTasks": {
          "type": "integer",
          "format": "int32"
        },
        "memoryUsed": {
          "format": "int64",
          "type": "string"
        },
        "totalShuffleWrite": {
          "format": "int64",
          "type": "string"
        },
        "diskUsed": {
          "type": "string",
          "format": "int64"
        },
        "rddBlocks": {
          "type": "integer",
          "format": "int32"
        },
        "totalInputBytes": {
          "type": "string",
          "format": "int64"
        },
        "totalShuffleRead": {
          "format": "int64",
          "type": "string"
        }
      }
    },
    "SummarizeSessionSparkApplicationStageAttemptTasksResponse": {
      "type": "object",
      "id": "SummarizeSessionSparkApplicationStageAttemptTasksResponse",
      "description": "Summary of tasks for a Spark Application stage attempt.",
      "properties": {
        "stageAttemptTasksSummary": {
          "description": "Summary of tasks for a Spark Application Stage Attempt",
          "$ref": "StageAttemptTasksSummary"
        }
      }
    },
    "AuthenticationConfig": {
      "type": "object",
      "id": "AuthenticationConfig",
      "description": "Authentication configuration for a workload is used to set the default identity for the workload execution. The config specifies the type of identity (service account or user) that will be used by workloads to access resources on the project(s).",
      "properties": {
        "userWorkloadAuthenticationType": {
          "description": "Optional. Authentication type for the user workload running in containers.",
          "enumDescriptions": [
            "If AuthenticationType is unspecified then END_USER_CREDENTIALS is used for 3.0 and newer runtimes, and SERVICE_ACCOUNT is used for older runtimes.",
            "Use service account credentials for authenticating to other services.",
            "Use OAuth credentials associated with the workload creator/user for authenticating to other services."
          ],
          "type": "string",
          "enum": [
            "AUTHENTICATION_TYPE_UNSPECIFIED",
            "SERVICE_ACCOUNT",
            "END_USER_CREDENTIALS"
          ]
        }
      }
    },
    "DataprocMetricConfig": {
      "type": "object",
      "description": "Dataproc metric config.",
      "properties": {
        "metrics": {
          "type": "array",
          "items": {
            "$ref": "Metric"
          },
          "description": "Required. Metrics sources to enable."
        }
      },
      "id": "DataprocMetricConfig"
    },
    "RddPartitionInfo": {
      "description": "Information about RDD partitions.",
      "properties": {
        "storageLevel": {
          "type": "string"
        },
        "memoryUsed": {
          "type": "string",
          "format": "int64"
        },
        "executors": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "blockName": {
          "type": "string"
        },
        "diskUsed": {
          "type": "string",
          "format": "int64"
        }
      },
      "id": "RddPartitionInfo",
      "type": "object"
    },
    "Cluster": {
      "type": "object",
      "id": "Cluster",
      "description": "Describes the identifying information, config, and status of a Dataproc cluster",
      "properties": {
        "labels": {
          "description": "Optional. The labels to associate with this cluster. Label keys must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). Label values may be empty, but, if present, must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). No more than 32 labels can be associated with a cluster.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "metrics": {
          "$ref": "ClusterMetrics",
          "description": "Output only. Contains cluster daemon metrics such as HDFS and YARN stats.Beta Feature: This report is available for testing purposes only. It may be changed before final release.",
          "readOnly": true
        },
        "status": {
          "$ref": "ClusterStatus",
          "description": "Output only. Cluster status.",
          "readOnly": true
        },
        "clusterUuid": {
          "readOnly": true,
          "description": "Output only. A cluster UUID (Unique Universal Identifier). Dataproc generates this value when it creates the cluster.",
          "type": "string"
        },
        "virtualClusterConfig": {
          "description": "Optional. The virtual cluster config is used when creating a Dataproc cluster that does not directly control the underlying compute resources, for example, when creating a Dataproc-on-GKE cluster (https://cloud.google.com/dataproc/docs/guides/dpgke/dataproc-gke-overview). Dataproc may set default values, and values may change when clusters are updated. Exactly one of config or virtual_cluster_config must be specified.",
          "$ref": "VirtualClusterConfig"
        },
        "statusHistory": {
          "type": "array",
          "items": {
            "$ref": "ClusterStatus"
          },
          "description": "Output only. The previous cluster status.",
          "readOnly": true
        },
        "clusterName": {
          "type": "string",
          "description": "Required. The cluster name, which must be unique within a project. The name must start with a lowercase letter, and can contain up to 51 lowercase letters, numbers, and hyphens. It cannot end with a hyphen. The name of a deleted cluster can be reused."
        },
        "projectId": {
          "type": "string",
          "description": "Required. The Google Cloud Platform project ID that the cluster belongs to."
        },
        "config": {
          "description": "Optional. The cluster config for a cluster of Compute Engine Instances. Note that Dataproc may set default values, and values may change when clusters are updated.Exactly one of ClusterConfig or VirtualClusterConfig must be specified.",
          "$ref": "ClusterConfig"
        }
      }
    },
    "AuxiliaryServicesConfig": {
      "id": "AuxiliaryServicesConfig",
      "description": "Auxiliary services configuration for a Cluster.",
      "properties": {
        "sparkHistoryServerConfig": {
          "description": "Optional. The Spark History Server configuration for the workload.",
          "$ref": "SparkHistoryServerConfig"
        },
        "metastoreConfig": {
          "description": "Optional. The Hive Metastore configuration for this workload.",
          "$ref": "MetastoreConfig"
        }
      },
      "type": "object"
    },
    "ListAutoscalingPoliciesResponse": {
      "description": "A response to a request to list autoscaling policies in a project.",
      "properties": {
        "nextPageToken": {
          "readOnly": true,
          "description": "Output only. This token is included in the response if there are more results to fetch.",
          "type": "string"
        },
        "policies": {
          "readOnly": true,
          "description": "Output only. Autoscaling policies list.",
          "type": "array",
          "items": {
            "$ref": "AutoscalingPolicy"
          }
        }
      },
      "id": "ListAutoscalingPoliciesResponse",
      "type": "object"
    },
    "ListWorkflowTemplatesResponse": {
      "type": "object",
      "description": "A response to a request to list workflow templates in a project.",
      "properties": {
        "templates": {
          "type": "array",
          "items": {
            "$ref": "WorkflowTemplate"
          },
          "readOnly": true,
          "description": "Output only. WorkflowTemplates list."
        },
        "nextPageToken": {
          "readOnly": true,
          "description": "Output only. This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent ListWorkflowTemplatesRequest.",
          "type": "string"
        },
        "unreachable": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Output only. List of workflow templates that could not be included in the response. Attempting to get one of these resources may indicate why it was not included in the list response.",
          "readOnly": true
        }
      },
      "id": "ListWorkflowTemplatesResponse"
    },
    "StageShufflePushReadMetrics": {
      "type": "object",
      "properties": {
        "remoteMergedChunksFetched": {
          "type": "string",
          "format": "int64"
        },
        "remoteMergedBlocksFetched": {
          "format": "int64",
          "type": "string"
        },
        "remoteMergedBytesRead": {
          "format": "int64",
          "type": "string"
        },
        "remoteMergedReqsDuration": {
          "format": "int64",
          "type": "string"
        },
        "localMergedChunksFetched": {
          "type": "string",
          "format": "int64"
        },
        "mergedFetchFallbackCount": {
          "type": "string",
          "format": "int64"
        },
        "localMergedBlocksFetched": {
          "format": "int64",
          "type": "string"
        },
        "localMergedBytesRead": {
          "format": "int64",
          "type": "string"
        },
        "corruptMergedBlockChunks": {
          "format": "int64",
          "type": "string"
        }
      },
      "id": "StageShufflePushReadMetrics"
    },
    "FallbackReason": {
      "type": "object",
      "description": "Native SQL Execution Data",
      "properties": {
        "fallbackNode": {
          "description": "Optional. Fallback node information.",
          "type": "string"
        },
        "fallbackReason": {
          "type": "string",
          "description": "Optional. Fallback to Spark reason."
        }
      },
      "id": "FallbackReason"
    },
    "ResourceProfileInfo": {
      "type": "object",
      "description": "Resource profile that contains information about all the resources required by executors and tasks.",
      "properties": {
        "resourceProfileId": {
          "format": "int32",
          "type": "integer"
        },
        "taskResources": {
          "type": "object",
          "additionalProperties": {
            "$ref": "TaskResourceRequest"
          }
        },
        "executorResources": {
          "type": "object",
          "additionalProperties": {
            "$ref": "ExecutorResourceRequest"
          }
        }
      },
      "id": "ResourceProfileInfo"
    },
    "RddDataDistribution": {
      "description": "Details about RDD usage.",
      "properties": {
        "address": {
          "type": "string"
        },
        "memoryUsed": {
          "format": "int64",
          "type": "string"
        },
        "offHeapMemoryUsed": {
          "format": "int64",
          "type": "string"
        },
        "onHeapMemoryUsed": {
          "format": "int64",
          "type": "string"
        },
        "onHeapMemoryRemaining": {
          "type": "string",
          "format": "int64"
        },
        "offHeapMemoryRemaining": {
          "type": "string",
          "format": "int64"
        },
        "diskUsed": {
          "type": "string",
          "format": "int64"
        },
        "memoryRemaining": {
          "type": "string",
          "format": "int64"
        }
      },
      "id": "RddDataDistribution",
      "type": "object"
    },
    "BuildInfo": {
      "type": "object",
      "description": "Native Build Info",
      "properties": {
        "buildKey": {
          "description": "Optional. Build key.",
          "type": "string"
        },
        "buildValue": {
          "type": "string",
          "description": "Optional. Build value."
        }
      },
      "id": "BuildInfo"
    },
    "WriteSparkApplicationContextRequest": {
      "type": "object",
      "id": "WriteSparkApplicationContextRequest",
      "description": "Write Spark Application data to internal storage systems",
      "properties": {
        "parent": {
          "description": "Required. Parent (Batch) resource reference.",
          "type": "string"
        },
        "sparkWrapperObjects": {
          "type": "array",
          "items": {
            "$ref": "SparkWrapperObject"
          }
        }
      }
    },
    "ShufflePushReadMetrics": {
      "type": "object",
      "id": "ShufflePushReadMetrics",
      "properties": {
        "remoteMergedBlocksFetched": {
          "type": "string",
          "format": "int64"
        },
        "remoteMergedBytesRead": {
          "format": "int64",
          "type": "string"
        },
        "remoteMergedReqsDuration": {
          "format": "int64",
          "type": "string"
        },
        "remoteMergedChunksFetched": {
          "type": "string",
          "format": "int64"
        },
        "mergedFetchFallbackCount": {
          "type": "string",
          "format": "int64"
        },
        "localMergedBlocksFetched": {
          "format": "int64",
          "type": "string"
        },
        "localMergedChunksFetched": {
          "type": "string",
          "format": "int64"
        },
        "corruptMergedBlockChunks": {
          "format": "int64",
          "type": "string"
        },
        "localMergedBytesRead": {
          "type": "string",
          "format": "int64"
        }
      }
    },
    "StopClusterRequest": {
      "description": "A request to stop a cluster.",
      "properties": {
        "requestId": {
          "type": "string",
          "description": "Optional. A unique ID used to identify the request. If the server receives two StopClusterRequest (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.StopClusterRequest)s with the same id, then the second request will be ignored and the first google.longrunning.Operation created and stored in the backend is returned.Recommendation: Set this value to a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier).T[...]"
        },
        "clusterUuid": {
          "description": "Optional. Specifying the cluster_uuid means the RPC will fail (with error NOT_FOUND) if a cluster with the specified UUID does not exist.",
          "type": "string"
        }
      },
      "id": "StopClusterRequest",
      "type": "object"
    },
    "WorkflowMetadata": {
      "id": "WorkflowMetadata",
      "description": "A Dataproc workflow template resource.",
      "properties": {
        "dagTimeout": {
          "readOnly": true,
          "description": "Output only. The timeout duration for the DAG of jobs, expressed in seconds (see JSON representation of duration (https://developers.google.com/protocol-buffers/docs/proto3#json)).",
          "type": "string",
          "format": "google-duration"
        },
        "startTime": {
          "description": "Output only. Workflow start time.",
          "readOnly": true,
          "format": "google-datetime",
          "type": "string"
        },
        "graph": {
          "$ref": "WorkflowGraph",
          "readOnly": true,
          "description": "Output only. The workflow graph."
        },
        "createCluster": {
          "readOnly": true,
          "description": "Output only. The create cluster operation metadata.",
          "$ref": "ClusterOperation"
        },
        "version": {
          "format": "int32",
          "type": "integer",
          "description": "Output only. The version of template at the time of workflow instantiation.",
          "readOnly": true
        },
        "state": {
          "description": "Output only. The workflow state.",
          "readOnly": true,
          "enumDescriptions": [
            "Unused.",
            "The operation has been created.",
            "The operation is running.",
            "The operation is done; either cancelled or completed."
          ],
          "type": "string",
          "enum": [
            "UNKNOWN",
            "PENDING",
            "RUNNING",
            "DONE"
          ]
        },
        "dagStartTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "Output only. DAG start time, only set for workflows with dag_timeout when DAG begins.",
          "readOnly": true
        },
        "dagEndTime": {
          "description": "Output only. DAG end time, only set for workflows with dag_timeout when DAG ends.",
          "readOnly": true,
          "format": "google-datetime",
          "type": "string"
        },
        "deleteCluster": {
          "$ref": "ClusterOperation",
          "description": "Output only. The delete cluster operation metadata.",
          "readOnly": true
        },
        "clusterName": {
          "readOnly": true,
          "description": "Output only. The name of the target cluster.",
          "type": "string"
        },
        "clusterUuid": {
          "readOnly": true,
          "description": "Output only. The UUID of target cluster.",
          "type": "string"
        },
        "endTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "Output only. Workflow end time.",
          "readOnly": true
        },
        "template": {
          "description": "Output only. The resource name of the workflow template as described in https://cloud.google.com/apis/design/resource_names. For projects.regions.workflowTemplates, the resource name of the template has the following format: projects/{project_id}/regions/{region}/workflowTemplates/{template_id} For projects.locations.workflowTemplates, the resource name of the template has the following format: projects/{project_id}/locations/{location}/workflowTemplates/{template_id}",
          "readOnly": true,
          "type": "string"
        }
      },
      "type": "object"
    },
    "ClusterMetrics": {
      "id": "ClusterMetrics",
      "description": "Contains cluster daemon metrics, such as HDFS and YARN stats.Beta Feature: This report is available for testing purposes only. It may be changed before final release.",
      "properties": {
        "yarnMetrics": {
          "description": "YARN metrics.",
          "additionalProperties": {
            "type": "string",
            "format": "int64"
          },
          "type": "object"
        },
        "hdfsMetrics": {
          "type": "object",
          "description": "The HDFS metrics.",
          "additionalProperties": {
            "format": "int64",
            "type": "string"
          }
        }
      },
      "type": "object"
    },
    "SummarizeSparkApplicationExecutorsResponse": {
      "id": "SummarizeSparkApplicationExecutorsResponse",
      "description": "Consolidated summary of executors for a Spark Application.",
      "properties": {
        "totalExecutorSummary": {
          "description": "Overall consolidated summary for all executors.",
          "$ref": "ConsolidatedExecutorSummary"
        },
        "applicationId": {
          "type": "string",
          "description": "Spark Application Id"
        },
        "activeExecutorSummary": {
          "description": "Consolidated summary for active executors.",
          "$ref": "ConsolidatedExecutorSummary"
        },
        "deadExecutorSummary": {
          "description": "Consolidated summary for dead executors.",
          "$ref": "ConsolidatedExecutorSummary"
        }
      },
      "type": "object"
    },
    "SparkConnectConfig": {
      "type": "object",
      "description": "Spark connect configuration for an interactive session.",
      "properties": {},
      "id": "SparkConnectConfig"
    },
    "NativeBuildInfoUiData": {
      "properties": {
        "buildClass": {
          "type": "string",
          "description": "Optional. Build class of Native."
        },
        "buildInfo": {
          "description": "Optional. Build related details.",
          "type": "array",
          "items": {
            "$ref": "BuildInfo"
          }
        }
      },
      "id": "NativeBuildInfoUiData",
      "type": "object"
    },
    "TaskData": {
      "type": "object",
      "id": "TaskData",
      "description": "Data corresponding to tasks created by spark.",
      "properties": {
        "speculative": {
          "type": "boolean"
        },
        "hasMetrics": {
          "type": "boolean"
        },
        "stageAttemptId": {
          "type": "integer",
          "format": "int32"
        },
        "taskId": {
          "format": "int64",
          "type": "string"
        },
        "taskMetrics": {
          "$ref": "TaskMetrics"
        },
        "schedulerDelayMillis": {
          "type": "string",
          "format": "int64"
        },
        "errorMessage": {
          "type": "string"
        },
        "index": {
          "type": "integer",
          "format": "int32"
        },
        "host": {
          "type": "string"
        },
        "accumulatorUpdates": {
          "type": "array",
          "items": {
            "$ref": "AccumulableInfo"
          }
        },
        "attempt": {
          "format": "int32",
          "type": "integer"
        },
        "launchTime": {
          "type": "string",
          "format": "google-datetime"
        },
        "stageId": {
          "format": "int64",
          "type": "string"
        },
        "durationMillis": {
          "format": "int64",
          "type": "string"
        },
        "partitionId": {
          "format": "int32",
          "type": "integer"
        },
        "taskLocality": {
          "type": "string"
        },
        "gettingResultTimeMillis": {
          "format": "int64",
          "type": "string"
        },
        "executorId": {
          "type": "string"
        },
        "executorLogs": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "resultFetchStart": {
          "type": "string",
          "format": "google-datetime"
        },
        "status": {
          "type": "string"
        }
      }
    },
    "SparkBatch": {
      "id": "SparkBatch",
      "description": "A configuration for running an Apache Spark (https://spark.apache.org/) batch workload.",
      "properties": {
        "mainClass": {
          "description": "Optional. The name of the driver main class. The jar file that contains the class must be in the classpath or specified in jar_file_uris.",
          "type": "string"
        },
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. The arguments to pass to the driver. Do not include arguments that can be set as batch properties, such as --conf, since a collision can occur that causes an incorrect batch submission."
        },
        "mainJarFileUri": {
          "type": "string",
          "description": "Optional. The HCFS URI of the jar file that contains the main class."
        },
        "fileUris": {
          "description": "Optional. HCFS URIs of files to be placed in the working directory of each executor.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "jarFileUris": {
          "description": "Optional. HCFS URIs of jar files to add to the classpath of the Spark driver and tasks.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "archiveUris": {
          "description": "Optional. HCFS URIs of archives to be extracted into the working directory of each executor. Supported file types: .jar, .tar, .tar.gz, .tgz, and .zip.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "type": "object"
    },
    "ExecutionConfig": {
      "type": "object",
      "id": "ExecutionConfig",
      "description": "Execution configuration for a workload.",
      "properties": {
        "ttl": {
          "format": "google-duration",
          "type": "string",
          "description": "Optional. The duration after which the workload will be terminated, specified as the JSON representation for Duration (https://protobuf.dev/programming-guides/proto3/#json). When the workload exceeds this duration, it will be unconditionally terminated without waiting for ongoing work to finish. If ttl is not specified for a batch workload, the workload will be allowed to run until it exits naturally (or run forever without exiting). If ttl is not specified for an inter[...]"
        },
        "idleTtl": {
          "format": "google-duration",
          "type": "string",
          "description": "Optional. Applies to sessions only. The duration to keep the session alive while it's idling. Exceeding this threshold causes the session to terminate. This field cannot be set on a batch workload. Minimum value is 10 minutes; maximum value is 14 days (see JSON representation of Duration (https://developers.google.com/protocol-buffers/docs/proto3#json)). Defaults to 1 hour if not set. If both ttl and idle_ttl are specified for an interactive session, the conditions are [...]"
        },
        "serviceAccount": {
          "type": "string",
          "description": "Optional. Service account that used to execute workload."
        },
        "networkTags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. Tags used for network traffic control."
        },
        "kmsKey": {
          "type": "string",
          "description": "Optional. The Cloud KMS key to use for encryption."
        },
        "subnetworkUri": {
          "description": "Optional. Subnetwork URI to connect workload to.",
          "type": "string"
        },
        "authenticationConfig": {
          "description": "Optional. Authentication configuration used to set the default identity for the workload execution. The config specifies the type of identity (service account or user) that will be used by workloads to access resources on the project(s).",
          "$ref": "AuthenticationConfig"
        },
        "networkUri": {
          "type": "string",
          "description": "Optional. Network URI to connect workload to."
        },
        "stagingBucket": {
          "type": "string",
          "description": "Optional. A Cloud Storage bucket used to stage workload dependencies, config files, and store workload output and other ephemeral data, such as Spark history files. If you do not specify a staging bucket, Cloud Dataproc will determine a Cloud Storage location according to the region where your workload is running, and then create and manage project-level, per-location staging and temporary buckets. This field requires a Cloud Storage bucket name, not a gs://... URI to a[...]"
        },
        "resourceManagerTags": {
          "type": "object",
          "description": "Optional. Associates Resource Manager tags with the workload nodes. There is a max limit of 30 tags. Keys and values can be either in numeric format, such as tagKeys/{tag_key_id} and tagValues/{tag_value_id}, or in namespaced format, such as {org_id|project_id}/{tag_key_short_name} and {tag_value_short_name}.",
          "additionalProperties": {
            "type": "string"
          }
        }
      }
    },
    "Operation": {
      "type": "object",
      "description": "This resource represents a long-running operation that is the result of a network API call.",
      "properties": {
        "name": {
          "description": "The server-assigned name, which is only unique within the same service that originally returns it. If you use the default HTTP mapping, the name should be a resource name ending with operations/{unique_id}.",
          "type": "string"
        },
        "metadata": {
          "description": "Service-specific metadata associated with the operation. It typically contains progress information and common metadata such as create time. Some services might not provide such metadata. Any method that returns a long-running operation should document the metadata type, if any.",
          "additionalProperties": {
            "description": "Properties of the object. Contains field @type with type URL.",
            "type": "any"
          },
          "type": "object"
        },
        "done": {
          "description": "If the value is false, it means the operation is still in progress. If true, the operation is completed, and either error or response is available.",
          "type": "boolean"
        },
        "error": {
          "description": "The error result of the operation in case of failure or cancellation.",
          "$ref": "Status"
        }
      },
      "id": "Operation"
    },
    "GkeNodePoolAcceleratorConfig": {
      "type": "object",
      "id": "GkeNodePoolAcceleratorConfig",
      "description": "A GkeNodeConfigAcceleratorConfig represents a Hardware Accelerator request for a node pool.",
      "properties": {
        "acceleratorCount": {
          "description": "The number of accelerator cards exposed to an instance.",
          "format": "int64",
          "type": "string"
        },
        "acceleratorType": {
          "type": "string",
          "description": "The accelerator type resource namename (see GPUs on Compute Engine)."
        },
        "gpuPartitionSize": {
          "type": "string",
          "description": "Size of partitions to create on the GPU. Valid values are described in the NVIDIA mig user guide (https://docs.nvidia.com/datacenter/tesla/mig-user-guide/#partitioning)."
        }
      }
    },
    "MemoryMetrics": {
      "properties": {
        "totalOnHeapStorageMemory": {
          "format": "int64",
          "type": "string"
        },
        "totalOffHeapStorageMemory": {
          "type": "string",
          "format": "int64"
        },
        "usedOffHeapStorageMemory": {
          "format": "int64",
          "type": "string"
        },
        "usedOnHeapStorageMemory": {
          "format": "int64",
          "type": "string"
        }
      },
      "id": "MemoryMetrics",
      "type": "object"
    },
    "RepairClusterRequest": {
      "type": "object",
      "id": "RepairClusterRequest",
      "description": "A request to repair a cluster.",
      "properties": {
        "requestId": {
          "type": "string",
          "description": "Optional. A unique ID used to identify the request. If the server receives two RepairClusterRequests with the same ID, the second request is ignored, and the first google.longrunning.Operation created and stored in the backend is returned.Recommendation: Set this value to a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier).The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), and hyphens (-). The maximum length is 40 characters."
        },
        "nodePools": {
          "description": "Optional. Node pools and corresponding repair action to be taken. All node pools should be unique in this request. i.e. Multiple entries for the same node pool id are not allowed.",
          "type": "array",
          "items": {
            "$ref": "NodePool"
          }
        },
        "dataprocSuperUser": {
          "description": "Optional. Whether the request is submitted by Dataproc super user. If true, IAM will check 'dataproc.clusters.repair' permission instead of 'dataproc.clusters.update' permission. This is to give Dataproc superuser the ability to repair clusters without granting the overly broad update permission.",
          "type": "boolean"
        },
        "gracefulDecommissionTimeout": {
          "description": "Optional. Timeout for graceful YARN decommissioning. Graceful decommissioning facilitates the removal of cluster nodes without interrupting jobs in progress. The timeout specifies the amount of time to wait for jobs finish before forcefully removing nodes. The default timeout is 0 for forceful decommissioning, and the maximum timeout period is 1 day. (see JSON Mapping—Duration (https://developers.google.com/protocol-buffers/docs/proto3#json)).graceful_decommission_timeo[...]",
          "type": "string",
          "format": "google-duration"
        },
        "cluster": {
          "description": "Optional. Cluster to be repaired",
          "$ref": "ClusterToRepair"
        },
        "parentOperationId": {
          "type": "string",
          "description": "Optional. operation id of the parent operation sending the repair request"
        },
        "clusterUuid": {
          "type": "string",
          "description": "Optional. Specifying the cluster_uuid means the RPC will fail (with error NOT_FOUND) if a cluster with the specified UUID does not exist."
        }
      }
    },
    "TrinoJob": {
      "type": "object",
      "id": "TrinoJob",
      "description": "A Dataproc job for running Trino (https://trino.io/) queries. IMPORTANT: The Dataproc Trino Optional Component (https://cloud.google.com/dataproc/docs/concepts/components/trino) must be enabled when the cluster is created to submit a Trino job to the cluster.",
      "properties": {
        "queryList": {
          "description": "A list of queries.",
          "$ref": "QueryList"
        },
        "outputFormat": {
          "description": "Optional. The format in which query output will be displayed. See the Trino documentation for supported output formats",
          "type": "string"
        },
        "clientTags": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. Trino client tags to attach to this query"
        },
        "properties": {
          "description": "Optional. A mapping of property names to values. Used to set Trino session properties (https://trino.io/docs/current/sql/set-session.html) Equivalent to using the --session flag in the Trino CLI",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "continueOnFailure": {
          "description": "Optional. Whether to continue executing queries if a query fails. The default value is false. Setting to true can be useful when executing independent parallel queries.",
          "type": "boolean"
        },
        "queryFileUri": {
          "description": "The HCFS URI of the script that contains SQL queries.",
          "type": "string"
        },
        "loggingConfig": {
          "description": "Optional. The runtime log config for job execution.",
          "$ref": "LoggingConfig"
        }
      }
    },
    "SearchSessionSparkApplicationStagesResponse": {
      "id": "SearchSessionSparkApplicationStagesResponse",
      "description": "A list of stages associated with a Spark Application.",
      "properties": {
        "sparkApplicationStages": {
          "description": "Output only. Data corresponding to a stage.",
          "readOnly": true,
          "type": "array",
          "items": {
            "$ref": "StageData"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSessionSparkApplicationStages."
        }
      },
      "type": "object"
    },
    "ClusterSelector": {
      "id": "ClusterSelector",
      "description": "A selector that chooses target cluster for jobs based on metadata.",
      "properties": {
        "zone": {
          "description": "Optional. The zone where workflow process executes. This parameter does not affect the selection of the cluster.If unspecified, the zone of the first cluster matching the selector is used.",
          "type": "string"
        },
        "clusterLabels": {
          "description": "Required. The cluster labels. Cluster must have all labels to match.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "NodeGroupOperationMetadata": {
      "id": "NodeGroupOperationMetadata",
      "description": "Metadata describing the node group operation.",
      "properties": {
        "labels": {
          "type": "object",
          "description": "Output only. Labels associated with the operation.",
          "additionalProperties": {
            "type": "string"
          },
          "readOnly": true
        },
        "nodeGroupId": {
          "type": "string",
          "readOnly": true,
          "description": "Output only. Node group ID for the operation."
        },
        "warnings": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Output only. Errors encountered during operation execution.",
          "readOnly": true
        },
        "statusHistory": {
          "type": "array",
          "items": {
            "$ref": "ClusterOperationStatus"
          },
          "description": "Output only. The previous operation status.",
          "readOnly": true
        },
        "clusterUuid": {
          "description": "Output only. Cluster UUID associated with the node group operation.",
          "readOnly": true,
          "type": "string"
        },
        "status": {
          "description": "Output only. Current operation status.",
          "readOnly": true,
          "$ref": "ClusterOperationStatus"
        },
        "description": {
          "type": "string",
          "description": "Output only. Short description of operation.",
          "readOnly": true
        },
        "operationType": {
          "type": "string",
          "enum": [
            "NODE_GROUP_OPERATION_TYPE_UNSPECIFIED",
            "CREATE",
            "UPDATE",
            "DELETE",
            "RESIZE",
            "REPAIR",
            "UPDATE_LABELS",
            "START",
            "STOP",
            "UPDATE_METADATA_CONFIG"
          ],
          "description": "The operation type.",
          "enumDescriptions": [
            "Node group operation type is unknown.",
            "Create node group operation type.",
            "Update node group operation type.",
            "Delete node group operation type.",
            "Resize node group operation type.",
            "Repair node group operation type.",
            "Update node group label operation type.",
            "Start node group operation type.",
            "Stop node group operation type.",
            "This operation type is used to update the metadata config of a node group. We update the metadata of the VMs in the node group and await for intended config change to be completed at the node group level. Currently, only the identity config update is supported."
          ]
        }
      },
      "type": "object"
    },
    "ClusterOperation": {
      "type": "object",
      "description": "The cluster operation triggered by a workflow.",
      "properties": {
        "done": {
          "type": "boolean",
          "readOnly": true,
          "description": "Output only. Indicates the operation is done."
        },
        "error": {
          "readOnly": true,
          "description": "Output only. Error, if operation failed.",
          "type": "string"
        },
        "operationId": {
          "readOnly": true,
          "description": "Output only. The id of the cluster operation.",
          "type": "string"
        }
      },
      "id": "ClusterOperation"
    },
    "ValueInfo": {
      "type": "object",
      "description": "Annotatated property value.",
      "properties": {
        "value": {
          "description": "Property value.",
          "type": "string"
        },
        "overriddenValue": {
          "description": "Optional. Value which was replaced by the corresponding component.",
          "type": "string"
        },
        "annotation": {
          "type": "string",
          "description": "Annotation, comment or explanation why the property was set."
        }
      },
      "id": "ValueInfo"
    },
    "AccessSparkApplicationEnvironmentInfoResponse": {
      "type": "object",
      "id": "AccessSparkApplicationEnvironmentInfoResponse",
      "description": "Environment details of a Saprk Application.",
      "properties": {
        "applicationEnvironmentInfo": {
          "description": "Details about the Environment that the application is running in.",
          "$ref": "ApplicationEnvironmentInfo"
        }
      }
    },
    "RepositoryConfig": {
      "id": "RepositoryConfig",
      "description": "Configuration for dependency repositories",
      "properties": {
        "pypiRepositoryConfig": {
          "description": "Optional. Configuration for PyPi repository.",
          "$ref": "PyPiRepositoryConfig"
        }
      },
      "type": "object"
    },
    "Metric": {
      "description": "A Dataproc custom metric.",
      "properties": {
        "metricSource": {
          "type": "string",
          "enum": [
            "METRIC_SOURCE_UNSPECIFIED",
            "MONITORING_AGENT_DEFAULTS",
            "HDFS",
            "SPARK",
            "YARN",
            "SPARK_HISTORY_SERVER",
            "HIVESERVER2",
            "HIVEMETASTORE",
            "FLINK"
          ],
          "description": "Required. A standard set of metrics is collected unless metricOverrides are specified for the metric source (see Custom metrics (https://cloud.google.com/dataproc/docs/guides/dataproc-metrics#custom_metrics) for more information).",
          "enumDescriptions": [
            "Required unspecified metric source.",
            "Monitoring agent metrics. If this source is enabled, Dataproc enables the monitoring agent in Compute Engine, and collects monitoring agent metrics, which are published with an agent.googleapis.com prefix.",
            "HDFS metric source.",
            "Spark metric source.",
            "YARN metric source.",
            "Spark History Server metric source.",
            "Hiveserver2 metric source.",
            "hivemetastore metric source",
            "flink metric source"
          ]
        },
        "metricOverrides": {
          "description": "Optional. Specify one or more Custom metrics (https://cloud.google.com/dataproc/docs/guides/dataproc-metrics#custom_metrics) to collect for the metric course (for the SPARK metric source (any Spark metric (https://spark.apache.org/docs/latest/monitoring.html#metrics) can be specified).Provide metrics in the following format: METRIC_SOURCE: INSTANCE:GROUP:METRIC Use camelcase as appropriate.Examples: yarn:ResourceManager:QueueMetrics:AppsCompleted spark:driver:DAGSchedul[...]",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "id": "Metric",
      "type": "object"
    },
    "Empty": {
      "description": "A generic empty message that you can re-use to avoid defining duplicated empty messages in your APIs. A typical example is to use it as the request or the response type of an API method. For instance: service Foo { rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty); } ",
      "properties": {},
      "id": "Empty",
      "type": "object"
    },
    "ApplicationEnvironmentInfo": {
      "type": "object",
      "description": "Details about the Environment that the application is running in.",
      "properties": {
        "hadoopProperties": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "resourceProfiles": {
          "type": "array",
          "items": {
            "$ref": "ResourceProfileInfo"
          }
        },
        "classpathEntries": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "runtime": {
          "$ref": "SparkRuntimeInfo"
        },
        "sparkProperties": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "systemProperties": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "metricsProperties": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        }
      },
      "id": "ApplicationEnvironmentInfo"
    },
    "ListClustersResponse": {
      "type": "object",
      "description": "The list of all clusters in a project.",
      "properties": {
        "clusters": {
          "readOnly": true,
          "description": "Output only. The clusters in the project.",
          "type": "array",
          "items": {
            "$ref": "Cluster"
          }
        },
        "nextPageToken": {
          "type": "string",
          "readOnly": true,
          "description": "Output only. This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent ListClustersRequest."
        }
      },
      "id": "ListClustersResponse"
    },
    "SparkPlanGraphNodeWrapper": {
      "type": "object",
      "id": "SparkPlanGraphNodeWrapper",
      "description": "Wrapper user to represent either a node or a cluster.",
      "properties": {
        "node": {
          "$ref": "SparkPlanGraphNode"
        },
        "cluster": {
          "$ref": "SparkPlanGraphCluster"
        }
      }
    },
    "ListOperationsResponse": {
      "description": "The response message for Operations.ListOperations.",
      "properties": {
        "operations": {
          "type": "array",
          "items": {
            "$ref": "Operation"
          },
          "description": "A list of operations that matches the specified filter in the request."
        },
        "nextPageToken": {
          "description": "The standard List next-page token.",
          "type": "string"
        },
        "unreachable": {
          "description": "Unordered list. Unreachable resources. Populated when the request sets ListOperationsRequest.return_partial_success and reads across collections. For example, when attempting to list all resources across all supported locations.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "id": "ListOperationsResponse",
      "type": "object"
    },
    "SearchSessionSparkApplicationExecutorsResponse": {
      "type": "object",
      "description": "List of Executors associated with a Spark Application.",
      "properties": {
        "sparkApplicationExecutors": {
          "description": "Details about executors used by the application.",
          "type": "array",
          "items": {
            "$ref": "ExecutorSummary"
          }
        },
        "nextPageToken": {
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSessionSparkApplicationExecutorsRequest.",
          "type": "string"
        }
      },
      "id": "SearchSessionSparkApplicationExecutorsResponse"
    },
    "StagesSummary": {
      "type": "object",
      "id": "StagesSummary",
      "description": "Data related to Stages page summary",
      "properties": {
        "applicationId": {
          "type": "string"
        },
        "numCompletedStages": {
          "format": "int32",
          "type": "integer"
        },
        "numPendingStages": {
          "type": "integer",
          "format": "int32"
        },
        "numSkippedStages": {
          "format": "int32",
          "type": "integer"
        },
        "numActiveStages": {
          "format": "int32",
          "type": "integer"
        },
        "numFailedStages": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "CohortInfo": {
      "type": "object",
      "id": "CohortInfo",
      "description": "Information about the cohort that the workload belongs to.",
      "properties": {
        "cohortSource": {
          "type": "string",
          "enum": [
            "COHORT_SOURCE_UNSPECIFIED",
            "USER_PROVIDED",
            "AIRFLOW"
          ],
          "enumDescriptions": [
            "Cohort source is unspecified.",
            "Indicates that the cohort was explicitly provided.",
            "Composed from the labels coming from Airflow/Composer."
          ],
          "readOnly": true,
          "description": "Output only. Source of the cohort."
        },
        "cohort": {
          "description": "Output only. Final cohort that was used to tune the workload.",
          "readOnly": true,
          "type": "string"
        }
      }
    },
    "AccessSparkApplicationJobResponse": {
      "type": "object",
      "description": "Details of a particular job associated with Spark Application",
      "properties": {
        "jobData": {
          "readOnly": true,
          "description": "Output only. Data corresponding to a spark job.",
          "$ref": "JobData"
        }
      },
      "id": "AccessSparkApplicationJobResponse"
    },
    "TestIamPermissionsRequest": {
      "type": "object",
      "description": "Request message for TestIamPermissions method.",
      "properties": {
        "permissions": {
          "description": "The set of permissions to check for the resource. Permissions with wildcards (such as * or storage.*) are not allowed. For more information see IAM Overview (https://cloud.google.com/iam/docs/overview#permissions).",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "id": "TestIamPermissionsRequest"
    },
    "SearchSessionSparkApplicationsResponse": {
      "id": "SearchSessionSparkApplicationsResponse",
      "description": "A list of summary of Spark Applications",
      "properties": {
        "sparkApplications": {
          "type": "array",
          "items": {
            "$ref": "SparkApplication"
          },
          "description": "Output only. High level information corresponding to an application.",
          "readOnly": true
        },
        "nextPageToken": {
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSessionSparkApplicationsRequest.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "JupyterConfig": {
      "id": "JupyterConfig",
      "description": "Jupyter configuration for an interactive session.",
      "properties": {
        "kernel": {
          "description": "Optional. Kernel",
          "enumDescriptions": [
            "The kernel is unknown.",
            "Python kernel.",
            "Scala kernel."
          ],
          "type": "string",
          "enum": [
            "KERNEL_UNSPECIFIED",
            "PYTHON",
            "SCALA"
          ]
        },
        "displayName": {
          "type": "string",
          "description": "Optional. Display name, shown in the Jupyter kernelspec card."
        }
      },
      "type": "object"
    },
    "SearchSparkApplicationSqlQueriesResponse": {
      "type": "object",
      "id": "SearchSparkApplicationSqlQueriesResponse",
      "description": "List of all queries for a Spark Application.",
      "properties": {
        "sparkApplicationSqlQueries": {
          "readOnly": true,
          "description": "Output only. SQL Execution Data",
          "type": "array",
          "items": {
            "$ref": "SqlExecutionUiData"
          }
        },
        "nextPageToken": {
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSparkApplicationSqlQueriesRequest.",
          "type": "string"
        }
      }
    },
    "SparkRBatch": {
      "id": "SparkRBatch",
      "description": "A configuration for running an Apache SparkR (https://spark.apache.org/docs/latest/sparkr.html) batch workload.",
      "properties": {
        "args": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "description": "Optional. The arguments to pass to the Spark driver. Do not include arguments that can be set as batch properties, such as --conf, since a collision can occur that causes an incorrect batch submission."
        },
        "mainRFileUri": {
          "type": "string",
          "description": "Required. The HCFS URI of the main R file to use as the driver. Must be a .R or .r file."
        },
        "fileUris": {
          "description": "Optional. HCFS URIs of files to be placed in the working directory of each executor.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "archiveUris": {
          "description": "Optional. HCFS URIs of archives to be extracted into the working directory of each executor. Supported file types: .jar, .tar, .tar.gz, .tgz, and .zip.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "type": "object"
    },
    "SparkPlanGraph": {
      "type": "object",
      "id": "SparkPlanGraph",
      "description": "A graph used for storing information of an executionPlan of DataFrame.",
      "properties": {
        "nodes": {
          "type": "array",
          "items": {
            "$ref": "SparkPlanGraphNodeWrapper"
          }
        },
        "edges": {
          "type": "array",
          "items": {
            "$ref": "SparkPlanGraphEdge"
          }
        },
        "executionId": {
          "type": "string",
          "format": "int64"
        }
      }
    },
    "SparkPlanGraphCluster": {
      "type": "object",
      "id": "SparkPlanGraphCluster",
      "description": "Represents a tree of spark plan.",
      "properties": {
        "desc": {
          "type": "string"
        },
        "nodes": {
          "type": "array",
          "items": {
            "$ref": "SparkPlanGraphNodeWrapper"
          }
        },
        "metrics": {
          "type": "array",
          "items": {
            "$ref": "SqlPlanMetric"
          }
        },
        "metadata": {
          "description": "Optional. Additional metadata for the spark plan graph cluster.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "sparkPlanGraphClusterId": {
          "type": "string",
          "format": "int64"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "AccessSessionSparkApplicationSqlQueryResponse": {
      "type": "object",
      "id": "AccessSessionSparkApplicationSqlQueryResponse",
      "description": "Details of a query for a Spark Application",
      "properties": {
        "executionData": {
          "description": "SQL Execution Data",
          "$ref": "SqlExecutionUiData"
        }
      }
    },
    "LoggingConfig": {
      "id": "LoggingConfig",
      "description": "The runtime logging config of the job.",
      "properties": {
        "driverLogLevels": {
          "type": "object",
          "description": "The per-package log levels for the driver. This can include \"root\" package name to configure rootLogger. Examples: - 'com.google = FATAL' - 'root = INFO' - 'org.apache = DEBUG'",
          "additionalProperties": {
            "enumDescriptions": [
              "Level is unspecified. Use default level for log4j.",
              "Use ALL level for log4j.",
              "Use TRACE level for log4j.",
              "Use DEBUG level for log4j.",
              "Use INFO level for log4j.",
              "Use WARN level for log4j.",
              "Use ERROR level for log4j.",
              "Use FATAL level for log4j.",
              "Turn off log4j."
            ],
            "type": "string",
            "enum": [
              "LEVEL_UNSPECIFIED",
              "ALL",
              "TRACE",
              "DEBUG",
              "INFO",
              "WARN",
              "ERROR",
              "FATAL",
              "OFF"
            ]
          }
        }
      },
      "type": "object"
    },
    "ShuffleWriteQuantileMetrics": {
      "type": "object",
      "properties": {
        "writeBytes": {
          "$ref": "Quantiles"
        },
        "writeRecords": {
          "$ref": "Quantiles"
        },
        "writeTimeNanos": {
          "$ref": "Quantiles"
        }
      },
      "id": "ShuffleWriteQuantileMetrics"
    },
    "NodeInitializationAction": {
      "id": "NodeInitializationAction",
      "description": "Specifies an executable to run on a fully configured node and a timeout period for executable completion.",
      "properties": {
        "executableFile": {
          "type": "string",
          "description": "Required. Cloud Storage URI of executable file."
        },
        "executionTimeout": {
          "description": "Optional. Amount of time executable has to complete. Default is 10 minutes (see JSON representation of Duration (https://developers.google.com/protocol-buffers/docs/proto3#json)).Cluster creation fails with an explanatory error message (the name of the executable that caused the error and the exceeded timeout period) if the executable is not completed at end of the timeout period.",
          "type": "string",
          "format": "google-duration"
        }
      },
      "type": "object"
    },
    "Session": {
      "id": "Session",
      "description": "A representation of a session.",
      "properties": {
        "labels": {
          "type": "object",
          "description": "Optional. The labels to associate with the session. Label keys must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). Label values may be empty, but, if present, must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). No more than 32 labels can be associated with a session.",
          "additionalProperties": {
            "type": "string"
          }
        },
        "sessionTemplate": {
          "type": "string",
          "description": "Optional. The session template used by the session.Only resource names, including project ID and location, are valid.Example: * https://www.googleapis.com/compute/v1/projects/[project_id]/locations/[dataproc_region]/sessionTemplates/[template_id] * projects/[project_id]/locations/[dataproc_region]/sessionTemplates/[template_id]The template must be in the same project and Dataproc region as the session."
        },
        "createTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "Output only. The time when the session was created.",
          "readOnly": true
        },
        "stateHistory": {
          "type": "array",
          "items": {
            "$ref": "SessionStateHistory"
          },
          "readOnly": true,
          "description": "Output only. Historical state information for the session."
        },
        "jupyterSession": {
          "description": "Optional. Jupyter session config.",
          "$ref": "JupyterConfig"
        },
        "stateMessage": {
          "type": "string",
          "description": "Output only. Session state details, such as the failure description if the state is FAILED.",
          "readOnly": true
        },
        "sparkConnectSession": {
          "description": "Optional. Spark connect session config.",
          "$ref": "SparkConnectConfig"
        },
        "user": {
          "type": "string",
          "description": "Optional. The email address of the user who owns the session."
        },
        "runtimeInfo": {
          "$ref": "RuntimeInfo",
          "description": "Output only. Runtime information about session execution.",
          "readOnly": true
        },
        "runtimeConfig": {
          "description": "Optional. Runtime configuration for the session execution.",
          "$ref": "RuntimeConfig"
        },
        "state": {
          "description": "Output only. A state of the session.",
          "readOnly": true,
          "enumDescriptions": [
            "The session state is unknown.",
            "The session is created prior to running.",
            "The session is running.",
            "The session is terminating.",
            "The session is terminated successfully.",
            "The session is no longer running due to an error."
          ],
          "type": "string",
          "enum": [
            "STATE_UNSPECIFIED",
            "CREATING",
            "ACTIVE",
            "TERMINATING",
            "TERMINATED",
            "FAILED"
          ]
        },
        "stateTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "Output only. The time when the session entered the current state.",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "description": "Identifier. The resource name of the session."
        },
        "uuid": {
          "type": "string",
          "description": "Output only. A session UUID (Unique Universal Identifier). The service generates this value when it creates the session.",
          "readOnly": true
        },
        "environmentConfig": {
          "description": "Optional. Environment configuration for the session execution.",
          "$ref": "EnvironmentConfig"
        },
        "creator": {
          "readOnly": true,
          "description": "Output only. The email address of the user who created the session.",
          "type": "string"
        }
      },
      "type": "object"
    },
    "InstanceGroupAutoscalingPolicyConfig": {
      "type": "object",
      "description": "Configuration for the size bounds of an instance group, including its proportional size to other groups.",
      "properties": {
        "minInstances": {
          "description": "Optional. Minimum number of instances for this group.Primary workers - Bounds: 2, max_instances. Default: 2. Secondary workers - Bounds: 0, max_instances. Default: 0.",
          "type": "integer",
          "format": "int32"
        },
        "weight": {
          "description": "Optional. Weight for the instance group, which is used to determine the fraction of total workers in the cluster from this instance group. For example, if primary workers have weight 2, and secondary workers have weight 1, the cluster will have approximately 2 primary workers for each secondary worker.The cluster may not reach the specified balance if constrained by min/max bounds or other autoscaling settings. For example, if max_instances for secondary workers is 0, t[...]",
          "format": "int32",
          "type": "integer"
        },
        "maxInstances": {
          "description": "Required. Maximum number of instances for this group. Required for primary workers. Note that by default, clusters will not use secondary workers. Required for secondary workers if the minimum secondary instances is set.Primary workers - Bounds: [min_instances, ). Secondary workers - Bounds: [min_instances, ). Default: 0.",
          "type": "integer",
[...]
