{
  "baseUrl": "https://datamanager.googleapis.com/",
  "canonicalName": "Data Manager",
  "mtlsRootUrl": "https://datamanager.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/datamanager": {
          "description": "See, edit, create, import, or delete your customer data in Google Ads, Google Marketing Platform (Campaign Manager 360, Search Ads 360, Display & Video 360), and Google Analytics"
        },
        "https://www.googleapis.com/auth/datamanager.partnerlink": {
          "description": "View, create, or delete your partner links in Google Ads, Marketing Platform (Campaign Manager 360, Search Ads 360, Display & Video 360), and Analytics"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "title": "Data Manager API",
  "basePath": "",
  "batchPath": "batch",
  "rootUrl": "https://datamanager.googleapis.com/",
  "discoveryVersion": "v1",
  "name": "datamanager",
  "version": "v1",
  "ownerDomain": "google.com",
  "id": "datamanager:v1",
  "revision": "20260420",
  "protocol": "rest",
  "documentationLink": "https://developers.google.com/data-manager",
  "version_module": true,
  "resources": {
    "requestStatus": {
      "methods": {
        "retrieve": {
          "flatPath": "v1/requestStatus:retrieve",
          "path": "v1/requestStatus:retrieve",
          "id": "datamanager.requestStatus.retrieve",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/datamanager"
          ],
          "description": "Gets the status of a request given request id."
        }
      }
    },
    "events": {
      "methods": {
        "ingest": {
          "flatPath": "v1/events:ingest",
          "path": "v1/events:ingest",
          "id": "datamanager.events.ingest",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/datamanager"
          ],
          "description": "Uploads a list of Event resources from the provided Destination."
        }
      }
    },
    "accountTypes": {
      "resources": {
        "accounts": {
          "resources": {
            "userLists": {
              "methods": {
                "create": {
                  "id": "datamanager.accountTypes.accounts.userLists.create",
                  "path": "v1/{+parent}/userLists",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userLists",
                  "description": "Creates a UserList. Authorization Headers: This method supports the following optional headers to define how the API authorizes access for the request: * `login-account`: (Optional) The resource name of the account where the Google Account of the credentials is a user. If not set, defaults to the account of the request. Format: `accountTypes/{loginAccountType}/accounts/{loginAccountId}` * `linked-account`: (Optional) The resource name of the account with an esta[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "httpMethod": "POST"
                },
                "get": {
                  "id": "datamanager.accountTypes.accounts.userLists.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userLists/{userListsId}",
                  "description": "Gets a UserList. Authorization Headers: This method supports the following optional headers to define how the API authorizes access for the request: * `login-account`: (Optional) The resource name of the account where the Google Account of the credentials is a user. If not set, defaults to the account of the request. Format: `accountTypes/{loginAccountType}/accounts/{loginAccountId}` * `linked-account`: (Optional) The resource name of the account with an establi[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "httpMethod": "GET"
                },
                "list": {
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userLists",
                  "path": "v1/{+parent}/userLists",
                  "id": "datamanager.accountTypes.accounts.userLists.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "description": "Lists UserLists. Authorization Headers: This method supports the following optional headers to define how the API authorizes access for the request: * `login-account`: (Optional) The resource name of the account where the Google Account of the credentials is a user. If not set, defaults to the account of the request. Format: `accountTypes/{loginAccountType}/accounts/{loginAccountId}` * `linked-account`: (Optional) The resource name of the account with an establi[...]"
                },
                "delete": {
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userLists/{userListsId}",
                  "path": "v1/{+name}",
                  "id": "datamanager.accountTypes.accounts.userLists.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "description": "Deletes a UserList. Authorization Headers: This method supports the following optional headers to define how the API authorizes access for the request: * `login-account`: (Optional) The resource name of the account where the Google Account of the credentials is a user. If not set, defaults to the account of the request. Format: `accountTypes/{loginAccountType}/accounts/{loginAccountId}` * `linked-account`: (Optional) The resource name of the account with an esta[...]"
                },
                "patch": {
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userLists/{userListsId}",
                  "path": "v1/{+name}",
                  "id": "datamanager.accountTypes.accounts.userLists.patch",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "description": "Updates a UserList. Authorization Headers: This method supports the following optional headers to define how the API authorizes access for the request: * `login-account`: (Optional) The resource name of the account where the Google Account of the credentials is a user. If not set, defaults to the account of the request. Format: `accountTypes/{loginAccountType}/accounts/{loginAccountId}` * `linked-account`: (Optional) The resource name of the account with an esta[...]"
                }
              }
            },
            "userListDirectLicenses": {
              "methods": {
                "patch": {
                  "id": "datamanager.accountTypes.accounts.userListDirectLicenses.patch",
                  "path": "v1/{+name}",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListDirectLicenses/{userListDirectLicensesId}",
                  "description": "Updates a user list direct license. This feature is only available to data partners.",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "httpMethod": "PATCH"
                },
                "get": {
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListDirectLicenses/{userListDirectLicensesId}",
                  "path": "v1/{+name}",
                  "id": "datamanager.accountTypes.accounts.userListDirectLicenses.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "description": "Retrieves a user list direct license. This feature is only available to data partners."
                },
                "list": {
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListDirectLicenses",
                  "path": "v1/{+parent}/userListDirectLicenses",
                  "id": "datamanager.accountTypes.accounts.userListDirectLicenses.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "description": "Lists all user list direct licenses owned by the parent account. This feature is only available to data partners."
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "description": "Creates a user list direct license. This feature is only available to data partners.",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListDirectLicenses",
                  "path": "v1/{+parent}/userListDirectLicenses",
                  "id": "datamanager.accountTypes.accounts.userListDirectLicenses.create"
                }
              }
            },
            "userListGlobalLicenses": {
              "methods": {
                "create": {
                  "httpMethod": "POST",
                  "description": "Creates a user list global license. This feature is only available to data partners.",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "path": "v1/{+parent}/userListGlobalLicenses",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListGlobalLicenses",
                  "id": "datamanager.accountTypes.accounts.userListGlobalLicenses.create"
                },
                "get": {
                  "description": "Retrieves a user list global license. This feature is only available to data partners.",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "httpMethod": "GET",
                  "id": "datamanager.accountTypes.accounts.userListGlobalLicenses.get",
                  "path": "v1/{+name}",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListGlobalLicenses/{userListGlobalLicensesId}"
                },
                "list": {
                  "description": "Lists all user list global licenses owned by the parent account. This feature is only available to data partners.",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "httpMethod": "GET",
                  "id": "datamanager.accountTypes.accounts.userListGlobalLicenses.list",
                  "path": "v1/{+parent}/userListGlobalLicenses",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListGlobalLicenses"
                },
                "patch": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListGlobalLicenses/{userListGlobalLicensesId}",
                  "id": "datamanager.accountTypes.accounts.userListGlobalLicenses.patch",
                  "httpMethod": "PATCH",
                  "description": "Updates a user list global license. This feature is only available to data partners.",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ]
                }
              },
              "resources": {
                "userListGlobalLicenseCustomerInfos": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/datamanager"
                      ],
                      "description": "Lists all customer info for a user list global license. This feature is only available to data partners.",
                      "httpMethod": "GET",
                      "id": "datamanager.accountTypes.accounts.userListGlobalLicenses.userListGlobalLicenseCustomerInfos.list",
                      "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/userListGlobalLicenses/{userListGlobalLicensesId}/userListGlobalLicenseCustomerInfos",
                      "path": "v1/{+parent}/userListGlobalLicenseCustomerInfos"
                    }
                  }
                }
              }
            },
            "partnerLinks": {
              "methods": {
                "create": {
                  "path": "v1/{+parent}/partnerLinks",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/partnerLinks",
                  "id": "datamanager.accountTypes.accounts.partnerLinks.create",
                  "httpMethod": "POST",
                  "description": "Creates a partner link for the given account. Authorization Headers: This method supports the following optional headers to define how the API authorizes access for the request: * `login-account`: (Optional) The resource name of the account where the Google Account of the credentials is a user. If not set, defaults to the account of the request. Format: `accountTypes/{loginAccountType}/accounts/{loginAccountId}`",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager",
                    "https://www.googleapis.com/auth/datamanager.partnerlink"
                  ]
                },
                "delete": {
                  "id": "datamanager.accountTypes.accounts.partnerLinks.delete",
                  "path": "v1/{+name}",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/partnerLinks/{partnerLinksId}",
                  "description": "Deletes a partner link for the given account. Authorization Headers: This method supports the following optional headers to define how the API authorizes access for the request: * `login-account`: (Optional) The resource name of the account where the Google Account of the credentials is a user. If not set, defaults to the account of the request. Format: `accountTypes/{loginAccountType}/accounts/{loginAccountId}`",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager",
                    "https://www.googleapis.com/auth/datamanager.partnerlink"
                  ],
                  "httpMethod": "DELETE"
                },
                "search": {
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/partnerLinks:search",
                  "path": "v1/{+parent}/partnerLinks:search",
                  "id": "datamanager.accountTypes.accounts.partnerLinks.search",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager",
                    "https://www.googleapis.com/auth/datamanager.partnerlink"
                  ],
                  "description": "Searches for all partner links to and from a given account. Authorization Headers: This method supports the following optional headers to define how the API authorizes access for the request: * `login-account`: (Optional) The resource name of the account where the Google Account of the credentials is a user. If not set, defaults to the account of the request. Format: `accountTypes/{loginAccountType}/accounts/{loginAccountId}`"
                }
              }
            },
            "insights": {
              "methods": {
                "retrieve": {
                  "description": "Retrieves marketing data insights for a given user list. This feature is only available to data partners. Authorization Headers: This method supports the following optional headers to define how the API authorizes access for the request: * `login-account`: (Optional) The resource name of the account where the Google Account of the credentials is a user. If not set, defaults to the account of the request. Format: `accountTypes/{loginAccountType}/accounts/{loginAc[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/datamanager"
                  ],
                  "httpMethod": "POST",
                  "id": "datamanager.accountTypes.accounts.insights.retrieve",
                  "path": "v1/{+parent}/insights:retrieve",
                  "flatPath": "v1/accountTypes/{accountTypesId}/accounts/{accountsId}/insights:retrieve"
                }
              }
            }
          }
        }
      }
    },
    "audienceMembers": {
      "methods": {
        "ingest": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/datamanager"
          ],
          "description": "Uploads a list of AudienceMember resources to the provided Destination.",
          "flatPath": "v1/audienceMembers:ingest",
          "path": "v1/audienceMembers:ingest",
          "id": "datamanager.audienceMembers.ingest"
        },
        "remove": {
          "scopes": [
            "https://www.googleapis.com/auth/datamanager"
          ],
          "description": "Removes a list of AudienceMember resources from the provided Destination.",
          "httpMethod": "POST",
          "id": "datamanager.audienceMembers.remove",
          "flatPath": "v1/audienceMembers:remove",
          "path": "v1/audienceMembers:remove"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "servicePath": "",
  "description": "A unified ingestion API for data partners, agencies and advertisers to connect first-party data across Google advertising products.",
  "ownerName": "Google"
}