{
  "version_module": true,
  "description": "A unified, intelligent governance solution for data and AI assets.",
  "discoveryVersion": "v1",
  "rootUrl": "https://dataplex.googleapis.com/",
  "ownerName": "Google",
  "canonicalName": "Cloud Dataplex",
  "batchPath": "batch",
  "title": "Cloud Dataplex API",
  "version": "v1",
  "mtlsRootUrl": "https://dataplex.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dataplex.read-write": {
          "description": "See, edit, configure, and delete your Google Cloud Dataplex data and see the email address for your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/dataplex.readonly": {
          "description": "See your Google Cloud Dataplex data and the email address of your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform.read-only": {
          "description": "View your data across Google Cloud services and see the email address of your Google Account"
        }
      }
    }
  },
  "name": "dataplex",
  "protocol": "rest",
  "resources": {
    "projects": {
      "resources": {
        "locations": {
          "methods": {
            "modifyEntry": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/dataplex.read-write"
              ],
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:modifyEntry",
              "description": "Modifies an entry using the permission on the source system.",
              "id": "dataplex.projects.locations.modifyEntry",
              "path": "v1/{+name}:modifyEntry",
              "httpMethod": "POST"
            },
            "searchEntries": {
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:searchEntries",
              "description": "Searches for Entries matching the given query and scope.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only",
                "https://www.googleapis.com/auth/dataplex.read-write",
                "https://www.googleapis.com/auth/dataplex.readonly"
              ],
              "httpMethod": "POST",
              "path": "v1/{+name}:searchEntries",
              "id": "dataplex.projects.locations.searchEntries"
            },
            "lookupContext": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only",
                "https://www.googleapis.com/auth/dataplex.read-write",
                "https://www.googleapis.com/auth/dataplex.readonly"
              ],
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:lookupContext",
              "description": "Looks up LLM Context for the specified resources.",
              "id": "dataplex.projects.locations.lookupContext",
              "httpMethod": "POST",
              "path": "v1/{+name}:lookupContext"
            },
            "get": {
              "id": "dataplex.projects.locations.get",
              "path": "v1/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/dataplex.read-write"
              ],
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}",
              "description": "Gets information about a location."
            },
            "lookupEntry": {
              "httpMethod": "GET",
              "path": "v1/{+name}:lookupEntry",
              "id": "dataplex.projects.locations.lookupEntry",
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:lookupEntry",
              "description": "Looks up an entry by name using the permission on the source system.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/cloud-platform.read-only",
                "https://www.googleapis.com/auth/dataplex.read-write",
                "https://www.googleapis.com/auth/dataplex.readonly"
              ]
            },
            "list": {
              "id": "dataplex.projects.locations.list",
              "httpMethod": "GET",
              "path": "v1/{+name}/locations",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/dataplex.read-write"
              ],
              "flatPath": "v1/projects/{projectsId}/locations",
              "description": "Lists information about the supported locations for this service.This method lists locations based on the resource scope provided in the ListLocationsRequest.name field: Global locations: If name is empty, the method lists the public locations available to all projects. Project-specific locations: If name follows the format projects/{project}, the method lists locations visible to that specific project. This includes public, private, or other project-specific locati[...]"
            },
            "lookupEntryLinks": {
              "path": "v1/{+name}:lookupEntryLinks",
              "httpMethod": "GET",
              "id": "dataplex.projects.locations.lookupEntryLinks",
              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}:lookupEntryLinks",
              "description": "Looks up Entry Links referencing the specified Entry.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/dataplex.read-write"
              ]
            }
          },
          "resources": {
            "dataScans": {
              "methods": {
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.dataScans.getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.dataScans.testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "httpMethod": "POST"
                },
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataplex.projects.locations.dataScans.setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}",
                  "description": "Gets a DataScan resource.",
                  "id": "dataplex.projects.locations.dataScans.get",
                  "httpMethod": "GET",
                  "path": "v1/{+name}"
                },
                "run": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:run",
                  "description": "Runs an on-demand execution of a DataScan",
                  "id": "dataplex.projects.locations.dataScans.run",
                  "path": "v1/{+name}:run",
                  "httpMethod": "POST"
                },
                "generateDataQualityRules": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}:generateDataQualityRules",
                  "description": "Generates recommended data quality rules based on the results of a data profiling scan.Use the recommendations to build rules for a data quality scan.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}:generateDataQualityRules",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.dataScans.generateDataQualityRules"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}",
                  "description": "Updates a DataScan resource.",
                  "id": "dataplex.projects.locations.dataScans.patch",
                  "path": "v1/{+name}",
                  "httpMethod": "PATCH"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans",
                  "description": "Creates a DataScan resource.",
                  "id": "dataplex.projects.locations.dataScans.create",
                  "path": "v1/{+parent}/dataScans",
                  "httpMethod": "POST"
                },
                "list": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans",
                  "description": "Lists DataScans.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/dataScans",
                  "id": "dataplex.projects.locations.dataScans.list"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}",
                  "description": "Deletes a DataScan resource.",
                  "id": "dataplex.projects.locations.dataScans.delete",
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE"
                }
              },
              "resources": {
                "jobs": {
                  "methods": {
                    "get": {
                      "httpMethod": "GET",
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.dataScans.jobs.get",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}/jobs/{jobsId}",
                      "description": "Gets a DataScanJob resource.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "generateDataQualityRules": {
                      "id": "dataplex.projects.locations.dataScans.jobs.generateDataQualityRules",
                      "path": "v1/{+name}:generateDataQualityRules",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}/jobs/{jobsId}:generateDataQualityRules",
                      "description": "Generates recommended data quality rules based on the results of a data profiling scan.Use the recommendations to build rules for a data quality scan."
                    },
                    "list": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}/jobs",
                      "description": "Lists DataScanJobs under the given DataScan.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "path": "v1/{+parent}/jobs",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.dataScans.jobs.list"
                    },
                    "cancel": {
                      "id": "dataplex.projects.locations.dataScans.jobs.cancel",
                      "path": "v1/{+name}:cancel",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataScans/{dataScansId}/jobs/{jobsId}:cancel",
                      "description": "Cancels a running/pending DataScan job."
                    }
                  }
                }
              }
            },
            "governanceRules": {
              "methods": {
                "setIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/governanceRules/{governanceRulesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataplex.projects.locations.governanceRules.setIamPolicy"
                },
                "getIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/governanceRules/{governanceRulesId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+resource}:getIamPolicy",
                  "id": "dataplex.projects.locations.governanceRules.getIamPolicy"
                },
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/governanceRules/{governanceRulesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.governanceRules.testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "httpMethod": "POST"
                }
              }
            },
            "dataDomains": {
              "methods": {
                "setIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataDomains/{dataDomainsId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:setIamPolicy",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.dataDomains.setIamPolicy"
                },
                "getIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataDomains/{dataDomainsId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataplex.projects.locations.dataDomains.getIamPolicy",
                  "httpMethod": "GET",
                  "path": "v1/{+resource}:getIamPolicy"
                },
                "testIamPermissions": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataDomains/{dataDomainsId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.dataDomains.testIamPermissions"
                }
              }
            },
            "dataAttributeBindings": {
              "methods": {
                "testIamPermissions": {
                  "path": "v1/{+resource}:testIamPermissions",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.dataAttributeBindings.testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "delete": {
                  "id": "dataplex.projects.locations.dataAttributeBindings.delete",
                  "deprecated": true,
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}",
                  "description": "Deletes a DataAttributeBinding resource. All attributes within the DataAttributeBinding must be deleted before the DataAttributeBinding can be deleted."
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}",
                  "description": "Retrieves a DataAttributeBinding resource.",
                  "id": "dataplex.projects.locations.dataAttributeBindings.get",
                  "deprecated": true,
                  "path": "v1/{+name}",
                  "httpMethod": "GET"
                },
                "setIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:setIamPolicy",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.dataAttributeBindings.setIamPolicy"
                },
                "list": {
                  "id": "dataplex.projects.locations.dataAttributeBindings.list",
                  "deprecated": true,
                  "path": "v1/{+parent}/dataAttributeBindings",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings",
                  "description": "Lists DataAttributeBinding resources in a project and location."
                },
                "create": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings",
                  "description": "Create a DataAttributeBinding resource.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/dataAttributeBindings",
                  "deprecated": true,
                  "id": "dataplex.projects.locations.dataAttributeBindings.create"
                },
                "getIamPolicy": {
                  "httpMethod": "GET",
                  "path": "v1/{+resource}:getIamPolicy",
                  "id": "dataplex.projects.locations.dataAttributeBindings.getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "patch": {
                  "deprecated": true,
                  "id": "dataplex.projects.locations.dataAttributeBindings.patch",
                  "httpMethod": "PATCH",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataAttributeBindings/{dataAttributeBindingsId}",
                  "description": "Updates a DataAttributeBinding resource."
                }
              }
            },
            "entryTypes": {
              "methods": {
                "list": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes",
                  "description": "Lists EntryType resources in a project and location.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "path": "v1/{+parent}/entryTypes",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.entryTypes.list"
                },
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataplex.projects.locations.entryTypes.setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "delete": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}",
                  "description": "Deletes an EntryType.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "DELETE",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.entryTypes.delete"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}",
                  "description": "Gets an EntryType.",
                  "id": "dataplex.projects.locations.entryTypes.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET"
                },
                "testIamPermissions": {
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.entryTypes.testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "patch": {
                  "id": "dataplex.projects.locations.entryTypes.patch",
                  "httpMethod": "PATCH",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}",
                  "description": "Updates an EntryType."
                },
                "getIamPolicy": {
                  "id": "dataplex.projects.locations.entryTypes.getIamPolicy",
                  "httpMethod": "GET",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes/{entryTypesId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                },
                "create": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryTypes",
                  "description": "Creates an EntryType.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+parent}/entryTypes",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.entryTypes.create"
                }
              }
            },
            "dataTaxonomies": {
              "methods": {
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.dataTaxonomies.testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "httpMethod": "POST"
                },
                "delete": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}",
                  "description": "Deletes a DataTaxonomy resource. All attributes within the DataTaxonomy must be deleted before the DataTaxonomy can be deleted.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "id": "dataplex.projects.locations.dataTaxonomies.delete",
                  "deprecated": true
                },
                "get": {
                  "id": "dataplex.projects.locations.dataTaxonomies.get",
                  "deprecated": true,
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}",
                  "description": "Retrieves a DataTaxonomy resource."
                },
                "setIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataplex.projects.locations.dataTaxonomies.setIamPolicy",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies",
                  "description": "Lists DataTaxonomy resources in a project and location.",
                  "id": "dataplex.projects.locations.dataTaxonomies.list",
                  "deprecated": true,
                  "path": "v1/{+parent}/dataTaxonomies",
                  "httpMethod": "GET"
                },
                "create": {
                  "path": "v1/{+parent}/dataTaxonomies",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.dataTaxonomies.create",
                  "deprecated": true,
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies",
                  "description": "Create a DataTaxonomy resource.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "getIamPolicy": {
                  "id": "dataplex.projects.locations.dataTaxonomies.getIamPolicy",
                  "httpMethod": "GET",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                },
                "patch": {
                  "path": "v1/{+name}",
                  "httpMethod": "PATCH",
                  "id": "dataplex.projects.locations.dataTaxonomies.patch",
                  "deprecated": true,
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}",
                  "description": "Updates a DataTaxonomy resource.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              },
              "resources": {
                "attributes": {
                  "methods": {
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes",
                      "description": "Create a DataAttribute resource.",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.create",
                      "deprecated": true,
                      "path": "v1/{+parent}/attributes",
                      "httpMethod": "POST"
                    },
                    "getIamPolicy": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}:getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+resource}:getIamPolicy",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.getIamPolicy"
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}",
                      "description": "Updates a DataAttribute resource.",
                      "deprecated": true,
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.patch",
                      "httpMethod": "PATCH",
                      "path": "v1/{+name}"
                    },
                    "testIamPermissions": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}:testIamPermissions",
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "POST",
                      "path": "v1/{+resource}:testIamPermissions",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.testIamPermissions"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "path": "v1/{+name}",
                      "deprecated": true,
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.delete",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}",
                      "description": "Deletes a Data Attribute resource.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "get": {
                      "deprecated": true,
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.get",
                      "httpMethod": "GET",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}",
                      "description": "Retrieves a Data Attribute resource."
                    },
                    "setIamPolicy": {
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.setIamPolicy",
                      "path": "v1/{+resource}:setIamPolicy",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes/{attributesId}:setIamPolicy",
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                    },
                    "list": {
                      "path": "v1/{+parent}/attributes",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.dataTaxonomies.attributes.list",
                      "deprecated": true,
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataTaxonomies/{dataTaxonomiesId}/attributes",
                      "description": "Lists Data Attribute resources in a DataTaxonomy.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    }
                  }
                }
              }
            },
            "metadataJobs": {
              "methods": {
                "create": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataJobs",
                  "description": "Creates a metadata job. For example, use a metadata job to import metadata from a third-party system into Dataplex Universal Catalog.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/metadataJobs",
                  "id": "dataplex.projects.locations.metadataJobs.create"
                },
                "cancel": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataJobs/{metadataJobsId}:cancel",
                  "description": "Cancels a metadata job.If you cancel a metadata import job that is in progress, the changes in the job might be partially applied. We recommend that you reset the state of the entry groups in your project by running another metadata job that reverts the changes from the canceled job.",
                  "id": "dataplex.projects.locations.metadataJobs.cancel",
                  "path": "v1/{+name}:cancel",
                  "httpMethod": "POST"
                },
                "get": {
                  "id": "dataplex.projects.locations.metadataJobs.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataJobs/{metadataJobsId}",
                  "description": "Gets a metadata job."
                },
                "list": {
                  "path": "v1/{+parent}/metadataJobs",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.metadataJobs.list",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataJobs",
                  "description": "Lists metadata jobs.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            },
            "changeRequests": {
              "methods": {
                "getIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/changeRequests/{changeRequestsId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataplex.projects.locations.changeRequests.getIamPolicy",
                  "httpMethod": "GET",
                  "path": "v1/{+resource}:getIamPolicy"
                },
                "testIamPermissions": {
                  "id": "dataplex.projects.locations.changeRequests.testIamPermissions",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/changeRequests/{changeRequestsId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                },
                "setIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/changeRequests/{changeRequestsId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataplex.projects.locations.changeRequests.setIamPolicy"
                }
              }
            },
            "entryLinkTypes": {
              "methods": {
                "getIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryLinkTypes/{entryLinkTypesId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:getIamPolicy",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.entryLinkTypes.getIamPolicy"
                },
                "testIamPermissions": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryLinkTypes/{entryLinkTypesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.entryLinkTypes.testIamPermissions"
                },
                "setIamPolicy": {
                  "id": "dataplex.projects.locations.entryLinkTypes.setIamPolicy",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryLinkTypes/{entryLinkTypesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                }
              }
            },
            "glossaries": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries",
                  "description": "Creates a new Glossary resource.",
                  "id": "dataplex.projects.locations.glossaries.create",
                  "path": "v1/{+parent}/glossaries",
                  "httpMethod": "POST"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}",
                  "description": "Updates a Glossary resource.",
                  "id": "dataplex.projects.locations.glossaries.patch",
                  "httpMethod": "PATCH",
                  "path": "v1/{+name}"
                },
                "getIamPolicy": {
                  "id": "dataplex.projects.locations.glossaries.getIamPolicy",
                  "httpMethod": "GET",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}",
                  "description": "Deletes a Glossary resource. All the categories and terms within the Glossary must be deleted before the Glossary can be deleted.",
                  "id": "dataplex.projects.locations.glossaries.delete",
                  "httpMethod": "DELETE",
                  "path": "v1/{+name}"
                },
                "get": {
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.glossaries.get",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}",
                  "description": "Gets a Glossary resource.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ]
                },
                "list": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries",
                  "description": "Lists Glossary resources in a project and location.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "path": "v1/{+parent}/glossaries",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.glossaries.list"
                },
                "setIamPolicy": {
                  "id": "dataplex.projects.locations.glossaries.setIamPolicy",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                },
                "testIamPermissions": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.glossaries.testIamPermissions"
                }
              },
              "resources": {
                "categories": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "path": "v1/{+parent}/categories",
                      "id": "dataplex.projects.locations.glossaries.categories.list",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories",
                      "description": "Lists GlossaryCategory resources in a Glossary.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "setIamPolicy": {
                      "httpMethod": "POST",
                      "path": "v1/{+resource}:setIamPolicy",
                      "id": "dataplex.projects.locations.glossaries.categories.setIamPolicy",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}:setIamPolicy",
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "delete": {
                      "id": "dataplex.projects.locations.glossaries.categories.delete",
                      "path": "v1/{+name}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}",
                      "description": "Deletes a GlossaryCategory resource. All the GlossaryCategories and GlossaryTerms nested directly under the specified GlossaryCategory will be moved one level up to the parent in the hierarchy."
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}",
                      "description": "Gets a GlossaryCategory resource.",
                      "id": "dataplex.projects.locations.glossaries.categories.get",
                      "httpMethod": "GET",
                      "path": "v1/{+name}"
                    },
                    "testIamPermissions": {
                      "id": "dataplex.projects.locations.glossaries.categories.testIamPermissions",
                      "path": "v1/{+resource}:testIamPermissions",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}:testIamPermissions",
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                    },
                    "patch": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}",
                      "description": "Updates a GlossaryCategory resource.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "PATCH",
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.glossaries.categories.patch"
                    },
                    "getIamPolicy": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories/{categoriesId}:getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+resource}:getIamPolicy",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.glossaries.categories.getIamPolicy"
                    },
                    "create": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/categories",
                      "description": "Creates a new GlossaryCategory resource.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "POST",
                      "path": "v1/{+parent}/categories",
                      "id": "dataplex.projects.locations.glossaries.categories.create"
                    }
                  }
                },
                "terms": {
                  "methods": {
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}",
                      "description": "Updates a GlossaryTerm resource.",
                      "id": "dataplex.projects.locations.glossaries.terms.patch",
                      "httpMethod": "PATCH",
                      "path": "v1/{+name}"
                    },
                    "getIamPolicy": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}:getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "id": "dataplex.projects.locations.glossaries.terms.getIamPolicy",
                      "path": "v1/{+resource}:getIamPolicy",
                      "httpMethod": "GET"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms",
                      "description": "Creates a new GlossaryTerm resource.",
                      "id": "dataplex.projects.locations.glossaries.terms.create",
                      "httpMethod": "POST",
                      "path": "v1/{+parent}/terms"
                    },
                    "testIamPermissions": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}:testIamPermissions",
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                      "id": "dataplex.projects.locations.glossaries.terms.testIamPermissions",
                      "httpMethod": "POST",
                      "path": "v1/{+resource}:testIamPermissions"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms",
                      "description": "Lists GlossaryTerm resources in a Glossary.",
                      "id": "dataplex.projects.locations.glossaries.terms.list",
                      "path": "v1/{+parent}/terms",
                      "httpMethod": "GET"
                    },
                    "setIamPolicy": {
                      "path": "v1/{+resource}:setIamPolicy",
                      "httpMethod": "POST",
                      "id": "dataplex.projects.locations.glossaries.terms.setIamPolicy",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}:setIamPolicy",
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "delete": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}",
                      "description": "Deletes a GlossaryTerm resource.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "DELETE",
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.glossaries.terms.delete"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/glossaries/{glossariesId}/terms/{termsId}",
                      "description": "Gets a GlossaryTerm resource.",
                      "id": "dataplex.projects.locations.glossaries.terms.get",
                      "httpMethod": "GET",
                      "path": "v1/{+name}"
                    }
                  }
                }
              }
            },
            "lakes": {
              "methods": {
                "getIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataplex.projects.locations.lakes.getIamPolicy",
                  "httpMethod": "GET",
                  "path": "v1/{+resource}:getIamPolicy"
                },
                "patch": {
                  "id": "dataplex.projects.locations.lakes.patch",
                  "path": "v1/{+name}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}",
                  "description": "Updates a lake resource."
                },
                "create": {
                  "path": "v1/{+parent}/lakes",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.lakes.create",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes",
                  "description": "Creates a lake resource.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.lakes.testIamPermissions",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions"
                },
                "setIamPolicy": {
                  "id": "dataplex.projects.locations.lakes.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes",
                  "description": "Lists lake resources in a project and location.",
                  "id": "dataplex.projects.locations.lakes.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/lakes"
                },
                "delete": {
                  "id": "dataplex.projects.locations.lakes.delete",
                  "httpMethod": "DELETE",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}",
                  "description": "Deletes a lake resource. All zones within the lake must be deleted before the lake can be deleted."
                },
                "get": {
                  "id": "dataplex.projects.locations.lakes.get",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}",
                  "description": "Retrieves a lake resource."
                }
              },
              "resources": {
                "zones": {
                  "methods": {
                    "testIamPermissions": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}:testIamPermissions",
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "POST",
                      "path": "v1/{+resource}:testIamPermissions",
                      "id": "dataplex.projects.locations.lakes.zones.testIamPermissions"
                    },
                    "setIamPolicy": {
                      "path": "v1/{+resource}:setIamPolicy",
                      "httpMethod": "POST",
                      "id": "dataplex.projects.locations.lakes.zones.setIamPolicy",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}:setIamPolicy",
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones",
                      "description": "Lists zone resources in a lake.",
                      "id": "dataplex.projects.locations.lakes.zones.list",
                      "path": "v1/{+parent}/zones",
                      "httpMethod": "GET"
                    },
                    "delete": {
                      "id": "dataplex.projects.locations.lakes.zones.delete",
                      "httpMethod": "DELETE",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}",
                      "description": "Deletes a zone resource. All assets within a zone must be deleted before the zone can be deleted."
                    },
                    "get": {
                      "path": "v1/{+name}",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.lakes.zones.get",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}",
                      "description": "Retrieves a zone resource.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "getIamPolicy": {
                      "httpMethod": "GET",
                      "path": "v1/{+resource}:getIamPolicy",
                      "id": "dataplex.projects.locations.lakes.zones.getIamPolicy",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}:getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "patch": {
                      "id": "dataplex.projects.locations.lakes.zones.patch",
                      "path": "v1/{+name}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}",
                      "description": "Updates a zone resource."
                    },
                    "create": {
                      "path": "v1/{+parent}/zones",
                      "httpMethod": "POST",
                      "id": "dataplex.projects.locations.lakes.zones.create",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones",
                      "description": "Creates a zone resource within a lake.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    }
                  },
                  "resources": {
                    "actions": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/actions",
                          "description": "Lists action resources in a zone.",
                          "id": "dataplex.projects.locations.lakes.zones.actions.list",
                          "path": "v1/{+parent}/actions",
                          "httpMethod": "GET"
                        }
                      }
                    },
                    "entities": {
                      "methods": {
                        "create": {
                          "id": "dataplex.projects.locations.lakes.zones.entities.create",
                          "httpMethod": "POST",
                          "path": "v1/{+parent}/entities",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities",
                          "description": "Create a metadata entity."
                        },
                        "update": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}",
                          "description": "Update a metadata entity. Only supports full resource update.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "httpMethod": "PUT",
                          "path": "v1/{+name}",
                          "id": "dataplex.projects.locations.lakes.zones.entities.update"
                        },
                        "delete": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}",
                          "description": "Delete a metadata entity.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "path": "v1/{+name}",
                          "httpMethod": "DELETE",
                          "id": "dataplex.projects.locations.lakes.zones.entities.delete"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}",
                          "description": "Get a metadata entity.",
                          "id": "dataplex.projects.locations.lakes.zones.entities.get",
                          "path": "v1/{+name}",
                          "httpMethod": "GET"
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities",
                          "description": "List metadata entities in a zone.",
                          "id": "dataplex.projects.locations.lakes.zones.entities.list",
                          "httpMethod": "GET",
                          "path": "v1/{+parent}/entities"
                        }
                      },
                      "resources": {
                        "partitions": {
                          "methods": {
                            "create": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/dataplex.read-write"
                              ],
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}/partitions",
                              "description": "Create a metadata partition.",
                              "id": "dataplex.projects.locations.lakes.zones.entities.partitions.create",
                              "path": "v1/{+parent}/partitions",
                              "httpMethod": "POST"
                            },
                            "delete": {
                              "id": "dataplex.projects.locations.lakes.zones.entities.partitions.delete",
                              "path": "v1/{+name}",
                              "httpMethod": "DELETE",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/dataplex.read-write"
                              ],
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}/partitions/{partitionsId}",
                              "description": "Delete a metadata partition."
                            },
                            "get": {
                              "id": "dataplex.projects.locations.lakes.zones.entities.partitions.get",
                              "path": "v1/{+name}",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/dataplex.read-write"
                              ],
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}/partitions/{partitionsId}",
                              "description": "Get a metadata partition of an entity."
                            },
                            "list": {
                              "path": "v1/{+parent}/partitions",
                              "httpMethod": "GET",
                              "id": "dataplex.projects.locations.lakes.zones.entities.partitions.list",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/entities/{entitiesId}/partitions",
                              "description": "List metadata partitions of an entity.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/dataplex.read-write"
                              ]
                            }
                          }
                        }
                      }
                    },
                    "assets": {
                      "methods": {
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}",
                          "description": "Deletes an asset resource. The referenced storage resource is detached (default) or deleted based on the associated Lifecycle policy.",
                          "id": "dataplex.projects.locations.lakes.zones.assets.delete",
                          "httpMethod": "DELETE",
                          "path": "v1/{+name}"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}",
                          "description": "Retrieves an asset resource.",
                          "id": "dataplex.projects.locations.lakes.zones.assets.get",
                          "httpMethod": "GET",
                          "path": "v1/{+name}"
                        },
                        "setIamPolicy": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}:setIamPolicy",
                          "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                          "id": "dataplex.projects.locations.lakes.zones.assets.setIamPolicy",
                          "httpMethod": "POST",
                          "path": "v1/{+resource}:setIamPolicy"
                        },
                        "list": {
                          "httpMethod": "GET",
                          "path": "v1/{+parent}/assets",
                          "id": "dataplex.projects.locations.lakes.zones.assets.list",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets",
                          "description": "Lists asset resources in a zone.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ]
                        },
                        "testIamPermissions": {
                          "path": "v1/{+resource}:testIamPermissions",
                          "httpMethod": "POST",
                          "id": "dataplex.projects.locations.lakes.zones.assets.testIamPermissions",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}:testIamPermissions",
                          "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ]
                        },
                        "create": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets",
                          "description": "Creates an asset resource.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "httpMethod": "POST",
                          "path": "v1/{+parent}/assets",
                          "id": "dataplex.projects.locations.lakes.zones.assets.create"
                        },
                        "getIamPolicy": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}:getIamPolicy",
                          "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                          "id": "dataplex.projects.locations.lakes.zones.assets.getIamPolicy",
                          "httpMethod": "GET",
                          "path": "v1/{+resource}:getIamPolicy"
                        },
                        "patch": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}",
                          "description": "Updates an asset resource.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "path": "v1/{+name}",
                          "httpMethod": "PATCH",
                          "id": "dataplex.projects.locations.lakes.zones.assets.patch"
                        }
                      },
                      "resources": {
                        "actions": {
                          "methods": {
                            "list": {
                              "path": "v1/{+parent}/actions",
                              "httpMethod": "GET",
                              "id": "dataplex.projects.locations.lakes.zones.assets.actions.list",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/zones/{zonesId}/assets/{assetsId}/actions",
                              "description": "Lists action resources in an asset.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/cloud-platform.read-only",
                                "https://www.googleapis.com/auth/dataplex.read-write",
                                "https://www.googleapis.com/auth/dataplex.readonly"
                              ]
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "tasks": {
                  "methods": {
                    "patch": {
                      "id": "dataplex.projects.locations.lakes.tasks.patch",
                      "httpMethod": "PATCH",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}",
                      "description": "Update the task resource."
                    },
                    "create": {
                      "httpMethod": "POST",
                      "path": "v1/{+parent}/tasks",
                      "id": "dataplex.projects.locations.lakes.tasks.create",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks",
                      "description": "Creates a task resource within a lake.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "list": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks",
                      "description": "Lists tasks under the given lake.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "path": "v1/{+parent}/tasks",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.lakes.tasks.list"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}",
                      "description": "Delete the task resource.",
                      "id": "dataplex.projects.locations.lakes.tasks.delete",
                      "httpMethod": "DELETE",
                      "path": "v1/{+name}"
                    },
                    "getIamPolicy": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}:getIamPolicy",
                      "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+resource}:getIamPolicy",
                      "httpMethod": "GET",
                      "id": "dataplex.projects.locations.lakes.tasks.getIamPolicy"
                    },
                    "testIamPermissions": {
                      "id": "dataplex.projects.locations.lakes.tasks.testIamPermissions",
                      "path": "v1/{+resource}:testIamPermissions",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}:testIamPermissions",
                      "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                    },
                    "setIamPolicy": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}:setIamPolicy",
                      "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                      "id": "dataplex.projects.locations.lakes.tasks.setIamPolicy",
                      "httpMethod": "POST",
                      "path": "v1/{+resource}:setIamPolicy"
                    },
                    "get": {
                      "httpMethod": "GET",
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.lakes.tasks.get",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}",
                      "description": "Get task resource.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    },
                    "run": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}:run",
                      "description": "Run an on demand execution of a Task.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "POST",
                      "path": "v1/{+name}:run",
                      "id": "dataplex.projects.locations.lakes.tasks.run"
                    }
                  },
                  "resources": {
                    "jobs": {
                      "methods": {
                        "cancel": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}/jobs/{jobsId}:cancel",
                          "description": "Cancel jobs running for the task resource.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/dataplex.read-write"
                          ],
                          "path": "v1/{+name}:cancel",
                          "httpMethod": "POST",
                          "id": "dataplex.projects.locations.lakes.tasks.jobs.cancel"
                        },
                        "get": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}/jobs/{jobsId}",
                          "description": "Get job resource.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ],
                          "path": "v1/{+name}",
                          "httpMethod": "GET",
                          "id": "dataplex.projects.locations.lakes.tasks.jobs.get"
                        },
                        "list": {
                          "path": "v1/{+parent}/jobs",
                          "httpMethod": "GET",
                          "id": "dataplex.projects.locations.lakes.tasks.jobs.list",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/tasks/{tasksId}/jobs",
                          "description": "Lists Jobs under the given task.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud-platform.read-only",
                            "https://www.googleapis.com/auth/dataplex.read-write",
                            "https://www.googleapis.com/auth/dataplex.readonly"
                          ]
                        }
                      }
                    }
                  }
                },
                "actions": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "path": "v1/{+parent}/actions",
                      "id": "dataplex.projects.locations.lakes.actions.list",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/lakes/{lakesId}/actions",
                      "description": "Lists action resources in a lake.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ]
                    }
                  }
                }
              }
            },
            "operations": {
              "methods": {
                "cancel": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}:cancel",
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it beco[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}:cancel",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.operations.cancel"
                },
                "get": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.operations.get"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "id": "dataplex.projects.locations.operations.delete",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns UNIMPLEMENTED.",
                  "id": "dataplex.projects.locations.operations.list",
                  "httpMethod": "GET",
                  "path": "v1/{+name}/operations"
                }
              }
            },
            "dataProducts": {
              "methods": {
                "testIamPermissions": {
                  "id": "dataplex.projects.locations.dataProducts.testIamPermissions",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                },
                "delete": {
                  "id": "dataplex.projects.locations.dataProducts.delete",
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}",
                  "description": "Deletes a data product. The deletion will fail if the data product is not empty (i.e. contains at least one data asset)."
                },
                "get": {
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.dataProducts.get",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}",
                  "description": "Gets a data product.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ]
                },
                "setIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataplex.projects.locations.dataProducts.setIamPolicy"
                },
                "list": {
                  "id": "dataplex.projects.locations.dataProducts.list",
                  "path": "v1/{+parent}/dataProducts",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts",
                  "description": "Lists data products for a given project."
                },
                "create": {
                  "id": "dataplex.projects.locations.dataProducts.create",
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/dataProducts",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts",
                  "description": "Creates a data product."
                },
                "getIamPolicy": {
                  "id": "dataplex.projects.locations.dataProducts.getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                },
                "patch": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}",
                  "description": "Updates a data product.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "httpMethod": "PATCH",
                  "id": "dataplex.projects.locations.dataProducts.patch"
                }
              },
              "resources": {
                "dataAssets": {
                  "methods": {
                    "patch": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets/{dataAssetsId}",
                      "description": "Updates a data asset.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+name}",
                      "httpMethod": "PATCH",
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.patch"
                    },
                    "create": {
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.create",
                      "httpMethod": "POST",
                      "path": "v1/{+parent}/dataAssets",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets",
                      "description": "Creates a data asset."
                    },
                    "list": {
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.list",
                      "httpMethod": "GET",
                      "path": "v1/{+parent}/dataAssets",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets",
                      "description": "Lists data assets for a given data product."
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets/{dataAssetsId}",
                      "description": "Deletes a data asset.",
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.delete",
                      "path": "v1/{+name}",
                      "httpMethod": "DELETE"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataProducts/{dataProductsId}/dataAssets/{dataAssetsId}",
                      "description": "Gets a data asset.",
                      "id": "dataplex.projects.locations.dataProducts.dataAssets.get",
                      "path": "v1/{+name}",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            },
            "policyIntents": {
              "methods": {
                "getIamPolicy": {
                  "path": "v1/{+resource}:getIamPolicy",
                  "httpMethod": "GET",
                  "id": "dataplex.projects.locations.policyIntents.getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/policyIntents/{policyIntentsId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "testIamPermissions": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/policyIntents/{policyIntentsId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.policyIntents.testIamPermissions"
                },
                "setIamPolicy": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/policyIntents/{policyIntentsId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:setIamPolicy",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.policyIntents.setIamPolicy"
                }
              }
            },
            "entryGroups": {
              "methods": {
                "delete": {
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "id": "dataplex.projects.locations.entryGroups.delete",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}",
                  "description": "Deletes an EntryGroup.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "get": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}",
                  "description": "Gets an EntryGroup.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.entryGroups.get"
                },
                "list": {
                  "id": "dataplex.projects.locations.entryGroups.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/entryGroups",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups",
                  "description": "Lists EntryGroup resources in a project and location."
                },
                "setIamPolicy": {
                  "id": "dataplex.projects.locations.entryGroups.setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                },
                "testIamPermissions": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataplex.projects.locations.entryGroups.testIamPermissions"
                },
                "create": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups",
                  "description": "Creates an EntryGroup.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+parent}/entryGroups",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.entryGroups.create"
                },
                "patch": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}",
                  "description": "Updates an EntryGroup.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "httpMethod": "PATCH",
                  "id": "dataplex.projects.locations.entryGroups.patch"
                },
                "getIamPolicy": {
                  "id": "dataplex.projects.locations.entryGroups.getIamPolicy",
                  "httpMethod": "GET",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                }
              },
              "resources": {
                "entryLinks": {
                  "methods": {
                    "delete": {
                      "path": "v1/{+name}",
                      "httpMethod": "DELETE",
                      "id": "dataplex.projects.locations.entryGroups.entryLinks.delete",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entryLinks/{entryLinksId}",
                      "description": "Deletes an Entry Link.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "get": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entryLinks/{entryLinksId}",
                      "description": "Gets an Entry Link.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "GET",
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.entryGroups.entryLinks.get"
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.entryGroups.entryLinks.patch",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entryLinks/{entryLinksId}",
                      "description": "Updates an Entry Link.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ]
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entryLinks",
                      "description": "Creates an Entry Link.",
                      "id": "dataplex.projects.locations.entryGroups.entryLinks.create",
                      "httpMethod": "POST",
                      "path": "v1/{+parent}/entryLinks"
                    }
                  }
                },
                "entries": {
                  "methods": {
                    "create": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries",
                      "description": "Creates an Entry.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+parent}/entries",
                      "httpMethod": "POST",
                      "id": "dataplex.projects.locations.entryGroups.entries.create"
                    },
                    "patch": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries/{entriesId}",
                      "description": "Updates an Entry.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "path": "v1/{+name}",
                      "httpMethod": "PATCH",
                      "id": "dataplex.projects.locations.entryGroups.entries.patch"
                    },
                    "delete": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries/{entriesId}",
                      "description": "Deletes an Entry.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataplex.read-write"
                      ],
                      "httpMethod": "DELETE",
                      "path": "v1/{+name}",
                      "id": "dataplex.projects.locations.entryGroups.entries.delete"
                    },
                    "get": {
                      "id": "dataplex.projects.locations.entryGroups.entries.get",
                      "path": "v1/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries/{entriesId}",
                      "description": "Gets an Entry."
                    },
                    "list": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/entryGroups/{entryGroupsId}/entries",
                      "description": "Lists Entries within an EntryGroup.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud-platform.read-only",
                        "https://www.googleapis.com/auth/dataplex.read-write",
                        "https://www.googleapis.com/auth/dataplex.readonly"
                      ],
                      "httpMethod": "GET",
                      "path": "v1/{+parent}/entries",
                      "id": "dataplex.projects.locations.entryGroups.entries.list"
                    }
                  }
                }
              }
            },
            "aspectTypes": {
              "methods": {
                "create": {
                  "path": "v1/{+parent}/aspectTypes",
                  "httpMethod": "POST",
                  "id": "dataplex.projects.locations.aspectTypes.create",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes",
                  "description": "Creates an AspectType.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.aspectTypes.patch",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}",
                  "description": "Updates an AspectType.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "getIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataplex.projects.locations.aspectTypes.getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "httpMethod": "GET"
                },
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataplex.projects.locations.aspectTypes.testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions",
                  "httpMethod": "POST"
                },
                "delete": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}",
                  "description": "Deletes an AspectType.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "id": "dataplex.projects.locations.aspectTypes.delete"
                },
                "get": {
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.aspectTypes.get",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}",
                  "description": "Gets an AspectType.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ]
                },
                "list": {
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/aspectTypes",
                  "id": "dataplex.projects.locations.aspectTypes.list",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes",
                  "description": "Lists AspectType resources in a project and location.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/cloud-platform.read-only",
                    "https://www.googleapis.com/auth/dataplex.read-write",
                    "https://www.googleapis.com/auth/dataplex.readonly"
                  ]
                },
                "setIamPolicy": {
                  "id": "dataplex.projects.locations.aspectTypes.setIamPolicy",
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/aspectTypes/{aspectTypesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                }
              }
            },
            "metadataFeeds": {
              "methods": {
                "patch": {
                  "path": "v1/{+name}",
                  "httpMethod": "PATCH",
                  "id": "dataplex.projects.locations.metadataFeeds.patch",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds/{metadataFeedsId}",
                  "description": "Updates a MetadataFeed.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "create": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds",
                  "description": "Creates a MetadataFeed.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/metadataFeeds",
                  "id": "dataplex.projects.locations.metadataFeeds.create"
                },
                "list": {
                  "id": "dataplex.projects.locations.metadataFeeds.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/metadataFeeds",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds",
                  "description": "Retrieve a list of MetadataFeeds."
                },
                "get": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds/{metadataFeedsId}",
                  "description": "Gets a MetadataFeed.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.metadataFeeds.get"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "path": "v1/{+name}",
                  "id": "dataplex.projects.locations.metadataFeeds.delete",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/metadataFeeds/{metadataFeedsId}",
                  "description": "Deletes a MetadataFeed.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            }
          }
        }
      }
    },
    "organizations": {
      "resources": {
        "locations": {
          "resources": {
            "encryptionConfigs": {
              "methods": {
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}",
                  "description": "Update an EncryptionConfig.",
                  "id": "dataplex.organizations.locations.encryptionConfigs.patch",
                  "path": "v1/{+name}",
                  "httpMethod": "PATCH"
                },
                "getIamPolicy": {
                  "id": "dataplex.organizations.locations.encryptionConfigs.getIamPolicy",
                  "httpMethod": "GET",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs",
                  "description": "Create an EncryptionConfig.",
                  "id": "dataplex.organizations.locations.encryptionConfigs.create",
                  "path": "v1/{+parent}/encryptionConfigs",
                  "httpMethod": "POST"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs",
                  "description": "List EncryptionConfigs.",
                  "id": "dataplex.organizations.locations.encryptionConfigs.list",
                  "httpMethod": "GET",
                  "path": "v1/{+parent}/encryptionConfigs"
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "httpMethod": "POST",
                  "id": "dataplex.organizations.locations.encryptionConfigs.setIamPolicy",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "delete": {
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}",
                  "description": "Delete an EncryptionConfig.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "id": "dataplex.organizations.locations.encryptionConfigs.delete"
                },
                "get": {
                  "id": "dataplex.organizations.locations.encryptionConfigs.get",
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}",
                  "description": "Get an EncryptionConfig."
                },
                "testIamPermissions": {
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/encryptionConfigs/{encryptionConfigsId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "httpMethod": "POST",
                  "id": "dataplex.organizations.locations.encryptionConfigs.testIamPermissions"
                }
              }
            },
            "operations": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "id": "dataplex.organizations.locations.operations.get",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/operations/{operationsId}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/operations/{operationsId}",
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED.",
                  "id": "dataplex.organizations.locations.operations.delete",
                  "httpMethod": "DELETE",
                  "path": "v1/{+name}"
                },
                "list": {
                  "id": "dataplex.organizations.locations.operations.list",
                  "httpMethod": "GET",
                  "path": "v1/{+name}/operations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ],
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/operations",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns UNIMPLEMENTED."
                },
                "cancel": {
                  "httpMethod": "POST",
                  "path": "v1/{+name}:cancel",
                  "id": "dataplex.organizations.locations.operations.cancel",
                  "flatPath": "v1/organizations/{organizationsId}/locations/{locationsId}/operations/{operationsId}:cancel",
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it beco[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataplex.read-write"
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "baseUrl": "https://dataplex.googleapis.com/",
  "documentationLink": "https://cloud.google.com/dataplex/docs",
  "id": "dataplex:v1",
  "servicePath": "",
  "fullyEncodeReservedExpansion": true,
  "ownerDomain": "google.com",
  "kind": "discovery#restDescription",
  "basePath": "",
  "revision": "20260406"
}