{
  "ownerName": "Google",
  "id": "dataproc:v1",
  "protocol": "rest",
  "documentationLink": "https://cloud.google.com/dataproc/",
  "servicePath": "",
  "version": "v1",
  "ownerDomain": "google.com",
  "canonicalName": "Dataproc",
  "discoveryVersion": "v1",
  "basePath": "",
  "baseUrl": "https://dataproc.googleapis.com/",
  "kind": "discovery#restDescription",
  "resources": {
    "projects": {
      "resources": {
        "regions": {
          "resources": {
            "operations": {
              "methods": {
                "list": {
                  "id": "dataproc.projects.regions.operations.list",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns UNIMPLEMENTED.",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ]
                },
                "delete": {
                  "path": "v1/{+name}",
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED.",
                  "id": "dataproc.projects.regions.operations.delete",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "DELETE"
                },
                "getIamPolicy": {
                  "id": "dataproc.projects.regions.operations.getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "path": "v1/{+resource}:getIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataproc.projects.regions.operations.setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                },
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "id": "dataproc.projects.regions.operations.testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning."
                },
                "cancel": {
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it beco[...]",
                  "id": "dataproc.projects.regions.operations.cancel",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}:cancel",
                  "path": "v1/{+name}:cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST"
                },
                "get": {
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "id": "dataproc.projects.regions.operations.get",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/operations/{operationsId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "httpMethod": "GET"
                }
              }
            },
            "workflowTemplates": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+parent}/workflowTemplates",
                  "id": "dataproc.projects.regions.workflowTemplates.create",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates",
                  "description": "Creates new workflow template."
                },
                "list": {
                  "path": "v1/{+parent}/workflowTemplates",
                  "id": "dataproc.projects.regions.workflowTemplates.list",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates",
                  "description": "Lists workflows that match the specified filter in the request.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "httpMethod": "GET"
                },
                "instantiate": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.regions.workflowTemplates.instantiate",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}:instantiate",
                  "description": "Instantiates a template and begins execution.The returned Operation can be used to track execution of workflow by polling operations.get. The Operation will complete when entire workflow is finished.The running workflow can be aborted via operations.cancel. This will cause any inflight jobs to be cancelled and workflow-owned clusters to be deleted.The Operation.metadata will be WorkflowMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.d[...]",
                  "path": "v1/{+name}:instantiate"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "id": "dataproc.projects.regions.workflowTemplates.delete",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}",
                  "description": "Deletes a workflow template. It does not cancel in-progress workflows.",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "setIamPolicy": {
                  "id": "dataproc.projects.regions.workflowTemplates.setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "path": "v1/{+resource}:setIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "testIamPermissions": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataproc.projects.regions.workflowTemplates.testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}:testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions"
                },
                "get": {
                  "id": "dataproc.projects.regions.workflowTemplates.get",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}",
                  "description": "Retrieves the latest workflow template.Can retrieve previously instantiated template by specifying optional version parameter.",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ]
                },
                "update": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "PUT",
                  "description": "Updates (replaces) workflow template. The updated template must contain version that matches the current server version.",
                  "id": "dataproc.projects.regions.workflowTemplates.update",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}",
                  "path": "v1/{+name}"
                },
                "getIamPolicy": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.regions.workflowTemplates.getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates/{workflowTemplatesId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "path": "v1/{+resource}:getIamPolicy"
                },
                "instantiateInline": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.regions.workflowTemplates.instantiateInline",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/workflowTemplates:instantiateInline",
                  "description": "Instantiates a template and begins execution.This method is equivalent to executing the sequence CreateWorkflowTemplate, InstantiateWorkflowTemplate, DeleteWorkflowTemplate.The returned Operation can be used to track execution of workflow by polling operations.get. The Operation will complete when entire workflow is finished.The running workflow can be aborted via operations.cancel. This will cause any inflight jobs to be cancelled and workflow-owned clusters to[...]",
                  "path": "v1/{+parent}/workflowTemplates:instantiateInline"
                }
              }
            },
            "jobs": {
              "methods": {
                "delete": {
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Deletes the job from the project. If the job is active, the delete fails, and the response returns FAILED_PRECONDITION.",
                  "id": "dataproc.projects.regions.jobs.delete",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "path": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}"
                },
                "patch": {
                  "id": "dataproc.projects.regions.jobs.patch",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "description": "Updates a job in a project.",
                  "path": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "list": {
                  "description": "Lists regions/{region}/jobs in a project.",
                  "id": "dataproc.projects.regions.jobs.list",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs",
                  "path": "v1/projects/{projectId}/regions/{region}/jobs",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "httpMethod": "GET"
                },
                "submit": {
                  "path": "v1/projects/{projectId}/regions/{region}/jobs:submit",
                  "id": "dataproc.projects.regions.jobs.submit",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs:submit",
                  "description": "Submits a job to a cluster.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST"
                },
                "submitAsOperation": {
                  "path": "v1/projects/{projectId}/regions/{region}/jobs:submitAsOperation",
                  "id": "dataproc.projects.regions.jobs.submitAsOperation",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs:submitAsOperation",
                  "description": "Submits job to a cluster.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "getIamPolicy": {
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataproc.projects.regions.jobs.getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/jobs/{jobsId}:getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "get": {
                  "description": "Gets the resource representation for a job in a project.",
                  "id": "dataproc.projects.regions.jobs.get",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "path": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ]
                },
                "cancel": {
                  "description": "Starts a job cancellation request. To access the job resource after cancellation, call regions/{region}/jobs.list (https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.jobs/list) or regions/{region}/jobs.get (https://cloud.google.com/dataproc/docs/reference/rest/v1/projects.regions.jobs/get).",
                  "id": "dataproc.projects.regions.jobs.cancel",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}:cancel",
                  "path": "v1/projects/{projectId}/regions/{region}/jobs/{jobId}:cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST"
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataproc.projects.regions.jobs.setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/jobs/{jobsId}:setIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST"
                },
                "testIamPermissions": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataproc.projects.regions.jobs.testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/jobs/{jobsId}:testIamPermissions",
                  "path": "v1/{+resource}:testIamPermissions"
                }
              }
            },
            "autoscalingPolicies": {
              "methods": {
                "update": {
                  "description": "Updates (replaces) autoscaling policy.Disabled check for update_mask, because all updates will be full replacements.",
                  "id": "dataproc.projects.regions.autoscalingPolicies.update",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}",
                  "path": "v1/{+name}",
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "delete": {
                  "id": "dataproc.projects.regions.autoscalingPolicies.delete",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}",
                  "description": "Deletes an autoscaling policy. It is an error to delete an autoscaling policy that is in use by one or more clusters.",
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "getIamPolicy": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+resource}:getIamPolicy",
                  "id": "dataproc.projects.regions.autoscalingPolicies.getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set."
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists autoscaling policies in the project.",
                  "id": "dataproc.projects.regions.autoscalingPolicies.list",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies",
                  "path": "v1/{+parent}/autoscalingPolicies"
                },
                "get": {
                  "description": "Retrieves autoscaling policy.",
                  "id": "dataproc.projects.regions.autoscalingPolicies.get",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "GET"
                },
                "create": {
                  "description": "Creates new autoscaling policy.",
                  "id": "dataproc.projects.regions.autoscalingPolicies.create",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies",
                  "path": "v1/{+parent}/autoscalingPolicies",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "setIamPolicy": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataproc.projects.regions.autoscalingPolicies.setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors."
                },
                "testIamPermissions": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataproc.projects.regions.autoscalingPolicies.testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/autoscalingPolicies/{autoscalingPoliciesId}:testIamPermissions"
                }
              }
            },
            "clusters": {
              "methods": {
                "patch": {
                  "id": "dataproc.projects.regions.clusters.patch",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "description": "Updates a cluster in a project. The returned Operation.metadata will be ClusterOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#clusteroperationmetadata). The cluster must be in a RUNNING state or an error is returned.",
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "PATCH"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Deletes a cluster in a project. The returned Operation.metadata will be ClusterOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#clusteroperationmetadata).",
                  "id": "dataproc.projects.regions.clusters.delete",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}"
                },
                "start": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Starts a cluster in a project.",
                  "id": "dataproc.projects.regions.clusters.start",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:start",
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:start"
                },
                "stop": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:stop",
                  "id": "dataproc.projects.regions.clusters.stop",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:stop",
                  "description": "Stops a cluster in a project."
                },
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "id": "dataproc.projects.regions.clusters.setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}:setIamPolicy",
                  "path": "v1/{+resource}:setIamPolicy"
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}",
                  "description": "Gets the resource representation for a cluster in a project.",
                  "id": "dataproc.projects.regions.clusters.get",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}"
                },
                "injectCredentials": {
                  "path": "v1/{+project}/{+region}/{+cluster}:injectCredentials",
                  "description": "Inject encrypted credentials into all of the VMs in a cluster.The target cluster must be a personal auth cluster assigned to the user who is issuing the RPC.",
                  "id": "dataproc.projects.regions.clusters.injectCredentials",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}:injectCredentials",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "list": {
                  "path": "v1/projects/{projectId}/regions/{region}/clusters",
                  "id": "dataproc.projects.regions.clusters.list",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters",
                  "description": "Lists all regions/{region}/clusters in a project alphabetically.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "httpMethod": "GET"
                },
                "diagnose": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "description": "Gets cluster diagnostic information. The returned Operation.metadata will be ClusterOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#clusteroperationmetadata). After the operation completes, Operation.response contains DiagnoseClusterResults (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#diagnoseclusterresults).",
                  "id": "dataproc.projects.regions.clusters.diagnose",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:diagnose",
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:diagnose"
                },
                "create": {
                  "path": "v1/projects/{projectId}/regions/{region}/clusters",
                  "description": "Creates a cluster in a project. The returned Operation.metadata will be ClusterOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#clusteroperationmetadata).",
                  "id": "dataproc.projects.regions.clusters.create",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST"
                },
                "repair": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:repair",
                  "description": "Repairs a cluster.",
                  "id": "dataproc.projects.regions.clusters.repair",
                  "flatPath": "v1/projects/{projectId}/regions/{region}/clusters/{clusterName}:repair"
                },
                "getIamPolicy": {
                  "id": "dataproc.projects.regions.clusters.getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}:getIamPolicy",
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "path": "v1/{+resource}:getIamPolicy",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "testIamPermissions": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+resource}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataproc.projects.regions.clusters.testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}:testIamPermissions"
                }
              },
              "resources": {
                "nodeGroups": {
                  "methods": {
                    "repair": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "httpMethod": "POST",
                      "id": "dataproc.projects.regions.clusters.nodeGroups.repair",
                      "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}/nodeGroups/{nodeGroupsId}:repair",
                      "description": "Repair nodes in a node group.",
                      "path": "v1/{+name}:repair"
                    },
                    "resize": {
                      "description": "Resizes a node group in a cluster. The returned Operation.metadata is NodeGroupOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#nodegroupoperationmetadata).",
                      "id": "dataproc.projects.regions.clusters.nodeGroups.resize",
                      "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}/nodeGroups/{nodeGroupsId}:resize",
                      "path": "v1/{+name}:resize",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ]
                    },
                    "get": {
                      "id": "dataproc.projects.regions.clusters.nodeGroups.get",
                      "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}/nodeGroups/{nodeGroupsId}",
                      "description": "Gets the resource representation for a node group in a cluster.",
                      "path": "v1/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "httpMethod": "POST",
                      "id": "dataproc.projects.regions.clusters.nodeGroups.create",
                      "flatPath": "v1/projects/{projectsId}/regions/{regionsId}/clusters/{clustersId}/nodeGroups",
                      "description": "Creates a node group in a cluster. The returned Operation.metadata is NodeGroupOperationMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#nodegroupoperationmetadata).",
                      "path": "v1/{+parent}/nodeGroups"
                    }
                  }
                }
              }
            }
          }
        },
        "locations": {
          "resources": {
            "batches": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "description": "Gets the batch workload resource representation.",
                  "id": "dataproc.projects.locations.batches.get",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}"
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.locations.batches.create",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches",
                  "description": "Creates a batch workload that executes asynchronously.",
                  "path": "v1/{+parent}/batches"
                },
                "analyze": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.locations.batches.analyze",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}:analyze",
                  "description": "Analyze a Batch for possible recommendations and insights.",
                  "path": "v1/{+name}:analyze"
                },
                "delete": {
                  "description": "Deletes the batch workload resource. If the batch is not in a CANCELLED, SUCCEEDED or FAILED State, the delete operation fails and the response returns FAILED_PRECONDITION.",
                  "id": "dataproc.projects.locations.batches.delete",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}",
                  "path": "v1/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "path": "v1/{+parent}/batches",
                  "id": "dataproc.projects.locations.batches.list",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches",
                  "description": "Lists batch workloads."
                }
              },
              "resources": {
                "sparkApplications": {
                  "methods": {
                    "searchStages": {
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchStages",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchStages",
                      "description": "Obtain data corresponding to stages for a Spark Application.",
                      "path": "v1/{+name}:searchStages",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET"
                    },
                    "summarizeJobs": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "path": "v1/{+name}:summarizeJobs",
                      "description": "Obtain summary of Jobs for a Spark Application",
                      "id": "dataproc.projects.locations.batches.sparkApplications.summarizeJobs",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:summarizeJobs"
                    },
                    "accessStageRddGraph": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "path": "v1/{+name}:accessStageRddGraph",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessStageRddGraph",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessStageRddGraph",
                      "description": "Obtain RDD operation graph for a Spark Application Stage. Limits the number of clusters returned as part of the graph to 10000."
                    },
                    "access": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "path": "v1/{+name}:access",
                      "id": "dataproc.projects.locations.batches.sparkApplications.access",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:access",
                      "description": "Obtain high level information corresponding to a single Spark Application."
                    },
                    "summarizeStageAttemptTasks": {
                      "path": "v1/{+name}:summarizeStageAttemptTasks",
                      "description": "Obtain summary of Tasks for a Spark Application Stage Attempt",
                      "id": "dataproc.projects.locations.batches.sparkApplications.summarizeStageAttemptTasks",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:summarizeStageAttemptTasks",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET"
                    },
                    "accessSqlPlan": {
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessSqlPlan",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessSqlPlan",
                      "description": "Obtain Spark Plan Graph for a Spark Application SQL execution. Limits the number of clusters returned as part of the graph to 10000.",
                      "path": "v1/{+name}:accessSqlPlan",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET"
                    },
                    "searchStageAttempts": {
                      "description": "Obtain data corresponding to a spark stage attempts for a Spark Application.",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchStageAttempts",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchStageAttempts",
                      "path": "v1/{+name}:searchStageAttempts",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "accessStageAttempt": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "path": "v1/{+name}:accessStageAttempt",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessStageAttempt",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessStageAttempt",
                      "description": "Obtain data corresponding to a spark stage attempt for a Spark Application."
                    },
                    "searchStageAttemptTasks": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchStageAttemptTasks",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchStageAttemptTasks",
                      "description": "Obtain data corresponding to tasks for a spark stage attempt for a Spark Application.",
                      "path": "v1/{+name}:searchStageAttemptTasks"
                    },
                    "write": {
                      "description": "Write wrapper objects from dataplane to spanner",
                      "id": "dataproc.projects.locations.batches.sparkApplications.write",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:write",
                      "path": "v1/{+name}:write",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ],
                      "httpMethod": "POST"
                    },
                    "searchExecutorStageSummary": {
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchExecutorStageSummary",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchExecutorStageSummary",
                      "description": "Obtain executor summary with respect to a spark stage attempt.",
                      "path": "v1/{+name}:searchExecutorStageSummary",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET"
                    },
                    "searchJobs": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "path": "v1/{+name}:searchJobs",
                      "description": "Obtain list of spark jobs corresponding to a Spark Application.",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchJobs",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchJobs"
                    },
                    "searchExecutors": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain data corresponding to executors for a Spark Application.",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchExecutors",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchExecutors",
                      "path": "v1/{+name}:searchExecutors"
                    },
                    "accessEnvironmentInfo": {
                      "description": "Obtain environment details for a Spark Application",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessEnvironmentInfo",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessEnvironmentInfo",
                      "path": "v1/{+name}:accessEnvironmentInfo",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "accessSqlQuery": {
                      "path": "v1/{+name}:accessSqlQuery",
                      "description": "Obtain data corresponding to a particular SQL Query for a Spark Application.",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessSqlQuery",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessSqlQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET"
                    },
                    "search": {
                      "id": "dataproc.projects.locations.batches.sparkApplications.search",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications:search",
                      "description": "Obtain high level information and list of Spark Applications corresponding to a batch",
                      "path": "v1/{+parent}/sparkApplications:search",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET"
                    },
                    "summarizeExecutors": {
                      "description": "Obtain summary of Executor Summary for a Spark Application",
                      "id": "dataproc.projects.locations.batches.sparkApplications.summarizeExecutors",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:summarizeExecutors",
                      "path": "v1/{+name}:summarizeExecutors",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "searchSqlQueries": {
                      "path": "v1/{+name}:searchSqlQueries",
                      "id": "dataproc.projects.locations.batches.sparkApplications.searchSqlQueries",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:searchSqlQueries",
                      "description": "Obtain data corresponding to SQL Queries for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET"
                    },
                    "accessJob": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "path": "v1/{+name}:accessJob",
                      "description": "Obtain data corresponding to a spark job for a Spark Application.",
                      "id": "dataproc.projects.locations.batches.sparkApplications.accessJob",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:accessJob"
                    },
                    "summarizeStages": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.batches.sparkApplications.summarizeStages",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/batches/{batchesId}/sparkApplications/{sparkApplicationsId}:summarizeStages",
                      "description": "Obtain summary of Stages for a Spark Application",
                      "path": "v1/{+name}:summarizeStages"
                    }
                  }
                }
              }
            },
            "sessions": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "httpMethod": "GET",
                  "path": "v1/{+name}",
                  "id": "dataproc.projects.locations.sessions.get",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}",
                  "description": "Gets the resource representation for an interactive session."
                },
                "create": {
                  "path": "v1/{+parent}/sessions",
                  "description": "Create an interactive session asynchronously.",
                  "id": "dataproc.projects.locations.sessions.create",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "terminate": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "path": "v1/{+name}:terminate",
                  "description": "Terminates the interactive session.",
                  "id": "dataproc.projects.locations.sessions.terminate",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}:terminate"
                },
                "delete": {
                  "description": "Deletes the interactive session resource. If the session is not in terminal state, it is terminated, and then deleted.",
                  "id": "dataproc.projects.locations.sessions.delete",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "DELETE"
                },
                "list": {
                  "path": "v1/{+parent}/sessions",
                  "description": "Lists interactive sessions.",
                  "id": "dataproc.projects.locations.sessions.list",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "httpMethod": "GET"
                }
              },
              "resources": {
                "sparkApplications": {
                  "methods": {
                    "accessJob": {
                      "description": "Obtain data corresponding to a spark job for a Spark Application.",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessJob",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessJob",
                      "path": "v1/{+name}:accessJob",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "summarizeStages": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.summarizeStages",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:summarizeStages",
                      "description": "Obtain summary of Stages for a Spark Application",
                      "path": "v1/{+name}:summarizeStages"
                    },
                    "searchSqlQueries": {
                      "parameters": {
                        "pageToken": {
                          "description": "Optional. A page token received from a previous SearchSessionSparkApplicationSqlQueries call. Provide this token to retrieve the subsequent page.",
                          "location": "query",
                          "type": "string"
                        },
                        "details": {
                          "description": "Optional. Lists/ hides details of Spark plan nodes. True is set to list and false to hide.",
                          "location": "query",
                          "type": "boolean"
                        },
                        "planDescription": {
                          "location": "query",
                          "description": "Optional. Enables/ disables physical plan description on demand",
                          "type": "boolean"
                        },
                        "pageSize": {
                          "type": "integer",
                          "format": "int32",
                          "location": "query",
                          "description": "Optional. Maximum number of queries to return in each response. The service may return fewer than this. The default page size is 10; the maximum page size is 100."
                        },
                        "name": {
                          "description": "Required. The fully qualified name of the session to retrieve in the format \"projects/PROJECT_ID/locations/DATAPROC_REGION/sessions/SESSION_ID/sparkApplications/APPLICATION_ID\"",
                          "pattern": "^projects/[^/]+/locations/[^/]+/sessions/[^/]+/sparkApplications/[^/]+$",
                          "location": "path",
                          "required": true,
                          "type": "string"
                        },
                        "parent": {
                          "description": "Required. Parent (Session) resource reference.",
                          "location": "query",
                          "type": "string"
                        },
                        "operationIds": {
                          "repeated": true,
                          "type": "string",
                          "description": "Optional. List of Spark Connect operation IDs to filter by if provided.",
                          "location": "query"
                        }
                      },
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "path": "v1/{+name}:searchSqlQueries",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchSqlQueries",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchSqlQueries",
                      "description": "Obtain data corresponding to SQL Queries for a Spark Application."
                    },
                    "search": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.search",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications:search",
                      "description": "Obtain high level information and list of Spark Applications corresponding to a batch",
                      "path": "v1/{+parent}/sparkApplications:search"
                    },
                    "summarizeExecutors": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.summarizeExecutors",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:summarizeExecutors",
                      "description": "Obtain summary of Executor Summary for a Spark Application",
                      "path": "v1/{+name}:summarizeExecutors"
                    },
                    "accessSqlQuery": {
                      "path": "v1/{+name}:accessSqlQuery",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessSqlQuery",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessSqlQuery",
                      "description": "Obtain data corresponding to a particular SQL Query for a Spark Application.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET"
                    },
                    "accessEnvironmentInfo": {
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessEnvironmentInfo",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessEnvironmentInfo",
                      "description": "Obtain environment details for a Spark Application",
                      "path": "v1/{+name}:accessEnvironmentInfo",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET"
                    },
                    "searchJobs": {
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchJobs",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchJobs",
                      "description": "Obtain list of spark jobs corresponding to a Spark Application.",
                      "path": "v1/{+name}:searchJobs",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET"
                    },
                    "searchExecutors": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "description": "Obtain data corresponding to executors for a Spark Application.",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchExecutors",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchExecutors",
                      "path": "v1/{+name}:searchExecutors"
                    },
                    "searchExecutorStageSummary": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "description": "Obtain executor summary with respect to a spark stage attempt.",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchExecutorStageSummary",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchExecutorStageSummary",
                      "path": "v1/{+name}:searchExecutorStageSummary"
                    },
                    "write": {
                      "path": "v1/{+name}:write",
                      "description": "Write wrapper objects from dataplane to spanner",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.write",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:write",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc"
                      ]
                    },
                    "searchStageAttemptTasks": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "path": "v1/{+name}:searchStageAttemptTasks",
                      "description": "Obtain data corresponding to tasks for a spark stage attempt for a Spark Application.",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchStageAttemptTasks",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchStageAttemptTasks"
                    },
                    "searchStageAttempts": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchStageAttempts",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchStageAttempts",
                      "description": "Obtain data corresponding to a spark stage attempts for a Spark Application.",
                      "path": "v1/{+name}:searchStageAttempts"
                    },
                    "accessStageAttempt": {
                      "path": "v1/{+name}:accessStageAttempt",
                      "description": "Obtain data corresponding to a spark stage attempt for a Spark Application.",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessStageAttempt",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessStageAttempt",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "accessSqlPlan": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessSqlPlan",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessSqlPlan",
                      "description": "Obtain Spark Plan Graph for a Spark Application SQL execution. Limits the number of clusters returned as part of the graph to 10000.",
                      "path": "v1/{+name}:accessSqlPlan"
                    },
                    "summarizeStageAttemptTasks": {
                      "id": "dataproc.projects.locations.sessions.sparkApplications.summarizeStageAttemptTasks",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:summarizeStageAttemptTasks",
                      "description": "Obtain summary of Tasks for a Spark Application Stage Attempt",
                      "path": "v1/{+name}:summarizeStageAttemptTasks",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "access": {
                      "path": "v1/{+name}:access",
                      "description": "Obtain high level information corresponding to a single Spark Application.",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.access",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:access",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "accessStageRddGraph": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "id": "dataproc.projects.locations.sessions.sparkApplications.accessStageRddGraph",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:accessStageRddGraph",
                      "description": "Obtain RDD operation graph for a Spark Application Stage. Limits the number of clusters returned as part of the graph to 10000.",
                      "path": "v1/{+name}:accessStageRddGraph"
                    },
                    "searchStages": {
                      "id": "dataproc.projects.locations.sessions.sparkApplications.searchStages",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:searchStages",
                      "description": "Obtain data corresponding to stages for a Spark Application.",
                      "path": "v1/{+name}:searchStages",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ]
                    },
                    "summarizeJobs": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/dataproc",
                        "https://www.googleapis.com/auth/dataproc.read-only"
                      ],
                      "httpMethod": "GET",
                      "id": "dataproc.projects.locations.sessions.sparkApplications.summarizeJobs",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessions/{sessionsId}/sparkApplications/{sparkApplicationsId}:summarizeJobs",
                      "description": "Obtain summary of Jobs for a Spark Application",
                      "path": "v1/{+name}:summarizeJobs"
                    }
                  }
                }
              }
            },
            "autoscalingPolicies": {
              "methods": {
                "get": {
                  "path": "v1/{+name}",
                  "description": "Retrieves autoscaling policy.",
                  "id": "dataproc.projects.locations.autoscalingPolicies.get",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "create": {
                  "path": "v1/{+parent}/autoscalingPolicies",
                  "description": "Creates new autoscaling policy.",
                  "id": "dataproc.projects.locations.autoscalingPolicies.create",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "setIamPolicy": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.locations.autoscalingPolicies.setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "path": "v1/{+resource}:setIamPolicy"
                },
                "testIamPermissions": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "path": "v1/{+resource}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "id": "dataproc.projects.locations.autoscalingPolicies.testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}:testIamPermissions"
                },
                "update": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "PUT",
                  "description": "Updates (replaces) autoscaling policy.Disabled check for update_mask, because all updates will be full replacements.",
                  "id": "dataproc.projects.locations.autoscalingPolicies.update",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}",
                  "path": "v1/{+name}"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "description": "Deletes an autoscaling policy. It is an error to delete an autoscaling policy that is in use by one or more clusters.",
                  "id": "dataproc.projects.locations.autoscalingPolicies.delete",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "getIamPolicy": {
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataproc.projects.locations.autoscalingPolicies.getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies/{autoscalingPoliciesId}:getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST"
                },
                "list": {
                  "id": "dataproc.projects.locations.autoscalingPolicies.list",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/autoscalingPolicies",
                  "description": "Lists autoscaling policies in the project.",
                  "path": "v1/{+parent}/autoscalingPolicies",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                }
              }
            },
            "sessionTemplates": {
              "methods": {
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "PATCH",
                  "id": "dataproc.projects.locations.sessionTemplates.patch",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates/{sessionTemplatesId}",
                  "description": "Updates the session template synchronously.",
                  "path": "v1/{+name}"
                },
                "list": {
                  "path": "v1/{+parent}/sessionTemplates",
                  "description": "Lists session templates.",
                  "id": "dataproc.projects.locations.sessionTemplates.list",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ]
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Deletes a session template.",
                  "id": "dataproc.projects.locations.sessionTemplates.delete",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates/{sessionTemplatesId}",
                  "path": "v1/{+name}"
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "id": "dataproc.projects.locations.sessionTemplates.create",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates",
                  "description": "Create a session template synchronously.",
                  "path": "v1/{+parent}/sessionTemplates"
                },
                "get": {
                  "path": "v1/{+name}",
                  "description": "Gets the resource representation for a session template.",
                  "id": "dataproc.projects.locations.sessionTemplates.get",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/sessionTemplates/{sessionTemplatesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "httpMethod": "GET"
                }
              }
            },
            "operations": {
              "methods": {
                "cancel": {
                  "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it beco[...]",
                  "id": "dataproc.projects.locations.operations.cancel",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}:cancel",
                  "path": "v1/{+name}:cancel",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST"
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "id": "dataproc.projects.locations.operations.list",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns UNIMPLEMENTED.",
                  "path": "v1/{+name}"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns google.rpc.Code.UNIMPLEMENTED.",
                  "id": "dataproc.projects.locations.operations.delete",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "path": "v1/{+name}"
                },
                "get": {
                  "id": "dataproc.projects.locations.operations.get",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "path": "v1/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ]
                }
              }
            },
            "workflowTemplates": {
              "methods": {
                "create": {
                  "path": "v1/{+parent}/workflowTemplates",
                  "id": "dataproc.projects.locations.workflowTemplates.create",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates",
                  "description": "Creates new workflow template.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST"
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ],
                  "path": "v1/{+parent}/workflowTemplates",
                  "id": "dataproc.projects.locations.workflowTemplates.list",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates",
                  "description": "Lists workflows that match the specified filter in the request."
                },
                "instantiate": {
                  "path": "v1/{+name}:instantiate",
                  "id": "dataproc.projects.locations.workflowTemplates.instantiate",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}:instantiate",
                  "description": "Instantiates a template and begins execution.The returned Operation can be used to track execution of workflow by polling operations.get. The Operation will complete when entire workflow is finished.The running workflow can be aborted via operations.cancel. This will cause any inflight jobs to be cancelled and workflow-owned clusters to be deleted.The Operation.metadata will be WorkflowMetadata (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.d[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST"
                },
                "delete": {
                  "path": "v1/{+name}",
                  "id": "dataproc.projects.locations.workflowTemplates.delete",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}",
                  "description": "Deletes a workflow template. It does not cancel in-progress workflows.",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "setIamPolicy": {
                  "path": "v1/{+resource}:setIamPolicy",
                  "id": "dataproc.projects.locations.workflowTemplates.setIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}:setIamPolicy",
                  "description": "Sets the access control policy on the specified resource. Replaces any existing policy.Can return NOT_FOUND, INVALID_ARGUMENT, and PERMISSION_DENIED errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST"
                },
                "testIamPermissions": {
                  "id": "dataproc.projects.locations.workflowTemplates.testIamPermissions",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}:testIamPermissions",
                  "description": "Returns permissions that a caller has on the specified resource. If the resource does not exist, this will return an empty set of permissions, not a NOT_FOUND error.Note: This operation is designed to be used for building permission-aware UIs and command-line tools, not for authorization checking. This operation may \"fail open\" without warning.",
                  "path": "v1/{+resource}:testIamPermissions",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST"
                },
                "get": {
                  "path": "v1/{+name}",
                  "description": "Retrieves the latest workflow template.Can retrieve previously instantiated template by specifying optional version parameter.",
                  "id": "dataproc.projects.locations.workflowTemplates.get",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc",
                    "https://www.googleapis.com/auth/dataproc.read-only"
                  ]
                },
                "instantiateInline": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "httpMethod": "POST",
                  "description": "Instantiates a template and begins execution.This method is equivalent to executing the sequence CreateWorkflowTemplate, InstantiateWorkflowTemplate, DeleteWorkflowTemplate.The returned Operation can be used to track execution of workflow by polling operations.get. The Operation will complete when entire workflow is finished.The running workflow can be aborted via operations.cancel. This will cause any inflight jobs to be cancelled and workflow-owned clusters to[...]",
                  "id": "dataproc.projects.locations.workflowTemplates.instantiateInline",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates:instantiateInline",
                  "path": "v1/{+parent}/workflowTemplates:instantiateInline"
                },
                "update": {
                  "path": "v1/{+name}",
                  "id": "dataproc.projects.locations.workflowTemplates.update",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}",
                  "description": "Updates (replaces) workflow template. The updated template must contain version that matches the current server version.",
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ]
                },
                "getIamPolicy": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/dataproc"
                  ],
                  "description": "Gets the access control policy for a resource. Returns an empty policy if the resource exists and does not have a policy set.",
                  "id": "dataproc.projects.locations.workflowTemplates.getIamPolicy",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/workflowTemplates/{workflowTemplatesId}:getIamPolicy",
                  "path": "v1/{+resource}:getIamPolicy"
                }
              }
            }
          }
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dataproc": {
          "description": "See, edit, configure, and delete your Google Cloud Dataproc data and see the email address for your Google Account"
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/dataproc.read-only": {
          "description": "See your Google Cloud Dataproc data and the email address of your Google Account"
        }
      }
    }
  },
  "schemas": {
    "KerberosConfig": {
      "type": "object",
      "id": "KerberosConfig",
      "properties": {
        "keyPasswordUri": {
          "type": "string",
          "description": "Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided key. For the self-signed certificate, this password is generated by Dataproc."
        },
        "kmsKeyUri": {
          "description": "Optional. The URI of the KMS key used to encrypt sensitive files.",
          "type": "string"
        },
        "truststorePasswordUri": {
          "description": "Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided truststore. For the self-signed certificate, this password is generated by Dataproc.",
          "type": "string"
        },
        "enableKerberos": {
          "description": "Optional. Flag to indicate whether to Kerberize the cluster (default: false). Set this field to true to enable Kerberos on a cluster.",
          "type": "boolean"
        },
        "crossRealmTrustAdminServer": {
          "type": "string",
          "description": "Optional. The admin server (IP or hostname) for the remote trusted realm in a cross realm trust relationship."
        },
        "rootPrincipalPasswordUri": {
          "type": "string",
          "description": "Optional. The Cloud Storage URI of a KMS encrypted file containing the root principal password."
        },
        "crossRealmTrustRealm": {
          "description": "Optional. The remote realm the Dataproc on-cluster KDC will trust, should the user enable cross realm trust.",
          "type": "string"
        },
        "truststoreUri": {
          "description": "Optional. The Cloud Storage URI of the truststore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate.",
          "type": "string"
        },
        "kdcDbKeyUri": {
          "type": "string",
          "description": "Optional. The Cloud Storage URI of a KMS encrypted file containing the master key of the KDC database."
        },
        "crossRealmTrustSharedPasswordUri": {
          "type": "string",
          "description": "Optional. The Cloud Storage URI of a KMS encrypted file containing the shared password between the on-cluster Kerberos realm and the remote trusted realm, in a cross realm trust relationship."
        },
        "tgtLifetimeHours": {
          "description": "Optional. The lifetime of the ticket granting ticket, in hours. If not specified, or user specifies 0, then default value 10 will be used.",
          "type": "integer",
          "format": "int32"
        },
        "keystoreUri": {
          "type": "string",
          "description": "Optional. The Cloud Storage URI of the keystore file used for SSL encryption. If not provided, Dataproc will provide a self-signed certificate."
        },
        "keystorePasswordUri": {
          "type": "string",
          "description": "Optional. The Cloud Storage URI of a KMS encrypted file containing the password to the user provided keystore. For the self-signed certificate, this password is generated by Dataproc."
        },
        "crossRealmTrustKdc": {
          "description": "Optional. The KDC (IP or hostname) for the remote trusted realm in a cross realm trust relationship.",
          "type": "string"
        },
        "realm": {
          "description": "Optional. The name of the on-cluster Kerberos realm. If not specified, the uppercased domain of hostnames will be the realm.",
          "type": "string"
        }
      },
      "description": "Specifies Kerberos related configuration."
    },
    "TaskQuantileMetrics": {
      "type": "object",
      "id": "TaskQuantileMetrics",
      "properties": {
        "gettingResultTimeMillis": {
          "$ref": "Quantiles"
        },
        "shuffleReadMetrics": {
          "$ref": "ShuffleReadQuantileMetrics"
        },
        "executorRunTimeMillis": {
          "$ref": "Quantiles"
        },
        "executorCpuTimeNanos": {
          "$ref": "Quantiles"
        },
        "memoryBytesSpilled": {
          "$ref": "Quantiles"
        },
        "inputMetrics": {
          "$ref": "InputQuantileMetrics"
        },
        "shuffleWriteMetrics": {
          "$ref": "ShuffleWriteQuantileMetrics"
        },
        "jvmGcTimeMillis": {
          "$ref": "Quantiles"
        },
        "durationMillis": {
          "$ref": "Quantiles"
        },
        "executorDeserializeCpuTimeNanos": {
          "$ref": "Quantiles"
        },
        "resultSize": {
          "$ref": "Quantiles"
        },
        "schedulerDelayMillis": {
          "$ref": "Quantiles"
        },
        "resultSerializationTimeMillis": {
          "$ref": "Quantiles"
        },
        "executorDeserializeTimeMillis": {
          "$ref": "Quantiles"
        },
        "diskBytesSpilled": {
          "$ref": "Quantiles"
        },
        "outputMetrics": {
          "$ref": "OutputQuantileMetrics"
        },
        "peakExecutionMemoryBytes": {
          "$ref": "Quantiles"
        }
      }
    },
    "ClusterStatus": {
      "description": "The status of a cluster and its instances.",
      "type": "object",
      "id": "ClusterStatus",
      "properties": {
        "substate": {
          "enumDescriptions": [
            "The cluster substate is unknown.",
            "The cluster is known to be in an unhealthy state (for example, critical daemons are not running or HDFS capacity is exhausted).Applies to RUNNING state.",
            "The agent-reported status is out of date (may occur if Dataproc loses communication with Agent).Applies to RUNNING state."
          ],
          "enum": [
            "UNSPECIFIED",
            "UNHEALTHY",
            "STALE_STATUS"
          ],
          "readOnly": true,
          "type": "string",
          "description": "Output only. Additional state information that includes status reported by the agent."
        },
        "state": {
          "enumDescriptions": [
            "The cluster state is unknown.",
            "The cluster is being created and set up. It is not ready for use.",
            "The cluster is currently running and healthy. It is ready for use.Note: The cluster state changes from \"creating\" to \"running\" status after the master node(s), first two primary worker nodes (and the last primary worker node if primary workers > 2) are running.",
            "The cluster encountered an error. It is not ready for use.",
            "The cluster has encountered an error while being updated. Jobs can be submitted to the cluster, but the cluster cannot be updated.",
            "The cluster is being deleted. It cannot be used.",
            "The cluster is being updated. It continues to accept and process jobs.",
            "The cluster is being stopped. It cannot be used.",
            "The cluster is currently stopped. It is not ready for use.",
            "The cluster is being started. It is not ready for use.",
            "The cluster is being repaired. It is not ready for use.",
            "Cluster creation is currently waiting for resources to be available. Once all resources are available, it will transition to CREATING and then RUNNING."
          ],
          "enum": [
            "UNKNOWN",
            "CREATING",
            "RUNNING",
            "ERROR",
            "ERROR_DUE_TO_UPDATE",
            "DELETING",
            "UPDATING",
            "STOPPING",
            "STOPPED",
            "STARTING",
            "REPAIRING",
            "SCHEDULED"
          ],
          "description": "Output only. The cluster's state.",
          "readOnly": true,
          "type": "string"
        },
        "detail": {
          "readOnly": true,
          "type": "string",
          "description": "Optional. Output only. Details of cluster's state."
        },
        "stateStartTime": {
          "description": "Output only. Time when this state was entered (see JSON representation of Timestamp (https://developers.google.com/protocol-buffers/docs/proto3#json)).",
          "format": "google-datetime",
          "readOnly": true,
          "type": "string"
        }
      }
    },
    "NodePool": {
      "description": "indicating a list of workers of same type",
      "type": "object",
      "id": "NodePool",
      "properties": {
        "instanceNames": {
          "description": "Name of instances to be repaired. These instances must belong to specified node pool.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "repairAction": {
          "type": "string",
          "description": "Required. Repair action to take on specified resources of the node pool.",
          "enumDescriptions": [
            "No action will be taken by default.",
            "delete the specified list of nodes."
          ],
          "enum": [
            "REPAIR_ACTION_UNSPECIFIED",
            "DELETE"
          ]
        },
        "id": {
          "type": "string",
          "description": "Required. A unique id of the node pool. Primary and Secondary workers can be specified using special reserved ids PRIMARY_WORKER_POOL and SECONDARY_WORKER_POOL respectively. Aux node pools can be referenced using corresponding pool id."
        }
      }
    },
    "OutputMetrics": {
      "description": "Metrics about the data written by the task.",
      "type": "object",
      "id": "OutputMetrics",
      "properties": {
        "bytesWritten": {
          "type": "string",
          "format": "int64"
        },
        "recordsWritten": {
          "type": "string",
          "format": "int64"
        }
      }
    },
    "SearchSessionSparkApplicationStagesResponse": {
      "type": "object",
      "id": "SearchSessionSparkApplicationStagesResponse",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSessionSparkApplicationStages."
        },
        "sparkApplicationStages": {
          "description": "Output only. Data corresponding to a stage.",
          "items": {
            "$ref": "StageData"
          },
          "readOnly": true,
          "type": "array"
        }
      },
      "description": "A list of stages associated with a Spark Application."
    },
    "DataprocMetricConfig": {
      "id": "DataprocMetricConfig",
      "properties": {
        "metrics": {
          "type": "array",
          "description": "Required. Metrics sources to enable.",
          "items": {
            "$ref": "Metric"
          }
        }
      },
      "type": "object",
      "description": "Dataproc metric config."
    },
    "SqlPlanMetric": {
      "id": "SqlPlanMetric",
      "properties": {
        "name": {
          "type": "string"
        },
        "metricType": {
          "type": "string"
        },
        "accumulatorId": {
          "type": "string",
          "format": "int64"
        }
      },
      "type": "object",
      "description": "Metrics related to SQL execution."
    },
    "Cluster": {
      "id": "Cluster",
      "properties": {
        "status": {
          "readOnly": true,
          "description": "Output only. Cluster status.",
          "$ref": "ClusterStatus"
        },
        "projectId": {
          "type": "string",
          "description": "Required. The Google Cloud Platform project ID that the cluster belongs to."
        },
        "metrics": {
          "readOnly": true,
          "description": "Output only. Contains cluster daemon metrics such as HDFS and YARN stats.Beta Feature: This report is available for testing purposes only. It may be changed before final release.",
          "$ref": "ClusterMetrics"
        },
        "clusterUuid": {
          "readOnly": true,
          "type": "string",
          "description": "Output only. A cluster UUID (Unique Universal Identifier). Dataproc generates this value when it creates the cluster."
        },
        "statusHistory": {
          "readOnly": true,
          "type": "array",
          "description": "Output only. The previous cluster status.",
          "items": {
            "$ref": "ClusterStatus"
          }
        },
        "virtualClusterConfig": {
          "description": "Optional. The virtual cluster config is used when creating a Dataproc cluster that does not directly control the underlying compute resources, for example, when creating a Dataproc-on-GKE cluster (https://cloud.google.com/dataproc/docs/guides/dpgke/dataproc-gke-overview). Dataproc may set default values, and values may change when clusters are updated. Exactly one of config or virtual_cluster_config must be specified.",
          "$ref": "VirtualClusterConfig"
        },
        "config": {
          "description": "Optional. The cluster config for a cluster of Compute Engine Instances. Note that Dataproc may set default values, and values may change when clusters are updated.Exactly one of ClusterConfig or VirtualClusterConfig must be specified.",
          "$ref": "ClusterConfig"
        },
        "clusterName": {
          "type": "string",
          "description": "Required. The cluster name, which must be unique within a project. The name must start with a lowercase letter, and can contain up to 51 lowercase letters, numbers, and hyphens. It cannot end with a hyphen. The name of a deleted cluster can be reused."
        },
        "labels": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Optional. The labels to associate with this cluster. Label keys must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). Label values may be empty, but, if present, must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). No more than 32 labels can be associated with a cluster."
        }
      },
      "type": "object",
      "description": "Describes the identifying information, config, and status of a Dataproc cluster"
    },
    "NamespacedGkeDeploymentTarget": {
      "description": "Deprecated. Used only for the deprecated beta. A full, namespace-isolated deployment target for an existing GKE cluster.",
      "type": "object",
      "id": "NamespacedGkeDeploymentTarget",
      "properties": {
        "targetGkeCluster": {
          "description": "Optional. The target GKE cluster to deploy to. Format: 'projects/{project}/locations/{location}/clusters/{cluster_id}'",
          "type": "string"
        },
        "clusterNamespace": {
          "description": "Optional. A namespace within the GKE cluster to deploy into.",
          "type": "string"
        }
      },
      "deprecated": true
    },
    "AccessSessionSparkApplicationStageAttemptResponse": {
      "description": "Stage Attempt for a Stage of a Spark Application",
      "id": "AccessSessionSparkApplicationStageAttemptResponse",
      "properties": {
        "stageData": {
          "description": "Output only. Data corresponding to a stage.",
          "$ref": "StageData",
          "readOnly": true
        }
      },
      "type": "object"
    },
    "ShufflePushReadQuantileMetrics": {
      "id": "ShufflePushReadQuantileMetrics",
      "properties": {
        "remoteMergedBytesRead": {
          "$ref": "Quantiles"
        },
        "mergedFetchFallbackCount": {
          "$ref": "Quantiles"
        },
        "corruptMergedBlockChunks": {
          "$ref": "Quantiles"
        },
        "localMergedBlocksFetched": {
          "$ref": "Quantiles"
        },
        "localMergedChunksFetched": {
          "$ref": "Quantiles"
        },
        "remoteMergedBlocksFetched": {
          "$ref": "Quantiles"
        },
        "remoteMergedChunksFetched": {
          "$ref": "Quantiles"
        },
        "remoteMergedReqsDuration": {
          "$ref": "Quantiles"
        },
        "localMergedBytesRead": {
          "$ref": "Quantiles"
        }
      },
      "type": "object"
    },
    "KubernetesSoftwareConfig": {
      "id": "KubernetesSoftwareConfig",
      "properties": {
        "componentVersion": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object",
          "description": "The components that should be installed in this Dataproc cluster. The key must be a string from the KubernetesComponent enumeration. The value is the version of the software to be installed. At least one entry must be specified."
        },
        "properties": {
          "description": "The properties to set on daemon config files.Property keys are specified in prefix:property format, for example spark:spark.kubernetes.container.image. The following are supported prefixes and their mappings: spark: spark-defaults.confFor more information, see Cluster properties (https://cloud.google.com/dataproc/docs/concepts/cluster-properties).",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "type": "object",
      "description": "The software configuration for this Dataproc cluster running on Kubernetes."
    },
    "AccessSparkApplicationStageAttemptResponse": {
      "description": "Stage Attempt for a Stage of a Spark Application",
      "type": "object",
      "id": "AccessSparkApplicationStageAttemptResponse",
      "properties": {
        "stageData": {
          "description": "Output only. Data corresponding to a stage.",
          "$ref": "StageData",
          "readOnly": true
        }
      }
    },
    "DiagnoseClusterRequest": {
      "description": "A request to collect cluster diagnostic information.",
      "type": "object",
      "id": "DiagnoseClusterRequest",
      "properties": {
        "tarballGcsDir": {
          "description": "Optional. (Optional) The output Cloud Storage directory for the diagnostic tarball. If not specified, a task-specific directory in the cluster's staging bucket will be used.",
          "type": "string"
        },
        "job": {
          "description": "Optional. DEPRECATED Specifies the job on which diagnosis is to be performed. Format: projects/{project}/regions/{region}/jobs/{job}",
          "type": "string",
          "deprecated": true
        },
        "jobs": {
          "description": "Optional. Specifies a list of jobs on which diagnosis is to be performed. Format: projects/{project}/regions/{region}/jobs/{job}",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "yarnApplicationIds": {
          "description": "Optional. Specifies a list of yarn applications on which diagnosis is to be performed.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "diagnosisInterval": {
          "description": "Optional. Time interval in which diagnosis should be carried out on the cluster.",
          "$ref": "Interval"
        },
        "yarnApplicationId": {
          "type": "string",
          "deprecated": true,
          "description": "Optional. DEPRECATED Specifies the yarn application on which diagnosis is to be performed."
        },
        "tarballAccess": {
          "description": "Optional. (Optional) The access type to the diagnostic tarball. If not specified, falls back to default access of the bucket",
          "enumDescriptions": [
            "Tarball Access unspecified. Falls back to default access of the bucket",
            "Google Cloud Support group has read access to the diagnostic tarball",
            "Google Cloud Dataproc Diagnose service account has read access to the diagnostic tarball"
          ],
          "enum": [
            "TARBALL_ACCESS_UNSPECIFIED",
            "GOOGLE_CLOUD_SUPPORT",
            "GOOGLE_DATAPROC_DIAGNOSE"
          ],
          "type": "string"
        }
      }
    },
    "SparkConnectConfig": {
      "description": "Spark connect configuration for an interactive session.",
      "id": "SparkConnectConfig",
      "properties": {},
      "type": "object"
    },
    "ResizeNodeGroupRequest": {
      "id": "ResizeNodeGroupRequest",
      "properties": {
        "requestId": {
          "type": "string",
          "description": "Optional. A unique ID used to identify the request. If the server receives two ResizeNodeGroupRequest (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.ResizeNodeGroupRequests) with the same ID, the second request is ignored and the first google.longrunning.Operation created and stored in the backend is returned.Recommendation: Set this value to a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier).The[...]"
        },
        "parentOperationId": {
          "description": "Optional. operation id of the parent operation sending the resize request",
          "type": "string"
        },
        "size": {
          "description": "Required. The number of running instances for the node group to maintain. The group adds or removes instances to maintain the number of instances specified by this parameter.",
          "type": "integer",
          "format": "int32"
        },
        "gracefulDecommissionTimeout": {
          "description": "Optional. Timeout for graceful YARN decommissioning. Graceful decommissioning (https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/scaling-clusters#graceful_decommissioning) allows the removal of nodes from the Compute Engine node group without interrupting jobs in progress. This timeout specifies how long to wait for jobs in progress to finish before forcefully removing nodes (and potentially interrupting jobs). Default timeout is 0 (for forceful decom[...]",
          "format": "google-duration",
          "type": "string"
        }
      },
      "type": "object",
      "description": "A request to resize a node group."
    },
    "SearchSparkApplicationJobsResponse": {
      "description": "A list of Jobs associated with a Spark Application.",
      "type": "object",
      "id": "SearchSparkApplicationJobsResponse",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSparkApplicationJobsRequest."
        },
        "sparkApplicationJobs": {
          "readOnly": true,
          "type": "array",
          "description": "Output only. Data corresponding to a spark job.",
          "items": {
            "$ref": "JobData"
          }
        }
      }
    },
    "GkeNodePoolAutoscalingConfig": {
      "type": "object",
      "id": "GkeNodePoolAutoscalingConfig",
      "properties": {
        "minNodeCount": {
          "description": "The minimum number of nodes in the node pool. Must be >= 0 and <= max_node_count.",
          "type": "integer",
          "format": "int32"
        },
        "maxNodeCount": {
          "description": "The maximum number of nodes in the node pool. Must be >= min_node_count, and must be > 0. Note: Quota must be sufficient to scale up the cluster.",
          "format": "int32",
          "type": "integer"
        }
      },
      "description": "GkeNodePoolAutoscaling contains information the cluster autoscaler needs to adjust the size of the node pool to the current cluster usage."
    },
    "Job": {
      "description": "A Dataproc job resource.",
      "type": "object",
      "id": "Job",
      "properties": {
        "driverOutputResourceUri": {
          "readOnly": true,
          "type": "string",
          "description": "Output only. A URI pointing to the location of the stdout of the job's driver program."
        },
        "scheduling": {
          "description": "Optional. Job scheduling configuration.",
          "$ref": "JobScheduling"
        },
        "pysparkJob": {
          "description": "Optional. Job is a PySpark job.",
          "$ref": "PySparkJob"
        },
        "reference": {
          "description": "Optional. The fully qualified reference to the job, which can be used to obtain the equivalent REST path of the job resource. If this property is not specified when a job is created, the server generates a job_id.",
          "$ref": "JobReference"
        },
        "hiveJob": {
          "description": "Optional. Job is a Hive job.",
          "$ref": "HiveJob"
        },
        "labels": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Optional. The labels to associate with this job. Label keys must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). Label values can be empty, but, if present, must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). No more than 32 labels can be associated with a job."
        },
        "prestoJob": {
          "description": "Optional. Job is a Presto job.",
          "$ref": "PrestoJob"
        },
        "yarnApplications": {
          "description": "Output only. The collection of YARN applications spun up by this job.Beta Feature: This report is available for testing purposes only. It might be changed before final release.",
          "items": {
            "$ref": "YarnApplication"
          },
          "readOnly": true,
          "type": "array"
        },
        "driverControlFilesUri": {
          "readOnly": true,
          "type": "string",
          "description": "Output only. If present, the location of miscellaneous control files which can be used as part of job setup and handling. If not present, control files might be placed in the same location as driver_output_uri."
        },
        "hadoopJob": {
          "description": "Optional. Job is a Hadoop job.",
          "$ref": "HadoopJob"
        },
        "sparkSqlJob": {
          "description": "Optional. Job is a SparkSql job.",
          "$ref": "SparkSqlJob"
        },
        "jobUuid": {
          "description": "Output only. A UUID that uniquely identifies a job within the project over time. This is in contrast to a user-settable reference.job_id that might be reused over time.",
          "readOnly": true,
          "type": "string"
        },
        "driverSchedulingConfig": {
          "description": "Optional. Driver scheduling configuration.",
          "$ref": "DriverSchedulingConfig"
        },
        "pigJob": {
          "description": "Optional. Job is a Pig job.",
          "$ref": "PigJob"
        },
        "trinoJob": {
          "description": "Optional. Job is a Trino job.",
          "$ref": "TrinoJob"
        },
        "placement": {
          "description": "Required. Job information, including how, when, and where to run the job.",
          "$ref": "JobPlacement"
        },
        "status": {
          "description": "Output only. The job status. Additional application-specific status information might be contained in the type_job and yarn_applications fields.",
          "$ref": "JobStatus",
          "readOnly": true
        },
        "sparkJob": {
          "description": "Optional. Job is a Spark job.",
          "$ref": "SparkJob"
        },
        "sparkRJob": {
          "description": "Optional. Job is a SparkR job.",
          "$ref": "SparkRJob"
        },
        "flinkJob": {
          "description": "Optional. Job is a Flink job.",
          "$ref": "FlinkJob"
        },
        "done": {
          "readOnly": true,
          "type": "boolean",
          "description": "Output only. Indicates whether the job is completed. If the value is false, the job is still in progress. If true, the job is completed, and status.state field will indicate if it was successful, failed, or cancelled."
        },
        "statusHistory": {
          "description": "Output only. The previous job status.",
          "items": {
            "$ref": "JobStatus"
          },
          "readOnly": true,
          "type": "array"
        }
      }
    },
    "SetIamPolicyRequest": {
      "description": "Request message for SetIamPolicy method.",
      "type": "object",
      "id": "SetIamPolicyRequest",
      "properties": {
        "policy": {
          "description": "REQUIRED: The complete policy to be applied to the resource. The size of the policy is limited to a few 10s of KB. An empty policy is a valid policy but certain Google Cloud services (such as Projects) might reject them.",
          "$ref": "Policy"
        }
      }
    },
    "AccessSessionSparkApplicationResponse": {
      "id": "AccessSessionSparkApplicationResponse",
      "properties": {
        "application": {
          "description": "Output only. High level information corresponding to an application.",
          "$ref": "ApplicationInfo",
          "readOnly": true
        }
      },
      "type": "object",
      "description": "A summary of Spark Application"
    },
    "StageShufflePushReadMetrics": {
      "type": "object",
      "id": "StageShufflePushReadMetrics",
      "properties": {
        "mergedFetchFallbackCount": {
          "type": "string",
          "format": "int64"
        },
        "corruptMergedBlockChunks": {
          "format": "int64",
          "type": "string"
        },
        "localMergedBlocksFetched": {
          "format": "int64",
          "type": "string"
        },
        "localMergedChunksFetched": {
          "format": "int64",
          "type": "string"
        },
        "remoteMergedBytesRead": {
          "type": "string",
          "format": "int64"
        },
        "localMergedBytesRead": {
          "type": "string",
          "format": "int64"
        },
        "remoteMergedReqsDuration": {
          "type": "string",
          "format": "int64"
        },
        "remoteMergedChunksFetched": {
          "type": "string",
          "format": "int64"
        },
        "remoteMergedBlocksFetched": {
          "type": "string",
          "format": "int64"
        }
      }
    },
    "ShufflePushReadMetrics": {
      "id": "ShufflePushReadMetrics",
      "properties": {
        "corruptMergedBlockChunks": {
          "type": "string",
          "format": "int64"
        },
        "localMergedBlocksFetched": {
          "type": "string",
          "format": "int64"
        },
        "localMergedChunksFetched": {
          "format": "int64",
          "type": "string"
        },
        "mergedFetchFallbackCount": {
          "format": "int64",
          "type": "string"
        },
        "remoteMergedBytesRead": {
          "type": "string",
          "format": "int64"
        },
        "localMergedBytesRead": {
          "type": "string",
          "format": "int64"
        },
        "remoteMergedReqsDuration": {
          "format": "int64",
          "type": "string"
        },
        "remoteMergedChunksFetched": {
          "type": "string",
          "format": "int64"
        },
        "remoteMergedBlocksFetched": {
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object"
    },
    "ClusterOperationStatus": {
      "id": "ClusterOperationStatus",
      "properties": {
        "innerState": {
          "description": "Output only. A message containing the detailed operation state.",
          "readOnly": true,
          "type": "string"
        },
        "details": {
          "readOnly": true,
          "type": "string",
          "description": "Output only. A message containing any operation metadata details."
        },
        "state": {
          "enumDescriptions": [
            "Unused.",
            "The operation has been created.",
            "The operation is running.",
            "The operation is done; either cancelled or completed."
          ],
          "enum": [
            "UNKNOWN",
            "PENDING",
            "RUNNING",
            "DONE"
          ],
          "readOnly": true,
          "type": "string",
          "description": "Output only. A message containing the operation state."
        },
        "stateStartTime": {
          "format": "google-datetime",
          "readOnly": true,
          "type": "string",
          "description": "Output only. The time this state was entered."
        }
      },
      "type": "object",
      "description": "The status of the operation."
    },
    "SearchSparkApplicationStagesResponse": {
      "type": "object",
      "id": "SearchSparkApplicationStagesResponse",
      "properties": {
        "sparkApplicationStages": {
          "description": "Output only. Data corresponding to a stage.",
          "items": {
            "$ref": "StageData"
          },
          "readOnly": true,
          "type": "array"
        },
        "nextPageToken": {
          "type": "string",
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSparkApplicationStages."
        }
      },
      "description": "A list of stages associated with a Spark Application."
    },
    "AccessSessionSparkApplicationEnvironmentInfoResponse": {
      "id": "AccessSessionSparkApplicationEnvironmentInfoResponse",
      "properties": {
        "applicationEnvironmentInfo": {
          "description": "Details about the Environment that the application is running in.",
          "$ref": "ApplicationEnvironmentInfo"
        }
      },
      "type": "object",
      "description": "Environment details of a Saprk Application."
    },
    "CancelJobRequest": {
      "id": "CancelJobRequest",
      "properties": {},
      "type": "object",
      "description": "A request to cancel a job."
    },
    "SpeculationStageSummary": {
      "description": "Details of the speculation task when speculative execution is enabled.",
      "id": "SpeculationStageSummary",
      "properties": {
        "numKilledTasks": {
          "type": "integer",
          "format": "int32"
        },
        "stageId": {
          "format": "int64",
          "type": "string"
        },
        "stageAttemptId": {
          "format": "int32",
          "type": "integer"
        },
        "numActiveTasks": {
          "format": "int32",
          "type": "integer"
        },
        "numTasks": {
          "type": "integer",
          "format": "int32"
        },
        "numCompletedTasks": {
          "type": "integer",
          "format": "int32"
        },
        "numFailedTasks": {
          "type": "integer",
          "format": "int32"
        }
      },
      "type": "object"
    },
    "BasicYarnAutoscalingConfig": {
      "type": "object",
      "id": "BasicYarnAutoscalingConfig",
      "properties": {
        "scaleDownFactor": {
          "description": "Required. Fraction of average YARN pending memory in the last cooldown period for which to remove workers. A scale-down factor of 1 will result in scaling down so that there is no available memory remaining after the update (more aggressive scaling). A scale-down factor of 0 disables removing workers, which can be beneficial for autoscaling a single job. See How autoscaling works (https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/autoscaling#how_autos[...]",
          "type": "number",
          "format": "double"
        },
        "scaleUpMinWorkerFraction": {
          "description": "Optional. Minimum scale-up threshold as a fraction of total cluster size before scaling occurs. For example, in a 20-worker cluster, a threshold of 0.1 means the autoscaler must recommend at least a 2-worker scale-up for the cluster to scale. A threshold of 0 means the autoscaler will scale up on any recommended change.Bounds: 0.0, 1.0. Default: 0.0.",
          "format": "double",
          "type": "number"
        },
        "scaleDownMinWorkerFraction": {
          "description": "Optional. Minimum scale-down threshold as a fraction of total cluster size before scaling occurs. For example, in a 20-worker cluster, a threshold of 0.1 means the autoscaler must recommend at least a 2 worker scale-down for the cluster to scale. A threshold of 0 means the autoscaler will scale down on any recommended change.Bounds: 0.0, 1.0. Default: 0.0.",
          "format": "double",
          "type": "number"
        },
        "scaleUpFactor": {
          "description": "Required. Fraction of average YARN pending memory in the last cooldown period for which to add workers. A scale-up factor of 1.0 will result in scaling up so that there is no pending memory remaining after the update (more aggressive scaling). A scale-up factor closer to 0 will result in a smaller magnitude of scaling up (less aggressive scaling). See How autoscaling works (https://cloud.google.com/dataproc/docs/concepts/configuring-clusters/autoscaling#how_autoscaling_[...]",
          "format": "double",
          "type": "number"
        },
        "gracefulDecommissionTimeout": {
          "description": "Required. Timeout for YARN graceful decommissioning of Node Managers. Specifies the duration to wait for jobs to complete before forcefully removing workers (and potentially interrupting jobs). Only applicable to downscaling operations.Bounds: 0s, 1d.",
          "type": "string",
          "format": "google-duration"
        }
      },
      "description": "Basic autoscaling configurations for YARN."
    },
    "ListJobsResponse": {
      "description": "A list of jobs in a project.",
      "id": "ListJobsResponse",
      "properties": {
        "nextPageToken": {
          "type": "string",
          "description": "Optional. This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent ListJobsRequest."
        },
        "jobs": {
          "readOnly": true,
          "type": "array",
          "description": "Output only. Jobs list.",
          "items": {
            "$ref": "Job"
          }
        },
        "unreachable": {
          "readOnly": true,
          "type": "array",
          "description": "Output only. List of jobs with kms_key-encrypted parameters that could not be decrypted. A response to a jobs.get request may indicate the reason for the decryption failure for a specific job.",
          "items": {
            "type": "string"
          }
        }
      },
      "type": "object"
    },
    "WorkflowMetadata": {
      "id": "WorkflowMetadata",
      "properties": {
        "createCluster": {
          "description": "Output only. The create cluster operation metadata.",
          "$ref": "ClusterOperation",
          "readOnly": true
        },
        "version": {
          "description": "Output only. The version of template at the time of workflow instantiation.",
          "format": "int32",
          "readOnly": true,
          "type": "integer"
        },
        "template": {
          "description": "Output only. The resource name of the workflow template as described in https://cloud.google.com/apis/design/resource_names. For projects.regions.workflowTemplates, the resource name of the template has the following format: projects/{project_id}/regions/{region}/workflowTemplates/{template_id} For projects.locations.workflowTemplates, the resource name of the template has the following format: projects/{project_id}/locations/{location}/workflowTemplates/{template_id}",
          "readOnly": true,
          "type": "string"
        },
        "graph": {
          "readOnly": true,
          "description": "Output only. The workflow graph.",
          "$ref": "WorkflowGraph"
        },
        "state": {
          "description": "Output only. The workflow state.",
          "readOnly": true,
          "type": "string",
          "enumDescriptions": [
            "Unused.",
            "The operation has been created.",
            "The operation is running.",
            "The operation is done; either cancelled or completed."
          ],
          "enum": [
            "UNKNOWN",
            "PENDING",
            "RUNNING",
            "DONE"
          ]
        },
        "endTime": {
          "readOnly": true,
          "type": "string",
          "format": "google-datetime",
          "description": "Output only. Workflow end time."
        },
        "clusterUuid": {
          "description": "Output only. The UUID of target cluster.",
          "readOnly": true,
          "type": "string"
        },
        "startTime": {
          "readOnly": true,
          "type": "string",
          "format": "google-datetime",
          "description": "Output only. Workflow start time."
        },
        "dagStartTime": {
          "description": "Output only. DAG start time, only set for workflows with dag_timeout when DAG begins.",
          "format": "google-datetime",
          "readOnly": true,
          "type": "string"
        },
        "dagEndTime": {
          "description": "Output only. DAG end time, only set for workflows with dag_timeout when DAG ends.",
          "readOnly": true,
          "type": "string",
          "format": "google-datetime"
        },
        "deleteCluster": {
          "description": "Output only. The delete cluster operation metadata.",
          "$ref": "ClusterOperation",
          "readOnly": true
        },
        "clusterName": {
          "description": "Output only. The name of the target cluster.",
          "readOnly": true,
          "type": "string"
        },
        "dagTimeout": {
          "description": "Output only. The timeout duration for the DAG of jobs, expressed in seconds (see JSON representation of duration (https://developers.google.com/protocol-buffers/docs/proto3#json)).",
          "format": "google-duration",
          "readOnly": true,
          "type": "string"
        }
      },
      "type": "object",
      "description": "A Dataproc workflow template resource."
    },
    "SparkPlanGraph": {
      "description": "A graph used for storing information of an executionPlan of DataFrame.",
      "id": "SparkPlanGraph",
      "properties": {
        "executionId": {
          "type": "string",
          "format": "int64"
        },
        "nodes": {
          "type": "array",
          "items": {
            "$ref": "SparkPlanGraphNodeWrapper"
          }
        },
        "edges": {
          "items": {
            "$ref": "SparkPlanGraphEdge"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "WorkflowTemplatePlacement": {
      "id": "WorkflowTemplatePlacement",
      "properties": {
        "managedCluster": {
          "description": "A cluster that is managed by the workflow.",
          "$ref": "ManagedCluster"
        },
        "clusterSelector": {
          "description": "Optional. A selector that chooses target cluster for jobs based on metadata.The selector is evaluated at the time each job is submitted.",
          "$ref": "ClusterSelector"
        }
      },
      "type": "object",
      "description": "Specifies workflow execution target.Either managed_cluster or cluster_selector is required."
    },
    "ResourceProfileInfo": {
      "description": "Resource profile that contains information about all the resources required by executors and tasks.",
      "type": "object",
      "id": "ResourceProfileInfo",
      "properties": {
        "taskResources": {
          "type": "object",
          "additionalProperties": {
            "$ref": "TaskResourceRequest"
          }
        },
        "resourceProfileId": {
          "type": "integer",
          "format": "int32"
        },
        "executorResources": {
          "type": "object",
          "additionalProperties": {
            "$ref": "ExecutorResourceRequest"
          }
        }
      }
    },
    "LifecycleConfig": {
      "type": "object",
      "id": "LifecycleConfig",
      "properties": {
        "autoStopTime": {
          "description": "Optional. The time when cluster will be auto-stopped (see JSON representation of Timestamp (https://developers.google.com/protocol-buffers/docs/proto3#json)).",
          "format": "google-datetime",
          "type": "string"
        },
        "autoDeleteTime": {
          "type": "string",
          "format": "google-datetime",
          "description": "Optional. The time when cluster will be auto-deleted (see JSON representation of Timestamp (https://developers.google.com/protocol-buffers/docs/proto3#json))."
        },
        "idleDeleteTtl": {
          "description": "Optional. The duration to keep the cluster alive while idling (when no jobs are running). Passing this threshold will cause the cluster to be deleted. Minimum value is 5 minutes; maximum value is 14 days (see JSON representation of Duration (https://developers.google.com/protocol-buffers/docs/proto3#json)).",
          "format": "google-duration",
          "type": "string"
        },
        "idleStopTtl": {
          "type": "string",
          "format": "google-duration",
          "description": "Optional. The duration to keep the cluster started while idling (when no jobs are running). Passing this threshold will cause the cluster to be stopped. Minimum value is 5 minutes; maximum value is 14 days (see JSON representation of Duration (https://developers.google.com/protocol-buffers/docs/proto3#json))."
        },
        "autoStopTtl": {
          "format": "google-duration",
          "type": "string",
          "description": "Optional. The lifetime duration of the cluster. The cluster will be auto-stopped at the end of this period, calculated from the time of submission of the create or update cluster request. Minimum value is 10 minutes; maximum value is 14 days (see JSON representation of Duration (https://developers.google.com/protocol-buffers/docs/proto3#json))."
        },
        "idleStartTime": {
          "description": "Output only. The time when cluster became idle (most recent job finished) and became eligible for deletion due to idleness (see JSON representation of Timestamp (https://developers.google.com/protocol-buffers/docs/proto3#json)).",
          "readOnly": true,
          "type": "string",
          "format": "google-datetime"
        },
        "autoDeleteTtl": {
          "description": "Optional. The lifetime duration of cluster. The cluster will be auto-deleted at the end of this period. Minimum value is 10 minutes; maximum value is 14 days (see JSON representation of Duration (https://developers.google.com/protocol-buffers/docs/proto3#json)).",
          "type": "string",
          "format": "google-duration"
        }
      },
      "description": "Specifies the cluster auto-delete schedule configuration."
    },
    "SearchSessionSparkApplicationStageAttemptTasksResponse": {
      "type": "object",
      "id": "SearchSessionSparkApplicationStageAttemptTasksResponse",
      "properties": {
        "sparkApplicationStageAttemptTasks": {
          "readOnly": true,
          "type": "array",
          "description": "Output only. Data corresponding to tasks created by spark.",
          "items": {
            "$ref": "TaskData"
          }
        },
        "nextPageToken": {
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSessionSparkApplicationStageAttemptTasksRequest.",
          "type": "string"
        }
      },
      "description": "List of tasks for a stage of a Spark Application"
    },
    "PySparkNotebookBatch": {
      "type": "object",
      "id": "PySparkNotebookBatch",
      "properties": {
        "pythonFileUris": {
          "type": "array",
          "description": "Optional. HCFS URIs of Python files to pass to the PySpark framework.",
          "items": {
            "type": "string"
          }
        },
        "jarFileUris": {
          "description": "Optional. HCFS URIs of jar files to be added to the Spark CLASSPATH.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "notebookFileUri": {
          "description": "Required. The HCFS URI of the notebook file to execute.",
          "type": "string"
        },
        "fileUris": {
          "type": "array",
          "description": "Optional. HCFS URIs of files to be placed in the working directory of each executor",
          "items": {
            "type": "string"
          }
        },
        "params": {
          "description": "Optional. The parameters to pass to the notebook.",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "archiveUris": {
          "type": "array",
          "description": "Optional. HCFS URIs of archives to be extracted into the working directory of each executor. Supported file types: .jar, .tar, .tar.gz, .tgz, and .zip.",
          "items": {
            "type": "string"
          }
        }
      },
      "description": "A configuration for running a PySpark Notebook batch workload."
    },
    "SearchSparkApplicationStageAttemptsResponse": {
      "type": "object",
      "id": "SearchSparkApplicationStageAttemptsResponse",
      "properties": {
        "sparkApplicationStageAttempts": {
          "readOnly": true,
          "type": "array",
          "description": "Output only. Data corresponding to a stage attempts",
          "items": {
            "$ref": "StageData"
          }
        },
        "nextPageToken": {
          "type": "string",
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent ListSparkApplicationStageAttemptsRequest."
        }
      },
      "description": "A list of Stage Attempts for a Stage of a Spark Application."
    },
    "EnvironmentConfig": {
      "type": "object",
      "id": "EnvironmentConfig",
      "properties": {
        "executionConfig": {
          "description": "Optional. Execution configuration for a workload.",
          "$ref": "ExecutionConfig"
        },
        "peripheralsConfig": {
          "description": "Optional. Peripherals configuration that workload has access to.",
          "$ref": "PeripheralsConfig"
        }
      },
      "description": "Environment configuration for a workload."
    },
    "SparkPlanGraphNodeWrapper": {
      "description": "Wrapper user to represent either a node or a cluster.",
      "type": "object",
      "id": "SparkPlanGraphNodeWrapper",
      "properties": {
        "node": {
          "$ref": "SparkPlanGraphNode"
        },
        "cluster": {
          "$ref": "SparkPlanGraphCluster"
        }
      }
    },
    "SearchSessionSparkApplicationJobsResponse": {
      "description": "A list of Jobs associated with a Spark Application.",
      "type": "object",
      "id": "SearchSessionSparkApplicationJobsResponse",
      "properties": {
        "sparkApplicationJobs": {
          "readOnly": true,
          "type": "array",
          "description": "Output only. Data corresponding to a spark job.",
          "items": {
            "$ref": "JobData"
          }
        },
        "nextPageToken": {
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSessionSparkApplicationJobsRequest.",
          "type": "string"
        }
      }
    },
    "AccessSparkApplicationEnvironmentInfoResponse": {
      "id": "AccessSparkApplicationEnvironmentInfoResponse",
      "properties": {
        "applicationEnvironmentInfo": {
          "description": "Details about the Environment that the application is running in.",
          "$ref": "ApplicationEnvironmentInfo"
        }
      },
      "type": "object",
      "description": "Environment details of a Saprk Application."
    },
    "StreamingQueryProgress": {
      "id": "StreamingQueryProgress",
      "properties": {
        "name": {
          "type": "string"
        },
        "eventTime": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "stateOperators": {
          "items": {
            "$ref": "StateOperatorProgress"
          },
          "type": "array"
        },
        "sink": {
          "$ref": "SinkProgress"
        },
        "observedMetrics": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "batchDuration": {
          "type": "string",
          "format": "int64"
        },
        "sources": {
          "items": {
            "$ref": "SourceProgress"
          },
          "type": "array"
        },
        "timestamp": {
          "type": "string"
        },
        "durationMillis": {
          "additionalProperties": {
            "format": "int64",
            "type": "string"
          },
          "type": "object"
        },
        "streamingQueryProgressId": {
          "type": "string"
        },
        "runId": {
          "type": "string"
        },
        "batchId": {
          "format": "int64",
          "type": "string"
        }
      },
      "type": "object"
    },
    "SummarizeSparkApplicationExecutorsResponse": {
      "type": "object",
      "id": "SummarizeSparkApplicationExecutorsResponse",
      "properties": {
        "totalExecutorSummary": {
          "description": "Overall consolidated summary for all executors.",
          "$ref": "ConsolidatedExecutorSummary"
        },
        "activeExecutorSummary": {
          "description": "Consolidated summary for active executors.",
          "$ref": "ConsolidatedExecutorSummary"
        },
        "applicationId": {
          "description": "Spark Application Id",
          "type": "string"
        },
        "deadExecutorSummary": {
          "description": "Consolidated summary for dead executors.",
          "$ref": "ConsolidatedExecutorSummary"
        }
      },
      "description": "Consolidated summary of executors for a Spark Application."
    },
    "AppSummary": {
      "type": "object",
      "id": "AppSummary",
      "properties": {
        "numCompletedJobs": {
          "format": "int32",
          "type": "integer"
        },
        "numCompletedStages": {
          "format": "int32",
          "type": "integer"
        }
      }
    },
    "TerminateSessionRequest": {
      "description": "A request to terminate an interactive session.",
      "type": "object",
      "id": "TerminateSessionRequest",
      "properties": {
        "requestId": {
          "description": "Optional. A unique ID used to identify the request. If the service receives two TerminateSessionRequest (https://cloud.google.com/dataproc/docs/reference/rpc/google.cloud.dataproc.v1#google.cloud.dataproc.v1.TerminateSessionRequest)s with the same ID, the second request is ignored.Recommendation: Set this value to a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier).The value must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), and hyphe[...]",
          "type": "string"
        }
      }
    },
    "SparkSqlJob": {
      "type": "object",
      "id": "SparkSqlJob",
      "properties": {
        "properties": {
          "description": "Optional. A mapping of property names to values, used to configure Spark SQL's SparkConf. Properties that conflict with values set by the Dataproc API might be overwritten.",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "queryList": {
          "description": "A list of queries.",
          "$ref": "QueryList"
        },
        "scriptVariables": {
          "description": "Optional. Mapping of query variable names to values (equivalent to the Spark SQL command: SET name=\"value\";).",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "jarFileUris": {
          "description": "Optional. HCFS URIs of jar files to be added to the Spark CLASSPATH.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "loggingConfig": {
          "description": "Optional. The runtime log config for job execution.",
          "$ref": "LoggingConfig"
        },
        "queryFileUri": {
          "type": "string",
          "description": "The HCFS URI of the script that contains SQL queries."
        }
      },
      "description": "A Dataproc job for running Apache Spark SQL (https://spark.apache.org/sql/) queries."
    },
    "NodeGroupAffinity": {
      "id": "NodeGroupAffinity",
      "properties": {
        "nodeGroupUri": {
          "type": "string",
          "description": "Required. The URI of a sole-tenant node group resource (https://cloud.google.com/compute/docs/reference/rest/v1/nodeGroups) that the cluster will be created on.A full URL, partial URI, or node group name are valid. Examples: https://www.googleapis.com/compute/v1/projects/[project_id]/zones/[zone]/nodeGroups/node-group-1 projects/[project_id]/zones/[zone]/nodeGroups/node-group-1 node-group-1"
        }
      },
      "type": "object",
      "description": "Node Group Affinity for clusters using sole-tenant node groups. The Dataproc NodeGroupAffinity resource is not related to the Dataproc NodeGroup resource."
    },
    "RuntimeConfig": {
      "description": "Runtime configuration for a workload.",
      "id": "RuntimeConfig",
      "properties": {
        "containerImage": {
          "type": "string",
          "description": "Optional. Optional custom container image for the job runtime environment. If not specified, a default container image will be used."
        },
        "repositoryConfig": {
          "description": "Optional. Dependency repository configuration.",
          "$ref": "RepositoryConfig"
        },
        "version": {
          "type": "string",
          "description": "Optional. Version of the batch runtime."
        },
        "autotuningConfig": {
          "description": "Optional. Autotuning configuration of the workload.",
          "$ref": "AutotuningConfig"
        },
        "cohort": {
          "description": "Optional. Cohort identifier. Identifies families of the workloads that have the same shape, for example, daily ETL jobs.",
          "type": "string"
        },
        "properties": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object",
          "description": "Optional. A mapping of property names to values, which are used to configure workload execution."
        }
      },
      "type": "object"
    },
    "OutputQuantileMetrics": {
      "type": "object",
      "id": "OutputQuantileMetrics",
      "properties": {
        "bytesWritten": {
          "$ref": "Quantiles"
        },
        "recordsWritten": {
          "$ref": "Quantiles"
        }
      }
    },
    "AttachedDiskConfig": {
      "description": "Specifies the config of attached disk options for single VM instance.",
      "type": "object",
      "id": "AttachedDiskConfig",
      "properties": {
        "provisionedThroughput": {
          "description": "Optional. Indicates how much throughput to provision for the attached disk. This sets the number of throughput mb per second that the disk can handle. See https://cloud.google.com/compute/docs/disks/hyperdisks#hyperdisk-features",
          "type": "string",
          "format": "int64"
        },
        "diskSizeGb": {
          "description": "Optional. Disk size in GB.",
          "type": "integer",
          "format": "int32"
        },
        "diskType": {
          "description": "Optional. Disk type.",
          "enumDescriptions": [
            "Required unspecified disk type.",
            "Hyperdisk Balanced disk type.",
            "Hyperdisk Extreme disk type.",
            "Hyperdisk ML disk type.",
            "Hyperdisk Throughput disk type."
          ],
          "enum": [
            "DISK_TYPE_UNSPECIFIED",
            "HYPERDISK_BALANCED",
            "HYPERDISK_EXTREME",
            "HYPERDISK_ML",
            "HYPERDISK_THROUGHPUT"
          ],
          "type": "string"
        },
        "provisionedIops": {
          "description": "Optional. Indicates how many IOPS to provision for the attached disk. This sets the number of I/O operations per second that the disk can handle. See https://cloud.google.com/compute/docs/disks/hyperdisks#hyperdisk-features",
          "type": "string",
          "format": "int64"
        }
      }
    },
    "RepairClusterRequest": {
      "description": "A request to repair a cluster.",
      "id": "RepairClusterRequest",
      "properties": {
        "gracefulDecommissionTimeout": {
          "description": "Optional. Timeout for graceful YARN decommissioning. Graceful decommissioning facilitates the removal of cluster nodes without interrupting jobs in progress. The timeout specifies the amount of time to wait for jobs finish before forcefully removing nodes. The default timeout is 0 for forceful decommissioning, and the maximum timeout period is 1 day. (see JSON Mapping—Duration (https://developers.google.com/protocol-buffers/docs/proto3#json)).graceful_decommission_timeo[...]",
          "format": "google-duration",
          "type": "string"
        },
        "clusterUuid": {
          "type": "string",
          "description": "Optional. Specifying the cluster_uuid means the RPC will fail (with error NOT_FOUND) if a cluster with the specified UUID does not exist."
        },
        "dataprocSuperUser": {
          "type": "boolean",
          "description": "Optional. Whether the request is submitted by Dataproc super user. If true, IAM will check 'dataproc.clusters.repair' permission instead of 'dataproc.clusters.update' permission. This is to give Dataproc superuser the ability to repair clusters without granting the overly broad update permission."
        },
        "parentOperationId": {
          "type": "string",
          "description": "Optional. operation id of the parent operation sending the repair request"
        },
        "requestId": {
          "type": "string",
          "description": "Optional. A unique ID used to identify the request. If the server receives two RepairClusterRequests with the same ID, the second request is ignored, and the first google.longrunning.Operation created and stored in the backend is returned.Recommendation: Set this value to a UUID (https://en.wikipedia.org/wiki/Universally_unique_identifier).The ID must contain only letters (a-z, A-Z), numbers (0-9), underscores (_), and hyphens (-). The maximum length is 40 characters."
        },
        "nodePools": {
          "type": "array",
          "description": "Optional. Node pools and corresponding repair action to be taken. All node pools should be unique in this request. i.e. Multiple entries for the same node pool id are not allowed.",
          "items": {
            "$ref": "NodePool"
          }
        },
        "cluster": {
          "description": "Optional. Cluster to be repaired",
          "$ref": "ClusterToRepair"
        }
      },
      "type": "object"
    },
    "ShuffleReadMetrics": {
      "description": "Shuffle data read by the task.",
      "type": "object",
      "id": "ShuffleReadMetrics",
      "properties": {
        "localBlocksFetched": {
          "type": "string",
          "format": "int64"
        },
        "remoteBytesRead": {
          "type": "string",
          "format": "int64"
        },
        "recordsRead": {
          "format": "int64",
          "type": "string"
        },
        "localBytesRead": {
          "format": "int64",
          "type": "string"
        },
        "fetchWaitTimeMillis": {
          "type": "string",
          "format": "int64"
        },
        "shufflePushReadMetrics": {
          "$ref": "ShufflePushReadMetrics"
        },
        "remoteBytesReadToDisk": {
          "type": "string",
          "format": "int64"
        },
        "remoteBlocksFetched": {
          "type": "string",
          "format": "int64"
        },
        "remoteReqsDuration": {
          "type": "string",
          "format": "int64"
        }
      }
    },
    "UsageSnapshot": {
      "description": "The usage snapshot represents the resources consumed by a workload at a specified time.",
      "type": "object",
      "id": "UsageSnapshot",
      "properties": {
        "shuffleStorageGbPremium": {
          "description": "Optional. Shuffle Storage in gigabytes (GB) charged at premium tier. (see Dataproc Serverless pricing (https://cloud.google.com/dataproc-serverless/pricing))",
          "type": "string",
          "format": "int64"
        },
        "shuffleStorageGb": {
          "format": "int64",
          "type": "string",
          "description": "Optional. Shuffle Storage in gigabytes (GB). (see Dataproc Serverless pricing (https://cloud.google.com/dataproc-serverless/pricing))"
        },
        "milliAccelerator": {
          "format": "int64",
          "type": "string",
          "description": "Optional. Milli (one-thousandth) accelerator. (see Dataproc Serverless pricing (https://cloud.google.com/dataproc-serverless/pricing))"
        },
        "milliDcu": {
          "description": "Optional. Milli (one-thousandth) Dataproc Compute Units (DCUs) (see Dataproc Serverless pricing (https://cloud.google.com/dataproc-serverless/pricing)).",
          "type": "string",
          "format": "int64"
        },
        "acceleratorType": {
          "description": "Optional. Accelerator type being used, if any",
          "type": "string"
        },
        "milliDcuPremium": {
          "description": "Optional. Milli (one-thousandth) Dataproc Compute Units (DCUs) charged at premium tier (see Dataproc Serverless pricing (https://cloud.google.com/dataproc-serverless/pricing)).",
          "type": "string",
          "format": "int64"
        },
        "snapshotTime": {
          "format": "google-datetime",
          "type": "string",
          "description": "Optional. The timestamp of the usage snapshot."
        }
      }
    },
    "ListSessionsResponse": {
      "description": "A list of interactive sessions.",
      "type": "object",
      "id": "ListSessionsResponse",
      "properties": {
        "sessions": {
          "description": "Output only. The sessions from the specified collection.",
          "items": {
            "$ref": "Session"
          },
          "readOnly": true,
          "type": "array"
        },
        "nextPageToken": {
          "description": "A token, which can be sent as page_token, to retrieve the next page. If this field is omitted, there are no subsequent pages.",
          "type": "string"
        }
      }
    },
    "JobsSummary": {
      "id": "JobsSummary",
      "properties": {
        "applicationId": {
          "type": "string",
          "description": "Spark Application Id"
        },
        "failedJobs": {
          "format": "int32",
          "type": "integer",
          "description": "Number of failed jobs"
        },
        "activeJobs": {
          "format": "int32",
          "type": "integer",
          "description": "Number of active jobs"
        },
        "completedJobs": {
          "type": "integer",
          "format": "int32",
          "description": "Number of completed jobs"
        },
        "attempts": {
          "type": "array",
          "description": "Attempts info",
          "items": {
            "$ref": "ApplicationAttemptInfo"
          }
        },
        "schedulingMode": {
          "description": "Spark Scheduling mode",
          "type": "string"
        }
      },
      "type": "object",
      "description": "Data related to Jobs page summary"
    },
    "Binding": {
      "id": "Binding",
      "properties": {
        "condition": {
          "description": "The condition that is associated with this binding.If the condition evaluates to true, then this binding applies to the current request.If the condition evaluates to false, then this binding does not apply to the current request. However, a different role binding might grant the same role to one or more of the principals in this binding.To learn which resources support conditions in their IAM policies, see the IAM documentation (https://cloud.google.com/iam/help/conditi[...]",
          "$ref": "Expr"
        },
        "role": {
          "description": "Role that is assigned to the list of members, or principals. For example, roles/viewer, roles/editor, or roles/owner.For an overview of the IAM roles and permissions, see the IAM documentation (https://cloud.google.com/iam/docs/roles-overview). For a list of the available pre-defined roles, see here (https://cloud.google.com/iam/docs/understanding-roles).",
          "type": "string"
        },
        "members": {
          "description": "Specifies the principals requesting access for a Google Cloud resource. members can have the following values: allUsers: A special identifier that represents anyone who is on the internet; with or without a Google account. allAuthenticatedUsers: A special identifier that represents anyone who is authenticated with a Google account or a service account. Does not include identities that come from external identity providers (IdPs) through identity federation. user:{emaili[...]",
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object",
      "description": "Associates members, or principals, with a role."
    },
    "WriteSessionSparkApplicationContextResponse": {
      "description": "Response returned as an acknowledgement of receipt of data.",
      "type": "object",
      "id": "WriteSessionSparkApplicationContextResponse",
      "properties": {}
    },
    "DiagnoseClusterResults": {
      "description": "The location of diagnostic output.",
      "type": "object",
      "id": "DiagnoseClusterResults",
      "properties": {
        "outputUri": {
          "description": "Output only. The Cloud Storage URI of the diagnostic output. The output report is a plain text file with a summary of collected diagnostics.",
          "readOnly": true,
          "type": "string"
        }
      }
    },
    "StateOperatorProgress": {
      "id": "StateOperatorProgress",
      "properties": {
        "numRowsUpdated": {
          "format": "int64",
          "type": "string"
        },
        "numRowsRemoved": {
          "format": "int64",
          "type": "string"
        },
        "allUpdatesTimeMs": {
          "format": "int64",
          "type": "string"
        },
        "allRemovalsTimeMs": {
          "type": "string",
          "format": "int64"
        },
        "commitTimeMs": {
          "type": "string",
          "format": "int64"
        },
        "operatorName": {
          "type": "string"
        },
        "numRowsTotal": {
          "type": "string",
          "format": "int64"
        },
        "customMetrics": {
          "type": "object",
          "additionalProperties": {
            "format": "int64",
            "type": "string"
          }
        },
        "numRowsDroppedByWatermark": {
          "format": "int64",
          "type": "string"
        },
        "numStateStoreInstances": {
          "type": "string",
          "format": "int64"
        },
        "numShufflePartitions": {
          "format": "int64",
          "type": "string"
        },
        "memoryUsedBytes": {
          "type": "string",
          "format": "int64"
        }
      },
      "type": "object"
    },
    "ValueInfo": {
      "id": "ValueInfo",
      "properties": {
        "annotation": {
          "type": "string",
          "description": "Annotation, comment or explanation why the property was set."
        },
        "overriddenValue": {
          "type": "string",
          "description": "Optional. Value which was replaced by the corresponding component."
        },
        "value": {
          "type": "string",
          "description": "Property value."
        }
      },
      "type": "object",
      "description": "Annotatated property value."
    },
    "ConsolidatedExecutorSummary": {
      "description": "Consolidated summary about executors used by the application.",
      "id": "ConsolidatedExecutorSummary",
      "properties": {
        "totalShuffleWrite": {
          "format": "int64",
          "type": "string"
        },
        "memoryUsed": {
          "type": "string",
          "format": "int64"
        },
        "rddBlocks": {
          "type": "integer",
          "format": "int32"
        },
        "maxMemory": {
          "type": "string",
          "format": "int64"
        },
        "completedTasks": {
          "type": "integer",
          "format": "int32"
        },
        "totalTasks": {
          "format": "int32",
          "type": "integer"
        },
        "totalInputBytes": {
          "format": "int64",
          "type": "string"
        },
        "activeTasks": {
          "type": "integer",
          "format": "int32"
        },
        "isExcluded": {
          "type": "integer",
          "format": "int32"
        },
        "diskUsed": {
          "format": "int64",
          "type": "string"
        },
        "totalGcTimeMillis": {
          "type": "string",
          "format": "int64"
        },
        "totalDurationMillis": {
          "format": "int64",
          "type": "string"
        },
        "count": {
          "type": "integer",
          "format": "int32"
        },
        "totalShuffleRead": {
          "format": "int64",
          "type": "string"
        },
        "failedTasks": {
          "format": "int32",
          "type": "integer"
        },
        "memoryMetrics": {
          "$ref": "MemoryMetrics"
        },
        "totalCores": {
          "type": "integer",
          "format": "int32"
        }
      },
      "type": "object"
    },
    "StageInputMetrics": {
      "type": "object",
      "id": "StageInputMetrics",
      "properties": {
        "recordsRead": {
          "type": "string",
          "format": "int64"
        },
        "bytesRead": {
          "format": "int64",
          "type": "string"
        }
      },
      "description": "Metrics about the input read by the stage."
    },
    "NodeGroup": {
      "description": "Dataproc Node Group. The Dataproc NodeGroup resource is not related to the Dataproc NodeGroupAffinity resource.",
      "type": "object",
      "id": "NodeGroup",
      "properties": {
        "name": {
          "description": "The Node group resource name (https://aip.dev/122).",
          "type": "string"
        },
        "nodeGroupConfig": {
          "description": "Optional. The node group instance group configuration.",
          "$ref": "InstanceGroupConfig"
        },
        "labels": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          },
          "description": "Optional. Node group labels. Label keys must consist of from 1 to 63 characters and conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). Label values can be empty. If specified, they must consist of from 1 to 63 characters and conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). The node group must have no more than 32 labels."
        },
        "roles": {
          "description": "Required. Node group roles.",
          "items": {
            "enumDescriptions": [
              "Required unspecified role.",
              "Job drivers run on the node pool."
            ],
            "enum": [
              "ROLE_UNSPECIFIED",
              "DRIVER"
            ],
            "type": "string"
          },
          "type": "array"
        }
      }
    },
    "ExecutorPeakMetricsDistributions": {
      "id": "ExecutorPeakMetricsDistributions",
      "properties": {
        "quantiles": {
          "items": {
            "format": "double",
            "type": "number"
          },
          "type": "array"
        },
        "executorMetrics": {
          "type": "array",
          "items": {
            "$ref": "ExecutorMetrics"
          }
        }
      },
      "type": "object"
    },
    "JobStatus": {
      "id": "JobStatus",
      "properties": {
        "details": {
          "description": "Optional. Output only. Job state details, such as an error description if the state is ERROR.",
          "readOnly": true,
          "type": "string"
        },
        "substate": {
          "description": "Output only. Additional state information, which includes status reported by the agent.",
          "readOnly": true,
          "type": "string",
          "enumDescriptions": [
            "The job substate is unknown.",
            "The Job is submitted to the agent.Applies to RUNNING state.",
            "The Job has been received and is awaiting execution (it might be waiting for a condition to be met). See the \"details\" field for the reason for the delay.Applies to RUNNING state.",
            "The agent-reported status is out of date, which can be caused by a loss of communication between the agent and Dataproc. If the agent does not send a timely update, the job will fail.Applies to RUNNING state."
          ],
          "enum": [
            "UNSPECIFIED",
            "SUBMITTED",
            "QUEUED",
            "STALE_STATUS"
          ]
        },
        "state": {
          "enumDescriptions": [
            "The job state is unknown.",
            "The job is pending; it has been submitted, but is not yet running.",
            "Job has been received by the service and completed initial setup; it will soon be submitted to the cluster.",
            "The job is running on the cluster.",
            "A CancelJob request has been received, but is pending.",
            "Transient in-flight resources have been canceled, and the request to cancel the running job has been issued to the cluster.",
            "The job cancellation was successful.",
            "The job has completed successfully.",
            "The job has completed, but encountered an error.",
            "Job attempt has failed. The detail field contains failure details for this attempt.Applies to restartable jobs only."
          ],
          "enum": [
            "STATE_UNSPECIFIED",
            "PENDING",
            "SETUP_DONE",
            "RUNNING",
            "CANCEL_PENDING",
            "CANCEL_STARTED",
            "CANCELLED",
            "DONE",
            "ERROR",
            "ATTEMPT_FAILURE"
          ],
          "description": "Output only. A state message specifying the overall job state.",
          "readOnly": true,
          "type": "string"
        },
        "stateStartTime": {
          "description": "Output only. The time when this state was entered.",
          "readOnly": true,
          "type": "string",
          "format": "google-datetime"
        }
      },
      "type": "object",
      "description": "Dataproc job status."
    },
    "ShuffleWriteQuantileMetrics": {
      "type": "object",
      "id": "ShuffleWriteQuantileMetrics",
      "properties": {
        "writeRecords": {
          "$ref": "Quantiles"
        },
        "writeTimeNanos": {
          "$ref": "Quantiles"
        },
        "writeBytes": {
          "$ref": "Quantiles"
        }
      }
    },
    "InstanceFlexibilityPolicy": {
      "description": "Instance flexibility Policy allowing a mixture of VM shapes and provisioning models.",
      "type": "object",
      "id": "InstanceFlexibilityPolicy",
      "properties": {
        "instanceSelectionResults": {
          "readOnly": true,
          "type": "array",
          "description": "Output only. A list of instance selection results in the group.",
          "items": {
            "$ref": "InstanceSelectionResult"
          }
        },
        "instanceMachineTypes": {
          "description": "Output only. A map of instance short name to machine type. The key is the short name of the Compute Engine instance, and the value is the full machine-type name (e.g., 'n1-standard-16'). See Machine types for more information on valid machine type strings.",
          "readOnly": true,
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "provisioningModelMix": {
          "description": "Optional. Defines how the Group selects the provisioning model to ensure required reliability.",
          "$ref": "ProvisioningModelMix"
        },
        "instanceSelectionList": {
          "description": "Optional. List of instance selection options that the group will use when creating new VMs.",
          "items": {
            "$ref": "InstanceSelection"
          },
          "type": "array"
        }
      }
    },
    "BuildInfo": {
      "id": "BuildInfo",
      "properties": {
        "buildValue": {
          "description": "Optional. Build value.",
          "type": "string"
        },
        "buildKey": {
          "type": "string",
          "description": "Optional. Build key."
        }
      },
      "type": "object",
      "description": "Native Build Info"
    },
    "AutotuningConfig": {
      "type": "object",
      "id": "AutotuningConfig",
      "properties": {
        "scenarios": {
          "description": "Optional. Scenarios for which tunings are applied.",
          "items": {
            "type": "string",
            "enumDescriptions": [
              "Default value.",
              "Scaling recommendations such as initialExecutors.",
              "Adding hints for potential relation broadcasts.",
              "Memory management for workloads.",
              "No autotuning.",
              "Automatic selection of scenarios."
            ],
            "enum": [
              "SCENARIO_UNSPECIFIED",
              "SCALING",
              "BROADCAST_HASH_JOIN",
              "MEMORY",
              "NONE",
              "AUTO"
            ]
          },
          "type": "array"
        }
      },
      "description": "Autotuning configuration of the workload."
    },
    "JobData": {
      "type": "object",
      "id": "JobData",
      "properties": {
        "name": {
          "type": "string"
        },
        "numFailedStages": {
          "type": "integer",
          "format": "int32"
        },
        "numTasks": {
          "type": "integer",
          "format": "int32"
        },
        "numFailedTasks": {
          "format": "int32",
          "type": "integer"
        },
        "sqlExecutionId": {
          "type": "string",
          "format": "int64"
        },
        "numActiveTasks": {
          "type": "integer",
          "format": "int32"
        },
        "numCompletedStages": {
          "format": "int32",
          "type": "integer"
        },
        "stageIds": {
          "items": {
            "type": "string",
            "format": "int64"
          },
          "type": "array"
        },
        "jobId": {
          "type": "string",
          "format": "int64"
        },
        "status": {
          "enumDescriptions": [
            "",
            "",
            "",
            "",
            ""
          ],
          "enum": [
            "JOB_EXECUTION_STATUS_UNSPECIFIED",
            "JOB_EXECUTION_STATUS_RUNNING",
            "JOB_EXECUTION_STATUS_SUCCEEDED",
            "JOB_EXECUTION_STATUS_FAILED",
            "JOB_EXECUTION_STATUS_UNKNOWN"
          ],
          "type": "string"
        },
        "numActiveStages": {
          "type": "integer",
          "format": "int32"
        },
        "description": {
          "type": "string"
        },
        "numSkippedStages": {
          "format": "int32",
          "type": "integer"
        },
        "jobGroup": {
          "type": "string"
        },
        "completionTime": {
          "type": "string",
          "format": "google-datetime"
        },
        "numKilledTasks": {
          "type": "integer",
          "format": "int32"
        },
        "numCompletedIndices": {
          "format": "int32",
          "type": "integer"
        },
        "numCompletedTasks": {
          "type": "integer",
          "format": "int32"
        },
        "skippedStages": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          }
        },
        "submissionTime": {
          "type": "string",
          "format": "google-datetime"
        },
        "numSkippedTasks": {
          "type": "integer",
          "format": "int32"
        },
        "killTasksSummary": {
          "type": "object",
          "additionalProperties": {
            "format": "int32",
            "type": "integer"
          }
        }
      },
      "description": "Data corresponding to a spark job."
    },
    "SparkPlanGraphEdge": {
      "type": "object",
      "id": "SparkPlanGraphEdge",
      "properties": {
        "fromId": {
          "type": "string",
          "format": "int64"
        },
        "toId": {
          "format": "int64",
          "type": "string"
        }
      },
      "description": "Represents a directed edge in the spark plan tree from child to parent."
    },
    "SinkProgress": {
      "id": "SinkProgress",
      "properties": {
        "numOutputRows": {
          "format": "int64",
          "type": "string"
        },
        "metrics": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "description": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "Session": {
      "description": "A representation of a session.",
      "id": "Session",
      "properties": {
        "name": {
          "type": "string",
          "description": "Identifier. The resource name of the session."
        },
        "creator": {
          "readOnly": true,
          "type": "string",
          "description": "Output only. The email address of the user who created the session."
        },
        "sparkConnectSession": {
          "description": "Optional. Spark connect session config.",
          "$ref": "SparkConnectConfig"
        },
        "jupyterSession": {
          "description": "Optional. Jupyter session config.",
          "$ref": "JupyterConfig"
        },
        "runtimeInfo": {
          "description": "Output only. Runtime information about session execution.",
          "$ref": "RuntimeInfo",
          "readOnly": true
        },
        "stateTime": {
          "description": "Output only. The time when the session entered the current state.",
          "format": "google-datetime",
          "readOnly": true,
          "type": "string"
        },
        "stateMessage": {
          "readOnly": true,
          "type": "string",
          "description": "Output only. Session state details, such as the failure description if the state is FAILED."
        },
        "runtimeConfig": {
          "description": "Optional. Runtime configuration for the session execution.",
          "$ref": "RuntimeConfig"
        },
        "createTime": {
          "description": "Output only. The time when the session was created.",
          "format": "google-datetime",
          "readOnly": true,
          "type": "string"
        },
        "labels": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object",
          "description": "Optional. The labels to associate with the session. Label keys must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). Label values may be empty, but, if present, must contain 1 to 63 characters, and must conform to RFC 1035 (https://www.ietf.org/rfc/rfc1035.txt). No more than 32 labels can be associated with a session."
        },
        "environmentConfig": {
          "description": "Optional. Environment configuration for the session execution.",
          "$ref": "EnvironmentConfig"
        },
        "uuid": {
          "description": "Output only. A session UUID (Unique Universal Identifier). The service generates this value when it creates the session.",
          "readOnly": true,
          "type": "string"
        },
        "user": {
          "type": "string",
          "description": "Optional. The email address of the user who owns the session."
        },
        "state": {
          "enumDescriptions": [
            "The session state is unknown.",
            "The session is created prior to running.",
            "The session is running.",
            "The session is terminating.",
            "The session is terminated successfully.",
            "The session is no longer running due to an error."
          ],
          "enum": [
            "STATE_UNSPECIFIED",
            "CREATING",
            "ACTIVE",
            "TERMINATING",
            "TERMINATED",
            "FAILED"
          ],
          "readOnly": true,
          "type": "string",
          "description": "Output only. A state of the session."
        },
        "sessionTemplate": {
          "description": "Optional. The session template used by the session.Only resource names, including project ID and location, are valid.Example: * https://www.googleapis.com/compute/v1/projects/[project_id]/locations/[dataproc_region]/sessionTemplates/[template_id] * projects/[project_id]/locations/[dataproc_region]/sessionTemplates/[template_id]The template must be in the same project and Dataproc region as the session.",
          "type": "string"
        },
        "stateHistory": {
          "description": "Output only. Historical state information for the session.",
          "items": {
            "$ref": "SessionStateHistory"
          },
          "readOnly": true,
          "type": "array"
        }
      },
      "type": "object"
    },
    "SearchSparkApplicationSqlQueriesResponse": {
      "id": "SearchSparkApplicationSqlQueriesResponse",
      "properties": {
        "sparkApplicationSqlQueries": {
          "description": "Output only. SQL Execution Data",
          "items": {
            "$ref": "SqlExecutionUiData"
          },
          "readOnly": true,
          "type": "array"
        },
        "nextPageToken": {
          "type": "string",
          "description": "This token is included in the response if there are more results to fetch. To fetch additional results, provide this value as the page_token in a subsequent SearchSparkApplicationSqlQueriesRequest."
        }
      },
      "type": "object",
      "description": "List of all queries for a Spark Application."
    },
    "ApplicationEnvironmentInfo": {
      "id": "ApplicationEnvironmentInfo",
      "properties": {
        "classpathEntries": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "runtime": {
          "$ref": "SparkRuntimeInfo"
        },
        "resourceProfiles": {
          "type": "array",
          "items": {
            "$ref": "ResourceProfileInfo"
          }
        },
        "hadoopProperties": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "metricsProperties": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "sparkProperties": {
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "systemProperties": {
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        }
      },
      "type": "object",
      "description": "Details about the Environment that the application is running in."
    },
    "TemplateParameter": {
      "type": "object",
      "id": "TemplateParameter",
      "properties": {
        "description": {
          "type": "string",
          "description": "Optional. Brief description of the parameter. Must not exceed 1024 characters."
        },
        "validation": {
          "description": "Optional. Validation rules to be applied to this parameter's value.",
          "$ref": "ParameterValidation"
        },
        "fields": {
          "description": "Required. Paths to all fields that the parameter replaces. A field is allowed to appear in at most one parameter's list of field paths.A field path is similar in syntax to a google.protobuf.FieldMask. For example, a field path that references the zone field of a workflow template's cluster selector would be specified as placement.clusterSelector.zone.Also, field paths can reference fields using the following syntax: Values in maps can be referenced by key: labels'key' p[...]",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "name": {
          "type": "string",
          "description": "Required. Parameter name. The parameter name is used as the key, and paired with the parameter value, which are passed to the template when the template is instantiated. The name must contain only capital letters (A-Z), numbers (0-9), and underscores (_), and must not start with a number. The maximum length is 40 characters."
        }
      },
      "description": "A configurable parameter that replaces one or more fields in the template. Parameterizable fields: - Labels - File uris - Job properties - Job arguments - Script variables - Main class (in HadoopJob and SparkJob) - Zone (in ClusterSelector)"
    },
    "SparkRJob": {
      "description": "A Dataproc job for running Apache SparkR (https://spark.apache.org/docs/latest/sparkr.html) applications on YARN.",
      "type": "object",
      "id": "SparkRJob",
      "properties": {
        "properties": {
          "description": "Optional. A mapping of property names to values, used to configure SparkR. Properties that conflict with values set by the Dataproc API might be overwritten. Can include properties set in /etc/spark/conf/spark-defaults.conf and classes in user code.",
          "additionalProperties": {
            "type": "string"
          },
          "type": "object"
        },
        "mainRFileUri": {
          "type": "string",
          "description": "Required. The HCFS URI of the main R file to use as the driver. Must be a .R file."
        },
        "args": {
          "type": "array",
          "description": "Optional. The arguments to pass to the driver. Do not include arguments, such as --conf, that can be set as job properties, since a collision may occur that causes an incorrect job submission.",
          "items": {
            "type": "string"
          }
        },
        "fileUris": {
          "description": "Optional. HCFS URIs of files to be placed in the working directory of each executor. Useful for naively parallel tasks.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "archiveUris": {
          "description": "Optional. HCFS URIs of archives to be extracted into the working directory of each executor. Supported file types: .jar, .tar, .tar.gz, .tgz, and .zip.",
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "loggingConfig": {
          "description": "Optional. The runtime log config for job execution.",
          "$ref": "LoggingConfig"
        }
      }
    },
    "RddOperationCluster": {
      "id": "RddOperationCluster",
      "properties": {
        "childNodes": {
          "items": {
            "$ref": "RddOperationNode"
          },
          "type": "array"
        },
        "rddClusterId": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "childClusters": {
          "type": "array",
          "items": {
            "$ref": "RddOperationCluster"
          }
        }
      },
      "type": "object",
      "description": "A grouping of nodes representing higher level constructs (stage, job etc.)."
    },
    "GkeNodeConfig": {
      "description": "Parameters that describe cluster nodes.",
      "id": "GkeNodeConfig",
      "properties": {
        "accelerators": {
          "description": "Optional. A list of hardware accelerators (https://cloud.google.com/compute/docs/gpus) to attach to each node.",
          "items": {
            "$ref": "GkeNodePoolAcceleratorConfig"
          },
          "type": "array"
        },
        "preemptible": {
          "type": "boolean",
          "description": "Optional. Whether the nodes are created as legacy preemptible VM instances (https://cloud.google.com/compute/docs/instances/preemptible). Also see Spot VMs, preemptible VM instances without a maximum lifetime. Legacy and Spot preemptible nodes cannot be used in a node pool with the CONTROLLER role or in the DEFAULT node pool if the CONTROLLER role is not assigned (the DEFAULT node pool will assume the CONTROLLER role)."
        },
        "bootDiskKmsKey": {
[...]
