{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        }
      }
    }
  },
  "revision": "20260310",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "canonicalName": "Dfareporting",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "basePath": "/dfareporting/v4/",
  "ownerName": "Google",
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "servicePath": "dfareporting/v4/",
  "name": "dfareporting",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "ownerDomain": "google.com",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://dfareporting.googleapis.com/",
  "version": "v4",
  "protocol": "rest",
  "resources": {
    "billingAssignments": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "id": "dfareporting.billingAssignments.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "id": "dfareporting.billingAssignments.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing assignments.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets the account's active ad summary by account ID.",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "httpMethod": "GET"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "id": "dfareporting.metros.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of metros.",
          "path": "userprofiles/{+profileId}/metros"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "list": {
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight configuration.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "PUT"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "id": "dfareporting.floodlightConfigurations.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight configuration by ID.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "httpMethod": "GET"
        }
      }
    },
    "orders": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders/{+id}",
          "description": "Gets one order by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.orders.get",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders/{ordersId}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.orders.list",
          "httpMethod": "GET"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "id": "dfareporting.advertiserInvoices.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.list",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.patch",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.placementStrategies.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}"
        },
        "get": {
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "description": "Gets one placement strategy by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.get",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.placementStrategies.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Inserts a new placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.delete",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "description": "Deletes an existing content category."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "id": "dfareporting.contentCategories.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing content category. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "PATCH"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.get",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "description": "Gets one content category by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new content category.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "id": "dfareporting.contentCategories.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "POST"
        },
        "list": {
          "id": "dfareporting.contentCategories.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Updates an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.update",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.remarketingListShares.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.patch",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "httpMethod": "PATCH"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.update",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share.",
          "httpMethod": "PUT"
        }
      }
    },
    "ads": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/ads",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.patch",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "PATCH"
        },
        "get": {
          "id": "dfareporting.ads.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "description": "Gets one ad by ID.",
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Inserts a new ad.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.insert",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.list"
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.update",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Updates an existing ad."
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already."
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaignCreativeAssociations.list"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one mobile carrier by ID.",
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "id": "dfareporting.mobileCarriers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileCarriers.list",
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "description": "Retrieves a list of mobile carriers.",
          "httpMethod": "GET"
        }
      }
    },
    "placements": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.placements.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placements"
        },
        "generatetags": {
          "description": "Generates tags for a placement.",
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "id": "dfareporting.placements.generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "description": "Gets one placement by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.get",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}"
        },
        "insert": {
          "description": "Inserts a new placement.",
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "id": "dfareporting.placements.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.update",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "path": "userprofiles/{+profileId}/placements",
          "description": "Updates an existing placement."
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.tvCampaignSummaries.list",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "description": "Retrieves a list of TV campaign summaries.",
          "httpMethod": "GET"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.get",
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "description": "Gets one account permission by ID."
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves the list of account permissions.",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "id": "dfareporting.accountPermissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "id": "dfareporting.billingRates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.get",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "description": "Gets one change log by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.list",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "path": "userprofiles/{+profileId}/changeLogs",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "httpMethod": "GET"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "description": "Gets one TvCampaignDetail by ID.",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "id": "dfareporting.tvCampaignDetails.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "httpMethod": "GET"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "description": "Inserts conversions.",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "id": "dfareporting.conversions.batchinsert"
        },
        "batchupdate": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "id": "dfareporting.conversions.batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Updates existing conversions.",
          "path": "userprofiles/{profileId}/conversions/batchupdate"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetableRemarketingLists.get",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "description": "Gets one remarketing list by ID."
        },
        "list": {
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "id": "dfareporting.targetableRemarketingLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissionGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "description": "Gets one account permission group by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissionGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "description": "Retrieves the list of account permission groups.",
          "path": "userprofiles/{+profileId}/accountPermissionGroups"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.update"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.patch"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one floodlight activity group by ID.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "id": "dfareporting.floodlightActivityGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity group.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.remarketingLists.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/remarketingLists"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.get",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "description": "Gets one remarketing list by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new remarketing list.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.list",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Updates an existing remarketing list.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.update"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "description": "Gets one user role permission by ID.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissions.get"
        },
        "list": {
          "description": "Gets a list of user role permissions, possibly filtered.",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.get",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "description": "Gets one platform type by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "path": "userprofiles/{+profileId}/platformTypes",
          "description": "Retrieves a list of platform types.",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.list",
          "httpMethod": "GET"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.languages.list",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "path": "userprofiles/{+profileId}/languages",
          "description": "Retrieves a list of languages.",
          "httpMethod": "GET"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one landing page by ID.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "id": "dfareporting.advertiserLandingPages.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}"
        },
        "insert": {
          "description": "Inserts a new landing page.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "POST"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.list",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Retrieves a list of landing pages.",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.update",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page.",
          "httpMethod": "PUT"
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "description": "Gets one account by ID.",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.get"
        },
        "list": {
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/accounts",
          "id": "dfareporting.accounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "id": "dfareporting.accounts.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account.",
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "PUT"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "id": "dfareporting.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/accounts"
        }
      }
    },
    "creatives": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.creatives.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creatives"
        },
        "update": {
          "description": "Updates an existing creative.",
          "path": "userprofiles/{+profileId}/creatives",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "get": {
          "id": "dfareporting.creatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "description": "Gets one creative by ID.",
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Inserts a new creative.",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.insert"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.patch",
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Updates an existing creative. This method supports patch semantics."
        }
      }
    },
    "creativeFields": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.list"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "id": "dfareporting.creativeFields.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "PUT"
        },
        "get": {
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "description": "Gets one creative field by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.get",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new creative field.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "id": "dfareporting.creativeFields.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "delete": {
          "description": "Deletes an existing creative field.",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "id": "dfareporting.creativeFields.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "httpMethod": "DELETE"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "id": "dfareporting.creativeFields.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        }
      }
    },
    "eventTags": {
      "methods": {
        "delete": {
          "description": "Deletes an existing event tag.",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "id": "dfareporting.eventTags.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "DELETE"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "PATCH"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one event tag by ID.",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "id": "dfareporting.eventTags.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new event tag.",
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.eventTags.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "update": {
          "description": "Updates an existing event tag.",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "generatetag": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.generatetag",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "description": "Generates a tag for a floodlight activity.",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "update": {
          "description": "Updates an existing floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "description": "Gets one floodlight activity by ID."
        },
        "insert": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Inserts a new floodlight activity.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.insert",
          "httpMethod": "POST"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.delete",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "description": "Deletes an existing floodlight activity."
        },
        "patch": {
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        }
      }
    },
    "sizes": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "path": "userprofiles/{+profileId}/sizes",
          "id": "dfareporting.sizes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sizes"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one size by ID.",
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "id": "dfareporting.sizes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.sizes.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "description": "Inserts a new size.",
          "path": "userprofiles/{+profileId}/sizes"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "description": "Retrieves a list of regions.",
          "path": "userprofiles/{+profileId}/regions",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "id": "dfareporting.regions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "generateCode": {
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "id": "dfareporting.dynamicProfiles.generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "id": "dfareporting.dynamicProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a dynamic profile by ID.",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "studio/dynamicProfiles",
          "description": "Inserts a new dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.insert",
          "flatPath": "studio/dynamicProfiles"
        },
        "publish": {
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicProfiles.publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Publish for a dynamic profile.",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.update",
          "path": "studio/dynamicProfiles",
          "description": "Updates an existing dynamic profile."
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "id": "dfareporting.operatingSystems.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system by DART ID.",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of operating systems.",
          "path": "userprofiles/{+profileId}/operatingSystems",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "id": "dfareporting.operatingSystems.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.advertiserGroups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.advertiserGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.advertiserGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "description": "Gets one advertiser group by ID.",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.list"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.get",
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "description": "Gets one country by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of countries.",
          "path": "userprofiles/{+profileId}/countries",
          "id": "dfareporting.countries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/countries"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "description": "Gets one user role permission group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissionGroups.get"
        },
        "list": {
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "description": "Gets a list of all supported user role permission groups.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissionGroups.list",
          "httpMethod": "GET"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "list": {
          "id": "dfareporting.targetingTemplates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Updates an existing targeting template.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.update",
          "httpMethod": "PUT"
        },
        "get": {
          "id": "dfareporting.targetingTemplates.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "description": "Gets one targeting template by ID.",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new targeting template.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/targetingTemplates"
        }
      }
    },
    "sites": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.sites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "description": "Gets one site by ID.",
          "path": "userprofiles/{+profileId}/sites/{+id}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.insert",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "description": "Inserts a new site.",
          "httpMethod": "POST"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.sites.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Updates an existing site. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/sites"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.update",
          "path": "userprofiles/{+profileId}/sites",
          "description": "Updates an existing site."
        }
      }
    },
    "placementGroups": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/placementGroups",
          "id": "dfareporting.placementGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Updates an existing placement group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "patch": {
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placementGroups",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "id": "dfareporting.placementGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        },
        "get": {
          "description": "Gets one placement group by ID.",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "id": "dfareporting.placementGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Inserts a new placement group.",
          "httpMethod": "POST"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "description": "Gets one billing profile by ID.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.get"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.list"
        },
        "update": {
          "path": "userprofiles/{+profileId}/billingProfiles",
          "description": "Updates an existing billing profile.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.update",
          "httpMethod": "PUT"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "id": "dfareporting.browsers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of browsers.",
          "path": "userprofiles/{+profileId}/browsers"
        }
      }
    },
    "projects": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectsId}",
          "id": "dfareporting.projects.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one project by ID.",
          "path": "userprofiles/{+profileId}/projects/{+id}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/projects",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.projects.list",
          "flatPath": "userprofiles/{userprofilesId}/projects"
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.directorySites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "description": "Gets one directory site by ID.",
          "path": "userprofiles/{+profileId}/directorySites/{+id}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "id": "dfareporting.directorySites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new directory site.",
          "path": "userprofiles/{+profileId}/directorySites",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "id": "dfareporting.directorySites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/directorySites"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "id": "dfareporting.postalCodes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one postal code by ID.",
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "httpMethod": "GET"
        },
        "list": {
          "path": "userprofiles/{+profileId}/postalCodes",
          "description": "Retrieves a list of postal codes.",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.list",
          "httpMethod": "GET"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.list",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging."
        },
        "update": {
          "description": "Updates an existing account user profile.",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PUT"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.patch"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "id": "dfareporting.accountUserProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account user profile by ID.",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.insert",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Inserts a new account user profile.",
          "httpMethod": "POST"
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "retransform": {
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicFeeds.retransform",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "httpMethod": "POST"
        },
        "get": {
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicFeeds.get",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "description": "Gets a dynamic feed by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "studio/dynamicFeeds",
          "id": "dfareporting.dynamicFeeds.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new dynamic feed.",
          "path": "studio/dynamicFeeds"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.dynamicFeeds.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicFeeds",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "path": "studio/dynamicFeeds"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "id": "dfareporting.cities.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of cities, possibly filtered.",
          "path": "userprofiles/{+profileId}/cities",
          "httpMethod": "GET"
        }
      }
    },
    "userRoles": {
      "methods": {
        "get": {
          "description": "Gets one user role by ID.",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "id": "dfareporting.userRoles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Inserts a new user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.insert",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "POST"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.patch",
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing user role.",
          "path": "userprofiles/{+profileId}/userRoles/{+id}"
        },
        "list": {
          "id": "dfareporting.userRoles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.update",
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Updates an existing user role."
        }
      }
    },
    "subaccounts": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "id": "dfareporting.subaccounts.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one subaccount by ID.",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}"
        },
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.insert",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Inserts a new subaccount."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.patch",
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.list",
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.update",
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Updates an existing subaccount."
        }
      }
    },
    "campaigns": {
      "methods": {
        "list": {
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "id": "dfareporting.campaigns.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "id": "dfareporting.campaigns.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing campaign.",
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "PUT"
        },
        "get": {
          "description": "Gets one campaign by ID.",
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "id": "dfareporting.campaigns.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Inserts a new campaign.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.insert",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "POST"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "id": "dfareporting.campaigns.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one mobile app by ID.",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "id": "dfareporting.mobileApps.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.mobileApps.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "description": "Retrieves list of available mobile apps.",
          "path": "userprofiles/{+profileId}/mobileApps",
          "httpMethod": "GET"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.dimensionValues.query",
          "httpMethod": "POST"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "httpMethod": "POST"
        },
        "delete": {
          "description": "Deletes an existing dynamic targeting key.",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "httpMethod": "DELETE"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "description": "Retrieves a list of dynamic targeting keys.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.list"
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "publish": {
          "flatPath": "studio/creatives/{creativesId}/publish",
          "httpMethod": "POST",
          "id": "dfareporting.studioCreatives.publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Publish for a studio creative.",
          "path": "studio/creatives/{+studioCreativeId}/publish"
        },
        "get": {
          "id": "dfareporting.studioCreatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creatives/{creativesId}",
          "description": "Gets a studio creative by ID.",
          "path": "studio/creatives/{+studioCreativeId}",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.studioCreatives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creatives",
          "description": "Inserts a new studio creative.",
          "path": "studio/creatives"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "flatPath": "reports/{reportId}/files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.get",
          "path": "reports/{reportId}/files/{fileId}",
          "supportsMediaDownload": true,
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "httpMethod": "GET"
        },
        "list": {
          "path": "userprofiles/{profileId}/files",
          "description": "Lists files for a user profile.",
          "flatPath": "userprofiles/{profileId}/files",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.list",
          "httpMethod": "GET"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeAssets.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "description": "Inserts a new creative asset."
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "description": "Gets one video format by ID.",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.videoFormats.get",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Lists available video formats.",
          "path": "userprofiles/{+profileId}/videoFormats",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "id": "dfareporting.videoFormats.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "description": "Gets one creative field value by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Inserts a new creative field value.",
          "httpMethod": "POST"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.delete",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "description": "Deletes an existing creative field value."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.patch",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.list",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.update",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value.",
          "httpMethod": "PUT"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "description": "Gets one operating system version by ID.",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "id": "dfareporting.operatingSystemVersions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystemVersions.list",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "description": "Retrieves a list of operating system versions."
        }
      }
    },
    "reports": {
      "resources": {
        "files": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "supportsMediaDownload": true,
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "id": "dfareporting.reports.files.get",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "id": "dfareporting.reports.files.list",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Lists files for a report.",
              "path": "userprofiles/{profileId}/reports/{reportId}/files"
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "id": "dfareporting.reports.compatibleFields.query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "POST"
            }
          }
        }
      },
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/reports",
          "description": "Retrieves list of reports.",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.list",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.get",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Retrieves a report by its ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "path": "userprofiles/{profileId}/reports",
          "description": "Creates a report.",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.insert",
          "httpMethod": "POST"
        },
        "run": {
          "httpMethod": "POST",
          "description": "Runs a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "id": "dfareporting.reports.run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.delete",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Deletes a report by its ID."
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Updates an existing report. This method supports patch semantics.",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "get": {
          "id": "dfareporting.inventoryItems.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems/{inventoryItemsId}",
          "description": "Gets one inventory item by ID.",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems/{+id}",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.inventoryItems.list",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems",
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        }
      }
    },
    "advertisers": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.get",
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "description": "Gets one advertiser by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new advertiser.",
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.patch",
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing advertiser.",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "id": "dfareporting.studioCreativeAssets.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creativeAssets",
          "description": "Inserts a new studio creative asset.",
          "path": "studio/creativeAssets"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one user profile by ID.",
          "path": "userprofiles/{profileId}",
          "id": "dfareporting.userProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves list of user profiles for a user.",
          "path": "userprofiles",
          "id": "dfareporting.userProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "description": "Gets one creative group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.get"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "id": "dfareporting.creativeGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative group.",
          "path": "userprofiles/{+profileId}/creativeGroups"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.patch",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Updates an existing creative group. This method supports patch semantics."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.list",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.creativeGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "description": "Updates an existing creative group.",
          "path": "userprofiles/{+profileId}/creativeGroups"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one connection type by ID.",
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "id": "dfareporting.connectionTypes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.list",
          "path": "userprofiles/{+profileId}/connectionTypes",
          "description": "Retrieves a list of connection types."
        }
      }
    }
  },
  "title": "Campaign Manager 360 API",
  "id": "dfareporting:v4"
}