{
  "ownerName": "Google",
  "revision": "20260310",
  "servicePath": "dfareporting/v5/",
  "discoveryVersion": "v1",
  "canonicalName": "Dfareporting",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "title": "Campaign Manager 360 API",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "kind": "discovery#restDescription",
  "resources": {
    "platformTypes": {
      "methods": {
        "get": {
          "id": "dfareporting.platformTypes.get",
          "httpMethod": "GET",
          "description": "Gets one platform type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}"
        },
        "list": {
          "id": "dfareporting.platformTypes.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of platform types.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/platformTypes",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one connection type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "id": "dfareporting.connectionTypes.get"
        },
        "list": {
          "id": "dfareporting.connectionTypes.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of connection types.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/connectionTypes",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes"
        }
      }
    },
    "ads": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing ad.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "id": "dfareporting.ads.update"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one ad by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "id": "dfareporting.ads.get"
        },
        "insert": {
          "id": "dfareporting.ads.insert",
          "path": "userprofiles/{+profileId}/ads",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "POST",
          "description": "Inserts a new ad.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "id": "dfareporting.ads.list"
        },
        "patch": {
          "id": "dfareporting.ads.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/ads",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "delete": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.delete",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field value."
        },
        "update": {
          "id": "dfareporting.creativeFieldValues.update",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PUT",
          "description": "Updates an existing creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one creative field value by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "id": "dfareporting.creativeFieldValues.get"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new creative field value.",
          "id": "dfareporting.creativeFieldValues.insert"
        },
        "list": {
          "id": "dfareporting.creativeFieldValues.list",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging."
        },
        "patch": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "id": "dfareporting.creativeFieldValues.patch"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "id": "dfareporting.mobileApps.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one mobile app by ID.",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}"
        },
        "list": {
          "id": "dfareporting.mobileApps.list",
          "path": "userprofiles/{+profileId}/mobileApps",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "httpMethod": "GET",
          "description": "Retrieves list of available mobile apps.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userRoles": {
      "methods": {
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes an existing user role.",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/userRoles",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new user role.",
          "id": "dfareporting.userRoles.insert"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/userRoles",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.patch"
        },
        "list": {
          "id": "dfareporting.userRoles.list",
          "path": "userprofiles/{+profileId}/userRoles",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "GET",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.userRoles.update",
          "path": "userprofiles/{+profileId}/userRoles",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PUT",
          "description": "Updates an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.userRoles.get",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one user role by ID."
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "insert": {
          "id": "dfareporting.floodlightActivities.insert",
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "list": {
          "id": "dfareporting.floodlightActivities.list",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging."
        },
        "patch": {
          "id": "dfareporting.floodlightActivities.patch",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity. This method supports patch semantics."
        },
        "update": {
          "id": "dfareporting.floodlightActivities.update",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.floodlightActivities.get",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one floodlight activity by ID."
        },
        "delete": {
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.delete"
        },
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Generates a tag for a floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag"
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "get": {
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets a dynamic profile by ID.",
          "id": "dfareporting.dynamicProfiles.get"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing dynamic profile.",
          "path": "studio/dynamicProfiles",
          "flatPath": "studio/dynamicProfiles",
          "id": "dfareporting.dynamicProfiles.update"
        },
        "insert": {
          "id": "dfareporting.dynamicProfiles.insert",
          "path": "studio/dynamicProfiles",
          "flatPath": "studio/dynamicProfiles",
          "httpMethod": "POST",
          "description": "Inserts a new dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "generateCode": {
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "id": "dfareporting.dynamicProfiles.generateCode"
        },
        "publish": {
          "id": "dfareporting.dynamicProfiles.publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Publish for a dynamic profile.",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish"
        }
      }
    },
    "eventTags": {
      "methods": {
        "insert": {
          "id": "dfareporting.eventTags.insert",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "POST",
          "description": "Inserts a new event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.eventTags.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "patch": {
          "id": "dfareporting.eventTags.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.update"
        },
        "get": {
          "id": "dfareporting.eventTags.get",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "GET",
          "description": "Gets one event tag by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.delete"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/regions",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of regions.",
          "id": "dfareporting.regions.list"
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "id": "dfareporting.tvCampaignSummaries.list",
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "httpMethod": "GET",
          "description": "Retrieves a list of TV campaign summaries.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.delete",
          "httpMethod": "DELETE",
          "description": "Deletes an existing advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.update"
        },
        "get": {
          "id": "dfareporting.advertiserGroups.get",
          "httpMethod": "GET",
          "description": "Gets one advertiser group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new advertiser group.",
          "id": "dfareporting.advertiserGroups.insert"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.list"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.patch"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new account user profile.",
          "id": "dfareporting.accountUserProfiles.insert"
        },
        "list": {
          "id": "dfareporting.accountUserProfiles.list",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "GET",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.accountUserProfiles.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        },
        "update": {
          "id": "dfareporting.accountUserProfiles.update",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing account user profile."
        },
        "get": {
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one account user profile by ID.",
          "id": "dfareporting.accountUserProfiles.get"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "id": "dfareporting.dimensionValues.query",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "httpMethod": "POST",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one country by ID.",
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "id": "dfareporting.countries.get"
        },
        "list": {
          "id": "dfareporting.countries.list",
          "path": "userprofiles/{+profileId}/countries",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "httpMethod": "GET",
          "description": "Retrieves a list of countries.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "update": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.update"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "id": "dfareporting.remarketingLists.get"
        },
        "insert": {
          "id": "dfareporting.remarketingLists.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new remarketing list.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.patch"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.list"
        }
      }
    },
    "placements": {
      "methods": {
        "generatetags": {
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "httpMethod": "POST",
          "description": "Generates tags for a placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.generatetags"
        },
        "insert": {
          "id": "dfareporting.placements.insert",
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "POST",
          "description": "Inserts a new placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.placements.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "list": {
          "id": "dfareporting.placements.list",
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging."
        },
        "update": {
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "PUT",
          "description": "Updates an existing placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.update"
        },
        "get": {
          "id": "dfareporting.placements.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one placement by ID.",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": true,
          "path": "reports/{reportId}/files/{fileId}",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "id": "dfareporting.files.get"
        },
        "list": {
          "id": "dfareporting.files.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "description": "Lists files for a user profile.",
          "path": "userprofiles/{profileId}/files",
          "flatPath": "userprofiles/{profileId}/files"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing landing page.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.update"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one landing page by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "id": "dfareporting.advertiserLandingPages.get"
        },
        "insert": {
          "id": "dfareporting.advertiserLandingPages.insert",
          "httpMethod": "POST",
          "description": "Inserts a new landing page.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "list": {
          "id": "dfareporting.advertiserLandingPages.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of landing pages.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "patch": {
          "id": "dfareporting.advertiserLandingPages.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        }
      }
    },
    "accounts": {
      "methods": {
        "update": {
          "id": "dfareporting.accounts.update",
          "httpMethod": "PUT",
          "description": "Updates an existing account.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts",
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        },
        "get": {
          "id": "dfareporting.accounts.get",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one account by ID."
        },
        "list": {
          "id": "dfareporting.accounts.list",
          "httpMethod": "GET",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts",
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        },
        "patch": {
          "id": "dfareporting.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing account. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/accounts",
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new studio creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creatives",
          "flatPath": "studio/creatives",
          "id": "dfareporting.studioCreatives.insert"
        },
        "publish": {
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "flatPath": "studio/creatives/{creativesId}/publish",
          "httpMethod": "POST",
          "description": "Publish for a studio creative.",
          "id": "dfareporting.studioCreatives.publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.studioCreatives.get",
          "path": "studio/creatives/{+studioCreativeId}",
          "flatPath": "studio/creatives/{creativesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets a studio creative by ID."
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "update": {
          "id": "dfareporting.placementStrategies.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "get": {
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one placement strategy by ID.",
          "id": "dfareporting.placementStrategies.get"
        },
        "insert": {
          "id": "dfareporting.placementStrategies.insert",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "POST",
          "description": "Inserts a new placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.placementStrategies.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "list": {
          "id": "dfareporting.placementStrategies.list",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.delete",
          "httpMethod": "DELETE",
          "description": "Deletes an existing placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "id": "dfareporting.accountPermissions.get",
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one account permission by ID."
        },
        "list": {
          "id": "dfareporting.accountPermissions.list",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "httpMethod": "GET",
          "description": "Retrieves the list of account permissions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "get": {
          "id": "dfareporting.floodlightConfigurations.get",
          "httpMethod": "GET",
          "description": "Gets one floodlight configuration by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}"
        },
        "update": {
          "id": "dfareporting.floodlightConfigurations.update",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight configuration."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.list"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "id": "dfareporting.floodlightConfigurations.patch"
        }
      }
    },
    "campaigns": {
      "methods": {
        "insert": {
          "id": "dfareporting.campaigns.insert",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new campaign."
        },
        "list": {
          "id": "dfareporting.campaigns.list",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "id": "dfareporting.campaigns.patch"
        },
        "update": {
          "id": "dfareporting.campaigns.update",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PUT",
          "description": "Updates an existing campaign.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one campaign by ID.",
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "id": "dfareporting.campaigns.get"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "insert": {
          "id": "dfareporting.floodlightActivityGroups.insert",
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "list": {
          "id": "dfareporting.floodlightActivityGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "id": "dfareporting.floodlightActivityGroups.patch"
        },
        "update": {
          "id": "dfareporting.floodlightActivityGroups.update",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight activity group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.floodlightActivityGroups.get",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one account permission group by ID.",
          "id": "dfareporting.accountPermissionGroups.get"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves the list of account permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "id": "dfareporting.accountPermissionGroups.list"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one operating system version by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "id": "dfareporting.operatingSystemVersions.get"
        },
        "list": {
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of operating system versions.",
          "id": "dfareporting.operatingSystemVersions.list"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "id": "dfareporting.browsers.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of browsers.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/browsers",
          "flatPath": "userprofiles/{userprofilesId}/browsers"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one mobile carrier by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "id": "dfareporting.mobileCarriers.get"
        },
        "list": {
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of mobile carriers.",
          "id": "dfareporting.mobileCarriers.list"
        }
      }
    },
    "sizes": {
      "methods": {
        "insert": {
          "id": "dfareporting.sizes.insert",
          "path": "userprofiles/{+profileId}/sizes",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "POST",
          "description": "Inserts a new size.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.sizes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "path": "userprofiles/{+profileId}/sizes",
          "flatPath": "userprofiles/{userprofilesId}/sizes"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one size by ID.",
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "id": "dfareporting.sizes.get"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "insert": {
          "id": "dfareporting.creativeGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new creative group.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "list": {
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.list"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "id": "dfareporting.creativeGroups.patch"
        },
        "update": {
          "id": "dfareporting.creativeGroups.update",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing creative group."
        },
        "get": {
          "id": "dfareporting.creativeGroups.get",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one creative group by ID."
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one change log by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "id": "dfareporting.changeLogs.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "path": "userprofiles/{+profileId}/changeLogs",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "id": "dfareporting.changeLogs.list"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing dynamic targeting key.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.delete"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of dynamic targeting keys.",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.list"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.insert"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "update": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PUT",
          "description": "Updates an existing targeting template.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.update"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one targeting template by ID.",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "id": "dfareporting.targetingTemplates.get"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "POST",
          "description": "Inserts a new targeting template.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.insert"
        },
        "patch": {
          "id": "dfareporting.targetingTemplates.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        },
        "list": {
          "id": "dfareporting.targetingTemplates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "supportsMediaUpload": true,
          "id": "dfareporting.studioCreativeAssets.insert",
          "path": "studio/creativeAssets",
          "flatPath": "studio/creativeAssets",
          "httpMethod": "POST",
          "description": "Inserts a new studio creative asset.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "id": "dfareporting.userRolePermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one user role permission by ID.",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}"
        },
        "list": {
          "id": "dfareporting.userRolePermissions.list",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets a list of user role permissions, possibly filtered."
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "httpMethod": "POST",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations"
        },
        "list": {
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "httpMethod": "GET",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaignCreativeAssociations.list"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "id": "dfareporting.postalCodes.get",
          "httpMethod": "GET",
          "description": "Gets one postal code by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/postalCodes",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of postal codes.",
          "id": "dfareporting.postalCodes.list"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one operating system by DART ID.",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "id": "dfareporting.operatingSystems.get"
        },
        "list": {
          "id": "dfareporting.operatingSystems.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of operating systems.",
          "path": "userprofiles/{+profileId}/operatingSystems",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "id": "dfareporting.subaccounts.update"
        },
        "get": {
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "httpMethod": "GET",
          "description": "Gets one subaccount by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.get"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "id": "dfareporting.subaccounts.insert"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "id": "dfareporting.subaccounts.patch"
        },
        "list": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.subaccounts.list"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "id": "dfareporting.targetableRemarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}"
        },
        "list": {
          "id": "dfareporting.targetableRemarketingLists.list",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one user role permission group by ID.",
          "id": "dfareporting.userRolePermissionGroups.get"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Gets a list of all supported user role permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "id": "dfareporting.userRolePermissionGroups.list"
        }
      }
    },
    "creatives": {
      "methods": {
        "get": {
          "id": "dfareporting.creatives.get",
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one creative by ID."
        },
        "update": {
          "path": "userprofiles/{+profileId}/creatives",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing creative.",
          "id": "dfareporting.creatives.update"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.list"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing creative. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.patch"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.insert"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "id": "dfareporting.cities.list",
          "path": "userprofiles/{+profileId}/cities",
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of cities, possibly filtered."
        }
      }
    },
    "conversions": {
      "methods": {
        "batchupdate": {
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "httpMethod": "POST",
          "description": "Updates existing conversions.",
          "id": "dfareporting.conversions.batchupdate"
        },
        "batchinsert": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "httpMethod": "POST",
          "description": "Inserts conversions.",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "id": "dfareporting.conversions.batchinsert"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "httpMethod": "GET",
          "description": "Gets one TvCampaignDetail by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.tvCampaignDetails.get"
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "insert": {
          "id": "dfareporting.dynamicFeeds.insert",
          "httpMethod": "POST",
          "description": "Inserts a new dynamic feed.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds",
          "flatPath": "studio/dynamicFeeds"
        },
        "update": {
          "id": "dfareporting.dynamicFeeds.update",
          "httpMethod": "PUT",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds",
          "flatPath": "studio/dynamicFeeds"
        },
        "retransform": {
          "id": "dfareporting.dynamicFeeds.retransform",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform"
        },
        "get": {
          "id": "dfareporting.dynamicFeeds.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets a dynamic feed by ID.",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing billing profile.",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "id": "dfareporting.billingProfiles.update"
        },
        "get": {
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one billing profile by ID.",
          "id": "dfareporting.billingProfiles.get"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "id": "dfareporting.billingProfiles.list"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/languages",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "httpMethod": "GET",
          "description": "Retrieves a list of languages.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.languages.list"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "id": "dfareporting.metros.list",
          "path": "userprofiles/{+profileId}/metros",
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of metros."
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "supportsMediaUpload": true,
          "id": "dfareporting.creativeAssets.insert",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new creative asset."
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "id": "dfareporting.billingRates.list",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "httpMethod": "GET",
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets the account's active ad summary by account ID.",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "id": "dfareporting.accountActiveAdSummaries.get"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/placementGroups",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "POST",
          "description": "Inserts a new placement group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.insert"
        },
        "patch": {
          "id": "dfareporting.placementGroups.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "id": "dfareporting.placementGroups.list"
        },
        "update": {
          "id": "dfareporting.placementGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing placement group.",
          "path": "userprofiles/{+profileId}/placementGroups",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "get": {
          "id": "dfareporting.placementGroups.get",
          "httpMethod": "GET",
          "description": "Gets one placement group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}"
        }
      }
    },
    "advertisers": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new advertiser.",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.insert"
        },
        "list": {
          "id": "dfareporting.advertisers.list",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.patch"
        },
        "update": {
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.update"
        },
        "get": {
          "id": "dfareporting.advertisers.get",
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one advertiser by ID."
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one video format by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "id": "dfareporting.videoFormats.get"
        },
        "list": {
          "id": "dfareporting.videoFormats.list",
          "httpMethod": "GET",
          "description": "Lists available video formats.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/videoFormats",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats"
        }
      }
    },
    "directorySites": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/directorySites",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "id": "dfareporting.directorySites.list"
        },
        "insert": {
          "id": "dfareporting.directorySites.insert",
          "path": "userprofiles/{+profileId}/directorySites",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new directory site."
        },
        "get": {
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one directory site by ID.",
          "id": "dfareporting.directorySites.get"
        }
      }
    },
    "sites": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/sites",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing site. This method supports patch semantics.",
          "id": "dfareporting.sites.patch"
        },
        "list": {
          "id": "dfareporting.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/sites",
          "flatPath": "userprofiles/{userprofilesId}/sites"
        },
        "insert": {
          "id": "dfareporting.sites.insert",
          "path": "userprofiles/{+profileId}/sites",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "POST",
          "description": "Inserts a new site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one site by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "id": "dfareporting.sites.get"
        },
        "update": {
          "id": "dfareporting.sites.update",
          "path": "userprofiles/{+profileId}/sites",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing site."
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserInvoices.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "httpMethod": "GET",
          "description": "Retrieves a list of billing assignments.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.list"
        },
        "insert": {
          "id": "dfareporting.billingAssignments.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "get": {
          "id": "dfareporting.contentCategories.get",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "GET",
          "description": "Gets one content category by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "id": "dfareporting.contentCategories.update"
        },
        "list": {
          "id": "dfareporting.contentCategories.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "patch": {
          "id": "dfareporting.contentCategories.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "insert": {
          "id": "dfareporting.contentCategories.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new content category.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.delete",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}"
        }
      }
    },
    "reports": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "description": "Creates a report.",
          "path": "userprofiles/{profileId}/reports",
          "flatPath": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.insert"
        },
        "list": {
          "id": "dfareporting.reports.list",
          "path": "userprofiles/{profileId}/reports",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "description": "Retrieves list of reports."
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.update"
        },
        "get": {
          "id": "dfareporting.reports.get",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a report by its ID."
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes a report by its ID.",
          "id": "dfareporting.reports.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "run": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "description": "Runs a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "id": "dfareporting.reports.run"
        }
      },
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "id": "dfareporting.reports.compatibleFields.query",
              "httpMethod": "POST",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        },
        "files": {
          "methods": {
            "get": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "supportsMediaDownload": true,
              "id": "dfareporting.reports.files.get"
            },
            "list": {
              "id": "dfareporting.reports.files.list",
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "GET",
              "description": "Lists files for a report."
            }
          }
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "id": "dfareporting.userProfiles.get",
          "path": "userprofiles/{profileId}",
          "flatPath": "userprofiles/{profileId}",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one user profile by ID."
        },
        "list": {
          "path": "userprofiles",
          "flatPath": "userprofiles",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "update": {
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "PUT",
          "description": "Updates an existing creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.update"
        },
        "get": {
          "id": "dfareporting.creativeFields.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one creative field by ID.",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}"
        },
        "insert": {
          "id": "dfareporting.creativeFields.insert",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "POST",
          "description": "Inserts a new creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "id": "dfareporting.creativeFields.list"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "id": "dfareporting.creativeFields.patch"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field.",
          "id": "dfareporting.creativeFields.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "patch": {
          "id": "dfareporting.remarketingListShares.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        },
        "update": {
          "id": "dfareporting.remarketingListShares.update",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list share.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "httpMethod": "GET",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.get"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "id": "dfareporting:v5",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v5/",
  "name": "dfareporting",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "protocol": "rest",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "version": "v5",
  "basePath": "/dfareporting/v5/"
}