{
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "batchPath": "batch",
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "protocol": "rest",
  "basePath": "/dfareporting/v5/",
  "name": "dfareporting",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v5/",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "id": "dfareporting:v5",
  "title": "Campaign Manager 360 API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "servicePath": "dfareporting/v5/",
  "fullyEncodeReservedExpansion": true,
  "version": "v5",
  "revision": "20260310",
  "kind": "discovery#restDescription",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "resources": {
    "advertisers": {
      "methods": {
        "patch": {
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "id": "dfareporting.advertisers.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "PATCH"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.get",
          "description": "Gets one advertiser by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.list",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "update": {
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.update"
        },
        "insert": {
          "description": "Inserts a new advertiser.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.insert",
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "POST"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}",
          "id": "dfareporting.userProfiles.get",
          "flatPath": "userprofiles/{profileId}",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user profile by ID."
        },
        "list": {
          "path": "userprofiles",
          "httpMethod": "GET",
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles"
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "path": "studio/dynamicFeeds",
          "id": "dfareporting.dynamicFeeds.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicFeeds",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored."
        },
        "get": {
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicFeeds.get",
          "description": "Gets a dynamic feed by ID.",
          "httpMethod": "GET",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}"
        },
        "insert": {
          "description": "Inserts a new dynamic feed.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicFeeds",
          "id": "dfareporting.dynamicFeeds.insert",
          "path": "studio/dynamicFeeds",
          "httpMethod": "POST"
        },
        "retransform": {
          "id": "dfareporting.dynamicFeeds.retransform",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "httpMethod": "POST",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations"
        },
        "list": {
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "httpMethod": "GET",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaignCreativeAssociations.list"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "httpMethod": "GET",
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingRates.list"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "description": "Retrieves a list of dynamic targeting keys."
        },
        "insert": {
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "httpMethod": "POST"
        },
        "delete": {
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "description": "Deletes an existing dynamic targeting key."
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.list"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.update",
          "description": "Updates an existing advertiser group.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "delete": {
          "id": "dfareporting.advertiserGroups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "description": "Deletes an existing advertiser group."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.insert",
          "description": "Inserts a new advertiser group.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.patch",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "get": {
          "id": "dfareporting.advertiserGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "description": "Gets one advertiser group by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets the account's active ad summary by account ID."
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "get": {
          "description": "Gets a dynamic profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "id": "dfareporting.dynamicProfiles.get",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "httpMethod": "GET"
        },
        "generateCode": {
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "id": "dfareporting.dynamicProfiles.generateCode",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "studio/dynamicProfiles",
          "id": "dfareporting.dynamicProfiles.update",
          "flatPath": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing dynamic profile."
        },
        "insert": {
          "description": "Inserts a new dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicProfiles",
          "id": "dfareporting.dynamicProfiles.insert",
          "path": "studio/dynamicProfiles",
          "httpMethod": "POST"
        },
        "publish": {
          "id": "dfareporting.dynamicProfiles.publish",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "description": "Publish for a dynamic profile."
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "description": "Gets a list of all supported user role permission groups.",
          "id": "dfareporting.userRolePermissionGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one user role permission group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissionGroups.get",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "httpMethod": "GET"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "GET",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "id": "dfareporting.placementStrategies.list"
        },
        "update": {
          "description": "Updates an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "id": "dfareporting.placementStrategies.update",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "PUT"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.insert",
          "description": "Inserts a new placement strategy."
        },
        "delete": {
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "description": "Deletes an existing placement strategy.",
          "id": "dfareporting.placementStrategies.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "DELETE"
        },
        "get": {
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "httpMethod": "GET",
          "description": "Gets one placement strategy by ID.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.get"
        },
        "patch": {
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "id": "dfareporting.placementStrategies.patch",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "PATCH"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "insert": {
          "description": "Inserts a new landing page.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.insert",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.list",
          "description": "Retrieves a list of landing pages.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "update": {
          "id": "dfareporting.advertiserLandingPages.update",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing landing page.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing landing page. This method supports patch semantics."
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "id": "dfareporting.advertiserLandingPages.get",
          "description": "Gets one landing page by ID."
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/metros",
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.metros.list",
          "description": "Retrieves a list of metros."
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "httpMethod": "GET",
          "description": "Gets one operating system by DART ID.",
          "id": "dfareporting.operatingSystems.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}"
        },
        "list": {
          "description": "Retrieves a list of operating systems.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "id": "dfareporting.operatingSystems.list",
          "path": "userprofiles/{+profileId}/operatingSystems",
          "httpMethod": "GET"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "id": "dfareporting.accountUserProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "description": "Gets one account user profile by ID."
        },
        "patch": {
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.patch"
        },
        "list": {
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "GET",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.list"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.update",
          "description": "Updates an existing account user profile."
        },
        "insert": {
          "id": "dfareporting.accountUserProfiles.insert",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new account user profile.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/accountUserProfiles"
        }
      }
    },
    "ads": {
      "methods": {
        "get": {
          "description": "Gets one ad by ID.",
          "id": "dfareporting.ads.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "httpMethod": "GET"
        },
        "patch": {
          "description": "Updates an existing ad. This method supports patch semantics.",
          "id": "dfareporting.ads.patch",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "PATCH"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "id": "dfareporting.ads.insert",
          "description": "Inserts a new ad.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/ads"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.list",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/ads"
        },
        "update": {
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "PUT",
          "description": "Updates an existing ad.",
          "id": "dfareporting.ads.update",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics."
        },
        "update": {
          "description": "Updates an existing remarketing list share.",
          "id": "dfareporting.remarketingListShares.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "httpMethod": "PUT"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.get",
          "description": "Gets one remarketing list share by remarketing list ID."
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "id": "dfareporting.accountPermissionGroups.get",
          "description": "Gets one account permission group by ID."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissionGroups.list",
          "description": "Retrieves the list of account permission groups.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissionGroups"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "id": "dfareporting.mobileCarriers.list",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of mobile carriers.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/mobileCarriers"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "id": "dfareporting.mobileCarriers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "description": "Gets one mobile carrier by ID."
        }
      }
    },
    "userRoles": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.patch",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/userRoles"
        },
        "get": {
          "id": "dfareporting.userRoles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "description": "Gets one user role by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRoles/{+id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.list",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRoles"
        },
        "update": {
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "PUT",
          "description": "Updates an existing user role.",
          "id": "dfareporting.userRoles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "description": "Deletes an existing user role.",
          "id": "dfareporting.userRoles.delete",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.insert",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "POST"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "httpMethod": "GET",
          "description": "Gets one video format by ID.",
          "id": "dfareporting.videoFormats.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}"
        },
        "list": {
          "id": "dfareporting.videoFormats.list",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Lists available video formats.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/videoFormats"
        }
      }
    },
    "placements": {
      "methods": {
        "generatetags": {
          "id": "dfareporting.placements.generatetags",
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates tags for a placement.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placements/generatetags"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.list",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placements"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.update",
          "description": "Updates an existing placement."
        },
        "insert": {
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "POST",
          "description": "Inserts a new placement.",
          "id": "dfareporting.placements.insert",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.patch",
          "description": "Updates an existing placement. This method supports patch semantics."
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "id": "dfareporting.placements.get",
          "description": "Gets one placement by ID."
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "httpMethod": "GET",
          "description": "Gets one mobile app by ID.",
          "id": "dfareporting.mobileApps.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}"
        },
        "list": {
          "id": "dfareporting.mobileApps.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "description": "Retrieves list of available mobile apps.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/mobileApps"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "list": {
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "description": "Updates an existing creative group."
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative group."
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "id": "dfareporting.creativeGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "description": "Gets one creative group by ID."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.patch",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creativeGroups"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/platformTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "id": "dfareporting.platformTypes.list",
          "description": "Retrieves a list of platform types."
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.get",
          "description": "Gets one platform type by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}"
        }
      }
    },
    "reports": {
      "methods": {
        "get": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "GET",
          "description": "Retrieves a report by its ID.",
          "id": "dfareporting.reports.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "insert": {
          "description": "Creates a report.",
          "id": "dfareporting.reports.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports",
          "path": "userprofiles/{profileId}/reports",
          "httpMethod": "POST"
        },
        "delete": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Deletes a report by its ID.",
          "id": "dfareporting.reports.delete",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "list": {
          "description": "Retrieves list of reports.",
          "id": "dfareporting.reports.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports",
          "path": "userprofiles/{profileId}/reports",
          "httpMethod": "GET"
        },
        "run": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "id": "dfareporting.reports.run",
          "description": "Runs a report."
        },
        "update": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "description": "Updates a report.",
          "id": "dfareporting.reports.update",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      },
      "resources": {
        "files": {
          "methods": {
            "get": {
              "supportsMediaDownload": true,
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "id": "dfareporting.reports.files.get",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "id": "dfareporting.reports.files.list",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "description": "Lists files for a report."
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "id": "dfareporting.reports.compatibleFields.query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST"
            }
          }
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "httpMethod": "GET",
          "description": "Gets one billing profile by ID.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "id": "dfareporting.billingProfiles.list",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles"
        },
        "update": {
          "path": "userprofiles/{+profileId}/billingProfiles",
          "httpMethod": "PUT",
          "description": "Updates an existing billing profile.",
          "id": "dfareporting.billingProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles"
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "path": "studio/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creatives",
          "id": "dfareporting.studioCreatives.insert",
          "description": "Inserts a new studio creative."
        },
        "publish": {
          "description": "Publish for a studio creative.",
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "flatPath": "studio/creatives/{creativesId}/publish",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.studioCreatives.publish"
        },
        "get": {
          "path": "studio/creatives/{+studioCreativeId}",
          "httpMethod": "GET",
          "description": "Gets a studio creative by ID.",
          "id": "dfareporting.studioCreatives.get",
          "flatPath": "studio/creatives/{creativesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "description": "Retrieves list of report dimension values for a list of filters.",
          "id": "dfareporting.dimensionValues.query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "httpMethod": "POST"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "patch": {
          "id": "dfareporting.subaccounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/subaccounts"
        },
        "get": {
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "httpMethod": "GET",
          "description": "Gets one subaccount by ID.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.get"
        },
        "list": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "GET",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.list"
        },
        "update": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "PUT",
          "description": "Updates an existing subaccount.",
          "id": "dfareporting.subaccounts.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "POST",
          "description": "Inserts a new subaccount.",
          "id": "dfareporting.subaccounts.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "httpMethod": "GET",
          "description": "Gets one operating system version by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "id": "dfareporting.operatingSystemVersions.get"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystemVersions.list",
          "description": "Retrieves a list of operating system versions."
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "id": "dfareporting.cities.list",
          "description": "Retrieves a list of cities, possibly filtered.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/cities"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "description": "Gets one TvCampaignDetail by ID.",
          "id": "dfareporting.tvCampaignDetails.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "httpMethod": "GET"
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "httpMethod": "GET",
          "description": "Retrieves a list of TV campaign summaries.",
          "id": "dfareporting.tvCampaignSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/connectionTypes",
          "httpMethod": "GET",
          "description": "Retrieves a list of connection types.",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.list"
        },
        "get": {
          "id": "dfareporting.connectionTypes.get",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one connection type by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "list": {
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.list",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.update",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "PUT"
        },
        "generatetag": {
          "description": "Generates a tag for a floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "id": "dfareporting.floodlightActivities.generatetag",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "httpMethod": "POST"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "description": "Deletes an existing floodlight activity.",
          "id": "dfareporting.floodlightActivities.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "httpMethod": "DELETE"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.insert",
          "description": "Inserts a new floodlight activity."
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity. This method supports patch semantics."
        },
        "get": {
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity by ID.",
          "id": "dfareporting.floodlightActivities.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST",
          "description": "Inserts conversions.",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "id": "dfareporting.conversions.batchinsert"
        },
        "batchupdate": {
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "description": "Updates existing conversions.",
          "id": "dfareporting.conversions.batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate"
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "description": "Lists files for a user profile.",
          "id": "dfareporting.files.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/files"
        },
        "get": {
          "httpMethod": "GET",
          "path": "reports/{reportId}/files/{fileId}",
          "id": "dfareporting.files.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "reports/{reportId}/files/{fileId}",
          "supportsMediaDownload": true,
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download."
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.list",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/changeLogs"
        },
        "get": {
          "id": "dfareporting.changeLogs.get",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one change log by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "id": "dfareporting.creativeAssets.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "supportsMediaUpload": true,
          "description": "Inserts a new creative asset."
        }
      }
    },
    "eventTags": {
      "methods": {
        "delete": {
          "description": "Deletes an existing event tag.",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.eventTags.delete"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.insert",
          "description": "Inserts a new event tag."
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.list",
          "description": "Retrieves a list of event tags, possibly filtered."
        },
        "update": {
          "description": "Updates an existing event tag.",
          "id": "dfareporting.eventTags.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "PUT"
        },
        "patch": {
          "id": "dfareporting.eventTags.patch",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "get": {
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "httpMethod": "GET",
          "description": "Gets one event tag by ID.",
          "id": "dfareporting.eventTags.get",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "sites": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PATCH",
          "description": "Updates an existing site. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.patch"
        },
        "get": {
          "description": "Gets one site by ID.",
          "id": "dfareporting.sites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "httpMethod": "GET"
        },
        "list": {
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "id": "dfareporting.sites.list"
        },
        "update": {
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PUT",
          "description": "Updates an existing site.",
          "id": "dfareporting.sites.update",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "POST",
          "description": "Inserts a new site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "id": "dfareporting.sites.insert"
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "path": "studio/creativeAssets",
          "id": "dfareporting.studioCreativeAssets.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creativeAssets",
          "supportsMediaUpload": true,
          "description": "Inserts a new studio creative asset."
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "httpMethod": "GET",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "id": "dfareporting.advertiserInvoices.list"
        }
      }
    },
    "directorySites": {
      "methods": {
        "list": {
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "id": "dfareporting.directorySites.list",
          "path": "userprofiles/{+profileId}/directorySites",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.get",
          "description": "Gets one directory site by ID."
        },
        "insert": {
          "path": "userprofiles/{+profileId}/directorySites",
          "httpMethod": "POST",
          "description": "Inserts a new directory site.",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.insert"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/regions",
          "httpMethod": "GET",
          "description": "Retrieves a list of regions.",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.regions.list"
        }
      }
    },
    "sizes": {
      "methods": {
        "insert": {
          "id": "dfareporting.sizes.insert",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new size.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/sizes"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "id": "dfareporting.sizes.list",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "id": "dfareporting.sizes.get",
          "description": "Gets one size by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/sizes/{+id}"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "id": "dfareporting.userRolePermissions.get",
          "description": "Gets one user role permission by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "httpMethod": "GET",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list"
        }
      }
    },
    "campaigns": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "GET",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.list"
        },
        "update": {
          "description": "Updates an existing campaign.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.update",
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "PUT"
        },
        "insert": {
          "id": "dfareporting.campaigns.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Inserts a new campaign.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/campaigns"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "id": "dfareporting.campaigns.get",
          "description": "Gets one campaign by ID."
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/campaigns",
          "id": "dfareporting.campaigns.patch",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing campaign. This method supports patch semantics."
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "list": {
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.targetableRemarketingLists.list",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "httpMethod": "GET"
        },
        "get": {
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.targetableRemarketingLists.get",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "httpMethod": "GET"
        }
      }
    },
    "countries": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.list",
          "description": "Retrieves a list of countries.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/countries"
        },
        "get": {
          "id": "dfareporting.countries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "description": "Gets one country by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/countries/{+dartId}"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "insert": {
          "description": "Inserts a new creative field.",
          "id": "dfareporting.creativeFields.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "POST"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "description": "Deletes an existing creative field.",
          "id": "dfareporting.creativeFields.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "httpMethod": "DELETE"
        },
        "list": {
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeFields.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing creative field.",
          "id": "dfareporting.creativeFields.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "PUT"
        },
        "get": {
          "id": "dfareporting.creativeFields.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "description": "Gets one creative field by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.patch",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creativeFields"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "httpMethod": "GET",
          "description": "Gets one postal code by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "id": "dfareporting.postalCodes.get"
        },
        "list": {
          "description": "Retrieves a list of postal codes.",
          "id": "dfareporting.postalCodes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "path": "userprofiles/{+profileId}/postalCodes",
          "httpMethod": "GET"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "list": {
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.list",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "GET"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.update",
          "description": "Updates an existing floodlight configuration.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/floodlightConfigurations"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.patch",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics."
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.get",
          "description": "Gets one floodlight configuration by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/languages",
          "id": "dfareporting.languages.list",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of languages."
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "insert": {
          "id": "dfareporting.targetingTemplates.insert",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new targeting template.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/targetingTemplates"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.list",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging."
        },
        "update": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "PUT",
          "description": "Updates an existing targeting template.",
          "id": "dfareporting.targetingTemplates.update",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "id": "dfareporting.targetingTemplates.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "description": "Gets one targeting template by ID."
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "description": "Updates an existing targeting template. This method supports patch semantics."
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/browsers",
          "httpMethod": "GET",
          "description": "Retrieves a list of browsers.",
          "id": "dfareporting.browsers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/browsers"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "POST",
          "description": "Inserts a new placement group.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.insert"
        },
        "list": {
          "id": "dfareporting.placementGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/placementGroups",
          "id": "dfareporting.placementGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "description": "Updates an existing placement group."
        },
        "get": {
          "id": "dfareporting.placementGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "description": "Gets one placement group by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "id": "dfareporting.placementGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "httpMethod": "GET",
          "description": "Retrieves a list of billing assignments.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "id": "dfareporting.billingAssignments.list"
        },
        "insert": {
          "id": "dfareporting.billingAssignments.insert",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "insert": {
          "id": "dfareporting.remarketingLists.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Inserts a new remarketing list.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/remarketingLists"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.list",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingLists"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.update",
          "description": "Updates an existing remarketing list.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/remarketingLists"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "id": "dfareporting.remarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "description": "Gets one remarketing list by ID."
        },
        "patch": {
          "id": "dfareporting.remarketingLists.patch",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/remarketingLists"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "get": {
          "description": "Gets one creative field value by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "id": "dfareporting.creativeFieldValues.get",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "httpMethod": "GET"
        },
        "patch": {
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.patch",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "PATCH"
        },
        "list": {
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeFieldValues.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.creativeFieldValues.update",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field value.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.insert",
          "description": "Inserts a new creative field value.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "description": "Deletes an existing creative field value.",
          "id": "dfareporting.creativeFieldValues.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "httpMethod": "DELETE"
        }
      }
    },
    "accounts": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "id": "dfareporting.accounts.list",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accounts"
        },
        "update": {
          "description": "Updates an existing account.",
          "id": "dfareporting.accounts.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "PUT"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/accounts",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.patch",
          "description": "Updates an existing account. This method supports patch semantics."
        },
        "get": {
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "httpMethod": "GET",
          "description": "Gets one account by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "id": "dfareporting.accounts.get"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "description": "Gets one account permission by ID.",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.get",
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "id": "dfareporting.accountPermissions.list",
          "description": "Retrieves the list of account permissions.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissions"
        }
      }
    },
    "creatives": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.list",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging."
        },
        "update": {
          "id": "dfareporting.creatives.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "description": "Updates an existing creative.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creatives"
        },
        "insert": {
          "description": "Inserts a new creative.",
          "id": "dfareporting.creatives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "POST"
        },
        "patch": {
          "id": "dfareporting.creatives.patch",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creatives"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "id": "dfareporting.creatives.get",
          "description": "Gets one creative by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creatives/{+id}"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "get": {
          "description": "Gets one content category by ID.",
          "id": "dfareporting.contentCategories.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "httpMethod": "GET"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "PATCH",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "id": "dfareporting.contentCategories.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "insert": {
          "description": "Inserts a new content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "id": "dfareporting.contentCategories.insert",
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "POST"
        },
        "delete": {
          "id": "dfareporting.contentCategories.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "description": "Deletes an existing content category."
        },
        "list": {
          "id": "dfareporting.contentCategories.list",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/contentCategories"
        },
        "update": {
          "id": "dfareporting.contentCategories.update",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing content category.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/contentCategories"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "list": {
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.list",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "GET"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.update",
          "description": "Updates an existing floodlight activity group.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity group.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.insert"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "id": "dfareporting.floodlightActivityGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "description": "Gets one floodlight activity group by ID."
        },
        "patch": {
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "PATCH"
        }
      }
    }
  },
  "canonicalName": "Dfareporting"
}