{
  "id": "dfareporting:v5",
  "version": "v5",
  "fullyEncodeReservedExpansion": true,
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v5/",
  "protocol": "rest",
  "revision": "20260310",
  "name": "dfareporting",
  "canonicalName": "Dfareporting",
  "ownerDomain": "google.com",
  "title": "Campaign Manager 360 API",
  "basePath": "/dfareporting/v5/",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "kind": "discovery#restDescription",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "resources": {
    "advertisers": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.insert",
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "id": "dfareporting.advertisers.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. This method supports patch semantics."
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.advertisers.get",
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "description": "Gets one advertiser by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.advertisers.update",
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Updates an existing advertiser."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "id": "dfareporting.advertisers.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging."
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "description": "Gets one directory site by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "id": "dfareporting.directorySites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/directorySites",
          "id": "dfareporting.directorySites.list",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new directory site.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/directorySites",
          "id": "dfareporting.directorySites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/directorySites"
        }
      }
    },
    "placements": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placements",
          "id": "dfareporting.placements.list",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging."
        },
        "generatetags": {
          "description": "Generates tags for a placement.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "id": "dfareporting.placements.generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags"
        },
        "get": {
          "description": "Gets one placement by ID.",
          "id": "dfareporting.placements.get",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}"
        },
        "patch": {
          "id": "dfareporting.placements.patch",
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.placements.insert",
          "path": "userprofiles/{+profileId}/placements",
          "description": "Inserts a new placement.",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing placement.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/placements",
          "id": "dfareporting.placements.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements"
        }
      }
    },
    "sites": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Updates an existing site. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.patch"
        },
        "insert": {
          "id": "dfareporting.sites.insert",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "POST",
          "description": "Inserts a new site.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "id": "dfareporting.sites.get",
          "httpMethod": "GET",
          "description": "Gets one site by ID.",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.update",
          "description": "Updates an existing site.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.sites.list",
          "path": "userprofiles/{+profileId}/sites",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "generateCode": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "id": "dfareporting.dynamicProfiles.generateCode",
          "httpMethod": "GET"
        },
        "publish": {
          "id": "dfareporting.dynamicProfiles.publish",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "httpMethod": "POST",
          "description": "Publish for a dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "description": "Gets a dynamic profile by ID.",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "id": "dfareporting.dynamicProfiles.get",
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicProfiles",
          "description": "Inserts a new dynamic profile.",
          "id": "dfareporting.dynamicProfiles.insert",
          "path": "studio/dynamicProfiles",
          "httpMethod": "POST"
        },
        "update": {
          "description": "Updates an existing dynamic profile.",
          "httpMethod": "PUT",
          "id": "dfareporting.dynamicProfiles.update",
          "path": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicProfiles"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.postalCodes.get",
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "description": "Gets one postal code by ID.",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of postal codes.",
          "path": "userprofiles/{+profileId}/postalCodes",
          "id": "dfareporting.postalCodes.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/postalCodes"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.placementGroups.list",
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{+profileId}/placementGroups",
          "id": "dfareporting.placementGroups.update",
          "httpMethod": "PUT",
          "description": "Updates an existing placement group.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.placementGroups.patch",
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Updates an existing placement group. This method supports patch semantics."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "description": "Inserts a new placement group.",
          "httpMethod": "POST",
          "id": "dfareporting.placementGroups.insert",
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "id": "dfareporting.placementGroups.get",
          "description": "Gets one placement group by ID."
        }
      }
    },
    "creativeFields": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeFields.list",
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing creative field.",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFields.update",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Inserts a new creative field.",
          "id": "dfareporting.creativeFields.insert",
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "POST"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "id": "dfareporting.creativeFields.patch",
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "PATCH"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFields.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field."
        },
        "get": {
          "description": "Gets one creative field by ID.",
          "id": "dfareporting.creativeFields.get",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}"
        }
      }
    },
    "ads": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.list",
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "GET",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging."
        },
        "insert": {
          "id": "dfareporting.ads.insert",
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "POST",
          "description": "Inserts a new ad.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/ads",
          "id": "dfareporting.ads.patch",
          "httpMethod": "PATCH"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "description": "Gets one ad by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.ads.get",
          "path": "userprofiles/{+profileId}/ads/{+id}"
        },
        "update": {
          "id": "dfareporting.ads.update",
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "PUT",
          "description": "Updates an existing ad.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "description": "Gets one connection type by ID.",
          "id": "dfareporting.connectionTypes.get",
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}"
        },
        "list": {
          "description": "Retrieves a list of connection types.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/connectionTypes",
          "id": "dfareporting.connectionTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivities.list",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.update",
          "description": "Updates an existing floodlight activity."
        },
        "generatetag": {
          "description": "Generates a tag for a floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "id": "dfareporting.floodlightActivities.generatetag",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing floodlight activity.",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "id": "dfareporting.floodlightActivities.delete",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "description": "Gets one floodlight activity by ID.",
          "id": "dfareporting.floodlightActivities.get",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "description": "Inserts a new floodlight activity.",
          "id": "dfareporting.floodlightActivities.insert",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "POST"
        },
        "patch": {
          "id": "dfareporting.floodlightActivities.patch",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.browsers.list",
          "path": "userprofiles/{+profileId}/browsers",
          "httpMethod": "GET",
          "description": "Retrieves a list of browsers."
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "description": "Retrieves a list of languages.",
          "id": "dfareporting.languages.list",
          "path": "userprofiles/{+profileId}/languages",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/languages"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "description": "Gets one change log by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.changeLogs.get",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.changeLogs.list",
          "path": "userprofiles/{+profileId}/changeLogs"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "list": {
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "insert": {
          "description": "Inserts a new creative group.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeGroups.patch",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one creative group by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.creativeGroups.get",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "description": "Updates an existing creative group.",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeGroups.update",
          "path": "userprofiles/{+profileId}/creativeGroups"
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "id": "dfareporting.countries.get",
          "httpMethod": "GET",
          "description": "Gets one country by ID."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/countries",
          "id": "dfareporting.countries.list",
          "description": "Retrieves a list of countries."
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "httpMethod": "POST",
          "id": "dfareporting.conversions.batchinsert",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "description": "Inserts conversions.",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ]
        },
        "batchupdate": {
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "id": "dfareporting.conversions.batchupdate",
          "description": "Updates existing conversions."
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "description": "Inserts a new studio creative asset.",
          "supportsMediaUpload": true,
          "id": "dfareporting.studioCreativeAssets.insert",
          "path": "studio/creativeAssets",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creativeAssets"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.list"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "description": "Gets one user role permission by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissions.get",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}"
        },
        "list": {
          "description": "Gets a list of user role permissions, possibly filtered.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "id": "dfareporting.dimensionValues.query",
          "httpMethod": "POST"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.update",
          "description": "Updates an existing remarketing list.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one remarketing list by ID.",
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "id": "dfareporting.remarketingLists.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.patch"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Inserts a new remarketing list.",
          "id": "dfareporting.remarketingLists.insert",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.list",
          "httpMethod": "GET"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "list": {
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "id": "dfareporting.contentCategories.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "description": "Inserts a new content category.",
          "id": "dfareporting.contentCategories.insert",
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "POST"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/contentCategories",
          "id": "dfareporting.contentCategories.patch",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing content category.",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "id": "dfareporting.contentCategories.delete",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}"
        },
        "get": {
          "description": "Gets one content category by ID.",
          "id": "dfareporting.contentCategories.get",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "description": "Updates an existing content category.",
          "httpMethod": "PUT",
          "id": "dfareporting.contentCategories.update",
          "path": "userprofiles/{+profileId}/contentCategories"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "id": "dfareporting.targetableRemarketingLists.get",
          "description": "Gets one remarketing list by ID."
        },
        "list": {
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "id": "dfareporting.targetableRemarketingLists.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "id": "dfareporting.targetingTemplates.get",
          "httpMethod": "GET",
          "description": "Gets one targeting template by ID."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "id": "dfareporting.targetingTemplates.patch",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "PATCH"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.insert",
          "httpMethod": "POST",
          "description": "Inserts a new targeting template.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "description": "Updates an existing targeting template.",
          "httpMethod": "PUT",
          "id": "dfareporting.targetingTemplates.update",
          "path": "userprofiles/{+profileId}/targetingTemplates"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.list",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging."
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "id": "dfareporting.platformTypes.get",
          "description": "Gets one platform type by ID.",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "description": "Retrieves a list of platform types.",
          "path": "userprofiles/{+profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list",
          "httpMethod": "GET"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "id": "dfareporting.billingProfiles.update",
          "description": "Updates an existing billing profile.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "description": "Gets one billing profile by ID.",
          "id": "dfareporting.billingProfiles.get",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "id": "dfareporting.billingProfiles.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles"
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "id": "dfareporting.dynamicFeeds.get",
          "description": "Gets a dynamic feed by ID.",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new dynamic feed.",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicFeeds.insert",
          "path": "studio/dynamicFeeds",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicFeeds"
        },
        "retransform": {
          "httpMethod": "POST",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "id": "dfareporting.dynamicFeeds.retransform",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicFeeds",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "httpMethod": "PUT",
          "path": "studio/dynamicFeeds",
          "id": "dfareporting.dynamicFeeds.update"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "reports/{reportId}/files/{fileId}",
          "id": "dfareporting.files.get",
          "supportsMediaDownload": true,
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/files",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/files",
          "id": "dfareporting.files.list",
          "httpMethod": "GET",
          "description": "Lists files for a user profile."
        }
      }
    },
    "creatives": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "description": "Gets one creative by ID.",
          "id": "dfareporting.creatives.get",
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.creatives.insert",
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Inserts a new creative."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.patch",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative. This method supports patch semantics."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creatives",
          "id": "dfareporting.creatives.update",
          "description": "Updates an existing creative."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creatives",
          "id": "dfareporting.creatives.list",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging."
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "update": {
          "description": "Updates an existing remarketing list share.",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "id": "dfareporting.remarketingListShares.get",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        }
      }
    },
    "userRoles": {
      "methods": {
        "list": {
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "id": "dfareporting.userRoles.list",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        },
        "update": {
          "description": "Updates an existing user role.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/userRoles",
          "id": "dfareporting.userRoles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        },
        "patch": {
          "id": "dfareporting.userRoles.patch",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "PATCH",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "userprofiles/{+profileId}/userRoles",
          "id": "dfareporting.userRoles.insert",
          "httpMethod": "POST",
          "description": "Inserts a new user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.get",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "GET",
          "description": "Gets one user role by ID."
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "id": "dfareporting.userRoles.delete",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing user role."
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "description": "Gets one operating system version by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystemVersions.get",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "id": "dfareporting.operatingSystemVersions.list",
          "description": "Retrieves a list of operating system versions.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "description": "Gets the account's active ad summary by account ID.",
          "httpMethod": "GET",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserInvoices.list",
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices"
        }
      }
    },
    "campaigns": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/campaigns",
          "id": "dfareporting.campaigns.list"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "id": "dfareporting.campaigns.insert",
          "httpMethod": "POST",
          "description": "Inserts a new campaign."
        },
        "patch": {
          "path": "userprofiles/{+profileId}/campaigns",
          "id": "dfareporting.campaigns.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "description": "Gets one campaign by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "id": "dfareporting.campaigns.get"
        },
        "update": {
          "id": "dfareporting.campaigns.update",
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "PUT",
          "description": "Updates an existing campaign.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "id": "dfareporting.creativeFieldValues.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field value."
        },
        "get": {
          "id": "dfareporting.creativeFieldValues.get",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "httpMethod": "GET",
          "description": "Gets one creative field value by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "description": "Inserts a new creative field value.",
          "httpMethod": "POST",
          "id": "dfareporting.creativeFieldValues.insert",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.patch",
          "description": "Updates an existing creative field value. This method supports patch semantics."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "description": "Updates an existing creative field value.",
          "id": "dfareporting.creativeFieldValues.update",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "PUT"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.creativeFieldValues.list",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging."
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "description": "Gets one user profile by ID.",
          "path": "userprofiles/{profileId}",
          "id": "dfareporting.userProfiles.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}"
        },
        "list": {
          "description": "Retrieves list of user profiles for a user.",
          "httpMethod": "GET",
          "id": "dfareporting.userProfiles.list",
          "path": "userprofiles",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "description": "Gets one operating system by DART ID.",
          "id": "dfareporting.operatingSystems.get",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystems",
          "id": "dfareporting.operatingSystems.list",
          "description": "Retrieves a list of operating systems.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accounts": {
      "methods": {
        "update": {
          "id": "dfareporting.accounts.update",
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "PUT",
          "description": "Updates an existing account.",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts",
          "id": "dfareporting.accounts.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing account. This method supports patch semantics."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "description": "Gets one account by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "id": "dfareporting.accounts.get"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accounts",
          "id": "dfareporting.accounts.list",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging."
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "id": "dfareporting.accountPermissions.get",
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "httpMethod": "GET",
          "description": "Gets one account permission by ID.",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "description": "Retrieves the list of account permissions.",
          "id": "dfareporting.accountPermissions.list",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "httpMethod": "GET"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "patch": {
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.floodlightConfigurations.get",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "description": "Gets one floodlight configuration by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.list"
        },
        "update": {
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.update",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight configuration.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "description": "Gets one user role permission group by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissionGroups.get",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissionGroups.list",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "description": "Gets a list of all supported user role permission groups."
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "id": "dfareporting.mobileApps.get",
          "httpMethod": "GET",
          "description": "Gets one mobile app by ID."
        },
        "list": {
          "description": "Retrieves list of available mobile apps.",
          "httpMethod": "GET",
          "id": "dfareporting.mobileApps.list",
          "path": "userprofiles/{+profileId}/mobileApps",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileApps"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "description": "Retrieves a list of billing assignments.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "id": "dfareporting.billingAssignments.list",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "id": "dfareporting.billingAssignments.insert",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "description": "Retrieves a list of metros.",
          "httpMethod": "GET",
          "id": "dfareporting.metros.list",
          "path": "userprofiles/{+profileId}/metros",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/metros"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "description": "Gets one TvCampaignDetail by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.tvCampaignDetails.get",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}"
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "id": "dfareporting.tvCampaignSummaries.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of TV campaign summaries."
        }
      }
    },
    "reports": {
      "resources": {
        "files": {
          "methods": {
            "get": {
              "supportsMediaDownload": true,
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "httpMethod": "GET",
              "id": "dfareporting.reports.files.get",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}"
            },
            "list": {
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "id": "dfareporting.reports.files.list",
              "httpMethod": "GET",
              "description": "Lists files for a report."
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "id": "dfareporting.reports.compatibleFields.query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        }
      },
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports",
          "description": "Retrieves list of reports.",
          "path": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.list",
          "httpMethod": "GET"
        },
        "run": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "description": "Runs a report.",
          "httpMethod": "POST",
          "id": "dfareporting.reports.run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.insert",
          "description": "Creates a report.",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Deletes a report by its ID.",
          "httpMethod": "DELETE",
          "id": "dfareporting.reports.delete",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        },
        "get": {
          "description": "Retrieves a report by its ID.",
          "httpMethod": "GET",
          "id": "dfareporting.reports.get",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Updates a report.",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.update"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.update",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "PUT",
          "description": "Updates an existing account user profile."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "id": "dfareporting.accountUserProfiles.get",
          "description": "Gets one account user profile by ID."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.insert",
          "description": "Inserts a new account user profile."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.patch",
          "httpMethod": "PATCH"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.list",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging."
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivityGroups.list",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing floodlight activity group.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "get": {
          "id": "dfareporting.floodlightActivityGroups.get",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Inserts a new floodlight activity group."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics."
        }
      }
    },
    "subaccounts": {
      "methods": {
        "list": {
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/subaccounts",
          "id": "dfareporting.subaccounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "description": "Gets one subaccount by ID.",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "id": "dfareporting.subaccounts.get",
          "httpMethod": "GET"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/subaccounts",
          "id": "dfareporting.subaccounts.patch",
          "description": "Updates an existing subaccount. This method supports patch semantics."
        },
        "insert": {
          "description": "Inserts a new subaccount.",
          "httpMethod": "POST",
          "id": "dfareporting.subaccounts.insert",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "description": "Updates an existing subaccount.",
          "httpMethod": "PUT",
          "id": "dfareporting.subaccounts.update",
          "path": "userprofiles/{+profileId}/subaccounts"
        }
      }
    },
    "sizes": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.sizes.insert",
          "path": "userprofiles/{+profileId}/sizes",
          "description": "Inserts a new size."
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "id": "dfareporting.sizes.get",
          "description": "Gets one size by ID.",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.sizes.list",
          "path": "userprofiles/{+profileId}/sizes",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "list": {
          "description": "Retrieves a list of landing pages.",
          "id": "dfareporting.advertiserLandingPages.list",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "description": "Inserts a new landing page.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.insert"
        },
        "patch": {
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "id": "dfareporting.advertiserLandingPages.patch",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.get",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "httpMethod": "GET",
          "description": "Gets one landing page by ID."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "description": "Updates an existing landing page.",
          "httpMethod": "PUT",
          "id": "dfareporting.advertiserLandingPages.update",
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "id": "dfareporting.regions.list",
          "path": "userprofiles/{+profileId}/regions",
          "httpMethod": "GET",
          "description": "Retrieves a list of regions.",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "description": "Gets one account permission group by ID.",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "id": "dfareporting.accountPermissionGroups.get",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissionGroups.list",
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "description": "Retrieves the list of account permission groups."
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "description": "Retrieves a list of cities, possibly filtered.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/cities",
          "id": "dfareporting.cities.list"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "delete": {
          "description": "Deletes an existing advertiser group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.delete",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "httpMethod": "DELETE"
        },
        "get": {
          "description": "Gets one advertiser group by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "id": "dfareporting.advertiserGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Inserts a new advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.insert",
          "httpMethod": "POST"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.update",
          "description": "Updates an existing advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.list",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging."
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "update": {
          "description": "Updates an existing placement strategy.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "delete": {
          "description": "Deletes an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "id": "dfareporting.placementStrategies.delete",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "DELETE"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "id": "dfareporting.placementStrategies.get",
          "description": "Gets one placement strategy by ID.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.patch",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement strategy. This method supports patch semantics."
        },
        "insert": {
          "description": "Inserts a new placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.insert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "list": {
          "path": "userprofiles/{+profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "id": "dfareporting.videoFormats.get",
          "description": "Gets one video format by ID.",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Lists available video formats.",
          "id": "dfareporting.videoFormats.list",
          "path": "userprofiles/{+profileId}/videoFormats",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/videoFormats"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "description": "Gets one mobile carrier by ID.",
          "id": "dfareporting.mobileCarriers.get",
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Retrieves a list of mobile carriers.",
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "id": "dfareporting.mobileCarriers.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers"
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creatives",
          "description": "Inserts a new studio creative.",
          "httpMethod": "POST",
          "id": "dfareporting.studioCreatives.insert",
          "path": "studio/creatives"
        },
        "publish": {
          "httpMethod": "POST",
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "id": "dfareporting.studioCreatives.publish",
          "flatPath": "studio/creatives/{creativesId}/publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Publish for a studio creative."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creatives/{creativesId}",
          "description": "Gets a studio creative by ID.",
          "id": "dfareporting.studioCreatives.get",
          "path": "studio/creatives/{+studioCreativeId}",
          "httpMethod": "GET"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing dynamic targeting key."
        },
        "list": {
          "description": "Retrieves a list of dynamic targeting keys.",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys"
        },
        "insert": {
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "eventTags": {
      "methods": {
        "update": {
          "path": "userprofiles/{+profileId}/eventTags",
          "id": "dfareporting.eventTags.update",
          "httpMethod": "PUT",
          "description": "Updates an existing event tag.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.insert",
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "POST",
          "description": "Inserts a new event tag."
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/eventTags",
          "id": "dfareporting.eventTags.patch",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "id": "dfareporting.eventTags.delete",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.get",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "httpMethod": "GET",
          "description": "Gets one event tag by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "id": "dfareporting.eventTags.list",
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "GET"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeAssets.insert",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "httpMethod": "POST",
          "description": "Inserts a new creative asset.",
          "supportsMediaUpload": true
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "id": "dfareporting.billingRates.list",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates"
        }
      }
    }
  },
  "ownerName": "Google",
  "servicePath": "dfareporting/v5/",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  }
}