{
  "batchPath": "batch",
  "name": "dfareporting",
  "kind": "discovery#restDescription",
  "version": "v5",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "servicePath": "dfareporting/v5/",
  "ownerDomain": "google.com",
  "revision": "20260310",
  "basePath": "/dfareporting/v5/",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v5/",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "protocol": "rest",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "title": "Campaign Manager 360 API",
  "canonicalName": "Dfareporting",
  "resources": {
    "countries": {
      "methods": {
        "get": {
          "id": "dfareporting.countries.get",
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "description": "Gets one country by ID.",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of countries.",
          "id": "dfareporting.countries.list",
          "path": "userprofiles/{+profileId}/countries",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/countries"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingRates.list",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "description": "Retrieves a list of billing rates. This method supports paging."
        }
      }
    },
    "accounts": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account.",
          "id": "dfareporting.accounts.update",
          "path": "userprofiles/{+profileId}/accounts"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "description": "Gets one account by ID.",
          "id": "dfareporting.accounts.get",
          "path": "userprofiles/{+profileId}/accounts/{+id}"
        },
        "list": {
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.accounts.list",
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        },
        "patch": {
          "id": "dfareporting.accounts.patch",
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Updates an existing account. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "patch": {
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "id": "dfareporting.remarketingLists.patch",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.remarketingLists.list",
          "path": "userprofiles/{+profileId}/remarketingLists"
        },
        "insert": {
          "description": "Inserts a new remarketing list.",
          "id": "dfareporting.remarketingLists.insert",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "update": {
          "id": "dfareporting.remarketingLists.update",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Updates an existing remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.remarketingLists.get",
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}"
        }
      }
    },
    "eventTags": {
      "methods": {
        "delete": {
          "description": "Deletes an existing event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.delete",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one event tag by ID.",
          "id": "dfareporting.eventTags.get",
          "path": "userprofiles/{+profileId}/eventTags/{+id}"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing event tag.",
          "id": "dfareporting.eventTags.update",
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "insert": {
          "id": "dfareporting.eventTags.insert",
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Inserts a new event tag.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.list",
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Retrieves a list of event tags, possibly filtered."
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.patch",
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Updates an existing event tag. This method supports patch semantics."
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Inserts a new floodlight activity group."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.list",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics."
        },
        "get": {
          "id": "dfareporting.floodlightActivityGroups.get",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "description": "Gets one floodlight activity group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.update",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        }
      }
    },
    "creatives": {
      "methods": {
        "get": {
          "id": "dfareporting.creatives.get",
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "description": "Gets one creative by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing creative.",
          "id": "dfareporting.creatives.update",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        },
        "insert": {
          "description": "Inserts a new creative.",
          "id": "dfareporting.creatives.insert",
          "path": "userprofiles/{+profileId}/creatives",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.creatives.list",
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        },
        "patch": {
          "id": "dfareporting.creatives.patch",
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Updates an existing creative. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "update": {
          "description": "Updates an existing account user profile.",
          "id": "dfareporting.accountUserProfiles.update",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "description": "Gets one account user profile by ID.",
          "id": "dfareporting.accountUserProfiles.get",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.list",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging."
        },
        "patch": {
          "id": "dfareporting.accountUserProfiles.patch",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        },
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "description": "Inserts a new account user profile.",
          "id": "dfareporting.accountUserProfiles.insert",
          "path": "userprofiles/{+profileId}/accountUserProfiles"
        }
      }
    },
    "userRoles": {
      "methods": {
        "update": {
          "description": "Updates an existing user role.",
          "id": "dfareporting.userRoles.update",
          "path": "userprofiles/{+profileId}/userRoles",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "get": {
          "description": "Gets one user role by ID.",
          "id": "dfareporting.userRoles.get",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}"
        },
        "delete": {
          "description": "Deletes an existing user role.",
          "id": "dfareporting.userRoles.delete",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}"
        },
        "patch": {
          "description": "Updates an existing user role. This method supports patch semantics.",
          "id": "dfareporting.userRoles.patch",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        },
        "list": {
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "id": "dfareporting.userRoles.list",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        },
        "insert": {
          "description": "Inserts a new user role.",
          "id": "dfareporting.userRoles.insert",
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserGroups.list",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "id": "dfareporting.advertiserGroups.patch",
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "insert": {
          "id": "dfareporting.advertiserGroups.insert",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Inserts a new advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.advertiserGroups.update",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "delete": {
          "description": "Deletes an existing advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "id": "dfareporting.advertiserGroups.delete",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.advertiserGroups.get",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "description": "Gets one advertiser group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "id": "dfareporting.mobileApps.get",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "description": "Gets one mobile app by ID.",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.mobileApps.list",
          "path": "userprofiles/{+profileId}/mobileApps",
          "description": "Retrieves list of available mobile apps.",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "supportsMediaUpload": true,
          "id": "dfareporting.studioCreativeAssets.insert",
          "path": "studio/creativeAssets",
          "description": "Inserts a new studio creative asset.",
          "flatPath": "studio/creativeAssets",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing dynamic targeting key."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement."
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "description": "Retrieves a list of dynamic targeting keys.",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "update": {
          "id": "dfareporting.targetingTemplates.update",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Updates an existing targeting template.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one targeting template by ID.",
          "id": "dfareporting.targetingTemplates.get",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}"
        },
        "patch": {
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "id": "dfareporting.targetingTemplates.patch",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "id": "dfareporting.targetingTemplates.list",
          "path": "userprofiles/{+profileId}/targetingTemplates"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new targeting template.",
          "id": "dfareporting.targetingTemplates.insert",
          "path": "userprofiles/{+profileId}/targetingTemplates"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "list": {
          "description": "Retrieves a list of billing assignments.",
          "id": "dfareporting.billingAssignments.list",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments"
        },
        "insert": {
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "id": "dfareporting.billingAssignments.insert",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one mobile carrier by ID.",
          "id": "dfareporting.mobileCarriers.get",
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of mobile carriers.",
          "id": "dfareporting.mobileCarriers.list",
          "path": "userprofiles/{+profileId}/mobileCarriers"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "list": {
          "description": "Retrieves the list of account permissions.",
          "id": "dfareporting.accountPermissions.list",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions"
        },
        "get": {
          "id": "dfareporting.accountPermissions.get",
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "description": "Gets one account permission by ID.",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "ads": {
      "methods": {
        "list": {
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "id": "dfareporting.ads.list",
          "path": "userprofiles/{+profileId}/ads",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "id": "dfareporting.ads.patch",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Updates an existing ad. This method supports patch semantics."
        },
        "insert": {
          "id": "dfareporting.ads.insert",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Inserts a new ad.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads"
        },
        "update": {
          "id": "dfareporting.ads.update",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Updates an existing ad.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.ads.get",
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "description": "Gets one ad by ID."
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "id": "dfareporting.accountActiveAdSummaries.get",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "description": "Gets the account's active ad summary by account ID.",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "id": "dfareporting.connectionTypes.get",
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "description": "Gets one connection type by ID.",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of connection types.",
          "id": "dfareporting.connectionTypes.list",
          "path": "userprofiles/{+profileId}/connectionTypes"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "id": "dfareporting.platformTypes.get",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "description": "Gets one platform type by ID.",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.platformTypes.list",
          "path": "userprofiles/{+profileId}/platformTypes",
          "description": "Retrieves a list of platform types."
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "delete": {
          "description": "Deletes an existing creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.delete",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "id": "dfareporting.creativeFieldValues.get",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "description": "Gets one creative field value by ID."
        },
        "update": {
          "id": "dfareporting.creativeFieldValues.update",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new creative field value.",
          "id": "dfareporting.creativeFieldValues.insert",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.list",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeFieldValues.patch",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value. This method supports patch semantics."
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "description": "Inserts a new floodlight activity.",
          "id": "dfareporting.floodlightActivities.insert",
          "path": "userprofiles/{+profileId}/floodlightActivities"
        },
        "list": {
          "id": "dfareporting.floodlightActivities.list",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "id": "dfareporting.floodlightActivities.patch",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "id": "dfareporting.floodlightActivities.delete",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing floodlight activity."
        },
        "get": {
          "description": "Gets one floodlight activity by ID.",
          "id": "dfareporting.floodlightActivities.get",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}"
        },
        "update": {
          "id": "dfareporting.floodlightActivities.update",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "description": "Generates a tag for a floodlight activity.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "insert": {
          "description": "Inserts a new creative field.",
          "id": "dfareporting.creativeFields.insert",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.creativeFields.list",
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging."
        },
        "patch": {
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "id": "dfareporting.creativeFields.patch",
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "id": "dfareporting.creativeFields.delete",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "id": "dfareporting.creativeFields.get",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "description": "Gets one creative field by ID."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFields.update",
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Updates an existing creative field."
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "id": "dfareporting.dimensionValues.query",
          "path": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "id": "dfareporting.changeLogs.get",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "description": "Gets one change log by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.list",
          "path": "userprofiles/{+profileId}/changeLogs",
          "description": "Retrieves a list of change logs. This method supports paging."
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "insert": {
          "description": "Inserts a new placement strategy.",
          "id": "dfareporting.placementStrategies.insert",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "id": "dfareporting.placementStrategies.patch",
          "path": "userprofiles/{+profileId}/placementStrategies"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "id": "dfareporting.placementStrategies.list",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging."
        },
        "delete": {
          "description": "Deletes an existing placement strategy.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.delete",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "httpMethod": "DELETE"
        },
        "get": {
          "id": "dfareporting.placementStrategies.get",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "description": "Gets one placement strategy by ID.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.placementStrategies.update",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Updates an existing placement strategy.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.targetableRemarketingLists.list",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists"
        },
        "get": {
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.targetableRemarketingLists.get",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "id": "dfareporting.languages.list",
          "path": "userprofiles/{+profileId}/languages",
          "description": "Retrieves a list of languages.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/languages"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "list": {
          "id": "dfareporting.contentCategories.list",
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "description": "Updates an existing content category. This method supports patch semantics.",
          "id": "dfareporting.contentCategories.patch",
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.insert",
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Inserts a new content category."
        },
        "update": {
          "id": "dfareporting.contentCategories.update",
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Updates an existing content category.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.delete",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "description": "Deletes an existing content category."
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.get",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "description": "Gets one content category by ID."
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserInvoices.list",
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "insert": {
          "description": "Inserts a new subaccount.",
          "id": "dfareporting.subaccounts.insert",
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "patch": {
          "id": "dfareporting.subaccounts.patch",
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.subaccounts.list",
          "path": "userprofiles/{+profileId}/subaccounts"
        },
        "get": {
          "id": "dfareporting.subaccounts.get",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "description": "Gets one subaccount by ID.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.subaccounts.update",
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Updates an existing subaccount.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "id": "dfareporting.postalCodes.list",
          "path": "userprofiles/{+profileId}/postalCodes",
          "description": "Retrieves a list of postal codes.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/postalCodes"
        },
        "get": {
          "description": "Gets one postal code by ID.",
          "id": "dfareporting.postalCodes.get",
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}"
        }
      }
    },
    "reports": {
      "methods": {
        "delete": {
          "description": "Deletes a report by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.delete",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a report by its ID.",
          "id": "dfareporting.reports.get",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        },
        "update": {
          "description": "Updates a report.",
          "id": "dfareporting.reports.update",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "run": {
          "description": "Runs a report.",
          "id": "dfareporting.reports.run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.insert",
          "path": "userprofiles/{profileId}/reports",
          "description": "Creates a report."
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports",
          "description": "Retrieves list of reports.",
          "id": "dfareporting.reports.list",
          "path": "userprofiles/{profileId}/reports"
        }
      },
      "resources": {
        "files": {
          "methods": {
            "get": {
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "id": "dfareporting.reports.files.get",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "supportsMediaDownload": true,
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "GET",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "id": "dfareporting.reports.files.list",
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "description": "Lists files for a report."
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "POST",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "id": "dfareporting.reports.compatibleFields.query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of cities, possibly filtered.",
          "id": "dfareporting.cities.list",
          "path": "userprofiles/{+profileId}/cities"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "insert": {
          "id": "dfareporting.advertiserLandingPages.insert",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Inserts a new landing page.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of landing pages.",
          "id": "dfareporting.advertiserLandingPages.list",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "id": "dfareporting.advertiserLandingPages.patch",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "get": {
          "id": "dfareporting.advertiserLandingPages.get",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "description": "Gets one landing page by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.update",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page."
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "description": "Gets one operating system by DART ID.",
          "id": "dfareporting.operatingSystems.get",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "description": "Retrieves a list of operating systems.",
          "id": "dfareporting.operatingSystems.list",
          "path": "userprofiles/{+profileId}/operatingSystems"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "description": "Gets one user role permission group by ID.",
          "id": "dfareporting.userRolePermissionGroups.get",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}"
        },
        "list": {
          "id": "dfareporting.userRolePermissionGroups.list",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "description": "Gets a list of all supported user role permission groups.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups"
        }
      }
    },
    "campaigns": {
      "methods": {
        "update": {
          "id": "dfareporting.campaigns.update",
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.campaigns.get",
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "description": "Gets one campaign by ID.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.campaigns.list",
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "id": "dfareporting.campaigns.patch",
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics."
        },
        "insert": {
          "description": "Inserts a new campaign.",
          "id": "dfareporting.campaigns.insert",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Inserts conversions.",
          "id": "dfareporting.conversions.batchinsert",
          "path": "userprofiles/{profileId}/conversions/batchinsert"
        },
        "batchupdate": {
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "id": "dfareporting.conversions.batchupdate",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "description": "Updates existing conversions."
        }
      }
    },
    "sizes": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new size.",
          "id": "dfareporting.sizes.insert",
          "path": "userprofiles/{+profileId}/sizes"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "id": "dfareporting.sizes.list",
          "path": "userprofiles/{+profileId}/sizes"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.sizes.get",
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "description": "Gets one size by ID."
        }
      }
    },
    "advertisers": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "description": "Gets one advertiser by ID.",
          "id": "dfareporting.advertisers.get",
          "path": "userprofiles/{+profileId}/advertisers/{+id}"
        },
        "update": {
          "id": "dfareporting.advertisers.update",
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Updates an existing advertiser.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "insert": {
          "description": "Inserts a new advertiser.",
          "id": "dfareporting.advertisers.insert",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.list",
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging."
        },
        "patch": {
          "id": "dfareporting.advertisers.patch",
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placements": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Updates an existing placement.",
          "id": "dfareporting.placements.update",
          "path": "userprofiles/{+profileId}/placements"
        },
        "get": {
          "id": "dfareporting.placements.get",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "description": "Gets one placement by ID.",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "generatetags": {
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.generatetags",
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "description": "Generates tags for a placement."
        },
        "patch": {
          "id": "dfareporting.placements.patch",
          "path": "userprofiles/{+profileId}/placements",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "id": "dfareporting.placements.list",
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement.",
          "id": "dfareporting.placements.insert",
          "path": "userprofiles/{+profileId}/placements"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "list": {
          "flatPath": "userprofiles",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list",
          "path": "userprofiles"
        },
        "get": {
          "id": "dfareporting.userProfiles.get",
          "path": "userprofiles/{profileId}",
          "description": "Gets one user profile by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of regions.",
          "id": "dfareporting.regions.list",
          "path": "userprofiles/{+profileId}/regions"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "id": "dfareporting.operatingSystemVersions.list",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "description": "Retrieves a list of operating system versions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystemVersions.get",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "description": "Gets one operating system version by ID."
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "id": "dfareporting.browsers.list",
          "path": "userprofiles/{+profileId}/browsers",
          "description": "Retrieves a list of browsers.",
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "insert": {
          "flatPath": "studio/dynamicFeeds",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.dynamicFeeds.insert",
          "path": "studio/dynamicFeeds",
          "description": "Inserts a new dynamic feed."
        },
        "update": {
          "id": "dfareporting.dynamicFeeds.update",
          "path": "studio/dynamicFeeds",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicFeeds"
        },
        "get": {
          "id": "dfareporting.dynamicFeeds.get",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "description": "Gets a dynamic feed by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}"
        },
        "retransform": {
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "id": "dfareporting.dynamicFeeds.retransform",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform"
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "insert": {
          "flatPath": "studio/dynamicProfiles",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.insert",
          "path": "studio/dynamicProfiles",
          "description": "Inserts a new dynamic profile."
        },
        "publish": {
          "description": "Publish for a dynamic profile.",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.publish",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "httpMethod": "POST"
        },
        "generateCode": {
          "id": "dfareporting.dynamicProfiles.generateCode",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.dynamicProfiles.get",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "description": "Gets a dynamic profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}"
        },
        "update": {
          "description": "Updates an existing dynamic profile.",
          "id": "dfareporting.dynamicProfiles.update",
          "path": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "studio/dynamicProfiles"
        }
      }
    },
    "sites": {
      "methods": {
        "insert": {
          "id": "dfareporting.sites.insert",
          "path": "userprofiles/{+profileId}/sites",
          "description": "Inserts a new site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/sites"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.sites.patch",
          "path": "userprofiles/{+profileId}/sites",
          "description": "Updates an existing site. This method supports patch semantics."
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "id": "dfareporting.sites.list",
          "path": "userprofiles/{+profileId}/sites",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging."
        },
        "get": {
          "id": "dfareporting.sites.get",
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "description": "Gets one site by ID.",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Updates an existing site.",
          "id": "dfareporting.sites.update",
          "path": "userprofiles/{+profileId}/sites"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one account permission group by ID.",
          "id": "dfareporting.accountPermissionGroups.get",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}"
        },
        "list": {
          "description": "Retrieves the list of account permission groups.",
          "id": "dfareporting.accountPermissionGroups.list",
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "get": {
          "id": "dfareporting.placementGroups.get",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "description": "Gets one placement group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.update",
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Updates an existing placement group."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "description": "Inserts a new placement group.",
          "id": "dfareporting.placementGroups.insert",
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "patch": {
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "id": "dfareporting.placementGroups.patch",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.placementGroups.list",
          "path": "userprofiles/{+profileId}/placementGroups"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "id": "dfareporting.tvCampaignDetails.get",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "description": "Gets one TvCampaignDetail by ID.",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "description": "Updates an existing creative group.",
          "id": "dfareporting.creativeGroups.update",
          "path": "userprofiles/{+profileId}/creativeGroups"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "description": "Gets one creative group by ID.",
          "id": "dfareporting.creativeGroups.get",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "id": "dfareporting.creativeGroups.patch",
          "path": "userprofiles/{+profileId}/creativeGroups"
        },
        "insert": {
          "description": "Inserts a new creative group.",
          "id": "dfareporting.creativeGroups.insert",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.list",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "description": "Updates an existing billing profile.",
          "id": "dfareporting.billingProfiles.update",
          "path": "userprofiles/{+profileId}/billingProfiles"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "description": "Gets one billing profile by ID.",
          "id": "dfareporting.billingProfiles.get",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "get": {
          "id": "dfareporting.floodlightConfigurations.get",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "description": "Gets one floodlight configuration by ID.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing floodlight configuration.",
          "id": "dfareporting.floodlightConfigurations.update",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations"
        },
        "list": {
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "id": "dfareporting.floodlightConfigurations.list",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "id": "dfareporting.floodlightConfigurations.patch",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations"
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "insert": {
          "description": "Inserts a new studio creative.",
          "id": "dfareporting.studioCreatives.insert",
          "path": "studio/creatives",
          "flatPath": "studio/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creatives/{creativesId}",
          "id": "dfareporting.studioCreatives.get",
          "path": "studio/creatives/{+studioCreativeId}",
          "description": "Gets a studio creative by ID."
        },
        "publish": {
          "flatPath": "studio/creatives/{creativesId}/publish",
          "id": "dfareporting.studioCreatives.publish",
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Publish for a studio creative."
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "description": "Gets one directory site by ID.",
          "id": "dfareporting.directorySites.get",
          "path": "userprofiles/{+profileId}/directorySites/{+id}"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "id": "dfareporting.directorySites.list",
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging."
        },
        "insert": {
          "id": "dfareporting.directorySites.insert",
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Inserts a new directory site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/directorySites"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "list": {
          "description": "Lists available video formats.",
          "id": "dfareporting.videoFormats.list",
          "path": "userprofiles/{+profileId}/videoFormats",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats"
        },
        "get": {
          "description": "Gets one video format by ID.",
          "id": "dfareporting.videoFormats.get",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}"
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "id": "dfareporting.tvCampaignSummaries.list",
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "description": "Retrieves a list of TV campaign summaries.",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "id": "dfareporting.creativeAssets.insert",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "supportsMediaUpload": true,
          "description": "Inserts a new creative asset."
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "id": "dfareporting.files.get",
          "path": "reports/{reportId}/files/{fileId}",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "supportsMediaDownload": true,
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/files",
          "description": "Lists files for a user profile.",
          "id": "dfareporting.files.list",
          "path": "userprofiles/{profileId}/files"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissions.list",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "description": "Gets a list of user role permissions, possibly filtered."
        },
        "get": {
          "id": "dfareporting.userRolePermissions.get",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "description": "Gets one user role permission by ID.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "patch": {
          "id": "dfareporting.remarketingListShares.patch",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "description": "Updates an existing remarketing list share.",
          "id": "dfareporting.remarketingListShares.update",
          "path": "userprofiles/{+profileId}/remarketingListShares"
        },
        "get": {
          "id": "dfareporting.remarketingListShares.get",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "id": "dfareporting.metros.list",
          "path": "userprofiles/{+profileId}/metros",
          "description": "Retrieves a list of metros."
        }
      }
    }
  },
  "ownerName": "Google",
  "id": "dfareporting:v5",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/"
}