{
  "version": "v5",
  "basePath": "/dfareporting/v5/",
  "ownerDomain": "google.com",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "canonicalName": "Dfareporting",
  "protocol": "rest",
  "servicePath": "dfareporting/v5/",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "title": "Campaign Manager 360 API",
  "resources": {
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one TvCampaignDetail by ID.",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "id": "dfareporting.tvCampaignDetails.get",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "id": "dfareporting.remarketingListShares.patch",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "id": "dfareporting.remarketingListShares.get",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list share.",
          "id": "dfareporting.remarketingListShares.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserInvoices.list",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one landing page by ID.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "id": "dfareporting.advertiserLandingPages.get",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new landing page.",
          "id": "dfareporting.advertiserLandingPages.insert",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "list": {
          "description": "Retrieves a list of landing pages.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.list",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing landing page.",
          "id": "dfareporting.advertiserLandingPages.update",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "description": "Inserts a new creative asset.",
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeAssets.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets"
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one directory site by ID.",
          "id": "dfareporting.directorySites.get",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites/{+id}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.insert",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Inserts a new directory site.",
          "httpMethod": "POST"
        },
        "list": {
          "path": "userprofiles/{+profileId}/directorySites",
          "id": "dfareporting.directorySites.list",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging."
        }
      }
    },
    "placements": {
      "methods": {
        "patch": {
          "id": "dfareporting.placements.patch",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement. This method supports patch semantics."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one placement by ID.",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "id": "dfareporting.placements.get",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new placement.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.insert",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "path": "userprofiles/{+profileId}/placements"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/placements",
          "id": "dfareporting.placements.list",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "generatetags": {
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "id": "dfareporting.placements.generatetags",
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Generates tags for a placement."
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing placement.",
          "id": "dfareporting.placements.update",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "description": "Gets one connection type by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.get",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/connectionTypes",
          "id": "dfareporting.connectionTypes.list",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of connection types."
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "update": {
          "description": "Updates an existing dynamic profile.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.update",
          "flatPath": "studio/dynamicProfiles",
          "path": "studio/dynamicProfiles"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a dynamic profile by ID.",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "id": "dfareporting.dynamicProfiles.get",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "studio/dynamicProfiles",
          "id": "dfareporting.dynamicProfiles.insert",
          "flatPath": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new dynamic profile."
        },
        "generateCode": {
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "httpMethod": "GET",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.generateCode",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode"
        },
        "publish": {
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Publish for a dynamic profile.",
          "id": "dfareporting.dynamicProfiles.publish",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "httpMethod": "POST"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "id": "dfareporting.billingProfiles.get",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "httpMethod": "GET",
          "description": "Gets one billing profile by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.list",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing billing profile.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.update",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "path": "userprofiles/{+profileId}/billingProfiles"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "patch": {
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "path": "userprofiles/{+profileId}/floodlightConfigurations"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one floodlight configuration by ID.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "id": "dfareporting.floodlightConfigurations.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing floodlight configuration.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.update",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "id": "dfareporting.billingAssignments.insert",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.list",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "description": "Retrieves a list of billing assignments.",
          "httpMethod": "GET"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "description": "Inserts conversions.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "id": "dfareporting.conversions.batchinsert",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "path": "userprofiles/{profileId}/conversions/batchinsert"
        },
        "batchupdate": {
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "id": "dfareporting.conversions.batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "httpMethod": "POST",
          "description": "Updates existing conversions."
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "description": "Gets one remarketing list by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetableRemarketingLists.get",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetableRemarketingLists.list",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userProfiles.get",
          "flatPath": "userprofiles/{profileId}",
          "path": "userprofiles/{profileId}",
          "description": "Gets one user profile by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Retrieves list of user profiles for a user.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userProfiles.list",
          "flatPath": "userprofiles",
          "path": "userprofiles"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one creative group by ID.",
          "id": "dfareporting.creativeGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Inserts a new creative group.",
          "httpMethod": "POST"
        },
        "list": {
          "id": "dfareporting.creativeGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging."
        },
        "patch": {
          "id": "dfareporting.creativeGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative group. This method supports patch semantics."
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing creative group.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "id": "dfareporting.operatingSystems.get",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one operating system by DART ID."
        },
        "list": {
          "description": "Retrieves a list of operating systems.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.list",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems"
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of TV campaign summaries.",
          "id": "dfareporting.tvCampaignSummaries.list",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/tvCampaignSummaries"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.patch",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "get": {
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "id": "dfareporting.placementStrategies.get",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one placement strategy by ID."
        },
        "insert": {
          "description": "Inserts a new placement strategy.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.insert",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "list": {
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.list",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "id": "dfareporting.placementStrategies.delete",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing placement strategy."
        },
        "update": {
          "id": "dfareporting.placementStrategies.update",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "PUT",
          "description": "Updates an existing placement strategy."
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "description": "Inserts a new studio creative asset.",
          "path": "studio/creativeAssets",
          "id": "dfareporting.studioCreativeAssets.insert",
          "flatPath": "studio/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "delete": {
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.delete",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "httpMethod": "DELETE"
        },
        "update": {
          "id": "dfareporting.advertiserGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser group."
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "id": "dfareporting.advertiserGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "get": {
          "description": "Gets one advertiser group by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new advertiser group.",
          "id": "dfareporting.advertiserGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "list": {
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "description": "Retrieves a list of cities, possibly filtered.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/cities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.cities.list",
          "flatPath": "userprofiles/{userprofilesId}/cities"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of metros.",
          "id": "dfareporting.metros.list",
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/metros"
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "retransform": {
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "id": "dfareporting.dynamicFeeds.retransform",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published)."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a dynamic feed by ID.",
          "id": "dfareporting.dynamicFeeds.get",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds/{+dynamicFeedId}"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new dynamic feed.",
          "id": "dfareporting.dynamicFeeds.insert",
          "flatPath": "studio/dynamicFeeds",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds"
        },
        "update": {
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicFeeds.update",
          "flatPath": "studio/dynamicFeeds",
          "path": "studio/dynamicFeeds"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "update": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.update",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "description": "Updates an existing subaccount.",
          "httpMethod": "PUT"
        },
        "get": {
          "description": "Gets one subaccount by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.get",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}"
        },
        "insert": {
          "description": "Inserts a new subaccount.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.insert",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "list": {
          "id": "dfareporting.subaccounts.list",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "GET",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.patch",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "httpMethod": "PATCH"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "description": "Gets one account permission by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.get",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}"
        },
        "list": {
          "description": "Retrieves the list of account permissions.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.list",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "description": "Gets one postal code by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.get",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}"
        },
        "list": {
          "description": "Retrieves a list of postal codes.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.list",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.regions.list",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "description": "Retrieves a list of regions.",
          "httpMethod": "GET"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "description": "Gets one creative field value by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new creative field value.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.patch",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        },
        "update": {
          "description": "Updates an existing creative field value.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.update",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        },
        "delete": {
          "id": "dfareporting.creativeFieldValues.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field value.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one operating system version by ID.",
          "id": "dfareporting.operatingSystemVersions.get",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}"
        },
        "list": {
          "description": "Retrieves a list of operating system versions.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystemVersions.list",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "path": "userprofiles/{+profileId}/operatingSystemVersions"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/languages",
          "id": "dfareporting.languages.list",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of languages."
        }
      }
    },
    "userRoles": {
      "methods": {
        "delete": {
          "description": "Deletes an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.delete",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/userRoles/{+id}"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing user role.",
          "path": "userprofiles/{+profileId}/userRoles",
          "id": "dfareporting.userRoles.update",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/userRoles",
          "id": "dfareporting.userRoles.patch",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.get",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "description": "Gets one user role by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/userRoles",
          "id": "dfareporting.userRoles.insert",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new user role."
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "id": "dfareporting.userRoles.list",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissionGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "description": "Gets one user role permission group by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Gets a list of all supported user role permission groups.",
          "id": "dfareporting.userRolePermissionGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "delete": {
          "description": "Deletes an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.delete",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}"
        },
        "update": {
          "id": "dfareporting.contentCategories.update",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "PUT",
          "description": "Updates an existing content category."
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "id": "dfareporting.contentCategories.patch",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one content category by ID.",
          "id": "dfareporting.contentCategories.get",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories/{+id}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.insert",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Inserts a new content category.",
          "httpMethod": "POST"
        },
        "list": {
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.list",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "path": "userprofiles/{+profileId}/contentCategories"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "id": "dfareporting.billingRates.list",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of browsers.",
          "path": "userprofiles/{+profileId}/browsers",
          "id": "dfareporting.browsers.list",
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing account user profile.",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.update",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one account user profile by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.get",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.insert",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Inserts a new account user profile.",
          "httpMethod": "POST"
        },
        "list": {
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.list",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "id": "dfareporting.accountUserProfiles.patch",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "id": "dfareporting.mobileCarriers.get",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one mobile carrier by ID."
        },
        "list": {
          "description": "Retrieves a list of mobile carriers.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileCarriers.list",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "path": "userprofiles/{+profileId}/mobileCarriers"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "description": "Gets one video format by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.videoFormats.get",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Lists available video formats.",
          "id": "dfareporting.videoFormats.list",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/videoFormats"
        }
      }
    },
    "sites": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.patch",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing site. This method supports patch semantics."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one site by ID.",
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "id": "dfareporting.sites.get",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new site.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.insert",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.list",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.sites.update",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PUT",
          "description": "Updates an existing site."
        }
      }
    },
    "placementGroups": {
      "methods": {
        "patch": {
          "id": "dfareporting.placementGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement group. This method supports patch semantics."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "description": "Gets one placement group by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "description": "Inserts a new placement group.",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.placementGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "update": {
          "id": "dfareporting.placementGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing placement group."
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "insert": {
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement."
        },
        "list": {
          "description": "Retrieves a list of dynamic targeting keys.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.list",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing dynamic targeting key."
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.patch",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing remarketing list. This method supports patch semantics."
        },
        "get": {
          "id": "dfareporting.remarketingLists.get",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID."
        },
        "insert": {
          "description": "Inserts a new remarketing list.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.insert",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists"
        },
        "list": {
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.list",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Updates an existing remarketing list.",
          "httpMethod": "PUT"
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.get",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "description": "Gets one account by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.list",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{+profileId}/accounts",
          "id": "dfareporting.accounts.update",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing account."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.patch",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Updates an existing account. This method supports patch semantics.",
          "httpMethod": "PATCH"
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "description": "Gets one country by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.get",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "path": "userprofiles/{+profileId}/countries/{+dartId}"
        },
        "list": {
          "description": "Retrieves a list of countries.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.list",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "path": "userprofiles/{+profileId}/countries"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "description": "Gets one floodlight activity group by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Inserts a new floodlight activity group.",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivityGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups"
        },
        "patch": {
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups"
        },
        "update": {
          "description": "Updates an existing floodlight activity group.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileApps.get",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "description": "Gets one mobile app by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.mobileApps.list",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileApps",
          "httpMethod": "GET",
          "description": "Retrieves list of available mobile apps."
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.get",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "description": "Gets one size by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new size.",
          "id": "dfareporting.sizes.insert",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.list",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "path": "userprofiles/{+profileId}/sizes",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "httpMethod": "GET"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "id": "dfareporting.accountPermissionGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "httpMethod": "GET",
          "description": "Gets one account permission group by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissionGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "description": "Retrieves the list of account permission groups.",
          "httpMethod": "GET"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.patch",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "httpMethod": "PATCH"
        },
        "get": {
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "id": "dfareporting.targetingTemplates.get",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one targeting template by ID."
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new targeting template.",
          "id": "dfareporting.targetingTemplates.insert",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates"
        },
        "list": {
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.list",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "path": "userprofiles/{+profileId}/targetingTemplates"
        },
        "update": {
          "description": "Updates an existing targeting template.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.update",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "description": "Gets the account's active ad summary by account ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountActiveAdSummaries.get",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}"
        }
      }
    },
    "ads": {
      "methods": {
        "update": {
          "description": "Updates an existing ad.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.update",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        },
        "patch": {
          "id": "dfareporting.ads.patch",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "PATCH",
          "description": "Updates an existing ad. This method supports patch semantics."
        },
        "get": {
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "id": "dfareporting.ads.get",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "description": "Gets one ad by ID."
        },
        "insert": {
          "description": "Inserts a new ad.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.insert",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "path": "userprofiles/{+profileId}/ads"
        },
        "list": {
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.list",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "httpMethod": "GET"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "httpMethod": "POST",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "id": "dfareporting.dimensionValues.query",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.get",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "path": "reports/{reportId}/files/{fileId}",
          "supportsMediaDownload": true
        },
        "list": {
          "httpMethod": "GET",
          "description": "Lists files for a user profile.",
          "id": "dfareporting.files.list",
          "flatPath": "userprofiles/{profileId}/files",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/files"
        }
      }
    },
    "creatives": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets one creative by ID.",
          "id": "dfareporting.creatives.get",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives/{+id}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.insert",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Inserts a new creative.",
          "httpMethod": "POST"
        },
        "list": {
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.list",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing creative. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/creatives",
          "id": "dfareporting.creatives.patch",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.update",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "description": "Updates an existing creative.",
          "httpMethod": "PUT"
        }
      }
    },
    "eventTags": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.get",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "description": "Gets one event tag by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new event tag.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.insert",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "list": {
          "description": "Retrieves a list of event tags, possibly filtered.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.list",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "id": "dfareporting.eventTags.patch",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "update": {
          "id": "dfareporting.eventTags.update",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "PUT",
          "description": "Updates an existing event tag."
        },
        "delete": {
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "description": "Deletes an existing event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.delete",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "DELETE"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "delete": {
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "description": "Deletes an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.delete",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "httpMethod": "DELETE"
        },
        "generatetag": {
          "httpMethod": "POST",
          "description": "Generates a tag for a floodlight activity.",
          "id": "dfareporting.floodlightActivities.generatetag",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.update",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "description": "Gets one floodlight activity by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.insert",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertisers": {
      "methods": {
        "update": {
          "path": "userprofiles/{+profileId}/advertisers",
          "id": "dfareporting.advertisers.update",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.get",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "description": "Gets one advertiser by ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "id": "dfareporting.advertisers.insert",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser."
        },
        "list": {
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.list",
          "flatPath": "userprofiles/{userprofilesId}/advertisers"
        },
        "patch": {
          "id": "dfareporting.advertisers.patch",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. This method supports patch semantics."
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "id": "dfareporting.changeLogs.get",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "httpMethod": "GET",
          "description": "Gets one change log by ID."
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "id": "dfareporting.changeLogs.list",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/changeLogs"
        }
      }
    },
    "campaigns": {
      "methods": {
        "update": {
          "path": "userprofiles/{+profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.update",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Updates an existing campaign.",
          "httpMethod": "PUT"
        },
        "get": {
          "description": "Gets one campaign by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.get",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "path": "userprofiles/{+profileId}/campaigns/{+id}"
        },
        "insert": {
          "id": "dfareporting.campaigns.insert",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "POST",
          "description": "Inserts a new campaign."
        },
        "list": {
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.list",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "path": "userprofiles/{+profileId}/campaigns"
        },
        "patch": {
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.patch",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "path": "userprofiles/{+profileId}/campaigns"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.get",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "description": "Gets one platform type by ID.",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of platform types.",
          "path": "userprofiles/{+profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "description": "Gets one user role permission by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissions.get",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissions.list",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "httpMethod": "GET"
        }
      }
    },
    "reports": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "description": "Updates a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.update",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "delete": {
          "description": "Deletes a report by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.delete",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        },
        "get": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.get",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Retrieves a report by its ID.",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Creates a report.",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.insert",
          "flatPath": "userprofiles/{profileId}/reports"
        },
        "list": {
          "description": "Retrieves list of reports.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.list",
          "flatPath": "userprofiles/{profileId}/reports"
        },
        "run": {
          "description": "Runs a report.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.run",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run"
        }
      },
      "resources": {
        "files": {
          "methods": {
            "get": {
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "httpMethod": "GET",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "supportsMediaDownload": true,
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "id": "dfareporting.reports.files.get",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}"
            },
            "list": {
              "httpMethod": "GET",
              "description": "Lists files for a report.",
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "id": "dfareporting.reports.files.list",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ]
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "httpMethod": "POST",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "id": "dfareporting.reports.compatibleFields.query",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        }
      }
    },
    "creativeFields": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field.",
          "id": "dfareporting.creativeFields.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing creative field.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "id": "dfareporting.creativeFields.update",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "id": "dfareporting.creativeFields.patch",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets one creative field by ID.",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "id": "dfareporting.creativeFields.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Inserts a new creative field.",
          "httpMethod": "POST"
        },
        "list": {
          "id": "dfareporting.creativeFields.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "GET",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging."
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "publish": {
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "description": "Publish for a studio creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.studioCreatives.publish",
          "flatPath": "studio/creatives/{creativesId}/publish",
          "httpMethod": "POST"
        },
        "get": {
          "description": "Gets a studio creative by ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.studioCreatives.get",
          "flatPath": "studio/creatives/{creativesId}",
          "path": "studio/creatives/{+studioCreativeId}"
        },
        "insert": {
          "path": "studio/creatives",
          "id": "dfareporting.studioCreatives.insert",
          "flatPath": "studio/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new studio creative."
        }
      }
    }
  },
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v5/",
  "ownerName": "Google",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "id": "dfareporting:v5",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "name": "dfareporting",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "revision": "20260213"
}