{
  "rootUrl": "https://dfareporting.googleapis.com/",
  "id": "dfareporting:v4",
  "servicePath": "dfareporting/v4/",
  "version": "v4",
  "discoveryVersion": "v1",
  "resources": {
    "creatives": {
      "methods": {
        "get": {
          "description": "Gets one creative by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "id": "dfareporting.creatives.get",
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "description": "Inserts a new creative.",
          "id": "dfareporting.creatives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "POST"
        },
        "patch": {
          "id": "dfareporting.creatives.patch",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        },
        "list": {
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.list"
        },
        "update": {
          "id": "dfareporting.creatives.update",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative.",
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "list": {
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "id": "dfareporting.subaccounts.list",
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.update",
          "description": "Updates an existing subaccount.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.get",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "description": "Gets one subaccount by ID."
        },
        "patch": {
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "id": "dfareporting.subaccounts.patch",
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "description": "Inserts a new subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "POST",
          "id": "dfareporting.subaccounts.insert"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "list": {
          "description": "Retrieves the list of account permissions.",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.list"
        },
        "get": {
          "id": "dfareporting.accountPermissions.get",
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account permission by ID.",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.targetableRemarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.targetableRemarketingLists.list",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "id": "dfareporting.conversions.batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "description": "Inserts conversions."
        },
        "batchupdate": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "id": "dfareporting.conversions.batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "description": "Updates existing conversions."
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "list": {
          "description": "Gets a list of all supported user role permission groups.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "id": "dfareporting.userRolePermissionGroups.list",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.userRolePermissionGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "description": "Gets one user role permission group by ID."
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "update": {
          "description": "Updates an existing floodlight activity.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.update",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "generatetag": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "id": "dfareporting.floodlightActivities.generatetag",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "description": "Generates a tag for a floodlight activity."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivities.list"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.insert",
          "description": "Inserts a new floodlight activity.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "id": "dfareporting.floodlightActivities.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "PATCH"
        },
        "delete": {
          "id": "dfareporting.floodlightActivities.delete",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "description": "Gets one floodlight activity by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivities.get"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserInvoices.list",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level."
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "id": "dfareporting.postalCodes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/postalCodes",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "description": "Retrieves a list of postal codes."
        },
        "get": {
          "id": "dfareporting.postalCodes.get",
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one postal code by ID.",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}"
        }
      }
    },
    "projects": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/projects",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.projects.list",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "flatPath": "userprofiles/{userprofilesId}/projects"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/projects/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.projects.get",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectsId}",
          "description": "Gets one project by ID."
        }
      }
    },
    "sites": {
      "methods": {
        "update": {
          "description": "Updates an existing site.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.update"
        },
        "list": {
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "id": "dfareporting.sites.list",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one site by ID.",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.get"
        },
        "patch": {
          "id": "dfareporting.sites.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Updates an existing site. This method supports patch semantics."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Inserts a new site.",
          "id": "dfareporting.sites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "POST"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.patch",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "description": "Inserts a new placement group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "POST",
          "id": "dfareporting.placementGroups.insert"
        },
        "get": {
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.get",
          "description": "Gets one placement group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "description": "Updates an existing placement group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.placementGroups.update"
        },
        "list": {
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "id": "dfareporting.placementGroups.list",
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "description": "Gets one floodlight activity group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.get"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "description": "Inserts a new floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "POST"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics."
        },
        "update": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.update",
          "description": "Updates an existing floodlight activity group.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "list": {
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.list",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "ads": {
      "methods": {
        "get": {
          "id": "dfareporting.ads.get",
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one ad by ID.",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}"
        },
        "insert": {
          "id": "dfareporting.ads.insert",
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new ad.",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "PATCH",
          "id": "dfareporting.ads.patch"
        },
        "list": {
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.list"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "PUT",
          "id": "dfareporting.ads.update",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "description": "Updates an existing ad."
        }
      }
    },
    "userProfiles": {
      "methods": {
        "list": {
          "description": "Retrieves list of user profiles for a user.",
          "flatPath": "userprofiles",
          "path": "userprofiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userProfiles.list"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}",
          "description": "Gets one user profile by ID.",
          "id": "dfareporting.userProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}",
          "httpMethod": "GET"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "list": {
          "description": "Lists available video formats.",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "path": "userprofiles/{+profileId}/videoFormats",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.videoFormats.list"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "description": "Gets one video format by ID.",
          "id": "dfareporting.videoFormats.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "httpMethod": "GET"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.insert",
          "description": "Inserts a new account user profile.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "id": "dfareporting.accountUserProfiles.patch",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "description": "Updates an existing account user profile. This method supports patch semantics."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "description": "Gets one account user profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.accountUserProfiles.get"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "description": "Updates an existing account user profile.",
          "id": "dfareporting.accountUserProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "PUT"
        },
        "list": {
          "id": "dfareporting.accountUserProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging."
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "list": {
          "id": "dfareporting.billingProfiles.list",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles"
        },
        "get": {
          "description": "Gets one billing profile by ID.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.get"
        },
        "update": {
          "id": "dfareporting.billingProfiles.update",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing billing profile.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles"
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "description": "Gets one size by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.sizes.get"
        },
        "insert": {
          "description": "Inserts a new size.",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "path": "userprofiles/{+profileId}/sizes",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.insert"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "id": "dfareporting.sizes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes",
          "httpMethod": "GET"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "description": "Updates an existing creative field value.",
          "id": "dfareporting.creativeFieldValues.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "PUT"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeFieldValues.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "description": "Inserts a new creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "POST",
          "id": "dfareporting.creativeFieldValues.insert"
        },
        "patch": {
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.patch",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "id": "dfareporting.creativeFieldValues.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field value."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFieldValues.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "description": "Gets one creative field value by ID."
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "delete": {
          "id": "dfareporting.placementStrategies.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing placement strategy."
        },
        "get": {
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.get",
          "description": "Gets one placement strategy by ID.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}"
        },
        "patch": {
          "id": "dfareporting.placementStrategies.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Inserts a new placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "POST",
          "id": "dfareporting.placementStrategies.insert"
        },
        "update": {
          "id": "dfareporting.placementStrategies.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Updates an existing placement strategy."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "GET",
          "id": "dfareporting.placementStrategies.list"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "description": "Inserts a new creative asset.",
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "supportsMediaUpload": true,
          "id": "dfareporting.creativeAssets.insert",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "description": "Inserts a new creative group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "POST",
          "id": "dfareporting.creativeGroups.insert"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.patch",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "get": {
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.get",
          "description": "Gets one creative group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "GET",
          "id": "dfareporting.creativeGroups.list"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "description": "Updates an existing creative group.",
          "id": "dfareporting.creativeGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "PUT"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "description": "Retrieves a list of metros.",
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "path": "userprofiles/{+profileId}/metros",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.metros.list"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "id": "dfareporting.platformTypes.list",
          "path": "userprofiles/{+profileId}/platformTypes",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of platform types.",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes"
        },
        "get": {
          "description": "Gets one platform type by ID.",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.get"
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.inventoryItems.get",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems/{inventoryItemsId}",
          "description": "Gets one inventory item by ID."
        },
        "list": {
          "id": "dfareporting.inventoryItems.list",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.list",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "update": {
          "id": "dfareporting.advertiserGroups.update",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Inserts a new advertiser group.",
          "id": "dfareporting.advertiserGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "POST"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "id": "dfareporting.advertiserGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "PATCH"
        },
        "delete": {
          "id": "dfareporting.advertiserGroups.delete",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing advertiser group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        },
        "get": {
          "description": "Gets one advertiser group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "id": "dfareporting.advertiserGroups.get",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "description": "Retrieves a list of operating system versions.",
          "id": "dfareporting.operatingSystemVersions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "httpMethod": "GET"
        },
        "get": {
          "description": "Gets one operating system version by ID.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "id": "dfareporting.operatingSystemVersions.get",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "eventTags": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Inserts a new event tag.",
          "id": "dfareporting.eventTags.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "POST"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.patch",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "id": "dfareporting.eventTags.delete"
        },
        "get": {
          "description": "Gets one event tag by ID.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.get"
        },
        "list": {
          "description": "Retrieves a list of event tags, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.list"
        },
        "update": {
          "description": "Updates an existing event tag.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.update"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "id": "dfareporting.mobileCarriers.get",
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile carrier by ID.",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "description": "Retrieves a list of mobile carriers.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "httpMethod": "GET",
          "id": "dfareporting.mobileCarriers.list"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "get": {
          "description": "Gets one remarketing list by ID.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.get"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "PATCH",
          "id": "dfareporting.remarketingLists.patch"
        },
        "insert": {
          "id": "dfareporting.remarketingLists.insert",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new remarketing list.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingLists.list",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Updates an existing remarketing list.",
          "id": "dfareporting.remarketingLists.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "PUT"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "description": "Retrieves a list of browsers.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/browsers",
          "httpMethod": "GET",
          "id": "dfareporting.browsers.list"
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicFeeds.insert",
          "flatPath": "studio/dynamicFeeds",
          "description": "Inserts a new dynamic feed."
        },
        "get": {
          "id": "dfareporting.dynamicFeeds.get",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a dynamic feed by ID.",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}"
        },
        "update": {
          "flatPath": "studio/dynamicFeeds",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds",
          "httpMethod": "PUT",
          "id": "dfareporting.dynamicFeeds.update"
        },
        "retransform": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicFeeds.retransform",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published)."
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing dynamic targeting key.",
          "id": "dfareporting.dynamicTargetingKeys.delete"
        },
        "insert": {
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys"
        },
        "list": {
          "description": "Retrieves a list of dynamic targeting keys.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.list"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "description": "Gets one remarketing list share by remarketing list ID.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.get"
        },
        "update": {
          "description": "Updates an existing remarketing list share.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.update"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.patch",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        }
      }
    },
    "orders": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "id": "dfareporting.orders.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders",
          "httpMethod": "GET"
        },
        "get": {
          "id": "dfareporting.orders.get",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one order by ID.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders/{ordersId}"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "description": "Retrieves list of report dimension values for a list of filters.",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "id": "dfareporting.dimensionValues.query",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      }
    },
    "advertisers": {
      "methods": {
        "list": {
          "id": "dfareporting.advertisers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging."
        },
        "update": {
          "id": "dfareporting.advertisers.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "description": "Updates an existing advertiser."
        },
        "get": {
          "id": "dfareporting.advertisers.get",
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one advertiser by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}"
        },
        "insert": {
          "description": "Inserts a new advertiser.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.insert"
        },
        "patch": {
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.patch",
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placements": {
      "methods": {
        "patch": {
          "description": "Updates an existing placement. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.patch",
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Inserts a new placement.",
          "id": "dfareporting.placements.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "POST"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.placements.get",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "description": "Gets one placement by ID."
        },
        "list": {
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.list",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "generatetags": {
          "description": "Generates tags for a placement.",
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.generatetags"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "PUT",
          "id": "dfareporting.placements.update",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Updates an existing placement."
        }
      }
    },
    "campaigns": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "PUT",
          "id": "dfareporting.campaigns.update",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Updates an existing campaign."
        },
        "list": {
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.list",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        },
        "insert": {
          "id": "dfareporting.campaigns.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Inserts a new campaign."
        },
        "patch": {
          "id": "dfareporting.campaigns.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics."
        },
        "get": {
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.get",
          "description": "Gets one campaign by ID.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "description": "Gets one change log by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.changeLogs.get"
        },
        "list": {
          "path": "userprofiles/{+profileId}/changeLogs",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.list",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "description": "Retrieves a list of regions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/regions",
          "httpMethod": "GET",
          "id": "dfareporting.regions.list"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "httpMethod": "GET",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "description": "Gets the account's active ad summary by account ID."
        }
      }
    },
    "creativeFields": {
      "methods": {
        "delete": {
          "id": "dfareporting.creativeFields.delete",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "description": "Gets one creative field by ID.",
          "id": "dfareporting.creativeFields.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new creative field.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "id": "dfareporting.creativeFields.insert",
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "id": "dfareporting.creativeFields.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "PATCH"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFields.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging."
        },
        "update": {
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.update",
          "description": "Updates an existing creative field.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations"
        },
        "list": {
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaignCreativeAssociations.list"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "description": "Gets one mobile app by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.mobileApps.get"
        },
        "list": {
          "description": "Retrieves list of available mobile apps.",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "id": "dfareporting.mobileApps.list",
          "path": "userprofiles/{+profileId}/mobileApps",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "id": "dfareporting.billingAssignments.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned."
        },
        "list": {
          "id": "dfareporting.billingAssignments.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "description": "Retrieves a list of billing assignments."
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "description": "Retrieves a list of landing pages.",
          "id": "dfareporting.advertiserLandingPages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing landing page.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.update",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.advertiserLandingPages.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "description": "Inserts a new landing page."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "PATCH",
          "id": "dfareporting.advertiserLandingPages.patch",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "description": "Updates an existing landing page. This method supports patch semantics."
        },
        "get": {
          "description": "Gets one landing page by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "id": "dfareporting.advertiserLandingPages.get",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "list": {
          "description": "Retrieves a list of operating systems.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "id": "dfareporting.operatingSystems.list",
          "path": "userprofiles/{+profileId}/operatingSystems",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one operating system by DART ID.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.get"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "delete": {
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing content category.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.delete"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.contentCategories.get",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "description": "Gets one content category by ID."
        },
        "insert": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.insert",
          "description": "Inserts a new content category.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "patch": {
          "description": "Updates an existing content category. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "id": "dfareporting.contentCategories.patch",
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.contentCategories.list",
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "update": {
          "id": "dfareporting.contentCategories.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "description": "Updates an existing content category."
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.targetingTemplates.get",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "description": "Gets one targeting template by ID."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "PATCH",
          "id": "dfareporting.targetingTemplates.patch"
        },
        "insert": {
          "id": "dfareporting.targetingTemplates.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "description": "Inserts a new targeting template."
        },
        "update": {
          "id": "dfareporting.targetingTemplates.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "description": "Updates an existing targeting template."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "GET",
          "id": "dfareporting.targetingTemplates.list",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging."
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/connectionTypes",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.list",
          "description": "Retrieves a list of connection types.",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes"
        },
        "get": {
          "id": "dfareporting.connectionTypes.get",
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one connection type by ID.",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}"
        }
      }
    },
    "userRoles": {
      "methods": {
        "patch": {
          "description": "Updates an existing user role. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.patch",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.userRoles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "description": "Inserts a new user role."
        },
        "get": {
          "id": "dfareporting.userRoles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "description": "Gets one user role by ID."
        },
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "GET",
          "id": "dfareporting.userRoles.list",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging."
        },
        "update": {
          "description": "Updates an existing user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.update"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "description": "Retrieves a list of languages.",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "path": "userprofiles/{+profileId}/languages",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.languages.list"
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "description": "Gets one country by ID.",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.get"
        },
        "list": {
          "description": "Retrieves a list of countries.",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "id": "dfareporting.countries.list",
          "path": "userprofiles/{+profileId}/countries",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightConfigurations.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "description": "Gets one floodlight configuration by ID."
        },
        "update": {
          "id": "dfareporting.floodlightConfigurations.update",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight configuration.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightConfigurations.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics."
        },
        "list": {
          "id": "dfareporting.floodlightConfigurations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "description": "Retrieves a list of floodlight configurations, possibly filtered."
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "flatPath": "studio/creativeAssets",
          "description": "Inserts a new studio creative asset.",
          "id": "dfareporting.studioCreativeAssets.insert",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creativeAssets",
          "httpMethod": "POST"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "description": "Retrieves the list of account permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissionGroups.list"
        },
        "get": {
          "description": "Gets one account permission group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "id": "dfareporting.accountPermissionGroups.get",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "httpMethod": "GET",
          "id": "dfareporting.billingRates.list"
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "description": "Retrieves a list of TV campaign summaries.",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "id": "dfareporting.tvCampaignSummaries.list",
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accounts": {
      "methods": {
        "patch": {
          "description": "Updates an existing account. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "id": "dfareporting.accounts.patch",
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.accounts.get",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account by ID.",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}"
        },
        "update": {
          "id": "dfareporting.accounts.update",
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account.",
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.accounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "GET"
        }
      }
    },
    "directorySites": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/directorySites",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.insert",
          "description": "Inserts a new directory site.",
          "flatPath": "userprofiles/{userprofilesId}/directorySites"
        },
        "get": {
          "description": "Gets one directory site by ID.",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.get"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites",
          "httpMethod": "GET",
          "id": "dfareporting.directorySites.list"
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "generateCode": {
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "httpMethod": "GET",
          "id": "dfareporting.dynamicProfiles.generateCode"
        },
        "update": {
          "id": "dfareporting.dynamicProfiles.update",
          "path": "studio/dynamicProfiles",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing dynamic profile.",
          "flatPath": "studio/dynamicProfiles"
        },
        "insert": {
          "description": "Inserts a new dynamic profile.",
          "flatPath": "studio/dynamicProfiles",
          "id": "dfareporting.dynamicProfiles.insert",
          "path": "studio/dynamicProfiles",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "publish": {
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "httpMethod": "POST",
          "description": "Publish for a dynamic profile.",
          "id": "dfareporting.dynamicProfiles.publish"
        },
        "get": {
          "description": "Gets a dynamic profile by ID.",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "id": "dfareporting.dynamicProfiles.get",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creatives",
          "httpMethod": "POST",
          "id": "dfareporting.studioCreatives.insert",
          "flatPath": "studio/creatives",
          "description": "Inserts a new studio creative."
        },
        "publish": {
          "id": "dfareporting.studioCreatives.publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creatives/{creativesId}/publish",
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "httpMethod": "POST",
          "description": "Publish for a studio creative."
        },
        "get": {
          "flatPath": "studio/creatives/{creativesId}",
          "description": "Gets a studio creative by ID.",
          "id": "dfareporting.studioCreatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creatives/{+studioCreativeId}",
          "httpMethod": "GET"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "description": "Gets one user role permission by ID.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissions.get"
        },
        "list": {
          "id": "dfareporting.userRolePermissions.list",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of user role permissions, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions"
        }
      }
    },
    "reports": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "description": "Deletes a report by its ID.",
          "id": "dfareporting.reports.delete"
        },
        "get": {
          "id": "dfareporting.reports.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Retrieves a report by its ID."
        },
        "insert": {
          "path": "userprofiles/{profileId}/reports",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.insert",
          "description": "Creates a report.",
          "flatPath": "userprofiles/{profileId}/reports"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Updates an existing report. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PATCH",
          "id": "dfareporting.reports.patch"
        },
        "run": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST",
          "id": "dfareporting.reports.run",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "description": "Runs a report."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "id": "dfareporting.reports.update",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Updates a report."
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/reports",
          "description": "Retrieves list of reports.",
          "id": "dfareporting.reports.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "files": {
          "methods": {
            "get": {
              "id": "dfareporting.reports.files.get",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "supportsMediaDownload": true,
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}"
            },
            "list": {
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "description": "Lists files for a report.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "httpMethod": "GET",
              "id": "dfareporting.reports.files.list"
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST",
              "id": "dfareporting.reports.compatibleFields.query"
            }
          }
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "id": "dfareporting.cities.list",
          "path": "userprofiles/{+profileId}/cities",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of cities, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/cities"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "description": "Gets one TvCampaignDetail by ID.",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "id": "dfareporting.tvCampaignDetails.get",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/files",
          "description": "Lists files for a user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "id": "dfareporting.files.list"
        },
        "get": {
          "supportsMediaDownload": true,
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "id": "dfareporting.files.get",
          "path": "reports/{reportId}/files/{fileId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      }
    }
  },
  "canonicalName": "Dfareporting",
  "ownerName": "Google",
  "title": "Campaign Manager 360 API",
  "name": "dfareporting",
  "kind": "discovery#restDescription",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "revision": "20260310",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "basePath": "/dfareporting/v4/",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "protocol": "rest"
}