{
  "rootUrl": "https://dfareporting.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "basePath": "/dfareporting/v5/",
  "discoveryVersion": "v1",
  "version": "v5",
  "protocol": "rest",
  "kind": "discovery#restDescription",
  "id": "dfareporting:v5",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v5/",
  "fullyEncodeReservedExpansion": true,
  "canonicalName": "Dfareporting",
  "revision": "20260310",
  "resources": {
    "languages": {
      "methods": {
        "list": {
          "id": "dfareporting.languages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/languages",
          "description": "Retrieves a list of languages.",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "httpMethod": "GET"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "description": "Gets one user role permission group by ID.",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissionGroups.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissionGroups.list",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "description": "Gets a list of all supported user role permission groups.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "httpMethod": "GET"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivityGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "description": "Gets one floodlight activity group by ID."
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "description": "Inserts a new floodlight activity group.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.insert"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.list",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups"
        },
        "update": {
          "id": "dfareporting.floodlightActivityGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity group.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "PUT"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "get": {
          "description": "Gets one landing page by ID.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "id": "dfareporting.advertiserLandingPages.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "POST",
          "id": "dfareporting.advertiserLandingPages.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new landing page.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "description": "Retrieves a list of landing pages.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.list"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page.",
          "id": "dfareporting.advertiserLandingPages.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "PATCH",
          "id": "dfareporting.advertiserLandingPages.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page. This method supports patch semantics."
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "get": {
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "description": "Gets a dynamic profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.get",
          "httpMethod": "GET",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "studio/dynamicProfiles",
          "description": "Inserts a new dynamic profile.",
          "path": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.insert"
        },
        "generateCode": {
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "id": "dfareporting.dynamicProfiles.generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.update",
          "path": "studio/dynamicProfiles",
          "description": "Updates an existing dynamic profile.",
          "flatPath": "studio/dynamicProfiles",
          "httpMethod": "PUT"
        },
        "publish": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.publish",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "httpMethod": "POST",
          "description": "Publish for a dynamic profile.",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.get",
          "description": "Gets one account permission by ID.",
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}"
        },
        "list": {
          "id": "dfareporting.accountPermissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of account permissions.",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "httpMethod": "GET"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "httpMethod": "GET",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets the account's active ad summary by account ID.",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}"
        }
      }
    },
    "placements": {
      "methods": {
        "generatetags": {
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "httpMethod": "POST",
          "id": "dfareporting.placements.generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates tags for a placement.",
          "path": "userprofiles/{+profileId}/placements/generatetags"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/placements",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "list": {
          "path": "userprofiles/{+profileId}/placements",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "id": "dfareporting.placements.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "path": "userprofiles/{+profileId}/placements",
          "description": "Updates an existing placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.update"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.get",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "description": "Gets one placement by ID."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "POST",
          "id": "dfareporting.placements.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "description": "Inserts a new placement."
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "description": "Gets one mobile app by ID.",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileApps.get"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileApps.list",
          "description": "Retrieves list of available mobile apps.",
          "path": "userprofiles/{+profileId}/mobileApps"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles",
          "path": "userprofiles",
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{profileId}",
          "httpMethod": "GET",
          "id": "dfareporting.userProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user profile by ID.",
          "path": "userprofiles/{profileId}"
        }
      }
    },
    "countries": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.list",
          "path": "userprofiles/{+profileId}/countries",
          "description": "Retrieves a list of countries.",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "httpMethod": "GET"
        },
        "get": {
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "description": "Gets one country by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "description": "Gets one creative field value by ID.",
          "id": "dfareporting.creativeFieldValues.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.insert",
          "description": "Inserts a new creative field value.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        },
        "delete": {
          "id": "dfareporting.creativeFieldValues.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "description": "Deletes an existing creative field value.",
          "httpMethod": "DELETE"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.list"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.update",
          "description": "Updates an existing creative field value.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PUT"
        },
        "patch": {
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        }
      }
    },
    "ads": {
      "methods": {
        "list": {
          "id": "dfareporting.ads.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.update",
          "description": "Updates an existing ad.",
          "path": "userprofiles/{+profileId}/ads"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.patch"
        },
        "get": {
          "id": "dfareporting.ads.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "description": "Gets one ad by ID.",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.insert",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Inserts a new ad.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "POST"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "description": "Gets one operating system by DART ID.",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.get"
        },
        "list": {
          "description": "Retrieves a list of operating systems.",
          "path": "userprofiles/{+profileId}/operatingSystems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list by ID.",
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Inserts a new remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "patch": {
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "list": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Updates an existing remarketing list.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "patch": {
          "id": "dfareporting.placementStrategies.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "PATCH"
        },
        "list": {
          "id": "dfareporting.placementStrategies.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Updates an existing placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "description": "Gets one placement strategy by ID.",
          "id": "dfareporting.placementStrategies.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.insert",
          "description": "Inserts a new placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies"
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "description": "Deletes an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.delete",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "description": "Retrieves the list of account permission groups.",
          "id": "dfareporting.accountPermissionGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups"
        },
        "get": {
          "description": "Gets one account permission group by ID.",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "id": "dfareporting.accountPermissionGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "description": "Gets one remarketing list by ID.",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetableRemarketingLists.get"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "id": "dfareporting.targetableRemarketingLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists"
        }
      }
    },
    "advertisers": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.list"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PUT",
          "id": "dfareporting.advertisers.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser.",
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "patch": {
          "id": "dfareporting.advertisers.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PATCH"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "description": "Gets one advertiser by ID.",
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "id": "dfareporting.advertisers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "description": "Inserts a new advertiser.",
          "path": "userprofiles/{+profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.insert"
        }
      }
    },
    "eventTags": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.list"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Updates an existing event tag.",
          "id": "dfareporting.eventTags.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.get",
          "description": "Gets one event tag by ID.",
          "path": "userprofiles/{+profileId}/eventTags/{+id}"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Inserts a new event tag.",
          "id": "dfareporting.eventTags.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.delete",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "description": "Deletes an existing event tag."
        }
      }
    },
    "userRoles": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PATCH",
          "id": "dfareporting.userRoles.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Updates an existing user role. This method supports patch semantics."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.list",
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.userRoles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Updates an existing user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PUT"
        },
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing user role.",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "DELETE"
        },
        "get": {
          "description": "Gets one user role by ID.",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "id": "dfareporting.userRoles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}"
        },
        "insert": {
          "id": "dfareporting.userRoles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new user role.",
          "path": "userprofiles/{+profileId}/userRoles",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "POST"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.patch",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.list",
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.placementGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement group.",
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "get": {
          "description": "Gets one placement group by ID.",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "id": "dfareporting.placementGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.insert",
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Inserts a new placement group."
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "path": "userprofiles/{+profileId}/regions",
          "description": "Retrieves a list of regions.",
          "id": "dfareporting.regions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.list",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creativeGroups"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group.",
          "path": "userprofiles/{+profileId}/creativeGroups"
        },
        "patch": {
          "id": "dfareporting.creativeGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "PATCH"
        },
        "get": {
          "id": "dfareporting.creativeGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "description": "Gets one creative group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.insert",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Inserts a new creative group.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "POST"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "description": "Retrieves a list of mobile carriers.",
          "id": "dfareporting.mobileCarriers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one mobile carrier by ID.",
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileCarriers.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations"
        },
        "list": {
          "id": "dfareporting.campaignCreativeAssociations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "httpMethod": "GET"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "id": "dfareporting.contentCategories.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Updates an existing content category.",
          "id": "dfareporting.contentCategories.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.patch",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "PATCH"
        },
        "get": {
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "description": "Gets one content category by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "POST",
          "id": "dfareporting.contentCategories.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new content category.",
          "path": "userprofiles/{+profileId}/contentCategories"
        },
        "delete": {
          "id": "dfareporting.contentCategories.delete",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "description": "Deletes an existing content category.",
          "httpMethod": "DELETE"
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "httpMethod": "GET",
          "id": "dfareporting.directorySites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one directory site by ID.",
          "path": "userprofiles/{+profileId}/directorySites/{+id}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.insert",
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Inserts a new directory site."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.list",
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "GET"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.cities.list",
          "path": "userprofiles/{+profileId}/cities",
          "description": "Retrieves a list of cities, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "httpMethod": "GET"
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.get",
          "description": "Gets one account by ID.",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "httpMethod": "GET"
        },
        "list": {
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.accounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        },
        "update": {
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Updates an existing account.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "PATCH",
          "id": "dfareporting.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Updates an existing account. This method supports patch semantics."
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.patch",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PATCH"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.list",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/targetingTemplates"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PUT",
          "id": "dfareporting.targetingTemplates.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Updates an existing targeting template."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.get",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "description": "Gets one targeting template by ID.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "httpMethod": "GET"
        },
        "insert": {
          "id": "dfareporting.targetingTemplates.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new targeting template.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "POST"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys"
        },
        "delete": {
          "description": "Deletes an existing dynamic targeting key.",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "description": "Retrieves a list of dynamic targeting keys.",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.list",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.update",
          "description": "Updates an existing floodlight configuration.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.patch",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics."
        },
        "get": {
          "id": "dfareporting.floodlightConfigurations.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "description": "Gets one floodlight configuration by ID.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "httpMethod": "GET"
        }
      }
    },
    "sites": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "description": "Gets one site by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.get"
        },
        "insert": {
          "description": "Inserts a new site.",
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/sites"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "description": "Updates an existing site. This method supports patch semantics.",
          "id": "dfareporting.sites.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/sites",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "id": "dfareporting.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/sites"
        },
        "update": {
          "id": "dfareporting.sites.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing site.",
          "path": "userprofiles/{+profileId}/sites",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "PUT"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserInvoices.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "httpMethod": "GET"
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "description": "Retrieves a list of TV campaign summaries.",
          "id": "dfareporting.tvCampaignSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "description": "Gets one video format by ID.",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "id": "dfareporting.videoFormats.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.videoFormats.list",
          "path": "userprofiles/{+profileId}/videoFormats",
          "description": "Lists available video formats."
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "httpMethod": "GET",
          "id": "dfareporting.metros.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of metros.",
          "path": "userprofiles/{+profileId}/metros"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "description": "Deletes an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.delete",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}"
        },
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates a tag for a floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "description": "Gets one floodlight activity by ID.",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "id": "dfareporting.floodlightActivities.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.insert",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Inserts a new floodlight activity."
        },
        "list": {
          "id": "dfareporting.floodlightActivities.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.floodlightActivities.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "PUT"
        },
        "patch": {
          "id": "dfareporting.floodlightActivities.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "PATCH"
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "description": "Gets a dynamic feed by ID.",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "id": "dfareporting.dynamicFeeds.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new dynamic feed.",
          "path": "studio/dynamicFeeds",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicFeeds.insert",
          "httpMethod": "POST",
          "flatPath": "studio/dynamicFeeds"
        },
        "retransform": {
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicFeeds.retransform",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published)."
        },
        "update": {
          "id": "dfareporting.dynamicFeeds.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "path": "studio/dynamicFeeds",
          "flatPath": "studio/dynamicFeeds",
          "httpMethod": "PUT"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.list",
          "path": "userprofiles/{+profileId}/changeLogs",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "httpMethod": "GET"
        },
        "get": {
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "description": "Gets one change log by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}"
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "description": "Gets one size by ID.",
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.get"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "description": "Inserts a new size.",
          "path": "userprofiles/{+profileId}/sizes",
          "id": "dfareporting.sizes.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/sizes",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "id": "dfareporting.sizes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/sizes"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.list",
          "path": "userprofiles/{+profileId}/postalCodes",
          "description": "Retrieves a list of postal codes.",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.get",
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "description": "Gets one postal code by ID.",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "httpMethod": "GET"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingRates.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates"
        }
      }
    },
    "reports": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/reports",
          "description": "Retrieves list of reports.",
          "id": "dfareporting.reports.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports"
        },
        "update": {
          "description": "Updates a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.get",
          "description": "Retrieves a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "GET"
        },
        "insert": {
          "path": "userprofiles/{profileId}/reports",
          "description": "Creates a report.",
          "id": "dfareporting.reports.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.delete",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "description": "Deletes a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        },
        "run": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST",
          "id": "dfareporting.reports.run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Runs a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}/run"
        }
      },
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "id": "dfareporting.reports.compatibleFields.query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST"
            }
          }
        },
        "files": {
          "methods": {
            "get": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "id": "dfareporting.reports.files.get",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "supportsMediaDownload": true,
              "httpMethod": "GET",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "description": "Lists files for a report.",
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "id": "dfareporting.reports.files.list",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ]
            }
          }
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "publish": {
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "description": "Publish for a studio creative.",
          "httpMethod": "POST",
          "id": "dfareporting.studioCreatives.publish",
          "flatPath": "studio/creatives/{creativesId}/publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.studioCreatives.get",
          "description": "Gets a studio creative by ID.",
          "path": "studio/creatives/{+studioCreativeId}",
          "flatPath": "studio/creatives/{creativesId}",
          "httpMethod": "GET"
        },
        "insert": {
          "path": "studio/creatives",
          "description": "Inserts a new studio creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.studioCreatives.insert",
          "httpMethod": "POST",
          "flatPath": "studio/creatives"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "description": "Gets one subaccount by ID."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.insert",
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Inserts a new subaccount."
        },
        "patch": {
          "id": "dfareporting.subaccounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "PATCH"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/subaccounts"
        },
        "update": {
          "description": "Updates an existing subaccount.",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.list",
          "path": "userprofiles/{+profileId}/platformTypes",
          "description": "Retrieves a list of platform types."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.get",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "description": "Gets one platform type by ID.",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "httpMethod": "GET"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.list",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creativeFields"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.update",
          "description": "Updates an existing creative field.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "PUT"
        },
        "patch": {
          "id": "dfareporting.creativeFields.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "PATCH"
        },
        "get": {
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "description": "Gets one creative field by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Inserts a new creative field.",
          "id": "dfareporting.creativeFields.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "description": "Deletes an existing creative field."
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.get",
          "description": "Gets one connection type by ID.",
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Retrieves a list of connection types.",
          "path": "userprofiles/{+profileId}/connectionTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.insert",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "description": "Retrieves a list of billing assignments.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.list"
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "id": "dfareporting.studioCreativeAssets.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new studio creative asset.",
          "path": "studio/creativeAssets",
          "flatPath": "studio/creativeAssets",
          "supportsMediaUpload": true,
          "httpMethod": "POST"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "id": "dfareporting.creativeAssets.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative asset.",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "description": "Retrieves a list of browsers.",
          "path": "userprofiles/{+profileId}/browsers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.browsers.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/browsers"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchupdate": {
          "id": "dfareporting.conversions.batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "description": "Updates existing conversions.",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST"
        },
        "batchinsert": {
          "description": "Inserts conversions.",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "id": "dfareporting.conversions.batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "httpMethod": "POST",
          "id": "dfareporting.dimensionValues.query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves list of report dimension values for a list of filters.",
          "path": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.list"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.update",
          "description": "Updates an existing advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PUT"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PATCH",
          "id": "dfareporting.advertiserGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics."
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one advertiser group by ID.",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Inserts a new advertiser group.",
          "id": "dfareporting.advertiserGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.delete",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "description": "Deletes an existing advertiser group."
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.list"
        },
        "update": {
          "id": "dfareporting.accountUserProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Updates an existing account user profile.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PUT"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.patch",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PATCH"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "description": "Gets one account user profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.get"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "POST",
          "id": "dfareporting.accountUserProfiles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Inserts a new account user profile."
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingListShares.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list share by remarketing list ID.",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "httpMethod": "PATCH",
          "id": "dfareporting.remarketingListShares.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "httpMethod": "PUT",
          "id": "dfareporting.remarketingListShares.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share."
        }
      }
    },
    "campaigns": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.list",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "GET"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.update",
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PUT"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.patch",
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PATCH"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "description": "Gets one campaign by ID.",
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "id": "dfareporting.campaigns.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "POST",
          "id": "dfareporting.campaigns.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Inserts a new campaign."
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "id": "dfareporting.operatingSystemVersions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system version by ID.",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.operatingSystemVersions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of operating system versions.",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "httpMethod": "GET"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "description": "Gets one TvCampaignDetail by ID.",
          "id": "dfareporting.tvCampaignDetails.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "description": "Gets one billing profile by ID.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "id": "dfareporting.billingProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "id": "dfareporting.billingProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/billingProfiles",
          "description": "Updates an existing billing profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles"
        }
      }
    },
    "creatives": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "description": "Gets one creative by ID.",
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.get"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "POST",
          "id": "dfareporting.creatives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Inserts a new creative."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.list",
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging."
        },
        "update": {
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Updates an existing creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Updates an existing creative. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "id": "dfareporting.files.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "path": "reports/{reportId}/files/{fileId}",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "supportsMediaDownload": true,
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/files",
          "path": "userprofiles/{profileId}/files",
          "description": "Lists files for a user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.list"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissions.list"
        },
        "get": {
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "description": "Gets one user role permission by ID.",
          "id": "dfareporting.userRolePermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}"
        }
      }
    }
  },
  "servicePath": "dfareporting/v5/",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "batchPath": "batch",
  "title": "Campaign Manager 360 API",
  "name": "dfareporting"
}