{
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "basePath": "/dfareporting/v5/",
  "title": "Campaign Manager 360 API",
  "name": "dfareporting",
  "id": "dfareporting:v5",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "ownerDomain": "google.com",
  "protocol": "rest",
  "revision": "20260310",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v5/",
  "kind": "discovery#restDescription",
  "servicePath": "dfareporting/v5/",
  "resources": {
    "cities": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of cities, possibly filtered.",
          "path": "userprofiles/{+profileId}/cities",
          "id": "dfareporting.cities.list"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field value.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.update"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "id": "dfareporting.creativeFieldValues.get",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "description": "Gets one creative field value by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeFieldValues.list"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "POST",
          "id": "dfareporting.creativeFieldValues.insert",
          "description": "Inserts a new creative field value.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "description": "Deletes an existing creative field value.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.delete"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeFieldValues.patch",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "contentCategories": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "GET",
          "id": "dfareporting.contentCategories.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one content category by ID.",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "id": "dfareporting.contentCategories.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Updates an existing content category."
        },
        "insert": {
          "id": "dfareporting.contentCategories.insert",
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Inserts a new content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "list": {
          "id": "dfareporting.contentCategories.list",
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "delete": {
          "id": "dfareporting.contentCategories.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "description": "Deletes an existing content category."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "id": "dfareporting.contentCategories.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "delete": {
          "id": "dfareporting.creativeFields.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "description": "Deletes an existing creative field.",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "DELETE"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeFields.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/creativeFields"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "id": "dfareporting.creativeFields.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "description": "Gets one creative field by ID."
        },
        "update": {
          "id": "dfareporting.creativeFields.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Updates an existing creative field.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "insert": {
          "id": "dfareporting.creativeFields.insert",
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Inserts a new creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFields.list",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "studio/dynamicFeeds",
          "id": "dfareporting.dynamicFeeds.insert",
          "path": "studio/dynamicFeeds",
          "description": "Inserts a new dynamic feed.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "description": "Gets a dynamic feed by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicFeeds.get"
        },
        "retransform": {
          "httpMethod": "POST",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "id": "dfareporting.dynamicFeeds.retransform",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published)."
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "studio/dynamicFeeds",
          "path": "studio/dynamicFeeds",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicFeeds.update"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "description": "Gets the account's active ad summary by account ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountActiveAdSummaries.get"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "patch": {
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "PATCH"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "POST",
          "id": "dfareporting.creativeGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative group.",
          "path": "userprofiles/{+profileId}/creativeGroups"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "description": "Gets one creative group by ID.",
          "id": "dfareporting.creativeGroups.get"
        },
        "update": {
          "id": "dfareporting.creativeGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Updates an existing creative group.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "description": "Gets one video format by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.videoFormats.get"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "httpMethod": "GET",
          "id": "dfareporting.videoFormats.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Lists available video formats.",
          "path": "userprofiles/{+profileId}/videoFormats"
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "insert": {
          "id": "dfareporting.studioCreatives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new studio creative.",
          "path": "studio/creatives",
          "flatPath": "studio/creatives",
          "httpMethod": "POST"
        },
        "publish": {
          "id": "dfareporting.studioCreatives.publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creatives/{creativesId}/publish",
          "description": "Publish for a studio creative.",
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "httpMethod": "POST"
        },
        "get": {
          "id": "dfareporting.studioCreatives.get",
          "path": "studio/creatives/{+studioCreativeId}",
          "description": "Gets a studio creative by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "studio/creatives/{creativesId}"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Inserts a new remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "list": {
          "id": "dfareporting.remarketingLists.list",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list by ID.",
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "id": "dfareporting.remarketingLists.get",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Updates an existing remarketing list.",
          "id": "dfareporting.remarketingLists.update"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.patch"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "update": {
          "id": "dfareporting.billingProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles",
          "description": "Updates an existing billing profile.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "httpMethod": "GET",
          "description": "Gets one billing profile by ID.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "id": "dfareporting.billingProfiles.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "id": "dfareporting.mobileCarriers.list",
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "description": "Retrieves a list of mobile carriers.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers"
        },
        "get": {
          "id": "dfareporting.mobileCarriers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile carrier by ID.",
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "httpMethod": "GET"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "description": "Gets a list of all supported user role permission groups.",
          "id": "dfareporting.userRolePermissionGroups.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups"
        },
        "get": {
          "id": "dfareporting.userRolePermissionGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission group by ID.",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "httpMethod": "GET"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserLandingPages.get",
          "description": "Gets one landing page by ID.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.advertiserLandingPages.update",
          "description": "Updates an existing landing page.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "PUT"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Inserts a new landing page.",
          "id": "dfareporting.advertiserLandingPages.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Retrieves a list of landing pages.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.list"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "ads": {
      "methods": {
        "patch": {
          "id": "dfareporting.ads.patch",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "POST",
          "description": "Inserts a new ad.",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.insert"
        },
        "list": {
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.list",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "GET"
        },
        "get": {
          "id": "dfareporting.ads.get",
          "description": "Gets one ad by ID.",
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "PUT",
          "id": "dfareporting.ads.update",
          "description": "Updates an existing ad.",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.targetableRemarketingLists.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}"
        },
        "list": {
          "id": "dfareporting.targetableRemarketingLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "httpMethod": "GET"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "description": "Gets one operating system version by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystemVersions.get"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "id": "dfareporting.operatingSystemVersions.list",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "description": "Retrieves a list of operating system versions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertisers": {
      "methods": {
        "patch": {
          "id": "dfareporting.advertisers.patch",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PATCH"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/advertisers",
          "id": "dfareporting.advertisers.list"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Inserts a new advertiser.",
          "id": "dfareporting.advertisers.insert"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Updates an existing advertiser.",
          "id": "dfareporting.advertisers.update"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "description": "Gets one advertiser by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.get"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}",
          "id": "dfareporting.userProfiles.get",
          "path": "userprofiles/{profileId}",
          "description": "Gets one user profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.userProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves list of user profiles for a user.",
          "path": "userprofiles",
          "flatPath": "userprofiles",
          "httpMethod": "GET"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserGroups.list",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "POST",
          "id": "dfareporting.advertiserGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "update": {
          "id": "dfareporting.advertiserGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PUT"
        },
        "get": {
          "id": "dfareporting.advertiserGroups.get",
          "description": "Gets one advertiser group by ID.",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "httpMethod": "GET"
        },
        "delete": {
          "id": "dfareporting.advertiserGroups.delete",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "description": "Deletes an existing advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.patch"
        }
      }
    },
    "eventTags": {
      "methods": {
        "delete": {
          "id": "dfareporting.eventTags.delete",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "description": "Deletes an existing event tag.",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "PATCH",
          "id": "dfareporting.eventTags.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Updates an existing event tag.",
          "id": "dfareporting.eventTags.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "GET",
          "description": "Gets one event tag by ID.",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.get"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Retrieves a list of event tags, possibly filtered."
        },
        "insert": {
          "description": "Inserts a new event tag.",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.insert",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "POST"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration.",
          "id": "dfareporting.floodlightConfigurations.update"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "description": "Gets one floodlight configuration by ID.",
          "id": "dfareporting.floodlightConfigurations.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.list"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightConfigurations.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "httpMethod": "POST",
          "id": "dfareporting.creativeAssets.insert",
          "description": "Inserts a new creative asset.",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creatives": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Updates an existing creative. This method supports patch semantics."
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "description": "Gets one creative by ID.",
          "id": "dfareporting.creatives.get"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "PUT",
          "id": "dfareporting.creatives.update",
          "description": "Updates an existing creative.",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative.",
          "path": "userprofiles/{+profileId}/creatives",
          "id": "dfareporting.creatives.insert",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "POST"
        },
        "list": {
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.list",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "GET"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "id": "dfareporting.accountUserProfiles.patch",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.list",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "POST",
          "id": "dfareporting.accountUserProfiles.insert",
          "description": "Inserts a new account user profile.",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.update",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Updates an existing account user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.accountUserProfiles.get",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "description": "Gets one account user profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "POST",
          "id": "dfareporting.floodlightActivities.insert",
          "description": "Inserts a new floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "get": {
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "description": "Gets one floodlight activity by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}"
        },
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "description": "Generates a tag for a floodlight activity.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag"
        },
        "update": {
          "description": "Updates an existing floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.update",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "PUT"
        },
        "delete": {
          "id": "dfareporting.floodlightActivities.delete",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "description": "Deletes an existing floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.patch",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "description": "Lists files for a user profile.",
          "path": "userprofiles/{profileId}/files",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.list"
        },
        "get": {
          "supportsMediaDownload": true,
          "httpMethod": "GET",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "id": "dfareporting.files.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "reports/{reportId}/files/{fileId}",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download."
        }
      }
    },
    "placementGroups": {
      "methods": {
        "insert": {
          "description": "Inserts a new placement group.",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "POST"
        },
        "list": {
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "GET"
        },
        "get": {
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "description": "Gets one placement group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.placementGroups.update",
          "description": "Updates an existing placement group.",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "id": "dfareporting.placementGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Updates an existing placement group. This method supports patch semantics."
        }
      }
    },
    "placements": {
      "methods": {
        "patch": {
          "id": "dfareporting.placements.patch",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "PATCH"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.list",
          "path": "userprofiles/{+profileId}/placements",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "userprofiles/{+profileId}/placements",
          "description": "Inserts a new placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.update",
          "path": "userprofiles/{+profileId}/placements",
          "description": "Updates an existing placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "generatetags": {
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates tags for a placement.",
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "id": "dfareporting.placements.generatetags"
        },
        "get": {
          "id": "dfareporting.placements.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "description": "Gets one placement by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "POST",
          "id": "dfareporting.placementStrategies.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies"
        },
        "list": {
          "id": "dfareporting.placementStrategies.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement strategy by ID.",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "id": "dfareporting.placementStrategies.get",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Updates an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "patch": {
          "id": "dfareporting.placementStrategies.patch",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "PATCH"
        },
        "delete": {
          "id": "dfareporting.placementStrategies.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "description": "Deletes an existing placement strategy."
        }
      }
    },
    "sizes": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/sizes",
          "description": "Inserts a new size.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/sizes"
        },
        "list": {
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "path": "userprofiles/{+profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.list",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one size by ID.",
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "id": "dfareporting.sizes.get",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "httpMethod": "GET"
        }
      }
    },
    "sites": {
      "methods": {
        "patch": {
          "id": "dfareporting.sites.patch",
          "description": "Updates an existing site. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "PATCH"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "id": "dfareporting.sites.list"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "description": "Inserts a new site.",
          "id": "dfareporting.sites.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/sites"
        },
        "update": {
          "description": "Updates an existing site.",
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.update",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "PUT"
        },
        "get": {
          "id": "dfareporting.sites.get",
          "description": "Gets one site by ID.",
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "httpMethod": "GET"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "id": "dfareporting.userRolePermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission by ID.",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "httpMethod": "GET",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissions.list"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "patch": {
          "id": "dfareporting.targetingTemplates.patch",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PATCH"
        },
        "list": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        },
        "insert": {
          "id": "dfareporting.targetingTemplates.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new targeting template.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "POST"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Updates an existing targeting template.",
          "id": "dfareporting.targetingTemplates.update"
        },
        "get": {
          "id": "dfareporting.targetingTemplates.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "description": "Gets one targeting template by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "description": "Retrieves a list of billing assignments.",
          "id": "dfareporting.billingAssignments.list"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "id": "dfareporting.billingAssignments.insert"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "httpMethod": "POST",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.dimensionValues.query"
        }
      }
    },
    "userRoles": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PATCH",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.patch"
        },
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "description": "Deletes an existing user role.",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "DELETE"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/userRoles",
          "id": "dfareporting.userRoles.list",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "GET"
        },
        "insert": {
          "id": "dfareporting.userRoles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Inserts a new user role.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PUT",
          "id": "dfareporting.userRoles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing user role.",
          "path": "userprofiles/{+profileId}/userRoles"
        },
        "get": {
          "id": "dfareporting.userRoles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "description": "Gets one user role by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one TvCampaignDetail by ID.",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "id": "dfareporting.tvCampaignDetails.get",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "httpMethod": "GET"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingListShares.get",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing remarketing list share.",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "httpMethod": "PUT"
        },
        "patch": {
          "id": "dfareporting.remarketingListShares.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "id": "dfareporting.regions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/regions",
          "description": "Retrieves a list of regions."
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "id": "dfareporting.advertiserInvoices.list"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "httpMethod": "GET",
          "id": "dfareporting.metros.list",
          "description": "Retrieves a list of metros.",
          "path": "userprofiles/{+profileId}/metros",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "id": "dfareporting.postalCodes.list",
          "path": "userprofiles/{+profileId}/postalCodes",
          "description": "Retrieves a list of postal codes.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.postalCodes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one postal code by ID.",
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "httpMethod": "GET"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "description": "Retrieves a list of platform types.",
          "path": "userprofiles/{+profileId}/platformTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.list",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "httpMethod": "GET"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "httpMethod": "GET",
          "id": "dfareporting.platformTypes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one platform type by ID.",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystems.get",
          "description": "Gets one operating system by DART ID.",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of operating systems.",
          "path": "userprofiles/{+profileId}/operatingSystems",
          "id": "dfareporting.operatingSystems.list",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "httpMethod": "GET"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/accountPermissions",
          "description": "Retrieves the list of account permissions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "description": "Gets one account permission by ID.",
          "id": "dfareporting.accountPermissions.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}"
        }
      }
    },
    "campaigns": {
      "methods": {
        "list": {
          "id": "dfareporting.campaigns.list",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "GET"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Inserts a new campaign.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign.",
          "id": "dfareporting.campaigns.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        },
        "get": {
          "id": "dfareporting.campaigns.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "description": "Gets one campaign by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}"
        },
        "patch": {
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.patch",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PATCH"
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "studio/creativeAssets",
          "path": "studio/creativeAssets",
          "supportsMediaUpload": true,
          "description": "Inserts a new studio creative asset.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.studioCreativeAssets.insert"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "id": "dfareporting.changeLogs.get",
          "description": "Gets one change log by ID.",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "id": "dfareporting.changeLogs.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/changeLogs",
          "description": "Retrieves a list of change logs. This method supports paging."
        }
      }
    },
    "directorySites": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "GET",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.list"
        },
        "insert": {
          "id": "dfareporting.directorySites.insert",
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Inserts a new directory site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/directorySites"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one directory site by ID.",
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "id": "dfareporting.directorySites.get"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "id": "dfareporting.billingRates.list"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "patch": {
          "id": "dfareporting.subaccounts.patch",
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "GET",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.list"
        },
        "insert": {
          "id": "dfareporting.subaccounts.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Inserts a new subaccount.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "update": {
          "id": "dfareporting.subaccounts.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Updates an existing subaccount.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one subaccount by ID.",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}"
        }
      }
    },
    "countries": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of countries.",
          "path": "userprofiles/{+profileId}/countries",
          "id": "dfareporting.countries.list",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "httpMethod": "GET"
        },
        "get": {
          "id": "dfareporting.countries.get",
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "description": "Gets one country by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "id": "dfareporting.browsers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of browsers.",
          "path": "userprofiles/{+profileId}/browsers",
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "httpMethod": "GET"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "description": "Retrieves a list of connection types.",
          "path": "userprofiles/{+profileId}/connectionTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.list",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "httpMethod": "GET"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one connection type by ID.",
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "id": "dfareporting.connectionTypes.get"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchupdate": {
          "id": "dfareporting.conversions.batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "description": "Updates existing conversions.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate"
        },
        "batchinsert": {
          "id": "dfareporting.conversions.batchinsert",
          "description": "Inserts conversions.",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "PATCH"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity group by ID.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.get"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Inserts a new floodlight activity group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivityGroups.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "list": {
          "description": "Retrieves a list of dynamic targeting keys.",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.list",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "httpMethod": "GET"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "description": "Deletes an existing dynamic targeting key.",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.delete"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.insert"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/languages",
          "description": "Retrieves a list of languages.",
          "id": "dfareporting.languages.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/languages"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "description": "Gets one account permission group by ID.",
          "id": "dfareporting.accountPermissionGroups.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissionGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of account permission groups.",
          "path": "userprofiles/{+profileId}/accountPermissionGroups"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "id": "dfareporting.mobileApps.get",
          "description": "Gets one mobile app by ID.",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.mobileApps.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileApps",
          "description": "Retrieves list of available mobile apps.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps"
        }
      }
    },
    "accounts": {
      "methods": {
        "list": {
          "id": "dfareporting.accounts.list",
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Updates an existing account. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.patch"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "PUT",
          "description": "Updates an existing account.",
          "path": "userprofiles/{+profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.update"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "httpMethod": "GET",
          "description": "Gets one account by ID.",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.get"
        }
      }
    },
    "reports": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Updates a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.update",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT"
        },
        "get": {
          "description": "Retrieves a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.get",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "GET",
          "description": "Retrieves list of reports.",
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.list"
        },
        "insert": {
          "id": "dfareporting.reports.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Creates a report.",
          "path": "userprofiles/{profileId}/reports",
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "POST"
        },
        "run": {
          "id": "dfareporting.reports.run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Runs a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Deletes a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.reports.delete"
        }
      },
      "resources": {
        "files": {
          "methods": {
            "get": {
              "supportsMediaDownload": true,
              "httpMethod": "GET",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "id": "dfareporting.reports.files.get",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ]
            },
            "list": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "description": "Lists files for a report.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "id": "dfareporting.reports.files.list",
              "httpMethod": "GET",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files"
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST",
              "id": "dfareporting.reports.compatibleFields.query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ]
            }
          }
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "id": "dfareporting.tvCampaignSummaries.list",
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "description": "Retrieves a list of TV campaign summaries.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries"
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "publish": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "description": "Publish for a dynamic profile.",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicProfiles.publish"
        },
        "insert": {
          "description": "Inserts a new dynamic profile.",
          "path": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.insert",
          "flatPath": "studio/dynamicProfiles",
          "httpMethod": "POST"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles",
          "description": "Updates an existing dynamic profile.",
          "id": "dfareporting.dynamicProfiles.update",
          "httpMethod": "PUT",
          "flatPath": "studio/dynamicProfiles"
        },
        "generateCode": {
          "httpMethod": "GET",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "id": "dfareporting.dynamicProfiles.generateCode"
        },
        "get": {
          "id": "dfareporting.dynamicProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a dynamic profile by ID.",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "httpMethod": "GET"
        }
      }
    }
  },
  "canonicalName": "Dfareporting",
  "version": "v5",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "ownerName": "Google"
}