{
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v5/",
  "basePath": "/dfareporting/v5/",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "kind": "discovery#restDescription",
  "version": "v5",
  "discoveryVersion": "v1",
  "ownerDomain": "google.com",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://dfareporting.googleapis.com/",
  "ownerName": "Google",
  "revision": "20260310",
  "batchPath": "batch",
  "id": "dfareporting:v5",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        }
      }
    }
  },
  "protocol": "rest",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "servicePath": "dfareporting/v5/",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "canonicalName": "Dfareporting",
  "title": "Campaign Manager 360 API",
  "resources": {
    "studioCreatives": {
      "methods": {
        "insert": {
          "flatPath": "studio/creatives",
          "httpMethod": "POST",
          "description": "Inserts a new studio creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creatives",
          "id": "dfareporting.studioCreatives.insert"
        },
        "publish": {
          "flatPath": "studio/creatives/{creativesId}/publish",
          "httpMethod": "POST",
          "id": "dfareporting.studioCreatives.publish",
          "description": "Publish for a studio creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creatives/{+studioCreativeId}/publish"
        },
        "get": {
          "id": "dfareporting.studioCreatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creatives/{+studioCreativeId}",
          "description": "Gets a studio creative by ID.",
          "flatPath": "studio/creatives/{creativesId}",
          "httpMethod": "GET"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFieldValues.delete",
          "description": "Deletes an existing creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}"
        },
        "patch": {
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.patch"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "description": "Inserts a new creative field value.",
          "id": "dfareporting.creativeFieldValues.insert"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "description": "Gets one creative field value by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFieldValues.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFieldValues.list"
        },
        "update": {
          "id": "dfareporting.creativeFieldValues.update",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "description": "Updates an existing creative field value."
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "supportsMediaUpload": true,
          "id": "dfareporting.studioCreativeAssets.insert",
          "description": "Inserts a new studio creative asset.",
          "httpMethod": "POST",
          "flatPath": "studio/creativeAssets",
          "path": "studio/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "get": {
          "id": "dfareporting.accountUserProfiles.get",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account user profile by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}"
        },
        "list": {
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.list"
        },
        "update": {
          "id": "dfareporting.accountUserProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PUT",
          "description": "Updates an existing account user profile."
        },
        "patch": {
          "id": "dfareporting.accountUserProfiles.patch",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "description": "Inserts a new account user profile.",
          "id": "dfareporting.accountUserProfiles.insert"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "id": "dfareporting.accountPermissionGroups.get",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "description": "Gets one account permission group by ID."
        },
        "list": {
          "id": "dfareporting.accountPermissionGroups.list",
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "description": "Retrieves the list of account permission groups."
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "id": "dfareporting.billingProfiles.get",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one billing profile by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "httpMethod": "GET",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "id": "dfareporting.billingProfiles.list"
        },
        "update": {
          "id": "dfareporting.billingProfiles.update",
          "description": "Updates an existing billing profile.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.insert"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "httpMethod": "GET",
          "description": "Retrieves a list of billing assignments.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "id": "dfareporting.billingAssignments.list"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "id": "dfareporting.advertiserInvoices.list"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.get"
        },
        "update": {
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list share.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.update"
        },
        "patch": {
          "id": "dfareporting.remarketingListShares.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "httpMethod": "PATCH"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "description": "Gets one advertiser group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserGroups.get"
        },
        "list": {
          "id": "dfareporting.advertiserGroups.list",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging."
        },
        "update": {
          "id": "dfareporting.advertiserGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PUT"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.delete",
          "description": "Deletes an existing advertiser group.",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        },
        "patch": {
          "id": "dfareporting.advertiserGroups.patch",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.advertiserGroups.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Inserts a new advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "campaigns": {
      "methods": {
        "get": {
          "id": "dfareporting.campaigns.get",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "httpMethod": "GET",
          "description": "Gets one campaign by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+id}"
        },
        "list": {
          "id": "dfareporting.campaigns.list",
          "path": "userprofiles/{+profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PUT",
          "id": "dfareporting.campaigns.update"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PATCH",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "id": "dfareporting.campaigns.patch"
        },
        "insert": {
          "id": "dfareporting.campaigns.insert",
          "path": "userprofiles/{+profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Inserts a new campaign."
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "id": "dfareporting.tvCampaignSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "description": "Retrieves a list of TV campaign summaries.",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "httpMethod": "GET"
        }
      }
    },
    "creatives": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "id": "dfareporting.creatives.get"
        },
        "list": {
          "id": "dfareporting.creatives.list",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "PUT",
          "description": "Updates an existing creative.",
          "id": "dfareporting.creatives.update"
        },
        "insert": {
          "description": "Inserts a new creative.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.insert"
        },
        "patch": {
          "id": "dfareporting.creatives.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative. This method supports patch semantics."
        }
      }
    },
    "reports": {
      "resources": {
        "files": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "supportsMediaDownload": true,
              "id": "dfareporting.reports.files.get"
            },
            "list": {
              "id": "dfareporting.reports.files.list",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "httpMethod": "GET",
              "description": "Lists files for a report."
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "id": "dfareporting.reports.compatibleFields.query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "httpMethod": "POST",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        }
      },
      "methods": {
        "insert": {
          "description": "Creates a report.",
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports",
          "id": "dfareporting.reports.insert"
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.delete",
          "description": "Deletes a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "get": {
          "id": "dfareporting.reports.get",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Retrieves a report by its ID."
        },
        "list": {
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports",
          "description": "Retrieves list of reports.",
          "id": "dfareporting.reports.list"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "description": "Updates a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.update"
        },
        "run": {
          "description": "Runs a report.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.run"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}",
          "flatPath": "userprofiles/{profileId}",
          "httpMethod": "GET",
          "description": "Gets one user profile by ID.",
          "id": "dfareporting.userProfiles.get"
        },
        "list": {
          "path": "userprofiles",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves list of user profiles for a user.",
          "httpMethod": "GET",
          "flatPath": "userprofiles",
          "id": "dfareporting.userProfiles.list"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "flatPath": "reports/{reportId}/files/{fileId}",
          "httpMethod": "GET",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "reports/{reportId}/files/{fileId}",
          "id": "dfareporting.files.get",
          "supportsMediaDownload": true
        },
        "list": {
          "id": "dfareporting.files.list",
          "path": "userprofiles/{profileId}/files",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/files",
          "description": "Lists files for a user profile."
        }
      }
    },
    "creativeFields": {
      "methods": {
        "get": {
          "id": "dfareporting.creativeFields.get",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "description": "Gets one creative field by ID."
        },
        "list": {
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.list"
        },
        "update": {
          "id": "dfareporting.creativeFields.update",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "PUT",
          "description": "Updates an existing creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.delete",
          "description": "Deletes an existing creative field.",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "id": "dfareporting.creativeFields.patch"
        },
        "insert": {
          "id": "dfareporting.creativeFields.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Inserts a new creative field.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "id": "dfareporting.operatingSystemVersions.get",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "description": "Gets one operating system version by ID."
        },
        "list": {
          "id": "dfareporting.operatingSystemVersions.list",
          "description": "Retrieves a list of operating system versions.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystemVersions"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "description": "Retrieves a list of metros.",
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/metros",
          "id": "dfareporting.metros.list"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "id": "dfareporting.videoFormats.get",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one video format by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}"
        },
        "list": {
          "description": "Lists available video formats.",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/videoFormats",
          "id": "dfareporting.videoFormats.list"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "id": "dfareporting.accountPermissions.get",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "httpMethod": "GET",
          "description": "Gets one account permission by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}"
        },
        "list": {
          "id": "dfareporting.accountPermissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissions",
          "description": "Retrieves the list of account permissions.",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "httpMethod": "GET"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "id": "dfareporting.conversions.batchinsert",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "description": "Inserts conversions."
        },
        "batchupdate": {
          "id": "dfareporting.conversions.batchupdate",
          "description": "Updates existing conversions.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ]
        }
      }
    },
    "ads": {
      "methods": {
        "insert": {
          "id": "dfareporting.ads.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "description": "Inserts a new ad.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "POST"
        },
        "patch": {
          "id": "dfareporting.ads.patch",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        },
        "get": {
          "description": "Gets one ad by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.get"
        },
        "list": {
          "id": "dfareporting.ads.list",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads"
        },
        "update": {
          "description": "Updates an existing ad.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "id": "dfareporting.ads.update"
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "id": "dfareporting.countries.get",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "httpMethod": "GET",
          "description": "Gets one country by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/countries/{+dartId}"
        },
        "list": {
          "id": "dfareporting.countries.list",
          "description": "Retrieves a list of countries.",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/countries"
        }
      }
    },
    "userRoles": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "id": "dfareporting.userRoles.get"
        },
        "list": {
          "id": "dfareporting.userRoles.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.userRoles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PUT",
          "description": "Updates an existing user role."
        },
        "insert": {
          "id": "dfareporting.userRoles.insert",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "POST",
          "description": "Inserts a new user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles"
        },
        "patch": {
          "id": "dfareporting.userRoles.patch",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.userRoles.delete",
          "description": "Deletes an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles/{+id}"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission group by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "id": "dfareporting.userRolePermissionGroups.get"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "description": "Gets a list of all supported user role permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "id": "dfareporting.userRolePermissionGroups.list"
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "insert": {
          "id": "dfareporting.dynamicProfiles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles",
          "description": "Inserts a new dynamic profile.",
          "flatPath": "studio/dynamicProfiles",
          "httpMethod": "POST"
        },
        "get": {
          "id": "dfareporting.dynamicProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "httpMethod": "GET",
          "description": "Gets a dynamic profile by ID."
        },
        "update": {
          "path": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "studio/dynamicProfiles",
          "description": "Updates an existing dynamic profile.",
          "id": "dfareporting.dynamicProfiles.update"
        },
        "generateCode": {
          "id": "dfareporting.dynamicProfiles.generateCode",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "httpMethod": "GET",
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode"
        },
        "publish": {
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicProfiles.publish",
          "description": "Publish for a dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish"
        }
      }
    },
    "accounts": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "PATCH",
          "description": "Updates an existing account. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts",
          "id": "dfareporting.accounts.patch"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "description": "Gets one account by ID.",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.get"
        },
        "list": {
          "path": "userprofiles/{+profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.accounts.list"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Updates an existing account.",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "PUT",
          "id": "dfareporting.accounts.update"
        }
      }
    },
    "eventTags": {
      "methods": {
        "delete": {
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "id": "dfareporting.eventTags.delete",
          "description": "Deletes an existing event tag."
        },
        "patch": {
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "id": "dfareporting.eventTags.patch"
        },
        "insert": {
          "id": "dfareporting.eventTags.insert",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new event tag.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "get": {
          "id": "dfareporting.eventTags.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "description": "Gets one event tag by ID.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.eventTags.list",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "GET",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "update": {
          "id": "dfareporting.eventTags.update",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing event tag.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.insert"
        },
        "patch": {
          "id": "dfareporting.floodlightActivityGroups.patch",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "description": "Gets one floodlight activity group by ID.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.get"
        },
        "list": {
          "id": "dfareporting.floodlightActivityGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging."
        },
        "update": {
          "id": "dfareporting.floodlightActivityGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "PUT"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "patch": {
          "id": "dfareporting.targetingTemplates.patch",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new targeting template.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.insert"
        },
        "get": {
          "id": "dfareporting.targetingTemplates.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "httpMethod": "GET",
          "description": "Gets one targeting template by ID."
        },
        "list": {
          "id": "dfareporting.targetingTemplates.list",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PUT",
          "description": "Updates an existing targeting template.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.update"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Inserts a new creative group.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "POST",
          "id": "dfareporting.creativeGroups.insert"
        },
        "patch": {
          "id": "dfareporting.creativeGroups.patch",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "description": "Updates an existing creative group. This method supports patch semantics."
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "description": "Gets one creative group by ID.",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.get"
        },
        "list": {
          "id": "dfareporting.creativeGroups.list",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing creative group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.update"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "httpMethod": "GET",
          "description": "Retrieves a list of regions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/regions",
          "id": "dfareporting.regions.list"
        }
      }
    },
    "sizes": {
      "methods": {
        "insert": {
          "id": "dfareporting.sizes.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes",
          "description": "Inserts a new size.",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "POST"
        },
        "get": {
          "id": "dfareporting.sizes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "httpMethod": "GET",
          "description": "Gets one size by ID."
        },
        "list": {
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "path": "userprofiles/{+profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.list"
        }
      }
    },
    "sites": {
      "methods": {
        "patch": {
          "description": "Updates an existing site. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.patch"
        },
        "insert": {
          "id": "dfareporting.sites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "description": "Inserts a new site.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "POST"
        },
        "get": {
          "id": "dfareporting.sites.get",
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "description": "Gets one site by ID."
        },
        "list": {
          "id": "dfareporting.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.sites.update",
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Updates an existing site."
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds",
          "description": "Inserts a new dynamic feed.",
          "flatPath": "studio/dynamicFeeds",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicFeeds.insert"
        },
        "retransform": {
          "id": "dfareporting.dynamicFeeds.retransform",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published)."
        },
        "get": {
          "id": "dfareporting.dynamicFeeds.get",
          "httpMethod": "GET",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "description": "Gets a dynamic feed by ID.",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "flatPath": "studio/dynamicFeeds",
          "httpMethod": "PUT",
          "id": "dfareporting.dynamicFeeds.update"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightConfigurations.patch"
        },
        "get": {
          "id": "dfareporting.floodlightConfigurations.get",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "description": "Gets one floodlight configuration by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "id": "dfareporting.floodlightConfigurations.list"
        },
        "update": {
          "description": "Updates an existing floodlight configuration.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.update"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "list": {
          "id": "dfareporting.dynamicTargetingKeys.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "httpMethod": "GET",
          "description": "Retrieves a list of dynamic targeting keys."
        },
        "insert": {
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement."
        },
        "delete": {
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "description": "Deletes an existing dynamic targeting key.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "description": "Gets one TvCampaignDetail by ID.",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.tvCampaignDetails.get"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "id": "dfareporting.connectionTypes.get",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "httpMethod": "GET",
          "description": "Gets one connection type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/connectionTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "description": "Retrieves a list of connection types.",
          "id": "dfareporting.connectionTypes.list"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "description": "Inserts a new landing page.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.insert"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch"
        },
        "get": {
          "id": "dfareporting.advertiserLandingPages.get",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one landing page by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}"
        },
        "list": {
          "id": "dfareporting.advertiserLandingPages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "GET",
          "description": "Retrieves a list of landing pages."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "PUT",
          "id": "dfareporting.advertiserLandingPages.update"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "description": "Generates a tag for a floodlight activity.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "id": "dfareporting.floodlightActivities.get"
        },
        "list": {
          "id": "dfareporting.floodlightActivities.list",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "update": {
          "id": "dfareporting.floodlightActivities.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "PUT"
        },
        "insert": {
          "id": "dfareporting.floodlightActivities.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.floodlightActivities.delete",
          "description": "Deletes an existing floodlight activity."
        },
        "patch": {
          "id": "dfareporting.floodlightActivities.patch",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "id": "dfareporting.browsers.list",
          "description": "Retrieves a list of browsers.",
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/browsers"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "patch": {
          "id": "dfareporting.placementGroups.patch",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.placementGroups.insert",
          "description": "Inserts a new placement group.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.placementGroups.get",
          "description": "Gets one placement group by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.placementGroups.list",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "update": {
          "id": "dfareporting.placementGroups.update",
          "description": "Updates an existing placement group.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "id": "dfareporting.billingRates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "httpMethod": "GET",
          "description": "Retrieves a list of billing rates. This method supports paging."
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "id": "dfareporting.changeLogs.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "description": "Gets one change log by ID.",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of change logs. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/changeLogs",
          "id": "dfareporting.changeLogs.list"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "get": {
          "description": "Gets one remarketing list by ID.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "id": "dfareporting.remarketingLists.get"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.list"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list.",
          "id": "dfareporting.remarketingLists.update"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.patch"
        },
        "insert": {
          "id": "dfareporting.remarketingLists.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "POST",
          "description": "Inserts a new remarketing list."
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "id": "dfareporting.platformTypes.get",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "httpMethod": "GET",
          "description": "Gets one platform type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/platformTypes/{+id}"
        },
        "list": {
          "description": "Retrieves a list of platform types.",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "id": "dfareporting.cities.list",
          "path": "userprofiles/{+profileId}/cities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "description": "Retrieves a list of cities, possibly filtered."
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "description": "Retrieves a list of languages.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "path": "userprofiles/{+profileId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.languages.list"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "id": "dfareporting.targetableRemarketingLists.get",
          "description": "Gets one remarketing list by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.targetableRemarketingLists.list"
        }
      }
    },
    "advertisers": {
      "methods": {
        "insert": {
          "id": "dfareporting.advertisers.insert",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "patch": {
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "id": "dfareporting.advertisers.patch"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "httpMethod": "GET",
          "description": "Gets one advertiser by ID.",
          "id": "dfareporting.advertisers.get"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "id": "dfareporting.advertisers.list"
        },
        "update": {
          "id": "dfareporting.advertisers.update",
          "description": "Updates an existing advertiser.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "description": "Gets one mobile carrier by ID.",
          "id": "dfareporting.mobileCarriers.get"
        },
        "list": {
          "description": "Retrieves a list of mobile carriers.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileCarriers.list"
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "description": "Gets one directory site by ID.",
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.get"
        },
        "list": {
          "id": "dfareporting.directorySites.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Inserts a new directory site.",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "POST",
          "id": "dfareporting.directorySites.insert"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "insert": {
          "description": "Inserts a new subaccount.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.insert"
        },
        "patch": {
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.patch"
        },
        "get": {
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "description": "Gets one subaccount by ID.",
          "id": "dfareporting.subaccounts.get"
        },
        "list": {
          "id": "dfareporting.subaccounts.list",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "update": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "description": "Updates an existing subaccount.",
          "id": "dfareporting.subaccounts.update"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative asset.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "supportsMediaUpload": true,
          "id": "dfareporting.creativeAssets.insert"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "description": "Gets one user role permission by ID.",
          "id": "dfareporting.userRolePermissions.get"
        },
        "list": {
          "description": "Gets a list of user role permissions, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "id": "dfareporting.mobileApps.get",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "description": "Gets one mobile app by ID."
        },
        "list": {
          "description": "Retrieves list of available mobile apps.",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileApps",
          "id": "dfareporting.mobileApps.list"
        }
      }
    },
    "placements": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.patch"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "description": "Inserts a new placement.",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "POST",
          "id": "dfareporting.placements.insert"
        },
        "get": {
          "id": "dfareporting.placements.get",
          "description": "Gets one placement by ID.",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/{+id}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "id": "dfareporting.placements.list"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "PUT",
          "description": "Updates an existing placement.",
          "id": "dfareporting.placements.update"
        },
        "generatetags": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "description": "Generates tags for a placement.",
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "httpMethod": "POST",
          "id": "dfareporting.placements.generatetags"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "id": "dfareporting.postalCodes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "description": "Gets one postal code by ID.",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.postalCodes.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "description": "Retrieves a list of postal codes.",
          "path": "userprofiles/{+profileId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "description": "Gets one placement strategy by ID.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "GET",
          "id": "dfareporting.placementStrategies.get"
        },
        "list": {
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.list"
        },
        "update": {
          "description": "Updates an existing placement strategy.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.update"
        },
        "patch": {
          "id": "dfareporting.placementStrategies.patch",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics."
        },
        "delete": {
          "id": "dfareporting.placementStrategies.delete",
          "description": "Deletes an existing placement strategy.",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.placementStrategies.insert",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement strategy.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "description": "Gets one operating system by DART ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystems",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "httpMethod": "GET",
          "description": "Retrieves a list of operating systems.",
          "id": "dfareporting.operatingSystems.list"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaignCreativeAssociations.insert"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "httpMethod": "GET",
          "id": "dfareporting.campaignCreativeAssociations.list"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "description": "Gets the account's active ad summary by account ID.",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "httpMethod": "GET",
          "id": "dfareporting.accountActiveAdSummaries.get"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "description": "Gets one content category by ID.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "GET",
          "id": "dfareporting.contentCategories.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "GET",
          "id": "dfareporting.contentCategories.list"
        },
        "update": {
          "id": "dfareporting.contentCategories.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "description": "Updates an existing content category.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "POST",
          "description": "Inserts a new content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "id": "dfareporting.contentCategories.insert"
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "id": "dfareporting.contentCategories.delete",
          "description": "Deletes an existing content category.",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.contentCategories.patch",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "path": "userprofiles/{+profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves list of report dimension values for a list of filters.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "id": "dfareporting.dimensionValues.query"
        }
      }
    }
  },
  "name": "dfareporting"
}