{
  "ownerName": "Google",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "version": "v4",
  "ownerDomain": "google.com",
  "title": "Campaign Manager 360 API",
  "revision": "20260310",
  "canonicalName": "Dfareporting",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "name": "dfareporting",
  "resources": {
    "files": {
      "methods": {
        "get": {
          "path": "reports/{reportId}/files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "httpMethod": "GET",
          "id": "dfareporting.files.get",
          "supportsMediaDownload": true
        },
        "list": {
          "path": "userprofiles/{profileId}/files",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Lists files for a user profile.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/files",
          "id": "dfareporting.files.list"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissions.get",
          "description": "Gets one user role permission by ID.",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "id": "dfareporting.userRolePermissions.list",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "httpMethod": "GET"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "description": "Gets one remarketing list by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "id": "dfareporting.targetableRemarketingLists.get",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "id": "dfareporting.targetableRemarketingLists.list"
        }
      }
    },
    "userRoles": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles",
          "id": "dfareporting.userRoles.insert",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "POST",
          "description": "Inserts a new user role."
        },
        "update": {
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.update",
          "description": "Updates an existing user role."
        },
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "description": "Deletes an existing user role."
        },
        "list": {
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.list",
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.patch",
          "description": "Updates an existing user role. This method supports patch semantics."
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "id": "dfareporting.userRoles.get",
          "description": "Gets one user role by ID.",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "description": "Gets one directory site by ID.",
          "id": "dfareporting.directorySites.get",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites/{+id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "id": "dfareporting.directorySites.list",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites",
          "id": "dfareporting.directorySites.insert",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "POST",
          "description": "Inserts a new directory site."
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing dynamic targeting key."
        },
        "insert": {
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.insert"
        },
        "list": {
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "description": "Retrieves a list of dynamic targeting keys."
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "supportsMediaUpload": true,
          "id": "dfareporting.creativeAssets.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "description": "Inserts a new creative asset."
        }
      }
    },
    "creativeFields": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "id": "dfareporting.creativeFields.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "description": "Gets one creative field by ID."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "id": "dfareporting.creativeFields.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Updates an existing creative field. This method supports patch semantics."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFields.list",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.delete",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field."
        },
        "insert": {
          "description": "Inserts a new creative field.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "id": "dfareporting.creativeFields.insert",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Updates an existing creative field.",
          "id": "dfareporting.creativeFields.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        }
      }
    },
    "creatives": {
      "methods": {
        "list": {
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "GET",
          "id": "dfareporting.creatives.list",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "httpMethod": "GET",
          "id": "dfareporting.creatives.get"
        },
        "patch": {
          "description": "Updates an existing creative. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.patch",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "POST",
          "id": "dfareporting.creatives.insert",
          "description": "Inserts a new creative."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "id": "dfareporting.creatives.update",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "PUT",
          "description": "Updates an existing creative."
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "description": "Retrieves a list of metros.",
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "httpMethod": "GET",
          "id": "dfareporting.metros.list",
          "path": "userprofiles/{+profileId}/metros",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "list": {
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "httpMethod": "GET",
          "id": "dfareporting.billingProfiles.list",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing billing profile.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "httpMethod": "PUT",
          "id": "dfareporting.billingProfiles.update",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "id": "dfareporting.billingProfiles.get",
          "description": "Gets one billing profile by ID.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "id": "dfareporting.languages.list",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "httpMethod": "GET",
          "description": "Retrieves a list of languages.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/languages"
        }
      }
    },
    "placements": {
      "methods": {
        "insert": {
          "description": "Inserts a new placement.",
          "id": "dfareporting.placements.insert",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "description": "Updates an existing placement.",
          "id": "dfareporting.placements.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "generatetags": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "description": "Generates tags for a placement.",
          "id": "dfareporting.placements.generatetags",
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "httpMethod": "POST"
        },
        "list": {
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "id": "dfareporting.placements.list",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements"
        },
        "patch": {
          "id": "dfareporting.placements.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "id": "dfareporting.placements.get",
          "description": "Gets one placement by ID.",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile carrier by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "id": "dfareporting.mobileCarriers.get"
        },
        "list": {
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of mobile carriers.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "id": "dfareporting.mobileCarriers.list"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "id": "dfareporting.accountPermissions.get",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "httpMethod": "GET",
          "description": "Gets one account permission by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissions",
          "id": "dfareporting.accountPermissions.list",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "httpMethod": "GET",
          "description": "Retrieves the list of account permissions."
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "description": "Retrieves list of report dimension values for a list of filters.",
          "id": "dfareporting.dimensionValues.query",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "id": "dfareporting.billingAssignments.list",
          "description": "Retrieves a list of billing assignments.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "id": "dfareporting.billingAssignments.insert",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "httpMethod": "POST"
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "get": {
          "description": "Gets a dynamic profile by ID.",
          "id": "dfareporting.dynamicProfiles.get",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}"
        },
        "publish": {
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.publish",
          "description": "Publish for a dynamic profile."
        },
        "generateCode": {
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "httpMethod": "GET",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "id": "dfareporting.dynamicProfiles.generateCode",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "studio/dynamicProfiles",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicProfiles.insert",
          "description": "Inserts a new dynamic profile.",
          "path": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicProfiles",
          "httpMethod": "PUT",
          "id": "dfareporting.dynamicProfiles.update",
          "description": "Updates an existing dynamic profile."
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of TV campaign summaries.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "id": "dfareporting.tvCampaignSummaries.list"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "delete": {
          "description": "Deletes an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.delete",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "DELETE"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Inserts a new placement strategy.",
          "id": "dfareporting.placementStrategies.insert",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "POST"
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "id": "dfareporting.placementStrategies.update",
          "description": "Updates an existing placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.patch",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement strategy. This method supports patch semantics."
        },
        "get": {
          "id": "dfareporting.placementStrategies.get",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "GET",
          "description": "Gets one placement strategy by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "id": "dfareporting.placementStrategies.list",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging."
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "description": "Gets one mobile app by ID.",
          "id": "dfareporting.mobileApps.get",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileApps/{+id}"
        },
        "list": {
          "description": "Retrieves list of available mobile apps.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "id": "dfareporting.mobileApps.list",
          "path": "userprofiles/{+profileId}/mobileApps",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}",
          "description": "Gets one user profile by ID.",
          "id": "dfareporting.userProfiles.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}"
        },
        "list": {
          "path": "userprofiles",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves list of user profiles for a user.",
          "flatPath": "userprofiles",
          "httpMethod": "GET",
          "id": "dfareporting.userProfiles.list"
        }
      }
    },
    "accounts": {
      "methods": {
        "update": {
          "description": "Updates an existing account.",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "PUT",
          "id": "dfareporting.accounts.update",
          "path": "userprofiles/{+profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "id": "dfareporting.accounts.list",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "description": "Gets one account by ID.",
          "id": "dfareporting.accounts.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "PATCH",
          "id": "dfareporting.accounts.patch"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "update": {
          "description": "Updates an existing remarketing list share.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.update",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.remarketingListShares.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares"
        },
        "get": {
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list share by remarketing list ID.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingListShares.get"
        }
      }
    },
    "projects": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/projects/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one project by ID.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectsId}",
          "httpMethod": "GET",
          "id": "dfareporting.projects.get"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/projects",
          "httpMethod": "GET",
          "id": "dfareporting.projects.list",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "path": "userprofiles/{+profileId}/projects",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight activity by ID.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivities.get"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivities.patch"
        },
        "list": {
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivities.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities"
        },
        "generatetag": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "description": "Generates a tag for a floodlight activity.",
          "id": "dfareporting.floodlightActivities.generatetag",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "httpMethod": "POST"
        },
        "delete": {
          "id": "dfareporting.floodlightActivities.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "description": "Deletes an existing floodlight activity."
        },
        "insert": {
          "id": "dfareporting.floodlightActivities.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "description": "Inserts a new floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities"
        },
        "update": {
          "id": "dfareporting.floodlightActivities.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "description": "Updates an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "httpMethod": "GET",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "get": {
          "id": "dfareporting.floodlightConfigurations.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "httpMethod": "GET",
          "description": "Gets one floodlight configuration by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics."
        },
        "update": {
          "description": "Updates an existing floodlight configuration.",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.update",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "id": "dfareporting.floodlightConfigurations.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "GET"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "id": "dfareporting.contentCategories.list"
        },
        "get": {
          "description": "Gets one content category by ID.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "GET",
          "id": "dfareporting.contentCategories.get",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "id": "dfareporting.contentCategories.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "description": "Updates an existing content category. This method supports patch semantics."
        },
        "delete": {
          "description": "Deletes an existing content category.",
          "id": "dfareporting.contentCategories.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}"
        },
        "insert": {
          "description": "Inserts a new content category.",
          "id": "dfareporting.contentCategories.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories"
        },
        "update": {
          "id": "dfareporting.contentCategories.update",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "PUT",
          "description": "Updates an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "httpMethod": "GET",
          "id": "dfareporting.platformTypes.get",
          "description": "Gets one platform type by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "description": "Retrieves a list of platform types."
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "id": "dfareporting.billingRates.list",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "description": "Gets one user role permission group by ID.",
          "id": "dfareporting.userRolePermissionGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "id": "dfareporting.userRolePermissionGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "description": "Gets a list of all supported user role permission groups."
        }
      }
    },
    "advertisers": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "id": "dfareporting.advertisers.get",
          "description": "Gets one advertiser by ID.",
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "id": "dfareporting.advertisers.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/advertisers"
        },
        "list": {
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "id": "dfareporting.advertisers.list",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "id": "dfareporting.advertisers.insert",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "id": "dfareporting.advertisers.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "description": "Updates an existing advertiser."
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "httpMethod": "GET",
          "id": "dfareporting.postalCodes.get",
          "description": "Gets one postal code by ID."
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "id": "dfareporting.postalCodes.list",
          "description": "Retrieves a list of postal codes.",
          "path": "userprofiles/{+profileId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "description": "Inserts a new account user profile."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "description": "Updates an existing account user profile."
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "httpMethod": "GET",
          "id": "dfareporting.accountUserProfiles.get",
          "description": "Gets one account user profile by ID.",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "id": "dfareporting.accountUserProfiles.patch"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "id": "dfareporting.accountUserProfiles.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "description": "Gets one size by ID.",
          "id": "dfareporting.sizes.get",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes/{+id}"
        },
        "list": {
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "GET",
          "id": "dfareporting.sizes.list",
          "path": "userprofiles/{+profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes",
          "id": "dfareporting.sizes.insert",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "POST",
          "description": "Inserts a new size."
        }
      }
    },
    "subaccounts": {
      "methods": {
        "insert": {
          "description": "Inserts a new subaccount.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "id": "dfareporting.subaccounts.insert",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.subaccounts.update",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "PUT",
          "description": "Updates an existing subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "id": "dfareporting.subaccounts.patch",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "PATCH",
          "description": "Updates an existing subaccount. This method supports patch semantics."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "id": "dfareporting.subaccounts.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "description": "Gets one subaccount by ID."
        },
        "list": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.list",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging."
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "id": "dfareporting.advertiserGroups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing advertiser group."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "POST",
          "id": "dfareporting.advertiserGroups.insert",
          "description": "Inserts a new advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser group."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserGroups.list",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one advertiser group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserGroups.get",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "id": "dfareporting.advertiserGroups.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "id": "dfareporting.advertiserInvoices.list"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "id": "dfareporting.placementGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "POST",
          "description": "Inserts a new placement group."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Updates an existing placement group.",
          "id": "dfareporting.placementGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "PUT"
        },
        "list": {
          "id": "dfareporting.placementGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "patch": {
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "id": "dfareporting.placementGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "get": {
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement group by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "id": "dfareporting.placementGroups.get"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.delete",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field value."
        },
        "insert": {
          "description": "Inserts a new creative field value.",
          "id": "dfareporting.creativeFieldValues.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFieldValues.update",
          "description": "Updates an existing creative field value.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "id": "dfareporting.creativeFieldValues.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "httpMethod": "GET",
          "description": "Gets one creative field value by ID."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "description": "Updates an existing creative field value. This method supports patch semantics."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeFieldValues.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "list": {
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "id": "dfareporting.targetingTemplates.list",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PATCH",
          "id": "dfareporting.targetingTemplates.patch",
          "description": "Updates an existing targeting template. This method supports patch semantics."
        },
        "get": {
          "description": "Gets one targeting template by ID.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "httpMethod": "GET",
          "id": "dfareporting.targetingTemplates.get",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new targeting template.",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.insert",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing targeting template.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PUT",
          "id": "dfareporting.targetingTemplates.update"
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "get": {
          "description": "Gets one inventory item by ID.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems/{inventoryItemsId}",
          "httpMethod": "GET",
          "id": "dfareporting.inventoryItems.get",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems",
          "httpMethod": "GET",
          "id": "dfareporting.inventoryItems.list",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "orders": {
      "methods": {
        "get": {
          "id": "dfareporting.orders.get",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders/{ordersId}",
          "httpMethod": "GET",
          "description": "Gets one order by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders/{+id}"
        },
        "list": {
          "id": "dfareporting.orders.list",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders",
          "httpMethod": "GET",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "description": "Gets one account permission group by ID.",
          "id": "dfareporting.accountPermissionGroups.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}"
        },
        "list": {
          "description": "Retrieves the list of account permission groups.",
          "id": "dfareporting.accountPermissionGroups.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissionGroups"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "get": {
          "description": "Gets one creative group by ID.",
          "id": "dfareporting.creativeGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeGroups.patch",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "POST",
          "description": "Inserts a new creative group."
        },
        "update": {
          "description": "Updates an existing creative group.",
          "id": "dfareporting.creativeGroups.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "list": {
          "description": "Retrieves a list of landing pages.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserLandingPages.list",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one landing page by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "id": "dfareporting.advertiserLandingPages.get",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "description": "Updates an existing landing page. This method supports patch semantics."
        },
        "insert": {
          "description": "Inserts a new landing page.",
          "id": "dfareporting.advertiserLandingPages.insert",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "update": {
          "description": "Updates an existing landing page.",
          "id": "dfareporting.advertiserLandingPages.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "description": "Gets one TvCampaignDetail by ID.",
          "id": "dfareporting.tvCampaignDetails.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "description": "Retrieves a list of browsers.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "id": "dfareporting.browsers.list",
          "path": "userprofiles/{+profileId}/browsers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "description": "Gets the account's active ad summary by account ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "id": "dfareporting.dynamicFeeds.get",
          "httpMethod": "GET",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "description": "Gets a dynamic feed by ID."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds",
          "description": "Inserts a new dynamic feed.",
          "id": "dfareporting.dynamicFeeds.insert",
          "flatPath": "studio/dynamicFeeds",
          "httpMethod": "POST"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds",
          "id": "dfareporting.dynamicFeeds.update",
          "flatPath": "studio/dynamicFeeds",
          "httpMethod": "PUT",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored."
        },
        "retransform": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "id": "dfareporting.dynamicFeeds.retransform",
          "httpMethod": "POST",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "id": "dfareporting.conversions.batchinsert",
          "description": "Inserts conversions.",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ]
        },
        "batchupdate": {
          "id": "dfareporting.conversions.batchupdate",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "description": "Updates existing conversions.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchupdate"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system by DART ID.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystems.get"
        },
        "list": {
          "description": "Retrieves a list of operating systems.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystems.list",
          "path": "userprofiles/{+profileId}/operatingSystems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "patch": {
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.patch",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.remarketingLists.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}"
        },
        "list": {
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.remarketingLists.list",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Inserts a new remarketing list.",
          "id": "dfareporting.remarketingLists.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "update": {
          "id": "dfareporting.remarketingLists.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "description": "Retrieves a list of regions.",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "httpMethod": "GET",
          "id": "dfareporting.regions.list",
          "path": "userprofiles/{+profileId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "id": "dfareporting.connectionTypes.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "description": "Gets one connection type by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/connectionTypes",
          "description": "Retrieves a list of connection types.",
          "id": "dfareporting.connectionTypes.list",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "httpMethod": "GET"
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "description": "Inserts a new studio creative asset.",
          "id": "dfareporting.studioCreativeAssets.insert",
          "httpMethod": "POST",
          "flatPath": "studio/creativeAssets",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creativeAssets"
        }
      }
    },
    "reports": {
      "methods": {
        "list": {
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "GET",
          "id": "dfareporting.reports.list",
          "description": "Retrieves list of reports."
        },
        "get": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves a report by its ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.get"
        },
        "patch": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Updates an existing report. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PATCH",
          "id": "dfareporting.reports.patch"
        },
        "delete": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.delete",
          "description": "Deletes a report by its ID."
        },
        "insert": {
          "description": "Creates a report.",
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "POST",
          "id": "dfareporting.reports.insert",
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "run": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "id": "dfareporting.reports.run",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "description": "Runs a report."
        },
        "update": {
          "id": "dfareporting.reports.update",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "description": "Updates a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}"
        }
      },
      "resources": {
        "files": {
          "methods": {
            "get": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "GET",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "id": "dfareporting.reports.files.get",
              "supportsMediaDownload": true,
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download."
            },
            "list": {
              "id": "dfareporting.reports.files.list",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "httpMethod": "GET",
              "description": "Lists files for a report.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files"
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "httpMethod": "POST",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "id": "dfareporting.reports.compatibleFields.query"
            }
          }
        }
      }
    },
    "eventTags": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of event tags, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "GET",
          "id": "dfareporting.eventTags.list"
        },
        "get": {
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one event tag by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "id": "dfareporting.eventTags.get"
        },
        "patch": {
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "id": "dfareporting.eventTags.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "id": "dfareporting.eventTags.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing event tag."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Inserts a new event tag.",
          "id": "dfareporting.eventTags.insert",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "POST"
        },
        "update": {
          "id": "dfareporting.eventTags.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Updates an existing event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system version by ID.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystemVersions.get"
        },
        "list": {
          "id": "dfareporting.operatingSystemVersions.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "description": "Retrieves a list of operating system versions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystemVersions"
        }
      }
    },
    "ads": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "POST",
          "id": "dfareporting.ads.insert",
          "description": "Inserts a new ad.",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing ad.",
          "id": "dfareporting.ads.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads"
        },
        "get": {
          "description": "Gets one ad by ID.",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "httpMethod": "GET",
          "id": "dfareporting.ads.get",
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.ads.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "GET",
          "id": "dfareporting.ads.list",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "studio/creatives",
          "id": "dfareporting.studioCreatives.insert",
          "description": "Inserts a new studio creative.",
          "path": "studio/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "publish": {
          "httpMethod": "POST",
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "flatPath": "studio/creatives/{creativesId}/publish",
          "id": "dfareporting.studioCreatives.publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Publish for a studio creative."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creatives/{+studioCreativeId}",
          "description": "Gets a studio creative by ID.",
          "id": "dfareporting.studioCreatives.get",
          "httpMethod": "GET",
          "flatPath": "studio/creatives/{creativesId}"
        }
      }
    },
    "sites": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new site.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "POST",
          "id": "dfareporting.sites.insert"
        },
        "update": {
          "id": "dfareporting.sites.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Updates an existing site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "description": "Updates an existing site. This method supports patch semantics.",
          "id": "dfareporting.sites.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/sites"
        },
        "get": {
          "description": "Gets one site by ID.",
          "id": "dfareporting.sites.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites/{+id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.list",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging."
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "description": "Gets one change log by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "id": "dfareporting.changeLogs.get",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "id": "dfareporting.changeLogs.list",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "path": "userprofiles/{+profileId}/changeLogs",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity group."
        },
        "update": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity group.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.floodlightActivityGroups.update"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivityGroups.list",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.floodlightActivityGroups.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "description": "Gets one floodlight activity group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "campaigns": {
      "methods": {
        "get": {
          "description": "Gets one campaign by ID.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "id": "dfareporting.campaigns.get",
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "id": "dfareporting.campaigns.patch",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PATCH"
        },
        "list": {
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "id": "dfareporting.campaigns.list",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "id": "dfareporting.campaigns.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Inserts a new campaign."
        },
        "update": {
          "path": "userprofiles/{+profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing campaign.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PUT",
          "id": "dfareporting.campaigns.update"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/cities",
          "description": "Retrieves a list of cities, possibly filtered.",
          "id": "dfareporting.cities.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/cities"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "id": "dfareporting.videoFormats.get",
          "description": "Gets one video format by ID.",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/videoFormats",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Lists available video formats.",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "id": "dfareporting.videoFormats.list"
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "httpMethod": "GET",
          "id": "dfareporting.countries.get",
          "description": "Gets one country by ID.",
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.countries.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "description": "Retrieves a list of countries.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/countries"
        }
      }
    }
  },
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "basePath": "/dfareporting/v4/",
  "id": "dfareporting:v4",
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "servicePath": "dfareporting/v4/",
  "fullyEncodeReservedExpansion": true,
  "protocol": "rest"
}