{
  "ownerDomain": "google.com",
  "discoveryVersion": "v1",
  "name": "dfareporting",
  "id": "dfareporting:v5",
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://dfareporting.googleapis.com/",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "basePath": "/dfareporting/v5/",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "canonicalName": "Dfareporting",
  "resources": {
    "creativeAssets": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.creativeAssets.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "supportsMediaUpload": true,
          "description": "Inserts a new creative asset."
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "id": "dfareporting.tvCampaignDetails.get",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "description": "Gets one TvCampaignDetail by ID."
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "generateCode": {
          "httpMethod": "GET",
          "id": "dfareporting.dynamicProfiles.generateCode",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates code for a dynamic profile, which will need unescaping."
        },
        "get": {
          "description": "Gets a dynamic profile by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.dynamicProfiles.get",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.dynamicProfiles.insert",
          "flatPath": "studio/dynamicProfiles",
          "path": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new dynamic profile."
        },
        "update": {
          "path": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.dynamicProfiles.update",
          "flatPath": "studio/dynamicProfiles",
          "description": "Updates an existing dynamic profile."
        },
        "publish": {
          "httpMethod": "POST",
          "id": "dfareporting.dynamicProfiles.publish",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "description": "Publish for a dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "generatetag": {
          "description": "Generates a tag for a floodlight activity.",
          "id": "dfareporting.floodlightActivities.generatetag",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag"
        },
        "get": {
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivities.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "description": "Gets one floodlight activity by ID."
        },
        "patch": {
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivities.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "id": "dfareporting.floodlightActivities.delete",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "description": "Deletes an existing floodlight activity."
        },
        "insert": {
          "id": "dfareporting.floodlightActivities.insert",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Inserts a new floodlight activity."
        },
        "list": {
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivities.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing floodlight activity.",
          "httpMethod": "PUT",
          "id": "dfareporting.floodlightActivities.update",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "id": "dfareporting.targetableRemarketingLists.get",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.targetableRemarketingLists.list",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.creativeGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative group by ID."
        },
        "patch": {
          "id": "dfareporting.creativeGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Updates an existing creative group. This method supports patch semantics."
        },
        "insert": {
          "description": "Inserts a new creative group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.creativeGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging."
        },
        "update": {
          "description": "Updates an existing creative group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "PUT"
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "supportsMediaUpload": true,
          "description": "Inserts a new studio creative asset.",
          "httpMethod": "POST",
          "id": "dfareporting.studioCreativeAssets.insert",
          "flatPath": "studio/creativeAssets",
          "path": "studio/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertisers": {
      "methods": {
        "insert": {
          "description": "Inserts a new advertiser.",
          "id": "dfareporting.advertisers.insert",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "list": {
          "id": "dfareporting.advertisers.list",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging."
        },
        "update": {
          "description": "Updates an existing advertiser.",
          "id": "dfareporting.advertisers.update",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "get": {
          "description": "Gets one advertiser by ID.",
          "id": "dfareporting.advertisers.get",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers/{+id}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "id": "dfareporting.advertisers.patch",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. This method supports patch semantics."
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.connectionTypes.list",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "path": "userprofiles/{+profileId}/connectionTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of connection types."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "id": "dfareporting.connectionTypes.get",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "httpMethod": "GET",
          "description": "Gets one connection type by ID."
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "retransform": {
          "id": "dfareporting.dynamicFeeds.retransform",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published)."
        },
        "insert": {
          "description": "Inserts a new dynamic feed.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds",
          "id": "dfareporting.dynamicFeeds.insert",
          "flatPath": "studio/dynamicFeeds",
          "httpMethod": "POST"
        },
        "update": {
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "id": "dfareporting.dynamicFeeds.update",
          "flatPath": "studio/dynamicFeeds",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds"
        },
        "get": {
          "description": "Gets a dynamic feed by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "id": "dfareporting.dynamicFeeds.get",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "httpMethod": "GET"
        }
      }
    },
    "eventTags": {
      "methods": {
        "insert": {
          "id": "dfareporting.eventTags.insert",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Inserts a new event tag."
        },
        "list": {
          "description": "Retrieves a list of event tags, possibly filtered.",
          "httpMethod": "GET",
          "id": "dfareporting.eventTags.list",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.eventTags.update",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Updates an existing event tag."
        },
        "get": {
          "description": "Gets one event tag by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.eventTags.get",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.eventTags.patch",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Updates an existing event tag. This method supports patch semantics."
        },
        "delete": {
          "id": "dfareporting.eventTags.delete",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "description": "Deletes an existing event tag."
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystemVersions.get",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system version by ID."
        },
        "list": {
          "description": "Retrieves a list of operating system versions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "id": "dfareporting.operatingSystemVersions.list",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "httpMethod": "GET"
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "description": "Gets one country by ID.",
          "id": "dfareporting.countries.get",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/countries/{+dartId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/countries",
          "id": "dfareporting.countries.list",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "httpMethod": "GET",
          "description": "Retrieves a list of countries."
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.patch",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PATCH",
          "description": "Updates an existing targeting template. This method supports patch semantics."
        },
        "get": {
          "description": "Gets one targeting template by ID.",
          "id": "dfareporting.targetingTemplates.get",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.targetingTemplates.insert",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "description": "Inserts a new targeting template."
        },
        "list": {
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.list",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing targeting template.",
          "httpMethod": "PUT",
          "id": "dfareporting.targetingTemplates.update",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "directorySites": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites",
          "id": "dfareporting.directorySites.insert",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "POST",
          "description": "Inserts a new directory site."
        },
        "list": {
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "id": "dfareporting.directorySites.list",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites"
        },
        "get": {
          "description": "Gets one directory site by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "id": "dfareporting.directorySites.get",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "httpMethod": "GET"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserInvoices.list",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level."
        }
      }
    },
    "reports": {
      "methods": {
        "insert": {
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.reports.insert",
          "flatPath": "userprofiles/{profileId}/reports",
          "description": "Creates a report."
        },
        "list": {
          "id": "dfareporting.reports.list",
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports",
          "description": "Retrieves list of reports."
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.reports.update",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Updates a report."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.get",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "GET",
          "description": "Retrieves a report by its ID."
        },
        "run": {
          "description": "Runs a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.reports.run",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run"
        },
        "delete": {
          "id": "dfareporting.reports.delete",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Deletes a report by its ID."
        }
      },
      "resources": {
        "files": {
          "methods": {
            "list": {
              "description": "Lists files for a report.",
              "id": "dfareporting.reports.files.list",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files"
            },
            "get": {
              "supportsMediaDownload": true,
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "id": "dfareporting.reports.files.get",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}"
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "POST",
              "id": "dfareporting.reports.compatibleFields.query",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        }
      }
    },
    "contentCategories": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "description": "Deletes an existing content category.",
          "id": "dfareporting.contentCategories.delete",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "DELETE"
        },
        "get": {
          "description": "Gets one content category by ID.",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.contentCategories.get",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}"
        },
        "patch": {
          "description": "Updates an existing content category. This method supports patch semantics.",
          "id": "dfareporting.contentCategories.patch",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories"
        },
        "insert": {
          "description": "Inserts a new content category.",
          "id": "dfareporting.contentCategories.insert",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories"
        },
        "list": {
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "id": "dfareporting.contentCategories.list",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories"
        },
        "update": {
          "description": "Updates an existing content category.",
          "id": "dfareporting.contentCategories.update",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystems.get",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system by DART ID."
        },
        "list": {
          "id": "dfareporting.operatingSystems.list",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystems",
          "description": "Retrieves a list of operating systems."
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "description": "Retrieves a list of regions.",
          "path": "userprofiles/{+profileId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.regions.list",
          "flatPath": "userprofiles/{userprofilesId}/regions"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "id": "dfareporting.languages.list",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/languages",
          "description": "Retrieves a list of languages."
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "description": "Retrieves a list of TV campaign summaries.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "id": "dfareporting.tvCampaignSummaries.list",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "httpMethod": "GET"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/postalCodes",
          "id": "dfareporting.postalCodes.list",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "httpMethod": "GET",
          "description": "Retrieves a list of postal codes."
        },
        "get": {
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.postalCodes.get",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "description": "Gets one postal code by ID."
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "list": {
          "description": "Gets a list of all supported user role permission groups.",
          "id": "dfareporting.userRolePermissionGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups"
        },
        "get": {
          "description": "Gets one user role permission group by ID.",
          "id": "dfareporting.userRolePermissionGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "insert": {
          "description": "Inserts a new remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.insert",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "POST"
        },
        "list": {
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.remarketingLists.list",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list."
        },
        "patch": {
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "id": "dfareporting.remarketingLists.patch",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists"
        },
        "get": {
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.remarketingLists.get",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "description": "Gets one remarketing list by ID."
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "httpMethod": "POST"
        },
        "list": {
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "insert": {
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement."
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of dynamic targeting keys."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "description": "Deletes an existing dynamic targeting key.",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "httpMethod": "DELETE"
        }
      }
    },
    "accounts": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.accounts.list",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "path": "userprofiles/{+profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging."
        },
        "update": {
          "path": "userprofiles/{+profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.accounts.update",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "description": "Updates an existing account."
        },
        "get": {
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.accounts.get",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "description": "Gets one account by ID."
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.accounts.patch",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "path": "userprofiles/{+profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account. This method supports patch semantics."
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "id": "dfareporting.metros.list",
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/metros",
          "description": "Retrieves a list of metros."
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "list": {
          "id": "dfareporting.userRolePermissions.list",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "description": "Gets a list of user role permissions, possibly filtered."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "id": "dfareporting.userRolePermissions.get",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "httpMethod": "GET",
          "description": "Gets one user role permission by ID."
        }
      }
    },
    "campaigns": {
      "methods": {
        "insert": {
          "description": "Inserts a new campaign.",
          "httpMethod": "POST",
          "id": "dfareporting.campaigns.insert",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "path": "userprofiles/{+profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.campaigns.list",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "id": "dfareporting.campaigns.update",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PUT",
          "description": "Updates an existing campaign."
        },
        "get": {
          "description": "Gets one campaign by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "id": "dfareporting.campaigns.get",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "httpMethod": "GET"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.campaigns.patch",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics."
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "list": {
          "id": "dfareporting.accountPermissionGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "description": "Retrieves the list of account permission groups."
        },
        "get": {
          "description": "Gets one account permission group by ID.",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissionGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "description": "Retrieves a list of browsers.",
          "httpMethod": "GET",
          "id": "dfareporting.browsers.list",
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "path": "userprofiles/{+profileId}/browsers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "id": "dfareporting.accountActiveAdSummaries.get",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "description": "Gets the account's active ad summary by account ID."
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "description": "Gets one mobile carrier by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "id": "dfareporting.mobileCarriers.get",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.mobileCarriers.list",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "description": "Retrieves a list of mobile carriers."
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.studioCreatives.insert",
          "flatPath": "studio/creatives",
          "path": "studio/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new studio creative."
        },
        "publish": {
          "id": "dfareporting.studioCreatives.publish",
          "flatPath": "studio/creatives/{creativesId}/publish",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "description": "Publish for a studio creative."
        },
        "get": {
          "description": "Gets a studio creative by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creatives/{+studioCreativeId}",
          "id": "dfareporting.studioCreatives.get",
          "flatPath": "studio/creatives/{creativesId}",
          "httpMethod": "GET"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.billingRates.list",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing rates. This method supports paging."
        }
      }
    },
    "subaccounts": {
      "methods": {
        "patch": {
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "id": "dfareporting.subaccounts.patch",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts"
        },
        "get": {
          "id": "dfareporting.subaccounts.get",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "description": "Gets one subaccount by ID."
        },
        "insert": {
          "description": "Inserts a new subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "id": "dfareporting.subaccounts.insert",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "POST"
        },
        "list": {
          "id": "dfareporting.subaccounts.list",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging."
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.subaccounts.update",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing subaccount."
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "id": "dfareporting.floodlightActivityGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "description": "Gets one floodlight activity group by ID."
        },
        "patch": {
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups"
        },
        "insert": {
          "description": "Inserts a new floodlight activity group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivityGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging."
        },
        "update": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.floodlightActivityGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group."
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.billingAssignments.insert",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned."
        },
        "list": {
          "description": "Retrieves a list of billing assignments.",
          "httpMethod": "GET",
          "id": "dfareporting.billingAssignments.list",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "description": "Retrieves a list of cities, possibly filtered.",
          "path": "userprofiles/{+profileId}/cities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.cities.list",
          "flatPath": "userprofiles/{userprofilesId}/cities"
        }
      }
    },
    "creatives": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "id": "dfareporting.creatives.insert",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "POST",
          "description": "Inserts a new creative."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "id": "dfareporting.creatives.list",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "GET",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging."
        },
        "update": {
          "description": "Updates an existing creative.",
          "httpMethod": "PUT",
          "id": "dfareporting.creatives.update",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "id": "dfareporting.creatives.get",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "httpMethod": "GET",
          "description": "Gets one creative by ID."
        },
        "patch": {
          "id": "dfareporting.creatives.patch",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Updates an existing creative. This method supports patch semantics."
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "get": {
          "id": "dfareporting.advertiserLandingPages.get",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "description": "Gets one landing page by ID."
        },
        "patch": {
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.advertiserLandingPages.patch",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.advertiserLandingPages.insert",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new landing page."
        },
        "list": {
          "description": "Retrieves a list of landing pages.",
          "id": "dfareporting.advertiserLandingPages.list",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.advertiserLandingPages.update",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing landing page."
        }
      }
    },
    "sites": {
      "methods": {
        "insert": {
          "description": "Inserts a new site.",
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.sites.insert",
          "flatPath": "userprofiles/{userprofilesId}/sites"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.list",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging."
        },
        "update": {
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.sites.update",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Updates an existing site."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.patch",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "PATCH",
          "description": "Updates an existing site. This method supports patch semantics."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "id": "dfareporting.sites.get",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "httpMethod": "GET",
          "description": "Gets one site by ID."
        }
      }
    },
    "userRoles": {
      "methods": {
        "patch": {
          "description": "Updates an existing user role. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles",
          "id": "dfareporting.userRoles.patch",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PATCH"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.userRoles.get",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role by ID."
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "dfareporting.userRoles.delete",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "description": "Deletes an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new user role.",
          "id": "dfareporting.userRoles.insert",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles"
        },
        "list": {
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.userRoles.list",
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        },
        "update": {
          "description": "Updates an existing user role.",
          "id": "dfareporting.userRoles.update",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles"
        }
      }
    },
    "placements": {
      "methods": {
        "patch": {
          "description": "Updates an existing placement. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "id": "dfareporting.placements.patch",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "PATCH"
        },
        "get": {
          "description": "Gets one placement by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "id": "dfareporting.placements.get",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "httpMethod": "GET"
        },
        "generatetags": {
          "description": "Generates tags for a placement.",
          "httpMethod": "POST",
          "id": "dfareporting.placements.generatetags",
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.placements.insert",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Inserts a new placement."
        },
        "list": {
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "id": "dfareporting.placements.list",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements"
        },
        "update": {
          "id": "dfareporting.placements.update",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "description": "Updates an existing placement."
        }
      }
    },
    "userProfiles": {
      "methods": {
        "list": {
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list",
          "flatPath": "userprofiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles"
        },
        "get": {
          "description": "Gets one user profile by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.userProfiles.get",
          "flatPath": "userprofiles/{profileId}",
          "path": "userprofiles/{profileId}",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "delete": {
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "description": "Deletes an existing advertiser group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "id": "dfareporting.advertiserGroups.delete",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        },
        "get": {
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.advertiserGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "description": "Gets one advertiser group by ID."
        },
        "patch": {
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PATCH"
        },
        "insert": {
          "description": "Inserts a new advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.advertiserGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "list": {
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.advertiserGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group."
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "description": "Inserts conversions.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "id": "dfareporting.conversions.batchinsert",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST"
        },
        "batchupdate": {
          "description": "Updates existing conversions.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "id": "dfareporting.conversions.batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "delete": {
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "description": "Deletes an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "id": "dfareporting.placementStrategies.delete",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.placementStrategies.patch",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement strategy. This method supports patch semantics."
        },
        "get": {
          "id": "dfareporting.placementStrategies.get",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "description": "Gets one placement strategy by ID."
        },
        "insert": {
          "description": "Inserts a new placement strategy.",
          "id": "dfareporting.placementStrategies.insert",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.list",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "GET",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging."
        },
        "update": {
          "description": "Updates an existing placement strategy.",
          "id": "dfareporting.placementStrategies.update",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.creativeFieldValues.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative field value."
        },
        "list": {
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFieldValues.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFieldValues.update",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "description": "Updates an existing creative field value."
        },
        "delete": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "description": "Deletes an existing creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFieldValues.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "id": "dfareporting.creativeFieldValues.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "httpMethod": "GET",
          "description": "Gets one creative field value by ID."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.patch",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field value. This method supports patch semantics."
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.remarketingListShares.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list share."
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.remarketingListShares.patch",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list share. This method supports patch semantics."
        },
        "get": {
          "description": "Gets one remarketing list share by remarketing list ID.",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingListShares.get",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placementGroups": {
      "methods": {
        "insert": {
          "description": "Inserts a new placement group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "id": "dfareporting.placementGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "POST"
        },
        "list": {
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "update": {
          "description": "Updates an existing placement group.",
          "httpMethod": "PUT",
          "id": "dfareporting.placementGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.placementGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Updates an existing placement group. This method supports patch semantics."
        },
        "get": {
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "description": "Gets one placement group by ID."
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "description": "Gets one billing profile by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.billingProfiles.get",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.billingProfiles.list",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging."
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.billingProfiles.update",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing billing profile."
        }
      }
    },
    "mobileApps": {
      "methods": {
        "list": {
          "description": "Retrieves list of available mobile apps.",
          "id": "dfareporting.mobileApps.list",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileApps"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.mobileApps.get",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile app by ID."
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.dimensionValues.query",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "description": "Retrieves list of report dimension values for a list of filters."
        }
      }
    },
    "ads": {
      "methods": {
        "insert": {
          "description": "Inserts a new ad.",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.ads.insert",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        },
        "list": {
          "id": "dfareporting.ads.list",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging."
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.ads.update",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad."
        },
        "get": {
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.ads.get",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "description": "Gets one ad by ID."
        },
        "patch": {
          "description": "Updates an existing ad. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "id": "dfareporting.ads.patch",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "PATCH"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "insert": {
          "description": "Inserts a new creative field.",
          "id": "dfareporting.creativeFields.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields"
        },
        "list": {
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "id": "dfareporting.creativeFields.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "GET"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "id": "dfareporting.creativeFields.update",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "PUT",
          "description": "Updates an existing creative field."
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.creativeFields.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative field by ID."
        },
        "patch": {
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeFields.patch",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Updates an existing creative field. This method supports patch semantics."
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFields.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "description": "Deletes an existing creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "description": "Lists files for a user profile.",
          "httpMethod": "GET",
          "id": "dfareporting.files.list",
          "flatPath": "userprofiles/{profileId}/files",
          "path": "userprofiles/{profileId}/files",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "get": {
          "supportsMediaDownload": true,
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "reports/{reportId}/files/{fileId}",
          "id": "dfareporting.files.get",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "httpMethod": "GET"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "insert": {
          "description": "Inserts a new account user profile.",
          "id": "dfareporting.accountUserProfiles.insert",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles"
        },
        "list": {
          "id": "dfareporting.accountUserProfiles.list",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging."
        },
        "update": {
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "id": "dfareporting.accountUserProfiles.update",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "description": "Updates an existing account user profile."
        },
        "get": {
          "description": "Gets one account user profile by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.accountUserProfiles.get",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.patch",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "description": "Updates an existing account user profile. This method supports patch semantics."
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "description": "Retrieves a list of platform types.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "httpMethod": "GET"
        },
        "get": {
          "description": "Gets one platform type by ID.",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.platformTypes.get",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "id": "dfareporting.accountPermissions.get",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "description": "Gets one account permission by ID."
        },
        "list": {
          "description": "Retrieves the list of account permissions.",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissions.list",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions"
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "id": "dfareporting.sizes.get",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "description": "Gets one size by ID."
        },
        "insert": {
          "id": "dfareporting.sizes.insert",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes",
          "description": "Inserts a new size."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes",
          "id": "dfareporting.sizes.list",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "GET",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI."
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "list": {
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "id": "dfareporting.floodlightConfigurations.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.update",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight configuration."
        },
        "get": {
          "description": "Gets one floodlight configuration by ID.",
          "id": "dfareporting.floodlightConfigurations.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}"
        },
        "patch": {
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "PATCH"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/changeLogs",
          "id": "dfareporting.changeLogs.list",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "httpMethod": "GET",
          "description": "Retrieves a list of change logs. This method supports paging."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "id": "dfareporting.changeLogs.get",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "httpMethod": "GET",
          "description": "Gets one change log by ID."
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "description": "Gets one video format by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "id": "dfareporting.videoFormats.get",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Lists available video formats.",
          "id": "dfareporting.videoFormats.list",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/videoFormats"
        }
      }
    }
  },
  "ownerName": "Google",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v5/",
  "protocol": "rest",
  "revision": "20260310",
  "version": "v5",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "title": "Campaign Manager 360 API",
  "servicePath": "dfareporting/v5/"
}