{
  "rootUrl": "https://dfareporting.googleapis.com/",
  "discoveryVersion": "v1",
  "servicePath": "dfareporting/v4/",
  "revision": "20260310",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "resources": {
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of TV campaign summaries.",
          "id": "dfareporting.tvCampaignSummaries.list",
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "httpMethod": "GET"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles",
          "id": "dfareporting.userProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves list of user profiles for a user.",
          "flatPath": "userprofiles"
        },
        "get": {
          "path": "userprofiles/{profileId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user profile by ID.",
          "id": "dfareporting.userProfiles.get",
          "flatPath": "userprofiles/{profileId}"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative asset.",
          "id": "dfareporting.creativeAssets.insert",
          "supportsMediaUpload": true,
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "httpMethod": "POST"
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one directory site by ID.",
          "id": "dfareporting.directorySites.get",
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "httpMethod": "GET"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/directorySites",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new directory site.",
          "id": "dfareporting.directorySites.insert",
          "flatPath": "userprofiles/{userprofilesId}/directorySites"
        },
        "list": {
          "id": "dfareporting.directorySites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/directorySites"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "id": "dfareporting.operatingSystemVersions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of operating system versions.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "id": "dfareporting.operatingSystemVersions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system version by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "id": "dfareporting.floodlightActivities.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing floodlight activity."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new floodlight activity.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/floodlightActivities"
        },
        "list": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivities.list"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight activity by ID.",
          "id": "dfareporting.floodlightActivities.get",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity."
        },
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates a tag for a floodlight activity.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "id": "dfareporting.floodlightActivities.patch"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account user profile."
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "id": "dfareporting.accountUserProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account user profile by ID.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "id": "dfareporting.accountUserProfiles.patch",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new account user profile.",
          "id": "dfareporting.accountUserProfiles.insert",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/languages",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of languages.",
          "id": "dfareporting.languages.list"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of account permission groups.",
          "id": "dfareporting.accountPermissionGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account permission group by ID.",
          "id": "dfareporting.accountPermissionGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "httpMethod": "GET"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "id": "dfareporting.platformTypes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one platform type by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of platform types.",
          "id": "dfareporting.platformTypes.list",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "path": "userprofiles/{+profileId}/platformTypes",
          "httpMethod": "GET"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile app by ID.",
          "id": "dfareporting.mobileApps.get",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "id": "dfareporting.mobileApps.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves list of available mobile apps.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/mobileApps"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one change log by ID.",
          "id": "dfareporting.changeLogs.get",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "httpMethod": "GET"
        },
        "list": {
          "id": "dfareporting.changeLogs.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of change logs. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/changeLogs"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "id": "dfareporting.contentCategories.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new content category."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "id": "dfareporting.contentCategories.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/contentCategories"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "id": "dfareporting.contentCategories.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing content category."
        },
        "patch": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing content category. This method supports patch semantics.",
          "id": "dfareporting.contentCategories.patch",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "get": {
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one content category by ID.",
          "id": "dfareporting.contentCategories.get"
        },
        "update": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing content category.",
          "id": "dfareporting.contentCategories.update",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        }
      }
    },
    "countries": {
      "methods": {
        "list": {
          "id": "dfareporting.countries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of countries.",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/countries"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "id": "dfareporting.countries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one country by ID."
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "id": "dfareporting.billingAssignments.insert",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "httpMethod": "POST"
        },
        "list": {
          "id": "dfareporting.billingAssignments.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing assignments.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "id": "dfareporting.billingRates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing rates. This method supports paging."
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "id": "dfareporting.tvCampaignDetails.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one TvCampaignDetail by ID.",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}"
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/files",
          "id": "dfareporting.files.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Lists files for a user profile.",
          "flatPath": "userprofiles/{profileId}/files"
        },
        "get": {
          "flatPath": "reports/{reportId}/files/{fileId}",
          "id": "dfareporting.files.get",
          "supportsMediaDownload": true,
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "httpMethod": "GET",
          "path": "reports/{reportId}/files/{fileId}"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one postal code by ID.",
          "id": "dfareporting.postalCodes.get",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "httpMethod": "GET"
        },
        "list": {
          "path": "userprofiles/{+profileId}/postalCodes",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of postal codes.",
          "id": "dfareporting.postalCodes.list"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/regions",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "id": "dfareporting.regions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of regions."
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission by ID.",
          "id": "dfareporting.userRolePermissions.get",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of user role permissions, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of account permissions.",
          "id": "dfareporting.accountPermissions.list",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "httpMethod": "GET"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "id": "dfareporting.accountPermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account permission by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}"
        }
      }
    },
    "ads": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "id": "dfareporting.ads.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new ad.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/ads"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/ads",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "id": "dfareporting.ads.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging."
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/ads",
          "id": "dfareporting.ads.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "id": "dfareporting.ads.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one ad by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/ads/{+id}"
        },
        "update": {
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad.",
          "id": "dfareporting.ads.update",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "id": "dfareporting.advertiserInvoices.list",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "get": {
          "id": "dfareporting.creativeGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}"
        },
        "update": {
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group.",
          "id": "dfareporting.creativeGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "id": "dfareporting.creativeGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group. This method supports patch semantics."
        },
        "insert": {
          "id": "dfareporting.creativeGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative group.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeGroups"
        },
        "list": {
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging."
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one video format by ID.",
          "id": "dfareporting.videoFormats.get",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}"
        },
        "list": {
          "id": "dfareporting.videoFormats.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Lists available video formats.",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/videoFormats"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new subaccount.",
          "id": "dfareporting.subaccounts.insert",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "POST"
        },
        "list": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.subaccounts.list"
        },
        "get": {
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one subaccount by ID.",
          "id": "dfareporting.subaccounts.get",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "id": "dfareporting.subaccounts.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing subaccount."
        },
        "patch": {
          "id": "dfareporting.subaccounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/subaccounts"
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "id": "dfareporting.accounts.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account by ID.",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accounts/{+id}"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account.",
          "id": "dfareporting.accounts.update",
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "PUT"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "id": "dfareporting.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/accounts"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.accounts.list",
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "GET"
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "id": "dfareporting.inventoryItems.list"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems/{inventoryItemsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one inventory item by ID.",
          "id": "dfareporting.inventoryItems.get",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems/{+id}",
          "httpMethod": "GET"
        }
      }
    },
    "advertisers": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new advertiser.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "id": "dfareporting.advertisers.list",
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "GET"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "id": "dfareporting.advertisers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one advertiser by ID."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser.",
          "id": "dfareporting.advertisers.update",
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "PUT"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "POST"
        },
        "list": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivityGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "id": "dfareporting.floodlightActivityGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight activity group by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}"
        },
        "update": {
          "id": "dfareporting.floodlightActivityGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity group.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "id": "dfareporting.dimensionValues.query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves list of report dimension values for a list of filters.",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    },
    "userRoles": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role by ID.",
          "id": "dfareporting.userRoles.get"
        },
        "update": {
          "id": "dfareporting.userRoles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/userRoles"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/userRoles",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing user role. This method supports patch semantics."
        },
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/userRoles",
          "id": "dfareporting.userRoles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "id": "dfareporting.userRoles.list",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "GET"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations"
        },
        "list": {
          "id": "dfareporting.floodlightConfigurations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightConfigurations"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight configuration by ID.",
          "id": "dfareporting.floodlightConfigurations.get",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight configuration.",
          "id": "dfareporting.floodlightConfigurations.update",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "PUT"
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "insert": {
          "flatPath": "studio/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new studio creative.",
          "id": "dfareporting.studioCreatives.insert",
          "path": "studio/creatives",
          "httpMethod": "POST"
        },
        "publish": {
          "flatPath": "studio/creatives/{creativesId}/publish",
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Publish for a studio creative.",
          "id": "dfareporting.studioCreatives.publish",
          "httpMethod": "POST"
        },
        "get": {
          "id": "dfareporting.studioCreatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a studio creative by ID.",
          "flatPath": "studio/creatives/{creativesId}",
          "httpMethod": "GET",
          "path": "studio/creatives/{+studioCreativeId}"
        }
      }
    },
    "creatives": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative.",
          "id": "dfareporting.creatives.insert"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creatives",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging."
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "id": "dfareporting.creatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creatives/{+id}"
        },
        "update": {
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative.",
          "id": "dfareporting.creatives.update"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative. This method supports patch semantics.",
          "id": "dfareporting.creatives.patch",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PATCH"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing dynamic targeting key.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of dynamic targeting keys.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative field value by ID.",
          "id": "dfareporting.creativeFieldValues.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field value.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "id": "dfareporting.creativeFieldValues.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field value."
        },
        "insert": {
          "id": "dfareporting.creativeFieldValues.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative field value.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeFieldValues.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "GET"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one targeting template by ID.",
          "id": "dfareporting.targetingTemplates.get",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing targeting template.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/targetingTemplates"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "id": "dfareporting.targetingTemplates.patch",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "PATCH"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new targeting template.",
          "id": "dfareporting.targetingTemplates.insert",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "POST"
        },
        "list": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "id": "dfareporting.targetingTemplates.list"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "delete": {
          "id": "dfareporting.advertiserGroups.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        },
        "patch": {
          "id": "dfareporting.advertiserGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one advertiser group by ID.",
          "id": "dfareporting.advertiserGroups.get",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "PUT"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placementGroups",
          "id": "dfareporting.placementGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement group.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "list": {
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.placementGroups.list"
        },
        "update": {
          "id": "dfareporting.placementGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement group.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "id": "dfareporting.placementGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "id": "dfareporting.placementGroups.patch",
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PATCH"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "id": "dfareporting.browsers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of browsers.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/browsers"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "id": "dfareporting.mobileCarriers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of mobile carriers.",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "id": "dfareporting.mobileCarriers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile carrier by ID."
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/metros",
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "id": "dfareporting.metros.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of metros."
        }
      }
    },
    "reports": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves a report by its ID."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Updates a report.",
          "id": "dfareporting.reports.update",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Updates an existing report. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "run": {
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Runs a report.",
          "id": "dfareporting.reports.run",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run"
        },
        "delete": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Deletes a report by its ID.",
          "id": "dfareporting.reports.delete",
          "httpMethod": "DELETE"
        },
        "insert": {
          "path": "userprofiles/{profileId}/reports",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Creates a report.",
          "id": "dfareporting.reports.insert"
        },
        "list": {
          "id": "dfareporting.reports.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves list of reports.",
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/reports"
        }
      },
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "id": "dfareporting.reports.compatibleFields.query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST"
            }
          }
        },
        "files": {
          "methods": {
            "get": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "supportsMediaDownload": true,
              "id": "dfareporting.reports.files.get",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Lists files for a report.",
              "id": "dfareporting.reports.files.list",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "projects": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "id": "dfareporting.projects.list",
          "flatPath": "userprofiles/{userprofilesId}/projects",
          "path": "userprofiles/{+profileId}/projects",
          "httpMethod": "GET"
        },
        "get": {
          "path": "userprofiles/{+profileId}/projects/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one project by ID.",
          "id": "dfareporting.projects.get",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectsId}"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "id": "dfareporting.creativeFields.patch"
        },
        "get": {
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative field by ID.",
          "id": "dfareporting.creativeFields.get"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "id": "dfareporting.creativeFields.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creativeFields"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "id": "dfareporting.creativeFields.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative field."
        },
        "list": {
          "id": "dfareporting.creativeFields.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "id": "dfareporting.creativeFields.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field."
        }
      }
    },
    "sites": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing site.",
          "id": "dfareporting.sites.update",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PUT"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one site by ID.",
          "id": "dfareporting.sites.get",
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing site. This method supports patch semantics.",
          "id": "dfareporting.sites.patch",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PATCH"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new site.",
          "flatPath": "userprofiles/{userprofilesId}/sites"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/sites"
        }
      }
    },
    "eventTags": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/eventTags",
          "id": "dfareporting.eventTags.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing event tag.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "id": "dfareporting.eventTags.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one event tag by ID.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new event tag.",
          "id": "dfareporting.eventTags.insert",
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "POST"
        },
        "list": {
          "id": "dfareporting.eventTags.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of event tags, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "delete": {
          "id": "dfareporting.eventTags.delete",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing event tag.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Inserts conversions.",
          "id": "dfareporting.conversions.batchinsert"
        },
        "batchupdate": {
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Updates existing conversions.",
          "id": "dfareporting.conversions.batchupdate"
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a dynamic profile by ID.",
          "id": "dfareporting.dynamicProfiles.get",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "studio/dynamicProfiles",
          "id": "dfareporting.dynamicProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing dynamic profile.",
          "httpMethod": "PUT",
          "path": "studio/dynamicProfiles"
        },
        "generateCode": {
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "httpMethod": "GET",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "id": "dfareporting.dynamicProfiles.generateCode"
        },
        "insert": {
          "path": "studio/dynamicProfiles",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new dynamic profile.",
          "id": "dfareporting.dynamicProfiles.insert",
          "flatPath": "studio/dynamicProfiles"
        },
        "publish": {
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Publish for a dynamic profile.",
          "id": "dfareporting.dynamicProfiles.publish",
          "httpMethod": "POST"
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one size by ID.",
          "id": "dfareporting.sizes.get",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new size.",
          "id": "dfareporting.sizes.insert",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "path": "userprofiles/{+profileId}/sizes",
          "httpMethod": "POST"
        },
        "list": {
          "path": "userprofiles/{+profileId}/sizes",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "id": "dfareporting.sizes.list"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets the account's active ad summary by account ID."
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "path": "studio/dynamicFeeds",
          "flatPath": "studio/dynamicFeeds",
          "id": "dfareporting.dynamicFeeds.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new dynamic feed."
        },
        "get": {
          "id": "dfareporting.dynamicFeeds.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a dynamic feed by ID.",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "httpMethod": "GET",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "id": "dfareporting.dynamicFeeds.update",
          "flatPath": "studio/dynamicFeeds",
          "path": "studio/dynamicFeeds",
          "httpMethod": "PUT"
        },
        "retransform": {
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "id": "dfareporting.dynamicFeeds.retransform",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "httpMethod": "POST"
        }
      }
    },
    "orders": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one order by ID.",
          "id": "dfareporting.orders.get",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders/{ordersId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "id": "dfareporting.orders.list",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders",
          "httpMethod": "GET"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "update": {
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list share.",
          "id": "dfareporting.remarketingListShares.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        },
        "get": {
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list share by remarketing list ID.",
          "id": "dfareporting.remarketingListShares.get",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "id": "dfareporting.remarketingListShares.patch",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "update": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list.",
          "id": "dfareporting.remarketingLists.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "id": "dfareporting.remarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list by ID."
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new remarketing list."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingLists"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/connectionTypes",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "id": "dfareporting.connectionTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of connection types."
        },
        "get": {
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one connection type by ID.",
          "id": "dfareporting.connectionTypes.get",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement strategy.",
          "id": "dfareporting.placementStrategies.insert"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "id": "dfareporting.placementStrategies.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging."
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing placement strategy.",
          "id": "dfareporting.placementStrategies.delete",
          "httpMethod": "DELETE"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "id": "dfareporting.placementStrategies.patch"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement strategy by ID.",
          "id": "dfareporting.placementStrategies.get",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.placementStrategies.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement strategy.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/placementStrategies"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "id": "dfareporting.userRolePermissionGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission group by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "id": "dfareporting.userRolePermissionGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of all supported user role permission groups.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new landing page.",
          "id": "dfareporting.advertiserLandingPages.insert",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of landing pages.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "id": "dfareporting.advertiserLandingPages.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one landing page by ID."
        },
        "update": {
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing landing page.",
          "id": "dfareporting.advertiserLandingPages.update",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "id": "dfareporting.advertiserLandingPages.patch",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "PATCH"
        }
      }
    },
    "placements": {
      "methods": {
        "generatetags": {
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "id": "dfareporting.placements.generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates tags for a placement.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placements/generatetags"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement."
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging."
        },
        "patch": {
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement. This method supports patch semantics.",
          "id": "dfareporting.placements.patch"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/placements"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "id": "dfareporting.placements.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placements/{+id}"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of cities, possibly filtered.",
          "id": "dfareporting.cities.list",
          "path": "userprofiles/{+profileId}/cities",
          "httpMethod": "GET"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "id": "dfareporting.targetableRemarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.targetableRemarketingLists.list",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists"
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "path": "studio/creativeAssets",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new studio creative asset.",
          "id": "dfareporting.studioCreativeAssets.insert",
          "supportsMediaUpload": true,
          "flatPath": "studio/creativeAssets"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "id": "dfareporting.operatingSystems.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system by DART ID.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/operatingSystems",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of operating systems.",
          "id": "dfareporting.operatingSystems.list",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems"
        }
      }
    },
    "campaigns": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new campaign.",
          "id": "dfareporting.campaigns.insert"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "id": "dfareporting.campaigns.list",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "GET"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "id": "dfareporting.campaigns.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing campaign. This method supports patch semantics."
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one campaign by ID.",
          "id": "dfareporting.campaigns.get",
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing campaign.",
          "id": "dfareporting.campaigns.update",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "id": "dfareporting.billingProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing billing profile.",
          "id": "dfareporting.billingProfiles.update",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "httpMethod": "PUT"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one billing profile by ID.",
          "id": "dfareporting.billingProfiles.get",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "httpMethod": "GET"
        }
      }
    }
  },
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "name": "dfareporting",
  "protocol": "rest",
  "id": "dfareporting:v4",
  "title": "Campaign Manager 360 API",
  "version": "v4",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "basePath": "/dfareporting/v4/",
  "canonicalName": "Dfareporting",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "kind": "discovery#restDescription",
  "batchPath": "batch"
}