{
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "batchPath": "batch",
  "name": "dfareporting",
  "discoveryVersion": "v1",
  "title": "Campaign Manager 360 API",
  "ownerName": "Google",
  "revision": "20260310",
  "fullyEncodeReservedExpansion": true,
  "version": "v4",
  "id": "dfareporting:v4",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        }
      }
    }
  },
  "servicePath": "dfareporting/v4/",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "basePath": "/dfareporting/v4/",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "resources": {
    "connectionTypes": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/connectionTypes",
          "description": "Retrieves a list of connection types.",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "httpMethod": "GET",
          "id": "dfareporting.connectionTypes.list"
        },
        "get": {
          "description": "Gets one connection type by ID.",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "id": "dfareporting.connectionTypes.get"
        }
      }
    },
    "reports": {
      "methods": {
        "list": {
          "id": "dfareporting.reports.list",
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "GET",
          "description": "Retrieves list of reports.",
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "run": {
          "id": "dfareporting.reports.run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST",
          "description": "Runs a report."
        },
        "insert": {
          "id": "dfareporting.reports.insert",
          "path": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "POST",
          "description": "Creates a report."
        },
        "delete": {
          "id": "dfareporting.reports.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Deletes a report by its ID.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "GET",
          "description": "Retrieves a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.get"
        },
        "update": {
          "id": "dfareporting.reports.update",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "description": "Updates a report."
        },
        "patch": {
          "id": "dfareporting.reports.patch",
          "description": "Updates an existing report. This method supports patch semantics.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}"
        }
      },
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "id": "dfareporting.reports.compatibleFields.query"
            }
          }
        },
        "files": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "description": "Lists files for a report.",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "httpMethod": "GET",
              "id": "dfareporting.reports.files.list"
            },
            "get": {
              "id": "dfareporting.reports.files.get",
              "supportsMediaDownload": true,
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download."
            }
          }
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "get": {
          "id": "dfareporting.studioCreatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creatives/{+studioCreativeId}",
          "description": "Gets a studio creative by ID.",
          "flatPath": "studio/creatives/{creativesId}",
          "httpMethod": "GET"
        },
        "insert": {
          "path": "studio/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creatives",
          "httpMethod": "POST",
          "description": "Inserts a new studio creative.",
          "id": "dfareporting.studioCreatives.insert"
        },
        "publish": {
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "id": "dfareporting.studioCreatives.publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creatives/{creativesId}/publish",
          "httpMethod": "POST",
          "description": "Publish for a studio creative."
        }
      }
    },
    "advertisers": {
      "methods": {
        "list": {
          "id": "dfareporting.advertisers.list",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.advertisers.insert",
          "description": "Inserts a new advertiser.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "get": {
          "description": "Gets one advertiser by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "id": "dfareporting.advertisers.get"
        },
        "update": {
          "id": "dfareporting.advertisers.update",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser.",
          "path": "userprofiles/{+profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.patch"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "patch": {
          "id": "dfareporting.placementStrategies.patch",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "id": "dfareporting.placementStrategies.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.placementStrategies.get",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "GET",
          "description": "Gets one placement strategy by ID.",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.placementStrategies.update",
          "description": "Updates an existing placement strategy.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "GET",
          "id": "dfareporting.placementStrategies.list"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Inserts a new placement strategy.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "POST",
          "id": "dfareporting.placementStrategies.insert"
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "id": "dfareporting.countries.get",
          "description": "Gets one country by ID.",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/countries/{+dartId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/countries",
          "description": "Retrieves a list of countries.",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "httpMethod": "GET",
          "id": "dfareporting.countries.list"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "list": {
          "id": "dfareporting.mobileApps.list",
          "path": "userprofiles/{+profileId}/mobileApps",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "httpMethod": "GET",
          "description": "Retrieves list of available mobile apps."
        },
        "get": {
          "id": "dfareporting.mobileApps.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "description": "Gets one mobile app by ID.",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "httpMethod": "GET"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "httpMethod": "GET",
          "description": "Retrieves a list of postal codes.",
          "path": "userprofiles/{+profileId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.list"
        },
        "get": {
          "description": "Gets one postal code by ID.",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "id": "dfareporting.postalCodes.get"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "httpMethod": "GET",
          "description": "Gets one TvCampaignDetail by ID.",
          "id": "dfareporting.tvCampaignDetails.get"
        }
      }
    },
    "projects": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectsId}",
          "httpMethod": "GET",
          "description": "Gets one project by ID.",
          "path": "userprofiles/{+profileId}/projects/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.projects.get"
        },
        "list": {
          "id": "dfareporting.projects.list",
          "flatPath": "userprofiles/{userprofilesId}/projects",
          "httpMethod": "GET",
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "path": "userprofiles/{+profileId}/projects",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "id": "dfareporting.videoFormats.get",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "httpMethod": "GET",
          "description": "Gets one video format by ID.",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "httpMethod": "GET",
          "description": "Lists available video formats.",
          "path": "userprofiles/{+profileId}/videoFormats",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.videoFormats.list"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "list": {
          "id": "dfareporting.billingProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "httpMethod": "GET"
        },
        "get": {
          "id": "dfareporting.billingProfiles.get",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "httpMethod": "GET",
          "description": "Gets one billing profile by ID.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.billingProfiles.update",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "httpMethod": "PUT",
          "description": "Updates an existing billing profile."
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "description": "Retrieves a list of dynamic targeting keys.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "httpMethod": "GET",
          "id": "dfareporting.dynamicTargetingKeys.list"
        },
        "delete": {
          "description": "Deletes an existing dynamic targeting key.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}"
        },
        "insert": {
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "id": "dfareporting.dynamicTargetingKeys.insert"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "id": "dfareporting.dimensionValues.query",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field.",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "id": "dfareporting.creativeFields.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one creative field by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "id": "dfareporting.creativeFields.get"
        },
        "update": {
          "id": "dfareporting.creativeFields.update",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "PUT",
          "description": "Updates an existing creative field.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.creativeFields.patch",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field. This method supports patch semantics."
        },
        "insert": {
          "id": "dfareporting.creativeFields.insert",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "POST",
          "description": "Inserts a new creative field."
        },
        "list": {
          "id": "dfareporting.creativeFields.list",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields"
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "id": "dfareporting.studioCreativeAssets.insert",
          "path": "studio/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creativeAssets",
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "description": "Inserts a new studio creative asset."
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "id": "dfareporting.browsers.list",
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "httpMethod": "GET",
          "description": "Retrieves a list of browsers.",
          "path": "userprofiles/{+profileId}/browsers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "get": {
          "description": "Gets one inventory item by ID.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems/{inventoryItemsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems/{+id}",
          "id": "dfareporting.inventoryItems.get"
        },
        "list": {
          "id": "dfareporting.inventoryItems.list",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems",
          "httpMethod": "GET",
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creatives": {
      "methods": {
        "get": {
          "id": "dfareporting.creatives.get",
          "description": "Gets one creative by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives/{+id}"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "PUT",
          "description": "Updates an existing creative.",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.update"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative. This method supports patch semantics.",
          "id": "dfareporting.creatives.patch"
        },
        "insert": {
          "id": "dfareporting.creatives.insert",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "POST",
          "description": "Inserts a new creative."
        },
        "list": {
          "id": "dfareporting.creatives.list",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "GET",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "id": "dfareporting.accountPermissionGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "httpMethod": "GET",
          "description": "Gets one account permission group by ID.",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "httpMethod": "GET",
          "description": "Retrieves the list of account permission groups.",
          "id": "dfareporting.accountPermissionGroups.list"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFieldValues.list"
        },
        "insert": {
          "description": "Inserts a new creative field value.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.insert"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field value.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "id": "dfareporting.creativeFieldValues.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one creative field value by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "id": "dfareporting.creativeFieldValues.get"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFieldValues.update"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "id": "dfareporting.creativeFieldValues.patch"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "patch": {
          "id": "dfareporting.subaccounts.patch",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts"
        },
        "get": {
          "id": "dfareporting.subaccounts.get",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "httpMethod": "GET",
          "description": "Gets one subaccount by ID.",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "PUT",
          "description": "Updates an existing subaccount.",
          "id": "dfareporting.subaccounts.update"
        },
        "list": {
          "id": "dfareporting.subaccounts.list",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts"
        },
        "insert": {
          "id": "dfareporting.subaccounts.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Inserts a new subaccount.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "POST"
        }
      }
    },
    "eventTags": {
      "methods": {
        "delete": {
          "description": "Deletes an existing event tag.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.eventTags.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags/{+id}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "description": "Gets one event tag by ID.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "GET",
          "id": "dfareporting.eventTags.get"
        },
        "update": {
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "PUT",
          "description": "Updates an existing event tag.",
          "id": "dfareporting.eventTags.update"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "PATCH",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.patch"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Inserts a new event tag.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "POST",
          "id": "dfareporting.eventTags.insert"
        },
        "list": {
          "id": "dfareporting.eventTags.list",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "GET",
          "description": "Retrieves a list of event tags, possibly filtered."
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "id": "dfareporting.metros.list",
          "path": "userprofiles/{+profileId}/metros",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "httpMethod": "GET",
          "description": "Retrieves a list of metros."
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "description": "Gets a list of all supported user role permission groups.",
          "id": "dfareporting.userRolePermissionGroups.list"
        },
        "get": {
          "description": "Gets one user role permission group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "id": "dfareporting.userRolePermissionGroups.get"
        }
      }
    },
    "orders": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders/{+id}",
          "description": "Gets one order by ID.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders/{ordersId}",
          "httpMethod": "GET",
          "id": "dfareporting.orders.get"
        },
        "list": {
          "id": "dfareporting.orders.list",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders",
          "httpMethod": "GET",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "directorySites": {
      "methods": {
        "insert": {
          "id": "dfareporting.directorySites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Inserts a new directory site.",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "GET",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.list"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "description": "Gets one directory site by ID.",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "httpMethod": "GET",
          "id": "dfareporting.directorySites.get"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "httpMethod": "PATCH",
          "id": "dfareporting.remarketingListShares.patch"
        },
        "get": {
          "id": "dfareporting.remarketingListShares.get",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "httpMethod": "GET",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing remarketing list share.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.update"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "GET",
          "description": "Retrieves a list of landing pages.",
          "id": "dfareporting.advertiserLandingPages.list"
        },
        "insert": {
          "description": "Inserts a new landing page.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.insert"
        },
        "get": {
          "id": "dfareporting.advertiserLandingPages.get",
          "description": "Gets one landing page by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}"
        },
        "update": {
          "id": "dfareporting.advertiserLandingPages.update",
          "description": "Updates an existing landing page.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "PATCH",
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "id": "dfareporting.advertiserLandingPages.patch"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "id": "dfareporting.languages.list",
          "description": "Retrieves a list of languages.",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/languages"
        }
      }
    },
    "sizes": {
      "methods": {
        "list": {
          "id": "dfareporting.sizes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "description": "Gets one size by ID.",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "httpMethod": "GET",
          "id": "dfareporting.sizes.get"
        },
        "insert": {
          "id": "dfareporting.sizes.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes",
          "description": "Inserts a new size.",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "POST"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "httpMethod": "GET",
          "description": "Gets one floodlight configuration by ID.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.get"
        },
        "update": {
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight configuration.",
          "id": "dfareporting.floodlightConfigurations.update"
        },
        "patch": {
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.patch"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightConfigurations.list"
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "retransform": {
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "httpMethod": "POST",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "id": "dfareporting.dynamicFeeds.retransform"
        },
        "get": {
          "id": "dfareporting.dynamicFeeds.get",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "httpMethod": "GET",
          "description": "Gets a dynamic feed by ID."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "flatPath": "studio/dynamicFeeds",
          "httpMethod": "PUT",
          "id": "dfareporting.dynamicFeeds.update"
        },
        "insert": {
          "id": "dfareporting.dynamicFeeds.insert",
          "description": "Inserts a new dynamic feed.",
          "flatPath": "studio/dynamicFeeds",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "insert": {
          "description": "Inserts a new floodlight activity group.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.insert"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.list"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity group by ID.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.get"
        },
        "update": {
          "id": "dfareporting.floodlightActivityGroups.update",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight activity group."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.patch"
        }
      }
    },
    "sites": {
      "methods": {
        "patch": {
          "id": "dfareporting.sites.patch",
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "PATCH",
          "description": "Updates an existing site. This method supports patch semantics."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "description": "Gets one site by ID.",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "httpMethod": "GET",
          "id": "dfareporting.sites.get"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites",
          "description": "Updates an existing site.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "PUT",
          "id": "dfareporting.sites.update"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "GET",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.list"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "POST",
          "description": "Inserts a new site.",
          "id": "dfareporting.sites.insert"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "httpMethod": "GET",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "id": "dfareporting.advertiserInvoices.list"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "list": {
          "id": "dfareporting.userRolePermissions.list",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "httpMethod": "GET",
          "description": "Gets a list of user role permissions, possibly filtered.",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "httpMethod": "GET",
          "description": "Gets one user role permission by ID.",
          "id": "dfareporting.userRolePermissions.get"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "httpMethod": "GET",
          "description": "Gets one mobile carrier by ID.",
          "id": "dfareporting.mobileCarriers.get"
        },
        "list": {
          "id": "dfareporting.mobileCarriers.list",
          "description": "Retrieves a list of mobile carriers.",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileCarriers"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "id": "dfareporting.accountActiveAdSummaries.get",
          "description": "Gets the account's active ad summary by account ID.",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}"
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "id": "dfareporting.tvCampaignSummaries.list",
          "description": "Retrieves a list of TV campaign summaries.",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/tvCampaignSummaries"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/cities",
          "description": "Retrieves a list of cities, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "httpMethod": "GET",
          "id": "dfareporting.cities.list"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "id": "dfareporting.changeLogs.list",
          "path": "userprofiles/{+profileId}/changeLogs",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "httpMethod": "GET",
          "description": "Retrieves a list of change logs. This method supports paging."
        },
        "get": {
          "id": "dfareporting.changeLogs.get",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "httpMethod": "GET",
          "description": "Gets one change log by ID."
        }
      }
    },
    "contentCategories": {
      "methods": {
        "insert": {
          "id": "dfareporting.contentCategories.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Inserts a new content category.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "GET",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.list"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing content category.",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "id": "dfareporting.contentCategories.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.contentCategories.get",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "GET",
          "description": "Gets one content category by ID."
        },
        "update": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "PUT",
          "description": "Updates an existing content category.",
          "id": "dfareporting.contentCategories.update"
        },
        "patch": {
          "id": "dfareporting.contentCategories.patch",
          "path": "userprofiles/{+profileId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "PATCH",
          "description": "Updates an existing content category. This method supports patch semantics."
        }
      }
    },
    "placements": {
      "methods": {
        "generatetags": {
          "description": "Generates tags for a placement.",
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "id": "dfareporting.placements.generatetags"
        },
        "patch": {
          "id": "dfareporting.placements.patch",
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement. This method supports patch semantics."
        },
        "get": {
          "id": "dfareporting.placements.get",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "httpMethod": "GET",
          "description": "Gets one placement by ID.",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "PUT",
          "description": "Updates an existing placement.",
          "id": "dfareporting.placements.update"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "POST",
          "description": "Inserts a new placement.",
          "id": "dfareporting.placements.insert"
        },
        "list": {
          "id": "dfareporting.placements.list",
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "GET",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging."
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "id": "dfareporting.platformTypes.get",
          "description": "Gets one platform type by ID.",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/platformTypes/{+id}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "httpMethod": "GET",
          "description": "Retrieves a list of platform types.",
          "path": "userprofiles/{+profileId}/platformTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.list"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "insert": {
          "id": "dfareporting.remarketingLists.insert",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "POST",
          "description": "Inserts a new remarketing list.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.remarketingLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "GET"
        },
        "patch": {
          "id": "dfareporting.remarketingLists.patch",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "PATCH",
          "description": "Updates an existing remarketing list. This method supports patch semantics."
        },
        "get": {
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "id": "dfareporting.remarketingLists.get"
        },
        "update": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "PUT",
          "description": "Updates an existing remarketing list.",
          "id": "dfareporting.remarketingLists.update"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "httpMethod": "GET",
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingRates.list"
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "list": {
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list"
        },
        "insert": {
          "description": "Inserts a new creative group.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.insert"
        },
        "get": {
          "id": "dfareporting.creativeGroups.get",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "httpMethod": "GET",
          "description": "Gets one creative group by ID."
        },
        "update": {
          "id": "dfareporting.creativeGroups.update",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing creative group."
        },
        "patch": {
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.patch"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "list": {
          "id": "dfareporting.accountUserProfiles.list",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "GET",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging."
        },
        "insert": {
          "id": "dfareporting.accountUserProfiles.insert",
          "description": "Inserts a new account user profile.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles"
        },
        "get": {
          "id": "dfareporting.accountUserProfiles.get",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "httpMethod": "GET",
          "description": "Gets one account user profile by ID."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PUT",
          "description": "Updates an existing account user profile.",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.update"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "id": "dfareporting.accountUserProfiles.patch"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "httpMethod": "GET",
          "description": "Retrieves a list of regions.",
          "path": "userprofiles/{+profileId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.regions.list"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "flatPath": "reports/{reportId}/files/{fileId}",
          "httpMethod": "GET",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "supportsMediaDownload": true,
          "path": "reports/{reportId}/files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.get"
        },
        "list": {
          "id": "dfareporting.files.list",
          "path": "userprofiles/{profileId}/files",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "description": "Lists files for a user profile."
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "id": "dfareporting.userProfiles.get",
          "path": "userprofiles/{profileId}",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{profileId}",
          "httpMethod": "GET",
          "description": "Gets one user profile by ID."
        },
        "list": {
          "path": "userprofiles",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles",
          "httpMethod": "GET",
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "id": "dfareporting.billingAssignments.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "httpMethod": "POST"
        },
        "list": {
          "id": "dfareporting.billingAssignments.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "description": "Retrieves a list of billing assignments.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "httpMethod": "GET"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "id": "dfareporting.conversions.batchinsert",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST",
          "description": "Inserts conversions."
        },
        "batchupdate": {
          "id": "dfareporting.conversions.batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "description": "Updates existing conversions.",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ]
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "list": {
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "id": "dfareporting.targetableRemarketingLists.list"
        },
        "get": {
          "id": "dfareporting.targetableRemarketingLists.get",
          "description": "Gets one remarketing list by ID.",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "generatetag": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "description": "Generates a tag for a floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.generatetag"
        },
        "list": {
          "id": "dfareporting.floodlightActivities.list",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging."
        },
        "insert": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "POST",
          "description": "Inserts a new floodlight activity.",
          "id": "dfareporting.floodlightActivities.insert"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "id": "dfareporting.floodlightActivities.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.floodlightActivities.get",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity by ID."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.update"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivities.patch"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "GET",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.list"
        },
        "insert": {
          "description": "Inserts a new targeting template.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.insert"
        },
        "patch": {
          "id": "dfareporting.targetingTemplates.patch",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PATCH",
          "description": "Updates an existing targeting template. This method supports patch semantics."
        },
        "get": {
          "id": "dfareporting.targetingTemplates.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "description": "Gets one targeting template by ID.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PUT",
          "description": "Updates an existing targeting template.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.update"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "httpMethod": "GET",
          "description": "Retrieves the list of account permissions.",
          "path": "userprofiles/{+profileId}/accountPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.list"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "httpMethod": "GET",
          "description": "Gets one account permission by ID.",
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.get"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "httpMethod": "DELETE",
          "description": "Deletes an existing advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "id": "dfareporting.advertiserGroups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "description": "Gets one advertiser group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserGroups.get"
        },
        "update": {
          "id": "dfareporting.advertiserGroups.update",
          "description": "Updates an existing advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "patch": {
          "id": "dfareporting.advertiserGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PATCH"
        },
        "list": {
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.list"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.insert"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "description": "Inserts a new creative asset.",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeAssets.insert"
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "generateCode": {
          "id": "dfareporting.dynamicProfiles.generateCode",
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode"
        },
        "insert": {
          "flatPath": "studio/dynamicProfiles",
          "httpMethod": "POST",
          "description": "Inserts a new dynamic profile.",
          "path": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.insert"
        },
        "get": {
          "id": "dfareporting.dynamicProfiles.get",
          "description": "Gets a dynamic profile by ID.",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}"
        },
        "update": {
          "id": "dfareporting.dynamicProfiles.update",
          "flatPath": "studio/dynamicProfiles",
          "httpMethod": "PUT",
          "description": "Updates an existing dynamic profile.",
          "path": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "publish": {
          "description": "Publish for a dynamic profile.",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicProfiles.publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "id": "dfareporting.operatingSystemVersions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "description": "Retrieves a list of operating system versions.",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "httpMethod": "GET"
        },
        "get": {
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "httpMethod": "GET",
          "description": "Gets one operating system version by ID.",
          "id": "dfareporting.operatingSystemVersions.get"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "httpMethod": "GET",
          "description": "Gets one operating system by DART ID.",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystems.get"
        },
        "list": {
          "path": "userprofiles/{+profileId}/operatingSystems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "httpMethod": "GET",
          "description": "Retrieves a list of operating systems.",
          "id": "dfareporting.operatingSystems.list"
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "httpMethod": "GET",
          "description": "Gets one account by ID.",
          "id": "dfareporting.accounts.get"
        },
        "update": {
          "description": "Updates an existing account.",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts",
          "id": "dfareporting.accounts.update"
        },
        "patch": {
          "id": "dfareporting.accounts.patch",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "PATCH",
          "description": "Updates an existing account. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts",
          "id": "dfareporting.accounts.list"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "insert": {
          "description": "Inserts a new placement group.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "id": "dfareporting.placementGroups.insert"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "GET",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.list"
        },
        "patch": {
          "id": "dfareporting.placementGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "PATCH",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.placementGroups.get",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "httpMethod": "GET",
          "description": "Gets one placement group by ID."
        },
        "update": {
          "id": "dfareporting.placementGroups.update",
          "description": "Updates an existing placement group.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups"
        }
      }
    },
    "campaigns": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "httpMethod": "GET",
          "description": "Gets one campaign by ID.",
          "id": "dfareporting.campaigns.get"
        },
        "update": {
          "id": "dfareporting.campaigns.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PUT"
        },
        "patch": {
          "id": "dfareporting.campaigns.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PATCH"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "GET",
          "id": "dfareporting.campaigns.list"
        },
        "insert": {
          "description": "Inserts a new campaign.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "id": "dfareporting.campaigns.insert"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "httpMethod": "POST",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.campaignCreativeAssociations.list",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "httpMethod": "GET",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging."
        }
      }
    },
    "userRoles": {
      "methods": {
        "list": {
          "id": "dfareporting.userRoles.list",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles"
        },
        "insert": {
          "id": "dfareporting.userRoles.insert",
          "description": "Inserts a new user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PATCH",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "id": "dfareporting.userRoles.patch"
        },
        "get": {
          "id": "dfareporting.userRoles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "description": "Gets one user role by ID.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PUT",
          "description": "Updates an existing user role.",
          "id": "dfareporting.userRoles.update"
        },
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "description": "Deletes an existing user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "httpMethod": "DELETE"
        }
      }
    },
    "ads": {
      "methods": {
        "insert": {
          "id": "dfareporting.ads.insert",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "POST",
          "description": "Inserts a new ad.",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "GET",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "id": "dfareporting.ads.list"
        },
        "get": {
          "id": "dfareporting.ads.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "description": "Gets one ad by ID.",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.ads.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "description": "Updates an existing ad.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "PUT"
        },
        "patch": {
          "id": "dfareporting.ads.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "PATCH"
        }
      }
    }
  },
  "rootUrl": "https://dfareporting.googleapis.com/",
  "canonicalName": "Dfareporting",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "protocol": "rest"
}