{
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "title": "Campaign Manager 360 API",
  "kind": "discovery#restDescription",
  "batchPath": "batch",
  "version": "v4",
  "discoveryVersion": "v1",
  "basePath": "/dfareporting/v4/",
  "name": "dfareporting",
  "resources": {
    "creativeGroups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.insert",
          "description": "Inserts a new creative group.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "POST"
        },
        "patch": {
          "id": "dfareporting.creativeGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "description": "Updates an existing creative group. This method supports patch semantics."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "id": "dfareporting.creativeGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "description": "Gets one creative group by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "id": "dfareporting.creativeGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing creative group.",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.update"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.metros.list",
          "path": "userprofiles/{+profileId}/metros",
          "httpMethod": "GET",
          "description": "Retrieves a list of metros.",
          "flatPath": "userprofiles/{userprofilesId}/metros"
        }
      }
    },
    "sites": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Inserts a new site.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/sites",
          "id": "dfareporting.sites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one site by ID.",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.get"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.update",
          "description": "Updates an existing site.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PUT"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/sites",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "id": "dfareporting.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "description": "Updates an existing site. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sites.patch"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "PATCH",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.patch"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.get",
          "description": "Gets one targeting template by ID.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "description": "Updates an existing targeting template.",
          "id": "dfareporting.targetingTemplates.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.list",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "GET",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        },
        "insert": {
          "id": "dfareporting.targetingTemplates.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "description": "Inserts a new targeting template."
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "description": "Inserts a new studio creative asset.",
          "flatPath": "studio/creativeAssets",
          "path": "studio/creativeAssets",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.studioCreativeAssets.insert",
          "supportsMediaUpload": true
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "list": {
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetableRemarketingLists.list"
        },
        "get": {
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetableRemarketingLists.get"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.get",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "httpMethod": "GET",
          "description": "Gets one change log by ID.",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.list",
          "path": "userprofiles/{+profileId}/changeLogs",
          "httpMethod": "GET",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs"
        }
      }
    },
    "sizes": {
      "methods": {
        "insert": {
          "id": "dfareporting.sizes.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "description": "Inserts a new size.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/sizes"
        },
        "list": {
          "path": "userprofiles/{+profileId}/sizes",
          "httpMethod": "GET",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.list"
        },
        "get": {
          "description": "Gets one size by ID.",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.sizes.get"
        }
      }
    },
    "ads": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/ads",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "id": "dfareporting.ads.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "description": "Gets one ad by ID.",
          "id": "dfareporting.ads.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing ad.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.update"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.patch",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "PATCH"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "POST",
          "description": "Inserts a new ad.",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.insert"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "description": "Retrieves a list of mobile carriers.",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileCarriers.list"
        },
        "get": {
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "httpMethod": "GET",
          "description": "Gets one mobile carrier by ID.",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileCarriers.get"
        }
      }
    },
    "userRoles": {
      "methods": {
        "insert": {
          "description": "Inserts a new user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.insert"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing user role.",
          "id": "dfareporting.userRoles.delete",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "DELETE"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.patch",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "PATCH"
        },
        "list": {
          "id": "dfareporting.userRoles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRoles"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.get",
          "description": "Gets one user role by ID.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.update"
        }
      }
    },
    "accounts": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "GET",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.list"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.get",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "httpMethod": "GET",
          "description": "Gets one account by ID.",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}"
        },
        "update": {
          "id": "dfareporting.accounts.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/accounts",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "description": "Updates an existing account."
        },
        "patch": {
          "id": "dfareporting.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/accounts",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "description": "Updates an existing account. This method supports patch semantics."
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "id": "dfareporting.cities.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "description": "Retrieves a list of cities, possibly filtered.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/cities"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserInvoices.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level."
        }
      }
    },
    "reports": {
      "methods": {
        "delete": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Deletes a report by its ID.",
          "id": "dfareporting.reports.delete",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "insert": {
          "path": "userprofiles/{profileId}/reports",
          "httpMethod": "POST",
          "description": "Creates a report.",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.insert"
        },
        "run": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST",
          "description": "Runs a report.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.get",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "GET",
          "description": "Retrieves a report by its ID.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "update": {
          "id": "dfareporting.reports.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Updates a report.",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        },
        "list": {
          "id": "dfareporting.reports.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports",
          "description": "Retrieves list of reports.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/reports"
        },
        "patch": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Updates an existing report. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      },
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "id": "dfareporting.reports.compatibleFields.query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        },
        "files": {
          "methods": {
            "get": {
              "id": "dfareporting.reports.files.get",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "supportsMediaDownload": true,
              "httpMethod": "GET",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download."
            },
            "list": {
              "id": "dfareporting.reports.files.list",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "description": "Lists files for a report.",
              "httpMethod": "GET",
              "path": "userprofiles/{profileId}/reports/{reportId}/files"
            }
          }
        }
      }
    },
    "campaigns": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.insert",
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "POST",
          "description": "Inserts a new campaign.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        },
        "get": {
          "description": "Gets one campaign by ID.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.get"
        },
        "update": {
          "id": "dfareporting.campaigns.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Updates an existing campaign.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/campaigns"
        },
        "list": {
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.list"
        },
        "patch": {
          "id": "dfareporting.campaigns.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics."
        }
      }
    },
    "eventTags": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/eventTags",
          "id": "dfareporting.eventTags.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.eventTags.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "description": "Gets one event tag by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/eventTags/{+id}"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Updates an existing event tag.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/eventTags",
          "id": "dfareporting.eventTags.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/eventTags",
          "id": "dfareporting.eventTags.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "id": "dfareporting.eventTags.delete",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing event tag.",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/eventTags/{+id}"
        },
        "insert": {
          "id": "dfareporting.eventTags.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "description": "Inserts a new event tag."
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "description": "Gets one operating system by DART ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "id": "dfareporting.operatingSystems.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystems",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "description": "Retrieves a list of operating systems.",
          "id": "dfareporting.operatingSystems.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems",
          "httpMethod": "GET",
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.inventoryItems.list"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.inventoryItems.get",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems/{+id}",
          "httpMethod": "GET",
          "description": "Gets one inventory item by ID.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems/{inventoryItemsId}"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.patch",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        },
        "get": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "httpMethod": "GET",
          "description": "Gets one creative field value by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.get"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "description": "Updates an existing creative field value.",
          "id": "dfareporting.creativeFieldValues.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.creativeFieldValues.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging."
        },
        "insert": {
          "description": "Inserts a new creative field value.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.insert"
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "id": "dfareporting.creativeFieldValues.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field value."
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "id": "dfareporting.mobileApps.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "description": "Gets one mobile app by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileApps.list",
          "path": "userprofiles/{+profileId}/mobileApps",
          "httpMethod": "GET",
          "description": "Retrieves list of available mobile apps.",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.dimensionValues.query",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "httpMethod": "POST",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/languages",
          "httpMethod": "GET",
          "description": "Retrieves a list of languages.",
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.languages.list"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "description": "Gets one postal code by ID.",
          "id": "dfareporting.postalCodes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.list",
          "path": "userprofiles/{+profileId}/postalCodes",
          "httpMethod": "GET",
          "description": "Retrieves a list of postal codes.",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "description": "Gets one floodlight activity group by ID.",
          "id": "dfareporting.floodlightActivityGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.floodlightActivityGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging."
        },
        "patch": {
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.patch"
        },
        "insert": {
          "id": "dfareporting.floodlightActivityGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "description": "Inserts a new floodlight activity group."
        }
      }
    },
    "directorySites": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.list",
          "path": "userprofiles/{+profileId}/directorySites",
          "httpMethod": "GET",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/directorySites"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "description": "Gets one directory site by ID.",
          "id": "dfareporting.directorySites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "path": "userprofiles/{+profileId}/directorySites",
          "httpMethod": "POST",
          "description": "Inserts a new directory site.",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.insert"
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "get": {
          "id": "dfareporting.studioCreatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creatives/{creativesId}",
          "description": "Gets a studio creative by ID.",
          "httpMethod": "GET",
          "path": "studio/creatives/{+studioCreativeId}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "studio/creatives",
          "flatPath": "studio/creatives",
          "description": "Inserts a new studio creative.",
          "id": "dfareporting.studioCreatives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "publish": {
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Publish for a studio creative.",
          "id": "dfareporting.studioCreatives.publish",
          "flatPath": "studio/creatives/{creativesId}/publish"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "reports/{reportId}/files/{fileId}",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "supportsMediaDownload": true,
          "id": "dfareporting.files.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.list",
          "path": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "description": "Lists files for a user profile.",
          "flatPath": "userprofiles/{profileId}/files"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.get",
          "description": "Gets one account user profile by ID.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.update",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "PUT",
          "description": "Updates an existing account user profile.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        },
        "list": {
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "GET",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.list"
        },
        "patch": {
          "id": "dfareporting.accountUserProfiles.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "description": "Updates an existing account user profile. This method supports patch semantics."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.insert",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "POST",
          "description": "Inserts a new account user profile.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "description": "Generates a tag for a floodlight activity.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.list",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.get",
          "description": "Gets one floodlight activity by ID.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.floodlightActivities.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "description": "Updates an existing floodlight activity."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.patch",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing floodlight activity.",
          "id": "dfareporting.floodlightActivities.delete",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "httpMethod": "DELETE"
        },
        "insert": {
          "id": "dfareporting.floodlightActivities.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "description": "Inserts a new floodlight activity.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/floodlightActivities"
        }
      }
    },
    "orders": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders/{+id}",
          "httpMethod": "GET",
          "description": "Gets one order by ID.",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders/{ordersId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.orders.get"
        },
        "list": {
          "id": "dfareporting.orders.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "id": "dfareporting.accountPermissionGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "description": "Gets one account permission group by ID."
        },
        "list": {
          "id": "dfareporting.accountPermissionGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "description": "Retrieves the list of account permission groups.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissionGroups"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.get",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "GET",
          "description": "Gets one creative field by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}"
        },
        "update": {
          "id": "dfareporting.creativeFields.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Updates an existing creative field."
        },
        "list": {
          "id": "dfareporting.creativeFields.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "id": "dfareporting.creativeFields.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "id": "dfareporting.creativeFields.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing creative field.",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "description": "Inserts a new creative field.",
          "id": "dfareporting.creativeFields.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "publish": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Publish for a dynamic profile.",
          "id": "dfareporting.dynamicProfiles.publish",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "httpMethod": "POST"
        },
        "get": {
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "httpMethod": "GET",
          "description": "Gets a dynamic profile by ID.",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.get"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.update",
          "path": "studio/dynamicProfiles",
          "httpMethod": "PUT",
          "description": "Updates an existing dynamic profile.",
          "flatPath": "studio/dynamicProfiles"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "studio/dynamicProfiles",
          "flatPath": "studio/dynamicProfiles",
          "description": "Inserts a new dynamic profile.",
          "id": "dfareporting.dynamicProfiles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "generateCode": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.generateCode",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "httpMethod": "GET",
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.insert"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.delete",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        },
        "patch": {
          "id": "dfareporting.advertiserGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/advertiserGroups"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "description": "Gets one advertiser group by ID.",
          "id": "dfareporting.advertiserGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "PUT",
          "description": "Updates an existing advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.update"
        },
        "list": {
          "id": "dfareporting.advertiserGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging."
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.insert"
        },
        "list": {
          "description": "Retrieves a list of billing assignments.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.list"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "description": "Gets one account permission by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "id": "dfareporting.accountPermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.accountPermissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "description": "Retrieves the list of account permissions.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissions"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "description": "Inserts a new subaccount.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/subaccounts",
          "id": "dfareporting.subaccounts.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/subaccounts",
          "id": "dfareporting.subaccounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "description": "Gets one subaccount by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "id": "dfareporting.subaccounts.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "description": "Updates an existing subaccount.",
          "id": "dfareporting.subaccounts.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.subaccounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/subaccounts"
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "insert": {
          "flatPath": "studio/dynamicFeeds",
          "description": "Inserts a new dynamic feed.",
          "httpMethod": "POST",
          "path": "studio/dynamicFeeds",
          "id": "dfareporting.dynamicFeeds.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "description": "Gets a dynamic feed by ID.",
          "httpMethod": "GET",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "id": "dfareporting.dynamicFeeds.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.dynamicFeeds.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicFeeds",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "httpMethod": "PUT",
          "path": "studio/dynamicFeeds"
        },
        "retransform": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicFeeds.retransform",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "httpMethod": "POST",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "description": "Gets the account's active ad summary by account ID.",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "description": "Gets one user role permission by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "id": "dfareporting.userRolePermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Gets a list of user role permissions, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissions.list"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "description": "Gets one TvCampaignDetail by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "id": "dfareporting.tvCampaignDetails.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "contentCategories": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "httpMethod": "GET",
          "description": "Gets one content category by ID.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.get"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "description": "Updates an existing content category.",
          "id": "dfareporting.contentCategories.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "id": "dfareporting.contentCategories.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.patch",
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "PATCH",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing content category.",
          "id": "dfareporting.contentCategories.delete",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}"
        },
        "insert": {
          "description": "Inserts a new content category.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.insert"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing dynamic targeting key.",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "httpMethod": "DELETE"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.list",
          "description": "Retrieves a list of dynamic targeting keys.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.insert"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.floodlightConfigurations.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "description": "Gets one floodlight configuration by ID."
        },
        "update": {
          "description": "Updates an existing floodlight configuration.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.update"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "PATCH",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.patch"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "list": {
          "id": "dfareporting.videoFormats.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "description": "Lists available video formats.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/videoFormats"
        },
        "get": {
          "description": "Gets one video format by ID.",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.videoFormats.get"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "id": "dfareporting.remarketingListShares.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "description": "Updates an existing remarketing list share.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "id": "dfareporting.remarketingListShares.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.remarketingListShares.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/remarketingListShares"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.browsers.list",
          "description": "Retrieves a list of browsers.",
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "path": "userprofiles/{+profileId}/browsers",
          "httpMethod": "GET"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}",
          "description": "Gets one user profile by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}",
          "id": "dfareporting.userProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userProfiles.list",
          "path": "userprofiles",
          "httpMethod": "GET",
          "description": "Retrieves list of user profiles for a user.",
          "flatPath": "userprofiles"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "list": {
          "id": "dfareporting.campaignCreativeAssociations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "httpMethod": "POST",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeAssets.insert",
          "supportsMediaUpload": true,
          "description": "Inserts a new creative asset.",
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "httpMethod": "POST"
        }
      }
    },
    "countries": {
      "methods": {
        "list": {
          "id": "dfareporting.countries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/countries",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "description": "Retrieves a list of countries."
        },
        "get": {
          "description": "Gets one country by ID.",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.get"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.insert",
          "description": "Inserts a new placement group.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "POST"
        },
        "list": {
          "id": "dfareporting.placementGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "get": {
          "id": "dfareporting.placementGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "description": "Gets one placement group by ID."
        },
        "update": {
          "description": "Updates an existing placement group.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.update"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/placementGroups",
          "id": "dfareporting.placementGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "description": "Gets one operating system version by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "id": "dfareporting.operatingSystemVersions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "description": "Retrieves a list of operating system versions.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "id": "dfareporting.operatingSystemVersions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "placements": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.insert",
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "POST",
          "description": "Inserts a new placement.",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "generatetags": {
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "description": "Generates tags for a placement.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "id": "dfareporting.placements.generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.placements.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/placements"
        },
        "list": {
          "id": "dfareporting.placements.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placements"
        },
        "get": {
          "id": "dfareporting.placements.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "description": "Gets one placement by ID."
        },
        "update": {
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "PUT",
          "description": "Updates an existing placement.",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.update"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.insert",
          "description": "Inserts a new remarketing list.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "POST"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "id": "dfareporting.remarketingLists.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "httpMethod": "GET",
          "description": "Gets one remarketing list by ID.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.get"
        },
        "update": {
          "description": "Updates an existing remarketing list.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.update"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "id": "dfareporting.placementStrategies.delete",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing placement strategy."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Inserts a new placement strategy.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.placementStrategies.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "description": "Gets one placement strategy by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Updates an existing placement strategy.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "id": "dfareporting.placementStrategies.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.placementStrategies.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/placementStrategies"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "id": "dfareporting.regions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "description": "Retrieves a list of regions.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/regions"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "id": "dfareporting.billingRates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "description": "Retrieves a list of billing rates. This method supports paging."
        }
      }
    },
    "advertisers": {
      "methods": {
        "list": {
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.list"
        },
        "get": {
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "httpMethod": "GET",
          "description": "Gets one advertiser by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.get"
        },
        "update": {
          "id": "dfareporting.advertisers.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "description": "Updates an existing advertiser.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.patch"
        },
        "insert": {
          "id": "dfareporting.advertisers.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "description": "Inserts a new advertiser.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/advertisers"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "description": "Retrieves a list of platform types.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/platformTypes",
          "id": "dfareporting.platformTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "httpMethod": "GET",
          "description": "Gets one platform type by ID.",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.platformTypes.get"
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "id": "dfareporting.tvCampaignSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "description": "Retrieves a list of TV campaign summaries."
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "id": "dfareporting.conversions.batchinsert",
          "description": "Inserts conversions.",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST"
        },
        "batchupdate": {
          "description": "Updates existing conversions.",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "id": "dfareporting.conversions.batchupdate"
        }
      }
    },
    "projects": {
      "methods": {
        "list": {
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "flatPath": "userprofiles/{userprofilesId}/projects",
          "path": "userprofiles/{+profileId}/projects",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.projects.list"
        },
        "get": {
          "id": "dfareporting.projects.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectsId}",
          "description": "Gets one project by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/projects/{+id}"
        }
      }
    },
    "creatives": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "description": "Inserts a new creative.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creatives",
          "id": "dfareporting.creatives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.creatives.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creatives"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.get",
          "description": "Gets one creative by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.update",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PUT",
          "description": "Updates an existing creative.",
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.patch",
          "description": "Updates an existing creative. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PATCH"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "description": "Gets a list of all supported user role permission groups.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissionGroups.list"
        },
        "get": {
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "httpMethod": "GET",
          "description": "Gets one user role permission group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissionGroups.get"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.get",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "httpMethod": "GET",
          "description": "Gets one billing profile by ID.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.update",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "httpMethod": "PUT",
          "description": "Updates an existing billing profile.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles"
        },
        "list": {
          "id": "dfareporting.billingProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "id": "dfareporting.connectionTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/connectionTypes",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "description": "Retrieves a list of connection types."
        },
        "get": {
          "description": "Gets one connection type by ID.",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.connectionTypes.get"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "patch": {
          "id": "dfareporting.advertiserLandingPages.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "description": "Updates an existing landing page. This method supports patch semantics."
        },
        "get": {
          "description": "Gets one landing page by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.get"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "description": "Updates an existing landing page.",
          "id": "dfareporting.advertiserLandingPages.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.list",
          "description": "Retrieves a list of landing pages.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "description": "Inserts a new landing page.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    }
  },
  "ownerName": "Google",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://dfareporting.googleapis.com/",
  "ownerDomain": "google.com",
  "id": "dfareporting:v4",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "canonicalName": "Dfareporting",
  "servicePath": "dfareporting/v4/",
  "protocol": "rest",
  "revision": "20260310"
}