{
  "ownerName": "Google",
  "name": "dfareporting",
  "servicePath": "dfareporting/v5/",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v5/",
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "fullyEncodeReservedExpansion": true,
  "version": "v5",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "id": "dfareporting:v5",
  "protocol": "rest",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "resources": {
    "advertiserLandingPages": {
      "methods": {
        "list": {
          "description": "Retrieves a list of landing pages.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.list",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "GET"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "httpMethod": "GET",
          "description": "Gets one landing page by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.get"
        },
        "update": {
          "id": "dfareporting.advertiserLandingPages.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing landing page.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "id": "dfareporting.advertiserLandingPages.patch",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "PATCH"
        },
        "insert": {
          "description": "Inserts a new landing page.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "httpMethod": "GET",
          "description": "Gets one advertiser group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.get"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "PUT"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.patch"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "id": "dfareporting.advertiserGroups.insert",
          "description": "Inserts a new advertiser group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.delete",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}"
        },
        "list": {
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "path": "userprofiles/{+profileId}/advertiserGroups"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account permission by ID."
        },
        "list": {
          "path": "userprofiles/{+profileId}/accountPermissions",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissions.list",
          "description": "Retrieves the list of account permissions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "httpMethod": "GET",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserInvoices.list"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "httpMethod": "GET",
          "description": "Gets one mobile app by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileApps.get"
        },
        "list": {
          "id": "dfareporting.mobileApps.list",
          "description": "Retrieves list of available mobile apps.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileApps",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "httpMethod": "GET"
        }
      }
    },
    "sizes": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "path": "userprofiles/{+profileId}/sizes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new size.",
          "id": "dfareporting.sizes.insert"
        },
        "list": {
          "id": "dfareporting.sizes.list",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "id": "dfareporting.sizes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one size by ID."
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "id": "dfareporting.languages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of languages.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/languages",
          "flatPath": "userprofiles/{userprofilesId}/languages"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "reports/{reportId}/files/{fileId}",
          "path": "reports/{reportId}/files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "supportsMediaDownload": true,
          "id": "dfareporting.files.get"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/files",
          "flatPath": "userprofiles/{profileId}/files",
          "id": "dfareporting.files.list",
          "description": "Lists files for a user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "id": "dfareporting.billingAssignments.insert"
        },
        "list": {
          "id": "dfareporting.billingAssignments.list",
          "description": "Retrieves a list of billing assignments.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "httpMethod": "GET"
        }
      }
    },
    "eventTags": {
      "methods": {
        "insert": {
          "description": "Inserts a new event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.insert",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "POST"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "description": "Deletes an existing event tag.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.delete",
          "httpMethod": "DELETE"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "httpMethod": "GET",
          "description": "Gets one event tag by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.get"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing event tag.",
          "id": "dfareporting.eventTags.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "path": "userprofiles/{+profileId}/eventTags"
        },
        "patch": {
          "id": "dfareporting.eventTags.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "httpMethod": "PATCH"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of event tags, possibly filtered.",
          "id": "dfareporting.eventTags.list"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "id": "dfareporting.userRolePermissionGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission group by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}"
        },
        "list": {
          "id": "dfareporting.userRolePermissionGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of all supported user role permission groups.",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "httpMethod": "GET"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "id": "dfareporting.floodlightConfigurations.get",
          "description": "Gets one floodlight configuration by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.update"
        },
        "patch": {
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "path": "userprofiles/{+profileId}/floodlightConfigurations"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "GET",
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.list"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "GET",
          "id": "dfareporting.contentCategories.list",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing content category.",
          "id": "dfareporting.contentCategories.delete",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new content category.",
          "id": "dfareporting.contentCategories.insert",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "POST"
        },
        "get": {
          "id": "dfareporting.contentCategories.get",
          "description": "Gets one content category by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}"
        },
        "update": {
          "id": "dfareporting.contentCategories.update",
          "description": "Updates an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "patch": {
          "id": "dfareporting.contentCategories.patch",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "httpMethod": "GET",
          "description": "Gets the account's active ad summary by account ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountActiveAdSummaries.get"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "id": "dfareporting.conversions.batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Inserts conversions.",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST"
        },
        "batchupdate": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "id": "dfareporting.conversions.batchupdate",
          "description": "Updates existing conversions.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ]
        }
      }
    },
    "placementGroups": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.placementGroups.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement group.",
          "id": "dfareporting.placementGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "POST"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "id": "dfareporting.placementGroups.patch"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "httpMethod": "GET",
          "description": "Gets one placement group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.get"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement group.",
          "id": "dfareporting.placementGroups.update"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one platform type by ID.",
          "id": "dfareporting.platformTypes.get"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/platformTypes",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "id": "dfareporting.platformTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of platform types."
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "list": {
          "id": "dfareporting.creativeGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "GET"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "POST",
          "id": "dfareporting.creativeGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative group."
        },
        "get": {
          "id": "dfareporting.creativeGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative group by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}"
        },
        "update": {
          "id": "dfareporting.creativeGroups.update",
          "description": "Updates an existing creative group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.patch"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one connection type by ID.",
          "id": "dfareporting.connectionTypes.get",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of connection types.",
          "id": "dfareporting.connectionTypes.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "path": "userprofiles/{+profileId}/connectionTypes"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "id": "dfareporting.billingRates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing rates. This method supports paging."
        }
      }
    },
    "directorySites": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/directorySites",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "id": "dfareporting.directorySites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new directory site."
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "path": "userprofiles/{+profileId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "id": "dfareporting.directorySites.list"
        },
        "get": {
          "description": "Gets one directory site by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.get",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "httpMethod": "GET"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "id": "dfareporting.remarketingListShares.patch",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "httpMethod": "PATCH"
        },
        "get": {
          "id": "dfareporting.remarketingListShares.get",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.remarketingListShares.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list share.",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "httpMethod": "PUT"
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "insert": {
          "description": "Inserts a new studio creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.studioCreatives.insert",
          "httpMethod": "POST",
          "flatPath": "studio/creatives",
          "path": "studio/creatives"
        },
        "publish": {
          "flatPath": "studio/creatives/{creativesId}/publish",
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Publish for a studio creative.",
          "id": "dfareporting.studioCreatives.publish",
          "httpMethod": "POST"
        },
        "get": {
          "flatPath": "studio/creatives/{creativesId}",
          "path": "studio/creatives/{+studioCreativeId}",
          "httpMethod": "GET",
          "description": "Gets a studio creative by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.studioCreatives.get"
        }
      }
    },
    "userRoles": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "id": "dfareporting.userRoles.list",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "GET"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/userRoles",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.patch",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "id": "dfareporting.userRoles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/userRoles",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.update",
          "description": "Updates an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.userRoles.insert",
          "description": "Inserts a new user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/userRoles",
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing user role.",
          "id": "dfareporting.userRoles.delete",
          "httpMethod": "DELETE"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeFields.list"
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Inserts a new creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.insert"
        },
        "delete": {
          "description": "Deletes an existing creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.delete",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}"
        },
        "get": {
          "description": "Gets one creative field by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.creativeFields.update",
          "description": "Updates an existing creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "PUT"
        },
        "patch": {
          "id": "dfareporting.creativeFields.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "httpMethod": "GET"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new remarketing list."
        },
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "id": "dfareporting.remarketingLists.patch"
        },
        "get": {
          "id": "dfareporting.remarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list.",
          "id": "dfareporting.remarketingLists.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "PUT"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingLists.list"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission by ID.",
          "id": "dfareporting.userRolePermissions.get"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of user role permissions, possibly filtered.",
          "id": "dfareporting.userRolePermissions.list"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "insert": {
          "id": "dfareporting.creativeFieldValues.insert",
          "description": "Inserts a new creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "id": "dfareporting.creativeFieldValues.delete",
          "httpMethod": "DELETE",
          "description": "Deletes an existing creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "id": "dfareporting.creativeFieldValues.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative field value by ID."
        },
        "update": {
          "id": "dfareporting.creativeFieldValues.update",
          "description": "Updates an existing creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PUT"
        },
        "patch": {
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        },
        "list": {
          "id": "dfareporting.creativeFieldValues.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        }
      }
    },
    "placements": {
      "methods": {
        "generatetags": {
          "id": "dfareporting.placements.generatetags",
          "description": "Generates tags for a placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "httpMethod": "POST"
        },
        "list": {
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.list",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement. This method supports patch semantics.",
          "id": "dfareporting.placements.patch",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "PATCH"
        },
        "get": {
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "httpMethod": "GET",
          "id": "dfareporting.placements.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement by ID."
        },
        "update": {
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "PUT",
          "id": "dfareporting.placements.update",
          "description": "Updates an existing placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "POST",
          "description": "Inserts a new placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.insert"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "id": "dfareporting.metros.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of metros.",
          "path": "userprofiles/{+profileId}/metros",
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "httpMethod": "GET"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "description": "Gets one TvCampaignDetail by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.tvCampaignDetails.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "GET",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.list"
        },
        "insert": {
          "id": "dfareporting.accountUserProfiles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new account user profile.",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "POST"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account user profile by ID.",
          "id": "dfareporting.accountUserProfiles.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}"
        },
        "update": {
          "description": "Updates an existing account user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.update",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "PUT"
        },
        "patch": {
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.patch",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "PATCH"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "id": "dfareporting.targetableRemarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.targetableRemarketingLists.list",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "httpMethod": "GET"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}",
          "path": "userprofiles/{profileId}",
          "httpMethod": "GET",
          "description": "Gets one user profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userProfiles.get"
        },
        "list": {
          "id": "dfareporting.userProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves list of user profiles for a user.",
          "path": "userprofiles",
          "flatPath": "userprofiles",
          "httpMethod": "GET"
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "id": "dfareporting.countries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one country by ID."
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/countries",
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "id": "dfareporting.countries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of countries."
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "id": "dfareporting.tvCampaignSummaries.list",
          "description": "Retrieves a list of TV campaign summaries.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "httpMethod": "GET"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of browsers.",
          "id": "dfareporting.browsers.list",
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "path": "userprofiles/{+profileId}/browsers",
          "httpMethod": "GET"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "path": "userprofiles/{+profileId}/cities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of cities, possibly filtered.",
          "id": "dfareporting.cities.list"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "insert": {
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "httpMethod": "DELETE",
          "description": "Deletes an existing dynamic targeting key.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of dynamic targeting keys.",
          "id": "dfareporting.dynamicTargetingKeys.list"
        }
      }
    },
    "accounts": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "id": "dfareporting.accounts.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "path": "userprofiles/{+profileId}/accounts"
        },
        "get": {
          "description": "Gets one account by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "path": "userprofiles/{+profileId}/accounts/{+id}"
        },
        "update": {
          "id": "dfareporting.accounts.update",
          "description": "Updates an existing account.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/accounts",
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/accounts",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "PATCH",
          "id": "dfareporting.accounts.patch",
          "description": "Updates an existing account. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "sites": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new site.",
          "id": "dfareporting.sites.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites"
        },
        "patch": {
          "id": "dfareporting.sites.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing site. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/sites",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "PATCH"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "id": "dfareporting.sites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one site by ID."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing site.",
          "id": "dfareporting.sites.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/sites",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "id": "dfareporting.sites.list",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivityGroups.list",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.floodlightActivityGroups.insert",
          "description": "Inserts a new floodlight activity group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "get": {
          "id": "dfareporting.floodlightActivityGroups.get",
          "description": "Gets one floodlight activity group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.update",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "PUT"
        },
        "patch": {
          "id": "dfareporting.floodlightActivityGroups.patch",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "PATCH"
        }
      }
    },
    "advertisers": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "GET",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.list"
        },
        "get": {
          "description": "Gets one advertiser by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.get",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PUT",
          "id": "dfareporting.advertisers.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser."
        },
        "patch": {
          "id": "dfareporting.advertisers.patch",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "httpMethod": "PATCH"
        },
        "insert": {
          "id": "dfareporting.advertisers.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new advertiser.",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers"
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "studio/dynamicFeeds",
          "path": "studio/dynamicFeeds",
          "description": "Inserts a new dynamic feed.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicFeeds.insert"
        },
        "retransform": {
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicFeeds.retransform",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "httpMethod": "POST"
        },
        "get": {
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "httpMethod": "GET",
          "id": "dfareporting.dynamicFeeds.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a dynamic feed by ID."
        },
        "update": {
          "id": "dfareporting.dynamicFeeds.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "path": "studio/dynamicFeeds",
          "flatPath": "studio/dynamicFeeds",
          "httpMethod": "PUT"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.dimensionValues.query"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "id": "dfareporting.operatingSystems.get",
          "description": "Gets one operating system by DART ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/operatingSystems",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystems.list",
          "description": "Retrieves a list of operating systems.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "reports": {
      "methods": {
        "get": {
          "id": "dfareporting.reports.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves a report by its ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "update": {
          "id": "dfareporting.reports.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Updates a report.",
          "httpMethod": "PUT",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "run": {
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Runs a report.",
          "id": "dfareporting.reports.run"
        },
        "delete": {
          "id": "dfareporting.reports.delete",
          "httpMethod": "DELETE",
          "description": "Deletes a report by its ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Creates a report.",
          "id": "dfareporting.reports.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports",
          "path": "userprofiles/{profileId}/reports"
        },
        "list": {
          "description": "Retrieves list of reports.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports",
          "path": "userprofiles/{profileId}/reports"
        }
      },
      "resources": {
        "files": {
          "methods": {
            "get": {
              "supportsMediaDownload": true,
              "id": "dfareporting.reports.files.get",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET"
            },
            "list": {
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "httpMethod": "GET",
              "id": "dfareporting.reports.files.list",
              "description": "Lists files for a report.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ]
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "id": "dfareporting.reports.compatibleFields.query"
            }
          }
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "list": {
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "GET"
        },
        "insert": {
          "id": "dfareporting.floodlightActivities.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "POST"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing floodlight activity.",
          "id": "dfareporting.floodlightActivities.delete",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}"
        },
        "generatetag": {
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "id": "dfareporting.floodlightActivities.generatetag",
          "description": "Generates a tag for a floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one floodlight activity by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}"
        },
        "update": {
          "id": "dfareporting.floodlightActivities.update",
          "description": "Updates an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "patch": {
          "id": "dfareporting.floodlightActivities.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        }
      }
    },
    "ads": {
      "methods": {
        "get": {
          "id": "dfareporting.ads.get",
          "description": "Gets one ad by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "httpMethod": "GET"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/ads",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "id": "dfareporting.ads.update",
          "description": "Updates an existing ad.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{+profileId}/ads",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "PATCH",
          "id": "dfareporting.ads.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad. This method supports patch semantics."
        },
        "insert": {
          "id": "dfareporting.ads.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new ad.",
          "path": "userprofiles/{+profileId}/ads",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "id": "dfareporting.ads.list"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/regions",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "httpMethod": "GET",
          "id": "dfareporting.regions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of regions."
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "publish": {
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "id": "dfareporting.dynamicProfiles.publish",
          "httpMethod": "POST",
          "description": "Publish for a dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "description": "Gets a dynamic profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.get"
        },
        "update": {
          "description": "Updates an existing dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.update",
          "httpMethod": "PUT",
          "flatPath": "studio/dynamicProfiles",
          "path": "studio/dynamicProfiles"
        },
        "generateCode": {
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "httpMethod": "GET",
          "id": "dfareporting.dynamicProfiles.generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates code for a dynamic profile, which will need unescaping."
        },
        "insert": {
          "httpMethod": "POST",
          "flatPath": "studio/dynamicProfiles",
          "path": "studio/dynamicProfiles",
          "description": "Inserts a new dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicProfiles.insert"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PATCH",
          "id": "dfareporting.targetingTemplates.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing targeting template. This method supports patch semantics."
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "id": "dfareporting.targetingTemplates.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one targeting template by ID."
        },
        "update": {
          "id": "dfareporting.targetingTemplates.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing targeting template.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PUT"
        },
        "insert": {
          "description": "Inserts a new targeting template.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "path": "userprofiles/{+profileId}/targetingTemplates"
        },
        "list": {
          "id": "dfareporting.targetingTemplates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "id": "dfareporting.changeLogs.get",
          "description": "Gets one change log by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of change logs. This method supports paging.",
          "id": "dfareporting.changeLogs.list",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "path": "userprofiles/{+profileId}/changeLogs",
          "httpMethod": "GET"
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "flatPath": "studio/creativeAssets",
          "path": "studio/creativeAssets",
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new studio creative asset.",
          "id": "dfareporting.studioCreativeAssets.insert"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "id": "dfareporting.billingProfiles.get",
          "description": "Gets one billing profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing billing profile.",
          "id": "dfareporting.billingProfiles.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "path": "userprofiles/{+profileId}/billingProfiles"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "id": "dfareporting.billingProfiles.list"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissionGroups.get",
          "description": "Gets one account permission group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of account permission groups.",
          "id": "dfareporting.accountPermissionGroups.list"
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "id": "dfareporting.operatingSystemVersions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system version by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "httpMethod": "GET",
          "description": "Retrieves a list of operating system versions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.operatingSystemVersions.list"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "get": {
          "description": "Gets one postal code by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.postalCodes.get",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "path": "userprofiles/{+profileId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of postal codes.",
          "id": "dfareporting.postalCodes.list"
        }
      }
    },
    "campaigns": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "id": "dfareporting.campaigns.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new campaign."
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "id": "dfareporting.campaigns.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one campaign by ID."
        },
        "update": {
          "id": "dfareporting.campaigns.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing campaign.",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        },
        "patch": {
          "id": "dfareporting.campaigns.patch",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "GET",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.campaigns.list"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "id": "dfareporting.mobileCarriers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile carrier by ID.",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of mobile carriers.",
          "id": "dfareporting.mobileCarriers.list"
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "id": "dfareporting.videoFormats.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one video format by ID."
        },
        "list": {
          "description": "Lists available video formats.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.videoFormats.list",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "path": "userprofiles/{+profileId}/videoFormats",
          "httpMethod": "GET"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "delete": {
          "description": "Deletes an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.delete",
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "POST",
          "id": "dfareporting.placementStrategies.insert",
          "description": "Inserts a new placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "id": "dfareporting.placementStrategies.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement strategy. This method supports patch semantics."
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "httpMethod": "GET",
          "description": "Gets one placement strategy by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.get"
        },
        "update": {
          "id": "dfareporting.placementStrategies.update",
          "description": "Updates an existing placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "httpMethod": "GET",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementStrategies.list"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "id": "dfareporting.creativeAssets.insert",
          "description": "Inserts a new creative asset.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "httpMethod": "POST",
          "supportsMediaUpload": true
        }
      }
    },
    "creatives": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "id": "dfareporting.creatives.list",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "GET"
        },
        "get": {
          "description": "Gets one creative by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.get",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative.",
          "id": "dfareporting.creatives.update"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PATCH",
          "description": "Updates an existing creative. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.patch"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative.",
          "id": "dfareporting.creatives.insert",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "POST"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.list",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.subaccounts.insert",
          "description": "Inserts a new subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "id": "dfareporting.subaccounts.patch",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one subaccount by ID.",
          "id": "dfareporting.subaccounts.get"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "PUT",
          "description": "Updates an existing subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.update"
        }
      }
    }
  },
  "revision": "20260310",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "basePath": "/dfareporting/v5/",
  "ownerDomain": "google.com",
  "title": "Campaign Manager 360 API",
  "canonicalName": "Dfareporting"
}