{
  "ownerName": "Google",
  "servicePath": "dfareporting/v4/",
  "name": "dfareporting",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "revision": "20260310",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "title": "Campaign Manager 360 API",
  "fullyEncodeReservedExpansion": true,
  "version": "v4",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "id": "dfareporting:v4",
  "canonicalName": "Dfareporting",
  "batchPath": "batch",
  "resources": {
    "targetingTemplates": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.targetingTemplates.get",
          "description": "Gets one targeting template by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.insert",
          "description": "Inserts a new targeting template.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        },
        "patch": {
          "id": "dfareporting.targetingTemplates.patch",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "PATCH"
        },
        "list": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetingTemplates.list",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Updates an existing targeting template.",
          "id": "dfareporting.targetingTemplates.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account by ID.",
          "id": "dfareporting.accounts.get",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "GET",
          "id": "dfareporting.accounts.list",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/accounts",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing account.",
          "id": "dfareporting.accounts.update"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accounts.patch",
          "description": "Updates an existing account. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/accounts",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/browsers",
          "path": "userprofiles/{+profileId}/browsers",
          "httpMethod": "GET",
          "id": "dfareporting.browsers.list",
          "description": "Retrieves a list of browsers.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "contentCategories": {
      "methods": {
        "delete": {
          "description": "Deletes an existing content category.",
          "id": "dfareporting.contentCategories.delete",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories/{+id}"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one content category by ID.",
          "id": "dfareporting.contentCategories.get"
        },
        "insert": {
          "id": "dfareporting.contentCategories.insert",
          "description": "Inserts a new content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "POST"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "path": "userprofiles/{+profileId}/contentCategories",
          "httpMethod": "PATCH",
          "id": "dfareporting.contentCategories.patch",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "id": "dfareporting.contentCategories.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/contentCategories"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/contentCategories",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing content category.",
          "id": "dfareporting.contentCategories.update"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "generatetag": {
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.generatetag",
          "description": "Generates a tag for a floodlight activity."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "id": "dfareporting.floodlightActivities.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivities.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivities.update",
          "description": "Updates an existing floodlight activity."
        },
        "delete": {
          "id": "dfareporting.floodlightActivities.delete",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "description": "Deletes an existing floodlight activity.",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE"
        },
        "get": {
          "description": "Gets one floodlight activity by ID.",
          "id": "dfareporting.floodlightActivities.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new floodlight activity.",
          "id": "dfareporting.floodlightActivities.insert"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "delete": {
          "description": "Deletes an existing creative field.",
          "id": "dfareporting.creativeFields.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "description": "Gets one creative field by ID.",
          "id": "dfareporting.creativeFields.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "id": "dfareporting.creativeFields.insert",
          "description": "Inserts a new creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "POST"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creativeFields",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "id": "dfareporting.creativeFields.patch"
        },
        "list": {
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "id": "dfareporting.creativeFields.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields"
        },
        "update": {
          "description": "Updates an existing creative field.",
          "id": "dfareporting.creativeFields.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creativeFields"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "id": "dfareporting.placementStrategies.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "id": "dfareporting.placementStrategies.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement strategy.",
          "id": "dfareporting.placementStrategies.update"
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "description": "Deletes an existing placement strategy.",
          "id": "dfareporting.placementStrategies.delete",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}"
        },
        "get": {
          "id": "dfareporting.placementStrategies.get",
          "description": "Gets one placement strategy by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement strategy.",
          "id": "dfareporting.placementStrategies.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "get": {
          "id": "dfareporting.inventoryItems.get",
          "description": "Gets one inventory item by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems/{inventoryItemsId}",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems/{+id}",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems",
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "id": "dfareporting.inventoryItems.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "projects": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/projects",
          "flatPath": "userprofiles/{userprofilesId}/projects",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "id": "dfareporting.projects.list"
        },
        "get": {
          "path": "userprofiles/{+profileId}/projects/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.projects.get",
          "description": "Gets one project by ID."
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "description": "Gets one TvCampaignDetail by ID.",
          "id": "dfareporting.tvCampaignDetails.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "description": "Gets the account's active ad summary by account ID.",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "description": "Gets one size by ID.",
          "id": "dfareporting.sizes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/sizes/{+id}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "path": "userprofiles/{+profileId}/sizes",
          "httpMethod": "POST",
          "id": "dfareporting.sizes.insert",
          "description": "Inserts a new size.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "id": "dfareporting.sizes.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/sizes",
          "flatPath": "userprofiles/{userprofilesId}/sizes"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "description": "Gets one account permission group by ID.",
          "id": "dfareporting.accountPermissionGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.accountPermissionGroups.list",
          "description": "Retrieves the list of account permission groups.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "httpMethod": "GET"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list",
          "httpMethod": "GET",
          "path": "userprofiles",
          "flatPath": "userprofiles"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user profile by ID.",
          "id": "dfareporting.userProfiles.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}",
          "flatPath": "userprofiles/{profileId}"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.placementGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.update",
          "description": "Updates an existing placement group.",
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placementGroups.patch",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placementGroups",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one placement group by ID.",
          "id": "dfareporting.placementGroups.get"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new placement group.",
          "id": "dfareporting.placementGroups.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placementGroups",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingAssignments.insert",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments"
        },
        "list": {
          "description": "Retrieves a list of billing assignments.",
          "id": "dfareporting.billingAssignments.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.advertiserGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.update"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "id": "dfareporting.advertiserGroups.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.get",
          "description": "Gets one advertiser group by ID.",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.insert",
          "description": "Inserts a new advertiser group.",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing advertiser group.",
          "id": "dfareporting.advertiserGroups.delete",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "id": "dfareporting.conversions.batchinsert",
          "description": "Inserts conversions.",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert"
        },
        "batchupdate": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "id": "dfareporting.conversions.batchupdate",
          "description": "Updates existing conversions.",
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "description": "Gets one floodlight activity group by ID.",
          "id": "dfareporting.floodlightActivityGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.insert"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivityGroups.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "update": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightActivityGroups.update",
          "description": "Updates an existing floodlight activity group."
        },
        "patch": {
          "id": "dfareporting.floodlightActivityGroups.patch",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "PATCH"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "list": {
          "id": "dfareporting.creativeFieldValues.list",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing creative field value.",
          "id": "dfareporting.creativeFieldValues.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "id": "dfareporting.creativeFieldValues.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        },
        "delete": {
          "id": "dfareporting.creativeFieldValues.delete",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "description": "Deletes an existing creative field value.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE"
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative field value by ID.",
          "id": "dfareporting.creativeFieldValues.get"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.insert",
          "description": "Inserts a new creative field value.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "update": {
          "id": "dfareporting.dynamicProfiles.update",
          "description": "Updates an existing dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicProfiles",
          "path": "studio/dynamicProfiles",
          "httpMethod": "PUT"
        },
        "publish": {
          "id": "dfareporting.dynamicProfiles.publish",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "description": "Publish for a dynamic profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "httpMethod": "POST"
        },
        "generateCode": {
          "httpMethod": "GET",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "id": "dfareporting.dynamicProfiles.generateCode"
        },
        "get": {
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "httpMethod": "GET",
          "id": "dfareporting.dynamicProfiles.get",
          "description": "Gets a dynamic profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "path": "studio/dynamicProfiles",
          "flatPath": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new dynamic profile.",
          "id": "dfareporting.dynamicProfiles.insert"
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new studio creative asset.",
          "id": "dfareporting.studioCreativeAssets.insert",
          "httpMethod": "POST",
          "path": "studio/creativeAssets",
          "flatPath": "studio/creativeAssets",
          "supportsMediaUpload": true
        }
      }
    },
    "videoFormats": {
      "methods": {
        "list": {
          "description": "Lists available video formats.",
          "id": "dfareporting.videoFormats.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/videoFormats"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one video format by ID.",
          "id": "dfareporting.videoFormats.get",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/metros",
          "description": "Retrieves a list of metros.",
          "id": "dfareporting.metros.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystemVersions.list",
          "description": "Retrieves a list of operating system versions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system version by ID.",
          "id": "dfareporting.operatingSystemVersions.get"
        }
      }
    },
    "placements": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.patch",
          "description": "Updates an existing placement. This method supports patch semantics."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.placements.list",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement.",
          "id": "dfareporting.placements.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/placements",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "get": {
          "id": "dfareporting.placements.get",
          "description": "Gets one placement by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "httpMethod": "GET"
        },
        "insert": {
          "id": "dfareporting.placements.insert",
          "description": "Inserts a new placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "POST"
        },
        "generatetags": {
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "description": "Generates tags for a placement.",
          "id": "dfareporting.placements.generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creatives": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "id": "dfareporting.creatives.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creatives",
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        },
        "update": {
          "id": "dfareporting.creatives.update",
          "description": "Updates an existing creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PUT"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.patch",
          "description": "Updates an existing creative. This method supports patch semantics."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.get",
          "description": "Gets one creative by ID.",
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/creatives",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creatives.insert",
          "description": "Inserts a new creative."
        }
      }
    },
    "advertisers": {
      "methods": {
        "get": {
          "description": "Gets one advertiser by ID.",
          "id": "dfareporting.advertisers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertisers/{+id}"
        },
        "insert": {
          "id": "dfareporting.advertisers.insert",
          "description": "Inserts a new advertiser.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "POST"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "id": "dfareporting.advertisers.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers"
        },
        "list": {
          "path": "userprofiles/{+profileId}/advertisers",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertisers.list",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging."
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/advertisers",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser.",
          "id": "dfareporting.advertisers.update"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "insert": {
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations"
        },
        "list": {
          "id": "dfareporting.campaignCreativeAssociations.list",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "httpMethod": "GET"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.targetableRemarketingLists.get",
          "description": "Gets one remarketing list by ID.",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.targetableRemarketingLists.list"
        }
      }
    },
    "reports": {
      "methods": {
        "delete": {
          "description": "Deletes a report by its ID.",
          "id": "dfareporting.reports.delete",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.get",
          "description": "Retrieves a report by its ID.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.insert",
          "description": "Creates a report.",
          "path": "userprofiles/{profileId}/reports",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/reports",
          "flatPath": "userprofiles/{profileId}/reports",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves list of reports.",
          "id": "dfareporting.reports.list"
        },
        "update": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.reports.update",
          "description": "Updates a report."
        },
        "run": {
          "id": "dfareporting.reports.run",
          "description": "Runs a report.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "httpMethod": "POST"
        },
        "patch": {
          "description": "Updates an existing report. This method supports patch semantics.",
          "id": "dfareporting.reports.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "httpMethod": "PATCH",
          "path": "userprofiles/{profileId}/reports/{reportId}"
        }
      },
      "resources": {
        "files": {
          "methods": {
            "get": {
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET",
              "id": "dfareporting.reports.files.get",
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "supportsMediaDownload": true,
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Lists files for a report.",
              "id": "dfareporting.reports.files.list"
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "id": "dfareporting.reports.compatibleFields.query",
              "httpMethod": "POST",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "update": {
          "path": "studio/dynamicFeeds",
          "httpMethod": "PUT",
          "flatPath": "studio/dynamicFeeds",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicFeeds.update",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored."
        },
        "get": {
          "httpMethod": "GET",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a dynamic feed by ID.",
          "id": "dfareporting.dynamicFeeds.get"
        },
        "insert": {
          "path": "studio/dynamicFeeds",
          "httpMethod": "POST",
          "flatPath": "studio/dynamicFeeds",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicFeeds.insert",
          "description": "Inserts a new dynamic feed."
        },
        "retransform": {
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicFeeds.retransform",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/postalCodes",
          "description": "Retrieves a list of postal codes.",
          "id": "dfareporting.postalCodes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one postal code by ID.",
          "id": "dfareporting.postalCodes.get"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "list": {
          "id": "dfareporting.mobileApps.list",
          "description": "Retrieves list of available mobile apps.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileApps",
          "path": "userprofiles/{+profileId}/mobileApps",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileApps.get",
          "description": "Gets one mobile app by ID.",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "description": "Gets one mobile carrier by ID.",
          "id": "dfareporting.mobileCarriers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.mobileCarriers.list",
          "description": "Retrieves a list of mobile carriers."
        }
      }
    },
    "campaigns": {
      "methods": {
        "get": {
          "description": "Gets one campaign by ID.",
          "id": "dfareporting.campaigns.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/campaigns/{+id}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/campaigns",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new campaign.",
          "id": "dfareporting.campaigns.insert"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "id": "dfareporting.campaigns.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "id": "dfareporting.campaigns.list",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign.",
          "id": "dfareporting.campaigns.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userRoles": {
      "methods": {
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "description": "Deletes an existing user role.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "DELETE"
        },
        "get": {
          "description": "Gets one user role by ID.",
          "id": "dfareporting.userRoles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRoles/{+id}"
        },
        "insert": {
          "description": "Inserts a new user role.",
          "id": "dfareporting.userRoles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/userRoles"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "PATCH",
          "id": "dfareporting.userRoles.patch",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "httpMethod": "GET",
          "id": "dfareporting.userRoles.list",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Updates an existing user role.",
          "id": "dfareporting.userRoles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of change logs. This method supports paging.",
          "id": "dfareporting.changeLogs.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/changeLogs",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.changeLogs.get",
          "description": "Gets one change log by ID.",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/regions",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of regions.",
          "id": "dfareporting.regions.list"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of connection types.",
          "id": "dfareporting.connectionTypes.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/connectionTypes",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "description": "Gets one connection type by ID.",
          "id": "dfareporting.connectionTypes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeGroups.list",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group.",
          "id": "dfareporting.creativeGroups.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "id": "dfareporting.creativeGroups.patch"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.creativeGroups.get",
          "description": "Gets one creative group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new creative group.",
          "id": "dfareporting.creativeGroups.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "supportsMediaDownload": true,
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "id": "dfareporting.files.get",
          "httpMethod": "GET",
          "path": "reports/{reportId}/files/{fileId}",
          "flatPath": "reports/{reportId}/files/{fileId}"
        },
        "list": {
          "path": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/files",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "id": "dfareporting.files.list",
          "description": "Lists files for a user profile."
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "id": "dfareporting.cities.list",
          "description": "Retrieves a list of cities, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "path": "userprofiles/{+profileId}/cities",
          "httpMethod": "GET"
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one landing page by ID.",
          "id": "dfareporting.advertiserLandingPages.get"
        },
        "insert": {
          "id": "dfareporting.advertiserLandingPages.insert",
          "description": "Inserts a new landing page.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserLandingPages.list",
          "description": "Retrieves a list of landing pages.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "update": {
          "description": "Updates an existing landing page.",
          "id": "dfareporting.advertiserLandingPages.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/advertiserLandingPages"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "id": "dfareporting.advertiserLandingPages.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "description": "Inserts a new creative asset.",
          "id": "dfareporting.creativeAssets.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "id": "dfareporting.floodlightConfigurations.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one floodlight configuration by ID.",
          "id": "dfareporting.floodlightConfigurations.get",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.floodlightConfigurations.list",
          "description": "Retrieves a list of floodlight configurations, possibly filtered."
        },
        "update": {
          "id": "dfareporting.floodlightConfigurations.update",
          "description": "Updates an existing floodlight configuration.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "httpMethod": "PUT"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one remarketing list share by remarketing list ID.",
          "id": "dfareporting.remarketingListShares.get",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}"
        },
        "update": {
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.update",
          "description": "Updates an existing remarketing list share."
        },
        "patch": {
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.remarketingListShares.patch",
          "description": "Updates an existing remarketing list share. This method supports patch semantics."
        }
      }
    },
    "orders": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.orders.list",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders"
        },
        "get": {
          "description": "Gets one order by ID.",
          "id": "dfareporting.orders.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders/{ordersId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders/{+id}"
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.platformTypes.get",
          "description": "Gets one platform type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/platformTypes",
          "description": "Retrieves a list of platform types.",
          "id": "dfareporting.platformTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of user role permissions, possibly filtered.",
          "id": "dfareporting.userRolePermissions.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "description": "Gets one user role permission by ID.",
          "id": "dfareporting.userRolePermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role permission group by ID.",
          "id": "dfareporting.userRolePermissionGroups.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRolePermissionGroups.list",
          "description": "Gets a list of all supported user role permission groups.",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups"
        }
      }
    },
    "eventTags": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of event tags, possibly filtered.",
          "id": "dfareporting.eventTags.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/eventTags",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "update": {
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.update",
          "description": "Updates an existing event tag."
        },
        "patch": {
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.patch",
          "description": "Updates an existing event tag. This method supports patch semantics."
        },
        "delete": {
          "description": "Deletes an existing event tag.",
          "id": "dfareporting.eventTags.delete",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one event tag by ID.",
          "id": "dfareporting.eventTags.get"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.insert",
          "description": "Inserts a new event tag.",
          "path": "userprofiles/{+profileId}/eventTags",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "description": "Gets one operating system by DART ID.",
          "id": "dfareporting.operatingSystems.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of operating systems.",
          "id": "dfareporting.operatingSystems.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystems",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems"
        }
      }
    },
    "ads": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/ads",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad. This method supports patch semantics.",
          "id": "dfareporting.ads.patch"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "GET",
          "id": "dfareporting.ads.list",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.ads.update",
          "description": "Updates an existing ad."
        },
        "get": {
          "id": "dfareporting.ads.get",
          "description": "Gets one ad by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/ads",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new ad.",
          "id": "dfareporting.ads.insert"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.list",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.billingProfiles.update",
          "description": "Updates an existing billing profile.",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "description": "Gets one billing profile by ID.",
          "id": "dfareporting.billingProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "subaccounts": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one subaccount by ID.",
          "id": "dfareporting.subaccounts.get"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "POST",
          "id": "dfareporting.subaccounts.insert",
          "description": "Inserts a new subaccount.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.list",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing subaccount.",
          "id": "dfareporting.subaccounts.update",
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/subaccounts",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.subaccounts.patch",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/subaccounts",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "id": "dfareporting.billingRates.list"
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "id": "dfareporting.countries.get",
          "description": "Gets one country by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.countries.list",
          "description": "Retrieves a list of countries.",
          "path": "userprofiles/{+profileId}/countries",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/countries"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.get",
          "description": "Gets one account permission by ID."
        },
        "list": {
          "path": "userprofiles/{+profileId}/accountPermissions",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountPermissions.list",
          "description": "Retrieves the list of account permissions."
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.directorySites.get",
          "description": "Gets one directory site by ID."
        },
        "insert": {
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/directorySites",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new directory site.",
          "id": "dfareporting.directorySites.insert"
        },
        "list": {
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/directorySites",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "id": "dfareporting.directorySites.list"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys"
        },
        "delete": {
          "description": "Deletes an existing dynamic targeting key.",
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of dynamic targeting keys.",
          "id": "dfareporting.dynamicTargetingKeys.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "description": "Retrieves a list of languages.",
          "id": "dfareporting.languages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/languages"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "description": "Gets one account user profile by ID.",
          "id": "dfareporting.accountUserProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new account user profile.",
          "id": "dfareporting.accountUserProfiles.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        },
        "list": {
          "id": "dfareporting.accountUserProfiles.list",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.accountUserProfiles.update",
          "description": "Updates an existing account user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "PUT"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.accountUserProfiles.patch",
          "description": "Updates an existing account user profile. This method supports patch semantics."
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves list of report dimension values for a list of filters.",
          "id": "dfareporting.dimensionValues.query"
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.studioCreatives.get",
          "description": "Gets a studio creative by ID.",
          "path": "studio/creatives/{+studioCreativeId}",
          "httpMethod": "GET",
          "flatPath": "studio/creatives/{creativesId}"
        },
        "insert": {
          "path": "studio/creatives",
          "httpMethod": "POST",
          "flatPath": "studio/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.studioCreatives.insert",
          "description": "Inserts a new studio creative."
        },
        "publish": {
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "id": "dfareporting.studioCreatives.publish",
          "flatPath": "studio/creatives/{creativesId}/publish",
          "description": "Publish for a studio creative."
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "description": "Retrieves a list of TV campaign summaries.",
          "id": "dfareporting.tvCampaignSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingLists.get",
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new remarketing list.",
          "id": "dfareporting.remarketingLists.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/remarketingLists"
        },
        "patch": {
          "id": "dfareporting.remarketingLists.patch",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "httpMethod": "PATCH"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "id": "dfareporting.remarketingLists.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list.",
          "id": "dfareporting.remarketingLists.update"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "id": "dfareporting.advertiserInvoices.list",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices",
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "httpMethod": "GET"
        }
      }
    },
    "sites": {
      "methods": {
        "get": {
          "id": "dfareporting.sites.get",
          "description": "Gets one site by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}",
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "httpMethod": "GET"
        },
        "insert": {
          "id": "dfareporting.sites.insert",
          "description": "Inserts a new site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/sites",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "id": "dfareporting.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.sites.update",
          "description": "Updates an existing site.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PUT"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "httpMethod": "PATCH",
          "id": "dfareporting.sites.patch",
          "description": "Updates an existing site. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    }
  },
  "protocol": "rest",
  "ownerDomain": "google.com",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "basePath": "/dfareporting/v4/",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360."
}