{
  "discoveryVersion": "v1",
  "protocol": "rest",
  "ownerName": "Google",
  "resources": {
    "platformTypes": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.platformTypes.list",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/platformTypes",
          "description": "Retrieves a list of platform types."
        },
        "get": {
          "id": "dfareporting.platformTypes.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "description": "Gets one platform type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/platformTypes/{+id}"
        }
      }
    },
    "userProfiles": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{profileId}",
          "httpMethod": "GET",
          "id": "dfareporting.userProfiles.get",
          "path": "userprofiles/{profileId}",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user profile by ID."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles",
          "description": "Retrieves list of user profiles for a user.",
          "id": "dfareporting.userProfiles.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles"
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "description": "Gets one user role permission group by ID.",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}",
          "id": "dfareporting.userRolePermissionGroups.get",
          "httpMethod": "GET"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups",
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissionGroups.list",
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets a list of all supported user role permission groups."
        }
      }
    },
    "eventTags": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "description": "Gets one event tag by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.eventTags.get",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of event tags, possibly filtered."
        },
        "update": {
          "id": "dfareporting.eventTags.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Updates an existing event tag."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "id": "dfareporting.eventTags.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.eventTags.insert",
          "flatPath": "userprofiles/{userprofilesId}/eventTags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Inserts a new event tag."
        },
        "delete": {
          "description": "Deletes an existing event tag.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.eventTags.delete"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightConfigurations.get",
          "description": "Gets one floodlight configuration by ID.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "description": "Retrieves a list of floodlight configurations, possibly filtered.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightConfigurations.list"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.update",
          "httpMethod": "PUT",
          "description": "Updates an existing floodlight configuration.",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.floodlightConfigurations.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/postalCodes",
          "id": "dfareporting.postalCodes.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of postal codes.",
          "path": "userprofiles/{+profileId}/postalCodes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one postal code by ID.",
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}",
          "id": "dfareporting.postalCodes.get",
          "httpMethod": "GET"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new account user profile.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.insert",
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "id": "dfareporting.accountUserProfiles.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        },
        "update": {
          "id": "dfareporting.accountUserProfiles.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "description": "Updates an existing account user profile.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles"
        },
        "patch": {
          "description": "Updates an existing account user profile. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "id": "dfareporting.accountUserProfiles.patch",
          "httpMethod": "PATCH"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "description": "Gets one account user profile by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.accountUserProfiles.get",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}"
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "list": {
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivityGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.floodlightActivityGroups.update",
          "description": "Updates an existing floodlight activity group.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivityGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics."
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "id": "dfareporting.floodlightActivityGroups.get",
          "httpMethod": "GET",
          "description": "Gets one floodlight activity group by ID.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new floodlight activity group.",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "httpMethod": "POST"
        }
      }
    },
    "advertisers": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.insert",
          "httpMethod": "POST",
          "description": "Inserts a new advertiser.",
          "path": "userprofiles/{+profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.advertisers.list",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers"
        },
        "update": {
          "description": "Updates an existing advertiser.",
          "path": "userprofiles/{+profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.update",
          "httpMethod": "PUT"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "id": "dfareporting.advertisers.patch",
          "httpMethod": "PATCH"
        },
        "get": {
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one advertiser by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}",
          "httpMethod": "GET",
          "id": "dfareporting.advertisers.get"
        }
      }
    },
    "countries": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/countries",
          "description": "Retrieves a list of countries.",
          "id": "dfareporting.countries.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/countries"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}",
          "httpMethod": "GET",
          "id": "dfareporting.countries.get",
          "description": "Gets one country by ID.",
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "creatives": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.creatives.list",
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        },
        "update": {
          "description": "Updates an existing creative.",
          "path": "userprofiles/{+profileId}/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "id": "dfareporting.creatives.update",
          "httpMethod": "PUT"
        },
        "patch": {
          "description": "Updates an existing creative. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "id": "dfareporting.creatives.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        },
        "get": {
          "description": "Gets one creative by ID.",
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}",
          "id": "dfareporting.creatives.get",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.creatives.insert",
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "description": "Inserts a new creative.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "id": "dfareporting.dimensionValues.query",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging."
        },
        "insert": {
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already."
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "id": "dfareporting.targetableRemarketingLists.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "description": "Gets one remarketing list by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "id": "dfareporting.targetableRemarketingLists.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}"
        }
      }
    },
    "mobileApps": {
      "methods": {
        "list": {
          "description": "Retrieves list of available mobile apps.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileApps",
          "id": "dfareporting.mobileApps.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps"
        },
        "get": {
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one mobile app by ID.",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "httpMethod": "GET",
          "id": "dfareporting.mobileApps.get"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "list": {
          "description": "Gets a list of user role permissions, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissions.list",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions"
        },
        "get": {
          "description": "Gets one user role permission by ID.",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "id": "dfareporting.userRolePermissions.get",
          "httpMethod": "GET"
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/cities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of cities, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/cities",
          "id": "dfareporting.cities.list",
          "httpMethod": "GET"
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "description": "Gets the account's active ad summary by account ID.",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "httpMethod": "GET",
          "id": "dfareporting.accountActiveAdSummaries.get"
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "description": "Retrieves a list of TV campaign summaries.",
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries",
          "id": "dfareporting.tvCampaignSummaries.list",
          "httpMethod": "GET"
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "list": {
          "description": "Retrieves a list of connection types.",
          "path": "userprofiles/{+profileId}/connectionTypes",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "id": "dfareporting.connectionTypes.list",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.connectionTypes.get",
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}",
          "description": "Gets one connection type by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}"
        }
      }
    },
    "creativeFields": {
      "methods": {
        "get": {
          "description": "Gets one creative field by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFields.get",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}"
        },
        "list": {
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFields.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "update": {
          "description": "Updates an existing creative field.",
          "path": "userprofiles/{+profileId}/creativeFields",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "id": "dfareporting.creativeFields.update",
          "httpMethod": "PUT"
        },
        "patch": {
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeFields.patch",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "insert": {
          "description": "Inserts a new creative field.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "id": "dfareporting.creativeFields.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "delete": {
          "description": "Deletes an existing creative field.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFields.delete"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "list": {
          "description": "Retrieves a list of operating systems.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystems",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystems.list",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems"
        },
        "get": {
          "id": "dfareporting.operatingSystems.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "description": "Gets one operating system by DART ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.billingRates.list",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates",
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates"
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "id": "dfareporting.remarketingLists.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing remarketing list. This method supports patch semantics."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingLists.list",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "description": "Updates an existing remarketing list.",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "httpMethod": "PUT",
          "id": "dfareporting.remarketingLists.update"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingLists.get",
          "description": "Gets one remarketing list by ID.",
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "description": "Inserts a new remarketing list.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists",
          "id": "dfareporting.remarketingLists.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "description": "Inserts conversions.",
          "id": "dfareporting.conversions.batchinsert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert"
        },
        "batchupdate": {
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "description": "Updates existing conversions.",
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate",
          "httpMethod": "POST",
          "id": "dfareporting.conversions.batchupdate"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "description": "Inserts a new creative asset.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "supportsMediaUpload": true,
          "id": "dfareporting.creativeAssets.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets"
        }
      }
    },
    "placementGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.get",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}",
          "description": "Gets one placement group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups/{+id}"
        },
        "patch": {
          "id": "dfareporting.placementGroups.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups"
        },
        "list": {
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "id": "dfareporting.placementGroups.list",
          "httpMethod": "GET"
        },
        "update": {
          "path": "userprofiles/{+profileId}/placementGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing placement group.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.placementGroups.update"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.placementGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "description": "Inserts a new placement group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "id": "dfareporting.regions.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "description": "Retrieves a list of regions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/regions"
        }
      }
    },
    "projects": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/projects/{+id}",
          "description": "Gets one project by ID.",
          "id": "dfareporting.projects.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectsId}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/projects",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of projects, possibly filtered. This method supports paging .",
          "flatPath": "userprofiles/{userprofilesId}/projects",
          "id": "dfareporting.projects.list",
          "httpMethod": "GET"
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles",
          "description": "Inserts a new dynamic profile.",
          "id": "dfareporting.dynamicProfiles.insert",
          "httpMethod": "POST",
          "flatPath": "studio/dynamicProfiles"
        },
        "publish": {
          "id": "dfareporting.dynamicProfiles.publish",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "description": "Publish for a dynamic profile."
        },
        "get": {
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}",
          "httpMethod": "GET",
          "id": "dfareporting.dynamicProfiles.get",
          "description": "Gets a dynamic profile by ID.",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "generateCode": {
          "httpMethod": "GET",
          "id": "dfareporting.dynamicProfiles.generateCode",
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "description": "Generates code for a dynamic profile, which will need unescaping.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode"
        },
        "update": {
          "id": "dfareporting.dynamicProfiles.update",
          "httpMethod": "PUT",
          "flatPath": "studio/dynamicProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicProfiles",
          "description": "Updates an existing dynamic profile."
        }
      }
    },
    "changeLogs": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.changeLogs.list",
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/changeLogs",
          "description": "Retrieves a list of change logs. This method supports paging."
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "httpMethod": "GET",
          "id": "dfareporting.changeLogs.get",
          "description": "Gets one change log by ID.",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "get": {
          "id": "dfareporting.dynamicFeeds.get",
          "httpMethod": "GET",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "description": "Gets a dynamic feed by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds/{+dynamicFeedId}"
        },
        "insert": {
          "description": "Inserts a new dynamic feed.",
          "path": "studio/dynamicFeeds",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicFeeds",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicFeeds.insert"
        },
        "retransform": {
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicFeeds.retransform",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published)."
        },
        "update": {
          "id": "dfareporting.dynamicFeeds.update",
          "httpMethod": "PUT",
          "flatPath": "studio/dynamicFeeds",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored."
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "description": "Gets one TvCampaignDetail by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.tvCampaignDetails.get",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}"
        }
      }
    },
    "orders": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders",
          "id": "dfareporting.orders.list",
          "httpMethod": "GET",
          "description": "Retrieves a list of orders, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/orders/{ordersId}",
          "id": "dfareporting.orders.get",
          "httpMethod": "GET",
          "description": "Gets one order by ID.",
          "path": "userprofiles/{+profileId}/projects/{projectId}/orders/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "description": "Retrieves a list of languages.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/languages",
          "httpMethod": "GET",
          "id": "dfareporting.languages.list",
          "flatPath": "userprofiles/{userprofilesId}/languages"
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "publish": {
          "description": "Publish for a studio creative.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.studioCreatives.publish",
          "flatPath": "studio/creatives/{creativesId}/publish",
          "path": "studio/creatives/{+studioCreativeId}/publish"
        },
        "get": {
          "id": "dfareporting.studioCreatives.get",
          "httpMethod": "GET",
          "flatPath": "studio/creatives/{creativesId}",
          "description": "Gets a studio creative by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creatives/{+studioCreativeId}"
        },
        "insert": {
          "description": "Inserts a new studio creative.",
          "path": "studio/creatives",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/creatives",
          "httpMethod": "POST",
          "id": "dfareporting.studioCreatives.insert"
        }
      }
    },
    "reports": {
      "methods": {
        "run": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run",
          "id": "dfareporting.reports.run",
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Runs a report."
        },
        "delete": {
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Deletes a report by its ID."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports",
          "description": "Creates a report.",
          "id": "dfareporting.reports.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports"
        },
        "list": {
          "id": "dfareporting.reports.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{profileId}/reports",
          "description": "Retrieves list of reports.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.update",
          "httpMethod": "PUT",
          "description": "Updates a report.",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "patch": {
          "description": "Updates an existing report. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "get": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "id": "dfareporting.reports.get",
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "description": "Retrieves a report by its ID."
        }
      },
      "resources": {
        "files": {
          "methods": {
            "get": {
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "httpMethod": "GET",
              "id": "dfareporting.reports.files.get",
              "supportsMediaDownload": true,
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "id": "dfareporting.reports.files.list",
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "description": "Lists files for a report.",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "path": "userprofiles/{profileId}/reports/{reportId}/files"
            }
          }
        },
        "compatibleFields": {
          "methods": {
            "query": {
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query",
              "httpMethod": "POST",
              "id": "dfareporting.reports.compatibleFields.query",
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions."
            }
          }
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "insert": {
          "id": "dfareporting.placementStrategies.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "description": "Inserts a new placement strategy.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies"
        },
        "delete": {
          "description": "Deletes an existing placement strategy.",
          "id": "dfareporting.placementStrategies.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}"
        },
        "get": {
          "description": "Gets one placement strategy by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "id": "dfareporting.placementStrategies.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}"
        },
        "patch": {
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "id": "dfareporting.placementStrategies.patch",
          "httpMethod": "PATCH"
        },
        "list": {
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "GET",
          "id": "dfareporting.placementStrategies.list"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "PUT",
          "id": "dfareporting.placementStrategies.update",
          "description": "Updates an existing placement strategy.",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "campaigns": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Inserts a new campaign.",
          "id": "dfareporting.campaigns.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.campaigns.get",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}",
          "description": "Gets one campaign by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+id}"
        },
        "list": {
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "httpMethod": "GET",
          "id": "dfareporting.campaigns.list",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.campaigns.update",
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "httpMethod": "PATCH",
          "id": "dfareporting.campaigns.patch",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/campaigns",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "description": "Retrieves a list of operating system versions.",
          "id": "dfareporting.operatingSystemVersions.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystemVersions.get",
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one operating system version by ID."
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "insert": {
          "description": "Inserts a new creative group.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "POST",
          "id": "dfareporting.creativeGroups.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "get": {
          "description": "Gets one creative group by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "id": "dfareporting.creativeGroups.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}"
        },
        "list": {
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "httpMethod": "GET",
          "id": "dfareporting.creativeGroups.list",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeGroups.update",
          "description": "Updates an existing creative group.",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "id": "dfareporting.advertiserInvoices.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices"
        }
      }
    },
    "inventoryItems": {
      "methods": {
        "list": {
          "description": "Retrieves a list of inventory items, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems",
          "httpMethod": "GET",
          "id": "dfareporting.inventoryItems.list"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/projects/{projectId}/inventoryItems/{inventoryItemsId}",
          "id": "dfareporting.inventoryItems.get",
          "httpMethod": "GET",
          "description": "Gets one inventory item by ID.",
          "path": "userprofiles/{+profileId}/projects/{projectId}/inventoryItems/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "flatPath": "reports/{reportId}/files/{fileId}",
          "httpMethod": "GET",
          "id": "dfareporting.files.get",
          "supportsMediaDownload": true,
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "path": "reports/{reportId}/files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "id": "dfareporting.files.list",
          "description": "Lists files for a user profile.",
          "path": "userprofiles/{profileId}/files",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ]
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Retrieves a list of landing pages.",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserLandingPages.list",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.update",
          "httpMethod": "PUT",
          "description": "Updates an existing landing page.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.advertiserLandingPages.patch",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page. This method supports patch semantics."
        },
        "get": {
          "id": "dfareporting.advertiserLandingPages.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}",
          "description": "Gets one landing page by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}"
        },
        "insert": {
          "description": "Inserts a new landing page.",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "id": "dfareporting.advertiserLandingPages.insert",
          "httpMethod": "POST"
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissions.get",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "description": "Gets one account permission by ID."
        },
        "list": {
          "description": "Retrieves the list of account permissions.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissions",
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissions.list",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "POST",
          "id": "dfareporting.advertiserGroups.insert"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.advertiserGroups.delete",
          "description": "Deletes an existing advertiser group."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "description": "Gets one advertiser group by ID.",
          "id": "dfareporting.advertiserGroups.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.advertiserGroups.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "update": {
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "httpMethod": "PUT",
          "id": "dfareporting.advertiserGroups.update"
        },
        "patch": {
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "httpMethod": "PATCH",
          "id": "dfareporting.advertiserGroups.patch",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/metros",
          "description": "Retrieves a list of metros.",
          "id": "dfareporting.metros.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/metros"
        }
      }
    },
    "subaccounts": {
      "methods": {
        "insert": {
          "id": "dfareporting.subaccounts.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Inserts a new subaccount."
        },
        "patch": {
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "id": "dfareporting.subaccounts.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "list": {
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.list"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.subaccounts.update",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Updates an existing subaccount."
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}",
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.get",
          "description": "Gets one subaccount by ID.",
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "description": "Gets one directory site by ID.",
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "httpMethod": "GET",
          "id": "dfareporting.directorySites.get"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.directorySites.insert",
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Inserts a new directory site."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.directorySites.list",
          "flatPath": "userprofiles/{userprofilesId}/directorySites"
        }
      }
    },
    "placements": {
      "methods": {
        "insert": {
          "id": "dfareporting.placements.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "description": "Inserts a new placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements"
        },
        "generatetags": {
          "description": "Generates tags for a placement.",
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "id": "dfareporting.placements.generatetags",
          "httpMethod": "POST"
        },
        "get": {
          "description": "Gets one placement by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "id": "dfareporting.placements.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}"
        },
        "patch": {
          "description": "Updates an existing placement. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "PATCH",
          "id": "dfareporting.placements.patch"
        },
        "list": {
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/placements",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "httpMethod": "GET",
          "id": "dfareporting.placements.list"
        },
        "update": {
          "description": "Updates an existing placement.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements",
          "httpMethod": "PUT",
          "id": "dfareporting.placements.update",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        }
      }
    },
    "ads": {
      "methods": {
        "insert": {
          "description": "Inserts a new ad.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "httpMethod": "POST",
          "id": "dfareporting.ads.insert",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        },
        "get": {
          "id": "dfareporting.ads.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "description": "Gets one ad by ID."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "GET",
          "id": "dfareporting.ads.list",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "httpMethod": "PUT",
          "id": "dfareporting.ads.update",
          "path": "userprofiles/{+profileId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing ad."
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.ads.patch",
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/ads",
          "description": "Updates an existing ad. This method supports patch semantics."
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "description": "Gets one video format by ID.",
          "id": "dfareporting.videoFormats.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}"
        },
        "list": {
          "description": "Lists available video formats.",
          "path": "userprofiles/{+profileId}/videoFormats",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/videoFormats",
          "id": "dfareporting.videoFormats.list",
          "httpMethod": "GET"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves the list of account permission groups.",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups",
          "id": "dfareporting.accountPermissionGroups.list",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "description": "Gets one account permission group by ID.",
          "id": "dfareporting.accountPermissionGroups.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}"
        }
      }
    },
    "accounts": {
      "methods": {
        "list": {
          "id": "dfareporting.accounts.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging."
        },
        "update": {
          "description": "Updates an existing account.",
          "path": "userprofiles/{+profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "id": "dfareporting.accounts.update",
          "httpMethod": "PUT"
        },
        "patch": {
          "description": "Updates an existing account. This method supports patch semantics.",
          "path": "userprofiles/{+profileId}/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "PATCH",
          "id": "dfareporting.accounts.patch"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "id": "dfareporting.accounts.get",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one account by ID."
        }
      }
    },
    "contentCategories": {
      "methods": {
        "delete": {
          "description": "Deletes an existing content category.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.contentCategories.delete",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.contentCategories.insert",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "description": "Inserts a new content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.contentCategories.list",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories"
        },
        "update": {
          "description": "Updates an existing content category.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "id": "dfareporting.contentCategories.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "patch": {
          "description": "Updates an existing content category. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "id": "dfareporting.contentCategories.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}",
          "id": "dfareporting.contentCategories.get",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one content category by ID."
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "id": "dfareporting.billingAssignments.insert",
          "httpMethod": "POST",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "description": "Retrieves a list of billing assignments.",
          "httpMethod": "GET",
          "id": "dfareporting.billingAssignments.list",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "httpMethod": "GET",
          "id": "dfareporting.mobileCarriers.list",
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of mobile carriers."
        },
        "get": {
          "description": "Gets one mobile carrier by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "id": "dfareporting.mobileCarriers.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}"
        }
      }
    },
    "sites": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "id": "dfareporting.sites.insert",
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new site."
        },
        "patch": {
          "id": "dfareporting.sites.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "description": "Updates an existing site. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites"
        },
        "list": {
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "id": "dfareporting.sites.list",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates an existing site.",
          "path": "userprofiles/{+profileId}/sites",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "id": "dfareporting.sites.update",
          "httpMethod": "PUT"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "description": "Gets one site by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.sites.get",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}"
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "description": "Gets one billing profile by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "id": "dfareporting.billingProfiles.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "id": "dfareporting.billingProfiles.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging."
        },
        "update": {
          "path": "userprofiles/{+profileId}/billingProfiles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing billing profile.",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "id": "dfareporting.billingProfiles.update",
          "httpMethod": "PUT"
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one size by ID.",
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}",
          "id": "dfareporting.sizes.get",
          "httpMethod": "GET"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes",
          "description": "Inserts a new size.",
          "id": "dfareporting.sizes.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/sizes"
        },
        "list": {
          "id": "dfareporting.sizes.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.creativeFieldValues.insert",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "description": "Inserts a new creative field value.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.creativeFieldValues.delete",
          "description": "Deletes an existing creative field value."
        },
        "get": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one creative field value by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "id": "dfareporting.creativeFieldValues.get",
          "httpMethod": "GET"
        },
        "list": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFieldValues.list"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues",
          "id": "dfareporting.creativeFieldValues.update",
          "httpMethod": "PUT",
          "description": "Updates an existing creative field value.",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeFieldValues.patch",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement."
        },
        "delete": {
          "description": "Deletes an existing dynamic targeting key.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.dynamicTargetingKeys.delete"
        },
        "list": {
          "id": "dfareporting.dynamicTargetingKeys.list",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys",
          "description": "Retrieves a list of dynamic targeting keys.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys"
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.remarketingListShares.get",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "description": "Gets one remarketing list share by remarketing list ID."
        },
        "patch": {
          "id": "dfareporting.remarketingListShares.patch",
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.remarketingListShares.update",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares",
          "description": "Updates an existing remarketing list share.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Inserts a new targeting template.",
          "httpMethod": "POST",
          "id": "dfareporting.targetingTemplates.insert",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.patch",
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing targeting template. This method supports patch semantics."
        },
        "list": {
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging.",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "GET",
          "id": "dfareporting.targetingTemplates.list"
        },
        "update": {
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing targeting template.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "PUT",
          "id": "dfareporting.targetingTemplates.update"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "id": "dfareporting.targetingTemplates.get",
          "httpMethod": "GET",
          "description": "Gets one targeting template by ID.",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "description": "Inserts a new studio creative asset.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creativeAssets",
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "id": "dfareporting.studioCreativeAssets.insert",
          "flatPath": "studio/creativeAssets"
        }
      }
    },
    "userRoles": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "POST",
          "id": "dfareporting.userRoles.insert",
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Inserts a new user role."
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "id": "dfareporting.userRoles.delete",
          "description": "Deletes an existing user role."
        },
        "get": {
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Gets one user role by ID.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}",
          "httpMethod": "GET",
          "id": "dfareporting.userRoles.get"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Updates an existing user role. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "httpMethod": "PATCH",
          "id": "dfareporting.userRoles.patch"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.list",
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging."
        },
        "update": {
          "description": "Updates an existing user role.",
          "path": "userprofiles/{+profileId}/userRoles",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.update",
          "httpMethod": "PUT"
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/browsers",
          "description": "Retrieves a list of browsers.",
          "httpMethod": "GET",
          "id": "dfareporting.browsers.list",
          "flatPath": "userprofiles/{userprofilesId}/browsers"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "description": "Gets one floodlight activity by ID.",
          "id": "dfareporting.floodlightActivities.get",
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.list",
          "httpMethod": "GET"
        },
        "update": {
          "id": "dfareporting.floodlightActivities.update",
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "description": "Updates an existing floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivities.patch",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity. This method supports patch semantics."
        },
        "generatetag": {
          "id": "dfareporting.floodlightActivities.generatetag",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "description": "Generates a tag for a floodlight activity."
        },
        "insert": {
          "description": "Inserts a new floodlight activity.",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "id": "dfareporting.floodlightActivities.insert",
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}",
          "id": "dfareporting.floodlightActivities.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "description": "Deletes an existing floodlight activity."
        }
      }
    }
  },
  "revision": "20260310",
  "title": "Campaign Manager 360 API",
  "servicePath": "dfareporting/v4/",
  "basePath": "/dfareporting/v4/",
  "batchPath": "batch",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v4/",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        }
      }
    }
  },
  "canonicalName": "Dfareporting",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "id": "dfareporting:v4",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "kind": "discovery#restDescription",
  "name": "dfareporting",
  "version": "v4"
}