{
  "id": "dfareporting:v5",
  "revision": "20260310",
  "description": "Build applications to efficiently manage large or complex trafficking, reporting, and attribution workflows for Campaign Manager 360.",
  "version": "v5",
  "basePath": "/dfareporting/v5/",
  "name": "dfareporting",
  "rootUrl": "https://dfareporting.googleapis.com/",
  "servicePath": "dfareporting/v5/",
  "ownerDomain": "google.com",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "title": "Campaign Manager 360 API",
  "discoveryVersion": "v1",
  "resources": {
    "placements": {
      "methods": {
        "update": {
          "path": "userprofiles/{+profileId}/placements",
          "description": "Updates an existing placement.",
          "httpMethod": "PUT",
          "id": "dfareporting.placements.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "generatetags": {
          "flatPath": "userprofiles/{userprofilesId}/placements/generatetags",
          "path": "userprofiles/{+profileId}/placements/generatetags",
          "description": "Generates tags for a placement.",
          "httpMethod": "POST",
          "id": "dfareporting.placements.generatetags",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "path": "userprofiles/{+profileId}/placements",
          "description": "Retrieves a list of placements, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.placements.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "id": "dfareporting.placements.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/placements",
          "description": "Updates an existing placement. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/placements"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/placements/{placementsId}",
          "httpMethod": "GET",
          "id": "dfareporting.placements.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placements/{+id}",
          "description": "Gets one placement by ID."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placements",
          "id": "dfareporting.placements.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/placements",
          "description": "Inserts a new placement."
        }
      }
    },
    "placementGroups": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Inserts a new placement group.",
          "id": "dfareporting.placementGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "update": {
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Updates an existing placement group.",
          "id": "dfareporting.placementGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Retrieves a list of placement groups, possibly filtered. This method supports paging."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/placementGroups",
          "path": "userprofiles/{+profileId}/placementGroups",
          "description": "Updates an existing placement group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.placementGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.placementGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementGroups/{+id}",
          "description": "Gets one placement group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/placementGroups/{placementGroupsId}"
        }
      }
    },
    "sites": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "description": "Updates an existing site. This method supports patch semantics.",
          "id": "dfareporting.sites.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.sites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sites/{+id}",
          "description": "Gets one site by ID.",
          "flatPath": "userprofiles/{userprofilesId}/sites/{sitesId}"
        },
        "list": {
          "id": "dfareporting.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/sites",
          "description": "Retrieves a list of sites, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/sites"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "path": "userprofiles/{+profileId}/sites",
          "description": "Updates an existing site.",
          "id": "dfareporting.sites.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/sites",
          "id": "dfareporting.sites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/sites",
          "description": "Inserts a new site."
        }
      }
    },
    "billingProfiles": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/billingProfiles/{+id}",
          "description": "Gets one billing profile by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.billingProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}"
        },
        "update": {
          "path": "userprofiles/{+profileId}/billingProfiles",
          "description": "Updates an existing billing profile.",
          "httpMethod": "PUT",
          "id": "dfareporting.billingProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles",
          "id": "dfareporting.billingProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/billingProfiles",
          "description": "Retrieves a list of billing profiles, possibly filtered. This method supports paging."
        }
      }
    },
    "countries": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/countries/{+dartId}",
          "description": "Gets one country by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.countries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/countries/{countriesId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/countries",
          "id": "dfareporting.countries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/countries",
          "description": "Retrieves a list of countries."
        }
      }
    },
    "userRolePermissionGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissionGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/userRolePermissionGroups/{+id}",
          "description": "Gets one user role permission group by ID.",
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups/{userRolePermissionGroupsId}"
        },
        "list": {
          "path": "userprofiles/{+profileId}/userRolePermissionGroups",
          "description": "Gets a list of all supported user role permission groups.",
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissionGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissionGroups"
        }
      }
    },
    "creativeAssets": {
      "methods": {
        "insert": {
          "supportsMediaUpload": true,
          "flatPath": "userprofiles/{userprofilesId}/creativeAssets/{creativeAssetsId}/creativeAssets",
          "id": "dfareporting.creativeAssets.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeAssets/{+advertiserId}/creativeAssets",
          "description": "Inserts a new creative asset."
        }
      }
    },
    "campaignCreativeAssociations": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Retrieves the list of creative IDs associated with the specified campaign. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.campaignCreativeAssociations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}/campaignCreativeAssociations",
          "path": "userprofiles/{+profileId}/campaigns/{+campaignId}/campaignCreativeAssociations",
          "description": "Associates a creative with the specified campaign. This method creates a default ad with dimensions matching the creative in the campaign if such a default ad does not exist already.",
          "httpMethod": "POST",
          "id": "dfareporting.campaignCreativeAssociations.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "studioCreativeAssets": {
      "methods": {
        "insert": {
          "id": "dfareporting.studioCreativeAssets.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "studio/creativeAssets",
          "description": "Inserts a new studio creative asset.",
          "supportsMediaUpload": true,
          "flatPath": "studio/creativeAssets"
        }
      }
    },
    "billingAssignments": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments",
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "description": "Retrieves a list of billing assignments.",
          "id": "dfareporting.billingAssignments.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingAssignments",
          "description": "Inserts a new billing assignment and returns the new assignment. Only one of advertiser_id or campaign_id is support per request. If the new assignment has no effect (assigning a campaign to the parent advertiser billing profile or assigning an advertiser to the account billing profile), no assignment will be returned.",
          "id": "dfareporting.billingAssignments.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingAssignments"
        }
      }
    },
    "accountPermissionGroups": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissionGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissionGroups",
          "description": "Retrieves the list of account permission groups.",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountPermissionGroups/{accountPermissionGroupsId}",
          "id": "dfareporting.accountPermissionGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountPermissionGroups/{+id}",
          "description": "Gets one account permission group by ID."
        }
      }
    },
    "cities": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/cities",
          "description": "Retrieves a list of cities, possibly filtered.",
          "httpMethod": "GET",
          "id": "dfareporting.cities.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/cities"
        }
      }
    },
    "mobileCarriers": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/mobileCarriers/{+id}",
          "description": "Gets one mobile carrier by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.mobileCarriers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers/{mobileCarriersId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/mobileCarriers",
          "id": "dfareporting.mobileCarriers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/mobileCarriers",
          "description": "Retrieves a list of mobile carriers."
        }
      }
    },
    "accountPermissions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountPermissions",
          "description": "Retrieves the list of account permissions.",
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions"
        },
        "get": {
          "path": "userprofiles/{+profileId}/accountPermissions/{+id}",
          "description": "Gets one account permission by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.accountPermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accountPermissions/{accountPermissionsId}"
        }
      }
    },
    "creativeFieldValues": {
      "methods": {
        "update": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value.",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFieldValues.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        },
        "list": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Retrieves a list of creative field values, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFieldValues.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        },
        "get": {
          "id": "dfareporting.creativeFieldValues.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "description": "Gets one creative field value by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Updates an existing creative field value. This method supports patch semantics.",
          "id": "dfareporting.creativeFieldValues.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        },
        "insert": {
          "id": "dfareporting.creativeFieldValues.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues",
          "description": "Inserts a new creative field value.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues"
        },
        "delete": {
          "path": "userprofiles/{+profileId}/creativeFields/{+creativeFieldId}/creativeFieldValues/{+id}",
          "description": "Deletes an existing creative field value.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}/creativeFieldValues/{creativeFieldValuesId}",
          "httpMethod": "DELETE",
          "id": "dfareporting.creativeFieldValues.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "advertiserLandingPages": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Inserts a new landing page.",
          "httpMethod": "POST",
          "id": "dfareporting.advertiserLandingPages.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "httpMethod": "PUT",
          "id": "dfareporting.advertiserLandingPages.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Retrieves a list of landing pages.",
          "id": "dfareporting.advertiserLandingPages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "get": {
          "id": "dfareporting.advertiserLandingPages.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserLandingPages/{+id}",
          "description": "Gets one landing page by ID.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages/{advertiserLandingPagesId}"
        },
        "patch": {
          "id": "dfareporting.advertiserLandingPages.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/advertiserLandingPages",
          "description": "Updates an existing landing page. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserLandingPages"
        }
      }
    },
    "targetableRemarketingLists": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists",
          "id": "dfareporting.targetableRemarketingLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists",
          "description": "Retrieves a list of targetable remarketing lists, possibly filtered. This method supports paging."
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/targetableRemarketingLists/{targetableRemarketingListsId}",
          "id": "dfareporting.targetableRemarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetableRemarketingLists/{+id}",
          "description": "Gets one remarketing list by ID."
        }
      }
    },
    "browsers": {
      "methods": {
        "list": {
          "id": "dfareporting.browsers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/browsers",
          "description": "Retrieves a list of browsers.",
          "flatPath": "userprofiles/{userprofilesId}/browsers"
        }
      }
    },
    "floodlightActivities": {
      "methods": {
        "generatetag": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/generatetag",
          "id": "dfareporting.floodlightActivities.generatetag",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/floodlightActivities/generatetag",
          "description": "Generates a tag for a floodlight activity."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities",
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity.",
          "id": "dfareporting.floodlightActivities.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "list": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Retrieves a list of floodlight activities, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivities.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "get": {
          "id": "dfareporting.floodlightActivities.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "description": "Gets one floodlight activity by ID.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Updates an existing floodlight activity. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightActivities.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/floodlightActivities",
          "description": "Inserts a new floodlight activity.",
          "httpMethod": "POST",
          "id": "dfareporting.floodlightActivities.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "dfareporting.floodlightActivities.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivities/{+id}",
          "description": "Deletes an existing floodlight activity.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivities/{floodlightActivitiesId}"
        }
      }
    },
    "operatingSystems": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems/{operatingSystemsId}",
          "id": "dfareporting.operatingSystems.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/operatingSystems/{+dartId}",
          "description": "Gets one operating system by DART ID."
        },
        "list": {
          "path": "userprofiles/{+profileId}/operatingSystems",
          "description": "Retrieves a list of operating systems.",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystems.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/operatingSystems"
        }
      }
    },
    "eventTags": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "description": "Gets one event tag by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.eventTags.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.eventTags.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Updates an existing event tag. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.eventTags.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Updates an existing event tag.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "list": {
          "id": "dfareporting.eventTags.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Retrieves a list of event tags, possibly filtered.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/eventTags/{eventTagsId}",
          "path": "userprofiles/{+profileId}/eventTags/{+id}",
          "description": "Deletes an existing event tag.",
          "httpMethod": "DELETE",
          "id": "dfareporting.eventTags.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.eventTags.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/eventTags",
          "description": "Inserts a new event tag.",
          "flatPath": "userprofiles/{userprofilesId}/eventTags"
        }
      }
    },
    "changeLogs": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/changeLogs/{changeLogsId}",
          "path": "userprofiles/{+profileId}/changeLogs/{+id}",
          "description": "Gets one change log by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.changeLogs.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/changeLogs",
          "path": "userprofiles/{+profileId}/changeLogs",
          "description": "Retrieves a list of change logs. This method supports paging.",
          "id": "dfareporting.changeLogs.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "languages": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/languages",
          "httpMethod": "GET",
          "id": "dfareporting.languages.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/languages",
          "description": "Retrieves a list of languages."
        }
      }
    },
    "advertisers": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Inserts a new advertiser.",
          "httpMethod": "POST",
          "id": "dfareporting.advertisers.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers"
        },
        "get": {
          "path": "userprofiles/{+profileId}/advertisers/{+id}",
          "description": "Gets one advertiser by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.advertisers.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Updates an existing advertiser. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.advertisers.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Updates an existing advertiser.",
          "httpMethod": "PUT",
          "id": "dfareporting.advertisers.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/advertisers",
          "path": "userprofiles/{+profileId}/advertisers",
          "description": "Retrieves a list of advertisers, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.advertisers.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "remarketingListShares": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.remarketingListShares.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        },
        "patch": {
          "id": "dfareporting.remarketingListShares.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/remarketingListShares",
          "description": "Updates an existing remarketing list share. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingListShares/{remarketingListSharesId}",
          "path": "userprofiles/{+profileId}/remarketingListShares/{+remarketingListId}",
          "description": "Gets one remarketing list share by remarketing list ID.",
          "id": "dfareporting.remarketingListShares.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "dynamicTargetingKeys": {
      "methods": {
        "delete": {
          "id": "dfareporting.dynamicTargetingKeys.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys/{+objectId}",
          "description": "Deletes an existing dynamic targeting key.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys/{dynamicTargetingKeysId}"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "description": "Inserts a new dynamic targeting key. Keys must be created at the advertiser level before being assigned to the advertiser's ads, creatives, or placements. There is a maximum of 1000 keys per advertiser, out of which a maximum of 20 keys can be assigned per ad, creative, or placement.",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicTargetingKeys.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys"
        },
        "list": {
          "id": "dfareporting.dynamicTargetingKeys.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/dynamicTargetingKeys",
          "description": "Retrieves a list of dynamic targeting keys.",
          "flatPath": "userprofiles/{userprofilesId}/dynamicTargetingKeys"
        }
      }
    },
    "billingRates": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/billingProfiles/{+billingProfileId}/billingRates",
          "description": "Retrieves a list of billing rates. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.billingRates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/billingProfiles/{billingProfilesId}/billingRates"
        }
      }
    },
    "tvCampaignDetails": {
      "methods": {
        "get": {
          "id": "dfareporting.tvCampaignDetails.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/tvCampaignDetails/{+id}",
          "description": "Gets one TvCampaignDetail by ID.",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignDetails/{tvCampaignDetailsId}"
        }
      }
    },
    "advertiserInvoices": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/advertisers/{+advertiserId}/invoices",
          "description": "Retrieves a list of invoices for a particular issue month. The api only works if the billing profile invoice level is set to either advertiser or campaign non-consolidated invoice level.",
          "id": "dfareporting.advertiserInvoices.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/advertisers/{advertisersId}/invoices"
        }
      }
    },
    "campaigns": {
      "methods": {
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Inserts a new campaign.",
          "id": "dfareporting.campaigns.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.campaigns.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns/{+id}",
          "description": "Gets one campaign by ID.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns/{campaignsId}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.campaigns.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/campaigns"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Updates an existing campaign.",
          "httpMethod": "PUT",
          "id": "dfareporting.campaigns.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/campaigns",
          "path": "userprofiles/{+profileId}/campaigns",
          "description": "Retrieves a list of campaigns, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.campaigns.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "floodlightActivityGroups": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups/{floodlightActivityGroupsId}",
          "httpMethod": "GET",
          "id": "dfareporting.floodlightActivityGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightActivityGroups/{+id}",
          "description": "Gets one floodlight activity group by ID."
        },
        "patch": {
          "id": "dfareporting.floodlightActivityGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups",
          "id": "dfareporting.floodlightActivityGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Updates an existing floodlight activity group."
        },
        "list": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Retrieves a list of floodlight activity groups, possibly filtered. This method supports paging.",
          "id": "dfareporting.floodlightActivityGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        },
        "insert": {
          "path": "userprofiles/{+profileId}/floodlightActivityGroups",
          "description": "Inserts a new floodlight activity group.",
          "id": "dfareporting.floodlightActivityGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{userprofilesId}/floodlightActivityGroups"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "path": "reports/{reportId}/files/{fileId}",
          "supportsMediaDownload": true,
          "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
          "httpMethod": "GET",
          "id": "dfareporting.files.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "reports/{reportId}/files/{fileId}"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/files",
          "httpMethod": "GET",
          "id": "dfareporting.files.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/files",
          "description": "Lists files for a user profile."
        }
      }
    },
    "accountActiveAdSummaries": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accountActiveAdSummaries/{accountActiveAdSummariesId}",
          "id": "dfareporting.accountActiveAdSummaries.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/accountActiveAdSummaries/{+summaryAccountId}",
          "description": "Gets the account's active ad summary by account ID."
        }
      }
    },
    "creativeFields": {
      "methods": {
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields",
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Updates an existing creative field.",
          "httpMethod": "PUT",
          "id": "dfareporting.creativeFields.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Retrieves a list of creative fields, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.creativeFields.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}",
          "id": "dfareporting.creativeFields.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "description": "Gets one creative field by ID."
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.creativeFields.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Updates an existing creative field. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "insert": {
          "id": "dfareporting.creativeFields.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeFields",
          "description": "Inserts a new creative field.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields"
        },
        "delete": {
          "id": "dfareporting.creativeFields.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/creativeFields/{+id}",
          "description": "Deletes an existing creative field.",
          "flatPath": "userprofiles/{userprofilesId}/creativeFields/{creativeFieldsId}"
        }
      }
    },
    "placementStrategies": {
      "methods": {
        "patch": {
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Updates an existing placement strategy. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.placementStrategies.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "httpMethod": "GET",
          "id": "dfareporting.placementStrategies.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "description": "Gets one placement strategy by ID."
        },
        "list": {
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Retrieves a list of placement strategies, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.placementStrategies.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Updates an existing placement strategy.",
          "httpMethod": "PUT",
          "id": "dfareporting.placementStrategies.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "delete": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies/{placementStrategiesId}",
          "path": "userprofiles/{+profileId}/placementStrategies/{+id}",
          "description": "Deletes an existing placement strategy.",
          "httpMethod": "DELETE",
          "id": "dfareporting.placementStrategies.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/placementStrategies",
          "httpMethod": "POST",
          "id": "dfareporting.placementStrategies.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/placementStrategies",
          "description": "Inserts a new placement strategy."
        }
      }
    },
    "userProfiles": {
      "methods": {
        "list": {
          "flatPath": "userprofiles",
          "httpMethod": "GET",
          "id": "dfareporting.userProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles",
          "description": "Retrieves list of user profiles for a user."
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.userProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions",
            "https://www.googleapis.com/auth/dfareporting",
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{profileId}",
          "description": "Gets one user profile by ID.",
          "flatPath": "userprofiles/{profileId}"
        }
      }
    },
    "postalCodes": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/postalCodes",
          "description": "Retrieves a list of postal codes.",
          "httpMethod": "GET",
          "id": "dfareporting.postalCodes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/postalCodes"
        },
        "get": {
          "path": "userprofiles/{+profileId}/postalCodes/{+code}",
          "description": "Gets one postal code by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.postalCodes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/postalCodes/{postalCodesId}"
        }
      }
    },
    "tvCampaignSummaries": {
      "methods": {
        "list": {
          "path": "userprofiles/{+profileId}/tvCampaignSummaries",
          "description": "Retrieves a list of TV campaign summaries.",
          "id": "dfareporting.tvCampaignSummaries.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/tvCampaignSummaries"
        }
      }
    },
    "advertiserGroups": {
      "methods": {
        "delete": {
          "id": "dfareporting.advertiserGroups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "description": "Deletes an existing advertiser group."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Inserts a new advertiser group.",
          "id": "dfareporting.advertiserGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups/{advertiserGroupsId}",
          "httpMethod": "GET",
          "id": "dfareporting.advertiserGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/advertiserGroups/{+id}",
          "description": "Gets one advertiser group by ID."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.advertiserGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.advertiserGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Updates an existing advertiser group.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        },
        "list": {
          "id": "dfareporting.advertiserGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/advertiserGroups",
          "description": "Retrieves a list of advertiser groups, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/advertiserGroups"
        }
      }
    },
    "dynamicFeeds": {
      "methods": {
        "insert": {
          "flatPath": "studio/dynamicFeeds",
          "id": "dfareporting.dynamicFeeds.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "studio/dynamicFeeds",
          "description": "Inserts a new dynamic feed."
        },
        "update": {
          "httpMethod": "PUT",
          "id": "dfareporting.dynamicFeeds.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/dynamicFeeds",
          "description": "Updates a new dynamic feed. For draft feeds, only Element can be updated. For published feeds, only FeedSchedule can be updated. Other fields will be ignored.",
          "flatPath": "studio/dynamicFeeds"
        },
        "retransform": {
          "id": "dfareporting.dynamicFeeds.retransform",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}/retransform",
          "description": "Retransforms a dynamic feed. Only draft feeds can be retransformed (i.e. the feed has not been published).",
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}/retransform"
        },
        "get": {
          "flatPath": "studio/dynamicFeeds/{dynamicFeedsId}",
          "path": "studio/dynamicFeeds/{+dynamicFeedId}",
          "description": "Gets a dynamic feed by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.dynamicFeeds.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "operatingSystemVersions": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/operatingSystemVersions/{+id}",
          "description": "Gets one operating system version by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystemVersions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions/{operatingSystemVersionsId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/operatingSystemVersions",
          "httpMethod": "GET",
          "id": "dfareporting.operatingSystemVersions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/operatingSystemVersions",
          "description": "Retrieves a list of operating system versions."
        }
      }
    },
    "connectionTypes": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/connectionTypes/{+id}",
          "description": "Gets one connection type by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.connectionTypes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes/{connectionTypesId}"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/connectionTypes",
          "path": "userprofiles/{+profileId}/connectionTypes",
          "description": "Retrieves a list of connection types.",
          "id": "dfareporting.connectionTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "contentCategories": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "id": "dfareporting.contentCategories.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Inserts a new content category.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "delete": {
          "id": "dfareporting.contentCategories.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "description": "Deletes an existing content category.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}"
        },
        "update": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Updates an existing content category.",
          "httpMethod": "PUT",
          "id": "dfareporting.contentCategories.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "list": {
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Retrieves a list of content categories, possibly filtered. This method supports paging.",
          "id": "dfareporting.contentCategories.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        },
        "get": {
          "id": "dfareporting.contentCategories.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/contentCategories/{+id}",
          "description": "Gets one content category by ID.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories/{contentCategoriesId}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "dfareporting.contentCategories.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/contentCategories",
          "description": "Updates an existing content category. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/contentCategories"
        }
      }
    },
    "reports": {
      "methods": {
        "delete": {
          "id": "dfareporting.reports.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Deletes a report by its ID.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "insert": {
          "path": "userprofiles/{profileId}/reports",
          "description": "Creates a report.",
          "httpMethod": "POST",
          "id": "dfareporting.reports.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "flatPath": "userprofiles/{profileId}/reports"
        },
        "get": {
          "httpMethod": "GET",
          "id": "dfareporting.reports.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Retrieves a report by its ID.",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}"
        },
        "run": {
          "path": "userprofiles/{profileId}/reports/{reportId}/run",
          "description": "Runs a report.",
          "id": "dfareporting.reports.run",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "flatPath": "userprofiles/{profileId}/reports/{reportId}/run"
        },
        "update": {
          "flatPath": "userprofiles/{profileId}/reports/{reportId}",
          "path": "userprofiles/{profileId}/reports/{reportId}",
          "description": "Updates a report.",
          "id": "dfareporting.reports.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "PUT"
        },
        "list": {
          "flatPath": "userprofiles/{profileId}/reports",
          "httpMethod": "GET",
          "id": "dfareporting.reports.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "path": "userprofiles/{profileId}/reports",
          "description": "Retrieves list of reports."
        }
      },
      "resources": {
        "compatibleFields": {
          "methods": {
            "query": {
              "path": "userprofiles/{profileId}/reports/compatiblefields/query",
              "description": "Returns the fields that are compatible to be selected in the respective sections of a report criteria, given the fields already selected in the input report and user permissions.",
              "httpMethod": "POST",
              "id": "dfareporting.reports.compatibleFields.query",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "flatPath": "userprofiles/{profileId}/reports/compatiblefields/query"
            }
          }
        },
        "files": {
          "methods": {
            "get": {
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "path": "userprofiles/{profileId}/reports/{reportId}/files/{fileId}",
              "supportsMediaDownload": true,
              "description": "Retrieves a report file by its report ID and file ID. This method supports media download.",
              "id": "dfareporting.reports.files.get",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "GET"
            },
            "list": {
              "flatPath": "userprofiles/{profileId}/reports/{reportId}/files",
              "path": "userprofiles/{profileId}/reports/{reportId}/files",
              "description": "Lists files for a report.",
              "id": "dfareporting.reports.files.list",
              "scopes": [
                "https://www.googleapis.com/auth/dfareporting"
              ],
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "sizes": {
      "methods": {
        "get": {
          "path": "userprofiles/{+profileId}/sizes/{+id}",
          "description": "Gets one size by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.sizes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/sizes/{sizesId}"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.sizes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/sizes",
          "description": "Retrieves a list of sizes, possibly filtered. Retrieved sizes are globally unique and may include values not currently in use by your account. Due to this, the list of sizes returned by this method may differ from the list seen in the Trafficking UI.",
          "flatPath": "userprofiles/{userprofilesId}/sizes"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/sizes",
          "path": "userprofiles/{+profileId}/sizes",
          "description": "Inserts a new size.",
          "httpMethod": "POST",
          "id": "dfareporting.sizes.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "mobileApps": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/mobileApps/{mobileAppsId}",
          "path": "userprofiles/{+profileId}/mobileApps/{+id}",
          "description": "Gets one mobile app by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.mobileApps.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "path": "userprofiles/{+profileId}/mobileApps",
          "description": "Retrieves list of available mobile apps.",
          "id": "dfareporting.mobileApps.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/mobileApps"
        }
      }
    },
    "floodlightConfigurations": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations/{floodlightConfigurationsId}",
          "path": "userprofiles/{+profileId}/floodlightConfigurations/{+id}",
          "description": "Gets one floodlight configuration by ID.",
          "id": "dfareporting.floodlightConfigurations.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "httpMethod": "PATCH",
          "id": "dfareporting.floodlightConfigurations.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration. This method supports patch semantics."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations",
          "id": "dfareporting.floodlightConfigurations.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "description": "Retrieves a list of floodlight configurations, possibly filtered."
        },
        "update": {
          "path": "userprofiles/{+profileId}/floodlightConfigurations",
          "description": "Updates an existing floodlight configuration.",
          "httpMethod": "PUT",
          "id": "dfareporting.floodlightConfigurations.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/floodlightConfigurations"
        }
      }
    },
    "regions": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/regions",
          "id": "dfareporting.regions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/regions",
          "description": "Retrieves a list of regions."
        }
      }
    },
    "platformTypes": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/platformTypes/{platformTypesId}",
          "httpMethod": "GET",
          "id": "dfareporting.platformTypes.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/platformTypes/{+id}",
          "description": "Gets one platform type by ID."
        },
        "list": {
          "id": "dfareporting.platformTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/platformTypes",
          "description": "Retrieves a list of platform types.",
          "flatPath": "userprofiles/{userprofilesId}/platformTypes"
        }
      }
    },
    "directorySites": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites/{directorySitesId}",
          "path": "userprofiles/{+profileId}/directorySites/{+id}",
          "description": "Gets one directory site by ID.",
          "id": "dfareporting.directorySites.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Inserts a new directory site.",
          "id": "dfareporting.directorySites.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/directorySites",
          "httpMethod": "GET",
          "id": "dfareporting.directorySites.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/directorySites",
          "description": "Retrieves a list of directory sites, possibly filtered. This method supports paging."
        }
      }
    },
    "dynamicProfiles": {
      "methods": {
        "update": {
          "flatPath": "studio/dynamicProfiles",
          "id": "dfareporting.dynamicProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "studio/dynamicProfiles",
          "description": "Updates an existing dynamic profile."
        },
        "get": {
          "path": "studio/dynamicProfiles/{+dynamicProfileId}",
          "description": "Gets a dynamic profile by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.dynamicProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}"
        },
        "insert": {
          "flatPath": "studio/dynamicProfiles",
          "path": "studio/dynamicProfiles",
          "description": "Inserts a new dynamic profile.",
          "httpMethod": "POST",
          "id": "dfareporting.dynamicProfiles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "generateCode": {
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/generateCode",
          "id": "dfareporting.dynamicProfiles.generateCode",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/generateCode",
          "description": "Generates code for a dynamic profile, which will need unescaping."
        },
        "publish": {
          "httpMethod": "POST",
          "id": "dfareporting.dynamicProfiles.publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "studio/dynamicProfiles/{dynamicProfilesId}/publish",
          "path": "studio/dynamicProfiles/{+dynamicProfileId}/publish",
          "description": "Publish for a dynamic profile."
        }
      }
    },
    "videoFormats": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/videoFormats/{videoFormatsId}",
          "path": "userprofiles/{+profileId}/videoFormats/{+id}",
          "description": "Gets one video format by ID.",
          "id": "dfareporting.videoFormats.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "list": {
          "path": "userprofiles/{+profileId}/videoFormats",
          "description": "Lists available video formats.",
          "httpMethod": "GET",
          "id": "dfareporting.videoFormats.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/videoFormats"
        }
      }
    },
    "dimensionValues": {
      "methods": {
        "query": {
          "id": "dfareporting.dimensionValues.query",
          "scopes": [
            "https://www.googleapis.com/auth/dfareporting"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/dimensionvalues/query",
          "description": "Retrieves list of report dimension values for a list of filters.",
          "flatPath": "userprofiles/{profileId}/dimensionvalues/query"
        }
      }
    },
    "userRolePermissions": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions/{userRolePermissionsId}",
          "path": "userprofiles/{+profileId}/userRolePermissions/{+id}",
          "description": "Gets one user role permission by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.userRolePermissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/userRolePermissions",
          "id": "dfareporting.userRolePermissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRolePermissions",
          "description": "Gets a list of user role permissions, possibly filtered."
        }
      }
    },
    "studioCreatives": {
      "methods": {
        "insert": {
          "path": "studio/creatives",
          "description": "Inserts a new studio creative.",
          "id": "dfareporting.studioCreatives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "flatPath": "studio/creatives"
        },
        "publish": {
          "flatPath": "studio/creatives/{creativesId}/publish",
          "path": "studio/creatives/{+studioCreativeId}/publish",
          "description": "Publish for a studio creative.",
          "httpMethod": "POST",
          "id": "dfareporting.studioCreatives.publish",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "studio/creatives/{creativesId}",
          "httpMethod": "GET",
          "id": "dfareporting.studioCreatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "studio/creatives/{+studioCreativeId}",
          "description": "Gets a studio creative by ID."
        }
      }
    },
    "remarketingLists": {
      "methods": {
        "insert": {
          "id": "dfareporting.remarketingLists.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Inserts a new remarketing list.",
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Updates an existing remarketing list. This method supports patch semantics.",
          "id": "dfareporting.remarketingLists.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists/{remarketingListsId}",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/remarketingLists/{+id}",
          "description": "Gets one remarketing list by ID."
        },
        "list": {
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Retrieves a list of remarketing lists, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.remarketingLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/remarketingLists",
          "path": "userprofiles/{+profileId}/remarketingLists",
          "description": "Updates an existing remarketing list.",
          "id": "dfareporting.remarketingLists.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        }
      }
    },
    "conversions": {
      "methods": {
        "batchinsert": {
          "id": "dfareporting.conversions.batchinsert",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{profileId}/conversions/batchinsert",
          "description": "Inserts conversions.",
          "flatPath": "userprofiles/{profileId}/conversions/batchinsert"
        },
        "batchupdate": {
          "path": "userprofiles/{profileId}/conversions/batchupdate",
          "description": "Updates existing conversions.",
          "httpMethod": "POST",
          "id": "dfareporting.conversions.batchupdate",
          "scopes": [
            "https://www.googleapis.com/auth/ddmconversions"
          ],
          "flatPath": "userprofiles/{profileId}/conversions/batchupdate"
        }
      }
    },
    "metros": {
      "methods": {
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/metros",
          "path": "userprofiles/{+profileId}/metros",
          "description": "Retrieves a list of metros.",
          "id": "dfareporting.metros.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "accountUserProfiles": {
      "methods": {
        "get": {
          "id": "dfareporting.accountUserProfiles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{profileId}/accountUserProfiles/{+id}",
          "description": "Gets one account user profile by ID.",
          "flatPath": "userprofiles/{profileId}/accountUserProfiles/{accountUserProfilesId}"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "httpMethod": "PATCH",
          "id": "dfareporting.accountUserProfiles.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Updates an existing account user profile. This method supports patch semantics."
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Retrieves a list of account user profiles, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.accountUserProfiles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.accountUserProfiles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Updates an existing account user profile.",
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/accountUserProfiles",
          "path": "userprofiles/{+profileId}/accountUserProfiles",
          "description": "Inserts a new account user profile.",
          "httpMethod": "POST",
          "id": "dfareporting.accountUserProfiles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        }
      }
    },
    "ads": {
      "methods": {
        "insert": {
          "path": "userprofiles/{+profileId}/ads",
          "description": "Inserts a new ad.",
          "httpMethod": "POST",
          "id": "dfareporting.ads.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/ads"
        },
        "get": {
          "path": "userprofiles/{+profileId}/ads/{+id}",
          "description": "Gets one ad by ID.",
          "id": "dfareporting.ads.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/ads/{adsId}"
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/ads",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Updates an existing ad. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.ads.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "update": {
          "id": "dfareporting.ads.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Updates an existing ad.",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        },
        "list": {
          "id": "dfareporting.ads.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/ads",
          "description": "Retrieves a list of ads, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/ads"
        }
      }
    },
    "creatives": {
      "methods": {
        "get": {
          "id": "dfareporting.creatives.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/creatives/{+id}",
          "description": "Gets one creative by ID.",
          "flatPath": "userprofiles/{userprofilesId}/creatives/{creativesId}"
        },
        "patch": {
          "id": "dfareporting.creatives.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Updates an existing creative. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Updates an existing creative.",
          "id": "dfareporting.creatives.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creatives",
          "httpMethod": "GET",
          "id": "dfareporting.creatives.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Retrieves a list of creatives, possibly filtered. This method supports paging."
        },
        "insert": {
          "path": "userprofiles/{+profileId}/creatives",
          "description": "Inserts a new creative.",
          "httpMethod": "POST",
          "id": "dfareporting.creatives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/creatives"
        }
      }
    },
    "targetingTemplates": {
      "methods": {
        "patch": {
          "id": "dfareporting.targetingTemplates.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Updates an existing targeting template. This method supports patch semantics.",
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates"
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates/{targetingTemplatesId}",
          "id": "dfareporting.targetingTemplates.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetingTemplates/{+id}",
          "description": "Gets one targeting template by ID."
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Updates an existing targeting template.",
          "id": "dfareporting.targetingTemplates.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "id": "dfareporting.targetingTemplates.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Retrieves a list of targeting templates, optionally filtered. This method supports paging."
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/targetingTemplates",
          "httpMethod": "POST",
          "id": "dfareporting.targetingTemplates.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/targetingTemplates",
          "description": "Inserts a new targeting template."
        }
      }
    },
    "creativeGroups": {
      "methods": {
        "update": {
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Updates an existing creative group.",
          "id": "dfareporting.creativeGroups.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Retrieves a list of creative groups, possibly filtered. This method supports paging.",
          "httpMethod": "GET",
          "id": "dfareporting.creativeGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups/{creativeGroupsId}",
          "path": "userprofiles/{+profileId}/creativeGroups/{+id}",
          "description": "Gets one creative group by ID.",
          "httpMethod": "GET",
          "id": "dfareporting.creativeGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "patch": {
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Updates an existing creative group. This method supports patch semantics.",
          "id": "dfareporting.creativeGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PATCH",
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/creativeGroups",
          "id": "dfareporting.creativeGroups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/creativeGroups",
          "description": "Inserts a new creative group."
        }
      }
    },
    "subaccounts": {
      "methods": {
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Updates an existing subaccount. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.subaccounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/subaccounts/{+id}",
          "description": "Gets one subaccount by ID.",
          "id": "dfareporting.subaccounts.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts/{subaccountsId}"
        },
        "list": {
          "httpMethod": "GET",
          "id": "dfareporting.subaccounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Gets a list of subaccounts, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "update": {
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Updates an existing subaccount.",
          "id": "dfareporting.subaccounts.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/subaccounts"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/subaccounts",
          "id": "dfareporting.subaccounts.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST",
          "path": "userprofiles/{+profileId}/subaccounts",
          "description": "Inserts a new subaccount."
        }
      }
    },
    "userRoles": {
      "methods": {
        "list": {
          "id": "dfareporting.userRoles.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Retrieves a list of user roles, possibly filtered. This method supports paging.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles"
        },
        "update": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "id": "dfareporting.userRoles.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Updates an existing user role."
        },
        "patch": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Updates an existing user role. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.userRoles.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ]
        },
        "get": {
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "description": "Gets one user role by ID.",
          "id": "dfareporting.userRoles.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}"
        },
        "insert": {
          "flatPath": "userprofiles/{userprofilesId}/userRoles",
          "path": "userprofiles/{+profileId}/userRoles",
          "description": "Inserts a new user role.",
          "id": "dfareporting.userRoles.insert",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "POST"
        },
        "delete": {
          "id": "dfareporting.userRoles.delete",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "DELETE",
          "path": "userprofiles/{+profileId}/userRoles/{+id}",
          "description": "Deletes an existing user role.",
          "flatPath": "userprofiles/{userprofilesId}/userRoles/{userRolesId}"
        }
      }
    },
    "accounts": {
      "methods": {
        "get": {
          "flatPath": "userprofiles/{userprofilesId}/accounts/{accountsId}",
          "path": "userprofiles/{+profileId}/accounts/{+id}",
          "description": "Gets one account by ID.",
          "id": "dfareporting.accounts.get",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "GET"
        },
        "patch": {
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Updates an existing account. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "dfareporting.accounts.patch",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        },
        "update": {
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Updates an existing account.",
          "id": "dfareporting.accounts.update",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "httpMethod": "PUT",
          "flatPath": "userprofiles/{userprofilesId}/accounts"
        },
        "list": {
          "flatPath": "userprofiles/{userprofilesId}/accounts",
          "httpMethod": "GET",
          "id": "dfareporting.accounts.list",
          "scopes": [
            "https://www.googleapis.com/auth/dfatrafficking"
          ],
          "path": "userprofiles/{+profileId}/accounts",
          "description": "Retrieves the list of accounts, possibly filtered. This method supports paging."
        }
      }
    }
  },
  "canonicalName": "Dfareporting",
  "protocol": "rest",
  "baseUrl": "https://dfareporting.googleapis.com/dfareporting/v5/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/dfareporting": {
          "description": "View and manage DoubleClick for Advertisers reports"
        },
        "https://www.googleapis.com/auth/ddmconversions": {
          "description": "Manage DoubleClick Digital Marketing conversions"
        },
        "https://www.googleapis.com/auth/dfatrafficking": {
          "description": "View and manage your DoubleClick Campaign Manager's (DCM) display ad campaigns"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "documentationLink": "https://developers.google.com/doubleclick-advertisers/",
  "ownerName": "Google",
  "mtlsRootUrl": "https://dfareporting.mtls.googleapis.com/"
}