{
  "version_module": true,
  "protocol": "rest",
  "documentationLink": "https://cloud.google.com/generative-ai-app-builder/docs/",
  "canonicalName": "Discovery Engine",
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "fullyEncodeReservedExpansion": true,
  "version": "v1alpha",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/discoveryengine.readwrite": {
          "description": "View, edit, create, and delete all your data associated with any Discovery Engine API product, such as Agentspace, Vertex AI Search, or NotebookLM Enterprise, including both end user data and administration or configuration data."
        },
        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite": {
          "description": "View your Agentspace chat history, including uploaded files and generated reports and visualizations, and interact with the Agentspace assistant on your behalf."
        }
      }
    }
  },
  "revision": "20260322",
  "name": "discoveryengine",
  "mtlsRootUrl": "https://discoveryengine.mtls.googleapis.com/",
  "baseUrl": "https://discoveryengine.googleapis.com/",
  "id": "discoveryengine:v1alpha",
  "batchPath": "batch",
  "basePath": "",
  "description": "Discovery Engine API.",
  "ownerDomain": "google.com",
  "servicePath": "",
  "title": "Discovery Engine API",
  "rootUrl": "https://discoveryengine.googleapis.com/",
  "resources": {
    "projects": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "path": "v1alpha/{+name}",
          "id": "discoveryengine.projects.patch",
          "flatPath": "v1alpha/projects/{projectsId}",
          "description": "Updates the editable settings of a Discovery Engine Project.",
          "httpMethod": "PATCH"
        },
        "reportConsentChange": {
          "description": "Updates service terms for this project. This method can be used to retroactively accept the latest terms. Terms available for update: * [Terms for data use](https://cloud.google.com/retail/data-use-terms)",
          "flatPath": "v1alpha/projects/{projectsId}:reportConsentChange",
          "id": "discoveryengine.projects.reportConsentChange",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "path": "v1alpha/{+project}:reportConsentChange",
          "httpMethod": "POST"
        },
        "provision": {
          "description": "Provisions the project resource. During the process, related systems will get prepared and initialized. Caller must read the [Terms for data use](https://cloud.google.com/retail/data-use-terms), and optionally specify in request to provide consent to that service terms.",
          "httpMethod": "POST",
          "flatPath": "v1alpha/projects/{projectsId}:provision",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "path": "v1alpha/{+name}:provision",
          "id": "discoveryengine.projects.provision"
        },
        "get": {
          "path": "v1alpha/{+name}",
          "description": "Gets a Project. Returns NOT_FOUND when the project is not yet created.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "flatPath": "v1alpha/projects/{projectsId}",
          "id": "discoveryengine.projects.get"
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/projects/{projectsId}/operations/{operationsId}",
              "path": "v1alpha/{+name}",
              "id": "discoveryengine.projects.operations.get",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ]
            },
            "list": {
              "id": "discoveryengine.projects.operations.list",
              "path": "v1alpha/{+name}/operations",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
              "httpMethod": "GET",
              "flatPath": "v1alpha/projects/{projectsId}/operations"
            }
          }
        },
        "locations": {
          "methods": {
            "queryConfigurablePricingUsageStats": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "path": "v1alpha/{+project}/locations/{location}:queryConfigurablePricingUsageStats",
              "description": "Queries configurable pricing usage stats for a project.",
              "id": "discoveryengine.projects.locations.queryConfigurablePricingUsageStats",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{location}:queryConfigurablePricingUsageStats",
              "httpMethod": "GET"
            },
            "removeDedicatedCrawlRate": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:removeDedicatedCrawlRate",
              "id": "discoveryengine.projects.locations.removeDedicatedCrawlRate",
              "description": "Removes the dedicated crawl rate for a craw_rate_scope. If the dedicated crawl rate was set, this will disable vertex AI's crawl bot from using the dedicated crawl rate for crawling. If the dedicated crawl rate was not set, this is a no-op.",
              "httpMethod": "POST",
              "path": "v1alpha/{+location}:removeDedicatedCrawlRate"
            },
            "setUpDataConnector": {
              "id": "discoveryengine.projects.locations.setUpDataConnector",
              "description": "Creates a Collection and sets up the DataConnector for it. To stop a DataConnector after setup, use the CollectionService.DeleteCollection method.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setUpDataConnector",
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}:setUpDataConnector"
            },
            "completeExternalIdentities": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "path": "v1alpha/{+parent}:completeExternalIdentities",
              "id": "discoveryengine.projects.locations.completeExternalIdentities",
              "httpMethod": "GET",
              "description": "This method provides suggestions for users and groups managed in an external identity provider, based on the provided prefix.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:completeExternalIdentities"
            },
            "updateCmekConfig": {
              "path": "v1alpha/{+name}",
              "id": "discoveryengine.projects.locations.updateCmekConfig",
              "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfig",
              "httpMethod": "PATCH"
            },
            "obtainCrawlRate": {
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:obtainCrawlRate",
              "description": "Obtains the time series data of organic or dedicated crawl rate for monitoring. When dedicated crawl rate is not set, it will return vertex AI's organic crawl rate time series. Organic crawl means Google automatically crawl the internet at its own convenience. When dedicated crawl rate is set, it will return vertex AI's dedicated crawl rate time series.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.locations.obtainCrawlRate",
              "path": "v1alpha/{+location}:obtainCrawlRate",
              "httpMethod": "POST"
            },
            "getAclConfig": {
              "description": "Gets the AclConfig.",
              "id": "discoveryengine.projects.locations.getAclConfig",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/aclConfig",
              "path": "v1alpha/{+name}"
            },
            "estimateDataSize": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "description": "Estimates the data size to be used by a customer.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:estimateDataSize",
              "httpMethod": "POST",
              "path": "v1alpha/{+location}:estimateDataSize",
              "id": "discoveryengine.projects.locations.estimateDataSize"
            },
            "getCmekConfig": {
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "description": "Gets the CmekConfig.",
              "id": "discoveryengine.projects.locations.getCmekConfig",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfig"
            },
            "setUpDataConnectorV2": {
              "id": "discoveryengine.projects.locations.setUpDataConnectorV2",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setUpDataConnectorV2",
              "path": "v1alpha/{+parent}:setUpDataConnectorV2",
              "description": "Creates a Collection and sets up the DataConnector for it. To stop a DataConnector after setup, use the CollectionService.DeleteCollection method.",
              "httpMethod": "POST"
            },
            "updateAclConfig": {
              "description": "Default ACL configuration for use in a location of a customer's project. Updates will only reflect to new data stores. Existing data stores will still use the old value.",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/aclConfig",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.locations.updateAclConfig",
              "httpMethod": "PATCH"
            },
            "setDedicatedCrawlRate": {
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setDedicatedCrawlRate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "description": "Sets the dedicated crawl rate for a crawl_rate_scope. If the dedicated crawl rate was not set, this will enable vertex AI's crawl bot to use the new dedicated crawl rate for crawling. If the dedicated crawl rate was set, vertex AI's crawl bot will try to update the rate to the new value. If the new value is too high, the crawl bot may crawl at a lower rate to avoid overloading the user's website.",
              "id": "discoveryengine.projects.locations.setDedicatedCrawlRate",
              "path": "v1alpha/{+location}:setDedicatedCrawlRate"
            }
          },
          "resources": {
            "userStores": {
              "methods": {
                "patch": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Updates the User Store.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.userStores.patch"
                },
                "batchUpdateUserLicenses": {
                  "path": "v1alpha/{+parent}:batchUpdateUserLicenses",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}:batchUpdateUserLicenses",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.userStores.batchUpdateUserLicenses",
                  "description": "Updates the User License. This method is used for batch assign/unassign licenses to users.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "get": {
                  "id": "discoveryengine.projects.locations.userStores.get",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "path": "v1alpha/{+name}",
                  "description": "Gets the User Store.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET"
                }
              },
              "resources": {
                "userLicenses": {
                  "methods": {
                    "list": {
                      "path": "v1alpha/{+parent}/userLicenses",
                      "description": "Lists the User Licenses.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/userLicenses",
                      "id": "discoveryengine.projects.locations.userStores.userLicenses.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET"
                    }
                  }
                },
                "licenseConfigsUsageStats": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "description": "Lists all the LicenseConfigUsageStatss associated with the project.",
                      "id": "discoveryengine.projects.locations.userStores.licenseConfigsUsageStats.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/licenseConfigsUsageStats",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/licenseConfigsUsageStats"
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.userStores.operations.get",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/operations/{operationsId}"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.userStores.operations.list",
                      "path": "v1alpha/{+name}/operations",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/operations",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                    }
                  }
                }
              }
            },
            "operations": {
              "methods": {
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "id": "discoveryengine.projects.locations.operations.get"
                },
                "list": {
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}/operations",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.operations.list"
                }
              }
            },
            "dataStores": {
              "methods": {
                "create": {
                  "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                  "path": "v1alpha/{+parent}/dataStores",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.create"
                },
                "completeQuery": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Completes the specified user input with keyword suggestions.",
                  "id": "discoveryengine.projects.locations.dataStores.completeQuery",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:completeQuery",
                  "path": "v1alpha/{+dataStore}:completeQuery"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "id": "discoveryengine.projects.locations.dataStores.list",
                  "path": "v1alpha/{+parent}/dataStores",
                  "description": "Lists all the DataStores associated with the project.",
                  "httpMethod": "GET"
                },
                "replacePatientFilter": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:replacePatientFilter",
                  "path": "v1alpha/{+dataStore}:replacePatientFilter",
                  "description": "Replaces the patient filter for the data store. This method is essentially a combination of DeletePatientFilters and AddPatientFilter. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the new filter w[...]",
                  "id": "discoveryengine.projects.locations.dataStores.replacePatientFilter"
                },
                "addPatientFilter": {
                  "description": "Adds a group of patient IDs as a patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. The filter group must be a FHIR resource name of type Group, and the filter will be constructed from the direct members of the group which are Patient resources.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.addPatientFilter",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:addPatientFilter",
                  "path": "v1alpha/{+dataStore}:addPatientFilter",
                  "httpMethod": "POST"
                },
                "removePatientFilter": {
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:removePatientFilter",
                  "id": "discoveryengine.projects.locations.dataStores.removePatientFilter",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Removes a group of patient IDs from the patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the list of patient IDs to remove will be constructed from the direct member[...]",
                  "path": "v1alpha/{+dataStore}:removePatientFilter"
                },
                "deletePatientFilter": {
                  "description": "Deletes the entire patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter.",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:deletePatientFilter",
                  "id": "discoveryengine.projects.locations.dataStores.deletePatientFilter",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+dataStore}:deletePatientFilter"
                },
                "patch": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Updates a DataStore",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.dataStores.patch",
                  "path": "v1alpha/{+name}"
                },
                "updateDocumentProcessingConfig": {
                  "httpMethod": "PATCH",
                  "description": "Updates the DocumentProcessingConfig. DocumentProcessingConfig is a singleon resource of DataStore. It's empty when DataStore is created. The first call to this method will set up DocumentProcessingConfig.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.dataStores.updateDocumentProcessingConfig"
                },
                "getSiteSearchEngine": {
                  "description": "Gets the SiteSearchEngine.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine",
                  "id": "discoveryengine.projects.locations.dataStores.getSiteSearchEngine",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET"
                },
                "get": {
                  "httpMethod": "GET",
                  "description": "Gets a DataStore.",
                  "id": "discoveryengine.projects.locations.dataStores.get",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}"
                },
                "getDocumentProcessingConfig": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                  "description": "Gets a DocumentProcessingConfig.",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.dataStores.getDocumentProcessingConfig"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "description": "Deletes a DataStore.",
                  "path": "v1alpha/{+name}"
                }
              },
              "resources": {
                "schemas": {
                  "methods": {
                    "patch": {
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.patch",
                      "description": "Updates a Schema.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "get": {
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "description": "Gets a Schema."
                    },
                    "create": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.create",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/schemas",
                      "description": "Creates a Schema.",
                      "httpMethod": "POST"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes a Schema.",
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.delete",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "path": "v1alpha/{+name}"
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.list",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "description": "Gets a list of Schemas.",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/schemas"
                    }
                  }
                },
                "suggestionDenyListEntries": {
                  "methods": {
                    "import": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:import"
                    },
                    "purge": {
                      "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.purge",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge"
                    }
                  }
                },
                "controls": {
                  "methods": {
                    "create": {
                      "id": "discoveryengine.projects.locations.dataStores.controls.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/controls",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned."
                    },
                    "get": {
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.controls.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "httpMethod": "GET",
                      "description": "Gets a Control."
                    },
                    "patch": {
                      "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.controls.patch",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "path": "v1alpha/{+name}"
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.controls.list",
                      "path": "v1alpha/{+parent}/controls",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Lists all Controls by their parent DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "httpMethod": "GET"
                    },
                    "delete": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.controls.delete",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned."
                    }
                  }
                },
                "branches": {
                  "methods": {
                    "batchGetDocumentsMetadata": {
                      "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                      "path": "v1alpha/{+parent}/batchGetDocumentsMetadata",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.branches.batchGetDocumentsMetadata"
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.branches.get",
                      "description": "Retrieves a Branch.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}"
                    },
                    "list": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/branches",
                      "id": "discoveryengine.projects.locations.dataStores.branches.list",
                      "description": "Lists all Branchs under the specified parent DataStore.",
                      "httpMethod": "GET"
                    }
                  },
                  "resources": {
                    "operations": {
                      "methods": {
                        "cancel": {
                          "httpMethod": "POST",
                          "path": "v1alpha/{+name}:cancel",
                          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instea[...]",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.cancel"
                        },
                        "get": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.get",
                          "httpMethod": "GET",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.list",
                          "path": "v1alpha/{+name}/operations",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations"
                        }
                      }
                    },
                    "documents": {
                      "resources": {
                        "chunks": {
                          "methods": {
                            "get": {
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks/{chunksId}",
                              "httpMethod": "GET",
                              "description": "Gets a Document."
                            },
                            "list": {
                              "description": "Gets a list of Chunks.",
                              "path": "v1alpha/{+parent}/chunks",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.list",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks"
                            }
                          }
                        }
                      },
                      "methods": {
                        "purge": {
                          "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.purge",
                          "path": "v1alpha/{+parent}/documents:purge"
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.list",
                          "description": "Gets a list of Documents.",
                          "httpMethod": "GET",
                          "path": "v1alpha/{+parent}/documents",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents"
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "path": "v1alpha/{+parent}/documents",
                          "httpMethod": "POST",
                          "description": "Creates a Document."
                        },
                        "import": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated.",
                          "path": "v1alpha/{+parent}/documents:import",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.import"
                        },
                        "delete": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.delete",
                          "description": "Deletes a Document.",
                          "httpMethod": "DELETE",
                          "path": "v1alpha/{+name}"
                        },
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "path": "v1alpha/{+name}",
                          "description": "Updates a Document.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.patch"
                        },
                        "getProcessedDocument": {
                          "path": "v1alpha/{+name}:getProcessedDocument",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}:getProcessedDocument",
                          "description": "Gets the parsed layout information for a Document.",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.getProcessedDocument"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "description": "Gets a Document.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}"
                        }
                      }
                    }
                  }
                },
                "servingConfigs": {
                  "methods": {
                    "streamAnswer": {
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+servingConfig}:streamAnswer",
                      "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.streamAnswer"
                    },
                    "recommend": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.recommend",
                      "path": "v1alpha/{+servingConfig}:recommend",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "description": "Makes a recommendation, which requires a contextual user event."
                    },
                    "list": {
                      "description": "Lists all ServingConfigs linked to this dataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "httpMethod": "GET"
                    },
                    "answer": {
                      "path": "v1alpha/{+servingConfig}:answer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Answer query method.",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.answer",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer"
                    },
                    "get": {
                      "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET"
                    },
                    "searchLite": {
                      "path": "v1alpha/{+servingConfig}:searchLite",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, it i[...]",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.searchLite",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite"
                    },
                    "create": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "path": "v1alpha/{+parent}/servingConfigs"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "httpMethod": "DELETE",
                      "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.delete",
                      "path": "v1alpha/{+name}"
                    },
                    "search": {
                      "path": "v1alpha/{+servingConfig}:search",
                      "description": "Performs a search.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.search"
                    },
                    "patch": {
                      "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.patch",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "httpMethod": "PATCH"
                    }
                  }
                },
                "sessions": {
                  "resources": {
                    "answers": {
                      "methods": {
                        "get": {
                          "httpMethod": "GET",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.sessions.answers.get",
                          "description": "Gets a Answer."
                        }
                      }
                    }
                  },
                  "methods": {
                    "list": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "path": "v1alpha/{+parent}/sessions",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "description": "Lists all Sessions by their parent DataStore."
                    },
                    "get": {
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.get",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets a Session."
                    },
                    "patch": {
                      "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.patch",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "PATCH",
                      "path": "v1alpha/{+name}"
                    },
                    "delete": {
                      "id": "discoveryengine.projects.locations.dataStores.sessions.delete",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                      "httpMethod": "DELETE"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.create",
                      "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                      "path": "v1alpha/{+parent}/sessions",
                      "httpMethod": "POST"
                    }
                  }
                },
                "siteSearchEngine": {
                  "methods": {
                    "disableAdvancedSiteSearch": {
                      "path": "v1alpha/{+siteSearchEngine}:disableAdvancedSiteSearch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.disableAdvancedSiteSearch",
                      "httpMethod": "POST",
                      "description": "Downgrade from advanced site search to basic site search."
                    },
                    "recrawlUris": {
                      "path": "v1alpha/{+siteSearchEngine}:recrawlUris",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.recrawlUris",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                      "description": "Request on-demand recrawl for a list of URIs.",
                      "httpMethod": "POST"
                    },
                    "enableAdvancedSiteSearch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch",
                      "path": "v1alpha/{+siteSearchEngine}:enableAdvancedSiteSearch",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.enableAdvancedSiteSearch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Upgrade from basic site search to advanced site search."
                    }
                  },
                  "resources": {
                    "targetSites": {
                      "methods": {
                        "create": {
                          "description": "Creates a TargetSite.",
                          "httpMethod": "POST",
                          "path": "v1alpha/{+parent}/targetSites",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites"
                        },
                        "list": {
                          "path": "v1alpha/{+parent}/targetSites",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "description": "Gets a list of TargetSites."
                        },
                        "delete": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "description": "Deletes a TargetSite.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.delete",
                          "httpMethod": "DELETE"
                        },
                        "patch": {
                          "path": "v1alpha/{+name}",
                          "description": "Updates a TargetSite.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.patch",
                          "httpMethod": "PATCH"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a TargetSite.",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.get",
                          "httpMethod": "GET"
                        },
                        "batchCreate": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/targetSites:batchCreate",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.batchCreate",
                          "description": "Creates TargetSite in a batch."
                        }
                      }
                    },
                    "sitemaps": {
                      "methods": {
                        "create": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.create",
                          "path": "v1alpha/{+parent}/sitemaps",
                          "httpMethod": "POST",
                          "description": "Creates a Sitemap.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "delete": {
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.delete",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes a Sitemap."
                        },
                        "fetch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/sitemaps:fetch",
                          "description": "Fetch Sitemaps in a DataStore.",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.fetch",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch"
                        }
                      }
                    }
                  }
                },
                "models": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "path": "v1alpha/{+name}/operations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.list",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                        },
                        "get": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET"
                        }
                      }
                    }
                  }
                },
                "widgetConfigs": {
                  "methods": {
                    "patch": {
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.patch",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                      "httpMethod": "PATCH",
                      "description": "Update a WidgetConfig.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "get": {
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                      "description": "Gets a WidgetConfig.",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "conversations": {
                  "methods": {
                    "delete": {
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.conversations.delete",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "path": "v1alpha/{+name}",
                      "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned."
                    },
                    "converse": {
                      "path": "v1alpha/{+name}:converse",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.converse",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Converses a conversation."
                    },
                    "patch": {
                      "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.patch",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}"
                    },
                    "get": {
                      "description": "Gets a Conversation.",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.conversations.get",
                      "path": "v1alpha/{+name}"
                    },
                    "list": {
                      "path": "v1alpha/{+parent}/conversations",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.conversations.list",
                      "description": "Lists all Conversations by their parent DataStore."
                    },
                    "create": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "path": "v1alpha/{+parent}/conversations",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.create",
                      "httpMethod": "POST",
                      "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations",
                      "path": "v1alpha/{+name}/operations",
                      "httpMethod": "GET",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "id": "discoveryengine.projects.locations.dataStores.operations.list"
                    },
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations/{operationsId}",
                      "httpMethod": "GET",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.dataStores.operations.get",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "userEvents": {
                  "methods": {
                    "collect": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:collect",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.collect",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                      "path": "v1alpha/{+parent}/userEvents:collect"
                    },
                    "import": {
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.import",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:import",
                      "httpMethod": "POST",
                      "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/userEvents:import"
                    },
                    "purge": {
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.purge",
                      "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                      "path": "v1alpha/{+parent}/userEvents:purge",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "write": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:write",
                      "path": "v1alpha/{+parent}/userEvents:write",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.write",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Writes a single user event."
                    }
                  }
                },
                "completionSuggestions": {
                  "methods": {
                    "import": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.import",
                      "description": "Imports CompletionSuggestions for a DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/completionSuggestions:import"
                    },
                    "purge": {
                      "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.purge",
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}/completionSuggestions:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "completionConfig": {
                  "methods": {
                    "completeQuery": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud_search.query",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "description": "Completes the user input with advanced keyword suggestions.",
                      "id": "discoveryengine.projects.locations.dataStores.completionConfig.completeQuery",
                      "path": "v1alpha/{+completionConfig}:completeQuery"
                    }
                  }
                }
              }
            },
            "identityMappingStores": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.identityMappingStores.get",
                  "description": "Gets the Identity Mapping Store.",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "delete": {
                  "description": "Deletes the Identity Mapping Store.",
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.identityMappingStores.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "listIdentityMappings": {
                  "path": "v1alpha/{+identityMappingStore}:listIdentityMappings",
                  "id": "discoveryengine.projects.locations.identityMappingStores.listIdentityMappings",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:listIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists Identity Mappings in an Identity Mapping Store."
                },
                "purgeIdentityMappings": {
                  "path": "v1alpha/{+identityMappingStore}:purgeIdentityMappings",
                  "description": "Purges specified or all Identity Mapping Entries from an Identity Mapping Store.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:purgeIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.purgeIdentityMappings",
                  "httpMethod": "POST"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.create",
                  "description": "Creates a new Identity Mapping Store.",
                  "httpMethod": "POST",
                  "path": "v1alpha/{+parent}/identityMappingStores",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores"
                },
                "importIdentityMappings": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:importIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.importIdentityMappings",
                  "httpMethod": "POST",
                  "description": "Imports a list of Identity Mapping Entries to an Identity Mapping Store.",
                  "path": "v1alpha/{+identityMappingStore}:importIdentityMappings"
                },
                "list": {
                  "description": "Lists all Identity Mapping Stores.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "path": "v1alpha/{+parent}/identityMappingStores",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.identityMappingStores.list"
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations/{operationsId}",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}"
                    },
                    "list": {
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}/operations",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.list",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            },
            "authorizations": {
              "methods": {
                "create": {
                  "id": "discoveryengine.projects.locations.authorizations.create",
                  "description": "Creates an Authorization.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/authorizations",
                  "httpMethod": "POST"
                },
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}",
                  "description": "Gets an Authorization.",
                  "id": "discoveryengine.projects.locations.authorizations.get"
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.authorizations.delete",
                  "description": "Deletes an Authorization.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Lists all Authorizations under an Engine.",
                  "path": "v1alpha/{+parent}/authorizations",
                  "id": "discoveryengine.projects.locations.authorizations.list"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.authorizations.patch",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Updates an Authorization",
                  "path": "v1alpha/{+name}"
                }
              }
            },
            "cmekConfigs": {
              "methods": {
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location.",
                  "id": "discoveryengine.projects.locations.cmekConfigs.patch",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}"
                },
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.cmekConfigs.get",
                  "description": "Gets the CmekConfig."
                },
                "delete": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.cmekConfigs.delete",
                  "description": "De-provisions a CmekConfig."
                },
                "list": {
                  "description": "Lists all the CmekConfigs with the project.",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.cmekConfigs.list",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/cmekConfigs"
                }
              }
            },
            "rankingConfigs": {
              "methods": {
                "rank": {
                  "id": "discoveryengine.projects.locations.rankingConfigs.rank",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Ranks a list of text records based on the given input query.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/rankingConfigs/{rankingConfigsId}:rank",
                  "path": "v1alpha/{+rankingConfig}:rank",
                  "httpMethod": "POST"
                }
              }
            },
            "requirements": {
              "methods": {
                "checkRequirement": {
                  "id": "discoveryengine.projects.locations.requirements.checkRequirement",
                  "path": "v1alpha/{+location}/requirements:checkRequirement",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/requirements:checkRequirement",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Check a particular requirement."
                }
              }
            },
            "licenseConfigs": {
              "methods": {
                "create": {
                  "description": "Creates a LicenseConfig This method should only be used for creating NotebookLm licenses or Gemini Enterprise free trial licenses.",
                  "path": "v1alpha/{+parent}/licenseConfigs",
                  "id": "discoveryengine.projects.locations.licenseConfigs.create",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs"
                },
                "get": {
                  "id": "discoveryengine.projects.locations.licenseConfigs.get",
                  "description": "Gets a LicenseConfig.",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}"
                },
                "patch": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.licenseConfigs.patch",
                  "description": "Updates the LicenseConfig",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                }
              }
            },
            "evaluations": {
              "methods": {
                "create": {
                  "httpMethod": "POST",
                  "description": "Creates a Evaluation. Upon creation, the evaluation will be automatically triggered and begin execution.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.evaluations.create",
                  "path": "v1alpha/{+parent}/evaluations"
                },
                "listResults": {
                  "id": "discoveryengine.projects.locations.evaluations.listResults",
                  "path": "v1alpha/{+evaluation}:listResults",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}:listResults",
                  "description": "Gets a list of results for a given a Evaluation."
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.evaluations.get",
                  "description": "Gets a Evaluation."
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/evaluations",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.evaluations.list",
                  "description": "Gets a list of Evaluations.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations"
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}/operations/{operationsId}",
                      "path": "v1alpha/{+name}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.evaluations.operations.get"
                    }
                  }
                }
              }
            },
            "collections": {
              "methods": {
                "delete": {
                  "id": "discoveryengine.projects.locations.collections.delete",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}",
                  "description": "Deletes a Collection.",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "DELETE"
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.collections.get",
                  "description": "Gets a Collection.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}"
                },
                "updateDataConnector": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.collections.updateDataConnector",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector",
                  "httpMethod": "PATCH",
                  "description": "Updates a DataConnector."
                },
                "patch": {
                  "id": "discoveryengine.projects.locations.collections.patch",
                  "description": "Updates a Collection.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}",
                  "httpMethod": "PATCH"
                },
                "list": {
                  "path": "v1alpha/{+parent}/collections",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections",
                  "description": "Gets a list of Collections.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.collections.list"
                },
                "getDataConnector": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Gets the DataConnector. DataConnector is a singleton resource for each Collection.",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.collections.getDataConnector"
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "list": {
                      "path": "v1alpha/{+name}/operations",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/operations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.operations.list"
                    },
                    "get": {
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/operations/{operationsId}",
                      "id": "discoveryengine.projects.locations.collections.operations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "httpMethod": "GET"
                    }
                  }
                },
                "dataConnector": {
                  "methods": {
                    "getConnectorSecret": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:getConnectorSecret",
                      "path": "v1alpha/{+name}:getConnectorSecret",
                      "httpMethod": "GET",
                      "description": "Get the secret for the associated connector.",
                      "id": "discoveryengine.projects.locations.collections.dataConnector.getConnectorSecret",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "checkRefreshToken": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:checkRefreshToken",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}:checkRefreshToken",
                      "deprecated": true,
                      "id": "discoveryengine.projects.locations.collections.dataConnector.checkRefreshToken",
                      "description": "Deprecated: Checks the existence of a refresh token for the EUC user for a given connection and returns its details. Use AcquireAccessToken instead and then check the validity of the returned token by asking the 3rd party system. There's no way to know for sure if a refresh token is valid without asking the 3rd party system.",
                      "httpMethod": "GET"
                    },
                    "acquireAccessToken": {
                      "httpMethod": "POST",
                      "description": "Uses the per-user refresh token minted with AcquireAndStoreRefreshToken to generate and return a new access token and its details. Takes the access token from cache if available. Rotates the stored refresh token if needed. Uses the end user identity to return the user specific access token. Does *not* return the credentials configured by the administrator. Used by action execution and UI.",
                      "id": "discoveryengine.projects.locations.collections.dataConnector.acquireAccessToken",
                      "path": "v1alpha/{+name}:acquireAccessToken",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:acquireAccessToken",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "startConnectorRun": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:startConnectorRun",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.dataConnector.startConnectorRun",
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}:startConnectorRun",
                      "description": "Starts an immediate synchronization process for a DataConnector. Third Party Connector Users must specify which entities should be synced. FHIR Connectors must provide a timestamp to indicate the point in time from which data should be synced."
                    }
                  },
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.list",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations",
                          "path": "v1alpha/{+name}/operations"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations/{operationsId}",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.get",
                          "httpMethod": "GET"
                        }
                      }
                    },
                    "connectorRuns": {
                      "methods": {
                        "list": {
                          "description": "Lists the ConnectorRuns of a DataConnector.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/connectorRuns",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.connectorRuns.list",
                          "path": "v1alpha/{+parent}/connectorRuns"
                        }
                      }
                    }
                  }
                },
                "dataStores": {
                  "methods": {
                    "patch": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.patch",
                      "description": "Updates a DataStore",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}"
                    },
                    "getDocumentProcessingConfig": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets a DocumentProcessingConfig.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.collections.dataStores.getDocumentProcessingConfig"
                    },
                    "deletePatientFilter": {
                      "description": "Deletes the entire patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:deletePatientFilter",
                      "path": "v1alpha/{+dataStore}:deletePatientFilter",
                      "id": "discoveryengine.projects.locations.collections.dataStores.deletePatientFilter",
                      "httpMethod": "POST"
                    },
                    "removePatientFilter": {
                      "description": "Removes a group of patient IDs from the patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the list of patient IDs to remove will be constructed from the direct me[...]",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:removePatientFilter",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+dataStore}:removePatientFilter",
                      "id": "discoveryengine.projects.locations.collections.dataStores.removePatientFilter",
                      "httpMethod": "POST"
                    },
                    "addPatientFilter": {
                      "path": "v1alpha/{+dataStore}:addPatientFilter",
                      "id": "discoveryengine.projects.locations.collections.dataStores.addPatientFilter",
                      "description": "Adds a group of patient IDs as a patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. The filter group must be a FHIR resource name of type Group, and the filter will be constructed from the direct members of the group which are Patient resources.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:addPatientFilter",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST"
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.list",
                      "description": "Lists all the DataStores associated with the project.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores",
                      "path": "v1alpha/{+parent}/dataStores"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.collections.dataStores.delete",
                      "description": "Deletes a DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}"
                    },
                    "updateDocumentProcessingConfig": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.dataStores.updateDocumentProcessingConfig",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                      "description": "Updates the DocumentProcessingConfig. DocumentProcessingConfig is a singleon resource of DataStore. It's empty when DataStore is created. The first call to this method will set up DocumentProcessingConfig.",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH"
                    },
                    "trainCustomModel": {
                      "description": "Trains a custom model.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:trainCustomModel",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.dataStores.trainCustomModel",
                      "path": "v1alpha/{+dataStore}:trainCustomModel",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "replacePatientFilter": {
                      "path": "v1alpha/{+dataStore}:replacePatientFilter",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:replacePatientFilter",
                      "id": "discoveryengine.projects.locations.collections.dataStores.replacePatientFilter",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Replaces the patient filter for the data store. This method is essentially a combination of DeletePatientFilters and AddPatientFilter. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the new filt[...]"
                    },
                    "getSiteSearchEngine": {
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets the SiteSearchEngine.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.getSiteSearchEngine",
                      "httpMethod": "GET"
                    },
                    "completeQuery": {
                      "description": "Completes the specified user input with keyword suggestions.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+dataStore}:completeQuery",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:completeQuery",
                      "id": "discoveryengine.projects.locations.collections.dataStores.completeQuery",
                      "httpMethod": "GET"
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets a DataStore."
                    },
                    "create": {
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}/dataStores",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.dataStores.create",
                      "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately."
                    }
                  },
                  "resources": {
                    "completionSuggestions": {
                      "methods": {
                        "import": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.import",
                          "description": "Imports CompletionSuggestions for a DataStore.",
                          "path": "v1alpha/{+parent}/completionSuggestions:import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:import"
                        },
                        "purge": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                          "path": "v1alpha/{+parent}/completionSuggestions:purge",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.purge",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:purge"
                        }
                      }
                    },
                    "operations": {
                      "methods": {
                        "get": {
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations/{operationsId}"
                        },
                        "list": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.list",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "path": "v1alpha/{+name}/operations",
                          "httpMethod": "GET"
                        }
                      }
                    },
                    "completionConfig": {
                      "methods": {
                        "completeQuery": {
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                          "path": "v1alpha/{+completionConfig}:completeQuery",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud_search.query",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionConfig.completeQuery",
                          "description": "Completes the user input with advanced keyword suggestions."
                        }
                      }
                    },
                    "servingConfigs": {
                      "methods": {
                        "list": {
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.list",
                          "path": "v1alpha/{+parent}/servingConfigs",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "description": "Lists all ServingConfigs linked to this dataStore."
                        },
                        "searchLite": {
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+servingConfig}:searchLite",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.searchLite"
                        },
                        "answer": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                          "path": "v1alpha/{+servingConfig}:answer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "description": "Answer query method.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.answer"
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.create",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                          "path": "v1alpha/{+parent}/servingConfigs"
                        },
                        "search": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                          "description": "Performs a search.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.search",
                          "path": "v1alpha/{+servingConfig}:search",
                          "httpMethod": "POST"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.get",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}"
                        },
                        "delete": {
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.delete"
                        },
                        "recommend": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.recommend",
                          "description": "Makes a recommendation, which requires a contextual user event.",
                          "path": "v1alpha/{+servingConfig}:recommend",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "streamAnswer": {
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                          "httpMethod": "POST",
                          "path": "v1alpha/{+servingConfig}:streamAnswer",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.streamAnswer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.patch",
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}"
                        }
                      }
                    },
                    "suggestionDenyListEntries": {
                      "methods": {
                        "purge": {
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.purge",
                          "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge",
                          "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore."
                        },
                        "import": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                          "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                          "path": "v1alpha/{+parent}/suggestionDenyListEntries:import"
                        }
                      }
                    },
                    "userEvents": {
                      "methods": {
                        "write": {
                          "description": "Writes a single user event.",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/userEvents:write",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:write",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.write"
                        },
                        "import": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:import",
                          "httpMethod": "POST",
                          "path": "v1alpha/{+parent}/userEvents:import",
                          "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "purge": {
                          "path": "v1alpha/{+parent}/userEvents:purge",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:purge",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first."
                        },
                        "collect": {
                          "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.collect",
                          "path": "v1alpha/{+parent}/userEvents:collect",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:collect",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "customModels": {
                      "methods": {
                        "list": {
                          "path": "v1alpha/{+dataStore}/customModels",
                          "description": "Gets a list of all the custom models.",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/customModels",
                          "id": "discoveryengine.projects.locations.collections.dataStores.customModels.list"
                        }
                      }
                    },
                    "controls": {
                      "methods": {
                        "get": {
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.get",
                          "description": "Gets a Control.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}"
                        },
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.delete",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "httpMethod": "DELETE"
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.create",
                          "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                          "httpMethod": "POST",
                          "path": "v1alpha/{+parent}/controls",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "list": {
                          "path": "v1alpha/{+parent}/controls",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Lists all Controls by their parent DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.list"
                        },
                        "patch": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH"
                        }
                      }
                    },
                    "widgetConfigs": {
                      "methods": {
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.widgetConfigs.patch",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Update a WidgetConfig.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                          "path": "v1alpha/{+name}"
                        },
                        "get": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                          "path": "v1alpha/{+name}",
                          "description": "Gets a WidgetConfig.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.widgetConfigs.get",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "branches": {
                      "methods": {
                        "list": {
                          "path": "v1alpha/{+parent}/branches",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches",
                          "httpMethod": "GET",
                          "description": "Lists all Branchs under the specified parent DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.list"
                        },
                        "batchGetDocumentsMetadata": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.batchGetDocumentsMetadata",
                          "httpMethod": "GET",
                          "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/batchGetDocumentsMetadata"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}",
                          "description": "Retrieves a Branch.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.get",
                          "path": "v1alpha/{+name}"
                        }
                      },
                      "resources": {
                        "documents": {
                          "methods": {
                            "purge": {
                              "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+parent}/documents:purge",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.purge",
                              "httpMethod": "POST",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge"
                            },
                            "getProcessedDocument": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}:getProcessedDocument",
                              "path": "v1alpha/{+name}:getProcessedDocument",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.getProcessedDocument",
                              "description": "Gets the parsed layout information for a Document."
                            },
                            "create": {
                              "path": "v1alpha/{+parent}/documents",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "httpMethod": "POST",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.create",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Creates a Document."
                            },
                            "list": {
                              "path": "v1alpha/{+parent}/documents",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.list",
                              "description": "Gets a list of Documents.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            },
                            "patch": {
                              "description": "Updates a Document.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.patch",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "PATCH",
                              "path": "v1alpha/{+name}",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}"
                            },
                            "delete": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.delete",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "httpMethod": "DELETE",
                              "description": "Deletes a Document."
                            },
                            "get": {
                              "description": "Gets a Document.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.get",
                              "path": "v1alpha/{+name}"
                            },
                            "import": {
                              "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated.",
                              "path": "v1alpha/{+parent}/documents:import",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.import",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                              "httpMethod": "POST"
                            }
                          },
                          "resources": {
                            "chunks": {
                              "methods": {
                                "list": {
                                  "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.chunks.list",
                                  "description": "Gets a list of Chunks.",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "path": "v1alpha/{+parent}/chunks",
                                  "httpMethod": "GET"
                                },
                                "get": {
                                  "path": "v1alpha/{+name}",
                                  "description": "Gets a Document.",
                                  "httpMethod": "GET",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks/{chunksId}",
                                  "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.chunks.get",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ]
                                }
                              }
                            }
                          }
                        },
                        "operations": {
                          "methods": {
                            "list": {
                              "path": "v1alpha/{+name}/operations",
                              "httpMethod": "GET",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.list"
                            },
                            "get": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                              "httpMethod": "GET",
                              "path": "v1alpha/{+name}",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            },
                            "cancel": {
                              "httpMethod": "POST",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.cancel",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                              "path": "v1alpha/{+name}:cancel",
                              "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; in[...]"
                            }
                          }
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.list",
                          "description": "Lists all Conversations by their parent DataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "httpMethod": "GET",
                          "path": "v1alpha/{+parent}/conversations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.create",
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                          "path": "v1alpha/{+parent}/conversations",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "get": {
                          "description": "Gets a Conversation.",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}"
                        },
                        "converse": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "description": "Converses a conversation.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.converse",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                          "path": "v1alpha/{+name}:converse"
                        },
                        "delete": {
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "path": "v1alpha/{+name}",
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned."
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.patch",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                          "httpMethod": "PATCH",
                          "path": "v1alpha/{+name}"
                        }
                      }
                    },
                    "schemas": {
                      "methods": {
                        "delete": {
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.delete",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "DELETE",
                          "description": "Deletes a Schema."
                        },
                        "get": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "description": "Gets a Schema.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET"
                        },
                        "list": {
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.list",
                          "path": "v1alpha/{+parent}/schemas",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "description": "Gets a list of Schemas.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.patch",
                          "description": "Updates a Schema.",
                          "httpMethod": "PATCH",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}"
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.create",
                          "description": "Creates a Schema.",
                          "path": "v1alpha/{+parent}/schemas",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      },
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "path": "v1alpha/{+name}/operations",
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.list",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                            },
                            "get": {
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations/{operationsId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.get",
                              "path": "v1alpha/{+name}"
                            }
                          }
                        }
                      }
                    },
                    "siteSearchEngine": {
                      "resources": {
                        "targetSites": {
                          "methods": {
                            "batchCreate": {
                              "httpMethod": "POST",
                              "path": "v1alpha/{+parent}/targetSites:batchCreate",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                              "description": "Creates TargetSite in a batch.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.batchCreate"
                            },
                            "delete": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.delete",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "httpMethod": "DELETE",
                              "description": "Deletes a TargetSite.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}"
                            },
                            "get": {
                              "description": "Gets a TargetSite.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.get",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "GET"
                            },
                            "list": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "path": "v1alpha/{+parent}/targetSites",
                              "description": "Gets a list of TargetSites.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.list"
                            },
                            "patch": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Updates a TargetSite.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.patch",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "PATCH"
                            },
                            "create": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                              "description": "Creates a TargetSite.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.create",
                              "path": "v1alpha/{+parent}/targetSites",
                              "httpMethod": "POST"
                            }
                          },
                          "resources": {
                            "operations": {
                              "methods": {
                                "get": {
                                  "httpMethod": "GET",
                                  "path": "v1alpha/{+name}",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations/{operationsId}",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.get",
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                                },
                                "list": {
                                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                                  "httpMethod": "GET",
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.list",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "path": "v1alpha/{+name}/operations"
                                }
                              }
                            }
                          }
                        },
                        "sitemaps": {
                          "methods": {
                            "fetch": {
                              "httpMethod": "GET",
                              "description": "Fetch Sitemaps in a DataStore.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                              "path": "v1alpha/{+parent}/sitemaps:fetch",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.fetch"
                            },
                            "delete": {
[...]
