{
  "version_module": true,
  "name": "discoveryengine",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "canonicalName": "Discovery Engine",
  "rootUrl": "https://discoveryengine.googleapis.com/",
  "ownerDomain": "google.com",
  "revision": "20260418",
  "resources": {
    "billingAccounts": {
      "resources": {
        "billingAccountLicenseConfigs": {
          "methods": {
            "distributeLicenseConfig": {
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.distributeLicenseConfig",
              "path": "v1alpha/{+billingAccountLicenseConfig}:distributeLicenseConfig",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "description": "Distributes a LicenseConfig from billing account level to project level.",
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}:distributeLicenseConfig"
            },
            "retractLicenseConfig": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.retractLicenseConfig",
              "path": "v1alpha/{+billingAccountLicenseConfig}:retractLicenseConfig",
              "httpMethod": "POST",
              "description": "This method is called from the billing account side to retract the LicenseConfig from the given project back to the billing account.",
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}:retractLicenseConfig"
            },
            "list": {
              "description": "Lists all BillingAccountLicenseConfigs for a given billing account.",
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.list",
              "path": "v1alpha/{+parent}/billingAccountLicenseConfigs",
              "httpMethod": "GET"
            },
            "get": {
              "description": "Gets a BillingAccountLicenseConfig.",
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}",
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ]
            }
          }
        }
      }
    },
    "projects": {
      "methods": {
        "patch": {
          "flatPath": "v1alpha/projects/{projectsId}",
          "description": "Updates the editable settings of a Discovery Engine Project.",
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "id": "discoveryengine.projects.patch",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite",
            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite",
            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
          ],
          "id": "discoveryengine.projects.get",
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "description": "Gets a Project. Returns NOT_FOUND when the project is not yet created.",
          "flatPath": "v1alpha/projects/{projectsId}"
        },
        "provision": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite",
            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
          ],
          "id": "discoveryengine.projects.provision",
          "path": "v1alpha/{+name}:provision",
          "httpMethod": "POST",
          "description": "Provisions the project resource. During the process, related systems will get prepared and initialized. Caller must read the [Terms for data use](https://cloud.google.com/retail/data-use-terms), and optionally specify in request to provide consent to that service terms.",
          "flatPath": "v1alpha/projects/{projectsId}:provision"
        },
        "reportConsentChange": {
          "flatPath": "v1alpha/projects/{projectsId}:reportConsentChange",
          "description": "Updates service terms for this project. This method can be used to retroactively accept the latest terms. Terms available for update: * [Terms for data use](https://cloud.google.com/retail/data-use-terms)",
          "path": "v1alpha/{+project}:reportConsentChange",
          "httpMethod": "POST",
          "id": "discoveryengine.projects.reportConsentChange",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite",
            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
          ]
        }
      },
      "resources": {
        "locations": {
          "methods": {
            "removeDedicatedCrawlRate": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "id": "discoveryengine.projects.locations.removeDedicatedCrawlRate",
              "path": "v1alpha/{+location}:removeDedicatedCrawlRate",
              "httpMethod": "POST",
              "description": "Removes the dedicated crawl rate for a craw_rate_scope. If the dedicated crawl rate was set, this will disable vertex AI's crawl bot from using the dedicated crawl rate for crawling. If the dedicated crawl rate was not set, this is a no-op.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:removeDedicatedCrawlRate"
            },
            "updateCmekConfig": {
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "id": "discoveryengine.projects.locations.updateCmekConfig",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfig",
              "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location."
            },
            "updateAclConfig": {
              "id": "discoveryengine.projects.locations.updateAclConfig",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "description": "Default ACL configuration for use in a location of a customer's project. Updates will only reflect to new data stores. Existing data stores will still use the old value.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/aclConfig"
            },
            "getAclConfig": {
              "description": "Gets the AclConfig.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/aclConfig",
              "id": "discoveryengine.projects.locations.getAclConfig",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ]
            },
            "completeExternalIdentities": {
              "description": "This method provides suggestions for users and groups managed in an external identity provider, based on the provided prefix.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:completeExternalIdentities",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "id": "discoveryengine.projects.locations.completeExternalIdentities",
              "path": "v1alpha/{+parent}:completeExternalIdentities",
              "httpMethod": "GET"
            },
            "setUpDataConnector": {
              "description": "Creates a Collection and sets up the DataConnector for it. To stop a DataConnector after setup, use the CollectionService.DeleteCollection method.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setUpDataConnector",
              "id": "discoveryengine.projects.locations.setUpDataConnector",
              "path": "v1alpha/{+parent}:setUpDataConnector",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ]
            },
            "estimateDataSize": {
              "id": "discoveryengine.projects.locations.estimateDataSize",
              "path": "v1alpha/{+location}:estimateDataSize",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "description": "Estimates the data size to be used by a customer.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:estimateDataSize"
            },
            "getCmekConfig": {
              "description": "Gets the CmekConfig.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfig",
              "id": "discoveryengine.projects.locations.getCmekConfig",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ]
            },
            "setUpDataConnectorV2": {
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setUpDataConnectorV2",
              "description": "Creates a Collection and sets up the DataConnector for it. To stop a DataConnector after setup, use the CollectionService.DeleteCollection method.",
              "path": "v1alpha/{+parent}:setUpDataConnectorV2",
              "httpMethod": "POST",
              "id": "discoveryengine.projects.locations.setUpDataConnectorV2",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ]
            },
            "setDedicatedCrawlRate": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "path": "v1alpha/{+location}:setDedicatedCrawlRate",
              "httpMethod": "POST",
              "id": "discoveryengine.projects.locations.setDedicatedCrawlRate",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setDedicatedCrawlRate",
              "description": "Sets the dedicated crawl rate for a crawl_rate_scope. If the dedicated crawl rate was not set, this will enable vertex AI's crawl bot to use the new dedicated crawl rate for crawling. If the dedicated crawl rate was set, vertex AI's crawl bot will try to update the rate to the new value. If the new value is too high, the crawl bot may crawl at a lower rate to avoid overloading the user's website."
            },
            "obtainCrawlRate": {
              "id": "discoveryengine.projects.locations.obtainCrawlRate",
              "path": "v1alpha/{+location}:obtainCrawlRate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "description": "Obtains the time series data of organic or dedicated crawl rate for monitoring. When dedicated crawl rate is not set, it will return vertex AI's organic crawl rate time series. Organic crawl means Google automatically crawl the internet at its own convenience. When dedicated crawl rate is set, it will return vertex AI's dedicated crawl rate time series.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:obtainCrawlRate"
            },
            "queryConfigurablePricingUsageStats": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "id": "discoveryengine.projects.locations.queryConfigurablePricingUsageStats",
              "path": "v1alpha/{+project}/locations/{location}:queryConfigurablePricingUsageStats",
              "httpMethod": "GET",
              "description": "Queries configurable pricing usage stats for a project.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{location}:queryConfigurablePricingUsageStats"
            }
          },
          "resources": {
            "evaluations": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}/operations/{operationsId}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.evaluations.operations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                }
              },
              "methods": {
                "list": {
                  "path": "v1alpha/{+parent}/evaluations",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.evaluations.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "description": "Gets a list of Evaluations."
                },
                "get": {
                  "description": "Gets a Evaluation.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}",
                  "id": "discoveryengine.projects.locations.evaluations.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "create": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "description": "Creates a Evaluation. Upon creation, the evaluation will be automatically triggered and begin execution.",
                  "path": "v1alpha/{+parent}/evaluations",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.evaluations.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "listResults": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}:listResults",
                  "description": "Gets a list of results for a given a Evaluation.",
                  "path": "v1alpha/{+evaluation}:listResults",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.evaluations.listResults",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                }
              }
            },
            "userStores": {
              "resources": {
                "operations": {
                  "methods": {
                    "list": {
                      "id": "discoveryengine.projects.locations.userStores.operations.list",
                      "path": "v1alpha/{+name}/operations",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/operations"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.userStores.operations.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/operations/{operationsId}"
                    }
                  }
                },
                "licenseConfigsUsageStats": {
                  "methods": {
                    "list": {
                      "path": "v1alpha/{+parent}/licenseConfigsUsageStats",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.userStores.licenseConfigsUsageStats.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/licenseConfigsUsageStats",
                      "description": "Lists all the LicenseConfigUsageStatss associated with the project."
                    }
                  }
                },
                "userLicenses": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/userLicenses",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.userStores.userLicenses.list",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/userLicenses",
                      "description": "Lists the User Licenses."
                    }
                  }
                }
              },
              "methods": {
                "batchUpdateUserLicenses": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.userStores.batchUpdateUserLicenses",
                  "path": "v1alpha/{+parent}:batchUpdateUserLicenses",
                  "httpMethod": "POST",
                  "description": "Updates the User License. This method is used for batch assign/unassign licenses to users.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}:batchUpdateUserLicenses"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.userStores.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "description": "Gets the User Store.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.userStores.patch",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "description": "Updates the User Store."
                }
              }
            },
            "identityMappingStores": {
              "resources": {
                "operations": {
                  "methods": {
                    "list": {
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.list",
                      "path": "v1alpha/{+name}/operations",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations/{operationsId}"
                    }
                  }
                }
              },
              "methods": {
                "get": {
                  "id": "discoveryengine.projects.locations.identityMappingStores.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets the Identity Mapping Store.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}"
                },
                "importIdentityMappings": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:importIdentityMappings",
                  "description": "Imports a list of Identity Mapping Entries to an Identity Mapping Store.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+identityMappingStore}:importIdentityMappings",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.identityMappingStores.importIdentityMappings"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.delete",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "description": "Deletes the Identity Mapping Store.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}"
                },
                "list": {
                  "description": "Lists all Identity Mapping Stores.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "id": "discoveryengine.projects.locations.identityMappingStores.list",
                  "path": "v1alpha/{+parent}/identityMappingStores",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "create": {
                  "id": "discoveryengine.projects.locations.identityMappingStores.create",
                  "path": "v1alpha/{+parent}/identityMappingStores",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Creates a new Identity Mapping Store.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores"
                },
                "listIdentityMappings": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.listIdentityMappings",
                  "path": "v1alpha/{+identityMappingStore}:listIdentityMappings",
                  "httpMethod": "GET",
                  "description": "Lists Identity Mappings in an Identity Mapping Store.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:listIdentityMappings"
                },
                "purgeIdentityMappings": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+identityMappingStore}:purgeIdentityMappings",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.identityMappingStores.purgeIdentityMappings",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:purgeIdentityMappings",
                  "description": "Purges specified or all Identity Mapping Entries from an Identity Mapping Store."
                }
              }
            },
            "licenseConfigs": {
              "methods": {
                "get": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.licenseConfigs.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}",
                  "description": "Gets a LicenseConfig."
                },
                "create": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs",
                  "description": "Creates a LicenseConfig This method should only be used for creating NotebookLm licenses or Gemini Enterprise free trial licenses.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/licenseConfigs",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.licenseConfigs.create"
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.licenseConfigs.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}",
                  "description": "Updates the LicenseConfig"
                }
              }
            },
            "notebooks": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.notebooks.create",
                  "path": "v1alpha/{+parent}/notebooks",
                  "httpMethod": "POST",
                  "description": "Creates a notebook.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks"
                },
                "listRecentlyViewed": {
                  "path": "v1alpha/{+parent}/notebooks:listRecentlyViewed",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.notebooks.listRecentlyViewed",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks:listRecentlyViewed",
                  "description": "Lists the notebooks ordered by last view time."
                },
                "batchDelete": {
                  "description": "Batch deletes Notebooks.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks:batchDelete",
                  "id": "discoveryengine.projects.locations.notebooks.batchDelete",
                  "path": "v1alpha/{+parent}/notebooks:batchDelete",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.notebooks.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "description": "Gets a notebook.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}"
                },
                "share": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.notebooks.share",
                  "path": "v1alpha/{+name}:share",
                  "httpMethod": "POST",
                  "description": "Shares a notebook to other accounts.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}:share"
                }
              },
              "resources": {
                "audioOverviews": {
                  "methods": {
                    "create": {
                      "description": "Generates a new audio overview.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/audioOverviews",
                      "id": "discoveryengine.projects.locations.notebooks.audioOverviews.create",
                      "path": "v1alpha/{+parent}/audioOverviews",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "delete": {
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.notebooks.audioOverviews.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/audioOverviews/{audioOverviewsId}",
                      "description": "Deletes an audio overview."
                    }
                  }
                },
                "sources": {
                  "methods": {
                    "batchDelete": {
                      "description": "Deletes multiple sources",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/sources:batchDelete",
                      "id": "discoveryengine.projects.locations.notebooks.sources.batchDelete",
                      "path": "v1alpha/{+parent}/sources:batchDelete",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "get": {
                      "description": "Gets a Source.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/sources/{sourcesId}",
                      "id": "discoveryengine.projects.locations.notebooks.sources.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "batchCreate": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/sources:batchCreate",
                      "description": "Creates a list of Sources.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/sources:batchCreate",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.notebooks.sources.batchCreate"
                    }
                  }
                }
              }
            },
            "groundingConfigs": {
              "methods": {
                "check": {
                  "path": "v1alpha/{+groundingConfig}:check",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.groundingConfigs.check",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/groundingConfigs/{groundingConfigsId}:check",
                  "description": "Performs a grounding check."
                }
              }
            },
            "authorizations": {
              "methods": {
                "create": {
                  "description": "Creates an Authorization.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations",
                  "id": "discoveryengine.projects.locations.authorizations.create",
                  "path": "v1alpha/{+parent}/authorizations",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.authorizations.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "description": "Updates an Authorization"
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.authorizations.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "description": "Gets an Authorization."
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "id": "discoveryengine.projects.locations.authorizations.delete",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "description": "Deletes an Authorization."
                },
                "list": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations",
                  "description": "Lists all Authorizations under an Engine.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/authorizations",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.authorizations.list"
                }
              }
            },
            "dataStores": {
              "methods": {
                "addPatientFilter": {
                  "description": "Adds a group of patient IDs as a patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. The filter group must be a FHIR resource name of type Group, and the filter will be constructed from the direct members of the group which are Patient resources.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:addPatientFilter",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.addPatientFilter",
                  "path": "v1alpha/{+dataStore}:addPatientFilter",
                  "httpMethod": "POST"
                },
                "removePatientFilter": {
                  "description": "Removes a group of patient IDs from the patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the list of patient IDs to remove will be constructed from the direct member[...]",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:removePatientFilter",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.removePatientFilter",
                  "path": "v1alpha/{+dataStore}:removePatientFilter",
                  "httpMethod": "POST"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "description": "Updates a DataStore",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}"
                },
                "getSiteSearchEngine": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.getSiteSearchEngine",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "description": "Gets the SiteSearchEngine.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine"
                },
                "delete": {
                  "description": "Deletes a DataStore.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.delete",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "description": "Lists all the DataStores associated with the project.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "id": "discoveryengine.projects.locations.dataStores.list",
                  "path": "v1alpha/{+parent}/dataStores",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "create": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/dataStores",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.dataStores.create"
                },
                "completeQuery": {
                  "id": "discoveryengine.projects.locations.dataStores.completeQuery",
                  "path": "v1alpha/{+dataStore}:completeQuery",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Completes the specified user input with keyword suggestions.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:completeQuery"
                },
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "description": "Gets a DataStore.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.dataStores.get"
                },
                "replacePatientFilter": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:replacePatientFilter",
                  "description": "Replaces the patient filter for the data store. This method is essentially a combination of DeletePatientFilters and AddPatientFilter. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the new filter w[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+dataStore}:replacePatientFilter",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.dataStores.replacePatientFilter"
                },
                "deletePatientFilter": {
                  "id": "discoveryengine.projects.locations.dataStores.deletePatientFilter",
                  "path": "v1alpha/{+dataStore}:deletePatientFilter",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Deletes the entire patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:deletePatientFilter"
                },
                "getDocumentProcessingConfig": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.dataStores.getDocumentProcessingConfig",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                  "description": "Gets a DocumentProcessingConfig."
                },
                "updateDocumentProcessingConfig": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                  "description": "Updates the DocumentProcessingConfig. DocumentProcessingConfig is a singleon resource of DataStore. It's empty when DataStore is created. The first call to this method will set up DocumentProcessingConfig.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.dataStores.updateDocumentProcessingConfig",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                }
              },
              "resources": {
                "sessions": {
                  "methods": {
                    "list": {
                      "path": "v1alpha/{+parent}/sessions",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "description": "Lists all Sessions by their parent DataStore."
                    },
                    "delete": {
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned."
                    },
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "description": "Gets a Session.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.get"
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.sessions.patch",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.sessions.create",
                      "path": "v1alpha/{+parent}/sessions",
                      "httpMethod": "POST",
                      "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions"
                    }
                  },
                  "resources": {
                    "answers": {
                      "methods": {
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.sessions.answers.get",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                          "description": "Gets a Answer."
                        }
                      }
                    }
                  }
                },
                "branches": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "cancel": {
                          "path": "v1alpha/{+name}:cancel",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.cancel",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instea[...]"
                        },
                        "get": {
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}/operations",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.list",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                        }
                      }
                    },
                    "documents": {
                      "resources": {
                        "chunks": {
                          "methods": {
                            "get": {
                              "description": "Gets a Document.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks/{chunksId}",
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.get",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            },
                            "list": {
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.list",
                              "path": "v1alpha/{+parent}/chunks",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets a list of Chunks.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks"
                            }
                          }
                        }
                      },
                      "methods": {
                        "patch": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "description": "Updates a Document.",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "getProcessedDocument": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.getProcessedDocument",
                          "path": "v1alpha/{+name}:getProcessedDocument",
                          "httpMethod": "GET",
                          "description": "Gets the parsed layout information for a Document.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}:getProcessedDocument"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "description": "Gets a Document.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}"
                        },
                        "import": {
                          "path": "v1alpha/{+parent}/documents:import",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                          "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated."
                        },
                        "delete": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "description": "Deletes a Document.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.delete"
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/documents",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.list",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "description": "Gets a list of Documents."
                        },
                        "purge": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                          "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/documents:purge",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.purge"
                        },
                        "create": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "description": "Creates a Document.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/documents",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.create"
                        }
                      }
                    }
                  },
                  "methods": {
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}",
                      "description": "Retrieves a Branch.",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.branches.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/branches",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.branches.list",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches",
                      "description": "Lists all Branchs under the specified parent DataStore."
                    },
                    "batchGetDocumentsMetadata": {
                      "path": "v1alpha/{+parent}/batchGetDocumentsMetadata",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.branches.batchGetDocumentsMetadata",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                      "description": "Gets index freshness metadata for Documents. Supported for website search only."
                    }
                  }
                },
                "suggestionDenyListEntries": {
                  "methods": {
                    "import": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.import",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:import",
                      "httpMethod": "POST",
                      "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import"
                    },
                    "purge": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.purge",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge",
                      "httpMethod": "POST",
                      "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge"
                    }
                  }
                },
                "completionSuggestions": {
                  "methods": {
                    "import": {
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.import",
                      "path": "v1alpha/{+parent}/completionSuggestions:import",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Imports CompletionSuggestions for a DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:import"
                    },
                    "purge": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                      "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/completionSuggestions:purge",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.purge"
                    }
                  }
                },
                "completionConfig": {
                  "methods": {
                    "completeQuery": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud_search.query",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.completionConfig.completeQuery",
                      "path": "v1alpha/{+completionConfig}:completeQuery",
                      "httpMethod": "POST",
                      "description": "Completes the user input with advanced keyword suggestions.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionConfig:completeQuery"
                    }
                  }
                },
                "models": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations",
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.list",
                          "path": "v1alpha/{+name}/operations",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "get": {
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET"
                        }
                      }
                    }
                  }
                },
                "widgetConfigs": {
                  "methods": {
                    "patch": {
                      "description": "Update a WidgetConfig.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.patch",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "description": "Gets a WidgetConfig.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}"
                    }
                  }
                },
                "servingConfigs": {
                  "methods": {
                    "search": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                      "description": "Performs a search.",
                      "path": "v1alpha/{+servingConfig}:search",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.search",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "answer": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                      "description": "Answer query method.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+servingConfig}:answer",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.answer"
                    },
                    "streamAnswer": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+servingConfig}:streamAnswer",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.streamAnswer",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                      "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream."
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}"
                    },
                    "searchLite": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+servingConfig}:searchLite",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.searchLite",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                      "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, it i[...]"
                    },
                    "create": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.create"
                    },
                    "recommend": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.recommend",
                      "path": "v1alpha/{+servingConfig}:recommend",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Makes a recommendation, which requires a contextual user event.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend"
                    },
                    "delete": {
                      "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.delete",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "list": {
                      "description": "Lists all ServingConfigs linked to this dataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.list",
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.patch",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist."
                    }
                  }
                },
                "userEvents": {
                  "methods": {
                    "write": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/userEvents:write",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.write",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:write",
                      "description": "Writes a single user event."
                    },
                    "import": {
                      "path": "v1alpha/{+parent}/userEvents:import",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:import",
                      "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata."
                    },
                    "collect": {
                      "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:collect",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.collect",
                      "path": "v1alpha/{+parent}/userEvents:collect",
                      "httpMethod": "GET"
                    },
                    "purge": {
                      "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.purge",
                      "path": "v1alpha/{+parent}/userEvents:purge",
                      "httpMethod": "POST"
                    }
                  }
                },
                "conversations": {
                  "methods": {
                    "create": {
                      "path": "v1alpha/{+parent}/conversations",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned."
                    },
                    "converse": {
                      "id": "discoveryengine.projects.locations.dataStores.conversations.converse",
                      "path": "v1alpha/{+name}:converse",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Converses a conversation.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse"
                    },
                    "delete": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.delete"
                    },
                    "list": {
                      "description": "Lists all Conversations by their parent DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.list",
                      "path": "v1alpha/{+parent}/conversations",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "patch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "get": {
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "description": "Gets a Conversation."
                    }
                  }
                },
                "controls": {
                  "methods": {
                    "create": {
                      "path": "v1alpha/{+parent}/controls",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.controls.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned."
                    },
                    "delete": {
                      "id": "discoveryengine.projects.locations.dataStores.controls.delete",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}"
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.controls.list",
                      "path": "v1alpha/{+parent}/controls",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists all Controls by their parent DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls"
                    },
                    "patch": {
                      "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "id": "discoveryengine.projects.locations.dataStores.controls.patch",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "description": "Gets a Control.",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.controls.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                },
                "schemas": {
                  "methods": {
                    "patch": {
                      "description": "Updates a Schema.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.patch",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a Schema.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}"
                    },
                    "delete": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "description": "Deletes a Schema.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.delete"
                    },
                    "list": {
                      "description": "Gets a list of Schemas.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.schemas.list",
                      "path": "v1alpha/{+parent}/schemas",
                      "httpMethod": "GET"
                    },
                    "create": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "description": "Creates a Schema.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/schemas",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.create"
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "list": {
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations",
                      "id": "discoveryengine.projects.locations.dataStores.operations.list",
                      "path": "v1alpha/{+name}/operations",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.operations.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations/{operationsId}"
                    }
                  }
                },
                "siteSearchEngine": {
                  "resources": {
                    "targetSites": {
                      "methods": {
                        "get": {
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "description": "Gets a TargetSite."
                        },
                        "patch": {
                          "description": "Updates a TargetSite.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.patch",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH"
                        },
                        "list": {
                          "description": "Gets a list of TargetSites.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.list",
                          "path": "v1alpha/{+parent}/targetSites",
                          "httpMethod": "GET"
                        },
                        "delete": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.delete",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a TargetSite.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}"
                        },
                        "create": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "description": "Creates a TargetSite.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/targetSites",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.create"
                        },
                        "batchCreate": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/targetSites:batchCreate",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.batchCreate",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                          "description": "Creates TargetSite in a batch."
                        }
                      }
                    },
                    "sitemaps": {
                      "methods": {
                        "create": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps",
                          "description": "Creates a Sitemap.",
                          "path": "v1alpha/{+parent}/sitemaps",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "fetch": {
                          "description": "Fetch Sitemaps in a DataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.fetch",
                          "path": "v1alpha/{+parent}/sitemaps:fetch",
                          "httpMethod": "GET"
                        },
                        "delete": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}",
                          "description": "Deletes a Sitemap.",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        }
                      }
                    }
                  },
                  "methods": {
                    "enableAdvancedSiteSearch": {
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.enableAdvancedSiteSearch",
                      "path": "v1alpha/{+siteSearchEngine}:enableAdvancedSiteSearch",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Upgrade from basic site search to advanced site search.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch"
                    },
                    "disableAdvancedSiteSearch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+siteSearchEngine}:disableAdvancedSiteSearch",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.disableAdvancedSiteSearch",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                      "description": "Downgrade from advanced site search to basic site search."
                    },
                    "recrawlUris": {
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.recrawlUris",
                      "path": "v1alpha/{+siteSearchEngine}:recrawlUris",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Request on-demand recrawl for a list of URIs.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris"
                    }
                  }
                }
              }
            },
            "cmekConfigs": {
              "methods": {
                "list": {
                  "description": "Lists all the CmekConfigs with the project.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.cmekConfigs.list",
                  "path": "v1alpha/{+parent}/cmekConfigs",
                  "httpMethod": "GET"
                },
                "delete": {
                  "id": "discoveryengine.projects.locations.cmekConfigs.delete",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "De-provisions a CmekConfig.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.cmekConfigs.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "description": "Gets the CmekConfig.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}"
                },
                "patch": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.cmekConfigs.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                }
              }
            },
            "requirements": {
              "methods": {
                "checkRequirement": {
                  "description": "Check a particular requirement.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/requirements:checkRequirement",
                  "id": "discoveryengine.projects.locations.requirements.checkRequirement",
                  "path": "v1alpha/{+location}/requirements:checkRequirement",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                }
              }
            },
            "operations": {
              "methods": {
                "list": {
                  "id": "discoveryengine.projects.locations.operations.list",
                  "path": "v1alpha/{+name}/operations",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.operations.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}"
                }
              }
            },
            "podcasts": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.podcasts.operations.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/podcasts/{podcastsId}/operations/{operationsId}"
                    }
                  }
                }
              }
            },
            "sampleQuerySets": {
              "methods": {
                "create": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets",
                  "description": "Creates a SampleQuerySet",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/sampleQuerySets",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.create"
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "description": "Gets a SampleQuerySet."
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "description": "Updates a SampleQuerySet."
                },
                "list": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets",
                  "description": "Gets a list of SampleQuerySets.",
                  "path": "v1alpha/{+parent}/sampleQuerySets",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "description": "Deletes a SampleQuerySet."
                }
              },
              "resources": {
                "sampleQueries": {
                  "methods": {
                    "create": {
                      "path": "v1alpha/{+parent}/sampleQueries",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries",
                      "description": "Creates a SampleQuery"
                    },
                    "patch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "description": "Updates a SampleQuery.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.patch"
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a SampleQuery.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}"
                    },
                    "import": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries:import",
                      "description": "Bulk import of multiple SampleQuerys. Sample queries that already exist may be deleted. Note: It is possible for a subset of the SampleQuerys to be successfully imported.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/sampleQueries:import",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.import"
                    },
                    "delete": {
                      "description": "Deletes a SampleQuery.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.delete",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/sampleQueries",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.list",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries",
                      "description": "Gets a list of SampleQuerys."
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.sampleQuerySets.operations.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/operations/{operationsId}"
                    }
                  }
                }
              }
            },
            "userEvents": {
              "methods": {
                "write": {
                  "description": "Writes a single user event.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:write",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.userEvents.write",
                  "path": "v1alpha/{+parent}/userEvents:write",
                  "httpMethod": "POST"
                },
                "import": {
                  "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:import",
                  "id": "discoveryengine.projects.locations.userEvents.import",
                  "path": "v1alpha/{+parent}/userEvents:import",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "collect": {
                  "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:collect",
                  "id": "discoveryengine.projects.locations.userEvents.collect",
                  "path": "v1alpha/{+parent}/userEvents:collect",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                }
              }
            },
            "collections": {
              "resources": {
                "dataConnector": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "path": "v1alpha/{+name}/operations",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.get",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations/{operationsId}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                        }
                      }
                    },
                    "connectorRuns": {
                      "methods": {
                        "list": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/connectorRuns",
                          "description": "Lists the ConnectorRuns of a DataConnector.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/connectorRuns",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.connectorRuns.list"
                        }
                      }
                    }
                  },
                  "methods": {
                    "checkRefreshToken": {
                      "deprecated": true,
                      "description": "Deprecated: Checks the existence of a refresh token for the EUC user for a given connection and returns its details. Use AcquireAccessToken instead and then check the validity of the returned token by asking the 3rd party system. There's no way to know for sure if a refresh token is valid without asking the 3rd party system.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:checkRefreshToken",
                      "id": "discoveryengine.projects.locations.collections.dataConnector.checkRefreshToken",
                      "path": "v1alpha/{+name}:checkRefreshToken",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "acquireAccessToken": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}:acquireAccessToken",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.dataConnector.acquireAccessToken",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:acquireAccessToken",
                      "description": "Uses the per-user refresh token minted with AcquireAndStoreRefreshToken to generate and return a new access token and its details. Takes the access token from cache if available. Rotates the stored refresh token if needed. Uses the end user identity to return the user specific access token. Does *not* return the credentials configured by the administrator. Used by action execution and UI."
                    },
                    "startConnectorRun": {
                      "id": "discoveryengine.projects.locations.collections.dataConnector.startConnectorRun",
                      "path": "v1alpha/{+parent}:startConnectorRun",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Starts an immediate synchronization process for a DataConnector. Third Party Connector Users must specify which entities should be synced. FHIR Connectors must provide a timestamp to indicate the point in time from which data should be synced.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:startConnectorRun"
                    },
                    "getConnectorSecret": {
                      "id": "discoveryengine.projects.locations.collections.dataConnector.getConnectorSecret",
                      "path": "v1alpha/{+name}:getConnectorSecret",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Get the secret for the associated connector.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:getConnectorSecret"
                    },
                    "mcp": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/mcp",
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.collections.dataConnector.mcp",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/mcp",
                      "description": "ServeMcpDeleteRequest serves a MCP DELETE request."
                    }
                  }
                },
                "engines": {
                  "methods": {
                    "tune": {
                      "description": "Tunes an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:tune",
                      "id": "discoveryengine.projects.locations.collections.engines.tune",
                      "path": "v1alpha/{+name}:tune",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "create": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines",
                      "description": "Creates an Engine.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/engines",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.engines.create"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.engines.list",
                      "path": "v1alpha/{+parent}/engines",
                      "httpMethod": "GET",
                      "description": "Lists all the Engines associated with the project.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines"
                    },
                    "getWorkspaceSettings": {
                      "id": "discoveryengine.projects.locations.collections.engines.getWorkspaceSettings",
                      "path": "v1alpha/{+name}:getWorkspaceSettings",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Get Workspace settings for the end user.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:getWorkspaceSettings"
                    },
                    "delete": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "description": "Deletes an Engine.",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.collections.engines.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "setIamPolicy": {
                      "path": "v1alpha/{+resource}:setIamPolicy",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.engines.setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:setIamPolicy",
                      "description": "Sets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. **Important:** When setting a policy directly on an Engine resource, the only recommended roles in the bindings are: `roles/discoveryengine.user` and `roles/discoveryengine.agentspaceUser`. Attempting to grant any other role will result in a warning in logging."
                    },
                    "resume": {
                      "id": "discoveryengine.projects.locations.collections.engines.resume",
                      "path": "v1alpha/{+name}:resume",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Resumes the training of an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:resume"
                    },
                    "patch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "description": "Updates an Engine",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.collections.engines.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "pause": {
                      "path": "v1alpha/{+name}:pause",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.engines.pause",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:pause",
                      "description": "Pauses the training of an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION."
                    },
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "description": "Gets an Engine.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.collections.engines.get"
                    },
                    "getIamPolicy": {
                      "description": "Gets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. An empty policy is returned if the resource exists but does not have a policy set on it.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:getIamPolicy",
                      "id": "discoveryengine.projects.locations.collections.engines.getIamPolicy",
                      "path": "v1alpha/{+resource}:getIamPolicy",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  },
                  "resources": {
                    "servingConfigs": {
                      "methods": {
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.patch",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}"
                        },
                        "delete": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}",
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.delete"
                        },
                        "list": {
                          "description": "Lists all ServingConfigs linked to this dataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.list",
                          "path": "v1alpha/{+parent}/servingConfigs",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "create": {
                          "path": "v1alpha/{+parent}/servingConfigs",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs",
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned."
                        },
                        "recommend": {
                          "path": "v1alpha/{+servingConfig}:recommend",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.recommend",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:recommend",
                          "description": "Makes a recommendation, which requires a contextual user event."
                        },
                        "searchLite": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:searchLite",
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+servingConfig}:searchLite",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.searchLite"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}"
                        },
                        "streamAnswer": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:streamAnswer",
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                          "path": "v1alpha/{+servingConfig}:streamAnswer",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.streamAnswer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "search": {
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.search",
                          "path": "v1alpha/{+servingConfig}:search",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Performs a search.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:search"
                        },
                        "answer": {
                          "description": "Answer query method.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:answer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.answer",
                          "path": "v1alpha/{+servingConfig}:answer",
                          "httpMethod": "POST"
                        }
                      }
                    },
                    "operations": {
                      "methods": {
                        "list": {
                          "path": "v1alpha/{+name}/operations",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.engines.operations.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.engines.operations.get",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/operations/{operationsId}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                        }
                      }
                    },
                    "controls": {
                      "methods": {
                        "create": {
                          "path": "v1alpha/{+parent}/controls",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.controls.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls",
                          "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned."
                        },
                        "get": {
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.engines.controls.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls/{controlsId}",
                          "description": "Gets a Control."
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.engines.controls.patch",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls/{controlsId}"
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.controls.list",
                          "path": "v1alpha/{+parent}/controls",
                          "httpMethod": "GET",
                          "description": "Lists all Controls by their parent DataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls"
                        },
                        "delete": {
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.engines.controls.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls/{controlsId}",
                          "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned."
                        }
                      }
                    },
                    "completionConfig": {
                      "methods": {
                        "completeQuery": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud_search.query",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+completionConfig}:completeQuery",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.completionConfig.completeQuery",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/completionConfig:completeQuery",
                          "description": "Completes the user input with advanced keyword suggestions."
                        },
                        "removeSuggestion": {
                          "description": "Removes the search history suggestion in an engine for a user. This will remove the suggestion from being returned in the AdvancedCompleteQueryResponse.recent_search_suggestions for this user. If the user searches the same suggestion again, the new history will override and suggest this suggestion again.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/completionConfig:removeSuggestion",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.completionConfig.removeSuggestion",
                          "path": "v1alpha/{+completionConfig}:removeSuggestion",
                          "httpMethod": "POST"
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.patch",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.get",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}",
                          "description": "Gets a Conversation."
                        },
                        "delete": {
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}",
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned."
                        },
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.list",
                          "path": "v1alpha/{+parent}/conversations",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists all Conversations by their parent DataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations"
                        },
                        "create": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations",
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/conversations",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.create"
                        },
                        "converse": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}:converse",
                          "description": "Converses a conversation.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}:converse",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.converse"
                        }
                      }
                    },
                    "widgetConfigs": {
                      "methods": {
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.widgetConfigs.patch",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "description": "Update a WidgetConfig.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/widgetConfigs/{widgetConfigsId}"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.widgetConfigs.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "description": "Gets a WidgetConfig.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/widgetConfigs/{widgetConfigsId}"
                        }
                      }
                    },
                    "assistants": {
                      "resources": {
                        "agents": {
                          "methods": {
                            "create": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.create",
                              "path": "v1alpha/{+parent}/agents",
                              "httpMethod": "POST",
                              "description": "Creates an Agent.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents"
                            },
                            "get": {
                              "path": "v1alpha/{+name}",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}",
                              "description": "Gets an Agent."
                            },
                            "patch": {
                              "path": "v1alpha/{+name}",
                              "httpMethod": "PATCH",
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.patch",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}",
                              "description": "Updates an Agent"
                            },
                            "list": {
                              "description": "Lists all Agents under an Assistant which were created by the caller.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.list",
                              "path": "v1alpha/{+parent}/agents",
                              "httpMethod": "GET"
                            },
                            "delete": {
                              "description": "Deletes an Agent.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}",
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.delete",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "DELETE",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            }
                          },
                          "resources": {
                            "operations": {
                              "methods": {
                                "get": {
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/operations/{operationsId}",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                                  ],
                                  "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.operations.get",
                                  "path": "v1alpha/{+name}",
                                  "httpMethod": "GET"
                                }
                              }
                            },
                            "files": {
                              "methods": {
                                "import": {
                                  "description": "Imports a file to an Agent. Currently only No-Code agents are supported.",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/files:import",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                                  ],
[...]
