{
  "canonicalName": "Discovery Engine",
  "title": "Discovery Engine API",
  "fullyEncodeReservedExpansion": true,
  "version_module": true,
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "servicePath": "",
  "id": "discoveryengine:v1beta",
  "name": "discoveryengine",
  "revision": "20260418",
  "ownerName": "Google",
  "basePath": "",
  "description": "Discovery Engine API.",
  "version": "v1beta",
  "ownerDomain": "google.com",
  "baseUrl": "https://discoveryengine.googleapis.com/",
  "batchPath": "batch",
  "resources": {
    "billingAccounts": {
      "resources": {
        "billingAccountLicenseConfigs": {
          "methods": {
            "distributeLicenseConfig": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "description": "Distributes a LicenseConfig from billing account level to project level.",
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.distributeLicenseConfig",
              "flatPath": "v1beta/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}:distributeLicenseConfig",
              "httpMethod": "POST",
              "path": "v1beta/{+billingAccountLicenseConfig}:distributeLicenseConfig"
            },
            "retractLicenseConfig": {
              "flatPath": "v1beta/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}:retractLicenseConfig",
              "httpMethod": "POST",
              "path": "v1beta/{+billingAccountLicenseConfig}:retractLicenseConfig",
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.retractLicenseConfig",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "description": "This method is called from the billing account side to retract the LicenseConfig from the given project back to the billing account."
            }
          }
        }
      }
    },
    "projects": {
      "resources": {
        "operations": {
          "methods": {
            "list": {
              "flatPath": "v1beta/projects/{projectsId}/operations",
              "path": "v1beta/{+name}/operations",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
              "id": "discoveryengine.projects.operations.list"
            },
            "get": {
              "path": "v1beta/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1beta/projects/{projectsId}/operations/{operationsId}",
              "id": "discoveryengine.projects.operations.get",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
            }
          }
        },
        "locations": {
          "resources": {
            "userEvents": {
              "methods": {
                "write": {
                  "id": "discoveryengine.projects.locations.userEvents.write",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Writes a single user event.",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userEvents:write",
                  "httpMethod": "POST",
                  "path": "v1beta/{+parent}/userEvents:write"
                },
                "import": {
                  "path": "v1beta/{+parent}/userEvents:import",
                  "httpMethod": "POST",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userEvents:import",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                  "id": "discoveryengine.projects.locations.userEvents.import"
                },
                "collect": {
                  "id": "discoveryengine.projects.locations.userEvents.collect",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userEvents:collect",
                  "path": "v1beta/{+parent}/userEvents:collect",
                  "httpMethod": "GET"
                }
              }
            },
            "identityMappingStores": {
              "methods": {
                "list": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "path": "v1beta/{+parent}/identityMappingStores",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.identityMappingStores.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Lists all Identity Mapping Stores."
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets the Identity Mapping Store.",
                  "id": "discoveryengine.projects.locations.identityMappingStores.get",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "path": "v1beta/{+name}",
                  "httpMethod": "GET"
                },
                "purgeIdentityMappings": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:purgeIdentityMappings",
                  "path": "v1beta/{+identityMappingStore}:purgeIdentityMappings",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.identityMappingStores.purgeIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Purges specified or all Identity Mapping Entries from an Identity Mapping Store."
                },
                "listIdentityMappings": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:listIdentityMappings",
                  "path": "v1beta/{+identityMappingStore}:listIdentityMappings",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Lists Identity Mappings in an Identity Mapping Store.",
                  "id": "discoveryengine.projects.locations.identityMappingStores.listIdentityMappings"
                },
                "create": {
                  "path": "v1beta/{+parent}/identityMappingStores",
                  "httpMethod": "POST",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Creates a new Identity Mapping Store.",
                  "id": "discoveryengine.projects.locations.identityMappingStores.create"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Deletes the Identity Mapping Store.",
                  "id": "discoveryengine.projects.locations.identityMappingStores.delete"
                },
                "importIdentityMappings": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:importIdentityMappings",
                  "path": "v1beta/{+identityMappingStore}:importIdentityMappings",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.identityMappingStores.importIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Imports a list of Identity Mapping Entries to an Identity Mapping Store."
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "list": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations",
                      "httpMethod": "GET",
                      "path": "v1beta/{+name}/operations",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                    },
                    "get": {
                      "httpMethod": "GET",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations/{operationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.get"
                    }
                  }
                }
              }
            },
            "sampleQuerySets": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/operations/{operationsId}",
                      "path": "v1beta/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.operations.get"
                    }
                  }
                },
                "sampleQueries": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a SampleQuery.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "httpMethod": "GET",
                      "path": "v1beta/{+name}"
                    },
                    "import": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Bulk import of multiple SampleQuerys. Sample queries that already exist may be deleted. Note: It is possible for a subset of the SampleQuerys to be successfully imported.",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.import",
                      "path": "v1beta/{+parent}/sampleQueries:import",
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries:import"
                    },
                    "list": {
                      "path": "v1beta/{+parent}/sampleQueries",
                      "httpMethod": "GET",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a list of SampleQuerys.",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.list"
                    },
                    "create": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries",
                      "path": "v1beta/{+parent}/sampleQueries",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a SampleQuery",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.create"
                    },
                    "delete": {
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a SampleQuery.",
                      "path": "v1beta/{+name}",
                      "httpMethod": "DELETE",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}"
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates a SampleQuery."
                    }
                  }
                }
              },
              "methods": {
                "create": {
                  "path": "v1beta/{+parent}/sampleQuerySets",
                  "httpMethod": "POST",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Creates a SampleQuerySet",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.create"
                },
                "delete": {
                  "path": "v1beta/{+name}",
                  "httpMethod": "DELETE",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Deletes a SampleQuerySet."
                },
                "patch": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "path": "v1beta/{+name}",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Updates a SampleQuerySet."
                },
                "get": {
                  "id": "discoveryengine.projects.locations.sampleQuerySets.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a SampleQuerySet.",
                  "path": "v1beta/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a list of SampleQuerySets.",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.list",
                  "path": "v1beta/{+parent}/sampleQuerySets",
                  "httpMethod": "GET",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets"
                }
              }
            },
            "groundingConfigs": {
              "methods": {
                "check": {
                  "id": "discoveryengine.projects.locations.groundingConfigs.check",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Performs a grounding check.",
                  "httpMethod": "POST",
                  "path": "v1beta/{+groundingConfig}:check",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/groundingConfigs/{groundingConfigsId}:check"
                }
              }
            },
            "dataStores": {
              "resources": {
                "sessions": {
                  "resources": {
                    "answers": {
                      "methods": {
                        "get": {
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a Answer.",
                          "id": "discoveryengine.projects.locations.dataStores.sessions.answers.get"
                        }
                      }
                    }
                  },
                  "methods": {
                    "get": {
                      "path": "v1beta/{+name}",
                      "httpMethod": "GET",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a Session.",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.get"
                    },
                    "list": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "httpMethod": "GET",
                      "path": "v1beta/{+parent}/sessions",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists all Sessions by their parent DataStore."
                    },
                    "create": {
                      "httpMethod": "POST",
                      "path": "v1beta/{+parent}/sessions",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned."
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.delete",
                      "path": "v1beta/{+name}",
                      "httpMethod": "DELETE",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}"
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.patch"
                    }
                  }
                },
                "schemas": {
                  "methods": {
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a list of Schemas.",
                      "httpMethod": "GET",
                      "path": "v1beta/{+parent}/schemas",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas"
                    },
                    "get": {
                      "path": "v1beta/{+name}",
                      "httpMethod": "GET",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a Schema.",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.get"
                    },
                    "patch": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "path": "v1beta/{+name}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates a Schema."
                    },
                    "create": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a Schema.",
                      "httpMethod": "POST",
                      "path": "v1beta/{+parent}/schemas",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a Schema.",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.delete",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "path": "v1beta/{+name}",
                      "httpMethod": "DELETE"
                    }
                  }
                },
                "completionConfig": {
                  "methods": {
                    "completeQuery": {
                      "httpMethod": "POST",
                      "path": "v1beta/{+completionConfig}:completeQuery",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud_search.query",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Completes the user input with advanced keyword suggestions.",
                      "id": "discoveryengine.projects.locations.dataStores.completionConfig.completeQuery"
                    }
                  }
                },
                "servingConfigs": {
                  "methods": {
                    "answer": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.answer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Answer query method.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                      "httpMethod": "POST",
                      "path": "v1beta/{+servingConfig}:answer"
                    },
                    "create": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "path": "v1beta/{+parent}/servingConfigs",
                      "httpMethod": "POST"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.delete",
                      "path": "v1beta/{+name}",
                      "httpMethod": "DELETE",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}"
                    },
                    "searchLite": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, it i[...]",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.searchLite",
                      "httpMethod": "POST",
                      "path": "v1beta/{+servingConfig}:searchLite",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite"
                    },
                    "streamAnswer": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                      "path": "v1beta/{+servingConfig}:streamAnswer",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.streamAnswer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream."
                    },
                    "recommend": {
                      "path": "v1beta/{+servingConfig}:recommend",
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Makes a recommendation, which requires a contextual user event.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.recommend"
                    },
                    "patch": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "httpMethod": "PATCH",
                      "path": "v1beta/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.patch"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.get",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "httpMethod": "GET",
                      "path": "v1beta/{+name}"
                    },
                    "search": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Performs a search.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.search",
                      "path": "v1beta/{+servingConfig}:search",
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search"
                    },
                    "list": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "httpMethod": "GET",
                      "path": "v1beta/{+parent}/servingConfigs",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists all ServingConfigs linked to this dataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.list"
                    }
                  }
                },
                "suggestionDenyListEntries": {
                  "methods": {
                    "purge": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.purge",
                      "httpMethod": "POST",
                      "path": "v1beta/{+parent}/suggestionDenyListEntries:purge",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge"
                    },
                    "import": {
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                      "httpMethod": "POST",
                      "path": "v1beta/{+parent}/suggestionDenyListEntries:import"
                    }
                  }
                },
                "models": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations",
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}/operations",
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}"
                        }
                      }
                    }
                  }
                },
                "userEvents": {
                  "methods": {
                    "write": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:write",
                      "path": "v1beta/{+parent}/userEvents:write",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.write",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Writes a single user event."
                    },
                    "import": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:import",
                      "httpMethod": "POST",
                      "path": "v1beta/{+parent}/userEvents:import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.import"
                    },
                    "collect": {
                      "path": "v1beta/{+parent}/userEvents:collect",
                      "httpMethod": "GET",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:collect",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.collect",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly."
                    },
                    "purge": {
                      "path": "v1beta/{+parent}/userEvents:purge",
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:purge",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first."
                    }
                  }
                },
                "branches": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.list",
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}/operations",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations"
                        },
                        "get": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.get"
                        },
                        "cancel": {
                          "path": "v1beta/{+name}:cancel",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.cancel",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instea[...]"
                        }
                      }
                    },
                    "documents": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a list of Documents.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.list",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/documents"
                        },
                        "purge": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.purge",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                          "path": "v1beta/{+parent}/documents:purge",
                          "httpMethod": "POST"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a Document.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.get",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET"
                        },
                        "import": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.import",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                          "path": "v1beta/{+parent}/documents:import",
                          "httpMethod": "POST"
                        },
                        "patch": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "httpMethod": "PATCH",
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a Document.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.patch"
                        },
                        "create": {
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}/documents",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates a Document."
                        },
                        "delete": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a Document.",
                          "path": "v1beta/{+name}",
                          "httpMethod": "DELETE",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}"
                        }
                      }
                    }
                  },
                  "methods": {
                    "batchGetDocumentsMetadata": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                      "path": "v1beta/{+parent}/batchGetDocumentsMetadata",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.branches.batchGetDocumentsMetadata",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets index freshness metadata for Documents. Supported for website search only."
                    }
                  }
                },
                "completionSuggestions": {
                  "methods": {
                    "purge": {
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                      "httpMethod": "POST",
                      "path": "v1beta/{+parent}/completionSuggestions:purge"
                    },
                    "import": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Imports CompletionSuggestions for a DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.import",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                      "httpMethod": "POST",
                      "path": "v1beta/{+parent}/completionSuggestions:import"
                    }
                  }
                },
                "siteSearchEngine": {
                  "methods": {
                    "disableAdvancedSiteSearch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Downgrade from advanced site search to basic site search.",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.disableAdvancedSiteSearch",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                      "httpMethod": "POST",
                      "path": "v1beta/{+siteSearchEngine}:disableAdvancedSiteSearch"
                    },
                    "enableAdvancedSiteSearch": {
                      "httpMethod": "POST",
                      "path": "v1beta/{+siteSearchEngine}:enableAdvancedSiteSearch",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.enableAdvancedSiteSearch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Upgrade from basic site search to advanced site search."
                    },
                    "recrawlUris": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Request on-demand recrawl for a list of URIs.",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.recrawlUris",
                      "httpMethod": "POST",
                      "path": "v1beta/{+siteSearchEngine}:recrawlUris",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris"
                    }
                  },
                  "resources": {
                    "targetSites": {
                      "methods": {
                        "list": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a list of TargetSites.",
                          "path": "v1beta/{+parent}/targetSites",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a TargetSite.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.get"
                        },
                        "batchCreate": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates TargetSite in a batch.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.batchCreate",
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}/targetSites:batchCreate",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate"
                        },
                        "patch": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a TargetSite.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.patch"
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates a TargetSite.",
                          "path": "v1beta/{+parent}/targetSites",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites"
                        },
                        "delete": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "httpMethod": "DELETE",
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a TargetSite.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.delete"
                        }
                      }
                    },
                    "sitemaps": {
                      "methods": {
                        "fetch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Fetch Sitemaps in a DataStore.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.fetch",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                          "path": "v1beta/{+parent}/sitemaps:fetch",
                          "httpMethod": "GET"
                        },
                        "create": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps",
                          "path": "v1beta/{+parent}/sitemaps",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates a Sitemap."
                        },
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a Sitemap.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.delete",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "DELETE"
                        }
                      }
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "list": {
                      "path": "v1beta/{+name}/operations",
                      "httpMethod": "GET",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations",
                      "id": "discoveryengine.projects.locations.dataStores.operations.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                    },
                    "get": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations/{operationsId}",
                      "path": "v1beta/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.dataStores.operations.get"
                    }
                  }
                },
                "conversations": {
                  "methods": {
                    "converse": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                      "path": "v1beta/{+name}:converse",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Converses a conversation.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.converse"
                    },
                    "patch": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "httpMethod": "PATCH",
                      "path": "v1beta/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.patch"
                    },
                    "create": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "httpMethod": "POST",
                      "path": "v1beta/{+parent}/conversations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.create"
                    },
                    "delete": {
                      "id": "discoveryengine.projects.locations.dataStores.conversations.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "httpMethod": "DELETE",
                      "path": "v1beta/{+name}"
                    },
                    "list": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "path": "v1beta/{+parent}/conversations",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists all Conversations by their parent DataStore."
                    },
                    "get": {
                      "path": "v1beta/{+name}",
                      "httpMethod": "GET",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a Conversation."
                    }
                  }
                },
                "controls": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists all Controls by their parent DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.list",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "path": "v1beta/{+parent}/controls",
                      "httpMethod": "GET"
                    },
                    "get": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "path": "v1beta/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a Control.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.get"
                    },
                    "patch": {
                      "path": "v1beta/{+name}",
                      "httpMethod": "PATCH",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.patch"
                    },
                    "create": {
                      "path": "v1beta/{+parent}/controls",
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "id": "discoveryengine.projects.locations.dataStores.controls.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned."
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.delete"
                    }
                  }
                }
              },
              "methods": {
                "get": {
                  "path": "v1beta/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "id": "discoveryengine.projects.locations.dataStores.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a DataStore."
                },
                "completeQuery": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:completeQuery",
                  "path": "v1beta/{+dataStore}:completeQuery",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Completes the specified user input with keyword suggestions.",
                  "id": "discoveryengine.projects.locations.dataStores.completeQuery"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Lists all the DataStores associated with the project.",
                  "id": "discoveryengine.projects.locations.dataStores.list",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "httpMethod": "GET",
                  "path": "v1beta/{+parent}/dataStores"
                },
                "create": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "httpMethod": "POST",
                  "path": "v1beta/{+parent}/dataStores",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                  "id": "discoveryengine.projects.locations.dataStores.create"
                },
                "delete": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "httpMethod": "DELETE",
                  "path": "v1beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Deletes a DataStore.",
                  "id": "discoveryengine.projects.locations.dataStores.delete"
                },
                "getSiteSearchEngine": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine",
                  "httpMethod": "GET",
                  "path": "v1beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets the SiteSearchEngine.",
                  "id": "discoveryengine.projects.locations.dataStores.getSiteSearchEngine"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Updates a DataStore",
                  "id": "discoveryengine.projects.locations.dataStores.patch",
                  "path": "v1beta/{+name}",
                  "httpMethod": "PATCH",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}"
                }
              }
            },
            "operations": {
              "methods": {
                "list": {
                  "path": "v1beta/{+name}/operations",
                  "httpMethod": "GET",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/operations",
                  "id": "discoveryengine.projects.locations.operations.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                },
                "get": {
                  "path": "v1beta/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "id": "discoveryengine.projects.locations.operations.get"
                }
              }
            },
            "podcasts": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/podcasts/{podcastsId}/operations/{operationsId}",
                      "httpMethod": "GET",
                      "path": "v1beta/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.podcasts.operations.get"
                    }
                  }
                }
              }
            },
            "licenseConfigs": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Creates a LicenseConfig This method should only be used for creating NotebookLm licenses or Gemini Enterprise free trial licenses.",
                  "id": "discoveryengine.projects.locations.licenseConfigs.create",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/licenseConfigs",
                  "path": "v1beta/{+parent}/licenseConfigs",
                  "httpMethod": "POST"
                },
                "get": {
                  "httpMethod": "GET",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a LicenseConfig.",
                  "id": "discoveryengine.projects.locations.licenseConfigs.get"
                },
                "patch": {
                  "id": "discoveryengine.projects.locations.licenseConfigs.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Updates the LicenseConfig",
                  "httpMethod": "PATCH",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}"
                }
              }
            },
            "evaluations": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "path": "v1beta/{+parent}/evaluations",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "id": "discoveryengine.projects.locations.evaluations.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a list of Evaluations."
                },
                "listResults": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a list of results for a given a Evaluation.",
                  "id": "discoveryengine.projects.locations.evaluations.listResults",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}:listResults",
                  "httpMethod": "GET",
                  "path": "v1beta/{+evaluation}:listResults"
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "v1beta/{+parent}/evaluations",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Creates a Evaluation. Upon creation, the evaluation will be automatically triggered and begin execution.",
                  "id": "discoveryengine.projects.locations.evaluations.create"
                },
                "get": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}",
                  "path": "v1beta/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.evaluations.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a Evaluation."
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.evaluations.operations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "httpMethod": "GET",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}/operations/{operationsId}"
                    }
                  }
                }
              }
            },
            "collections": {
              "resources": {
                "dataConnector": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations",
                          "path": "v1beta/{+name}/operations",
                          "httpMethod": "GET"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.get",
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations/{operationsId}"
                        }
                      }
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "list": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/operations",
                      "httpMethod": "GET",
                      "path": "v1beta/{+name}/operations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "id": "discoveryengine.projects.locations.collections.operations.list"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.collections.operations.get",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/operations/{operationsId}",
                      "path": "v1beta/{+name}",
                      "httpMethod": "GET"
                    }
                  }
                },
                "dataStores": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "path": "v1beta/{+name}/operations",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.list"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations/{operationsId}"
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "create": {
                          "path": "v1beta/{+parent}/conversations",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.create"
                        },
                        "delete": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned."
                        },
                        "converse": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                          "httpMethod": "POST",
                          "path": "v1beta/{+name}:converse",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Converses a conversation.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.converse"
                        },
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.patch",
                          "httpMethod": "PATCH",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a Conversation.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.get",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}"
                        },
                        "list": {
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/conversations",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists all Conversations by their parent DataStore."
                        }
                      }
                    },
                    "controls": {
                      "methods": {
                        "get": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a Control."
                        },
                        "list": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/controls",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists all Controls by their parent DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.list"
                        },
                        "create": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "path": "v1beta/{+parent}/controls",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.create"
                        },
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.delete",
                          "httpMethod": "DELETE",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}"
                        },
                        "patch": {
                          "httpMethod": "PATCH",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned."
                        }
                      }
                    },
                    "siteSearchEngine": {
                      "methods": {
                        "enableAdvancedSiteSearch": {
                          "path": "v1beta/{+siteSearchEngine}:enableAdvancedSiteSearch",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Upgrade from basic site search to advanced site search.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.enableAdvancedSiteSearch"
                        },
                        "recrawlUris": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.recrawlUris",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Request on-demand recrawl for a list of URIs.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                          "path": "v1beta/{+siteSearchEngine}:recrawlUris",
                          "httpMethod": "POST"
                        },
                        "fetchDomainVerificationStatus": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Returns list of target sites with its domain verification status. This method can only be called under data store with BASIC_SITE_SEARCH state at the moment.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.fetchDomainVerificationStatus",
                          "path": "v1beta/{+siteSearchEngine}:fetchDomainVerificationStatus",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:fetchDomainVerificationStatus"
                        },
                        "batchVerifyTargetSites": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.batchVerifyTargetSites",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Verify target sites' ownership and validity. This API sends all the target sites under site search engine for verification.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:batchVerifyTargetSites",
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}:batchVerifyTargetSites"
                        },
                        "disableAdvancedSiteSearch": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                          "httpMethod": "POST",
                          "path": "v1beta/{+siteSearchEngine}:disableAdvancedSiteSearch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Downgrade from advanced site search to basic site search.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.disableAdvancedSiteSearch"
                        }
                      },
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "httpMethod": "GET",
                              "path": "v1beta/{+name}/operations",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/operations",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.operations.list"
                            },
                            "get": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.operations.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/operations/{operationsId}",
                              "httpMethod": "GET",
                              "path": "v1beta/{+name}"
                            }
                          }
                        },
                        "sitemaps": {
                          "methods": {
                            "create": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Creates a Sitemap.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.create",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps",
                              "httpMethod": "POST",
                              "path": "v1beta/{+parent}/sitemaps"
                            },
                            "delete": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}",
                              "path": "v1beta/{+name}",
                              "httpMethod": "DELETE",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Deletes a Sitemap.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.delete"
                            },
                            "fetch": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Fetch Sitemaps in a DataStore.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.fetch",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                              "path": "v1beta/{+parent}/sitemaps:fetch",
                              "httpMethod": "GET"
                            }
                          }
                        },
                        "targetSites": {
                          "resources": {
                            "operations": {
                              "methods": {
                                "list": {
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.list",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                                  ],
                                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations",
                                  "httpMethod": "GET",
                                  "path": "v1beta/{+name}/operations"
                                },
                                "get": {
                                  "path": "v1beta/{+name}",
                                  "httpMethod": "GET",
                                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations/{operationsId}",
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.get",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                                  ],
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                                }
                              }
                            }
                          },
                          "methods": {
                            "get": {
                              "httpMethod": "GET",
                              "path": "v1beta/{+name}",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets a TargetSite.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.get"
                            },
                            "list": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                              "httpMethod": "GET",
                              "path": "v1beta/{+parent}/targetSites",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.list",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets a list of TargetSites."
                            },
                            "create": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Creates a TargetSite.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.create",
                              "path": "v1beta/{+parent}/targetSites",
                              "httpMethod": "POST",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites"
                            },
                            "delete": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Deletes a TargetSite.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.delete",
                              "path": "v1beta/{+name}",
                              "httpMethod": "DELETE",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}"
                            },
                            "patch": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "httpMethod": "PATCH",
                              "path": "v1beta/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Updates a TargetSite.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.patch"
                            },
                            "batchCreate": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.batchCreate",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Creates TargetSite in a batch.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                              "path": "v1beta/{+parent}/targetSites:batchCreate",
                              "httpMethod": "POST"
                            }
                          }
                        }
                      }
                    },
                    "branches": {
                      "resources": {
                        "operations": {
                          "methods": {
                            "get": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                              "path": "v1beta/{+name}",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                            },
                            "cancel": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.cancel",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; in[...]",
                              "path": "v1beta/{+name}:cancel",
                              "httpMethod": "POST",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel"
                            },
                            "list": {
                              "path": "v1beta/{+name}/operations",
                              "httpMethod": "GET",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.list"
                            }
                          }
                        },
                        "documents": {
                          "methods": {
                            "get": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets a Document.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.get",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "path": "v1beta/{+name}",
                              "httpMethod": "GET"
                            },
                            "import": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.import",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                              "httpMethod": "POST",
                              "path": "v1beta/{+parent}/documents:import"
                            },
                            "purge": {
                              "path": "v1beta/{+parent}/documents:purge",
                              "httpMethod": "POST",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.purge"
                            },
                            "list": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets a list of Documents.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.list",
                              "httpMethod": "GET",
                              "path": "v1beta/{+parent}/documents",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents"
                            },
                            "create": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "httpMethod": "POST",
                              "path": "v1beta/{+parent}/documents",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Creates a Document.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.create"
                            },
                            "delete": {
                              "httpMethod": "DELETE",
                              "path": "v1beta/{+name}",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Deletes a Document.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.delete"
                            },
                            "patch": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.patch",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Updates a Document.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "httpMethod": "PATCH",
                              "path": "v1beta/{+name}"
                            }
                          }
                        }
                      },
                      "methods": {
                        "batchGetDocumentsMetadata": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.batchGetDocumentsMetadata",
                          "path": "v1beta/{+parent}/batchGetDocumentsMetadata",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata"
                        }
                      }
                    },
                    "completionSuggestions": {
                      "methods": {
                        "purge": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                          "path": "v1beta/{+parent}/completionSuggestions:purge",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Permanently deletes all CompletionSuggestions for a DataStore."
                        },
                        "import": {
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}/completionSuggestions:import",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Imports CompletionSuggestions for a DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.import"
                        }
                      }
                    },
                    "customModels": {
                      "methods": {
                        "list": {
                          "path": "v1beta/{+dataStore}/customModels",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/customModels",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a list of all the custom models.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.customModels.list"
                        }
                      }
                    },
                    "userEvents": {
                      "methods": {
                        "write": {
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}/userEvents:write",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:write",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.write",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Writes a single user event."
                        },
                        "import": {
                          "path": "v1beta/{+parent}/userEvents:import",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:import",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata."
                        },
                        "collect": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.collect",
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/userEvents:collect",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:collect"
                        },
                        "purge": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.purge",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:purge",
                          "path": "v1beta/{+parent}/userEvents:purge",
                          "httpMethod": "POST"
                        }
                      }
                    },
                    "models": {
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.list",
                              "httpMethod": "GET",
                              "path": "v1beta/{+name}/operations",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations"
                            },
                            "get": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                              "httpMethod": "GET",
                              "path": "v1beta/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                            }
                          }
                        }
                      }
                    },
                    "completionConfig": {
                      "methods": {
                        "completeQuery": {
                          "path": "v1beta/{+completionConfig}:completeQuery",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud_search.query",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Completes the user input with advanced keyword suggestions.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionConfig.completeQuery"
                        }
                      }
                    },
                    "servingConfigs": {
                      "methods": {
                        "search": {
                          "path": "v1beta/{+servingConfig}:search",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Performs a search.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.search"
                        },
                        "list": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "path": "v1beta/{+parent}/servingConfigs",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists all ServingConfigs linked to this dataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.list"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist."
                        },
                        "streamAnswer": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.streamAnswer",
                          "path": "v1beta/{+servingConfig}:streamAnswer",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer"
                        },
                        "recommend": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Makes a recommendation, which requires a contextual user event.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.recommend",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                          "path": "v1beta/{+servingConfig}:recommend",
                          "httpMethod": "POST"
                        },
                        "patch": {
                          "httpMethod": "PATCH",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.patch"
                        },
                        "searchLite": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.searchLite",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "path": "v1beta/{+servingConfig}:searchLite",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite"
                        },
                        "answer": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                          "httpMethod": "POST",
                          "path": "v1beta/{+servingConfig}:answer",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.answer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Answer query method."
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}/servingConfigs"
                        },
                        "delete": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "httpMethod": "DELETE",
                          "path": "v1beta/{+name}"
                        }
                      }
                    },
                    "suggestionDenyListEntries": {
                      "methods": {
                        "purge": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.purge",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}/suggestionDenyListEntries:purge"
                        },
                        "import": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                          "path": "v1beta/{+parent}/suggestionDenyListEntries:import",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import"
                        }
                      }
                    },
                    "sessions": {
                      "resources": {
                        "answers": {
                          "methods": {
                            "get": {
                              "httpMethod": "GET",
                              "path": "v1beta/{+name}",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.sessions.answers.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets a Answer."
                            }
                          }
                        }
                      },
                      "methods": {
                        "patch": {
                          "httpMethod": "PATCH",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned."
                        },
                        "create": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}/sessions",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.create"
                        },
                        "delete": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned."
                        },
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists all Sessions by their parent DataStore.",
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/sessions",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions"
                        },
                        "get": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a Session.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.get"
                        }
                      }
                    },
                    "schemas": {
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "path": "v1beta/{+name}/operations",
                              "httpMethod": "GET",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.list"
                            },
                            "get": {
                              "path": "v1beta/{+name}",
                              "httpMethod": "GET",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations/{operationsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.get"
                            }
                          }
                        }
                      },
                      "methods": {
                        "get": {
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a Schema.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.get"
                        },
                        "list": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "path": "v1beta/{+parent}/schemas",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a list of Schemas."
                        },
                        "create": {
                          "path": "v1beta/{+parent}/schemas",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates a Schema."
                        },
                        "delete": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "httpMethod": "DELETE",
                          "path": "v1beta/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a Schema."
                        },
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a Schema.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.patch",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "httpMethod": "PATCH",
                          "path": "v1beta/{+name}"
                        }
                      }
                    }
                  },
                  "methods": {
                    "patch": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates a DataStore",
                      "path": "v1beta/{+name}",
                      "httpMethod": "PATCH",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}"
                    },
                    "getSiteSearchEngine": {
                      "httpMethod": "GET",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the SiteSearchEngine.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.getSiteSearchEngine"
                    },
                    "create": {
                      "path": "v1beta/{+parent}/dataStores",
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.create"
                    },
                    "delete": {
                      "path": "v1beta/{+name}",
                      "httpMethod": "DELETE",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "id": "discoveryengine.projects.locations.collections.dataStores.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a DataStore."
                    },
                    "completeQuery": {
                      "httpMethod": "GET",
                      "path": "v1beta/{+dataStore}:completeQuery",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:completeQuery",
                      "id": "discoveryengine.projects.locations.collections.dataStores.completeQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Completes the specified user input with keyword suggestions."
                    },
                    "list": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores",
                      "path": "v1beta/{+parent}/dataStores",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.collections.dataStores.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists all the DataStores associated with the project."
                    },
                    "get": {
                      "httpMethod": "GET",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a DataStore.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.get"
                    },
                    "trainCustomModel": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Trains a custom model.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.trainCustomModel",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:trainCustomModel",
                      "path": "v1beta/{+dataStore}:trainCustomModel",
                      "httpMethod": "POST"
                    }
                  }
                },
                "engines": {
                  "methods": {
                    "getIamPolicy": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:getIamPolicy",
                      "path": "v1beta/{+resource}:getIamPolicy",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. An empty policy is returned if the resource exists but does not have a policy set on it.",
                      "id": "discoveryengine.projects.locations.collections.engines.getIamPolicy"
                    },
                    "create": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines",
                      "httpMethod": "POST",
                      "path": "v1beta/{+parent}/engines",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates an Engine.",
                      "id": "discoveryengine.projects.locations.collections.engines.create"
                    },
                    "delete": {
                      "id": "discoveryengine.projects.locations.collections.engines.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes an Engine.",
                      "path": "v1beta/{+name}",
                      "httpMethod": "DELETE",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}"
                    },
                    "setIamPolicy": {
                      "httpMethod": "POST",
                      "path": "v1beta/{+resource}:setIamPolicy",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Sets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. **Important:** When setting a policy directly on an Engine resource, the only recommended roles in the bindings are: `roles/discoveryengine.user` and `roles/discoveryengine.agentspaceUser`. Attempting to grant any other role will result in a warning in logging.",
                      "id": "discoveryengine.projects.locations.collections.engines.setIamPolicy"
                    },
                    "get": {
                      "httpMethod": "GET",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets an Engine.",
                      "id": "discoveryengine.projects.locations.collections.engines.get"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists all the Engines associated with the project.",
                      "id": "discoveryengine.projects.locations.collections.engines.list",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines",
                      "path": "v1beta/{+parent}/engines",
                      "httpMethod": "GET"
                    },
                    "pause": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Pauses the training of an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION.",
                      "id": "discoveryengine.projects.locations.collections.engines.pause",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:pause",
                      "path": "v1beta/{+name}:pause",
                      "httpMethod": "POST"
                    },
                    "tune": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:tune",
                      "path": "v1beta/{+name}:tune",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.engines.tune",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Tunes an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION."
                    },
                    "resume": {
                      "id": "discoveryengine.projects.locations.collections.engines.resume",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Resumes the training of an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:resume",
                      "path": "v1beta/{+name}:resume",
                      "httpMethod": "POST"
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates an Engine",
                      "id": "discoveryengine.projects.locations.collections.engines.patch",
                      "path": "v1beta/{+name}",
                      "httpMethod": "PATCH",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}"
                    }
                  },
                  "resources": {
                    "controls": {
                      "methods": {
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.engines.controls.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a Control.",
[...]
