{
  "description": "Discovery Engine API.",
  "documentationLink": "https://cloud.google.com/generative-ai-app-builder/docs/",
  "version_module": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/discoveryengine.readwrite": {
          "description": "View, edit, create, and delete all your data associated with any Discovery Engine API product, such as Agentspace, Vertex AI Search, or NotebookLM Enterprise, including both end user data and administration or configuration data."
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite": {
          "description": "View your Agentspace chat history, including uploaded files and generated reports and visualizations, and interact with the Agentspace assistant on your behalf."
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        }
      }
    }
  },
  "id": "discoveryengine:v1alpha",
  "baseUrl": "https://discoveryengine.googleapis.com/",
  "title": "Discovery Engine API",
  "ownerDomain": "google.com",
  "discoveryVersion": "v1",
  "version": "v1alpha",
  "rootUrl": "https://discoveryengine.googleapis.com/",
  "batchPath": "batch",
  "mtlsRootUrl": "https://discoveryengine.mtls.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "kind": "discovery#restDescription",
  "name": "discoveryengine",
  "servicePath": "",
  "resources": {
    "projects": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "flatPath": "v1alpha/projects/{projectsId}",
          "id": "discoveryengine.projects.patch",
          "path": "v1alpha/{+name}",
          "description": "Updates the editable settings of a Discovery Engine Project.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ]
        },
        "reportConsentChange": {
          "path": "v1alpha/{+project}:reportConsentChange",
          "flatPath": "v1alpha/projects/{projectsId}:reportConsentChange",
          "description": "Updates service terms for this project. This method can be used to retroactively accept the latest terms. Terms available for update: * [Terms for data use](https://cloud.google.com/retail/data-use-terms)",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "httpMethod": "POST",
          "id": "discoveryengine.projects.reportConsentChange"
        },
        "get": {
          "path": "v1alpha/{+name}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "id": "discoveryengine.projects.get",
          "flatPath": "v1alpha/projects/{projectsId}",
          "description": "Gets a Project. Returns NOT_FOUND when the project is not yet created.",
          "httpMethod": "GET"
        },
        "provision": {
          "path": "v1alpha/{+name}:provision",
          "description": "Provisions the project resource. During the process, related systems will get prepared and initialized. Caller must read the [Terms for data use](https://cloud.google.com/retail/data-use-terms), and optionally specify in request to provide consent to that service terms.",
          "id": "discoveryengine.projects.provision",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "flatPath": "v1alpha/projects/{projectsId}:provision"
        }
      },
      "resources": {
        "locations": {
          "resources": {
            "requirements": {
              "methods": {
                "checkRequirement": {
                  "id": "discoveryengine.projects.locations.requirements.checkRequirement",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/requirements:checkRequirement",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "POST",
                  "path": "v1alpha/{+location}/requirements:checkRequirement",
                  "description": "Check a particular requirement."
                }
              }
            },
            "cmekConfigs": {
              "methods": {
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.cmekConfigs.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "path": "v1alpha/{+name}",
                  "description": "De-provisions a CmekConfig."
                },
                "list": {
                  "path": "v1alpha/{+parent}/cmekConfigs",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Lists all the CmekConfigs with the project.",
                  "id": "discoveryengine.projects.locations.cmekConfigs.list"
                },
                "patch": {
                  "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "id": "discoveryengine.projects.locations.cmekConfigs.patch",
                  "path": "v1alpha/{+name}"
                },
                "get": {
                  "id": "discoveryengine.projects.locations.cmekConfigs.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "description": "Gets the CmekConfig.",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}"
                }
              }
            },
            "identityMappingStores": {
              "methods": {
                "listIdentityMappings": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:listIdentityMappings",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.identityMappingStores.listIdentityMappings",
                  "description": "Lists Identity Mappings in an Identity Mapping Store.",
                  "path": "v1alpha/{+identityMappingStore}:listIdentityMappings"
                },
                "purgeIdentityMappings": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.purgeIdentityMappings",
                  "description": "Purges specified or all Identity Mapping Entries from an Identity Mapping Store.",
                  "path": "v1alpha/{+identityMappingStore}:purgeIdentityMappings",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:purgeIdentityMappings",
                  "httpMethod": "POST"
                },
                "importIdentityMappings": {
                  "httpMethod": "POST",
                  "path": "v1alpha/{+identityMappingStore}:importIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Imports a list of Identity Mapping Entries to an Identity Mapping Store.",
                  "id": "discoveryengine.projects.locations.identityMappingStores.importIdentityMappings",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:importIdentityMappings"
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "path": "v1alpha/{+parent}/identityMappingStores",
                  "id": "discoveryengine.projects.locations.identityMappingStores.create",
                  "description": "Creates a new Identity Mapping Store."
                },
                "list": {
                  "path": "v1alpha/{+parent}/identityMappingStores",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.identityMappingStores.list",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "description": "Lists all Identity Mapping Stores.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "delete": {
                  "description": "Deletes the Identity Mapping Store.",
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.identityMappingStores.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}"
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "description": "Gets the Identity Mapping Store.",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "id": "discoveryengine.projects.locations.identityMappingStores.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.list",
                      "path": "v1alpha/{+name}/operations",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations"
                    },
                    "get": {
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.get",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations/{operationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                }
              }
            },
            "groundingConfigs": {
              "methods": {
                "check": {
                  "id": "discoveryengine.projects.locations.groundingConfigs.check",
                  "path": "v1alpha/{+groundingConfig}:check",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/groundingConfigs/{groundingConfigsId}:check",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Performs a grounding check."
                }
              }
            },
            "dataStores": {
              "methods": {
                "patch": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.patch",
                  "httpMethod": "PATCH",
                  "description": "Updates a DataStore",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}"
                },
                "deletePatientFilter": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+dataStore}:deletePatientFilter",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.dataStores.deletePatientFilter",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:deletePatientFilter",
                  "description": "Deletes the entire patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter."
                },
                "removePatientFilter": {
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.dataStores.removePatientFilter",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:removePatientFilter",
                  "description": "Removes a group of patient IDs from the patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the list of patient IDs to remove will be constructed from the direct member[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+dataStore}:removePatientFilter"
                },
                "getDocumentProcessingConfig": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.getDocumentProcessingConfig",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                  "path": "v1alpha/{+name}",
                  "description": "Gets a DocumentProcessingConfig."
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "description": "Lists all the DataStores associated with the project.",
                  "id": "discoveryengine.projects.locations.dataStores.list",
                  "path": "v1alpha/{+parent}/dataStores",
                  "httpMethod": "GET"
                },
                "replacePatientFilter": {
                  "description": "Replaces the patient filter for the data store. This method is essentially a combination of DeletePatientFilters and AddPatientFilter. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the new filter w[...]",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:replacePatientFilter",
                  "path": "v1alpha/{+dataStore}:replacePatientFilter",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.replacePatientFilter"
                },
                "completeQuery": {
                  "path": "v1alpha/{+dataStore}:completeQuery",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:completeQuery",
                  "id": "discoveryengine.projects.locations.dataStores.completeQuery",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Completes the specified user input with keyword suggestions."
                },
                "delete": {
                  "description": "Deletes a DataStore.",
                  "id": "discoveryengine.projects.locations.dataStores.delete",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "addPatientFilter": {
                  "description": "Adds a group of patient IDs as a patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. The filter group must be a FHIR resource name of type Group, and the filter will be constructed from the direct members of the group which are Patient resources.",
                  "httpMethod": "POST",
                  "path": "v1alpha/{+dataStore}:addPatientFilter",
                  "id": "discoveryengine.projects.locations.dataStores.addPatientFilter",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:addPatientFilter",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "updateDocumentProcessingConfig": {
                  "description": "Updates the DocumentProcessingConfig. DocumentProcessingConfig is a singleon resource of DataStore. It's empty when DataStore is created. The first call to this method will set up DocumentProcessingConfig.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.updateDocumentProcessingConfig",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                  "httpMethod": "PATCH",
                  "path": "v1alpha/{+name}"
                },
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.dataStores.get",
                  "description": "Gets a DataStore."
                },
                "create": {
                  "id": "discoveryengine.projects.locations.dataStores.create",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "path": "v1alpha/{+parent}/dataStores",
                  "httpMethod": "POST",
                  "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "getSiteSearchEngine": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Gets the SiteSearchEngine.",
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.dataStores.getSiteSearchEngine",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine"
                }
              },
              "resources": {
                "models": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "path": "v1alpha/{+name}/operations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.list",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations"
                        },
                        "get": {
                          "path": "v1alpha/{+name}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.get",
                          "httpMethod": "GET"
                        }
                      }
                    }
                  }
                },
                "schemas": {
                  "methods": {
                    "list": {
                      "description": "Gets a list of Schemas.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.list",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/schemas"
                    },
                    "delete": {
                      "description": "Deletes a Schema.",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.delete",
                      "path": "v1alpha/{+name}"
                    },
                    "create": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.create",
                      "path": "v1alpha/{+parent}/schemas",
                      "description": "Creates a Schema.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas"
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "description": "Updates a Schema.",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.patch"
                    },
                    "get": {
                      "description": "Gets a Schema.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.get",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}"
                    }
                  }
                },
                "sessions": {
                  "methods": {
                    "delete": {
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.delete",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}"
                    },
                    "create": {
                      "path": "v1alpha/{+parent}/sessions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.create"
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.sessions.get",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets a Session."
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.sessions.list",
                      "path": "v1alpha/{+parent}/sessions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "description": "Lists all Sessions by their parent DataStore.",
                      "httpMethod": "GET"
                    },
                    "patch": {
                      "id": "discoveryengine.projects.locations.dataStores.sessions.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned."
                    }
                  },
                  "resources": {
                    "answers": {
                      "methods": {
                        "get": {
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.sessions.answers.get",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "description": "Gets a Answer."
                        }
                      }
                    }
                  }
                },
                "suggestionDenyListEntries": {
                  "methods": {
                    "purge": {
                      "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.purge"
                    },
                    "import": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.import",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:import",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import"
                    }
                  }
                },
                "conversations": {
                  "methods": {
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.delete",
                      "httpMethod": "DELETE",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "path": "v1alpha/{+name}"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.create",
                      "path": "v1alpha/{+parent}/conversations"
                    },
                    "list": {
                      "description": "Lists all Conversations by their parent DataStore.",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/conversations",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations"
                    },
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "description": "Gets a Conversation.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.get"
                    },
                    "converse": {
                      "description": "Converses a conversation.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.converse",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "path": "v1alpha/{+name}:converse",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse"
                    },
                    "patch": {
                      "path": "v1alpha/{+name}",
                      "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "branches": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "path": "v1alpha/{+parent}/branches",
                      "id": "discoveryengine.projects.locations.dataStores.branches.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Lists all Branchs under the specified parent DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches"
                    },
                    "batchGetDocumentsMetadata": {
                      "path": "v1alpha/{+parent}/batchGetDocumentsMetadata",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                      "id": "discoveryengine.projects.locations.dataStores.branches.batchGetDocumentsMetadata",
                      "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.branches.get",
                      "description": "Retrieves a Branch.",
                      "path": "v1alpha/{+name}"
                    }
                  },
                  "resources": {
                    "documents": {
                      "methods": {
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes a Document.",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.delete",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}"
                        },
                        "purge": {
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                          "path": "v1alpha/{+parent}/documents:purge",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.purge"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "description": "Gets a Document.",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.get"
                        },
                        "import": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.import",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                          "path": "v1alpha/{+parent}/documents:import",
                          "httpMethod": "POST"
                        },
                        "patch": {
                          "description": "Updates a Document.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.patch",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH"
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.create",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/documents",
                          "description": "Creates a Document.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents"
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a list of Documents.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "path": "v1alpha/{+parent}/documents",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.list"
                        },
                        "getProcessedDocument": {
                          "httpMethod": "GET",
                          "description": "Gets the parsed layout information for a Document.",
                          "path": "v1alpha/{+name}:getProcessedDocument",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}:getProcessedDocument",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.getProcessedDocument"
                        }
                      },
                      "resources": {
                        "chunks": {
                          "methods": {
                            "list": {
                              "description": "Gets a list of Chunks.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+parent}/chunks",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks",
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.list",
                              "httpMethod": "GET"
                            },
                            "get": {
                              "description": "Gets a Document.",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks/{chunksId}",
                              "path": "v1alpha/{+name}"
                            }
                          }
                        }
                      }
                    },
                    "operations": {
                      "methods": {
                        "get": {
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.get",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}"
                        },
                        "list": {
                          "path": "v1alpha/{+name}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "cancel": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                          "path": "v1alpha/{+name}:cancel",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.cancel",
                          "httpMethod": "POST",
                          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instea[...]",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    }
                  }
                },
                "completionConfig": {
                  "methods": {
                    "completeQuery": {
                      "id": "discoveryengine.projects.locations.dataStores.completionConfig.completeQuery",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                      "path": "v1alpha/{+completionConfig}:completeQuery",
                      "description": "Completes the user input with advanced keyword suggestions.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud_search.query",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST"
                    }
                  }
                },
                "userEvents": {
                  "methods": {
                    "import": {
                      "path": "v1alpha/{+parent}/userEvents:import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.import",
                      "httpMethod": "POST",
                      "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:import"
                    },
                    "purge": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.purge",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:purge",
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}/userEvents:purge"
                    },
                    "write": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:write",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.write",
                      "description": "Writes a single user event.",
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}/userEvents:write"
                    },
                    "collect": {
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.collect",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/userEvents:collect",
                      "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:collect"
                    }
                  }
                },
                "widgetConfigs": {
                  "methods": {
                    "patch": {
                      "description": "Update a WidgetConfig.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.patch",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}"
                    },
                    "get": {
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.get",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                      "description": "Gets a WidgetConfig.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "siteSearchEngine": {
                  "methods": {
                    "recrawlUris": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.recrawlUris",
                      "path": "v1alpha/{+siteSearchEngine}:recrawlUris",
                      "description": "Request on-demand recrawl for a list of URIs."
                    },
                    "enableAdvancedSiteSearch": {
                      "httpMethod": "POST",
                      "description": "Upgrade from basic site search to advanced site search.",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.enableAdvancedSiteSearch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+siteSearchEngine}:enableAdvancedSiteSearch",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch"
                    },
                    "disableAdvancedSiteSearch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                      "path": "v1alpha/{+siteSearchEngine}:disableAdvancedSiteSearch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "description": "Downgrade from advanced site search to basic site search.",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.disableAdvancedSiteSearch"
                    }
                  },
                  "resources": {
                    "targetSites": {
                      "methods": {
                        "batchCreate": {
                          "path": "v1alpha/{+parent}/targetSites:batchCreate",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Creates TargetSite in a batch.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.batchCreate"
                        },
                        "delete": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "description": "Deletes a TargetSite.",
                          "httpMethod": "DELETE",
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "get": {
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.get",
                          "description": "Gets a TargetSite.",
                          "path": "v1alpha/{+name}"
                        },
                        "create": {
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "description": "Creates a TargetSite.",
                          "path": "v1alpha/{+parent}/targetSites",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.create"
                        },
                        "list": {
                          "description": "Gets a list of TargetSites.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.list",
                          "httpMethod": "GET",
                          "path": "v1alpha/{+parent}/targetSites",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.patch",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "description": "Updates a TargetSite."
                        }
                      }
                    },
                    "sitemaps": {
                      "methods": {
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.create",
                          "description": "Creates a Sitemap.",
                          "httpMethod": "POST",
                          "path": "v1alpha/{+parent}/sitemaps"
                        },
                        "delete": {
                          "httpMethod": "DELETE",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.delete",
                          "description": "Deletes a Sitemap.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}"
                        },
                        "fetch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                          "path": "v1alpha/{+parent}/sitemaps:fetch",
                          "description": "Fetch Sitemaps in a DataStore.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.fetch",
                          "httpMethod": "GET"
                        }
                      }
                    }
                  }
                },
                "completionSuggestions": {
                  "methods": {
                    "purge": {
                      "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                      "path": "v1alpha/{+parent}/completionSuggestions:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.purge",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                      "httpMethod": "POST"
                    },
                    "import": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                      "path": "v1alpha/{+parent}/completionSuggestions:import",
                      "description": "Imports CompletionSuggestions for a DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.import",
                      "httpMethod": "POST"
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "list": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations",
                      "path": "v1alpha/{+name}/operations",
                      "id": "discoveryengine.projects.locations.dataStores.operations.list",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.operations.get",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations/{operationsId}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                    }
                  }
                },
                "servingConfigs": {
                  "methods": {
                    "list": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "httpMethod": "GET",
                      "description": "Lists all ServingConfigs linked to this dataStore.",
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.list"
                    },
                    "recommend": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+servingConfig}:recommend",
                      "description": "Makes a recommendation, which requires a contextual user event.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.recommend",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                      "httpMethod": "POST"
                    },
                    "patch": {
                      "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.patch"
                    },
                    "searchLite": {
                      "path": "v1alpha/{+servingConfig}:searchLite",
                      "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, it i[...]",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.searchLite",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite"
                    },
                    "answer": {
                      "description": "Answer query method.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.answer",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                      "path": "v1alpha/{+servingConfig}:answer"
                    },
                    "streamAnswer": {
                      "path": "v1alpha/{+servingConfig}:streamAnswer",
                      "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.streamAnswer"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.get",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "DELETE",
                      "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.delete",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}"
                    },
                    "create": {
                      "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.create",
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST"
                    },
                    "search": {
                      "description": "Performs a search.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.search",
                      "path": "v1alpha/{+servingConfig}:search",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "controls": {
                  "methods": {
                    "create": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "path": "v1alpha/{+parent}/controls",
                      "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST"
                    },
                    "patch": {
                      "id": "discoveryengine.projects.locations.dataStores.controls.patch",
                      "httpMethod": "PATCH",
                      "path": "v1alpha/{+name}",
                      "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "get": {
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "httpMethod": "GET",
                      "description": "Gets a Control.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Lists all Controls by their parent DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.list",
                      "path": "v1alpha/{+parent}/controls",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls"
                    },
                    "delete": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.controls.delete",
                      "httpMethod": "DELETE",
                      "path": "v1alpha/{+name}",
                      "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned."
                    }
                  }
                }
              }
            },
            "userStores": {
              "methods": {
                "batchUpdateUserLicenses": {
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}:batchUpdateUserLicenses",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+parent}:batchUpdateUserLicenses",
                  "id": "discoveryengine.projects.locations.userStores.batchUpdateUserLicenses",
                  "description": "Updates the User License. This method is used for batch assign/unassign licenses to users."
                },
                "get": {
                  "id": "discoveryengine.projects.locations.userStores.get",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "description": "Gets the User Store."
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.userStores.patch",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "httpMethod": "PATCH",
                  "description": "Updates the User Store.",
                  "path": "v1alpha/{+name}"
                }
              },
              "resources": {
                "licenseConfigsUsageStats": {
                  "methods": {
                    "list": {
                      "path": "v1alpha/{+parent}/licenseConfigsUsageStats",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/licenseConfigsUsageStats",
                      "id": "discoveryengine.projects.locations.userStores.licenseConfigsUsageStats.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Lists all the LicenseConfigUsageStatss associated with the project.",
                      "httpMethod": "GET"
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "get": {
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.userStores.operations.get",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/operations/{operationsId}",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.userStores.operations.list",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/operations",
                      "path": "v1alpha/{+name}/operations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "userLicenses": {
                  "methods": {
                    "list": {
                      "id": "discoveryengine.projects.locations.userStores.userLicenses.list",
                      "path": "v1alpha/{+parent}/userLicenses",
                      "description": "Lists the User Licenses.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/userLicenses",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            },
            "podcasts": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.podcasts.operations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/podcasts/{podcastsId}/operations/{operationsId}",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            },
            "collections": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.collections.get",
                  "path": "v1alpha/{+name}",
                  "description": "Gets a Collection.",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/collections",
                  "description": "Gets a list of Collections.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.collections.list"
                },
                "patch": {
                  "id": "discoveryengine.projects.locations.collections.patch",
                  "httpMethod": "PATCH",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Updates a Collection.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}"
                },
                "getDataConnector": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.collections.getDataConnector",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Gets the DataConnector. DataConnector is a singleton resource for each Collection."
                },
                "delete": {
                  "id": "discoveryengine.projects.locations.collections.delete",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "description": "Deletes a Collection."
                },
                "updateDataConnector": {
                  "id": "discoveryengine.projects.locations.collections.updateDataConnector",
                  "description": "Updates a DataConnector.",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                }
              },
              "resources": {
                "dataStores": {
                  "methods": {
                    "get": {
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "id": "discoveryengine.projects.locations.collections.dataStores.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "description": "Gets a DataStore."
                    },
                    "removePatientFilter": {
                      "path": "v1alpha/{+dataStore}:removePatientFilter",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:removePatientFilter",
                      "id": "discoveryengine.projects.locations.collections.dataStores.removePatientFilter",
                      "httpMethod": "POST",
                      "description": "Removes a group of patient IDs from the patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the list of patient IDs to remove will be constructed from the direct me[...]"
                    },
                    "updateDocumentProcessingConfig": {
                      "description": "Updates the DocumentProcessingConfig. DocumentProcessingConfig is a singleon resource of DataStore. It's empty when DataStore is created. The first call to this method will set up DocumentProcessingConfig.",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.collections.dataStores.updateDocumentProcessingConfig",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/documentProcessingConfig"
                    },
                    "list": {
                      "description": "Lists all the DataStores associated with the project.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/dataStores",
                      "id": "discoveryengine.projects.locations.collections.dataStores.list",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores"
                    },
                    "replacePatientFilter": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:replacePatientFilter",
                      "description": "Replaces the patient filter for the data store. This method is essentially a combination of DeletePatientFilters and AddPatientFilter. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the new filt[...]",
                      "path": "v1alpha/{+dataStore}:replacePatientFilter",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.dataStores.replacePatientFilter",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "create": {
                      "path": "v1alpha/{+parent}/dataStores",
                      "id": "discoveryengine.projects.locations.collections.dataStores.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores",
                      "httpMethod": "POST",
                      "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately."
                    },
                    "patch": {
                      "description": "Updates a DataStore",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.dataStores.patch"
                    },
                    "deletePatientFilter": {
                      "description": "Deletes the entire patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter.",
                      "path": "v1alpha/{+dataStore}:deletePatientFilter",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:deletePatientFilter",
                      "id": "discoveryengine.projects.locations.collections.dataStores.deletePatientFilter",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "delete": {
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.collections.dataStores.delete",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "DELETE",
                      "description": "Deletes a DataStore."
                    },
                    "trainCustomModel": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.trainCustomModel",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:trainCustomModel",
                      "description": "Trains a custom model.",
                      "path": "v1alpha/{+dataStore}:trainCustomModel",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "getSiteSearchEngine": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine",
                      "id": "discoveryengine.projects.locations.collections.dataStores.getSiteSearchEngine",
                      "path": "v1alpha/{+name}",
                      "description": "Gets the SiteSearchEngine.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET"
                    },
                    "addPatientFilter": {
                      "path": "v1alpha/{+dataStore}:addPatientFilter",
                      "id": "discoveryengine.projects.locations.collections.dataStores.addPatientFilter",
                      "httpMethod": "POST",
                      "description": "Adds a group of patient IDs as a patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. The filter group must be a FHIR resource name of type Group, and the filter will be constructed from the direct members of the group which are Patient resources.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:addPatientFilter",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "getDocumentProcessingConfig": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets a DocumentProcessingConfig.",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.collections.dataStores.getDocumentProcessingConfig"
                    },
                    "completeQuery": {
                      "description": "Completes the specified user input with keyword suggestions.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:completeQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+dataStore}:completeQuery",
                      "id": "discoveryengine.projects.locations.collections.dataStores.completeQuery",
                      "httpMethod": "GET"
                    }
                  },
                  "resources": {
                    "widgetConfigs": {
                      "methods": {
                        "get": {
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.widgetConfigs.get",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a WidgetConfig.",
                          "httpMethod": "GET"
                        },
                        "patch": {
                          "description": "Update a WidgetConfig.",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                          "httpMethod": "PATCH",
                          "id": "discoveryengine.projects.locations.collections.dataStores.widgetConfigs.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "controls": {
                      "methods": {
                        "patch": {
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "httpMethod": "PATCH"
                        },
                        "create": {
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.create",
                          "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "path": "v1alpha/{+parent}/controls",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "get": {
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.get",
                          "description": "Gets a Control.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "httpMethod": "GET"
                        },
                        "list": {
                          "path": "v1alpha/{+parent}/controls",
                          "httpMethod": "GET",
                          "description": "Lists all Controls by their parent DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.list"
                        },
                        "delete": {
                          "path": "v1alpha/{+name}",
                          "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.delete"
                        }
                      }
                    },
                    "userEvents": {
                      "methods": {
                        "purge": {
                          "path": "v1alpha/{+parent}/userEvents:purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.purge",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:purge"
                        },
                        "write": {
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:write",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.write",
                          "path": "v1alpha/{+parent}/userEvents:write",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Writes a single user event."
                        },
                        "collect": {
                          "httpMethod": "GET",
                          "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:collect",
                          "path": "v1alpha/{+parent}/userEvents:collect",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.collect"
                        },
                        "import": {
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:import",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.import",
                          "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/userEvents:import"
                        }
                      }
                    },
                    "customModels": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.customModels.list",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/customModels",
                          "httpMethod": "GET",
                          "description": "Gets a list of all the custom models.",
                          "path": "v1alpha/{+dataStore}/customModels"
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "converse": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.converse",
                          "description": "Converses a conversation.",
                          "path": "v1alpha/{+name}:converse",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "delete": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.delete",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "httpMethod": "DELETE"
                        },
                        "patch": {
                          "httpMethod": "PATCH",
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.patch"
                        },
                        "list": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/conversations",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.list",
                          "description": "Lists all Conversations by their parent DataStore.",
                          "httpMethod": "GET"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a Conversation.",
                          "httpMethod": "GET",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.get"
                        },
                        "create": {
                          "path": "v1alpha/{+parent}/conversations",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.create",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned."
                        }
                      }
                    },
                    "completionConfig": {
                      "methods": {
                        "completeQuery": {
                          "description": "Completes the user input with advanced keyword suggestions.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud_search.query",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionConfig.completeQuery",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                          "path": "v1alpha/{+completionConfig}:completeQuery",
                          "httpMethod": "POST"
                        }
                      }
                    },
                    "schemas": {
                      "methods": {
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a Schema.",
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.get",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}"
                        },
                        "patch": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "description": "Updates a Schema.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.patch"
                        },
                        "list": {
                          "path": "v1alpha/{+parent}/schemas",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.list",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "description": "Gets a list of Schemas."
                        },
                        "create": {
                          "description": "Creates a Schema.",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.create",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/schemas"
                        },
                        "delete": {
                          "description": "Deletes a Schema.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.delete",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "httpMethod": "DELETE",
                          "path": "v1alpha/{+name}"
                        }
                      },
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations",
                              "httpMethod": "GET",
                              "path": "v1alpha/{+name}/operations",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.list"
                            },
                            "get": {
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "path": "v1alpha/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.get",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations/{operationsId}",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            }
                          }
                        }
                      }
                    },
                    "servingConfigs": {
                      "methods": {
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "httpMethod": "GET"
                        },
                        "patch": {
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.patch",
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "httpMethod": "PATCH",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "list": {
                          "path": "v1alpha/{+parent}/servingConfigs",
                          "description": "Lists all ServingConfigs linked to this dataStore.",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "search": {
                          "path": "v1alpha/{+servingConfig}:search",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.search",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                          "description": "Performs a search.",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "recommend": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                          "path": "v1alpha/{+servingConfig}:recommend",
                          "description": "Makes a recommendation, which requires a contextual user event.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.recommend",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "delete": {
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.delete",
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                          "path": "v1alpha/{+parent}/servingConfigs",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.create"
                        },
                        "streamAnswer": {
                          "httpMethod": "POST",
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                          "path": "v1alpha/{+servingConfig}:streamAnswer",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.streamAnswer"
                        },
                        "searchLite": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                          "httpMethod": "POST",
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.searchLite",
                          "path": "v1alpha/{+servingConfig}:searchLite"
                        },
                        "answer": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.answer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+servingConfig}:answer",
                          "description": "Answer query method.",
                          "httpMethod": "POST"
                        }
                      }
                    },
                    "sessions": {
                      "resources": {
                        "answers": {
                          "methods": {
                            "get": {
                              "description": "Gets a Answer.",
                              "httpMethod": "GET",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                              "path": "v1alpha/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.sessions.answers.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            }
                          }
                        }
                      },
                      "methods": {
                        "create": {
                          "path": "v1alpha/{+parent}/sessions",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.create",
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions"
                        },
                        "get": {
                          "description": "Gets a Session.",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.get",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}"
                        },
                        "list": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "path": "v1alpha/{+parent}/sessions",
                          "description": "Lists all Sessions by their parent DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.list"
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.patch",
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}"
                        },
                        "delete": {
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.delete",
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "httpMethod": "DELETE"
                        }
                      }
                    },
                    "models": {
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.list",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}/operations"
                            },
                            "get": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.get",
                              "httpMethod": "GET",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                            }
                          }
                        }
                      }
                    },
                    "suggestionDenyListEntries": {
                      "methods": {
                        "import": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.import",
                          "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                          "path": "v1alpha/{+parent}/suggestionDenyListEntries:import"
                        },
                        "purge": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                          "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge"
                        }
                      }
                    },
                    "branches": {
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.list",
                              "httpMethod": "GET",
                              "path": "v1alpha/{+name}/operations",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                            },
                            "cancel": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.cancel",
                              "path": "v1alpha/{+name}:cancel",
                              "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; in[...]",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "POST"
                            },
                            "get": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.get",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "httpMethod": "GET"
                            }
                          }
                        },
                        "documents": {
                          "resources": {
                            "chunks": {
                              "methods": {
                                "list": {
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks",
                                  "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.chunks.list",
                                  "description": "Gets a list of Chunks.",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "httpMethod": "GET",
                                  "path": "v1alpha/{+parent}/chunks"
                                },
                                "get": {
                                  "description": "Gets a Document.",
                                  "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.chunks.get",
                                  "httpMethod": "GET",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "path": "v1alpha/{+name}",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks/{chunksId}"
                                }
                              }
                            }
                          },
                          "methods": {
                            "delete": {
                              "description": "Deletes a Document.",
                              "path": "v1alpha/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.delete",
                              "httpMethod": "DELETE",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}"
                            },
                            "import": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.import",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                              "path": "v1alpha/{+parent}/documents:import",
                              "httpMethod": "POST"
                            },
                            "purge": {
                              "httpMethod": "POST",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.purge",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                              "path": "v1alpha/{+parent}/documents:purge",
                              "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            },
                            "getProcessedDocument": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}:getProcessedDocument",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.getProcessedDocument",
                              "httpMethod": "GET",
                              "path": "v1alpha/{+name}:getProcessedDocument",
                              "description": "Gets the parsed layout information for a Document."
                            },
                            "get": {
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.get",
                              "path": "v1alpha/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "description": "Gets a Document."
                            },
                            "create": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "description": "Creates a Document.",
                              "path": "v1alpha/{+parent}/documents",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "POST",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.create"
                            },
                            "patch": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.patch",
                              "description": "Updates a Document.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}",
                              "httpMethod": "PATCH",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}"
                            },
                            "list": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.list",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+parent}/documents",
                              "description": "Gets a list of Documents."
                            }
                          }
                        }
                      },
                      "methods": {
                        "batchGetDocumentsMetadata": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                          "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.batchGetDocumentsMetadata",
                          "path": "v1alpha/{+parent}/batchGetDocumentsMetadata",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "get": {
                          "path": "v1alpha/{+name}",
                          "description": "Retrieves a Branch.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET"
                        },
                        "list": {
                          "description": "Lists all Branchs under the specified parent DataStore.",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches",
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.list",
                          "path": "v1alpha/{+parent}/branches",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "operations": {
                      "methods": {
                        "list": {
                          "path": "v1alpha/{+name}/operations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.list",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations/{operationsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                        }
                      }
                    },
                    "siteSearchEngine": {
                      "methods": {
                        "batchVerifyTargetSites": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:batchVerifyTargetSites",
                          "description": "Verify target sites' ownership and validity. This API sends all the target sites under site search engine for verification.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.batchVerifyTargetSites",
                          "path": "v1alpha/{+parent}:batchVerifyTargetSites",
                          "httpMethod": "POST"
                        },
                        "fetchDomainVerificationStatus": {
                          "httpMethod": "GET",
                          "description": "Returns list of target sites with its domain verification status. This method can only be called under data store with BASIC_SITE_SEARCH state at the moment.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.fetchDomainVerificationStatus",
                          "path": "v1alpha/{+siteSearchEngine}:fetchDomainVerificationStatus",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:fetchDomainVerificationStatus",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "disableAdvancedSiteSearch": {
                          "path": "v1alpha/{+siteSearchEngine}:disableAdvancedSiteSearch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "description": "Downgrade from advanced site search to basic site search.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.disableAdvancedSiteSearch"
                        },
                        "setUriPatternDocumentData": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:setUriPatternDocumentData",
                          "path": "v1alpha/{+siteSearchEngine}:setUriPatternDocumentData",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Sets the URI Pattern to Document data mapping for an Advanced Site Search DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.setUriPatternDocumentData",
                          "httpMethod": "POST"
                        },
                        "enableAdvancedSiteSearch": {
                          "path": "v1alpha/{+siteSearchEngine}:enableAdvancedSiteSearch",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Upgrade from basic site search to advanced site search.",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.enableAdvancedSiteSearch"
                        },
                        "getUriPatternDocumentData": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:getUriPatternDocumentData",
                          "httpMethod": "GET",
                          "path": "v1alpha/{+siteSearchEngine}:getUriPatternDocumentData",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.getUriPatternDocumentData",
                          "description": "Gets the URI Pattern to Document data mapping for an Advanced Site Search DataStore."
                        },
                        "recrawlUris": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.recrawlUris",
                          "httpMethod": "POST",
                          "description": "Request on-demand recrawl for a list of URIs.",
                          "path": "v1alpha/{+siteSearchEngine}:recrawlUris"
                        }
                      },
                      "resources": {
                        "operations": {
                          "methods": {
                            "get": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/operations/{operationsId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.operations.get",
                              "httpMethod": "GET",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "path": "v1alpha/{+name}"
                            },
                            "list": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.operations.list",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/operations",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}/operations",
                              "httpMethod": "GET"
                            }
                          }
                        },
                        "sitemaps": {
                          "methods": {
                            "delete": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}",
                              "description": "Deletes a Sitemap.",
                              "httpMethod": "DELETE",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.delete",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}"
                            },
                            "fetch": {
                              "httpMethod": "GET",
                              "description": "Fetch Sitemaps in a DataStore.",
                              "path": "v1alpha/{+parent}/sitemaps:fetch",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.fetch",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch"
                            },
                            "create": {
                              "path": "v1alpha/{+parent}/sitemaps",
                              "description": "Creates a Sitemap.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.create",
                              "httpMethod": "POST",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps"
                            }
                          }
                        },
                        "targetSites": {
                          "methods": {
                            "patch": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Updates a TargetSite.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.patch",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "PATCH"
                            },
                            "batchCreate": {
                              "description": "Creates TargetSite in a batch.",
                              "path": "v1alpha/{+parent}/targetSites:batchCreate",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                              "httpMethod": "POST",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.batchCreate",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            },
                            "delete": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Deletes a TargetSite.",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "DELETE",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.delete"
                            },
                            "get": {
                              "path": "v1alpha/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.get",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Gets a TargetSite."
                            },
                            "create": {
                              "path": "v1alpha/{+parent}/targetSites",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Creates a TargetSite.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.create",
                              "httpMethod": "POST",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites"
                            },
                            "list": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.list",
                              "path": "v1alpha/{+parent}/targetSites",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                              "description": "Gets a list of TargetSites.",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            }
                          },
                          "resources": {
                            "operations": {
                              "methods": {
                                "list": {
                                  "httpMethod": "GET",
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.list",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations",
                                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "path": "v1alpha/{+name}/operations"
                                },
                                "get": {
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations/{operationsId}",
                                  "path": "v1alpha/{+name}",
                                  "httpMethod": "GET",
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.get"
                                }
                              }
                            }
                          }
                        }
                      }
                    },
                    "completionSuggestions": {
                      "methods": {
                        "import": {
                          "path": "v1alpha/{+parent}/completionSuggestions:import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "description": "Imports CompletionSuggestions for a DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.import",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:import"
                        },
                        "purge": {
                          "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                          "path": "v1alpha/{+parent}/completionSuggestions:purge",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:purge"
                        }
                      }
                    }
                  }
                },
                "dataConnector": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.list",
                          "path": "v1alpha/{+name}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                        },
                        "get": {
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations/{operationsId}",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.get",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                        }
                      }
                    },
                    "connectorRuns": {
                      "methods": {
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.dataConnector.connectorRuns.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/connectorRuns",
                          "description": "Lists the ConnectorRuns of a DataConnector.",
                          "path": "v1alpha/{+parent}/connectorRuns"
                        }
                      }
                    }
                  },
                  "methods": {
                    "acquireAccessToken": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Uses the per-user refresh token minted with AcquireAndStoreRefreshToken to generate and return a new access token and its details. Takes the access token from cache if available. Rotates the stored refresh token if needed. Uses the end user identity to return the user specific access token. Does *not* return the credentials configured by the administrator. Used by action execution and UI.",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.dataConnector.acquireAccessToken",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:acquireAccessToken",
                      "path": "v1alpha/{+name}:acquireAccessToken"
                    },
                    "getConnectorSecret": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:getConnectorSecret",
                      "httpMethod": "GET",
                      "description": "Get the secret for the associated connector.",
                      "id": "discoveryengine.projects.locations.collections.dataConnector.getConnectorSecret",
                      "path": "v1alpha/{+name}:getConnectorSecret",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "checkRefreshToken": {
                      "id": "discoveryengine.projects.locations.collections.dataConnector.checkRefreshToken",
                      "description": "Deprecated: Checks the existence of a refresh token for the EUC user for a given connection and returns its details. Use AcquireAccessToken instead and then check the validity of the returned token by asking the 3rd party system. There's no way to know for sure if a refresh token is valid without asking the 3rd party system.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:checkRefreshToken",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}:checkRefreshToken",
                      "deprecated": true
                    },
                    "startConnectorRun": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:startConnectorRun",
                      "path": "v1alpha/{+parent}:startConnectorRun",
                      "id": "discoveryengine.projects.locations.collections.dataConnector.startConnectorRun",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Starts an immediate synchronization process for a DataConnector. Third Party Connector Users must specify which entities should be synced. FHIR Connectors must provide a timestamp to indicate the point in time from which data should be synced.",
                      "httpMethod": "POST"
                    }
                  }
                },
                "engines": {
                  "methods": {
                    "delete": {
                      "path": "v1alpha/{+name}",
                      "description": "Deletes an Engine.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.collections.engines.delete",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}"
                    },
                    "create": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/engines",
                      "description": "Creates an Engine.",
                      "id": "discoveryengine.projects.locations.collections.engines.create",
                      "httpMethod": "POST"
                    },
                    "patch": {
                      "description": "Updates an Engine",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.collections.engines.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}"
                    },
                    "getIamPolicy": {
                      "id": "discoveryengine.projects.locations.collections.engines.getIamPolicy",
                      "path": "v1alpha/{+resource}:getIamPolicy",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:getIamPolicy",
                      "httpMethod": "GET",
                      "description": "Gets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. An empty policy is returned if the resource exists but does not have a policy set on it.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "list": {
                      "description": "Lists all the Engines associated with the project.",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+parent}/engines",
                      "id": "discoveryengine.projects.locations.collections.engines.list",
[...]
