{
  "basePath": "",
  "batchPath": "batch",
  "description": "Discovery Engine API.",
  "id": "discoveryengine:v1alpha",
  "documentationLink": "https://cloud.google.com/generative-ai-app-builder/docs/",
  "servicePath": "",
  "name": "discoveryengine",
  "fullyEncodeReservedExpansion": true,
  "ownerDomain": "google.com",
  "title": "Discovery Engine API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/discoveryengine.readwrite": {
          "description": "View, edit, create, and delete all your data associated with any Discovery Engine API product, such as Agentspace, Vertex AI Search, or NotebookLM Enterprise, including both end user data and administration or configuration data."
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite": {
          "description": "View your Agentspace chat history, including uploaded files and generated reports and visualizations, and interact with the Agentspace assistant on your behalf."
        },
        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite": {
          "description": "Interact with Discovery Engine API products, such as Agentspace, Vertex AI Search, or NotebookLM Enterprise, on your behalf. It will also allow the app to view all data that you have access to when you use or interact with a Discovery Engine API product."
        }
      }
    }
  },
  "ownerName": "Google",
  "revision": "20260427",
  "protocol": "rest",
  "rootUrl": "https://discoveryengine.googleapis.com/",
  "kind": "discovery#restDescription",
  "baseUrl": "https://discoveryengine.googleapis.com/",
  "version_module": true,
  "discoveryVersion": "v1",
  "resources": {
    "billingAccounts": {
      "resources": {
        "billingAccountLicenseConfigs": {
          "methods": {
            "distributeLicenseConfig": {
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}:distributeLicenseConfig",
              "description": "Distributes a LicenseConfig from billing account level to project level.",
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.distributeLicenseConfig",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "path": "v1alpha/{+billingAccountLicenseConfig}:distributeLicenseConfig",
              "httpMethod": "POST"
            },
            "get": {
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.get",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}",
              "description": "Gets a BillingAccountLicenseConfig."
            },
            "retractLicenseConfig": {
              "description": "This method is called from the billing account side to retract the LicenseConfig from the given project back to the billing account.",
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}:retractLicenseConfig",
              "path": "v1alpha/{+billingAccountLicenseConfig}:retractLicenseConfig",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.retractLicenseConfig"
            },
            "list": {
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.list",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "path": "v1alpha/{+parent}/billingAccountLicenseConfigs",
              "httpMethod": "GET",
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs",
              "description": "Lists all BillingAccountLicenseConfigs for a given billing account."
            }
          }
        }
      }
    },
    "projects": {
      "methods": {
        "patch": {
          "path": "v1alpha/{+name}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite",
            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
          ],
          "id": "discoveryengine.projects.patch",
          "description": "Updates the editable settings of a Discovery Engine Project.",
          "flatPath": "v1alpha/projects/{projectsId}"
        },
        "get": {
          "description": "Gets a Project. Returns NOT_FOUND when the project is not yet created.",
          "flatPath": "v1alpha/projects/{projectsId}",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite",
            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
          ],
          "path": "v1alpha/{+name}",
          "httpMethod": "GET",
          "id": "discoveryengine.projects.get"
        },
        "reportConsentChange": {
          "id": "discoveryengine.projects.reportConsentChange",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite",
            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
          ],
          "path": "v1alpha/{+project}:reportConsentChange",
          "httpMethod": "POST",
          "flatPath": "v1alpha/projects/{projectsId}:reportConsentChange",
          "description": "Updates service terms for this project. This method can be used to retroactively accept the latest terms. Terms available for update: * [Terms for data use](https://cloud.google.com/retail/data-use-terms)"
        },
        "provision": {
          "flatPath": "v1alpha/projects/{projectsId}:provision",
          "description": "Provisions the project resource. During the process, related systems will get prepared and initialized. Caller must read the [Terms for data use](https://cloud.google.com/retail/data-use-terms), and optionally specify in request to provide consent to that service terms.",
          "id": "discoveryengine.projects.provision",
          "path": "v1alpha/{+name}:provision",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite",
            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
          ]
        }
      },
      "resources": {
        "locations": {
          "methods": {
            "getAclConfig": {
              "description": "Gets the AclConfig.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/aclConfig",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "id": "discoveryengine.projects.locations.getAclConfig"
            },
            "updateCmekConfig": {
              "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfig",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "id": "discoveryengine.projects.locations.updateCmekConfig"
            },
            "removeDedicatedCrawlRate": {
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:removeDedicatedCrawlRate",
              "description": "Removes the dedicated crawl rate for a craw_rate_scope. If the dedicated crawl rate was set, this will disable vertex AI's crawl bot from using the dedicated crawl rate for crawling. If the dedicated crawl rate was not set, this is a no-op.",
              "id": "discoveryengine.projects.locations.removeDedicatedCrawlRate",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "path": "v1alpha/{+location}:removeDedicatedCrawlRate",
              "httpMethod": "POST"
            },
            "setUpDataConnectorV2": {
              "id": "discoveryengine.projects.locations.setUpDataConnectorV2",
              "path": "v1alpha/{+parent}:setUpDataConnectorV2",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setUpDataConnectorV2",
              "description": "Creates a Collection and sets up the DataConnector for it. To stop a DataConnector after setup, use the CollectionService.DeleteCollection method."
            },
            "setUpDataConnector": {
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setUpDataConnector",
              "description": "Creates a Collection and sets up the DataConnector for it. To stop a DataConnector after setup, use the CollectionService.DeleteCollection method.",
              "id": "discoveryengine.projects.locations.setUpDataConnector",
              "path": "v1alpha/{+parent}:setUpDataConnector",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ]
            },
            "obtainCrawlRate": {
              "path": "v1alpha/{+location}:obtainCrawlRate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "id": "discoveryengine.projects.locations.obtainCrawlRate",
              "description": "Obtains the time series data of organic or dedicated crawl rate for monitoring. When dedicated crawl rate is not set, it will return vertex AI's organic crawl rate time series. Organic crawl means Google automatically crawl the internet at its own convenience. When dedicated crawl rate is set, it will return vertex AI's dedicated crawl rate time series.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:obtainCrawlRate"
            },
            "setDedicatedCrawlRate": {
              "description": "Sets the dedicated crawl rate for a crawl_rate_scope. If the dedicated crawl rate was not set, this will enable vertex AI's crawl bot to use the new dedicated crawl rate for crawling. If the dedicated crawl rate was set, vertex AI's crawl bot will try to update the rate to the new value. If the new value is too high, the crawl bot may crawl at a lower rate to avoid overloading the user's website.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setDedicatedCrawlRate",
              "path": "v1alpha/{+location}:setDedicatedCrawlRate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "id": "discoveryengine.projects.locations.setDedicatedCrawlRate"
            },
            "queryConfigurablePricingUsageStats": {
              "description": "Queries configurable pricing usage stats for a project.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{location}:queryConfigurablePricingUsageStats",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "path": "v1alpha/{+project}/locations/{location}:queryConfigurablePricingUsageStats",
              "httpMethod": "GET",
              "id": "discoveryengine.projects.locations.queryConfigurablePricingUsageStats"
            },
            "updateAclConfig": {
              "id": "discoveryengine.projects.locations.updateAclConfig",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/aclConfig",
              "description": "Default ACL configuration for use in a location of a customer's project. Updates will only reflect to new data stores. Existing data stores will still use the old value."
            },
            "getCmekConfig": {
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfig",
              "description": "Gets the CmekConfig.",
              "id": "discoveryengine.projects.locations.getCmekConfig",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ]
            },
            "estimateDataSize": {
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:estimateDataSize",
              "description": "Estimates the data size to be used by a customer.",
              "id": "discoveryengine.projects.locations.estimateDataSize",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "path": "v1alpha/{+location}:estimateDataSize",
              "httpMethod": "POST"
            },
            "completeExternalIdentities": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "path": "v1alpha/{+parent}:completeExternalIdentities",
              "httpMethod": "GET",
              "id": "discoveryengine.projects.locations.completeExternalIdentities",
              "description": "This method provides suggestions for users and groups managed in an external identity provider, based on the provided prefix.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:completeExternalIdentities"
            }
          },
          "resources": {
            "licenseConfigs": {
              "methods": {
                "create": {
                  "id": "discoveryengine.projects.locations.licenseConfigs.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/licenseConfigs",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs",
                  "description": "Creates a LicenseConfig This method should only be used for creating NotebookLm licenses or Gemini Enterprise free trial licenses."
                },
                "get": {
                  "description": "Gets a LicenseConfig.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.licenseConfigs.get"
                },
                "patch": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}",
                  "description": "Updates the LicenseConfig",
                  "id": "discoveryengine.projects.locations.licenseConfigs.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                }
              }
            },
            "evaluations": {
              "methods": {
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}",
                  "description": "Gets a Evaluation.",
                  "id": "discoveryengine.projects.locations.evaluations.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET"
                },
                "listResults": {
                  "id": "discoveryengine.projects.locations.evaluations.listResults",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+evaluation}:listResults",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}:listResults",
                  "description": "Gets a list of results for a given a Evaluation."
                },
                "create": {
                  "description": "Creates a Evaluation. Upon creation, the evaluation will be automatically triggered and begin execution.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/evaluations",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.evaluations.create"
                },
                "list": {
                  "description": "Gets a list of Evaluations.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/evaluations",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.evaluations.list"
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}/operations/{operationsId}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.evaluations.operations.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                }
              }
            },
            "userStores": {
              "methods": {
                "patch": {
                  "id": "discoveryengine.projects.locations.userStores.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "description": "Updates the User Store."
                },
                "batchUpdateUserLicenses": {
                  "path": "v1alpha/{+parent}:batchUpdateUserLicenses",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.userStores.batchUpdateUserLicenses",
                  "description": "Updates the User License. This method is used for batch assign/unassign licenses to users.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}:batchUpdateUserLicenses"
                },
                "get": {
                  "description": "Gets the User Store.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.userStores.get"
                }
              },
              "resources": {
                "licenseConfigsUsageStats": {
                  "methods": {
                    "list": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/licenseConfigsUsageStats",
                      "description": "Lists all the LicenseConfigUsageStatss associated with the project.",
                      "id": "discoveryengine.projects.locations.userStores.licenseConfigsUsageStats.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/licenseConfigsUsageStats",
                      "httpMethod": "GET"
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/operations/{operationsId}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.userStores.operations.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}/operations",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.userStores.operations.list",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/operations"
                    }
                  }
                },
                "userLicenses": {
                  "methods": {
                    "list": {
                      "id": "discoveryengine.projects.locations.userStores.userLicenses.list",
                      "path": "v1alpha/{+parent}/userLicenses",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/userLicenses",
                      "description": "Lists the User Licenses."
                    }
                  }
                }
              }
            },
            "dataStores": {
              "methods": {
                "delete": {
                  "description": "Deletes a DataStore.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "id": "discoveryengine.projects.locations.dataStores.delete"
                },
                "getSiteSearchEngine": {
                  "description": "Gets the SiteSearchEngine.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.dataStores.getSiteSearchEngine"
                },
                "removePatientFilter": {
                  "path": "v1alpha/{+dataStore}:removePatientFilter",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.removePatientFilter",
                  "description": "Removes a group of patient IDs from the patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the list of patient IDs to remove will be constructed from the direct member[...]",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:removePatientFilter"
                },
                "patch": {
                  "id": "discoveryengine.projects.locations.dataStores.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "description": "Updates a DataStore"
                },
                "create": {
                  "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/dataStores",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.dataStores.create"
                },
                "deletePatientFilter": {
                  "id": "discoveryengine.projects.locations.dataStores.deletePatientFilter",
                  "path": "v1alpha/{+dataStore}:deletePatientFilter",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:deletePatientFilter",
                  "description": "Deletes the entire patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter."
                },
                "get": {
                  "id": "discoveryengine.projects.locations.dataStores.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "description": "Gets a DataStore."
                },
                "updateDocumentProcessingConfig": {
                  "id": "discoveryengine.projects.locations.dataStores.updateDocumentProcessingConfig",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                  "description": "Updates the DocumentProcessingConfig. DocumentProcessingConfig is a singleon resource of DataStore. It's empty when DataStore is created. The first call to this method will set up DocumentProcessingConfig."
                },
                "replacePatientFilter": {
                  "id": "discoveryengine.projects.locations.dataStores.replacePatientFilter",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+dataStore}:replacePatientFilter",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:replacePatientFilter",
                  "description": "Replaces the patient filter for the data store. This method is essentially a combination of DeletePatientFilters and AddPatientFilter. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the new filter w[...]"
                },
                "getDocumentProcessingConfig": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.dataStores.getDocumentProcessingConfig",
                  "description": "Gets a DocumentProcessingConfig.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig"
                },
                "addPatientFilter": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:addPatientFilter",
                  "description": "Adds a group of patient IDs as a patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. The filter group must be a FHIR resource name of type Group, and the filter will be constructed from the direct members of the group which are Patient resources.",
                  "id": "discoveryengine.projects.locations.dataStores.addPatientFilter",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+dataStore}:addPatientFilter",
                  "httpMethod": "POST"
                },
                "list": {
                  "path": "v1alpha/{+parent}/dataStores",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.list",
                  "description": "Lists all the DataStores associated with the project.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores"
                },
                "completeQuery": {
                  "description": "Completes the specified user input with keyword suggestions.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:completeQuery",
                  "path": "v1alpha/{+dataStore}:completeQuery",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.completeQuery"
                }
              },
              "resources": {
                "models": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "get": {
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.get"
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}/operations",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.list",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations"
                        }
                      }
                    }
                  }
                },
                "completionConfig": {
                  "methods": {
                    "completeQuery": {
                      "description": "Completes the user input with advanced keyword suggestions.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                      "path": "v1alpha/{+completionConfig}:completeQuery",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud_search.query",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.completionConfig.completeQuery"
                    }
                  }
                },
                "controls": {
                  "methods": {
                    "patch": {
                      "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.controls.patch"
                    },
                    "create": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.create",
                      "path": "v1alpha/{+parent}/controls",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "delete": {
                      "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.controls.delete"
                    },
                    "list": {
                      "description": "Lists all Controls by their parent DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "path": "v1alpha/{+parent}/controls",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.controls.list"
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.controls.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "description": "Gets a Control."
                    }
                  }
                },
                "schemas": {
                  "methods": {
                    "patch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "description": "Updates a Schema.",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.patch",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "create": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/schemas",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "description": "Creates a Schema."
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.list",
                      "path": "v1alpha/{+parent}/schemas",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "description": "Gets a list of Schemas."
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.delete",
                      "description": "Deletes a Schema.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}"
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "description": "Gets a Schema."
                    }
                  }
                },
                "conversations": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.conversations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "description": "Gets a Conversation."
                    },
                    "delete": {
                      "id": "discoveryengine.projects.locations.dataStores.conversations.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned."
                    },
                    "list": {
                      "description": "Lists all Conversations by their parent DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/conversations",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.list"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/conversations",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.create",
                      "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations"
                    },
                    "converse": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                      "description": "Converses a conversation.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.converse",
                      "path": "v1alpha/{+name}:converse",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.patch",
                      "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}"
                    }
                  }
                },
                "branches": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/branches",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.branches.list",
                      "description": "Lists all Branchs under the specified parent DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches"
                    },
                    "batchGetDocumentsMetadata": {
                      "id": "discoveryengine.projects.locations.dataStores.branches.batchGetDocumentsMetadata",
                      "path": "v1alpha/{+parent}/batchGetDocumentsMetadata",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                      "description": "Gets index freshness metadata for Documents. Supported for website search only."
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.branches.get",
                      "description": "Retrieves a Branch.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}"
                    }
                  },
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.list",
                          "path": "v1alpha/{+name}/operations",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                        },
                        "cancel": {
                          "path": "v1alpha/{+name}:cancel",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.cancel",
                          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instea[...]",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel"
                        }
                      }
                    },
                    "documents": {
                      "methods": {
                        "get": {
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.get",
                          "description": "Gets a Document.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}"
                        },
                        "getProcessedDocument": {
                          "description": "Gets the parsed layout information for a Document.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}:getProcessedDocument",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}:getProcessedDocument",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.getProcessedDocument"
                        },
                        "list": {
                          "path": "v1alpha/{+parent}/documents",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.list",
                          "description": "Gets a list of Documents.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents"
                        },
                        "delete": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "description": "Deletes a Document.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE"
                        },
                        "import": {
                          "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                          "path": "v1alpha/{+parent}/documents:import",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.import"
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/documents",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "description": "Creates a Document."
                        },
                        "patch": {
                          "description": "Updates a Document.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.patch"
                        },
                        "purge": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/documents:purge",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                          "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false."
                        }
                      },
                      "resources": {
                        "chunks": {
                          "methods": {
                            "get": {
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.get",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks/{chunksId}",
                              "description": "Gets a Document."
                            },
                            "list": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "path": "v1alpha/{+parent}/chunks",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.list",
                              "description": "Gets a list of Chunks.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "userEvents": {
                  "methods": {
                    "write": {
                      "description": "Writes a single user event.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:write",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/userEvents:write",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.write"
                    },
                    "import": {
                      "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:import",
                      "path": "v1alpha/{+parent}/userEvents:import",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.import"
                    },
                    "collect": {
                      "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:collect",
                      "path": "v1alpha/{+parent}/userEvents:collect",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.collect"
                    },
                    "purge": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:purge",
                      "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/userEvents:purge",
                      "httpMethod": "POST"
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}/operations",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.operations.list",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations"
                    },
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations/{operationsId}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.dataStores.operations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET"
                    }
                  }
                },
                "completionSuggestions": {
                  "methods": {
                    "import": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/completionSuggestions:import",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.import",
                      "description": "Imports CompletionSuggestions for a DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:import"
                    },
                    "purge": {
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/completionSuggestions:purge",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                      "description": "Permanently deletes all CompletionSuggestions for a DataStore."
                    }
                  }
                },
                "sessions": {
                  "methods": {
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.patch",
                      "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}"
                    },
                    "create": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.create",
                      "path": "v1alpha/{+parent}/sessions",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "delete": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.delete",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "list": {
                      "description": "Lists all Sessions by their parent DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "path": "v1alpha/{+parent}/sessions",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.sessions.list"
                    },
                    "get": {
                      "description": "Gets a Session.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.get"
                    }
                  },
                  "resources": {
                    "answers": {
                      "methods": {
                        "get": {
                          "description": "Gets a Answer.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.sessions.answers.get"
                        }
                      }
                    }
                  }
                },
                "suggestionDenyListEntries": {
                  "methods": {
                    "import": {
                      "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:import",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.import"
                    },
                    "purge": {
                      "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.purge"
                    }
                  }
                },
                "siteSearchEngine": {
                  "methods": {
                    "recrawlUris": {
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.recrawlUris",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+siteSearchEngine}:recrawlUris",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                      "description": "Request on-demand recrawl for a list of URIs."
                    },
                    "disableAdvancedSiteSearch": {
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.disableAdvancedSiteSearch",
                      "path": "v1alpha/{+siteSearchEngine}:disableAdvancedSiteSearch",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                      "description": "Downgrade from advanced site search to basic site search."
                    },
                    "enableAdvancedSiteSearch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+siteSearchEngine}:enableAdvancedSiteSearch",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.enableAdvancedSiteSearch",
                      "description": "Upgrade from basic site search to advanced site search.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch"
                    }
                  },
                  "resources": {
                    "targetSites": {
                      "methods": {
                        "get": {
                          "description": "Gets a TargetSite.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.get"
                        },
                        "delete": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "description": "Deletes a TargetSite.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.delete",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "list": {
                          "description": "Gets a list of TargetSites.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "path": "v1alpha/{+parent}/targetSites",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.list"
                        },
                        "create": {
                          "description": "Creates a TargetSite.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/targetSites",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.create"
                        },
                        "batchCreate": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                          "description": "Creates TargetSite in a batch.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.batchCreate",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/targetSites:batchCreate",
                          "httpMethod": "POST"
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "description": "Updates a TargetSite."
                        }
                      }
                    },
                    "sitemaps": {
                      "methods": {
                        "delete": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}",
                          "description": "Deletes a Sitemap.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.delete",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "create": {
                          "path": "v1alpha/{+parent}/sitemaps",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.create",
                          "description": "Creates a Sitemap.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps"
                        },
                        "fetch": {
                          "description": "Fetch Sitemaps in a DataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                          "path": "v1alpha/{+parent}/sitemaps:fetch",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.fetch"
                        }
                      }
                    }
                  }
                },
                "widgetConfigs": {
                  "methods": {
                    "get": {
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.get",
                      "description": "Gets a WidgetConfig.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}"
                    },
                    "patch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                      "description": "Update a WidgetConfig.",
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.patch",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                },
                "servingConfigs": {
                  "methods": {
                    "list": {
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.list",
                      "description": "Lists all ServingConfigs linked to this dataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs"
                    },
                    "searchLite": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.searchLite",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+servingConfig}:searchLite",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                      "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, it i[...]"
                    },
                    "answer": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.answer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+servingConfig}:answer",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                      "description": "Answer query method."
                    },
                    "streamAnswer": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.streamAnswer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+servingConfig}:streamAnswer",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                      "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream."
                    },
                    "get": {
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.get",
                      "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}"
                    },
                    "recommend": {
                      "path": "v1alpha/{+servingConfig}:recommend",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.recommend",
                      "description": "Makes a recommendation, which requires a contextual user event.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend"
                    },
                    "search": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.search",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+servingConfig}:search",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                      "description": "Performs a search."
                    },
                    "delete": {
                      "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.delete"
                    },
                    "patch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.patch",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "create": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.create",
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned."
                    }
                  }
                }
              }
            },
            "groundingConfigs": {
              "methods": {
                "check": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+groundingConfig}:check",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.groundingConfigs.check",
                  "description": "Performs a grounding check.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/groundingConfigs/{groundingConfigsId}:check"
                }
              }
            },
            "podcasts": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.podcasts.operations.get",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/podcasts/{podcastsId}/operations/{operationsId}"
                    }
                  }
                }
              }
            },
            "requirements": {
              "methods": {
                "checkRequirement": {
                  "path": "v1alpha/{+location}/requirements:checkRequirement",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.requirements.checkRequirement",
                  "description": "Check a particular requirement.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/requirements:checkRequirement"
                }
              }
            },
            "userEvents": {
              "methods": {
                "write": {
                  "id": "discoveryengine.projects.locations.userEvents.write",
                  "path": "v1alpha/{+parent}/userEvents:write",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:write",
                  "description": "Writes a single user event."
                },
                "import": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:import",
                  "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                  "id": "discoveryengine.projects.locations.userEvents.import",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/userEvents:import",
                  "httpMethod": "POST"
                },
                "collect": {
                  "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:collect",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/userEvents:collect",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.userEvents.collect"
                }
              }
            },
            "operations": {
              "methods": {
                "list": {
                  "id": "discoveryengine.projects.locations.operations.list",
                  "path": "v1alpha/{+name}/operations",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.operations.get",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}"
                }
              }
            },
            "authorizations": {
              "methods": {
                "create": {
                  "description": "Creates an Authorization.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/authorizations",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.authorizations.create"
                },
                "patch": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "description": "Updates an Authorization",
                  "id": "discoveryengine.projects.locations.authorizations.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "description": "Gets an Authorization.",
                  "id": "discoveryengine.projects.locations.authorizations.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET"
                },
                "delete": {
                  "description": "Deletes an Authorization.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "id": "discoveryengine.projects.locations.authorizations.delete"
                },
                "list": {
                  "id": "discoveryengine.projects.locations.authorizations.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/authorizations",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations",
                  "description": "Lists all Authorizations under an Engine."
                }
              }
            },
            "collections": {
              "methods": {
                "patch": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}",
                  "description": "Updates a Collection.",
                  "id": "discoveryengine.projects.locations.collections.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "updateDataConnector": {
                  "id": "discoveryengine.projects.locations.collections.updateDataConnector",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector",
                  "description": "Updates a DataConnector."
                },
                "list": {
                  "id": "discoveryengine.projects.locations.collections.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/collections",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections",
                  "description": "Gets a list of Collections."
                },
                "delete": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}",
                  "description": "Deletes a Collection.",
                  "id": "discoveryengine.projects.locations.collections.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.collections.get",
                  "description": "Gets a Collection.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}"
                },
                "getDataConnector": {
                  "id": "discoveryengine.projects.locations.collections.getDataConnector",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector",
                  "description": "Gets the DataConnector. DataConnector is a singleton resource for each Collection."
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "list": {
                      "path": "v1alpha/{+name}/operations",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.operations.list",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/operations"
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.collections.operations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/operations/{operationsId}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                    }
                  }
                },
                "dataStores": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.collections.dataStores.get",
                      "description": "Gets a DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}"
                    },
                    "deletePatientFilter": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.deletePatientFilter",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+dataStore}:deletePatientFilter",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:deletePatientFilter",
                      "description": "Deletes the entire patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter."
                    },
                    "getDocumentProcessingConfig": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                      "description": "Gets a DocumentProcessingConfig.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.getDocumentProcessingConfig",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET"
                    },
                    "updateDocumentProcessingConfig": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.collections.dataStores.updateDocumentProcessingConfig",
                      "description": "Updates the DocumentProcessingConfig. DocumentProcessingConfig is a singleon resource of DataStore. It's empty when DataStore is created. The first call to this method will set up DocumentProcessingConfig.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/documentProcessingConfig"
                    },
                    "replacePatientFilter": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.replacePatientFilter",
                      "path": "v1alpha/{+dataStore}:replacePatientFilter",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:replacePatientFilter",
                      "description": "Replaces the patient filter for the data store. This method is essentially a combination of DeletePatientFilters and AddPatientFilter. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the new filt[...]"
                    },
                    "trainCustomModel": {
                      "description": "Trains a custom model.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:trainCustomModel",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+dataStore}:trainCustomModel",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.dataStores.trainCustomModel"
                    },
                    "removePatientFilter": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:removePatientFilter",
                      "description": "Removes a group of patient IDs from the patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the list of patient IDs to remove will be constructed from the direct me[...]",
                      "id": "discoveryengine.projects.locations.collections.dataStores.removePatientFilter",
                      "path": "v1alpha/{+dataStore}:removePatientFilter",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "getSiteSearchEngine": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.collections.dataStores.getSiteSearchEngine",
                      "description": "Gets the SiteSearchEngine.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine"
                    },
                    "delete": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "description": "Deletes a DataStore.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/dataStores",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.dataStores.create",
                      "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores"
                    },
                    "patch": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "description": "Updates a DataStore"
                    },
                    "completeQuery": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.completeQuery",
                      "path": "v1alpha/{+dataStore}:completeQuery",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:completeQuery",
                      "description": "Completes the specified user input with keyword suggestions."
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/dataStores",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.collections.dataStores.list",
                      "description": "Lists all the DataStores associated with the project.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores"
                    },
                    "addPatientFilter": {
                      "description": "Adds a group of patient IDs as a patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. The filter group must be a FHIR resource name of type Group, and the filter will be constructed from the direct members of the group which are Patient resources.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:addPatientFilter",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1alpha/{+dataStore}:addPatientFilter",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.dataStores.addPatientFilter"
                    }
                  },
                  "resources": {
                    "suggestionDenyListEntries": {
                      "methods": {
                        "import": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                          "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.import",
                          "path": "v1alpha/{+parent}/suggestionDenyListEntries:import",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "purge": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                          "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore."
                        }
                      }
                    },
                    "sessions": {
                      "methods": {
                        "get": {
                          "description": "Gets a Session.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.get"
                        },
                        "delete": {
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.delete"
                        },
                        "list": {
                          "description": "Lists all Sessions by their parent DataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "path": "v1alpha/{+parent}/sessions",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.list"
                        },
                        "create": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/sessions",
                          "httpMethod": "POST"
                        },
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.patch",
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}"
                        }
                      },
                      "resources": {
                        "answers": {
                          "methods": {
                            "get": {
                              "description": "Gets a Answer.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.sessions.answers.get"
                            }
                          }
                        }
                      }
                    },
                    "operations": {
                      "methods": {
                        "get": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations/{operationsId}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.list",
                          "path": "v1alpha/{+name}/operations",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                        }
                      }
                    },
                    "completionSuggestions": {
                      "methods": {
                        "import": {
                          "description": "Imports CompletionSuggestions for a DataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/completionSuggestions:import",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.import"
                        },
                        "purge": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                          "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.purge",
                          "path": "v1alpha/{+parent}/completionSuggestions:purge",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        }
                      }
                    },
                    "userEvents": {
                      "methods": {
                        "import": {
                          "path": "v1alpha/{+parent}/userEvents:import",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.import",
                          "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:import"
                        },
                        "collect": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.collect",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/userEvents:collect",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:collect",
                          "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly."
                        },
                        "purge": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.purge",
                          "path": "v1alpha/{+parent}/userEvents:purge",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:purge",
                          "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first."
                        },
                        "write": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:write",
                          "description": "Writes a single user event.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.write",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/userEvents:write",
                          "httpMethod": "POST"
                        }
                      }
                    },
                    "servingConfigs": {
                      "methods": {
                        "search": {
                          "path": "v1alpha/{+servingConfig}:search",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.search",
                          "description": "Performs a search.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search"
                        },
                        "delete": {
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.delete"
                        },
                        "create": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.create",
                          "path": "v1alpha/{+parent}/servingConfigs",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.patch",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist."
                        },
                        "searchLite": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.searchLite",
                          "path": "v1alpha/{+servingConfig}:searchLite",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "answer": {
                          "description": "Answer query method.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                          "path": "v1alpha/{+servingConfig}:answer",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.answer"
                        },
                        "streamAnswer": {
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+servingConfig}:streamAnswer",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.streamAnswer"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist."
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/servingConfigs",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.list",
                          "description": "Lists all ServingConfigs linked to this dataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs"
                        },
                        "recommend": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+servingConfig}:recommend",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.recommend",
                          "description": "Makes a recommendation, which requires a contextual user event.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend"
                        }
                      }
                    },
                    "widgetConfigs": {
                      "methods": {
                        "get": {
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.widgetConfigs.get",
                          "description": "Gets a WidgetConfig.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}"
                        },
                        "patch": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                          "description": "Update a WidgetConfig.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.widgetConfigs.patch",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        }
                      }
                    },
                    "siteSearchEngine": {
                      "methods": {
                        "batchVerifyTargetSites": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.batchVerifyTargetSites",
                          "path": "v1alpha/{+parent}:batchVerifyTargetSites",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:batchVerifyTargetSites",
                          "description": "Verify target sites' ownership and validity. This API sends all the target sites under site search engine for verification."
                        },
                        "fetchDomainVerificationStatus": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:fetchDomainVerificationStatus",
                          "description": "Returns list of target sites with its domain verification status. This method can only be called under data store with BASIC_SITE_SEARCH state at the moment.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.fetchDomainVerificationStatus",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+siteSearchEngine}:fetchDomainVerificationStatus",
                          "httpMethod": "GET"
                        },
                        "enableAdvancedSiteSearch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+siteSearchEngine}:enableAdvancedSiteSearch",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.enableAdvancedSiteSearch",
                          "description": "Upgrade from basic site search to advanced site search.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch"
                        },
                        "setUriPatternDocumentData": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:setUriPatternDocumentData",
                          "description": "Sets the URI Pattern to Document data mapping for an Advanced Site Search DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.setUriPatternDocumentData",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+siteSearchEngine}:setUriPatternDocumentData",
                          "httpMethod": "POST"
                        },
                        "recrawlUris": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.recrawlUris",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+siteSearchEngine}:recrawlUris",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                          "description": "Request on-demand recrawl for a list of URIs."
                        },
                        "getUriPatternDocumentData": {
                          "description": "Gets the URI Pattern to Document data mapping for an Advanced Site Search DataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:getUriPatternDocumentData",
                          "path": "v1alpha/{+siteSearchEngine}:getUriPatternDocumentData",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.getUriPatternDocumentData"
                        },
                        "disableAdvancedSiteSearch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.disableAdvancedSiteSearch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+siteSearchEngine}:disableAdvancedSiteSearch",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                          "description": "Downgrade from advanced site search to basic site search."
                        }
                      },
                      "resources": {
                        "targetSites": {
                          "methods": {
                            "create": {
                              "path": "v1alpha/{+parent}/targetSites",
                              "httpMethod": "POST",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.create",
                              "description": "Creates a TargetSite.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites"
                            },
                            "batchCreate": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.batchCreate",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "path": "v1alpha/{+parent}/targetSites:batchCreate",
                              "httpMethod": "POST",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                              "description": "Creates TargetSite in a batch."
                            },
                            "patch": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "description": "Updates a TargetSite.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.patch",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "path": "v1alpha/{+name}",
                              "httpMethod": "PATCH"
                            },
                            "get": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.get",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "description": "Gets a TargetSite."
                            },
                            "delete": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.delete",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "DELETE",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "description": "Deletes a TargetSite."
                            },
                            "list": {
                              "path": "v1alpha/{+parent}/targetSites",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.list",
                              "description": "Gets a list of TargetSites.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites"
                            }
                          },
                          "resources": {
                            "operations": {
                              "methods": {
                                "list": {
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                                  ],
                                  "path": "v1alpha/{+name}/operations",
                                  "httpMethod": "GET",
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.list",
                                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations"
                                },
                                "get": {
                                  "path": "v1alpha/{+name}",
                                  "httpMethod": "GET",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                                  ],
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.get",
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations/{operationsId}"
                                }
                              }
                            }
                          }
                        },
                        "sitemaps": {
                          "methods": {
                            "delete": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}",
                              "description": "Deletes a Sitemap.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.delete",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "DELETE",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            },
                            "create": {
                              "description": "Creates a Sitemap.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps",
                              "path": "v1alpha/{+parent}/sitemaps",
                              "httpMethod": "POST",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.create"
                            },
                            "fetch": {
                              "description": "Fetch Sitemaps in a DataStore.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "path": "v1alpha/{+parent}/sitemaps:fetch",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.fetch"
                            }
                          }
                        },
                        "operations": {
                          "methods": {
                            "get": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.operations.get",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/operations/{operationsId}",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                            },
                            "list": {
                              "path": "v1alpha/{+name}/operations",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.operations.list",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/operations"
                            }
                          }
                        }
                      }
                    },
                    "customModels": {
                      "methods": {
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.customModels.list",
                          "path": "v1alpha/{+dataStore}/customModels",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/customModels",
                          "description": "Gets a list of all the custom models."
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "converse": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                          "description": "Converses a conversation.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.converse",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}:converse",
                          "httpMethod": "POST"
                        },
                        "patch": {
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.patch",
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}"
                        },
                        "create": {
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/conversations",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.create"
                        },
                        "delete": {
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.delete"
                        },
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.list",
                          "path": "v1alpha/{+parent}/conversations",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "description": "Lists all Conversations by their parent DataStore."
                        },
                        "get": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "description": "Gets a Conversation.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        }
                      }
                    },
                    "branches": {
                      "methods": {
                        "list": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches",
                          "description": "Lists all Branchs under the specified parent DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.list",
                          "path": "v1alpha/{+parent}/branches",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "batchGetDocumentsMetadata": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.batchGetDocumentsMetadata",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/batchGetDocumentsMetadata",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
[...]
