{
  "baseUrl": "https://discoveryengine.googleapis.com/",
  "description": "Discovery Engine API.",
  "discoveryVersion": "v1",
  "ownerDomain": "google.com",
  "servicePath": "",
  "canonicalName": "Discovery Engine",
  "id": "discoveryengine:v1alpha",
  "fullyEncodeReservedExpansion": true,
  "resources": {
    "billingAccounts": {
      "resources": {
        "billingAccountLicenseConfigs": {
          "methods": {
            "distributeLicenseConfig": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}:distributeLicenseConfig",
              "httpMethod": "POST",
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.distributeLicenseConfig",
              "path": "v1alpha/{+billingAccountLicenseConfig}:distributeLicenseConfig",
              "description": "Distributes a LicenseConfig from billing account level to project level."
            },
            "get": {
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.get",
              "description": "Gets a BillingAccountLicenseConfig.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}/billingAccountLicenseConfigs",
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.list",
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "description": "Lists all BillingAccountLicenseConfigs for a given billing account."
            },
            "retractLicenseConfig": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}:retractLicenseConfig",
              "httpMethod": "POST",
              "description": "This method is called from the billing account side to retract the LicenseConfig from the given project back to the billing account.",
              "path": "v1alpha/{+billingAccountLicenseConfig}:retractLicenseConfig",
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.retractLicenseConfig"
            }
          }
        }
      }
    },
    "projects": {
      "methods": {
        "patch": {
          "flatPath": "v1alpha/projects/{projectsId}",
          "description": "Updates the editable settings of a Discovery Engine Project.",
          "path": "v1alpha/{+name}",
          "id": "discoveryengine.projects.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ]
        },
        "reportConsentChange": {
          "httpMethod": "POST",
          "description": "Updates service terms for this project. This method can be used to retroactively accept the latest terms. Terms available for update: * [Terms for data use](https://cloud.google.com/retail/data-use-terms)",
          "flatPath": "v1alpha/projects/{projectsId}:reportConsentChange",
          "path": "v1alpha/{+project}:reportConsentChange",
          "id": "discoveryengine.projects.reportConsentChange",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ]
        },
        "provision": {
          "id": "discoveryengine.projects.provision",
          "description": "Provisions the project resource. During the process, related systems will get prepared and initialized. Caller must read the [Terms for data use](https://cloud.google.com/retail/data-use-terms), and optionally specify in request to provide consent to that service terms.",
          "path": "v1alpha/{+name}:provision",
          "flatPath": "v1alpha/projects/{projectsId}:provision",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "v1alpha/projects/{projectsId}",
          "description": "Gets a Project. Returns NOT_FOUND when the project is not yet created.",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "path": "v1alpha/{+name}",
          "id": "discoveryengine.projects.get"
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
              "id": "discoveryengine.projects.operations.get",
              "flatPath": "v1alpha/projects/{projectsId}/operations/{operationsId}",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ]
            },
            "list": {
              "flatPath": "v1alpha/projects/{projectsId}/operations",
              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
              "path": "v1alpha/{+name}/operations",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.operations.list",
              "httpMethod": "GET"
            }
          }
        },
        "locations": {
          "methods": {
            "completeExternalIdentities": {
              "description": "This method provides suggestions for users and groups managed in an external identity provider, based on the provided prefix.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:completeExternalIdentities",
              "path": "v1alpha/{+parent}:completeExternalIdentities",
              "id": "discoveryengine.projects.locations.completeExternalIdentities",
              "httpMethod": "GET"
            },
            "getAclConfig": {
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/aclConfig",
              "id": "discoveryengine.projects.locations.getAclConfig",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "httpMethod": "GET",
              "description": "Gets the AclConfig.",
              "path": "v1alpha/{+name}"
            },
            "removeDedicatedCrawlRate": {
              "description": "Removes the dedicated crawl rate for a craw_rate_scope. If the dedicated crawl rate was set, this will disable vertex AI's crawl bot from using the dedicated crawl rate for crawling. If the dedicated crawl rate was not set, this is a no-op.",
              "path": "v1alpha/{+location}:removeDedicatedCrawlRate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.locations.removeDedicatedCrawlRate",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:removeDedicatedCrawlRate"
            },
            "getCmekConfig": {
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfig",
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "id": "discoveryengine.projects.locations.getCmekConfig",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "description": "Gets the CmekConfig."
            },
            "setUpDataConnector": {
              "path": "v1alpha/{+parent}:setUpDataConnector",
              "httpMethod": "POST",
              "id": "discoveryengine.projects.locations.setUpDataConnector",
              "description": "Creates a Collection and sets up the DataConnector for it. To stop a DataConnector after setup, use the CollectionService.DeleteCollection method.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setUpDataConnector",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ]
            },
            "queryConfigurablePricingUsageStats": {
              "httpMethod": "GET",
              "path": "v1alpha/{+project}/locations/{location}:queryConfigurablePricingUsageStats",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{location}:queryConfigurablePricingUsageStats",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.locations.queryConfigurablePricingUsageStats",
              "description": "Queries configurable pricing usage stats for a project."
            },
            "setUpDataConnectorV2": {
              "httpMethod": "POST",
              "path": "v1alpha/{+parent}:setUpDataConnectorV2",
              "id": "discoveryengine.projects.locations.setUpDataConnectorV2",
              "description": "Creates a Collection and sets up the DataConnector for it. To stop a DataConnector after setup, use the CollectionService.DeleteCollection method.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setUpDataConnectorV2",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ]
            },
            "obtainCrawlRate": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "description": "Obtains the time series data of organic or dedicated crawl rate for monitoring. When dedicated crawl rate is not set, it will return vertex AI's organic crawl rate time series. Organic crawl means Google automatically crawl the internet at its own convenience. When dedicated crawl rate is set, it will return vertex AI's dedicated crawl rate time series.",
              "path": "v1alpha/{+location}:obtainCrawlRate",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:obtainCrawlRate",
              "httpMethod": "POST",
              "id": "discoveryengine.projects.locations.obtainCrawlRate"
            },
            "updateAclConfig": {
              "description": "Default ACL configuration for use in a location of a customer's project. Updates will only reflect to new data stores. Existing data stores will still use the old value.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/aclConfig",
              "id": "discoveryengine.projects.locations.updateAclConfig",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ]
            },
            "updateCmekConfig": {
              "httpMethod": "PATCH",
              "path": "v1alpha/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfig",
              "id": "discoveryengine.projects.locations.updateCmekConfig"
            },
            "estimateDataSize": {
              "description": "Estimates the data size to be used by a customer.",
              "httpMethod": "POST",
              "path": "v1alpha/{+location}:estimateDataSize",
              "id": "discoveryengine.projects.locations.estimateDataSize",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:estimateDataSize",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ]
            },
            "setDedicatedCrawlRate": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.locations.setDedicatedCrawlRate",
              "description": "Sets the dedicated crawl rate for a crawl_rate_scope. If the dedicated crawl rate was not set, this will enable vertex AI's crawl bot to use the new dedicated crawl rate for crawling. If the dedicated crawl rate was set, vertex AI's crawl bot will try to update the rate to the new value. If the new value is too high, the crawl bot may crawl at a lower rate to avoid overloading the user's website.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setDedicatedCrawlRate",
              "path": "v1alpha/{+location}:setDedicatedCrawlRate"
            }
          },
          "resources": {
            "sampleQuerySets": {
              "methods": {
                "get": {
                  "id": "discoveryengine.projects.locations.sampleQuerySets.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "description": "Gets a SampleQuerySet.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "path": "v1alpha/{+name}"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "description": "Deletes a SampleQuerySet.",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Gets a list of SampleQuerySets.",
                  "path": "v1alpha/{+parent}/sampleQuerySets",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.list"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "PATCH",
                  "description": "Updates a SampleQuerySet.",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.patch",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "path": "v1alpha/{+name}"
                },
                "create": {
                  "path": "v1alpha/{+parent}/sampleQuerySets",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates a SampleQuerySet",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets"
                }
              },
              "resources": {
                "sampleQueries": {
                  "methods": {
                    "delete": {
                      "httpMethod": "DELETE",
                      "description": "Deletes a SampleQuery.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.delete"
                    },
                    "create": {
                      "path": "v1alpha/{+parent}/sampleQueries",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Creates a SampleQuery",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.create",
                      "httpMethod": "POST"
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.patch",
                      "description": "Updates a SampleQuery.",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}"
                    },
                    "get": {
                      "description": "Gets a SampleQuery.",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.get",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}"
                    },
                    "import": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries:import",
                      "path": "v1alpha/{+parent}/sampleQueries:import",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.import",
                      "description": "Bulk import of multiple SampleQuerys. Sample queries that already exist may be deleted. Note: It is possible for a subset of the SampleQuerys to be successfully imported.",
                      "httpMethod": "POST"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.list",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries",
                      "description": "Gets a list of SampleQuerys.",
                      "path": "v1alpha/{+parent}/sampleQueries"
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/operations/{operationsId}",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.operations.get",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            },
            "dataStores": {
              "methods": {
                "delete": {
                  "id": "discoveryengine.projects.locations.dataStores.delete",
                  "description": "Deletes a DataStore.",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "DELETE"
                },
                "deletePatientFilter": {
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:deletePatientFilter",
                  "path": "v1alpha/{+dataStore}:deletePatientFilter",
                  "id": "discoveryengine.projects.locations.dataStores.deletePatientFilter",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Deletes the entire patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter."
                },
                "addPatientFilter": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+dataStore}:addPatientFilter",
                  "id": "discoveryengine.projects.locations.dataStores.addPatientFilter",
                  "description": "Adds a group of patient IDs as a patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. The filter group must be a FHIR resource name of type Group, and the filter will be constructed from the direct members of the group which are Patient resources.",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:addPatientFilter"
                },
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "id": "discoveryengine.projects.locations.dataStores.get",
                  "description": "Gets a DataStore.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "getSiteSearchEngine": {
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.dataStores.getSiteSearchEngine",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine",
                  "description": "Gets the SiteSearchEngine.",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "updateDocumentProcessingConfig": {
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.updateDocumentProcessingConfig",
                  "path": "v1alpha/{+name}",
                  "description": "Updates the DocumentProcessingConfig. DocumentProcessingConfig is a singleon resource of DataStore. It's empty when DataStore is created. The first call to this method will set up DocumentProcessingConfig.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig"
                },
                "completeQuery": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:completeQuery",
                  "id": "discoveryengine.projects.locations.dataStores.completeQuery",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "path": "v1alpha/{+dataStore}:completeQuery",
                  "description": "Completes the specified user input with keyword suggestions."
                },
                "replacePatientFilter": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:replacePatientFilter",
                  "path": "v1alpha/{+dataStore}:replacePatientFilter",
                  "description": "Replaces the patient filter for the data store. This method is essentially a combination of DeletePatientFilters and AddPatientFilter. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the new filter w[...]",
                  "id": "discoveryengine.projects.locations.dataStores.replacePatientFilter"
                },
                "removePatientFilter": {
                  "path": "v1alpha/{+dataStore}:removePatientFilter",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "POST",
                  "description": "Removes a group of patient IDs from the patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the list of patient IDs to remove will be constructed from the direct member[...]",
                  "id": "discoveryengine.projects.locations.dataStores.removePatientFilter",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:removePatientFilter"
                },
                "patch": {
                  "description": "Updates a DataStore",
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.dataStores.patch",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}"
                },
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "path": "v1alpha/{+parent}/dataStores",
                  "id": "discoveryengine.projects.locations.dataStores.list",
                  "description": "Lists all the DataStores associated with the project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "getDocumentProcessingConfig": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                  "description": "Gets a DocumentProcessingConfig.",
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.dataStores.getDocumentProcessingConfig",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "create": {
                  "id": "discoveryengine.projects.locations.dataStores.create",
                  "path": "v1alpha/{+parent}/dataStores",
                  "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                }
              },
              "resources": {
                "completionSuggestions": {
                  "methods": {
                    "purge": {
                      "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}/completionSuggestions:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.purge"
                    },
                    "import": {
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.import",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "description": "Imports CompletionSuggestions for a DataStore.",
                      "path": "v1alpha/{+parent}/completionSuggestions:import"
                    }
                  }
                },
                "servingConfigs": {
                  "methods": {
                    "searchLite": {
                      "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, it i[...]",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.searchLite",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+servingConfig}:searchLite",
                      "httpMethod": "POST"
                    },
                    "patch": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.patch",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "httpMethod": "PATCH",
                      "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.list",
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Lists all ServingConfigs linked to this dataStore."
                    },
                    "recommend": {
                      "description": "Makes a recommendation, which requires a contextual user event.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.recommend",
                      "path": "v1alpha/{+servingConfig}:recommend",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                      "httpMethod": "POST"
                    },
                    "answer": {
                      "description": "Answer query method.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.answer",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                      "path": "v1alpha/{+servingConfig}:answer"
                    },
                    "streamAnswer": {
                      "path": "v1alpha/{+servingConfig}:streamAnswer",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.streamAnswer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer"
                    },
                    "get": {
                      "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.get",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}"
                    },
                    "search": {
                      "path": "v1alpha/{+servingConfig}:search",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Performs a search.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.search"
                    },
                    "delete": {
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.delete",
                      "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}"
                    },
                    "create": {
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.create",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs"
                    }
                  }
                },
                "completionConfig": {
                  "methods": {
                    "completeQuery": {
                      "id": "discoveryengine.projects.locations.dataStores.completionConfig.completeQuery",
                      "description": "Completes the user input with advanced keyword suggestions.",
                      "httpMethod": "POST",
                      "path": "v1alpha/{+completionConfig}:completeQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud_search.query",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionConfig:completeQuery"
                    }
                  }
                },
                "controls": {
                  "methods": {
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.create",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "path": "v1alpha/{+parent}/controls"
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.controls.list",
                      "path": "v1alpha/{+parent}/controls",
                      "description": "Lists all Controls by their parent DataStore.",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls"
                    },
                    "patch": {
                      "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "id": "discoveryengine.projects.locations.dataStores.controls.patch",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "description": "Gets a Control.",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.controls.get",
                      "httpMethod": "GET"
                    },
                    "delete": {
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.controls.delete",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned."
                    }
                  }
                },
                "siteSearchEngine": {
                  "resources": {
                    "targetSites": {
                      "methods": {
                        "list": {
                          "description": "Gets a list of TargetSites.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.list",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "path": "v1alpha/{+parent}/targetSites"
                        },
                        "create": {
                          "description": "Creates a TargetSite.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "path": "v1alpha/{+parent}/targetSites",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.create"
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.patch",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "description": "Updates a TargetSite.",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.delete",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "description": "Deletes a TargetSite.",
                          "httpMethod": "DELETE"
                        },
                        "batchCreate": {
                          "description": "Creates TargetSite in a batch.",
                          "httpMethod": "POST",
                          "path": "v1alpha/{+parent}/targetSites:batchCreate",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.batchCreate",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.get",
                          "description": "Gets a TargetSite.",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "httpMethod": "GET"
                        }
                      }
                    },
                    "sitemaps": {
                      "methods": {
                        "fetch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "path": "v1alpha/{+parent}/sitemaps:fetch",
                          "description": "Fetch Sitemaps in a DataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.fetch"
                        },
                        "delete": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.delete",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "description": "Deletes a Sitemap.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}"
                        },
                        "create": {
                          "path": "v1alpha/{+parent}/sitemaps",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.create",
                          "description": "Creates a Sitemap."
                        }
                      }
                    }
                  },
                  "methods": {
                    "recrawlUris": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                      "path": "v1alpha/{+siteSearchEngine}:recrawlUris",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.recrawlUris",
                      "description": "Request on-demand recrawl for a list of URIs.",
                      "httpMethod": "POST"
                    },
                    "disableAdvancedSiteSearch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                      "description": "Downgrade from advanced site search to basic site search.",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.disableAdvancedSiteSearch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+siteSearchEngine}:disableAdvancedSiteSearch"
                    },
                    "enableAdvancedSiteSearch": {
                      "path": "v1alpha/{+siteSearchEngine}:enableAdvancedSiteSearch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch",
                      "description": "Upgrade from basic site search to advanced site search.",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.enableAdvancedSiteSearch",
                      "httpMethod": "POST"
                    }
                  }
                },
                "models": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "get": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.get",
                          "path": "v1alpha/{+name}"
                        },
                        "list": {
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.list",
                          "path": "v1alpha/{+name}/operations",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                        }
                      }
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}/operations",
                      "id": "discoveryengine.projects.locations.dataStores.operations.list",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations"
                    },
                    "get": {
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations/{operationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.operations.get",
                      "path": "v1alpha/{+name}"
                    }
                  }
                },
                "conversations": {
                  "methods": {
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.create",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "path": "v1alpha/{+parent}/conversations",
                      "httpMethod": "POST"
                    },
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "description": "Gets a Conversation.",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.conversations.get"
                    },
                    "converse": {
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}:converse",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.converse",
                      "description": "Converses a conversation."
                    },
                    "patch": {
                      "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.conversations.patch",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "httpMethod": "PATCH"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Lists all Conversations by their parent DataStore.",
                      "path": "v1alpha/{+parent}/conversations",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.list",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations"
                    },
                    "delete": {
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.delete",
                      "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "sessions": {
                  "methods": {
                    "patch": {
                      "id": "discoveryengine.projects.locations.dataStores.sessions.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "PATCH",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "path": "v1alpha/{+name}",
                      "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned."
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.sessions.delete",
                      "httpMethod": "DELETE",
                      "path": "v1alpha/{+name}",
                      "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}"
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.sessions.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "description": "Gets a Session."
                    },
                    "list": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "path": "v1alpha/{+parent}/sessions",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.list",
                      "description": "Lists all Sessions by their parent DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "create": {
                      "path": "v1alpha/{+parent}/sessions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.sessions.create",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "httpMethod": "POST",
                      "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned."
                    }
                  },
                  "resources": {
                    "answers": {
                      "methods": {
                        "get": {
                          "httpMethod": "GET",
                          "description": "Gets a Answer.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.sessions.answers.get",
                          "path": "v1alpha/{+name}"
                        }
                      }
                    }
                  }
                },
                "userEvents": {
                  "methods": {
                    "write": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}/userEvents:write",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.write",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:write",
                      "description": "Writes a single user event."
                    },
                    "purge": {
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                      "path": "v1alpha/{+parent}/userEvents:purge",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:purge",
                      "httpMethod": "POST"
                    },
                    "import": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.import",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:import",
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}/userEvents:import"
                    },
                    "collect": {
                      "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.collect",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+parent}/userEvents:collect",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:collect"
                    }
                  }
                },
                "widgetConfigs": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.get",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                      "httpMethod": "GET",
                      "description": "Gets a WidgetConfig.",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "patch": {
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.patch",
                      "httpMethod": "PATCH",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                      "description": "Update a WidgetConfig."
                    }
                  }
                },
                "schemas": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.list",
                      "path": "v1alpha/{+parent}/schemas",
                      "description": "Gets a list of Schemas."
                    },
                    "patch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.patch",
                      "path": "v1alpha/{+name}",
                      "description": "Updates a Schema."
                    },
                    "get": {
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.get",
                      "description": "Gets a Schema.",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}"
                    },
                    "delete": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.delete",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "description": "Deletes a Schema.",
                      "path": "v1alpha/{+name}"
                    },
                    "create": {
                      "description": "Creates a Schema.",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "path": "v1alpha/{+parent}/schemas",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.create"
                    }
                  }
                },
                "suggestionDenyListEntries": {
                  "methods": {
                    "import": {
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.import",
                      "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:import",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST"
                    },
                    "purge": {
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.purge",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                      "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore."
                    }
                  }
                },
                "branches": {
                  "methods": {
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.branches.list",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+parent}/branches",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches",
                      "description": "Lists all Branchs under the specified parent DataStore."
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.branches.get",
                      "description": "Retrieves a Branch.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}"
                    },
                    "batchGetDocumentsMetadata": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                      "id": "discoveryengine.projects.locations.dataStores.branches.batchGetDocumentsMetadata",
                      "path": "v1alpha/{+parent}/batchGetDocumentsMetadata"
                    }
                  },
                  "resources": {
                    "documents": {
                      "methods": {
                        "patch": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.patch",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "description": "Updates a Document."
                        },
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.delete",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "httpMethod": "DELETE",
                          "path": "v1alpha/{+name}",
                          "description": "Deletes a Document."
                        },
                        "import": {
                          "path": "v1alpha/{+parent}/documents:import",
                          "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated.",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "list": {
                          "description": "Gets a list of Documents.",
                          "path": "v1alpha/{+parent}/documents",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.list"
                        },
                        "getProcessedDocument": {
                          "path": "v1alpha/{+name}:getProcessedDocument",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.getProcessedDocument",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}:getProcessedDocument",
                          "description": "Gets the parsed layout information for a Document.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "description": "Gets a Document.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.get",
                          "path": "v1alpha/{+name}"
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.create",
                          "description": "Creates a Document.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "path": "v1alpha/{+parent}/documents",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST"
                        },
                        "purge": {
                          "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.purge",
                          "path": "v1alpha/{+parent}/documents:purge",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      },
                      "resources": {
                        "chunks": {
                          "methods": {
                            "get": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks/{chunksId}",
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.get",
                              "path": "v1alpha/{+name}",
                              "description": "Gets a Document.",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            },
                            "list": {
                              "path": "v1alpha/{+parent}/chunks",
                              "description": "Gets a list of Chunks.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.list",
                              "httpMethod": "GET"
                            }
                          }
                        }
                      }
                    },
                    "operations": {
                      "methods": {
                        "get": {
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.get",
                          "httpMethod": "GET"
                        },
                        "list": {
                          "path": "v1alpha/{+name}/operations",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.list",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                        },
                        "cancel": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instea[...]",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.cancel",
                          "path": "v1alpha/{+name}:cancel",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    }
                  }
                }
              }
            },
            "requirements": {
              "methods": {
                "checkRequirement": {
                  "path": "v1alpha/{+location}/requirements:checkRequirement",
                  "description": "Check a particular requirement.",
                  "id": "discoveryengine.projects.locations.requirements.checkRequirement",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/requirements:checkRequirement"
                }
              }
            },
            "groundingConfigs": {
              "methods": {
                "check": {
                  "httpMethod": "POST",
                  "path": "v1alpha/{+groundingConfig}:check",
                  "id": "discoveryengine.projects.locations.groundingConfigs.check",
                  "description": "Performs a grounding check.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/groundingConfigs/{groundingConfigsId}:check"
                }
              }
            },
            "identityMappingStores": {
              "resources": {
                "operations": {
                  "methods": {
                    "list": {
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}/operations",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations/{operationsId}",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.get"
                    }
                  }
                }
              },
              "methods": {
                "purgeIdentityMappings": {
                  "httpMethod": "POST",
                  "description": "Purges specified or all Identity Mapping Entries from an Identity Mapping Store.",
                  "path": "v1alpha/{+identityMappingStore}:purgeIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.purgeIdentityMappings",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:purgeIdentityMappings"
                },
                "listIdentityMappings": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.listIdentityMappings",
                  "description": "Lists Identity Mappings in an Identity Mapping Store.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:listIdentityMappings",
                  "path": "v1alpha/{+identityMappingStore}:listIdentityMappings"
                },
                "importIdentityMappings": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+identityMappingStore}:importIdentityMappings",
                  "httpMethod": "POST",
                  "description": "Imports a list of Identity Mapping Entries to an Identity Mapping Store.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:importIdentityMappings",
                  "id": "discoveryengine.projects.locations.identityMappingStores.importIdentityMappings"
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "description": "Deletes the Identity Mapping Store.",
                  "id": "discoveryengine.projects.locations.identityMappingStores.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "DELETE"
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "description": "Gets the Identity Mapping Store.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "id": "discoveryengine.projects.locations.identityMappingStores.get"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates a new Identity Mapping Store.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "id": "discoveryengine.projects.locations.identityMappingStores.create",
                  "path": "v1alpha/{+parent}/identityMappingStores"
                },
                "list": {
                  "httpMethod": "GET",
                  "description": "Lists all Identity Mapping Stores.",
                  "id": "discoveryengine.projects.locations.identityMappingStores.list",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "path": "v1alpha/{+parent}/identityMappingStores",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                }
              }
            },
            "userEvents": {
              "methods": {
                "write": {
                  "description": "Writes a single user event.",
                  "path": "v1alpha/{+parent}/userEvents:write",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.userEvents.write",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:write",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "import": {
                  "path": "v1alpha/{+parent}/userEvents:import",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:import",
                  "id": "discoveryengine.projects.locations.userEvents.import"
                },
                "collect": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:collect",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/userEvents:collect",
                  "httpMethod": "GET",
                  "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                  "id": "discoveryengine.projects.locations.userEvents.collect"
                }
              }
            },
            "userStores": {
              "resources": {
                "userLicenses": {
                  "methods": {
                    "list": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/userLicenses",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Lists the User Licenses.",
                      "path": "v1alpha/{+parent}/userLicenses",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.userStores.userLicenses.list"
                    }
                  }
                },
                "licenseConfigsUsageStats": {
                  "methods": {
                    "list": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/licenseConfigsUsageStats",
                      "path": "v1alpha/{+parent}/licenseConfigsUsageStats",
                      "id": "discoveryengine.projects.locations.userStores.licenseConfigsUsageStats.list",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Lists all the LicenseConfigUsageStatss associated with the project."
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}/operations",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "id": "discoveryengine.projects.locations.userStores.operations.list",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/operations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "get": {
                      "path": "v1alpha/{+name}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.userStores.operations.get",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/operations/{operationsId}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                }
              },
              "methods": {
                "patch": {
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.userStores.patch",
                  "description": "Updates the User Store.",
                  "httpMethod": "PATCH"
                },
                "get": {
                  "description": "Gets the User Store.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "id": "discoveryengine.projects.locations.userStores.get",
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}"
                },
                "delete": {
                  "id": "discoveryengine.projects.locations.userStores.delete",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Deletes the User Store.",
                  "path": "v1alpha/{+name}"
                },
                "create": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.userStores.create",
                  "path": "v1alpha/{+parent}/userStores",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Creates a new User Store."
                },
                "batchUpdateUserLicenses": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}:batchUpdateUserLicenses",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Updates the User License. This method is used for batch assign/unassign licenses to users.",
                  "id": "discoveryengine.projects.locations.userStores.batchUpdateUserLicenses",
                  "path": "v1alpha/{+parent}:batchUpdateUserLicenses"
                }
              }
            },
            "podcasts": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/podcasts/{podcastsId}/operations/{operationsId}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.podcasts.operations.get"
                    }
                  }
                }
              }
            },
            "evaluations": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.evaluations.list",
                  "description": "Gets a list of Evaluations.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "path": "v1alpha/{+parent}/evaluations",
                  "httpMethod": "GET"
                },
                "create": {
                  "path": "v1alpha/{+parent}/evaluations",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.evaluations.create",
                  "description": "Creates a Evaluation. Upon creation, the evaluation will be automatically triggered and begin execution.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations"
                },
                "listResults": {
                  "id": "discoveryengine.projects.locations.evaluations.listResults",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}:listResults",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+evaluation}:listResults",
                  "httpMethod": "GET",
                  "description": "Gets a list of results for a given a Evaluation."
                },
                "get": {
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.evaluations.get",
                  "description": "Gets a Evaluation.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}/operations/{operationsId}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.evaluations.operations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                }
              }
            },
            "cmekConfigs": {
              "methods": {
                "delete": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "De-provisions a CmekConfig.",
                  "httpMethod": "DELETE",
                  "id": "discoveryengine.projects.locations.cmekConfigs.delete",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.cmekConfigs.patch",
                  "path": "v1alpha/{+name}",
                  "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "httpMethod": "PATCH"
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "id": "discoveryengine.projects.locations.cmekConfigs.get",
                  "description": "Gets the CmekConfig.",
                  "path": "v1alpha/{+name}"
                },
                "list": {
                  "id": "discoveryengine.projects.locations.cmekConfigs.list",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs",
                  "path": "v1alpha/{+parent}/cmekConfigs",
                  "description": "Lists all the CmekConfigs with the project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                }
              }
            },
            "notebooks": {
              "methods": {
                "create": {
                  "id": "discoveryengine.projects.locations.notebooks.create",
                  "path": "v1alpha/{+parent}/notebooks",
                  "description": "Creates a notebook.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks",
                  "httpMethod": "POST"
                },
                "get": {
                  "description": "Gets a notebook.",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.notebooks.get",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "batchDelete": {
                  "id": "discoveryengine.projects.locations.notebooks.batchDelete",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks:batchDelete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "POST",
                  "path": "v1alpha/{+parent}/notebooks:batchDelete",
                  "description": "Batch deletes Notebooks."
                },
                "listRecentlyViewed": {
                  "id": "discoveryengine.projects.locations.notebooks.listRecentlyViewed",
                  "path": "v1alpha/{+parent}/notebooks:listRecentlyViewed",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks:listRecentlyViewed",
                  "description": "Lists the notebooks ordered by last view time."
                },
                "share": {
                  "path": "v1alpha/{+name}:share",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}:share",
                  "description": "Shares a notebook to other accounts.",
                  "id": "discoveryengine.projects.locations.notebooks.share",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "POST"
                }
              },
              "resources": {
                "sources": {
                  "methods": {
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/sources/{sourcesId}",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.notebooks.sources.get",
                      "description": "Gets a Source.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "batchCreate": {
                      "id": "discoveryengine.projects.locations.notebooks.sources.batchCreate",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/sources:batchCreate",
                      "httpMethod": "POST",
                      "description": "Creates a list of Sources.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/sources:batchCreate"
                    },
                    "batchDelete": {
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}/sources:batchDelete",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/sources:batchDelete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes multiple sources",
                      "id": "discoveryengine.projects.locations.notebooks.sources.batchDelete"
                    }
                  }
                },
                "audioOverviews": {
                  "methods": {
                    "create": {
                      "path": "v1alpha/{+parent}/audioOverviews",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/audioOverviews",
                      "description": "Generates a new audio overview.",
                      "id": "discoveryengine.projects.locations.notebooks.audioOverviews.create",
                      "httpMethod": "POST"
                    },
                    "delete": {
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/audioOverviews/{audioOverviewsId}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes an audio overview.",
                      "id": "discoveryengine.projects.locations.notebooks.audioOverviews.delete"
                    }
                  }
                }
              }
            },
            "authorizations": {
              "methods": {
                "get": {
                  "id": "discoveryengine.projects.locations.authorizations.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}",
                  "description": "Gets an Authorization.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}"
                },
                "delete": {
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.authorizations.delete",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "description": "Deletes an Authorization.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "DELETE"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Updates an Authorization",
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.authorizations.patch"
                },
                "create": {
                  "path": "v1alpha/{+parent}/authorizations",
                  "id": "discoveryengine.projects.locations.authorizations.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations",
                  "httpMethod": "POST",
                  "description": "Creates an Authorization."
                },
                "list": {
                  "httpMethod": "GET",
                  "path": "v1alpha/{+parent}/authorizations",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations",
                  "id": "discoveryengine.projects.locations.authorizations.list",
                  "description": "Lists all Authorizations under an Engine.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                }
              }
            },
            "operations": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations",
                  "path": "v1alpha/{+name}/operations",
                  "id": "discoveryengine.projects.locations.operations.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "get": {
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "id": "discoveryengine.projects.locations.operations.get",
                  "httpMethod": "GET"
                }
              }
            },
            "collections": {
              "resources": {
                "dataStores": {
                  "methods": {
                    "trainCustomModel": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+dataStore}:trainCustomModel",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:trainCustomModel",
                      "httpMethod": "POST",
                      "description": "Trains a custom model.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.trainCustomModel"
                    },
                    "create": {
                      "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/dataStores",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores",
                      "id": "discoveryengine.projects.locations.collections.dataStores.create"
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.list",
                      "path": "v1alpha/{+parent}/dataStores",
                      "description": "Lists all the DataStores associated with the project.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores"
                    },
                    "deletePatientFilter": {
                      "httpMethod": "POST",
                      "description": "Deletes the entire patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:deletePatientFilter",
                      "path": "v1alpha/{+dataStore}:deletePatientFilter",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.dataStores.deletePatientFilter"
                    },
                    "patch": {
                      "description": "Updates a DataStore",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "PATCH",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "id": "discoveryengine.projects.locations.collections.dataStores.patch"
                    },
                    "addPatientFilter": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.addPatientFilter",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:addPatientFilter",
                      "path": "v1alpha/{+dataStore}:addPatientFilter",
                      "description": "Adds a group of patient IDs as a patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. The filter group must be a FHIR resource name of type Group, and the filter will be constructed from the direct members of the group which are Patient resources.",
                      "httpMethod": "POST"
                    },
                    "removePatientFilter": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:removePatientFilter",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "description": "Removes a group of patient IDs from the patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the list of patient IDs to remove will be constructed from the direct me[...]",
                      "id": "discoveryengine.projects.locations.collections.dataStores.removePatientFilter",
                      "path": "v1alpha/{+dataStore}:removePatientFilter"
                    },
                    "delete": {
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes a DataStore.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.delete"
                    },
                    "getDocumentProcessingConfig": {
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.collections.dataStores.getDocumentProcessingConfig",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets a DocumentProcessingConfig."
                    },
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.collections.dataStores.get",
                      "path": "v1alpha/{+name}",
                      "description": "Gets a DataStore."
                    },
                    "updateDocumentProcessingConfig": {
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Updates the DocumentProcessingConfig. DocumentProcessingConfig is a singleon resource of DataStore. It's empty when DataStore is created. The first call to this method will set up DocumentProcessingConfig.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                      "id": "discoveryengine.projects.locations.collections.dataStores.updateDocumentProcessingConfig"
                    },
                    "replacePatientFilter": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:replacePatientFilter",
                      "path": "v1alpha/{+dataStore}:replacePatientFilter",
                      "description": "Replaces the patient filter for the data store. This method is essentially a combination of DeletePatientFilters and AddPatientFilter. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the new filt[...]",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.dataStores.replacePatientFilter"
                    },
                    "getSiteSearchEngine": {
                      "description": "Gets the SiteSearchEngine.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.dataStores.getSiteSearchEngine",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}"
                    },
                    "completeQuery": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.completeQuery",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+dataStore}:completeQuery",
                      "description": "Completes the specified user input with keyword suggestions.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:completeQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  },
                  "resources": {
                    "models": {
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.list",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}/operations",
                              "httpMethod": "GET",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations"
                            },
                            "get": {
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.get",
                              "path": "v1alpha/{+name}",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}"
                            }
                          }
                        }
                      }
                    },
                    "completionSuggestions": {
                      "methods": {
                        "import": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.import",
                          "description": "Imports CompletionSuggestions for a DataStore.",
                          "path": "v1alpha/{+parent}/completionSuggestions:import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "purge": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.purge",
                          "path": "v1alpha/{+parent}/completionSuggestions:purge",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                          "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "schemas": {
                      "methods": {
                        "get": {
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.get",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "description": "Gets a Schema.",
                          "path": "v1alpha/{+name}"
                        },
                        "list": {
                          "path": "v1alpha/{+parent}/schemas",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a list of Schemas.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.list",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "httpMethod": "GET"
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "description": "Creates a Schema.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.create",
                          "path": "v1alpha/{+parent}/schemas",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas"
                        },
                        "patch": {
                          "path": "v1alpha/{+name}",
                          "description": "Updates a Schema.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.patch"
                        },
                        "delete": {
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes a Schema.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.delete",
                          "httpMethod": "DELETE"
                        }
                      },
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.list",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations",
                              "path": "v1alpha/{+name}/operations",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET"
                            },
                            "get": {
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.get",
                              "path": "v1alpha/{+name}",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations/{operationsId}",
                              "httpMethod": "GET"
                            }
                          }
                        }
                      }
                    },
                    "servingConfigs": {
                      "methods": {
                        "streamAnswer": {
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.streamAnswer",
                          "path": "v1alpha/{+servingConfig}:streamAnswer",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "patch": {
                          "path": "v1alpha/{+name}",
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.patch",
                          "httpMethod": "PATCH"
                        },
                        "create": {
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.create",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "path": "v1alpha/{+parent}/servingConfigs",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "httpMethod": "GET",
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.get"
                        },
                        "searchLite": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+servingConfig}:searchLite",
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.searchLite"
                        },
                        "search": {
                          "description": "Performs a search.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.search",
                          "path": "v1alpha/{+servingConfig}:search"
                        },
                        "recommend": {
                          "description": "Makes a recommendation, which requires a contextual user event.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.recommend",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                          "httpMethod": "POST",
                          "path": "v1alpha/{+servingConfig}:recommend"
                        },
                        "delete": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist."
                        },
                        "list": {
                          "description": "Lists all ServingConfigs linked to this dataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.list",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/servingConfigs"
                        },
                        "answer": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Answer query method.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.answer",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                          "path": "v1alpha/{+servingConfig}:answer"
                        }
                      }
                    },
                    "sessions": {
                      "methods": {
                        "create": {
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "path": "v1alpha/{+parent}/sessions",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.create"
                        },
                        "list": {
                          "httpMethod": "GET",
                          "description": "Lists all Sessions by their parent DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.list",
                          "path": "v1alpha/{+parent}/sessions",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions"
                        },
                        "get": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a Session.",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET"
                        },
                        "delete": {
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.delete",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned."
                        },
                        "patch": {
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.patch",
                          "httpMethod": "PATCH"
                        }
                      },
                      "resources": {
                        "answers": {
                          "methods": {
                            "get": {
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Gets a Answer.",
                              "path": "v1alpha/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.sessions.answers.get",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}"
                            }
                          }
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "description": "Lists all Conversations by their parent DataStore.",
                          "httpMethod": "GET",
                          "path": "v1alpha/{+parent}/conversations"
                        },
                        "get": {
                          "description": "Gets a Conversation.",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "patch": {
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.patch",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "create": {
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                          "path": "v1alpha/{+parent}/conversations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.create",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "httpMethod": "POST"
                        },
                        "delete": {
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.delete",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "DELETE",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}"
                        },
                        "converse": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}:converse",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.converse",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                          "description": "Converses a conversation."
                        }
                      }
                    },
                    "customModels": {
                      "methods": {
                        "list": {
                          "description": "Gets a list of all the custom models.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/customModels",
                          "id": "discoveryengine.projects.locations.collections.dataStores.customModels.list",
                          "path": "v1alpha/{+dataStore}/customModels",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "completionConfig": {
                      "methods": {
                        "completeQuery": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                          "description": "Completes the user input with advanced keyword suggestions.",
                          "path": "v1alpha/{+completionConfig}:completeQuery",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud_search.query",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionConfig.completeQuery"
                        }
                      }
                    },
                    "branches": {
                      "methods": {
                        "list": {
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/branches",
                          "description": "Lists all Branchs under the specified parent DataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches",
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.list"
                        },
                        "batchGetDocumentsMetadata": {
                          "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.batchGetDocumentsMetadata",
                          "path": "v1alpha/{+parent}/batchGetDocumentsMetadata",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                          "httpMethod": "GET"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.get",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "description": "Retrieves a Branch.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}"
                        }
                      },
                      "resources": {
                        "documents": {
                          "resources": {
                            "chunks": {
                              "methods": {
                                "list": {
                                  "description": "Gets a list of Chunks.",
                                  "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.chunks.list",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks",
                                  "httpMethod": "GET",
                                  "path": "v1alpha/{+parent}/chunks",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ]
                                },
                                "get": {
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "path": "v1alpha/{+name}",
                                  "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.chunks.get",
                                  "description": "Gets a Document.",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks/{chunksId}",
                                  "httpMethod": "GET"
                                }
                              }
                            }
                          },
                          "methods": {
                            "delete": {
                              "description": "Deletes a Document.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.delete",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "httpMethod": "DELETE"
                            },
                            "get": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.get",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}",
                              "httpMethod": "GET",
                              "description": "Gets a Document."
                            },
                            "getProcessedDocument": {
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.getProcessedDocument",
                              "path": "v1alpha/{+name}:getProcessedDocument",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}:getProcessedDocument",
                              "description": "Gets the parsed layout information for a Document."
                            },
                            "purge": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.purge",
                              "path": "v1alpha/{+parent}/documents:purge",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                              "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "POST"
                            },
                            "list": {
                              "httpMethod": "GET",
                              "description": "Gets a list of Documents.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.list",
                              "path": "v1alpha/{+parent}/documents",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents"
                            },
                            "patch": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "description": "Updates a Document.",
                              "path": "v1alpha/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.patch",
                              "httpMethod": "PATCH"
                            },
                            "create": {
                              "httpMethod": "POST",
                              "description": "Creates a Document.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "path": "v1alpha/{+parent}/documents",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.create"
                            },
                            "import": {
                              "path": "v1alpha/{+parent}/documents:import",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.import",
                              "httpMethod": "POST",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import"
                            }
                          }
                        },
                        "operations": {
                          "methods": {
                            "get": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.get",
                              "httpMethod": "GET"
                            },
                            "list": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.list",
                              "path": "v1alpha/{+name}/operations",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            },
                            "cancel": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                              "path": "v1alpha/{+name}:cancel",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; in[...]",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.cancel",
                              "httpMethod": "POST"
                            }
                          }
                        }
                      }
                    },
                    "widgetConfigs": {
                      "methods": {
                        "get": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a WidgetConfig.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.widgetConfigs.get",
                          "httpMethod": "GET",
                          "path": "v1alpha/{+name}"
                        },
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.widgetConfigs.patch",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                          "description": "Update a WidgetConfig."
                        }
                      }
                    },
                    "controls": {
                      "methods": {
                        "patch": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.patch",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH"
                        },
                        "create": {
                          "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                          "path": "v1alpha/{+parent}/controls",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.create"
                        },
                        "delete": {
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "httpMethod": "DELETE",
                          "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.delete"
                        },
                        "get": {
                          "description": "Gets a Control.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET"
                        },
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Lists all Controls by their parent DataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "path": "v1alpha/{+parent}/controls",
                          "httpMethod": "GET"
                        }
                      }
                    },
                    "suggestionDenyListEntries": {
                      "methods": {
                        "import": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.import",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                          "path": "v1alpha/{+parent}/suggestionDenyListEntries:import",
                          "description": "Imports all SuggestionDenyListEntry for a DataStore."
                        },
                        "purge": {
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.purge",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                          "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                          "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "userEvents": {
                      "methods": {
                        "collect": {
[...]
