{
  "protocol": "rest",
  "ownerDomain": "google.com",
  "servicePath": "",
  "discoveryVersion": "v1",
  "canonicalName": "Discovery Engine",
  "revision": "20260322",
  "baseUrl": "https://discoveryengine.googleapis.com/",
  "name": "discoveryengine",
  "mtlsRootUrl": "https://discoveryengine.mtls.googleapis.com/",
  "basePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite": {
          "description": "View your Agentspace chat history, including uploaded files and generated reports and visualizations, and interact with the Agentspace assistant on your behalf."
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/discoveryengine.readwrite": {
          "description": "View, edit, create, and delete all your data associated with any Discovery Engine API product, such as Agentspace, Vertex AI Search, or NotebookLM Enterprise, including both end user data and administration or configuration data."
        }
      }
    }
  },
  "version": "v1alpha",
  "description": "Discovery Engine API.",
  "ownerName": "Google",
  "title": "Discovery Engine API",
  "version_module": true,
  "resources": {
    "projects": {
      "methods": {
        "reportConsentChange": {
          "flatPath": "v1alpha/projects/{projectsId}:reportConsentChange",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "id": "discoveryengine.projects.reportConsentChange",
          "path": "v1alpha/{+project}:reportConsentChange",
          "description": "Updates service terms for this project. This method can be used to retroactively accept the latest terms. Terms available for update: * [Terms for data use](https://cloud.google.com/retail/data-use-terms)"
        },
        "provision": {
          "path": "v1alpha/{+name}:provision",
          "description": "Provisions the project resource. During the process, related systems will get prepared and initialized. Caller must read the [Terms for data use](https://cloud.google.com/retail/data-use-terms), and optionally specify in request to provide consent to that service terms.",
          "httpMethod": "POST",
          "id": "discoveryengine.projects.provision",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "flatPath": "v1alpha/projects/{projectsId}:provision"
        },
        "get": {
          "flatPath": "v1alpha/projects/{projectsId}",
          "path": "v1alpha/{+name}",
          "id": "discoveryengine.projects.get",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "httpMethod": "GET",
          "description": "Gets a Project. Returns NOT_FOUND when the project is not yet created."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "flatPath": "v1alpha/projects/{projectsId}",
          "httpMethod": "PATCH",
          "id": "discoveryengine.projects.patch",
          "description": "Updates the editable settings of a Discovery Engine Project.",
          "path": "v1alpha/{+name}"
        }
      },
      "resources": {
        "locations": {
          "methods": {
            "estimateDataSize": {
              "description": "Estimates the data size to be used by a customer.",
              "id": "discoveryengine.projects.locations.estimateDataSize",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "httpMethod": "POST",
              "path": "v1alpha/{+location}:estimateDataSize",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:estimateDataSize"
            },
            "getAclConfig": {
              "httpMethod": "GET",
              "description": "Gets the AclConfig.",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/aclConfig",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "path": "v1alpha/{+name}",
              "id": "discoveryengine.projects.locations.getAclConfig"
            },
            "obtainCrawlRate": {
              "path": "v1alpha/{+location}:obtainCrawlRate",
              "id": "discoveryengine.projects.locations.obtainCrawlRate",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "description": "Obtains the time series data of organic or dedicated crawl rate for monitoring. When dedicated crawl rate is not set, it will return vertex AI's organic crawl rate time series. Organic crawl means Google automatically crawl the internet at its own convenience. When dedicated crawl rate is set, it will return vertex AI's dedicated crawl rate time series.",
              "httpMethod": "POST",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:obtainCrawlRate"
            },
            "completeExternalIdentities": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.locations.completeExternalIdentities",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:completeExternalIdentities",
              "description": "This method provides suggestions for users and groups managed in an external identity provider, based on the provided prefix.",
              "httpMethod": "GET",
              "path": "v1alpha/{+parent}:completeExternalIdentities"
            },
            "removeDedicatedCrawlRate": {
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:removeDedicatedCrawlRate",
              "id": "discoveryengine.projects.locations.removeDedicatedCrawlRate",
              "path": "v1alpha/{+location}:removeDedicatedCrawlRate",
              "description": "Removes the dedicated crawl rate for a craw_rate_scope. If the dedicated crawl rate was set, this will disable vertex AI's crawl bot from using the dedicated crawl rate for crawling. If the dedicated crawl rate was not set, this is a no-op.",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ]
            },
            "setUpDataConnector": {
              "id": "discoveryengine.projects.locations.setUpDataConnector",
              "path": "v1alpha/{+parent}:setUpDataConnector",
              "description": "Creates a Collection and sets up the DataConnector for it. To stop a DataConnector after setup, use the CollectionService.DeleteCollection method.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "httpMethod": "POST",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setUpDataConnector"
            },
            "updateCmekConfig": {
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfig",
              "path": "v1alpha/{+name}",
              "httpMethod": "PATCH",
              "id": "discoveryengine.projects.locations.updateCmekConfig",
              "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ]
            },
            "updateAclConfig": {
              "httpMethod": "PATCH",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/aclConfig",
              "path": "v1alpha/{+name}",
              "description": "Default ACL configuration for use in a location of a customer's project. Updates will only reflect to new data stores. Existing data stores will still use the old value.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.locations.updateAclConfig"
            },
            "queryConfigurablePricingUsageStats": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "path": "v1alpha/{+project}/locations/{location}:queryConfigurablePricingUsageStats",
              "id": "discoveryengine.projects.locations.queryConfigurablePricingUsageStats",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{location}:queryConfigurablePricingUsageStats",
              "description": "Queries configurable pricing usage stats for a project.",
              "httpMethod": "GET"
            },
            "setDedicatedCrawlRate": {
              "httpMethod": "POST",
              "id": "discoveryengine.projects.locations.setDedicatedCrawlRate",
              "path": "v1alpha/{+location}:setDedicatedCrawlRate",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setDedicatedCrawlRate",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "description": "Sets the dedicated crawl rate for a crawl_rate_scope. If the dedicated crawl rate was not set, this will enable vertex AI's crawl bot to use the new dedicated crawl rate for crawling. If the dedicated crawl rate was set, vertex AI's crawl bot will try to update the rate to the new value. If the new value is too high, the crawl bot may crawl at a lower rate to avoid overloading the user's website."
            },
            "setUpDataConnectorV2": {
              "description": "Creates a Collection and sets up the DataConnector for it. To stop a DataConnector after setup, use the CollectionService.DeleteCollection method.",
              "id": "discoveryengine.projects.locations.setUpDataConnectorV2",
              "path": "v1alpha/{+parent}:setUpDataConnectorV2",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}:setUpDataConnectorV2"
            },
            "getCmekConfig": {
              "httpMethod": "GET",
              "path": "v1alpha/{+name}",
              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfig",
              "description": "Gets the CmekConfig.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.locations.getCmekConfig"
            }
          },
          "resources": {
            "rankingConfigs": {
              "methods": {
                "rank": {
                  "path": "v1alpha/{+rankingConfig}:rank",
                  "description": "Ranks a list of text records based on the given input query.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/rankingConfigs/{rankingConfigsId}:rank",
                  "id": "discoveryengine.projects.locations.rankingConfigs.rank"
                }
              }
            },
            "userEvents": {
              "methods": {
                "write": {
                  "httpMethod": "POST",
                  "description": "Writes a single user event.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/userEvents:write",
                  "id": "discoveryengine.projects.locations.userEvents.write",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:write"
                },
                "collect": {
                  "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                  "id": "discoveryengine.projects.locations.userEvents.collect",
                  "path": "v1alpha/{+parent}/userEvents:collect",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:collect",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "import": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                  "path": "v1alpha/{+parent}/userEvents:import",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:import",
                  "id": "discoveryengine.projects.locations.userEvents.import",
                  "httpMethod": "POST"
                }
              }
            },
            "groundingConfigs": {
              "methods": {
                "check": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/groundingConfigs/{groundingConfigsId}:check",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "POST",
                  "path": "v1alpha/{+groundingConfig}:check",
                  "description": "Performs a grounding check.",
                  "id": "discoveryengine.projects.locations.groundingConfigs.check"
                }
              }
            },
            "notebooks": {
              "methods": {
                "share": {
                  "path": "v1alpha/{+name}:share",
                  "id": "discoveryengine.projects.locations.notebooks.share",
                  "description": "Shares a notebook to other accounts.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}:share",
                  "httpMethod": "POST"
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "v1alpha/{+parent}/notebooks",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.notebooks.create",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks",
                  "description": "Creates a notebook."
                },
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}",
                  "description": "Gets a notebook.",
                  "id": "discoveryengine.projects.locations.notebooks.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}"
                },
                "listRecentlyViewed": {
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.notebooks.listRecentlyViewed",
                  "description": "Lists the notebooks ordered by last view time.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks:listRecentlyViewed",
                  "path": "v1alpha/{+parent}/notebooks:listRecentlyViewed"
                },
                "batchDelete": {
                  "description": "Batch deletes Notebooks.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.notebooks.batchDelete",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks:batchDelete",
                  "path": "v1alpha/{+parent}/notebooks:batchDelete",
                  "httpMethod": "POST"
                }
              },
              "resources": {
                "audioOverviews": {
                  "methods": {
                    "create": {
                      "id": "discoveryengine.projects.locations.notebooks.audioOverviews.create",
                      "description": "Generates a new audio overview.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/audioOverviews",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/audioOverviews",
                      "httpMethod": "POST"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.notebooks.audioOverviews.delete",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/audioOverviews/{audioOverviewsId}",
                      "description": "Deletes an audio overview."
                    }
                  }
                },
                "sources": {
                  "methods": {
                    "get": {
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/sources/{sourcesId}",
                      "id": "discoveryengine.projects.locations.notebooks.sources.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets a Source.",
                      "httpMethod": "GET"
                    },
                    "batchDelete": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/sources:batchDelete",
                      "path": "v1alpha/{+parent}/sources:batchDelete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes multiple sources",
                      "id": "discoveryengine.projects.locations.notebooks.sources.batchDelete",
                      "httpMethod": "POST"
                    },
                    "batchCreate": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/sources:batchCreate",
                      "path": "v1alpha/{+parent}/sources:batchCreate",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "description": "Creates a list of Sources.",
                      "id": "discoveryengine.projects.locations.notebooks.sources.batchCreate"
                    }
                  }
                }
              }
            },
            "cmekConfigs": {
              "methods": {
                "list": {
                  "id": "discoveryengine.projects.locations.cmekConfigs.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Lists all the CmekConfigs with the project.",
                  "path": "v1alpha/{+parent}/cmekConfigs",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs"
                },
                "delete": {
                  "id": "discoveryengine.projects.locations.cmekConfigs.delete",
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "description": "De-provisions a CmekConfig.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}"
                },
                "get": {
                  "description": "Gets the CmekConfig.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.cmekConfigs.get"
                },
                "patch": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location.",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.cmekConfigs.patch"
                }
              }
            },
            "identityMappingStores": {
              "methods": {
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.identityMappingStores.get",
                  "description": "Gets the Identity Mapping Store.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "create": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "id": "discoveryengine.projects.locations.identityMappingStores.create",
                  "description": "Creates a new Identity Mapping Store.",
                  "path": "v1alpha/{+parent}/identityMappingStores",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "list": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/identityMappingStores",
                  "description": "Lists all Identity Mapping Stores.",
                  "id": "discoveryengine.projects.locations.identityMappingStores.list"
                },
                "purgeIdentityMappings": {
                  "path": "v1alpha/{+identityMappingStore}:purgeIdentityMappings",
                  "id": "discoveryengine.projects.locations.identityMappingStores.purgeIdentityMappings",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:purgeIdentityMappings",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Purges specified or all Identity Mapping Entries from an Identity Mapping Store."
                },
                "importIdentityMappings": {
                  "path": "v1alpha/{+identityMappingStore}:importIdentityMappings",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:importIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.importIdentityMappings",
                  "httpMethod": "POST",
                  "description": "Imports a list of Identity Mapping Entries to an Identity Mapping Store."
                },
                "delete": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "description": "Deletes the Identity Mapping Store.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.delete"
                },
                "listIdentityMappings": {
                  "id": "discoveryengine.projects.locations.identityMappingStores.listIdentityMappings",
                  "description": "Lists Identity Mappings in an Identity Mapping Store.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:listIdentityMappings",
                  "path": "v1alpha/{+identityMappingStore}:listIdentityMappings",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations/{operationsId}",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "list": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations",
                      "httpMethod": "GET",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "path": "v1alpha/{+name}/operations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.list"
                    }
                  }
                }
              }
            },
            "evaluations": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}/operations/{operationsId}",
                      "id": "discoveryengine.projects.locations.evaluations.operations.get"
                    }
                  }
                }
              },
              "methods": {
                "create": {
                  "id": "discoveryengine.projects.locations.evaluations.create",
                  "description": "Creates a Evaluation. Upon creation, the evaluation will be automatically triggered and begin execution.",
                  "path": "v1alpha/{+parent}/evaluations",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}",
                  "httpMethod": "GET",
                  "description": "Gets a Evaluation.",
                  "id": "discoveryengine.projects.locations.evaluations.get",
                  "path": "v1alpha/{+name}"
                },
                "list": {
                  "path": "v1alpha/{+parent}/evaluations",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.evaluations.list",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "description": "Gets a list of Evaluations."
                },
                "listResults": {
                  "description": "Gets a list of results for a given a Evaluation.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "path": "v1alpha/{+evaluation}:listResults",
                  "id": "discoveryengine.projects.locations.evaluations.listResults",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}:listResults"
                }
              }
            },
            "dataStores": {
              "methods": {
                "deletePatientFilter": {
                  "httpMethod": "POST",
                  "description": "Deletes the entire patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+dataStore}:deletePatientFilter",
                  "id": "discoveryengine.projects.locations.dataStores.deletePatientFilter",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:deletePatientFilter"
                },
                "delete": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "description": "Deletes a DataStore.",
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "DELETE",
                  "id": "discoveryengine.projects.locations.dataStores.delete"
                },
                "patch": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "id": "discoveryengine.projects.locations.dataStores.patch",
                  "path": "v1alpha/{+name}",
                  "description": "Updates a DataStore",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "updateDocumentProcessingConfig": {
                  "description": "Updates the DocumentProcessingConfig. DocumentProcessingConfig is a singleon resource of DataStore. It's empty when DataStore is created. The first call to this method will set up DocumentProcessingConfig.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.updateDocumentProcessingConfig",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                  "path": "v1alpha/{+name}"
                },
                "getSiteSearchEngine": {
                  "id": "discoveryengine.projects.locations.dataStores.getSiteSearchEngine",
                  "description": "Gets the SiteSearchEngine.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "path": "v1alpha/{+name}"
                },
                "addPatientFilter": {
                  "id": "discoveryengine.projects.locations.dataStores.addPatientFilter",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:addPatientFilter",
                  "path": "v1alpha/{+dataStore}:addPatientFilter",
                  "description": "Adds a group of patient IDs as a patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. The filter group must be a FHIR resource name of type Group, and the filter will be constructed from the direct members of the group which are Patient resources."
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.dataStores.get",
                  "httpMethod": "GET",
                  "description": "Gets a DataStore.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}"
                },
                "completeQuery": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:completeQuery",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+dataStore}:completeQuery",
                  "id": "discoveryengine.projects.locations.dataStores.completeQuery",
                  "httpMethod": "GET",
                  "description": "Completes the specified user input with keyword suggestions."
                },
                "list": {
                  "description": "Lists all the DataStores associated with the project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.dataStores.list",
                  "path": "v1alpha/{+parent}/dataStores",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores"
                },
                "removePatientFilter": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:removePatientFilter",
                  "path": "v1alpha/{+dataStore}:removePatientFilter",
                  "id": "discoveryengine.projects.locations.dataStores.removePatientFilter",
                  "description": "Removes a group of patient IDs from the patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the list of patient IDs to remove will be constructed from the direct member[...]",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "create": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.dataStores.create",
                  "path": "v1alpha/{+parent}/dataStores"
                },
                "getDocumentProcessingConfig": {
                  "path": "v1alpha/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                  "id": "discoveryengine.projects.locations.dataStores.getDocumentProcessingConfig",
                  "httpMethod": "GET",
                  "description": "Gets a DocumentProcessingConfig."
                },
                "replacePatientFilter": {
                  "httpMethod": "POST",
                  "description": "Replaces the patient filter for the data store. This method is essentially a combination of DeletePatientFilters and AddPatientFilter. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the new filter w[...]",
                  "path": "v1alpha/{+dataStore}:replacePatientFilter",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:replacePatientFilter",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.replacePatientFilter"
                }
              },
              "resources": {
                "sessions": {
                  "methods": {
                    "list": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "httpMethod": "GET",
                      "description": "Lists all Sessions by their parent DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.sessions.list",
                      "path": "v1alpha/{+parent}/sessions"
                    },
                    "create": {
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}/sessions",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.create"
                    },
                    "patch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.patch"
                    },
                    "delete": {
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "DELETE",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.delete",
                      "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned."
                    },
                    "get": {
                      "path": "v1alpha/{+name}",
                      "description": "Gets a Session.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.get"
                    }
                  },
                  "resources": {
                    "answers": {
                      "methods": {
                        "get": {
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.sessions.answers.get",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "description": "Gets a Answer."
                        }
                      }
                    }
                  }
                },
                "suggestionDenyListEntries": {
                  "methods": {
                    "purge": {
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge",
                      "httpMethod": "POST"
                    },
                    "import": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                      "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.import",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:import"
                    }
                  }
                },
                "controls": {
                  "methods": {
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.controls.delete",
                      "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}"
                    },
                    "get": {
                      "description": "Gets a Control.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.get",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}"
                    },
                    "patch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "path": "v1alpha/{+name}",
                      "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "PATCH"
                    },
                    "create": {
                      "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.controls.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/controls",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls"
                    },
                    "list": {
                      "path": "v1alpha/{+parent}/controls",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "description": "Lists all Controls by their parent DataStore.",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.controls.list"
                    }
                  }
                },
                "completionConfig": {
                  "methods": {
                    "completeQuery": {
                      "description": "Completes the user input with advanced keyword suggestions.",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.completionConfig.completeQuery",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                      "path": "v1alpha/{+completionConfig}:completeQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud_search.query",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "servingConfigs": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "description": "Lists all ServingConfigs linked to this dataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "recommend": {
                      "description": "Makes a recommendation, which requires a contextual user event.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+servingConfig}:recommend",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.recommend",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend"
                    },
                    "streamAnswer": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.streamAnswer",
                      "httpMethod": "POST",
                      "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                      "path": "v1alpha/{+servingConfig}:streamAnswer"
                    },
                    "answer": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+servingConfig}:answer",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.answer",
                      "httpMethod": "POST",
                      "description": "Answer query method."
                    },
                    "patch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.patch",
                      "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "httpMethod": "PATCH",
                      "path": "v1alpha/{+name}"
                    },
                    "get": {
                      "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.get",
                      "httpMethod": "GET"
                    },
                    "create": {
                      "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.create",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.delete",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "httpMethod": "DELETE"
                    },
                    "searchLite": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.searchLite",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                      "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, it i[...]",
                      "httpMethod": "POST",
                      "path": "v1alpha/{+servingConfig}:searchLite",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "search": {
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.search",
                      "path": "v1alpha/{+servingConfig}:search",
                      "description": "Performs a search."
                    }
                  }
                },
                "conversations": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "description": "Gets a Conversation."
                    },
                    "list": {
                      "description": "Lists all Conversations by their parent DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "path": "v1alpha/{+parent}/conversations",
                      "httpMethod": "GET"
                    },
                    "converse": {
                      "id": "discoveryengine.projects.locations.dataStores.conversations.converse",
                      "path": "v1alpha/{+name}:converse",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Converses a conversation.",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse"
                    },
                    "create": {
                      "path": "v1alpha/{+parent}/conversations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.conversations.create",
                      "httpMethod": "POST",
                      "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                      "httpMethod": "DELETE",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.delete",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}"
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+name}",
                      "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.patch"
                    }
                  }
                },
                "userEvents": {
                  "methods": {
                    "purge": {
                      "path": "v1alpha/{+parent}/userEvents:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.purge",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:purge",
                      "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first."
                    },
                    "collect": {
                      "path": "v1alpha/{+parent}/userEvents:collect",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:collect",
                      "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.collect",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "import": {
                      "path": "v1alpha/{+parent}/userEvents:import",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:import",
                      "httpMethod": "POST"
                    },
                    "write": {
                      "path": "v1alpha/{+parent}/userEvents:write",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:write",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Writes a single user event.",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.write"
                    }
                  }
                },
                "widgetConfigs": {
                  "methods": {
                    "patch": {
                      "description": "Update a WidgetConfig.",
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.patch",
                      "path": "v1alpha/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                      "httpMethod": "PATCH"
                    },
                    "get": {
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                      "description": "Gets a WidgetConfig.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.get",
                      "httpMethod": "GET"
                    }
                  }
                },
                "completionSuggestions": {
                  "methods": {
                    "import": {
                      "description": "Imports CompletionSuggestions for a DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.import",
                      "path": "v1alpha/{+parent}/completionSuggestions:import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                      "httpMethod": "POST"
                    },
                    "purge": {
                      "httpMethod": "POST",
                      "path": "v1alpha/{+parent}/completionSuggestions:purge",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Permanently deletes all CompletionSuggestions for a DataStore."
                    }
                  }
                },
                "branches": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "httpMethod": "GET",
                          "path": "v1alpha/{+name}/operations",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.list"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "path": "v1alpha/{+name}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.get"
                        },
                        "cancel": {
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instea[...]",
                          "path": "v1alpha/{+name}:cancel",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.cancel"
                        }
                      }
                    },
                    "documents": {
                      "resources": {
                        "chunks": {
                          "methods": {
                            "list": {
                              "path": "v1alpha/{+parent}/chunks",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.list",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Gets a list of Chunks."
                            },
                            "get": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks/{chunksId}",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}",
                              "description": "Gets a Document.",
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.get"
                            }
                          }
                        }
                      },
                      "methods": {
                        "purge": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.purge",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/documents:purge",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                          "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false."
                        },
                        "delete": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes a Document.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.delete",
                          "path": "v1alpha/{+name}"
                        },
                        "patch": {
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Updates a Document.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.patch",
                          "httpMethod": "PATCH",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}"
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "description": "Gets a list of Documents.",
                          "path": "v1alpha/{+parent}/documents",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.list"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.get",
                          "description": "Gets a Document.",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}"
                        },
                        "import": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                          "path": "v1alpha/{+parent}/documents:import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.import",
                          "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated."
                        },
                        "getProcessedDocument": {
                          "description": "Gets the parsed layout information for a Document.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}:getProcessedDocument",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "path": "v1alpha/{+name}:getProcessedDocument",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.getProcessedDocument"
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "description": "Creates a Document.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.create",
                          "path": "v1alpha/{+parent}/documents"
                        }
                      }
                    }
                  },
                  "methods": {
                    "list": {
                      "description": "Lists all Branchs under the specified parent DataStore.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.branches.list",
                      "path": "v1alpha/{+parent}/branches"
                    },
                    "get": {
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}",
                      "httpMethod": "GET",
                      "description": "Retrieves a Branch.",
                      "id": "discoveryengine.projects.locations.dataStores.branches.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "batchGetDocumentsMetadata": {
                      "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+parent}/batchGetDocumentsMetadata",
                      "id": "discoveryengine.projects.locations.dataStores.branches.batchGetDocumentsMetadata",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "schemas": {
                  "methods": {
                    "delete": {
                      "description": "Deletes a Schema.",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.delete",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "patch": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.patch",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "description": "Updates a Schema.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.list",
                      "httpMethod": "GET",
                      "description": "Gets a list of Schemas.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/schemas"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/schemas",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "description": "Creates a Schema.",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.create",
                      "httpMethod": "POST"
                    },
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.schemas.get",
                      "description": "Gets a Schema.",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}"
                    }
                  }
                },
                "siteSearchEngine": {
                  "methods": {
                    "disableAdvancedSiteSearch": {
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.disableAdvancedSiteSearch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+siteSearchEngine}:disableAdvancedSiteSearch",
                      "description": "Downgrade from advanced site search to basic site search.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                      "httpMethod": "POST"
                    },
                    "recrawlUris": {
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.recrawlUris",
                      "path": "v1alpha/{+siteSearchEngine}:recrawlUris",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Request on-demand recrawl for a list of URIs.",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris"
                    },
                    "enableAdvancedSiteSearch": {
                      "httpMethod": "POST",
                      "path": "v1alpha/{+siteSearchEngine}:enableAdvancedSiteSearch",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.enableAdvancedSiteSearch",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch",
                      "description": "Upgrade from basic site search to advanced site search.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  },
                  "resources": {
                    "sitemaps": {
                      "methods": {
                        "fetch": {
                          "path": "v1alpha/{+parent}/sitemaps:fetch",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.fetch",
                          "description": "Fetch Sitemaps in a DataStore.",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "delete": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.delete",
                          "httpMethod": "DELETE",
                          "description": "Deletes a Sitemap.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}"
                        },
                        "create": {
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Creates a Sitemap.",
                          "path": "v1alpha/{+parent}/sitemaps",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps"
                        }
                      }
                    },
                    "targetSites": {
                      "methods": {
                        "delete": {
                          "description": "Deletes a TargetSite.",
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.delete",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}"
                        },
                        "list": {
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.list",
                          "description": "Gets a list of TargetSites.",
                          "path": "v1alpha/{+parent}/targetSites",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites"
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.patch",
                          "description": "Updates a TargetSite.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.get",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a TargetSite.",
                          "path": "v1alpha/{+name}"
                        },
                        "batchCreate": {
                          "path": "v1alpha/{+parent}/targetSites:batchCreate",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.batchCreate",
                          "description": "Creates TargetSite in a batch."
                        },
                        "create": {
                          "path": "v1alpha/{+parent}/targetSites",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "description": "Creates a TargetSite."
                        }
                      }
                    }
                  }
                },
                "models": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.get"
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations",
                          "path": "v1alpha/{+name}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.list",
                          "httpMethod": "GET"
                        }
                      }
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.operations.list",
                      "path": "v1alpha/{+name}/operations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations",
                      "httpMethod": "GET",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.operations.get",
                      "httpMethod": "GET",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations/{operationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                    }
                  }
                }
              }
            },
            "requirements": {
              "methods": {
                "checkRequirement": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/requirements:checkRequirement",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.requirements.checkRequirement",
                  "httpMethod": "POST",
                  "path": "v1alpha/{+location}/requirements:checkRequirement",
                  "description": "Check a particular requirement."
                }
              }
            },
            "sampleQuerySets": {
              "resources": {
                "sampleQueries": {
                  "methods": {
                    "delete": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes a SampleQuery.",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.delete"
                    },
                    "list": {
                      "path": "v1alpha/{+parent}/sampleQueries",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.list",
                      "description": "Gets a list of SampleQuerys.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries"
                    },
                    "import": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1alpha/{+parent}/sampleQueries:import",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries:import",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.import",
                      "description": "Bulk import of multiple SampleQuerys. Sample queries that already exist may be deleted. Note: It is possible for a subset of the SampleQuerys to be successfully imported.",
                      "httpMethod": "POST"
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "description": "Gets a SampleQuery.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "create": {
                      "path": "v1alpha/{+parent}/sampleQueries",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.create",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries",
                      "httpMethod": "POST",
                      "description": "Creates a SampleQuery"
                    },
                    "patch": {
                      "description": "Updates a SampleQuery.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.patch"
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.sampleQuerySets.operations.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/operations/{operationsId}",
                      "path": "v1alpha/{+name}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "httpMethod": "GET"
                    }
                  }
                }
              },
              "methods": {
                "list": {
                  "id": "discoveryengine.projects.locations.sampleQuerySets.list",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "path": "v1alpha/{+parent}/sampleQuerySets",
                  "description": "Gets a list of SampleQuerySets."
                },
                "create": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.sampleQuerySets.create",
                  "path": "v1alpha/{+parent}/sampleQuerySets",
                  "httpMethod": "POST",
                  "description": "Creates a SampleQuerySet"
                },
                "delete": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "httpMethod": "DELETE",
                  "path": "v1alpha/{+name}",
                  "description": "Deletes a SampleQuerySet.",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "httpMethod": "PATCH",
                  "path": "v1alpha/{+name}",
                  "description": "Updates a SampleQuerySet.",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.patch"
                },
                "get": {
                  "description": "Gets a SampleQuerySet.",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.get"
                }
              }
            },
            "licenseConfigs": {
              "methods": {
                "get": {
                  "description": "Gets a LicenseConfig.",
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.licenseConfigs.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}",
                  "httpMethod": "PATCH",
                  "path": "v1alpha/{+name}",
                  "id": "discoveryengine.projects.locations.licenseConfigs.patch",
                  "description": "Updates the LicenseConfig"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1alpha/{+parent}/licenseConfigs",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs",
                  "httpMethod": "POST",
                  "description": "Creates a LicenseConfig This method should only be used for creating NotebookLm licenses or Gemini Enterprise free trial licenses.",
                  "id": "discoveryengine.projects.locations.licenseConfigs.create"
                }
              }
            },
            "collections": {
              "resources": {
                "engines": {
                  "methods": {
                    "resume": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.engines.resume",
                      "path": "v1alpha/{+name}:resume",
                      "httpMethod": "POST",
                      "description": "Resumes the training of an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:resume"
                    },
                    "patch": {
                      "description": "Updates an Engine",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "PATCH",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.collections.engines.patch"
                    },
                    "delete": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes an Engine.",
                      "path": "v1alpha/{+name}",
                      "id": "discoveryengine.projects.locations.collections.engines.delete"
                    },
                    "setIamPolicy": {
                      "id": "discoveryengine.projects.locations.collections.engines.setIamPolicy",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Sets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. **Important:** When setting a policy directly on an Engine resource, the only recommended roles in the bindings are: `roles/discoveryengine.user` and `roles/discoveryengine.agentspaceUser`. Attempting to grant any other role will result in a warning in logging.",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:setIamPolicy",
                      "path": "v1alpha/{+resource}:setIamPolicy"
                    },
                    "getIamPolicy": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:getIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.engines.getIamPolicy",
                      "httpMethod": "GET",
                      "description": "Gets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. An empty policy is returned if the resource exists but does not have a policy set on it.",
                      "path": "v1alpha/{+resource}:getIamPolicy"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.collections.engines.list",
                      "path": "v1alpha/{+parent}/engines",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines",
                      "description": "Lists all the Engines associated with the project.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "tune": {
                      "description": "Tunes an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.engines.tune",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:tune",
                      "path": "v1alpha/{+name}:tune",
                      "httpMethod": "POST"
                    },
                    "pause": {
                      "path": "v1alpha/{+name}:pause",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:pause",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Pauses the training of an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION.",
                      "id": "discoveryengine.projects.locations.collections.engines.pause"
                    },
                    "getWorkspaceSettings": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:getWorkspaceSettings",
                      "httpMethod": "GET",
                      "description": "Get Workspace settings for the end user.",
                      "path": "v1alpha/{+name}:getWorkspaceSettings",
                      "id": "discoveryengine.projects.locations.collections.engines.getWorkspaceSettings"
                    },
                    "create": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.engines.create",
                      "path": "v1alpha/{+parent}/engines",
                      "httpMethod": "POST",
                      "description": "Creates an Engine."
                    },
                    "get": {
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "description": "Gets an Engine.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.engines.get",
                      "path": "v1alpha/{+name}"
                    }
                  },
                  "resources": {
                    "operations": {
                      "methods": {
                        "get": {
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.engines.operations.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/operations/{operationsId}"
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}/operations",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "id": "discoveryengine.projects.locations.collections.engines.operations.list"
                        }
                      }
                    },
                    "widgetConfigs": {
                      "methods": {
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a WidgetConfig.",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.engines.widgetConfigs.get",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/widgetConfigs/{widgetConfigsId}"
                        },
                        "patch": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/widgetConfigs/{widgetConfigsId}",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "id": "discoveryengine.projects.locations.collections.engines.widgetConfigs.patch",
                          "description": "Update a WidgetConfig."
                        }
                      }
                    },
                    "completionConfig": {
                      "methods": {
                        "removeSuggestion": {
                          "description": "Removes the search history suggestion in an engine for a user. This will remove the suggestion from being returned in the AdvancedCompleteQueryResponse.recent_search_suggestions for this user. If the user searches the same suggestion again, the new history will override and suggest this suggestion again.",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/completionConfig:removeSuggestion",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.completionConfig.removeSuggestion",
                          "path": "v1alpha/{+completionConfig}:removeSuggestion"
                        },
                        "completeQuery": {
                          "httpMethod": "POST",
                          "path": "v1alpha/{+completionConfig}:completeQuery",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud_search.query",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Completes the user input with advanced keyword suggestions.",
                          "id": "discoveryengine.projects.locations.collections.engines.completionConfig.completeQuery",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/completionConfig:completeQuery"
                        }
                      }
                    },
                    "analytics": {
                      "methods": {
                        "getConfig": {
                          "id": "discoveryengine.projects.locations.collections.engines.analytics.getConfig",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/analytics/config",
                          "description": "Gets the AnalyticsConfig.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}"
                        },
                        "exportMetrics": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/analytics:exportMetrics",
                          "path": "v1alpha/{+analytics}:exportMetrics",
                          "id": "discoveryengine.projects.locations.collections.engines.analytics.exportMetrics",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Exports metrics."
                        },
                        "updateConfig": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.analytics.updateConfig",
                          "httpMethod": "PATCH",
                          "description": "Updates the AnalyticsConfig for analytics.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/analytics/config",
                          "path": "v1alpha/{+name}"
                        }
                      }
                    },
                    "servingConfigs": {
                      "methods": {
                        "search": {
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.search",
                          "path": "v1alpha/{+servingConfig}:search",
                          "description": "Performs a search.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:search"
                        },
                        "searchLite": {
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:searchLite",
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.searchLite",
                          "path": "v1alpha/{+servingConfig}:searchLite",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.delete",
                          "httpMethod": "DELETE",
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}"
                        },
                        "get": {
                          "path": "v1alpha/{+name}",
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.get",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}"
                        },
                        "patch": {
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}"
                        },
                        "recommend": {
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:recommend",
                          "description": "Makes a recommendation, which requires a contextual user event.",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.recommend",
                          "path": "v1alpha/{+servingConfig}:recommend"
                        },
                        "streamAnswer": {
                          "path": "v1alpha/{+servingConfig}:streamAnswer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:streamAnswer",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.streamAnswer"
                        },
                        "answer": {
                          "httpMethod": "POST",
                          "description": "Answer query method.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:answer",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.answer",
                          "path": "v1alpha/{+servingConfig}:answer"
                        },
                        "create": {
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                          "path": "v1alpha/{+parent}/servingConfigs",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.create"
                        },
                        "list": {
                          "httpMethod": "GET",
                          "description": "Lists all ServingConfigs linked to this dataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs",
                          "path": "v1alpha/{+parent}/servingConfigs",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.list"
                        }
                      }
                    },
                    "controls": {
                      "methods": {
                        "create": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls",
                          "id": "discoveryengine.projects.locations.collections.engines.controls.create",
                          "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                          "path": "v1alpha/{+parent}/controls",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "delete": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls/{controlsId}",
                          "httpMethod": "DELETE",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.controls.delete",
                          "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned."
                        },
                        "patch": {
                          "httpMethod": "PATCH",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls/{controlsId}",
                          "id": "discoveryengine.projects.locations.collections.engines.controls.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned."
                        },
                        "get": {
                          "httpMethod": "GET",
                          "description": "Gets a Control.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls/{controlsId}",
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.collections.engines.controls.get"
                        },
                        "list": {
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/controls",
                          "description": "Lists all Controls by their parent DataStore.",
                          "id": "discoveryengine.projects.locations.collections.engines.controls.list",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls"
                        }
                      }
                    },
                    "assistants": {
                      "methods": {
                        "create": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.create",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/assistants",
                          "description": "Creates an Assistant."
                        },
                        "delete": {
                          "httpMethod": "DELETE",
                          "description": "Deletes an Assistant.",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.delete"
                        },
                        "list": {
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants",
                          "path": "v1alpha/{+parent}/assistants",
                          "description": "Lists all Assistants under an Engine.",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "streamAssist": {
                          "path": "v1alpha/{+name}:streamAssist",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}:streamAssist",
                          "description": "Assists the user with a query in a streaming fashion.",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.streamAssist"
                        },
                        "patch": {
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.patch",
                          "path": "v1alpha/{+name}",
                          "description": "Updates an Assistant"
                        },
                        "get": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.get",
                          "path": "v1alpha/{+name}",
                          "description": "Gets an Assistant."
                        }
                      },
                      "resources": {
                        "agents": {
                          "methods": {
                            "delete": {
                              "path": "v1alpha/{+name}",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}",
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.delete",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "DELETE",
                              "description": "Deletes an Agent."
                            },
                            "patch": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}",
                              "path": "v1alpha/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Updates an Agent",
                              "httpMethod": "PATCH",
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.patch"
                            },
                            "get": {
                              "httpMethod": "GET",
                              "description": "Gets an Agent.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}",
                              "path": "v1alpha/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.get"
                            },
                            "create": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents",
                              "description": "Creates an Agent.",
                              "path": "v1alpha/{+parent}/agents",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.create",
                              "httpMethod": "POST"
                            },
                            "list": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents",
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.list",
                              "description": "Lists all Agents under an Assistant which were created by the caller.",
                              "path": "v1alpha/{+parent}/agents",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            }
                          },
                          "resources": {
                            "files": {
                              "methods": {
                                "import": {
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "httpMethod": "POST",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/files:import",
                                  "description": "Imports a file to an Agent. Currently only No-Code agents are supported.",
                                  "path": "v1alpha/{+parent}/files:import",
                                  "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.files.import"
                                }
                              }
                            },
                            "operations": {
                              "methods": {
                                "get": {
                                  "httpMethod": "GET",
                                  "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.operations.get",
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/operations/{operationsId}",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "path": "v1alpha/{+name}"
                                }
                              }
                            }
                          }
                        },
                        "cannedQueries": {
                          "methods": {
                            "patch": {
                              "path": "v1alpha/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/cannedQueries/{cannedQueriesId}",
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.cannedQueries.patch",
                              "httpMethod": "PATCH",
                              "description": "Updates a CannedQuery."
                            },
                            "create": {
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.cannedQueries.create",
                              "description": "Creates a CannedQuery.",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/cannedQueries",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "POST",
                              "path": "v1alpha/{+parent}/cannedQueries"
                            },
                            "delete": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Deletes a CannedQuery.",
                              "path": "v1alpha/{+name}",
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.cannedQueries.delete",
                              "httpMethod": "DELETE",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/cannedQueries/{cannedQueriesId}"
                            },
                            "list": {
                              "description": "Lists all CannedQuerys under an Assistant.",
                              "path": "v1alpha/{+parent}/cannedQueries",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/cannedQueries",
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.cannedQueries.list",
                              "httpMethod": "GET"
                            },
                            "get": {
                              "description": "Gets a CannedQuery.",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.cannedQueries.get",
                              "path": "v1alpha/{+name}",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/cannedQueries/{cannedQueriesId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            }
                          }
                        }
                      }
                    },
                    "sessions": {
                      "methods": {
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.get",
                          "httpMethod": "GET",
                          "description": "Gets a Session.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}"
                        },
                        "list": {
                          "path": "v1alpha/{+parent}/sessions",
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.list",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions",
                          "description": "Lists all Sessions by their parent DataStore.",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.create",
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                          "path": "v1alpha/{+parent}/sessions",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions",
                          "httpMethod": "POST"
                        },
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}",
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.patch",
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH"
                        },
                        "delete": {
                          "path": "v1alpha/{+name}",
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.delete",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}",
                          "httpMethod": "DELETE"
                        }
                      },
                      "resources": {
                        "files": {
                          "methods": {
                            "list": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}/files",
                              "path": "v1alpha/{+parent}/files",
                              "id": "discoveryengine.projects.locations.collections.engines.sessions.files.list",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Lists metadata for all files in the current session."
                            }
                          }
                        },
                        "operations": {
                          "methods": {
                            "get": {
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.engines.sessions.operations.get",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}/operations/{operationsId}",
                              "path": "v1alpha/{+name}"
                            }
                          }
                        },
                        "alphaEvolveExperiments": {
                          "resources": {
                            "operations": {
                              "methods": {
                                "get": {
                                  "id": "discoveryengine.projects.locations.collections.engines.sessions.alphaEvolveExperiments.operations.get",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}/alphaEvolveExperiments/{alphaEvolveExperimentsId}/operations/{operationsId}",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                                  "path": "v1alpha/{+name}",
                                  "httpMethod": "GET"
                                }
                              }
                            }
                          }
                        },
                        "answers": {
                          "methods": {
                            "get": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}/answers/{answersId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Gets a Answer.",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.engines.sessions.answers.get"
                            }
                          }
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "patch": {
                          "httpMethod": "PATCH",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}",
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "create": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.create",
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                          "path": "v1alpha/{+parent}/conversations"
                        },
                        "delete": {
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.delete",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE"
                        },
                        "converse": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.converse",
                          "path": "v1alpha/{+name}:converse",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}:converse",
                          "description": "Converses a conversation.",
                          "httpMethod": "POST"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.get",
                          "httpMethod": "GET",
                          "path": "v1alpha/{+name}",
                          "description": "Gets a Conversation.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}"
                        },
                        "list": {
                          "description": "Lists all Conversations by their parent DataStore.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.list",
                          "path": "v1alpha/{+parent}/conversations"
                        }
                      }
                    }
                  }
                },
                "dataStores": {
                  "resources": {
                    "schemas": {
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "httpMethod": "GET",
                              "path": "v1alpha/{+name}/operations",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.list",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations"
                            },
                            "get": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "httpMethod": "GET",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations/{operationsId}"
                            }
                          }
                        }
                      },
                      "methods": {
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "description": "Updates a Schema.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.patch",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}"
                        },
                        "delete": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.delete",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+name}",
                          "description": "Deletes a Schema."
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.create",
                          "description": "Creates a Schema.",
                          "path": "v1alpha/{+parent}/schemas",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.get",
                          "description": "Gets a Schema.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "list": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/schemas",
                          "description": "Gets a list of Schemas.",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.list"
                        }
                      }
                    },
                    "suggestionDenyListEntries": {
                      "methods": {
                        "import": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.import",
                          "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/suggestionDenyListEntries:import",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import"
                        },
                        "purge": {
                          "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge",
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                          "httpMethod": "POST",
                          "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore."
                        }
                      }
                    },
                    "models": {
                      "resources": {
                        "operations": {
                          "methods": {
                            "get": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "path": "v1alpha/{+name}",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                              "httpMethod": "GET"
                            },
                            "list": {
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1alpha/{+name}/operations",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.list",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations"
                            }
                          }
                        }
                      }
                    },
                    "controls": {
                      "methods": {
                        "patch": {
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.patch",
                          "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH"
                        },
                        "get": {
                          "description": "Gets a Control.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.get"
                        },
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.list",
                          "description": "Lists all Controls by their parent DataStore.",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/controls",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls"
                        },
                        "create": {
                          "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.create",
                          "path": "v1alpha/{+parent}/controls"
                        },
                        "delete": {
                          "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "DELETE",
                          "path": "v1alpha/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.delete",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}"
                        }
                      }
                    },
                    "sessions": {
                      "methods": {
                        "delete": {
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "path": "v1alpha/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.delete"
                        },
                        "patch": {
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a Session.",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.get",
                          "httpMethod": "GET",
                          "path": "v1alpha/{+name}"
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1alpha/{+parent}/sessions",
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.create",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions"
                        },
                        "list": {
                          "httpMethod": "GET",
                          "path": "v1alpha/{+parent}/sessions",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.list",
                          "description": "Lists all Sessions by their parent DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
[...]
