{
  "baseUrl": "https://discoveryengine.googleapis.com/",
  "ownerDomain": "google.com",
  "discoveryVersion": "v1",
  "resources": {
    "projects": {
      "methods": {
        "provision": {
          "path": "v1beta/{+name}:provision",
          "description": "Provisions the project resource. During the process, related systems will get prepared and initialized. Caller must read the [Terms for data use](https://cloud.google.com/retail/data-use-terms), and optionally specify in request to provide consent to that service terms.",
          "flatPath": "v1beta/projects/{projectsId}:provision",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite",
            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
          ],
          "httpMethod": "POST",
          "id": "discoveryengine.projects.provision"
        }
      },
      "resources": {
        "locations": {
          "resources": {
            "operations": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.operations.list",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/operations",
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                  "path": "v1beta/{+name}/operations"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "httpMethod": "GET",
                  "path": "v1beta/{+name}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "id": "discoveryengine.projects.locations.operations.get",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}"
                }
              }
            },
            "collections": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.collections.operations.get",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/operations/{operationsId}",
                      "path": "v1beta/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "list": {
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/operations",
                      "id": "discoveryengine.projects.locations.collections.operations.list",
                      "httpMethod": "GET",
                      "path": "v1beta/{+name}/operations"
                    }
                  }
                },
                "dataConnector": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}/operations",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.list"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.get",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations/{operationsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        }
                      }
                    }
                  }
                },
                "dataStores": {
                  "resources": {
                    "completionConfig": {
                      "methods": {
                        "completeQuery": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud_search.query",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Completes the user input with advanced keyword suggestions.",
                          "path": "v1beta/{+completionConfig}:completeQuery",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionConfig.completeQuery",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionConfig:completeQuery"
                        }
                      }
                    },
                    "suggestionDenyListEntries": {
                      "methods": {
                        "purge": {
                          "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                          "path": "v1beta/{+parent}/suggestionDenyListEntries:purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.purge"
                        },
                        "import": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                          "path": "v1beta/{+parent}/suggestionDenyListEntries:import"
                        }
                      }
                    },
                    "models": {
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "httpMethod": "GET",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations",
                              "path": "v1beta/{+name}/operations",
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.list"
                            },
                            "get": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "path": "v1beta/{+name}",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.get",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "httpMethod": "GET"
                            }
                          }
                        }
                      }
                    },
                    "branches": {
                      "methods": {
                        "batchGetDocumentsMetadata": {
                          "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/batchGetDocumentsMetadata",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.batchGetDocumentsMetadata",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata"
                        }
                      },
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.list",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "path": "v1beta/{+name}/operations"
                            },
                            "get": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "path": "v1beta/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.get"
                            },
                            "cancel": {
                              "path": "v1beta/{+name}:cancel",
                              "httpMethod": "POST",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.cancel",
                              "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; in[...]",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel"
                            }
                          }
                        },
                        "documents": {
                          "methods": {
                            "purge": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "path": "v1beta/{+parent}/documents:purge",
                              "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                              "httpMethod": "POST",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.purge",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge"
                            },
                            "list": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets a list of Documents.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.list",
                              "path": "v1beta/{+parent}/documents"
                            },
                            "delete": {
                              "path": "v1beta/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.delete",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "description": "Deletes a Document.",
                              "httpMethod": "DELETE",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            },
                            "patch": {
                              "description": "Updates a Document.",
                              "path": "v1beta/{+name}",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.patch",
                              "httpMethod": "PATCH"
                            },
                            "import": {
                              "httpMethod": "POST",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.import",
                              "path": "v1beta/{+parent}/documents:import",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                              "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated."
                            },
                            "get": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "path": "v1beta/{+name}",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "description": "Gets a Document.",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.get"
                            },
                            "create": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.create",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "description": "Creates a Document.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "path": "v1beta/{+parent}/documents",
                              "httpMethod": "POST"
                            }
                          }
                        }
                      }
                    },
                    "completionSuggestions": {
                      "methods": {
                        "purge": {
                          "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+parent}/completionSuggestions:purge"
                        },
                        "import": {
                          "path": "v1beta/{+parent}/completionSuggestions:import",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.import",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Imports CompletionSuggestions for a DataStore."
                        }
                      }
                    },
                    "operations": {
                      "methods": {
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.get",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations/{operationsId}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                        },
                        "list": {
                          "httpMethod": "GET",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "path": "v1beta/{+name}/operations",
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.list",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.create",
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}/conversations",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.get",
                          "description": "Gets a Conversation.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}"
                        },
                        "delete": {
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "path": "v1beta/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.delete"
                        },
                        "list": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "description": "Lists all Conversations by their parent DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/conversations",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.list"
                        },
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.patch"
                        },
                        "converse": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+name}:converse",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                          "httpMethod": "POST",
                          "description": "Converses a conversation.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.converse"
                        }
                      }
                    },
                    "servingConfigs": {
                      "methods": {
                        "streamAnswer": {
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.streamAnswer",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+servingConfig}:streamAnswer"
                        },
                        "searchLite": {
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "path": "v1beta/{+servingConfig}:searchLite",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.searchLite"
                        },
                        "list": {
                          "path": "v1beta/{+parent}/servingConfigs",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "description": "Lists all ServingConfigs linked to this dataStore.",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "answer": {
                          "httpMethod": "POST",
                          "description": "Answer query method.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+servingConfig}:answer",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.answer",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer"
                        },
                        "search": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.search",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+servingConfig}:search",
                          "description": "Performs a search."
                        },
                        "recommend": {
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                          "path": "v1beta/{+servingConfig}:recommend",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.recommend",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Makes a recommendation, which requires a contextual user event."
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.patch",
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist."
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.create",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+parent}/servingConfigs",
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned."
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.get",
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.delete",
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "httpMethod": "DELETE"
                        }
                      }
                    },
                    "sessions": {
                      "methods": {
                        "get": {
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "description": "Gets a Session.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.get",
                          "httpMethod": "GET"
                        },
                        "patch": {
                          "path": "v1beta/{+name}",
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.patch",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}"
                        },
                        "delete": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.delete",
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "DELETE",
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned."
                        },
                        "create": {
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.create",
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}/sessions"
                        },
                        "list": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "path": "v1beta/{+parent}/sessions",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists all Sessions by their parent DataStore.",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.list"
                        }
                      },
                      "resources": {
                        "answers": {
                          "methods": {
                            "get": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.sessions.answers.get",
                              "description": "Gets a Answer.",
                              "httpMethod": "GET",
                              "path": "v1beta/{+name}",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            }
                          }
                        }
                      }
                    },
                    "siteSearchEngine": {
                      "resources": {
                        "sitemaps": {
                          "methods": {
                            "create": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.create",
                              "httpMethod": "POST",
                              "path": "v1beta/{+parent}/sitemaps",
                              "description": "Creates a Sitemap.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            },
                            "fetch": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.fetch",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                              "description": "Fetch Sitemaps in a DataStore.",
                              "httpMethod": "GET",
                              "path": "v1beta/{+parent}/sitemaps:fetch",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            },
                            "delete": {
                              "httpMethod": "DELETE",
                              "description": "Deletes a Sitemap.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}",
                              "path": "v1beta/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.delete"
                            }
                          }
                        },
                        "targetSites": {
                          "resources": {
                            "operations": {
                              "methods": {
                                "list": {
                                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations",
                                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                                  "httpMethod": "GET",
                                  "path": "v1beta/{+name}/operations",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                                  ],
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.list"
                                },
                                "get": {
                                  "httpMethod": "GET",
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                                  "path": "v1beta/{+name}",
                                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations/{operationsId}",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                                  ],
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.get"
                                }
                              }
                            }
                          },
                          "methods": {
                            "list": {
                              "httpMethod": "GET",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.list",
                              "path": "v1beta/{+parent}/targetSites",
                              "description": "Gets a list of TargetSites.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            },
                            "create": {
                              "path": "v1beta/{+parent}/targetSites",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.create",
                              "httpMethod": "POST",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                              "description": "Creates a TargetSite."
                            },
                            "delete": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.delete",
                              "httpMethod": "DELETE",
                              "path": "v1beta/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Deletes a TargetSite.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}"
                            },
                            "get": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets a TargetSite.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "path": "v1beta/{+name}",
                              "httpMethod": "GET"
                            },
                            "patch": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "httpMethod": "PATCH",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.patch",
                              "path": "v1beta/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Updates a TargetSite."
                            },
                            "batchCreate": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                              "httpMethod": "POST",
                              "description": "Creates TargetSite in a batch.",
                              "path": "v1beta/{+parent}/targetSites:batchCreate",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.batchCreate",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            }
                          }
                        },
                        "operations": {
                          "methods": {
                            "list": {
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "path": "v1beta/{+name}/operations",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/operations",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.operations.list",
                              "httpMethod": "GET"
                            },
                            "get": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/operations/{operationsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.operations.get",
                              "httpMethod": "GET",
                              "path": "v1beta/{+name}"
                            }
                          }
                        }
                      },
                      "methods": {
                        "fetchDomainVerificationStatus": {
                          "path": "v1beta/{+siteSearchEngine}:fetchDomainVerificationStatus",
                          "description": "Returns list of target sites with its domain verification status. This method can only be called under data store with BASIC_SITE_SEARCH state at the moment.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.fetchDomainVerificationStatus",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:fetchDomainVerificationStatus"
                        },
                        "batchVerifyTargetSites": {
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:batchVerifyTargetSites",
                          "description": "Verify target sites' ownership and validity. This API sends all the target sites under site search engine for verification.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+parent}:batchVerifyTargetSites",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.batchVerifyTargetSites"
                        },
                        "recrawlUris": {
                          "description": "Request on-demand recrawl for a list of URIs.",
                          "path": "v1beta/{+siteSearchEngine}:recrawlUris",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.recrawlUris",
                          "httpMethod": "POST"
                        },
                        "disableAdvancedSiteSearch": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                          "path": "v1beta/{+siteSearchEngine}:disableAdvancedSiteSearch",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.disableAdvancedSiteSearch",
                          "description": "Downgrade from advanced site search to basic site search.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "POST"
                        },
                        "enableAdvancedSiteSearch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.enableAdvancedSiteSearch",
                          "description": "Upgrade from basic site search to advanced site search.",
                          "path": "v1beta/{+siteSearchEngine}:enableAdvancedSiteSearch",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch"
                        }
                      }
                    },
                    "customModels": {
                      "methods": {
                        "list": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/customModels",
                          "description": "Gets a list of all the custom models.",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+dataStore}/customModels",
                          "id": "discoveryengine.projects.locations.collections.dataStores.customModels.list"
                        }
                      }
                    },
                    "controls": {
                      "methods": {
                        "get": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a Control.",
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.get"
                        },
                        "list": {
                          "description": "Lists all Controls by their parent DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "path": "v1beta/{+parent}/controls"
                        },
                        "delete": {
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "httpMethod": "DELETE",
                          "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.delete"
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+parent}/controls",
                          "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.create"
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.patch",
                          "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                          "httpMethod": "PATCH",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+name}"
                        }
                      }
                    },
                    "schemas": {
                      "methods": {
                        "delete": {
                          "description": "Deletes a Schema.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "path": "v1beta/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "DELETE"
                        },
                        "list": {
                          "path": "v1beta/{+parent}/schemas",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a list of Schemas.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "httpMethod": "GET"
                        },
                        "create": {
                          "description": "Creates a Schema.",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.create",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+parent}/schemas"
                        },
                        "get": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "description": "Gets a Schema.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET"
                        },
                        "patch": {
                          "path": "v1beta/{+name}",
                          "httpMethod": "PATCH",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.patch",
                          "description": "Updates a Schema."
                        }
                      },
                      "resources": {
                        "operations": {
                          "methods": {
                            "get": {
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "path": "v1beta/{+name}",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations/{operationsId}"
                            },
                            "list": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "path": "v1beta/{+name}/operations",
                              "httpMethod": "GET",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.list",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations"
                            }
                          }
                        }
                      }
                    },
                    "userEvents": {
                      "methods": {
                        "purge": {
                          "path": "v1beta/{+parent}/userEvents:purge",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:purge",
                          "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first."
                        },
                        "import": {
                          "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:import",
                          "path": "v1beta/{+parent}/userEvents:import",
                          "httpMethod": "POST"
                        },
                        "write": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Writes a single user event.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:write",
                          "path": "v1beta/{+parent}/userEvents:write",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.write"
                        },
                        "collect": {
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/userEvents:collect",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:collect",
                          "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.collect"
                        }
                      }
                    }
                  },
                  "methods": {
                    "getSiteSearchEngine": {
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.collections.dataStores.getSiteSearchEngine",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine",
                      "description": "Gets the SiteSearchEngine.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "delete": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "description": "Deletes a DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.collections.dataStores.delete",
                      "path": "v1beta/{+name}"
                    },
                    "patch": {
                      "description": "Updates a DataStore",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.collections.dataStores.patch",
                      "path": "v1beta/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "create": {
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores",
                      "id": "discoveryengine.projects.locations.collections.dataStores.create",
                      "path": "v1beta/{+parent}/dataStores"
                    },
                    "completeQuery": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.completeQuery",
                      "httpMethod": "GET",
                      "path": "v1beta/{+dataStore}:completeQuery",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:completeQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Completes the specified user input with keyword suggestions."
                    },
                    "trainCustomModel": {
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:trainCustomModel",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.dataStores.trainCustomModel",
                      "path": "v1beta/{+dataStore}:trainCustomModel",
                      "description": "Trains a custom model."
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+parent}/dataStores",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores",
                      "httpMethod": "GET",
                      "description": "Lists all the DataStores associated with the project.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.list"
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.get",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+name}",
                      "httpMethod": "GET",
                      "description": "Gets a DataStore."
                    }
                  }
                },
                "engines": {
                  "methods": {
                    "pause": {
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:pause",
                      "description": "Pauses the training of an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION.",
                      "id": "discoveryengine.projects.locations.collections.engines.pause",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+name}:pause"
                    },
                    "delete": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.engines.delete",
                      "description": "Deletes an Engine.",
                      "path": "v1beta/{+name}"
                    },
                    "setIamPolicy": {
                      "path": "v1beta/{+resource}:setIamPolicy",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Sets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. **Important:** When setting a policy directly on an Engine resource, the only recommended roles in the bindings are: `roles/discoveryengine.user` and `roles/discoveryengine.agentspaceUser`. Attempting to grant any other role will result in a warning in logging.",
                      "id": "discoveryengine.projects.locations.collections.engines.setIamPolicy",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:setIamPolicy"
                    },
                    "create": {
                      "path": "v1beta/{+parent}/engines",
                      "id": "discoveryengine.projects.locations.collections.engines.create",
                      "description": "Creates an Engine.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "POST"
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "id": "discoveryengine.projects.locations.collections.engines.patch",
                      "description": "Updates an Engine",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "getIamPolicy": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:getIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.engines.getIamPolicy",
                      "httpMethod": "GET",
                      "path": "v1beta/{+resource}:getIamPolicy",
                      "description": "Gets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. An empty policy is returned if the resource exists but does not have a policy set on it."
                    },
                    "resume": {
                      "httpMethod": "POST",
                      "path": "v1beta/{+name}:resume",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:resume",
                      "id": "discoveryengine.projects.locations.collections.engines.resume",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Resumes the training of an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION."
                    },
                    "list": {
                      "description": "Lists all the Engines associated with the project.",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines",
                      "id": "discoveryengine.projects.locations.collections.engines.list",
                      "path": "v1beta/{+parent}/engines"
                    },
                    "get": {
                      "httpMethod": "GET",
                      "description": "Gets an Engine.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "path": "v1beta/{+name}",
                      "id": "discoveryengine.projects.locations.collections.engines.get"
                    },
                    "tune": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:tune",
                      "path": "v1beta/{+name}:tune",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Tunes an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION.",
                      "id": "discoveryengine.projects.locations.collections.engines.tune",
                      "httpMethod": "POST"
                    }
                  },
                  "resources": {
                    "conversations": {
                      "methods": {
                        "patch": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}",
                          "path": "v1beta/{+name}",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.patch",
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.create",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}/conversations",
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned."
                        },
                        "delete": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}",
                          "httpMethod": "DELETE",
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+name}"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}",
                          "description": "Gets a Conversation.",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.get",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "converse": {
                          "path": "v1beta/{+name}:converse",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.converse",
                          "description": "Converses a conversation.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}:converse",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists all Conversations by their parent DataStore.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.list",
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/conversations"
                        }
                      }
                    },
                    "completionConfig": {
                      "methods": {
                        "completeQuery": {
                          "id": "discoveryengine.projects.locations.collections.engines.completionConfig.completeQuery",
                          "description": "Completes the user input with advanced keyword suggestions.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/completionConfig:completeQuery",
                          "path": "v1beta/{+completionConfig}:completeQuery",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud_search.query",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "POST"
                        },
                        "removeSuggestion": {
                          "path": "v1beta/{+completionConfig}:removeSuggestion",
                          "httpMethod": "POST",
                          "description": "Removes the search history suggestion in an engine for a user. This will remove the suggestion from being returned in the AdvancedCompleteQueryResponse.recent_search_suggestions for this user. If the user searches the same suggestion again, the new history will override and suggest this suggestion again.",
                          "id": "discoveryengine.projects.locations.collections.engines.completionConfig.removeSuggestion",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/completionConfig:removeSuggestion",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        }
                      }
                    },
                    "assistants": {
                      "resources": {
                        "agents": {
                          "resources": {
                            "operations": {
                              "methods": {
                                "get": {
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                                  ],
                                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/operations/{operationsId}",
                                  "path": "v1beta/{+name}",
                                  "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.operations.get",
                                  "httpMethod": "GET",
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                                }
                              }
                            }
                          }
                        }
                      },
                      "methods": {
                        "streamAssist": {
                          "path": "v1beta/{+name}:streamAssist",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}:streamAssist",
                          "description": "Assists the user with a query in a streaming fashion.",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.streamAssist",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates an Assistant.",
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}/assistants",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.create",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants"
                        },
                        "patch": {
                          "httpMethod": "PATCH",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+name}",
                          "description": "Updates an Assistant"
                        },
                        "list": {
                          "path": "v1beta/{+parent}/assistants",
                          "description": "Lists all Assistants under an Engine.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.list",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants",
                          "httpMethod": "GET"
                        },
                        "get": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets an Assistant.",
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET"
                        },
                        "delete": {
                          "httpMethod": "DELETE",
                          "description": "Deletes an Assistant.",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.delete",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}"
                        }
                      }
                    },
                    "controls": {
                      "methods": {
                        "patch": {
                          "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                          "httpMethod": "PATCH",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls/{controlsId}",
                          "path": "v1beta/{+name}",
                          "id": "discoveryengine.projects.locations.collections.engines.controls.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.engines.controls.list",
                          "description": "Lists all Controls by their parent DataStore.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/controls"
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.collections.engines.controls.create",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls",
                          "path": "v1beta/{+parent}/controls",
                          "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "POST"
                        },
                        "get": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls/{controlsId}",
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}",
                          "description": "Gets a Control.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.controls.get"
                        },
                        "delete": {
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls/{controlsId}",
                          "id": "discoveryengine.projects.locations.collections.engines.controls.delete",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned."
                        }
                      }
                    },
                    "sessions": {
                      "methods": {
                        "patch": {
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}",
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.patch"
                        },
                        "get": {
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a Session.",
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.get",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}"
                        },
                        "create": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions",
                          "path": "v1beta/{+parent}/sessions",
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.create",
                          "httpMethod": "POST",
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.list",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions",
                          "path": "v1beta/{+parent}/sessions",
                          "description": "Lists all Sessions by their parent DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "GET"
                        },
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}",
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.delete",
                          "httpMethod": "DELETE"
                        }
                      },
                      "resources": {
                        "answers": {
                          "methods": {
                            "get": {
                              "path": "v1beta/{+name}",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}/answers/{answersId}",
                              "httpMethod": "GET",
                              "description": "Gets a Answer.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.engines.sessions.answers.get"
                            }
                          }
                        }
                      }
                    },
                    "operations": {
                      "methods": {
                        "list": {
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.engines.operations.list",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "path": "v1beta/{+name}/operations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/operations/{operationsId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.engines.operations.get"
                        }
                      }
                    },
                    "servingConfigs": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.list",
                          "path": "v1beta/{+parent}/servingConfigs",
                          "description": "Lists all ServingConfigs linked to this dataStore.",
                          "httpMethod": "GET"
                        },
                        "delete": {
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "path": "v1beta/{+name}",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.delete",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "DELETE"
                        },
                        "get": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}",
                          "path": "v1beta/{+name}",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.get",
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "GET"
                        },
                        "create": {
                          "path": "v1beta/{+parent}/servingConfigs",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.create",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs",
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "POST"
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "PATCH"
                        },
                        "searchLite": {
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.searchLite",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:searchLite",
                          "path": "v1beta/{+servingConfig}:searchLite"
                        },
                        "recommend": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Makes a recommendation, which requires a contextual user event.",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.recommend",
                          "path": "v1beta/{+servingConfig}:recommend",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:recommend",
                          "httpMethod": "POST"
                        },
                        "answer": {
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.answer",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:answer",
                          "path": "v1beta/{+servingConfig}:answer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Answer query method."
                        },
                        "search": {
                          "description": "Performs a search.",
                          "path": "v1beta/{+servingConfig}:search",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.search",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:search",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "POST"
                        },
                        "streamAnswer": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.streamAnswer",
                          "path": "v1beta/{+servingConfig}:streamAnswer",
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:streamAnswer"
                        }
                      }
                    }
                  }
                }
              }
            },
            "identityMappingStores": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.create",
                  "path": "v1beta/{+parent}/identityMappingStores",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "description": "Creates a new Identity Mapping Store.",
                  "httpMethod": "POST"
                },
                "delete": {
                  "id": "discoveryengine.projects.locations.identityMappingStores.delete",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "description": "Deletes the Identity Mapping Store.",
                  "path": "v1beta/{+name}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "importIdentityMappings": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:importIdentityMappings",
                  "path": "v1beta/{+identityMappingStore}:importIdentityMappings",
                  "id": "discoveryengine.projects.locations.identityMappingStores.importIdentityMappings",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Imports a list of Identity Mapping Entries to an Identity Mapping Store."
                },
                "purgeIdentityMappings": {
                  "path": "v1beta/{+identityMappingStore}:purgeIdentityMappings",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:purgeIdentityMappings",
                  "description": "Purges specified or all Identity Mapping Entries from an Identity Mapping Store.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.identityMappingStores.purgeIdentityMappings"
                },
                "listIdentityMappings": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:listIdentityMappings",
                  "id": "discoveryengine.projects.locations.identityMappingStores.listIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1beta/{+identityMappingStore}:listIdentityMappings",
                  "httpMethod": "GET",
                  "description": "Lists Identity Mappings in an Identity Mapping Store."
                },
                "list": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "description": "Lists all Identity Mapping Stores.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "httpMethod": "GET",
                  "path": "v1beta/{+parent}/identityMappingStores",
                  "id": "discoveryengine.projects.locations.identityMappingStores.list"
                },
                "get": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "httpMethod": "GET",
                  "description": "Gets the Identity Mapping Store.",
                  "id": "discoveryengine.projects.locations.identityMappingStores.get",
                  "path": "v1beta/{+name}"
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations/{operationsId}",
                      "path": "v1beta/{+name}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.get"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.list",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "httpMethod": "GET",
                      "path": "v1beta/{+name}/operations",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations"
                    }
                  }
                }
              }
            },
            "userStores": {
              "methods": {
                "patch": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "path": "v1beta/{+name}",
                  "httpMethod": "PATCH",
                  "description": "Updates the User Store.",
                  "id": "discoveryengine.projects.locations.userStores.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "batchUpdateUserLicenses": {
                  "path": "v1beta/{+parent}:batchUpdateUserLicenses",
                  "description": "Updates the User License. This method is used for batch assign/unassign licenses to users.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.userStores.batchUpdateUserLicenses",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}:batchUpdateUserLicenses"
                },
                "get": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "id": "discoveryengine.projects.locations.userStores.get",
                  "path": "v1beta/{+name}",
                  "description": "Gets the User Store.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "httpMethod": "GET"
                }
              },
              "resources": {
                "userLicenses": {
                  "methods": {
                    "list": {
                      "id": "discoveryengine.projects.locations.userStores.userLicenses.list",
                      "description": "Lists the User Licenses.",
                      "httpMethod": "GET",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/userLicenses",
                      "path": "v1beta/{+parent}/userLicenses",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                },
                "licenseConfigsUsageStats": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "path": "v1beta/{+parent}/licenseConfigsUsageStats",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/licenseConfigsUsageStats",
                      "description": "Lists all the LicenseConfigUsageStatss associated with the project.",
                      "id": "discoveryengine.projects.locations.userStores.licenseConfigsUsageStats.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                }
              }
            },
            "sampleQuerySets": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.create",
                  "description": "Creates a SampleQuerySet",
                  "path": "v1beta/{+parent}/sampleQuerySets"
                },
                "get": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1beta/{+name}",
                  "httpMethod": "GET",
                  "description": "Gets a SampleQuerySet.",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.get"
                },
                "list": {
                  "id": "discoveryengine.projects.locations.sampleQuerySets.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "httpMethod": "GET",
                  "description": "Gets a list of SampleQuerySets.",
                  "path": "v1beta/{+parent}/sampleQuerySets",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "httpMethod": "DELETE",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.delete",
                  "description": "Deletes a SampleQuerySet."
                },
                "patch": {
                  "description": "Updates a SampleQuerySet.",
                  "httpMethod": "PATCH",
                  "path": "v1beta/{+name}",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.patch",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}"
                }
              },
              "resources": {
                "sampleQueries": {
                  "methods": {
                    "delete": {
                      "description": "Deletes a SampleQuery.",
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "path": "v1beta/{+name}"
                    },
                    "patch": {
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.patch",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates a SampleQuery.",
                      "httpMethod": "PATCH"
                    },
                    "create": {
                      "path": "v1beta/{+parent}/sampleQueries",
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries",
                      "description": "Creates a SampleQuery",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "import": {
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.import",
                      "description": "Bulk import of multiple SampleQuerys. Sample queries that already exist may be deleted. Note: It is possible for a subset of the SampleQuerys to be successfully imported.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries:import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+parent}/sampleQueries:import",
                      "httpMethod": "POST"
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.get",
                      "description": "Gets a SampleQuery.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+name}",
                      "httpMethod": "GET"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.list",
                      "description": "Gets a list of SampleQuerys.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries",
                      "httpMethod": "GET",
                      "path": "v1beta/{+parent}/sampleQueries"
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "get": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/operations/{operationsId}",
                      "path": "v1beta/{+name}",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.operations.get",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                }
              }
            },
            "podcasts": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "path": "v1beta/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/podcasts/{podcastsId}/operations/{operationsId}",
                      "id": "discoveryengine.projects.locations.podcasts.operations.get",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            },
            "rankingConfigs": {
              "methods": {
                "rank": {
                  "httpMethod": "POST",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/rankingConfigs/{rankingConfigsId}:rank",
                  "id": "discoveryengine.projects.locations.rankingConfigs.rank",
                  "description": "Ranks a list of text records based on the given input query.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "path": "v1beta/{+rankingConfig}:rank"
                }
              }
            },
            "dataStores": {
              "resources": {
                "models": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+name}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.list"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.get",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "path": "v1beta/{+name}"
                        }
                      }
                    }
                  }
                },
                "servingConfigs": {
                  "methods": {
                    "answer": {
                      "httpMethod": "POST",
                      "path": "v1beta/{+servingConfig}:answer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.answer",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                      "description": "Answer query method."
                    },
                    "patch": {
                      "path": "v1beta/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.patch",
                      "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "create": {
                      "httpMethod": "POST",
                      "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.create",
                      "path": "v1beta/{+parent}/servingConfigs",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "list": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "description": "Lists all ServingConfigs linked to this dataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.list",
                      "path": "v1beta/{+parent}/servingConfigs",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.get",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+name}"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.delete",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}"
                    },
                    "streamAnswer": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.streamAnswer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+servingConfig}:streamAnswer",
                      "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream."
                    },
                    "recommend": {
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+servingConfig}:recommend",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.recommend",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                      "description": "Makes a recommendation, which requires a contextual user event."
                    },
                    "search": {
                      "httpMethod": "POST",
                      "path": "v1beta/{+servingConfig}:search",
                      "description": "Performs a search.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.search",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "searchLite": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                      "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, it i[...]",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.searchLite",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+servingConfig}:searchLite"
                    }
                  }
                },
                "completionConfig": {
                  "methods": {
                    "completeQuery": {
                      "description": "Completes the user input with advanced keyword suggestions.",
                      "path": "v1beta/{+completionConfig}:completeQuery",
                      "id": "discoveryengine.projects.locations.dataStores.completionConfig.completeQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud_search.query",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionConfig:completeQuery"
                    }
                  }
                },
                "conversations": {
                  "methods": {
                    "create": {
                      "httpMethod": "POST",
                      "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.conversations.create",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "path": "v1beta/{+parent}/conversations"
                    },
                    "get": {
                      "description": "Gets a Conversation.",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.get"
                    },
                    "converse": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                      "httpMethod": "POST",
                      "path": "v1beta/{+name}:converse",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.converse",
                      "description": "Converses a conversation.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "list": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "GET",
                      "path": "v1beta/{+parent}/conversations",
                      "description": "Lists all Conversations by their parent DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.list"
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.patch",
                      "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+name}"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+name}",
                      "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.delete",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}"
                    }
                  }
                },
                "userEvents": {
                  "methods": {
                    "write": {
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.write",
                      "description": "Writes a single user event.",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:write",
                      "path": "v1beta/{+parent}/userEvents:write"
                    },
                    "collect": {
                      "path": "v1beta/{+parent}/userEvents:collect",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.collect",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                      "httpMethod": "GET",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:collect"
                    },
                    "import": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:import",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "POST",
                      "path": "v1beta/{+parent}/userEvents:import",
                      "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata."
                    },
                    "purge": {
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.purge",
                      "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+parent}/userEvents:purge",
                      "httpMethod": "POST"
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "list": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations",
                      "path": "v1beta/{+name}/operations",
                      "httpMethod": "GET",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "id": "discoveryengine.projects.locations.dataStores.operations.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.operations.get",
                      "httpMethod": "GET",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations/{operationsId}"
                    }
                  }
                },
                "suggestionDenyListEntries": {
                  "methods": {
                    "import": {
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+parent}/suggestionDenyListEntries:import",
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.import",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                      "description": "Imports all SuggestionDenyListEntry for a DataStore."
                    },
                    "purge": {
                      "path": "v1beta/{+parent}/suggestionDenyListEntries:purge",
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.purge",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                      "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                },
                "controls": {
                  "methods": {
                    "list": {
                      "path": "v1beta/{+parent}/controls",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "id": "discoveryengine.projects.locations.dataStores.controls.list",
                      "httpMethod": "GET",
                      "description": "Lists all Controls by their parent DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.dataStores.controls.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                      "path": "v1beta/{+name}"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                      "path": "v1beta/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.controls.delete",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "httpMethod": "DELETE"
                    },
                    "get": {
                      "path": "v1beta/{+name}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a Control.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "id": "discoveryengine.projects.locations.dataStores.controls.get"
                    },
                    "create": {
                      "path": "v1beta/{+parent}/controls",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.controls.create",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "httpMethod": "POST",
                      "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned."
                    }
                  }
                },
                "completionSuggestions": {
                  "methods": {
                    "import": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+parent}/completionSuggestions:import",
                      "description": "Imports CompletionSuggestions for a DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.import",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                      "httpMethod": "POST"
                    },
                    "purge": {
                      "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.purge",
                      "path": "v1beta/{+parent}/completionSuggestions:purge"
                    }
                  }
                },
                "siteSearchEngine": {
                  "methods": {
                    "disableAdvancedSiteSearch": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                      "path": "v1beta/{+siteSearchEngine}:disableAdvancedSiteSearch",
                      "description": "Downgrade from advanced site search to basic site search.",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.disableAdvancedSiteSearch",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "enableAdvancedSiteSearch": {
                      "httpMethod": "POST",
                      "description": "Upgrade from basic site search to advanced site search.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "path": "v1beta/{+siteSearchEngine}:enableAdvancedSiteSearch",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.enableAdvancedSiteSearch"
                    },
                    "recrawlUris": {
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.recrawlUris",
                      "path": "v1beta/{+siteSearchEngine}:recrawlUris",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                      "description": "Request on-demand recrawl for a list of URIs."
                    }
                  },
                  "resources": {
                    "targetSites": {
                      "methods": {
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "description": "Deletes a TargetSite.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.delete",
                          "httpMethod": "DELETE"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.get",
                          "path": "v1beta/{+name}",
                          "description": "Gets a TargetSite.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "httpMethod": "GET"
                        },
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "path": "v1beta/{+name}",
                          "httpMethod": "PATCH",
                          "description": "Updates a TargetSite.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.patch",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}"
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/targetSites",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.list",
                          "description": "Gets a list of TargetSites.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites"
                        },
                        "batchCreate": {
                          "path": "v1beta/{+parent}/targetSites:batchCreate",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
[...]
