{
  "description": "Discovery Engine API.",
  "version": "v1beta",
  "title": "Discovery Engine API",
  "version_module": true,
  "discoveryVersion": "v1",
  "id": "discoveryengine:v1beta",
  "documentationLink": "https://cloud.google.com/generative-ai-app-builder/docs/",
  "revision": "20260322",
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite": {
          "description": "View your Agentspace chat history, including uploaded files and generated reports and visualizations, and interact with the Agentspace assistant on your behalf."
        },
        "https://www.googleapis.com/auth/discoveryengine.readwrite": {
          "description": "View, edit, create, and delete all your data associated with any Discovery Engine API product, such as Agentspace, Vertex AI Search, or NotebookLM Enterprise, including both end user data and administration or configuration data."
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        }
      }
    }
  },
  "basePath": "",
  "ownerName": "Google",
  "fullyEncodeReservedExpansion": true,
  "servicePath": "",
  "baseUrl": "https://discoveryengine.googleapis.com/",
  "canonicalName": "Discovery Engine",
  "protocol": "rest",
  "resources": {
    "projects": {
      "methods": {
        "provision": {
          "path": "v1beta/{+name}:provision",
          "scopes": [
            "https://www.googleapis.com/auth/cloud-platform",
            "https://www.googleapis.com/auth/discoveryengine.readwrite"
          ],
          "description": "Provisions the project resource. During the process, related systems will get prepared and initialized. Caller must read the [Terms for data use](https://cloud.google.com/retail/data-use-terms), and optionally specify in request to provide consent to that service terms.",
          "id": "discoveryengine.projects.provision",
          "httpMethod": "POST",
          "flatPath": "v1beta/projects/{projectsId}:provision"
        }
      },
      "resources": {
        "locations": {
          "methods": {
            "updateAclConfig": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.locations.updateAclConfig",
              "httpMethod": "PATCH",
              "description": "Default ACL configuration for use in a location of a customer's project. Updates will only reflect to new data stores. Existing data stores will still use the old value.",
              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/aclConfig",
              "path": "v1beta/{+name}"
            },
            "removeDedicatedCrawlRate": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.locations.removeDedicatedCrawlRate",
              "httpMethod": "POST",
              "path": "v1beta/{+location}:removeDedicatedCrawlRate",
              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}:removeDedicatedCrawlRate",
              "description": "Removes the dedicated crawl rate for a craw_rate_scope. If the dedicated crawl rate was set, this will disable vertex AI's crawl bot from using the dedicated crawl rate for crawling. If the dedicated crawl rate was not set, this is a no-op."
            },
            "setDedicatedCrawlRate": {
              "id": "discoveryengine.projects.locations.setDedicatedCrawlRate",
              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}:setDedicatedCrawlRate",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "path": "v1beta/{+location}:setDedicatedCrawlRate",
              "description": "Sets the dedicated crawl rate for a crawl_rate_scope. If the dedicated crawl rate was not set, this will enable vertex AI's crawl bot to use the new dedicated crawl rate for crawling. If the dedicated crawl rate was set, vertex AI's crawl bot will try to update the rate to the new value. If the new value is too high, the crawl bot may crawl at a lower rate to avoid overloading the user's website.",
              "httpMethod": "POST"
            },
            "obtainCrawlRate": {
              "description": "Obtains the time series data of organic or dedicated crawl rate for monitoring. When dedicated crawl rate is not set, it will return vertex AI's organic crawl rate time series. Organic crawl means Google automatically crawl the internet at its own convenience. When dedicated crawl rate is set, it will return vertex AI's dedicated crawl rate time series.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "httpMethod": "POST",
              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}:obtainCrawlRate",
              "path": "v1beta/{+location}:obtainCrawlRate",
              "id": "discoveryengine.projects.locations.obtainCrawlRate"
            },
            "getCmekConfig": {
              "path": "v1beta/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.locations.getCmekConfig",
              "httpMethod": "GET",
              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/cmekConfig",
              "description": "Gets the CmekConfig."
            },
            "getAclConfig": {
              "httpMethod": "GET",
              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/aclConfig",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "id": "discoveryengine.projects.locations.getAclConfig",
              "path": "v1beta/{+name}",
              "description": "Gets the AclConfig."
            },
            "updateCmekConfig": {
              "path": "v1beta/{+name}",
              "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/cmekConfig",
              "id": "discoveryengine.projects.locations.updateCmekConfig",
              "httpMethod": "PATCH"
            }
          },
          "resources": {
            "sampleQuerySets": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.list",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets",
                  "path": "v1beta/{+parent}/sampleQuerySets",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Gets a list of SampleQuerySets."
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.create",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets",
                  "description": "Creates a SampleQuerySet",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1beta/{+parent}/sampleQuerySets"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.sampleQuerySets.patch",
                  "description": "Updates a SampleQuerySet.",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "httpMethod": "PATCH",
                  "path": "v1beta/{+name}"
                },
                "delete": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "path": "v1beta/{+name}",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Deletes a SampleQuerySet."
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Gets a SampleQuerySet.",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.get",
                  "httpMethod": "GET",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}"
                }
              },
              "resources": {
                "sampleQueries": {
                  "methods": {
                    "create": {
                      "path": "v1beta/{+parent}/sampleQueries",
                      "description": "Creates a SampleQuery",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.create",
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+parent}/sampleQueries",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.list",
                      "httpMethod": "GET",
                      "description": "Gets a list of SampleQuerys.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.delete",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "description": "Deletes a SampleQuery.",
                      "httpMethod": "DELETE"
                    },
                    "import": {
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.import",
                      "path": "v1beta/{+parent}/sampleQueries:import",
                      "description": "Bulk import of multiple SampleQuerys. Sample queries that already exist may be deleted. Note: It is possible for a subset of the SampleQuerys to be successfully imported.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries:import",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "get": {
                      "path": "v1beta/{+name}",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.get",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "description": "Gets a SampleQuery."
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.patch",
                      "description": "Updates a SampleQuery.",
                      "path": "v1beta/{+name}",
                      "httpMethod": "PATCH",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}"
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "get": {
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "path": "v1beta/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.operations.get",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/operations/{operationsId}"
                    }
                  }
                }
              }
            },
            "cmekConfigs": {
              "methods": {
                "list": {
                  "path": "v1beta/{+parent}/cmekConfigs",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/cmekConfigs",
                  "httpMethod": "GET",
                  "description": "Lists all the CmekConfigs with the project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.cmekConfigs.list"
                },
                "patch": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "id": "discoveryengine.projects.locations.cmekConfigs.patch",
                  "path": "v1beta/{+name}",
                  "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location.",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "get": {
                  "httpMethod": "GET",
                  "description": "Gets the CmekConfig.",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.cmekConfigs.get"
                },
                "delete": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "path": "v1beta/{+name}",
                  "id": "discoveryengine.projects.locations.cmekConfigs.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "DELETE",
                  "description": "De-provisions a CmekConfig."
                }
              }
            },
            "licenseConfigs": {
              "methods": {
                "patch": {
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.licenseConfigs.patch",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}",
                  "description": "Updates the LicenseConfig"
                },
                "create": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/licenseConfigs",
                  "id": "discoveryengine.projects.locations.licenseConfigs.create",
                  "description": "Creates a LicenseConfig This method should only be used for creating NotebookLm licenses or Gemini Enterprise free trial licenses.",
                  "httpMethod": "POST",
                  "path": "v1beta/{+parent}/licenseConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "get": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}",
                  "description": "Gets a LicenseConfig.",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.licenseConfigs.get",
                  "path": "v1beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                }
              }
            },
            "groundingConfigs": {
              "methods": {
                "check": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "POST",
                  "description": "Performs a grounding check.",
                  "path": "v1beta/{+groundingConfig}:check",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/groundingConfigs/{groundingConfigsId}:check",
                  "id": "discoveryengine.projects.locations.groundingConfigs.check"
                }
              }
            },
            "userStores": {
              "methods": {
                "batchUpdateUserLicenses": {
                  "httpMethod": "POST",
                  "description": "Updates the User License. This method is used for batch assign/unassign licenses to users.",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}:batchUpdateUserLicenses",
                  "id": "discoveryengine.projects.locations.userStores.batchUpdateUserLicenses",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1beta/{+parent}:batchUpdateUserLicenses"
                },
                "patch": {
                  "id": "discoveryengine.projects.locations.userStores.patch",
                  "description": "Updates the User Store.",
                  "path": "v1beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "httpMethod": "PATCH"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "description": "Gets the User Store.",
                  "id": "discoveryengine.projects.locations.userStores.get"
                }
              },
              "resources": {
                "licenseConfigsUsageStats": {
                  "methods": {
                    "list": {
                      "id": "discoveryengine.projects.locations.userStores.licenseConfigsUsageStats.list",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/licenseConfigsUsageStats",
                      "path": "v1beta/{+parent}/licenseConfigsUsageStats",
                      "description": "Lists all the LicenseConfigUsageStatss associated with the project.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET"
                    }
                  }
                },
                "userLicenses": {
                  "methods": {
                    "list": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/userLicenses",
                      "description": "Lists the User Licenses.",
                      "path": "v1beta/{+parent}/userLicenses",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.userStores.userLicenses.list",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            },
            "podcasts": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/podcasts/{podcastsId}/operations/{operationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "path": "v1beta/{+name}",
                      "id": "discoveryengine.projects.locations.podcasts.operations.get",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            },
            "userEvents": {
              "methods": {
                "write": {
                  "path": "v1beta/{+parent}/userEvents:write",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userEvents:write",
                  "description": "Writes a single user event.",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.userEvents.write",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "collect": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1beta/{+parent}/userEvents:collect",
                  "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userEvents:collect",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.userEvents.collect"
                },
                "import": {
                  "id": "discoveryengine.projects.locations.userEvents.import",
                  "httpMethod": "POST",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/userEvents:import",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1beta/{+parent}/userEvents:import",
                  "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata."
                }
              }
            },
            "operations": {
              "methods": {
                "list": {
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                  "id": "discoveryengine.projects.locations.operations.list",
                  "path": "v1beta/{+name}/operations",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/operations"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "id": "discoveryengine.projects.locations.operations.get",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "path": "v1beta/{+name}",
                  "httpMethod": "GET"
                }
              }
            },
            "collections": {
              "resources": {
                "operations": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "path": "v1beta/{+name}/operations",
                      "id": "discoveryengine.projects.locations.collections.operations.list",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/operations",
                      "httpMethod": "GET"
                    },
                    "get": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/operations/{operationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+name}",
                      "id": "discoveryengine.projects.locations.collections.operations.get",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "httpMethod": "GET"
                    }
                  }
                },
                "dataStores": {
                  "resources": {
                    "models": {
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.list",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1beta/{+name}/operations"
                            },
                            "get": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.get",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "path": "v1beta/{+name}",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                            }
                          }
                        }
                      }
                    },
                    "sessions": {
                      "resources": {
                        "answers": {
                          "methods": {
                            "get": {
                              "description": "Gets a Answer.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.sessions.answers.get",
                              "httpMethod": "GET",
                              "path": "v1beta/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}"
                            }
                          }
                        }
                      },
                      "methods": {
                        "delete": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.delete",
                          "path": "v1beta/{+name}",
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}"
                        },
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.patch",
                          "httpMethod": "PATCH",
                          "path": "v1beta/{+name}",
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned."
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.get",
                          "description": "Gets a Session.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "path": "v1beta/{+name}"
                        },
                        "create": {
                          "httpMethod": "POST",
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+parent}/sessions",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.create"
                        },
                        "list": {
                          "path": "v1beta/{+parent}/sessions",
                          "description": "Lists all Sessions by their parent DataStore.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "branches": {
                      "methods": {
                        "batchGetDocumentsMetadata": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/batchGetDocumentsMetadata",
                          "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.batchGetDocumentsMetadata"
                        }
                      },
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "path": "v1beta/{+name}/operations",
                              "httpMethod": "GET",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.list"
                            },
                            "cancel": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                              "httpMethod": "POST",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.cancel",
                              "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; in[...]",
                              "path": "v1beta/{+name}:cancel"
                            },
                            "get": {
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "path": "v1beta/{+name}",
                              "httpMethod": "GET",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            }
                          }
                        },
                        "documents": {
                          "methods": {
                            "import": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.import",
                              "path": "v1beta/{+parent}/documents:import",
                              "httpMethod": "POST",
                              "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated."
                            },
                            "create": {
                              "httpMethod": "POST",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.create",
                              "path": "v1beta/{+parent}/documents",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Creates a Document.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents"
                            },
                            "list": {
                              "description": "Gets a list of Documents.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.list",
                              "path": "v1beta/{+parent}/documents",
                              "httpMethod": "GET"
                            },
                            "purge": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1beta/{+parent}/documents:purge",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.purge",
                              "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                              "httpMethod": "POST"
                            },
                            "delete": {
                              "description": "Deletes a Document.",
                              "path": "v1beta/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.delete",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "DELETE"
                            },
                            "patch": {
                              "httpMethod": "PATCH",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.patch",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "path": "v1beta/{+name}",
                              "description": "Updates a Document."
                            },
                            "get": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "description": "Gets a Document.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.get",
                              "httpMethod": "GET",
                              "path": "v1beta/{+name}"
                            }
                          }
                        }
                      }
                    },
                    "servingConfigs": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+parent}/servingConfigs",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.list",
                          "description": "Lists all ServingConfigs linked to this dataStore.",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs"
                        },
                        "streamAnswer": {
                          "httpMethod": "POST",
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.streamAnswer",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+servingConfig}:streamAnswer"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.get",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist."
                        },
                        "answer": {
                          "path": "v1beta/{+servingConfig}:answer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Answer query method.",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.answer"
                        },
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.delete",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "path": "v1beta/{+name}"
                        },
                        "searchLite": {
                          "httpMethod": "POST",
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+servingConfig}:searchLite",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.searchLite",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite"
                        },
                        "create": {
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.create",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "path": "v1beta/{+parent}/servingConfigs",
                          "httpMethod": "POST"
                        },
                        "patch": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.patch",
                          "httpMethod": "PATCH"
                        },
                        "search": {
                          "description": "Performs a search.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.search",
                          "path": "v1beta/{+servingConfig}:search",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                          "httpMethod": "POST"
                        },
                        "recommend": {
                          "httpMethod": "POST",
                          "path": "v1beta/{+servingConfig}:recommend",
                          "description": "Makes a recommendation, which requires a contextual user event.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.recommend",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "suggestionDenyListEntries": {
                      "methods": {
                        "purge": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.purge",
                          "path": "v1beta/{+parent}/suggestionDenyListEntries:purge",
                          "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore."
                        },
                        "import": {
                          "path": "v1beta/{+parent}/suggestionDenyListEntries:import",
                          "httpMethod": "POST",
                          "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "siteSearchEngine": {
                      "resources": {
                        "targetSites": {
                          "methods": {
                            "delete": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "httpMethod": "DELETE",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1beta/{+name}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.delete",
                              "description": "Deletes a TargetSite."
                            },
                            "patch": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Updates a TargetSite.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.patch",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "httpMethod": "PATCH",
                              "path": "v1beta/{+name}"
                            },
                            "create": {
                              "description": "Creates a TargetSite.",
                              "httpMethod": "POST",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.create",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1beta/{+parent}/targetSites"
                            },
                            "get": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Gets a TargetSite.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.get",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "path": "v1beta/{+name}",
                              "httpMethod": "GET"
                            },
                            "batchCreate": {
                              "description": "Creates TargetSite in a batch.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.batchCreate",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                              "httpMethod": "POST",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1beta/{+parent}/targetSites:batchCreate"
                            },
                            "list": {
                              "path": "v1beta/{+parent}/targetSites",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.list",
                              "description": "Gets a list of TargetSites.",
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            }
                          },
                          "resources": {
                            "operations": {
                              "methods": {
                                "list": {
                                  "path": "v1beta/{+name}/operations",
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.list",
                                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                                  "httpMethod": "GET",
                                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ]
                                },
                                "get": {
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.get",
                                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations/{operationsId}",
                                  "httpMethod": "GET",
                                  "path": "v1beta/{+name}"
                                }
                              }
                            }
                          }
                        },
                        "sitemaps": {
                          "methods": {
                            "create": {
                              "path": "v1beta/{+parent}/sitemaps",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "POST",
                              "description": "Creates a Sitemap.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.create",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps"
                            },
                            "delete": {
                              "httpMethod": "DELETE",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.delete",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Deletes a Sitemap.",
                              "path": "v1beta/{+name}"
                            },
                            "fetch": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.fetch",
                              "path": "v1beta/{+parent}/sitemaps:fetch",
                              "httpMethod": "GET",
                              "description": "Fetch Sitemaps in a DataStore."
                            }
                          }
                        },
                        "operations": {
                          "methods": {
                            "list": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.operations.list",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/operations",
                              "path": "v1beta/{+name}/operations",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                            },
                            "get": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/operations/{operationsId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.operations.get",
                              "path": "v1beta/{+name}"
                            }
                          }
                        }
                      },
                      "methods": {
                        "disableAdvancedSiteSearch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Downgrade from advanced site search to basic site search.",
                          "path": "v1beta/{+siteSearchEngine}:disableAdvancedSiteSearch",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.disableAdvancedSiteSearch"
                        },
                        "fetchDomainVerificationStatus": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:fetchDomainVerificationStatus",
                          "path": "v1beta/{+siteSearchEngine}:fetchDomainVerificationStatus",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.fetchDomainVerificationStatus",
                          "httpMethod": "GET",
                          "description": "Returns list of target sites with its domain verification status. This method can only be called under data store with BASIC_SITE_SEARCH state at the moment."
                        },
                        "batchVerifyTargetSites": {
                          "httpMethod": "POST",
                          "description": "Verify target sites' ownership and validity. This API sends all the target sites under site search engine for verification.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:batchVerifyTargetSites",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.batchVerifyTargetSites",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+parent}:batchVerifyTargetSites"
                        },
                        "recrawlUris": {
                          "path": "v1beta/{+siteSearchEngine}:recrawlUris",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Request on-demand recrawl for a list of URIs.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.recrawlUris"
                        },
                        "enableAdvancedSiteSearch": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch",
                          "path": "v1beta/{+siteSearchEngine}:enableAdvancedSiteSearch",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Upgrade from basic site search to advanced site search.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.enableAdvancedSiteSearch"
                        }
                      }
                    },
                    "schemas": {
                      "methods": {
                        "get": {
                          "description": "Gets a Schema.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.get",
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "patch": {
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "description": "Updates a Schema.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH"
                        },
                        "list": {
                          "description": "Gets a list of Schemas.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/schemas",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas"
                        },
                        "create": {
                          "description": "Creates a Schema.",
                          "path": "v1beta/{+parent}/schemas",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.create",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas"
                        },
                        "delete": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.delete",
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "httpMethod": "DELETE",
                          "description": "Deletes a Schema."
                        }
                      },
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "httpMethod": "GET",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations",
                              "path": "v1beta/{+name}/operations",
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.list"
                            },
                            "get": {
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations/{operationsId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.get",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "httpMethod": "GET",
                              "path": "v1beta/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            }
                          }
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.list",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "path": "v1beta/{+parent}/conversations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Lists all Conversations by their parent DataStore."
                        },
                        "get": {
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a Conversation.",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.get"
                        },
                        "create": {
                          "path": "v1beta/{+parent}/conversations",
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.create",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations"
                        },
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.delete",
                          "httpMethod": "DELETE",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "path": "v1beta/{+name}"
                        },
                        "patch": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.patch",
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                          "httpMethod": "PATCH"
                        },
                        "converse": {
                          "path": "v1beta/{+name}:converse",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Converses a conversation.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.converse"
                        }
                      }
                    },
                    "completionConfig": {
                      "methods": {
                        "completeQuery": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud_search.query",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Completes the user input with advanced keyword suggestions.",
                          "path": "v1beta/{+completionConfig}:completeQuery",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionConfig.completeQuery",
                          "httpMethod": "POST"
                        }
                      }
                    },
                    "operations": {
                      "methods": {
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.get",
                          "path": "v1beta/{+name}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations/{operationsId}"
                        },
                        "list": {
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+name}/operations",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations",
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.list",
                          "httpMethod": "GET"
                        }
                      }
                    },
                    "controls": {
                      "methods": {
                        "list": {
                          "httpMethod": "GET",
                          "path": "v1beta/{+parent}/controls",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "description": "Lists all Controls by their parent DataStore."
                        },
                        "create": {
                          "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                          "path": "v1beta/{+parent}/controls",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls"
                        },
                        "patch": {
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "httpMethod": "PATCH",
                          "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.patch"
                        },
                        "get": {
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}",
                          "description": "Gets a Control.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.get"
                        },
                        "delete": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.delete",
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "httpMethod": "DELETE",
                          "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned."
                        }
                      }
                    },
                    "userEvents": {
                      "methods": {
                        "write": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:write",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.write",
                          "path": "v1beta/{+parent}/userEvents:write",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Writes a single user event."
                        },
                        "import": {
                          "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+parent}/userEvents:import",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.import",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:import",
                          "httpMethod": "POST"
                        },
                        "purge": {
                          "path": "v1beta/{+parent}/userEvents:purge",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:purge"
                        },
                        "collect": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:collect",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.collect",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+parent}/userEvents:collect",
                          "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                          "httpMethod": "GET"
                        }
                      }
                    },
                    "customModels": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.customModels.list",
                          "path": "v1beta/{+dataStore}/customModels",
                          "httpMethod": "GET",
                          "description": "Gets a list of all the custom models.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/customModels"
                        }
                      }
                    },
                    "completionSuggestions": {
                      "methods": {
                        "import": {
                          "path": "v1beta/{+parent}/completionSuggestions:import",
                          "httpMethod": "POST",
                          "description": "Imports CompletionSuggestions for a DataStore.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "purge": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.purge",
                          "httpMethod": "POST",
                          "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                          "path": "v1beta/{+parent}/completionSuggestions:purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    }
                  },
                  "methods": {
                    "list": {
                      "path": "v1beta/{+parent}/dataStores",
                      "httpMethod": "GET",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores",
                      "description": "Lists all the DataStores associated with the project.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.dataStores.list"
                    },
                    "trainCustomModel": {
                      "description": "Trains a custom model.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:trainCustomModel",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.dataStores.trainCustomModel",
                      "path": "v1beta/{+dataStore}:trainCustomModel"
                    },
                    "getSiteSearchEngine": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.getSiteSearchEngine",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets the SiteSearchEngine.",
                      "httpMethod": "GET"
                    },
                    "create": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores",
                      "path": "v1beta/{+parent}/dataStores",
                      "id": "discoveryengine.projects.locations.collections.dataStores.create",
                      "httpMethod": "POST",
                      "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "get": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets a DataStore.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.get",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "path": "v1beta/{+name}"
                    },
                    "delete": {
                      "description": "Deletes a DataStore.",
                      "httpMethod": "DELETE",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "path": "v1beta/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.dataStores.delete"
                    },
                    "patch": {
                      "description": "Updates a DataStore",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+name}",
                      "id": "discoveryengine.projects.locations.collections.dataStores.patch",
                      "httpMethod": "PATCH",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}"
                    },
                    "completeQuery": {
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.collections.dataStores.completeQuery",
                      "description": "Completes the specified user input with keyword suggestions.",
                      "path": "v1beta/{+dataStore}:completeQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:completeQuery"
                    }
                  }
                },
                "engines": {
                  "methods": {
                    "getIamPolicy": {
                      "id": "discoveryengine.projects.locations.collections.engines.getIamPolicy",
                      "path": "v1beta/{+resource}:getIamPolicy",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. An empty policy is returned if the resource exists but does not have a policy set on it.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:getIamPolicy"
                    },
                    "setIamPolicy": {
                      "id": "discoveryengine.projects.locations.collections.engines.setIamPolicy",
                      "httpMethod": "POST",
                      "description": "Sets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. **Important:** When setting a policy directly on an Engine resource, the only recommended roles in the bindings are: `roles/discoveryengine.user` and `roles/discoveryengine.agentspaceUser`. Attempting to grant any other role will result in a warning in logging.",
                      "path": "v1beta/{+resource}:setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:setIamPolicy"
                    },
                    "get": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "description": "Gets an Engine.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.engines.get",
                      "path": "v1beta/{+name}",
                      "httpMethod": "GET"
                    },
                    "create": {
                      "id": "discoveryengine.projects.locations.collections.engines.create",
                      "httpMethod": "POST",
                      "description": "Creates an Engine.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+parent}/engines",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines"
                    },
                    "pause": {
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.engines.pause",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:pause",
                      "description": "Pauses the training of an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION.",
                      "path": "v1beta/{+name}:pause",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "delete": {
                      "id": "discoveryengine.projects.locations.collections.engines.delete",
                      "httpMethod": "DELETE",
                      "path": "v1beta/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "description": "Deletes an Engine."
                    },
                    "tune": {
                      "description": "Tunes an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION.",
                      "httpMethod": "POST",
                      "path": "v1beta/{+name}:tune",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.engines.tune",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:tune"
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.collections.engines.list",
                      "path": "v1beta/{+parent}/engines",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines",
                      "description": "Lists all the Engines associated with the project."
                    },
                    "patch": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "id": "discoveryengine.projects.locations.collections.engines.patch",
                      "path": "v1beta/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Updates an Engine",
                      "httpMethod": "PATCH"
                    },
                    "resume": {
                      "id": "discoveryengine.projects.locations.collections.engines.resume",
                      "path": "v1beta/{+name}:resume",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:resume",
                      "httpMethod": "POST",
                      "description": "Resumes the training of an existing Engine. Only applicable if SolutionType is SOLUTION_TYPE_RECOMMENDATION."
                    }
                  },
                  "resources": {
                    "operations": {
                      "methods": {
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/operations/{operationsId}",
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}",
                          "id": "discoveryengine.projects.locations.collections.engines.operations.get"
                        },
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.engines.operations.list",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/operations",
                          "path": "v1beta/{+name}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "completionConfig": {
                      "methods": {
                        "removeSuggestion": {
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.completionConfig.removeSuggestion",
                          "description": "Removes the search history suggestion in an engine for a user. This will remove the suggestion from being returned in the AdvancedCompleteQueryResponse.recent_search_suggestions for this user. If the user searches the same suggestion again, the new history will override and suggest this suggestion again.",
                          "path": "v1beta/{+completionConfig}:removeSuggestion",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/completionConfig:removeSuggestion"
                        },
                        "completeQuery": {
                          "path": "v1beta/{+completionConfig}:completeQuery",
                          "description": "Completes the user input with advanced keyword suggestions.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud_search.query",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.completionConfig.completeQuery",
                          "httpMethod": "POST",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/completionConfig:completeQuery"
                        }
                      }
                    },
                    "servingConfigs": {
                      "methods": {
                        "recommend": {
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.recommend",
                          "description": "Makes a recommendation, which requires a contextual user event.",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+servingConfig}:recommend",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:recommend"
                        },
                        "list": {
                          "path": "v1beta/{+parent}/servingConfigs",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "description": "Lists all ServingConfigs linked to this dataStore.",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.list"
                        },
                        "delete": {
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "DELETE",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.delete",
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist."
                        },
                        "get": {
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.get",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}",
                          "path": "v1beta/{+name}"
                        },
                        "patch": {
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "path": "v1beta/{+name}",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.patch",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}"
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs",
                          "path": "v1beta/{+parent}/servingConfigs",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.create",
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                          "httpMethod": "POST"
                        },
                        "streamAnswer": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:streamAnswer",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.streamAnswer",
                          "path": "v1beta/{+servingConfig}:streamAnswer",
                          "httpMethod": "POST"
                        },
                        "search": {
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.search",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:search",
                          "description": "Performs a search.",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+servingConfig}:search"
                        },
                        "searchLite": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+servingConfig}:searchLite",
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:searchLite",
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.searchLite",
                          "httpMethod": "POST"
                        },
                        "answer": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/servingConfigs/{servingConfigsId}:answer",
                          "description": "Answer query method.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.servingConfigs.answer",
                          "httpMethod": "POST",
                          "path": "v1beta/{+servingConfig}:answer"
                        }
                      }
                    },
                    "assistants": {
                      "methods": {
                        "delete": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+name}",
                          "description": "Deletes an Assistant.",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.delete"
                        },
                        "streamAssist": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+name}:streamAssist",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}:streamAssist",
                          "description": "Assists the user with a query in a streaming fashion.",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.streamAssist",
                          "httpMethod": "POST"
                        },
                        "patch": {
                          "httpMethod": "PATCH",
                          "path": "v1beta/{+name}",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Updates an Assistant",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}"
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants",
                          "path": "v1beta/{+parent}/assistants",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.create",
                          "description": "Creates an Assistant."
                        },
                        "list": {
                          "description": "Lists all Assistants under an Engine.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+parent}/assistants",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.list"
                        },
                        "get": {
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}",
                          "httpMethod": "GET",
                          "description": "Gets an Assistant.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.get"
                        }
                      },
                      "resources": {
                        "agents": {
                          "resources": {
                            "operations": {
                              "methods": {
                                "get": {
                                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/operations/{operationsId}",
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                                  "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.operations.get",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "path": "v1beta/{+name}",
                                  "httpMethod": "GET"
                                }
                              }
                            }
                          }
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "delete": {
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.delete",
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "converse": {
                          "path": "v1beta/{+name}:converse",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "description": "Converses a conversation.",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.converse",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}:converse"
                        },
                        "create": {
                          "path": "v1beta/{+parent}/conversations",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations",
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned."
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.get",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}",
                          "path": "v1beta/{+name}",
                          "description": "Gets a Conversation.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}",
                          "path": "v1beta/{+name}",
                          "httpMethod": "PATCH",
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned."
                        },
                        "list": {
                          "path": "v1beta/{+parent}/conversations",
                          "httpMethod": "GET",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.list",
                          "description": "Lists all Conversations by their parent DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "controls": {
                      "methods": {
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+name}",
                          "id": "discoveryengine.projects.locations.collections.engines.controls.delete",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls/{controlsId}",
                          "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                          "httpMethod": "DELETE"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.engines.controls.get",
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls/{controlsId}",
                          "description": "Gets a Control."
                        },
                        "create": {
                          "httpMethod": "POST",
                          "path": "v1beta/{+parent}/controls",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.controls.create",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls",
                          "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned."
                        },
                        "list": {
                          "path": "v1beta/{+parent}/controls",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.controls.list",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls",
                          "description": "Lists all Controls by their parent DataStore.",
                          "httpMethod": "GET"
                        },
                        "patch": {
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.controls.patch",
                          "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/controls/{controlsId}",
                          "path": "v1beta/{+name}"
                        }
                      }
                    },
                    "sessions": {
                      "methods": {
                        "list": {
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions",
                          "httpMethod": "GET",
                          "description": "Lists all Sessions by their parent DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.list",
                          "path": "v1beta/{+parent}/sessions"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.get",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}",
                          "path": "v1beta/{+name}",
                          "description": "Gets a Session."
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.create",
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                          "path": "v1beta/{+parent}/sessions"
                        },
                        "delete": {
                          "httpMethod": "DELETE",
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}",
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.delete"
                        },
                        "patch": {
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}",
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.patch"
                        }
                      },
                      "resources": {
                        "answers": {
                          "methods": {
                            "get": {
                              "description": "Gets a Answer.",
                              "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}/answers/{answersId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1beta/{+name}",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.engines.sessions.answers.get"
                            }
                          }
                        }
                      }
                    }
                  }
                },
                "dataConnector": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "path": "v1beta/{+name}/operations",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.list",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations",
                          "httpMethod": "GET",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "get": {
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations/{operationsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.get",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                        }
                      }
                    }
                  }
                }
              }
            },
            "evaluations": {
              "methods": {
                "get": {
                  "id": "discoveryengine.projects.locations.evaluations.get",
                  "httpMethod": "GET",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}",
                  "description": "Gets a Evaluation.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1beta/{+name}"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.evaluations.list",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "path": "v1beta/{+parent}/evaluations",
                  "description": "Gets a list of Evaluations."
                },
                "listResults": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}:listResults",
                  "httpMethod": "GET",
                  "description": "Gets a list of results for a given a Evaluation.",
                  "path": "v1beta/{+evaluation}:listResults",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.evaluations.listResults"
                },
                "create": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "POST",
                  "path": "v1beta/{+parent}/evaluations",
                  "description": "Creates a Evaluation. Upon creation, the evaluation will be automatically triggered and begin execution.",
                  "id": "discoveryengine.projects.locations.evaluations.create"
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.evaluations.operations.get",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}/operations/{operationsId}",
                      "path": "v1beta/{+name}"
                    }
                  }
                }
              }
            },
            "identityMappingStores": {
              "methods": {
                "importIdentityMappings": {
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.identityMappingStores.importIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Imports a list of Identity Mapping Entries to an Identity Mapping Store.",
                  "path": "v1beta/{+identityMappingStore}:importIdentityMappings",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:importIdentityMappings"
                },
                "listIdentityMappings": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:listIdentityMappings",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.listIdentityMappings",
                  "path": "v1beta/{+identityMappingStore}:listIdentityMappings",
                  "description": "Lists Identity Mappings in an Identity Mapping Store."
                },
                "create": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Creates a new Identity Mapping Store.",
                  "path": "v1beta/{+parent}/identityMappingStores",
                  "id": "discoveryengine.projects.locations.identityMappingStores.create"
                },
                "get": {
                  "path": "v1beta/{+name}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.identityMappingStores.get",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "description": "Gets the Identity Mapping Store.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "purgeIdentityMappings": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.purgeIdentityMappings",
                  "description": "Purges specified or all Identity Mapping Entries from an Identity Mapping Store.",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:purgeIdentityMappings",
                  "path": "v1beta/{+identityMappingStore}:purgeIdentityMappings"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.identityMappingStores.list",
                  "path": "v1beta/{+parent}/identityMappingStores",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "description": "Lists all Identity Mapping Stores."
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "id": "discoveryengine.projects.locations.identityMappingStores.delete",
                  "description": "Deletes the Identity Mapping Store.",
                  "path": "v1beta/{+name}"
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.get",
                      "httpMethod": "GET",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations/{operationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+name}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                    },
                    "list": {
                      "path": "v1beta/{+name}/operations",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.list",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations"
                    }
                  }
                }
              }
            },
            "dataStores": {
              "methods": {
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.delete",
                  "httpMethod": "DELETE",
                  "path": "v1beta/{+name}",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "description": "Deletes a DataStore."
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists all the DataStores associated with the project.",
                  "path": "v1beta/{+parent}/dataStores",
                  "id": "discoveryengine.projects.locations.dataStores.list",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores"
                },
                "create": {
                  "id": "discoveryengine.projects.locations.dataStores.create",
                  "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                  "httpMethod": "POST",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1beta/{+parent}/dataStores"
                },
                "completeQuery": {
                  "path": "v1beta/{+dataStore}:completeQuery",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.completeQuery",
                  "description": "Completes the specified user input with keyword suggestions.",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:completeQuery"
                },
                "get": {
                  "description": "Gets a DataStore.",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1beta/{+name}",
                  "id": "discoveryengine.projects.locations.dataStores.get",
                  "httpMethod": "GET"
                },
                "patch": {
                  "id": "discoveryengine.projects.locations.dataStores.patch",
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "PATCH",
                  "path": "v1beta/{+name}",
                  "description": "Updates a DataStore"
                },
                "getSiteSearchEngine": {
                  "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.getSiteSearchEngine",
                  "description": "Gets the SiteSearchEngine.",
                  "httpMethod": "GET",
                  "path": "v1beta/{+name}"
                }
              },
              "resources": {
                "completionSuggestions": {
                  "methods": {
                    "import": {
                      "description": "Imports CompletionSuggestions for a DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.import",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                      "path": "v1beta/{+parent}/completionSuggestions:import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST"
                    },
                    "purge": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                      "path": "v1beta/{+parent}/completionSuggestions:purge",
                      "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.purge",
                      "httpMethod": "POST"
                    }
                  }
                },
                "schemas": {
                  "methods": {
                    "list": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.list",
                      "description": "Gets a list of Schemas.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "path": "v1beta/{+parent}/schemas"
                    },
                    "delete": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "httpMethod": "DELETE",
                      "path": "v1beta/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.schemas.delete",
                      "description": "Deletes a Schema."
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.patch",
                      "httpMethod": "PATCH",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "description": "Updates a Schema."
                    },
                    "create": {
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+parent}/schemas",
                      "description": "Creates a Schema.",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.create",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas"
                    },
                    "get": {
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.get",
                      "description": "Gets a Schema.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "path": "v1beta/{+name}"
                    }
                  }
                },
                "conversations": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.conversations.list",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "description": "Lists all Conversations by their parent DataStore.",
                      "httpMethod": "GET",
                      "path": "v1beta/{+parent}/conversations"
                    },
                    "delete": {
                      "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "DELETE",
                      "path": "v1beta/{+name}",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.delete"
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.patch",
                      "path": "v1beta/{+name}",
                      "httpMethod": "PATCH",
                      "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned."
                    },
                    "get": {
                      "path": "v1beta/{+name}",
                      "description": "Gets a Conversation.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.get",
                      "httpMethod": "GET"
                    },
                    "create": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.conversations.create",
                      "path": "v1beta/{+parent}/conversations",
                      "httpMethod": "POST"
                    },
                    "converse": {
                      "description": "Converses a conversation.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+name}:converse",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.converse",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                      "httpMethod": "POST"
                    }
                  }
                },
                "completionConfig": {
                  "methods": {
                    "completeQuery": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                      "id": "discoveryengine.projects.locations.dataStores.completionConfig.completeQuery",
                      "path": "v1beta/{+completionConfig}:completeQuery",
                      "description": "Completes the user input with advanced keyword suggestions.",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud_search.query",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "sessions": {
                  "resources": {
                    "answers": {
                      "methods": {
                        "get": {
                          "id": "discoveryengine.projects.locations.dataStores.sessions.answers.get",
                          "description": "Gets a Answer.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}"
                        }
                      }
                    }
                  },
                  "methods": {
                    "patch": {
                      "id": "discoveryengine.projects.locations.dataStores.sessions.patch",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                      "path": "v1beta/{+name}"
                    },
                    "list": {
                      "path": "v1beta/{+parent}/sessions",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "description": "Lists all Sessions by their parent DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.sessions.list",
                      "httpMethod": "GET"
                    },
                    "get": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.get",
                      "description": "Gets a Session.",
                      "path": "v1beta/{+name}"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "path": "v1beta/{+parent}/sessions",
                      "httpMethod": "POST",
                      "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.create"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.delete",
                      "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+name}"
                    }
                  }
                },
                "userEvents": {
                  "methods": {
                    "collect": {
                      "path": "v1beta/{+parent}/userEvents:collect",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:collect",
                      "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.collect",
                      "httpMethod": "GET"
                    },
                    "purge": {
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.purge",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:purge",
                      "path": "v1beta/{+parent}/userEvents:purge"
                    },
                    "write": {
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:write",
                      "path": "v1beta/{+parent}/userEvents:write",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Writes a single user event.",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.write"
                    },
                    "import": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:import",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+parent}/userEvents:import",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.import",
                      "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata."
                    }
                  }
                },
                "servingConfigs": {
                  "methods": {
                    "searchLite": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+servingConfig}:searchLite",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.searchLite",
                      "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, it i[...]",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                      "httpMethod": "POST"
                    },
                    "answer": {
                      "description": "Answer query method.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.answer",
                      "httpMethod": "POST",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                      "path": "v1beta/{+servingConfig}:answer"
                    },
                    "create": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.create",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "path": "v1beta/{+parent}/servingConfigs",
                      "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST"
                    },
                    "search": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.search",
                      "path": "v1beta/{+servingConfig}:search",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                      "description": "Performs a search.",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "delete": {
                      "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.delete",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+name}"
                    },
                    "recommend": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.recommend",
                      "path": "v1beta/{+servingConfig}:recommend",
                      "description": "Makes a recommendation, which requires a contextual user event.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "get": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.get",
                      "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1beta/{+name}"
                    },
                    "list": {
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "path": "v1beta/{+parent}/servingConfigs",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "description": "Lists all ServingConfigs linked to this dataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.list"
                    },
                    "streamAnswer": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.streamAnswer",
                      "path": "v1beta/{+servingConfig}:streamAnswer",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                      "httpMethod": "POST"
                    },
                    "patch": {
                      "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "PATCH",
                      "path": "v1beta/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.patch"
                    }
                  }
                },
                "branches": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "path": "v1beta/{+name}/operations",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.list"
                        },
                        "cancel": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.cancel",
                          "path": "v1beta/{+name}:cancel",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instea[...]",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "get": {
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1beta/{+name}",
                          "httpMethod": "GET"
                        }
                      }
                    },
                    "documents": {
                      "methods": {
                        "patch": {
                          "description": "Updates a Document.",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "httpMethod": "PATCH",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.patch",
                          "path": "v1beta/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "purge": {
                          "path": "v1beta/{+parent}/documents:purge",
                          "flatPath": "v1beta/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                          "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                          "httpMethod": "POST",
                          "scopes": [
[...]
