{
  "batchPath": "batch",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        },
        "https://www.googleapis.com/auth/discoveryengine.readwrite": {
          "description": "View, edit, create, and delete all your data associated with any Discovery Engine API product, such as Agentspace, Vertex AI Search, or NotebookLM Enterprise, including both end user data and administration or configuration data."
        },
        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite": {
          "description": "View your Agentspace chat history, including uploaded files and generated reports and visualizations, and interact with the Agentspace assistant on your behalf."
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        }
      }
    }
  },
  "version_module": true,
  "mtlsRootUrl": "https://discoveryengine.mtls.googleapis.com/",
  "revision": "20260310",
  "fullyEncodeReservedExpansion": true,
  "documentationLink": "https://cloud.google.com/generative-ai-app-builder/docs/",
  "discoveryVersion": "v1",
  "title": "Discovery Engine API",
  "baseUrl": "https://discoveryengine.googleapis.com/",
  "ownerDomain": "google.com",
  "name": "discoveryengine",
  "basePath": "",
  "kind": "discovery#restDescription",
  "id": "discoveryengine:v1",
  "version": "v1",
  "resources": {
    "projects": {
      "resources": {
        "operations": {
          "methods": {
            "cancel": {
              "id": "discoveryengine.projects.operations.cancel",
              "flatPath": "v1/projects/{projectsId}/operations/{operationsId}:cancel",
              "path": "v1/{+name}:cancel",
              "httpMethod": "POST",
              "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it become[...]",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ]
            },
            "list": {
              "id": "discoveryengine.projects.operations.list",
              "path": "v1/{+name}/operations",
              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ],
              "flatPath": "v1/projects/{projectsId}/operations"
            },
            "get": {
              "id": "discoveryengine.projects.operations.get",
              "httpMethod": "GET",
              "flatPath": "v1/projects/{projectsId}/operations/{operationsId}",
              "path": "v1/{+name}",
              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite"
              ]
            }
          }
        },
        "locations": {
          "resources": {
            "cmekConfigs": {
              "methods": {
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1/{+name}",
                  "id": "discoveryengine.projects.locations.cmekConfigs.delete",
                  "description": "De-provisions a CmekConfig.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "description": "Lists all the CmekConfigs with the project.",
                  "id": "discoveryengine.projects.locations.cmekConfigs.list",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/cmekConfigs",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1/{+parent}/cmekConfigs",
                  "httpMethod": "GET"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "path": "v1/{+name}",
                  "id": "discoveryengine.projects.locations.cmekConfigs.patch",
                  "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1/{+name}",
                  "id": "discoveryengine.projects.locations.cmekConfigs.get",
                  "description": "Gets the CmekConfig.",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}"
                }
              }
            },
            "dataStores": {
              "methods": {
                "delete": {
                  "description": "Deletes a DataStore.",
                  "id": "discoveryengine.projects.locations.dataStores.delete",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1/{+name}"
                },
                "list": {
                  "httpMethod": "GET",
                  "description": "Lists all the DataStores associated with the project.",
                  "path": "v1/{+parent}/dataStores",
                  "id": "discoveryengine.projects.locations.dataStores.list",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.patch",
                  "path": "v1/{+name}",
                  "description": "Updates a DataStore",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}"
                },
                "get": {
                  "description": "Gets a DataStore.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.get",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "path": "v1/{+name}",
                  "httpMethod": "GET"
                },
                "completeQuery": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:completeQuery",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.dataStores.completeQuery",
                  "path": "v1/{+dataStore}:completeQuery",
                  "description": "Completes the specified user input with keyword suggestions."
                },
                "getSiteSearchEngine": {
                  "path": "v1/{+name}",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Gets the SiteSearchEngine.",
                  "id": "discoveryengine.projects.locations.dataStores.getSiteSearchEngine",
                  "httpMethod": "GET"
                },
                "create": {
                  "httpMethod": "POST",
                  "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                  "path": "v1/{+parent}/dataStores",
                  "id": "discoveryengine.projects.locations.dataStores.create",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                }
              },
              "resources": {
                "userEvents": {
                  "methods": {
                    "write": {
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:write",
                      "path": "v1/{+parent}/userEvents:write",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.write",
                      "description": "Writes a single user event.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "purge": {
                      "httpMethod": "POST",
                      "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+parent}/userEvents:purge",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.purge"
                    },
                    "import": {
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+parent}/userEvents:import",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:import",
                      "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                      "httpMethod": "POST"
                    },
                    "collect": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:collect",
                      "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.collect",
                      "path": "v1/{+parent}/userEvents:collect",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "suggestionDenyListEntries": {
                  "methods": {
                    "purge": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+parent}/suggestionDenyListEntries:purge",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.purge",
                      "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge"
                    },
                    "import": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+parent}/suggestionDenyListEntries:import",
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.import",
                      "description": "Imports all SuggestionDenyListEntry for a DataStore."
                    }
                  }
                },
                "sessions": {
                  "methods": {
                    "patch": {
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.sessions.patch",
                      "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "path": "v1/{+name}"
                    },
                    "create": {
                      "path": "v1/{+parent}/sessions",
                      "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.create"
                    },
                    "delete": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+name}",
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.delete"
                    },
                    "list": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.list",
                      "httpMethod": "GET",
                      "path": "v1/{+parent}/sessions",
                      "description": "Lists all Sessions by their parent DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "get": {
                      "description": "Gets a Session.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "path": "v1/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.get",
                      "httpMethod": "GET"
                    }
                  },
                  "resources": {
                    "answers": {
                      "methods": {
                        "get": {
                          "httpMethod": "GET",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                          "id": "discoveryengine.projects.locations.dataStores.sessions.answers.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a Answer.",
                          "path": "v1/{+name}"
                        }
                      }
                    }
                  }
                },
                "branches": {
                  "methods": {
                    "batchGetDocumentsMetadata": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                      "id": "discoveryengine.projects.locations.dataStores.branches.batchGetDocumentsMetadata",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                      "path": "v1/{+parent}/batchGetDocumentsMetadata"
                    }
                  },
                  "resources": {
                    "documents": {
                      "methods": {
                        "create": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.create",
                          "description": "Creates a Document.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "path": "v1/{+parent}/documents",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST"
                        },
                        "import": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                          "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated.",
                          "path": "v1/{+parent}/documents:import",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.import"
                        },
                        "delete": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.delete",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1/{+name}",
                          "httpMethod": "DELETE",
                          "description": "Deletes a Document."
                        },
                        "purge": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.purge",
                          "path": "v1/{+parent}/documents:purge",
                          "httpMethod": "POST"
                        },
                        "get": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "path": "v1/{+name}",
                          "description": "Gets a Document.",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.get"
                        },
                        "list": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "path": "v1/{+parent}/documents",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.list",
                          "description": "Gets a list of Documents."
                        },
                        "patch": {
                          "description": "Updates a Document.",
                          "httpMethod": "PATCH",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.patch",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "operations": {
                      "methods": {
                        "get": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.get",
                          "path": "v1/{+name}",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}"
                        },
                        "cancel": {
                          "path": "v1/{+name}:cancel",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.cancel",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                          "httpMethod": "POST",
                          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instea[...]"
                        },
                        "list": {
                          "httpMethod": "GET",
                          "path": "v1/{+name}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.list"
                        }
                      }
                    }
                  }
                },
                "servingConfigs": {
                  "methods": {
                    "streamAnswer": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.streamAnswer",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+servingConfig}:streamAnswer",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                      "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream."
                    },
                    "delete": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.delete",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "DELETE",
                      "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "path": "v1/{+name}"
                    },
                    "create": {
                      "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.create",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "path": "v1/{+parent}/servingConfigs",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST"
                    },
                    "recommend": {
                      "description": "Makes a recommendation, which requires a contextual user event.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.recommend",
                      "path": "v1/{+servingConfig}:recommend",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                      "httpMethod": "POST"
                    },
                    "search": {
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Performs a search.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                      "path": "v1/{+servingConfig}:search",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.search"
                    },
                    "patch": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.patch",
                      "path": "v1/{+name}",
                      "httpMethod": "PATCH",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist."
                    },
                    "get": {
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.get",
                      "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "answer": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST",
                      "description": "Answer query method.",
                      "path": "v1/{+servingConfig}:answer",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.answer"
                    },
                    "searchLite": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.searchLite",
                      "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, it i[...]",
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                      "path": "v1/{+servingConfig}:searchLite"
                    },
                    "list": {
                      "description": "Lists all ServingConfigs linked to this dataStore.",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+parent}/servingConfigs"
                    }
                  }
                },
                "models": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "get": {
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.get",
                          "path": "v1/{+name}",
                          "httpMethod": "GET",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}"
                        },
                        "list": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations",
                          "path": "v1/{+name}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET"
                        }
                      }
                    }
                  }
                },
                "completionSuggestions": {
                  "methods": {
                    "import": {
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.import",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Imports CompletionSuggestions for a DataStore.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                      "path": "v1/{+parent}/completionSuggestions:import",
                      "httpMethod": "POST"
                    },
                    "purge": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.purge",
                      "path": "v1/{+parent}/completionSuggestions:purge",
                      "httpMethod": "POST",
                      "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:purge"
                    }
                  }
                },
                "controls": {
                  "methods": {
                    "get": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets a Control.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.get",
                      "path": "v1/{+name}",
                      "httpMethod": "GET"
                    },
                    "patch": {
                      "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                      "path": "v1/{+name}",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.controls.patch",
                      "httpMethod": "PATCH"
                    },
                    "delete": {
                      "path": "v1/{+name}",
                      "id": "discoveryengine.projects.locations.dataStores.controls.delete",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned."
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.create",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "httpMethod": "POST",
                      "path": "v1/{+parent}/controls"
                    },
                    "list": {
                      "description": "Lists all Controls by their parent DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.list",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+parent}/controls"
                    }
                  }
                },
                "schemas": {
                  "methods": {
                    "create": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.create",
                      "path": "v1/{+parent}/schemas",
                      "httpMethod": "POST",
                      "description": "Creates a Schema.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "delete": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.delete",
                      "description": "Deletes a Schema.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+name}"
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+name}",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "description": "Gets a Schema."
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets a list of Schemas.",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.list",
                      "httpMethod": "GET",
                      "path": "v1/{+parent}/schemas",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas"
                    },
                    "patch": {
                      "path": "v1/{+name}",
                      "httpMethod": "PATCH",
                      "description": "Updates a Schema.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.operations.get",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations/{operationsId}",
                      "httpMethod": "GET",
                      "path": "v1/{+name}"
                    },
                    "list": {
                      "path": "v1/{+name}/operations",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.operations.list",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "httpMethod": "GET"
                    }
                  }
                },
                "widgetConfigs": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.get",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                      "description": "Gets a WidgetConfig.",
                      "httpMethod": "GET",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "description": "Update a WidgetConfig.",
                      "path": "v1/{+name}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.patch",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}"
                    }
                  }
                },
                "completionConfig": {
                  "methods": {
                    "completeQuery": {
                      "description": "Completes the user input with advanced keyword suggestions.",
                      "id": "discoveryengine.projects.locations.dataStores.completionConfig.completeQuery",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud_search.query",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+completionConfig}:completeQuery"
                    }
                  }
                },
                "siteSearchEngine": {
                  "resources": {
                    "targetSites": {
                      "methods": {
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a TargetSite.",
                          "path": "v1/{+name}",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.get",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "httpMethod": "GET"
                        },
                        "delete": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "path": "v1/{+name}",
                          "description": "Deletes a TargetSite.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.delete"
                        },
                        "list": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "description": "Gets a list of TargetSites.",
                          "path": "v1/{+parent}/targetSites",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.list"
                        },
                        "patch": {
                          "description": "Updates a TargetSite.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.patch",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}"
                        },
                        "batchCreate": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "description": "Creates TargetSite in a batch.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                          "path": "v1/{+parent}/targetSites:batchCreate",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.batchCreate"
                        },
                        "create": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "path": "v1/{+parent}/targetSites",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.create",
                          "description": "Creates a TargetSite.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "sitemaps": {
                      "methods": {
                        "delete": {
                          "path": "v1/{+name}",
                          "description": "Deletes a Sitemap.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.delete",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}",
                          "httpMethod": "DELETE"
                        },
                        "create": {
                          "path": "v1/{+parent}/sitemaps",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps",
                          "description": "Creates a Sitemap.",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.create"
                        },
                        "fetch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1/{+parent}/sitemaps:fetch",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.fetch",
                          "description": "Fetch Sitemaps in a DataStore.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch"
                        }
                      }
                    }
                  },
                  "methods": {
                    "enableAdvancedSiteSearch": {
                      "httpMethod": "POST",
                      "description": "Upgrade from basic site search to advanced site search.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.enableAdvancedSiteSearch",
                      "path": "v1/{+siteSearchEngine}:enableAdvancedSiteSearch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "recrawlUris": {
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.recrawlUris",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                      "path": "v1/{+siteSearchEngine}:recrawlUris",
                      "description": "Request on-demand recrawl for a list of URIs.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    },
                    "disableAdvancedSiteSearch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Downgrade from advanced site search to basic site search.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.disableAdvancedSiteSearch",
                      "path": "v1/{+siteSearchEngine}:disableAdvancedSiteSearch",
                      "httpMethod": "POST"
                    }
                  }
                },
                "conversations": {
                  "methods": {
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.conversations.list",
                      "description": "Lists all Conversations by their parent DataStore.",
                      "httpMethod": "GET",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+parent}/conversations"
                    },
                    "delete": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.conversations.delete",
                      "httpMethod": "DELETE",
                      "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                      "path": "v1/{+name}"
                    },
                    "patch": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.patch",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "PATCH",
                      "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                      "path": "v1/{+name}"
                    },
                    "create": {
                      "path": "v1/{+parent}/conversations",
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.dataStores.conversations.create",
                      "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned."
                    },
                    "converse": {
                      "httpMethod": "POST",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+name}:converse",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.converse",
                      "description": "Converses a conversation."
                    },
                    "get": {
                      "path": "v1/{+name}",
                      "description": "Gets a Conversation.",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.get",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}"
                    }
                  }
                }
              }
            },
            "operations": {
              "methods": {
                "list": {
                  "id": "discoveryengine.projects.locations.operations.list",
                  "path": "v1/{+name}/operations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations",
                  "httpMethod": "GET"
                },
                "get": {
                  "path": "v1/{+name}",
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "id": "discoveryengine.projects.locations.operations.get"
                }
              }
            },
            "rankingConfigs": {
              "methods": {
                "rank": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Ranks a list of text records based on the given input query.",
                  "path": "v1/{+rankingConfig}:rank",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/rankingConfigs/{rankingConfigsId}:rank",
                  "id": "discoveryengine.projects.locations.rankingConfigs.rank"
                }
              }
            },
            "podcasts": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "path": "v1/{+name}",
                      "id": "discoveryengine.projects.locations.podcasts.operations.get",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/podcasts/{podcastsId}/operations/{operationsId}",
                      "httpMethod": "GET",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                }
              }
            },
            "groundingConfigs": {
              "methods": {
                "check": {
                  "path": "v1/{+groundingConfig}:check",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Performs a grounding check.",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.groundingConfigs.check",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/groundingConfigs/{groundingConfigsId}:check"
                }
              }
            },
            "userEvents": {
              "methods": {
                "collect": {
                  "path": "v1/{+parent}/userEvents:collect",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/userEvents:collect",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.userEvents.collect",
                  "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "write": {
                  "path": "v1/{+parent}/userEvents:write",
                  "id": "discoveryengine.projects.locations.userEvents.write",
                  "httpMethod": "POST",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/userEvents:write",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Writes a single user event."
                },
                "import": {
                  "httpMethod": "POST",
                  "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                  "id": "discoveryengine.projects.locations.userEvents.import",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/userEvents:import",
                  "path": "v1/{+parent}/userEvents:import",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                }
              }
            },
            "identityMappingStores": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations/{operationsId}",
                      "path": "v1/{+name}",
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.get",
                      "httpMethod": "GET"
                    },
                    "list": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations",
                      "httpMethod": "GET",
                      "path": "v1/{+name}/operations",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.list",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ]
                    }
                  }
                }
              },
              "methods": {
                "get": {
                  "description": "Gets the Identity Mapping Store.",
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "path": "v1/{+name}",
                  "id": "discoveryengine.projects.locations.identityMappingStores.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "list": {
                  "id": "discoveryengine.projects.locations.identityMappingStores.list",
                  "description": "Lists all Identity Mapping Stores.",
                  "path": "v1/{+parent}/identityMappingStores",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/identityMappingStores"
                },
                "listIdentityMappings": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:listIdentityMappings",
                  "httpMethod": "GET",
                  "path": "v1/{+identityMappingStore}:listIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Lists Identity Mappings in an Identity Mapping Store.",
                  "id": "discoveryengine.projects.locations.identityMappingStores.listIdentityMappings"
                },
                "delete": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "description": "Deletes the Identity Mapping Store.",
                  "httpMethod": "DELETE",
                  "id": "discoveryengine.projects.locations.identityMappingStores.delete",
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ]
                },
                "purgeIdentityMappings": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.purgeIdentityMappings",
                  "path": "v1/{+identityMappingStore}:purgeIdentityMappings",
                  "description": "Purges specified or all Identity Mapping Entries from an Identity Mapping Store.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:purgeIdentityMappings"
                },
                "create": {
                  "path": "v1/{+parent}/identityMappingStores",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.identityMappingStores.create",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "description": "Creates a new Identity Mapping Store."
                },
                "importIdentityMappings": {
                  "id": "discoveryengine.projects.locations.identityMappingStores.importIdentityMappings",
                  "description": "Imports a list of Identity Mapping Entries to an Identity Mapping Store.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:importIdentityMappings",
                  "path": "v1/{+identityMappingStore}:importIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "httpMethod": "POST"
                }
              }
            },
            "licenseConfigs": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.licenseConfigs.get",
                  "path": "v1/{+name}",
                  "description": "Gets a LicenseConfig.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}"
                },
                "create": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/licenseConfigs",
                  "description": "Creates a LicenseConfig This method should only be used for creating NotebookLm licenses or Gemini Enterprise free trial licenses.",
                  "path": "v1/{+parent}/licenseConfigs",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.licenseConfigs.create"
                },
                "patch": {
                  "path": "v1/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Updates the LicenseConfig",
                  "httpMethod": "PATCH",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}",
                  "id": "discoveryengine.projects.locations.licenseConfigs.patch"
                }
              }
            },
            "collections": {
              "methods": {
                "delete": {
                  "id": "discoveryengine.projects.locations.collections.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "description": "Deletes a Collection.",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}",
                  "path": "v1/{+name}"
                },
                "getDataConnector": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "id": "discoveryengine.projects.locations.collections.getDataConnector",
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector",
                  "path": "v1/{+name}",
                  "description": "Gets the DataConnector. DataConnector is a singleton resource for each Collection.",
                  "httpMethod": "GET"
                },
                "updateDataConnector": {
                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector",
                  "id": "discoveryengine.projects.locations.collections.updateDataConnector",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                  ],
                  "path": "v1/{+name}",
                  "description": "Updates a DataConnector."
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "path": "v1/{+name}",
                      "id": "discoveryengine.projects.locations.collections.operations.get",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/operations/{operationsId}",
                      "httpMethod": "GET"
                    },
                    "list": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/operations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.operations.list",
                      "path": "v1/{+name}/operations",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "httpMethod": "GET"
                    }
                  }
                },
                "dataConnector": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "get": {
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations/{operationsId}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.get",
                          "path": "v1/{+name}"
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.list",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations",
                          "path": "v1/{+name}/operations",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                        }
                      }
                    }
                  }
                },
                "dataStores": {
                  "resources": {
                    "models": {
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "path": "v1/{+name}/operations",
                              "httpMethod": "GET",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.list",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            },
                            "get": {
                              "httpMethod": "GET",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.models.operations.get",
                              "path": "v1/{+name}",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                            }
                          }
                        }
                      }
                    },
                    "completionSuggestions": {
                      "methods": {
                        "purge": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "description": "Permanently deletes all CompletionSuggestions for a DataStore.",
                          "path": "v1/{+parent}/completionSuggestions:purge",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.purge"
                        },
                        "import": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1/{+parent}/completionSuggestions:import",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.import",
                          "httpMethod": "POST",
                          "description": "Imports CompletionSuggestions for a DataStore.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:import"
                        }
                      }
                    },
                    "branches": {
                      "methods": {
                        "batchGetDocumentsMetadata": {
                          "path": "v1/{+parent}/batchGetDocumentsMetadata",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                          "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.batchGetDocumentsMetadata"
                        }
                      },
                      "resources": {
                        "documents": {
                          "methods": {
                            "list": {
                              "path": "v1/{+parent}/documents",
                              "description": "Gets a list of Documents.",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.list"
                            },
                            "patch": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1/{+name}",
                              "description": "Updates a Document.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.patch",
                              "httpMethod": "PATCH",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}"
                            },
                            "import": {
                              "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated.",
                              "httpMethod": "POST",
                              "path": "v1/{+parent}/documents:import",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.import"
                            },
                            "delete": {
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.delete",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Deletes a Document.",
                              "httpMethod": "DELETE",
                              "path": "v1/{+name}"
                            },
                            "get": {
                              "description": "Gets a Document.",
                              "httpMethod": "GET",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.get",
                              "path": "v1/{+name}"
                            },
                            "create": {
                              "description": "Creates a Document.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.create",
                              "httpMethod": "POST",
                              "path": "v1/{+parent}/documents",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            },
                            "purge": {
                              "httpMethod": "POST",
                              "path": "v1/{+parent}/documents:purge",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.purge",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge"
                            }
                          }
                        },
                        "operations": {
                          "methods": {
                            "list": {
                              "path": "v1/{+name}/operations",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.list"
                            },
                            "get": {
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.get",
                              "path": "v1/{+name}",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                            },
                            "cancel": {
                              "httpMethod": "POST",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.cancel",
                              "path": "v1/{+name}:cancel",
                              "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; in[...]"
                            }
                          }
                        }
                      }
                    },
                    "siteSearchEngine": {
                      "methods": {
                        "recrawlUris": {
                          "path": "v1/{+siteSearchEngine}:recrawlUris",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.recrawlUris",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Request on-demand recrawl for a list of URIs."
                        },
                        "batchVerifyTargetSites": {
                          "description": "Verify target sites' ownership and validity. This API sends all the target sites under site search engine for verification.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.batchVerifyTargetSites",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:batchVerifyTargetSites",
                          "path": "v1/{+parent}:batchVerifyTargetSites",
                          "httpMethod": "POST"
                        },
                        "enableAdvancedSiteSearch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.enableAdvancedSiteSearch",
                          "path": "v1/{+siteSearchEngine}:enableAdvancedSiteSearch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch",
                          "description": "Upgrade from basic site search to advanced site search.",
                          "httpMethod": "POST"
                        },
                        "disableAdvancedSiteSearch": {
                          "path": "v1/{+siteSearchEngine}:disableAdvancedSiteSearch",
                          "httpMethod": "POST",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Downgrade from advanced site search to basic site search.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.disableAdvancedSiteSearch"
                        },
                        "fetchDomainVerificationStatus": {
                          "httpMethod": "GET",
                          "description": "Returns list of target sites with its domain verification status. This method can only be called under data store with BASIC_SITE_SEARCH state at the moment.",
                          "path": "v1/{+siteSearchEngine}:fetchDomainVerificationStatus",
                          "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.fetchDomainVerificationStatus",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine:fetchDomainVerificationStatus"
                        }
                      },
                      "resources": {
                        "operations": {
                          "methods": {
                            "get": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.operations.get",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/operations/{operationsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1/{+name}",
                              "httpMethod": "GET"
                            },
                            "list": {
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.operations.list",
                              "httpMethod": "GET",
                              "path": "v1/{+name}/operations",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/operations",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            }
                          }
                        },
                        "sitemaps": {
                          "methods": {
                            "delete": {
                              "path": "v1/{+name}",
                              "description": "Deletes a Sitemap.",
                              "httpMethod": "DELETE",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.delete"
                            },
                            "create": {
                              "httpMethod": "POST",
                              "description": "Creates a Sitemap.",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps",
                              "path": "v1/{+parent}/sitemaps",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.create"
                            },
                            "fetch": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                              "description": "Fetch Sitemaps in a DataStore.",
                              "path": "v1/{+parent}/sitemaps:fetch",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.sitemaps.fetch",
                              "httpMethod": "GET"
                            }
                          }
                        },
                        "targetSites": {
                          "resources": {
                            "operations": {
                              "methods": {
                                "list": {
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.list",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                                  "path": "v1/{+name}/operations",
                                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations",
                                  "httpMethod": "GET"
                                },
                                "get": {
                                  "path": "v1/{+name}",
                                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/operations/{operationsId}",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "httpMethod": "GET",
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                                  "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.operations.get"
                                }
                              }
                            }
                          },
                          "methods": {
                            "get": {
                              "path": "v1/{+name}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.get",
                              "description": "Gets a TargetSite.",
                              "httpMethod": "GET"
                            },
                            "create": {
                              "httpMethod": "POST",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.create",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "description": "Creates a TargetSite.",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                              "path": "v1/{+parent}/targetSites"
                            },
                            "batchCreate": {
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                              "path": "v1/{+parent}/targetSites:batchCreate",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "POST",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.batchCreate",
                              "description": "Creates TargetSite in a batch."
                            },
                            "delete": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.delete",
                              "description": "Deletes a TargetSite.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "DELETE",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "path": "v1/{+name}"
                            },
                            "list": {
                              "path": "v1/{+parent}/targetSites",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.list",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                              "description": "Gets a list of TargetSites."
                            },
                            "patch": {
                              "description": "Updates a TargetSite.",
                              "path": "v1/{+name}",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.siteSearchEngine.targetSites.patch",
                              "httpMethod": "PATCH",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            }
                          }
                        }
                      }
                    },
                    "suggestionDenyListEntries": {
                      "methods": {
                        "purge": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "path": "v1/{+parent}/suggestionDenyListEntries:purge",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.purge",
                          "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore."
                        },
                        "import": {
                          "path": "v1/{+parent}/suggestionDenyListEntries:import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.import",
                          "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                          "httpMethod": "POST"
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "patch": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.patch",
                          "httpMethod": "PATCH",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "get": {
                          "description": "Gets a Conversation.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.get",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1/{+name}",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}"
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.create",
                          "path": "v1/{+parent}/conversations",
                          "httpMethod": "POST",
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned."
                        },
                        "converse": {
                          "path": "v1/{+name}:converse",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "description": "Converses a conversation.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.converse",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse"
                        },
                        "delete": {
                          "httpMethod": "DELETE",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.delete",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned."
                        },
                        "list": {
                          "path": "v1/{+parent}/conversations",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "description": "Lists all Conversations by their parent DataStore.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations"
                        }
                      }
                    },
                    "sessions": {
                      "methods": {
                        "delete": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "DELETE",
                          "path": "v1/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.delete"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.get",
                          "description": "Gets a Session.",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "httpMethod": "GET"
                        },
                        "create": {
                          "httpMethod": "POST",
                          "path": "v1/{+parent}/sessions",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.create",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "list": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Lists all Sessions by their parent DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.list",
                          "path": "v1/{+parent}/sessions",
                          "httpMethod": "GET"
                        },
                        "patch": {
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "path": "v1/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.patch",
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned."
                        }
                      },
                      "resources": {
                        "answers": {
                          "methods": {
                            "get": {
                              "description": "Gets a Answer.",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                              "path": "v1/{+name}",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.sessions.answers.get",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ]
                            }
                          }
                        }
                      }
                    },
                    "servingConfigs": {
                      "methods": {
                        "answer": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.answer",
                          "httpMethod": "POST",
                          "path": "v1/{+servingConfig}:answer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Answer query method.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer"
                        },
                        "streamAnswer": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.streamAnswer",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "path": "v1/{+servingConfig}:streamAnswer",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream."
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.patch",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "httpMethod": "PATCH",
                          "path": "v1/{+name}"
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.create",
                          "path": "v1/{+parent}/servingConfigs",
                          "httpMethod": "POST",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "get": {
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.get",
                          "path": "v1/{+name}"
                        },
                        "search": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1/{+servingConfig}:search",
                          "description": "Performs a search.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.search"
                        },
                        "searchLite": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "path": "v1/{+servingConfig}:searchLite",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.searchLite"
                        },
                        "list": {
                          "path": "v1/{+parent}/servingConfigs",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.list",
                          "httpMethod": "GET",
                          "description": "Lists all ServingConfigs linked to this dataStore."
                        },
                        "recommend": {
                          "path": "v1/{+servingConfig}:recommend",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.recommend",
                          "description": "Makes a recommendation, which requires a contextual user event."
                        },
                        "delete": {
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "httpMethod": "DELETE",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.delete",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "widgetConfigs": {
                      "methods": {
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                          "path": "v1/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.widgetConfigs.get",
                          "httpMethod": "GET",
                          "description": "Gets a WidgetConfig."
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.widgetConfigs.patch",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "description": "Update a WidgetConfig."
                        }
                      }
                    },
                    "schemas": {
                      "methods": {
                        "get": {
                          "path": "v1/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "httpMethod": "GET",
                          "description": "Gets a Schema."
                        },
                        "create": {
                          "description": "Creates a Schema.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "path": "v1/{+parent}/schemas",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.create"
                        },
                        "patch": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Updates a Schema.",
                          "httpMethod": "PATCH",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.patch"
                        },
                        "list": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "description": "Gets a list of Schemas.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1/{+parent}/schemas",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.list",
                          "httpMethod": "GET"
                        },
                        "delete": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "description": "Deletes a Schema.",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.delete",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      },
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.list",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "path": "v1/{+name}/operations",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                            },
                            "get": {
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}/operations/{operationsId}",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.schemas.operations.get",
                              "path": "v1/{+name}"
                            }
                          }
                        }
                      }
                    },
                    "userEvents": {
                      "methods": {
                        "write": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:write",
                          "description": "Writes a single user event.",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.write",
                          "path": "v1/{+parent}/userEvents:write",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "collect": {
                          "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.collect",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:collect",
                          "path": "v1/{+parent}/userEvents:collect",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET"
                        },
                        "purge": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.purge",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:purge",
                          "path": "v1/{+parent}/userEvents:purge",
                          "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST"
                        },
                        "import": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.userEvents.import",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/userEvents:import",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1/{+parent}/userEvents:import",
                          "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                          "httpMethod": "POST"
                        }
                      }
                    },
                    "operations": {
                      "methods": {
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.get",
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "path": "v1/{+name}",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations/{operationsId}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "list": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/operations",
                          "httpMethod": "GET",
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "path": "v1/{+name}/operations",
                          "id": "discoveryengine.projects.locations.collections.dataStores.operations.list",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "customModels": {
                      "methods": {
                        "list": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/customModels",
                          "path": "v1/{+dataStore}/customModels",
                          "id": "discoveryengine.projects.locations.collections.dataStores.customModels.list",
                          "httpMethod": "GET",
                          "description": "Gets a list of all the custom models.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "completionConfig": {
                      "methods": {
                        "completeQuery": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionConfig.completeQuery",
                          "path": "v1/{+completionConfig}:completeQuery",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud_search.query",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Completes the user input with advanced keyword suggestions."
                        }
                      }
                    },
                    "controls": {
                      "methods": {
                        "delete": {
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.delete",
                          "httpMethod": "DELETE",
                          "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned."
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.list",
                          "httpMethod": "GET",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "path": "v1/{+parent}/controls",
                          "description": "Lists all Controls by their parent DataStore."
                        },
                        "create": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls",
                          "path": "v1/{+parent}/controls",
                          "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.create",
                          "httpMethod": "POST"
                        },
                        "get": {
                          "description": "Gets a Control.",
                          "path": "v1/{+name}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.get",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "httpMethod": "GET"
                        },
                        "patch": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                          "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.controls.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "path": "v1/{+name}"
                        }
                      }
                    }
                  },
                  "methods": {
                    "create": {
                      "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+parent}/dataStores",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores",
                      "id": "discoveryengine.projects.locations.collections.dataStores.create",
                      "httpMethod": "POST"
                    },
                    "get": {
                      "description": "Gets a DataStore.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.get",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+name}",
                      "httpMethod": "GET"
                    },
                    "delete": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "DELETE",
                      "path": "v1/{+name}",
                      "description": "Deletes a DataStore.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.delete"
                    },
                    "getSiteSearchEngine": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/siteSearchEngine",
                      "path": "v1/{+name}",
                      "description": "Gets the SiteSearchEngine.",
                      "id": "discoveryengine.projects.locations.collections.dataStores.getSiteSearchEngine",
                      "httpMethod": "GET"
                    },
                    "completeQuery": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:completeQuery",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+dataStore}:completeQuery",
                      "id": "discoveryengine.projects.locations.collections.dataStores.completeQuery",
                      "description": "Completes the specified user input with keyword suggestions.",
                      "httpMethod": "GET"
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "description": "Updates a DataStore",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+name}",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}",
                      "id": "discoveryengine.projects.locations.collections.dataStores.patch"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores",
                      "description": "Lists all the DataStores associated with the project.",
                      "path": "v1/{+parent}/dataStores",
                      "id": "discoveryengine.projects.locations.collections.dataStores.list"
                    },
                    "trainCustomModel": {
                      "id": "discoveryengine.projects.locations.collections.dataStores.trainCustomModel",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "description": "Trains a custom model.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}:trainCustomModel",
                      "path": "v1/{+dataStore}:trainCustomModel"
                    }
                  }
                },
                "engines": {
                  "methods": {
                    "create": {
                      "description": "Creates an Engine.",
                      "id": "discoveryengine.projects.locations.collections.engines.create",
                      "path": "v1/{+parent}/engines",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines",
                      "httpMethod": "POST"
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "id": "discoveryengine.projects.locations.collections.engines.patch",
                      "description": "Updates an Engine",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "path": "v1/{+name}"
                    },
                    "getIamPolicy": {
                      "description": "Gets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. An empty policy is returned if the resource exists but does not have a policy set on it.",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:getIamPolicy",
                      "id": "discoveryengine.projects.locations.collections.engines.getIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "GET",
                      "path": "v1/{+resource}:getIamPolicy"
                    },
                    "get": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+name}",
                      "id": "discoveryengine.projects.locations.collections.engines.get",
                      "description": "Gets an Engine.",
                      "httpMethod": "GET"
                    },
                    "setIamPolicy": {
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}:setIamPolicy",
                      "description": "Sets the IAM access control policy for an Engine. A `NOT_FOUND` error is returned if the resource does not exist. **Important:** When setting a policy directly on an Engine resource, the only recommended roles in the bindings are: `roles/discoveryengine.user` and `roles/discoveryengine.agentspaceUser`. Attempting to grant any other role will result in a warning in logging.",
                      "id": "discoveryengine.projects.locations.collections.engines.setIamPolicy",
                      "path": "v1/{+resource}:setIamPolicy",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "POST"
                    },
                    "delete": {
                      "path": "v1/{+name}",
                      "id": "discoveryengine.projects.locations.collections.engines.delete",
                      "description": "Deletes an Engine.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "httpMethod": "DELETE",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}"
                    },
                    "list": {
                      "description": "Lists all the Engines associated with the project.",
                      "id": "discoveryengine.projects.locations.collections.engines.list",
                      "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite"
                      ],
                      "path": "v1/{+parent}/engines",
                      "httpMethod": "GET"
                    }
                  },
                  "resources": {
                    "sessions": {
                      "methods": {
                        "patch": {
                          "path": "v1/{+name}",
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.patch",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}"
                        },
                        "delete": {
                          "httpMethod": "DELETE",
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.delete",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}",
                          "path": "v1/{+name}"
                        },
                        "get": {
                          "path": "v1/{+name}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.get",
                          "description": "Gets a Session.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}"
                        },
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "POST",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions",
                          "path": "v1/{+parent}/sessions",
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.create",
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned."
                        },
                        "list": {
                          "path": "v1/{+parent}/sessions",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.sessions.list",
                          "description": "Lists all Sessions by their parent DataStore.",
                          "httpMethod": "GET",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions"
                        }
                      },
                      "resources": {
                        "answers": {
                          "methods": {
                            "get": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite"
                              ],
                              "id": "discoveryengine.projects.locations.collections.engines.sessions.answers.get",
                              "httpMethod": "GET",
                              "path": "v1/{+name}",
                              "description": "Gets a Answer.",
                              "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/sessions/{sessionsId}/answers/{answersId}"
                            }
                          }
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "patch": {
                          "path": "v1/{+name}",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.patch",
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}"
                        },
                        "create": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.create",
                          "httpMethod": "POST",
                          "path": "v1/{+parent}/conversations",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned."
                        },
                        "get": {
                          "httpMethod": "GET",
                          "description": "Gets a Conversation.",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.get",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}"
                        },
                        "delete": {
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.delete",
                          "httpMethod": "DELETE",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}",
                          "path": "v1/{+name}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Lists all Conversations by their parent DataStore.",
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.list",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations",
                          "httpMethod": "GET",
                          "path": "v1/{+parent}/conversations"
                        },
                        "converse": {
                          "id": "discoveryengine.projects.locations.collections.engines.conversations.converse",
                          "description": "Converses a conversation.",
                          "path": "v1/{+name}:converse",
                          "httpMethod": "POST",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/conversations/{conversationsId}:converse",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        }
                      }
                    },
                    "assistants": {
                      "methods": {
                        "list": {
                          "httpMethod": "GET",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1/{+parent}/assistants",
                          "description": "Lists all Assistants under an Engine.",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.list"
                        },
                        "delete": {
                          "path": "v1/{+name}",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.delete",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "description": "Deletes an Assistant."
                        },
                        "streamAssist": {
                          "description": "Assists the user with a query in a streaming fashion.",
                          "httpMethod": "POST",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}:streamAssist",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1/{+name}:streamAssist",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.streamAssist"
                        },
                        "create": {
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.create",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1/{+parent}/assistants",
                          "description": "Creates an Assistant.",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants"
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "path": "v1/{+name}",
                          "httpMethod": "PATCH",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}",
                          "description": "Updates an Assistant"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.engines.assistants.get",
                          "path": "v1/{+name}",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ],
                          "httpMethod": "GET",
                          "description": "Gets an Assistant."
                        }
                      },
                      "resources": {
                        "agents": {
                          "methods": {
                            "getCard": {
                              "flatPath": "projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/card",
                              "path": "{+tenant}/card",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform"
                              ],
                              "description": "GetAgentCard returns the agent card for the agent.",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.getCard"
                            }
                          },
                          "resources": {
                            "message": {
                              "methods": {
                                "send": {
                                  "flatPath": "projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/message:send",
                                  "path": "{+tenant}/message:send",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform"
                                  ],
                                  "description": "Send a message to the agent. This is a blocking call that will return the task once it is completed, or a LRO if requested.",
                                  "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.message.send",
                                  "httpMethod": "POST"
                                },
                                "stream": {
                                  "path": "{+tenant}/message:stream",
                                  "flatPath": "projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/message:stream",
                                  "description": "SendStreamingMessage is a streaming call that will return a stream of task update events until the Task is in an interrupted or terminal state.",
                                  "httpMethod": "POST",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform"
                                  ],
                                  "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.message.stream"
                                }
                              }
                            },
                            "tasks": {
                              "methods": {
                                "subscribe": {
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform"
                                  ],
                                  "httpMethod": "GET",
                                  "flatPath": "projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/tasks/{tasksId}:subscribe",
                                  "path": "{+tenant}/{+name}:subscribe",
                                  "description": "TaskSubscription is a streaming call that will return a stream of task update events. This attaches the stream to an existing in process task. If the task is complete the stream will return the completed task (like GetTask) and close the stream.",
                                  "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.tasks.subscribe"
                                },
                                "cancel": {
                                  "path": "{+tenant}/{+name}:cancel",
                                  "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.tasks.cancel",
                                  "description": "Cancel a task from the agent. If supported one should expect no more task updates for the task.",
                                  "flatPath": "projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/tasks/{tasksId}:cancel",
                                  "httpMethod": "POST",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform"
                                  ]
                                },
                                "get": {
                                  "description": "Get the current state of a task from the agent.",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform"
                                  ],
                                  "flatPath": "projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/tasks/{tasksId}",
                                  "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.tasks.get",
                                  "path": "{+tenant}/{+name}",
                                  "httpMethod": "GET"
                                }
                              },
                              "resources": {
                                "pushNotificationConfigs": {
                                  "methods": {
                                    "create": {
                                      "path": "{+tenant}/{+parent}",
                                      "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.tasks.pushNotificationConfigs.create",
                                      "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform"
                                      ],
                                      "description": "Set a push notification config for a task.",
                                      "flatPath": "projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/tasks/{tasksId}/pushNotificationConfigs",
                                      "httpMethod": "POST"
                                    },
                                    "list": {
                                      "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform"
                                      ],
                                      "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.tasks.pushNotificationConfigs.list",
                                      "flatPath": "projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/tasks/{tasksId}/pushNotificationConfigs",
                                      "description": "Get a list of push notifications configured for a task.",
                                      "path": "{+tenant}/{+parent}/pushNotificationConfigs",
                                      "httpMethod": "GET"
                                    },
                                    "get": {
                                      "path": "{+tenant}/{+name}",
                                      "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform"
                                      ],
                                      "description": "Get a push notification config for a task.",
                                      "flatPath": "projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/tasks/{tasksId}/pushNotificationConfigs/{pushNotificationConfigsId}",
                                      "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.tasks.pushNotificationConfigs.get",
                                      "httpMethod": "GET"
                                    },
                                    "delete": {
                                      "flatPath": "projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/tasks/{tasksId}/pushNotificationConfigs/{pushNotificationConfigsId}",
                                      "scopes": [
                                        "https://www.googleapis.com/auth/cloud-platform"
                                      ],
                                      "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.tasks.pushNotificationConfigs.delete",
                                      "path": "{+tenant}/{+name}",
                                      "httpMethod": "DELETE",
                                      "description": "Delete a push notification config for a task."
                                    }
                                  }
                                }
                              }
                            },
                            "operations": {
                              "methods": {
                                "get": {
                                  "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/assistants/{assistantsId}/agents/{agentsId}/operations/{operationsId}",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite"
                                  ],
                                  "httpMethod": "GET",
                                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                                  "id": "discoveryengine.projects.locations.collections.engines.assistants.agents.operations.get",
                                  "path": "v1/{+name}"
                                }
                              }
                            }
                          }
                        }
                      }
                    },
                    "widgetConfigs": {
                      "methods": {
                        "patch": {
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/widgetConfigs/{widgetConfigsId}",
                          "httpMethod": "PATCH",
                          "description": "Update a WidgetConfig.",
                          "path": "v1/{+name}",
                          "id": "discoveryengine.projects.locations.collections.engines.widgetConfigs.patch",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite"
                          ]
                        },
                        "get": {
                          "description": "Gets a WidgetConfig.",
                          "path": "v1/{+name}",
                          "flatPath": "v1/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/engines/{enginesId}/widgetConfigs/{widgetConfigsId}",
                          "scopes": [
[...]
