{
  "ownerDomain": "google.com",
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "description": "Discovery Engine API.",
  "baseUrl": "https://discoveryengine.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite": {
          "description": "View your Agentspace chat history, including uploaded files and generated reports and visualizations, and interact with the Agentspace assistant on your behalf."
        },
        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite": {
          "description": "Interact with Discovery Engine API products, such as Agentspace, Vertex AI Search, or NotebookLM Enterprise, on your behalf. It will also allow the app to view all data that you have access to when you use or interact with a Discovery Engine API product."
        },
        "https://www.googleapis.com/auth/discoveryengine.readwrite": {
          "description": "View, edit, create, and delete all your data associated with any Discovery Engine API product, such as Agentspace, Vertex AI Search, or NotebookLM Enterprise, including both end user data and administration or configuration data."
        },
        "https://www.googleapis.com/auth/cloud-platform": {
          "description": "See, edit, configure, and delete your Google Cloud data and see the email address for your Google Account."
        },
        "https://www.googleapis.com/auth/cloud_search.query": {
          "description": "Search your organization's data in the Cloud Search index"
        }
      }
    }
  },
  "rootUrl": "https://discoveryengine.googleapis.com/",
  "discoveryVersion": "v1",
  "documentationLink": "https://cloud.google.com/generative-ai-app-builder/docs/",
  "version": "v1alpha",
  "version_module": true,
  "canonicalName": "Discovery Engine",
  "basePath": "",
  "id": "discoveryengine:v1alpha",
  "protocol": "rest",
  "title": "Discovery Engine API",
  "servicePath": "",
  "fullyEncodeReservedExpansion": true,
  "mtlsRootUrl": "https://discoveryengine.mtls.googleapis.com/",
  "resources": {
    "billingAccounts": {
      "resources": {
        "billingAccountLicenseConfigs": {
          "methods": {
            "retractLicenseConfig": {
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}:retractLicenseConfig",
              "httpMethod": "POST",
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.retractLicenseConfig",
              "path": "v1alpha/{+billingAccountLicenseConfig}:retractLicenseConfig",
              "description": "This method is called from the billing account side to retract the LicenseConfig from the given project back to the billing account.",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "description": "Lists all BillingAccountLicenseConfigs for a given billing account.",
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.list",
              "path": "v1alpha/{+parent}/billingAccountLicenseConfigs",
              "httpMethod": "GET",
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs"
            },
            "distributeLicenseConfig": {
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.distributeLicenseConfig",
              "path": "v1alpha/{+billingAccountLicenseConfig}:distributeLicenseConfig",
              "httpMethod": "POST",
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}:distributeLicenseConfig",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "description": "Distributes a LicenseConfig from billing account level to project level."
            },
            "get": {
              "id": "discoveryengine.billingAccounts.billingAccountLicenseConfigs.get",
              "path": "v1alpha/{+name}",
              "httpMethod": "GET",
              "flatPath": "v1alpha/billingAccounts/{billingAccountsId}/billingAccountLicenseConfigs/{billingAccountLicenseConfigsId}",
              "scopes": [
                "https://www.googleapis.com/auth/cloud-platform",
                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
              ],
              "description": "Gets a BillingAccountLicenseConfig."
            }
          }
        }
      }
    },
    "projects": {
      "resources": {
        "locations": {
          "resources": {
            "userStores": {
              "methods": {
                "batchUpdateUserLicenses": {
                  "id": "discoveryengine.projects.locations.userStores.batchUpdateUserLicenses",
                  "path": "v1alpha/{+parent}:batchUpdateUserLicenses",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}:batchUpdateUserLicenses",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Updates the User License. This method is used for batch assign/unassign licenses to users."
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets the User Store.",
                  "id": "discoveryengine.projects.locations.userStores.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}"
                },
                "patch": {
                  "id": "discoveryengine.projects.locations.userStores.patch",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Updates the User Store."
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/operations/{operationsId}",
                      "id": "discoveryengine.projects.locations.userStores.operations.get",
                      "path": "v1alpha/{+name}"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/operations",
                      "id": "discoveryengine.projects.locations.userStores.operations.list",
                      "path": "v1alpha/{+name}/operations",
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                },
                "userLicenses": {
                  "methods": {
                    "list": {
                      "id": "discoveryengine.projects.locations.userStores.userLicenses.list",
                      "path": "v1alpha/{+parent}/userLicenses",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/userLicenses",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists the User Licenses."
                    }
                  }
                },
                "licenseConfigsUsageStats": {
                  "methods": {
                    "list": {
                      "id": "discoveryengine.projects.locations.userStores.licenseConfigsUsageStats.list",
                      "path": "v1alpha/{+parent}/licenseConfigsUsageStats",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userStores/{userStoresId}/licenseConfigsUsageStats",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists all the LicenseConfigUsageStatss associated with the project."
                    }
                  }
                }
              }
            },
            "groundingConfigs": {
              "methods": {
                "check": {
                  "id": "discoveryengine.projects.locations.groundingConfigs.check",
                  "path": "v1alpha/{+groundingConfig}:check",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/groundingConfigs/{groundingConfigsId}:check",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Performs a grounding check."
                }
              }
            },
            "podcasts": {
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.podcasts.operations.get",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/podcasts/{podcastsId}/operations/{operationsId}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                    }
                  }
                }
              }
            },
            "rankingConfigs": {
              "methods": {
                "rank": {
                  "description": "Ranks a list of text records based on the given input query.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/rankingConfigs/{rankingConfigsId}:rank",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.rankingConfigs.rank",
                  "path": "v1alpha/{+rankingConfig}:rank"
                }
              }
            },
            "operations": {
              "methods": {
                "list": {
                  "id": "discoveryengine.projects.locations.operations.list",
                  "path": "v1alpha/{+name}/operations",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
                },
                "get": {
                  "id": "discoveryengine.projects.locations.operations.get",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/operations/{operationsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                }
              }
            },
            "authorizations": {
              "methods": {
                "create": {
                  "id": "discoveryengine.projects.locations.authorizations.create",
                  "path": "v1alpha/{+parent}/authorizations",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Creates an Authorization."
                },
                "delete": {
                  "description": "Deletes an Authorization.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "id": "discoveryengine.projects.locations.authorizations.delete",
                  "path": "v1alpha/{+name}"
                },
                "list": {
                  "id": "discoveryengine.projects.locations.authorizations.list",
                  "path": "v1alpha/{+parent}/authorizations",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Lists all Authorizations under an Engine."
                },
                "patch": {
                  "description": "Updates an Authorization",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.authorizations.patch",
                  "path": "v1alpha/{+name}"
                },
                "get": {
                  "id": "discoveryengine.projects.locations.authorizations.get",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/authorizations/{authorizationsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets an Authorization."
                }
              }
            },
            "evaluations": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Creates a Evaluation. Upon creation, the evaluation will be automatically triggered and begin execution.",
                  "id": "discoveryengine.projects.locations.evaluations.create",
                  "path": "v1alpha/{+parent}/evaluations",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations",
                  "httpMethod": "POST"
                },
                "listResults": {
                  "id": "discoveryengine.projects.locations.evaluations.listResults",
                  "path": "v1alpha/{+evaluation}:listResults",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}:listResults",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a list of results for a given a Evaluation."
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a list of Evaluations.",
                  "id": "discoveryengine.projects.locations.evaluations.list",
                  "path": "v1alpha/{+parent}/evaluations",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a Evaluation.",
                  "id": "discoveryengine.projects.locations.evaluations.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}"
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/evaluations/{evaluationsId}/operations/{operationsId}",
                      "id": "discoveryengine.projects.locations.evaluations.operations.get",
                      "path": "v1alpha/{+name}"
                    }
                  }
                }
              }
            },
            "identityMappingStores": {
              "methods": {
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "id": "discoveryengine.projects.locations.identityMappingStores.create",
                  "path": "v1alpha/{+parent}/identityMappingStores",
                  "description": "Creates a new Identity Mapping Store.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "listIdentityMappings": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Lists Identity Mappings in an Identity Mapping Store.",
                  "id": "discoveryengine.projects.locations.identityMappingStores.listIdentityMappings",
                  "path": "v1alpha/{+identityMappingStore}:listIdentityMappings",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:listIdentityMappings",
                  "httpMethod": "GET"
                },
                "get": {
                  "id": "discoveryengine.projects.locations.identityMappingStores.get",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets the Identity Mapping Store."
                },
                "purgeIdentityMappings": {
                  "id": "discoveryengine.projects.locations.identityMappingStores.purgeIdentityMappings",
                  "path": "v1alpha/{+identityMappingStore}:purgeIdentityMappings",
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:purgeIdentityMappings",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Purges specified or all Identity Mapping Entries from an Identity Mapping Store."
                },
                "delete": {
                  "description": "Deletes the Identity Mapping Store.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}",
                  "id": "discoveryengine.projects.locations.identityMappingStores.delete",
                  "path": "v1alpha/{+name}"
                },
                "importIdentityMappings": {
                  "id": "discoveryengine.projects.locations.identityMappingStores.importIdentityMappings",
                  "path": "v1alpha/{+identityMappingStore}:importIdentityMappings",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}:importIdentityMappings",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Imports a list of Identity Mapping Entries to an Identity Mapping Store."
                },
                "list": {
                  "description": "Lists all Identity Mapping Stores.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.identityMappingStores.list",
                  "path": "v1alpha/{+parent}/identityMappingStores"
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.list",
                      "path": "v1alpha/{+name}/operations",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations",
                      "httpMethod": "GET"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "id": "discoveryengine.projects.locations.identityMappingStores.operations.get",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/identityMappingStores/{identityMappingStoresId}/operations/{operationsId}",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            },
            "sampleQuerySets": {
              "methods": {
                "create": {
                  "id": "discoveryengine.projects.locations.sampleQuerySets.create",
                  "path": "v1alpha/{+parent}/sampleQuerySets",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Creates a SampleQuerySet"
                },
                "list": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.list",
                  "path": "v1alpha/{+parent}/sampleQuerySets",
                  "description": "Gets a list of SampleQuerySets.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Deletes a SampleQuerySet.",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.delete",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}"
                },
                "get": {
                  "id": "discoveryengine.projects.locations.sampleQuerySets.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a SampleQuerySet."
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Updates a SampleQuerySet.",
                  "id": "discoveryengine.projects.locations.sampleQuerySets.patch",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}"
                }
              },
              "resources": {
                "operations": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.sampleQuerySets.operations.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/operations/{operationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                    }
                  }
                },
                "sampleQueries": {
                  "methods": {
                    "get": {
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.get",
                      "path": "v1alpha/{+name}",
                      "description": "Gets a SampleQuery.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "patch": {
                      "description": "Updates a SampleQuery.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "httpMethod": "PATCH",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.patch",
                      "path": "v1alpha/{+name}"
                    },
                    "list": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.list",
                      "path": "v1alpha/{+parent}/sampleQueries",
                      "description": "Gets a list of SampleQuerys.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a SampleQuery.",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.delete",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries/{sampleQueriesId}",
                      "httpMethod": "DELETE"
                    },
                    "create": {
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.create",
                      "path": "v1alpha/{+parent}/sampleQueries",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a SampleQuery"
                    },
                    "import": {
                      "description": "Bulk import of multiple SampleQuerys. Sample queries that already exist may be deleted. Note: It is possible for a subset of the SampleQuerys to be successfully imported.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/sampleQuerySets/{sampleQuerySetsId}/sampleQueries:import",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.sampleQuerySets.sampleQueries.import",
                      "path": "v1alpha/{+parent}/sampleQueries:import"
                    }
                  }
                }
              }
            },
            "userEvents": {
              "methods": {
                "collect": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:collect",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.userEvents.collect",
                  "path": "v1alpha/{+parent}/userEvents:collect",
                  "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "import": {
                  "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:import",
                  "id": "discoveryengine.projects.locations.userEvents.import",
                  "path": "v1alpha/{+parent}/userEvents:import"
                },
                "write": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/userEvents:write",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.userEvents.write",
                  "path": "v1alpha/{+parent}/userEvents:write",
                  "description": "Writes a single user event.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                }
              }
            },
            "cmekConfigs": {
              "methods": {
                "list": {
                  "description": "Lists all the CmekConfigs with the project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.cmekConfigs.list",
                  "path": "v1alpha/{+parent}/cmekConfigs"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "id": "discoveryengine.projects.locations.cmekConfigs.delete",
                  "path": "v1alpha/{+name}",
                  "description": "De-provisions a CmekConfig.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "patch": {
                  "id": "discoveryengine.projects.locations.cmekConfigs.patch",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Provisions a CMEK key for use in a location of a customer's project. This method will also conduct location validation on the provided cmekConfig to make sure the key is valid and can be used in the selected location."
                },
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/cmekConfigs/{cmekConfigsId}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.cmekConfigs.get",
                  "path": "v1alpha/{+name}",
                  "description": "Gets the CmekConfig.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                }
              }
            },
            "dataStores": {
              "resources": {
                "conversations": {
                  "methods": {
                    "converse": {
                      "id": "discoveryengine.projects.locations.dataStores.conversations.converse",
                      "path": "v1alpha/{+name}:converse",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Converses a conversation."
                    },
                    "create": {
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.create",
                      "path": "v1alpha/{+parent}/conversations",
                      "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "delete": {
                      "id": "discoveryengine.projects.locations.dataStores.conversations.delete",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned."
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.conversations.list",
                      "path": "v1alpha/{+parent}/conversations",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists all Conversations by their parent DataStore."
                    },
                    "patch": {
                      "httpMethod": "PATCH",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.patch",
                      "path": "v1alpha/{+name}",
                      "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "get": {
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                      "id": "discoveryengine.projects.locations.dataStores.conversations.get",
                      "path": "v1alpha/{+name}",
                      "description": "Gets a Conversation.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                },
                "servingConfigs": {
                  "methods": {
                    "answer": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.answer",
                      "path": "v1alpha/{+servingConfig}:answer",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Answer query method."
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.create",
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "httpMethod": "POST"
                    },
                    "recommend": {
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.recommend",
                      "path": "v1alpha/{+servingConfig}:recommend",
                      "description": "Makes a recommendation, which requires a contextual user event.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "streamAnswer": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.streamAnswer",
                      "path": "v1alpha/{+servingConfig}:streamAnswer",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream."
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.delete",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.list",
                      "path": "v1alpha/{+parent}/servingConfigs",
                      "description": "Lists all ServingConfigs linked to this dataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "patch": {
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.patch",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist."
                    },
                    "search": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Performs a search.",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.search",
                      "path": "v1alpha/{+servingConfig}:search",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                      "httpMethod": "POST"
                    },
                    "searchLite": {
                      "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, it i[...]",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.searchLite",
                      "path": "v1alpha/{+servingConfig}:searchLite"
                    },
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.servingConfigs.get",
                      "path": "v1alpha/{+name}",
                      "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                },
                "sessions": {
                  "resources": {
                    "answers": {
                      "methods": {
                        "get": {
                          "description": "Gets a Answer.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                          "id": "discoveryengine.projects.locations.dataStores.sessions.answers.get",
                          "path": "v1alpha/{+name}"
                        }
                      }
                    }
                  },
                  "methods": {
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.create",
                      "path": "v1alpha/{+parent}/sessions",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions"
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.patch",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}"
                    },
                    "get": {
                      "description": "Gets a Session.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.get",
                      "path": "v1alpha/{+name}"
                    },
                    "delete": {
                      "id": "discoveryengine.projects.locations.dataStores.sessions.delete",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned."
                    },
                    "list": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/sessions",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.sessions.list",
                      "path": "v1alpha/{+parent}/sessions",
                      "description": "Lists all Sessions by their parent DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                },
                "completionConfig": {
                  "methods": {
                    "completeQuery": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/cloud_search.query",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Completes the user input with advanced keyword suggestions.",
                      "id": "discoveryengine.projects.locations.dataStores.completionConfig.completeQuery",
                      "path": "v1alpha/{+completionConfig}:completeQuery",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionConfig:completeQuery"
                    }
                  }
                },
                "operations": {
                  "methods": {
                    "get": {
                      "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations/{operationsId}",
                      "id": "discoveryengine.projects.locations.dataStores.operations.get",
                      "path": "v1alpha/{+name}"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                      "id": "discoveryengine.projects.locations.dataStores.operations.list",
                      "path": "v1alpha/{+name}/operations",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/operations"
                    }
                  }
                },
                "siteSearchEngine": {
                  "methods": {
                    "recrawlUris": {
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.recrawlUris",
                      "path": "v1alpha/{+siteSearchEngine}:recrawlUris",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:recrawlUris",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Request on-demand recrawl for a list of URIs."
                    },
                    "enableAdvancedSiteSearch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Upgrade from basic site search to advanced site search.",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.enableAdvancedSiteSearch",
                      "path": "v1alpha/{+siteSearchEngine}:enableAdvancedSiteSearch",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:enableAdvancedSiteSearch",
                      "httpMethod": "POST"
                    },
                    "disableAdvancedSiteSearch": {
                      "description": "Downgrade from advanced site search to basic site search.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine:disableAdvancedSiteSearch",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.disableAdvancedSiteSearch",
                      "path": "v1alpha/{+siteSearchEngine}:disableAdvancedSiteSearch"
                    }
                  },
                  "resources": {
                    "targetSites": {
                      "methods": {
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates a TargetSite.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.create",
                          "path": "v1alpha/{+parent}/targetSites",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites"
                        },
                        "batchCreate": {
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites:batchCreate",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.batchCreate",
                          "path": "v1alpha/{+parent}/targetSites:batchCreate",
                          "description": "Creates TargetSite in a batch.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "get": {
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.get",
                          "path": "v1alpha/{+name}",
                          "description": "Gets a TargetSite.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "patch": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "httpMethod": "PATCH",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.patch",
                          "path": "v1alpha/{+name}",
                          "description": "Updates a TargetSite.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a TargetSite.",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.delete",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites/{targetSitesId}",
                          "httpMethod": "DELETE"
                        },
                        "list": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.targetSites.list",
                          "path": "v1alpha/{+parent}/targetSites",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/targetSites",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a list of TargetSites."
                        }
                      }
                    },
                    "sitemaps": {
                      "methods": {
                        "delete": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.delete",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps/{sitemapsId}",
                          "httpMethod": "DELETE",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a Sitemap."
                        },
                        "create": {
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps",
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.create",
                          "path": "v1alpha/{+parent}/sitemaps",
                          "description": "Creates a Sitemap.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "fetch": {
                          "id": "discoveryengine.projects.locations.dataStores.siteSearchEngine.sitemaps.fetch",
                          "path": "v1alpha/{+parent}/sitemaps:fetch",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine/sitemaps:fetch",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Fetch Sitemaps in a DataStore."
                        }
                      }
                    }
                  }
                },
                "widgetConfigs": {
                  "methods": {
                    "get": {
                      "description": "Gets a WidgetConfig.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.get",
                      "path": "v1alpha/{+name}"
                    },
                    "patch": {
                      "id": "discoveryengine.projects.locations.dataStores.widgetConfigs.patch",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/widgetConfigs/{widgetConfigsId}",
                      "httpMethod": "PATCH",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Update a WidgetConfig."
                    }
                  }
                },
                "models": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.list",
                          "path": "v1alpha/{+name}/operations",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations",
                          "httpMethod": "GET"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.dataStores.models.operations.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/models/{modelsId}/operations/{operationsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
                        }
                      }
                    }
                  }
                },
                "controls": {
                  "methods": {
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deletes a Control. If the Control to delete does not exist, a NOT_FOUND error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.delete",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "DELETE",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}"
                    },
                    "list": {
                      "id": "discoveryengine.projects.locations.dataStores.controls.list",
                      "path": "v1alpha/{+parent}/controls",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists all Controls by their parent DataStore."
                    },
                    "patch": {
                      "id": "discoveryengine.projects.locations.dataStores.controls.patch",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates a Control. Control action type cannot be changed. If the Control to update does not exist, a NOT_FOUND error is returned."
                    },
                    "get": {
                      "id": "discoveryengine.projects.locations.dataStores.controls.get",
                      "path": "v1alpha/{+name}",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls/{controlsId}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a Control."
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a Control. By default 1000 controls are allowed for a data store. A request can be submitted to adjust this limit. If the Control to create already exists, an ALREADY_EXISTS error is returned.",
                      "id": "discoveryengine.projects.locations.dataStores.controls.create",
                      "path": "v1alpha/{+parent}/controls",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/controls",
                      "httpMethod": "POST"
                    }
                  }
                },
                "userEvents": {
                  "methods": {
                    "write": {
                      "description": "Writes a single user event.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:write",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.write",
                      "path": "v1alpha/{+parent}/userEvents:write"
                    },
                    "purge": {
                      "description": "Deletes permanently all user events specified by the filter provided. Depending on the number of events specified by the filter, this operation could take hours or days to complete. To test a filter, use the list command first.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:purge",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.purge",
                      "path": "v1alpha/{+parent}/userEvents:purge"
                    },
                    "collect": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Writes a single user event from the browser. This uses a GET request to due to browser restriction of POST-ing to a third-party domain. This method is used only by the Discovery Engine API JavaScript pixel and Google Tag Manager. Users should not call this method directly.",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.collect",
                      "path": "v1alpha/{+parent}/userEvents:collect",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:collect"
                    },
                    "import": {
                      "description": "Bulk import of user events. Request processing might be synchronous. Events that already exist are skipped. Use this method for backfilling historical user events. Operation.response is of type ImportResponse. Note that it is possible for a subset of the items to be successfully inserted. Operation.metadata is of type ImportMetadata.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/userEvents:import",
                      "id": "discoveryengine.projects.locations.dataStores.userEvents.import",
                      "path": "v1alpha/{+parent}/userEvents:import"
                    }
                  }
                },
                "suggestionDenyListEntries": {
                  "methods": {
                    "import": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.import",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:import",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                      "httpMethod": "POST"
                    },
                    "purge": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.suggestionDenyListEntries.purge",
                      "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge",
                      "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                },
                "schemas": {
                  "methods": {
                    "create": {
                      "id": "discoveryengine.projects.locations.dataStores.schemas.create",
                      "path": "v1alpha/{+parent}/schemas",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a Schema."
                    },
                    "get": {
                      "description": "Gets a Schema.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.get",
                      "path": "v1alpha/{+name}"
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Updates a Schema.",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.patch",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "PATCH",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a list of Schemas.",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.list",
                      "path": "v1alpha/{+parent}/schemas",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas"
                    },
                    "delete": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                      "httpMethod": "DELETE",
                      "id": "discoveryengine.projects.locations.dataStores.schemas.delete",
                      "path": "v1alpha/{+name}",
                      "description": "Deletes a Schema.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                },
                "branches": {
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.list",
                          "path": "v1alpha/{+name}/operations",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                          "httpMethod": "GET"
                        },
                        "get": {
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.get",
                          "path": "v1alpha/{+name}"
                        },
                        "cancel": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instea[...]",
                          "id": "discoveryengine.projects.locations.dataStores.branches.operations.cancel",
                          "path": "v1alpha/{+name}:cancel",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel"
                        }
                      }
                    },
                    "documents": {
                      "resources": {
                        "chunks": {
                          "methods": {
                            "get": {
                              "httpMethod": "GET",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks/{chunksId}",
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.get",
                              "path": "v1alpha/{+name}",
                              "description": "Gets a Document.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            },
                            "list": {
                              "httpMethod": "GET",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks",
                              "id": "discoveryengine.projects.locations.dataStores.branches.documents.chunks.list",
                              "path": "v1alpha/{+parent}/chunks",
                              "description": "Gets a list of Chunks.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            }
                          }
                        }
                      },
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a list of Documents.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.list",
                          "path": "v1alpha/{+parent}/documents",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents"
                        },
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a Document.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.delete",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "httpMethod": "DELETE"
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.get",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a Document."
                        },
                        "patch": {
                          "description": "Updates a Document.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "httpMethod": "PATCH",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.patch",
                          "path": "v1alpha/{+name}"
                        },
                        "getProcessedDocument": {
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}:getProcessedDocument",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.getProcessedDocument",
                          "path": "v1alpha/{+name}:getProcessedDocument",
                          "description": "Gets the parsed layout information for a Document.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "create": {
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.create",
                          "path": "v1alpha/{+parent}/documents",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates a Document."
                        },
                        "import": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.import",
                          "path": "v1alpha/{+parent}/documents:import",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import"
                        },
                        "purge": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false.",
                          "id": "discoveryengine.projects.locations.dataStores.branches.documents.purge",
                          "path": "v1alpha/{+parent}/documents:purge",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                          "httpMethod": "POST"
                        }
                      }
                    }
                  },
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Lists all Branchs under the specified parent DataStore.",
                      "id": "discoveryengine.projects.locations.dataStores.branches.list",
                      "path": "v1alpha/{+parent}/branches",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches"
                    },
                    "get": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.branches.get",
                      "path": "v1alpha/{+name}",
                      "description": "Retrieves a Branch.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "batchGetDocumentsMetadata": {
                      "description": "Gets index freshness metadata for Documents. Supported for website search only.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                      "httpMethod": "GET",
                      "id": "discoveryengine.projects.locations.dataStores.branches.batchGetDocumentsMetadata",
                      "path": "v1alpha/{+parent}/batchGetDocumentsMetadata"
                    }
                  }
                },
                "completionSuggestions": {
                  "methods": {
                    "import": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.import",
                      "path": "v1alpha/{+parent}/completionSuggestions:import",
                      "description": "Imports CompletionSuggestions for a DataStore.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "purge": {
                      "id": "discoveryengine.projects.locations.dataStores.completionSuggestions.purge",
                      "path": "v1alpha/{+parent}/completionSuggestions:purge",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Permanently deletes all CompletionSuggestions for a DataStore."
                    }
                  }
                }
              },
              "methods": {
                "deletePatientFilter": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Deletes the entire patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter.",
                  "id": "discoveryengine.projects.locations.dataStores.deletePatientFilter",
                  "path": "v1alpha/{+dataStore}:deletePatientFilter",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:deletePatientFilter",
                  "httpMethod": "POST"
                },
                "addPatientFilter": {
                  "description": "Adds a group of patient IDs as a patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. The filter group must be a FHIR resource name of type Group, and the filter will be constructed from the direct members of the group which are Patient resources.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:addPatientFilter",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.dataStores.addPatientFilter",
                  "path": "v1alpha/{+dataStore}:addPatientFilter"
                },
                "completeQuery": {
                  "id": "discoveryengine.projects.locations.dataStores.completeQuery",
                  "path": "v1alpha/{+dataStore}:completeQuery",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:completeQuery",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Completes the specified user input with keyword suggestions."
                },
                "updateDocumentProcessingConfig": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Updates the DocumentProcessingConfig. DocumentProcessingConfig is a singleon resource of DataStore. It's empty when DataStore is created. The first call to this method will set up DocumentProcessingConfig.",
                  "id": "discoveryengine.projects.locations.dataStores.updateDocumentProcessingConfig",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig"
                },
                "create": {
                  "description": "Creates a DataStore. DataStore is for storing Documents. To serve these documents for Search, or Recommendation use case, an Engine needs to be created separately.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.dataStores.create",
                  "path": "v1alpha/{+parent}/dataStores"
                },
                "delete": {
                  "description": "Deletes a DataStore.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "httpMethod": "DELETE",
                  "id": "discoveryengine.projects.locations.dataStores.delete",
                  "path": "v1alpha/{+name}"
                },
                "patch": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.dataStores.patch",
                  "path": "v1alpha/{+name}",
                  "description": "Updates a DataStore",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "getDocumentProcessingConfig": {
                  "description": "Gets a DocumentProcessingConfig.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/documentProcessingConfig",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.dataStores.getDocumentProcessingConfig",
                  "path": "v1alpha/{+name}"
                },
                "get": {
                  "description": "Gets a DataStore.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.dataStores.get",
                  "path": "v1alpha/{+name}"
                },
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores",
                  "id": "discoveryengine.projects.locations.dataStores.list",
                  "path": "v1alpha/{+parent}/dataStores",
                  "description": "Lists all the DataStores associated with the project.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "getSiteSearchEngine": {
                  "id": "discoveryengine.projects.locations.dataStores.getSiteSearchEngine",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}/siteSearchEngine",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets the SiteSearchEngine."
                },
                "removePatientFilter": {
                  "description": "Removes a group of patient IDs from the patient filter for the data store. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the list of patient IDs to remove will be constructed from the direct member[...]",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:removePatientFilter",
                  "id": "discoveryengine.projects.locations.dataStores.removePatientFilter",
                  "path": "v1alpha/{+dataStore}:removePatientFilter"
                },
                "replacePatientFilter": {
                  "id": "discoveryengine.projects.locations.dataStores.replacePatientFilter",
                  "path": "v1alpha/{+dataStore}:replacePatientFilter",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/dataStores/{dataStoresId}:replacePatientFilter",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Replaces the patient filter for the data store. This method is essentially a combination of DeletePatientFilters and AddPatientFilter. Patient filters are empty by default when a data store is created, and are stored in a separate table. The data store must first be created, and must be a healthcare data store. This method will fail if the data store does not have a patient filter. The filter group must be a FHIR resource name of type Group, and the new filter w[...]"
                }
              }
            },
            "licenseConfigs": {
              "methods": {
                "patch": {
                  "httpMethod": "PATCH",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}",
                  "id": "discoveryengine.projects.locations.licenseConfigs.patch",
                  "path": "v1alpha/{+name}",
                  "description": "Updates the LicenseConfig",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a LicenseConfig.",
                  "id": "discoveryengine.projects.locations.licenseConfigs.get",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs/{licenseConfigsId}"
                },
                "create": {
                  "description": "Creates a LicenseConfig This method should only be used for creating NotebookLm licenses or Gemini Enterprise free trial licenses.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/licenseConfigs",
                  "id": "discoveryengine.projects.locations.licenseConfigs.create",
                  "path": "v1alpha/{+parent}/licenseConfigs"
                }
              }
            },
            "notebooks": {
              "methods": {
                "create": {
                  "description": "Creates a notebook.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.notebooks.create",
                  "path": "v1alpha/{+parent}/notebooks"
                },
                "batchDelete": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks:batchDelete",
                  "httpMethod": "POST",
                  "id": "discoveryengine.projects.locations.notebooks.batchDelete",
                  "path": "v1alpha/{+parent}/notebooks:batchDelete",
                  "description": "Batch deletes Notebooks.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "share": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Shares a notebook to other accounts.",
                  "id": "discoveryengine.projects.locations.notebooks.share",
                  "path": "v1alpha/{+name}:share",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}:share",
                  "httpMethod": "POST"
                },
                "get": {
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.notebooks.get",
                  "path": "v1alpha/{+name}",
                  "description": "Gets a notebook.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "listRecentlyViewed": {
                  "description": "Lists the notebooks ordered by last view time.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks:listRecentlyViewed",
                  "httpMethod": "GET",
                  "id": "discoveryengine.projects.locations.notebooks.listRecentlyViewed",
                  "path": "v1alpha/{+parent}/notebooks:listRecentlyViewed"
                }
              },
              "resources": {
                "audioOverviews": {
                  "methods": {
                    "delete": {
                      "description": "Deletes an audio overview.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "DELETE",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/audioOverviews/{audioOverviewsId}",
                      "id": "discoveryengine.projects.locations.notebooks.audioOverviews.delete",
                      "path": "v1alpha/{+name}"
                    },
                    "create": {
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/audioOverviews",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.notebooks.audioOverviews.create",
                      "path": "v1alpha/{+parent}/audioOverviews",
                      "description": "Generates a new audio overview.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    }
                  }
                },
                "sources": {
                  "methods": {
                    "get": {
                      "id": "discoveryengine.projects.locations.notebooks.sources.get",
                      "path": "v1alpha/{+name}",
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/sources/{sourcesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Gets a Source."
                    },
                    "batchDelete": {
                      "description": "Deletes multiple sources",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/sources:batchDelete",
                      "id": "discoveryengine.projects.locations.notebooks.sources.batchDelete",
                      "path": "v1alpha/{+parent}/sources:batchDelete"
                    },
                    "batchCreate": {
                      "id": "discoveryengine.projects.locations.notebooks.sources.batchCreate",
                      "path": "v1alpha/{+parent}/sources:batchCreate",
                      "httpMethod": "POST",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/notebooks/{notebooksId}/sources:batchCreate",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Creates a list of Sources."
                    }
                  }
                }
              }
            },
            "collections": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}",
                  "id": "discoveryengine.projects.locations.collections.get",
                  "path": "v1alpha/{+name}",
                  "description": "Gets a Collection.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ]
                },
                "patch": {
                  "id": "discoveryengine.projects.locations.collections.patch",
                  "path": "v1alpha/{+name}",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}",
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Updates a Collection."
                },
                "getDataConnector": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets the DataConnector. DataConnector is a singleton resource for each Collection.",
                  "id": "discoveryengine.projects.locations.collections.getDataConnector",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Gets a list of Collections.",
                  "id": "discoveryengine.projects.locations.collections.list",
                  "path": "v1alpha/{+parent}/collections",
                  "httpMethod": "GET",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "description": "Deletes a Collection.",
                  "id": "discoveryengine.projects.locations.collections.delete",
                  "path": "v1alpha/{+name}",
                  "httpMethod": "DELETE",
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}"
                },
                "updateDataConnector": {
                  "description": "Updates a DataConnector.",
                  "scopes": [
                    "https://www.googleapis.com/auth/cloud-platform",
                    "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                  ],
                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector",
                  "httpMethod": "PATCH",
                  "id": "discoveryengine.projects.locations.collections.updateDataConnector",
                  "path": "v1alpha/{+name}"
                }
              },
              "resources": {
                "dataConnector": {
                  "methods": {
                    "mcp": {
                      "httpMethod": "DELETE",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/mcp",
                      "id": "discoveryengine.projects.locations.collections.dataConnector.mcp",
                      "path": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/mcp",
                      "description": "ServeMcpDeleteRequest serves a MCP DELETE request.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ]
                    },
                    "acquireAccessToken": {
                      "description": "Uses the per-user refresh token minted with AcquireAndStoreRefreshToken to generate and return a new access token and its details. Takes the access token from cache if available. Rotates the stored refresh token if needed. Uses the end user identity to return the user specific access token. Does *not* return the credentials configured by the administrator. Used by action execution and UI.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:acquireAccessToken",
                      "httpMethod": "POST",
                      "id": "discoveryengine.projects.locations.collections.dataConnector.acquireAccessToken",
                      "path": "v1alpha/{+name}:acquireAccessToken"
                    },
                    "checkRefreshToken": {
                      "id": "discoveryengine.projects.locations.collections.dataConnector.checkRefreshToken",
                      "path": "v1alpha/{+name}:checkRefreshToken",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:checkRefreshToken",
                      "deprecated": true,
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Deprecated: Checks the existence of a refresh token for the EUC user for a given connection and returns its details. Use AcquireAccessToken instead and then check the validity of the returned token by asking the 3rd party system. There's no way to know for sure if a refresh token is valid without asking the 3rd party system."
                    },
                    "getConnectorSecret": {
                      "description": "Get the secret for the associated connector.",
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:getConnectorSecret",
                      "id": "discoveryengine.projects.locations.collections.dataConnector.getConnectorSecret",
                      "path": "v1alpha/{+name}:getConnectorSecret"
                    },
                    "startConnectorRun": {
                      "scopes": [
                        "https://www.googleapis.com/auth/cloud-platform",
                        "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.readwrite",
                        "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                      ],
                      "description": "Starts an immediate synchronization process for a DataConnector. Third Party Connector Users must specify which entities should be synced. FHIR Connectors must provide a timestamp to indicate the point in time from which data should be synced.",
                      "id": "discoveryengine.projects.locations.collections.dataConnector.startConnectorRun",
                      "path": "v1alpha/{+parent}:startConnectorRun",
                      "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector:startConnectorRun",
                      "httpMethod": "POST"
                    }
                  },
                  "resources": {
                    "operations": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.list",
                          "path": "v1alpha/{+name}/operations",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations",
                          "httpMethod": "GET"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.operations.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/operations/{operationsId}"
                        }
                      }
                    },
                    "connectorRuns": {
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists the ConnectorRuns of a DataConnector.",
                          "id": "discoveryengine.projects.locations.collections.dataConnector.connectorRuns.list",
                          "path": "v1alpha/{+parent}/connectorRuns",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataConnector/connectorRuns",
                          "httpMethod": "GET"
                        }
                      }
                    }
                  }
                },
                "dataStores": {
                  "resources": {
                    "sessions": {
                      "resources": {
                        "answers": {
                          "methods": {
                            "get": {
                              "description": "Gets a Answer.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "httpMethod": "GET",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}/answers/{answersId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.sessions.answers.get",
                              "path": "v1alpha/{+name}"
                            }
                          }
                        }
                      },
                      "methods": {
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a Session. If the Session to delete does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.delete",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "httpMethod": "DELETE"
                        },
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists all Sessions by their parent DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.list",
                          "path": "v1alpha/{+parent}/sessions",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "httpMethod": "GET"
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.patch",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a Session. Session action type cannot be changed. If the Session to update does not exist, a NOT_FOUND error is returned."
                        },
                        "get": {
                          "description": "Gets a Session.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions/{sessionsId}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.get",
                          "path": "v1alpha/{+name}"
                        },
                        "create": {
                          "description": "Creates a Session. If the Session to create already exists, an ALREADY_EXISTS error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/sessions",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.sessions.create",
                          "path": "v1alpha/{+parent}/sessions"
                        }
                      }
                    },
                    "completionConfig": {
                      "methods": {
                        "completeQuery": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionConfig:completeQuery",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionConfig.completeQuery",
                          "path": "v1alpha/{+completionConfig}:completeQuery",
                          "description": "Completes the user input with advanced keyword suggestions.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/cloud_search.query",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        }
                      }
                    },
                    "conversations": {
                      "methods": {
                        "delete": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Deletes a Conversation. If the Conversation to delete does not exist, a NOT_FOUND error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.delete",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "DELETE",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}"
                        },
                        "list": {
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.list",
                          "path": "v1alpha/{+parent}/conversations",
                          "description": "Lists all Conversations by their parent DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "patch": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.patch",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "httpMethod": "PATCH",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a Conversation. Conversation action type cannot be changed. If the Conversation to update does not exist, a NOT_FOUND error is returned."
                        },
                        "get": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a Conversation."
                        },
                        "converse": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Converses a conversation.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.converse",
                          "path": "v1alpha/{+name}:converse",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations/{conversationsId}:converse"
                        },
                        "create": {
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/conversations",
                          "id": "discoveryengine.projects.locations.collections.dataStores.conversations.create",
                          "path": "v1alpha/{+parent}/conversations",
                          "description": "Creates a Conversation. If the Conversation to create already exists, an ALREADY_EXISTS error is returned.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        }
                      }
                    },
                    "servingConfigs": {
                      "methods": {
                        "create": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Creates a ServingConfig. Note: The Google Cloud console works only with the default serving config. Additional ServingConfigs can be created and managed only via the API. A maximum of 100 ServingConfigs are allowed in an Engine, otherwise a RESOURCE_EXHAUSTED error is returned.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.create",
                          "path": "v1alpha/{+parent}/servingConfigs",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "httpMethod": "POST"
                        },
                        "answer": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:answer",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.answer",
                          "path": "v1alpha/{+servingConfig}:answer",
                          "description": "Answer query method.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "recommend": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.recommend",
                          "path": "v1alpha/{+servingConfig}:recommend",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:recommend",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Makes a recommendation, which requires a contextual user event."
                        },
                        "streamAnswer": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Answer query method (streaming). It takes one AnswerQueryRequest and returns multiple AnswerQueryResponse messages in a stream.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.streamAnswer",
                          "path": "v1alpha/{+servingConfig}:streamAnswer",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:streamAnswer",
                          "httpMethod": "POST"
                        },
                        "patch": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Updates a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.patch",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "PATCH",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}"
                        },
                        "delete": {
                          "httpMethod": "DELETE",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.delete",
                          "path": "v1alpha/{+name}",
                          "description": "Deletes a ServingConfig. Returns a NOT_FOUND error if the ServingConfig does not exist.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "list": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.list",
                          "path": "v1alpha/{+parent}/servingConfigs",
                          "description": "Lists all ServingConfigs linked to this dataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "search": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.search",
                          "path": "v1alpha/{+servingConfig}:search",
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:search",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Performs a search."
                        },
                        "searchLite": {
                          "description": "Performs a search. Similar to the SearchService.Search method, but a lite version that allows API key for authentication, where OAuth and IAM checks are not required. Only public website search is supported by this method. If data stores and engines not associated with public website search are specified, a `FAILED_PRECONDITION` error is returned. This method can be used for easy onboarding without having to implement an authentication backend. However, [...]",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}:searchLite",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.searchLite",
                          "path": "v1alpha/{+servingConfig}:searchLite"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a ServingConfig. Returns a NotFound error if the ServingConfig does not exist.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.servingConfigs.get",
                          "path": "v1alpha/{+name}",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/servingConfigs/{servingConfigsId}",
                          "httpMethod": "GET"
                        }
                      }
                    },
                    "customModels": {
                      "methods": {
                        "list": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/customModels",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.customModels.list",
                          "path": "v1alpha/{+dataStore}/customModels",
                          "description": "Gets a list of all the custom models.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        }
                      }
                    },
                    "completionSuggestions": {
                      "methods": {
                        "import": {
                          "httpMethod": "POST",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:import",
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.import",
                          "path": "v1alpha/{+parent}/completionSuggestions:import",
                          "description": "Imports CompletionSuggestions for a DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "purge": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.completionSuggestions.purge",
                          "path": "v1alpha/{+parent}/completionSuggestions:purge",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/completionSuggestions:purge",
                          "httpMethod": "POST",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Permanently deletes all CompletionSuggestions for a DataStore."
                        }
                      }
                    },
                    "branches": {
                      "resources": {
                        "operations": {
                          "methods": {
                            "cancel": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.cancel",
                              "path": "v1alpha/{+name}:cancel",
                              "httpMethod": "POST",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}:cancel",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; in[...]"
                            },
                            "get": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations/{operationsId}",
                              "httpMethod": "GET",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.get",
                              "path": "v1alpha/{+name}",
                              "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            },
                            "list": {
                              "httpMethod": "GET",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/operations",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.operations.list",
                              "path": "v1alpha/{+name}/operations",
                              "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            }
                          }
                        },
                        "documents": {
                          "methods": {
                            "create": {
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "httpMethod": "POST",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.create",
                              "path": "v1alpha/{+parent}/documents",
                              "description": "Creates a Document.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ]
                            },
                            "import": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.import",
                              "path": "v1alpha/{+parent}/documents:import",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:import",
                              "httpMethod": "POST",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Bulk import of multiple Documents. Request processing may be synchronous. Non-existing items are created. Note: It is possible for a subset of the Documents to be successfully updated."
                            },
                            "purge": {
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.purge",
                              "path": "v1alpha/{+parent}/documents:purge",
                              "httpMethod": "POST",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents:purge",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Permanently deletes all selected Documents in a branch. This process is asynchronous. Depending on the number of Documents to be deleted, this operation can take hours to complete. Before the delete operation completes, some Documents might still be returned by DocumentService.GetDocument or DocumentService.ListDocuments. To get a list of the Documents to be deleted, set PurgeDocumentsRequest.force to false."
                            },
                            "list": {
                              "description": "Gets a list of Documents.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "httpMethod": "GET",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.list",
                              "path": "v1alpha/{+parent}/documents"
                            },
                            "delete": {
                              "description": "Deletes a Document.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "httpMethod": "DELETE",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.delete",
                              "path": "v1alpha/{+name}"
                            },
                            "get": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets a Document.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.get",
                              "path": "v1alpha/{+name}",
                              "httpMethod": "GET",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}"
                            },
                            "patch": {
                              "description": "Updates a Document.",
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}",
                              "httpMethod": "PATCH",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.patch",
                              "path": "v1alpha/{+name}"
                            },
                            "getProcessedDocument": {
                              "scopes": [
                                "https://www.googleapis.com/auth/cloud-platform",
                                "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                              ],
                              "description": "Gets the parsed layout information for a Document.",
                              "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.getProcessedDocument",
                              "path": "v1alpha/{+name}:getProcessedDocument",
                              "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}:getProcessedDocument",
                              "httpMethod": "GET"
                            }
                          },
                          "resources": {
                            "chunks": {
                              "methods": {
                                "list": {
                                  "description": "Gets a list of Chunks.",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                                  ],
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks",
                                  "httpMethod": "GET",
                                  "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.chunks.list",
                                  "path": "v1alpha/{+parent}/chunks"
                                },
                                "get": {
                                  "id": "discoveryengine.projects.locations.collections.dataStores.branches.documents.chunks.get",
                                  "path": "v1alpha/{+name}",
                                  "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/documents/{documentsId}/chunks/{chunksId}",
                                  "httpMethod": "GET",
                                  "scopes": [
                                    "https://www.googleapis.com/auth/cloud-platform",
                                    "https://www.googleapis.com/auth/discoveryengine.readwrite",
                                    "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                                  ],
                                  "description": "Gets a Document."
                                }
                              }
                            }
                          }
                        }
                      },
                      "methods": {
                        "list": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Lists all Branchs under the specified parent DataStore.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.list",
                          "path": "v1alpha/{+parent}/branches",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches",
                          "httpMethod": "GET"
                        },
                        "get": {
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Retrieves a Branch.",
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.get",
                          "path": "v1alpha/{+name}",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}"
                        },
                        "batchGetDocumentsMetadata": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.branches.batchGetDocumentsMetadata",
                          "path": "v1alpha/{+parent}/batchGetDocumentsMetadata",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/branches/{branchesId}/batchGetDocumentsMetadata",
                          "httpMethod": "GET",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets index freshness metadata for Documents. Supported for website search only."
                        }
                      }
                    },
                    "suggestionDenyListEntries": {
                      "methods": {
                        "import": {
                          "description": "Imports all SuggestionDenyListEntry for a DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:import",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.import",
                          "path": "v1alpha/{+parent}/suggestionDenyListEntries:import"
                        },
                        "purge": {
                          "description": "Permanently deletes all SuggestionDenyListEntry for a DataStore.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.assist.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/suggestionDenyListEntries:purge",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.suggestionDenyListEntries.purge",
                          "path": "v1alpha/{+parent}/suggestionDenyListEntries:purge"
                        }
                      }
                    },
                    "schemas": {
                      "methods": {
                        "list": {
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.list",
                          "path": "v1alpha/{+parent}/schemas",
                          "httpMethod": "GET",
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "description": "Gets a list of Schemas."
                        },
                        "delete": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "httpMethod": "DELETE",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.delete",
                          "path": "v1alpha/{+name}",
                          "description": "Deletes a Schema.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        },
                        "get": {
                          "description": "Gets a Schema.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "httpMethod": "GET",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.get",
                          "path": "v1alpha/{+name}"
                        },
                        "patch": {
                          "description": "Updates a Schema.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ],
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas/{schemasId}",
                          "httpMethod": "PATCH",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.patch",
                          "path": "v1alpha/{+name}"
                        },
                        "create": {
                          "flatPath": "v1alpha/projects/{projectsId}/locations/{locationsId}/collections/{collectionsId}/dataStores/{dataStoresId}/schemas",
                          "httpMethod": "POST",
                          "id": "discoveryengine.projects.locations.collections.dataStores.schemas.create",
                          "path": "v1alpha/{+parent}/schemas",
                          "description": "Creates a Schema.",
                          "scopes": [
                            "https://www.googleapis.com/auth/cloud-platform",
                            "https://www.googleapis.com/auth/discoveryengine.readwrite",
                            "https://www.googleapis.com/auth/discoveryengine.serving.readwrite"
                          ]
                        }
                      },
                      "resources": {
                        "operations": {
                          "methods": {
                            "list": {
[...]
