{
  "rootUrl": "https://displayvideo.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        }
      }
    }
  },
  "protocol": "rest",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "revision": "20260505",
  "discoveryVersion": "v1",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "canonicalName": "Display Video",
  "resources": {
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a single targeting option.",
              "flatPath": "v3/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "path": "v3/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists targeting options of a given type.",
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "httpMethod": "GET",
              "flatPath": "v3/targetingTypes/{targetingTypesId}/targetingOptions",
              "path": "v3/targetingTypes/{+targetingType}/targetingOptions"
            },
            "search": {
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "flatPath": "v3/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "path": "v3/targetingTypes/{+targetingType}/targetingOptions:search"
            }
          }
        }
      }
    },
    "floodlightGroups": {
      "resources": {
        "floodlightActivities": {
          "methods": {
            "list": {
              "path": "v3/floodlightGroups/{+floodlightGroupId}/floodlightActivities",
              "httpMethod": "GET",
              "id": "displayvideo.floodlightGroups.floodlightActivities.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists Floodlight activities in a Floodlight group.",
              "flatPath": "v3/floodlightGroups/{floodlightGroupsId}/floodlightActivities"
            },
            "get": {
              "path": "v3/floodlightGroups/{+floodlightGroupId}/floodlightActivities/{+floodlightActivityId}",
              "flatPath": "v3/floodlightGroups/{floodlightGroupsId}/floodlightActivities/{floodlightActivitiesId}",
              "id": "displayvideo.floodlightGroups.floodlightActivities.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a Floodlight activity."
            }
          }
        }
      },
      "methods": {
        "get": {
          "path": "v3/floodlightGroups/{+floodlightGroupId}",
          "flatPath": "v3/floodlightGroups/{floodlightGroupsId}",
          "id": "displayvideo.floodlightGroups.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Floodlight group."
        },
        "patch": {
          "flatPath": "v3/floodlightGroups/{floodlightGroupId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.floodlightGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "path": "v3/floodlightGroups/{floodlightGroupId}"
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "flatPath": "v3/sdfdownloadtasks",
          "httpMethod": "POST",
          "id": "displayvideo.sdfdownloadtasks.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with `sdfdownloadtasks.operations.get`. Any errors can be found in the err[...]",
          "path": "v3/sdfdownloadtasks"
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "path": "v3/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "httpMethod": "GET",
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "flatPath": "v3/sdfdownloadtasks/operations/{operationsId}"
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "httpMethod": "GET",
          "id": "displayvideo.media.download",
          "flatPath": "download/{downloadId}",
          "supportsMediaDownload": true,
          "path": "download/{+resourceName}"
        },
        "upload": {
          "path": "media/{+resourceName}",
          "supportsMediaUpload": true,
          "flatPath": "media/{mediaId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "httpMethod": "POST",
          "id": "displayvideo.media.upload"
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "list": {
          "path": "v3/googleAudiences",
          "flatPath": "v3/googleAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "id": "displayvideo.googleAudiences.list",
          "httpMethod": "GET"
        },
        "get": {
          "path": "v3/googleAudiences/{+googleAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Google audience.",
          "id": "displayvideo.googleAudiences.get",
          "httpMethod": "GET",
          "flatPath": "v3/googleAudiences/{googleAudiencesId}"
        }
      }
    },
    "partners": {
      "resources": {
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "path": "v3/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "flatPath": "v3/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit"
                },
                "replace": {
                  "id": "displayvideo.partners.channels.sites.replace",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "flatPath": "v3/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "path": "v3/partners/{partnerId}/channels/{+channelId}/sites:replace"
                },
                "list": {
                  "path": "v3/partners/{+partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v3/partners/{partnersId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists sites in a channel.",
                  "httpMethod": "GET",
                  "id": "displayvideo.partners.channels.sites.list"
                },
                "create": {
                  "path": "v3/partners/{partnerId}/channels/{+channelId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Creates a site in a channel.",
                  "id": "displayvideo.partners.channels.sites.create",
                  "httpMethod": "POST",
                  "flatPath": "v3/partners/{partnerId}/channels/{channelsId}/sites"
                },
                "delete": {
                  "id": "displayvideo.partners.channels.sites.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a site from a channel.",
                  "flatPath": "v3/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "path": "v3/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}"
                }
              }
            }
          },
          "methods": {
            "patch": {
              "path": "v3/partners/{+partnerId}/channels/{channelId}",
              "flatPath": "v3/partners/{partnersId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.partners.channels.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a channel. Returns the updated channel if successful."
            },
            "get": {
              "path": "v3/partners/{+partnerId}/channels/{+channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a channel for a partner or advertiser.",
              "id": "displayvideo.partners.channels.get",
              "httpMethod": "GET",
              "flatPath": "v3/partners/{partnersId}/channels/{channelsId}"
            },
            "create": {
              "flatPath": "v3/partners/{partnersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "httpMethod": "POST",
              "id": "displayvideo.partners.channels.create",
              "path": "v3/partners/{+partnerId}/channels"
            },
            "list": {
              "path": "v3/partners/{+partnerId}/channels",
              "flatPath": "v3/partners/{partnersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists channels for a partner or advertiser.",
              "id": "displayvideo.partners.channels.list",
              "httpMethod": "GET"
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "list": {
                  "path": "v3/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists the targeting options assigned to a partner.",
                  "httpMethod": "GET",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "flatPath": "v3/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Gets a single targeting option assigned to a partner.",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "httpMethod": "GET",
                  "flatPath": "v3/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v3/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "flatPath": "v3/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v3/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                },
                "delete": {
                  "path": "v3/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v3/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes an assigned targeting option from a partner.",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "httpMethod": "DELETE"
                }
              }
            }
          }
        }
      },
      "methods": {
        "get": {
          "flatPath": "v3/partners/{partnersId}",
          "httpMethod": "GET",
          "id": "displayvideo.partners.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a partner.",
          "path": "v3/partners/{+partnerId}"
        },
        "list": {
          "flatPath": "v3/partners",
          "id": "displayvideo.partners.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "path": "v3/partners"
        },
        "editAssignedTargetingOptions": {
          "path": "v3/partners/{+partnerId}:editAssignedTargetingOptions",
          "flatPath": "v3/partners/{partnersId}:editAssignedTargetingOptions",
          "httpMethod": "POST",
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests ."
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a combined audience.",
          "id": "displayvideo.combinedAudiences.get",
          "httpMethod": "GET",
          "flatPath": "v3/combinedAudiences/{combinedAudiencesId}",
          "path": "v3/combinedAudiences/{+combinedAudienceId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "id": "displayvideo.combinedAudiences.list",
          "flatPath": "v3/combinedAudiences",
          "path": "v3/combinedAudiences"
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "list": {
          "path": "v3/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "id": "displayvideo.guaranteedOrders.list",
          "httpMethod": "GET",
          "flatPath": "v3/guaranteedOrders"
        },
        "create": {
          "flatPath": "v3/guaranteedOrders",
          "id": "displayvideo.guaranteedOrders.create",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful.",
          "path": "v3/guaranteedOrders"
        },
        "patch": {
          "flatPath": "v3/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.guaranteedOrders.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "path": "v3/guaranteedOrders/{+guaranteedOrderId}"
        },
        "get": {
          "flatPath": "v3/guaranteedOrders/{guaranteedOrdersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a guaranteed order.",
          "id": "displayvideo.guaranteedOrders.get",
          "httpMethod": "GET",
          "path": "v3/guaranteedOrders/{+guaranteedOrderId}"
        },
        "editGuaranteedOrderReadAccessors": {
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Edits read advertisers of a guaranteed order.",
          "flatPath": "v3/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "path": "v3/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors"
        }
      }
    },
    "inventorySourceGroups": {
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "create": {
              "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources"
            },
            "delete": {
              "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "httpMethod": "DELETE",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}"
            },
            "list": {
              "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists inventory sources assigned to an inventory source group.",
              "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources"
            },
            "bulkEdit": {
              "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources."
            }
          }
        }
      },
      "methods": {
        "get": {
          "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets an inventory source group.",
          "id": "displayvideo.inventorySourceGroups.get",
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "id": "displayvideo.inventorySourceGroups.patch",
          "httpMethod": "PATCH",
          "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupId}",
          "path": "v3/inventorySourceGroups/{inventorySourceGroupId}"
        },
        "list": {
          "path": "v3/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "id": "displayvideo.inventorySourceGroups.list",
          "httpMethod": "GET",
          "flatPath": "v3/inventorySourceGroups"
        },
        "create": {
          "flatPath": "v3/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "httpMethod": "POST",
          "id": "displayvideo.inventorySourceGroups.create",
          "path": "v3/inventorySourceGroups"
        },
        "delete": {
          "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "DELETE",
          "id": "displayvideo.inventorySourceGroups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Deletes an inventory source group."
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "flatPath": "v3/customLists/{customListsId}",
          "httpMethod": "GET",
          "id": "displayvideo.customLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a custom list.",
          "path": "v3/customLists/{+customListId}"
        },
        "list": {
          "httpMethod": "GET",
          "id": "displayvideo.customLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "flatPath": "v3/customLists",
          "path": "v3/customLists"
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "editCustomerMatchMembers": {
          "flatPath": "v3/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}:editCustomerMatchMembers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "httpMethod": "POST",
          "id": "displayvideo.firstAndThirdPartyAudiences.editCustomerMatchMembers",
          "path": "v3/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}:editCustomerMatchMembers"
        },
        "get": {
          "flatPath": "v3/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a first and third party audience.",
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "httpMethod": "GET",
          "path": "v3/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}"
        },
        "patch": {
          "flatPath": "v3/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "id": "displayvideo.firstAndThirdPartyAudiences.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "path": "v3/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}"
        },
        "create": {
          "path": "v3/firstAndThirdPartyAudiences",
          "flatPath": "v3/firstAndThirdPartyAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "id": "displayvideo.firstAndThirdPartyAudiences.create",
          "httpMethod": "POST"
        },
        "list": {
          "path": "v3/firstAndThirdPartyAudiences",
          "flatPath": "v3/firstAndThirdPartyAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "httpMethod": "GET"
        }
      }
    },
    "advertisers": {
      "resources": {
        "creatives": {
          "methods": {
            "get": {
              "flatPath": "v3/advertisers/{advertisersId}/creatives/{creativesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a creative.",
              "id": "displayvideo.advertisers.creatives.get",
              "httpMethod": "GET",
              "path": "v3/advertisers/{+advertiserId}/creatives/{+creativeId}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new creative. Returns the newly created creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "id": "displayvideo.advertisers.creatives.create",
              "httpMethod": "POST",
              "flatPath": "v3/advertisers/{advertisersId}/creatives",
              "path": "v3/advertisers/{+advertiserId}/creatives"
            },
            "delete": {
              "flatPath": "v3/advertisers/{advertisersId}/creatives/{creativesId}",
              "id": "displayvideo.advertisers.creatives.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "path": "v3/advertisers/{+advertiserId}/creatives/{+creativeId}"
            },
            "list": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.creatives.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v3/advertisers/{advertisersId}/creatives",
              "path": "v3/advertisers/{+advertiserId}/creatives"
            },
            "patch": {
              "path": "v3/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v3/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.creatives.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing creative. Returns the updated creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request."
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "get": {
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists",
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists"
            },
            "delete": {
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "httpMethod": "DELETE",
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}"
            },
            "list": {
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists"
            },
            "patch": {
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}"
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "create": {
                  "path": "v3/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "flatPath": "v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords"
                },
                "delete": {
                  "flatPath": "v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "path": "v3/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}"
                },
                "list": {
                  "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists negative keywords in a negative keyword list.",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords"
                },
                "replace": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "flatPath": "v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "path": "v3/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace"
                },
                "bulkEdit": {
                  "path": "v3/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "flatPath": "v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit"
                }
              }
            }
          }
        },
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "create": {
                  "flatPath": "v3/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Creates a site in a channel.",
                  "path": "v3/advertisers/{advertiserId}/channels/{+channelId}/sites"
                },
                "delete": {
                  "flatPath": "v3/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a site from a channel.",
                  "path": "v3/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}"
                },
                "list": {
                  "flatPath": "v3/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists sites in a channel.",
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "httpMethod": "GET",
                  "path": "v3/advertisers/{+advertiserId}/channels/{+channelId}/sites"
                },
                "replace": {
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "flatPath": "v3/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "path": "v3/advertisers/{advertiserId}/channels/{+channelId}/sites:replace"
                },
                "bulkEdit": {
                  "path": "v3/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "flatPath": "v3/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites."
                }
              }
            }
          },
          "methods": {
            "list": {
              "flatPath": "v3/advertisers/{advertisersId}/channels",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.channels.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists channels for a partner or advertiser.",
              "path": "v3/advertisers/{+advertiserId}/channels"
            },
            "get": {
              "flatPath": "v3/advertisers/{advertisersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.channels.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a channel for a partner or advertiser.",
              "path": "v3/advertisers/{+advertiserId}/channels/{+channelId}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "id": "displayvideo.advertisers.channels.create",
              "httpMethod": "POST",
              "flatPath": "v3/advertisers/{advertisersId}/channels",
              "path": "v3/advertisers/{+advertiserId}/channels"
            },
            "patch": {
              "flatPath": "v3/advertisers/{advertisersId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a channel. Returns the updated channel if successful.",
              "id": "displayvideo.advertisers.channels.patch",
              "httpMethod": "PATCH",
              "path": "v3/advertisers/{+advertiserId}/channels/{channelId}"
            }
          }
        },
        "adGroups": {
          "methods": {
            "bulkListAdGroupAssignedTargetingOptions": {
              "path": "v3/advertisers/{+advertiserId}/adGroups:bulkListAdGroupAssignedTargetingOptions",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups:bulkListAdGroupAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists assigned targeting options for multiple ad groups across targeting types. Inherited assigned targeting options are not included.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.adGroups.bulkListAdGroupAssignedTargetingOptions"
            },
            "bulkEditAssignedTargetingOptions": {
              "path": "v3/advertisers/{+advertiserId}/adGroups:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.adGroups.bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Bulk edits targeting options for multiple ad groups. The same set of delete and create requests will be applied to all specified ad groups. Specifically, the operation will delete the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.delete_requests from each ad group, and then create the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.create_requests. This method is only supported for Demand [...]",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups:bulkEditAssignedTargetingOptions"
            },
            "patch": {
              "id": "displayvideo.advertisers.adGroups.patch",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing ad group. Returns the updated ad group if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists ad groups.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.adGroups.list",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups",
              "path": "v3/advertisers/{+advertiserId}/adGroups"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new ad group. Returns the newly created ad group if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.adGroups.create",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups",
              "path": "v3/advertisers/{+advertiserId}/adGroups"
            },
            "delete": {
              "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a AdGroup. Returns error code `NOT_FOUND` if the ad group does not exist. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "id": "displayvideo.advertisers.adGroups.delete",
              "httpMethod": "DELETE",
              "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets an ad group.",
              "id": "displayvideo.advertisers.adGroups.get",
              "httpMethod": "GET",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.get",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Gets a single targeting option assigned to an ad group. Inherited assigned targeting options are not included."
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Assigns a targeting option to an ad group. Returns the assigned targeting option if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.create",
                      "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    },
                    "delete": {
                      "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "DELETE",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Deletes an assigned targeting option from an ad group. This method is only supported for Demand Gen ad groups with the AdGroupFormat `AD_GROUP_FORMAT_DEMAND_GEN`. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
                      "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Lists the targeting options assigned to an ad group. Inherited assigned targeting options are not included.",
                      "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    }
                  }
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "path": "v3/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v3/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Gets a single targeting option assigned to an advertiser."
                },
                "create": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "flatPath": "v3/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v3/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                },
                "delete": {
                  "path": "v3/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v3/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete"
                },
                "list": {
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "flatPath": "v3/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v3/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                }
              }
            }
          }
        },
        "locationLists": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists location lists based on a given advertiser id.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.locationLists.list",
              "flatPath": "v3/advertisers/{advertisersId}/locationLists",
              "path": "v3/advertisers/{+advertiserId}/locationLists"
            },
            "get": {
              "path": "v3/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.locationLists.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a location list.",
              "flatPath": "v3/advertisers/{advertisersId}/locationLists/{locationListsId}"
            },
            "create": {
              "path": "v3/advertisers/{+advertiserId}/locationLists",
              "id": "displayvideo.advertisers.locationLists.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "flatPath": "v3/advertisers/{advertisersId}/locationLists"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a location list. Returns the updated location list if successful.",
              "id": "displayvideo.advertisers.locationLists.patch",
              "httpMethod": "PATCH",
              "flatPath": "v3/advertisers/{advertisersId}/locationLists/{locationListId}",
              "path": "v3/advertisers/{+advertiserId}/locationLists/{locationListId}"
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "list": {
                  "flatPath": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists locations assigned to a location list.",
                  "path": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                },
                "bulkEdit": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in deletedAssignedLocations and then create the assigned locations provided in createdAssignedLocations.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "httpMethod": "POST",
                  "flatPath": "v3/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "path": "v3/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Creates an assignment between a location and a location list.",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "flatPath": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "path": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                },
                "delete": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes the assignment between a location and a location list.",
                  "flatPath": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "path": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}"
                }
              }
            }
          }
        },
        "lineItems": {
          "methods": {
            "get": {
              "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a line item.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.lineItems.get"
            },
            "bulkListAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists assigned targeting options for multiple line items across targeting types.",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "path": "v3/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions"
            },
            "bulkUpdate": {
              "path": "v3/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.bulkUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API.",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems:bulkUpdate"
            },
            "list": {
              "path": "v3/advertisers/{+advertiserId}/lineItems",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "id": "displayvideo.advertisers.lineItems.list",
              "httpMethod": "GET"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new line item. Returns the newly created line item if successful. YouTube & Partners line items cannot be created or updated using the API.",
              "id": "displayvideo.advertisers.lineItems.create",
              "httpMethod": "POST",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems",
              "path": "v3/advertisers/{+advertiserId}/lineItems"
            },
            "delete": {
              "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "id": "displayvideo.advertisers.lineItems.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. YouTube & Partners line items cannot be created or updated using the API.",
              "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}"
            },
            "bulkEditAssignedTargetingOptions": {
              "path": "v3/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkUpdate * lineItems.patch * assignedTargetingOp[...]"
            },
            "patch": {
              "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your de[...]",
              "id": "displayvideo.advertisers.lineItems.patch",
              "httpMethod": "PATCH"
            },
            "duplicate": {
              "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Duplicates a line item. Returns the ID of the created line item if successful. YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Gets a single targeting option assigned to a line item.",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "httpMethod": "GET",
                      "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * DeleteLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    },
                    "delete": {
                      "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * CreateLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "httpMethod": "DELETE",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete"
                    },
                    "list": {
                      "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Lists the targeting options assigned to a line item.",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "httpMethod": "GET",
                      "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    }
                  }
                }
              }
            }
          }
        },
        "campaigns": {
          "methods": {
            "get": {
              "path": "v3/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Gets a campaign.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.campaigns.get"
            },
            "create": {
              "path": "v3/advertisers/{+advertiserId}/campaigns",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.campaigns.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Creates a new campaign. Returns the newly created campaign if successful."
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.campaigns.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "path": "v3/advertisers/{+advertiserId}/campaigns/{+campaignId}"
            },
            "list": {
              "path": "v3/advertisers/{+advertiserId}/campaigns",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "id": "displayvideo.advertisers.campaigns.list",
              "httpMethod": "GET"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "id": "displayvideo.advertisers.campaigns.patch",
              "httpMethod": "PATCH",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "path": "v3/advertisers/{+advertiserId}/campaigns/{+campaignId}"
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "id": "displayvideo.advertisers.assets.upload",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "flatPath": "v3/advertisers/{advertisersId}/assets",
              "path": "v3/advertisers/{+advertiserId}/assets",
              "supportsMediaUpload": true
            }
          }
        },
        "invoices": {
          "methods": {
            "lookupInvoiceCurrency": {
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Retrieves the invoice currency used by an advertiser in a given month.",
              "flatPath": "v3/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "path": "v3/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency"
            },
            "list": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.invoices.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method.",
              "flatPath": "v3/advertisers/{advertisersId}/invoices",
              "path": "v3/advertisers/{+advertiserId}/invoices"
            }
          }
        },
        "adGroupAds": {
          "methods": {
            "get": {
              "path": "v3/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "id": "displayvideo.advertisers.adGroupAds.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets an ad group ad."
            },
            "create": {
              "path": "v3/advertisers/{+advertiserId}/adGroupAds",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "id": "displayvideo.advertisers.adGroupAds.create",
              "httpMethod": "POST"
            },
            "delete": {
              "path": "v3/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "id": "displayvideo.advertisers.adGroupAds.delete",
              "httpMethod": "DELETE",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}"
            },
            "list": {
              "id": "displayvideo.advertisers.adGroupAds.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists ad group ads.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds",
              "path": "v3/advertisers/{+advertiserId}/adGroupAds"
            },
            "patch": {
              "path": "v3/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.adGroupAds.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users."
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "patch": {
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "httpMethod": "PATCH",
              "path": "v3/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            },
            "list": {
              "path": "v3/advertisers/{+advertiserId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "id": "displayvideo.advertisers.insertionOrders.list",
              "httpMethod": "GET",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders"
            },
            "create": {
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.insertionOrders.create",
              "path": "v3/advertisers/{+advertiserId}/insertionOrders"
            },
            "delete": {
              "path": "v3/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "id": "displayvideo.advertisers.insertionOrders.get",
              "httpMethod": "GET",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "path": "v3/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            }
          }
        }
      },
      "methods": {
        "patch": {
          "flatPath": "v3/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "id": "displayvideo.advertisers.patch",
          "httpMethod": "PATCH",
          "path": "v3/advertisers/{+advertiserId}"
        },
        "create": {
          "path": "v3/advertisers",
          "id": "displayvideo.advertisers.create",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
          "flatPath": "v3/advertisers"
        },
        "delete": {
          "path": "v3/advertisers/{+advertiserId}",
          "flatPath": "v3/advertisers/{advertisersId}",
          "httpMethod": "DELETE",
          "id": "displayvideo.advertisers.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered."
        },
        "list": {
          "path": "v3/advertisers",
          "flatPath": "v3/advertisers",
          "id": "displayvideo.advertisers.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported."
        },
        "listAssignedTargetingOptions": {
          "path": "v3/advertisers/{+advertiserId}:listAssignedTargetingOptions",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "flatPath": "v3/advertisers/{advertisersId}:listAssignedTargetingOptions"
        },
        "editAssignedTargetingOptions": {
          "path": "v3/advertisers/{+advertiserId}:editAssignedTargetingOptions",
          "flatPath": "v3/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "httpMethod": "POST",
          "id": "displayvideo.advertisers.editAssignedTargetingOptions"
        },
        "get": {
          "id": "displayvideo.advertisers.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets an advertiser.",
          "flatPath": "v3/advertisers/{advertisersId}",
          "path": "v3/advertisers/{+advertiserId}"
        },
        "audit": {
          "path": "v3/advertisers/{+advertiserId}:audit",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.audit",
          "flatPath": "v3/advertisers/{advertisersId}:audit"
        }
      }
    },
    "users": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Gets a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "httpMethod": "GET",
          "id": "displayvideo.users.get",
          "flatPath": "v3/users/{usersId}",
          "path": "v3/users/{+userId}"
        },
        "list": {
          "flatPath": "v3/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "httpMethod": "GET",
          "id": "displayvideo.users.list",
          "path": "v3/users"
        },
        "bulkEditAssignedUserRoles": {
          "flatPath": "v3/users/{usersId}:bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature[...]",
          "httpMethod": "POST",
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "path": "v3/users/{+userId}:bulkEditAssignedUserRoles"
        },
        "create": {
          "path": "v3/users",
          "flatPath": "v3/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Creates a new user. Returns the newly created user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "id": "displayvideo.users.create",
          "httpMethod": "POST"
        },
        "delete": {
          "path": "v3/users/{+userId}",
          "flatPath": "v3/users/{usersId}",
          "httpMethod": "DELETE",
          "id": "displayvideo.users.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Deletes a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method."
        },
        "patch": {
          "id": "displayvideo.users.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Updates an existing user. Returns the updated user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v3/users/{usersId}",
          "path": "v3/users/{+userId}"
        }
      }
    },
    "customBiddingAlgorithms": {
      "resources": {
        "rules": {
          "methods": {
            "create": {
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new rules resource. Returns the newly created rules resource if successful. Requests creating a custom bidding rules resource under an algorithm assigned to a line item will return an error.",
              "id": "displayvideo.customBiddingAlgorithms.rules.create",
              "httpMethod": "POST"
            },
            "get": {
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules/{rulesId}",
              "httpMethod": "GET",
              "id": "displayvideo.customBiddingAlgorithms.rules.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Retrieves a rules resource.",
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules/{+customBiddingAlgorithmRulesId}"
            },
            "list": {
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules",
              "httpMethod": "GET",
              "id": "displayvideo.customBiddingAlgorithms.rules.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists rules resources that belong to the given algorithm. The order is defined by the order_by parameter.",
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules"
            }
          }
        },
        "scripts": {
          "methods": {
            "create": {
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "httpMethod": "POST",
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new custom bidding script. Returns the newly created script if successful. Requests creating a custom bidding script under an algorithm assigned to a line item will return an error.",
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts"
            },
            "get": {
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a custom bidding script.",
              "httpMethod": "GET",
              "id": "displayvideo.customBiddingAlgorithms.scripts.get"
            },
            "list": {
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter."
            }
          }
        }
      },
      "methods": {
        "patch": {
          "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful. Requests updating a custom bidding algorithm assigned to a line item will return an error.",
          "id": "displayvideo.customBiddingAlgorithms.patch",
          "httpMethod": "PATCH"
        },
        "uploadRules": {
          "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadRules",
          "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadRules",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a rules reference object for an AlgorithmRules file. The resulting reference object provides a resource path where the AlgorithmRules file should be uploaded. This reference object should be included when creating a new CustomBiddingAlgorithmRules resource.",
          "id": "displayvideo.customBiddingAlgorithms.uploadRules",
          "httpMethod": "GET"
        },
        "create": {
          "httpMethod": "POST",
          "id": "displayvideo.customBiddingAlgorithms.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "flatPath": "v3/customBiddingAlgorithms",
          "path": "v3/customBiddingAlgorithms"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "id": "displayvideo.customBiddingAlgorithms.list",
          "httpMethod": "GET",
          "flatPath": "v3/customBiddingAlgorithms",
          "path": "v3/customBiddingAlgorithms"
        },
        "get": {
          "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "httpMethod": "GET",
          "id": "displayvideo.customBiddingAlgorithms.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a custom bidding algorithm.",
          "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}"
        },
        "uploadScript": {
          "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "httpMethod": "GET",
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript"
        }
      }
    }
  },
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/display-video/",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "name": "displayvideo",
  "kind": "discovery#restDescription",
  "servicePath": "",
  "id": "displayvideo:v3",
  "title": "Display & Video 360 API",
  "basePath": "",
  "version_module": true,
  "version": "v3"
}