{
  "kind": "discovery#restDescription",
  "canonicalName": "Display Video",
  "discoveryVersion": "v1",
  "resources": {
    "advertisers": {
      "methods": {
        "create": {
          "path": "v3/advertisers",
          "httpMethod": "POST",
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
          "flatPath": "v3/advertisers",
          "id": "displayvideo.advertisers.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "listAssignedTargetingOptions": {
          "path": "v3/advertisers/{+advertiserId}:listAssignedTargetingOptions",
          "httpMethod": "GET",
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "flatPath": "v3/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "path": "v3/advertisers",
          "httpMethod": "GET",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "flatPath": "v3/advertisers",
          "id": "displayvideo.advertisers.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "audit": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.audit",
          "flatPath": "v3/advertisers/{advertisersId}:audit",
          "httpMethod": "GET",
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "path": "v3/advertisers/{+advertiserId}:audit"
        },
        "get": {
          "id": "displayvideo.advertisers.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v3/advertisers/{+advertiserId}",
          "httpMethod": "GET",
          "description": "Gets an advertiser.",
          "flatPath": "v3/advertisers/{advertisersId}"
        },
        "delete": {
          "flatPath": "v3/advertisers/{advertisersId}",
          "httpMethod": "DELETE",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "path": "v3/advertisers/{+advertiserId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.delete"
        },
        "patch": {
          "id": "displayvideo.advertisers.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v3/advertisers/{+advertiserId}",
          "flatPath": "v3/advertisers/{advertisersId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful."
        },
        "editAssignedTargetingOptions": {
          "id": "displayvideo.advertisers.editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v3/advertisers/{+advertiserId}:editAssignedTargetingOptions",
          "flatPath": "v3/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "httpMethod": "POST",
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests ."
        }
      },
      "resources": {
        "creatives": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.get",
              "httpMethod": "GET",
              "description": "Gets a creative.",
              "flatPath": "v3/advertisers/{advertisersId}/creatives/{creativesId}",
              "path": "v3/advertisers/{+advertiserId}/creatives/{+creativeId}"
            },
            "delete": {
              "id": "displayvideo.advertisers.creatives.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v3/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "DELETE",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request."
            },
            "patch": {
              "path": "v3/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing creative. Returns the updated creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "flatPath": "v3/advertisers/{advertisersId}/creatives/{creativesId}",
              "id": "displayvideo.advertisers.creatives.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.create",
              "flatPath": "v3/advertisers/{advertisersId}/creatives",
              "httpMethod": "POST",
              "description": "Creates a new creative. Returns the newly created creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "path": "v3/advertisers/{+advertiserId}/creatives"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.list",
              "httpMethod": "GET",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v3/advertisers/{advertisersId}/creatives",
              "path": "v3/advertisers/{+advertiserId}/creatives"
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method.",
              "flatPath": "v3/advertisers/{advertisersId}/invoices",
              "path": "v3/advertisers/{+advertiserId}/invoices",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.invoices.list"
            },
            "lookupInvoiceCurrency": {
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v3/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "flatPath": "v3/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "httpMethod": "GET",
              "description": "Retrieves the invoice currency used by an advertiser in a given month."
            }
          }
        },
        "lineItems": {
          "methods": {
            "patch": {
              "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your de[...]",
              "id": "displayvideo.advertisers.lineItems.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkEditAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkUpdate * lineItems.patch * assignedTargetingOp[...]",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "path": "v3/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.list",
              "httpMethod": "GET",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems",
              "path": "v3/advertisers/{+advertiserId}/lineItems"
            },
            "bulkListAssignedTargetingOptions": {
              "flatPath": "v3/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options for multiple line items across targeting types.",
              "path": "v3/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions"
            },
            "get": {
              "id": "displayvideo.advertisers.lineItems.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "GET",
              "description": "Gets a line item."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.delete",
              "httpMethod": "DELETE",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. YouTube & Partners line items cannot be created or updated using the API.",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}"
            },
            "create": {
              "path": "v3/advertisers/{+advertiserId}/lineItems",
              "httpMethod": "POST",
              "description": "Creates a new line item. Returns the newly created line item if successful. YouTube & Partners line items cannot be created or updated using the API.",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "duplicate": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "httpMethod": "POST",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful. YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate",
              "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate"
            },
            "bulkUpdate": {
              "flatPath": "v3/advertisers/{advertisersId}/lineItems:bulkUpdate",
              "httpMethod": "POST",
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API.",
              "path": "v3/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkUpdate"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "create": {
                      "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * DeleteLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "get": {
                      "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "delete": {
                      "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "DELETE",
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * CreateLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete"
                    },
                    "list": {
                      "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a line item.",
                      "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list"
                    }
                  }
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "list": {
                  "path": "v3/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v3/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "httpMethod": "POST",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "flatPath": "v3/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v3/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                },
                "get": {
                  "flatPath": "v3/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "path": "v3/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "flatPath": "v3/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "path": "v3/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                }
              }
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.assets.upload",
              "flatPath": "v3/advertisers/{advertisersId}/assets",
              "supportsMediaUpload": true,
              "httpMethod": "POST",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "path": "v3/advertisers/{+advertiserId}/assets"
            }
          }
        },
        "locationLists": {
          "resources": {
            "assignedLocations": {
              "methods": {
                "list": {
                  "path": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "GET",
                  "description": "Lists locations assigned to a location list.",
                  "flatPath": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "flatPath": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "POST",
                  "description": "Creates an assignment between a location and a location list."
                },
                "bulkEdit": {
                  "path": "v3/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in deletedAssignedLocations and then create the assigned locations provided in createdAssignedLocations.",
                  "flatPath": "v3/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "httpMethod": "DELETE",
                  "description": "Deletes the assignment between a location and a location list.",
                  "flatPath": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "path": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}"
                }
              }
            }
          },
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.locationLists.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/locationLists",
              "httpMethod": "POST",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "flatPath": "v3/advertisers/{advertisersId}/locationLists"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.get",
              "flatPath": "v3/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "httpMethod": "GET",
              "description": "Gets a location list.",
              "path": "v3/advertisers/{+advertiserId}/locationLists/{+locationListId}"
            },
            "patch": {
              "id": "displayvideo.advertisers.locationLists.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "httpMethod": "PATCH",
              "description": "Updates a location list. Returns the updated location list if successful.",
              "flatPath": "v3/advertisers/{advertisersId}/locationLists/{locationListId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.list",
              "flatPath": "v3/advertisers/{advertisersId}/locationLists",
              "httpMethod": "GET",
              "description": "Lists location lists based on a given advertiser id.",
              "path": "v3/advertisers/{+advertiserId}/locationLists"
            }
          }
        },
        "adGroups": {
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "create": {
                      "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "description": "Assigns a targeting option to an ad group. Returns the assigned targeting option if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "get": {
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to an ad group. Inherited assigned targeting options are not included.",
                      "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.get"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.delete",
                      "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "DELETE",
                      "description": "Deletes an assigned targeting option from an ad group. This method is only supported for Demand Gen ad groups with the AdGroupFormat `AD_GROUP_FORMAT_DEMAND_GEN`. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
                      "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    },
                    "list": {
                      "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to an ad group. Inherited assigned targeting options are not included.",
                      "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.patch",
              "httpMethod": "PATCH",
              "description": "Updates an existing ad group. Returns the updated ad group if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.get",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "httpMethod": "GET",
              "description": "Gets an ad group.",
              "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}"
            },
            "delete": {
              "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "httpMethod": "DELETE",
              "description": "Deletes a AdGroup. Returns error code `NOT_FOUND` if the ad group does not exist. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "id": "displayvideo.advertisers.adGroups.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkEditAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.adGroups.bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/adGroups:bulkEditAssignedTargetingOptions",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "description": "Bulk edits targeting options for multiple ad groups. The same set of delete and create requests will be applied to all specified ad groups. Specifically, the operation will delete the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.delete_requests from each ad group, and then create the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.create_requests. This method is only supported for Demand [...]"
            },
            "list": {
              "id": "displayvideo.advertisers.adGroups.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/adGroups",
              "httpMethod": "GET",
              "description": "Lists ad groups.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups"
            },
            "bulkListAdGroupAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.bulkListAdGroupAssignedTargetingOptions",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups:bulkListAdGroupAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options for multiple ad groups across targeting types. Inherited assigned targeting options are not included.",
              "path": "v3/advertisers/{+advertiserId}/adGroups:bulkListAdGroupAssignedTargetingOptions"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a new ad group. Returns the newly created ad group if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups",
              "path": "v3/advertisers/{+advertiserId}/adGroups",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.create"
            }
          }
        },
        "negativeKeywordLists": {
          "resources": {
            "negativeKeywords": {
              "methods": {
                "delete": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v3/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "flatPath": "v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}"
                },
                "replace": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "httpMethod": "POST",
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "flatPath": "v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "path": "v3/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "httpMethod": "POST",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "flatPath": "v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "path": "v3/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords"
                },
                "bulkEdit": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "flatPath": "v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "path": "v3/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit"
                },
                "list": {
                  "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "httpMethod": "GET",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list"
                }
              }
            }
          },
          "methods": {
            "list": {
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists",
              "httpMethod": "GET",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists",
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists",
              "httpMethod": "POST",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists"
            },
            "patch": {
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "httpMethod": "PATCH",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.patch"
            },
            "get": {
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "httpMethod": "GET",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}"
            }
          }
        },
        "adGroupAds": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds",
              "path": "v3/advertisers/{+advertiserId}/adGroupAds",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroupAds.create"
            },
            "list": {
              "path": "v3/advertisers/{+advertiserId}/adGroupAds",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds",
              "httpMethod": "GET",
              "description": "Lists ad group ads.",
              "id": "displayvideo.advertisers.adGroupAds.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "id": "displayvideo.advertisers.adGroupAds.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "httpMethod": "GET",
              "description": "Gets an ad group ad.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}"
            },
            "delete": {
              "path": "v3/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "httpMethod": "DELETE",
              "description": "Deletes an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "id": "displayvideo.advertisers.adGroupAds.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "path": "v3/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "httpMethod": "PATCH",
              "description": "Updates an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "id": "displayvideo.advertisers.adGroupAds.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "campaigns": {
          "methods": {
            "list": {
              "id": "displayvideo.advertisers.campaigns.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v3/advertisers/{+advertiserId}/campaigns",
              "httpMethod": "GET",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.create",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns",
              "httpMethod": "POST",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "path": "v3/advertisers/{+advertiserId}/campaigns"
            },
            "patch": {
              "id": "displayvideo.advertisers.campaigns.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v3/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing campaign. Returns the updated campaign if successful."
            },
            "get": {
              "flatPath": "v3/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "GET",
              "description": "Gets a campaign.",
              "path": "v3/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.get"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.delete",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "DELETE",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "path": "v3/advertisers/{+advertiserId}/campaigns/{+campaignId}"
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "patch": {
              "path": "v3/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "path": "v3/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "GET",
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "id": "displayvideo.advertisers.insertionOrders.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "path": "v3/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "DELETE",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders",
              "path": "v3/advertisers/{+advertiserId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.list"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.create",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders",
              "httpMethod": "POST",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "path": "v3/advertisers/{+advertiserId}/insertionOrders"
            }
          }
        },
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "replace": {
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "flatPath": "v3/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "path": "v3/advertisers/{advertiserId}/channels/{+channelId}/sites:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.replace"
                },
                "delete": {
                  "path": "v3/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "flatPath": "v3/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel.",
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "flatPath": "v3/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "path": "v3/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.list"
                },
                "create": {
                  "path": "v3/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "httpMethod": "POST",
                  "description": "Creates a site in a channel.",
                  "flatPath": "v3/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "flatPath": "v3/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "path": "v3/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit"
                }
              }
            }
          },
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.list",
              "flatPath": "v3/advertisers/{advertisersId}/channels",
              "httpMethod": "GET",
              "description": "Lists channels for a partner or advertiser.",
              "path": "v3/advertisers/{+advertiserId}/channels"
            },
            "patch": {
              "id": "displayvideo.advertisers.channels.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "flatPath": "v3/advertisers/{advertisersId}/channels/{channelId}"
            },
            "get": {
              "id": "displayvideo.advertisers.channels.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/channels/{+channelId}",
              "flatPath": "v3/advertisers/{advertisersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser."
            },
            "create": {
              "id": "displayvideo.advertisers.channels.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/channels",
              "httpMethod": "POST",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "flatPath": "v3/advertisers/{advertisersId}/channels"
            }
          }
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "get": {
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "httpMethod": "GET",
              "description": "Gets a single targeting option.",
              "flatPath": "v3/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}"
            },
            "list": {
              "flatPath": "v3/targetingTypes/{targetingTypesId}/targetingOptions",
              "httpMethod": "GET",
              "description": "Lists targeting options of a given type.",
              "path": "v3/targetingTypes/{+targetingType}/targetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.targetingTypes.targetingOptions.list"
            },
            "search": {
              "path": "v3/targetingTypes/{+targetingType}/targetingOptions:search",
              "flatPath": "v3/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "httpMethod": "POST",
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "patch": {
          "flatPath": "v3/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "path": "v3/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstAndThirdPartyAudiences.patch"
        },
        "get": {
          "path": "v3/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "httpMethod": "GET",
          "description": "Gets a first and third party audience.",
          "flatPath": "v3/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "path": "v3/firstAndThirdPartyAudiences",
          "flatPath": "v3/firstAndThirdPartyAudiences",
          "httpMethod": "GET",
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "id": "displayvideo.firstAndThirdPartyAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "editCustomerMatchMembers": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstAndThirdPartyAudiences.editCustomerMatchMembers",
          "flatPath": "v3/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}:editCustomerMatchMembers",
          "httpMethod": "POST",
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "path": "v3/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}:editCustomerMatchMembers"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstAndThirdPartyAudiences.create",
          "flatPath": "v3/firstAndThirdPartyAudiences",
          "httpMethod": "POST",
          "description": "Creates a FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "path": "v3/firstAndThirdPartyAudiences"
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "path": "v3/combinedAudiences/{+combinedAudienceId}",
          "flatPath": "v3/combinedAudiences/{combinedAudiencesId}",
          "httpMethod": "GET",
          "description": "Gets a combined audience.",
          "id": "displayvideo.combinedAudiences.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "flatPath": "v3/combinedAudiences",
          "path": "v3/combinedAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.combinedAudiences.list"
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "flatPath": "media/{mediaId}",
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "path": "media/{+resourceName}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "id": "displayvideo.media.upload"
        },
        "download": {
          "id": "displayvideo.media.download",
          "supportsMediaDownload": true,
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "path": "download/{+resourceName}",
          "httpMethod": "GET",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "flatPath": "download/{downloadId}"
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "create": {
          "id": "displayvideo.guaranteedOrders.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v3/guaranteedOrders",
          "flatPath": "v3/guaranteedOrders",
          "httpMethod": "POST",
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful."
        },
        "list": {
          "flatPath": "v3/guaranteedOrders",
          "httpMethod": "GET",
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "path": "v3/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.list"
        },
        "get": {
          "path": "v3/guaranteedOrders/{+guaranteedOrderId}",
          "flatPath": "v3/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "GET",
          "description": "Gets a guaranteed order.",
          "id": "displayvideo.guaranteedOrders.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "editGuaranteedOrderReadAccessors": {
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v3/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "flatPath": "v3/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "httpMethod": "POST",
          "description": "Edits read advertisers of a guaranteed order."
        },
        "patch": {
          "path": "v3/guaranteedOrders/{+guaranteedOrderId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "flatPath": "v3/guaranteedOrders/{guaranteedOrdersId}",
          "id": "displayvideo.guaranteedOrders.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.sdfdownloadtasks.create",
          "httpMethod": "POST",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with `sdfdownloadtasks.operations.get`. Any errors can be found in the err[...]",
          "flatPath": "v3/sdfdownloadtasks",
          "path": "v3/sdfdownloadtasks"
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "flatPath": "v3/sdfdownloadtasks/operations/{operationsId}",
              "httpMethod": "GET",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "path": "v3/{+name}"
            }
          }
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.patch",
          "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful. Requests updating a custom bidding algorithm assigned to a line item will return an error.",
          "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}"
        },
        "uploadScript": {
          "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "httpMethod": "GET",
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "uploadRules": {
          "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadRules",
          "httpMethod": "GET",
          "description": "Creates a rules reference object for an AlgorithmRules file. The resulting reference object provides a resource path where the AlgorithmRules file should be uploaded. This reference object should be included when creating a new CustomBiddingAlgorithmRules resource.",
          "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadRules",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.uploadRules"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a custom bidding algorithm.",
          "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.get"
        },
        "list": {
          "path": "v3/customBiddingAlgorithms",
          "httpMethod": "GET",
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "flatPath": "v3/customBiddingAlgorithms",
          "id": "displayvideo.customBiddingAlgorithms.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "path": "v3/customBiddingAlgorithms",
          "httpMethod": "POST",
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "flatPath": "v3/customBiddingAlgorithms",
          "id": "displayvideo.customBiddingAlgorithms.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "rules": {
          "methods": {
            "list": {
              "id": "displayvideo.customBiddingAlgorithms.rules.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "httpMethod": "GET",
              "description": "Lists rules resources that belong to the given algorithm. The order is defined by the order_by parameter.",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules"
            },
            "get": {
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules/{+customBiddingAlgorithmRulesId}",
              "httpMethod": "GET",
              "description": "Retrieves a rules resource.",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules/{rulesId}",
              "id": "displayvideo.customBiddingAlgorithms.rules.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "id": "displayvideo.customBiddingAlgorithms.rules.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "httpMethod": "POST",
              "description": "Creates a new rules resource. Returns the newly created rules resource if successful. Requests creating a custom bidding rules resource under an algorithm assigned to a line item will return an error.",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules"
            }
          }
        },
        "scripts": {
          "methods": {
            "list": {
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "httpMethod": "GET",
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets a custom bidding script.",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.scripts.get"
            },
            "create": {
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "httpMethod": "POST",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful. Requests creating a custom bidding script under an algorithm assigned to a line item will return an error."
            }
          }
        }
      }
    },
    "users": {
      "methods": {
        "patch": {
          "path": "v3/users/{+userId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing user. Returns the updated user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v3/users/{usersId}",
          "id": "displayvideo.users.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.get",
          "flatPath": "v3/users/{usersId}",
          "httpMethod": "GET",
          "description": "Gets a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "path": "v3/users/{+userId}"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.delete",
          "httpMethod": "DELETE",
          "description": "Deletes a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v3/users/{usersId}",
          "path": "v3/users/{+userId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.list",
          "flatPath": "v3/users",
          "httpMethod": "GET",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "path": "v3/users"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.create",
          "httpMethod": "POST",
          "description": "Creates a new user. Returns the newly created user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v3/users",
          "path": "v3/users"
        },
        "bulkEditAssignedUserRoles": {
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v3/users/{+userId}:bulkEditAssignedUserRoles",
          "httpMethod": "POST",
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature[...]",
          "flatPath": "v3/users/{usersId}:bulkEditAssignedUserRoles"
        }
      }
    },
    "inventorySourceGroups": {
      "methods": {
        "get": {
          "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "GET",
          "description": "Gets an inventory source group.",
          "id": "displayvideo.inventorySourceGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "delete": {
          "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "DELETE",
          "description": "Deletes an inventory source group.",
          "id": "displayvideo.inventorySourceGroups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "path": "v3/inventorySourceGroups/{inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.patch"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.create",
          "flatPath": "v3/inventorySourceGroups",
          "httpMethod": "POST",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "path": "v3/inventorySourceGroups"
        },
        "list": {
          "flatPath": "v3/inventorySourceGroups",
          "httpMethod": "GET",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "path": "v3/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.list"
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "httpMethod": "POST",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources"
            },
            "bulkEdit": {
              "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit"
            },
            "delete": {
              "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "httpMethod": "DELETE",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete"
            },
            "list": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "httpMethod": "GET",
              "description": "Lists inventory sources assigned to an inventory source group."
            }
          }
        }
      }
    },
    "partners": {
      "methods": {
        "editAssignedTargetingOptions": {
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v3/partners/{+partnerId}:editAssignedTargetingOptions",
          "httpMethod": "POST",
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "flatPath": "v3/partners/{partnersId}:editAssignedTargetingOptions"
        },
        "list": {
          "path": "v3/partners",
          "httpMethod": "GET",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "flatPath": "v3/partners",
          "id": "displayvideo.partners.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "path": "v3/partners/{+partnerId}",
          "flatPath": "v3/partners/{partnersId}",
          "httpMethod": "GET",
          "description": "Gets a partner.",
          "id": "displayvideo.partners.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "channels": {
          "resources": {
            "sites": {
              "methods": {
                "delete": {
                  "path": "v3/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "flatPath": "v3/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel.",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "replace": {
                  "flatPath": "v3/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "path": "v3/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.replace"
                },
                "create": {
                  "flatPath": "v3/partners/{partnerId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "description": "Creates a site in a channel.",
                  "path": "v3/partners/{partnerId}/channels/{+channelId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.create"
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "flatPath": "v3/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "path": "v3/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.bulkEdit"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.list",
                  "flatPath": "v3/partners/{partnersId}/channels/{channelsId}/sites",
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "path": "v3/partners/{+partnerId}/channels/{+channelId}/sites"
                }
              }
            }
          },
          "methods": {
            "get": {
              "flatPath": "v3/partners/{partnersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser.",
              "path": "v3/partners/{+partnerId}/channels/{+channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.get"
            },
            "create": {
              "flatPath": "v3/partners/{partnersId}/channels",
              "httpMethod": "POST",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "path": "v3/partners/{+partnerId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.create"
            },
            "list": {
              "flatPath": "v3/partners/{partnersId}/channels",
              "httpMethod": "GET",
              "description": "Lists channels for a partner or advertiser.",
              "path": "v3/partners/{+partnerId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.list"
            },
            "patch": {
              "path": "v3/partners/{+partnerId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "flatPath": "v3/partners/{partnersId}/channels/{channelId}",
              "id": "displayvideo.partners.channels.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "flatPath": "v3/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "path": "v3/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                },
                "delete": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v3/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v3/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes an assigned targeting option from a partner."
                },
                "create": {
                  "flatPath": "v3/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "path": "v3/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "flatPath": "v3/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "description": "Lists the targeting options assigned to a partner.",
                  "path": "v3/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                }
              }
            }
          }
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "path": "v3/customLists/{+customListId}",
          "flatPath": "v3/customLists/{customListsId}",
          "httpMethod": "GET",
          "description": "Gets a custom list.",
          "id": "displayvideo.customLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "flatPath": "v3/customLists",
          "httpMethod": "GET",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "path": "v3/customLists",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customLists.list"
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.floodlightGroups.get",
          "httpMethod": "GET",
          "description": "Gets a Floodlight group.",
          "flatPath": "v3/floodlightGroups/{floodlightGroupsId}",
          "path": "v3/floodlightGroups/{+floodlightGroupId}"
        },
        "patch": {
          "id": "displayvideo.floodlightGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v3/floodlightGroups/{floodlightGroupId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "flatPath": "v3/floodlightGroups/{floodlightGroupId}"
        }
      },
      "resources": {
        "floodlightActivities": {
          "methods": {
            "get": {
              "id": "displayvideo.floodlightGroups.floodlightActivities.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/floodlightGroups/{+floodlightGroupId}/floodlightActivities/{+floodlightActivityId}",
              "flatPath": "v3/floodlightGroups/{floodlightGroupsId}/floodlightActivities/{floodlightActivitiesId}",
              "httpMethod": "GET",
              "description": "Gets a Floodlight activity."
            },
            "list": {
              "id": "displayvideo.floodlightGroups.floodlightActivities.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/floodlightGroups/{+floodlightGroupId}/floodlightActivities",
              "httpMethod": "GET",
              "description": "Lists Floodlight activities in a Floodlight group.",
              "flatPath": "v3/floodlightGroups/{floodlightGroupsId}/floodlightActivities"
            }
          }
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "id": "displayvideo.googleAudiences.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v3/googleAudiences/{+googleAudienceId}",
          "httpMethod": "GET",
          "description": "Gets a Google audience.",
          "flatPath": "v3/googleAudiences/{googleAudiencesId}"
        },
        "list": {
          "id": "displayvideo.googleAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v3/googleAudiences",
          "httpMethod": "GET",
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "flatPath": "v3/googleAudiences"
        }
      }
    }
  },
  "baseUrl": "https://displayvideo.googleapis.com/",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "basePath": "",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "title": "Display & Video 360 API",
  "revision": "20260412",
  "batchPath": "batch",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        }
      }
    }
  },
  "servicePath": "",
  "version_module": true,
  "protocol": "rest",
  "ownerDomain": "google.com",
  "version": "v3",
  "documentationLink": "https://developers.google.com/display-video/",
  "ownerName": "Google",
  "fullyEncodeReservedExpansion": true,
  "id": "displayvideo:v3",
  "name": "displayvideo",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/"
}