{
  "id": "displayvideo:v2",
  "fullyEncodeReservedExpansion": true,
  "version": "v2",
  "canonicalName": "Display Video",
  "revision": "20260305",
  "basePath": "",
  "name": "displayvideo",
  "batchPath": "batch",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "documentationLink": "https://developers.google.com/display-video/",
  "title": "Display & Video 360 API",
  "ownerDomain": "google.com",
  "servicePath": "",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "ownerName": "Google",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "version_module": true,
  "kind": "discovery#restDescription",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        }
      }
    }
  },
  "resources": {
    "floodlightGroups": {
      "methods": {
        "get": {
          "path": "v2/floodlightGroups/{+floodlightGroupId}",
          "flatPath": "v2/floodlightGroups/{floodlightGroupsId}",
          "id": "displayvideo.floodlightGroups.get",
          "httpMethod": "GET",
          "description": "Gets a Floodlight group.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "path": "v2/floodlightGroups/{floodlightGroupId}",
          "flatPath": "v2/floodlightGroups/{floodlightGroupId}",
          "id": "displayvideo.floodlightGroups.patch"
        }
      },
      "resources": {
        "floodlightActivities": {
          "methods": {
            "get": {
              "id": "displayvideo.floodlightGroups.floodlightActivities.get",
              "path": "v2/floodlightGroups/{+floodlightGroupId}/floodlightActivities/{+floodlightActivityId}",
              "flatPath": "v2/floodlightGroups/{floodlightGroupsId}/floodlightActivities/{floodlightActivitiesId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a Floodlight activity."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists Floodlight activities in a Floodlight group.",
              "httpMethod": "GET",
              "id": "displayvideo.floodlightGroups.floodlightActivities.list",
              "path": "v2/floodlightGroups/{+floodlightGroupId}/floodlightActivities",
              "flatPath": "v2/floodlightGroups/{floodlightGroupsId}/floodlightActivities"
            }
          }
        }
      }
    },
    "users": {
      "methods": {
        "create": {
          "description": "Creates a new user. Returns the newly created user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v2/users",
          "flatPath": "v2/users",
          "id": "displayvideo.users.create",
          "httpMethod": "POST"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Gets a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "id": "displayvideo.users.get",
          "path": "v2/users/{+userId}",
          "flatPath": "v2/users/{usersId}",
          "httpMethod": "GET"
        },
        "bulkEditAssignedUserRoles": {
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature[...]",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v2/users/{+userId}:bulkEditAssignedUserRoles",
          "flatPath": "v2/users/{usersId}:bulkEditAssignedUserRoles",
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "httpMethod": "POST"
        },
        "patch": {
          "description": "Updates an existing user. Returns the updated user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "PATCH",
          "path": "v2/users/{+userId}",
          "flatPath": "v2/users/{usersId}",
          "id": "displayvideo.users.patch"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Deletes a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "id": "displayvideo.users.delete",
          "path": "v2/users/{+userId}",
          "flatPath": "v2/users/{usersId}",
          "httpMethod": "DELETE"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "id": "displayvideo.users.list",
          "path": "v2/users",
          "flatPath": "v2/users",
          "httpMethod": "GET"
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "description": "Gets a single targeting option.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists targeting options of a given type."
            },
            "search": {
              "httpMethod": "POST",
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions:search",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Searches for targeting options of a given type based on the given search terms."
            }
          }
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "id": "displayvideo.customLists.get",
          "path": "v2/customLists/{+customListId}",
          "flatPath": "v2/customLists/{customListsId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a custom list."
        },
        "list": {
          "id": "displayvideo.customLists.list",
          "path": "v2/customLists",
          "flatPath": "v2/customLists",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists custom lists. The order is defined by the order_by parameter."
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "create": {
          "httpMethod": "POST",
          "id": "displayvideo.guaranteedOrders.create",
          "path": "v2/guaranteedOrders",
          "flatPath": "v2/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful."
        },
        "editGuaranteedOrderReadAccessors": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Edits read advertisers of a guaranteed order.",
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "httpMethod": "POST"
        },
        "get": {
          "id": "displayvideo.guaranteedOrders.get",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a guaranteed order."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "id": "displayvideo.guaranteedOrders.patch",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "PATCH"
        },
        "list": {
          "httpMethod": "GET",
          "id": "displayvideo.guaranteedOrders.list",
          "path": "v2/guaranteedOrders",
          "flatPath": "v2/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results."
        }
      }
    },
    "advertisers": {
      "methods": {
        "audit": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "id": "displayvideo.advertisers.audit",
          "path": "v2/advertisers/{+advertiserId}:audit",
          "flatPath": "v2/advertisers/{advertisersId}:audit",
          "httpMethod": "GET"
        },
        "editAssignedTargetingOptions": {
          "httpMethod": "POST",
          "id": "displayvideo.advertisers.editAssignedTargetingOptions",
          "path": "v2/advertisers/{+advertiserId}:editAssignedTargetingOptions",
          "flatPath": "v2/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests ."
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "v2/advertisers/{+advertiserId}",
          "flatPath": "v2/advertisers/{advertisersId}",
          "id": "displayvideo.advertisers.patch",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "v2/advertisers/{+advertiserId}",
          "flatPath": "v2/advertisers/{advertisersId}",
          "id": "displayvideo.advertisers.delete",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.list",
          "path": "v2/advertisers",
          "flatPath": "v2/advertisers"
        },
        "listAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "path": "v2/advertisers/{+advertiserId}:listAssignedTargetingOptions",
          "flatPath": "v2/advertisers/{advertisersId}:listAssignedTargetingOptions"
        },
        "create": {
          "httpMethod": "POST",
          "id": "displayvideo.advertisers.create",
          "path": "v2/advertisers",
          "flatPath": "v2/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets an advertiser.",
          "id": "displayvideo.advertisers.get",
          "path": "v2/advertisers/{+advertiserId}",
          "flatPath": "v2/advertisers/{advertisersId}",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "insertionOrders": {
          "methods": {
            "list": {
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "id": "displayvideo.advertisers.insertionOrders.list"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it."
            },
            "get": {
              "id": "displayvideo.advertisers.insertionOrders.get",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist."
            },
            "create": {
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "id": "displayvideo.advertisers.insertionOrders.create",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "patch": {
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.patch"
            },
            "delete": {
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "httpMethod": "DELETE"
            },
            "list": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists negative keyword lists based on a given advertiser id."
            },
            "create": {
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}"
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "list": {
                  "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "httpMethod": "GET",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "replace": {
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace"
                },
                "delete": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a negative keyword from a negative keyword list."
                },
                "bulkEdit": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit"
                },
                "create": {
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "httpMethod": "POST"
                }
              }
            }
          }
        },
        "campaigns": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.campaigns.create",
              "path": "v2/advertisers/{+advertiserId}/campaigns",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Creates a new campaign. Returns the newly created campaign if successful."
            },
            "get": {
              "description": "Gets a campaign.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "id": "displayvideo.advertisers.campaigns.get"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "id": "displayvideo.advertisers.campaigns.patch",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "PATCH"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.campaigns.delete",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}"
            },
            "list": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.campaigns.list",
              "path": "v2/advertisers/{+advertiserId}/campaigns",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            }
          }
        },
        "manualTriggers": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers",
              "id": "displayvideo.advertisers.manualTriggers.create",
              "description": "Creates a new manual trigger. Returns the newly created manual trigger if successful. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.manualTriggers.get",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a manual trigger. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information."
            },
            "activate": {
              "id": "displayvideo.advertisers.manualTriggers.activate",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:activate",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:activate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Activates a manual trigger. Each activation of the manual trigger must be at least 5 minutes apart, otherwise an error will be returned. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information."
            },
            "patch": {
              "id": "displayvideo.advertisers.manualTriggers.patch",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a manual trigger. Returns the updated manual trigger if successful. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information."
            },
            "list": {
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers",
              "id": "displayvideo.advertisers.manualTriggers.list",
              "description": "Lists manual triggers that are accessible to the current user for a given advertiser ID. The order is defined by the order_by parameter. A single advertiser_id is required. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "deactivate": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deactivates a manual trigger. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "id": "displayvideo.advertisers.manualTriggers.deactivate",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:deactivate",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:deactivate",
              "httpMethod": "POST"
            }
          }
        },
        "channels": {
          "methods": {
            "get": {
              "description": "Gets a channel for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}",
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}",
              "id": "displayvideo.advertisers.channels.get",
              "httpMethod": "GET"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists channels for a partner or advertiser.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.channels.list",
              "path": "v2/advertisers/{+advertiserId}/channels",
              "flatPath": "v2/advertisers/{advertisersId}/channels"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/channels",
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "id": "displayvideo.advertisers.channels.create",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates a channel. Returns the updated channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/channels/{channelId}",
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelId}",
              "id": "displayvideo.advertisers.channels.patch"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites."
                },
                "create": {
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Creates a site in a channel."
                },
                "replace": {
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:replace",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a site from a channel.",
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists sites in a channel."
                }
              }
            }
          }
        },
        "locationLists": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a location list.",
              "id": "displayvideo.advertisers.locationLists.get",
              "path": "v2/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.locationLists.list",
              "path": "v2/advertisers/{+advertiserId}/locationLists",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists location lists based on a given advertiser id."
            },
            "create": {
              "id": "displayvideo.advertisers.locationLists.create",
              "path": "v2/advertisers/{+advertiserId}/locationLists",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new location list. Returns the newly created location list if successful."
            },
            "patch": {
              "description": "Updates a location list. Returns the updated location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListId}",
              "id": "displayvideo.advertisers.locationLists.patch"
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "bulkEdit": {
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in deletedAssignedLocations and then create the assigned locations provided in createdAssignedLocations.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "httpMethod": "POST"
                },
                "create": {
                  "description": "Creates an assignment between a location and a location list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes the assignment between a location and a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists locations assigned to a location list."
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Gets a single targeting option assigned to an advertiser."
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET"
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful."
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                }
              }
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.invoices.list",
              "path": "v2/advertisers/{+advertiserId}/invoices",
              "flatPath": "v2/advertisers/{advertisersId}/invoices",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method."
            },
            "lookupInvoiceCurrency": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "path": "v2/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "flatPath": "v2/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Retrieves the invoice currency used by an advertiser in a given month."
            }
          }
        },
        "creatives": {
          "methods": {
            "patch": {
              "description": "Updates an existing creative. Returns the updated creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "id": "displayvideo.advertisers.creatives.patch"
            },
            "delete": {
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "id": "displayvideo.advertisers.creatives.delete"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "id": "displayvideo.advertisers.creatives.list",
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "flatPath": "v2/advertisers/{advertisersId}/creatives",
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.creatives.create",
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "flatPath": "v2/advertisers/{advertisersId}/creatives",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new creative. Returns the newly created creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request."
            },
            "get": {
              "description": "Gets a creative.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "id": "displayvideo.advertisers.creatives.get"
            }
          }
        },
        "lineItems": {
          "methods": {
            "duplicate": {
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate",
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful. YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkEditAssignedTargetingOptions": {
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkUpdate * lineItems.patch * assignedTargetingOp[...]",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkListAssignedTargetingOptions": {
              "description": "Lists assigned targeting options for multiple line items across targeting types.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions"
            },
            "patch": {
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your de[...]",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "id": "displayvideo.advertisers.lineItems.patch"
            },
            "get": {
              "id": "displayvideo.advertisers.lineItems.get",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a line item."
            },
            "create": {
              "path": "v2/advertisers/{+advertiserId}/lineItems",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.create",
              "httpMethod": "POST",
              "description": "Creates a new line item. Returns the newly created line item if successful. YouTube & Partners line items cannot be created or updated using the API.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/lineItems",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.list",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkUpdate": {
              "id": "displayvideo.advertisers.lineItems.bulkUpdate",
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkUpdate",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API."
            },
            "delete": {
              "id": "displayvideo.advertisers.lineItems.delete",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. YouTube & Partners line items cannot be created or updated using the API."
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "create": {
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * DeleteLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API."
                    },
                    "delete": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "DELETE",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * CreateLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API."
                    },
                    "get": {
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "list": {
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "httpMethod": "POST",
              "path": "v2/advertisers/{+advertiserId}/assets",
              "flatPath": "v2/advertisers/{advertisersId}/assets",
              "id": "displayvideo.advertisers.assets.upload",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaUpload": true
            }
          }
        },
        "youtubeAdGroupAds": {
          "methods": {
            "get": {
              "description": "Gets a YouTube ad group ad.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds/{+youtubeAdGroupAdId}",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds/{youtubeAdGroupAdsId}",
              "id": "displayvideo.advertisers.youtubeAdGroupAds.get"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists YouTube ad group ads.",
              "id": "displayvideo.advertisers.youtubeAdGroupAds.list",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds",
              "httpMethod": "GET"
            }
          }
        },
        "youtubeAdGroups": {
          "methods": {
            "bulkListAdGroupAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists assigned targeting options for multiple YouTube ad groups across targeting types. Inherited assigned targeting options are not included.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.youtubeAdGroups.bulkListAdGroupAssignedTargetingOptions",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a YouTube ad group.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.youtubeAdGroups.get",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists YouTube ad groups.",
              "id": "displayvideo.advertisers.youtubeAdGroups.list",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "description": "Gets a single targeting option assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.get",
                      "httpMethod": "GET"
                    },
                    "list": {
                      "description": "Lists the targeting options assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "GET",
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.list"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Google audience.",
          "id": "displayvideo.googleAudiences.get",
          "path": "v2/googleAudiences/{+googleAudienceId}",
          "flatPath": "v2/googleAudiences/{googleAudiencesId}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v2/googleAudiences",
          "flatPath": "v2/googleAudiences",
          "id": "displayvideo.googleAudiences.list"
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "id": "displayvideo.combinedAudiences.get",
          "path": "v2/combinedAudiences/{+combinedAudienceId}",
          "flatPath": "v2/combinedAudiences/{combinedAudiencesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a combined audience."
        },
        "list": {
          "httpMethod": "GET",
          "path": "v2/combinedAudiences",
          "flatPath": "v2/combinedAudiences",
          "id": "displayvideo.combinedAudiences.list",
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "patch": {
          "id": "displayvideo.customBiddingAlgorithms.patch",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful. Requests updating a custom bidding algorithm assigned to a line item will return an error."
        },
        "list": {
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v2/customBiddingAlgorithms",
          "flatPath": "v2/customBiddingAlgorithms",
          "id": "displayvideo.customBiddingAlgorithms.list"
        },
        "uploadScript": {
          "httpMethod": "GET",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "path": "v2/customBiddingAlgorithms",
          "flatPath": "v2/customBiddingAlgorithms",
          "id": "displayvideo.customBiddingAlgorithms.create"
        },
        "get": {
          "description": "Gets a custom bidding algorithm.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "id": "displayvideo.customBiddingAlgorithms.get",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "scripts": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful. Requests creating a custom bidding script under an algorithm assigned to a line item will return an error.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "id": "displayvideo.customBiddingAlgorithms.scripts.get",
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a custom bidding script."
            },
            "list": {
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list",
              "httpMethod": "GET",
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    },
    "inventorySourceGroups": {
      "methods": {
        "list": {
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v2/inventorySourceGroups",
          "flatPath": "v2/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.list"
        },
        "patch": {
          "id": "displayvideo.inventorySourceGroups.patch",
          "path": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful."
        },
        "delete": {
          "id": "displayvideo.inventorySourceGroups.delete",
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Deletes an inventory source group."
        },
        "get": {
          "httpMethod": "GET",
          "id": "displayvideo.inventorySourceGroups.get",
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets an inventory source group."
        },
        "create": {
          "httpMethod": "POST",
          "path": "v2/inventorySourceGroups",
          "flatPath": "v2/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.create",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "bulkEdit": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "httpMethod": "POST",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "httpMethod": "DELETE",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists inventory sources assigned to an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "partners": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a partner.",
          "id": "displayvideo.partners.get",
          "path": "v2/partners/{+partnerId}",
          "flatPath": "v2/partners/{partnersId}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/partners",
          "flatPath": "v2/partners",
          "id": "displayvideo.partners.list",
          "httpMethod": "GET"
        },
        "editAssignedTargetingOptions": {
          "httpMethod": "POST",
          "path": "v2/partners/{+partnerId}:editAssignedTargetingOptions",
          "flatPath": "v2/partners/{partnersId}:editAssignedTargetingOptions",
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "channels": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "path": "v2/partners/{+partnerId}/channels",
              "flatPath": "v2/partners/{partnersId}/channels",
              "id": "displayvideo.partners.channels.create",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a channel. Returns the updated channel if successful.",
              "id": "displayvideo.partners.channels.patch",
              "path": "v2/partners/{+partnerId}/channels/{channelId}",
              "flatPath": "v2/partners/{partnersId}/channels/{channelId}",
              "httpMethod": "PATCH"
            },
            "get": {
              "description": "Gets a channel for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/partners/{+partnerId}/channels/{+channelId}",
              "flatPath": "v2/partners/{partnersId}/channels/{channelsId}",
              "id": "displayvideo.partners.channels.get",
              "httpMethod": "GET"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists channels for a partner or advertiser.",
              "id": "displayvideo.partners.channels.list",
              "path": "v2/partners/{+partnerId}/channels",
              "flatPath": "v2/partners/{partnersId}/channels",
              "httpMethod": "GET"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "httpMethod": "POST",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.channels.sites.create",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Creates a site in a channel."
                },
                "list": {
                  "description": "Lists sites in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/partners/{+partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v2/partners/{partnersId}/channels/{channelsId}/sites",
                  "id": "displayvideo.partners.channels.sites.list",
                  "httpMethod": "GET"
                },
                "replace": {
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "id": "displayvideo.partners.channels.sites.replace",
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a site from a channel.",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE"
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Gets a single targeting option assigned to a partner."
                },
                "list": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists the targeting options assigned to a partner."
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful."
                },
                "delete": {
                  "description": "Deletes an assigned targeting option from a partner.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete"
                }
              }
            }
          }
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "path": "v2/sdfdownloadtasks",
          "flatPath": "v2/sdfdownloadtasks",
          "id": "displayvideo.sdfdownloadtasks.create",
          "httpMethod": "POST",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with `sdfdownloadtasks.operations.get`. Any errors can be found in the err[...]",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "path": "v2/{+name}",
              "flatPath": "v2/sdfdownloadtasks/operations/{operationsId}",
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ]
            }
          }
        }
      }
    },
    "inventorySources": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySources.list",
          "path": "v2/inventorySources",
          "flatPath": "v2/inventorySources"
        },
        "editInventorySourceReadWriteAccessors": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source.",
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors",
          "path": "v2/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors",
          "flatPath": "v2/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors",
          "httpMethod": "POST"
        },
        "patch": {
          "path": "v2/inventorySources/{+inventorySourceId}",
          "flatPath": "v2/inventorySources/{inventorySourcesId}",
          "id": "displayvideo.inventorySources.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "path": "v2/inventorySources/{+inventorySourceId}",
          "flatPath": "v2/inventorySources/{inventorySourcesId}",
          "id": "displayvideo.inventorySources.get",
          "description": "Gets an inventory source.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful.",
          "id": "displayvideo.inventorySources.create",
          "path": "v2/inventorySources",
          "flatPath": "v2/inventorySources",
          "httpMethod": "POST"
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "id": "displayvideo.media.upload",
          "path": "media/{+resourceName}",
          "flatPath": "media/{mediaId}",
          "httpMethod": "POST"
        },
        "download": {
          "httpMethod": "GET",
          "id": "displayvideo.media.download",
          "path": "download/{+resourceName}",
          "flatPath": "download/{downloadId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "supportsMediaDownload": true,
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string."
        }
      }
    }
  }
}