{
  "title": "Display & Video 360 API",
  "fullyEncodeReservedExpansion": true,
  "version_module": true,
  "servicePath": "",
  "name": "displayvideo",
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "ownerName": "Google",
  "basePath": "",
  "revision": "20260312",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "documentationLink": "https://developers.google.com/display-video/",
  "protocol": "rest",
  "version": "v4",
  "id": "displayvideo:v4",
  "ownerDomain": "google.com",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "canonicalName": "Display Video",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        }
      }
    }
  },
  "resources": {
    "guaranteedOrders": {
      "methods": {
        "patch": {
          "id": "displayvideo.guaranteedOrders.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}",
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}"
        },
        "create": {
          "path": "v4/guaranteedOrders",
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful.",
          "flatPath": "v4/guaranteedOrders",
          "id": "displayvideo.guaranteedOrders.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "id": "displayvideo.guaranteedOrders.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}",
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}",
          "description": "Gets a guaranteed order."
        },
        "editGuaranteedOrderReadAccessors": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "httpMethod": "POST",
          "description": "Edits read advertisers of a guaranteed order.",
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors"
        },
        "list": {
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "path": "v4/guaranteedOrders",
          "flatPath": "v4/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.list",
          "httpMethod": "GET"
        }
      }
    },
    "inventorySourceGroups": {
      "methods": {
        "list": {
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "path": "v4/inventorySourceGroups",
          "flatPath": "v4/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.list",
          "httpMethod": "GET"
        },
        "delete": {
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}",
          "description": "Deletes an inventory source group.",
          "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.delete"
        },
        "get": {
          "description": "Gets an inventory source group.",
          "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.get",
          "httpMethod": "GET"
        },
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.create",
          "flatPath": "v4/inventorySourceGroups",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "path": "v4/inventorySourceGroups"
        },
        "patch": {
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupId}",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "path": "v4/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.patch"
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "description": "Lists inventory sources assigned to an inventory source group."
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}"
            },
            "create": {
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create"
            },
            "bulkEdit": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit"
            }
          }
        }
      }
    },
    "partners": {
      "methods": {
        "editAssignedTargetingOptions": {
          "httpMethod": "POST",
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/partners/{partnersId}:editAssignedTargetingOptions",
          "path": "v4/partners/{+partnerId}:editAssignedTargetingOptions",
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests ."
        },
        "get": {
          "flatPath": "v4/partners/{partnersId}",
          "description": "Gets a partner.",
          "path": "v4/partners/{+partnerId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.partners.get"
        },
        "list": {
          "id": "displayvideo.partners.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v4/partners",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "flatPath": "v4/partners"
        }
      },
      "resources": {
        "channels": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.list",
              "httpMethod": "GET",
              "description": "Lists channels for a partner or advertiser.",
              "path": "v4/partners/{+partnerId}/channels",
              "flatPath": "v4/partners/{partnersId}/channels"
            },
            "create": {
              "httpMethod": "POST",
              "id": "displayvideo.partners.channels.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/partners/{partnersId}/channels",
              "path": "v4/partners/{+partnerId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful."
            },
            "patch": {
              "description": "Updates a channel. Returns the updated channel if successful.",
              "path": "v4/partners/{+partnerId}/channels/{channelId}",
              "flatPath": "v4/partners/{partnersId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.patch",
              "httpMethod": "PATCH"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.get",
              "flatPath": "v4/partners/{partnersId}/channels/{channelsId}",
              "description": "Gets a channel for a partner or advertiser.",
              "path": "v4/partners/{+partnerId}/channels/{+channelId}"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "replace": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.replace",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites:replace"
                },
                "create": {
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites",
                  "description": "Creates a site in a channel.",
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.channels.sites.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.list",
                  "flatPath": "v4/partners/{partnersId}/channels/{channelsId}/sites",
                  "description": "Lists sites in a channel.",
                  "path": "v4/partners/{+partnerId}/channels/{+channelId}/sites"
                },
                "delete": {
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "description": "Deletes a site from a channel.",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE"
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit"
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "list": {
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to a partner.",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "description": "Deletes an assigned targeting option from a partner."
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful."
                },
                "get": {
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get"
                }
              }
            }
          }
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "get": {
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "description": "Gets a single targeting option.",
              "httpMethod": "GET",
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions",
              "description": "Lists targeting options of a given type.",
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions"
            },
            "search": {
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions:search",
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST"
            }
          }
        }
      }
    },
    "inventorySources": {
      "methods": {
        "get": {
          "flatPath": "v4/inventorySources/{inventorySourcesId}",
          "path": "v4/inventorySources/{+inventorySourceId}",
          "description": "Gets an inventory source.",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySources.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "flatPath": "v4/inventorySources",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "path": "v4/inventorySources",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.list"
        },
        "editInventorySourceReadWriteAccessors": {
          "flatPath": "v4/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors",
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source.",
          "path": "v4/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful.",
          "path": "v4/inventorySources/{+inventorySourceId}",
          "flatPath": "v4/inventorySources/{inventorySourcesId}"
        },
        "create": {
          "flatPath": "v4/inventorySources",
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful.",
          "path": "v4/inventorySources",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.create"
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "displayvideo.combinedAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/combinedAudiences",
          "path": "v4/combinedAudiences",
          "description": "Lists combined audiences. The order is defined by the order_by parameter."
        },
        "get": {
          "flatPath": "v4/combinedAudiences/{combinedAudiencesId}",
          "path": "v4/combinedAudiences/{+combinedAudienceId}",
          "description": "Gets a combined audience.",
          "httpMethod": "GET",
          "id": "displayvideo.combinedAudiences.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.googleAudiences.get",
          "httpMethod": "GET",
          "description": "Gets a Google audience.",
          "path": "v4/googleAudiences/{+googleAudienceId}",
          "flatPath": "v4/googleAudiences/{googleAudiencesId}"
        },
        "list": {
          "path": "v4/googleAudiences",
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "flatPath": "v4/googleAudiences",
          "id": "displayvideo.googleAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "users": {
      "methods": {
        "create": {
          "description": "Creates a new user. Returns the newly created user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "path": "v4/users",
          "flatPath": "v4/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.create",
          "httpMethod": "POST"
        },
        "patch": {
          "flatPath": "v4/users/{usersId}",
          "description": "Updates an existing user. Returns the updated user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "path": "v4/users/{+userId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.patch"
        },
        "bulkEditAssignedUserRoles": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "httpMethod": "POST",
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature[...]",
          "path": "v4/users/{+userId}:bulkEditAssignedUserRoles",
          "flatPath": "v4/users/{usersId}:bulkEditAssignedUserRoles"
        },
        "list": {
          "id": "displayvideo.users.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "GET",
          "path": "v4/users",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v4/users"
        },
        "delete": {
          "flatPath": "v4/users/{usersId}",
          "path": "v4/users/{+userId}",
          "description": "Deletes a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "httpMethod": "DELETE",
          "id": "displayvideo.users.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "get": {
          "path": "v4/users/{+userId}",
          "description": "Gets a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v4/users/{usersId}",
          "id": "displayvideo.users.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "sdfuploadtasks": {
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "id": "displayvideo.sdfuploadtasks.operations.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "httpMethod": "GET",
              "path": "v4/{+name}",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "flatPath": "v4/sdfuploadtasks/operations/{operationsId}"
            }
          }
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customLists.get",
          "flatPath": "v4/customLists/{customListsId}",
          "description": "Gets a custom list.",
          "path": "v4/customLists/{+customListId}"
        },
        "list": {
          "id": "displayvideo.customLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v4/customLists",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "flatPath": "v4/customLists"
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "flatPath": "media/{mediaId}",
          "supportsMediaUpload": true,
          "path": "media/{+resourceName}",
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "httpMethod": "POST",
          "id": "displayvideo.media.upload",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ]
        },
        "download": {
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "supportsMediaDownload": true,
          "path": "download/{+resourceName}",
          "flatPath": "download/{downloadId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "id": "displayvideo.media.download",
          "httpMethod": "GET"
        }
      }
    },
    "firstPartyAndPartnerAudiences": {
      "methods": {
        "editCustomerMatchMembers": {
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}:editCustomerMatchMembers",
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}:editCustomerMatchMembers",
          "id": "displayvideo.firstPartyAndPartnerAudiences.editCustomerMatchMembers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstPartyAndPartnerAudiences.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing FirstPartyAndPartnerAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}",
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}"
        },
        "create": {
          "path": "v4/firstPartyAndPartnerAudiences",
          "description": "Creates a FirstPartyAndPartnerAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "flatPath": "v4/firstPartyAndPartnerAudiences",
          "id": "displayvideo.firstPartyAndPartnerAudiences.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "id": "displayvideo.firstPartyAndPartnerAudiences.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}",
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}",
          "description": "Gets a first party or partner audience."
        },
        "list": {
          "flatPath": "v4/firstPartyAndPartnerAudiences",
          "path": "v4/firstPartyAndPartnerAudiences",
          "description": "Lists first party and partner audiences. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "id": "displayvideo.firstPartyAndPartnerAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "patch": {
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful. Requests updating a custom bidding algorithm assigned to a line item will return an error.",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "id": "displayvideo.customBiddingAlgorithms.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH"
        },
        "uploadRules": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.uploadRules",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadRules",
          "description": "Creates a rules reference object for an AlgorithmRules file. The resulting reference object provides a resource path where the AlgorithmRules file should be uploaded. This reference object should be included when creating a new CustomBiddingAlgorithmRules resource.",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadRules"
        },
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.create",
          "flatPath": "v4/customBiddingAlgorithms",
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "path": "v4/customBiddingAlgorithms"
        },
        "uploadScript": {
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.get",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "description": "Gets a custom bidding algorithm.",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}"
        },
        "list": {
          "id": "displayvideo.customBiddingAlgorithms.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v4/customBiddingAlgorithms",
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "flatPath": "v4/customBiddingAlgorithms"
        }
      },
      "resources": {
        "scripts": {
          "methods": {
            "get": {
              "id": "displayvideo.customBiddingAlgorithms.scripts.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "description": "Gets a custom bidding script.",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}"
            },
            "list": {
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "httpMethod": "GET",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful. Requests creating a custom bidding script under an algorithm assigned to a line item will return an error.",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST"
            }
          }
        },
        "rules": {
          "methods": {
            "list": {
              "description": "Lists rules resources that belong to the given algorithm. The order is defined by the order_by parameter.",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.rules.list",
              "httpMethod": "GET"
            },
            "create": {
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules",
              "description": "Creates a new rules resource. Returns the newly created rules resource if successful. Requests creating a custom bidding rules resource under an algorithm assigned to a line item will return an error.",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.rules.create"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.rules.get",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules/{rulesId}",
              "description": "Retrieves a rules resource.",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules/{+customBiddingAlgorithmRulesId}"
            }
          }
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "patch": {
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "path": "v4/floodlightGroups/{floodlightGroupId}",
          "flatPath": "v4/floodlightGroups/{floodlightGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.floodlightGroups.patch",
          "httpMethod": "PATCH"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.floodlightGroups.get",
          "flatPath": "v4/floodlightGroups/{floodlightGroupsId}",
          "description": "Gets a Floodlight group.",
          "path": "v4/floodlightGroups/{+floodlightGroupId}"
        }
      },
      "resources": {
        "floodlightActivities": {
          "methods": {
            "get": {
              "path": "v4/floodlightGroups/{+floodlightGroupId}/floodlightActivities/{+floodlightActivityId}",
              "description": "Gets a Floodlight activity.",
              "flatPath": "v4/floodlightGroups/{floodlightGroupsId}/floodlightActivities/{floodlightActivitiesId}",
              "id": "displayvideo.floodlightGroups.floodlightActivities.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET"
            },
            "list": {
              "flatPath": "v4/floodlightGroups/{floodlightGroupsId}/floodlightActivities",
              "description": "Lists Floodlight activities in a Floodlight group.",
              "path": "v4/floodlightGroups/{+floodlightGroupId}/floodlightActivities",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.floodlightGroups.floodlightActivities.list"
            }
          }
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.sdfdownloadtasks.create",
          "flatPath": "v4/sdfdownloadtasks",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with `sdfdownloadtasks.operations.get`. Any errors can be found in the err[...]",
          "path": "v4/sdfdownloadtasks"
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "httpMethod": "GET",
              "path": "v4/{+name}",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "flatPath": "v4/sdfdownloadtasks/operations/{operationsId}"
            }
          }
        }
      }
    },
    "advertisers": {
      "methods": {
        "listAssignedTargetingOptions": {
          "path": "v4/advertisers/{+advertiserId}:listAssignedTargetingOptions",
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "flatPath": "v4/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET"
        },
        "editAssignedTargetingOptions": {
          "id": "displayvideo.advertisers.editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "path": "v4/advertisers/{+advertiserId}:editAssignedTargetingOptions",
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "flatPath": "v4/advertisers/{advertisersId}:editAssignedTargetingOptions"
        },
        "patch": {
          "httpMethod": "PATCH",
          "id": "displayvideo.advertisers.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/advertisers/{advertisersId}",
          "path": "v4/advertisers/{+advertiserId}",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful."
        },
        "create": {
          "id": "displayvideo.advertisers.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "path": "v4/advertisers",
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
          "flatPath": "v4/advertisers"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.get",
          "flatPath": "v4/advertisers/{advertisersId}",
          "description": "Gets an advertiser.",
          "path": "v4/advertisers/{+advertiserId}"
        },
        "list": {
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/advertisers",
          "path": "v4/advertisers",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported."
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "displayvideo.advertisers.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/advertisers/{advertisersId}",
          "path": "v4/advertisers/{+advertiserId}",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered."
        },
        "audit": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.audit",
          "httpMethod": "GET",
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "path": "v4/advertisers/{+advertiserId}:audit",
          "flatPath": "v4/advertisers/{advertisersId}:audit"
        }
      },
      "resources": {
        "channels": {
          "methods": {
            "list": {
              "flatPath": "v4/advertisers/{advertisersId}/channels",
              "description": "Lists channels for a partner or advertiser.",
              "path": "v4/advertisers/{+advertiserId}/channels",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.list"
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.create",
              "flatPath": "v4/advertisers/{advertisersId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "path": "v4/advertisers/{+advertiserId}/channels"
            },
            "patch": {
              "flatPath": "v4/advertisers/{advertisersId}/channels/{channelId}",
              "path": "v4/advertisers/{+advertiserId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.channels.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "path": "v4/advertisers/{+advertiserId}/channels/{+channelId}",
              "description": "Gets a channel for a partner or advertiser.",
              "flatPath": "v4/advertisers/{advertisersId}/channels/{channelsId}",
              "id": "displayvideo.advertisers.channels.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "replace": {
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites:replace"
                },
                "create": {
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "description": "Creates a site in a channel.",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "path": "v4/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "flatPath": "v4/advertisers/{advertisersId}/channels/{channelsId}/sites"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel.",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}"
                },
                "bulkEdit": {
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit"
                }
              }
            }
          }
        },
        "adGroups": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.adGroups.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "description": "Updates an existing ad group. Returns the updated ad group if successful."
            },
            "bulkEditAssignedTargetingOptions": {
              "flatPath": "v4/advertisers/{advertisersId}/adGroups:bulkEditAssignedTargetingOptions",
              "description": "Bulk edits targeting options for multiple ad groups. The same set of delete and create requests will be applied to all specified ad groups. Specifically, the operation will delete the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.delete_requests from each ad group, and then create the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.create_requests. Only ad groups under a line item of line_[...]",
              "path": "v4/advertisers/{+advertiserId}/adGroups:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.bulkEditAssignedTargetingOptions"
            },
            "create": {
              "description": "Creates a new ad group. Returns the newly created ad group if successful.",
              "path": "v4/advertisers/{+advertiserId}/adGroups",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.create",
              "httpMethod": "POST"
            },
            "bulkListAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.adGroups.bulkListAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/adGroups:bulkListAssignedTargetingOptions",
              "description": "Lists assigned targeting options for multiple ad groups across targeting types. Inherited assigned targeting options are not included.",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups:bulkListAssignedTargetingOptions"
            },
            "get": {
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "description": "Gets an ad group.",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "id": "displayvideo.advertisers.adGroups.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.list",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups",
              "description": "Lists ad groups.",
              "path": "v4/advertisers/{+advertiserId}/adGroups"
            },
            "delete": {
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "description": "Deletes a AdGroup. Returns error code `NOT_FOUND` if the ad group does not exist.",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "id": "displayvideo.advertisers.adGroups.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.get",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "description": "Gets a single targeting option assigned to an ad group. Inherited assigned targeting options are not included.",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    },
                    "create": {
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "POST",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "description": "Assigns a targeting option to an ad group. Returns the assigned targeting option if successful. Only ad groups under a line item of line_item_type `LINE_ITEM_TYPE_DEMAND_GEN` are supported for this method.",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.list",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "description": "Lists the targeting options assigned to an ad group. Inherited assigned targeting options are not included.",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    },
                    "delete": {
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "DELETE",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Deletes an assigned targeting option from an ad group. Only ad groups under a line item of line_item_type `LINE_ITEM_TYPE_DEMAND_GEN` are supported for this method.",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    }
                  }
                }
              }
            },
            "youtubeAssetTypes": {
              "resources": {
                "youtubeAssetAssociations": {
                  "methods": {
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.create",
                      "httpMethod": "POST",
                      "description": "Creates a new association between the identified resource and a YouTube asset. Returns the newly-created association. *Warning:* This method is only available to an informed subset of users.",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations"
                    },
                    "list": {
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "description": "Lists the YouTube asset associations linked to the given resource.",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.list"
                    },
                    "delete": {
                      "description": "Deletes an existing association between the identified resource and a YouTube asset. *Warning:* This method is only available to an informed subset of users.",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations/{+youtubeAssetAssociationId}",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations/{youtubeAssetAssociationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.delete",
                      "httpMethod": "DELETE"
                    }
                  }
                }
              }
            }
          }
        },
        "adGroupAds": {
          "methods": {
            "list": {
              "path": "v4/advertisers/{+advertiserId}/adGroupAds",
              "description": "Lists ad group ads.",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds",
              "id": "displayvideo.advertisers.adGroupAds.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.adGroupAds.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "description": "Deletes an ad group ad."
            },
            "get": {
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "description": "Gets an ad group ad.",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroupAds.get"
            },
            "create": {
              "description": "Creates an ad group ad.",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroupAds.create",
              "httpMethod": "POST"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroupAds.patch",
              "httpMethod": "PATCH",
              "description": "Updates an ad group ad.",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}"
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "path": "v4/advertisers/{+advertiserId}/invoices",
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method.",
              "flatPath": "v4/advertisers/{advertisersId}/invoices",
              "id": "displayvideo.advertisers.invoices.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "GET"
            },
            "lookupInvoiceCurrency": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "path": "v4/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "description": "Retrieves the invoice currency used by an advertiser in a given month."
            }
          }
        },
        "adAssets": {
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.adAssets.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "path": "v4/advertisers/{+advertiserId}/adAssets",
              "description": "Creates an ad asset. Returns the newly-created ad asset if successful. Only supports the creation of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adAssets.list",
              "httpMethod": "GET",
              "description": "Lists ad assets under an advertiser ID. Only supports the retrieval of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "path": "v4/advertisers/{+advertiserId}/adAssets",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets"
            },
            "get": {
              "flatPath": "v4/advertisers/{advertisersId}/adAssets/{adAssetsId}",
              "path": "v4/advertisers/{+advertiserId}/adAssets/{+adAssetId}",
              "description": "Gets an ad asset. Only supports the retrieval of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.adAssets.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkCreate": {
              "id": "displayvideo.advertisers.adAssets.bulkCreate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "path": "v4/advertisers/{+advertiserId}/adAssets:bulkCreate",
              "description": "Creates multiple ad assets in a single request. Returns the newly-created ad assets if successful. Only supports the creation of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets:bulkCreate"
            },
            "upload": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adAssets.upload",
              "httpMethod": "POST",
              "description": "Uploads and creates an ad asset. Returns the ID of the newly-created ad asset if successful. Only supports the uploading of assets with the AdAssetType `AD_ASSET_TYPE_IMAGE`.",
              "path": "v4/advertisers/{+advertiserId}/adAssets:uploadAdAsset",
              "supportsMediaUpload": true,
              "flatPath": "v4/advertisers/{advertisersId}/adAssets:uploadAdAsset"
            }
          }
        },
        "lineItems": {
          "methods": {
            "get": {
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "description": "Gets a line item.",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "id": "displayvideo.advertisers.lineItems.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET"
            },
            "delete": {
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. YouTube & Partners line items cannot be created or updated using the API.",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.lineItems.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkListAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options for multiple line items across targeting types.",
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions"
            },
            "duplicate": {
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful. YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.list",
              "httpMethod": "GET",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v4/advertisers/{+advertiserId}/lineItems",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems"
            },
            "patch": {
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.lineItems.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your de[...]"
            },
            "bulkUpdate": {
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API.",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkUpdate",
              "id": "displayvideo.advertisers.lineItems.bulkUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST"
            },
            "bulkEditAssignedTargetingOptions": {
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkUpdate * lineItems.patch * assignedTargetingOp[...]",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "flatPath": "v4/advertisers/{advertisersId}/lineItems",
              "path": "v4/advertisers/{+advertiserId}/lineItems",
              "description": "Creates a new line item. Returns the newly created line item if successful. YouTube & Partners line items cannot be created or updated using the API.",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "create": {
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * DeleteLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "list": {
                      "description": "Lists the targeting options assigned to a line item.",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "httpMethod": "GET"
                    },
                    "delete": {
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * CreateLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "httpMethod": "DELETE",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            },
            "youtubeAssetTypes": {
              "resources": {
                "youtubeAssetAssociations": {
                  "methods": {
                    "create": {
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "description": "Creates a new association between the identified resource and a YouTube asset. Returns the newly-created association. *Warning:* This method is only available to an informed subset of users.",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "POST"
                    },
                    "list": {
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "GET",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "description": "Lists the YouTube asset associations linked to the given resource.",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations"
                    },
                    "delete": {
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations/{+youtubeAssetAssociationId}",
                      "description": "Deletes an existing association between the identified resource and a YouTube asset. *Warning:* This method is only available to an informed subset of users.",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations/{youtubeAssetAssociationsId}",
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "DELETE"
                    }
                  }
                }
              }
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "patch": {
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}"
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.create",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders"
            },
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.get",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            },
            "list": {
              "path": "v4/advertisers/{+advertiserId}/insertionOrders",
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders",
              "id": "displayvideo.advertisers.insertionOrders.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET"
            },
            "delete": {
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.delete"
            }
          }
        },
        "locationLists": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.locationLists.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/locationLists/{locationListId}",
              "path": "v4/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "description": "Updates a location list. Returns the updated location list if successful."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.get",
              "httpMethod": "GET",
              "description": "Gets a location list.",
              "path": "v4/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists/{locationListsId}"
            },
            "list": {
              "path": "v4/advertisers/{+advertiserId}/locationLists",
              "description": "Lists location lists based on a given advertiser id.",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists",
              "id": "displayvideo.advertisers.locationLists.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.create",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "path": "v4/advertisers/{+advertiserId}/locationLists"
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "httpMethod": "GET",
                  "description": "Lists locations assigned to a location list.",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                },
                "delete": {
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "description": "Deletes the assignment between a location and a location list.",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "description": "Creates an assignment between a location and a location list.",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST"
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in deletedAssignedLocations and then create the assigned locations provided in createdAssignedLocations."
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "list": {
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET"
                },
                "delete": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                },
                "create": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                },
                "get": {
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get"
                }
              }
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "httpMethod": "PATCH",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "httpMethod": "POST",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists"
            },
            "get": {
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}"
            },
            "list": {
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "httpMethod": "GET"
            },
            "delete": {
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "httpMethod": "DELETE"
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "list": {
                  "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list"
                },
                "delete": {
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete"
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure."
                },
                "replace": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace",
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace"
                },
                "create": {
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "httpMethod": "POST"
                }
              }
            }
          }
        },
        "campaigns": {
          "methods": {
            "get": {
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "description": "Gets a campaign.",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "id": "displayvideo.advertisers.campaigns.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.campaigns.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/campaigns",
              "path": "v4/advertisers/{+advertiserId}/campaigns",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.delete",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}"
            },
            "patch": {
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.patch"
            },
            "create": {
              "id": "displayvideo.advertisers.campaigns.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "POST",
              "path": "v4/advertisers/{+advertiserId}/campaigns",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns"
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "supportsMediaUpload": true,
              "flatPath": "v4/advertisers/{advertisersId}/assets",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "path": "v4/advertisers/{+advertiserId}/assets",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.assets.upload"
            }
          }
        },
        "creatives": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.list",
              "flatPath": "v4/advertisers/{advertisersId}/creatives",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v4/advertisers/{+advertiserId}/creatives"
            },
            "delete": {
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.delete"
            },
            "get": {
              "id": "displayvideo.advertisers.creatives.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "description": "Gets a creative.",
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}"
            },
            "create": {
              "flatPath": "v4/advertisers/{advertisersId}/creatives",
              "description": "Creates a new creative. Returns the newly created creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "path": "v4/advertisers/{+advertiserId}/creatives",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.create"
            },
            "patch": {
              "id": "displayvideo.advertisers.creatives.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "description": "Updates an existing creative. Returns the updated creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}"
            }
          }
        }
      }
    }
  },
  "baseUrl": "https://displayvideo.googleapis.com/",
  "kind": "discovery#restDescription"
}