{
  "basePath": "",
  "servicePath": "",
  "version": "v4",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "discoveryVersion": "v1",
  "resources": {
    "googleAudiences": {
      "methods": {
        "get": {
          "description": "Gets a Google audience.",
          "id": "displayvideo.googleAudiences.get",
          "path": "v4/googleAudiences/{+googleAudienceId}",
          "flatPath": "v4/googleAudiences/{googleAudiencesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/googleAudiences",
          "flatPath": "v4/googleAudiences",
          "httpMethod": "GET",
          "id": "displayvideo.googleAudiences.list",
          "description": "Lists Google audiences. The order is defined by the order_by parameter."
        }
      }
    },
    "customLists": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customLists.list",
          "path": "v4/customLists",
          "flatPath": "v4/customLists",
          "httpMethod": "GET",
          "description": "Lists custom lists. The order is defined by the order_by parameter."
        },
        "get": {
          "id": "displayvideo.customLists.get",
          "path": "v4/customLists/{+customListId}",
          "flatPath": "v4/customLists/{customListsId}",
          "httpMethod": "GET",
          "description": "Gets a custom list.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "partners": {
      "resources": {
        "channels": {
          "methods": {
            "get": {
              "id": "displayvideo.partners.channels.get",
              "path": "v4/partners/{+partnerId}/channels/{+channelId}",
              "flatPath": "v4/partners/{partnersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/partners/{+partnerId}/channels/{channelId}",
              "flatPath": "v4/partners/{partnersId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.partners.channels.patch",
              "description": "Updates a channel. Returns the updated channel if successful."
            },
            "create": {
              "path": "v4/partners/{+partnerId}/channels",
              "flatPath": "v4/partners/{partnersId}/channels",
              "httpMethod": "POST",
              "id": "displayvideo.partners.channels.create",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists channels for a partner or advertiser.",
              "path": "v4/partners/{+partnerId}/channels",
              "flatPath": "v4/partners/{partnersId}/channels",
              "httpMethod": "GET",
              "id": "displayvideo.partners.channels.list"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "path": "v4/partners/{+partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v4/partners/{partnersId}/channels/{channelsId}/sites",
                  "httpMethod": "GET",
                  "id": "displayvideo.partners.channels.sites.list",
                  "description": "Lists sites in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Creates a site in a channel.",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.channels.sites.create"
                },
                "delete": {
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "description": "Deletes a site from a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "replace": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.replace",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors."
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "description": "Lists the targeting options assigned to a partner."
                },
                "create": {
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "description": "Deletes an assigned targeting option from a partner.",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "get": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        }
      },
      "methods": {
        "editAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "path": "v4/partners/{+partnerId}:editAssignedTargetingOptions",
          "flatPath": "v4/partners/{partnersId}:editAssignedTargetingOptions",
          "httpMethod": "POST",
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests ."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/partners",
          "flatPath": "v4/partners",
          "httpMethod": "GET",
          "id": "displayvideo.partners.list",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter."
        },
        "get": {
          "id": "displayvideo.partners.get",
          "path": "v4/partners/{+partnerId}",
          "flatPath": "v4/partners/{partnersId}",
          "httpMethod": "GET",
          "description": "Gets a partner.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "advertisers": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "id": "displayvideo.advertisers.patch",
          "path": "v4/advertisers/{+advertiserId}",
          "flatPath": "v4/advertisers/{advertisersId}",
          "httpMethod": "PATCH"
        },
        "get": {
          "description": "Gets an advertiser.",
          "id": "displayvideo.advertisers.get",
          "path": "v4/advertisers/{+advertiserId}",
          "flatPath": "v4/advertisers/{advertisersId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "editAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "path": "v4/advertisers/{+advertiserId}:editAssignedTargetingOptions",
          "flatPath": "v4/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "httpMethod": "POST",
          "id": "displayvideo.advertisers.editAssignedTargetingOptions"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/advertisers",
          "flatPath": "v4/advertisers",
          "httpMethod": "GET",
          "id": "displayvideo.advertisers.list",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported."
        },
        "listAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "path": "v4/advertisers/{+advertiserId}:listAssignedTargetingOptions",
          "flatPath": "v4/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "httpMethod": "GET",
          "description": "Lists assigned targeting options of an advertiser across targeting types."
        },
        "audit": {
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "id": "displayvideo.advertisers.audit",
          "path": "v4/advertisers/{+advertiserId}:audit",
          "flatPath": "v4/advertisers/{advertisersId}:audit",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
          "id": "displayvideo.advertisers.create",
          "path": "v4/advertisers",
          "flatPath": "v4/advertisers",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "delete": {
          "id": "displayvideo.advertisers.delete",
          "path": "v4/advertisers/{+advertiserId}",
          "flatPath": "v4/advertisers/{advertisersId}",
          "httpMethod": "DELETE",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "lineItems": {
          "methods": {
            "bulkUpdate": {
              "id": "displayvideo.advertisers.lineItems.bulkUpdate",
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkUpdate",
              "httpMethod": "POST",
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.lineItems.get",
              "description": "Gets a line item.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkEditAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkUpdate * lineItems.patch * assignedTargetingOp[...]",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "duplicate": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful. YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors."
            },
            "create": {
              "description": "Creates a new line item. Returns the newly created line item if successful. YouTube & Partners line items cannot be created or updated using the API.",
              "path": "v4/advertisers/{+advertiserId}/lineItems",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. YouTube & Partners line items cannot be created or updated using the API.",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.lineItems.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your de[...]",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.lineItems.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkListAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions",
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options for multiple line items across targeting types."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v4/advertisers/{+advertiserId}/lineItems",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.lineItems.list"
            }
          },
          "resources": {
            "youtubeAssetTypes": {
              "resources": {
                "youtubeAssetAssociations": {
                  "methods": {
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Creates a new association between the identified resource and a YouTube asset. Returns the newly-created association. *Warning:* This method is only available to an informed subset of users.",
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.create",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "httpMethod": "POST"
                    },
                    "delete": {
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.delete",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations/{+youtubeAssetAssociationId}",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations/{youtubeAssetAssociationsId}",
                      "httpMethod": "DELETE",
                      "description": "Deletes an existing association between the identified resource and a YouTube asset. *Warning:* This method is only available to an informed subset of users.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "list": {
                      "description": "Lists the YouTube asset associations linked to the given resource.",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            },
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "list": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * DeleteLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * CreateLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "DELETE"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a line item."
                    }
                  }
                }
              }
            }
          }
        },
        "campaigns": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "id": "displayvideo.advertisers.campaigns.create",
              "path": "v4/advertisers/{+advertiserId}/campaigns",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns",
              "httpMethod": "POST"
            },
            "delete": {
              "id": "displayvideo.advertisers.campaigns.delete",
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "DELETE",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v4/advertisers/{+advertiserId}/campaigns",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.campaigns.list"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.get",
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "GET",
              "description": "Gets a campaign."
            },
            "patch": {
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.campaigns.patch",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            }
          }
        },
        "creatives": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.create",
              "path": "v4/advertisers/{+advertiserId}/creatives",
              "flatPath": "v4/advertisers/{advertisersId}/creatives",
              "httpMethod": "POST",
              "description": "Creates a new creative. Returns the newly created creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.creatives.delete"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing creative. Returns the updated creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "id": "displayvideo.advertisers.creatives.patch",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "PATCH"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.get",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "GET",
              "description": "Gets a creative."
            },
            "list": {
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v4/advertisers/{+advertiserId}/creatives",
              "flatPath": "v4/advertisers/{advertisersId}/creatives",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.creatives.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.insertionOrders.create"
            },
            "delete": {
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "DELETE",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "id": "displayvideo.advertisers.insertionOrders.list",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.insertionOrders.get"
            }
          }
        },
        "adGroupAds": {
          "methods": {
            "patch": {
              "description": "Updates an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "id": "displayvideo.advertisers.adGroupAds.patch",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroupAds.get",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "httpMethod": "GET",
              "description": "Gets an ad group ad."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists ad group ads.",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.adGroupAds.list"
            },
            "create": {
              "path": "v4/advertisers/{+advertiserId}/adGroupAds",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.adGroupAds.create",
              "description": "Creates an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.adGroupAds.delete"
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful."
                },
                "delete": {
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "get": {
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "adGroups": {
          "resources": {
            "youtubeAssetTypes": {
              "resources": {
                "youtubeAssetAssociations": {
                  "methods": {
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.create",
                      "description": "Creates a new association between the identified resource and a YouTube asset. Returns the newly-created association. *Warning:* This method is only available to an informed subset of users."
                    },
                    "delete": {
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations/{+youtubeAssetAssociationId}",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations/{youtubeAssetAssociationsId}",
                      "httpMethod": "DELETE",
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.delete",
                      "description": "Deletes an existing association between the identified resource and a YouTube asset. *Warning:* This method is only available to an informed subset of users.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.list",
                      "description": "Lists the YouTube asset associations linked to the given resource."
                    }
                  }
                }
              }
            },
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.get",
                      "description": "Gets a single targeting option assigned to an ad group. Inherited assigned targeting options are not included."
                    },
                    "create": {
                      "description": "Assigns a targeting option to an ad group. Returns the assigned targeting option if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.create",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "DELETE",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.delete",
                      "description": "Deletes an assigned targeting option from an ad group. This method is only supported for Demand Gen ad groups with the AdGroupFormat `AD_GROUP_FORMAT_DEMAND_GEN`. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users."
                    },
                    "list": {
                      "description": "Lists the targeting options assigned to an ad group. Inherited assigned targeting options are not included.",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            }
          },
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/adGroups",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.adGroups.create",
              "description": "Creates a new ad group. Returns the newly created ad group if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users."
            },
            "delete": {
              "description": "Deletes a AdGroup. Returns error code `NOT_FOUND` if the ad group does not exist. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.adGroups.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkEditAssignedTargetingOptions": {
              "id": "displayvideo.advertisers.adGroups.bulkEditAssignedTargetingOptions",
              "path": "v4/advertisers/{+advertiserId}/adGroups:bulkEditAssignedTargetingOptions",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "description": "Bulk edits targeting options for multiple ad groups. The same set of delete and create requests will be applied to all specified ad groups. Specifically, the operation will delete the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.delete_requests from each ad group, and then create the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.create_requests. This method is only supported for Demand [...]",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an existing ad group. Returns the updated ad group if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "id": "displayvideo.advertisers.adGroups.patch",
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "httpMethod": "PATCH"
            },
            "get": {
              "id": "displayvideo.advertisers.adGroups.get",
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "httpMethod": "GET",
              "description": "Gets an ad group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkListAssignedTargetingOptions": {
              "path": "v4/advertisers/{+advertiserId}/adGroups:bulkListAssignedTargetingOptions",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups:bulkListAssignedTargetingOptions",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.adGroups.bulkListAssignedTargetingOptions",
              "description": "Lists assigned targeting options for multiple ad groups across targeting types. Inherited assigned targeting options are not included.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "id": "displayvideo.advertisers.adGroups.list",
              "path": "v4/advertisers/{+advertiserId}/adGroups",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups",
              "httpMethod": "GET",
              "description": "Lists ad groups.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "locationLists": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.locationLists.get",
              "description": "Gets a location list."
            },
            "patch": {
              "description": "Updates a location list. Returns the updated location list if successful.",
              "path": "v4/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists/{locationListId}",
              "httpMethod": "PATCH",
              "id": "displayvideo.advertisers.locationLists.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "id": "displayvideo.advertisers.locationLists.create",
              "path": "v4/advertisers/{+advertiserId}/locationLists",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists",
              "httpMethod": "POST",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists location lists based on a given advertiser id.",
              "path": "v4/advertisers/{+advertiserId}/locationLists",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.locationLists.list"
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists locations assigned to a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "GET"
                },
                "create": {
                  "description": "Creates an assignment between a location and a location list.",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "description": "Deletes the assignment between a location and a location list.",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "path": "v4/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "httpMethod": "POST",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in deletedAssignedLocations and then create the assigned locations provided in createdAssignedLocations.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaUpload": true,
              "id": "displayvideo.advertisers.assets.upload",
              "path": "v4/advertisers/{+advertiserId}/assets",
              "flatPath": "v4/advertisers/{advertisersId}/assets",
              "httpMethod": "POST",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset)."
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists",
              "httpMethod": "POST",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.negativeKeywordLists.delete"
            },
            "list": {
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "httpMethod": "PATCH",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful."
            },
            "get": {
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "bulkEdit": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "httpMethod": "POST"
                },
                "list": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "httpMethod": "GET",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "replace": {
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "httpMethod": "POST",
                  "description": "Creates a negative keyword in a negative keyword list."
                },
                "delete": {
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "adAssets": {
          "methods": {
            "bulkCreate": {
              "id": "displayvideo.advertisers.adAssets.bulkCreate",
              "path": "v4/advertisers/{+advertiserId}/adAssets:bulkCreate",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets:bulkCreate",
              "httpMethod": "POST",
              "description": "Creates multiple ad assets in a single request. Returns the newly-created ad assets if successful. Only supports the creation of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/adAssets/{+adAssetId}",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets/{adAssetsId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.adAssets.get",
              "description": "Gets an ad asset. Only supports the retrieval of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`."
            },
            "list": {
              "id": "displayvideo.advertisers.adAssets.list",
              "path": "v4/advertisers/{+advertiserId}/adAssets",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets",
              "httpMethod": "GET",
              "description": "Lists ad assets under an advertiser ID. Only supports the retrieval of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "upload": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "supportsMediaUpload": true,
              "description": "Uploads and creates an ad asset. Returns the ID of the newly-created ad asset if successful. Only supports the uploading of assets with the AdAssetType `AD_ASSET_TYPE_IMAGE`.",
              "id": "displayvideo.advertisers.adAssets.upload",
              "path": "v4/advertisers/{+advertiserId}/adAssets:uploadAdAsset",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets:uploadAdAsset",
              "httpMethod": "POST"
            },
            "create": {
              "description": "Creates an ad asset. Returns the newly-created ad asset if successful. Only supports the creation of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "id": "displayvideo.advertisers.adAssets.create",
              "path": "v4/advertisers/{+advertiserId}/adAssets",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "channels": {
          "methods": {
            "get": {
              "description": "Gets a channel for a partner or advertiser.",
              "path": "v4/advertisers/{+advertiserId}/channels/{+channelId}",
              "flatPath": "v4/advertisers/{advertisersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.channels.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "id": "displayvideo.advertisers.channels.patch",
              "path": "v4/advertisers/{+advertiserId}/channels/{channelId}",
              "flatPath": "v4/advertisers/{advertisersId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/channels",
              "flatPath": "v4/advertisers/{advertisersId}/channels",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.channels.create",
              "description": "Creates a new channel. Returns the newly created channel if successful."
            },
            "list": {
              "description": "Lists channels for a partner or advertiser.",
              "id": "displayvideo.advertisers.channels.list",
              "path": "v4/advertisers/{+advertiserId}/channels",
              "flatPath": "v4/advertisers/{advertisersId}/channels",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "bulkEdit": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "httpMethod": "POST"
                },
                "list": {
                  "path": "v4/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "flatPath": "v4/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "description": "Lists sites in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "description": "Creates a site in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "description": "Deletes a site from a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "replace": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites:replace",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors."
                }
              }
            }
          }
        },
        "invoices": {
          "methods": {
            "lookupInvoiceCurrency": {
              "description": "Retrieves the invoice currency used by an advertiser in a given month.",
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "path": "v4/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "flatPath": "v4/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "list": {
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method.",
              "id": "displayvideo.advertisers.invoices.list",
              "path": "v4/advertisers/{+advertiserId}/invoices",
              "flatPath": "v4/advertisers/{advertisersId}/invoices",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "supportsMediaUpload": true,
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "path": "media/{+resourceName}",
          "flatPath": "media/{mediaId}",
          "httpMethod": "POST",
          "id": "displayvideo.media.upload",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ]
        },
        "download": {
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "supportsMediaDownload": true,
          "id": "displayvideo.media.download",
          "path": "download/{+resourceName}",
          "flatPath": "download/{downloadId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ]
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "list": {
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "id": "displayvideo.combinedAudiences.list",
          "path": "v4/combinedAudiences",
          "flatPath": "v4/combinedAudiences",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a combined audience.",
          "path": "v4/combinedAudiences/{+combinedAudienceId}",
          "flatPath": "v4/combinedAudiences/{combinedAudiencesId}",
          "httpMethod": "GET",
          "id": "displayvideo.combinedAudiences.get"
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/sdfdownloadtasks",
          "flatPath": "v4/sdfdownloadtasks",
          "httpMethod": "POST",
          "id": "displayvideo.sdfdownloadtasks.create",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with `sdfdownloadtasks.operations.get`. Any errors can be found in the err[...]"
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "path": "v4/{+name}",
              "flatPath": "v4/sdfdownloadtasks/operations/{operationsId}",
              "httpMethod": "GET",
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ]
            }
          }
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/guaranteedOrders",
          "flatPath": "v4/guaranteedOrders",
          "httpMethod": "POST",
          "id": "displayvideo.guaranteedOrders.create",
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful."
        },
        "editGuaranteedOrderReadAccessors": {
          "description": "Edits read advertisers of a guaranteed order.",
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "path": "v4/guaranteedOrders",
          "flatPath": "v4/guaranteedOrders",
          "httpMethod": "GET",
          "id": "displayvideo.guaranteedOrders.list",
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "id": "displayvideo.guaranteedOrders.get",
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}",
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "GET",
          "description": "Gets a guaranteed order.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "id": "displayvideo.guaranteedOrders.patch",
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}",
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "inventorySourceGroups": {
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.create",
          "path": "v4/inventorySourceGroups",
          "flatPath": "v4/inventorySourceGroups",
          "httpMethod": "POST",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Deletes an inventory source group.",
          "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "DELETE",
          "id": "displayvideo.inventorySourceGroups.delete"
        },
        "get": {
          "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySourceGroups.get",
          "description": "Gets an inventory source group.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "id": "displayvideo.inventorySourceGroups.patch",
          "path": "v4/inventorySourceGroups/{inventorySourceGroupId}",
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/inventorySourceGroups",
          "flatPath": "v4/inventorySourceGroups",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySourceGroups.list",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter."
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "httpMethod": "POST",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create"
            },
            "delete": {
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkEdit": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists inventory sources assigned to an inventory source group.",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "httpMethod": "GET",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list"
            }
          }
        }
      }
    },
    "users": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v4/users/{+userId}",
          "flatPath": "v4/users/{usersId}",
          "httpMethod": "GET",
          "id": "displayvideo.users.get",
          "description": "Gets a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method."
        },
        "bulkEditAssignedUserRoles": {
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature[...]",
          "path": "v4/users/{+userId}:bulkEditAssignedUserRoles",
          "flatPath": "v4/users/{usersId}:bulkEditAssignedUserRoles",
          "httpMethod": "POST",
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "patch": {
          "id": "displayvideo.users.patch",
          "path": "v4/users/{+userId}",
          "flatPath": "v4/users/{usersId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing user. Returns the updated user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v4/users",
          "flatPath": "v4/users",
          "httpMethod": "GET",
          "id": "displayvideo.users.list",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method."
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Creates a new user. Returns the newly created user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "path": "v4/users",
          "flatPath": "v4/users",
          "httpMethod": "POST",
          "id": "displayvideo.users.create"
        },
        "delete": {
          "id": "displayvideo.users.delete",
          "path": "v4/users/{+userId}",
          "flatPath": "v4/users/{usersId}",
          "httpMethod": "DELETE",
          "description": "Deletes a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        }
      }
    },
    "sdfuploadtasks": {
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "id": "displayvideo.sdfuploadtasks.operations.get",
              "path": "v4/{+name}",
              "flatPath": "v4/sdfuploadtasks/operations/{operationsId}",
              "httpMethod": "GET",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds."
            }
          }
        }
      }
    },
    "firstPartyAndPartnerAudiences": {
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/firstPartyAndPartnerAudiences",
          "flatPath": "v4/firstPartyAndPartnerAudiences",
          "httpMethod": "POST",
          "id": "displayvideo.firstPartyAndPartnerAudiences.create",
          "description": "Creates a FirstPartyAndPartnerAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`"
        },
        "editCustomerMatchMembers": {
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}:editCustomerMatchMembers",
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}:editCustomerMatchMembers",
          "httpMethod": "POST",
          "id": "displayvideo.firstPartyAndPartnerAudiences.editCustomerMatchMembers",
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstPartyAndPartnerAudiences.patch",
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}",
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing FirstPartyAndPartnerAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}",
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}",
          "httpMethod": "GET",
          "id": "displayvideo.firstPartyAndPartnerAudiences.get",
          "description": "Gets a first party or partner audience."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists first party and partner audiences. The order is defined by the order_by parameter.",
          "id": "displayvideo.firstPartyAndPartnerAudiences.list",
          "path": "v4/firstPartyAndPartnerAudiences",
          "flatPath": "v4/firstPartyAndPartnerAudiences",
          "httpMethod": "GET"
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "get": {
              "description": "Gets a single targeting option.",
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists targeting options of a given type.",
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions",
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions",
              "httpMethod": "GET"
            },
            "search": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions:search",
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "httpMethod": "POST"
            }
          }
        }
      }
    },
    "inventorySources": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/inventorySources/{+inventorySourceId}",
          "flatPath": "v4/inventorySources/{inventorySourcesId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.inventorySources.patch",
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets an inventory source.",
          "id": "displayvideo.inventorySources.get",
          "path": "v4/inventorySources/{+inventorySourceId}",
          "flatPath": "v4/inventorySources/{inventorySourcesId}",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "path": "v4/inventorySources",
          "flatPath": "v4/inventorySources",
          "httpMethod": "GET",
          "id": "displayvideo.inventorySources.list"
        },
        "editInventorySourceReadWriteAccessors": {
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source.",
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors",
          "path": "v4/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors",
          "flatPath": "v4/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful.",
          "id": "displayvideo.inventorySources.create",
          "path": "v4/inventorySources",
          "flatPath": "v4/inventorySources",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/floodlightGroups/{+floodlightGroupId}",
          "flatPath": "v4/floodlightGroups/{floodlightGroupsId}",
          "httpMethod": "GET",
          "id": "displayvideo.floodlightGroups.get",
          "description": "Gets a Floodlight group."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.floodlightGroups.patch",
          "path": "v4/floodlightGroups/{floodlightGroupId}",
          "flatPath": "v4/floodlightGroups/{floodlightGroupId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful."
        }
      },
      "resources": {
        "floodlightActivities": {
          "methods": {
            "get": {
              "description": "Gets a Floodlight activity.",
              "id": "displayvideo.floodlightGroups.floodlightActivities.get",
              "path": "v4/floodlightGroups/{+floodlightGroupId}/floodlightActivities/{+floodlightActivityId}",
              "flatPath": "v4/floodlightGroups/{floodlightGroupsId}/floodlightActivities/{floodlightActivitiesId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "description": "Lists Floodlight activities in a Floodlight group.",
              "path": "v4/floodlightGroups/{+floodlightGroupId}/floodlightActivities",
              "flatPath": "v4/floodlightGroups/{floodlightGroupsId}/floodlightActivities",
              "httpMethod": "GET",
              "id": "displayvideo.floodlightGroups.floodlightActivities.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    },
    "customBiddingAlgorithms": {
      "resources": {
        "rules": {
          "methods": {
            "list": {
              "id": "displayvideo.customBiddingAlgorithms.rules.list",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules",
              "httpMethod": "GET",
              "description": "Lists rules resources that belong to the given algorithm. The order is defined by the order_by parameter.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new rules resource. Returns the newly created rules resource if successful. Requests creating a custom bidding rules resource under an algorithm assigned to a line item will return an error.",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules",
              "httpMethod": "POST",
              "id": "displayvideo.customBiddingAlgorithms.rules.create"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules/{+customBiddingAlgorithmRulesId}",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules/{rulesId}",
              "httpMethod": "GET",
              "id": "displayvideo.customBiddingAlgorithms.rules.get",
              "description": "Retrieves a rules resource."
            }
          }
        },
        "scripts": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a custom bidding script.",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "httpMethod": "GET",
              "id": "displayvideo.customBiddingAlgorithms.scripts.get"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "httpMethod": "POST",
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful. Requests creating a custom bidding script under an algorithm assigned to a line item will return an error."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "httpMethod": "GET",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list"
            }
          }
        }
      },
      "methods": {
        "uploadRules": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.uploadRules",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadRules",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadRules",
          "httpMethod": "GET",
          "description": "Creates a rules reference object for an AlgorithmRules file. The resulting reference object provides a resource path where the AlgorithmRules file should be uploaded. This reference object should be included when creating a new CustomBiddingAlgorithmRules resource."
        },
        "list": {
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "path": "v4/customBiddingAlgorithms",
          "flatPath": "v4/customBiddingAlgorithms",
          "httpMethod": "GET",
          "id": "displayvideo.customBiddingAlgorithms.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "uploadScript": {
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "httpMethod": "GET",
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.get",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "httpMethod": "GET",
          "description": "Gets a custom bidding algorithm."
        },
        "patch": {
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful. Requests updating a custom bidding algorithm assigned to a line item will return an error.",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.customBiddingAlgorithms.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "id": "displayvideo.customBiddingAlgorithms.create",
          "path": "v4/customBiddingAlgorithms",
          "flatPath": "v4/customBiddingAlgorithms",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    }
  },
  "version_module": true,
  "kind": "discovery#restDescription",
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true,
  "id": "displayvideo:v4",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "batchPath": "batch",
  "documentationLink": "https://developers.google.com/display-video/",
  "revision": "20260407",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        }
      }
    }
  },
  "title": "Display & Video 360 API",
  "canonicalName": "Display Video",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "name": "displayvideo",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "baseUrl": "https://displayvideo.googleapis.com/"
}