{
  "discoveryVersion": "v1",
  "resources": {
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "search": {
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions:search"
            },
            "get": {
              "description": "Gets a single targeting option.",
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions",
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions",
              "description": "Lists targeting options of a given type.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.targetingTypes.targetingOptions.list"
            }
          }
        }
      }
    },
    "sdfuploadtasks": {
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "flatPath": "v4/sdfuploadtasks/operations/{operationsId}",
              "path": "v4/{+name}",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "id": "displayvideo.sdfuploadtasks.operations.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ]
            }
          }
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "flatPath": "v4/customLists/{customListsId}",
          "path": "v4/customLists/{+customListId}",
          "httpMethod": "GET",
          "id": "displayvideo.customLists.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a custom list."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customLists.list",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "path": "v4/customLists",
          "flatPath": "v4/customLists",
          "httpMethod": "GET"
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "description": "Gets a Floodlight group.",
          "id": "displayvideo.floodlightGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "flatPath": "v4/floodlightGroups/{floodlightGroupsId}",
          "path": "v4/floodlightGroups/{+floodlightGroupId}"
        },
        "patch": {
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "id": "displayvideo.floodlightGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "flatPath": "v4/floodlightGroups/{floodlightGroupId}",
          "path": "v4/floodlightGroups/{floodlightGroupId}"
        }
      },
      "resources": {
        "floodlightActivities": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "flatPath": "v4/floodlightGroups/{floodlightGroupsId}/floodlightActivities/{floodlightActivitiesId}",
              "path": "v4/floodlightGroups/{+floodlightGroupId}/floodlightActivities/{+floodlightActivityId}",
              "description": "Gets a Floodlight activity.",
              "id": "displayvideo.floodlightGroups.floodlightActivities.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "id": "displayvideo.floodlightGroups.floodlightActivities.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists Floodlight activities in a Floodlight group.",
              "flatPath": "v4/floodlightGroups/{floodlightGroupsId}/floodlightActivities",
              "path": "v4/floodlightGroups/{+floodlightGroupId}/floodlightActivities",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "advertisers": {
      "methods": {
        "listAssignedTargetingOptions": {
          "path": "v4/advertisers/{+advertiserId}:listAssignedTargetingOptions",
          "flatPath": "v4/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "description": "Lists assigned targeting options of an advertiser across targeting types."
        },
        "create": {
          "id": "displayvideo.advertisers.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
          "flatPath": "v4/advertisers",
          "path": "v4/advertisers",
          "httpMethod": "POST"
        },
        "audit": {
          "httpMethod": "GET",
          "path": "v4/advertisers/{+advertiserId}:audit",
          "flatPath": "v4/advertisers/{advertisersId}:audit",
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.audit"
        },
        "delete": {
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "id": "displayvideo.advertisers.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "DELETE",
          "flatPath": "v4/advertisers/{advertisersId}",
          "path": "v4/advertisers/{+advertiserId}"
        },
        "editAssignedTargetingOptions": {
          "httpMethod": "POST",
          "flatPath": "v4/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "path": "v4/advertisers/{+advertiserId}:editAssignedTargetingOptions",
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "id": "displayvideo.advertisers.editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "id": "displayvideo.advertisers.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets an advertiser.",
          "flatPath": "v4/advertisers/{advertisersId}",
          "path": "v4/advertisers/{+advertiserId}",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.list",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "path": "v4/advertisers",
          "flatPath": "v4/advertisers",
          "httpMethod": "GET"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.patch",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "path": "v4/advertisers/{+advertiserId}",
          "flatPath": "v4/advertisers/{advertisersId}",
          "httpMethod": "PATCH"
        }
      },
      "resources": {
        "adGroups": {
          "methods": {
            "bulkListAssignedTargetingOptions": {
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/adGroups:bulkListAssignedTargetingOptions",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups:bulkListAssignedTargetingOptions",
              "description": "Lists assigned targeting options for multiple ad groups across targeting types. Inherited assigned targeting options are not included.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.bulkListAssignedTargetingOptions"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups",
              "path": "v4/advertisers/{+advertiserId}/adGroups",
              "description": "Creates a new ad group. Returns the newly created ad group if successful.",
              "id": "displayvideo.advertisers.adGroups.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkEditAssignedTargetingOptions": {
              "httpMethod": "POST",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups:bulkEditAssignedTargetingOptions",
              "path": "v4/advertisers/{+advertiserId}/adGroups:bulkEditAssignedTargetingOptions",
              "description": "Bulk edits targeting options for multiple ad groups. The same set of delete and create requests will be applied to all specified ad groups. Specifically, the operation will delete the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.delete_requests from each ad group, and then create the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.create_requests. Only ad groups under a line item of line_[...]",
              "id": "displayvideo.advertisers.adGroups.bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.adGroups.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets an ad group."
            },
            "list": {
              "description": "Lists ad groups.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.list",
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/adGroups",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups"
            },
            "patch": {
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.patch",
              "description": "Updates an existing ad group. Returns the updated ad group if successful."
            },
            "delete": {
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.adGroups.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a AdGroup. Returns error code `NOT_FOUND` if the ad group does not exist."
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "delete": {
                      "httpMethod": "DELETE",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "description": "Deletes an assigned targeting option from an ad group. Only ad groups under a line item of line_item_type `LINE_ITEM_TYPE_DEMAND_GEN` are supported for this method.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.delete"
                    },
                    "get": {
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "GET",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Gets a single targeting option assigned to an ad group. Inherited assigned targeting options are not included."
                    },
                    "list": {
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Lists the targeting options assigned to an ad group. Inherited assigned targeting options are not included.",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "GET"
                    },
                    "create": {
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Assigns a targeting option to an ad group. Returns the assigned targeting option if successful. Only ad groups under a line item of line_item_type `LINE_ITEM_TYPE_DEMAND_GEN` are supported for this method."
                    }
                  }
                }
              }
            },
            "youtubeAssetTypes": {
              "resources": {
                "youtubeAssetAssociations": {
                  "methods": {
                    "delete": {
                      "description": "Deletes an existing association between the identified resource and a YouTube asset. *Warning:* This method is only available to an informed subset of users.",
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "DELETE",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations/{youtubeAssetAssociationsId}",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations/{+youtubeAssetAssociationId}"
                    },
                    "create": {
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.create",
                      "description": "Creates a new association between the identified resource and a YouTube asset. Returns the newly-created association. *Warning:* This method is only available to an informed subset of users."
                    },
                    "list": {
                      "description": "Lists the YouTube asset associations linked to the given resource.",
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations"
                    }
                  }
                }
              }
            }
          }
        },
        "channels": {
          "methods": {
            "create": {
              "flatPath": "v4/advertisers/{advertisersId}/channels",
              "path": "v4/advertisers/{+advertiserId}/channels",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.channels.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new channel. Returns the newly created channel if successful."
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/channels/{channelsId}",
              "path": "v4/advertisers/{+advertiserId}/channels/{+channelId}",
              "description": "Gets a channel for a partner or advertiser.",
              "id": "displayvideo.advertisers.channels.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/channels",
              "path": "v4/advertisers/{+advertiserId}/channels",
              "description": "Lists channels for a partner or advertiser.",
              "id": "displayvideo.advertisers.channels.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "description": "Updates a channel. Returns the updated channel if successful.",
              "id": "displayvideo.advertisers.channels.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v4/advertisers/{advertisersId}/channels/{channelId}",
              "path": "v4/advertisers/{+advertiserId}/channels/{channelId}"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "replace": {
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "httpMethod": "POST",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites:replace",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites:replace"
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "description": "Creates a site in a channel.",
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "description": "Deletes a site from a channel."
                },
                "list": {
                  "description": "Lists sites in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "httpMethod": "GET",
                  "path": "v4/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "flatPath": "v4/advertisers/{advertisersId}/channels/{channelsId}/sites"
                }
              }
            }
          }
        },
        "adGroupAds": {
          "methods": {
            "get": {
              "id": "displayvideo.advertisers.adGroupAds.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets an ad group ad.",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds",
              "description": "Lists ad group ads.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroupAds.list"
            },
            "patch": {
              "description": "Updates an ad group ad.",
              "id": "displayvideo.advertisers.adGroupAds.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}"
            },
            "delete": {
              "description": "Deletes an ad group ad.",
              "id": "displayvideo.advertisers.adGroupAds.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}"
            },
            "create": {
              "id": "displayvideo.advertisers.adGroupAds.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates an ad group ad.",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds",
              "httpMethod": "POST"
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "flatPath": "v4/advertisers/{advertisersId}/assets",
              "path": "v4/advertisers/{+advertiserId}/assets",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.assets.upload",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "supportsMediaUpload": true
            }
          }
        },
        "creatives": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "path": "v4/advertisers/{+advertiserId}/creatives",
              "flatPath": "v4/advertisers/{advertisersId}/creatives",
              "description": "Creates a new creative. Returns the newly created creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.create"
            },
            "delete": {
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "DELETE",
              "id": "displayvideo.advertisers.creatives.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request."
            },
            "get": {
              "id": "displayvideo.advertisers.creatives.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a creative.",
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/creatives",
              "flatPath": "v4/advertisers/{advertisersId}/creatives",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.list"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.patch",
              "description": "Updates an existing creative. Returns the updated creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "PATCH"
            }
          }
        },
        "campaigns": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "id": "displayvideo.advertisers.campaigns.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "get": {
              "description": "Gets a campaign.",
              "id": "displayvideo.advertisers.campaigns.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}"
            },
            "list": {
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "id": "displayvideo.advertisers.campaigns.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns",
              "path": "v4/advertisers/{+advertiserId}/campaigns"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.patch"
            },
            "create": {
              "path": "v4/advertisers/{+advertiserId}/campaigns",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.create",
              "description": "Creates a new campaign. Returns the newly created campaign if successful."
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "get": {
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID."
            },
            "list": {
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.negativeKeywordLists.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists negative keyword lists based on a given advertiser id."
            },
            "patch": {
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}"
            },
            "delete": {
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "httpMethod": "DELETE"
            },
            "create": {
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists",
              "httpMethod": "POST"
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "httpMethod": "POST"
                },
                "bulkEdit": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "httpMethod": "POST"
                },
                "replace": {
                  "httpMethod": "POST",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace"
                },
                "list": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists negative keywords in a negative keyword list.",
                  "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "httpMethod": "GET"
                },
                "delete": {
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}"
                }
              }
            }
          }
        },
        "lineItems": {
          "methods": {
            "bulkEditAssignedTargetingOptions": {
              "httpMethod": "POST",
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkUpdate * lineItems.patch * assignedTargetingOp[...]",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions"
            },
            "bulkListAssignedTargetingOptions": {
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "description": "Lists assigned targeting options for multiple line items across targeting types.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions"
            },
            "create": {
              "description": "Creates a new line item. Returns the newly created line item if successful. YouTube & Partners line items cannot be created or updated using the API.",
              "id": "displayvideo.advertisers.lineItems.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems",
              "path": "v4/advertisers/{+advertiserId}/lineItems"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.list",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v4/advertisers/{+advertiserId}/lineItems",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems",
              "httpMethod": "GET"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.patch",
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your de[...]",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "PATCH"
            },
            "bulkUpdate": {
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkUpdate",
              "httpMethod": "POST",
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkUpdate"
            },
            "duplicate": {
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Duplicates a line item. Returns the ID of the created line item if successful. YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors."
            },
            "delete": {
              "id": "displayvideo.advertisers.lineItems.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. YouTube & Partners line items cannot be created or updated using the API.",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "DELETE"
            },
            "get": {
              "description": "Gets a line item.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.get",
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "delete": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * CreateLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "DELETE"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET"
                    },
                    "list": {
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "description": "Lists the targeting options assigned to a line item."
                    },
                    "create": {
                      "httpMethod": "POST",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * DeleteLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            },
            "youtubeAssetTypes": {
              "resources": {
                "youtubeAssetAssociations": {
                  "methods": {
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.delete",
                      "description": "Deletes an existing association between the identified resource and a YouTube asset. *Warning:* This method is only available to an informed subset of users.",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations/{+youtubeAssetAssociationId}",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations/{youtubeAssetAssociationsId}",
                      "httpMethod": "DELETE"
                    },
                    "create": {
                      "httpMethod": "POST",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "description": "Creates a new association between the identified resource and a YouTube asset. Returns the newly-created association. *Warning:* This method is only available to an informed subset of users.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.create"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "description": "Lists the YouTube asset associations linked to the given resource.",
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "locationLists": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists",
              "path": "v4/advertisers/{+advertiserId}/locationLists",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "id": "displayvideo.advertisers.locationLists.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "path": "v4/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.get",
              "description": "Gets a location list."
            },
            "list": {
              "description": "Lists location lists based on a given advertiser id.",
              "id": "displayvideo.advertisers.locationLists.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists",
              "path": "v4/advertisers/{+advertiserId}/locationLists"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v4/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists/{locationListId}",
              "description": "Updates a location list. Returns the updated location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.patch"
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "list": {
                  "description": "Lists locations assigned to a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                },
                "bulkEdit": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in deletedAssignedLocations and then create the assigned locations provided in createdAssignedLocations.",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "httpMethod": "POST"
                },
                "create": {
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "description": "Creates an assignment between a location and a location list."
                },
                "delete": {
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "httpMethod": "DELETE",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes the assignment between a location and a location list."
                }
              }
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.insertionOrders.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders",
              "httpMethod": "POST"
            },
            "get": {
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "id": "displayvideo.advertisers.insertionOrders.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            },
            "list": {
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "id": "displayvideo.advertisers.insertionOrders.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.patch"
            },
            "delete": {
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "httpMethod": "DELETE",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}"
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "POST"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "adAssets": {
          "methods": {
            "create": {
              "path": "v4/advertisers/{+advertiserId}/adAssets",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adAssets.create",
              "description": "Creates an ad asset. Returns the newly-created ad asset if successful. Only supports the creation of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`."
            },
            "get": {
              "id": "displayvideo.advertisers.adAssets.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets an ad asset. Only supports the retrieval of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets/{adAssetsId}",
              "path": "v4/advertisers/{+advertiserId}/adAssets/{+adAssetId}",
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets",
              "path": "v4/advertisers/{+advertiserId}/adAssets",
              "description": "Lists ad assets under an advertiser ID. Only supports the retrieval of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "id": "displayvideo.advertisers.adAssets.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "upload": {
              "httpMethod": "POST",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets:uploadAdAsset",
              "path": "v4/advertisers/{+advertiserId}/adAssets:uploadAdAsset",
              "description": "Uploads and creates an ad asset. Returns the ID of the newly-created ad asset if successful. Only supports the uploading of assets with the AdAssetType `AD_ASSET_TYPE_IMAGE`.",
              "supportsMediaUpload": true,
              "id": "displayvideo.advertisers.adAssets.upload",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkCreate": {
              "description": "Creates multiple ad assets in a single request. Returns the newly-created ad assets if successful. Only supports the creation of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "id": "displayvideo.advertisers.adAssets.bulkCreate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets:bulkCreate",
              "path": "v4/advertisers/{+advertiserId}/adAssets:bulkCreate"
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method.",
              "id": "displayvideo.advertisers.invoices.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/invoices",
              "path": "v4/advertisers/{+advertiserId}/invoices"
            },
            "lookupInvoiceCurrency": {
              "path": "v4/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "flatPath": "v4/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "description": "Retrieves the invoice currency used by an advertiser in a given month."
            }
          }
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "description": "Gets a combined audience.",
          "id": "displayvideo.combinedAudiences.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "flatPath": "v4/combinedAudiences/{combinedAudiencesId}",
          "path": "v4/combinedAudiences/{+combinedAudienceId}"
        },
        "list": {
          "flatPath": "v4/combinedAudiences",
          "path": "v4/combinedAudiences",
          "httpMethod": "GET",
          "id": "displayvideo.combinedAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists combined audiences. The order is defined by the order_by parameter."
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "create": {
          "httpMethod": "POST",
          "path": "v4/guaranteedOrders",
          "flatPath": "v4/guaranteedOrders",
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.create"
        },
        "editGuaranteedOrderReadAccessors": {
          "httpMethod": "POST",
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "description": "Edits read advertisers of a guaranteed order.",
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}",
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.get",
          "description": "Gets a guaranteed order."
        },
        "list": {
          "id": "displayvideo.guaranteedOrders.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "flatPath": "v4/guaranteedOrders",
          "path": "v4/guaranteedOrders",
          "httpMethod": "GET"
        },
        "patch": {
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}",
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.patch",
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful."
        }
      }
    },
    "inventorySourceGroups": {
      "methods": {
        "delete": {
          "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.delete",
          "description": "Deletes an inventory source group."
        },
        "get": {
          "description": "Gets an inventory source group.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.get",
          "httpMethod": "GET",
          "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}",
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.list",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "path": "v4/inventorySourceGroups",
          "flatPath": "v4/inventorySourceGroups",
          "httpMethod": "GET"
        },
        "patch": {
          "id": "displayvideo.inventorySourceGroups.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupId}",
          "path": "v4/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH"
        },
        "create": {
          "id": "displayvideo.inventorySourceGroups.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "flatPath": "v4/inventorySourceGroups",
          "path": "v4/inventorySourceGroups",
          "httpMethod": "POST"
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "delete": {
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}"
            },
            "create": {
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "description": "Creates an assignment between an inventory source and an inventory source group."
            },
            "list": {
              "description": "Lists inventory sources assigned to an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources"
            },
            "bulkEdit": {
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit"
            }
          }
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "id": "displayvideo.googleAudiences.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Google audience.",
          "flatPath": "v4/googleAudiences/{googleAudiencesId}",
          "path": "v4/googleAudiences/{+googleAudienceId}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "id": "displayvideo.googleAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "flatPath": "v4/googleAudiences",
          "path": "v4/googleAudiences"
        }
      }
    },
    "users": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "v4/users/{+userId}",
          "flatPath": "v4/users/{usersId}",
          "description": "Gets a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.get"
        },
        "list": {
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.list",
          "httpMethod": "GET",
          "path": "v4/users",
          "flatPath": "v4/users"
        },
        "patch": {
          "id": "displayvideo.users.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Updates an existing user. Returns the updated user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v4/users/{usersId}",
          "path": "v4/users/{+userId}",
          "httpMethod": "PATCH"
        },
        "delete": {
          "id": "displayvideo.users.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Deletes a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v4/users/{usersId}",
          "path": "v4/users/{+userId}",
          "httpMethod": "DELETE"
        },
        "bulkEditAssignedUserRoles": {
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature[...]",
          "flatPath": "v4/users/{usersId}:bulkEditAssignedUserRoles",
          "path": "v4/users/{+userId}:bulkEditAssignedUserRoles",
          "httpMethod": "POST"
        },
        "create": {
          "id": "displayvideo.users.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Creates a new user. Returns the newly created user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v4/users",
          "path": "v4/users",
          "httpMethod": "POST"
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "id": "displayvideo.sdfdownloadtasks.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with `sdfdownloadtasks.operations.get`. Any errors can be found in the err[...]",
          "flatPath": "v4/sdfdownloadtasks",
          "path": "v4/sdfdownloadtasks",
          "httpMethod": "POST"
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "flatPath": "v4/sdfdownloadtasks/operations/{operationsId}",
              "path": "v4/{+name}",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "partners": {
      "methods": {
        "editAssignedTargetingOptions": {
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "flatPath": "v4/partners/{partnersId}:editAssignedTargetingOptions",
          "path": "v4/partners/{+partnerId}:editAssignedTargetingOptions",
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "path": "v4/partners/{+partnerId}",
          "flatPath": "v4/partners/{partnersId}",
          "description": "Gets a partner.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.partners.get"
        },
        "list": {
          "path": "v4/partners",
          "flatPath": "v4/partners",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.partners.list",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter."
        }
      },
      "resources": {
        "channels": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "flatPath": "v4/partners/{partnersId}/channels",
              "path": "v4/partners/{+partnerId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "id": "displayvideo.partners.channels.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "description": "Gets a channel for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.get",
              "httpMethod": "GET",
              "path": "v4/partners/{+partnerId}/channels/{+channelId}",
              "flatPath": "v4/partners/{partnersId}/channels/{channelsId}"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v4/partners/{+partnerId}/channels",
              "flatPath": "v4/partners/{partnersId}/channels",
              "description": "Lists channels for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.list"
            },
            "patch": {
              "id": "displayvideo.partners.channels.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates a channel. Returns the updated channel if successful.",
              "flatPath": "v4/partners/{partnersId}/channels/{channelId}",
              "path": "v4/partners/{+partnerId}/channels/{channelId}",
              "httpMethod": "PATCH"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "replace": {
                  "httpMethod": "POST",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "id": "displayvideo.partners.channels.sites.replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "httpMethod": "POST",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit"
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites",
                  "description": "Creates a site in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.create"
                },
                "delete": {
                  "id": "displayvideo.partners.channels.sites.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes a site from a channel.",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "description": "Lists sites in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.list",
                  "httpMethod": "GET",
                  "path": "v4/partners/{+partnerId}/channels/{+channelId}/sites",
                  "flatPath": "v4/partners/{partnersId}/channels/{channelsId}/sites"
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "description": "Deletes an assigned targeting option from a partner.",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "GET",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Gets a single targeting option assigned to a partner."
                },
                "list": {
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Lists the targeting options assigned to a partner."
                },
                "create": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "POST"
                }
              }
            }
          }
        }
      }
    },
    "inventorySources": {
      "methods": {
        "editInventorySourceReadWriteAccessors": {
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors",
          "httpMethod": "POST",
          "path": "v4/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors",
          "flatPath": "v4/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.get",
          "description": "Gets an inventory source.",
          "path": "v4/inventorySources/{+inventorySourceId}",
          "flatPath": "v4/inventorySources/{inventorySourcesId}",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "path": "v4/inventorySources",
          "flatPath": "v4/inventorySources",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.list"
        },
        "patch": {
          "id": "displayvideo.inventorySources.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful.",
          "flatPath": "v4/inventorySources/{inventorySourcesId}",
          "path": "v4/inventorySources/{+inventorySourceId}",
          "httpMethod": "PATCH"
        },
        "create": {
          "path": "v4/inventorySources",
          "flatPath": "v4/inventorySources",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.create",
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful."
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "uploadScript": {
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object."
        },
        "get": {
          "httpMethod": "GET",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "description": "Gets a custom bidding algorithm.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.get"
        },
        "list": {
          "id": "displayvideo.customBiddingAlgorithms.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "flatPath": "v4/customBiddingAlgorithms",
          "path": "v4/customBiddingAlgorithms",
          "httpMethod": "GET"
        },
        "patch": {
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.patch",
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful. Requests updating a custom bidding algorithm assigned to a line item will return an error."
        },
        "uploadRules": {
          "httpMethod": "GET",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadRules",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadRules",
          "description": "Creates a rules reference object for an AlgorithmRules file. The resulting reference object provides a resource path where the AlgorithmRules file should be uploaded. This reference object should be included when creating a new CustomBiddingAlgorithmRules resource.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.uploadRules"
        },
        "create": {
          "httpMethod": "POST",
          "path": "v4/customBiddingAlgorithms",
          "flatPath": "v4/customBiddingAlgorithms",
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.create"
        }
      },
      "resources": {
        "scripts": {
          "methods": {
            "create": {
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful. Requests creating a custom bidding script under an algorithm assigned to a line item will return an error."
            },
            "get": {
              "httpMethod": "GET",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "description": "Gets a custom bidding script.",
              "id": "displayvideo.customBiddingAlgorithms.scripts.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "rules": {
          "methods": {
            "get": {
              "description": "Retrieves a rules resource.",
              "id": "displayvideo.customBiddingAlgorithms.rules.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules/{rulesId}",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules/{+customBiddingAlgorithmRulesId}"
            },
            "list": {
              "id": "displayvideo.customBiddingAlgorithms.rules.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists rules resources that belong to the given algorithm. The order is defined by the order_by parameter.",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "description": "Creates a new rules resource. Returns the newly created rules resource if successful. Requests creating a custom bidding rules resource under an algorithm assigned to a line item will return an error.",
              "id": "displayvideo.customBiddingAlgorithms.rules.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    },
    "firstPartyAndPartnerAudiences": {
      "methods": {
        "editCustomerMatchMembers": {
          "httpMethod": "POST",
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}:editCustomerMatchMembers",
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}:editCustomerMatchMembers",
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstPartyAndPartnerAudiences.editCustomerMatchMembers"
        },
        "get": {
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}",
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstPartyAndPartnerAudiences.get",
          "description": "Gets a first party or partner audience."
        },
        "list": {
          "id": "displayvideo.firstPartyAndPartnerAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists first party and partner audiences. The order is defined by the order_by parameter.",
          "flatPath": "v4/firstPartyAndPartnerAudiences",
          "path": "v4/firstPartyAndPartnerAudiences",
          "httpMethod": "GET"
        },
        "patch": {
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}",
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.firstPartyAndPartnerAudiences.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing FirstPartyAndPartnerAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`"
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstPartyAndPartnerAudiences.create",
          "description": "Creates a FirstPartyAndPartnerAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "path": "v4/firstPartyAndPartnerAudiences",
          "flatPath": "v4/firstPartyAndPartnerAudiences",
          "httpMethod": "POST"
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "supportsMediaUpload": true,
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "id": "displayvideo.media.upload",
          "httpMethod": "POST",
          "path": "media/{+resourceName}",
          "flatPath": "media/{mediaId}"
        },
        "download": {
          "httpMethod": "GET",
          "flatPath": "download/{downloadId}",
          "path": "download/{+resourceName}",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "supportsMediaDownload": true,
          "id": "displayvideo.media.download",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ]
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "basePath": "",
  "ownerName": "Google",
  "protocol": "rest",
  "title": "Display & Video 360 API",
  "revision": "20260310",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "id": "displayvideo:v4",
  "name": "displayvideo",
  "documentationLink": "https://developers.google.com/display-video/",
  "servicePath": "",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "fullyEncodeReservedExpansion": true,
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "ownerDomain": "google.com",
  "version": "v4",
  "batchPath": "batch",
  "canonicalName": "Display Video",
  "version_module": true
}