{
  "protocol": "rest",
  "ownerName": "Google",
  "canonicalName": "Display Video",
  "name": "displayvideo",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "documentationLink": "https://developers.google.com/display-video/",
  "id": "displayvideo:v4",
  "title": "Display & Video 360 API",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "version_module": true,
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        }
      }
    }
  },
  "revision": "20260412",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "basePath": "",
  "servicePath": "",
  "resources": {
    "inventorySourceGroups": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "path": "v4/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.list",
          "flatPath": "v4/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.patch",
          "path": "v4/inventorySourceGroups/{inventorySourceGroupId}",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "httpMethod": "PATCH"
        },
        "create": {
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "path": "v4/inventorySourceGroups",
          "httpMethod": "POST",
          "flatPath": "v4/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.create"
        },
        "delete": {
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.delete",
          "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}",
          "description": "Deletes an inventory source group.",
          "httpMethod": "DELETE"
        },
        "get": {
          "httpMethod": "GET",
          "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}",
          "description": "Gets an inventory source group.",
          "id": "displayvideo.inventorySourceGroups.get",
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "description": "Lists inventory sources assigned to an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "httpMethod": "POST"
            },
            "delete": {
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "httpMethod": "DELETE"
            },
            "bulkEdit": {
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "httpMethod": "POST",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit"
            }
          }
        }
      }
    },
    "partners": {
      "methods": {
        "get": {
          "flatPath": "v4/partners/{partnersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.partners.get",
          "description": "Gets a partner.",
          "path": "v4/partners/{+partnerId}",
          "httpMethod": "GET"
        },
        "editAssignedTargetingOptions": {
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "flatPath": "v4/partners/{partnersId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "path": "v4/partners/{+partnerId}:editAssignedTargetingOptions",
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests ."
        },
        "list": {
          "flatPath": "v4/partners",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.partners.list",
          "path": "v4/partners",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to a partner.",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "httpMethod": "POST"
                },
                "delete": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "description": "Deletes an assigned targeting option from a partner."
                },
                "get": {
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "channels": {
          "methods": {
            "create": {
              "path": "v4/partners/{+partnerId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "httpMethod": "POST",
              "flatPath": "v4/partners/{partnersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.create"
            },
            "get": {
              "description": "Gets a channel for a partner or advertiser.",
              "path": "v4/partners/{+partnerId}/channels/{+channelId}",
              "httpMethod": "GET",
              "flatPath": "v4/partners/{partnersId}/channels/{channelsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.get"
            },
            "patch": {
              "description": "Updates a channel. Returns the updated channel if successful.",
              "path": "v4/partners/{+partnerId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "flatPath": "v4/partners/{partnersId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.patch"
            },
            "list": {
              "description": "Lists channels for a partner or advertiser.",
              "path": "v4/partners/{+partnerId}/channels",
              "httpMethod": "GET",
              "flatPath": "v4/partners/{partnersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.list"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "list": {
                  "flatPath": "v4/partners/{partnersId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.list",
                  "path": "v4/partners/{+partnerId}/channels/{+channelId}/sites",
                  "description": "Lists sites in a channel.",
                  "httpMethod": "GET"
                },
                "replace": {
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "httpMethod": "POST",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.replace"
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites",
                  "description": "Creates a site in a channel.",
                  "id": "displayvideo.partners.channels.sites.create",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "description": "Deletes a site from a channel.",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites."
                }
              }
            }
          }
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "uploadRules": {
          "id": "displayvideo.customBiddingAlgorithms.uploadRules",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadRules",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadRules",
          "description": "Creates a rules reference object for an AlgorithmRules file. The resulting reference object provides a resource path where the AlgorithmRules file should be uploaded. This reference object should be included when creating a new CustomBiddingAlgorithmRules resource."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a custom bidding algorithm.",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "id": "displayvideo.customBiddingAlgorithms.get",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "httpMethod": "POST",
          "path": "v4/customBiddingAlgorithms",
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "id": "displayvideo.customBiddingAlgorithms.create",
          "flatPath": "v4/customBiddingAlgorithms",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "id": "displayvideo.customBiddingAlgorithms.list",
          "flatPath": "v4/customBiddingAlgorithms",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "path": "v4/customBiddingAlgorithms"
        },
        "uploadScript": {
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript"
        },
        "patch": {
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful. Requests updating a custom bidding algorithm assigned to a line item will return an error.",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "httpMethod": "PATCH",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.patch"
        }
      },
      "resources": {
        "rules": {
          "methods": {
            "list": {
              "id": "displayvideo.customBiddingAlgorithms.rules.list",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "description": "Lists rules resources that belong to the given algorithm. The order is defined by the order_by parameter."
            },
            "get": {
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules/{+customBiddingAlgorithmRulesId}",
              "description": "Retrieves a rules resource.",
              "httpMethod": "GET",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules/{rulesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.rules.get"
            },
            "create": {
              "description": "Creates a new rules resource. Returns the newly created rules resource if successful. Requests creating a custom bidding rules resource under an algorithm assigned to a line item will return an error.",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "httpMethod": "POST",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.rules.create"
            }
          }
        },
        "scripts": {
          "methods": {
            "get": {
              "id": "displayvideo.customBiddingAlgorithms.scripts.get",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "description": "Gets a custom bidding script."
            },
            "create": {
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful. Requests creating a custom bidding script under an algorithm assigned to a line item will return an error.",
              "httpMethod": "POST",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.scripts.create"
            },
            "list": {
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.scripts.list",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "firstPartyAndPartnerAudiences": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets a first party or partner audience.",
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}",
          "id": "displayvideo.firstPartyAndPartnerAudiences.get",
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "id": "displayvideo.firstPartyAndPartnerAudiences.create",
          "flatPath": "v4/firstPartyAndPartnerAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "path": "v4/firstPartyAndPartnerAudiences",
          "description": "Creates a FirstPartyAndPartnerAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`"
        },
        "list": {
          "description": "Lists first party and partner audiences. The order is defined by the order_by parameter.",
          "path": "v4/firstPartyAndPartnerAudiences",
          "httpMethod": "GET",
          "flatPath": "v4/firstPartyAndPartnerAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstPartyAndPartnerAudiences.list"
        },
        "patch": {
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstPartyAndPartnerAudiences.patch",
          "description": "Updates an existing FirstPartyAndPartnerAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}",
          "httpMethod": "PATCH"
        },
        "editCustomerMatchMembers": {
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}:editCustomerMatchMembers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstPartyAndPartnerAudiences.editCustomerMatchMembers",
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}:editCustomerMatchMembers",
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "httpMethod": "POST"
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "httpMethod": "POST",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with `sdfdownloadtasks.operations.get`. Any errors can be found in the err[...]",
          "path": "v4/sdfdownloadtasks",
          "id": "displayvideo.sdfdownloadtasks.create",
          "flatPath": "v4/sdfdownloadtasks",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "flatPath": "v4/sdfdownloadtasks/operations/{operationsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "path": "v4/{+name}",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "list": {
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions",
              "description": "Lists targeting options of a given type.",
              "httpMethod": "GET",
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.targetingTypes.targetingOptions.list"
            },
            "search": {
              "httpMethod": "POST",
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions:search",
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "description": "Gets a single targeting option.",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "path": "media/{+resourceName}",
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "id": "displayvideo.media.upload",
          "flatPath": "media/{mediaId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ]
        },
        "download": {
          "httpMethod": "GET",
          "path": "download/{+resourceName}",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "id": "displayvideo.media.download",
          "flatPath": "download/{downloadId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "supportsMediaDownload": true
        }
      }
    },
    "advertisers": {
      "methods": {
        "editAssignedTargetingOptions": {
          "flatPath": "v4/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.editAssignedTargetingOptions",
          "path": "v4/advertisers/{+advertiserId}:editAssignedTargetingOptions",
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "httpMethod": "POST"
        },
        "listAssignedTargetingOptions": {
          "flatPath": "v4/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "path": "v4/advertisers/{+advertiserId}:listAssignedTargetingOptions",
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "httpMethod": "GET"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "path": "v4/advertisers/{+advertiserId}",
          "id": "displayvideo.advertisers.patch",
          "flatPath": "v4/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "id": "displayvideo.advertisers.list",
          "flatPath": "v4/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "path": "v4/advertisers"
        },
        "create": {
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
          "path": "v4/advertisers",
          "httpMethod": "POST",
          "flatPath": "v4/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.create"
        },
        "delete": {
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "path": "v4/advertisers/{+advertiserId}",
          "httpMethod": "DELETE",
          "flatPath": "v4/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.delete"
        },
        "get": {
          "path": "v4/advertisers/{+advertiserId}",
          "description": "Gets an advertiser.",
          "httpMethod": "GET",
          "flatPath": "v4/advertisers/{advertisersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.get"
        },
        "audit": {
          "path": "v4/advertisers/{+advertiserId}:audit",
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "httpMethod": "GET",
          "flatPath": "v4/advertisers/{advertisersId}:audit",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.audit"
        }
      },
      "resources": {
        "creatives": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates an existing creative. Returns the updated creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "id": "displayvideo.advertisers.creatives.patch",
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "id": "displayvideo.advertisers.creatives.list",
              "flatPath": "v4/advertisers/{advertisersId}/creatives",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v4/advertisers/{+advertiserId}/creatives"
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates a new creative. Returns the newly created creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "path": "v4/advertisers/{+advertiserId}/creatives",
              "id": "displayvideo.advertisers.creatives.create",
              "flatPath": "v4/advertisers/{advertisersId}/creatives",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.delete",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "httpMethod": "DELETE"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets a creative.",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "id": "displayvideo.advertisers.creatives.get",
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "id": "displayvideo.advertisers.invoices.list",
              "flatPath": "v4/advertisers/{advertisersId}/invoices",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/invoices",
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method."
            },
            "lookupInvoiceCurrency": {
              "flatPath": "v4/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "description": "Retrieves the invoice currency used by an advertiser in a given month.",
              "path": "v4/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "httpMethod": "GET"
            }
          }
        },
        "adAssets": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "description": "Gets an ad asset. Only supports the retrieval of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "path": "v4/advertisers/{+advertiserId}/adAssets/{+adAssetId}",
              "id": "displayvideo.advertisers.adAssets.get",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets/{adAssetsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "id": "displayvideo.advertisers.adAssets.create",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "description": "Creates an ad asset. Returns the newly-created ad asset if successful. Only supports the creation of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "path": "v4/advertisers/{+advertiserId}/adAssets"
            },
            "list": {
              "path": "v4/advertisers/{+advertiserId}/adAssets",
              "description": "Lists ad assets under an advertiser ID. Only supports the retrieval of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adAssets.list"
            },
            "upload": {
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "description": "Uploads and creates an ad asset. Returns the ID of the newly-created ad asset if successful. Only supports the uploading of assets with the AdAssetType `AD_ASSET_TYPE_IMAGE`.",
              "path": "v4/advertisers/{+advertiserId}/adAssets:uploadAdAsset",
              "id": "displayvideo.advertisers.adAssets.upload",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets:uploadAdAsset",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkCreate": {
              "httpMethod": "POST",
              "path": "v4/advertisers/{+advertiserId}/adAssets:bulkCreate",
              "description": "Creates multiple ad assets in a single request. Returns the newly-created ad assets if successful. Only supports the creation of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "id": "displayvideo.advertisers.adAssets.bulkCreate",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets:bulkCreate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "lineItems": {
          "methods": {
            "bulkListAssignedTargetingOptions": {
              "description": "Lists assigned targeting options for multiple line items across targeting types.",
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions",
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions"
            },
            "bulkUpdate": {
              "id": "displayvideo.advertisers.lineItems.bulkUpdate",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API."
            },
            "bulkEditAssignedTargetingOptions": {
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkUpdate * lineItems.patch * assignedTargetingOp[...]",
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST"
            },
            "delete": {
              "id": "displayvideo.advertisers.lineItems.delete",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. YouTube & Partners line items cannot be created or updated using the API.",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}"
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your de[...]",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "id": "displayvideo.advertisers.lineItems.patch",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.get",
              "description": "Gets a line item.",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "GET"
            },
            "duplicate": {
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful. YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "httpMethod": "POST",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.duplicate"
            },
            "create": {
              "description": "Creates a new line item. Returns the newly created line item if successful. YouTube & Partners line items cannot be created or updated using the API.",
              "path": "v4/advertisers/{+advertiserId}/lineItems",
              "httpMethod": "POST",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.create"
            },
            "list": {
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v4/advertisers/{+advertiserId}/lineItems",
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.list"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "create": {
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * DeleteLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create"
                    },
                    "delete": {
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * CreateLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "DELETE",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete"
                    },
                    "get": {
                      "httpMethod": "GET",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "list": {
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "description": "Lists the targeting options assigned to a line item.",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            },
            "youtubeAssetTypes": {
              "resources": {
                "youtubeAssetAssociations": {
                  "methods": {
                    "create": {
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.create",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "POST",
                      "description": "Creates a new association between the identified resource and a YouTube asset. Returns the newly-created association. *Warning:* This method is only available to an informed subset of users.",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations"
                    },
                    "delete": {
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations/{youtubeAssetAssociationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.delete",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations/{+youtubeAssetAssociationId}",
                      "description": "Deletes an existing association between the identified resource and a YouTube asset. *Warning:* This method is only available to an informed subset of users.",
                      "httpMethod": "DELETE"
                    },
                    "list": {
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.list",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "description": "Lists the YouTube asset associations linked to the given resource.",
                      "httpMethod": "GET"
                    }
                  }
                }
              }
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "id": "displayvideo.advertisers.assets.upload",
              "flatPath": "v4/advertisers/{advertisersId}/assets",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "path": "v4/advertisers/{+advertiserId}/assets",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset)."
            }
          }
        },
        "locationLists": {
          "methods": {
            "get": {
              "flatPath": "v4/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.get",
              "path": "v4/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "description": "Gets a location list.",
              "httpMethod": "GET"
            },
            "patch": {
              "description": "Updates a location list. Returns the updated location list if successful.",
              "path": "v4/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "httpMethod": "PATCH",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists/{locationListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.patch"
            },
            "create": {
              "id": "displayvideo.advertisers.locationLists.create",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "path": "v4/advertisers/{+advertiserId}/locationLists"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/locationLists",
              "description": "Lists location lists based on a given advertiser id.",
              "id": "displayvideo.advertisers.locationLists.list",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "list": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "description": "Lists locations assigned to a location list."
                },
                "bulkEdit": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in deletedAssignedLocations and then create the assigned locations provided in createdAssignedLocations."
                },
                "create": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates an assignment between a location and a location list.",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                },
                "delete": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "description": "Deletes the assignment between a location and a location list."
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "create": {
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "httpMethod": "POST"
                },
                "delete": {
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "httpMethod": "GET",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get"
                },
                "list": {
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "adGroupAds": {
          "methods": {
            "list": {
              "id": "displayvideo.advertisers.adGroupAds.list",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Lists ad group ads.",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "description": "Updates an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "id": "displayvideo.advertisers.adGroupAds.patch",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "id": "displayvideo.advertisers.adGroupAds.get",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Gets an ad group ad.",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds",
              "description": "Creates an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "id": "displayvideo.advertisers.adGroupAds.create",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "description": "Deletes an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "httpMethod": "DELETE",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroupAds.delete"
            }
          }
        },
        "campaigns": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v4/advertisers/{+advertiserId}/campaigns",
              "id": "displayvideo.advertisers.campaigns.list",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "patch": {
              "id": "displayvideo.advertisers.campaigns.patch",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "PATCH",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}"
            },
            "get": {
              "id": "displayvideo.advertisers.campaigns.get",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "description": "Gets a campaign."
            },
            "create": {
              "id": "displayvideo.advertisers.campaigns.create",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "POST",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "path": "v4/advertisers/{+advertiserId}/campaigns"
            },
            "delete": {
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "DELETE",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.delete"
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists",
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "httpMethod": "DELETE",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "httpMethod": "PATCH"
            },
            "list": {
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.list"
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "list": {
                  "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "httpMethod": "GET"
                },
                "replace": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace",
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords."
                },
                "create": {
                  "httpMethod": "POST",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "httpMethod": "POST",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit"
                }
              }
            }
          }
        },
        "channels": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/channels",
              "description": "Lists channels for a partner or advertiser.",
              "id": "displayvideo.advertisers.channels.list",
              "flatPath": "v4/advertisers/{advertisersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "description": "Gets a channel for a partner or advertiser.",
              "path": "v4/advertisers/{+advertiserId}/channels/{+channelId}",
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/channels/{channelsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.get"
            },
            "patch": {
              "id": "displayvideo.advertisers.channels.patch",
              "flatPath": "v4/advertisers/{advertisersId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "path": "v4/advertisers/{+advertiserId}/channels/{channelId}"
            },
            "create": {
              "path": "v4/advertisers/{+advertiserId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "httpMethod": "POST",
              "flatPath": "v4/advertisers/{advertisersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.create"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "list": {
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "flatPath": "v4/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "path": "v4/advertisers/{+advertiserId}/channels/{+channelId}/sites"
                },
                "replace": {
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites:replace",
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "description": "Creates a site in a channel.",
                  "httpMethod": "POST",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.create"
                },
                "delete": {
                  "id": "displayvideo.advertisers.channels.sites.delete",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "description": "Deletes a site from a channel."
                },
                "bulkEdit": {
                  "httpMethod": "POST",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "adGroups": {
          "methods": {
            "bulkListAssignedTargetingOptions": {
              "httpMethod": "GET",
              "path": "v4/advertisers/{+advertiserId}/adGroups:bulkListAssignedTargetingOptions",
              "description": "Lists assigned targeting options for multiple ad groups across targeting types. Inherited assigned targeting options are not included.",
              "id": "displayvideo.advertisers.adGroups.bulkListAssignedTargetingOptions",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups:bulkListAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkEditAssignedTargetingOptions": {
              "flatPath": "v4/advertisers/{advertisersId}/adGroups:bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.bulkEditAssignedTargetingOptions",
              "description": "Bulk edits targeting options for multiple ad groups. The same set of delete and create requests will be applied to all specified ad groups. Specifically, the operation will delete the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.delete_requests from each ad group, and then create the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.create_requests. This method is only supported for Demand [...]",
              "path": "v4/advertisers/{+advertiserId}/adGroups:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST"
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets an ad group.",
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "id": "displayvideo.advertisers.adGroups.get",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "id": "displayvideo.advertisers.adGroups.create",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "description": "Creates a new ad group. Returns the newly created ad group if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "path": "v4/advertisers/{+advertiserId}/adGroups"
            },
            "delete": {
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.delete",
              "description": "Deletes a AdGroup. Returns error code `NOT_FOUND` if the ad group does not exist. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "httpMethod": "DELETE"
            },
            "list": {
              "flatPath": "v4/advertisers/{advertisersId}/adGroups",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.list",
              "description": "Lists ad groups.",
              "path": "v4/advertisers/{+advertiserId}/adGroups",
              "httpMethod": "GET"
            },
            "patch": {
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.patch",
              "description": "Updates an existing ad group. Returns the updated ad group if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "httpMethod": "PATCH"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "description": "Lists the targeting options assigned to an ad group. Inherited assigned targeting options are not included.",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.list",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "create": {
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.create",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "POST",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "description": "Assigns a targeting option to an ad group. Returns the assigned targeting option if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users."
                    },
                    "delete": {
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.delete",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Deletes an assigned targeting option from an ad group. This method is only supported for Demand Gen ad groups with the AdGroupFormat `AD_GROUP_FORMAT_DEMAND_GEN`. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
                      "httpMethod": "DELETE"
                    },
                    "get": {
                      "httpMethod": "GET",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "description": "Gets a single targeting option assigned to an ad group. Inherited assigned targeting options are not included.",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.get",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    }
                  }
                }
              }
            },
            "youtubeAssetTypes": {
              "resources": {
                "youtubeAssetAssociations": {
                  "methods": {
                    "list": {
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.list",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "GET",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "description": "Lists the YouTube asset associations linked to the given resource."
                    },
                    "create": {
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.create",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "POST",
                      "description": "Creates a new association between the identified resource and a YouTube asset. Returns the newly-created association. *Warning:* This method is only available to an informed subset of users.",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations"
                    },
                    "delete": {
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations/{youtubeAssetAssociationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.delete",
                      "description": "Deletes an existing association between the identified resource and a YouTube asset. *Warning:* This method is only available to an informed subset of users.",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations/{+youtubeAssetAssociationId}",
                      "httpMethod": "DELETE"
                    }
                  }
                }
              }
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders",
              "id": "displayvideo.advertisers.insertionOrders.list",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "GET",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.get"
            },
            "create": {
              "path": "v4/advertisers/{+advertiserId}/insertionOrders",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "httpMethod": "POST",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.create"
            },
            "delete": {
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}"
            }
          }
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "path": "v4/floodlightGroups/{+floodlightGroupId}",
          "description": "Gets a Floodlight group.",
          "httpMethod": "GET",
          "flatPath": "v4/floodlightGroups/{floodlightGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.floodlightGroups.get"
        },
        "patch": {
          "path": "v4/floodlightGroups/{floodlightGroupId}",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "httpMethod": "PATCH",
          "flatPath": "v4/floodlightGroups/{floodlightGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.floodlightGroups.patch"
        }
      },
      "resources": {
        "floodlightActivities": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "path": "v4/floodlightGroups/{+floodlightGroupId}/floodlightActivities/{+floodlightActivityId}",
              "description": "Gets a Floodlight activity.",
              "id": "displayvideo.floodlightGroups.floodlightActivities.get",
              "flatPath": "v4/floodlightGroups/{floodlightGroupsId}/floodlightActivities/{floodlightActivitiesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "flatPath": "v4/floodlightGroups/{floodlightGroupsId}/floodlightActivities",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.floodlightGroups.floodlightActivities.list",
              "path": "v4/floodlightGroups/{+floodlightGroupId}/floodlightActivities",
              "description": "Lists Floodlight activities in a Floodlight group.",
              "httpMethod": "GET"
            }
          }
        }
      }
    },
    "inventorySources": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "path": "v4/inventorySources",
          "id": "displayvideo.inventorySources.list",
          "flatPath": "v4/inventorySources",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "editInventorySourceReadWriteAccessors": {
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors",
          "flatPath": "v4/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "path": "v4/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors",
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source."
        },
        "patch": {
          "flatPath": "v4/inventorySources/{inventorySourcesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.patch",
          "path": "v4/inventorySources/{+inventorySourceId}",
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful.",
          "httpMethod": "PATCH"
        },
        "get": {
          "description": "Gets an inventory source.",
          "path": "v4/inventorySources/{+inventorySourceId}",
          "httpMethod": "GET",
          "flatPath": "v4/inventorySources/{inventorySourcesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.get"
        },
        "create": {
          "id": "displayvideo.inventorySources.create",
          "flatPath": "v4/inventorySources",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful.",
          "path": "v4/inventorySources"
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "path": "v4/customLists/{+customListId}",
          "description": "Gets a custom list.",
          "httpMethod": "GET",
          "flatPath": "v4/customLists/{customListsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customLists.get"
        },
        "list": {
          "flatPath": "v4/customLists",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customLists.list",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "path": "v4/customLists",
          "httpMethod": "GET"
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets a Google audience.",
          "path": "v4/googleAudiences/{+googleAudienceId}",
          "id": "displayvideo.googleAudiences.get",
          "flatPath": "v4/googleAudiences/{googleAudiencesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "flatPath": "v4/googleAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.googleAudiences.list",
          "path": "v4/googleAudiences",
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "httpMethod": "GET"
        }
      }
    },
    "sdfuploadtasks": {
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "id": "displayvideo.sdfuploadtasks.operations.get",
              "flatPath": "v4/sdfuploadtasks/operations/{operationsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "httpMethod": "GET",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "path": "v4/{+name}"
            }
          }
        }
      }
    },
    "users": {
      "methods": {
        "bulkEditAssignedUserRoles": {
          "path": "v4/users/{+userId}:bulkEditAssignedUserRoles",
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature[...]",
          "httpMethod": "POST",
          "flatPath": "v4/users/{usersId}:bulkEditAssignedUserRoles",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.bulkEditAssignedUserRoles"
        },
        "list": {
          "path": "v4/users",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "httpMethod": "GET",
          "flatPath": "v4/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.list"
        },
        "patch": {
          "id": "displayvideo.users.patch",
          "flatPath": "v4/users/{usersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing user. Returns the updated user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "path": "v4/users/{+userId}"
        },
        "create": {
          "path": "v4/users",
          "description": "Creates a new user. Returns the newly created user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "httpMethod": "POST",
          "flatPath": "v4/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.create"
        },
        "delete": {
          "id": "displayvideo.users.delete",
          "flatPath": "v4/users/{usersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "DELETE",
          "path": "v4/users/{+userId}",
          "description": "Deletes a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method."
        },
        "get": {
          "flatPath": "v4/users/{usersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.get",
          "description": "Gets a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "path": "v4/users/{+userId}",
          "httpMethod": "GET"
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "create": {
          "id": "displayvideo.guaranteedOrders.create",
          "flatPath": "v4/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "path": "v4/guaranteedOrders",
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful."
        },
        "get": {
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.get",
          "description": "Gets a guaranteed order.",
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}",
          "httpMethod": "GET"
        },
        "editGuaranteedOrderReadAccessors": {
          "description": "Edits read advertisers of a guaranteed order.",
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "httpMethod": "POST",
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors"
        },
        "list": {
          "httpMethod": "GET",
          "path": "v4/guaranteedOrders",
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "id": "displayvideo.guaranteedOrders.list",
          "flatPath": "v4/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}",
          "id": "displayvideo.guaranteedOrders.patch",
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "flatPath": "v4/combinedAudiences/{combinedAudiencesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.combinedAudiences.get",
          "description": "Gets a combined audience.",
          "path": "v4/combinedAudiences/{+combinedAudienceId}",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "path": "v4/combinedAudiences",
          "httpMethod": "GET",
          "flatPath": "v4/combinedAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.combinedAudiences.list"
        }
      }
    }
  },
  "version": "v4",
  "ownerDomain": "google.com"
}