{
  "baseUrl": "https://displayvideo.googleapis.com/",
  "canonicalName": "Display Video",
  "fullyEncodeReservedExpansion": true,
  "servicePath": "",
  "title": "Display & Video 360 API",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "batchPath": "batch",
  "discoveryVersion": "v1",
  "version_module": true,
  "version": "v4",
  "revision": "20260412",
  "protocol": "rest",
  "resources": {
    "inventorySourceGroups": {
      "methods": {
        "get": {
          "id": "displayvideo.inventorySourceGroups.get",
          "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Gets an inventory source group.",
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}"
        },
        "patch": {
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/inventorySourceGroups/{inventorySourceGroupId}",
          "id": "displayvideo.inventorySourceGroups.patch"
        },
        "create": {
          "path": "v4/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/inventorySourceGroups",
          "httpMethod": "POST",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful."
        },
        "delete": {
          "id": "displayvideo.inventorySourceGroups.delete",
          "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}",
          "httpMethod": "DELETE",
          "description": "Deletes an inventory source group.",
          "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "id": "displayvideo.inventorySourceGroups.list",
          "path": "v4/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "flatPath": "v4/inventorySourceGroups"
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "list": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "httpMethod": "GET",
              "description": "Lists inventory sources assigned to an inventory source group.",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "httpMethod": "POST",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources"
            },
            "delete": {
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}"
            },
            "bulkEdit": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources.",
              "path": "v4/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit"
            }
          }
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "id": "displayvideo.googleAudiences.get",
          "path": "v4/googleAudiences/{+googleAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Gets a Google audience.",
          "flatPath": "v4/googleAudiences/{googleAudiencesId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/googleAudiences",
          "httpMethod": "GET",
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "path": "v4/googleAudiences",
          "id": "displayvideo.googleAudiences.list"
        }
      }
    },
    "users": {
      "methods": {
        "list": {
          "path": "v4/users",
          "id": "displayvideo.users.list",
          "flatPath": "v4/users",
          "httpMethod": "GET",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "create": {
          "flatPath": "v4/users",
          "httpMethod": "POST",
          "description": "Creates a new user. Returns the newly created user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v4/users",
          "id": "displayvideo.users.create"
        },
        "delete": {
          "flatPath": "v4/users/{usersId}",
          "httpMethod": "DELETE",
          "description": "Deletes a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v4/users/{+userId}",
          "id": "displayvideo.users.delete"
        },
        "bulkEditAssignedUserRoles": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "POST",
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature[...]",
          "flatPath": "v4/users/{usersId}:bulkEditAssignedUserRoles",
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "path": "v4/users/{+userId}:bulkEditAssignedUserRoles"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "httpMethod": "GET",
          "description": "Gets a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v4/users/{usersId}",
          "id": "displayvideo.users.get",
          "path": "v4/users/{+userId}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v4/users/{usersId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing user. Returns the updated user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "path": "v4/users/{+userId}",
          "id": "displayvideo.users.patch"
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets a custom list.",
          "flatPath": "v4/customLists/{customListsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customLists.get",
          "path": "v4/customLists/{+customListId}"
        },
        "list": {
          "id": "displayvideo.customLists.list",
          "path": "v4/customLists",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "flatPath": "v4/customLists"
        }
      }
    },
    "firstPartyAndPartnerAudiences": {
      "methods": {
        "create": {
          "id": "displayvideo.firstPartyAndPartnerAudiences.create",
          "path": "v4/firstPartyAndPartnerAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "description": "Creates a FirstPartyAndPartnerAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "flatPath": "v4/firstPartyAndPartnerAudiences"
        },
        "list": {
          "flatPath": "v4/firstPartyAndPartnerAudiences",
          "httpMethod": "GET",
          "description": "Lists first party and partner audiences. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/firstPartyAndPartnerAudiences",
          "id": "displayvideo.firstPartyAndPartnerAudiences.list"
        },
        "get": {
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}",
          "id": "displayvideo.firstPartyAndPartnerAudiences.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}",
          "httpMethod": "GET",
          "description": "Gets a first party or partner audience."
        },
        "patch": {
          "id": "displayvideo.firstPartyAndPartnerAudiences.patch",
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing FirstPartyAndPartnerAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}"
        },
        "editCustomerMatchMembers": {
          "id": "displayvideo.firstPartyAndPartnerAudiences.editCustomerMatchMembers",
          "path": "v4/firstPartyAndPartnerAudiences/{+firstPartyAndPartnerAudienceId}:editCustomerMatchMembers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "flatPath": "v4/firstPartyAndPartnerAudiences/{firstPartyAndPartnerAudiencesId}:editCustomerMatchMembers"
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "supportsMediaUpload": true,
          "id": "displayvideo.media.upload",
          "path": "media/{+resourceName}",
          "httpMethod": "POST",
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "flatPath": "media/{mediaId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ]
        },
        "download": {
          "path": "download/{+resourceName}",
          "id": "displayvideo.media.download",
          "flatPath": "download/{downloadId}",
          "httpMethod": "GET",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "supportsMediaDownload": true,
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ]
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "flatPath": "v4/customBiddingAlgorithms",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.list",
          "path": "v4/customBiddingAlgorithms"
        },
        "create": {
          "httpMethod": "POST",
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "flatPath": "v4/customBiddingAlgorithms",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.create",
          "path": "v4/customBiddingAlgorithms"
        },
        "uploadScript": {
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "httpMethod": "GET",
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "uploadRules": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadRules",
          "httpMethod": "GET",
          "description": "Creates a rules reference object for an AlgorithmRules file. The resulting reference object provides a resource path where the AlgorithmRules file should be uploaded. This reference object should be included when creating a new CustomBiddingAlgorithmRules resource.",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadRules",
          "id": "displayvideo.customBiddingAlgorithms.uploadRules"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Gets a custom bidding algorithm.",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "id": "displayvideo.customBiddingAlgorithms.get",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful. Requests updating a custom bidding algorithm assigned to a line item will return an error.",
          "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "id": "displayvideo.customBiddingAlgorithms.patch",
          "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}"
        }
      },
      "resources": {
        "rules": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates a new rules resource. Returns the newly created rules resource if successful. Requests creating a custom bidding rules resource under an algorithm assigned to a line item will return an error.",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.rules.create",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules"
            },
            "get": {
              "id": "displayvideo.customBiddingAlgorithms.rules.get",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules/{+customBiddingAlgorithmRulesId}",
              "httpMethod": "GET",
              "description": "Retrieves a rules resource.",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules/{rulesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "id": "displayvideo.customBiddingAlgorithms.rules.list",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Lists rules resources that belong to the given algorithm. The order is defined by the order_by parameter.",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules"
            }
          }
        },
        "scripts": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "httpMethod": "GET",
              "description": "Gets a custom bidding script.",
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "id": "displayvideo.customBiddingAlgorithms.scripts.get"
            },
            "list": {
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "httpMethod": "GET",
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list"
            },
            "create": {
              "path": "v4/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "flatPath": "v4/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "httpMethod": "POST",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful. Requests creating a custom bidding script under an algorithm assigned to a line item will return an error.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "path": "v4/sdfdownloadtasks",
          "id": "displayvideo.sdfdownloadtasks.create",
          "flatPath": "v4/sdfdownloadtasks",
          "httpMethod": "POST",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with `sdfdownloadtasks.operations.get`. Any errors can be found in the err[...]",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "path": "v4/{+name}",
              "httpMethod": "GET",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "flatPath": "v4/sdfdownloadtasks/operations/{operationsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ]
            }
          }
        }
      }
    },
    "sdfuploadtasks": {
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "id": "displayvideo.sdfuploadtasks.operations.get",
              "path": "v4/{+name}",
              "httpMethod": "GET",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "flatPath": "v4/sdfuploadtasks/operations/{operationsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ]
            }
          }
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "id": "displayvideo.combinedAudiences.get",
          "path": "v4/combinedAudiences/{+combinedAudienceId}",
          "httpMethod": "GET",
          "description": "Gets a combined audience.",
          "flatPath": "v4/combinedAudiences/{combinedAudiencesId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "flatPath": "v4/combinedAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.combinedAudiences.list",
          "path": "v4/combinedAudiences"
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "list": {
          "id": "displayvideo.guaranteedOrders.list",
          "path": "v4/guaranteedOrders",
          "httpMethod": "GET",
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "flatPath": "v4/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "httpMethod": "POST",
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful.",
          "flatPath": "v4/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.create",
          "path": "v4/guaranteedOrders"
        },
        "editGuaranteedOrderReadAccessors": {
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "httpMethod": "POST",
          "description": "Edits read advertisers of a guaranteed order.",
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}",
          "id": "displayvideo.guaranteedOrders.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "GET",
          "description": "Gets a guaranteed order."
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "path": "v4/guaranteedOrders/{+guaranteedOrderId}",
          "id": "displayvideo.guaranteedOrders.patch"
        }
      }
    },
    "partners": {
      "methods": {
        "editAssignedTargetingOptions": {
          "httpMethod": "POST",
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests .",
          "flatPath": "v4/partners/{partnersId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "path": "v4/partners/{+partnerId}:editAssignedTargetingOptions"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Gets a partner.",
          "flatPath": "v4/partners/{partnersId}",
          "id": "displayvideo.partners.get",
          "path": "v4/partners/{+partnerId}"
        },
        "list": {
          "id": "displayvideo.partners.list",
          "path": "v4/partners",
          "httpMethod": "GET",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "flatPath": "v4/partners",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "channels": {
          "methods": {
            "create": {
              "flatPath": "v4/partners/{partnersId}/channels",
              "httpMethod": "POST",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/partners/{+partnerId}/channels",
              "id": "displayvideo.partners.channels.create"
            },
            "get": {
              "path": "v4/partners/{+partnerId}/channels/{+channelId}",
              "id": "displayvideo.partners.channels.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/partners/{partnersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser."
            },
            "list": {
              "path": "v4/partners/{+partnerId}/channels",
              "id": "displayvideo.partners.channels.list",
              "flatPath": "v4/partners/{partnersId}/channels",
              "httpMethod": "GET",
              "description": "Lists channels for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "flatPath": "v4/partners/{partnersId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/partners/{+partnerId}/channels/{channelId}",
              "id": "displayvideo.partners.channels.patch"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "replace": {
                  "id": "displayvideo.partners.channels.sites.replace",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites:replace"
                },
                "create": {
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "description": "Creates a site in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites",
                  "id": "displayvideo.partners.channels.sites.create"
                },
                "delete": {
                  "id": "displayvideo.partners.channels.sites.delete",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel.",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}"
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "flatPath": "v4/partners/{partnersId}/channels/{channelsId}/sites",
                  "id": "displayvideo.partners.channels.sites.list",
                  "path": "v4/partners/{+partnerId}/channels/{+channelId}/sites"
                },
                "bulkEdit": {
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "path": "v4/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "flatPath": "v4/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit"
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get"
                },
                "list": {
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "description": "Lists the targeting options assigned to a partner."
                },
                "create": {
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create"
                },
                "delete": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v4/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Deletes an assigned targeting option from a partner.",
                  "flatPath": "v4/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                }
              }
            }
          }
        }
      }
    },
    "advertisers": {
      "methods": {
        "audit": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "flatPath": "v4/advertisers/{advertisersId}:audit",
          "id": "displayvideo.advertisers.audit",
          "path": "v4/advertisers/{+advertiserId}:audit"
        },
        "listAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "flatPath": "v4/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "path": "v4/advertisers/{+advertiserId}:listAssignedTargetingOptions"
        },
        "editAssignedTargetingOptions": {
          "httpMethod": "POST",
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "flatPath": "v4/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.editAssignedTargetingOptions",
          "path": "v4/advertisers/{+advertiserId}:editAssignedTargetingOptions"
        },
        "get": {
          "path": "v4/advertisers/{+advertiserId}",
          "id": "displayvideo.advertisers.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/advertisers/{advertisersId}",
          "httpMethod": "GET",
          "description": "Gets an advertiser."
        },
        "patch": {
          "flatPath": "v4/advertisers/{advertisersId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/advertisers/{+advertiserId}",
          "id": "displayvideo.advertisers.patch"
        },
        "create": {
          "httpMethod": "POST",
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
          "flatPath": "v4/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.create",
          "path": "v4/advertisers"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v4/advertisers/{advertisersId}",
          "httpMethod": "DELETE",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "path": "v4/advertisers/{+advertiserId}",
          "id": "displayvideo.advertisers.delete"
        },
        "list": {
          "id": "displayvideo.advertisers.list",
          "path": "v4/advertisers",
          "httpMethod": "GET",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "flatPath": "v4/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "channels": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "flatPath": "v4/advertisers/{advertisersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.create",
              "path": "v4/advertisers/{+advertiserId}/channels"
            },
            "get": {
              "path": "v4/advertisers/{+advertiserId}/channels/{+channelId}",
              "id": "displayvideo.advertisers.channels.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser."
            },
            "list": {
              "id": "displayvideo.advertisers.channels.list",
              "path": "v4/advertisers/{+advertiserId}/channels",
              "httpMethod": "GET",
              "description": "Lists channels for a partner or advertiser.",
              "flatPath": "v4/advertisers/{advertisersId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "flatPath": "v4/advertisers/{advertisersId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.patch",
              "path": "v4/advertisers/{+advertiserId}/channels/{channelId}"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "replace": {
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites:replace",
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit"
                },
                "list": {
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "flatPath": "v4/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "path": "v4/advertisers/{+advertiserId}/channels/{+channelId}/sites"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates a site in a channel.",
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v4/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel.",
                  "path": "v4/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "id": "displayvideo.advertisers.channels.sites.delete"
                }
              }
            }
          }
        },
        "adGroupAds": {
          "methods": {
            "list": {
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds",
              "httpMethod": "GET",
              "description": "Lists ad group ads.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/adGroupAds",
              "id": "displayvideo.advertisers.adGroupAds.list"
            },
            "create": {
              "path": "v4/advertisers/{+advertiserId}/adGroupAds",
              "id": "displayvideo.advertisers.adGroupAds.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds",
              "httpMethod": "POST",
              "description": "Creates an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users."
            },
            "delete": {
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "id": "displayvideo.advertisers.adGroupAds.delete",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "httpMethod": "DELETE",
              "description": "Deletes an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Gets an ad group ad.",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "id": "displayvideo.advertisers.adGroupAds.get",
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}"
            },
            "patch": {
              "path": "v4/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "id": "displayvideo.advertisers.adGroupAds.patch",
              "flatPath": "v4/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "httpMethod": "PATCH",
              "description": "Updates an ad group ad. This method is only supported for Demand Gen ads. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "creatives": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v4/advertisers/{advertisersId}/creatives",
              "id": "displayvideo.advertisers.creatives.list",
              "path": "v4/advertisers/{+advertiserId}/creatives"
            },
            "create": {
              "path": "v4/advertisers/{+advertiserId}/creatives",
              "id": "displayvideo.advertisers.creatives.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/creatives",
              "httpMethod": "POST",
              "description": "Creates a new creative. Returns the newly created creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request."
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.delete",
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}"
            },
            "get": {
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "GET",
              "description": "Gets a creative.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "id": "displayvideo.advertisers.creatives.get"
            },
            "patch": {
              "flatPath": "v4/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing creative. Returns the updated creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "id": "displayvideo.advertisers.creatives.patch"
            }
          }
        },
        "locationLists": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.create",
              "path": "v4/advertisers/{+advertiserId}/locationLists"
            },
            "get": {
              "flatPath": "v4/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "httpMethod": "GET",
              "description": "Gets a location list.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "id": "displayvideo.advertisers.locationLists.get"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/locationLists",
              "httpMethod": "GET",
              "description": "Lists location lists based on a given advertiser id.",
              "path": "v4/advertisers/{+advertiserId}/locationLists",
              "id": "displayvideo.advertisers.locationLists.list"
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates a location list. Returns the updated location list if successful.",
              "flatPath": "v4/advertisers/{advertisersId}/locationLists/{locationListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.patch",
              "path": "v4/advertisers/{+advertiserId}/locationLists/{locationListId}"
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "bulkEdit": {
                  "path": "v4/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in deletedAssignedLocations and then create the assigned locations provided in createdAssignedLocations.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "POST",
                  "description": "Creates an assignment between a location and a location list.",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create"
                },
                "delete": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Deletes the assignment between a location and a location list.",
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}"
                },
                "list": {
                  "flatPath": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "GET",
                  "description": "Lists locations assigned to a location list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v4/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list"
                }
              }
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "id": "displayvideo.advertisers.invoices.list",
              "path": "v4/advertisers/{+advertiserId}/invoices",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "GET",
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method.",
              "flatPath": "v4/advertisers/{advertisersId}/invoices"
            },
            "lookupInvoiceCurrency": {
              "path": "v4/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "httpMethod": "GET",
              "description": "Retrieves the invoice currency used by an advertiser in a given month."
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "create": {
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists",
              "httpMethod": "POST",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists",
              "id": "displayvideo.advertisers.negativeKeywordLists.create"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}"
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists",
              "httpMethod": "GET",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists",
              "id": "displayvideo.advertisers.negativeKeywordLists.list"
            },
            "get": {
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}"
            },
            "patch": {
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}"
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "bulkEdit": {
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit"
                },
                "list": {
                  "flatPath": "v4/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "httpMethod": "GET",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v4/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list"
                },
                "create": {
                  "httpMethod": "POST",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords"
                },
                "delete": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}"
                },
                "replace": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "flatPath": "v4/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "path": "v4/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace"
                }
              }
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "httpMethod": "POST",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "flatPath": "v4/advertisers/{advertisersId}/assets",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.assets.upload",
              "path": "v4/advertisers/{+advertiserId}/assets",
              "supportsMediaUpload": true
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "create": {
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful."
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                },
                "list": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "path": "v4/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "flatPath": "v4/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions"
                }
              }
            }
          }
        },
        "lineItems": {
          "methods": {
            "list": {
              "flatPath": "v4/advertisers/{advertisersId}/lineItems",
              "httpMethod": "GET",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.list"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "description": "Creates a new line item. Returns the newly created line item if successful. YouTube & Partners line items cannot be created or updated using the API.",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.create",
              "path": "v4/advertisers/{+advertiserId}/lineItems"
            },
            "delete": {
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "id": "displayvideo.advertisers.lineItems.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. YouTube & Partners line items cannot be created or updated using the API."
            },
            "bulkUpdate": {
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkUpdate",
              "httpMethod": "POST",
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "id": "displayvideo.advertisers.lineItems.bulkUpdate"
            },
            "bulkEditAssignedTargetingOptions": {
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkUpdate * lineItems.patch * assignedTargetingOp[...]"
            },
            "duplicate": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful. YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate",
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate"
            },
            "get": {
              "id": "displayvideo.advertisers.lineItems.get",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "description": "Gets a line item.",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}"
            },
            "patch": {
              "httpMethod": "PATCH",
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your de[...]",
              "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.patch",
              "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}"
            },
            "bulkListAssignedTargetingOptions": {
              "path": "v4/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions",
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options for multiple line items across targeting types."
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a line item."
                    },
                    "list": {
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a line item.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "create": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * DeleteLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "DELETE",
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * CreateLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete"
                    }
                  }
                }
              }
            },
            "youtubeAssetTypes": {
              "resources": {
                "youtubeAssetAssociations": {
                  "methods": {
                    "create": {
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.create",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "httpMethod": "POST",
                      "description": "Creates a new association between the identified resource and a YouTube asset. Returns the newly-created association. *Warning:* This method is only available to an informed subset of users.",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "delete": {
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.delete",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations/{+youtubeAssetAssociationId}",
                      "httpMethod": "DELETE",
                      "description": "Deletes an existing association between the identified resource and a YouTube asset. *Warning:* This method is only available to an informed subset of users.",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations/{youtubeAssetAssociationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "GET",
                      "description": "Lists the YouTube asset associations linked to the given resource.",
                      "flatPath": "v4/advertisers/{advertisersId}/lineItems/{lineItemsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "id": "displayvideo.advertisers.lineItems.youtubeAssetTypes.youtubeAssetAssociations.list",
                      "path": "v4/advertisers/{+advertiserId}/lineItems/{+lineItemId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations"
                    }
                  }
                }
              }
            }
          }
        },
        "adGroups": {
          "methods": {
            "list": {
              "flatPath": "v4/advertisers/{advertisersId}/adGroups",
              "httpMethod": "GET",
              "description": "Lists ad groups.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/adGroups",
              "id": "displayvideo.advertisers.adGroups.list"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/adGroups",
              "httpMethod": "POST",
              "description": "Creates a new ad group. Returns the newly created ad group if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "path": "v4/advertisers/{+advertiserId}/adGroups",
              "id": "displayvideo.advertisers.adGroups.create"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a AdGroup. Returns error code `NOT_FOUND` if the ad group does not exist. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "id": "displayvideo.advertisers.adGroups.delete"
            },
            "get": {
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "id": "displayvideo.advertisers.adGroups.get",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "httpMethod": "GET",
              "description": "Gets an ad group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "id": "displayvideo.advertisers.adGroups.patch",
              "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing ad group. Returns the updated ad group if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkListAssignedTargetingOptions": {
              "httpMethod": "GET",
              "description": "Lists assigned targeting options for multiple ad groups across targeting types. Inherited assigned targeting options are not included.",
              "flatPath": "v4/advertisers/{advertisersId}/adGroups:bulkListAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.bulkListAssignedTargetingOptions",
              "path": "v4/advertisers/{+advertiserId}/adGroups:bulkListAssignedTargetingOptions"
            },
            "bulkEditAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/adGroups:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "description": "Bulk edits targeting options for multiple ad groups. The same set of delete and create requests will be applied to all specified ad groups. Specifically, the operation will delete the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.delete_requests from each ad group, and then create the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.create_requests. This method is only supported for Demand [...]",
              "path": "v4/advertisers/{+advertiserId}/adGroups:bulkEditAssignedTargetingOptions",
              "id": "displayvideo.advertisers.adGroups.bulkEditAssignedTargetingOptions"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "create": {
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "description": "Assigns a targeting option to an ad group. Returns the assigned targeting option if successful. This method is only supported for Demand Gen ad groups. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.create"
                    },
                    "delete": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "DELETE",
                      "description": "Deletes an assigned targeting option from an ad group. This method is only supported for Demand Gen ad groups with the AdGroupFormat `AD_GROUP_FORMAT_DEMAND_GEN`. Retrieval and management of Demand Gen resources is currently in beta. This method is only available to allowlisted users.",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.delete",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    },
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to an ad group. Inherited assigned targeting options are not included.",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.get"
                    },
                    "list": {
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to an ad group. Inherited assigned targeting options are not included."
                    }
                  }
                }
              }
            },
            "youtubeAssetTypes": {
              "resources": {
                "youtubeAssetAssociations": {
                  "methods": {
                    "create": {
                      "httpMethod": "POST",
                      "description": "Creates a new association between the identified resource and a YouTube asset. Returns the newly-created association. *Warning:* This method is only available to an informed subset of users.",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.create",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations"
                    },
                    "delete": {
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.delete",
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations/{+youtubeAssetAssociationId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "httpMethod": "DELETE",
                      "description": "Deletes an existing association between the identified resource and a YouTube asset. *Warning:* This method is only available to an informed subset of users.",
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations/{youtubeAssetAssociationsId}"
                    },
                    "list": {
                      "path": "v4/advertisers/{+advertiserId}/adGroups/{+adGroupId}/youtubeAssetTypes/{+youtubeAssetType}/youtubeAssetAssociations",
                      "id": "displayvideo.advertisers.adGroups.youtubeAssetTypes.youtubeAssetAssociations.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v4/advertisers/{advertisersId}/adGroups/{adGroupsId}/youtubeAssetTypes/{youtubeAssetTypesId}/youtubeAssetAssociations",
                      "httpMethod": "GET",
                      "description": "Lists the YouTube asset associations linked to the given resource."
                    }
                  }
                }
              }
            }
          }
        },
        "campaigns": {
          "methods": {
            "get": {
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "id": "displayvideo.advertisers.campaigns.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "GET",
              "description": "Gets a campaign."
            },
            "patch": {
              "id": "displayvideo.advertisers.campaigns.patch",
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "PATCH",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}"
            },
            "create": {
              "path": "v4/advertisers/{+advertiserId}/campaigns",
              "id": "displayvideo.advertisers.campaigns.create",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns",
              "httpMethod": "POST",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "httpMethod": "DELETE",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "flatPath": "v4/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "id": "displayvideo.advertisers.campaigns.delete",
              "path": "v4/advertisers/{+advertiserId}/campaigns/{+campaignId}"
            },
            "list": {
              "path": "v4/advertisers/{+advertiserId}/campaigns",
              "id": "displayvideo.advertisers.campaigns.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/campaigns",
              "httpMethod": "GET",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "get": {
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "id": "displayvideo.advertisers.insertionOrders.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "GET",
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist."
            },
            "patch": {
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "PATCH",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}"
            },
            "create": {
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders",
              "httpMethod": "POST",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/advertisers/{+advertiserId}/insertionOrders",
              "id": "displayvideo.advertisers.insertionOrders.create"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "DELETE",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "path": "v4/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "id": "displayvideo.advertisers.insertionOrders.delete"
            },
            "list": {
              "path": "v4/advertisers/{+advertiserId}/insertionOrders",
              "id": "displayvideo.advertisers.insertionOrders.list",
              "flatPath": "v4/advertisers/{advertisersId}/insertionOrders",
              "httpMethod": "GET",
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "adAssets": {
          "methods": {
            "get": {
              "path": "v4/advertisers/{+advertiserId}/adAssets/{+adAssetId}",
              "id": "displayvideo.advertisers.adAssets.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/advertisers/{advertisersId}/adAssets/{adAssetsId}",
              "httpMethod": "GET",
              "description": "Gets an ad asset. Only supports the retrieval of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`."
            },
            "bulkCreate": {
              "path": "v4/advertisers/{+advertiserId}/adAssets:bulkCreate",
              "id": "displayvideo.advertisers.adAssets.bulkCreate",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets:bulkCreate",
              "httpMethod": "POST",
              "description": "Creates multiple ad assets in a single request. Returns the newly-created ad assets if successful. Only supports the creation of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "id": "displayvideo.advertisers.adAssets.list",
              "path": "v4/advertisers/{+advertiserId}/adAssets",
              "httpMethod": "GET",
              "description": "Lists ad assets under an advertiser ID. Only supports the retrieval of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "upload": {
              "supportsMediaUpload": true,
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "description": "Uploads and creates an ad asset. Returns the ID of the newly-created ad asset if successful. Only supports the uploading of assets with the AdAssetType `AD_ASSET_TYPE_IMAGE`.",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets:uploadAdAsset",
              "id": "displayvideo.advertisers.adAssets.upload",
              "path": "v4/advertisers/{+advertiserId}/adAssets:uploadAdAsset"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "POST",
              "description": "Creates an ad asset. Returns the newly-created ad asset if successful. Only supports the creation of assets of AdAssetType `AD_ASSET_TYPE_YOUTUBE_VIDEO`.",
              "flatPath": "v4/advertisers/{advertisersId}/adAssets",
              "id": "displayvideo.advertisers.adAssets.create",
              "path": "v4/advertisers/{+advertiserId}/adAssets"
            }
          }
        }
      }
    },
    "inventorySources": {
      "methods": {
        "create": {
          "httpMethod": "POST",
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful.",
          "flatPath": "v4/inventorySources",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.create",
          "path": "v4/inventorySources"
        },
        "list": {
          "flatPath": "v4/inventorySources",
          "httpMethod": "GET",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v4/inventorySources",
          "id": "displayvideo.inventorySources.list"
        },
        "editInventorySourceReadWriteAccessors": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "POST",
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source.",
          "flatPath": "v4/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors",
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors",
          "path": "v4/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors"
        },
        "get": {
          "id": "displayvideo.inventorySources.get",
          "path": "v4/inventorySources/{+inventorySourceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "description": "Gets an inventory source.",
          "flatPath": "v4/inventorySources/{inventorySourcesId}"
        },
        "patch": {
          "path": "v4/inventorySources/{+inventorySourceId}",
          "id": "displayvideo.inventorySources.patch",
          "flatPath": "v4/inventorySources/{inventorySourcesId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets a Floodlight group.",
          "flatPath": "v4/floodlightGroups/{floodlightGroupsId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.floodlightGroups.get",
          "path": "v4/floodlightGroups/{+floodlightGroupId}"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "flatPath": "v4/floodlightGroups/{floodlightGroupId}",
          "id": "displayvideo.floodlightGroups.patch",
          "path": "v4/floodlightGroups/{floodlightGroupId}"
        }
      },
      "resources": {
        "floodlightActivities": {
          "methods": {
            "get": {
              "path": "v4/floodlightGroups/{+floodlightGroupId}/floodlightActivities/{+floodlightActivityId}",
              "id": "displayvideo.floodlightGroups.floodlightActivities.get",
              "flatPath": "v4/floodlightGroups/{floodlightGroupsId}/floodlightActivities/{floodlightActivitiesId}",
              "httpMethod": "GET",
              "description": "Gets a Floodlight activity.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/floodlightGroups/{floodlightGroupsId}/floodlightActivities",
              "httpMethod": "GET",
              "description": "Lists Floodlight activities in a Floodlight group.",
              "path": "v4/floodlightGroups/{+floodlightGroupId}/floodlightActivities",
              "id": "displayvideo.floodlightGroups.floodlightActivities.list"
            }
          }
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "search": {
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "httpMethod": "POST",
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions:search",
              "id": "displayvideo.targetingTypes.targetingOptions.search"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "httpMethod": "GET",
              "description": "Gets a single targeting option.",
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "id": "displayvideo.targetingTypes.targetingOptions.get"
            },
            "list": {
              "path": "v4/targetingTypes/{+targetingType}/targetingOptions",
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "flatPath": "v4/targetingTypes/{targetingTypesId}/targetingOptions",
              "httpMethod": "GET",
              "description": "Lists targeting options of a given type.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    }
  },
  "id": "displayvideo:v4",
  "ownerDomain": "google.com",
  "basePath": "",
  "name": "displayvideo",
  "ownerName": "Google",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "kind": "discovery#restDescription",
  "documentationLink": "https://developers.google.com/display-video/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        }
      }
    }
  }
}