{
  "title": "Display & Video 360 API",
  "discoveryVersion": "v1",
  "basePath": "",
  "name": "displayvideo",
  "revision": "20260310",
  "id": "displayvideo:v3",
  "resources": {
    "customLists": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "v3/customLists/{+customListId}",
          "flatPath": "v3/customLists/{customListsId}",
          "description": "Gets a custom list.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customLists.get"
        },
        "list": {
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "flatPath": "v3/customLists",
          "path": "v3/customLists",
          "httpMethod": "GET",
          "id": "displayvideo.customLists.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "v3/combinedAudiences/{+combinedAudienceId}",
          "flatPath": "v3/combinedAudiences/{combinedAudiencesId}",
          "description": "Gets a combined audience.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.combinedAudiences.get"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.combinedAudiences.list",
          "httpMethod": "GET",
          "path": "v3/combinedAudiences",
          "flatPath": "v3/combinedAudiences",
          "description": "Lists combined audiences. The order is defined by the order_by parameter."
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "flatPath": "download/{downloadId}",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "httpMethod": "GET",
          "path": "download/{+resourceName}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "id": "displayvideo.media.download",
          "supportsMediaDownload": true
        },
        "upload": {
          "id": "displayvideo.media.upload",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "supportsMediaUpload": true,
          "path": "media/{+resourceName}",
          "httpMethod": "POST",
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "flatPath": "media/{mediaId}"
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.get",
          "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "description": "Gets a custom bidding algorithm.",
          "httpMethod": "GET",
          "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}"
        },
        "uploadRules": {
          "description": "Creates a rules reference object for an AlgorithmRules file. The resulting reference object provides a resource path where the AlgorithmRules file should be uploaded. This reference object should be included when creating a new CustomBiddingAlgorithmRules resource.",
          "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadRules",
          "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadRules",
          "httpMethod": "GET",
          "id": "displayvideo.customBiddingAlgorithms.uploadRules",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "id": "displayvideo.customBiddingAlgorithms.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v3/customBiddingAlgorithms",
          "httpMethod": "POST",
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "flatPath": "v3/customBiddingAlgorithms"
        },
        "uploadScript": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "httpMethod": "GET",
          "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object."
        },
        "list": {
          "flatPath": "v3/customBiddingAlgorithms",
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "path": "v3/customBiddingAlgorithms",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.list"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.customBiddingAlgorithms.patch",
          "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful. Requests updating a custom bidding algorithm assigned to a line item will return an error.",
          "httpMethod": "PATCH",
          "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}"
        }
      },
      "resources": {
        "scripts": {
          "methods": {
            "create": {
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new custom bidding script. Returns the newly created script if successful. Requests creating a custom bidding script under an algorithm assigned to a line item will return an error.",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "httpMethod": "POST"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.scripts.get",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "description": "Gets a custom bidding script.",
              "httpMethod": "GET",
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}"
            },
            "list": {
              "id": "displayvideo.customBiddingAlgorithms.scripts.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "httpMethod": "GET",
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts"
            }
          }
        },
        "rules": {
          "methods": {
            "list": {
              "id": "displayvideo.customBiddingAlgorithms.rules.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "httpMethod": "GET",
              "description": "Lists rules resources that belong to the given algorithm. The order is defined by the order_by parameter.",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules"
            },
            "create": {
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules",
              "description": "Creates a new rules resource. Returns the newly created rules resource if successful. Requests creating a custom bidding rules resource under an algorithm assigned to a line item will return an error.",
              "httpMethod": "POST",
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.rules.create"
            },
            "get": {
              "httpMethod": "GET",
              "path": "v3/customBiddingAlgorithms/{+customBiddingAlgorithmId}/rules/{+customBiddingAlgorithmRulesId}",
              "flatPath": "v3/customBiddingAlgorithms/{customBiddingAlgorithmsId}/rules/{rulesId}",
              "description": "Retrieves a rules resource.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.customBiddingAlgorithms.rules.get"
            }
          }
        }
      }
    },
    "partners": {
      "methods": {
        "editAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "path": "v3/partners/{+partnerId}:editAssignedTargetingOptions",
          "httpMethod": "POST",
          "flatPath": "v3/partners/{partnersId}:editAssignedTargetingOptions",
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests ."
        },
        "get": {
          "id": "displayvideo.partners.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a partner.",
          "flatPath": "v3/partners/{partnersId}",
          "httpMethod": "GET",
          "path": "v3/partners/{+partnerId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.partners.list",
          "flatPath": "v3/partners",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "path": "v3/partners"
        }
      },
      "resources": {
        "channels": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "path": "v3/partners/{+partnerId}/channels",
              "description": "Lists channels for a partner or advertiser.",
              "flatPath": "v3/partners/{partnersId}/channels",
              "id": "displayvideo.partners.channels.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "flatPath": "v3/partners/{partnersId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "httpMethod": "PATCH",
              "path": "v3/partners/{+partnerId}/channels/{channelId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.patch"
            },
            "get": {
              "id": "displayvideo.partners.channels.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v3/partners/{+partnerId}/channels/{+channelId}",
              "description": "Gets a channel for a partner or advertiser.",
              "flatPath": "v3/partners/{partnersId}/channels/{channelsId}"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.partners.channels.create",
              "httpMethod": "POST",
              "path": "v3/partners/{+partnerId}/channels",
              "flatPath": "v3/partners/{partnersId}/channels",
              "description": "Creates a new channel. Returns the newly created channel if successful."
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "list": {
                  "flatPath": "v3/partners/{partnersId}/channels/{channelsId}/sites",
                  "description": "Lists sites in a channel.",
                  "path": "v3/partners/{+partnerId}/channels/{+channelId}/sites",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.list"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "path": "v3/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "flatPath": "v3/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "description": "Deletes a site from a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.delete"
                },
                "replace": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.replace",
                  "path": "v3/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "httpMethod": "POST",
                  "flatPath": "v3/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors."
                },
                "bulkEdit": {
                  "id": "displayvideo.partners.channels.sites.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v3/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "flatPath": "v3/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit"
                },
                "create": {
                  "flatPath": "v3/partners/{partnerId}/channels/{channelsId}/sites",
                  "description": "Creates a site in a channel.",
                  "path": "v3/partners/{partnerId}/channels/{+channelId}/sites",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.channels.sites.create"
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "delete": {
                  "flatPath": "v3/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "description": "Deletes an assigned targeting option from a partner.",
                  "path": "v3/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete"
                },
                "list": {
                  "path": "v3/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "flatPath": "v3/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "description": "Lists the targeting options assigned to a partner.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list"
                },
                "create": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "flatPath": "v3/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "path": "v3/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "httpMethod": "POST"
                },
                "get": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get",
                  "path": "v3/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "GET",
                  "flatPath": "v3/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "description": "Gets a single targeting option assigned to a partner."
                }
              }
            }
          }
        }
      }
    },
    "inventorySourceGroups": {
      "methods": {
        "patch": {
          "path": "v3/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH",
          "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupId}",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySourceGroups.patch"
        },
        "delete": {
          "description": "Deletes an inventory source group.",
          "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}",
          "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}",
          "httpMethod": "DELETE",
          "id": "displayvideo.inventorySourceGroups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "path": "v3/inventorySourceGroups",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "flatPath": "v3/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "flatPath": "v3/inventorySourceGroups",
          "httpMethod": "POST",
          "path": "v3/inventorySourceGroups",
          "id": "displayvideo.inventorySourceGroups.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}",
          "httpMethod": "GET",
          "description": "Gets an inventory source group.",
          "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}",
          "id": "displayvideo.inventorySourceGroups.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "httpMethod": "POST",
              "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "description": "Creates an assignment between an inventory source and an inventory source group."
            },
            "delete": {
              "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete"
            },
            "bulkEdit": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST",
              "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources."
            },
            "list": {
              "path": "v3/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "httpMethod": "GET",
              "description": "Lists inventory sources assigned to an inventory source group.",
              "flatPath": "v3/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        }
      }
    },
    "users": {
      "methods": {
        "bulkEditAssignedUserRoles": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "flatPath": "v3/users/{usersId}:bulkEditAssignedUserRoles",
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature[...]",
          "path": "v3/users/{+userId}:bulkEditAssignedUserRoles",
          "httpMethod": "POST"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.get",
          "httpMethod": "GET",
          "path": "v3/users/{+userId}",
          "flatPath": "v3/users/{usersId}",
          "description": "Gets a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method."
        },
        "create": {
          "id": "displayvideo.users.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "description": "Creates a new user. Returns the newly created user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v3/users",
          "httpMethod": "POST",
          "path": "v3/users"
        },
        "list": {
          "flatPath": "v3/users",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "httpMethod": "GET",
          "path": "v3/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "id": "displayvideo.users.list"
        },
        "patch": {
          "description": "Updates an existing user. Returns the updated user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v3/users/{usersId}",
          "path": "v3/users/{+userId}",
          "httpMethod": "PATCH",
          "id": "displayvideo.users.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "delete": {
          "description": "Deletes a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "flatPath": "v3/users/{usersId}",
          "path": "v3/users/{+userId}",
          "httpMethod": "DELETE",
          "id": "displayvideo.users.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.floodlightGroups.patch",
          "httpMethod": "PATCH",
          "path": "v3/floodlightGroups/{floodlightGroupId}",
          "flatPath": "v3/floodlightGroups/{floodlightGroupId}",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.floodlightGroups.get",
          "httpMethod": "GET",
          "path": "v3/floodlightGroups/{+floodlightGroupId}",
          "flatPath": "v3/floodlightGroups/{floodlightGroupsId}",
          "description": "Gets a Floodlight group."
        }
      },
      "resources": {
        "floodlightActivities": {
          "methods": {
            "get": {
              "id": "displayvideo.floodlightGroups.floodlightActivities.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "httpMethod": "GET",
              "path": "v3/floodlightGroups/{+floodlightGroupId}/floodlightActivities/{+floodlightActivityId}",
              "description": "Gets a Floodlight activity.",
              "flatPath": "v3/floodlightGroups/{floodlightGroupsId}/floodlightActivities/{floodlightActivitiesId}"
            },
            "list": {
              "path": "v3/floodlightGroups/{+floodlightGroupId}/floodlightActivities",
              "httpMethod": "GET",
              "flatPath": "v3/floodlightGroups/{floodlightGroupsId}/floodlightActivities",
              "description": "Lists Floodlight activities in a Floodlight group.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.floodlightGroups.floodlightActivities.list"
            }
          }
        }
      }
    },
    "inventorySources": {
      "methods": {
        "create": {
          "description": "Creates a new inventory source. Returns the newly created inventory source if successful.",
          "flatPath": "v3/inventorySources",
          "path": "v3/inventorySources",
          "httpMethod": "POST",
          "id": "displayvideo.inventorySources.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.inventorySources.get",
          "flatPath": "v3/inventorySources/{inventorySourcesId}",
          "description": "Gets an inventory source.",
          "httpMethod": "GET",
          "path": "v3/inventorySources/{+inventorySourceId}"
        },
        "patch": {
          "id": "displayvideo.inventorySources.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates an existing inventory source. Returns the updated inventory source if successful.",
          "flatPath": "v3/inventorySources/{inventorySourcesId}",
          "httpMethod": "PATCH",
          "path": "v3/inventorySources/{+inventorySourceId}"
        },
        "editInventorySourceReadWriteAccessors": {
          "id": "displayvideo.inventorySources.editInventorySourceReadWriteAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Edits read/write accessors of an inventory source. Returns the updated read_write_accessors for the inventory source.",
          "flatPath": "v3/inventorySources/{inventorySourcesId}:editInventorySourceReadWriteAccessors",
          "httpMethod": "POST",
          "path": "v3/inventorySources/{+inventorySourceId}:editInventorySourceReadWriteAccessors"
        },
        "list": {
          "path": "v3/inventorySources",
          "httpMethod": "GET",
          "description": "Lists inventory sources that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, inventory sources with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "flatPath": "v3/inventorySources",
          "id": "displayvideo.inventorySources.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "advertisers": {
      "methods": {
        "editAssignedTargetingOptions": {
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "flatPath": "v3/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "httpMethod": "POST",
          "path": "v3/advertisers/{+advertiserId}:editAssignedTargetingOptions",
          "id": "displayvideo.advertisers.editAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "listAssignedTargetingOptions": {
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "flatPath": "v3/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "httpMethod": "GET",
          "path": "v3/advertisers/{+advertiserId}:listAssignedTargetingOptions"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.list",
          "path": "v3/advertisers",
          "httpMethod": "GET",
          "flatPath": "v3/advertisers",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported."
        },
        "audit": {
          "flatPath": "v3/advertisers/{advertisersId}:audit",
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "httpMethod": "GET",
          "path": "v3/advertisers/{+advertiserId}:audit",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.audit"
        },
        "patch": {
          "id": "displayvideo.advertisers.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "PATCH",
          "path": "v3/advertisers/{+advertiserId}",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "flatPath": "v3/advertisers/{advertisersId}"
        },
        "delete": {
          "httpMethod": "DELETE",
          "path": "v3/advertisers/{+advertiserId}",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "flatPath": "v3/advertisers/{advertisersId}",
          "id": "displayvideo.advertisers.delete",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.advertisers.get",
          "httpMethod": "GET",
          "path": "v3/advertisers/{+advertiserId}",
          "flatPath": "v3/advertisers/{advertisersId}",
          "description": "Gets an advertiser."
        },
        "create": {
          "id": "displayvideo.advertisers.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
          "flatPath": "v3/advertisers",
          "httpMethod": "POST",
          "path": "v3/advertisers"
        }
      },
      "resources": {
        "insertionOrders": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.get",
              "httpMethod": "GET",
              "path": "v3/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.insertionOrders.create",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "httpMethod": "POST",
              "path": "v3/advertisers/{+advertiserId}/insertionOrders"
            },
            "list": {
              "id": "displayvideo.advertisers.insertionOrders.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders",
              "path": "v3/advertisers/{+advertiserId}/insertionOrders",
              "httpMethod": "GET"
            },
            "patch": {
              "path": "v3/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "id": "displayvideo.advertisers.insertionOrders.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "flatPath": "v3/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "DELETE",
              "path": "v3/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "adGroups": {
          "methods": {
            "delete": {
              "id": "displayvideo.advertisers.adGroups.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Deletes a AdGroup. Returns error code `NOT_FOUND` if the ad group does not exist.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "httpMethod": "DELETE",
              "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}"
            },
            "patch": {
              "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "description": "Updates an existing ad group. Returns the updated ad group if successful.",
              "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.patch"
            },
            "list": {
              "id": "displayvideo.advertisers.adGroups.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists ad groups.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups",
              "httpMethod": "GET",
              "path": "v3/advertisers/{+advertiserId}/adGroups"
            },
            "bulkEditAssignedTargetingOptions": {
              "httpMethod": "POST",
              "path": "v3/advertisers/{+advertiserId}/adGroups:bulkEditAssignedTargetingOptions",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups:bulkEditAssignedTargetingOptions",
              "description": "Bulk edits targeting options for multiple ad groups. The same set of delete and create requests will be applied to all specified ad groups. Specifically, the operation will delete the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.delete_requests from each ad group, and then create the assigned targeting options provided in BulkEditAdGroupAssignedTargetingOptionsRequest.create_requests. Only ad groups under a line item of line_[...]",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.bulkEditAssignedTargetingOptions"
            },
            "bulkListAdGroupAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.bulkListAdGroupAssignedTargetingOptions",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups:bulkListAdGroupAssignedTargetingOptions",
              "description": "Lists assigned targeting options for multiple ad groups across targeting types. Inherited assigned targeting options are not included.",
              "httpMethod": "GET",
              "path": "v3/advertisers/{+advertiserId}/adGroups:bulkListAdGroupAssignedTargetingOptions"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.create",
              "httpMethod": "POST",
              "path": "v3/advertisers/{+advertiserId}/adGroups",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups",
              "description": "Creates a new ad group. Returns the newly created ad group if successful."
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.adGroups.get",
              "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}",
              "httpMethod": "GET",
              "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}",
              "description": "Gets an ad group."
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.get",
                      "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "GET",
                      "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "description": "Gets a single targeting option assigned to an ad group. Inherited assigned targeting options are not included."
                    },
                    "create": {
                      "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "description": "Assigns a targeting option to an ad group. Returns the assigned targeting option if successful. Only ad groups under a line item of line_item_type `LINE_ITEM_TYPE_DEMAND_GEN` are supported for this method.",
                      "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "list": {
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.list",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Lists the targeting options assigned to an ad group. Inherited assigned targeting options are not included.",
                      "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "GET"
                    },
                    "delete": {
                      "id": "displayvideo.advertisers.adGroups.targetingTypes.assignedTargetingOptions.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v3/advertisers/{+advertiserId}/adGroups/{+adGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "DELETE",
                      "description": "Deletes an assigned targeting option from an ad group. Only ad groups under a line item of line_item_type `LINE_ITEM_TYPE_DEMAND_GEN` are supported for this method.",
                      "flatPath": "v3/advertisers/{advertisersId}/adGroups/{adGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}"
                    }
                  }
                }
              }
            }
          }
        },
        "campaigns": {
          "methods": {
            "patch": {
              "httpMethod": "PATCH",
              "path": "v3/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.patch"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.delete",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "path": "v3/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "httpMethod": "DELETE"
            },
            "list": {
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns",
              "httpMethod": "GET",
              "path": "v3/advertisers/{+advertiserId}/campaigns",
              "id": "displayvideo.advertisers.campaigns.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.create",
              "httpMethod": "POST",
              "path": "v3/advertisers/{+advertiserId}/campaigns",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns",
              "description": "Creates a new campaign. Returns the newly created campaign if successful."
            },
            "get": {
              "httpMethod": "GET",
              "path": "v3/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "flatPath": "v3/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "description": "Gets a campaign.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.campaigns.get"
            }
          }
        },
        "locationLists": {
          "methods": {
            "patch": {
              "path": "v3/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "httpMethod": "PATCH",
              "flatPath": "v3/advertisers/{advertisersId}/locationLists/{locationListId}",
              "description": "Updates a location list. Returns the updated location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.patch"
            },
            "list": {
              "id": "displayvideo.advertisers.locationLists.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/locationLists",
              "httpMethod": "GET",
              "description": "Lists location lists based on a given advertiser id.",
              "flatPath": "v3/advertisers/{advertisersId}/locationLists"
            },
            "create": {
              "path": "v3/advertisers/{+advertiserId}/locationLists",
              "httpMethod": "POST",
              "flatPath": "v3/advertisers/{advertisersId}/locationLists",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.create"
            },
            "get": {
              "httpMethod": "GET",
              "path": "v3/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "flatPath": "v3/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "description": "Gets a location list.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.locationLists.get"
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "create": {
                  "flatPath": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "description": "Creates an assignment between a location and a location list.",
                  "httpMethod": "POST",
                  "path": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create"
                },
                "delete": {
                  "path": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes the assignment between a location and a location list.",
                  "flatPath": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in deletedAssignedLocations and then create the assigned locations provided in createdAssignedLocations.",
                  "flatPath": "v3/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "httpMethod": "POST",
                  "path": "v3/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit"
                },
                "list": {
                  "description": "Lists locations assigned to a location list.",
                  "flatPath": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "path": "v3/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "GET",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "creatives": {
          "methods": {
            "list": {
              "id": "displayvideo.advertisers.creatives.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/creatives",
              "httpMethod": "GET",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v3/advertisers/{advertisersId}/creatives"
            },
            "patch": {
              "flatPath": "v3/advertisers/{advertisersId}/creatives/{creativesId}",
              "description": "Updates an existing creative. Returns the updated creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "httpMethod": "PATCH",
              "path": "v3/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.patch"
            },
            "delete": {
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "flatPath": "v3/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "DELETE",
              "path": "v3/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "id": "displayvideo.advertisers.creatives.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "description": "Gets a creative.",
              "flatPath": "v3/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "GET",
              "path": "v3/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "id": "displayvideo.advertisers.creatives.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "create": {
              "flatPath": "v3/advertisers/{advertisersId}/creatives",
              "description": "Creates a new creative. Returns the newly created creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "httpMethod": "POST",
              "path": "v3/advertisers/{+advertiserId}/creatives",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.creatives.create"
            }
          }
        },
        "adGroupAds": {
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.adGroupAds.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/adGroupAds",
              "httpMethod": "POST",
              "description": "Creates an ad group ad.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds"
            },
            "get": {
              "id": "displayvideo.advertisers.adGroupAds.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "httpMethod": "GET",
              "description": "Gets an ad group ad.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}"
            },
            "patch": {
              "id": "displayvideo.advertisers.adGroupAds.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Updates an ad group ad.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "path": "v3/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "httpMethod": "PATCH"
            },
            "delete": {
              "description": "Deletes an ad group ad.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds/{adGroupAdsId}",
              "httpMethod": "DELETE",
              "path": "v3/advertisers/{+advertiserId}/adGroupAds/{+adGroupAdId}",
              "id": "displayvideo.advertisers.adGroupAds.delete",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "id": "displayvideo.advertisers.adGroupAds.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Lists ad group ads.",
              "flatPath": "v3/advertisers/{advertisersId}/adGroupAds",
              "httpMethod": "GET",
              "path": "v3/advertisers/{+advertiserId}/adGroupAds"
            }
          }
        },
        "channels": {
          "methods": {
            "create": {
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "flatPath": "v3/advertisers/{advertisersId}/channels",
              "path": "v3/advertisers/{+advertiserId}/channels",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.channels.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "id": "displayvideo.advertisers.channels.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a channel for a partner or advertiser.",
              "flatPath": "v3/advertisers/{advertisersId}/channels/{channelsId}",
              "path": "v3/advertisers/{+advertiserId}/channels/{+channelId}",
              "httpMethod": "GET"
            },
            "patch": {
              "flatPath": "v3/advertisers/{advertisersId}/channels/{channelId}",
              "description": "Updates a channel. Returns the updated channel if successful.",
              "path": "v3/advertisers/{+advertiserId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.patch"
            },
            "list": {
              "flatPath": "v3/advertisers/{advertisersId}/channels",
              "description": "Lists channels for a partner or advertiser.",
              "httpMethod": "GET",
              "path": "v3/advertisers/{+advertiserId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.channels.list"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "create": {
                  "description": "Creates a site in a channel.",
                  "flatPath": "v3/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "path": "v3/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "id": "displayvideo.advertisers.channels.sites.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "flatPath": "v3/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "httpMethod": "POST",
                  "path": "v3/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit"
                },
                "replace": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "flatPath": "v3/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "httpMethod": "POST",
                  "path": "v3/advertisers/{advertiserId}/channels/{+channelId}/sites:replace"
                },
                "delete": {
                  "flatPath": "v3/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "description": "Deletes a site from a channel.",
                  "path": "v3/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.channels.sites.delete"
                },
                "list": {
                  "path": "v3/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "flatPath": "v3/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "id": "displayvideo.advertisers.channels.sites.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                }
              }
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists",
              "httpMethod": "POST"
            },
            "get": {
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "httpMethod": "GET"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.patch"
            },
            "delete": {
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "httpMethod": "DELETE",
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.delete"
            },
            "list": {
              "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.negativeKeywordLists.list"
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "flatPath": "v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "httpMethod": "POST",
                  "path": "v3/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords"
                },
                "bulkEdit": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "POST",
                  "path": "v3/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit",
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "flatPath": "v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit"
                },
                "replace": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "flatPath": "v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "httpMethod": "POST",
                  "path": "v3/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace"
                },
                "list": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "httpMethod": "GET",
                  "path": "v3/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "flatPath": "v3/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "flatPath": "v3/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "description": "Deletes a negative keyword from a negative keyword list.",
                  "httpMethod": "DELETE",
                  "path": "v3/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}"
                }
              }
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "supportsMediaUpload": true,
              "id": "displayvideo.advertisers.assets.upload",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "flatPath": "v3/advertisers/{advertisersId}/assets",
              "httpMethod": "POST",
              "path": "v3/advertisers/{+advertiserId}/assets"
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "list": {
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "flatPath": "v3/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "path": "v3/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "delete": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "flatPath": "v3/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "path": "v3/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "flatPath": "v3/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "path": "v3/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                },
                "create": {
                  "httpMethod": "POST",
                  "path": "v3/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "flatPath": "v3/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create"
                }
              }
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "id": "displayvideo.advertisers.invoices.list",
              "path": "v3/advertisers/{+advertiserId}/invoices",
              "httpMethod": "GET",
              "flatPath": "v3/advertisers/{advertisersId}/invoices",
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method."
            },
            "lookupInvoiceCurrency": {
              "description": "Retrieves the invoice currency used by an advertiser in a given month.",
              "flatPath": "v3/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "path": "v3/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "httpMethod": "GET",
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            }
          }
        },
        "lineItems": {
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.lineItems.create",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Creates a new line item. Returns the newly created line item if successful. YouTube & Partners line items cannot be created or updated using the API.",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems",
              "httpMethod": "POST",
              "path": "v3/advertisers/{+advertiserId}/lineItems"
            },
            "patch": {
              "httpMethod": "PATCH",
              "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your de[...]",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "id": "displayvideo.advertisers.lineItems.patch",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "id": "displayvideo.advertisers.lineItems.list",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v3/advertisers/{+advertiserId}/lineItems",
              "httpMethod": "GET",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems"
            },
            "get": {
              "id": "displayvideo.advertisers.lineItems.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "description": "Gets a line item.",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "GET"
            },
            "duplicate": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful. YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
              "httpMethod": "POST",
              "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate"
            },
            "bulkListAssignedTargetingOptions": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "description": "Lists assigned targeting options for multiple line items across targeting types.",
              "httpMethod": "GET",
              "path": "v3/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions"
            },
            "bulkEditAssignedTargetingOptions": {
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkUpdate * lineItems.patch * assignedTargetingOp[...]",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "path": "v3/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.advertisers.lineItems.delete",
              "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "httpMethod": "DELETE",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. YouTube & Partners line items cannot be created or updated using the API."
            },
            "bulkUpdate": {
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API.",
              "flatPath": "v3/advertisers/{advertisersId}/lineItems:bulkUpdate",
              "path": "v3/advertisers/{+advertiserId}/lineItems:bulkUpdate",
              "httpMethod": "POST",
              "id": "displayvideo.advertisers.lineItems.bulkUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Gets a single targeting option assigned to a line item.",
                      "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET",
                      "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    },
                    "create": {
                      "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * DeleteLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "description": "Lists the targeting options assigned to a line item.",
                      "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "httpMethod": "GET"
                    },
                    "delete": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * CreateLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "flatPath": "v3/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "path": "v3/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "httpMethod": "DELETE"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "path": "v3/guaranteedOrders/{+guaranteedOrderId}",
          "flatPath": "v3/guaranteedOrders/{guaranteedOrdersId}",
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.patch"
        },
        "editGuaranteedOrderReadAccessors": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "path": "v3/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "httpMethod": "POST",
          "flatPath": "v3/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "description": "Edits read advertisers of a guaranteed order."
        },
        "list": {
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
          "flatPath": "v3/guaranteedOrders",
          "httpMethod": "GET",
          "path": "v3/guaranteedOrders",
          "id": "displayvideo.guaranteedOrders.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "create": {
          "id": "displayvideo.guaranteedOrders.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful.",
          "flatPath": "v3/guaranteedOrders",
          "httpMethod": "POST",
          "path": "v3/guaranteedOrders"
        },
        "get": {
          "id": "displayvideo.guaranteedOrders.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "httpMethod": "GET",
          "path": "v3/guaranteedOrders/{+guaranteedOrderId}",
          "description": "Gets a guaranteed order.",
          "flatPath": "v3/guaranteedOrders/{guaranteedOrdersId}"
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "httpMethod": "GET",
              "path": "v3/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "flatPath": "v3/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "description": "Gets a single targeting option."
            },
            "search": {
              "httpMethod": "POST",
              "path": "v3/targetingTypes/{+targetingType}/targetingOptions:search",
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "flatPath": "v3/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "httpMethod": "GET",
              "path": "v3/targetingTypes/{+targetingType}/targetingOptions",
              "flatPath": "v3/targetingTypes/{targetingTypesId}/targetingOptions",
              "description": "Lists targeting options of a given type.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "id": "displayvideo.targetingTypes.targetingOptions.list"
            }
          }
        }
      }
    },
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "httpMethod": "POST",
          "path": "v3/sdfdownloadtasks",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with `sdfdownloadtasks.operations.get`. Any errors can be found in the err[...]",
          "flatPath": "v3/sdfdownloadtasks",
          "id": "displayvideo.sdfdownloadtasks.create",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "id": "displayvideo.sdfdownloadtasks.operations.get",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "flatPath": "v3/sdfdownloadtasks/operations/{operationsId}",
              "httpMethod": "GET",
              "path": "v3/{+name}"
            }
          }
        }
      }
    },
    "firstAndThirdPartyAudiences": {
      "methods": {
        "create": {
          "httpMethod": "POST",
          "path": "v3/firstAndThirdPartyAudiences",
          "flatPath": "v3/firstAndThirdPartyAudiences",
          "description": "Creates a FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstAndThirdPartyAudiences.create"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstAndThirdPartyAudiences.get",
          "path": "v3/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "httpMethod": "GET",
          "flatPath": "v3/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "description": "Gets a first and third party audience."
        },
        "patch": {
          "description": "Updates an existing FirstAndThirdPartyAudience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "flatPath": "v3/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}",
          "httpMethod": "PATCH",
          "path": "v3/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}",
          "id": "displayvideo.firstAndThirdPartyAudiences.patch",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "flatPath": "v3/firstAndThirdPartyAudiences",
          "description": "Lists first and third party audiences. The order is defined by the order_by parameter.",
          "httpMethod": "GET",
          "path": "v3/firstAndThirdPartyAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "id": "displayvideo.firstAndThirdPartyAudiences.list"
        },
        "editCustomerMatchMembers": {
          "id": "displayvideo.firstAndThirdPartyAudiences.editCustomerMatchMembers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Updates the member list of a Customer Match audience. Only supported for the following audience_type: * `CUSTOMER_MATCH_CONTACT_INFO` * `CUSTOMER_MATCH_DEVICE_ID`",
          "flatPath": "v3/firstAndThirdPartyAudiences/{firstAndThirdPartyAudiencesId}:editCustomerMatchMembers",
          "path": "v3/firstAndThirdPartyAudiences/{+firstAndThirdPartyAudienceId}:editCustomerMatchMembers",
          "httpMethod": "POST"
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "get": {
          "id": "displayvideo.googleAudiences.get",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Gets a Google audience.",
          "flatPath": "v3/googleAudiences/{googleAudiencesId}",
          "httpMethod": "GET",
          "path": "v3/googleAudiences/{+googleAudienceId}"
        },
        "list": {
          "id": "displayvideo.googleAudiences.list",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "flatPath": "v3/googleAudiences",
          "httpMethod": "GET",
          "path": "v3/googleAudiences"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "documentationLink": "https://developers.google.com/display-video/",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        }
      }
    }
  },
  "servicePath": "",
  "batchPath": "batch",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "canonicalName": "Display Video",
  "ownerDomain": "google.com",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "ownerName": "Google",
  "version_module": true,
  "version": "v3",
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true
}