{
  "documentationLink": "https://developers.google.com/display-video/",
  "ownerName": "Google",
  "title": "Display & Video 360 API",
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "resources": {
    "sdfdownloadtasks": {
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/sdfdownloadtasks",
          "id": "displayvideo.sdfdownloadtasks.create",
          "flatPath": "v2/sdfdownloadtasks",
          "httpMethod": "POST",
          "description": "Creates an SDF Download Task. Returns an Operation. An SDF Download Task is a long-running, asynchronous operation. The metadata type of this operation is SdfDownloadTaskMetadata. If the request is successful, the response type of the operation is SdfDownloadTask. The response will not include the download files, which must be retrieved with media.download. The state of operation can be retrieved with `sdfdownloadtasks.operations.get`. Any errors can be found in the err[...]"
        }
      },
      "resources": {
        "operations": {
          "methods": {
            "get": {
              "path": "v2/{+name}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/doubleclickbidmanager"
              ],
              "flatPath": "v2/sdfdownloadtasks/operations/{operationsId}",
              "httpMethod": "GET",
              "description": "Gets the latest state of an asynchronous SDF download task operation. Clients should poll this method at intervals of 30 seconds.",
              "id": "displayvideo.sdfdownloadtasks.operations.get"
            }
          }
        }
      }
    },
    "customLists": {
      "methods": {
        "get": {
          "flatPath": "v2/customLists/{customListsId}",
          "httpMethod": "GET",
          "description": "Gets a custom list.",
          "id": "displayvideo.customLists.get",
          "path": "v2/customLists/{+customListId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "flatPath": "v2/customLists",
          "httpMethod": "GET",
          "description": "Lists custom lists. The order is defined by the order_by parameter.",
          "id": "displayvideo.customLists.list",
          "path": "v2/customLists",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      }
    },
    "customBiddingAlgorithms": {
      "methods": {
        "list": {
          "flatPath": "v2/customBiddingAlgorithms",
          "httpMethod": "GET",
          "description": "Lists custom bidding algorithms that are accessible to the current user and can be used in bidding stratgies. The order is defined by the order_by parameter.",
          "id": "displayvideo.customBiddingAlgorithms.list",
          "path": "v2/customBiddingAlgorithms",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "id": "displayvideo.customBiddingAlgorithms.patch",
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing custom bidding algorithm. Returns the updated custom bidding algorithm if successful. Requests updating a custom bidding algorithm assigned to a line item will return an error."
        },
        "create": {
          "id": "displayvideo.customBiddingAlgorithms.create",
          "flatPath": "v2/customBiddingAlgorithms",
          "httpMethod": "POST",
          "description": "Creates a new custom bidding algorithm. Returns the newly created custom bidding algorithm if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/customBiddingAlgorithms"
        },
        "get": {
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}",
          "httpMethod": "GET",
          "description": "Gets a custom bidding algorithm.",
          "id": "displayvideo.customBiddingAlgorithms.get"
        },
        "uploadScript": {
          "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}:uploadScript",
          "httpMethod": "GET",
          "description": "Creates a custom bidding script reference object for a script file. The resulting reference object provides a resource path to which the script file should be uploaded. This reference object should be included in when creating a new custom bidding script object.",
          "id": "displayvideo.customBiddingAlgorithms.uploadScript",
          "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}:uploadScript",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "scripts": {
          "methods": {
            "create": {
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "httpMethod": "POST",
              "description": "Creates a new custom bidding script. Returns the newly created script if successful. Requests creating a custom bidding script under an algorithm assigned to a line item will return an error.",
              "id": "displayvideo.customBiddingAlgorithms.scripts.create",
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts",
              "httpMethod": "GET",
              "description": "Lists custom bidding scripts that belong to the given algorithm. The order is defined by the order_by parameter.",
              "id": "displayvideo.customBiddingAlgorithms.scripts.list"
            },
            "get": {
              "path": "v2/customBiddingAlgorithms/{+customBiddingAlgorithmId}/scripts/{+customBiddingScriptId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/customBiddingAlgorithms/{customBiddingAlgorithmsId}/scripts/{scriptsId}",
              "httpMethod": "GET",
              "description": "Gets a custom bidding script.",
              "id": "displayvideo.customBiddingAlgorithms.scripts.get"
            }
          }
        }
      }
    },
    "partners": {
      "methods": {
        "get": {
          "id": "displayvideo.partners.get",
          "flatPath": "v2/partners/{partnersId}",
          "httpMethod": "GET",
          "description": "Gets a partner.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/partners/{+partnerId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/partners",
          "id": "displayvideo.partners.list",
          "flatPath": "v2/partners",
          "httpMethod": "GET",
          "description": "Lists partners that are accessible to the current user. The order is defined by the order_by parameter."
        },
        "editAssignedTargetingOptions": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/partners/{+partnerId}:editAssignedTargetingOptions",
          "id": "displayvideo.partners.editAssignedTargetingOptions",
          "flatPath": "v2/partners/{partnersId}:editAssignedTargetingOptions",
          "httpMethod": "POST",
          "description": "Edits targeting options under a single partner. The operation will delete the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.deleteRequests and then create the assigned targeting options provided in BulkEditPartnerAssignedTargetingOptionsRequest.createRequests ."
        }
      },
      "resources": {
        "channels": {
          "methods": {
            "list": {
              "path": "v2/partners/{+partnerId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/partners/{partnersId}/channels",
              "httpMethod": "GET",
              "description": "Lists channels for a partner or advertiser.",
              "id": "displayvideo.partners.channels.list"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/partners/{+partnerId}/channels/{channelId}",
              "id": "displayvideo.partners.channels.patch",
              "flatPath": "v2/partners/{partnersId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "description": "Updates a channel. Returns the updated channel if successful."
            },
            "get": {
              "id": "displayvideo.partners.channels.get",
              "flatPath": "v2/partners/{partnersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/partners/{+partnerId}/channels/{+channelId}"
            },
            "create": {
              "path": "v2/partners/{+partnerId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/partners/{partnersId}/channels",
              "httpMethod": "POST",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "id": "displayvideo.partners.channels.create"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "create": {
                  "id": "displayvideo.partners.channels.sites.create",
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "description": "Creates a site in a channel.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites"
                },
                "replace": {
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:replace",
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "id": "displayvideo.partners.channels.sites.replace"
                },
                "list": {
                  "path": "v2/partners/{+partnerId}/channels/{+channelId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/partners/{partnersId}/channels/{channelsId}/sites",
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "id": "displayvideo.partners.channels.sites.list"
                },
                "delete": {
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel.",
                  "id": "displayvideo.partners.channels.sites.delete",
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "path": "v2/partners/{partnerId}/channels/{+channelId}/sites:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/partners/{partnerId}/channels/{channelsId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "id": "displayvideo.partners.channels.sites.bulkEdit"
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "description": "Gets a single targeting option assigned to a partner.",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.get"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.delete",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes an assigned targeting option from a partner."
                },
                "list": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.list",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "description": "Lists the targeting options assigned to a partner."
                },
                "create": {
                  "id": "displayvideo.partners.targetingTypes.assignedTargetingOptions.create",
                  "flatPath": "v2/partners/{partnersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "description": "Assigns a targeting option to a partner. Returns the assigned targeting option if successful.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/partners/{+partnerId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                }
              }
            }
          }
        }
      }
    },
    "combinedAudiences": {
      "methods": {
        "get": {
          "path": "v2/combinedAudiences/{+combinedAudienceId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/combinedAudiences/{combinedAudiencesId}",
          "httpMethod": "GET",
          "description": "Gets a combined audience.",
          "id": "displayvideo.combinedAudiences.get"
        },
        "list": {
          "path": "v2/combinedAudiences",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/combinedAudiences",
          "httpMethod": "GET",
          "description": "Lists combined audiences. The order is defined by the order_by parameter.",
          "id": "displayvideo.combinedAudiences.list"
        }
      }
    },
    "media": {
      "methods": {
        "upload": {
          "flatPath": "media/{mediaId}",
          "httpMethod": "POST",
          "description": "Uploads media. Upload is supported on the URI `/upload/media/{resource_name=**}?upload_type=media.` **Note**: Upload requests will not be successful without including `upload_type=media` query string.",
          "id": "displayvideo.media.upload",
          "path": "media/{+resourceName}",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ]
        },
        "download": {
          "path": "download/{+resourceName}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video",
            "https://www.googleapis.com/auth/doubleclickbidmanager"
          ],
          "flatPath": "download/{downloadId}",
          "httpMethod": "GET",
          "description": "Downloads media. Download is supported on the URI `/download/{resource_name=**}?alt=media.` **Note**: Download requests will not be successful without including `alt=media` query string.",
          "id": "displayvideo.media.download",
          "supportsMediaDownload": true
        }
      }
    },
    "guaranteedOrders": {
      "methods": {
        "create": {
          "flatPath": "v2/guaranteedOrders",
          "httpMethod": "POST",
          "description": "Creates a new guaranteed order. Returns the newly created guaranteed order if successful.",
          "id": "displayvideo.guaranteedOrders.create",
          "path": "v2/guaranteedOrders",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/guaranteedOrders",
          "id": "displayvideo.guaranteedOrders.list",
          "flatPath": "v2/guaranteedOrders",
          "httpMethod": "GET",
          "description": "Lists guaranteed orders that are accessible to the current user. The order is defined by the order_by parameter. If a filter by entity_status is not specified, guaranteed orders with entity status `ENTITY_STATUS_ARCHIVED` will not be included in the results."
        },
        "patch": {
          "id": "displayvideo.guaranteedOrders.patch",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing guaranteed order. Returns the updated guaranteed order if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}"
        },
        "editGuaranteedOrderReadAccessors": {
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}:editGuaranteedOrderReadAccessors",
          "httpMethod": "POST",
          "description": "Edits read advertisers of a guaranteed order.",
          "id": "displayvideo.guaranteedOrders.editGuaranteedOrderReadAccessors",
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}:editGuaranteedOrderReadAccessors",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/guaranteedOrders/{+guaranteedOrderId}",
          "id": "displayvideo.guaranteedOrders.get",
          "flatPath": "v2/guaranteedOrders/{guaranteedOrdersId}",
          "httpMethod": "GET",
          "description": "Gets a guaranteed order."
        }
      }
    },
    "users": {
      "methods": {
        "create": {
          "path": "v2/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v2/users",
          "httpMethod": "POST",
          "description": "Creates a new user. Returns the newly created user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "id": "displayvideo.users.create"
        },
        "delete": {
          "path": "v2/users/{+userId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v2/users/{usersId}",
          "httpMethod": "DELETE",
          "description": "Deletes a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "id": "displayvideo.users.delete"
        },
        "list": {
          "flatPath": "v2/users",
          "httpMethod": "GET",
          "description": "Lists users that are accessible to the current user. If two users have user roles on the same partner or advertiser, they can access each other. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "id": "displayvideo.users.list",
          "path": "v2/users",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "patch": {
          "path": "v2/users/{+userId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "flatPath": "v2/users/{usersId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing user. Returns the updated user if successful. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "id": "displayvideo.users.patch"
        },
        "get": {
          "flatPath": "v2/users/{usersId}",
          "httpMethod": "GET",
          "description": "Gets a user. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature does not work for this method.",
          "id": "displayvideo.users.get",
          "path": "v2/users/{+userId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ]
        },
        "bulkEditAssignedUserRoles": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video-user-management"
          ],
          "path": "v2/users/{+userId}:bulkEditAssignedUserRoles",
          "id": "displayvideo.users.bulkEditAssignedUserRoles",
          "flatPath": "v2/users/{usersId}:bulkEditAssignedUserRoles",
          "httpMethod": "POST",
          "description": "Bulk edits user roles for a user. The operation will delete the assigned user roles provided in BulkEditAssignedUserRolesRequest.deletedAssignedUserRoles and then assign the user roles provided in BulkEditAssignedUserRolesRequest.createdAssignedUserRoles. This method has unique authentication requirements. Read the prerequisites in our [Managing Users guide](/display-video/api/guides/users/overview#prerequisites) before using this method. The \"Try this method\" feature[...]"
        }
      }
    },
    "floodlightGroups": {
      "methods": {
        "get": {
          "flatPath": "v2/floodlightGroups/{floodlightGroupsId}",
          "httpMethod": "GET",
          "description": "Gets a Floodlight group.",
          "id": "displayvideo.floodlightGroups.get",
          "path": "v2/floodlightGroups/{+floodlightGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "id": "displayvideo.floodlightGroups.patch",
          "flatPath": "v2/floodlightGroups/{floodlightGroupId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing Floodlight group. Returns the updated Floodlight group if successful.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/floodlightGroups/{floodlightGroupId}"
        }
      },
      "resources": {
        "floodlightActivities": {
          "methods": {
            "get": {
              "id": "displayvideo.floodlightGroups.floodlightActivities.get",
              "flatPath": "v2/floodlightGroups/{floodlightGroupsId}/floodlightActivities/{floodlightActivitiesId}",
              "httpMethod": "GET",
              "description": "Gets a Floodlight activity.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/floodlightGroups/{+floodlightGroupId}/floodlightActivities/{+floodlightActivityId}"
            },
            "list": {
              "path": "v2/floodlightGroups/{+floodlightGroupId}/floodlightActivities",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/floodlightGroups/{floodlightGroupsId}/floodlightActivities",
              "httpMethod": "GET",
              "description": "Lists Floodlight activities in a Floodlight group.",
              "id": "displayvideo.floodlightGroups.floodlightActivities.list"
            }
          }
        }
      }
    },
    "advertisers": {
      "methods": {
        "create": {
          "flatPath": "v2/advertisers",
          "httpMethod": "POST",
          "description": "Creates a new advertiser. Returns the newly created advertiser if successful. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
          "id": "displayvideo.advertisers.create",
          "path": "v2/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "editAssignedTargetingOptions": {
          "id": "displayvideo.advertisers.editAssignedTargetingOptions",
          "flatPath": "v2/advertisers/{advertisersId}:editAssignedTargetingOptions",
          "httpMethod": "POST",
          "description": "Edits targeting options under a single advertiser. The operation will delete the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAdvertiserAssignedTargetingOptionsRequest.create_requests .",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/advertisers/{+advertiserId}:editAssignedTargetingOptions"
        },
        "list": {
          "flatPath": "v2/advertisers",
          "httpMethod": "GET",
          "description": "Lists advertisers that are accessible to the current user. The order is defined by the order_by parameter. A single partner_id is required. Cross-partner listing is not supported.",
          "id": "displayvideo.advertisers.list",
          "path": "v2/advertisers",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "patch": {
          "flatPath": "v2/advertisers/{advertisersId}",
          "httpMethod": "PATCH",
          "description": "Updates an existing advertiser. Returns the updated advertiser if successful.",
          "id": "displayvideo.advertisers.patch",
          "path": "v2/advertisers/{+advertiserId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "listAssignedTargetingOptions": {
          "flatPath": "v2/advertisers/{advertisersId}:listAssignedTargetingOptions",
          "httpMethod": "GET",
          "description": "Lists assigned targeting options of an advertiser across targeting types.",
          "id": "displayvideo.advertisers.listAssignedTargetingOptions",
          "path": "v2/advertisers/{+advertiserId}:listAssignedTargetingOptions",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        },
        "delete": {
          "id": "displayvideo.advertisers.delete",
          "flatPath": "v2/advertisers/{advertisersId}",
          "httpMethod": "DELETE",
          "description": "Deletes an advertiser. Deleting an advertiser will delete all of its child resources, for example, campaigns, insertion orders and line items. A deleted advertiser cannot be recovered.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/advertisers/{+advertiserId}"
        },
        "audit": {
          "path": "v2/advertisers/{+advertiserId}:audit",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/advertisers/{advertisersId}:audit",
          "httpMethod": "GET",
          "description": "Audits an advertiser. Returns the counts of used entities per resource type under the advertiser provided. Used entities count towards their respective resource limit. See https://support.google.com/displayvideo/answer/6071450.",
          "id": "displayvideo.advertisers.audit"
        },
        "get": {
          "flatPath": "v2/advertisers/{advertisersId}",
          "httpMethod": "GET",
          "description": "Gets an advertiser.",
          "id": "displayvideo.advertisers.get",
          "path": "v2/advertisers/{+advertiserId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ]
        }
      },
      "resources": {
        "manualTriggers": {
          "methods": {
            "activate": {
              "id": "displayvideo.advertisers.manualTriggers.activate",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:activate",
              "httpMethod": "POST",
              "description": "Activates a manual trigger. Each activation of the manual trigger must be at least 5 minutes apart, otherwise an error will be returned. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:activate"
            },
            "deactivate": {
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}:deactivate",
              "httpMethod": "POST",
              "description": "Deactivates a manual trigger. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "id": "displayvideo.advertisers.manualTriggers.deactivate",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}:deactivate",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}",
              "id": "displayvideo.advertisers.manualTriggers.get",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "httpMethod": "GET",
              "description": "Gets a manual trigger. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information."
            },
            "create": {
              "path": "v2/advertisers/{+advertiserId}/manualTriggers",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers",
              "httpMethod": "POST",
              "description": "Creates a new manual trigger. Returns the newly created manual trigger if successful. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "id": "displayvideo.advertisers.manualTriggers.create"
            },
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers",
              "httpMethod": "GET",
              "description": "Lists manual triggers that are accessible to the current user for a given advertiser ID. The order is defined by the order_by parameter. A single advertiser_id is required. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "id": "displayvideo.advertisers.manualTriggers.list",
              "path": "v2/advertisers/{+advertiserId}/manualTriggers",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "id": "displayvideo.advertisers.manualTriggers.patch",
              "flatPath": "v2/advertisers/{advertisersId}/manualTriggers/{manualTriggersId}",
              "httpMethod": "PATCH",
              "description": "Updates a manual trigger. Returns the updated manual trigger if successful. **Warning:** Line Items using manual triggers no longer serve in Display & Video 360. This method will sunset on August 1, 2023. Read our [feature deprecation announcement](/display-video/api/deprecations#features.manual_triggers) for more information.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/manualTriggers/{+triggerId}"
            }
          }
        },
        "youtubeAdGroups": {
          "methods": {
            "bulkListAdGroupAssignedTargetingOptions": {
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups:bulkListAdGroupAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options for multiple YouTube ad groups across targeting types. Inherited assigned targeting options are not included.",
              "id": "displayvideo.advertisers.youtubeAdGroups.bulkListAdGroupAssignedTargetingOptions"
            },
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}",
              "httpMethod": "GET",
              "description": "Gets a YouTube ad group.",
              "id": "displayvideo.advertisers.youtubeAdGroups.get",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups",
              "httpMethod": "GET",
              "description": "Lists YouTube ad groups.",
              "id": "displayvideo.advertisers.youtubeAdGroups.list",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "list": {
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.list"
                    },
                    "get": {
                      "path": "v2/advertisers/{+advertiserId}/youtubeAdGroups/{+youtubeAdGroupId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroups/{youtubeAdGroupsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a YouTube ad group. Inherited assigned targeting options are not included.",
                      "id": "displayvideo.advertisers.youtubeAdGroups.targetingTypes.assignedTargetingOptions.get"
                    }
                  }
                }
              }
            }
          }
        },
        "targetingTypes": {
          "resources": {
            "assignedTargetingOptions": {
              "methods": {
                "get": {
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "GET",
                  "description": "Gets a single targeting option assigned to an advertiser.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.get"
                },
                "delete": {
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes an assigned targeting option from an advertiser.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.delete",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "list": {
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "GET",
                  "description": "Lists the targeting options assigned to an advertiser.",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.list",
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{+advertiserId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                  "id": "displayvideo.advertisers.targetingTypes.assignedTargetingOptions.create",
                  "flatPath": "v2/advertisers/{advertisersId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                  "httpMethod": "POST",
                  "description": "Assigns a targeting option to an advertiser. Returns the assigned targeting option if successful."
                }
              }
            }
          }
        },
        "negativeKeywordLists": {
          "methods": {
            "create": {
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists",
              "httpMethod": "POST",
              "description": "Creates a new negative keyword list. Returns the newly created negative keyword list if successful.",
              "id": "displayvideo.advertisers.negativeKeywordLists.create",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists",
              "httpMethod": "GET",
              "description": "Lists negative keyword lists based on a given advertiser id.",
              "id": "displayvideo.advertisers.negativeKeywordLists.list"
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{negativeKeywordListId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.patch",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListId}",
              "httpMethod": "PATCH",
              "description": "Updates a negative keyword list. Returns the updated negative keyword list if successful."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "id": "displayvideo.advertisers.negativeKeywordLists.delete",
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a negative keyword list given an advertiser ID and a negative keyword list ID."
            },
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}",
              "httpMethod": "GET",
              "description": "Gets a negative keyword list given an advertiser ID and a negative keyword list ID.",
              "id": "displayvideo.advertisers.negativeKeywordLists.get",
              "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          },
          "resources": {
            "negativeKeywords": {
              "methods": {
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords/{+keywordValue}",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.delete",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords/{negativeKeywordsId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a negative keyword from a negative keyword list."
                },
                "list": {
                  "flatPath": "v2/advertisers/{advertisersId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "httpMethod": "GET",
                  "description": "Lists negative keywords in a negative keyword list.",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.list",
                  "path": "v2/advertisers/{+advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords",
                  "httpMethod": "POST",
                  "description": "Creates a negative keyword in a negative keyword list.",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.create",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "replace": {
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:replace",
                  "httpMethod": "POST",
                  "description": "Replaces all negative keywords in a single negative keyword list. The operation will replace the keywords in a negative keyword list with keywords provided in ReplaceNegativeKeywordsRequest.new_negative_keywords.",
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.replace",
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:replace",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "id": "displayvideo.advertisers.negativeKeywordLists.negativeKeywords.bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/negativeKeywordLists/{negativeKeywordListsId}/negativeKeywords:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits negative keywords in a single negative keyword list. The operation will delete the negative keywords provided in BulkEditNegativeKeywordsRequest.deleted_negative_keywords and then create the negative keywords provided in BulkEditNegativeKeywordsRequest.created_negative_keywords. This operation is guaranteed to be atomic and will never result in a partial success or partial failure.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/negativeKeywordLists/{+negativeKeywordListId}/negativeKeywords:bulkEdit"
                }
              }
            }
          }
        },
        "channels": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}",
              "id": "displayvideo.advertisers.channels.get",
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}",
              "httpMethod": "GET",
              "description": "Gets a channel for a partner or advertiser."
            },
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "httpMethod": "GET",
              "description": "Lists channels for a partner or advertiser.",
              "id": "displayvideo.advertisers.channels.list",
              "path": "v2/advertisers/{+advertiserId}/channels",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/channels/{channelId}",
              "id": "displayvideo.advertisers.channels.patch",
              "flatPath": "v2/advertisers/{advertisersId}/channels/{channelId}",
              "httpMethod": "PATCH",
              "description": "Updates a channel. Returns the updated channel if successful."
            },
            "create": {
              "id": "displayvideo.advertisers.channels.create",
              "flatPath": "v2/advertisers/{advertisersId}/channels",
              "httpMethod": "POST",
              "description": "Creates a new channel. Returns the newly created channel if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/channels"
            }
          },
          "resources": {
            "sites": {
              "methods": {
                "list": {
                  "path": "v2/advertisers/{+advertiserId}/channels/{+channelId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertisersId}/channels/{channelsId}/sites",
                  "httpMethod": "GET",
                  "description": "Lists sites in a channel.",
                  "id": "displayvideo.advertisers.channels.sites.list"
                },
                "delete": {
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites/{+urlOrAppId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites/{sitesId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes a site from a channel.",
                  "id": "displayvideo.advertisers.channels.sites.delete"
                },
                "create": {
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites",
                  "httpMethod": "POST",
                  "description": "Creates a site in a channel.",
                  "id": "displayvideo.advertisers.channels.sites.create"
                },
                "replace": {
                  "id": "displayvideo.advertisers.channels.sites.replace",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:replace",
                  "httpMethod": "POST",
                  "description": "Replaces all of the sites under a single channel. The operation will replace the sites under a channel with the sites provided in ReplaceSitesRequest.new_sites. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:replace"
                },
                "bulkEdit": {
                  "id": "displayvideo.advertisers.channels.sites.bulkEdit",
                  "flatPath": "v2/advertisers/{advertiserId}/channels/{channelsId}/sites:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits sites under a single channel. The operation will delete the sites provided in BulkEditSitesRequest.deleted_sites and then create the sites provided in BulkEditSitesRequest.created_sites.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/channels/{+channelId}/sites:bulkEdit"
                }
              }
            }
          }
        },
        "creatives": {
          "methods": {
            "get": {
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "GET",
              "description": "Gets a creative.",
              "id": "displayvideo.advertisers.creatives.get"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/creatives",
              "id": "displayvideo.advertisers.creatives.create",
              "flatPath": "v2/advertisers/{advertisersId}/creatives",
              "httpMethod": "POST",
              "description": "Creates a new creative. Returns the newly created creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request."
            },
            "delete": {
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "DELETE",
              "description": "Deletes a creative. Returns error code `NOT_FOUND` if the creative does not exist. The creative should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, before it can be deleted. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "id": "displayvideo.advertisers.creatives.delete",
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "id": "displayvideo.advertisers.creatives.list",
              "flatPath": "v2/advertisers/{advertisersId}/creatives",
              "httpMethod": "GET",
              "description": "Lists creatives in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, creatives with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/creatives"
            },
            "patch": {
              "path": "v2/advertisers/{+advertiserId}/creatives/{+creativeId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/creatives/{creativesId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing creative. Returns the updated creative if successful. A [\"Standard\" user role](//support.google.com/displayvideo/answer/2723011) or greater for the parent advertiser or partner is required to make this request.",
              "id": "displayvideo.advertisers.creatives.patch"
            }
          }
        },
        "assets": {
          "methods": {
            "upload": {
              "id": "displayvideo.advertisers.assets.upload",
              "flatPath": "v2/advertisers/{advertisersId}/assets",
              "httpMethod": "POST",
              "description": "Uploads an asset. Returns the ID of the newly uploaded asset if successful. The asset file size should be no more than 10 MB for images, 200 MB for ZIP files, and 1 GB for videos. Must be used within the [multipart media upload process](/display-video/api/guides/how-tos/upload#multipart). Examples using provided client libraries can be found in our [Creating Creatives guide](/display-video/api/guides/creating-creatives/overview#upload_an_asset).",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/assets",
              "supportsMediaUpload": true
            }
          }
        },
        "insertionOrders": {
          "methods": {
            "get": {
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "GET",
              "description": "Gets an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist.",
              "id": "displayvideo.advertisers.insertionOrders.get"
            },
            "create": {
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "httpMethod": "POST",
              "description": "Creates a new insertion order. Returns the newly created insertion order if successful.",
              "id": "displayvideo.advertisers.insertionOrders.create"
            },
            "delete": {
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "DELETE",
              "description": "Deletes an insertion order. Returns error code `NOT_FOUND` if the insertion order does not exist. The insertion order should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it.",
              "id": "displayvideo.advertisers.insertionOrders.delete",
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "path": "v2/advertisers/{+advertiserId}/insertionOrders",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders",
              "httpMethod": "GET",
              "description": "Lists insertion orders in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, insertion orders with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "id": "displayvideo.advertisers.insertionOrders.list"
            },
            "patch": {
              "path": "v2/advertisers/{+advertiserId}/insertionOrders/{+insertionOrderId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/insertionOrders/{insertionOrdersId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing insertion order. Returns the updated insertion order if successful.",
              "id": "displayvideo.advertisers.insertionOrders.patch"
            }
          }
        },
        "lineItems": {
          "methods": {
            "bulkUpdate": {
              "id": "displayvideo.advertisers.lineItems.bulkUpdate",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkUpdate",
              "httpMethod": "POST",
              "description": "Updates multiple line items. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * UpdateLineItem * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkUpdate"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.create",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "httpMethod": "POST",
              "description": "Creates a new line item. Returns the newly created line item if successful. YouTube & Partners line items cannot be created or updated using the API."
            },
            "duplicate": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}:duplicate",
              "id": "displayvideo.advertisers.lineItems.duplicate",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}:duplicate",
              "httpMethod": "POST",
              "description": "Duplicates a line item. Returns the ID of the created line item if successful. YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors."
            },
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems",
              "id": "displayvideo.advertisers.lineItems.list",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems",
              "httpMethod": "GET",
              "description": "Lists line items in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, line items with `ENTITY_STATUS_ARCHIVED` will not be included in the results."
            },
            "bulkEditAssignedTargetingOptions": {
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkEditAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkEditAssignedTargetingOptions",
              "httpMethod": "POST",
              "description": "Bulk edits targeting options under multiple line items. The operation will delete the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.delete_requests and then create the assigned targeting options provided in BulkEditAssignedTargetingOptionsRequest.create_requests. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkUpdate * lineItems.patch * assignedTargetingOp[...]",
              "id": "displayvideo.advertisers.lineItems.bulkEditAssignedTargetingOptions"
            },
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "GET",
              "description": "Gets a line item.",
              "id": "displayvideo.advertisers.lineItems.get",
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkListAssignedTargetingOptions": {
              "path": "v2/advertisers/{+advertiserId}/lineItems:bulkListAssignedTargetingOptions",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems:bulkListAssignedTargetingOptions",
              "httpMethod": "GET",
              "description": "Lists assigned targeting options for multiple line items across targeting types.",
              "id": "displayvideo.advertisers.lineItems.bulkListAssignedTargetingOptions"
            },
            "patch": {
              "id": "displayvideo.advertisers.lineItems.patch",
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing line item. Returns the updated line item if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * BulkEditAssignedTargetingOptions * BulkUpdateLineItems * assignedTargetingOptions.create * assignedTargetingOptions.delete YouTube & Partners line items cannot be created or updated using the API. **This method regularly experiences high latency.** We recommend [increasing your de[...]",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}"
            },
            "delete": {
              "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}",
              "httpMethod": "DELETE",
              "description": "Deletes a line item. Returns error code `NOT_FOUND` if the line item does not exist. The line item should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. YouTube & Partners line items cannot be created or updated using the API.",
              "id": "displayvideo.advertisers.lineItems.delete"
            }
          },
          "resources": {
            "targetingTypes": {
              "resources": {
                "assignedTargetingOptions": {
                  "methods": {
                    "get": {
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "GET",
                      "description": "Gets a single targeting option assigned to a line item.",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.get",
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ]
                    },
                    "delete": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.delete",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions/{assignedTargetingOptionsId}",
                      "httpMethod": "DELETE",
                      "description": "Deletes an assigned targeting option from a line item. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * CreateLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions/{+assignedTargetingOptionId}"
                    },
                    "list": {
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions",
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.list",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "GET",
                      "description": "Lists the targeting options assigned to a line item."
                    },
                    "create": {
                      "id": "displayvideo.advertisers.lineItems.targetingTypes.assignedTargetingOptions.create",
                      "flatPath": "v2/advertisers/{advertisersId}/lineItems/{lineItemsId}/targetingTypes/{targetingTypesId}/assignedTargetingOptions",
                      "httpMethod": "POST",
                      "description": "Assigns a targeting option to a line item. Returns the assigned targeting option if successful. Requests to this endpoint cannot be made concurrently with the following requests updating the same line item: * lineItems.bulkEditAssignedTargetingOptions * lineItems.bulkUpdate * lineItems.patch * DeleteLineItemAssignedTargetingOption YouTube & Partners line items cannot be created or updated using the API.",
                      "scopes": [
                        "https://www.googleapis.com/auth/display-video"
                      ],
                      "path": "v2/advertisers/{+advertiserId}/lineItems/{+lineItemId}/targetingTypes/{+targetingType}/assignedTargetingOptions"
                    }
                  }
                }
              }
            }
          }
        },
        "campaigns": {
          "methods": {
            "get": {
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "GET",
              "description": "Gets a campaign.",
              "id": "displayvideo.advertisers.campaigns.get"
            },
            "create": {
              "flatPath": "v2/advertisers/{advertisersId}/campaigns",
              "httpMethod": "POST",
              "description": "Creates a new campaign. Returns the newly created campaign if successful.",
              "id": "displayvideo.advertisers.campaigns.create",
              "path": "v2/advertisers/{+advertiserId}/campaigns",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "list": {
              "id": "displayvideo.advertisers.campaigns.list",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns",
              "httpMethod": "GET",
              "description": "Lists campaigns in an advertiser. The order is defined by the order_by parameter. If a filter by entity_status is not specified, campaigns with `ENTITY_STATUS_ARCHIVED` will not be included in the results.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/campaigns"
            },
            "patch": {
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "PATCH",
              "description": "Updates an existing campaign. Returns the updated campaign if successful.",
              "id": "displayvideo.advertisers.campaigns.patch",
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/campaigns/{+campaignId}",
              "id": "displayvideo.advertisers.campaigns.delete",
              "flatPath": "v2/advertisers/{advertisersId}/campaigns/{campaignsId}",
              "httpMethod": "DELETE",
              "description": "Permanently deletes a campaign. A deleted campaign cannot be recovered. The campaign should be archived first, i.e. set entity_status to `ENTITY_STATUS_ARCHIVED`, to be able to delete it. **This method regularly experiences high latency.** We recommend [increasing your default timeout](/display-video/api/guides/best-practices/timeouts#client_library_timeout) to avoid errors."
            }
          }
        },
        "locationLists": {
          "methods": {
            "create": {
              "id": "displayvideo.advertisers.locationLists.create",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists",
              "httpMethod": "POST",
              "description": "Creates a new location list. Returns the newly created location list if successful.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/locationLists"
            },
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListsId}",
              "httpMethod": "GET",
              "description": "Gets a location list.",
              "id": "displayvideo.advertisers.locationLists.get",
              "path": "v2/advertisers/{+advertiserId}/locationLists/{+locationListId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "flatPath": "v2/advertisers/{advertisersId}/locationLists",
              "httpMethod": "GET",
              "description": "Lists location lists based on a given advertiser id.",
              "id": "displayvideo.advertisers.locationLists.list",
              "path": "v2/advertisers/{+advertiserId}/locationLists",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "patch": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/locationLists/{locationListId}",
              "id": "displayvideo.advertisers.locationLists.patch",
              "flatPath": "v2/advertisers/{advertisersId}/locationLists/{locationListId}",
              "httpMethod": "PATCH",
              "description": "Updates a location list. Returns the updated location list if successful."
            }
          },
          "resources": {
            "assignedLocations": {
              "methods": {
                "delete": {
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{assignedLocationsId}",
                  "httpMethod": "DELETE",
                  "description": "Deletes the assignment between a location and a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.delete",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations/{+assignedLocationId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "bulkEdit": {
                  "path": "v2/advertisers/{advertiserId}/locationLists/{+locationListId}/assignedLocations:bulkEdit",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListsId}/assignedLocations:bulkEdit",
                  "httpMethod": "POST",
                  "description": "Bulk edits multiple assignments between locations and a single location list. The operation will delete the assigned locations provided in deletedAssignedLocations and then create the assigned locations provided in createdAssignedLocations.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.bulkEdit"
                },
                "list": {
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "GET",
                  "description": "Lists locations assigned to a location list.",
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.list",
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ]
                },
                "create": {
                  "id": "displayvideo.advertisers.locationLists.assignedLocations.create",
                  "flatPath": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations",
                  "httpMethod": "POST",
                  "description": "Creates an assignment between a location and a location list.",
                  "scopes": [
                    "https://www.googleapis.com/auth/display-video"
                  ],
                  "path": "v2/advertisers/{advertiserId}/locationLists/{locationListId}/assignedLocations"
                }
              }
            }
          }
        },
        "youtubeAdGroupAds": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds",
              "id": "displayvideo.advertisers.youtubeAdGroupAds.list",
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds",
              "httpMethod": "GET",
              "description": "Lists YouTube ad group ads."
            },
            "get": {
              "flatPath": "v2/advertisers/{advertisersId}/youtubeAdGroupAds/{youtubeAdGroupAdsId}",
              "httpMethod": "GET",
              "description": "Gets a YouTube ad group ad.",
              "id": "displayvideo.advertisers.youtubeAdGroupAds.get",
              "path": "v2/advertisers/{+advertiserId}/youtubeAdGroupAds/{+youtubeAdGroupAdId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            }
          }
        },
        "invoices": {
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "path": "v2/advertisers/{+advertiserId}/invoices",
              "id": "displayvideo.advertisers.invoices.list",
              "flatPath": "v2/advertisers/{advertisersId}/invoices",
              "httpMethod": "GET",
              "description": "Lists invoices posted for an advertiser in a given month. Invoices generated by billing profiles with a \"Partner\" invoice level are not retrievable through this method."
            },
            "lookupInvoiceCurrency": {
              "path": "v2/advertisers/{+advertiserId}/invoices:lookupInvoiceCurrency",
              "scopes": [
                "https://www.googleapis.com/auth/display-video",
                "https://www.googleapis.com/auth/display-video-mediaplanning"
              ],
              "flatPath": "v2/advertisers/{advertisersId}/invoices:lookupInvoiceCurrency",
              "httpMethod": "GET",
              "description": "Retrieves the invoice currency used by an advertiser in a given month.",
              "id": "displayvideo.advertisers.invoices.lookupInvoiceCurrency"
            }
          }
        }
      }
    },
    "googleAudiences": {
      "methods": {
        "list": {
          "id": "displayvideo.googleAudiences.list",
          "flatPath": "v2/googleAudiences",
          "httpMethod": "GET",
          "description": "Lists Google audiences. The order is defined by the order_by parameter.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/googleAudiences"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/googleAudiences/{+googleAudienceId}",
          "id": "displayvideo.googleAudiences.get",
          "flatPath": "v2/googleAudiences/{googleAudiencesId}",
          "httpMethod": "GET",
          "description": "Gets a Google audience."
        }
      }
    },
    "inventorySourceGroups": {
      "methods": {
        "delete": {
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "DELETE",
          "description": "Deletes an inventory source group.",
          "id": "displayvideo.inventorySourceGroups.delete"
        },
        "list": {
          "path": "v2/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySourceGroups",
          "httpMethod": "GET",
          "description": "Lists inventory source groups that are accessible to the current user. The order is defined by the order_by parameter.",
          "id": "displayvideo.inventorySourceGroups.list"
        },
        "patch": {
          "path": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupId}",
          "httpMethod": "PATCH",
          "description": "Updates an inventory source group. Returns the updated inventory source group if successful.",
          "id": "displayvideo.inventorySourceGroups.patch"
        },
        "create": {
          "path": "v2/inventorySourceGroups",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "flatPath": "v2/inventorySourceGroups",
          "httpMethod": "POST",
          "description": "Creates a new inventory source group. Returns the newly created inventory source group if successful.",
          "id": "displayvideo.inventorySourceGroups.create"
        },
        "get": {
          "id": "displayvideo.inventorySourceGroups.get",
          "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}",
          "httpMethod": "GET",
          "description": "Gets an inventory source group.",
          "scopes": [
            "https://www.googleapis.com/auth/display-video"
          ],
          "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}"
        }
      },
      "resources": {
        "assignedInventorySources": {
          "methods": {
            "create": {
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "httpMethod": "POST",
              "description": "Creates an assignment between an inventory source and an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.create",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources",
              "httpMethod": "GET",
              "description": "Lists inventory sources assigned to an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.list",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "delete": {
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources/{assignedInventorySourcesId}",
              "httpMethod": "DELETE",
              "description": "Deletes the assignment between an inventory source and an inventory source group.",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.delete",
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources/{+assignedInventorySourceId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "bulkEdit": {
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/inventorySourceGroups/{+inventorySourceGroupId}/assignedInventorySources:bulkEdit",
              "id": "displayvideo.inventorySourceGroups.assignedInventorySources.bulkEdit",
              "flatPath": "v2/inventorySourceGroups/{inventorySourceGroupsId}/assignedInventorySources:bulkEdit",
              "httpMethod": "POST",
              "description": "Bulk edits multiple assignments between inventory sources and a single inventory source group. The operation will delete the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.deleted_assigned_inventory_sources and then create the assigned inventory sources provided in BulkEditAssignedInventorySourcesRequest.created_assigned_inventory_sources."
            }
          }
        }
      }
    },
    "targetingTypes": {
      "resources": {
        "targetingOptions": {
          "methods": {
            "get": {
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions/{targetingOptionsId}",
              "httpMethod": "GET",
              "description": "Gets a single targeting option.",
              "id": "displayvideo.targetingTypes.targetingOptions.get",
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions/{+targetingOptionId}",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ]
            },
            "list": {
              "id": "displayvideo.targetingTypes.targetingOptions.list",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions",
              "httpMethod": "GET",
              "description": "Lists targeting options of a given type.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions"
            },
            "search": {
              "id": "displayvideo.targetingTypes.targetingOptions.search",
              "flatPath": "v2/targetingTypes/{targetingTypesId}/targetingOptions:search",
              "httpMethod": "POST",
              "description": "Searches for targeting options of a given type based on the given search terms.",
              "scopes": [
                "https://www.googleapis.com/auth/display-video"
              ],
              "path": "v2/targetingTypes/{+targetingType}/targetingOptions:search"
            }
          }
        }
      }
    }
  },
  "servicePath": "",
  "version": "v2",
  "mtlsRootUrl": "https://displayvideo.mtls.googleapis.com/",
  "name": "displayvideo",
  "description": "Display & Video 360 API allows users to automate complex Display & Video 360 workflows, such as creating insertion orders and setting targeting options for individual line items.",
  "id": "displayvideo:v2",
  "rootUrl": "https://displayvideo.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "canonicalName": "Display Video",
  "kind": "discovery#restDescription",
  "revision": "20260421",
  "baseUrl": "https://displayvideo.googleapis.com/",
  "protocol": "rest",
  "version_module": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/display-video-user-management": {
          "description": "Private Service: https://www.googleapis.com/auth/display-video-user-management"
        },
        "https://www.googleapis.com/auth/doubleclickbidmanager": {
          "description": "View and manage your reports in DoubleClick Bid Manager"
        },
        "https://www.googleapis.com/auth/display-video-mediaplanning": {
          "description": "Create, see, and edit Display & Video 360 Campaign entities and see billing invoices"
        },
        "https://www.googleapis.com/auth/display-video": {
          "description": "Create, see, edit, and permanently delete your Display & Video 360 entities and reports"
        }
      }
    }
  },
  "basePath": ""
}