{
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "rootUrl": "https://www.googleapis.com/",
  "documentationLink": "https://developers.google.com/workspace/drive/",
  "ownerName": "Google",
  "id": "drive:v2",
  "protocol": "rest",
  "version": "v2",
  "batchPath": "batch/drive/v2",
  "basePath": "/drive/v2/",
  "revision": "20260428",
  "ownerDomain": "google.com",
  "title": "Google Drive API",
  "discoveryVersion": "v1",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "resources": {
    "drives": {
      "methods": {
        "delete": {
          "flatPath": "drives/{driveId}",
          "description": "Permanently deletes a shared drive for which the user is an `organizer`. The shared drive cannot contain any untrashed items.",
          "id": "drive.drives.delete",
          "path": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "DELETE"
        },
        "update": {
          "description": "Updates the metadata for a shared drive.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "PUT",
          "id": "drive.drives.update",
          "flatPath": "drives/{driveId}",
          "path": "drives/{driveId}"
        },
        "insert": {
          "flatPath": "drives",
          "id": "drive.drives.insert",
          "path": "drives",
          "description": "Creates a new shared drive.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "id": "drive.drives.list",
          "flatPath": "drives",
          "path": "drives",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](https://developers.google.com/workspace/drive/api/guides/search-shareddrives) guide.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "get": {
          "description": "Gets a shared drive's metadata by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.drives.get",
          "flatPath": "drives/{driveId}",
          "path": "drives/{driveId}"
        },
        "hide": {
          "flatPath": "drives/{driveId}/hide",
          "id": "drive.drives.hide",
          "path": "drives/{driveId}/hide",
          "description": "Hides a shared drive from the default view.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "POST"
        },
        "unhide": {
          "description": "Restores a shared drive to the default view.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives/{driveId}/unhide",
          "id": "drive.drives.unhide",
          "path": "drives/{driveId}/unhide"
        }
      }
    },
    "changes": {
      "methods": {
        "getStartPageToken": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets the starting pageToken for listing future changes.",
          "path": "changes/startPageToken",
          "id": "drive.changes.getStartPageToken",
          "flatPath": "changes/startPageToken"
        },
        "list": {
          "path": "changes",
          "supportsSubscription": true,
          "id": "drive.changes.list",
          "flatPath": "changes",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "description": "Lists the changes for a user or shared drive."
        },
        "watch": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Subscribe to changes for a user.",
          "supportsSubscription": true,
          "path": "changes/watch",
          "id": "drive.changes.watch",
          "flatPath": "changes/watch"
        },
        "get": {
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.get",
          "flatPath": "changes/{changeId}",
          "path": "changes/{changeId}"
        }
      }
    },
    "files": {
      "methods": {
        "delete": {
          "flatPath": "files/{fileId}",
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive, the user must be an `organizer` on the parent folder. If the target is a folder, all descendants owned by the user are also deleted.",
          "id": "drive.files.delete",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "DELETE"
        },
        "generateIds": {
          "flatPath": "files/generateIds",
          "id": "drive.files.generateIds",
          "path": "files/generateIds",
          "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "id": "drive.files.list",
          "flatPath": "files",
          "path": "files",
          "description": " Lists the user's files. For more information, see [Search for files and folders](https://developers.google.com/workspace/drive/api/guides/search-files). This method accepts the `q` parameter, which is a search query combining one or more search terms. This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "watch": {
          "id": "drive.files.watch",
          "flatPath": "files/{fileId}/watch",
          "path": "files/{fileId}/watch",
          "supportsSubscription": true,
          "description": "Subscribes to changes to a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "POST"
        },
        "modifyLabels": {
          "flatPath": "files/{fileId}/modifyLabels",
          "id": "drive.files.modifyLabels",
          "path": "files/{fileId}/modifyLabels",
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "httpMethod": "POST"
        },
        "export": {
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "httpMethod": "GET",
          "supportsMediaDownload": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/export",
          "id": "drive.files.export",
          "useMediaDownloadService": true,
          "path": "files/{fileId}/export"
        },
        "emptyTrash": {
          "flatPath": "files/trash",
          "description": "Permanently deletes all of the user's trashed files.",
          "id": "drive.files.emptyTrash",
          "httpMethod": "DELETE",
          "path": "files/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "untrash": {
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/untrash",
          "id": "drive.files.untrash",
          "path": "files/{fileId}/untrash"
        },
        "trash": {
          "flatPath": "files/{fileId}/trash",
          "id": "drive.files.trash",
          "path": "files/{fileId}/trash",
          "description": "Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](https://developers.google.com/workspace/drive/api/guides/manage-u[...]",
          "path": "files",
          "supportsMediaUpload": true,
          "flatPath": "files",
          "id": "drive.files.insert"
        },
        "copy": {
          "path": "files/{fileId}/copy",
          "id": "drive.files.copy",
          "flatPath": "files/{fileId}/copy",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "httpMethod": "POST",
          "description": "Creates a copy of the specified file."
        },
        "patch": {
          "id": "drive.files.patch",
          "flatPath": "files/{fileId}",
          "path": "files/{fileId}",
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "httpMethod": "PATCH"
        },
        "listLabels": {
          "path": "files/{fileId}/listLabels",
          "flatPath": "files/{fileId}/listLabels",
          "id": "drive.files.listLabels",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists the labels on a file."
        },
        "generateCseToken": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Generates a CSE token which can be used to create or update CSE files.",
          "path": "files/generateCseToken",
          "id": "drive.files.generateCseToken",
          "flatPath": "files/generateCseToken"
        },
        "touch": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Set the file's updated time to the current server time.",
          "path": "files/{fileId}/touch",
          "flatPath": "files/{fileId}/touch",
          "id": "drive.files.touch"
        },
        "update": {
          "path": "files/{fileId}",
          "supportsMediaUpload": true,
          "id": "drive.files.update",
          "flatPath": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "httpMethod": "PUT",
          "description": " Updates a file's metadata, content, or both. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:* `*/*` (Specify a valid MIME type, rather than the[...]"
        },
        "get": {
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](https://developers.google.com/workspace/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](https://developers.google.com/w[...]",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true,
          "id": "drive.files.get",
          "flatPath": "files/{fileId}",
          "supportsSubscription": true,
          "useMediaDownloadService": true,
          "path": "files/{fileId}"
        }
      }
    },
    "apps": {
      "methods": {
        "get": {
          "description": "Gets a specific app.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.apps.get",
          "flatPath": "apps/{appId}",
          "path": "apps/{appId}"
        },
        "list": {
          "description": "Lists a user's installed apps.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ],
          "flatPath": "apps",
          "id": "drive.apps.list",
          "path": "apps"
        }
      }
    },
    "revisions": {
      "methods": {
        "patch": {
          "description": "Updates a revision.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.revisions.patch",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "path": "files/{fileId}/revisions/{revisionId}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "description": "Gets a specific revision.",
          "path": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.get",
          "flatPath": "files/{fileId}/revisions/{revisionId}"
        },
        "update": {
          "path": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.update",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "PUT",
          "description": "Updates a revision."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "description": "Lists a file's revisions. **Important:** The list of revisions returned by this method might be incomplete for files with a large revision history, including frequently edited Google Docs, Sheets, and Slides. Older revisions might be omitted from the response, meaning the first revision returned may not be the oldest existing revision. The revision history visible in the Workspace editor user interface might be more complete than the list returned by the API.",
          "path": "files/{fileId}/revisions",
          "id": "drive.revisions.list",
          "flatPath": "files/{fileId}/revisions"
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.delete",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted."
        }
      }
    },
    "children": {
      "methods": {
        "insert": {
          "path": "files/{folderId}/children",
          "id": "drive.children.insert",
          "flatPath": "files/{folderId}/children",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "description": "Inserts a file into a folder."
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a folder's children.",
          "path": "files/{folderId}/children",
          "flatPath": "files/{folderId}/children",
          "id": "drive.children.list"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{folderId}/children/{childId}",
          "httpMethod": "DELETE",
          "id": "drive.children.delete",
          "flatPath": "files/{folderId}/children/{childId}",
          "description": "Removes a child from a folder."
        },
        "get": {
          "path": "files/{folderId}/children/{childId}",
          "id": "drive.children.get",
          "flatPath": "files/{folderId}/children/{childId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "description": "Gets a specific child reference."
        }
      }
    },
    "parents": {
      "methods": {
        "insert": {
          "flatPath": "files/{fileId}/parents",
          "id": "drive.parents.insert",
          "path": "files/{fileId}/parents",
          "description": "Adds a parent folder for a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "description": "Lists a file's parents.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.parents.list",
          "flatPath": "files/{fileId}/parents",
          "path": "files/{fileId}/parents"
        },
        "delete": {
          "flatPath": "files/{fileId}/parents/{parentId}",
          "description": "Removes a parent from a file.",
          "id": "drive.parents.delete",
          "httpMethod": "DELETE",
          "path": "files/{fileId}/parents/{parentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "flatPath": "files/{fileId}/parents/{parentId}",
          "id": "drive.parents.get",
          "path": "files/{fileId}/parents/{parentId}",
          "description": "Gets a specific parent reference.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "properties": {
      "methods": {
        "delete": {
          "id": "drive.properties.delete",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "description": "Deletes a property.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "path": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "DELETE"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "httpMethod": "PUT",
          "description": "Updates a property.",
          "path": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.update",
          "flatPath": "files/{fileId}/properties/{propertyKey}"
        },
        "insert": {
          "flatPath": "files/{fileId}/properties",
          "id": "drive.properties.insert",
          "path": "files/{fileId}/properties",
          "description": "Adds a property to a file, or updates it if it already exists.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "list": {
          "description": "Lists a file's properties.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/properties",
          "id": "drive.properties.list",
          "path": "files/{fileId}/properties"
        },
        "patch": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.patch",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Updates a property."
        },
        "get": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.get",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "description": "Gets a property by its key."
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "POST",
          "description": "Stops watching resources through this channel.",
          "path": "channels/stop",
          "flatPath": "channels/stop",
          "id": "drive.channels.stop"
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "flatPath": "about",
          "id": "drive.about.get",
          "path": "about",
          "description": "Gets the information about the current user along with Drive API settings",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "comments": {
      "methods": {
        "insert": {
          "path": "files/{fileId}/comments",
          "id": "drive.comments.insert",
          "flatPath": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "description": "Creates a new comment on the given file."
        },
        "list": {
          "path": "files/{fileId}/comments",
          "flatPath": "files/{fileId}/comments",
          "id": "drive.comments.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "description": "Lists a file's comments."
        },
        "update": {
          "description": "Updates an existing comment.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.comments.update",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}"
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a comment by ID.",
          "path": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.get",
          "flatPath": "files/{fileId}/comments/{commentId}"
        },
        "patch": {
          "path": "files/{fileId}/comments/{commentId}",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates an existing comment."
        },
        "delete": {
          "flatPath": "files/{fileId}/comments/{commentId}",
          "description": "Deletes a comment.",
          "id": "drive.comments.delete",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "DELETE"
        }
      }
    },
    "teamdrives": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "description": "Deprecated: Use `drives.get` instead.",
          "path": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.get",
          "flatPath": "teamdrives/{teamDriveId}"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "PUT",
          "description": "Deprecated: Use `drives.update` instead.",
          "path": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.update",
          "flatPath": "teamdrives/{teamDriveId}"
        },
        "insert": {
          "flatPath": "teamdrives",
          "id": "drive.teamdrives.insert",
          "path": "teamdrives",
          "description": "Deprecated: Use `drives.insert` instead.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Deprecated: Use `drives.list` instead.",
          "path": "teamdrives",
          "flatPath": "teamdrives",
          "id": "drive.teamdrives.list"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "teamdrives/{teamDriveId}",
          "httpMethod": "DELETE",
          "id": "drive.teamdrives.delete",
          "flatPath": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.delete` instead."
        }
      }
    },
    "permissions": {
      "methods": {
        "delete": {
          "id": "drive.permissions.delete",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/permissions/{permissionId}"
        },
        "getIdForEmail": {
          "description": "Returns the permission ID for an email address.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "permissionIds/{email}",
          "id": "drive.permissions.getIdForEmail",
          "path": "permissionIds/{email}"
        },
        "patch": {
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.patch",
          "path": "files/{fileId}/permissions/{permissionId}",
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a permission by ID.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.get"
        },
        "update": {
          "id": "drive.permissions.update",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "path": "files/{fileId}/permissions/{permissionId}",
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "insert": {
          "path": "files/{fileId}/permissions",
          "id": "drive.permissions.insert",
          "flatPath": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
        },
        "list": {
          "description": "Lists a file's or shared drive's permissions.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/permissions",
          "id": "drive.permissions.list",
          "path": "files/{fileId}/permissions"
        }
      }
    },
    "replies": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "description": "Gets a reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.get",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates an existing reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.patch",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "insert": {
          "id": "drive.replies.insert",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "description": "Creates a new reply to the given comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "description": "Lists all of the replies to a comment.",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "id": "drive.replies.list",
          "flatPath": "files/{fileId}/comments/{commentId}/replies"
        },
        "update": {
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.update",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "PUT",
          "description": "Updates an existing reply."
        },
        "delete": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Deletes a reply.",
          "id": "drive.replies.delete",
          "httpMethod": "DELETE",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    }
  },
  "servicePath": "drive/v2/",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.meet.readonly": {
          "description": "See and download your Google Drive files that were created or edited by Google Meet."
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        }
      }
    }
  },
  "name": "drive",
  "baseUrl": "https://www.googleapis.com/drive/v2/"
}