{
  "rootUrl": "https://www.googleapis.com/",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.meet.readonly": {
          "description": "See and download your Google Drive files that were created or edited by Google Meet."
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        }
      }
    }
  },
  "servicePath": "drive/v2/",
  "name": "drive",
  "documentationLink": "https://developers.google.com/workspace/drive/",
  "id": "drive:v2",
  "ownerName": "Google",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "baseUrl": "https://www.googleapis.com/drive/v2/",
  "kind": "discovery#restDescription",
  "batchPath": "batch/drive/v2",
  "basePath": "/drive/v2/",
  "revision": "20260407",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "title": "Google Drive API",
  "resources": {
    "channels": {
      "methods": {
        "stop": {
          "httpMethod": "POST",
          "id": "drive.channels.stop",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "channels/stop",
          "path": "channels/stop",
          "description": "Stops watching resources through this channel."
        }
      }
    },
    "comments": {
      "methods": {
        "patch": {
          "path": "files/{fileId}/comments/{commentId}",
          "description": "Updates an existing comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.patch",
          "httpMethod": "PATCH"
        },
        "list": {
          "path": "files/{fileId}/comments",
          "description": "Lists a file's comments.",
          "id": "drive.comments.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments"
        },
        "update": {
          "description": "Updates an existing comment.",
          "path": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.update",
          "httpMethod": "PUT",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "delete": {
          "id": "drive.comments.delete",
          "httpMethod": "DELETE",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Deletes a comment.",
          "flatPath": "files/{fileId}/comments/{commentId}"
        },
        "insert": {
          "description": "Creates a new comment on the given file.",
          "path": "files/{fileId}/comments",
          "flatPath": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "id": "drive.comments.insert"
        },
        "get": {
          "path": "files/{fileId}/comments/{commentId}",
          "description": "Gets a comment by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}",
          "httpMethod": "GET",
          "id": "drive.comments.get"
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "description": "Gets the information about the current user along with Drive API settings",
          "path": "about",
          "id": "drive.about.get",
          "httpMethod": "GET",
          "flatPath": "about",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "permissions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "drive.permissions.list",
          "flatPath": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's or shared drive's permissions.",
          "path": "files/{fileId}/permissions"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.update",
          "httpMethod": "PUT",
          "path": "files/{fileId}/permissions/{permissionId}",
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
        },
        "patch": {
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "PATCH",
          "id": "drive.permissions.patch",
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions/{permissionId}"
        },
        "get": {
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.permissions.get",
          "description": "Gets a permission by ID.",
          "path": "files/{fileId}/permissions/{permissionId}"
        },
        "getIdForEmail": {
          "description": "Returns the permission ID for an email address.",
          "path": "permissionIds/{email}",
          "flatPath": "permissionIds/{email}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.permissions.getIdForEmail"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "drive.permissions.delete",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "insert": {
          "path": "files/{fileId}/permissions",
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "id": "drive.permissions.insert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/permissions"
        }
      }
    },
    "files": {
      "methods": {
        "generateCseToken": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "files/generateCseToken",
          "httpMethod": "GET",
          "id": "drive.files.generateCseToken",
          "path": "files/generateCseToken",
          "description": "Generates a CSE token which can be used to create or update CSE files."
        },
        "copy": {
          "id": "drive.files.copy",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/copy",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "description": "Creates a copy of the specified file.",
          "path": "files/{fileId}/copy"
        },
        "delete": {
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive, the user must be an `organizer` on the parent folder. If the target is a folder, all descendants owned by the user are also deleted.",
          "flatPath": "files/{fileId}",
          "id": "drive.files.delete",
          "httpMethod": "DELETE"
        },
        "trash": {
          "description": "Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "path": "files/{fileId}/trash",
          "flatPath": "files/{fileId}/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "id": "drive.files.trash"
        },
        "update": {
          "httpMethod": "PUT",
          "id": "drive.files.update",
          "supportsMediaUpload": true,
          "flatPath": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "description": " Updates a file's metadata, content, or both. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:* `*/*` (Specify a valid MIME type, rather than the[...]",
          "path": "files/{fileId}"
        },
        "generateIds": {
          "id": "drive.files.generateIds",
          "httpMethod": "GET",
          "flatPath": "files/generateIds",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
          "path": "files/generateIds"
        },
        "patch": {
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
          "path": "files/{fileId}",
          "flatPath": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "id": "drive.files.patch",
          "httpMethod": "PATCH"
        },
        "listLabels": {
          "path": "files/{fileId}/listLabels",
          "description": "Lists the labels on a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/listLabels",
          "id": "drive.files.listLabels",
          "httpMethod": "GET"
        },
        "emptyTrash": {
          "id": "drive.files.emptyTrash",
          "httpMethod": "DELETE",
          "path": "files/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Permanently deletes all of the user's trashed files.",
          "flatPath": "files/trash"
        },
        "list": {
          "description": " Lists the user's files. For more information, see [Search for files and folders](https://developers.google.com/workspace/drive/api/guides/search-files). This method accepts the `q` parameter, which is a search query combining one or more search terms. This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.",
          "path": "files",
          "flatPath": "files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.files.list"
        },
        "export": {
          "flatPath": "files/{fileId}/export",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.files.export",
          "supportsMediaDownload": true,
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "path": "files/{fileId}/export",
          "useMediaDownloadService": true
        },
        "touch": {
          "path": "files/{fileId}/touch",
          "description": "Set the file's updated time to the current server time.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/touch",
          "id": "drive.files.touch",
          "httpMethod": "POST"
        },
        "untrash": {
          "flatPath": "files/{fileId}/untrash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "id": "drive.files.untrash",
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "path": "files/{fileId}/untrash"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}",
          "supportsSubscription": true,
          "httpMethod": "GET",
          "id": "drive.files.get",
          "path": "files/{fileId}",
          "useMediaDownloadService": true,
          "supportsMediaDownload": true,
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](https://developers.google.com/workspace/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](https://developers.google.com/w[...]"
        },
        "insert": {
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](https://developers.google.com/workspace/drive/api/guides/manage-u[...]",
          "path": "files",
          "id": "drive.files.insert",
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "flatPath": "files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "watch": {
          "description": "Subscribes to changes to a file.",
          "path": "files/{fileId}/watch",
          "flatPath": "files/{fileId}/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "POST",
          "id": "drive.files.watch",
          "supportsSubscription": true
        },
        "modifyLabels": {
          "path": "files/{fileId}/modifyLabels",
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/modifyLabels",
          "id": "drive.files.modifyLabels",
          "httpMethod": "POST"
        }
      }
    },
    "parents": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "id": "drive.parents.list",
          "flatPath": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's parents.",
          "path": "files/{fileId}/parents"
        },
        "get": {
          "flatPath": "files/{fileId}/parents/{parentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.parents.get",
          "description": "Gets a specific parent reference.",
          "path": "files/{fileId}/parents/{parentId}"
        },
        "delete": {
          "description": "Removes a parent from a file.",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "path": "files/{fileId}/parents/{parentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.parents.delete",
          "httpMethod": "DELETE"
        },
        "insert": {
          "description": "Adds a parent folder for a file.",
          "path": "files/{fileId}/parents",
          "flatPath": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "id": "drive.parents.insert"
        }
      }
    },
    "properties": {
      "methods": {
        "patch": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "description": "Updates a property.",
          "id": "drive.properties.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/properties/{propertyKey}"
        },
        "list": {
          "description": "Lists a file's properties.",
          "path": "files/{fileId}/properties",
          "flatPath": "files/{fileId}/properties",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.properties.list",
          "httpMethod": "GET"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "PUT",
          "id": "drive.properties.update",
          "path": "files/{fileId}/properties/{propertyKey}",
          "description": "Updates a property."
        },
        "delete": {
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "description": "Deletes a property.",
          "path": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "httpMethod": "DELETE",
          "id": "drive.properties.delete"
        },
        "insert": {
          "description": "Adds a property to a file, or updates it if it already exists.",
          "path": "files/{fileId}/properties",
          "id": "drive.properties.insert",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/properties",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "get": {
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.properties.get",
          "httpMethod": "GET",
          "description": "Gets a property by its key.",
          "path": "files/{fileId}/properties/{propertyKey}"
        }
      }
    },
    "changes": {
      "methods": {
        "watch": {
          "supportsSubscription": true,
          "id": "drive.changes.watch",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes/watch",
          "path": "changes/watch",
          "description": "Subscribe to changes for a user."
        },
        "get": {
          "path": "changes/{changeId}",
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes/{changeId}",
          "id": "drive.changes.get",
          "httpMethod": "GET"
        },
        "getStartPageToken": {
          "id": "drive.changes.getStartPageToken",
          "httpMethod": "GET",
          "flatPath": "changes/startPageToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets the starting pageToken for listing future changes.",
          "path": "changes/startPageToken"
        },
        "list": {
          "path": "changes",
          "description": "Lists the changes for a user or shared drive.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes",
          "supportsSubscription": true,
          "id": "drive.changes.list",
          "httpMethod": "GET"
        }
      }
    },
    "children": {
      "methods": {
        "delete": {
          "flatPath": "files/{folderId}/children/{childId}",
          "description": "Removes a child from a folder.",
          "path": "files/{folderId}/children/{childId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "DELETE",
          "id": "drive.children.delete"
        },
        "insert": {
          "path": "files/{folderId}/children",
          "description": "Inserts a file into a folder.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{folderId}/children",
          "httpMethod": "POST",
          "id": "drive.children.insert"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{folderId}/children/{childId}",
          "httpMethod": "GET",
          "id": "drive.children.get",
          "path": "files/{folderId}/children/{childId}",
          "description": "Gets a specific child reference."
        },
        "list": {
          "flatPath": "files/{folderId}/children",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.children.list",
          "httpMethod": "GET",
          "description": "Lists a folder's children.",
          "path": "files/{folderId}/children"
        }
      }
    },
    "drives": {
      "methods": {
        "list": {
          "path": "drives",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](https://developers.google.com/workspace/drive/api/guides/search-shareddrives) guide.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "drives",
          "httpMethod": "GET",
          "id": "drive.drives.list"
        },
        "update": {
          "flatPath": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.update",
          "httpMethod": "PUT",
          "description": "Updates the metadata for a shared drive.",
          "path": "drives/{driveId}"
        },
        "get": {
          "httpMethod": "GET",
          "id": "drive.drives.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "drives/{driveId}",
          "path": "drives/{driveId}",
          "description": "Gets a shared drive's metadata by ID."
        },
        "hide": {
          "id": "drive.drives.hide",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives/{driveId}/hide",
          "path": "drives/{driveId}/hide",
          "description": "Hides a shared drive from the default view."
        },
        "delete": {
          "path": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Permanently deletes a shared drive for which the user is an `organizer`. The shared drive cannot contain any untrashed items.",
          "flatPath": "drives/{driveId}",
          "id": "drive.drives.delete",
          "httpMethod": "DELETE"
        },
        "insert": {
          "path": "drives",
          "description": "Creates a new shared drive.",
          "httpMethod": "POST",
          "id": "drive.drives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives"
        },
        "unhide": {
          "description": "Restores a shared drive to the default view.",
          "path": "drives/{driveId}/unhide",
          "httpMethod": "POST",
          "id": "drive.drives.unhide",
          "flatPath": "drives/{driveId}/unhide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        }
      }
    },
    "replies": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "id": "drive.replies.list",
          "httpMethod": "GET",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "description": "Lists all of the replies to a comment."
        },
        "update": {
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Updates an existing reply.",
          "httpMethod": "PUT",
          "id": "drive.replies.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "patch": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "PATCH",
          "id": "drive.replies.patch",
          "description": "Updates an existing reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "get": {
          "description": "Gets a reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "GET",
          "id": "drive.replies.get",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "drive.replies.delete",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Deletes a reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "insert": {
          "description": "Creates a new reply to the given comment.",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "httpMethod": "POST",
          "id": "drive.replies.insert",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "revisions": {
      "methods": {
        "get": {
          "description": "Gets a specific revision.",
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.revisions.get"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "drive.revisions.delete",
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted."
        },
        "list": {
          "flatPath": "files/{fileId}/revisions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "id": "drive.revisions.list",
          "description": "Lists a file's revisions. **Important:** The list of revisions returned by this method might be incomplete for files with a large revision history, including frequently edited Google Docs, Sheets, and Slides. Older revisions might be omitted from the response, meaning the first revision returned may not be the oldest existing revision. The revision history visible in the Workspace editor user interface might be more complete than the list returned by the API.",
          "path": "files/{fileId}/revisions"
        },
        "update": {
          "description": "Updates a revision.",
          "path": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.update",
          "httpMethod": "PUT",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "patch": {
          "id": "drive.revisions.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "path": "files/{fileId}/revisions/{revisionId}",
          "description": "Updates a revision."
        }
      }
    },
    "teamdrives": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "teamdrives",
          "id": "drive.teamdrives.list",
          "httpMethod": "GET",
          "path": "teamdrives",
          "description": "Deprecated: Use `drives.list` instead."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "teamdrives/{teamDriveId}",
          "httpMethod": "PUT",
          "id": "drive.teamdrives.update",
          "path": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.update` instead."
        },
        "get": {
          "path": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.get` instead.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.get",
          "httpMethod": "GET"
        },
        "delete": {
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.delete` instead.",
          "httpMethod": "DELETE",
          "id": "drive.teamdrives.delete"
        },
        "insert": {
          "description": "Deprecated: Use `drives.insert` instead.",
          "path": "teamdrives",
          "id": "drive.teamdrives.insert",
          "httpMethod": "POST",
          "flatPath": "teamdrives",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        }
      }
    },
    "apps": {
      "methods": {
        "list": {
          "path": "apps",
          "description": "Lists a user's installed apps.",
          "id": "drive.apps.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ],
          "flatPath": "apps"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "apps/{appId}",
          "httpMethod": "GET",
          "id": "drive.apps.get",
          "path": "apps/{appId}",
          "description": "Gets a specific app."
        }
      }
    }
  },
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "version": "v2"
}