{
  "batchPath": "batch/drive/v2",
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "id": "drive:v2",
  "ownerName": "Google",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "resources": {
    "teamdrives": {
      "methods": {
        "get": {
          "path": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.get` instead.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.get",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Deprecated: Use `drives.list` instead.",
          "path": "teamdrives",
          "id": "drive.teamdrives.list",
          "httpMethod": "GET",
          "flatPath": "teamdrives"
        },
        "delete": {
          "flatPath": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.delete` instead.",
          "id": "drive.teamdrives.delete",
          "path": "teamdrives/{teamDriveId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Deprecated: Use `drives.update` instead.",
          "path": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.update",
          "httpMethod": "PUT",
          "flatPath": "teamdrives/{teamDriveId}"
        },
        "insert": {
          "flatPath": "teamdrives",
          "id": "drive.teamdrives.insert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "teamdrives",
          "description": "Deprecated: Use `drives.insert` instead."
        }
      }
    },
    "children": {
      "methods": {
        "list": {
          "id": "drive.children.list",
          "httpMethod": "GET",
          "flatPath": "files/{folderId}/children",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a folder's children.",
          "path": "files/{folderId}/children"
        },
        "delete": {
          "flatPath": "files/{folderId}/children/{childId}",
          "description": "Removes a child from a folder.",
          "id": "drive.children.delete",
          "path": "files/{folderId}/children/{childId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "path": "files/{folderId}/children/{childId}",
          "description": "Gets a specific child reference.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.children.get",
          "httpMethod": "GET",
          "flatPath": "files/{folderId}/children/{childId}"
        },
        "insert": {
          "id": "drive.children.insert",
          "httpMethod": "POST",
          "flatPath": "files/{folderId}/children",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{folderId}/children",
          "description": "Inserts a file into a folder."
        }
      }
    },
    "parents": {
      "methods": {
        "list": {
          "id": "drive.parents.list",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's parents.",
          "path": "files/{fileId}/parents"
        },
        "get": {
          "path": "files/{fileId}/parents/{parentId}",
          "description": "Gets a specific parent reference.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/parents/{parentId}",
          "id": "drive.parents.get",
          "httpMethod": "GET"
        },
        "insert": {
          "path": "files/{fileId}/parents",
          "description": "Adds a parent folder for a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/parents",
          "id": "drive.parents.insert",
          "httpMethod": "POST"
        },
        "delete": {
          "id": "drive.parents.delete",
          "path": "files/{fileId}/parents/{parentId}",
          "httpMethod": "DELETE",
          "description": "Removes a parent from a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/parents/{parentId}"
        }
      }
    },
    "comments": {
      "methods": {
        "get": {
          "path": "files/{fileId}/comments/{commentId}",
          "description": "Gets a comment by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.get",
          "httpMethod": "GET"
        },
        "insert": {
          "description": "Creates a new comment on the given file.",
          "path": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments",
          "id": "drive.comments.insert",
          "httpMethod": "POST"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Deletes a comment.",
          "id": "drive.comments.delete",
          "path": "files/{fileId}/comments/{commentId}",
          "httpMethod": "DELETE",
          "flatPath": "files/{fileId}/comments/{commentId}"
        },
        "update": {
          "id": "drive.comments.update",
          "httpMethod": "PUT",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}",
          "description": "Updates an existing comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/comments",
          "description": "Lists a file's comments.",
          "id": "drive.comments.list",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/comments"
        },
        "patch": {
          "flatPath": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates an existing comment.",
          "path": "files/{fileId}/comments/{commentId}"
        }
      }
    },
    "files": {
      "methods": {
        "get": {
          "flatPath": "files/{fileId}",
          "supportsSubscription": true,
          "supportsMediaDownload": true,
          "id": "drive.files.get",
          "httpMethod": "GET",
          "useMediaDownloadService": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](https://developers.google.com/workspace/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](https://developers.google.com/w[...]",
          "path": "files/{fileId}"
        },
        "delete": {
          "id": "drive.files.delete",
          "path": "files/{fileId}",
          "httpMethod": "DELETE",
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive, the user must be an `organizer` on the parent folder. If the target is a folder, all descendants owned by the user are also deleted.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}"
        },
        "trash": {
          "id": "drive.files.trash",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/trash",
          "description": "Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "description": " Updates a file's metadata, content, or both. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:* `*/*` (Specify a valid MIME type, rather than the[...]",
          "path": "files/{fileId}",
          "supportsMediaUpload": true,
          "id": "drive.files.update",
          "httpMethod": "PUT",
          "flatPath": "files/{fileId}"
        },
        "modifyLabels": {
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "path": "files/{fileId}/modifyLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/modifyLabels",
          "id": "drive.files.modifyLabels",
          "httpMethod": "POST"
        },
        "export": {
          "useMediaDownloadService": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/export",
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "supportsMediaDownload": true,
          "id": "drive.files.export",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/export"
        },
        "emptyTrash": {
          "flatPath": "files/trash",
          "description": "Permanently deletes all of the user's trashed files.",
          "id": "drive.files.emptyTrash",
          "path": "files/trash",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "listLabels": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists the labels on a file.",
          "path": "files/{fileId}/listLabels",
          "id": "drive.files.listLabels",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/listLabels"
        },
        "touch": {
          "id": "drive.files.touch",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/touch",
          "description": "Set the file's updated time to the current server time.",
          "path": "files/{fileId}/touch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "path": "files/{fileId}",
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
          "flatPath": "files/{fileId}",
          "id": "drive.files.patch",
          "httpMethod": "PATCH"
        },
        "untrash": {
          "path": "files/{fileId}/untrash",
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.untrash",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/untrash"
        },
        "generateIds": {
          "id": "drive.files.generateIds",
          "httpMethod": "GET",
          "flatPath": "files/generateIds",
          "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
          "path": "files/generateIds",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "copy": {
          "path": "files/{fileId}/copy",
          "description": "Creates a copy of the specified file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "id": "drive.files.copy",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/copy"
        },
        "list": {
          "flatPath": "files",
          "id": "drive.files.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files",
          "description": " Lists the user's files. For more information, see [Search for files and folders](https://developers.google.com/workspace/drive/api/guides/search-files). This method accepts the `q` parameter, which is a search query combining one or more search terms. This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results."
        },
        "insert": {
          "supportsMediaUpload": true,
          "path": "files",
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](https://developers.google.com/workspace/drive/api/guides/manage-u[...]",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files",
          "id": "drive.files.insert",
          "httpMethod": "POST"
        },
        "watch": {
          "path": "files/{fileId}/watch",
          "description": "Subscribes to changes to a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/watch",
          "supportsSubscription": true,
          "id": "drive.files.watch",
          "httpMethod": "POST"
        }
      }
    },
    "properties": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's properties.",
          "path": "files/{fileId}/properties",
          "id": "drive.properties.list",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/properties"
        },
        "patch": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.patch",
          "httpMethod": "PATCH"
        },
        "delete": {
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Deletes a property.",
          "id": "drive.properties.delete",
          "path": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "DELETE"
        },
        "update": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.update",
          "httpMethod": "PUT"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Adds a property to a file, or updates it if it already exists.",
          "path": "files/{fileId}/properties",
          "id": "drive.properties.insert",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/properties"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a property by its key.",
          "path": "files/{fileId}/properties/{propertyKey}",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.get",
          "httpMethod": "GET"
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "about",
          "description": "Gets the information about the current user along with Drive API settings",
          "flatPath": "about",
          "id": "drive.about.get",
          "httpMethod": "GET"
        }
      }
    },
    "revisions": {
      "methods": {
        "delete": {
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
          "id": "drive.revisions.delete",
          "path": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "DELETE"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates a revision.",
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.update",
          "httpMethod": "PUT"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/revisions",
          "description": "Lists a file's revisions. **Important:** The list of revisions returned by this method might be incomplete for files with a large revision history, including frequently edited Google Docs, Sheets, and Slides. Older revisions might be omitted from the response, meaning the first revision returned may not be the oldest existing revision. The revision history visible in the Workspace editor user interface might be more complete than the list returned by the API.",
          "id": "drive.revisions.list",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/revisions"
        },
        "patch": {
          "path": "files/{fileId}/revisions/{revisionId}",
          "description": "Updates a revision.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.revisions.patch",
          "httpMethod": "PATCH",
          "flatPath": "files/{fileId}/revisions/{revisionId}"
        },
        "get": {
          "id": "drive.revisions.get",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "path": "files/{fileId}/revisions/{revisionId}",
          "description": "Gets a specific revision.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "changes": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "path": "changes/{changeId}",
          "flatPath": "changes/{changeId}",
          "id": "drive.changes.get",
          "httpMethod": "GET"
        },
        "watch": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Subscribe to changes for a user.",
          "path": "changes/watch",
          "id": "drive.changes.watch",
          "httpMethod": "POST",
          "flatPath": "changes/watch",
          "supportsSubscription": true
        },
        "getStartPageToken": {
          "path": "changes/startPageToken",
          "description": "Gets the starting pageToken for listing future changes.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes/startPageToken",
          "id": "drive.changes.getStartPageToken",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Lists the changes for a user or shared drive.",
          "path": "changes",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.list",
          "httpMethod": "GET",
          "flatPath": "changes",
          "supportsSubscription": true
        }
      }
    },
    "drives": {
      "methods": {
        "get": {
          "path": "drives/{driveId}",
          "description": "Gets a shared drive's metadata by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "drives/{driveId}",
          "id": "drive.drives.get",
          "httpMethod": "GET"
        },
        "hide": {
          "path": "drives/{driveId}/hide",
          "description": "Hides a shared drive from the default view.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.hide",
          "httpMethod": "POST",
          "flatPath": "drives/{driveId}/hide"
        },
        "insert": {
          "path": "drives",
          "description": "Creates a new shared drive.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.insert",
          "httpMethod": "POST",
          "flatPath": "drives"
        },
        "delete": {
          "description": "Permanently deletes a shared drive for which the user is an `organizer`. The shared drive cannot contain any untrashed items.",
          "id": "drive.drives.delete",
          "path": "drives/{driveId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives/{driveId}"
        },
        "update": {
          "flatPath": "drives/{driveId}",
          "id": "drive.drives.update",
          "httpMethod": "PUT",
          "path": "drives/{driveId}",
          "description": "Updates the metadata for a shared drive.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "drives",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](https://developers.google.com/workspace/drive/api/guides/search-shareddrives) guide.",
          "flatPath": "drives",
          "id": "drive.drives.list",
          "httpMethod": "GET"
        },
        "unhide": {
          "id": "drive.drives.unhide",
          "httpMethod": "POST",
          "flatPath": "drives/{driveId}/unhide",
          "description": "Restores a shared drive to the default view.",
          "path": "drives/{driveId}/unhide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "channels/stop",
          "description": "Stops watching resources through this channel.",
          "id": "drive.channels.stop",
          "httpMethod": "POST",
          "flatPath": "channels/stop"
        }
      }
    },
    "apps": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ],
          "description": "Lists a user's installed apps.",
          "path": "apps",
          "flatPath": "apps",
          "id": "drive.apps.list",
          "httpMethod": "GET"
        },
        "get": {
          "path": "apps/{appId}",
          "description": "Gets a specific app.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.apps.get",
          "httpMethod": "GET",
          "flatPath": "apps/{appId}"
        }
      }
    },
    "permissions": {
      "methods": {
        "get": {
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.get",
          "httpMethod": "GET",
          "description": "Gets a permission by ID.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "getIdForEmail": {
          "id": "drive.permissions.getIdForEmail",
          "httpMethod": "GET",
          "flatPath": "permissionIds/{email}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Returns the permission ID for an email address.",
          "path": "permissionIds/{email}"
        },
        "delete": {
          "id": "drive.permissions.delete",
          "path": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "DELETE",
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/permissions/{permissionId}"
        },
        "update": {
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.update",
          "httpMethod": "PUT"
        },
        "insert": {
          "flatPath": "files/{fileId}/permissions",
          "id": "drive.permissions.insert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/permissions",
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's or shared drive's permissions.",
          "path": "files/{fileId}/permissions",
          "flatPath": "files/{fileId}/permissions",
          "id": "drive.permissions.list",
          "httpMethod": "GET"
        },
        "patch": {
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.patch",
          "httpMethod": "PATCH",
          "flatPath": "files/{fileId}/permissions/{permissionId}"
        }
      }
    },
    "replies": {
      "methods": {
        "get": {
          "id": "drive.replies.get",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "list": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "id": "drive.replies.list",
          "httpMethod": "GET",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "description": "Lists all of the replies to a comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "patch": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates an existing reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "insert": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "id": "drive.replies.insert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}/replies",
          "description": "Creates a new reply to the given comment."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Deletes a reply.",
          "id": "drive.replies.delete",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "DELETE",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "update": {
          "description": "Updates an existing reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.update",
          "httpMethod": "PUT"
        }
      }
    }
  },
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "name": "drive",
  "rootUrl": "https://www.googleapis.com/",
  "title": "Google Drive API",
  "basePath": "/drive/v2/",
  "baseUrl": "https://www.googleapis.com/drive/v2/",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.meet.readonly": {
          "description": "See and download your Google Drive files that were created or edited by Google Meet."
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        }
      }
    }
  },
  "revision": "20260401",
  "documentationLink": "https://developers.google.com/workspace/drive/",
  "servicePath": "drive/v2/",
  "protocol": "rest",
  "version": "v2"
}