{
  "ownerDomain": "google.com",
  "baseUrl": "https://www.googleapis.com/drive/v2/",
  "discoveryVersion": "v1",
  "resources": {
    "about": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets the information about the current user along with Drive API settings",
          "id": "drive.about.get",
          "httpMethod": "GET",
          "path": "about",
          "flatPath": "about"
        }
      }
    },
    "children": {
      "methods": {
        "list": {
          "path": "files/{folderId}/children",
          "flatPath": "files/{folderId}/children",
          "id": "drive.children.list",
          "httpMethod": "GET",
          "description": "Lists a folder's children.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "description": "Removes a child from a folder.",
          "id": "drive.children.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{folderId}/children/{childId}",
          "flatPath": "files/{folderId}/children/{childId}"
        },
        "insert": {
          "path": "files/{folderId}/children",
          "flatPath": "files/{folderId}/children",
          "id": "drive.children.insert",
          "httpMethod": "POST",
          "description": "Inserts a file into a folder.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a specific child reference.",
          "path": "files/{folderId}/children/{childId}",
          "flatPath": "files/{folderId}/children/{childId}",
          "id": "drive.children.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "untrash": {
          "id": "drive.files.untrash",
          "httpMethod": "POST",
          "path": "files/{fileId}/untrash",
          "flatPath": "files/{fileId}/untrash",
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "id": "drive.files.update",
          "httpMethod": "PUT",
          "path": "files/{fileId}",
          "flatPath": "files/{fileId}",
          "supportsMediaUpload": true,
          "description": " Updates a file's metadata, content, or both. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:* `*/*` (Specify a valid MIME type, rather than the[...]"
        },
        "emptyTrash": {
          "description": "Permanently deletes all of the user's trashed files.",
          "id": "drive.files.emptyTrash",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "files/trash",
          "flatPath": "files/trash"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "useMediaDownloadService": true,
          "supportsMediaDownload": true,
          "supportsSubscription": true,
          "id": "drive.files.get",
          "httpMethod": "GET",
          "path": "files/{fileId}",
          "flatPath": "files/{fileId}",
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](https://developers.google.com/workspace/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](https://developers.google.com/w[...]"
        },
        "modifyLabels": {
          "path": "files/{fileId}/modifyLabels",
          "flatPath": "files/{fileId}/modifyLabels",
          "id": "drive.files.modifyLabels",
          "httpMethod": "POST",
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "touch": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Set the file's updated time to the current server time.",
          "path": "files/{fileId}/touch",
          "flatPath": "files/{fileId}/touch",
          "id": "drive.files.touch",
          "httpMethod": "POST"
        },
        "delete": {
          "id": "drive.files.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}",
          "flatPath": "files/{fileId}",
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive, the user must be an `organizer` on the parent folder. If the target is a folder, all descendants owned by the user are also deleted."
        },
        "copy": {
          "path": "files/{fileId}/copy",
          "flatPath": "files/{fileId}/copy",
          "id": "drive.files.copy",
          "httpMethod": "POST",
          "description": "Creates a copy of the specified file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ]
        },
        "insert": {
          "supportsMediaUpload": true,
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](https://developers.google.com/workspace/drive/api/guides/manage-u[...]",
          "path": "files",
          "flatPath": "files",
          "id": "drive.files.insert",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "generateCseToken": {
          "id": "drive.files.generateCseToken",
          "httpMethod": "GET",
          "path": "files/generateCseToken",
          "flatPath": "files/generateCseToken",
          "description": "Generates a CSE token which can be used to create or update CSE files.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "generateIds": {
          "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
          "id": "drive.files.generateIds",
          "httpMethod": "GET",
          "path": "files/generateIds",
          "flatPath": "files/generateIds",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "patch": {
          "id": "drive.files.patch",
          "httpMethod": "PATCH",
          "path": "files/{fileId}",
          "flatPath": "files/{fileId}",
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ]
        },
        "trash": {
          "description": "Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "id": "drive.files.trash",
          "httpMethod": "POST",
          "path": "files/{fileId}/trash",
          "flatPath": "files/{fileId}/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "export": {
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "id": "drive.files.export",
          "httpMethod": "GET",
          "path": "files/{fileId}/export",
          "flatPath": "files/{fileId}/export",
          "supportsMediaDownload": true,
          "useMediaDownloadService": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "watch": {
          "description": "Subscribes to changes to a file.",
          "path": "files/{fileId}/watch",
          "flatPath": "files/{fileId}/watch",
          "id": "drive.files.watch",
          "httpMethod": "POST",
          "supportsSubscription": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "description": " Lists the user's files. For more information, see [Search for files and folders](https://developers.google.com/workspace/drive/api/guides/search-files). This method accepts the `q` parameter, which is a search query combining one or more search terms. This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.",
          "id": "drive.files.list",
          "httpMethod": "GET",
          "path": "files",
          "flatPath": "files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "listLabels": {
          "path": "files/{fileId}/listLabels",
          "flatPath": "files/{fileId}/listLabels",
          "id": "drive.files.listLabels",
          "httpMethod": "GET",
          "description": "Lists the labels on a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "apps": {
      "methods": {
        "get": {
          "path": "apps/{appId}",
          "flatPath": "apps/{appId}",
          "id": "drive.apps.get",
          "httpMethod": "GET",
          "description": "Gets a specific app.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "description": "Lists a user's installed apps.",
          "path": "apps",
          "flatPath": "apps",
          "id": "drive.apps.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ]
        }
      }
    },
    "replies": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a reply.",
          "id": "drive.replies.get",
          "httpMethod": "GET",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "list": {
          "description": "Lists all of the replies to a comment.",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "id": "drive.replies.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates an existing reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.update",
          "httpMethod": "PUT"
        },
        "delete": {
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Deletes a reply."
        },
        "insert": {
          "path": "files/{fileId}/comments/{commentId}/replies",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "id": "drive.replies.insert",
          "httpMethod": "POST",
          "description": "Creates a new reply to the given comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates an existing reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.patch",
          "httpMethod": "PATCH"
        }
      }
    },
    "comments": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a comment by ID.",
          "path": "files/{fileId}/comments/{commentId}",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.get",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Lists a file's comments.",
          "id": "drive.comments.list",
          "httpMethod": "GET",
          "path": "files/{fileId}/comments",
          "flatPath": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.update",
          "httpMethod": "PUT",
          "description": "Updates an existing comment."
        },
        "delete": {
          "description": "Deletes a comment.",
          "path": "files/{fileId}/comments/{commentId}",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.comments.insert",
          "httpMethod": "POST",
          "path": "files/{fileId}/comments",
          "flatPath": "files/{fileId}/comments",
          "description": "Creates a new comment on the given file."
        },
        "patch": {
          "description": "Updates an existing comment.",
          "path": "files/{fileId}/comments/{commentId}",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "teamdrives": {
      "methods": {
        "delete": {
          "description": "Deprecated: Use `drives.delete` instead.",
          "path": "teamdrives/{teamDriveId}",
          "flatPath": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.teamdrives.insert",
          "httpMethod": "POST",
          "path": "teamdrives",
          "flatPath": "teamdrives",
          "description": "Deprecated: Use `drives.insert` instead."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Deprecated: Use `drives.update` instead.",
          "path": "teamdrives/{teamDriveId}",
          "flatPath": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.update",
          "httpMethod": "PUT"
        },
        "list": {
          "description": "Deprecated: Use `drives.list` instead.",
          "path": "teamdrives",
          "flatPath": "teamdrives",
          "id": "drive.teamdrives.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Deprecated: Use `drives.get` instead.",
          "id": "drive.teamdrives.get",
          "httpMethod": "GET",
          "path": "teamdrives/{teamDriveId}",
          "flatPath": "teamdrives/{teamDriveId}"
        }
      }
    },
    "drives": {
      "methods": {
        "unhide": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.unhide",
          "httpMethod": "POST",
          "path": "drives/{driveId}/unhide",
          "flatPath": "drives/{driveId}/unhide",
          "description": "Restores a shared drive to the default view."
        },
        "delete": {
          "description": "Permanently deletes a shared drive for which the user is an `organizer`. The shared drive cannot contain any untrashed items.",
          "id": "drive.drives.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "drives/{driveId}",
          "flatPath": "drives/{driveId}"
        },
        "insert": {
          "description": "Creates a new shared drive.",
          "id": "drive.drives.insert",
          "httpMethod": "POST",
          "path": "drives",
          "flatPath": "drives",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "update": {
          "path": "drives/{driveId}",
          "flatPath": "drives/{driveId}",
          "id": "drive.drives.update",
          "httpMethod": "PUT",
          "description": "Updates the metadata for a shared drive.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "hide": {
          "id": "drive.drives.hide",
          "httpMethod": "POST",
          "path": "drives/{driveId}/hide",
          "flatPath": "drives/{driveId}/hide",
          "description": "Hides a shared drive from the default view.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "id": "drive.drives.list",
          "httpMethod": "GET",
          "path": "drives",
          "flatPath": "drives",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](https://developers.google.com/workspace/drive/api/guides/search-shareddrives) guide.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "get": {
          "id": "drive.drives.get",
          "httpMethod": "GET",
          "path": "drives/{driveId}",
          "flatPath": "drives/{driveId}",
          "description": "Gets a shared drive's metadata by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "properties": {
      "methods": {
        "delete": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Deletes a property."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.properties.insert",
          "httpMethod": "POST",
          "path": "files/{fileId}/properties",
          "flatPath": "files/{fileId}/properties",
          "description": "Adds a property to a file, or updates it if it already exists."
        },
        "patch": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.patch",
          "httpMethod": "PATCH",
          "description": "Updates a property.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "path": "files/{fileId}/properties/{propertyKey}",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.update",
          "httpMethod": "PUT",
          "description": "Updates a property."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's properties.",
          "path": "files/{fileId}/properties",
          "flatPath": "files/{fileId}/properties",
          "id": "drive.properties.list",
          "httpMethod": "GET"
        },
        "get": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.get",
          "httpMethod": "GET",
          "description": "Gets a property by its key.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "revisions": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's revisions. **Important:** The list of revisions returned by this method might be incomplete for files with a large revision history, including frequently edited Google Docs, Sheets, and Slides. Older revisions might be omitted from the response, meaning the first revision returned may not be the oldest existing revision. The revision history visible in the Workspace editor user interface might be more complete than the list returned by the API.",
          "path": "files/{fileId}/revisions",
          "flatPath": "files/{fileId}/revisions",
          "id": "drive.revisions.list",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a specific revision.",
          "id": "drive.revisions.get",
          "httpMethod": "GET",
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}"
        },
        "delete": {
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "patch": {
          "id": "drive.revisions.patch",
          "httpMethod": "PATCH",
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "description": "Updates a revision.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates a revision.",
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.update",
          "httpMethod": "PUT"
        }
      }
    },
    "changes": {
      "methods": {
        "list": {
          "supportsSubscription": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists the changes for a user or shared drive.",
          "id": "drive.changes.list",
          "httpMethod": "GET",
          "path": "changes",
          "flatPath": "changes"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "path": "changes/{changeId}",
          "flatPath": "changes/{changeId}",
          "id": "drive.changes.get",
          "httpMethod": "GET"
        },
        "getStartPageToken": {
          "description": "Gets the starting pageToken for listing future changes.",
          "id": "drive.changes.getStartPageToken",
          "httpMethod": "GET",
          "path": "changes/startPageToken",
          "flatPath": "changes/startPageToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "watch": {
          "path": "changes/watch",
          "flatPath": "changes/watch",
          "id": "drive.changes.watch",
          "httpMethod": "POST",
          "description": "Subscribe to changes for a user.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsSubscription": true
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "id": "drive.channels.stop",
          "httpMethod": "POST",
          "path": "channels/stop",
          "flatPath": "channels/stop",
          "description": "Stops watching resources through this channel.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "parents": {
      "methods": {
        "delete": {
          "description": "Removes a parent from a file.",
          "path": "files/{fileId}/parents/{parentId}",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "id": "drive.parents.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "insert": {
          "path": "files/{fileId}/parents",
          "flatPath": "files/{fileId}/parents",
          "id": "drive.parents.insert",
          "httpMethod": "POST",
          "description": "Adds a parent folder for a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.parents.list",
          "httpMethod": "GET",
          "path": "files/{fileId}/parents",
          "flatPath": "files/{fileId}/parents",
          "description": "Lists a file's parents."
        },
        "get": {
          "path": "files/{fileId}/parents/{parentId}",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "id": "drive.parents.get",
          "httpMethod": "GET",
          "description": "Gets a specific parent reference.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "permissions": {
      "methods": {
        "list": {
          "id": "drive.permissions.list",
          "httpMethod": "GET",
          "path": "files/{fileId}/permissions",
          "flatPath": "files/{fileId}/permissions",
          "description": "Lists a file's or shared drive's permissions.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "get": {
          "description": "Gets a permission by ID.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "id": "drive.permissions.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions",
          "flatPath": "files/{fileId}/permissions",
          "id": "drive.permissions.insert",
          "httpMethod": "POST"
        },
        "patch": {
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "getIdForEmail": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "permissionIds/{email}",
          "flatPath": "permissionIds/{email}",
          "id": "drive.permissions.getIdForEmail",
          "httpMethod": "GET",
          "description": "Returns the permission ID for an email address."
        },
        "update": {
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.update",
          "httpMethod": "PUT",
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/workspace/drive/",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "protocol": "rest",
  "basePath": "/drive/v2/",
  "ownerName": "Google",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "title": "Google Drive API",
  "servicePath": "drive/v2/",
  "rootUrl": "https://www.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.meet.readonly": {
          "description": "See and download your Google Drive files that were created or edited by Google Meet."
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        }
      }
    }
  },
  "revision": "20260407",
  "batchPath": "batch/drive/v2",
  "name": "drive",
  "version": "v2",
  "kind": "discovery#restDescription",
  "id": "drive:v2"
}