{
  "canonicalName": "Drive Labels",
  "discoveryVersion": "v1",
  "resources": {
    "users": {
      "methods": {
        "getCapabilities": {
          "flatPath": "v2beta/users/{usersId}/capabilities",
          "httpMethod": "GET",
          "path": "v2beta/{+name}",
          "id": "drivelabels.users.getCapabilities",
          "scopes": [
            "https://www.googleapis.com/auth/drive.admin.labels",
            "https://www.googleapis.com/auth/drive.admin.labels.readonly",
            "https://www.googleapis.com/auth/drive.labels",
            "https://www.googleapis.com/auth/drive.labels.readonly"
          ],
          "description": "Gets the user capabilities."
        }
      }
    },
    "limits": {
      "methods": {
        "getLabel": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.admin.labels",
            "https://www.googleapis.com/auth/drive.admin.labels.readonly",
            "https://www.googleapis.com/auth/drive.labels",
            "https://www.googleapis.com/auth/drive.labels.readonly"
          ],
          "description": "Get the constraints on the structure of a label; such as, the maximum number of fields allowed and maximum length of the label title.",
          "path": "v2beta/limits/label",
          "id": "drivelabels.limits.getLabel",
          "flatPath": "v2beta/limits/label",
          "httpMethod": "GET"
        }
      }
    },
    "labels": {
      "methods": {
        "enable": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.admin.labels",
            "https://www.googleapis.com/auth/drive.labels"
          ],
          "description": "Enable a disabled label and restore it to its published state. For more information, see [Disable, enable, and delete a label](https://developers.google.com/workspace/drive/labels/guides/disable-delete-label). This will result in a new published revision based on the current disabled published revision. If there's an existing disabled draft revision, a new revision will be created based on that draft and will be enabled.",
          "httpMethod": "POST",
          "flatPath": "v2beta/labels/{labelsId}:enable",
          "id": "drivelabels.labels.enable",
          "path": "v2beta/{+name}:enable"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "v2beta/labels",
          "id": "drivelabels.labels.list",
          "path": "v2beta/labels",
          "scopes": [
            "https://www.googleapis.com/auth/drive.admin.labels",
            "https://www.googleapis.com/auth/drive.admin.labels.readonly",
            "https://www.googleapis.com/auth/drive.labels",
            "https://www.googleapis.com/auth/drive.labels.readonly"
          ],
          "description": "List labels. For more information, see [Search for labels](https://developers.google.com/workspace/drive/labels/guides/search-label)."
        },
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.admin.labels",
            "https://www.googleapis.com/auth/drive.labels"
          ],
          "description": "Creates a label. For more information, see [Create and publish a label](https://developers.google.com/workspace/drive/labels/guides/create-label).",
          "path": "v2beta/labels",
          "id": "drivelabels.labels.create",
          "flatPath": "v2beta/labels",
          "httpMethod": "POST"
        },
        "updateLabelEnabledAppSettings": {
          "flatPath": "v2beta/labels/{labelsId}:updateLabelEnabledAppSettings",
          "httpMethod": "POST",
          "path": "v2beta/{+name}:updateLabelEnabledAppSettings",
          "id": "drivelabels.labels.updateLabelEnabledAppSettings",
          "description": "Updates a label's `EnabledAppSettings`. Enabling a label in a Google Workspace app allows it to be used in that app. This change isn't revisioned, doesn't require publishing, and takes effect immediately."
        },
        "publish": {
          "flatPath": "v2beta/labels/{labelsId}:publish",
          "httpMethod": "POST",
          "path": "v2beta/{+name}:publish",
          "id": "drivelabels.labels.publish",
          "scopes": [
            "https://www.googleapis.com/auth/drive.admin.labels",
            "https://www.googleapis.com/auth/drive.labels"
          ],
          "description": "Publish all draft changes to the label. Once published, the label may not return to its draft state. For more information, see [Create and publish a label](https://developers.google.com/workspace/drive/labels/guides/create-label). Publishing a label will result in a new published revision. All previous draft revisions will be deleted. Previous published revisions will be kept but are subject to automated deletion as needed. For more information, see [Label lifecycle](ht[...]"
        },
        "updatePermissions": {
          "id": "drivelabels.labels.updatePermissions",
          "path": "v2beta/{+parent}/permissions",
          "httpMethod": "PATCH",
          "flatPath": "v2beta/labels/{labelsId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive.admin.labels",
            "https://www.googleapis.com/auth/drive.labels"
          ],
          "description": "Updates a label's permissions. If a permission for the indicated principal doesn't exist, a label permission is created, otherwise the existing permission is updated. Permissions affect the label resource as a whole, aren't revisioned, and don't require publishing."
        },
        "updateLabelCopyMode": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.admin.labels",
            "https://www.googleapis.com/auth/drive.labels"
          ],
          "description": "Updates a label's `CopyMode`. Changes to this policy aren't revisioned, don't require publishing, and take effect immediately.",
          "id": "drivelabels.labels.updateLabelCopyMode",
          "path": "v2beta/{+name}:updateLabelCopyMode",
          "httpMethod": "POST",
          "flatPath": "v2beta/labels/{labelsId}:updateLabelCopyMode"
        },
        "disable": {
          "path": "v2beta/{+name}:disable",
          "id": "drivelabels.labels.disable",
          "flatPath": "v2beta/labels/{labelsId}:disable",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive.admin.labels",
            "https://www.googleapis.com/auth/drive.labels"
          ],
          "description": "Disable a published label. For more information, see [Disable, enable, and delete a label](https://developers.google.com/workspace/drive/labels/guides/disable-delete-label). Disabling a label will result in a new disabled published revision based on the current published revision. If there's a draft revision, a new disabled draft revision will be created based on the latest draft revision. Older draft revisions will be deleted. Once disabled, a label may be deleted with[...]"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.admin.labels",
            "https://www.googleapis.com/auth/drive.admin.labels.readonly",
            "https://www.googleapis.com/auth/drive.labels",
            "https://www.googleapis.com/auth/drive.labels.readonly"
          ],
          "description": "Get a label by its resource name. For more information, see [Search for labels](https://developers.google.com/workspace/drive/labels/guides/search-label). Resource name may be any of: * `labels/{id}` - See `labels/{id}@latest` * `labels/{id}@latest` - Gets the latest revision of the label. * `labels/{id}@published` - Gets the current published revision of the label. * `labels/{id}@{revision_id}` - Gets the label at the specified revision ID.",
          "httpMethod": "GET",
          "flatPath": "v2beta/labels/{labelsId}",
          "id": "drivelabels.labels.get",
          "path": "v2beta/{+name}"
        },
        "delta": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.admin.labels",
            "https://www.googleapis.com/auth/drive.labels"
          ],
          "description": "Updates a single label by applying a set of update requests resulting in a new draft revision. For more information, see [Update a label](https://developers.google.com/workspace/drive/labels/guides/update-label). The batch update is all-or-nothing: If any of the update requests are invalid, no changes are applied. The resulting draft revision must be published before the changes may be used with Drive items.",
          "path": "v2beta/{+name}:delta",
          "id": "drivelabels.labels.delta",
          "flatPath": "v2beta/labels/{labelsId}:delta",
          "httpMethod": "POST"
        },
        "delete": {
          "flatPath": "v2beta/labels/{labelsId}",
          "httpMethod": "DELETE",
          "path": "v2beta/{+name}",
          "id": "drivelabels.labels.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive.admin.labels",
            "https://www.googleapis.com/auth/drive.labels"
          ],
          "description": "Permanently deletes a label and related metadata on Drive items. For more information, see [Disable, enable, and delete a label](https://developers.google.com/workspace/drive/labels/guides/disable-delete-label). Once deleted, the label and related Drive item metadata will be deleted. Only draft labels and disabled labels may be deleted."
        }
      },
      "resources": {
        "permissions": {
          "methods": {
            "batchUpdate": {
              "scopes": [
                "https://www.googleapis.com/auth/drive.admin.labels",
                "https://www.googleapis.com/auth/drive.labels"
              ],
              "description": "Updates label permissions. If a permission for the indicated principal doesn't exist, a label permission is created, otherwise the existing permission is updated. Permissions affect the label resource as a whole, aren't revisioned, and don't require publishing.",
              "path": "v2beta/{+parent}/permissions:batchUpdate",
              "id": "drivelabels.labels.permissions.batchUpdate",
              "flatPath": "v2beta/labels/{labelsId}/permissions:batchUpdate",
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "v2beta/labels/{labelsId}/permissions",
              "httpMethod": "GET",
              "path": "v2beta/{+parent}/permissions",
              "id": "drivelabels.labels.permissions.list",
              "scopes": [
                "https://www.googleapis.com/auth/drive.admin.labels",
                "https://www.googleapis.com/auth/drive.admin.labels.readonly",
                "https://www.googleapis.com/auth/drive.labels",
                "https://www.googleapis.com/auth/drive.labels.readonly"
              ],
              "description": "Lists a label's permissions."
            },
            "batchDelete": {
              "httpMethod": "POST",
              "flatPath": "v2beta/labels/{labelsId}/permissions:batchDelete",
              "id": "drivelabels.labels.permissions.batchDelete",
              "path": "v2beta/{+parent}/permissions:batchDelete",
              "scopes": [
                "https://www.googleapis.com/auth/drive.admin.labels",
                "https://www.googleapis.com/auth/drive.labels"
              ],
              "description": "Deletes label permissions. Permissions affect the label resource as a whole, aren't revisioned, and don't require publishing."
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/drive.admin.labels",
                "https://www.googleapis.com/auth/drive.labels"
              ],
              "description": "Updates a label's permissions. If a permission for the indicated principal doesn't exist, a label permission is created, otherwise the existing permission is updated. Permissions affect the label resource as a whole, aren't revisioned, and don't require publishing.",
              "flatPath": "v2beta/labels/{labelsId}/permissions",
              "httpMethod": "POST",
              "path": "v2beta/{+parent}/permissions",
              "id": "drivelabels.labels.permissions.create"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/drive.admin.labels",
                "https://www.googleapis.com/auth/drive.labels"
              ],
              "description": "Deletes a label's permission. Permissions affect the label resource as a whole, aren't revisioned, and don't require publishing.",
              "path": "v2beta/{+name}",
              "id": "drivelabels.labels.permissions.delete",
              "flatPath": "v2beta/labels/{labelsId}/permissions/{permissionsId}",
              "httpMethod": "DELETE"
            }
          }
        },
        "revisions": {
          "methods": {
            "updatePermissions": {
              "httpMethod": "PATCH",
              "flatPath": "v2beta/labels/{labelsId}/revisions/{revisionsId}/permissions",
              "id": "drivelabels.labels.revisions.updatePermissions",
              "path": "v2beta/{+parent}/permissions",
              "scopes": [
                "https://www.googleapis.com/auth/drive.admin.labels",
                "https://www.googleapis.com/auth/drive.labels"
              ],
              "description": "Updates a label's permissions. If a permission for the indicated principal doesn't exist, a label permission is created, otherwise the existing permission is updated. Permissions affect the label resource as a whole, aren't revisioned, and don't require publishing."
            }
          },
          "resources": {
            "locks": {
              "methods": {
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "v2beta/labels/{labelsId}/revisions/{revisionsId}/locks",
                  "id": "drivelabels.labels.revisions.locks.list",
                  "path": "v2beta/{+parent}/locks",
                  "scopes": [
                    "https://www.googleapis.com/auth/drive.admin.labels",
                    "https://www.googleapis.com/auth/drive.admin.labels.readonly",
                    "https://www.googleapis.com/auth/drive.labels",
                    "https://www.googleapis.com/auth/drive.labels.readonly"
                  ],
                  "description": "Lists the label locks on a label."
                }
              }
            },
            "permissions": {
              "methods": {
                "list": {
                  "flatPath": "v2beta/labels/{labelsId}/revisions/{revisionsId}/permissions",
                  "httpMethod": "GET",
                  "path": "v2beta/{+parent}/permissions",
                  "id": "drivelabels.labels.revisions.permissions.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/drive.admin.labels",
                    "https://www.googleapis.com/auth/drive.admin.labels.readonly",
                    "https://www.googleapis.com/auth/drive.labels",
                    "https://www.googleapis.com/auth/drive.labels.readonly"
                  ],
                  "description": "Lists a label's permissions."
                },
                "batchDelete": {
                  "path": "v2beta/{+parent}/permissions:batchDelete",
                  "id": "drivelabels.labels.revisions.permissions.batchDelete",
                  "flatPath": "v2beta/labels/{labelsId}/revisions/{revisionsId}/permissions:batchDelete",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/drive.admin.labels",
                    "https://www.googleapis.com/auth/drive.labels"
                  ],
                  "description": "Deletes label permissions. Permissions affect the label resource as a whole, aren't revisioned, and don't require publishing."
                },
                "batchUpdate": {
                  "scopes": [
                    "https://www.googleapis.com/auth/drive.admin.labels",
                    "https://www.googleapis.com/auth/drive.labels"
                  ],
                  "description": "Updates label permissions. If a permission for the indicated principal doesn't exist, a label permission is created, otherwise the existing permission is updated. Permissions affect the label resource as a whole, aren't revisioned, and don't require publishing.",
                  "path": "v2beta/{+parent}/permissions:batchUpdate",
                  "id": "drivelabels.labels.revisions.permissions.batchUpdate",
                  "flatPath": "v2beta/labels/{labelsId}/revisions/{revisionsId}/permissions:batchUpdate",
                  "httpMethod": "POST"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "v2beta/labels/{labelsId}/revisions/{revisionsId}/permissions/{permissionsId}",
                  "id": "drivelabels.labels.revisions.permissions.delete",
                  "path": "v2beta/{+name}",
                  "scopes": [
                    "https://www.googleapis.com/auth/drive.admin.labels",
                    "https://www.googleapis.com/auth/drive.labels"
                  ],
                  "description": "Deletes a label's permission. Permissions affect the label resource as a whole, aren't revisioned, and don't require publishing."
                },
                "create": {
                  "flatPath": "v2beta/labels/{labelsId}/revisions/{revisionsId}/permissions",
                  "httpMethod": "POST",
                  "path": "v2beta/{+parent}/permissions",
                  "id": "drivelabels.labels.revisions.permissions.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/drive.admin.labels",
                    "https://www.googleapis.com/auth/drive.labels"
                  ],
                  "description": "Updates a label's permissions. If a permission for the indicated principal doesn't exist, a label permission is created, otherwise the existing permission is updated. Permissions affect the label resource as a whole, aren't revisioned, and don't require publishing."
                }
              }
            }
          }
        },
        "locks": {
          "methods": {
            "list": {
              "flatPath": "v2beta/labels/{labelsId}/locks",
              "httpMethod": "GET",
              "path": "v2beta/{+parent}/locks",
              "id": "drivelabels.labels.locks.list",
              "scopes": [
                "https://www.googleapis.com/auth/drive.admin.labels",
                "https://www.googleapis.com/auth/drive.admin.labels.readonly",
                "https://www.googleapis.com/auth/drive.labels",
                "https://www.googleapis.com/auth/drive.labels.readonly"
              ],
              "description": "Lists the label locks on a label."
            }
          }
        }
      }
    }
  },
  "id": "drivelabels:v2beta",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "mtlsRootUrl": "https://drivelabels.mtls.googleapis.com/",
  "documentationLink": "https://developers.google.com/workspace/drive/labels",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.labels": {
          "description": "See, edit, create, and delete your Google Drive labels"
        },
        "https://www.googleapis.com/auth/drive.admin.labels.readonly": {
          "description": "See all Google Drive labels and label-related admin policies in your organization"
        },
        "https://www.googleapis.com/auth/drive.labels.readonly": {
          "description": "See your Google Drive labels"
        },
        "https://www.googleapis.com/auth/drive.admin.labels": {
          "description": "See, edit, create, and delete all Google Drive labels in your organization, and see your organization's label-related admin policies"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "baseUrl": "https://drivelabels.googleapis.com/",
  "servicePath": "",
  "version": "v2beta",
  "rootUrl": "https://drivelabels.googleapis.com/",
  "ownerDomain": "google.com",
  "description": "An API for managing Drive Labels",
  "name": "drivelabels",
  "basePath": "",
  "revision": "20260504",
  "version_module": true,
  "title": "Drive Labels API",
  "ownerName": "Google",
  "protocol": "rest"
}