{
  "discoveryVersion": "v1",
  "servicePath": "drive/v2/",
  "name": "drive",
  "title": "Google Drive API",
  "id": "drive:v2",
  "ownerName": "Google",
  "version": "v2",
  "protocol": "rest",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "kind": "discovery#restDescription",
  "rootUrl": "https://www.googleapis.com/",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "revision": "20260428",
  "resources": {
    "parents": {
      "methods": {
        "get": {
          "flatPath": "files/{fileId}/parents/{parentId}",
          "path": "files/{fileId}/parents/{parentId}",
          "description": "Gets a specific parent reference.",
          "httpMethod": "GET",
          "id": "drive.parents.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.parents.delete",
          "path": "files/{fileId}/parents/{parentId}",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "httpMethod": "DELETE",
          "description": "Removes a parent from a file."
        },
        "insert": {
          "path": "files/{fileId}/parents",
          "flatPath": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.parents.insert",
          "httpMethod": "POST",
          "description": "Adds a parent folder for a file."
        },
        "list": {
          "path": "files/{fileId}/parents",
          "flatPath": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.parents.list",
          "httpMethod": "GET",
          "description": "Lists a file's parents."
        }
      }
    },
    "permissions": {
      "methods": {
        "getIdForEmail": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.permissions.getIdForEmail",
          "httpMethod": "GET",
          "description": "Returns the permission ID for an email address.",
          "path": "permissionIds/{email}",
          "flatPath": "permissionIds/{email}"
        },
        "insert": {
          "path": "files/{fileId}/permissions",
          "flatPath": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.insert",
          "httpMethod": "POST",
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.permissions.list",
          "httpMethod": "GET",
          "description": "Lists a file's or shared drive's permissions.",
          "path": "files/{fileId}/permissions",
          "flatPath": "files/{fileId}/permissions"
        },
        "patch": {
          "id": "drive.permissions.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "PATCH",
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}"
        },
        "delete": {
          "id": "drive.permissions.delete",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "DELETE"
        },
        "update": {
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "path": "files/{fileId}/permissions/{permissionId}",
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "PUT",
          "id": "drive.permissions.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a permission by ID.",
          "httpMethod": "GET"
        }
      }
    },
    "drives": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.drives.get",
          "httpMethod": "GET",
          "description": "Gets a shared drive's metadata by ID.",
          "path": "drives/{driveId}",
          "flatPath": "drives/{driveId}"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.delete",
          "path": "drives/{driveId}",
          "flatPath": "drives/{driveId}",
          "httpMethod": "DELETE",
          "description": "Permanently deletes a shared drive for which the user is an `organizer`. The shared drive cannot contain any untrashed items."
        },
        "update": {
          "flatPath": "drives/{driveId}",
          "path": "drives/{driveId}",
          "httpMethod": "PUT",
          "description": "Updates the metadata for a shared drive.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.update"
        },
        "unhide": {
          "path": "drives/{driveId}/unhide",
          "flatPath": "drives/{driveId}/unhide",
          "id": "drive.drives.unhide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Restores a shared drive to the default view.",
          "httpMethod": "POST"
        },
        "hide": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.hide",
          "httpMethod": "POST",
          "description": "Hides a shared drive from the default view.",
          "path": "drives/{driveId}/hide",
          "flatPath": "drives/{driveId}/hide"
        },
        "insert": {
          "path": "drives",
          "flatPath": "drives",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.insert",
          "httpMethod": "POST",
          "description": "Creates a new shared drive."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.drives.list",
          "httpMethod": "GET",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](https://developers.google.com/workspace/drive/api/guides/search-shareddrives) guide.",
          "path": "drives",
          "flatPath": "drives"
        }
      }
    },
    "replies": {
      "methods": {
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.replies.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "insert": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "description": "Creates a new reply to the given comment.",
          "httpMethod": "POST",
          "id": "drive.replies.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "httpMethod": "GET",
          "description": "Lists all of the replies to a comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.replies.list"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.replies.get",
          "httpMethod": "GET",
          "description": "Gets a reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.replies.delete",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "DELETE",
          "description": "Deletes a reply."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.replies.update",
          "httpMethod": "PUT",
          "description": "Updates an existing reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        }
      }
    },
    "properties": {
      "methods": {
        "patch": {
          "id": "drive.properties.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Updates a property.",
          "httpMethod": "PATCH",
          "path": "files/{fileId}/properties/{propertyKey}",
          "flatPath": "files/{fileId}/properties/{propertyKey}"
        },
        "insert": {
          "path": "files/{fileId}/properties",
          "flatPath": "files/{fileId}/properties",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.properties.insert",
          "httpMethod": "POST",
          "description": "Adds a property to a file, or updates it if it already exists."
        },
        "list": {
          "flatPath": "files/{fileId}/properties",
          "path": "files/{fileId}/properties",
          "description": "Lists a file's properties.",
          "httpMethod": "GET",
          "id": "drive.properties.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "get": {
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "path": "files/{fileId}/properties/{propertyKey}",
          "description": "Gets a property by its key.",
          "httpMethod": "GET",
          "id": "drive.properties.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "id": "drive.properties.delete",
          "path": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Deletes a property.",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "DELETE"
        },
        "update": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Updates a property.",
          "httpMethod": "PUT"
        }
      }
    },
    "teamdrives": {
      "methods": {
        "insert": {
          "flatPath": "teamdrives",
          "path": "teamdrives",
          "description": "Deprecated: Use `drives.insert` instead.",
          "httpMethod": "POST",
          "id": "drive.teamdrives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "flatPath": "teamdrives",
          "path": "teamdrives",
          "description": "Deprecated: Use `drives.list` instead.",
          "httpMethod": "GET",
          "id": "drive.teamdrives.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "id": "drive.teamdrives.delete",
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Deprecated: Use `drives.delete` instead.",
          "httpMethod": "DELETE",
          "flatPath": "teamdrives/{teamDriveId}"
        },
        "update": {
          "flatPath": "teamdrives/{teamDriveId}",
          "path": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.update` instead.",
          "httpMethod": "PUT",
          "id": "drive.teamdrives.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "get": {
          "flatPath": "teamdrives/{teamDriveId}",
          "path": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.get` instead.",
          "httpMethod": "GET",
          "id": "drive.teamdrives.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "touch": {
          "httpMethod": "POST",
          "description": "Set the file's updated time to the current server time.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.files.touch",
          "flatPath": "files/{fileId}/touch",
          "path": "files/{fileId}/touch"
        },
        "listLabels": {
          "path": "files/{fileId}/listLabels",
          "flatPath": "files/{fileId}/listLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.listLabels",
          "httpMethod": "GET",
          "description": "Lists the labels on a file."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.delete",
          "path": "files/{fileId}",
          "httpMethod": "DELETE",
          "flatPath": "files/{fileId}",
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive, the user must be an `organizer` on the parent folder. If the target is a folder, all descendants owned by the user are also deleted."
        },
        "emptyTrash": {
          "httpMethod": "DELETE",
          "flatPath": "files/trash",
          "description": "Permanently deletes all of the user's trashed files.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.files.emptyTrash",
          "path": "files/trash"
        },
        "copy": {
          "httpMethod": "POST",
          "description": "Creates a copy of the specified file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "id": "drive.files.copy",
          "flatPath": "files/{fileId}/copy",
          "path": "files/{fileId}/copy"
        },
        "trash": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.trash",
          "httpMethod": "POST",
          "description": "Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "path": "files/{fileId}/trash",
          "flatPath": "files/{fileId}/trash"
        },
        "generateIds": {
          "flatPath": "files/generateIds",
          "path": "files/generateIds",
          "httpMethod": "GET",
          "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.generateIds"
        },
        "patch": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "id": "drive.files.patch",
          "httpMethod": "PATCH",
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
          "path": "files/{fileId}",
          "flatPath": "files/{fileId}"
        },
        "generateCseToken": {
          "path": "files/generateCseToken",
          "flatPath": "files/generateCseToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.files.generateCseToken",
          "httpMethod": "GET",
          "description": "Generates a CSE token which can be used to create or update CSE files."
        },
        "insert": {
          "supportsMediaUpload": true,
          "flatPath": "files",
          "path": "files",
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](https://developers.google.com/workspace/drive/api/guides/manage-u[...]",
          "httpMethod": "POST",
          "id": "drive.files.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "id": "drive.files.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": " Lists the user's files. For more information, see [Search for files and folders](https://developers.google.com/workspace/drive/api/guides/search-files). This method accepts the `q` parameter, which is a search query combining one or more search terms. This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.",
          "httpMethod": "GET",
          "path": "files",
          "flatPath": "files"
        },
        "modifyLabels": {
          "flatPath": "files/{fileId}/modifyLabels",
          "path": "files/{fileId}/modifyLabels",
          "httpMethod": "POST",
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.files.modifyLabels"
        },
        "update": {
          "path": "files/{fileId}",
          "supportsMediaUpload": true,
          "flatPath": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "id": "drive.files.update",
          "httpMethod": "PUT",
          "description": " Updates a file's metadata, content, or both. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:* `*/*` (Specify a valid MIME type, rather than the[...]"
        },
        "export": {
          "useMediaDownloadService": true,
          "httpMethod": "GET",
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.export",
          "flatPath": "files/{fileId}/export",
          "supportsMediaDownload": true,
          "path": "files/{fileId}/export"
        },
        "get": {
          "id": "drive.files.get",
          "supportsSubscription": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](https://developers.google.com/workspace/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](https://developers.google.com/w[...]",
          "httpMethod": "GET",
          "useMediaDownloadService": true,
          "path": "files/{fileId}",
          "supportsMediaDownload": true,
          "flatPath": "files/{fileId}"
        },
        "untrash": {
          "path": "files/{fileId}/untrash",
          "flatPath": "files/{fileId}/untrash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.untrash",
          "httpMethod": "POST",
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files."
        },
        "watch": {
          "supportsSubscription": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.watch",
          "httpMethod": "POST",
          "description": "Subscribes to changes to a file.",
          "path": "files/{fileId}/watch",
          "flatPath": "files/{fileId}/watch"
        }
      }
    },
    "revisions": {
      "methods": {
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates a revision.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.revisions.patch",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "path": "files/{fileId}/revisions/{revisionId}"
        },
        "list": {
          "flatPath": "files/{fileId}/revisions",
          "path": "files/{fileId}/revisions",
          "description": "Lists a file's revisions. **Important:** The list of revisions returned by this method might be incomplete for files with a large revision history, including frequently edited Google Docs, Sheets, and Slides. Older revisions might be omitted from the response, meaning the first revision returned may not be the oldest existing revision. The revision history visible in the Workspace editor user interface might be more complete than the list returned by the API.",
          "httpMethod": "GET",
          "id": "drive.revisions.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "get": {
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "path": "files/{fileId}/revisions/{revisionId}",
          "description": "Gets a specific revision.",
          "httpMethod": "GET",
          "id": "drive.revisions.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.revisions.delete",
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "DELETE",
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted."
        },
        "update": {
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.revisions.update",
          "httpMethod": "PUT",
          "description": "Updates a revision."
        }
      }
    },
    "apps": {
      "methods": {
        "list": {
          "flatPath": "apps",
          "path": "apps",
          "httpMethod": "GET",
          "description": "Lists a user's installed apps.",
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ],
          "id": "drive.apps.list"
        },
        "get": {
          "path": "apps/{appId}",
          "flatPath": "apps/{appId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.apps.get",
          "httpMethod": "GET",
          "description": "Gets a specific app."
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "flatPath": "about",
          "path": "about",
          "httpMethod": "GET",
          "description": "Gets the information about the current user along with Drive API settings",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.about.get"
        }
      }
    },
    "changes": {
      "methods": {
        "watch": {
          "flatPath": "changes/watch",
          "path": "changes/watch",
          "httpMethod": "POST",
          "description": "Subscribe to changes for a user.",
          "supportsSubscription": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.watch"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.get",
          "httpMethod": "GET",
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "path": "changes/{changeId}",
          "flatPath": "changes/{changeId}"
        },
        "getStartPageToken": {
          "httpMethod": "GET",
          "description": "Gets the starting pageToken for listing future changes.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.getStartPageToken",
          "flatPath": "changes/startPageToken",
          "path": "changes/startPageToken"
        },
        "list": {
          "path": "changes",
          "flatPath": "changes",
          "supportsSubscription": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.list",
          "httpMethod": "GET",
          "description": "Lists the changes for a user or shared drive."
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "flatPath": "channels/stop",
          "path": "channels/stop",
          "httpMethod": "POST",
          "description": "Stops watching resources through this channel.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.channels.stop"
        }
      }
    },
    "children": {
      "methods": {
        "delete": {
          "id": "drive.children.delete",
          "path": "files/{folderId}/children/{childId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Removes a child from a folder.",
          "httpMethod": "DELETE",
          "flatPath": "files/{folderId}/children/{childId}"
        },
        "insert": {
          "path": "files/{folderId}/children",
          "flatPath": "files/{folderId}/children",
          "id": "drive.children.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Inserts a file into a folder.",
          "httpMethod": "POST"
        },
        "list": {
          "description": "Lists a folder's children.",
          "httpMethod": "GET",
          "id": "drive.children.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{folderId}/children",
          "path": "files/{folderId}/children"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a specific child reference.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.children.get",
          "flatPath": "files/{folderId}/children/{childId}",
          "path": "files/{folderId}/children/{childId}"
        }
      }
    },
    "comments": {
      "methods": {
        "delete": {
          "id": "drive.comments.delete",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Deletes a comment.",
          "httpMethod": "DELETE",
          "flatPath": "files/{fileId}/comments/{commentId}"
        },
        "update": {
          "path": "files/{fileId}/comments/{commentId}",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.comments.update",
          "httpMethod": "PUT",
          "description": "Updates an existing comment."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a comment by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.comments.get",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}"
        },
        "insert": {
          "description": "Creates a new comment on the given file.",
          "httpMethod": "POST",
          "id": "drive.comments.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments",
          "path": "files/{fileId}/comments"
        },
        "list": {
          "flatPath": "files/{fileId}/comments",
          "path": "files/{fileId}/comments",
          "description": "Lists a file's comments.",
          "httpMethod": "GET",
          "id": "drive.comments.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.comments.patch",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}"
        }
      }
    }
  },
  "basePath": "/drive/v2/",
  "ownerDomain": "google.com",
  "baseUrl": "https://www.googleapis.com/drive/v2/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.meet.readonly": {
          "description": "See and download your Google Drive files that were created or edited by Google Meet."
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        }
      }
    }
  },
  "batchPath": "batch/drive/v2",
  "documentationLink": "https://developers.google.com/workspace/drive/"
}