{
  "baseUrl": "https://www.googleapis.com/drive/v2/",
  "rootUrl": "https://www.googleapis.com/",
  "protocol": "rest",
  "ownerName": "Google",
  "name": "drive",
  "discoveryVersion": "v1",
  "resources": {
    "comments": {
      "methods": {
        "update": {
          "path": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.update",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates an existing comment.",
          "httpMethod": "PUT"
        },
        "delete": {
          "path": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.delete",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "description": "Deletes a comment.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "path": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.comments.list",
          "flatPath": "files/{fileId}/comments",
          "httpMethod": "GET",
          "description": "Lists a file's comments."
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing comment.",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.comments.patch",
          "flatPath": "files/{fileId}/comments/{commentId}"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a comment by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.comments.get",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}"
        },
        "insert": {
          "path": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.comments.insert",
          "flatPath": "files/{fileId}/comments",
          "httpMethod": "POST",
          "description": "Creates a new comment on the given file."
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.about.get",
          "flatPath": "about",
          "path": "about",
          "httpMethod": "GET",
          "description": "Gets the information about the current user along with Drive API settings"
        }
      }
    },
    "changes": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "path": "changes/{changeId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.get",
          "flatPath": "changes/{changeId}"
        },
        "getStartPageToken": {
          "httpMethod": "GET",
          "description": "Gets the starting pageToken for listing future changes.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.getStartPageToken",
          "flatPath": "changes/startPageToken",
          "path": "changes/startPageToken"
        },
        "list": {
          "path": "changes",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.list",
          "flatPath": "changes",
          "supportsSubscription": true,
          "httpMethod": "GET",
          "description": "Lists the changes for a user or shared drive."
        },
        "watch": {
          "supportsSubscription": true,
          "id": "drive.changes.watch",
          "flatPath": "changes/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "changes/watch",
          "description": "Subscribe to changes for a user.",
          "httpMethod": "POST"
        }
      }
    },
    "parents": {
      "methods": {
        "delete": {
          "id": "drive.parents.delete",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "description": "Removes a parent from a file.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/parents/{parentId}"
        },
        "list": {
          "id": "drive.parents.list",
          "flatPath": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/parents",
          "description": "Lists a file's parents.",
          "httpMethod": "GET"
        },
        "get": {
          "id": "drive.parents.get",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/parents/{parentId}",
          "description": "Gets a specific parent reference.",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Adds a parent folder for a file.",
          "path": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.parents.insert",
          "flatPath": "files/{fileId}/parents"
        }
      }
    },
    "teamdrives": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Deprecated: Use `drives.get` instead.",
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.teamdrives.get",
          "flatPath": "teamdrives/{teamDriveId}"
        },
        "delete": {
          "id": "drive.teamdrives.delete",
          "flatPath": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.delete` instead.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "teamdrives/{teamDriveId}"
        },
        "list": {
          "description": "Deprecated: Use `drives.list` instead.",
          "httpMethod": "GET",
          "id": "drive.teamdrives.list",
          "flatPath": "teamdrives",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "teamdrives"
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.teamdrives.update",
          "flatPath": "teamdrives/{teamDriveId}",
          "path": "teamdrives/{teamDriveId}",
          "httpMethod": "PUT",
          "description": "Deprecated: Use `drives.update` instead."
        },
        "insert": {
          "description": "Deprecated: Use `drives.insert` instead.",
          "httpMethod": "POST",
          "path": "teamdrives",
          "id": "drive.teamdrives.insert",
          "flatPath": "teamdrives",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        }
      }
    },
    "permissions": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.permissions.get",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "path": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "GET",
          "description": "Gets a permission by ID."
        },
        "delete": {
          "id": "drive.permissions.delete",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/permissions/{permissionId}"
        },
        "list": {
          "id": "drive.permissions.list",
          "flatPath": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/permissions",
          "description": "Lists a file's or shared drive's permissions.",
          "httpMethod": "GET"
        },
        "patch": {
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.patch",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "PATCH",
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
        },
        "getIdForEmail": {
          "httpMethod": "GET",
          "description": "Returns the permission ID for an email address.",
          "path": "permissionIds/{email}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.permissions.getIdForEmail",
          "flatPath": "permissionIds/{email}"
        },
        "update": {
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.update",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "PUT",
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied."
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.insert",
          "flatPath": "files/{fileId}/permissions"
        }
      }
    },
    "properties": {
      "methods": {
        "insert": {
          "path": "files/{fileId}/properties",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.properties.insert",
          "flatPath": "files/{fileId}/properties",
          "httpMethod": "POST",
          "description": "Adds a property to a file, or updates it if it already exists."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.properties.get",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "path": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "GET",
          "description": "Gets a property by its key."
        },
        "delete": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.delete",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "description": "Deletes a property.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "list": {
          "description": "Lists a file's properties.",
          "httpMethod": "GET",
          "path": "files/{fileId}/properties",
          "id": "drive.properties.list",
          "flatPath": "files/{fileId}/properties",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "patch": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.properties.patch",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "PATCH",
          "description": "Updates a property."
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.properties.update",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "path": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "PUT",
          "description": "Updates a property."
        }
      }
    },
    "drives": {
      "methods": {
        "delete": {
          "path": "drives/{driveId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.delete",
          "flatPath": "drives/{driveId}",
          "description": "Permanently deletes a shared drive for which the user is an `organizer`. The shared drive cannot contain any untrashed items."
        },
        "hide": {
          "httpMethod": "POST",
          "description": "Hides a shared drive from the default view.",
          "path": "drives/{driveId}/hide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.hide",
          "flatPath": "drives/{driveId}/hide"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.drives.list",
          "flatPath": "drives",
          "path": "drives",
          "httpMethod": "GET",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](https://developers.google.com/workspace/drive/api/guides/search-shareddrives) guide."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a shared drive's metadata by ID.",
          "path": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.drives.get",
          "flatPath": "drives/{driveId}"
        },
        "update": {
          "description": "Updates the metadata for a shared drive.",
          "httpMethod": "PUT",
          "path": "drives/{driveId}",
          "id": "drive.drives.update",
          "flatPath": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "unhide": {
          "id": "drive.drives.unhide",
          "flatPath": "drives/{driveId}/unhide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "drives/{driveId}/unhide",
          "description": "Restores a shared drive to the default view.",
          "httpMethod": "POST"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Creates a new shared drive.",
          "path": "drives",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.insert",
          "flatPath": "drives"
        }
      }
    },
    "revisions": {
      "methods": {
        "update": {
          "description": "Updates a revision.",
          "httpMethod": "PUT",
          "id": "drive.revisions.update",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/revisions/{revisionId}"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a specific revision.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.revisions.get",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "path": "files/{fileId}/revisions/{revisionId}"
        },
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.revisions.delete",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
          "path": "files/{fileId}/revisions/{revisionId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.revisions.list",
          "flatPath": "files/{fileId}/revisions",
          "path": "files/{fileId}/revisions",
          "httpMethod": "GET",
          "description": "Lists a file's revisions. **Important:** The list of revisions returned by this method might be incomplete for files with a large revision history, including frequently edited Google Docs, Sheets, and Slides. Older revisions might be omitted from the response, meaning the first revision returned may not be the oldest existing revision. The revision history visible in the Workspace editor user interface might be more complete than the list returned by the API."
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates a revision.",
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.revisions.patch",
          "flatPath": "files/{fileId}/revisions/{revisionId}"
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "description": "Stops watching resources through this channel.",
          "httpMethod": "POST",
          "id": "drive.channels.stop",
          "flatPath": "channels/stop",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "channels/stop"
        }
      }
    },
    "children": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets a specific child reference.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.children.get",
          "flatPath": "files/{folderId}/children/{childId}",
          "path": "files/{folderId}/children/{childId}"
        },
        "insert": {
          "description": "Inserts a file into a folder.",
          "httpMethod": "POST",
          "path": "files/{folderId}/children",
          "id": "drive.children.insert",
          "flatPath": "files/{folderId}/children",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "delete": {
          "id": "drive.children.delete",
          "flatPath": "files/{folderId}/children/{childId}",
          "description": "Removes a child from a folder.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{folderId}/children/{childId}"
        },
        "list": {
          "description": "Lists a folder's children.",
          "httpMethod": "GET",
          "path": "files/{folderId}/children",
          "id": "drive.children.list",
          "flatPath": "files/{folderId}/children",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "replies": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "description": "Creates a new reply to the given comment.",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.replies.insert",
          "flatPath": "files/{fileId}/comments/{commentId}/replies"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.replies.get",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "GET",
          "description": "Gets a reply."
        },
        "delete": {
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.delete",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Deletes a reply.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "description": "Lists all of the replies to a comment.",
          "httpMethod": "GET",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "id": "drive.replies.list",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Updates an existing reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.replies.patch",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "update": {
          "id": "drive.replies.update",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Updates an existing reply.",
          "httpMethod": "PUT"
        }
      }
    },
    "apps": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "description": "Gets a specific app.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.apps.get",
          "flatPath": "apps/{appId}",
          "path": "apps/{appId}"
        },
        "list": {
          "path": "apps",
          "id": "drive.apps.list",
          "flatPath": "apps",
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ],
          "description": "Lists a user's installed apps.",
          "httpMethod": "GET"
        }
      }
    },
    "files": {
      "methods": {
        "modifyLabels": {
          "id": "drive.files.modifyLabels",
          "flatPath": "files/{fileId}/modifyLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "path": "files/{fileId}/modifyLabels",
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "httpMethod": "POST"
        },
        "delete": {
          "path": "files/{fileId}",
          "id": "drive.files.delete",
          "flatPath": "files/{fileId}",
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive, the user must be an `organizer` on the parent folder. If the target is a folder, all descendants owned by the user are also deleted.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "path": "files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.list",
          "flatPath": "files",
          "httpMethod": "GET",
          "description": " Lists the user's files. For more information, see [Search for files and folders](https://developers.google.com/workspace/drive/api/guides/search-files). This method accepts the `q` parameter, which is a search query combining one or more search terms. This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results."
        },
        "generateIds": {
          "httpMethod": "GET",
          "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.generateIds",
          "flatPath": "files/generateIds",
          "path": "files/generateIds"
        },
        "touch": {
          "httpMethod": "POST",
          "description": "Set the file's updated time to the current server time.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.files.touch",
          "flatPath": "files/{fileId}/touch",
          "path": "files/{fileId}/touch"
        },
        "get": {
          "path": "files/{fileId}",
          "supportsSubscription": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.get",
          "flatPath": "files/{fileId}",
          "supportsMediaDownload": true,
          "httpMethod": "GET",
          "useMediaDownloadService": true,
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](https://developers.google.com/workspace/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](https://developers.google.com/w[...]"
        },
        "emptyTrash": {
          "path": "files/trash",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.files.emptyTrash",
          "flatPath": "files/trash",
          "description": "Permanently deletes all of the user's trashed files."
        },
        "insert": {
          "httpMethod": "POST",
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](https://developers.google.com/workspace/drive/api/guides/manage-u[...]",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.insert",
          "flatPath": "files",
          "path": "files"
        },
        "update": {
          "supportsMediaUpload": true,
          "description": " Updates a file's metadata, content, or both. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:* `*/*` (Specify a valid MIME type, rather than the[...]",
          "httpMethod": "PUT",
          "path": "files/{fileId}",
          "id": "drive.files.update",
          "flatPath": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ]
        },
        "copy": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "id": "drive.files.copy",
          "flatPath": "files/{fileId}/copy",
          "path": "files/{fileId}/copy",
          "httpMethod": "POST",
          "description": "Creates a copy of the specified file."
        },
        "trash": {
          "id": "drive.files.trash",
          "flatPath": "files/{fileId}/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/trash",
          "description": "Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "httpMethod": "POST"
        },
        "patch": {
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "path": "files/{fileId}",
          "id": "drive.files.patch",
          "flatPath": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ]
        },
        "untrash": {
          "httpMethod": "POST",
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "path": "files/{fileId}/untrash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.untrash",
          "flatPath": "files/{fileId}/untrash"
        },
        "watch": {
          "description": "Subscribes to changes to a file.",
          "httpMethod": "POST",
          "supportsSubscription": true,
          "id": "drive.files.watch",
          "flatPath": "files/{fileId}/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/watch"
        },
        "export": {
          "supportsMediaDownload": true,
          "useMediaDownloadService": true,
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "httpMethod": "GET",
          "path": "files/{fileId}/export",
          "id": "drive.files.export",
          "flatPath": "files/{fileId}/export",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "listLabels": {
          "description": "Lists the labels on a file.",
          "httpMethod": "GET",
          "id": "drive.files.listLabels",
          "flatPath": "files/{fileId}/listLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/listLabels"
        }
      }
    }
  },
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.meet.readonly": {
          "description": "See and download your Google Drive files that were created or edited by Google Meet."
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        }
      }
    }
  },
  "batchPath": "batch/drive/v2",
  "kind": "discovery#restDescription",
  "version": "v2",
  "title": "Google Drive API",
  "documentationLink": "https://developers.google.com/workspace/drive/",
  "ownerDomain": "google.com",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "basePath": "/drive/v2/",
  "servicePath": "drive/v2/",
  "revision": "20260401",
  "id": "drive:v2"
}