{
  "revision": "20260427",
  "batchPath": "batch/drive/v2",
  "id": "drive:v2",
  "protocol": "rest",
  "documentationLink": "https://developers.google.com/workspace/drive/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.meet.readonly": {
          "description": "See and download your Google Drive files that were created or edited by Google Meet."
        }
      }
    }
  },
  "baseUrl": "https://www.googleapis.com/drive/v2/",
  "version": "v2",
  "title": "Google Drive API",
  "discoveryVersion": "v1",
  "resources": {
    "files": {
      "methods": {
        "generateCseToken": {
          "path": "files/generateCseToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "files/generateCseToken",
          "description": "Generates a CSE token which can be used to create or update CSE files.",
          "id": "drive.files.generateCseToken",
          "httpMethod": "GET"
        },
        "emptyTrash": {
          "id": "drive.files.emptyTrash",
          "flatPath": "files/trash",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "files/trash",
          "description": "Permanently deletes all of the user's trashed files."
        },
        "update": {
          "flatPath": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "path": "files/{fileId}",
          "supportsMediaUpload": true,
          "id": "drive.files.update",
          "httpMethod": "PUT",
          "description": " Updates a file's metadata, content, or both. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:* `*/*` (Specify a valid MIME type, rather than the[...]"
        },
        "insert": {
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](https://developers.google.com/workspace/drive/api/guides/manage-u[...]",
          "id": "drive.files.insert",
          "httpMethod": "POST",
          "supportsMediaUpload": true,
          "path": "files",
          "flatPath": "files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "path": "files/{fileId}",
          "useMediaDownloadService": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}",
          "supportsMediaDownload": true,
          "supportsSubscription": true,
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](https://developers.google.com/workspace/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](https://developers.google.com/w[...]",
          "id": "drive.files.get",
          "httpMethod": "GET"
        },
        "trash": {
          "description": "Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "id": "drive.files.trash",
          "httpMethod": "POST",
          "path": "files/{fileId}/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/trash"
        },
        "delete": {
          "path": "files/{fileId}",
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive, the user must be an `organizer` on the parent folder. If the target is a folder, all descendants owned by the user are also deleted.",
          "id": "drive.files.delete",
          "flatPath": "files/{fileId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "patch": {
          "path": "files/{fileId}",
          "flatPath": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
          "id": "drive.files.patch",
          "httpMethod": "PATCH"
        },
        "watch": {
          "supportsSubscription": true,
          "path": "files/{fileId}/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/watch",
          "description": "Subscribes to changes to a file.",
          "id": "drive.files.watch",
          "httpMethod": "POST"
        },
        "copy": {
          "id": "drive.files.copy",
          "httpMethod": "POST",
          "description": "Creates a copy of the specified file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "flatPath": "files/{fileId}/copy",
          "path": "files/{fileId}/copy"
        },
        "export": {
          "id": "drive.files.export",
          "httpMethod": "GET",
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "flatPath": "files/{fileId}/export",
          "useMediaDownloadService": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/export",
          "supportsMediaDownload": true
        },
        "touch": {
          "path": "files/{fileId}/touch",
          "flatPath": "files/{fileId}/touch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Set the file's updated time to the current server time.",
          "id": "drive.files.touch",
          "httpMethod": "POST"
        },
        "untrash": {
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "id": "drive.files.untrash",
          "httpMethod": "POST",
          "path": "files/{fileId}/untrash",
          "flatPath": "files/{fileId}/untrash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "modifyLabels": {
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "id": "drive.files.modifyLabels",
          "httpMethod": "POST",
          "path": "files/{fileId}/modifyLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/modifyLabels"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files",
          "path": "files",
          "id": "drive.files.list",
          "httpMethod": "GET",
          "description": " Lists the user's files. For more information, see [Search for files and folders](https://developers.google.com/workspace/drive/api/guides/search-files). This method accepts the `q` parameter, which is a search query combining one or more search terms. This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results."
        },
        "generateIds": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/generateIds",
          "path": "files/generateIds",
          "id": "drive.files.generateIds",
          "httpMethod": "GET",
          "description": "Generates a set of file IDs which can be provided in insert or copy requests."
        },
        "listLabels": {
          "path": "files/{fileId}/listLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/listLabels",
          "description": "Lists the labels on a file.",
          "id": "drive.files.listLabels",
          "httpMethod": "GET"
        }
      }
    },
    "comments": {
      "methods": {
        "delete": {
          "description": "Deletes a comment.",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.comments.delete",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "httpMethod": "DELETE"
        },
        "insert": {
          "path": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments",
          "description": "Creates a new comment on the given file.",
          "id": "drive.comments.insert",
          "httpMethod": "POST"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments",
          "path": "files/{fileId}/comments",
          "id": "drive.comments.list",
          "httpMethod": "GET",
          "description": "Lists a file's comments."
        },
        "patch": {
          "description": "Updates an existing comment.",
          "id": "drive.comments.patch",
          "httpMethod": "PATCH",
          "path": "files/{fileId}/comments/{commentId}",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}",
          "description": "Updates an existing comment.",
          "id": "drive.comments.update",
          "httpMethod": "PUT"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}",
          "path": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.get",
          "httpMethod": "GET",
          "description": "Gets a comment by ID."
        }
      }
    },
    "replies": {
      "methods": {
        "delete": {
          "id": "drive.replies.delete",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Deletes a reply."
        },
        "get": {
          "description": "Gets a reply.",
          "id": "drive.replies.get",
          "httpMethod": "GET",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "patch": {
          "id": "drive.replies.patch",
          "httpMethod": "PATCH",
          "description": "Updates an existing reply.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "update": {
          "id": "drive.replies.update",
          "httpMethod": "PUT",
          "description": "Updates an existing reply.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "insert": {
          "id": "drive.replies.insert",
          "httpMethod": "POST",
          "description": "Creates a new reply to the given comment.",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}/replies"
        },
        "list": {
          "id": "drive.replies.list",
          "httpMethod": "GET",
          "description": "Lists all of the replies to a comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "path": "files/{fileId}/comments/{commentId}/replies"
        }
      }
    },
    "changes": {
      "methods": {
        "get": {
          "id": "drive.changes.get",
          "httpMethod": "GET",
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "flatPath": "changes/{changeId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "changes/{changeId}"
        },
        "getStartPageToken": {
          "path": "changes/startPageToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes/startPageToken",
          "description": "Gets the starting pageToken for listing future changes.",
          "id": "drive.changes.getStartPageToken",
          "httpMethod": "GET"
        },
        "list": {
          "description": "Lists the changes for a user or shared drive.",
          "id": "drive.changes.list",
          "httpMethod": "GET",
          "supportsSubscription": true,
          "path": "changes",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes"
        },
        "watch": {
          "description": "Subscribe to changes for a user.",
          "id": "drive.changes.watch",
          "httpMethod": "POST",
          "supportsSubscription": true,
          "path": "changes/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes/watch"
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "description": "Gets the information about the current user along with Drive API settings",
          "id": "drive.about.get",
          "httpMethod": "GET",
          "path": "about",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "about"
        }
      }
    },
    "apps": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "apps/{appId}",
          "path": "apps/{appId}",
          "id": "drive.apps.get",
          "httpMethod": "GET",
          "description": "Gets a specific app."
        },
        "list": {
          "id": "drive.apps.list",
          "httpMethod": "GET",
          "description": "Lists a user's installed apps.",
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ],
          "flatPath": "apps",
          "path": "apps"
        }
      }
    },
    "properties": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "path": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.get",
          "httpMethod": "GET",
          "description": "Gets a property by its key."
        },
        "insert": {
          "id": "drive.properties.insert",
          "httpMethod": "POST",
          "description": "Adds a property to a file, or updates it if it already exists.",
          "flatPath": "files/{fileId}/properties",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "path": "files/{fileId}/properties"
        },
        "list": {
          "id": "drive.properties.list",
          "httpMethod": "GET",
          "description": "Lists a file's properties.",
          "flatPath": "files/{fileId}/properties",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/properties"
        },
        "patch": {
          "description": "Updates a property.",
          "id": "drive.properties.patch",
          "httpMethod": "PATCH",
          "path": "files/{fileId}/properties/{propertyKey}",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "update": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "description": "Updates a property.",
          "id": "drive.properties.update",
          "httpMethod": "PUT"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.properties.delete",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "DELETE",
          "description": "Deletes a property.",
          "path": "files/{fileId}/properties/{propertyKey}"
        }
      }
    },
    "children": {
      "methods": {
        "delete": {
          "description": "Removes a child from a folder.",
          "path": "files/{folderId}/children/{childId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.children.delete",
          "flatPath": "files/{folderId}/children/{childId}",
          "httpMethod": "DELETE"
        },
        "insert": {
          "id": "drive.children.insert",
          "httpMethod": "POST",
          "description": "Inserts a file into a folder.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{folderId}/children",
          "path": "files/{folderId}/children"
        },
        "list": {
          "flatPath": "files/{folderId}/children",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{folderId}/children",
          "id": "drive.children.list",
          "httpMethod": "GET",
          "description": "Lists a folder's children."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{folderId}/children/{childId}",
          "path": "files/{folderId}/children/{childId}",
          "id": "drive.children.get",
          "httpMethod": "GET",
          "description": "Gets a specific child reference."
        }
      }
    },
    "revisions": {
      "methods": {
        "patch": {
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates a revision.",
          "id": "drive.revisions.patch",
          "httpMethod": "PATCH"
        },
        "update": {
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.update",
          "httpMethod": "PUT",
          "description": "Updates a revision."
        },
        "list": {
          "path": "files/{fileId}/revisions",
          "flatPath": "files/{fileId}/revisions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Lists a file's revisions. **Important:** The list of revisions returned by this method might be incomplete for files with a large revision history, including frequently edited Google Docs, Sheets, and Slides. Older revisions might be omitted from the response, meaning the first revision returned may not be the oldest existing revision. The revision history visible in the Workspace editor user interface might be more complete than the list returned by the API.",
          "id": "drive.revisions.list",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "path": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.get",
          "httpMethod": "GET",
          "description": "Gets a specific revision."
        },
        "delete": {
          "path": "files/{fileId}/revisions/{revisionId}",
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
          "id": "drive.revisions.delete",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "permissions": {
      "methods": {
        "insert": {
          "id": "drive.permissions.insert",
          "httpMethod": "POST",
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/permissions",
          "path": "files/{fileId}/permissions"
        },
        "list": {
          "id": "drive.permissions.list",
          "httpMethod": "GET",
          "description": "Lists a file's or shared drive's permissions.",
          "flatPath": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/permissions"
        },
        "patch": {
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "id": "drive.permissions.patch",
          "httpMethod": "PATCH",
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "id": "drive.permissions.update",
          "httpMethod": "PUT",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/permissions/{permissionId}"
        },
        "get": {
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.get",
          "httpMethod": "GET",
          "description": "Gets a permission by ID."
        },
        "getIdForEmail": {
          "flatPath": "permissionIds/{email}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "permissionIds/{email}",
          "id": "drive.permissions.getIdForEmail",
          "httpMethod": "GET",
          "description": "Returns the permission ID for an email address."
        },
        "delete": {
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.delete",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "DELETE"
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "path": "channels/stop",
          "flatPath": "channels/stop",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Stops watching resources through this channel.",
          "id": "drive.channels.stop",
          "httpMethod": "POST"
        }
      }
    },
    "teamdrives": {
      "methods": {
        "get": {
          "description": "Deprecated: Use `drives.get` instead.",
          "id": "drive.teamdrives.get",
          "httpMethod": "GET",
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "teamdrives/{teamDriveId}"
        },
        "update": {
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.update` instead.",
          "id": "drive.teamdrives.update",
          "httpMethod": "PUT"
        },
        "insert": {
          "description": "Deprecated: Use `drives.insert` instead.",
          "id": "drive.teamdrives.insert",
          "httpMethod": "POST",
          "path": "teamdrives",
          "flatPath": "teamdrives",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "description": "Deprecated: Use `drives.list` instead.",
          "id": "drive.teamdrives.list",
          "httpMethod": "GET",
          "path": "teamdrives",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "teamdrives"
        },
        "delete": {
          "id": "drive.teamdrives.delete",
          "flatPath": "teamdrives/{teamDriveId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.delete` instead."
        }
      }
    },
    "drives": {
      "methods": {
        "hide": {
          "path": "drives/{driveId}/hide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives/{driveId}/hide",
          "description": "Hides a shared drive from the default view.",
          "id": "drive.drives.hide",
          "httpMethod": "POST"
        },
        "get": {
          "path": "drives/{driveId}",
          "flatPath": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a shared drive's metadata by ID.",
          "id": "drive.drives.get",
          "httpMethod": "GET"
        },
        "update": {
          "description": "Updates the metadata for a shared drive.",
          "id": "drive.drives.update",
          "httpMethod": "PUT",
          "path": "drives/{driveId}",
          "flatPath": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "insert": {
          "description": "Creates a new shared drive.",
          "id": "drive.drives.insert",
          "httpMethod": "POST",
          "path": "drives",
          "flatPath": "drives",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "path": "drives",
          "flatPath": "drives",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](https://developers.google.com/workspace/drive/api/guides/search-shareddrives) guide.",
          "id": "drive.drives.list",
          "httpMethod": "GET"
        },
        "delete": {
          "id": "drive.drives.delete",
          "flatPath": "drives/{driveId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "drives/{driveId}",
          "description": "Permanently deletes a shared drive for which the user is an `organizer`. The shared drive cannot contain any untrashed items."
        },
        "unhide": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives/{driveId}/unhide",
          "path": "drives/{driveId}/unhide",
          "id": "drive.drives.unhide",
          "httpMethod": "POST",
          "description": "Restores a shared drive to the default view."
        }
      }
    },
    "parents": {
      "methods": {
        "get": {
          "description": "Gets a specific parent reference.",
          "id": "drive.parents.get",
          "httpMethod": "GET",
          "path": "files/{fileId}/parents/{parentId}",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "insert": {
          "path": "files/{fileId}/parents",
          "flatPath": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Adds a parent folder for a file.",
          "id": "drive.parents.insert",
          "httpMethod": "POST"
        },
        "list": {
          "id": "drive.parents.list",
          "httpMethod": "GET",
          "description": "Lists a file's parents.",
          "flatPath": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "path": "files/{fileId}/parents"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.parents.delete",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "httpMethod": "DELETE",
          "description": "Removes a parent from a file.",
          "path": "files/{fileId}/parents/{parentId}"
        }
      }
    }
  },
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "rootUrl": "https://www.googleapis.com/",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "basePath": "/drive/v2/",
  "ownerName": "Google",
  "name": "drive",
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "servicePath": "drive/v2/"
}