{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.meet.readonly": {
          "description": "See and download your Google Drive files that were created or edited by Google Meet."
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        }
      }
    }
  },
  "basePath": "/drive/v2/",
  "batchPath": "batch/drive/v2",
  "revision": "20260311",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/workspace/drive/",
  "name": "drive",
  "ownerName": "Google",
  "protocol": "rest",
  "servicePath": "drive/v2/",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "version": "v2",
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "id": "drive:v2",
  "kind": "discovery#restDescription",
  "title": "Google Drive API",
  "baseUrl": "https://www.googleapis.com/drive/v2/",
  "resources": {
    "files": {
      "methods": {
        "patch": {
          "id": "drive.files.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "flatPath": "files/{fileId}",
          "httpMethod": "PATCH",
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
          "path": "files/{fileId}"
        },
        "export": {
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "path": "files/{fileId}/export",
          "useMediaDownloadService": true,
          "httpMethod": "GET",
          "supportsMediaDownload": true,
          "id": "drive.files.export",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/export"
        },
        "modifyLabels": {
          "httpMethod": "POST",
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "path": "files/{fileId}/modifyLabels",
          "flatPath": "files/{fileId}/modifyLabels",
          "id": "drive.files.modifyLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "touch": {
          "httpMethod": "POST",
          "path": "files/{fileId}/touch",
          "description": "Set the file's updated time to the current server time.",
          "flatPath": "files/{fileId}/touch",
          "id": "drive.files.touch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "listLabels": {
          "path": "files/{fileId}/listLabels",
          "description": "Lists the labels on a file.",
          "httpMethod": "GET",
          "flatPath": "files/{fileId}/listLabels",
          "id": "drive.files.listLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "trash": {
          "flatPath": "files/{fileId}/trash",
          "id": "drive.files.trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "description": "Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "path": "files/{fileId}/trash"
        },
        "copy": {
          "id": "drive.files.copy",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "flatPath": "files/{fileId}/copy",
          "httpMethod": "POST",
          "description": "Creates a copy of the specified file.",
          "path": "files/{fileId}/copy"
        },
        "list": {
          "id": "drive.files.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files",
          "description": " Lists the user's files. For more information, see [Search for files and folders](/workspace/drive/api/guides/search-files). This method accepts the `q` parameter, which is a search query combining one or more search terms. This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results.",
          "path": "files",
          "httpMethod": "GET"
        },
        "get": {
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/workspace/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](/workspace/drive/api/guides/manage-downloads).",
          "path": "files/{fileId}",
          "useMediaDownloadService": true,
          "httpMethod": "GET",
          "supportsMediaDownload": true,
          "id": "drive.files.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}",
          "supportsSubscription": true
        },
        "watch": {
          "description": "Subscribes to changes to a file.",
          "path": "files/{fileId}/watch",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/watch",
          "supportsSubscription": true,
          "id": "drive.files.watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "insert": {
          "httpMethod": "POST",
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](/workspace/drive/api/guides/manage-uploads). Apps creating shortc[...]",
          "path": "files",
          "flatPath": "files",
          "id": "drive.files.insert",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "emptyTrash": {
          "flatPath": "files/trash",
          "description": "Permanently deletes all of the user's trashed files.",
          "path": "files/trash",
          "id": "drive.files.emptyTrash",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "DELETE"
        },
        "generateIds": {
          "flatPath": "files/generateIds",
          "id": "drive.files.generateIds",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "GET",
          "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
          "path": "files/generateIds"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "drive.files.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}",
          "flatPath": "files/{fileId}",
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive, the user must be an `organizer` on the parent folder. If the target is a folder, all descendants owned by the user are also deleted."
        },
        "untrash": {
          "httpMethod": "POST",
          "path": "files/{fileId}/untrash",
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "id": "drive.files.untrash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/untrash"
        },
        "update": {
          "id": "drive.files.update",
          "supportsMediaUpload": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "flatPath": "files/{fileId}",
          "path": "files/{fileId}",
          "description": " Updates a file's metadata, content, or both. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:* `*/*` (Specify a valid MIME type, rather than the[...]",
          "httpMethod": "PUT"
        }
      }
    },
    "replies": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Deletes a reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a reply.",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Updates an existing reply.",
          "id": "drive.replies.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "insert": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "id": "drive.replies.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Creates a new reply to the given comment.",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "httpMethod": "POST"
        },
        "list": {
          "id": "drive.replies.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "description": "Lists all of the replies to a comment.",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "httpMethod": "GET"
        },
        "update": {
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Updates an existing reply.",
          "httpMethod": "PUT",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "id": "drive.replies.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "teamdrives": {
      "methods": {
        "insert": {
          "flatPath": "teamdrives",
          "id": "drive.teamdrives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "description": "Deprecated: Use `drives.insert` instead.",
          "path": "teamdrives",
          "httpMethod": "POST"
        },
        "list": {
          "flatPath": "teamdrives",
          "id": "drive.teamdrives.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "path": "teamdrives",
          "description": "Deprecated: Use `drives.list` instead."
        },
        "update": {
          "httpMethod": "PUT",
          "path": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.update` instead.",
          "flatPath": "teamdrives/{teamDriveId}",
          "id": "drive.teamdrives.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "drive.teamdrives.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "path": "teamdrives/{teamDriveId}",
          "flatPath": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.delete` instead."
        },
        "get": {
          "id": "drive.teamdrives.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "teamdrives/{teamDriveId}",
          "httpMethod": "GET",
          "description": "Deprecated: Use `drives.get` instead.",
          "path": "teamdrives/{teamDriveId}"
        }
      }
    },
    "children": {
      "methods": {
        "insert": {
          "description": "Inserts a file into a folder.",
          "path": "files/{folderId}/children",
          "httpMethod": "POST",
          "id": "drive.children.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{folderId}/children"
        },
        "list": {
          "description": "Lists a folder's children.",
          "path": "files/{folderId}/children",
          "httpMethod": "GET",
          "flatPath": "files/{folderId}/children",
          "id": "drive.children.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "drive.children.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{folderId}/children/{childId}",
          "flatPath": "files/{folderId}/children/{childId}",
          "description": "Removes a child from a folder."
        },
        "get": {
          "flatPath": "files/{folderId}/children/{childId}",
          "id": "drive.children.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "path": "files/{folderId}/children/{childId}",
          "description": "Gets a specific child reference."
        }
      }
    },
    "drives": {
      "methods": {
        "insert": {
          "description": "Creates a new shared drive.",
          "path": "drives",
          "httpMethod": "POST",
          "flatPath": "drives",
          "id": "drive.drives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "id": "drive.drives.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "drives",
          "httpMethod": "GET",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](/workspace/drive/api/guides/search-shareddrives) guide.",
          "path": "drives"
        },
        "unhide": {
          "flatPath": "drives/{driveId}/unhide",
          "id": "drive.drives.unhide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "POST",
          "description": "Restores a shared drive to the default view.",
          "path": "drives/{driveId}/unhide"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates the metadata for a shared drive.",
          "path": "drives/{driveId}",
          "flatPath": "drives/{driveId}",
          "id": "drive.drives.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "drive.drives.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives/{driveId}",
          "description": "Permanently deletes a shared drive for which the user is an `organizer`. The shared drive cannot contain any untrashed items.",
          "path": "drives/{driveId}"
        },
        "get": {
          "id": "drive.drives.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "drives/{driveId}",
          "description": "Gets a shared drive's metadata by ID.",
          "path": "drives/{driveId}",
          "httpMethod": "GET"
        },
        "hide": {
          "httpMethod": "POST",
          "description": "Hides a shared drive from the default view.",
          "path": "drives/{driveId}/hide",
          "id": "drive.drives.hide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives/{driveId}/hide"
        }
      }
    },
    "properties": {
      "methods": {
        "insert": {
          "id": "drive.properties.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "flatPath": "files/{fileId}/properties",
          "httpMethod": "POST",
          "description": "Adds a property to a file, or updates it if it already exists.",
          "path": "files/{fileId}/properties"
        },
        "list": {
          "id": "drive.properties.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/properties",
          "path": "files/{fileId}/properties",
          "description": "Lists a file's properties.",
          "httpMethod": "GET"
        },
        "update": {
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "httpMethod": "PUT",
          "description": "Updates a property.",
          "path": "files/{fileId}/properties/{propertyKey}"
        },
        "delete": {
          "id": "drive.properties.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "path": "files/{fileId}/properties/{propertyKey}",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "description": "Deletes a property.",
          "httpMethod": "DELETE"
        },
        "get": {
          "id": "drive.properties.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "GET",
          "path": "files/{fileId}/properties/{propertyKey}",
          "description": "Gets a property by its key."
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "files/{fileId}/properties/{propertyKey}",
          "description": "Updates a property.",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "id": "drive.properties.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        }
      }
    },
    "apps": {
      "methods": {
        "list": {
          "id": "drive.apps.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ],
          "flatPath": "apps",
          "description": "Lists a user's installed apps.",
          "path": "apps",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a specific app.",
          "path": "apps/{appId}",
          "id": "drive.apps.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "apps/{appId}"
        }
      }
    },
    "comments": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "id": "drive.comments.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}",
          "description": "Deletes a comment.",
          "path": "files/{fileId}/comments/{commentId}"
        },
        "get": {
          "id": "drive.comments.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}",
          "httpMethod": "GET",
          "description": "Gets a comment by ID.",
          "path": "files/{fileId}/comments/{commentId}"
        },
        "patch": {
          "path": "files/{fileId}/comments/{commentId}",
          "description": "Updates an existing comment.",
          "httpMethod": "PATCH",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "insert": {
          "flatPath": "files/{fileId}/comments",
          "id": "drive.comments.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments",
          "description": "Creates a new comment on the given file.",
          "httpMethod": "POST"
        },
        "list": {
          "path": "files/{fileId}/comments",
          "description": "Lists a file's comments.",
          "httpMethod": "GET",
          "id": "drive.comments.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/comments"
        },
        "update": {
          "flatPath": "files/{fileId}/comments/{commentId}",
          "id": "drive.comments.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "path": "files/{fileId}/comments/{commentId}",
          "description": "Updates an existing comment.",
          "httpMethod": "PUT"
        }
      }
    },
    "parents": {
      "methods": {
        "insert": {
          "description": "Adds a parent folder for a file.",
          "path": "files/{fileId}/parents",
          "httpMethod": "POST",
          "flatPath": "files/{fileId}/parents",
          "id": "drive.parents.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "id": "drive.parents.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/parents",
          "path": "files/{fileId}/parents",
          "description": "Lists a file's parents.",
          "httpMethod": "GET"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "drive.parents.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/parents/{parentId}",
          "description": "Removes a parent from a file.",
          "path": "files/{fileId}/parents/{parentId}"
        },
        "get": {
          "description": "Gets a specific parent reference.",
          "path": "files/{fileId}/parents/{parentId}",
          "httpMethod": "GET",
          "id": "drive.parents.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/parents/{parentId}"
        }
      }
    },
    "permissions": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "path": "files/{fileId}/permissions/{permissionId}",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "id": "drive.permissions.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "httpMethod": "GET",
          "description": "Gets a permission by ID.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/permissions/{permissionId}"
        },
        "patch": {
          "path": "files/{fileId}/permissions/{permissionId}",
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "httpMethod": "PATCH",
          "id": "drive.permissions.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/permissions/{permissionId}"
        },
        "getIdForEmail": {
          "description": "Returns the permission ID for an email address.",
          "path": "permissionIds/{email}",
          "httpMethod": "GET",
          "id": "drive.permissions.getIdForEmail",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "permissionIds/{email}"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions",
          "id": "drive.permissions.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/permissions"
        },
        "list": {
          "path": "files/{fileId}/permissions",
          "description": "Lists a file's or shared drive's permissions.",
          "httpMethod": "GET",
          "id": "drive.permissions.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/permissions"
        },
        "update": {
          "id": "drive.permissions.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "path": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "PUT"
        }
      }
    },
    "changes": {
      "methods": {
        "get": {
          "id": "drive.changes.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes/{changeId}",
          "httpMethod": "GET",
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "path": "changes/{changeId}"
        },
        "getStartPageToken": {
          "id": "drive.changes.getStartPageToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes/startPageToken",
          "path": "changes/startPageToken",
          "description": "Gets the starting pageToken for listing future changes.",
          "httpMethod": "GET"
        },
        "list": {
          "id": "drive.changes.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes",
          "supportsSubscription": true,
          "httpMethod": "GET",
          "description": "Lists the changes for a user or shared drive.",
          "path": "changes"
        },
        "watch": {
          "httpMethod": "POST",
          "description": "Subscribe to changes for a user.",
          "path": "changes/watch",
          "id": "drive.changes.watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "changes/watch",
          "supportsSubscription": true
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "about",
          "description": "Gets the information about the current user along with Drive API settings",
          "flatPath": "about",
          "id": "drive.about.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "id": "drive.channels.stop",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "channels/stop",
          "httpMethod": "POST",
          "path": "channels/stop",
          "description": "Stops watching resources through this channel."
        }
      }
    },
    "revisions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Lists a file's revisions. **Important:** The list of revisions returned by this method might be incomplete for files with a large revision history, including frequently edited Google Docs, Sheets, and Slides. Older revisions might be omitted from the response, meaning the first revision returned may not be the oldest existing revision. The revision history visible in the Workspace editor user interface might be more complete than the list returned by the API.",
          "path": "files/{fileId}/revisions",
          "id": "drive.revisions.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/revisions"
        },
        "update": {
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Updates a revision.",
          "path": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "PUT"
        },
        "delete": {
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
          "id": "drive.revisions.delete",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "DELETE"
        },
        "get": {
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a specific revision.",
          "path": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "GET"
        },
        "patch": {
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "PATCH",
          "path": "files/{fileId}/revisions/{revisionId}",
          "description": "Updates a revision."
        }
      }
    }
  },
  "rootUrl": "https://www.googleapis.com/"
}