{
  "documentationLink": "https://developers.google.com/workspace/drive/",
  "version": "v2",
  "id": "drive:v2",
  "rootUrl": "https://www.googleapis.com/",
  "ownerDomain": "google.com",
  "batchPath": "batch/drive/v2",
  "ownerName": "Google",
  "basePath": "/drive/v2/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/drive.meet.readonly": {
          "description": "See and download your Google Drive files that were created or edited by Google Meet."
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "See information about your Google Drive files"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "description": "The Google Drive API allows clients to access resources from Google Drive.",
  "mtlsRootUrl": "https://www.mtls.googleapis.com/",
  "servicePath": "drive/v2/",
  "resources": {
    "channels": {
      "methods": {
        "stop": {
          "httpMethod": "POST",
          "path": "channels/stop",
          "description": "Stops watching resources through this channel.",
          "flatPath": "channels/stop",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.channels.stop"
        }
      }
    },
    "properties": {
      "methods": {
        "insert": {
          "description": "Adds a property to a file, or updates it if it already exists.",
          "flatPath": "files/{fileId}/properties",
          "id": "drive.properties.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "httpMethod": "POST",
          "path": "files/{fileId}/properties"
        },
        "update": {
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "description": "Updates a property.",
          "id": "drive.properties.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "httpMethod": "PUT",
          "path": "files/{fileId}/properties/{propertyKey}"
        },
        "patch": {
          "id": "drive.properties.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Updates a property.",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "path": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "PATCH"
        },
        "get": {
          "path": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.properties.get",
          "flatPath": "files/{fileId}/properties/{propertyKey}",
          "description": "Gets a property by its key."
        },
        "list": {
          "description": "Lists a file's properties.",
          "flatPath": "files/{fileId}/properties",
          "id": "drive.properties.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "path": "files/{fileId}/properties"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.properties.delete",
          "path": "files/{fileId}/properties/{propertyKey}",
          "httpMethod": "DELETE",
          "description": "Deletes a property.",
          "flatPath": "files/{fileId}/properties/{propertyKey}"
        }
      }
    },
    "parents": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "description": "Removes a parent from a file.",
          "flatPath": "files/{fileId}/parents/{parentId}",
          "id": "drive.parents.delete",
          "path": "files/{fileId}/parents/{parentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "path": "files/{fileId}/parents/{parentId}",
          "httpMethod": "GET",
          "id": "drive.parents.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a specific parent reference.",
          "flatPath": "files/{fileId}/parents/{parentId}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "files/{fileId}/parents",
          "flatPath": "files/{fileId}/parents",
          "description": "Adds a parent folder for a file.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.parents.insert"
        },
        "list": {
          "httpMethod": "GET",
          "path": "files/{fileId}/parents",
          "description": "Lists a file's parents.",
          "flatPath": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.parents.list"
        }
      }
    },
    "comments": {
      "methods": {
        "list": {
          "flatPath": "files/{fileId}/comments",
          "description": "Lists a file's comments.",
          "id": "drive.comments.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "path": "files/{fileId}/comments"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.comments.delete",
          "path": "files/{fileId}/comments/{commentId}",
          "httpMethod": "DELETE",
          "description": "Deletes a comment.",
          "flatPath": "files/{fileId}/comments/{commentId}"
        },
        "patch": {
          "path": "files/{fileId}/comments/{commentId}",
          "httpMethod": "PATCH",
          "id": "drive.comments.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}",
          "description": "Updates an existing comment."
        },
        "insert": {
          "path": "files/{fileId}/comments",
          "httpMethod": "POST",
          "id": "drive.comments.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Creates a new comment on the given file.",
          "flatPath": "files/{fileId}/comments"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "files/{fileId}/comments/{commentId}",
          "flatPath": "files/{fileId}/comments/{commentId}",
          "description": "Updates an existing comment.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.comments.update"
        },
        "get": {
          "path": "files/{fileId}/comments/{commentId}",
          "httpMethod": "GET",
          "id": "drive.comments.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a comment by ID.",
          "flatPath": "files/{fileId}/comments/{commentId}"
        }
      }
    },
    "apps": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.apps.get",
          "description": "Gets a specific app.",
          "flatPath": "apps/{appId}",
          "path": "apps/{appId}",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "path": "apps",
          "description": "Lists a user's installed apps.",
          "flatPath": "apps",
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ],
          "id": "drive.apps.list"
        }
      }
    },
    "files": {
      "methods": {
        "list": {
          "path": "files",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.list",
          "flatPath": "files",
          "description": " Lists the user's files. For more information, see [Search for files and folders](/workspace/drive/api/guides/search-files). This method accepts the `q` parameter, which is a search query combining one or more search terms. This method returns *all* files by default, including trashed files. If you don't want trashed files to appear in the list, use the `trashed=false` query parameter to remove trashed files from the results."
        },
        "trash": {
          "flatPath": "files/{fileId}/trash",
          "description": "Moves a file to the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.trash",
          "httpMethod": "POST",
          "path": "files/{fileId}/trash"
        },
        "update": {
          "httpMethod": "PUT",
          "path": "files/{fileId}",
          "supportsMediaUpload": true,
          "description": " Updates a file's metadata, content, or both. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might be changed automatically, such as `modifiedDate`. This method supports patch semantics. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:* `*/*` (Specify a valid MIME type, rather than the[...]",
          "flatPath": "files/{fileId}",
          "id": "drive.files.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "files/{fileId}",
          "flatPath": "files/{fileId}",
          "description": "Updates a file's metadata and/or content. When calling this method, only populate fields in the request that you want to modify. When updating fields, some fields might change automatically, such as modifiedDate. This method supports patch semantics.",
          "id": "drive.files.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ]
        },
        "watch": {
          "httpMethod": "POST",
          "path": "files/{fileId}/watch",
          "supportsSubscription": true,
          "description": "Subscribes to changes to a file.",
          "flatPath": "files/{fileId}/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.watch"
        },
        "modifyLabels": {
          "id": "drive.files.modifyLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "description": "Modifies the set of labels applied to a file. Returns a list of the labels that were added or modified.",
          "flatPath": "files/{fileId}/modifyLabels",
          "path": "files/{fileId}/modifyLabels",
          "httpMethod": "POST"
        },
        "listLabels": {
          "path": "files/{fileId}/listLabels",
          "httpMethod": "GET",
          "id": "drive.files.listLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "files/{fileId}/listLabels",
          "description": "Lists the labels on a file."
        },
        "untrash": {
          "path": "files/{fileId}/untrash",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.untrash",
          "flatPath": "files/{fileId}/untrash",
          "description": "Restores a file from the trash. The currently authenticated user must own the file or be at least a `fileOrganizer` on the parent for shared drive files."
        },
        "delete": {
          "id": "drive.files.delete",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}",
          "httpMethod": "DELETE",
          "description": "Permanently deletes a file owned by the user without moving it to the trash. If the file belongs to a shared drive, the user must be an `organizer` on the parent folder. If the target is a folder, all descendants owned by the user are also deleted."
        },
        "generateIds": {
          "path": "files/generateIds",
          "httpMethod": "GET",
          "id": "drive.files.generateIds",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/generateIds",
          "description": "Generates a set of file IDs which can be provided in insert or copy requests."
        },
        "insert": {
          "supportsMediaUpload": true,
          "description": " Inserts a new file. This method supports an */upload* URI and accepts uploaded media with the following characteristics: - *Maximum file size:* 5,120 GB - *Accepted Media MIME types:*`*/*` Note: Specify a valid MIME type, rather than the literal `*/*` value. The literal `*/*` is only used to indicate that any valid MIME type can be uploaded. For more information on uploading files, see [Upload file data](/workspace/drive/api/guides/manage-uploads). Apps creating shortc[...]",
          "flatPath": "files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.files.insert",
          "httpMethod": "POST",
          "path": "files"
        },
        "copy": {
          "path": "files/{fileId}/copy",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ],
          "id": "drive.files.copy",
          "description": "Creates a copy of the specified file.",
          "flatPath": "files/{fileId}/copy"
        },
        "emptyTrash": {
          "httpMethod": "DELETE",
          "description": "Permanently deletes all of the user's trashed files.",
          "flatPath": "files/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.files.emptyTrash",
          "path": "files/trash"
        },
        "export": {
          "httpMethod": "GET",
          "supportsMediaDownload": true,
          "path": "files/{fileId}/export",
          "flatPath": "files/{fileId}/export",
          "description": "Exports a Google Workspace document to the requested MIME type and returns exported byte content. Note that the exported content is limited to 10MB.",
          "useMediaDownloadService": true,
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.export"
        },
        "touch": {
          "description": "Set the file's updated time to the current server time.",
          "flatPath": "files/{fileId}/touch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ],
          "id": "drive.files.touch",
          "httpMethod": "POST",
          "path": "files/{fileId}/touch"
        },
        "get": {
          "httpMethod": "GET",
          "supportsMediaDownload": true,
          "path": "files/{fileId}",
          "supportsSubscription": true,
          "description": " Gets a file's metadata or content by ID. If you provide the URL parameter `alt=media`, then the response includes the file contents in the response body. Downloading content with `alt=media` only works if the file is stored in Drive. To download Google Docs, Sheets, and Slides use [`files.export`](/workspace/drive/api/reference/rest/v2/files/export) instead. For more information, see [Download & export files](/workspace/drive/api/guides/manage-downloads).",
          "useMediaDownloadService": true,
          "flatPath": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.files.get"
        }
      }
    },
    "changes": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "changes/{changeId}",
          "description": "Deprecated: Use `changes.getStartPageToken` and `changes.list` to retrieve recent changes.",
          "flatPath": "changes/{changeId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.get"
        },
        "getStartPageToken": {
          "path": "changes/startPageToken",
          "httpMethod": "GET",
          "id": "drive.changes.getStartPageToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets the starting pageToken for listing future changes.",
          "flatPath": "changes/startPageToken"
        },
        "watch": {
          "httpMethod": "POST",
          "path": "changes/watch",
          "flatPath": "changes/watch",
          "supportsSubscription": true,
          "description": "Subscribe to changes for a user.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.changes.watch"
        },
        "list": {
          "flatPath": "changes",
          "supportsSubscription": true,
          "description": "Lists the changes for a user or shared drive.",
          "id": "drive.changes.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "path": "changes"
        }
      }
    },
    "drives": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.drives.list",
          "flatPath": "drives",
          "description": " Lists the user's shared drives. This method accepts the `q` parameter, which is a search query combining one or more search terms. For more information, see the [Search for shared drives](/workspace/drive/api/guides/search-shareddrives) guide.",
          "path": "drives",
          "httpMethod": "GET"
        },
        "unhide": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.unhide",
          "description": "Restores a shared drive to the default view.",
          "flatPath": "drives/{driveId}/unhide",
          "path": "drives/{driveId}/unhide",
          "httpMethod": "POST"
        },
        "delete": {
          "id": "drive.drives.delete",
          "path": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "httpMethod": "DELETE",
          "description": "Permanently deletes a shared drive for which the user is an `organizer`. The shared drive cannot contain any untrashed items.",
          "flatPath": "drives/{driveId}"
        },
        "hide": {
          "id": "drive.drives.hide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "drives/{driveId}/hide",
          "description": "Hides a shared drive from the default view.",
          "path": "drives/{driveId}/hide",
          "httpMethod": "POST"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.insert",
          "description": "Creates a new shared drive.",
          "flatPath": "drives",
          "path": "drives",
          "httpMethod": "POST"
        },
        "update": {
          "description": "Updates the metadata for a shared drive.",
          "flatPath": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.drives.update",
          "httpMethod": "PUT",
          "path": "drives/{driveId}"
        },
        "get": {
          "flatPath": "drives/{driveId}",
          "description": "Gets a shared drive's metadata by ID.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.drives.get",
          "httpMethod": "GET",
          "path": "drives/{driveId}"
        }
      }
    },
    "replies": {
      "methods": {
        "get": {
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "GET",
          "id": "drive.replies.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Gets a reply.",
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "patch": {
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "PATCH",
          "id": "drive.replies.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Updates an existing reply."
        },
        "insert": {
          "httpMethod": "POST",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "description": "Creates a new reply to the given comment.",
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "id": "drive.replies.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "description": "Updates an existing reply.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.replies.update",
          "httpMethod": "PUT",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}"
        },
        "delete": {
          "id": "drive.replies.delete",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "httpMethod": "DELETE",
          "description": "Deletes a reply."
        },
        "list": {
          "flatPath": "files/{fileId}/comments/{commentId}/replies",
          "description": "Lists all of the replies to a comment.",
          "id": "drive.replies.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "path": "files/{fileId}/comments/{commentId}/replies"
        }
      }
    },
    "permissions": {
      "methods": {
        "insert": {
          "description": "Inserts a permission for a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "flatPath": "files/{fileId}/permissions",
          "id": "drive.permissions.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "httpMethod": "POST",
          "path": "files/{fileId}/permissions"
        },
        "update": {
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "description": "Updates a permission. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.update",
          "httpMethod": "PUT",
          "path": "files/{fileId}/permissions/{permissionId}"
        },
        "patch": {
          "description": "Updates a permission using patch semantics. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.permissions.patch",
          "httpMethod": "PATCH",
          "path": "files/{fileId}/permissions/{permissionId}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.permissions.get",
          "description": "Gets a permission by ID.",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "path": "files/{fileId}/permissions/{permissionId}",
          "httpMethod": "GET"
        },
        "getIdForEmail": {
          "id": "drive.permissions.getIdForEmail",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "description": "Returns the permission ID for an email address.",
          "flatPath": "permissionIds/{email}",
          "path": "permissionIds/{email}",
          "httpMethod": "GET"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.permissions.list",
          "flatPath": "files/{fileId}/permissions",
          "description": "Lists a file's or shared drive's permissions.",
          "path": "files/{fileId}/permissions",
          "httpMethod": "GET"
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes a permission from a file or shared drive. **Warning:** Concurrent permissions operations on the same file are not supported; only the last update is applied.",
          "flatPath": "files/{fileId}/permissions/{permissionId}",
          "id": "drive.permissions.delete",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "about": {
      "methods": {
        "get": {
          "path": "about",
          "httpMethod": "GET",
          "id": "drive.about.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "about",
          "description": "Gets the information about the current user along with Drive API settings"
        }
      }
    },
    "children": {
      "methods": {
        "insert": {
          "path": "files/{folderId}/children",
          "httpMethod": "POST",
          "id": "drive.children.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "description": "Inserts a file into a folder.",
          "flatPath": "files/{folderId}/children"
        },
        "list": {
          "flatPath": "files/{folderId}/children",
          "description": "Lists a folder's children.",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.children.list",
          "httpMethod": "GET",
          "path": "files/{folderId}/children"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "id": "drive.children.delete",
          "path": "files/{folderId}/children/{childId}",
          "flatPath": "files/{folderId}/children/{childId}",
          "httpMethod": "DELETE",
          "description": "Removes a child from a folder."
        },
        "get": {
          "description": "Gets a specific child reference.",
          "flatPath": "files/{folderId}/children/{childId}",
          "id": "drive.children.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "httpMethod": "GET",
          "path": "files/{folderId}/children/{childId}"
        }
      }
    },
    "revisions": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "files/{fileId}/revisions/{revisionId}",
          "description": "Gets a specific revision.",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.revisions.get"
        },
        "update": {
          "id": "drive.revisions.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "description": "Updates a revision.",
          "path": "files/{fileId}/revisions/{revisionId}",
          "httpMethod": "PUT"
        },
        "patch": {
          "httpMethod": "PATCH",
          "path": "files/{fileId}/revisions/{revisionId}",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "description": "Updates a revision.",
          "id": "drive.revisions.patch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Permanently deletes a file version. You can only delete revisions for files with binary content, like images or videos. Revisions for other files, like Google Docs or Sheets, and the last remaining file version can't be deleted.",
          "flatPath": "files/{fileId}/revisions/{revisionId}",
          "id": "drive.revisions.delete",
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "path": "files/{fileId}/revisions",
          "description": "Lists a file's revisions. **Important:** The list of revisions returned by this method might be incomplete for files with a large revision history, including frequently edited Google Docs, Sheets, and Slides. Older revisions might be omitted from the response, meaning the first revision returned may not be the oldest existing revision. The revision history visible in the Workspace editor user interface might be more complete than the list returned by the API.",
          "flatPath": "files/{fileId}/revisions",
          "id": "drive.revisions.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.meet.readonly",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "teamdrives": {
      "methods": {
        "delete": {
          "flatPath": "teamdrives/{teamDriveId}",
          "httpMethod": "DELETE",
          "description": "Deprecated: Use `drives.delete` instead.",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "id": "drive.teamdrives.delete",
          "path": "teamdrives/{teamDriveId}"
        },
        "list": {
          "path": "teamdrives",
          "httpMethod": "GET",
          "id": "drive.teamdrives.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "flatPath": "teamdrives",
          "description": "Deprecated: Use `drives.list` instead."
        },
        "get": {
          "path": "teamdrives/{teamDriveId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "id": "drive.teamdrives.get",
          "description": "Deprecated: Use `drives.get` instead.",
          "flatPath": "teamdrives/{teamDriveId}"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "teamdrives",
          "flatPath": "teamdrives",
          "description": "Deprecated: Use `drives.insert` instead.",
          "id": "drive.teamdrives.insert",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "update": {
          "id": "drive.teamdrives.update",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ],
          "flatPath": "teamdrives/{teamDriveId}",
          "description": "Deprecated: Use `drives.update` instead.",
          "path": "teamdrives/{teamDriveId}",
          "httpMethod": "PUT"
        }
      }
    }
  },
  "title": "Google Drive API",
  "name": "drive",
  "baseUrl": "https://www.googleapis.com/drive/v2/",
  "protocol": "rest",
  "revision": "20260305"
}