{
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "description": "The Google Play Games Service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "id": "games:v1",
  "ownerName": "Google",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/androidpublisher": {
          "description": "View and manage your Google Play Developer account"
        },
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "basePath": "",
  "canonicalName": "Games",
  "title": "Google Play Games Services API",
  "version": "v1",
  "rootUrl": "https://games.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "documentationLink": "https://developers.google.com/games/",
  "name": "games",
  "revision": "20260416",
  "baseUrl": "https://games.googleapis.com/",
  "resources": {
    "metagame": {
      "methods": {
        "getMetagameConfig": {
          "description": "Return the metagame configuration data for the calling application.",
          "path": "games/v1/metagameConfig",
          "flatPath": "games/v1/metagameConfig",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.metagame.getMetagameConfig"
        },
        "listCategoriesByPlayer": {
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "id": "games.metagame.listCategoriesByPlayer",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "achievements": {
      "methods": {
        "list": {
          "path": "games/v1/players/{playerId}/achievements",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "flatPath": "games/v1/players/{playerId}/achievements",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.list"
        },
        "unlock": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.unlock",
          "path": "games/v1/achievements/{achievementId}/unlock",
          "description": "Unlocks this achievement for the currently authenticated player.",
          "flatPath": "games/v1/achievements/{achievementId}/unlock"
        },
        "setStepsAtLeast": {
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.setStepsAtLeast"
        },
        "increment": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.increment",
          "path": "games/v1/achievements/{achievementId}/increment",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "flatPath": "games/v1/achievements/{achievementId}/increment"
        },
        "updateMultiple": {
          "path": "games/v1/achievements/updateMultiple",
          "description": "Updates multiple achievements for the currently authenticated player.",
          "flatPath": "games/v1/achievements/updateMultiple",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.updateMultiple"
        },
        "reveal": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.reveal",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "flatPath": "games/v1/achievements/{achievementId}/reveal"
        }
      }
    },
    "leaderboards": {
      "methods": {
        "list": {
          "flatPath": "games/v1/leaderboards",
          "path": "games/v1/leaderboards",
          "description": "Lists all the leaderboard metadata for your application.",
          "id": "games.leaderboards.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "get": {
          "id": "games.leaderboards.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "description": "Retrieves the metadata of the leaderboard with the given ID."
        }
      }
    },
    "snapshots": {
      "methods": {
        "list": {
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "path": "games/v1/players/{playerId}/snapshots",
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.snapshots.list"
        },
        "get": {
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "path": "games/v1/snapshots/{snapshotId}",
          "id": "games.snapshots.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.revisions.check",
          "path": "games/v1/revisions/check",
          "description": "Checks whether the games client is out of date.",
          "flatPath": "games/v1/revisions/check"
        }
      }
    },
    "recall": {
      "methods": {
        "linkPersona": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "id": "games.recall.linkPersona",
          "path": "games/v1/recall:linkPersona",
          "description": "Associate the PGS Player principal encoded in the provided recall session id with an in-game account",
          "flatPath": "games/v1/recall:linkPersona"
        },
        "lastTokenFromAllDeveloperGames": {
          "id": "games.recall.lastTokenFromAllDeveloperGames",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "path": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "description": "Retrieve the last Recall token from all developer games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile."
        },
        "gamesPlayerTokens": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "id": "games.recall.gamesPlayerTokens",
          "path": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "description": "Retrieve the Recall tokens from all requested games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have an active PGS Player profile.",
          "flatPath": "games/v1/recall/gamesPlayerTokens/{sessionId}"
        },
        "resetPersona": {
          "description": "Delete all Recall tokens linking the given persona to any player (with or without a profile).",
          "path": "games/v1/recall:resetPersona",
          "flatPath": "games/v1/recall:resetPersona",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "id": "games.recall.resetPersona"
        },
        "unlinkPersona": {
          "path": "games/v1/recall:unlinkPersona",
          "description": "Delete a Recall token linking the PGS Player principal identified by the Recall session and an in-game account identified either by the 'persona' or by the token value.",
          "flatPath": "games/v1/recall:unlinkPersona",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "id": "games.recall.unlinkPersona"
        },
        "retrieveTokens": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "id": "games.recall.retrieveTokens",
          "path": "games/v1/recall/tokens/{sessionId}",
          "description": "Retrieve all Recall tokens associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile.",
          "flatPath": "games/v1/recall/tokens/{sessionId}"
        }
      }
    },
    "events": {
      "methods": {
        "listByPlayer": {
          "id": "games.events.listByPlayer",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/events",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "path": "games/v1/events"
        },
        "record": {
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "path": "games/v1/events",
          "flatPath": "games/v1/events",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.events.record"
        },
        "listDefinitions": {
          "id": "games.events.listDefinitions",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/eventDefinitions",
          "description": "Returns a list of the event definitions in this application.",
          "path": "games/v1/eventDefinitions"
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "flatPath": "games/v1/stats",
          "path": "games/v1/stats",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "id": "games.stats.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "players": {
      "methods": {
        "get": {
          "id": "games.players.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "path": "games/v1/players/{playerId}"
        },
        "getScopedPlayerIds": {
          "description": "Retrieves scoped player identifiers for currently authenticated user.",
          "path": "games/v1/players/me/scopedIds",
          "flatPath": "games/v1/players/me/scopedIds",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.players.getScopedPlayerIds"
        },
        "getMultipleApplicationPlayerIds": {
          "id": "games.players.getMultipleApplicationPlayerIds",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/multipleApplicationPlayerIds",
          "path": "games/v1/players/me/multipleApplicationPlayerIds",
          "description": "Get the application player ids for the currently authenticated player across all requested games by the same developer as the calling application. This will only return ids for players that actually have an id (scoped or otherwise) with that game."
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.players.list",
          "path": "games/v1/players/me/players/{collection}",
          "description": "Get the collection of players for the currently authenticated user.",
          "flatPath": "games/v1/players/me/players/{collection}"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievementDefinitions.list",
          "description": "Lists all the achievement definitions for your application.",
          "path": "games/v1/achievements",
          "flatPath": "games/v1/achievements"
        }
      }
    },
    "scores": {
      "methods": {
        "get": {
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.get"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.list",
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}"
        },
        "listWindow": {
          "id": "games.scores.listWindow",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "description": "Lists the scores in a leaderboard around (and including) a player's score."
        },
        "submit": {
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "description": "Submits a score to the specified leaderboard.",
          "id": "games.scores.submit",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "submitMultiple": {
          "flatPath": "games/v1/leaderboards/scores",
          "description": "Submits multiple scores to leaderboards.",
          "path": "games/v1/leaderboards/scores",
          "id": "games.scores.submitMultiple",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "accesstokens": {
      "methods": {
        "generateRecallPlayGroupingApiToken": {
          "id": "games.accesstokens.generateRecallPlayGroupingApiToken",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "path": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "description": "Generates a Play Grouping API token for the PGS user identified by the Recall session ID provided in the request."
        },
        "generatePlayGroupingApiToken": {
          "flatPath": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "path": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "description": "Generates a Play Grouping API token for the PGS user identified by the attached credential.",
          "id": "games.accesstokens.generatePlayGroupingApiToken",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "applications": {
      "methods": {
        "getEndPoint": {
          "id": "games.applications.getEndPoint",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/getEndPoint",
          "description": "Returns a URL for the requested end point type.",
          "path": "games/v1/applications/getEndPoint"
        },
        "played": {
          "flatPath": "games/v1/applications/played",
          "id": "games.applications.played",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Indicate that the currently authenticated user is playing your application.",
          "path": "games/v1/applications/played"
        },
        "verify": {
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "path": "games/v1/applications/{applicationId}/verify",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "id": "games.applications.verify",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "get": {
          "flatPath": "games/v1/applications/{applicationId}",
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "path": "games/v1/applications/{applicationId}",
          "id": "games.applications.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    }
  },
  "protocol": "rest",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "servicePath": ""
}