{
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/androidpublisher": {
          "description": "View and manage your Google Play Developer account"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        }
      }
    }
  },
  "description": "The Google Play Games Service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "servicePath": "",
  "name": "games",
  "resources": {
    "applications": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.get",
          "httpMethod": "GET",
          "flatPath": "games/v1/applications/{applicationId}",
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "path": "games/v1/applications/{applicationId}"
        },
        "getEndPoint": {
          "description": "Returns a URL for the requested end point type.",
          "path": "games/v1/applications/getEndPoint",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.getEndPoint",
          "httpMethod": "POST",
          "flatPath": "games/v1/applications/getEndPoint"
        },
        "played": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.played",
          "httpMethod": "POST",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "path": "games/v1/applications/played",
          "flatPath": "games/v1/applications/played"
        },
        "verify": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.verify",
          "httpMethod": "GET",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "path": "games/v1/applications/{applicationId}/verify"
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "flatPath": "games/v1/revisions/check",
          "httpMethod": "GET",
          "id": "games.revisions.check",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/revisions/check",
          "description": "Checks whether the games client is out of date."
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "path": "games/v1/achievements",
          "description": "Lists all the achievement definitions for your application.",
          "id": "games.achievementDefinitions.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements",
          "httpMethod": "GET"
        }
      }
    },
    "events": {
      "methods": {
        "listByPlayer": {
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "path": "games/v1/events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.events.listByPlayer",
          "httpMethod": "GET",
          "flatPath": "games/v1/events"
        },
        "listDefinitions": {
          "path": "games/v1/eventDefinitions",
          "description": "Returns a list of the event definitions in this application.",
          "flatPath": "games/v1/eventDefinitions",
          "httpMethod": "GET",
          "id": "games.events.listDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "record": {
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "path": "games/v1/events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.events.record",
          "httpMethod": "POST",
          "flatPath": "games/v1/events"
        }
      }
    },
    "metagame": {
      "methods": {
        "getMetagameConfig": {
          "description": "Return the metagame configuration data for the calling application.",
          "path": "games/v1/metagameConfig",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.metagame.getMetagameConfig",
          "httpMethod": "GET",
          "flatPath": "games/v1/metagameConfig"
        },
        "listCategoriesByPlayer": {
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "httpMethod": "GET",
          "id": "games.metagame.listCategoriesByPlayer",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "description": "List play data aggregated per category for the player corresponding to `playerId`."
        }
      }
    },
    "scores": {
      "methods": {
        "listWindow": {
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "httpMethod": "GET",
          "id": "games.scores.listWindow",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "httpMethod": "GET",
          "id": "games.scores.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "description": "Lists the scores in a leaderboard, starting from the top."
        },
        "submitMultiple": {
          "description": "Submits multiple scores to leaderboards.",
          "path": "games/v1/leaderboards/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.submitMultiple",
          "httpMethod": "POST",
          "flatPath": "games/v1/leaderboards/scores"
        },
        "submit": {
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "httpMethod": "POST",
          "id": "games.scores.submit",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "description": "Submits a score to the specified leaderboard."
        },
        "get": {
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "httpMethod": "GET",
          "id": "games.scores.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "leaderboards": {
      "methods": {
        "list": {
          "path": "games/v1/leaderboards",
          "description": "Lists all the leaderboard metadata for your application.",
          "flatPath": "games/v1/leaderboards",
          "httpMethod": "GET",
          "id": "games.leaderboards.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "get": {
          "path": "games/v1/leaderboards/{leaderboardId}",
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "httpMethod": "GET",
          "id": "games.leaderboards.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "snapshots": {
      "methods": {
        "list": {
          "path": "games/v1/players/{playerId}/snapshots",
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "id": "games.snapshots.list",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "httpMethod": "GET"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.snapshots.get",
          "httpMethod": "GET",
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "path": "games/v1/snapshots/{snapshotId}"
        }
      }
    },
    "achievements": {
      "methods": {
        "reveal": {
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.reveal"
        },
        "unlock": {
          "description": "Unlocks this achievement for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/unlock",
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.unlock"
        },
        "increment": {
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.increment",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/increment"
        },
        "list": {
          "id": "games.achievements.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/achievements",
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}/achievements",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player."
        },
        "setStepsAtLeast": {
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.setStepsAtLeast",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast"
        },
        "updateMultiple": {
          "description": "Updates multiple achievements for the currently authenticated player.",
          "path": "games/v1/achievements/updateMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.updateMultiple",
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/updateMultiple"
        }
      }
    },
    "players": {
      "methods": {
        "getScopedPlayerIds": {
          "description": "Retrieves scoped player identifiers for currently authenticated user.",
          "path": "games/v1/players/me/scopedIds",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.players.getScopedPlayerIds",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/me/scopedIds"
        },
        "getMultipleApplicationPlayerIds": {
          "id": "games.players.getMultipleApplicationPlayerIds",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/multipleApplicationPlayerIds",
          "httpMethod": "GET",
          "path": "games/v1/players/me/multipleApplicationPlayerIds",
          "description": "Get the application player ids for the currently authenticated player across all requested games by the same developer as the calling application. This will only return ids for players that actually have an id (scoped or otherwise) with that game."
        },
        "list": {
          "id": "games.players.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/players/{collection}",
          "httpMethod": "GET",
          "path": "games/v1/players/me/players/{collection}",
          "description": "Get the collection of players for the currently authenticated user."
        },
        "get": {
          "path": "games/v1/players/{playerId}",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "id": "games.players.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}",
          "httpMethod": "GET"
        }
      }
    },
    "recall": {
      "methods": {
        "retrieveTokens": {
          "path": "games/v1/recall/tokens/{sessionId}",
          "description": "Retrieve all Recall tokens associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile.",
          "id": "games.recall.retrieveTokens",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/recall/tokens/{sessionId}",
          "httpMethod": "GET"
        },
        "lastTokenFromAllDeveloperGames": {
          "description": "Retrieve the last Recall token from all developer games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile.",
          "path": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "httpMethod": "GET",
          "flatPath": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "id": "games.recall.lastTokenFromAllDeveloperGames"
        },
        "linkPersona": {
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "id": "games.recall.linkPersona",
          "httpMethod": "POST",
          "flatPath": "games/v1/recall:linkPersona",
          "description": "Associate the PGS Player principal encoded in the provided recall session id with an in-game account",
          "path": "games/v1/recall:linkPersona"
        },
        "resetPersona": {
          "flatPath": "games/v1/recall:resetPersona",
          "httpMethod": "POST",
          "id": "games.recall.resetPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "path": "games/v1/recall:resetPersona",
          "description": "Delete all Recall tokens linking the given persona to any player (with or without a profile)."
        },
        "unlinkPersona": {
          "flatPath": "games/v1/recall:unlinkPersona",
          "httpMethod": "POST",
          "id": "games.recall.unlinkPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "path": "games/v1/recall:unlinkPersona",
          "description": "Delete a Recall token linking the PGS Player principal identified by the Recall session and an in-game account identified either by the 'persona' or by the token value."
        },
        "gamesPlayerTokens": {
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "id": "games.recall.gamesPlayerTokens",
          "httpMethod": "GET",
          "flatPath": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "description": "Retrieve the Recall tokens from all requested games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have an active PGS Player profile.",
          "path": "games/v1/recall/gamesPlayerTokens/{sessionId}"
        }
      }
    },
    "accesstokens": {
      "methods": {
        "generatePlayGroupingApiToken": {
          "description": "Generates a Play Grouping API token for the PGS user identified by the attached credential.",
          "path": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "httpMethod": "POST",
          "flatPath": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.accesstokens.generatePlayGroupingApiToken"
        },
        "generateRecallPlayGroupingApiToken": {
          "flatPath": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "httpMethod": "POST",
          "id": "games.accesstokens.generateRecallPlayGroupingApiToken",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "path": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "description": "Generates a Play Grouping API token for the PGS user identified by the Recall session ID provided in the request."
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "path": "games/v1/stats",
          "httpMethod": "GET",
          "flatPath": "games/v1/stats",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.stats.get"
        }
      }
    }
  },
  "title": "Google Play Games Services API",
  "revision": "20260423",
  "protocol": "rest",
  "canonicalName": "Games",
  "kind": "discovery#restDescription",
  "ownerDomain": "google.com",
  "documentationLink": "https://developers.google.com/games/",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "baseUrl": "https://games.googleapis.com/",
  "version": "v1",
  "rootUrl": "https://games.googleapis.com/",
  "id": "games:v1",
  "basePath": "",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "ownerName": "Google"
}