{
  "fullyEncodeReservedExpansion": true,
  "version": "v1",
  "canonicalName": "Games",
  "rootUrl": "https://games.googleapis.com/",
  "protocol": "rest",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/games/",
  "baseUrl": "https://games.googleapis.com/",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "title": "Google Play Games Services API",
  "name": "games",
  "ownerName": "Google",
  "kind": "discovery#restDescription",
  "id": "games:v1",
  "revision": "20260423",
  "servicePath": "",
  "basePath": "",
  "description": "The Google Play Games Service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "resources": {
    "stats": {
      "methods": {
        "get": {
          "id": "games.stats.get",
          "httpMethod": "GET",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "flatPath": "games/v1/stats",
          "path": "games/v1/stats",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "accesstokens": {
      "methods": {
        "generatePlayGroupingApiToken": {
          "path": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "httpMethod": "POST",
          "description": "Generates a Play Grouping API token for the PGS user identified by the attached credential.",
          "id": "games.accesstokens.generatePlayGroupingApiToken"
        },
        "generateRecallPlayGroupingApiToken": {
          "id": "games.accesstokens.generateRecallPlayGroupingApiToken",
          "description": "Generates a Play Grouping API token for the PGS user identified by the Recall session ID provided in the request.",
          "httpMethod": "POST",
          "flatPath": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "path": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ]
        }
      }
    },
    "achievements": {
      "methods": {
        "reveal": {
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "httpMethod": "POST",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "id": "games.achievements.reveal",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "increment": {
          "id": "games.achievements.increment",
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "httpMethod": "POST",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/increment",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "path": "games/v1/players/{playerId}/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/achievements",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "httpMethod": "GET",
          "id": "games.achievements.list"
        },
        "unlock": {
          "httpMethod": "POST",
          "description": "Unlocks this achievement for the currently authenticated player.",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "id": "games.achievements.unlock",
          "path": "games/v1/achievements/{achievementId}/unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "updateMultiple": {
          "path": "games/v1/achievements/updateMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.updateMultiple",
          "flatPath": "games/v1/achievements/updateMultiple",
          "httpMethod": "POST",
          "description": "Updates multiple achievements for the currently authenticated player."
        },
        "setStepsAtLeast": {
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.setStepsAtLeast",
          "httpMethod": "POST",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast"
        }
      }
    },
    "leaderboards": {
      "methods": {
        "list": {
          "path": "games/v1/leaderboards",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.leaderboards.list",
          "httpMethod": "GET",
          "description": "Lists all the leaderboard metadata for your application.",
          "flatPath": "games/v1/leaderboards"
        },
        "get": {
          "path": "games/v1/leaderboards/{leaderboardId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "httpMethod": "GET",
          "id": "games.leaderboards.get"
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "id": "games.revisions.check",
          "flatPath": "games/v1/revisions/check",
          "httpMethod": "GET",
          "description": "Checks whether the games client is out of date.",
          "path": "games/v1/revisions/check",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "metagame": {
      "methods": {
        "getMetagameConfig": {
          "flatPath": "games/v1/metagameConfig",
          "httpMethod": "GET",
          "description": "Return the metagame configuration data for the calling application.",
          "id": "games.metagame.getMetagameConfig",
          "path": "games/v1/metagameConfig",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listCategoriesByPlayer": {
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "id": "games.metagame.listCategoriesByPlayer",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "snapshots": {
      "methods": {
        "get": {
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "httpMethod": "GET",
          "id": "games.snapshots.get",
          "path": "games/v1/snapshots/{snapshotId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "id": "games.snapshots.list",
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "httpMethod": "GET",
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "path": "games/v1/players/{playerId}/snapshots",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "recall": {
      "methods": {
        "lastTokenFromAllDeveloperGames": {
          "flatPath": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "httpMethod": "GET",
          "description": "Retrieve the last Recall token from all developer games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile.",
          "id": "games.recall.lastTokenFromAllDeveloperGames",
          "path": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ]
        },
        "linkPersona": {
          "path": "games/v1/recall:linkPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/recall:linkPersona",
          "description": "Associate the PGS Player principal encoded in the provided recall session id with an in-game account",
          "httpMethod": "POST",
          "id": "games.recall.linkPersona"
        },
        "resetPersona": {
          "path": "games/v1/recall:resetPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/recall:resetPersona",
          "httpMethod": "POST",
          "description": "Delete all Recall tokens linking the given persona to any player (with or without a profile).",
          "id": "games.recall.resetPersona"
        },
        "retrieveTokens": {
          "path": "games/v1/recall/tokens/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "id": "games.recall.retrieveTokens",
          "flatPath": "games/v1/recall/tokens/{sessionId}",
          "httpMethod": "GET",
          "description": "Retrieve all Recall tokens associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile."
        },
        "gamesPlayerTokens": {
          "path": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "httpMethod": "GET",
          "description": "Retrieve the Recall tokens from all requested games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have an active PGS Player profile.",
          "id": "games.recall.gamesPlayerTokens"
        },
        "unlinkPersona": {
          "path": "games/v1/recall:unlinkPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "id": "games.recall.unlinkPersona",
          "flatPath": "games/v1/recall:unlinkPersona",
          "httpMethod": "POST",
          "description": "Delete a Recall token linking the PGS Player principal identified by the Recall session and an in-game account identified either by the 'persona' or by the token value."
        }
      }
    },
    "applications": {
      "methods": {
        "get": {
          "id": "games.applications.get",
          "flatPath": "games/v1/applications/{applicationId}",
          "httpMethod": "GET",
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "path": "games/v1/applications/{applicationId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "played": {
          "httpMethod": "POST",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "flatPath": "games/v1/applications/played",
          "id": "games.applications.played",
          "path": "games/v1/applications/played",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "getEndPoint": {
          "description": "Returns a URL for the requested end point type.",
          "httpMethod": "POST",
          "flatPath": "games/v1/applications/getEndPoint",
          "id": "games.applications.getEndPoint",
          "path": "games/v1/applications/getEndPoint",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "verify": {
          "path": "games/v1/applications/{applicationId}/verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "httpMethod": "GET",
          "id": "games.applications.verify"
        }
      }
    },
    "players": {
      "methods": {
        "list": {
          "id": "games.players.list",
          "httpMethod": "GET",
          "description": "Get the collection of players for the currently authenticated user.",
          "flatPath": "games/v1/players/me/players/{collection}",
          "path": "games/v1/players/me/players/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "getScopedPlayerIds": {
          "path": "games/v1/players/me/scopedIds",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/scopedIds",
          "httpMethod": "GET",
          "description": "Retrieves scoped player identifiers for currently authenticated user.",
          "id": "games.players.getScopedPlayerIds"
        },
        "getMultipleApplicationPlayerIds": {
          "path": "games/v1/players/me/multipleApplicationPlayerIds",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/multipleApplicationPlayerIds",
          "httpMethod": "GET",
          "description": "Get the application player ids for the currently authenticated player across all requested games by the same developer as the calling application. This will only return ids for players that actually have an id (scoped or otherwise) with that game.",
          "id": "games.players.getMultipleApplicationPlayerIds"
        },
        "get": {
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}",
          "id": "games.players.get",
          "path": "games/v1/players/{playerId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "path": "games/v1/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievementDefinitions.list",
          "flatPath": "games/v1/achievements",
          "description": "Lists all the achievement definitions for your application.",
          "httpMethod": "GET"
        }
      }
    },
    "scores": {
      "methods": {
        "get": {
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "httpMethod": "GET",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "id": "games.scores.get"
        },
        "list": {
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "id": "games.scores.list"
        },
        "listWindow": {
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "httpMethod": "GET",
          "id": "games.scores.listWindow"
        },
        "submit": {
          "id": "games.scores.submit",
          "httpMethod": "POST",
          "description": "Submits a score to the specified leaderboard.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "submitMultiple": {
          "path": "games/v1/leaderboards/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/scores",
          "httpMethod": "POST",
          "description": "Submits multiple scores to leaderboards.",
          "id": "games.scores.submitMultiple"
        }
      }
    },
    "events": {
      "methods": {
        "listByPlayer": {
          "id": "games.events.listByPlayer",
          "flatPath": "games/v1/events",
          "httpMethod": "GET",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "path": "games/v1/events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listDefinitions": {
          "id": "games.events.listDefinitions",
          "httpMethod": "GET",
          "description": "Returns a list of the event definitions in this application.",
          "flatPath": "games/v1/eventDefinitions",
          "path": "games/v1/eventDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "record": {
          "path": "games/v1/events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/events",
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "httpMethod": "POST",
          "id": "games.events.record"
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        },
        "https://www.googleapis.com/auth/androidpublisher": {
          "description": "View and manage your Google Play Developer account"
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "batchPath": "batch"
}