{
  "batchPath": "batch",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "ownerDomain": "google.com",
  "title": "Google Play Games Services API",
  "canonicalName": "Games",
  "resources": {
    "metagame": {
      "methods": {
        "getMetagameConfig": {
          "id": "games.metagame.getMetagameConfig",
          "description": "Return the metagame configuration data for the calling application.",
          "httpMethod": "GET",
          "flatPath": "games/v1/metagameConfig",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/metagameConfig"
        },
        "listCategoriesByPlayer": {
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "httpMethod": "GET",
          "id": "games.metagame.listCategoriesByPlayer",
          "path": "games/v1/players/{playerId}/categories/{collection}"
        }
      }
    },
    "snapshots": {
      "methods": {
        "get": {
          "id": "games.snapshots.get",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "httpMethod": "GET",
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/snapshots/{snapshotId}"
        },
        "list": {
          "path": "games/v1/players/{playerId}/snapshots",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "httpMethod": "GET",
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "id": "games.snapshots.list"
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "description": "Checks whether the games client is out of date.",
          "httpMethod": "GET",
          "id": "games.revisions.check",
          "flatPath": "games/v1/revisions/check",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/revisions/check"
        }
      }
    },
    "scores": {
      "methods": {
        "list": {
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "id": "games.scores.list",
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "submit": {
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "httpMethod": "POST",
          "description": "Submits a score to the specified leaderboard.",
          "id": "games.scores.submit"
        },
        "get": {
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.get",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "httpMethod": "GET"
        },
        "listWindow": {
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "id": "games.scores.listWindow",
          "httpMethod": "GET",
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}"
        },
        "submitMultiple": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/scores",
          "httpMethod": "POST",
          "description": "Submits multiple scores to leaderboards.",
          "id": "games.scores.submitMultiple",
          "path": "games/v1/leaderboards/scores"
        }
      }
    },
    "recall": {
      "methods": {
        "retrieveTokens": {
          "path": "games/v1/recall/tokens/{sessionId}",
          "flatPath": "games/v1/recall/tokens/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "id": "games.recall.retrieveTokens",
          "description": "Retrieve all Recall tokens associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile.",
          "httpMethod": "GET"
        },
        "lastTokenFromAllDeveloperGames": {
          "flatPath": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "id": "games.recall.lastTokenFromAllDeveloperGames",
          "description": "Retrieve the last Recall token from all developer games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile.",
          "httpMethod": "GET",
          "path": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}"
        },
        "unlinkPersona": {
          "httpMethod": "POST",
          "description": "Delete a Recall token linking the PGS Player principal identified by the Recall session and an in-game account identified either by the 'persona' or by the token value.",
          "id": "games.recall.unlinkPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/recall:unlinkPersona",
          "path": "games/v1/recall:unlinkPersona"
        },
        "gamesPlayerTokens": {
          "description": "Retrieve the Recall tokens from all requested games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have an active PGS Player profile.",
          "httpMethod": "GET",
          "id": "games.recall.gamesPlayerTokens",
          "flatPath": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "path": "games/v1/recall/gamesPlayerTokens/{sessionId}"
        },
        "resetPersona": {
          "id": "games.recall.resetPersona",
          "description": "Delete all Recall tokens linking the given persona to any player (with or without a profile).",
          "httpMethod": "POST",
          "flatPath": "games/v1/recall:resetPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "path": "games/v1/recall:resetPersona"
        },
        "linkPersona": {
          "id": "games.recall.linkPersona",
          "httpMethod": "POST",
          "description": "Associate the PGS Player principal encoded in the provided recall session id with an in-game account",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/recall:linkPersona",
          "path": "games/v1/recall:linkPersona"
        }
      }
    },
    "events": {
      "methods": {
        "record": {
          "path": "games/v1/events",
          "id": "games.events.record",
          "httpMethod": "POST",
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/events"
        },
        "listByPlayer": {
          "path": "games/v1/events",
          "flatPath": "games/v1/events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "httpMethod": "GET",
          "id": "games.events.listByPlayer"
        },
        "listDefinitions": {
          "httpMethod": "GET",
          "description": "Returns a list of the event definitions in this application.",
          "id": "games.events.listDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/eventDefinitions",
          "path": "games/v1/eventDefinitions"
        }
      }
    },
    "applications": {
      "methods": {
        "verify": {
          "httpMethod": "GET",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "id": "games.applications.verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "path": "games/v1/applications/{applicationId}/verify"
        },
        "getEndPoint": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/getEndPoint",
          "httpMethod": "POST",
          "description": "Returns a URL for the requested end point type.",
          "id": "games.applications.getEndPoint",
          "path": "games/v1/applications/getEndPoint"
        },
        "get": {
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "httpMethod": "GET",
          "id": "games.applications.get",
          "flatPath": "games/v1/applications/{applicationId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/applications/{applicationId}"
        },
        "played": {
          "flatPath": "games/v1/applications/played",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/applications/played",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "httpMethod": "POST",
          "id": "games.applications.played"
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "flatPath": "games/v1/stats",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.stats.get",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "httpMethod": "GET",
          "path": "games/v1/stats"
        }
      }
    },
    "players": {
      "methods": {
        "getScopedPlayerIds": {
          "path": "games/v1/players/me/scopedIds",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/scopedIds",
          "id": "games.players.getScopedPlayerIds",
          "httpMethod": "GET",
          "description": "Retrieves scoped player identifiers for currently authenticated user."
        },
        "getMultipleApplicationPlayerIds": {
          "path": "games/v1/players/me/multipleApplicationPlayerIds",
          "httpMethod": "GET",
          "description": "Get the application player ids for the currently authenticated player across all requested games by the same developer as the calling application. This will only return ids for players that actually have an id (scoped or otherwise) with that game.",
          "id": "games.players.getMultipleApplicationPlayerIds",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/multipleApplicationPlayerIds"
        },
        "get": {
          "path": "games/v1/players/{playerId}",
          "httpMethod": "GET",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "id": "games.players.get",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}"
        },
        "list": {
          "id": "games.players.list",
          "description": "Get the collection of players for the currently authenticated user.",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/me/players/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/me/players/{collection}"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Lists all the achievement definitions for your application.",
          "id": "games.achievementDefinitions.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements",
          "path": "games/v1/achievements"
        }
      }
    },
    "leaderboards": {
      "methods": {
        "list": {
          "description": "Lists all the leaderboard metadata for your application.",
          "httpMethod": "GET",
          "id": "games.leaderboards.list",
          "flatPath": "games/v1/leaderboards",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards"
        },
        "get": {
          "id": "games.leaderboards.get",
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/{leaderboardId}"
        }
      }
    },
    "accesstokens": {
      "methods": {
        "generateRecallPlayGroupingApiToken": {
          "description": "Generates a Play Grouping API token for the PGS user identified by the Recall session ID provided in the request.",
          "httpMethod": "POST",
          "id": "games.accesstokens.generateRecallPlayGroupingApiToken",
          "flatPath": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "path": "games/v1/accesstokens/generateRecallPlayGroupingApiToken"
        },
        "generatePlayGroupingApiToken": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "httpMethod": "POST",
          "description": "Generates a Play Grouping API token for the PGS user identified by the attached credential.",
          "id": "games.accesstokens.generatePlayGroupingApiToken",
          "path": "games/v1/accesstokens/generatePlayGroupingApiToken"
        }
      }
    },
    "achievements": {
      "methods": {
        "increment": {
          "id": "games.achievements.increment",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/increment"
        },
        "updateMultiple": {
          "flatPath": "games/v1/achievements/updateMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Updates multiple achievements for the currently authenticated player.",
          "httpMethod": "POST",
          "id": "games.achievements.updateMultiple",
          "path": "games/v1/achievements/updateMultiple"
        },
        "setStepsAtLeast": {
          "id": "games.achievements.setStepsAtLeast",
          "httpMethod": "POST",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast"
        },
        "unlock": {
          "path": "games/v1/achievements/{achievementId}/unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "httpMethod": "POST",
          "description": "Unlocks this achievement for the currently authenticated player.",
          "id": "games.achievements.unlock"
        },
        "list": {
          "path": "games/v1/players/{playerId}/achievements",
          "httpMethod": "GET",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "id": "games.achievements.list",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/achievements"
        },
        "reveal": {
          "path": "games/v1/achievements/{achievementId}/reveal",
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.reveal",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "httpMethod": "POST"
        }
      }
    }
  },
  "revision": "20260312",
  "basePath": "",
  "version": "v1",
  "baseUrl": "https://games.googleapis.com/",
  "id": "games:v1",
  "servicePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        },
        "https://www.googleapis.com/auth/androidpublisher": {
          "description": "View and manage your Google Play Developer account"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        }
      }
    }
  },
  "ownerName": "Google",
  "kind": "discovery#restDescription",
  "description": "The Google Play Games Service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "protocol": "rest",
  "rootUrl": "https://games.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "name": "games",
  "documentationLink": "https://developers.google.com/games/"
}