{
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/androidpublisher": {
          "description": "View and manage your Google Play Developer account"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        }
      }
    }
  },
  "revision": "20260416",
  "discoveryVersion": "v1",
  "resources": {
    "applications": {
      "methods": {
        "verify": {
          "httpMethod": "GET",
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "id": "games.applications.verify",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "path": "games/v1/applications/{applicationId}/verify",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "played": {
          "id": "games.applications.played",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "flatPath": "games/v1/applications/played",
          "path": "games/v1/applications/played",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST"
        },
        "getEndPoint": {
          "id": "games.applications.getEndPoint",
          "description": "Returns a URL for the requested end point type.",
          "flatPath": "games/v1/applications/getEndPoint",
          "path": "games/v1/applications/getEndPoint",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST"
        },
        "get": {
          "httpMethod": "GET",
          "path": "games/v1/applications/{applicationId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/{applicationId}",
          "id": "games.applications.get",
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data."
        }
      }
    },
    "achievements": {
      "methods": {
        "unlock": {
          "id": "games.achievements.unlock",
          "description": "Unlocks this achievement for the currently authenticated player.",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "path": "games/v1/achievements/{achievementId}/unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST"
        },
        "updateMultiple": {
          "path": "games/v1/achievements/updateMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.updateMultiple",
          "description": "Updates multiple achievements for the currently authenticated player.",
          "flatPath": "games/v1/achievements/updateMultiple",
          "httpMethod": "POST"
        },
        "setStepsAtLeast": {
          "id": "games.achievements.setStepsAtLeast",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/achievements",
          "id": "games.achievements.list",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player."
        },
        "reveal": {
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "id": "games.achievements.reveal",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "increment": {
          "path": "games/v1/achievements/{achievementId}/increment",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.increment",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "httpMethod": "POST"
        }
      }
    },
    "recall": {
      "methods": {
        "unlinkPersona": {
          "httpMethod": "POST",
          "path": "games/v1/recall:unlinkPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/recall:unlinkPersona",
          "id": "games.recall.unlinkPersona",
          "description": "Delete a Recall token linking the PGS Player principal identified by the Recall session and an in-game account identified either by the 'persona' or by the token value."
        },
        "linkPersona": {
          "httpMethod": "POST",
          "flatPath": "games/v1/recall:linkPersona",
          "id": "games.recall.linkPersona",
          "description": "Associate the PGS Player principal encoded in the provided recall session id with an in-game account",
          "path": "games/v1/recall:linkPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ]
        },
        "lastTokenFromAllDeveloperGames": {
          "id": "games.recall.lastTokenFromAllDeveloperGames",
          "description": "Retrieve the last Recall token from all developer games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile.",
          "flatPath": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "path": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "httpMethod": "GET"
        },
        "resetPersona": {
          "path": "games/v1/recall:resetPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/recall:resetPersona",
          "id": "games.recall.resetPersona",
          "description": "Delete all Recall tokens linking the given persona to any player (with or without a profile).",
          "httpMethod": "POST"
        },
        "retrieveTokens": {
          "path": "games/v1/recall/tokens/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/recall/tokens/{sessionId}",
          "id": "games.recall.retrieveTokens",
          "description": "Retrieve all Recall tokens associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile.",
          "httpMethod": "GET"
        },
        "gamesPlayerTokens": {
          "path": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "id": "games.recall.gamesPlayerTokens",
          "description": "Retrieve the Recall tokens from all requested games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have an active PGS Player profile.",
          "httpMethod": "GET"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "games/v1/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/achievements",
          "id": "games.achievementDefinitions.list",
          "description": "Lists all the achievement definitions for your application."
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "httpMethod": "GET",
          "id": "games.revisions.check",
          "description": "Checks whether the games client is out of date.",
          "flatPath": "games/v1/revisions/check",
          "path": "games/v1/revisions/check",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "accesstokens": {
      "methods": {
        "generatePlayGroupingApiToken": {
          "path": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "id": "games.accesstokens.generatePlayGroupingApiToken",
          "description": "Generates a Play Grouping API token for the PGS user identified by the attached credential.",
          "httpMethod": "POST"
        },
        "generateRecallPlayGroupingApiToken": {
          "httpMethod": "POST",
          "id": "games.accesstokens.generateRecallPlayGroupingApiToken",
          "description": "Generates a Play Grouping API token for the PGS user identified by the Recall session ID provided in the request.",
          "flatPath": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "path": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ]
        }
      }
    },
    "snapshots": {
      "methods": {
        "list": {
          "path": "games/v1/players/{playerId}/snapshots",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "id": "games.snapshots.list",
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "httpMethod": "GET"
        },
        "get": {
          "httpMethod": "GET",
          "id": "games.snapshots.get",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "path": "games/v1/snapshots/{snapshotId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "players": {
      "methods": {
        "getMultipleApplicationPlayerIds": {
          "path": "games/v1/players/me/multipleApplicationPlayerIds",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/multipleApplicationPlayerIds",
          "id": "games.players.getMultipleApplicationPlayerIds",
          "description": "Get the application player ids for the currently authenticated player across all requested games by the same developer as the calling application. This will only return ids for players that actually have an id (scoped or otherwise) with that game.",
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "id": "games.players.list",
          "description": "Get the collection of players for the currently authenticated user.",
          "flatPath": "games/v1/players/me/players/{collection}",
          "path": "games/v1/players/me/players/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "get": {
          "path": "games/v1/players/{playerId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.players.get",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "flatPath": "games/v1/players/{playerId}",
          "httpMethod": "GET"
        },
        "getScopedPlayerIds": {
          "httpMethod": "GET",
          "id": "games.players.getScopedPlayerIds",
          "description": "Retrieves scoped player identifiers for currently authenticated user.",
          "flatPath": "games/v1/players/me/scopedIds",
          "path": "games/v1/players/me/scopedIds",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "metagame": {
      "methods": {
        "getMetagameConfig": {
          "httpMethod": "GET",
          "id": "games.metagame.getMetagameConfig",
          "description": "Return the metagame configuration data for the calling application.",
          "flatPath": "games/v1/metagameConfig",
          "path": "games/v1/metagameConfig",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listCategoriesByPlayer": {
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.metagame.listCategoriesByPlayer",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "httpMethod": "GET"
        }
      }
    },
    "events": {
      "methods": {
        "record": {
          "httpMethod": "POST",
          "flatPath": "games/v1/events",
          "id": "games.events.record",
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "path": "games/v1/events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listDefinitions": {
          "id": "games.events.listDefinitions",
          "description": "Returns a list of the event definitions in this application.",
          "flatPath": "games/v1/eventDefinitions",
          "path": "games/v1/eventDefinitions",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET"
        },
        "listByPlayer": {
          "httpMethod": "GET",
          "path": "games/v1/events",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.events.listByPlayer",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "flatPath": "games/v1/events"
        }
      }
    },
    "scores": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "id": "games.scores.get",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'."
        },
        "list": {
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.list",
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "httpMethod": "GET"
        },
        "submitMultiple": {
          "path": "games/v1/leaderboards/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.submitMultiple",
          "description": "Submits multiple scores to leaderboards.",
          "flatPath": "games/v1/leaderboards/scores",
          "httpMethod": "POST"
        },
        "listWindow": {
          "httpMethod": "GET",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.scores.listWindow",
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}"
        },
        "submit": {
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "id": "games.scores.submit",
          "description": "Submits a score to the specified leaderboard.",
          "path": "games/v1/leaderboards/{leaderboardId}/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST"
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "games/v1/stats",
          "id": "games.stats.get",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "path": "games/v1/stats",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "leaderboards": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "id": "games.leaderboards.get",
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards",
          "id": "games.leaderboards.list",
          "description": "Lists all the leaderboard metadata for your application.",
          "path": "games/v1/leaderboards",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    }
  },
  "description": "The Google Play Games Service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "documentationLink": "https://developers.google.com/games/",
  "version": "v1",
  "kind": "discovery#restDescription",
  "rootUrl": "https://games.googleapis.com/",
  "ownerDomain": "google.com",
  "canonicalName": "Games",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "protocol": "rest",
  "title": "Google Play Games Services API",
  "ownerName": "Google",
  "id": "games:v1",
  "basePath": "",
  "batchPath": "batch",
  "baseUrl": "https://games.googleapis.com/",
  "name": "games",
  "servicePath": ""
}