{
  "id": "games:v1",
  "ownerName": "Google",
  "documentationLink": "https://developers.google.com/games/",
  "baseUrl": "https://games.googleapis.com/",
  "protocol": "rest",
  "ownerDomain": "google.com",
  "revision": "20260423",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://games.googleapis.com/",
  "description": "The Google Play Games Service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "version": "v1",
  "basePath": "",
  "discoveryVersion": "v1",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "canonicalName": "Games",
  "title": "Google Play Games Services API",
  "servicePath": "",
  "name": "games",
  "resources": {
    "achievements": {
      "methods": {
        "unlock": {
          "path": "games/v1/achievements/{achievementId}/unlock",
          "description": "Unlocks this achievement for the currently authenticated player.",
          "id": "games.achievements.unlock",
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "increment": {
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/increment",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "id": "games.achievements.increment"
        },
        "list": {
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "path": "games/v1/players/{playerId}/achievements",
          "id": "games.achievements.list",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "setStepsAtLeast": {
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "id": "games.achievements.setStepsAtLeast",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast"
        },
        "reveal": {
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements/{achievementId}/reveal",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "id": "games.achievements.reveal"
        },
        "updateMultiple": {
          "flatPath": "games/v1/achievements/updateMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "id": "games.achievements.updateMultiple",
          "description": "Updates multiple achievements for the currently authenticated player.",
          "path": "games/v1/achievements/updateMultiple"
        }
      }
    },
    "scores": {
      "methods": {
        "submit": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "httpMethod": "POST",
          "id": "games.scores.submit",
          "description": "Submits a score to the specified leaderboard.",
          "path": "games/v1/leaderboards/{leaderboardId}/scores"
        },
        "submitMultiple": {
          "path": "games/v1/leaderboards/scores",
          "description": "Submits multiple scores to leaderboards.",
          "id": "games.scores.submitMultiple",
          "httpMethod": "POST",
          "flatPath": "games/v1/leaderboards/scores",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "id": "games.scores.list"
        },
        "listWindow": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "httpMethod": "GET",
          "id": "games.scores.listWindow",
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}"
        },
        "get": {
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "id": "games.scores.get",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "metagame": {
      "methods": {
        "getMetagameConfig": {
          "description": "Return the metagame configuration data for the calling application.",
          "path": "games/v1/metagameConfig",
          "id": "games.metagame.getMetagameConfig",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/metagameConfig"
        },
        "listCategoriesByPlayer": {
          "id": "games.metagame.listCategoriesByPlayer",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "httpMethod": "GET"
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "flatPath": "games/v1/stats",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "id": "games.stats.get",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "path": "games/v1/stats"
        }
      }
    },
    "recall": {
      "methods": {
        "retrieveTokens": {
          "httpMethod": "GET",
          "flatPath": "games/v1/recall/tokens/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "path": "games/v1/recall/tokens/{sessionId}",
          "description": "Retrieve all Recall tokens associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile.",
          "id": "games.recall.retrieveTokens"
        },
        "linkPersona": {
          "path": "games/v1/recall:linkPersona",
          "description": "Associate the PGS Player principal encoded in the provided recall session id with an in-game account",
          "id": "games.recall.linkPersona",
          "httpMethod": "POST",
          "flatPath": "games/v1/recall:linkPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ]
        },
        "lastTokenFromAllDeveloperGames": {
          "description": "Retrieve the last Recall token from all developer games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile.",
          "path": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "id": "games.recall.lastTokenFromAllDeveloperGames",
          "httpMethod": "GET",
          "flatPath": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ]
        },
        "unlinkPersona": {
          "description": "Delete a Recall token linking the PGS Player principal identified by the Recall session and an in-game account identified either by the 'persona' or by the token value.",
          "path": "games/v1/recall:unlinkPersona",
          "id": "games.recall.unlinkPersona",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/recall:unlinkPersona"
        },
        "resetPersona": {
          "path": "games/v1/recall:resetPersona",
          "description": "Delete all Recall tokens linking the given persona to any player (with or without a profile).",
          "id": "games.recall.resetPersona",
          "httpMethod": "POST",
          "flatPath": "games/v1/recall:resetPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ]
        },
        "gamesPlayerTokens": {
          "id": "games.recall.gamesPlayerTokens",
          "description": "Retrieve the Recall tokens from all requested games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have an active PGS Player profile.",
          "path": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "flatPath": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "events": {
      "methods": {
        "listDefinitions": {
          "id": "games.events.listDefinitions",
          "path": "games/v1/eventDefinitions",
          "description": "Returns a list of the event definitions in this application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/eventDefinitions",
          "httpMethod": "GET"
        },
        "listByPlayer": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/events",
          "httpMethod": "GET",
          "id": "games.events.listByPlayer",
          "path": "games/v1/events",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user."
        },
        "record": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/events",
          "path": "games/v1/events",
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "id": "games.events.record"
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "path": "games/v1/revisions/check",
          "description": "Checks whether the games client is out of date.",
          "id": "games.revisions.check",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/revisions/check"
        }
      }
    },
    "snapshots": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "path": "games/v1/snapshots/{snapshotId}",
          "id": "games.snapshots.get"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "path": "games/v1/players/{playerId}/snapshots",
          "id": "games.snapshots.list"
        }
      }
    },
    "accesstokens": {
      "methods": {
        "generatePlayGroupingApiToken": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "description": "Generates a Play Grouping API token for the PGS user identified by the attached credential.",
          "path": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "id": "games.accesstokens.generatePlayGroupingApiToken"
        },
        "generateRecallPlayGroupingApiToken": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "flatPath": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "description": "Generates a Play Grouping API token for the PGS user identified by the Recall session ID provided in the request.",
          "path": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "id": "games.accesstokens.generateRecallPlayGroupingApiToken"
        }
      }
    },
    "applications": {
      "methods": {
        "played": {
          "flatPath": "games/v1/applications/played",
          "id": "games.applications.played",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "path": "games/v1/applications/played"
        },
        "getEndPoint": {
          "flatPath": "games/v1/applications/getEndPoint",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "id": "games.applications.getEndPoint",
          "description": "Returns a URL for the requested end point type.",
          "path": "games/v1/applications/getEndPoint"
        },
        "verify": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "httpMethod": "GET",
          "id": "games.applications.verify",
          "path": "games/v1/applications/{applicationId}/verify",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for."
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/{applicationId}",
          "httpMethod": "GET",
          "id": "games.applications.get",
          "path": "games/v1/applications/{applicationId}",
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data."
        }
      }
    },
    "players": {
      "methods": {
        "get": {
          "path": "games/v1/players/{playerId}",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "id": "games.players.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}"
        },
        "getMultipleApplicationPlayerIds": {
          "id": "games.players.getMultipleApplicationPlayerIds",
          "path": "games/v1/players/me/multipleApplicationPlayerIds",
          "description": "Get the application player ids for the currently authenticated player across all requested games by the same developer as the calling application. This will only return ids for players that actually have an id (scoped or otherwise) with that game.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/me/multipleApplicationPlayerIds",
          "httpMethod": "GET"
        },
        "list": {
          "id": "games.players.list",
          "description": "Get the collection of players for the currently authenticated user.",
          "path": "games/v1/players/me/players/{collection}",
          "flatPath": "games/v1/players/me/players/{collection}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET"
        },
        "getScopedPlayerIds": {
          "httpMethod": "GET",
          "flatPath": "games/v1/players/me/scopedIds",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Retrieves scoped player identifiers for currently authenticated user.",
          "path": "games/v1/players/me/scopedIds",
          "id": "games.players.getScopedPlayerIds"
        }
      }
    },
    "leaderboards": {
      "methods": {
        "get": {
          "id": "games.leaderboards.get",
          "description": "Retrieves the metadata of the leaderboard with the given ID.",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards",
          "description": "Lists all the leaderboard metadata for your application.",
          "id": "games.leaderboards.list"
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "games/v1/achievements",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "description": "Lists all the achievement definitions for your application.",
          "path": "games/v1/achievements",
          "id": "games.achievementDefinitions.list"
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        },
        "https://www.googleapis.com/auth/androidpublisher": {
          "description": "View and manage your Google Play Developer account"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        }
      }
    }
  },
  "kind": "discovery#restDescription"
}