{
  "batchPath": "batch",
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true,
  "revision": "20260312",
  "name": "games",
  "baseUrl": "https://games.googleapis.com/",
  "discoveryVersion": "v1",
  "mtlsRootUrl": "https://games.mtls.googleapis.com/",
  "rootUrl": "https://games.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/games": {
          "description": "Create, edit, and delete your Google Play Games activity"
        },
        "https://www.googleapis.com/auth/androidpublisher": {
          "description": "View and manage your Google Play Developer account"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "See, create, and delete its own configuration data in your Google Drive"
        }
      }
    }
  },
  "version": "v1",
  "kind": "discovery#restDescription",
  "basePath": "",
  "title": "Google Play Games Services API",
  "id": "games:v1",
  "description": "The Google Play Games Service allows developers to enhance games with social leaderboards, achievements, game state, sign-in with Google, and more.",
  "canonicalName": "Games",
  "documentationLink": "https://developers.google.com/games/",
  "servicePath": "",
  "resources": {
    "metagame": {
      "methods": {
        "getMetagameConfig": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/metagameConfig",
          "description": "Return the metagame configuration data for the calling application.",
          "httpMethod": "GET",
          "id": "games.metagame.getMetagameConfig",
          "path": "games/v1/metagameConfig"
        },
        "listCategoriesByPlayer": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/categories/{collection}",
          "description": "List play data aggregated per category for the player corresponding to `playerId`.",
          "path": "games/v1/players/{playerId}/categories/{collection}",
          "id": "games.metagame.listCategoriesByPlayer"
        }
      }
    },
    "applications": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "flatPath": "games/v1/applications/{applicationId}",
          "description": "Retrieves the metadata of the application with the given ID. If the requested application is not available for the specified `platformType`, the returned response will not include any instance data.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.applications.get",
          "path": "games/v1/applications/{applicationId}"
        },
        "played": {
          "flatPath": "games/v1/applications/played",
          "description": "Indicate that the currently authenticated user is playing your application.",
          "httpMethod": "POST",
          "id": "games.applications.played",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/applications/played"
        },
        "verify": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/applications/{applicationId}/verify",
          "description": "Verifies the auth token provided with this request is for the application with the specified ID, and returns the ID of the player it was granted for.",
          "httpMethod": "GET",
          "id": "games.applications.verify",
          "path": "games/v1/applications/{applicationId}/verify"
        },
        "getEndPoint": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "flatPath": "games/v1/applications/getEndPoint",
          "description": "Returns a URL for the requested end point type.",
          "id": "games.applications.getEndPoint",
          "path": "games/v1/applications/getEndPoint"
        }
      }
    },
    "recall": {
      "methods": {
        "resetPersona": {
          "httpMethod": "POST",
          "flatPath": "games/v1/recall:resetPersona",
          "description": "Delete all Recall tokens linking the given persona to any player (with or without a profile).",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "path": "games/v1/recall:resetPersona",
          "id": "games.recall.resetPersona"
        },
        "lastTokenFromAllDeveloperGames": {
          "id": "games.recall.lastTokenFromAllDeveloperGames",
          "path": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "flatPath": "games/v1/recall/developerGamesLastPlayerToken/{sessionId}",
          "description": "Retrieve the last Recall token from all developer games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ]
        },
        "unlinkPersona": {
          "path": "games/v1/recall:unlinkPersona",
          "id": "games.recall.unlinkPersona",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "httpMethod": "POST",
          "flatPath": "games/v1/recall:unlinkPersona",
          "description": "Delete a Recall token linking the PGS Player principal identified by the Recall session and an in-game account identified either by the 'persona' or by the token value."
        },
        "linkPersona": {
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "httpMethod": "POST",
          "flatPath": "games/v1/recall:linkPersona",
          "description": "Associate the PGS Player principal encoded in the provided recall session id with an in-game account",
          "id": "games.recall.linkPersona",
          "path": "games/v1/recall:linkPersona"
        },
        "gamesPlayerTokens": {
          "flatPath": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "description": "Retrieve the Recall tokens from all requested games that is associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have an active PGS Player profile.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "path": "games/v1/recall/gamesPlayerTokens/{sessionId}",
          "id": "games.recall.gamesPlayerTokens"
        },
        "retrieveTokens": {
          "path": "games/v1/recall/tokens/{sessionId}",
          "id": "games.recall.retrieveTokens",
          "flatPath": "games/v1/recall/tokens/{sessionId}",
          "description": "Retrieve all Recall tokens associated with the PGS Player encoded in the provided recall session id. The API is only available for users that have active PGS Player profile.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ]
        }
      }
    },
    "achievementDefinitions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "flatPath": "games/v1/achievements",
          "description": "Lists all the achievement definitions for your application.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/achievements",
          "id": "games.achievementDefinitions.list"
        }
      }
    },
    "players": {
      "methods": {
        "list": {
          "id": "games.players.list",
          "path": "games/v1/players/me/players/{collection}",
          "flatPath": "games/v1/players/me/players/{collection}",
          "description": "Get the collection of players for the currently authenticated user.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "getMultipleApplicationPlayerIds": {
          "path": "games/v1/players/me/multipleApplicationPlayerIds",
          "id": "games.players.getMultipleApplicationPlayerIds",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/me/multipleApplicationPlayerIds",
          "description": "Get the application player ids for the currently authenticated player across all requested games by the same developer as the calling application. This will only return ids for players that actually have an id (scoped or otherwise) with that game.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/players/{playerId}",
          "description": "Retrieves the Player resource with the given ID. To retrieve the player for the currently authenticated user, set `playerId` to `me`.",
          "httpMethod": "GET",
          "id": "games.players.get",
          "path": "games/v1/players/{playerId}"
        },
        "getScopedPlayerIds": {
          "httpMethod": "GET",
          "flatPath": "games/v1/players/me/scopedIds",
          "description": "Retrieves scoped player identifiers for currently authenticated user.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/players/me/scopedIds",
          "id": "games.players.getScopedPlayerIds"
        }
      }
    },
    "snapshots": {
      "methods": {
        "get": {
          "flatPath": "games/v1/snapshots/{snapshotId}",
          "description": "Retrieves the metadata for a given snapshot ID.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.snapshots.get",
          "path": "games/v1/snapshots/{snapshotId}"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/snapshots",
          "description": "Retrieves a list of snapshots created by your application for the player corresponding to the player ID.",
          "path": "games/v1/players/{playerId}/snapshots",
          "id": "games.snapshots.list"
        }
      }
    },
    "leaderboards": {
      "methods": {
        "get": {
          "id": "games.leaderboards.get",
          "path": "games/v1/leaderboards/{leaderboardId}",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}",
          "description": "Retrieves the metadata of the leaderboard with the given ID."
        },
        "list": {
          "id": "games.leaderboards.list",
          "path": "games/v1/leaderboards",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards",
          "description": "Lists all the leaderboard metadata for your application.",
          "httpMethod": "GET"
        }
      }
    },
    "accesstokens": {
      "methods": {
        "generatePlayGroupingApiToken": {
          "flatPath": "games/v1/accesstokens/generatePlayGroupingApiToken",
          "description": "Generates a Play Grouping API token for the PGS user identified by the attached credential.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.accesstokens.generatePlayGroupingApiToken",
          "path": "games/v1/accesstokens/generatePlayGroupingApiToken"
        },
        "generateRecallPlayGroupingApiToken": {
          "httpMethod": "POST",
          "flatPath": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "description": "Generates a Play Grouping API token for the PGS user identified by the Recall session ID provided in the request.",
          "scopes": [
            "https://www.googleapis.com/auth/androidpublisher"
          ],
          "path": "games/v1/accesstokens/generateRecallPlayGroupingApiToken",
          "id": "games.accesstokens.generateRecallPlayGroupingApiToken"
        }
      }
    },
    "scores": {
      "methods": {
        "submitMultiple": {
          "path": "games/v1/leaderboards/scores",
          "id": "games.scores.submitMultiple",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/scores",
          "description": "Submits multiple scores to leaderboards.",
          "httpMethod": "POST"
        },
        "get": {
          "path": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "id": "games.scores.get",
          "httpMethod": "GET",
          "flatPath": "games/v1/players/{playerId}/leaderboards/{leaderboardId}/scores/{timeSpan}",
          "description": "Get high scores, and optionally ranks, in leaderboards for the currently authenticated player. For a specific time span, `leaderboardId` can be set to `ALL` to retrieve data for all leaderboards in a given time span. `NOTE: You cannot ask for 'ALL' leaderboards and 'ALL' timeSpans in the same request; only one parameter may be set to 'ALL'.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        },
        "listWindow": {
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "description": "Lists the scores in a leaderboard around (and including) a player's score.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/{leaderboardId}/window/{collection}",
          "id": "games.scores.listWindow"
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "description": "Lists the scores in a leaderboard, starting from the top.",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/leaderboards/{leaderboardId}/scores/{collection}",
          "id": "games.scores.list"
        },
        "submit": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "flatPath": "games/v1/leaderboards/{leaderboardId}/scores",
          "description": "Submits a score to the specified leaderboard.",
          "httpMethod": "POST",
          "id": "games.scores.submit",
          "path": "games/v1/leaderboards/{leaderboardId}/scores"
        }
      }
    },
    "stats": {
      "methods": {
        "get": {
          "flatPath": "games/v1/stats",
          "description": "Returns engagement and spend statistics in this application for the currently authenticated user.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/stats",
          "id": "games.stats.get"
        }
      }
    },
    "achievements": {
      "methods": {
        "increment": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/increment",
          "description": "Increments the steps of the achievement with the given ID for the currently authenticated player.",
          "id": "games.achievements.increment",
          "path": "games/v1/achievements/{achievementId}/increment"
        },
        "reveal": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/reveal",
          "description": "Sets the state of the achievement with the given ID to `REVEALED` for the currently authenticated player.",
          "path": "games/v1/achievements/{achievementId}/reveal",
          "id": "games.achievements.reveal"
        },
        "list": {
          "flatPath": "games/v1/players/{playerId}/achievements",
          "description": "Lists the progress for all your application's achievements for the currently authenticated player.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.list",
          "path": "games/v1/players/{playerId}/achievements"
        },
        "unlock": {
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "httpMethod": "POST",
          "flatPath": "games/v1/achievements/{achievementId}/unlock",
          "description": "Unlocks this achievement for the currently authenticated player.",
          "id": "games.achievements.unlock",
          "path": "games/v1/achievements/{achievementId}/unlock"
        },
        "updateMultiple": {
          "flatPath": "games/v1/achievements/updateMultiple",
          "description": "Updates multiple achievements for the currently authenticated player.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.achievements.updateMultiple",
          "path": "games/v1/achievements/updateMultiple"
        },
        "setStepsAtLeast": {
          "id": "games.achievements.setStepsAtLeast",
          "path": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "flatPath": "games/v1/achievements/{achievementId}/setStepsAtLeast",
          "description": "Sets the steps for the currently authenticated player towards unlocking an achievement. If the steps parameter is less than the current number of steps that the player already gained for the achievement, the achievement is not modified.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ]
        }
      }
    },
    "revisions": {
      "methods": {
        "check": {
          "flatPath": "games/v1/revisions/check",
          "description": "Checks whether the games client is out of date.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/revisions/check",
          "id": "games.revisions.check"
        }
      }
    },
    "events": {
      "methods": {
        "record": {
          "flatPath": "games/v1/events",
          "description": "Records a batch of changes to the number of times events have occurred for the currently authenticated user of this application.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.events.record",
          "path": "games/v1/events"
        },
        "listByPlayer": {
          "flatPath": "games/v1/events",
          "description": "Returns a list showing the current progress on events in this application for the currently authenticated user.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "path": "games/v1/events",
          "id": "games.events.listByPlayer"
        },
        "listDefinitions": {
          "flatPath": "games/v1/eventDefinitions",
          "description": "Returns a list of the event definitions in this application.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/games"
          ],
          "id": "games.events.listDefinitions",
          "path": "games/v1/eventDefinitions"
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "ownerName": "Google"
}