{
  "documentationLink": "https://developers.google.com/workspace/gmail/api/",
  "kind": "discovery#restDescription",
  "discoveryVersion": "v1",
  "id": "gmail:v1",
  "name": "gmail",
  "description": "The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.",
  "baseUrl": "https://gmail.googleapis.com/",
  "mtlsRootUrl": "https://gmail.mtls.googleapis.com/",
  "servicePath": "",
  "version": "v1",
  "ownerName": "Google",
  "rootUrl": "https://gmail.googleapis.com/",
  "canonicalName": "Gmail",
  "revision": "20260413",
  "resources": {
    "users": {
      "resources": {
        "history": {
          "methods": {
            "list": {
              "id": "gmail.users.history.list",
              "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing `historyId`).",
              "path": "gmail/v1/users/{userId}/history",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/history"
            }
          }
        },
        "labels": {
          "methods": {
            "update": {
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "PUT",
              "id": "gmail.users.labels.update",
              "description": "Updates the specified label."
            },
            "patch": {
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "PATCH",
              "id": "gmail.users.labels.patch",
              "description": "Patch the specified label.",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "list": {
              "path": "gmail/v1/users/{userId}/labels",
              "httpMethod": "GET",
              "id": "gmail.users.labels.list",
              "description": "Lists all labels in the user's mailbox.",
              "flatPath": "gmail/v1/users/{userId}/labels",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "get": {
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "GET",
              "id": "gmail.users.labels.get",
              "description": "Gets the specified label."
            },
            "delete": {
              "id": "gmail.users.labels.delete",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to.",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "DELETE"
            },
            "create": {
              "id": "gmail.users.labels.create",
              "description": "Creates a new label.",
              "path": "gmail/v1/users/{userId}/labels",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/labels"
            }
          }
        },
        "messages": {
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "id": "gmail.users.messages.attachments.get",
                  "description": "Gets the specified message attachment.",
                  "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "httpMethod": "GET"
                }
              }
            }
          },
          "methods": {
            "get": {
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "httpMethod": "GET",
              "id": "gmail.users.messages.get",
              "description": "Gets the specified message."
            },
            "batchModify": {
              "path": "gmail/v1/users/{userId}/messages/batchModify",
              "httpMethod": "POST",
              "id": "gmail.users.messages.batchModify",
              "description": "Modifies the labels on the specified messages.",
              "flatPath": "gmail/v1/users/{userId}/messages/batchModify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "list": {
              "id": "gmail.users.messages.list",
              "description": "Lists the messages in the user's mailbox. For example usage, see [List Gmail messages](https://developers.google.com/workspace/gmail/api/guides/list-messages).",
              "path": "gmail/v1/users/{userId}/messages",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages"
            },
            "modify": {
              "id": "gmail.users.messages.modify",
              "description": "Modifies the labels on the specified message.",
              "path": "gmail/v1/users/{userId}/messages/{id}/modify",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/modify"
            },
            "insert": {
              "path": "gmail/v1/users/{userId}/messages",
              "httpMethod": "POST",
              "id": "gmail.users.messages.insert",
              "supportsMediaUpload": true,
              "description": "Directly inserts a message into only this user's mailbox similar to `IMAP APPEND`, bypassing most scanning and classification. Does not send a message.",
              "flatPath": "gmail/v1/users/{userId}/messages",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "import": {
              "path": "gmail/v1/users/{userId}/messages/import",
              "httpMethod": "POST",
              "id": "gmail.users.messages.import",
              "supportsMediaUpload": true,
              "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. This method doesn't perform SPF checks, so it might not work for some spam messages, such as those attempting to perform domain spoofing. This method does not send a message. Note that the maximum size of the message is 150MB.",
              "flatPath": "gmail/v1/users/{userId}/messages/import",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "delete": {
              "id": "gmail.users.messages.delete",
              "scopes": [
                "https://mail.google.com/"
              ],
              "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer `messages.trash` instead.",
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "httpMethod": "DELETE",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}"
            },
            "batchDelete": {
              "scopes": [
                "https://mail.google.com/"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/batchDelete",
              "id": "gmail.users.messages.batchDelete",
              "description": "Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.",
              "path": "gmail/v1/users/{userId}/messages/batchDelete",
              "httpMethod": "POST"
            },
            "send": {
              "flatPath": "gmail/v1/users/{userId}/messages/send",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.send"
              ],
              "path": "gmail/v1/users/{userId}/messages/send",
              "httpMethod": "POST",
              "id": "gmail.users.messages.send",
              "supportsMediaUpload": true,
              "description": "Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc` headers. For example usage, see [Sending email](https://developers.google.com/workspace/gmail/api/guides/sending)."
            },
            "trash": {
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/trash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/messages/{id}/trash",
              "httpMethod": "POST",
              "id": "gmail.users.messages.trash",
              "description": "Moves the specified message to the trash."
            },
            "untrash": {
              "id": "gmail.users.messages.untrash",
              "description": "Removes the specified message from the trash.",
              "path": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/untrash"
            }
          }
        },
        "drafts": {
          "methods": {
            "send": {
              "id": "gmail.users.drafts.send",
              "supportsMediaUpload": true,
              "description": "Sends the specified, existing draft to the recipients in the `To`, `Cc`, and `Bcc` headers.",
              "path": "gmail/v1/users/{userId}/drafts/send",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/drafts/send"
            },
            "update": {
              "id": "gmail.users.drafts.update",
              "supportsMediaUpload": true,
              "description": "Replaces a draft's content.",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "httpMethod": "PUT",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}"
            },
            "list": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "id": "gmail.users.drafts.list",
              "description": "Lists the drafts in the user's mailbox.",
              "path": "gmail/v1/users/{userId}/drafts",
              "httpMethod": "GET"
            },
            "get": {
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "httpMethod": "GET",
              "id": "gmail.users.drafts.get",
              "description": "Gets the specified draft."
            },
            "delete": {
              "id": "gmail.users.drafts.delete",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Immediately and permanently deletes the specified draft. Does not simply trash it.",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "httpMethod": "DELETE"
            },
            "create": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "id": "gmail.users.drafts.create",
              "supportsMediaUpload": true,
              "description": "Creates a new draft with the `DRAFT` label.",
              "path": "gmail/v1/users/{userId}/drafts",
              "httpMethod": "POST"
            }
          }
        },
        "settings": {
          "resources": {
            "filters": {
              "methods": {
                "create": {
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.filters.create",
                  "description": "Creates a filter. Note: you can only create a maximum of 1,000 filters.",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "id": "gmail.users.settings.filters.list",
                  "description": "Lists the message filters of a Gmail user.",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/filters"
                },
                "get": {
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.filters.get",
                  "description": "Gets a filter."
                },
                "delete": {
                  "id": "gmail.users.settings.filters.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "description": "Immediately and permanently deletes the specified filter.",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "httpMethod": "DELETE"
                }
              }
            },
            "forwardingAddresses": {
              "methods": {
                "create": {
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.forwardingAddresses.create",
                  "description": "Creates a forwarding address. If ownership verification is required, a message will be sent to the recipient and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. This method is only available to service account clients that have been delegated domain-wide authority."
                },
                "list": {
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.forwardingAddresses.list",
                  "description": "Lists the forwarding addresses for the specified account."
                },
                "get": {
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.forwardingAddresses.get",
                  "description": "Gets the specified forwarding address.",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "delete": {
                  "id": "gmail.users.settings.forwardingAddresses.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Deletes the specified forwarding address and revokes any verification that may have been required. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "httpMethod": "DELETE",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}"
                }
              }
            },
            "sendAs": {
              "resources": {
                "smimeInfo": {
                  "methods": {
                    "list": {
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.sendAs.smimeInfo.list",
                      "description": "Lists S/MIME configs for the specified send-as alias."
                    },
                    "delete": {
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "httpMethod": "DELETE",
                      "id": "gmail.users.settings.sendAs.smimeInfo.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Deletes the specified S/MIME config for the specified send-as alias."
                    },
                    "get": {
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.sendAs.smimeInfo.get",
                      "description": "Gets the specified S/MIME config for the specified send-as alias.",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "setDefault": {
                      "id": "gmail.users.settings.sendAs.smimeInfo.setDefault",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Sets the default S/MIME config for the specified send-as alias.",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "httpMethod": "POST",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault"
                    },
                    "insert": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "id": "gmail.users.settings.sendAs.smimeInfo.insert",
                      "description": "Insert (upload) the given S/MIME config for the specified send-as alias. Note that pkcs12 format is required for the key.",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "httpMethod": "POST"
                    }
                  }
                }
              },
              "methods": {
                "update": {
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "PUT",
                  "id": "gmail.users.settings.sendAs.update",
                  "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias. Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "patch": {
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "PATCH",
                  "id": "gmail.users.settings.sendAs.patch",
                  "description": "Patch the specified send-as alias."
                },
                "list": {
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.sendAs.list",
                  "description": "Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom \"from\" aliases.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "verify": {
                  "id": "gmail.users.settings.sendAs.verify",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Sends a verification email to the specified send-as alias address. The verification status must be `pending`. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "httpMethod": "POST"
                },
                "get": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.get",
                  "description": "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection.",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "GET"
                },
                "delete": {
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "DELETE",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Deletes the specified send-as alias. Revokes any verification that may have been required for using it. This method is only available to service account clients that have been delegated domain-wide authority."
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "id": "gmail.users.settings.sendAs.create",
                  "description": "Creates a custom \"from\" send-as alias. If an SMTP MSA is specified, Gmail will attempt to connect to the SMTP service to validate the configuration before creating the alias. If ownership verification is required for the alias, a message will be sent to the email address and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. If a signature is provided, Gmail will sani[...]",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "httpMethod": "POST"
                }
              }
            },
            "cse": {
              "resources": {
                "identities": {
                  "methods": {
                    "create": {
                      "path": "gmail/v1/users/{userId}/settings/cse/identities",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.cse.identities.create",
                      "description": "Creates and configures a client-side encryption identity that's authorized to send mail from the user account. Google publishes the S/MIME certificate to a shared domain-wide directory so that people within a Google Workspace organization can encrypt and send mail to the identity. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/[...]",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "get": {
                      "id": "gmail.users.settings.cse.identities.get",
                      "description": "Retrieves a client-side encryption identity configuration. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.co[...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}"
                    },
                    "delete": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "httpMethod": "DELETE",
                      "id": "gmail.users.settings.cse.identities.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Deletes a client-side encryption identity. The authenticated user can no longer use the identity to send encrypted messages. You cannot restore the identity after you delete it. Instead, use the CreateCseIdentity method to create another identity with the same configuration. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protoc[...]"
                    },
                    "patch": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
                      "httpMethod": "PATCH",
                      "id": "gmail.users.settings.cse.identities.patch",
                      "description": "Associates a different key pair with an existing client-side encryption identity. The updated key pair must validate against Google's [S/MIME certificate profiles](https://support.google.com/a/answer/7300887). For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authori[...]"
                    },
                    "list": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities",
                      "id": "gmail.users.settings.cse.identities.list",
                      "description": "Lists the client-side encrypted identities for an authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.go[...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities",
                      "httpMethod": "GET"
                    }
                  }
                },
                "keypairs": {
                  "methods": {
                    "disable": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
                      "id": "gmail.users.settings.cse.keypairs.disable",
                      "description": "Turns off a client-side encryption key pair. The authenticated user can no longer use the key pair to decrypt incoming CSE message texts or sign outgoing CSE mail. To regain access, use the EnableCseKeyPair to turn on the key pair. After 30 days, you can permanently delete the key pair by using the ObliterateCseKeyPair method. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service a[...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
                      "httpMethod": "POST"
                    },
                    "enable": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.cse.keypairs.enable",
                      "description": "Turns on a client-side encryption key pair that was turned off. The key pair becomes active again for any associated client-side encryption identities. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth[...]"
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "id": "gmail.users.settings.cse.keypairs.create",
                      "description": "Creates and uploads a client-side encryption S/MIME public key certificate chain and private key metadata for the authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#de[...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "httpMethod": "POST"
                    },
                    "obliterate": {
                      "id": "gmail.users.settings.cse.keypairs.obliterate",
                      "description": "Deletes a client-side encryption key pair permanently and immediately. You can only permanently delete key pairs that have been turned off for more than 30 days. To turn off a key pair, use the DisableCseKeyPair method. Gmail can't restore or decrypt any messages that were encrypted by an obliterated key. Authenticated users and Google Workspace administrators lose access to reading the encrypted messages. For administrators managing identities and keypairs [...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate"
                    },
                    "get": {
                      "id": "gmail.users.settings.cse.keypairs.get",
                      "description": "Retrieves an existing client-side encryption key pair. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.com/au[...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}"
                    },
                    "list": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.cse.keypairs.list",
                      "description": "Lists client-side encryption key pairs for an authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.google[...]"
                    }
                  }
                }
              }
            },
            "delegates": {
              "methods": {
                "list": {
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.delegates.list",
                  "description": "Lists the delegates for the specified account. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "create": {
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.delegates.create",
                  "description": "Adds a delegate with its verification status set directly to `accepted`, without sending any verification email. The delegate user must be a member of the same Google Workspace organization as the delegator user. Gmail imposes limitations on the number of delegates and delegators each user in a Google Workspace organization can have. These limits depend on your organization, but in general each user can have up to 25 delegates and up to 10 delegators. Note that [...]",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "delete": {
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.delegates.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Removes the specified delegate (which can be of any verification status), and revokes any verification that may have been required for using it. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority."
                },
                "get": {
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.delegates.get",
                  "description": "Gets the specified delegate. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority."
                }
              }
            }
          },
          "methods": {
            "getPop": {
              "id": "gmail.users.settings.getPop",
              "description": "Gets POP settings.",
              "path": "gmail/v1/users/{userId}/settings/pop",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/pop"
            },
            "getLanguage": {
              "id": "gmail.users.settings.getLanguage",
              "description": "Gets language settings.",
              "path": "gmail/v1/users/{userId}/settings/language",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/language"
            },
            "updateImap": {
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "id": "gmail.users.settings.updateImap",
              "description": "Updates IMAP settings.",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "httpMethod": "PUT"
            },
            "updateVacation": {
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateVacation",
              "description": "Updates vacation responder settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updatePop": {
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "id": "gmail.users.settings.updatePop",
              "description": "Updates POP settings.",
              "path": "gmail/v1/users/{userId}/settings/pop",
              "httpMethod": "PUT"
            },
            "updateLanguage": {
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "path": "gmail/v1/users/{userId}/settings/language",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateLanguage",
              "description": "Updates language settings. If successful, the return object contains the `displayLanguage` that was saved for the user, which may differ from the value passed into the request. This is because the requested `displayLanguage` may not be directly supported by Gmail but have a close variant that is, and so the variant may be chosen and saved instead."
            },
            "getAutoForwarding": {
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getAutoForwarding",
              "description": "Gets the auto-forwarding setting for the specified account."
            },
            "getVacation": {
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getVacation",
              "description": "Gets vacation responder settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getImap": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "id": "gmail.users.settings.getImap",
              "description": "Gets IMAP settings.",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "httpMethod": "GET"
            },
            "updateAutoForwarding": {
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.sharing"
              ],
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateAutoForwarding",
              "description": "Updates the auto-forwarding setting for the specified account. A verified forwarding address must be specified when auto-forwarding is enabled. This method is only available to service account clients that have been delegated domain-wide authority."
            }
          }
        },
        "threads": {
          "methods": {
            "delete": {
              "id": "gmail.users.threads.delete",
              "scopes": [
                "https://mail.google.com/"
              ],
              "description": "Immediately and permanently deletes the specified thread. Any messages that belong to the thread are also deleted. This operation cannot be undone. Prefer `threads.trash` instead.",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "httpMethod": "DELETE"
            },
            "get": {
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "httpMethod": "GET",
              "id": "gmail.users.threads.get",
              "description": "Gets the specified thread.",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "list": {
              "path": "gmail/v1/users/{userId}/threads",
              "httpMethod": "GET",
              "id": "gmail.users.threads.list",
              "description": "Lists the threads in the user's mailbox.",
              "flatPath": "gmail/v1/users/{userId}/threads",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "modify": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/modify",
              "id": "gmail.users.threads.modify",
              "description": "Modifies the labels applied to the thread. This applies to all messages in the thread.",
              "path": "gmail/v1/users/{userId}/threads/{id}/modify",
              "httpMethod": "POST"
            },
            "trash": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/trash",
              "id": "gmail.users.threads.trash",
              "description": "Moves the specified thread to the trash. Any messages that belong to the thread are also moved to the trash.",
              "path": "gmail/v1/users/{userId}/threads/{id}/trash",
              "httpMethod": "POST"
            },
            "untrash": {
              "id": "gmail.users.threads.untrash",
              "description": "Removes the specified thread from the trash. Any messages that belong to the thread are also removed from the trash.",
              "path": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/untrash"
            }
          }
        }
      },
      "methods": {
        "getProfile": {
          "flatPath": "gmail/v1/users/{userId}/profile",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "path": "gmail/v1/users/{userId}/profile",
          "httpMethod": "GET",
          "id": "gmail.users.getProfile",
          "description": "Gets the current user's Gmail profile."
        },
        "stop": {
          "flatPath": "gmail/v1/users/{userId}/stop",
          "path": "gmail/v1/users/{userId}/stop",
          "httpMethod": "POST",
          "id": "gmail.users.stop",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "description": "Stop receiving push notifications for the given user mailbox."
        },
        "watch": {
          "flatPath": "gmail/v1/users/{userId}/watch",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "path": "gmail/v1/users/{userId}/watch",
          "httpMethod": "POST",
          "id": "gmail.users.watch",
          "description": "Set up or update a push notification watch on the given user mailbox."
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/gmail.labels": {
          "description": "See and edit your email labels"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.action": {
          "description": "View your email messages when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {
          "description": "View your email message metadata when the add-on is running"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/gmail.compose": {
          "description": "Manage drafts and send emails"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        },
        "https://www.googleapis.com/auth/gmail.modify": {
          "description": "Read, compose, and send emails from your Gmail account"
        },
        "https://www.googleapis.com/auth/gmail.settings.sharing": {
          "description": "Manage your sensitive mail settings, including who can manage your mail"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {
          "description": "View your email messages when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.send": {
          "description": "Send email on your behalf"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {
          "description": "Manage drafts and send emails when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.insert": {
          "description": "Add emails into your Gmail mailbox"
        },
        "https://www.googleapis.com/auth/gmail.metadata": {
          "description": "View your email message metadata such as labels and headers, but not the email body"
        },
        "https://www.googleapis.com/auth/gmail.settings.basic": {
          "description": "See, edit, create, or change your email settings and filters in Gmail"
        }
      }
    }
  },
  "protocol": "rest",
  "ownerDomain": "google.com",
  "title": "Gmail API",
  "basePath": "",
  "batchPath": "batch"
}