{
  "name": "gmailpostmastertools",
  "revision": "20260312",
  "canonicalName": "Postmaster Tools",
  "kind": "discovery#restDescription",
  "resources": {
    "domains": {
      "methods": {
        "get": {
          "path": "v2/{+name}",
          "flatPath": "v2/domains/{domainsId}",
          "httpMethod": "GET",
          "id": "gmailpostmastertools.domains.get",
          "scopes": [
            "https://www.googleapis.com/auth/postmaster",
            "https://www.googleapis.com/auth/postmaster.domain"
          ],
          "description": "Retrieves detailed information about a domain registered by you. Returns NOT_FOUND if the domain is not registered by you. Domain represents the metadata of a domain that has been registered within the system and linked to a user."
        },
        "getComplianceStatus": {
          "description": "Retrieves the compliance status for a given domain. Returns PERMISSION_DENIED if you don't have permission to access compliance status for the domain.",
          "scopes": [
            "https://www.googleapis.com/auth/postmaster",
            "https://www.googleapis.com/auth/postmaster.traffic.readonly"
          ],
          "id": "gmailpostmastertools.domains.getComplianceStatus",
          "httpMethod": "GET",
          "path": "v2/{+name}",
          "flatPath": "v2/domains/{domainsId}/complianceStatus"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/postmaster",
            "https://www.googleapis.com/auth/postmaster.domain"
          ],
          "description": "Retrieves a list of all domains registered by you, along with their corresponding metadata. The order of domains in the response is unspecified and non-deterministic. Newly registered domains will not necessarily be added to the end of this list.",
          "path": "v2/domains",
          "flatPath": "v2/domains",
          "id": "gmailpostmastertools.domains.list",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "domainStats": {
          "methods": {
            "query": {
              "description": "Retrieves a list of domain statistics for a given domain and time period. Returns statistics only for dates where data is available. Returns PERMISSION_DENIED if you don't have permission to access DomainStats for the domain.",
              "scopes": [
                "https://www.googleapis.com/auth/postmaster",
                "https://www.googleapis.com/auth/postmaster.traffic.readonly"
              ],
              "id": "gmailpostmastertools.domains.domainStats.query",
              "httpMethod": "POST",
              "path": "v2/{+parent}/domainStats:query",
              "flatPath": "v2/domains/{domainsId}/domainStats:query"
            }
          }
        }
      }
    },
    "domainStats": {
      "methods": {
        "batchQuery": {
          "httpMethod": "POST",
          "id": "gmailpostmastertools.domainStats.batchQuery",
          "path": "v2/domainStats:batchQuery",
          "flatPath": "v2/domainStats:batchQuery",
          "description": "Executes a batch of QueryDomainStats requests for multiple domains. Returns PERMISSION_DENIED if you don't have permission to access DomainStats for any of the requested domains.",
          "scopes": [
            "https://www.googleapis.com/auth/postmaster",
            "https://www.googleapis.com/auth/postmaster.traffic.readonly"
          ]
        }
      }
    }
  },
  "protocol": "rest",
  "title": "Gmail Postmaster Tools API",
  "baseUrl": "https://gmailpostmastertools.googleapis.com/",
  "mtlsRootUrl": "https://gmailpostmastertools.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/postmaster": {
          "description": "Get email traffic metrics, manage domains, and manage domain users for the domains you have registered with Postmaster Tools"
        },
        "https://www.googleapis.com/auth/postmaster.domain": {
          "description": "View and manage the domains you have registered with Postmaster Tools"
        },
        "https://www.googleapis.com/auth/postmaster.traffic.readonly": {
          "description": "Get email traffic metrics for the domains you have registered with Postmaster Tools"
        }
      }
    }
  },
  "discoveryVersion": "v1",
  "id": "gmailpostmastertools:v2",
  "documentationLink": "https://developers.google.com/workspace/gmail/postmaster",
  "version": "v2",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "basePath": "",
  "servicePath": "",
  "rootUrl": "https://gmailpostmastertools.googleapis.com/",
  "description": "The Postmaster Tools API is a RESTful API that provides programmatic access to email traffic metrics (like spam reports, delivery errors etc) otherwise available through the Gmail Postmaster Tools UI currently.",
  "ownerName": "Google",
  "ownerDomain": "google.com"
}