{
  "canonicalName": "Gmail",
  "servicePath": "",
  "ownerName": "Google",
  "baseUrl": "https://gmail.googleapis.com/",
  "basePath": "",
  "version": "v1",
  "ownerDomain": "google.com",
  "mtlsRootUrl": "https://gmail.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "description": "The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.",
  "batchPath": "batch",
  "protocol": "rest",
  "id": "gmail:v1",
  "resources": {
    "users": {
      "resources": {
        "messages": {
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "description": "Gets the specified message attachment.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly"
                  ],
                  "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "httpMethod": "GET",
                  "id": "gmail.users.messages.attachments.get",
                  "flatPath": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}"
                }
              }
            }
          },
          "methods": {
            "insert": {
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "id": "gmail.users.messages.insert",
              "flatPath": "gmail/v1/users/{userId}/messages",
              "path": "gmail/v1/users/{userId}/messages",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Directly inserts a message into only this user's mailbox similar to `IMAP APPEND`, bypassing most scanning and classification. Does not send a message."
            },
            "batchDelete": {
              "path": "gmail/v1/users/{userId}/messages/batchDelete",
              "httpMethod": "POST",
              "id": "gmail.users.messages.batchDelete",
              "flatPath": "gmail/v1/users/{userId}/messages/batchDelete",
              "description": "Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.",
              "scopes": [
                "https://mail.google.com/"
              ]
            },
            "import": {
              "id": "gmail.users.messages.import",
              "flatPath": "gmail/v1/users/{userId}/messages/import",
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "path": "gmail/v1/users/{userId}/messages/import",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. This method doesn't perform SPF checks, so it might not work for some spam messages, such as those attempting to perform domain spoofing. This method does not send a message. Note that the maximum size of the message is 150MB."
            },
            "get": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "description": "Gets the specified message.",
              "id": "gmail.users.messages.get",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/messages/{id}"
            },
            "send": {
              "path": "gmail/v1/users/{userId}/messages/send",
              "id": "gmail.users.messages.send",
              "flatPath": "gmail/v1/users/{userId}/messages/send",
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "description": "Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc` headers. For example usage, see [Sending email](https://developers.google.com/workspace/gmail/api/guides/sending).",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.send"
              ]
            },
            "list": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "description": "Lists the messages in the user's mailbox. For example usage, see [List Gmail messages](https://developers.google.com/workspace/gmail/api/guides/list-messages).",
              "id": "gmail.users.messages.list",
              "flatPath": "gmail/v1/users/{userId}/messages",
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/messages"
            },
            "untrash": {
              "path": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "id": "gmail.users.messages.untrash",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "httpMethod": "POST",
              "description": "Removes the specified message from the trash.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "trash": {
              "description": "Moves the specified message to the trash.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/messages/{id}/trash",
              "id": "gmail.users.messages.trash",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/trash",
              "httpMethod": "POST"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "gmail.users.messages.delete",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "scopes": [
                "https://mail.google.com/"
              ],
              "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer `messages.trash` instead.",
              "path": "gmail/v1/users/{userId}/messages/{id}"
            },
            "batchModify": {
              "path": "gmail/v1/users/{userId}/messages/batchModify",
              "httpMethod": "POST",
              "id": "gmail.users.messages.batchModify",
              "flatPath": "gmail/v1/users/{userId}/messages/batchModify",
              "description": "Modifies the labels on the specified messages.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "modify": {
              "path": "gmail/v1/users/{userId}/messages/{id}/modify",
              "id": "gmail.users.messages.modify",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/modify",
              "httpMethod": "POST",
              "description": "Modifies the labels on the specified message.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            }
          }
        },
        "threads": {
          "methods": {
            "delete": {
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "description": "Immediately and permanently deletes the specified thread. Any messages that belong to the thread are also deleted. This operation cannot be undone. Prefer `threads.trash` instead.",
              "scopes": [
                "https://mail.google.com/"
              ],
              "id": "gmail.users.threads.delete",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "httpMethod": "DELETE"
            },
            "modify": {
              "path": "gmail/v1/users/{userId}/threads/{id}/modify",
              "id": "gmail.users.threads.modify",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/modify",
              "httpMethod": "POST",
              "description": "Modifies the labels applied to the thread. This applies to all messages in the thread.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "list": {
              "id": "gmail.users.threads.list",
              "flatPath": "gmail/v1/users/{userId}/threads",
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/threads",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "description": "Lists the threads in the user's mailbox."
            },
            "get": {
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "httpMethod": "GET",
              "id": "gmail.users.threads.get",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "description": "Gets the specified thread.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "trash": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Moves the specified thread to the trash. Any messages that belong to the thread are also moved to the trash.",
              "id": "gmail.users.threads.trash",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/trash",
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/threads/{id}/trash"
            },
            "untrash": {
              "httpMethod": "POST",
              "id": "gmail.users.threads.untrash",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "path": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Removes the specified thread from the trash. Any messages that belong to the thread are also removed from the trash."
            }
          }
        },
        "drafts": {
          "methods": {
            "create": {
              "description": "Creates a new draft with the `DRAFT` label.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/drafts",
              "id": "gmail.users.drafts.create",
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "httpMethod": "POST",
              "supportsMediaUpload": true
            },
            "list": {
              "description": "Lists the drafts in the user's mailbox.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/drafts",
              "httpMethod": "GET",
              "id": "gmail.users.drafts.list",
              "flatPath": "gmail/v1/users/{userId}/drafts"
            },
            "get": {
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "id": "gmail.users.drafts.get",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "httpMethod": "GET",
              "description": "Gets the specified draft.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "send": {
              "path": "gmail/v1/users/{userId}/drafts/send",
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "id": "gmail.users.drafts.send",
              "flatPath": "gmail/v1/users/{userId}/drafts/send",
              "description": "Sends the specified, existing draft to the recipients in the `To`, `Cc`, and `Bcc` headers.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "delete": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "DELETE",
              "id": "gmail.users.drafts.delete",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "description": "Immediately and permanently deletes the specified draft. Does not simply trash it."
            },
            "update": {
              "httpMethod": "PUT",
              "supportsMediaUpload": true,
              "id": "gmail.users.drafts.update",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Replaces a draft's content."
            }
          }
        },
        "labels": {
          "methods": {
            "delete": {
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "DELETE",
              "id": "gmail.users.labels.delete",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}"
            },
            "update": {
              "httpMethod": "PUT",
              "id": "gmail.users.labels.update",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Updates the specified label."
            },
            "create": {
              "description": "Creates a new label.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/labels",
              "httpMethod": "POST",
              "id": "gmail.users.labels.create",
              "flatPath": "gmail/v1/users/{userId}/labels"
            },
            "list": {
              "description": "Lists all labels in the user's mailbox.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "path": "gmail/v1/users/{userId}/labels",
              "httpMethod": "GET",
              "id": "gmail.users.labels.list",
              "flatPath": "gmail/v1/users/{userId}/labels"
            },
            "get": {
              "id": "gmail.users.labels.get",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "description": "Gets the specified label."
            },
            "patch": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Patch the specified label.",
              "id": "gmail.users.labels.patch",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "PATCH",
              "path": "gmail/v1/users/{userId}/labels/{id}"
            }
          }
        },
        "history": {
          "methods": {
            "list": {
              "path": "gmail/v1/users/{userId}/history",
              "id": "gmail.users.history.list",
              "flatPath": "gmail/v1/users/{userId}/history",
              "httpMethod": "GET",
              "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing `historyId`).",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            }
          }
        },
        "settings": {
          "resources": {
            "delegates": {
              "methods": {
                "get": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "description": "Gets the specified delegate. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.delegates.get",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.delegates.delete",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "description": "Removes the specified delegate (which can be of any verification status), and revokes any verification that may have been required for using it. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority."
                },
                "list": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "description": "Lists the delegates for the specified account. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.delegates.list",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "path": "gmail/v1/users/{userId}/settings/delegates"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Adds a delegate with its verification status set directly to `accepted`, without sending any verification email. The delegate user must be a member of the same Google Workspace organization as the delegator user. Gmail imposes limitations on the number of delegates and delegators each user in a Google Workspace organization can have. These limits depend on your organization, but in general each user can have up to 25 delegates and up to 10 delegators. Note that [...]",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.delegates.create",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "path": "gmail/v1/users/{userId}/settings/delegates"
                }
              }
            },
            "forwardingAddresses": {
              "methods": {
                "get": {
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "id": "gmail.users.settings.forwardingAddresses.get",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "httpMethod": "GET",
                  "description": "Gets the specified forwarding address.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "delete": {
                  "id": "gmail.users.settings.forwardingAddresses.delete",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Deletes the specified forwarding address and revokes any verification that may have been required. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}"
                },
                "list": {
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "id": "gmail.users.settings.forwardingAddresses.list",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "httpMethod": "GET",
                  "description": "Lists the forwarding addresses for the specified account.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.forwardingAddresses.create",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Creates a forwarding address. If ownership verification is required, a message will be sent to the recipient and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. This method is only available to service account clients that have been delegated domain-wide authority."
                }
              }
            },
            "filters": {
              "methods": {
                "get": {
                  "description": "Gets a filter.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "id": "gmail.users.settings.filters.get",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "httpMethod": "GET"
                },
                "delete": {
                  "description": "Immediately and permanently deletes the specified filter.",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "id": "gmail.users.settings.filters.delete",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "id": "gmail.users.settings.filters.list",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "httpMethod": "GET",
                  "description": "Lists the message filters of a Gmail user.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "create": {
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.filters.create",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "description": "Creates a filter. Note: you can only create a maximum of 1,000 filters.",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                }
              }
            },
            "cse": {
              "resources": {
                "identities": {
                  "methods": {
                    "delete": {
                      "httpMethod": "DELETE",
                      "id": "gmail.users.settings.cse.identities.delete",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Deletes a client-side encryption identity. The authenticated user can no longer use the identity to send encrypted messages. You cannot restore the identity after you delete it. Instead, use the CreateCseIdentity method to create another identity with the same configuration. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protoc[...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}"
                    },
                    "get": {
                      "id": "gmail.users.settings.cse.identities.get",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "httpMethod": "GET",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Retrieves a client-side encryption identity configuration. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.co[...]"
                    },
                    "patch": {
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
                      "httpMethod": "PATCH",
                      "id": "gmail.users.settings.cse.identities.patch",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
                      "description": "Associates a different key pair with an existing client-side encryption identity. The updated key pair must validate against Google's [S/MIME certificate profiles](https://support.google.com/a/answer/7300887). For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authori[...]",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "create": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Creates and configures a client-side encryption identity that's authorized to send mail from the user account. Google publishes the S/MIME certificate to a shared domain-wide directory so that people within a Google Workspace organization can encrypt and send mail to the identity. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/[...]",
                      "id": "gmail.users.settings.cse.identities.create",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities",
                      "httpMethod": "POST",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities"
                    },
                    "list": {
                      "path": "gmail/v1/users/{userId}/settings/cse/identities",
                      "id": "gmail.users.settings.cse.identities.list",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities",
                      "httpMethod": "GET",
                      "description": "Lists the client-side encrypted identities for an authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.go[...]",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    }
                  }
                },
                "keypairs": {
                  "methods": {
                    "create": {
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.cse.keypairs.create",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Creates and uploads a client-side encryption S/MIME public key certificate chain and private key metadata for the authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#de[...]"
                    },
                    "list": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Lists client-side encryption key pairs for an authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.google[...]",
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.cse.keypairs.list",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs"
                    },
                    "get": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Retrieves an existing client-side encryption key pair. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.com/au[...]",
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.cse.keypairs.get",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}"
                    },
                    "disable": {
                      "id": "gmail.users.settings.cse.keypairs.disable",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
                      "httpMethod": "POST",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Turns off a client-side encryption key pair. The authenticated user can no longer use the key pair to decrypt incoming CSE message texts or sign outgoing CSE mail. To regain access, use the EnableCseKeyPair to turn on the key pair. After 30 days, you can permanently delete the key pair by using the ObliterateCseKeyPair method. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service a[...]"
                    },
                    "enable": {
                      "description": "Turns on a client-side encryption key pair that was turned off. The key pair becomes active again for any associated client-side encryption identities. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth[...]",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "id": "gmail.users.settings.cse.keypairs.enable",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "httpMethod": "POST"
                    },
                    "obliterate": {
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
                      "id": "gmail.users.settings.cse.keypairs.obliterate",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
                      "httpMethod": "POST",
                      "description": "Deletes a client-side encryption key pair permanently and immediately. You can only permanently delete key pairs that have been turned off for more than 30 days. To turn off a key pair, use the DisableCseKeyPair method. Gmail can't restore or decrypt any messages that were encrypted by an obliterated key. Authenticated users and Google Workspace administrators lose access to reading the encrypted messages. For administrators managing identities and keypairs [...]",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    }
                  }
                }
              }
            },
            "sendAs": {
              "resources": {
                "smimeInfo": {
                  "methods": {
                    "get": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Gets the specified S/MIME config for the specified send-as alias.",
                      "id": "gmail.users.settings.sendAs.smimeInfo.get",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "httpMethod": "GET",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}"
                    },
                    "insert": {
                      "id": "gmail.users.settings.sendAs.smimeInfo.insert",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "httpMethod": "POST",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Insert (upload) the given S/MIME config for the specified send-as alias. Note that pkcs12 format is required for the key."
                    },
                    "list": {
                      "id": "gmail.users.settings.sendAs.smimeInfo.list",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "httpMethod": "GET",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Lists S/MIME configs for the specified send-as alias."
                    },
                    "delete": {
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "description": "Deletes the specified S/MIME config for the specified send-as alias.",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "id": "gmail.users.settings.sendAs.smimeInfo.delete",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "httpMethod": "DELETE"
                    },
                    "setDefault": {
                      "id": "gmail.users.settings.sendAs.smimeInfo.setDefault",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Sets the default S/MIME config for the specified send-as alias.",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault"
                    }
                  }
                }
              },
              "methods": {
                "delete": {
                  "description": "Deletes the specified send-as alias. Revokes any verification that may have been required for using it. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.delete",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "update": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias. Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.",
                  "id": "gmail.users.settings.sendAs.update",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "PUT",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "list": {
                  "description": "Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom \"from\" aliases.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.sendAs.list",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs"
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.sendAs.create",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Creates a custom \"from\" send-as alias. If an SMTP MSA is specified, Gmail will attempt to connect to the SMTP service to validate the configuration before creating the alias. If ownership verification is required for the alias, a message will be sent to the email address and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. If a signature is provided, Gmail will sani[...]"
                },
                "verify": {
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "description": "Sends a verification email to the specified send-as alias address. The verification status must be `pending`. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.sendAs.verify",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "httpMethod": "POST"
                },
                "get": {
                  "description": "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.sendAs.get",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "patch": {
                  "httpMethod": "PATCH",
                  "id": "gmail.users.settings.sendAs.patch",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Patch the specified send-as alias."
                }
              }
            }
          },
          "methods": {
            "getLanguage": {
              "description": "Gets language settings.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "path": "gmail/v1/users/{userId}/settings/language",
              "id": "gmail.users.settings.getLanguage",
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "httpMethod": "GET"
            },
            "updatePop": {
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Updates POP settings.",
              "id": "gmail.users.settings.updatePop",
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "httpMethod": "PUT",
              "path": "gmail/v1/users/{userId}/settings/pop"
            },
            "updateImap": {
              "description": "Updates IMAP settings.",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "path": "gmail/v1/users/{userId}/settings/imap",
              "id": "gmail.users.settings.updateImap",
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "httpMethod": "PUT"
            },
            "getAutoForwarding": {
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "id": "gmail.users.settings.getAutoForwarding",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "httpMethod": "GET",
              "description": "Gets the auto-forwarding setting for the specified account.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updateAutoForwarding": {
              "description": "Updates the auto-forwarding setting for the specified account. A verified forwarding address must be specified when auto-forwarding is enabled. This method is only available to service account clients that have been delegated domain-wide authority.",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.sharing"
              ],
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "id": "gmail.users.settings.updateAutoForwarding",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "httpMethod": "PUT"
            },
            "getImap": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Gets IMAP settings.",
              "id": "gmail.users.settings.getImap",
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/settings/imap"
            },
            "getPop": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Gets POP settings.",
              "id": "gmail.users.settings.getPop",
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/settings/pop"
            },
            "getVacation": {
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getVacation",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "description": "Gets vacation responder settings.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updateLanguage": {
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Updates language settings. If successful, the return object contains the `displayLanguage` that was saved for the user, which may differ from the value passed into the request. This is because the requested `displayLanguage` may not be directly supported by Gmail but have a close variant that is, and so the variant may be chosen and saved instead.",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateLanguage",
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "path": "gmail/v1/users/{userId}/settings/language"
            },
            "updateVacation": {
              "description": "Updates vacation responder settings.",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "id": "gmail.users.settings.updateVacation",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "httpMethod": "PUT"
            }
          }
        }
      },
      "methods": {
        "getProfile": {
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "description": "Gets the current user's Gmail profile.",
          "httpMethod": "GET",
          "id": "gmail.users.getProfile",
          "flatPath": "gmail/v1/users/{userId}/profile",
          "path": "gmail/v1/users/{userId}/profile"
        },
        "stop": {
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "id": "gmail.users.stop",
          "flatPath": "gmail/v1/users/{userId}/stop",
          "httpMethod": "POST",
          "path": "gmail/v1/users/{userId}/stop",
          "description": "Stop receiving push notifications for the given user mailbox."
        },
        "watch": {
          "httpMethod": "POST",
          "id": "gmail.users.watch",
          "flatPath": "gmail/v1/users/{userId}/watch",
          "path": "gmail/v1/users/{userId}/watch",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "description": "Set up or update a push notification watch on the given user mailbox."
        }
      }
    }
  },
  "rootUrl": "https://gmail.googleapis.com/",
  "title": "Gmail API",
  "documentationLink": "https://developers.google.com/workspace/gmail/api/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {
          "description": "Manage drafts and send emails when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.action": {
          "description": "View your email messages when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        },
        "https://www.googleapis.com/auth/gmail.settings.basic": {
          "description": "See, edit, create, or change your email settings and filters in Gmail"
        },
        "https://www.googleapis.com/auth/gmail.modify": {
          "description": "Read, compose, and send emails from your Gmail account"
        },
        "https://www.googleapis.com/auth/gmail.settings.sharing": {
          "description": "Manage your sensitive mail settings, including who can manage your mail"
        },
        "https://www.googleapis.com/auth/gmail.metadata": {
          "description": "View your email message metadata such as labels and headers, but not the email body"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/gmail.compose": {
          "description": "Manage drafts and send emails"
        },
        "https://www.googleapis.com/auth/gmail.insert": {
          "description": "Add emails into your Gmail mailbox"
        },
        "https://www.googleapis.com/auth/gmail.labels": {
          "description": "See and edit your email labels"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {
          "description": "View your email messages when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.send": {
          "description": "Send email on your behalf"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {
          "description": "View your email message metadata when the add-on is running"
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "name": "gmail",
  "revision": "20260309"
}