{
  "mtlsRootUrl": "https://gmail.mtls.googleapis.com/",
  "discoveryVersion": "v1",
  "name": "gmail",
  "id": "gmail:v1",
  "baseUrl": "https://gmail.googleapis.com/",
  "revision": "20260427",
  "canonicalName": "Gmail",
  "title": "Gmail API",
  "resources": {
    "users": {
      "methods": {
        "getProfile": {
          "id": "gmail.users.getProfile",
          "httpMethod": "GET",
          "flatPath": "gmail/v1/users/{userId}/profile",
          "description": "Gets the current user's Gmail profile.",
          "path": "gmail/v1/users/{userId}/profile",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        },
        "stop": {
          "flatPath": "gmail/v1/users/{userId}/stop",
          "path": "gmail/v1/users/{userId}/stop",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "description": "Turn off push notification delivery for the given user mailbox. For more information, see [Configure push notifications in Gmail API](https://developers.google.com/workspace/gmail/api/guides/push).",
          "id": "gmail.users.stop",
          "httpMethod": "POST"
        },
        "watch": {
          "httpMethod": "POST",
          "id": "gmail.users.watch",
          "path": "gmail/v1/users/{userId}/watch",
          "description": "Set up or update a push notification watch on the given user mailbox. For more information, see [Configure push notifications in Gmail API](https://developers.google.com/workspace/gmail/api/guides/push).",
          "flatPath": "gmail/v1/users/{userId}/watch",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        }
      },
      "resources": {
        "drafts": {
          "methods": {
            "update": {
              "supportsMediaUpload": true,
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "PUT",
              "id": "gmail.users.drafts.update",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "description": "Replaces a draft's content. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts).",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}"
            },
            "get": {
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "description": "Gets the specified draft. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts).",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "id": "gmail.users.drafts.get",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "delete": {
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "description": "Immediately and permanently deletes the specified draft. Does not simply trash it. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts).",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.drafts.delete",
              "httpMethod": "DELETE"
            },
            "create": {
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "description": "Creates a draft with the `DRAFT` label. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts).",
              "path": "gmail/v1/users/{userId}/drafts",
              "id": "gmail.users.drafts.create",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "supportsMediaUpload": true
            },
            "list": {
              "id": "gmail.users.drafts.list",
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "path": "gmail/v1/users/{userId}/drafts",
              "description": "Lists the drafts in the user's mailbox. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts).",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "send": {
              "supportsMediaUpload": true,
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.drafts.send",
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/drafts/send",
              "path": "gmail/v1/users/{userId}/drafts/send",
              "description": "Sends the specified, existing draft to the recipients in the `To`, `Cc`, and `Bcc` headers. For more information, see [Create and send draft emails](https://developers.google.com/workspace/gmail/api/guides/drafts)."
            }
          }
        },
        "history": {
          "methods": {
            "list": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/history",
              "path": "gmail/v1/users/{userId}/history",
              "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing `historyId`). For more information, see [Synchronize clients with Gmail](https://developers.google.com/workspace/gmail/api/guides/sync).",
              "id": "gmail.users.history.list",
              "httpMethod": "GET"
            }
          }
        },
        "messages": {
          "methods": {
            "trash": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "id": "gmail.users.messages.trash",
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/trash",
              "path": "gmail/v1/users/{userId}/messages/{id}/trash",
              "description": "Moves the specified message to the trash."
            },
            "untrash": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "description": "Removes the specified message from the trash.",
              "path": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "id": "gmail.users.messages.untrash",
              "httpMethod": "POST"
            },
            "batchDelete": {
              "scopes": [
                "https://mail.google.com/"
              ],
              "httpMethod": "POST",
              "id": "gmail.users.messages.batchDelete",
              "path": "gmail/v1/users/{userId}/messages/batchDelete",
              "description": "Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.",
              "flatPath": "gmail/v1/users/{userId}/messages/batchDelete"
            },
            "delete": {
              "httpMethod": "DELETE",
              "id": "gmail.users.messages.delete",
              "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer `messages.trash` instead.",
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "scopes": [
                "https://mail.google.com/"
              ],
              "flatPath": "gmail/v1/users/{userId}/messages/{id}"
            },
            "send": {
              "supportsMediaUpload": true,
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.send"
              ],
              "id": "gmail.users.messages.send",
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/messages/send",
              "description": "Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc` headers. For more information, see [Create and send email messages](https://developers.google.com/workspace/gmail/api/guides/sending).",
              "path": "gmail/v1/users/{userId}/messages/send"
            },
            "batchModify": {
              "id": "gmail.users.messages.batchModify",
              "httpMethod": "POST",
              "flatPath": "gmail/v1/users/{userId}/messages/batchModify",
              "description": "Modifies the labels on the specified messages.",
              "path": "gmail/v1/users/{userId}/messages/batchModify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "get": {
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "description": "Gets the specified message.",
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "id": "gmail.users.messages.get",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "modify": {
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/modify",
              "description": "Modifies the labels on the specified message.",
              "path": "gmail/v1/users/{userId}/messages/{id}/modify",
              "id": "gmail.users.messages.modify",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "import": {
              "httpMethod": "POST",
              "id": "gmail.users.messages.import",
              "path": "gmail/v1/users/{userId}/messages/import",
              "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. This method doesn't perform SPF checks, so it might not work for some spam messages, such as those attempting to perform domain spoofing. This method does not send a message. Note that the maximum size of the message is 150 MB.",
              "flatPath": "gmail/v1/users/{userId}/messages/import",
              "supportsMediaUpload": true,
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "insert": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "supportsMediaUpload": true,
              "flatPath": "gmail/v1/users/{userId}/messages",
              "path": "gmail/v1/users/{userId}/messages",
              "description": "Directly inserts a message into only this user's mailbox similar to `IMAP APPEND`, bypassing most scanning and classification. Does not send a message. For more information, see [Create and send email messages](https://developers.google.com/workspace/gmail/api/guides/sending).",
              "id": "gmail.users.messages.insert",
              "httpMethod": "POST"
            },
            "list": {
              "flatPath": "gmail/v1/users/{userId}/messages",
              "description": "Lists the messages in the user's mailbox. For more information, see [List Gmail messages](https://developers.google.com/workspace/gmail/api/guides/list-messages).",
              "path": "gmail/v1/users/{userId}/messages",
              "id": "gmail.users.messages.list",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            }
          },
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "id": "gmail.users.messages.attachments.get",
                  "description": "Gets the specified message attachment.",
                  "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "flatPath": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly"
                  ]
                }
              }
            }
          }
        },
        "threads": {
          "methods": {
            "delete": {
              "id": "gmail.users.threads.delete",
              "httpMethod": "DELETE",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "scopes": [
                "https://mail.google.com/"
              ],
              "description": "Immediately and permanently deletes the specified thread. Any messages that belong to the thread are also deleted. This operation cannot be undone. Prefer `threads.trash` instead. For more information, see [Manage threads](https://developers.google.com/workspace/gmail/api/guides/threads)."
            },
            "get": {
              "httpMethod": "GET",
              "id": "gmail.users.threads.get",
              "description": "Gets the specified thread. For more information, see [Manage threads](https://developers.google.com/workspace/gmail/api/guides/threads).",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "modify": {
              "httpMethod": "POST",
              "id": "gmail.users.threads.modify",
              "path": "gmail/v1/users/{userId}/threads/{id}/modify",
              "description": "Modifies the labels applied to the thread. This applies to all messages in the thread. For more information, see [Manage threads](https://developers.google.com/workspace/gmail/api/guides/threads).",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/modify",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "untrash": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Removes the specified thread from the trash. Any messages that belong to the thread are also removed from the trash. For more information, see [Manage threads](https://developers.google.com/workspace/gmail/api/guides/threads).",
              "path": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "httpMethod": "POST",
              "id": "gmail.users.threads.untrash"
            },
            "trash": {
              "path": "gmail/v1/users/{userId}/threads/{id}/trash",
              "description": "Moves the specified thread to the trash. Any messages that belong to the thread are also moved to the trash. For more information, see [Manage threads](https://developers.google.com/workspace/gmail/api/guides/threads).",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/trash",
              "httpMethod": "POST",
              "id": "gmail.users.threads.trash",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "list": {
              "flatPath": "gmail/v1/users/{userId}/threads",
              "path": "gmail/v1/users/{userId}/threads",
              "description": "Lists the threads in the user's mailbox. For more information, see [Manage threads](https://developers.google.com/workspace/gmail/api/guides/threads).",
              "id": "gmail.users.threads.list",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            }
          }
        },
        "settings": {
          "methods": {
            "getAutoForwarding": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET",
              "id": "gmail.users.settings.getAutoForwarding",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "description": "Gets the auto-forwarding setting for the specified account. For more information, see [Manage email forwarding](https://developers.google.com/workspace/gmail/api/guides/forwarding_settings).",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding"
            },
            "updateLanguage": {
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "path": "gmail/v1/users/{userId}/settings/language",
              "description": "Updates language settings. For more information, see [Manage language settings](https://developers.google.com/workspace/gmail/api/guides/language-settings). If successful, the return object contains the `displayLanguage` that was saved for the user, which may differ from the value passed into the request. This is because the requested `displayLanguage` may not be directly supported by Gmail but have a close variant that is, and so the variant may be chosen and saved[...]",
              "id": "gmail.users.settings.updateLanguage",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getImap": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Gets IMAP settings. For more information, see [Configure POP and IMAP settings with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/pop_imap_settings).",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getImap"
            },
            "updateImap": {
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "description": "Updates IMAP settings. For more information, see [Configure POP and IMAP settings with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/pop_imap_settings).",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "id": "gmail.users.settings.updateImap",
              "httpMethod": "PUT"
            },
            "getLanguage": {
              "httpMethod": "GET",
              "id": "gmail.users.settings.getLanguage",
              "path": "gmail/v1/users/{userId}/settings/language",
              "description": "Gets language settings. For more information, see [Manage language settings](https://developers.google.com/workspace/gmail/api/guides/language-settings).",
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "updateAutoForwarding": {
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateAutoForwarding",
              "description": "Updates the auto-forwarding setting for the specified account. A verified forwarding address must be specified when auto-forwarding is enabled. For more information, see [Manage email forwarding](https://developers.google.com/workspace/gmail/api/guides/forwarding_settings). This method is only available to service account clients that have been delegated domain-wide authority.",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.sharing"
              ]
            },
            "updatePop": {
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updatePop",
              "description": "Updates POP settings. For more information, see [Configure POP and IMAP settings with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/pop_imap_settings).",
              "path": "gmail/v1/users/{userId}/settings/pop",
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            },
            "getVacation": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET",
              "id": "gmail.users.settings.getVacation",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "description": "Gets vacation responder settings. For more information, see [Manage vacation settings with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/vacation_settings).",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation"
            },
            "getPop": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "path": "gmail/v1/users/{userId}/settings/pop",
              "description": "Gets POP settings. For more information, see [Configure POP and IMAP settings with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/pop_imap_settings).",
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "httpMethod": "GET",
              "id": "gmail.users.settings.getPop"
            },
            "updateVacation": {
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "description": "Updates vacation responder settings. For more information, see [Manage vacation settings with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/vacation_settings).",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "httpMethod": "PUT",
              "id": "gmail.users.settings.updateVacation",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ]
            }
          },
          "resources": {
            "sendAs": {
              "resources": {
                "smimeInfo": {
                  "methods": {
                    "get": {
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "description": "Gets the specified S/MIME config for the specified send-as alias. For more information, see [Manage S/MIME certificates with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).",
                      "id": "gmail.users.settings.sendAs.smimeInfo.get",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "delete": {
                      "description": "Deletes the specified S/MIME config for the specified send-as alias. For more information, see [Manage S/MIME certificates with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "httpMethod": "DELETE",
                      "id": "gmail.users.settings.sendAs.smimeInfo.delete"
                    },
                    "setDefault": {
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.sendAs.smimeInfo.setDefault",
                      "description": "Sets the default S/MIME config for the specified send-as alias. For more information, see [Manage S/MIME certificates with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault"
                    },
                    "list": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "description": "Lists S/MIME configs for the specified send-as alias. For more information, see [Manage S/MIME certificates with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).",
                      "id": "gmail.users.settings.sendAs.smimeInfo.list",
                      "httpMethod": "GET"
                    },
                    "insert": {
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "description": "Insert (upload) the given S/MIME config for the specified send-as alias. Note that `pkcs12` format is required for the key. For more information, see [Manage S/MIME certificates with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/smime_certs).",
                      "id": "gmail.users.settings.sendAs.smimeInfo.insert",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    }
                  }
                }
              },
              "methods": {
                "update": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.sendAs.update",
                  "httpMethod": "PUT",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias. For more information, see [Manage aliases and signatures with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/alias_and_signature_settings). Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "verify": {
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.sendAs.verify",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Sends a verification email to the specified send-as alias address. The verification status must be `pending`. For more information, see [Manage aliases and signatures with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/alias_and_signature_settings). This method is only available to service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify"
                },
                "get": {
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.sendAs.get",
                  "description": "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection. For more information, see [Manage aliases and signatures with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/alias_and_signature_settings).",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "create": {
                  "description": "Creates a custom \"from\" send-as alias. If an SMTP MSA is specified, Gmail will attempt to connect to the SMTP service to validate the configuration before creating the alias. If ownership verification is required for the alias, a message will be sent to the email address and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. If a signature is provided, Gmail will sani[...]",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.sendAs.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "delete": {
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "description": "Deletes the specified send-as alias. Revokes any verification that may have been required for using it. For more information, see [Manage aliases and signatures with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/alias_and_signature_settings). This method is only available to service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.sendAs.delete",
                  "httpMethod": "DELETE"
                },
                "patch": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Patch the specified send-as alias. For more information, see [Manage aliases and signatures with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/alias_and_signature_settings).",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "PATCH",
                  "id": "gmail.users.settings.sendAs.patch"
                },
                "list": {
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "description": "Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom \"from\" aliases. For more information, see [Manage aliases and signatures with the Gmail API](https://developers.google.com/workspace/gmail/api/guides/alias_and_signature_settings).",
                  "id": "gmail.users.settings.sendAs.list",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                }
              }
            },
            "forwardingAddresses": {
              "methods": {
                "create": {
                  "description": "Creates a forwarding address. If ownership verification is required, a message will be sent to the recipient and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. For more information, see [Manage email forwarding](https://developers.google.com/workspace/gmail/api/guides/forwarding_settings). This method is only available to service account clients that have been deleg[...]",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.forwardingAddresses.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "delete": {
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "description": "Deletes the specified forwarding address and revokes any verification that may have been required. For more information, see [Manage email forwarding](https://developers.google.com/workspace/gmail/api/guides/forwarding_settings). This method is only available to service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "id": "gmail.users.settings.forwardingAddresses.delete",
                  "httpMethod": "DELETE"
                },
                "get": {
                  "description": "Gets the specified forwarding address. For more information, see [Manage email forwarding](https://developers.google.com/workspace/gmail/api/guides/forwarding_settings).",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.forwardingAddresses.get",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "description": "Lists the forwarding addresses for the specified account. For more information, see [Manage email forwarding](https://developers.google.com/workspace/gmail/api/guides/forwarding_settings).",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.forwardingAddresses.list"
                }
              }
            },
            "filters": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "description": "Creates a filter. Note: you can only create a maximum of 1,000 filters. For more information, see [Manage Gmail filters](https://developers.google.com/workspace/gmail/api/guides/filter_settings).",
                  "id": "gmail.users.settings.filters.create",
                  "httpMethod": "POST"
                },
                "delete": {
                  "id": "gmail.users.settings.filters.delete",
                  "httpMethod": "DELETE",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "description": "Immediately and permanently deletes the specified filter. For more information, see [Manage Gmail filters](https://developers.google.com/workspace/gmail/api/guides/filter_settings).",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "get": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "id": "gmail.users.settings.filters.get",
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "description": "Gets a filter. For more information, see [Manage Gmail filters](https://developers.google.com/workspace/gmail/api/guides/filter_settings)."
                },
                "list": {
                  "description": "Lists the message filters of a Gmail user. For more information, see [Manage Gmail filters](https://developers.google.com/workspace/gmail/api/guides/filter_settings).",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "httpMethod": "GET",
                  "id": "gmail.users.settings.filters.list",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                }
              }
            },
            "delegates": {
              "methods": {
                "list": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "description": "Lists the delegates for the specified account. For more information, see [Manage delegates](https://developers.google.com/workspace/gmail/api/guides/delegate_settings). This method is only available to service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "id": "gmail.users.settings.delegates.list",
                  "httpMethod": "GET"
                },
                "get": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "description": "Gets the specified delegate. For more information, see [Manage delegates](https://developers.google.com/workspace/gmail/api/guides/delegate_settings). A delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "id": "gmail.users.settings.delegates.get",
                  "httpMethod": "GET"
                },
                "create": {
                  "httpMethod": "POST",
                  "id": "gmail.users.settings.delegates.create",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "description": "Adds a delegate with its verification status set directly to `accepted`, without sending any verification email. The delegate user must be a member of the same Google Workspace organization as the delegator user. For more information, see [Manage delegates](https://developers.google.com/workspace/gmail/api/guides/delegate_settings). Gmail imposes limitations on the number of delegates and delegators each user in a Google Workspace organization can have. These li[...]",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "delete": {
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Removes the specified delegate (which can be of any verification status), and revokes any verification that may have been required for using it. For more information, see [Manage delegates](https://developers.google.com/workspace/gmail/api/guides/delegate_settings). A delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "httpMethod": "DELETE",
                  "id": "gmail.users.settings.delegates.delete"
                }
              }
            },
            "cse": {
              "resources": {
                "keypairs": {
                  "methods": {
                    "obliterate": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Deletes a client-side encryption key pair permanently and immediately. You can only permanently delete key pairs that have been turned off for more than 30 days. To turn off a key pair, use the DisableCseKeyPair method. Gmail can't restore or decrypt any messages that were encrypted by an obliterated key. Authenticated users and Google Workspace administrators lose access to reading the encrypted messages. For administrators managing identities and keypairs [...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.cse.keypairs.obliterate"
                    },
                    "disable": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
                      "description": "Turns off a client-side encryption key pair. The authenticated user can no longer use the key pair to decrypt incoming CSE message texts or sign outgoing CSE mail. To regain access, use the EnableCseKeyPair to turn on the key pair. After 30 days, you can permanently delete the key pair by using the ObliterateCseKeyPair method. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service a[...]",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.cse.keypairs.disable"
                    },
                    "enable": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Turns on a client-side encryption key pair that was turned off. The key pair becomes active again for any associated client-side encryption identities. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth[...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.cse.keypairs.enable"
                    },
                    "get": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.cse.keypairs.get",
                      "description": "Retrieves an existing client-side encryption key pair. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.com/au[...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}"
                    },
                    "create": {
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "description": "Creates and uploads a client-side encryption S/MIME public key certificate chain and private key metadata for the authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#de[...]",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "httpMethod": "POST",
                      "id": "gmail.users.settings.cse.keypairs.create",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "list": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "id": "gmail.users.settings.cse.keypairs.list",
                      "httpMethod": "GET",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "description": "Lists client-side encryption key pairs for an authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.google[...]"
                    }
                  }
                },
                "identities": {
                  "methods": {
                    "get": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "description": "Retrieves a client-side encryption identity configuration. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.co[...]",
                      "id": "gmail.users.settings.cse.identities.get",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "create": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities",
                      "description": "Creates and configures a client-side encryption identity that's authorized to send mail from the user account. Google publishes the S/MIME certificate to a shared domain-wide directory so that people within a Google Workspace organization can encrypt and send mail to the identity. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/[...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities",
                      "id": "gmail.users.settings.cse.identities.create",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "delete": {
                      "id": "gmail.users.settings.cse.identities.delete",
                      "httpMethod": "DELETE",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "description": "Deletes a client-side encryption identity. The authenticated user can no longer use the identity to send encrypted messages. You cannot restore the identity after you delete it. Instead, use the CreateCseIdentity method to create another identity with the same configuration. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protoc[...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "id": "gmail.users.settings.cse.identities.patch",
                      "httpMethod": "PATCH",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
                      "description": "Associates a different key pair with an existing client-side encryption identity. The updated key pair must validate against Google's [S/MIME certificate profiles](https://support.google.com/a/answer/7300887). For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authori[...]"
                    },
                    "list": {
                      "httpMethod": "GET",
                      "id": "gmail.users.settings.cse.identities.list",
                      "description": "Lists the client-side encrypted identities for an authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.go[...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    }
                  }
                }
              }
            }
          }
        },
        "labels": {
          "methods": {
            "get": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "description": "Gets the specified label. For more information, see [Manage labels](https://developers.google.com/workspace/gmail/api/guides/labels).",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.get",
              "httpMethod": "GET"
            },
            "create": {
              "flatPath": "gmail/v1/users/{userId}/labels",
              "path": "gmail/v1/users/{userId}/labels",
              "description": "Creates a label. For more information, see [Manage labels](https://developers.google.com/workspace/gmail/api/guides/labels).",
              "id": "gmail.users.labels.create",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "delete": {
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it's applied to. For more information, see [Manage labels](https://developers.google.com/workspace/gmail/api/guides/labels).",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "DELETE",
              "id": "gmail.users.labels.delete"
            },
            "update": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "PUT",
              "id": "gmail.users.labels.update",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "description": "Updates the specified label. For more information, see [Manage labels](https://developers.google.com/workspace/gmail/api/guides/labels).",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}"
            },
            "patch": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "PATCH",
              "id": "gmail.users.labels.patch",
              "description": "Patch the specified label. For more information, see [Manage labels](https://developers.google.com/workspace/gmail/api/guides/labels).",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}"
            },
            "list": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET",
              "id": "gmail.users.labels.list",
              "path": "gmail/v1/users/{userId}/labels",
              "description": "Lists all labels in the user's mailbox. For more information, see [Manage labels](https://developers.google.com/workspace/gmail/api/guides/labels).",
              "flatPath": "gmail/v1/users/{userId}/labels"
            }
          }
        }
      }
    }
  },
  "ownerName": "Google",
  "description": "The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels.",
  "ownerDomain": "google.com",
  "documentationLink": "https://developers.google.com/workspace/gmail/api/",
  "protocol": "rest",
  "batchPath": "batch",
  "version": "v1",
  "servicePath": "",
  "rootUrl": "https://gmail.googleapis.com/",
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/gmail.modify": {
          "description": "Read, compose, and send emails from your Gmail account"
        },
        "https://www.googleapis.com/auth/gmail.settings.basic": {
          "description": "See, edit, create, or change your email settings and filters in Gmail"
        },
        "https://www.googleapis.com/auth/gmail.insert": {
          "description": "Add emails into your Gmail mailbox"
        },
        "https://www.googleapis.com/auth/gmail.send": {
          "description": "Send email on your behalf"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {
          "description": "View your email message metadata when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.action": {
          "description": "View your email messages when you interact with the add-on"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/gmail.metadata": {
          "description": "View your email message metadata such as labels and headers, but not the email body"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {
          "description": "Manage drafts and send emails when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.compose": {
          "description": "Manage drafts and send emails"
        },
        "https://www.googleapis.com/auth/gmail.settings.sharing": {
          "description": "Manage your sensitive mail settings, including who can manage your mail"
        },
        "https://www.googleapis.com/auth/gmail.labels": {
          "description": "See and edit your email labels"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {
          "description": "View your email messages when the add-on is running"
        }
      }
    }
  },
  "basePath": ""
}