{
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "protocol": "rest",
  "resources": {
    "users": {
      "methods": {
        "watch": {
          "httpMethod": "POST",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ],
          "description": "Set up or update a push notification watch on the given user mailbox.",
          "id": "gmail.users.watch",
          "path": "gmail/v1/users/{userId}/watch",
          "flatPath": "gmail/v1/users/{userId}/watch"
        },
        "getProfile": {
          "description": "Gets the current user's Gmail profile.",
          "flatPath": "gmail/v1/users/{userId}/profile",
          "path": "gmail/v1/users/{userId}/profile",
          "id": "gmail.users.getProfile",
          "httpMethod": "GET",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.compose",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        },
        "stop": {
          "httpMethod": "POST",
          "description": "Stop receiving push notifications for the given user mailbox.",
          "flatPath": "gmail/v1/users/{userId}/stop",
          "path": "gmail/v1/users/{userId}/stop",
          "id": "gmail.users.stop",
          "scopes": [
            "https://mail.google.com/",
            "https://www.googleapis.com/auth/gmail.metadata",
            "https://www.googleapis.com/auth/gmail.modify",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        }
      },
      "resources": {
        "messages": {
          "methods": {
            "import": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "flatPath": "gmail/v1/users/{userId}/messages/import",
              "id": "gmail.users.messages.import",
              "path": "gmail/v1/users/{userId}/messages/import",
              "description": "Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. This method doesn't perform SPF checks, so it might not work for some spam messages, such as those attempting to perform domain spoofing. This method does not send a message. Note that the maximum size of the message is 150MB."
            },
            "batchDelete": {
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/"
              ],
              "description": "Deletes many messages by message ID. Provides no guarantees that messages were not already deleted or even existed at all.",
              "flatPath": "gmail/v1/users/{userId}/messages/batchDelete",
              "id": "gmail.users.messages.batchDelete",
              "path": "gmail/v1/users/{userId}/messages/batchDelete"
            },
            "get": {
              "flatPath": "gmail/v1/users/{userId}/messages/{id}",
              "id": "gmail.users.messages.get",
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "description": "Gets the specified message.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET"
            },
            "modify": {
              "id": "gmail.users.messages.modify",
              "path": "gmail/v1/users/{userId}/messages/{id}/modify",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/modify",
              "description": "Modifies the labels on the specified message.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST"
            },
            "batchModify": {
              "flatPath": "gmail/v1/users/{userId}/messages/batchModify",
              "path": "gmail/v1/users/{userId}/messages/batchModify",
              "id": "gmail.users.messages.batchModify",
              "description": "Modifies the labels on the specified messages.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST"
            },
            "trash": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST",
              "path": "gmail/v1/users/{userId}/messages/{id}/trash",
              "id": "gmail.users.messages.trash",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/trash",
              "description": "Moves the specified message to the trash."
            },
            "list": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "description": "Lists the messages in the user's mailbox. For example usage, see [List Gmail messages](https://developers.google.com/workspace/gmail/api/guides/list-messages).",
              "flatPath": "gmail/v1/users/{userId}/messages",
              "path": "gmail/v1/users/{userId}/messages",
              "id": "gmail.users.messages.list"
            },
            "untrash": {
              "description": "Removes the specified message from the trash.",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "id": "gmail.users.messages.untrash",
              "path": "gmail/v1/users/{userId}/messages/{id}/untrash",
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ]
            },
            "insert": {
              "id": "gmail.users.messages.insert",
              "path": "gmail/v1/users/{userId}/messages",
              "flatPath": "gmail/v1/users/{userId}/messages",
              "description": "Directly inserts a message into only this user's mailbox similar to `IMAP APPEND`, bypassing most scanning and classification. Does not send a message.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.insert",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST",
              "supportsMediaUpload": true
            },
            "delete": {
              "httpMethod": "DELETE",
              "description": "Immediately and permanently deletes the specified message. This operation cannot be undone. Prefer `messages.trash` instead.",
              "id": "gmail.users.messages.delete",
              "scopes": [
                "https://mail.google.com/"
              ],
              "path": "gmail/v1/users/{userId}/messages/{id}",
              "flatPath": "gmail/v1/users/{userId}/messages/{id}"
            },
            "send": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.send"
              ],
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "flatPath": "gmail/v1/users/{userId}/messages/send",
              "path": "gmail/v1/users/{userId}/messages/send",
              "id": "gmail.users.messages.send",
              "description": "Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc` headers. For example usage, see [Sending email](https://developers.google.com/workspace/gmail/api/guides/sending)."
            }
          },
          "resources": {
            "attachments": {
              "methods": {
                "get": {
                  "description": "Gets the specified message attachment.",
                  "flatPath": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "path": "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}",
                  "id": "gmail.users.messages.attachments.get",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                    "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly"
                  ]
                }
              }
            }
          }
        },
        "settings": {
          "methods": {
            "getPop": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET",
              "id": "gmail.users.settings.getPop",
              "path": "gmail/v1/users/{userId}/settings/pop",
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "description": "Gets POP settings."
            },
            "getLanguage": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Gets language settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "path": "gmail/v1/users/{userId}/settings/language",
              "id": "gmail.users.settings.getLanguage"
            },
            "getVacation": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "id": "gmail.users.settings.getVacation",
              "description": "Gets vacation responder settings."
            },
            "updateVacation": {
              "flatPath": "gmail/v1/users/{userId}/settings/vacation",
              "id": "gmail.users.settings.updateVacation",
              "path": "gmail/v1/users/{userId}/settings/vacation",
              "description": "Updates vacation responder settings.",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "PUT"
            },
            "updateLanguage": {
              "flatPath": "gmail/v1/users/{userId}/settings/language",
              "path": "gmail/v1/users/{userId}/settings/language",
              "id": "gmail.users.settings.updateLanguage",
              "description": "Updates language settings. If successful, the return object contains the `displayLanguage` that was saved for the user, which may differ from the value passed into the request. This is because the requested `displayLanguage` may not be directly supported by Gmail but have a close variant that is, and so the variant may be chosen and saved instead.",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "PUT"
            },
            "updateAutoForwarding": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.sharing"
              ],
              "description": "Updates the auto-forwarding setting for the specified account. A verified forwarding address must be specified when auto-forwarding is enabled. This method is only available to service account clients that have been delegated domain-wide authority.",
              "id": "gmail.users.settings.updateAutoForwarding",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding"
            },
            "getAutoForwarding": {
              "flatPath": "gmail/v1/users/{userId}/settings/autoForwarding",
              "path": "gmail/v1/users/{userId}/settings/autoForwarding",
              "id": "gmail.users.settings.getAutoForwarding",
              "description": "Gets the auto-forwarding setting for the specified account.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET"
            },
            "updateImap": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "description": "Updates IMAP settings.",
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "id": "gmail.users.settings.updateImap"
            },
            "updatePop": {
              "scopes": [
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "PUT",
              "path": "gmail/v1/users/{userId}/settings/pop",
              "id": "gmail.users.settings.updatePop",
              "flatPath": "gmail/v1/users/{userId}/settings/pop",
              "description": "Updates POP settings."
            },
            "getImap": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly",
                "https://www.googleapis.com/auth/gmail.settings.basic"
              ],
              "httpMethod": "GET",
              "path": "gmail/v1/users/{userId}/settings/imap",
              "id": "gmail.users.settings.getImap",
              "flatPath": "gmail/v1/users/{userId}/settings/imap",
              "description": "Gets IMAP settings."
            }
          },
          "resources": {
            "forwardingAddresses": {
              "methods": {
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "httpMethod": "POST",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "id": "gmail.users.settings.forwardingAddresses.create",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "description": "Creates a forwarding address. If ownership verification is required, a message will be sent to the recipient and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. This method is only available to service account clients that have been delegated domain-wide authority."
                },
                "delete": {
                  "id": "gmail.users.settings.forwardingAddresses.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "httpMethod": "DELETE",
                  "description": "Deletes the specified forwarding address and revokes any verification that may have been required. This method is only available to service account clients that have been delegated domain-wide authority."
                },
                "list": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "id": "gmail.users.settings.forwardingAddresses.list",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses",
                  "description": "Lists the forwarding addresses for the specified account."
                },
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "description": "Gets the specified forwarding address.",
                  "flatPath": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}",
                  "id": "gmail.users.settings.forwardingAddresses.get",
                  "path": "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}"
                }
              }
            },
            "filters": {
              "methods": {
                "list": {
                  "flatPath": "gmail/v1/users/{userId}/settings/filters",
                  "id": "gmail.users.settings.filters.list",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "description": "Lists the message filters of a Gmail user.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET"
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "description": "Creates a filter. Note: you can only create a maximum of 1,000 filters.",
                  "id": "gmail.users.settings.filters.create",
                  "path": "gmail/v1/users/{userId}/settings/filters",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Immediately and permanently deletes the specified filter.",
                  "id": "gmail.users.settings.filters.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}"
                },
                "get": {
                  "flatPath": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "id": "gmail.users.settings.filters.get",
                  "path": "gmail/v1/users/{userId}/settings/filters/{id}",
                  "description": "Gets a filter.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET"
                }
              }
            },
            "cse": {
              "resources": {
                "identities": {
                  "methods": {
                    "list": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities",
                      "id": "gmail.users.settings.cse.identities.list",
                      "description": "Lists the client-side encrypted identities for an authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.go[...]"
                    },
                    "get": {
                      "description": "Retrieves a client-side encryption identity configuration. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.co[...]",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "id": "gmail.users.settings.cse.identities.get",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "create": {
                      "description": "Creates and configures a client-side encryption identity that's authorized to send mail from the user account. Google publishes the S/MIME certificate to a shared domain-wide directory so that people within a Google Workspace organization can encrypt and send mail to the identity. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/[...]",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities",
                      "id": "gmail.users.settings.cse.identities.create",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "delete": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}",
                      "id": "gmail.users.settings.cse.identities.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "DELETE",
                      "description": "Deletes a client-side encryption identity. The authenticated user can no longer use the identity to send encrypted messages. You cannot restore the identity after you delete it. Instead, use the CreateCseIdentity method to create another identity with the same configuration. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protoc[...]"
                    },
                    "patch": {
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "PATCH",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
                      "id": "gmail.users.settings.cse.identities.patch",
                      "path": "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}",
                      "description": "Associates a different key pair with an existing client-side encryption identity. The updated key pair must validate against Google's [S/MIME certificate profiles](https://support.google.com/a/answer/7300887). For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authori[...]"
                    }
                  }
                },
                "keypairs": {
                  "methods": {
                    "create": {
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "id": "gmail.users.settings.cse.keypairs.create",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "description": "Creates and uploads a client-side encryption S/MIME public key certificate chain and private key metadata for the authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#de[...]",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "POST"
                    },
                    "list": {
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "GET",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs",
                      "id": "gmail.users.settings.cse.keypairs.list",
                      "description": "Lists client-side encryption key pairs for an authenticated user. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.google[...]"
                    },
                    "enable": {
                      "description": "Turns on a client-side encryption key pair that was turned off. The key pair becomes active again for any associated client-side encryption identities. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth[...]",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable",
                      "id": "gmail.users.settings.cse.keypairs.enable",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "obliterate": {
                      "description": "Deletes a client-side encryption key pair permanently and immediately. You can only permanently delete key pairs that have been turned off for more than 30 days. To turn off a key pair, use the DisableCseKeyPair method. Gmail can't restore or decrypt any messages that were encrypted by an obliterated key. Authenticated users and Google Workspace administrators lose access to reading the encrypted messages. For administrators managing identities and keypairs [...]",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
                      "id": "gmail.users.settings.cse.keypairs.obliterate",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate",
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "disable": {
                      "id": "gmail.users.settings.cse.keypairs.disable",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable",
                      "description": "Turns off a client-side encryption key pair. The authenticated user can no longer use the key pair to decrypt incoming CSE message texts or sign outgoing CSE mail. To regain access, use the EnableCseKeyPair to turn on the key pair. After 30 days, you can permanently delete the key pair by using the ObliterateCseKeyPair method. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service a[...]",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "POST"
                    },
                    "get": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Retrieves an existing client-side encryption key pair. For administrators managing identities and keypairs for users in their organization, requests require authorization with a [service account](https://developers.google.com/identity/protocols/OAuth2ServiceAccount) that has [domain-wide delegation authority](https://developers.google.com/identity/protocols/OAuth2ServiceAccount#delegatingauthority) to impersonate users with the `https://www.googleapis.com/au[...]",
                      "flatPath": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}",
                      "id": "gmail.users.settings.cse.keypairs.get",
                      "path": "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}"
                    }
                  }
                }
              }
            },
            "sendAs": {
              "methods": {
                "patch": {
                  "httpMethod": "PATCH",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "description": "Patch the specified send-as alias.",
                  "id": "gmail.users.settings.sendAs.patch",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "update": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.basic",
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "httpMethod": "PUT",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.update",
                  "description": "Updates a send-as alias. If a signature is provided, Gmail will sanitize the HTML before saving it with the alias. Addresses other than the primary address for the account can only be updated by service account clients that have been delegated domain-wide authority."
                },
                "verify": {
                  "httpMethod": "POST",
                  "description": "Sends a verification email to the specified send-as alias address. The verification status must be `pending`. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify",
                  "id": "gmail.users.settings.sendAs.verify",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify"
                },
                "create": {
                  "description": "Creates a custom \"from\" send-as alias. If an SMTP MSA is specified, Gmail will attempt to connect to the SMTP service to validate the configuration before creating the alias. If ownership verification is required for the alias, a message will be sent to the email address and the resource's verification status will be set to `pending`; otherwise, the resource will be created with verification status set to `accepted`. If a signature is provided, Gmail will sani[...]",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "id": "gmail.users.settings.sendAs.create",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ]
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "description": "Deletes the specified send-as alias. Revokes any verification that may have been required for using it. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}"
                },
                "get": {
                  "description": "Gets the specified send-as alias. Fails with an HTTP 404 error if the specified address is not a member of the collection.",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "id": "gmail.users.settings.sendAs.get",
                  "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ]
                },
                "list": {
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET",
                  "flatPath": "gmail/v1/users/{userId}/settings/sendAs",
                  "path": "gmail/v1/users/{userId}/settings/sendAs",
                  "id": "gmail.users.settings.sendAs.list",
                  "description": "Lists the send-as aliases for the specified account. The result includes the primary send-as address associated with the account as well as any custom \"from\" aliases."
                }
              },
              "resources": {
                "smimeInfo": {
                  "methods": {
                    "list": {
                      "description": "Lists S/MIME configs for the specified send-as alias.",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "id": "gmail.users.settings.sendAs.smimeInfo.list",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "setDefault": {
                      "id": "gmail.users.settings.sendAs.smimeInfo.setDefault",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault",
                      "httpMethod": "POST",
                      "description": "Sets the default S/MIME config for the specified send-as alias."
                    },
                    "get": {
                      "description": "Gets the specified S/MIME config for the specified send-as alias.",
                      "id": "gmail.users.settings.sendAs.smimeInfo.get",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "httpMethod": "GET",
                      "scopes": [
                        "https://mail.google.com/",
                        "https://www.googleapis.com/auth/gmail.modify",
                        "https://www.googleapis.com/auth/gmail.readonly",
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ]
                    },
                    "delete": {
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}",
                      "id": "gmail.users.settings.sendAs.smimeInfo.delete",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "httpMethod": "DELETE",
                      "description": "Deletes the specified S/MIME config for the specified send-as alias."
                    },
                    "insert": {
                      "httpMethod": "POST",
                      "scopes": [
                        "https://www.googleapis.com/auth/gmail.settings.basic",
                        "https://www.googleapis.com/auth/gmail.settings.sharing"
                      ],
                      "description": "Insert (upload) the given S/MIME config for the specified send-as alias. Note that pkcs12 format is required for the key.",
                      "id": "gmail.users.settings.sendAs.smimeInfo.insert",
                      "path": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo",
                      "flatPath": "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo"
                    }
                  }
                }
              }
            },
            "delegates": {
              "methods": {
                "list": {
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "id": "gmail.users.settings.delegates.list",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "description": "Lists the delegates for the specified account. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET"
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "httpMethod": "POST",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates",
                  "id": "gmail.users.settings.delegates.create",
                  "path": "gmail/v1/users/{userId}/settings/delegates",
                  "description": "Adds a delegate with its verification status set directly to `accepted`, without sending any verification email. The delegate user must be a member of the same Google Workspace organization as the delegator user. Gmail imposes limitations on the number of delegates and delegators each user in a Google Workspace organization can have. These limits depend on your organization, but in general each user can have up to 25 delegates and up to 10 delegators. Note that [...]"
                },
                "delete": {
                  "id": "gmail.users.settings.delegates.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/gmail.settings.sharing"
                  ],
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "httpMethod": "DELETE",
                  "description": "Removes the specified delegate (which can be of any verification status), and revokes any verification that may have been required for using it. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority."
                },
                "get": {
                  "flatPath": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "path": "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}",
                  "id": "gmail.users.settings.delegates.get",
                  "description": "Gets the specified delegate. Note that a delegate user must be referred to by their primary email address, and not an email alias. This method is only available to service account clients that have been delegated domain-wide authority.",
                  "scopes": [
                    "https://mail.google.com/",
                    "https://www.googleapis.com/auth/gmail.modify",
                    "https://www.googleapis.com/auth/gmail.readonly",
                    "https://www.googleapis.com/auth/gmail.settings.basic"
                  ],
                  "httpMethod": "GET"
                }
              }
            }
          }
        },
        "drafts": {
          "methods": {
            "get": {
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "description": "Gets the specified draft.",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "id": "gmail.users.drafts.get"
            },
            "list": {
              "description": "Lists the drafts in the user's mailbox.",
              "path": "gmail/v1/users/{userId}/drafts",
              "id": "gmail.users.drafts.list",
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "delete": {
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "id": "gmail.users.drafts.delete",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "httpMethod": "DELETE",
              "description": "Immediately and permanently deletes the specified draft. Does not simply trash it."
            },
            "create": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST",
              "supportsMediaUpload": true,
              "id": "gmail.users.drafts.create",
              "path": "gmail/v1/users/{userId}/drafts",
              "flatPath": "gmail/v1/users/{userId}/drafts",
              "description": "Creates a new draft with the `DRAFT` label."
            },
            "send": {
              "flatPath": "gmail/v1/users/{userId}/drafts/send",
              "path": "gmail/v1/users/{userId}/drafts/send",
              "id": "gmail.users.drafts.send",
              "description": "Sends the specified, existing draft to the recipients in the `To`, `Cc`, and `Bcc` headers.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST",
              "supportsMediaUpload": true
            },
            "update": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.action.compose",
                "https://www.googleapis.com/auth/gmail.compose",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "PUT",
              "supportsMediaUpload": true,
              "path": "gmail/v1/users/{userId}/drafts/{id}",
              "id": "gmail.users.drafts.update",
              "flatPath": "gmail/v1/users/{userId}/drafts/{id}",
              "description": "Replaces a draft's content."
            }
          }
        },
        "threads": {
          "methods": {
            "delete": {
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "id": "gmail.users.threads.delete",
              "scopes": [
                "https://mail.google.com/"
              ],
              "httpMethod": "DELETE",
              "description": "Immediately and permanently deletes the specified thread. Any messages that belong to the thread are also deleted. This operation cannot be undone. Prefer `threads.trash` instead."
            },
            "trash": {
              "httpMethod": "POST",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Moves the specified thread to the trash. Any messages that belong to the thread are also moved to the trash.",
              "path": "gmail/v1/users/{userId}/threads/{id}/trash",
              "id": "gmail.users.threads.trash",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/trash"
            },
            "list": {
              "description": "Lists the threads in the user's mailbox.",
              "flatPath": "gmail/v1/users/{userId}/threads",
              "id": "gmail.users.threads.list",
              "path": "gmail/v1/users/{userId}/threads",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            },
            "untrash": {
              "id": "gmail.users.threads.untrash",
              "path": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/untrash",
              "description": "Removes the specified thread from the trash. Any messages that belong to the thread are also removed from the trash.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST"
            },
            "get": {
              "flatPath": "gmail/v1/users/{userId}/threads/{id}",
              "path": "gmail/v1/users/{userId}/threads/{id}",
              "id": "gmail.users.threads.get",
              "description": "Gets the specified thread.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.addons.current.message.action",
                "https://www.googleapis.com/auth/gmail.addons.current.message.metadata",
                "https://www.googleapis.com/auth/gmail.addons.current.message.readonly",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET"
            },
            "modify": {
              "flatPath": "gmail/v1/users/{userId}/threads/{id}/modify",
              "id": "gmail.users.threads.modify",
              "path": "gmail/v1/users/{userId}/threads/{id}/modify",
              "description": "Modifies the labels applied to the thread. This applies to all messages in the thread.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST"
            }
          }
        },
        "history": {
          "methods": {
            "list": {
              "description": "Lists the history of all changes to the given mailbox. History results are returned in chronological order (increasing `historyId`).",
              "flatPath": "gmail/v1/users/{userId}/history",
              "id": "gmail.users.history.list",
              "path": "gmail/v1/users/{userId}/history",
              "httpMethod": "GET",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ]
            }
          }
        },
        "labels": {
          "methods": {
            "list": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/labels",
              "path": "gmail/v1/users/{userId}/labels",
              "id": "gmail.users.labels.list",
              "description": "Lists all labels in the user's mailbox."
            },
            "get": {
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.metadata",
                "https://www.googleapis.com/auth/gmail.modify",
                "https://www.googleapis.com/auth/gmail.readonly"
              ],
              "httpMethod": "GET",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.get",
              "description": "Gets the specified label."
            },
            "create": {
              "flatPath": "gmail/v1/users/{userId}/labels",
              "path": "gmail/v1/users/{userId}/labels",
              "id": "gmail.users.labels.create",
              "description": "Creates a new label.",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "httpMethod": "POST"
            },
            "delete": {
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.delete",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "httpMethod": "DELETE",
              "description": "Immediately and permanently deletes the specified label and removes it from any messages and threads that it is applied to."
            },
            "update": {
              "httpMethod": "PUT",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Updates the specified label.",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "id": "gmail.users.labels.update"
            },
            "patch": {
              "httpMethod": "PATCH",
              "scopes": [
                "https://mail.google.com/",
                "https://www.googleapis.com/auth/gmail.labels",
                "https://www.googleapis.com/auth/gmail.modify"
              ],
              "description": "Patch the specified label.",
              "id": "gmail.users.labels.patch",
              "path": "gmail/v1/users/{userId}/labels/{id}",
              "flatPath": "gmail/v1/users/{userId}/labels/{id}"
            }
          }
        }
      }
    }
  },
  "baseUrl": "https://gmail.googleapis.com/",
  "canonicalName": "Gmail",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/gmail.labels": {
          "description": "See and edit your email labels"
        },
        "https://www.googleapis.com/auth/gmail.insert": {
          "description": "Add emails into your Gmail mailbox"
        },
        "https://www.googleapis.com/auth/gmail.compose": {
          "description": "Manage drafts and send emails"
        },
        "https://www.googleapis.com/auth/gmail.metadata": {
          "description": "View your email message metadata such as labels and headers, but not the email body"
        },
        "https://www.googleapis.com/auth/gmail.settings.sharing": {
          "description": "Manage your sensitive mail settings, including who can manage your mail"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.action.compose": {
          "description": "Manage drafts and send emails when you interact with the add-on"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.metadata": {
          "description": "View your email message metadata when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.settings.basic": {
          "description": "See, edit, create, or change your email settings and filters in Gmail"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.readonly": {
          "description": "View your email messages when the add-on is running"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        },
        "https://www.googleapis.com/auth/gmail.send": {
          "description": "Send email on your behalf"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        },
        "https://www.googleapis.com/auth/gmail.modify": {
          "description": "Read, compose, and send emails from your Gmail account"
        },
        "https://www.googleapis.com/auth/gmail.addons.current.message.action": {
          "description": "View your email messages when you interact with the add-on"
        }
      }
    }
  },
  "revision": "20260406",
  "servicePath": "",
  "rootUrl": "https://gmail.googleapis.com/",
  "documentationLink": "https://developers.google.com/workspace/gmail/api/",
  "mtlsRootUrl": "https://gmail.mtls.googleapis.com/",
  "title": "Gmail API",
  "basePath": "",
  "id": "gmail:v1",
  "name": "gmail",
  "ownerName": "Google",
  "version": "v1",
  "description": "The Gmail API lets you view and manage Gmail mailbox data like threads, messages, and labels."
}