{
  "description": "The Google Keep API is used in an enterprise environment to manage Google Keep content and resolve issues identified by cloud security software.",
  "discoveryVersion": "v1",
  "name": "keep",
  "mtlsRootUrl": "https://keep.mtls.googleapis.com/",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/keep": {
          "description": "See, edit, create and permanently delete all your Google Keep data"
        },
        "https://www.googleapis.com/auth/keep.readonly": {
          "description": "View all your Google Keep data"
        }
      }
    }
  },
  "basePath": "",
  "version": "v1",
  "id": "keep:v1",
  "protocol": "rest",
  "title": "Google Keep API",
  "ownerName": "Google",
  "servicePath": "",
  "revision": "20260412",
  "resources": {
    "notes": {
      "resources": {
        "permissions": {
          "methods": {
            "batchDelete": {
              "id": "keep.notes.permissions.batchDelete",
              "httpMethod": "POST",
              "flatPath": "v1/notes/{notesId}/permissions:batchDelete",
              "description": "Deletes one or more permissions on the note. The specified entities will immediately lose access. A permission with the `OWNER` role can't be removed. If removing a permission fails, then the entire request fails and no changes are made. Returns a 400 bad request error if a specified permission does not exist on the note.",
              "scopes": [
                "https://www.googleapis.com/auth/keep"
              ],
              "path": "v1/{+parent}/permissions:batchDelete"
            },
            "batchCreate": {
              "id": "keep.notes.permissions.batchCreate",
              "httpMethod": "POST",
              "flatPath": "v1/notes/{notesId}/permissions:batchCreate",
              "description": "Creates one or more permissions on the note. Only permissions with the `WRITER` role may be created. If adding any permission fails, then the entire request fails and no changes are made.",
              "scopes": [
                "https://www.googleapis.com/auth/keep"
              ],
              "path": "v1/{+parent}/permissions:batchCreate"
            }
          }
        }
      },
      "methods": {
        "create": {
          "id": "keep.notes.create",
          "httpMethod": "POST",
          "flatPath": "v1/notes",
          "description": "Creates a new note.",
          "scopes": [
            "https://www.googleapis.com/auth/keep"
          ],
          "path": "v1/notes"
        },
        "list": {
          "path": "v1/notes",
          "scopes": [
            "https://www.googleapis.com/auth/keep",
            "https://www.googleapis.com/auth/keep.readonly"
          ],
          "httpMethod": "GET",
          "id": "keep.notes.list",
          "description": "Lists notes. Every list call returns a page of results with `page_size` as the upper bound of returned items. A `page_size` of zero allows the server to choose the upper bound. The ListNotesResponse contains at most `page_size` entries. If there are more things left to list, it provides a `next_page_token` value. (Page tokens are opaque values.) To get the next page of results, copy the result's `next_page_token` into the next request's `page_token`. Repeat until the `n[...]",
          "flatPath": "v1/notes"
        },
        "delete": {
          "flatPath": "v1/notes/{notesId}",
          "description": "Deletes a note. Caller must have the `OWNER` role on the note to delete. Deleting a note removes the resource immediately and cannot be undone. Any collaborators will lose access to the note.",
          "id": "keep.notes.delete",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/keep"
          ],
          "path": "v1/{+name}"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/keep",
            "https://www.googleapis.com/auth/keep.readonly"
          ],
          "path": "v1/{+name}",
          "flatPath": "v1/notes/{notesId}",
          "description": "Gets a note.",
          "id": "keep.notes.get",
          "httpMethod": "GET"
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "scopes": [
            "https://www.googleapis.com/auth/keep",
            "https://www.googleapis.com/auth/keep.readonly"
          ],
          "path": "v1/{+name}",
          "id": "keep.media.download",
          "httpMethod": "GET",
          "useMediaDownloadService": true,
          "flatPath": "v1/notes/{notesId}/attachments/{attachmentsId}",
          "supportsMediaDownload": true,
          "description": "Gets an attachment. To download attachment media via REST requires the alt=media query parameter. Returns a 400 bad request error if attachment media is not available in the requested MIME type."
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true,
  "documentationLink": "https://developers.google.com/workspace/keep/api",
  "baseUrl": "https://keep.googleapis.com/",
  "ownerDomain": "google.com",
  "canonicalName": "Keep",
  "rootUrl": "https://keep.googleapis.com/",
  "batchPath": "batch",
  "kind": "discovery#restDescription",
  "version_module": true
}