{
  "rootUrl": "https://marketingplatformadmin.googleapis.com/",
  "discoveryVersion": "v1",
  "mtlsRootUrl": "https://marketingplatformadmin.mtls.googleapis.com/",
  "title": "Google Marketing Platform Admin API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/marketingplatformadmin.analytics.read": {
          "description": "View your Google Analytics product account data in GMP home"
        },
        "https://www.googleapis.com/auth/marketingplatformadmin.analytics.update": {
          "description": "Manage your Google Analytics product account data in GMP home"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/analytics/devguides/config/gmp/v1",
  "batchPath": "batch",
  "revision": "20260430",
  "resources": {
    "organizations": {
      "resources": {
        "analyticsAccountLinks": {
          "methods": {
            "create": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/marketingplatformadmin.analytics.update"
              ],
              "path": "v1alpha/{+parent}/analyticsAccountLinks",
              "id": "marketingplatformadmin.organizations.analyticsAccountLinks.create",
              "description": "Creates the link between the Analytics account and the Google Marketing Platform organization. User needs to be an org user, and admin on the Analytics account to create the link. If the account is already linked to an organization, user needs to unlink the account from the current organization, then try link again.",
              "flatPath": "v1alpha/organizations/{organizationsId}/analyticsAccountLinks"
            },
            "list": {
              "flatPath": "v1alpha/organizations/{organizationsId}/analyticsAccountLinks",
              "description": "Lists the Google Analytics accounts link to the specified Google Marketing Platform organization.",
              "id": "marketingplatformadmin.organizations.analyticsAccountLinks.list",
              "path": "v1alpha/{+parent}/analyticsAccountLinks",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/marketingplatformadmin.analytics.read",
                "https://www.googleapis.com/auth/marketingplatformadmin.analytics.update"
              ]
            },
            "delete": {
              "description": "Deletes the AnalyticsAccountLink, which detaches the Analytics account from the Google Marketing Platform organization. User needs to be an org user, and admin on the Analytics account in order to delete the link.",
              "flatPath": "v1alpha/organizations/{organizationsId}/analyticsAccountLinks/{analyticsAccountLinksId}",
              "id": "marketingplatformadmin.organizations.analyticsAccountLinks.delete",
              "path": "v1alpha/{+name}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/marketingplatformadmin.analytics.update"
              ]
            },
            "setPropertyServiceLevel": {
              "description": "Updates the service level for an Analytics property.",
              "flatPath": "v1alpha/organizations/{organizationsId}/analyticsAccountLinks/{analyticsAccountLinksId}:setPropertyServiceLevel",
              "id": "marketingplatformadmin.organizations.analyticsAccountLinks.setPropertyServiceLevel",
              "path": "v1alpha/{+analyticsAccountLink}:setPropertyServiceLevel",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/marketingplatformadmin.analytics.update"
              ]
            }
          }
        }
      },
      "methods": {
        "findSalesPartnerManagedClients": {
          "id": "marketingplatformadmin.organizations.findSalesPartnerManagedClients",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/marketingplatformadmin.analytics.read",
            "https://www.googleapis.com/auth/marketingplatformadmin.analytics.update"
          ],
          "path": "v1alpha/{+organization}:findSalesPartnerManagedClients",
          "description": "Returns a list of clients managed by the sales partner organization. User needs to be an OrgAdmin/BillingAdmin on the sales partner organization in order to view the end clients.",
          "flatPath": "v1alpha/organizations/{organizationsId}:findSalesPartnerManagedClients"
        },
        "reportPropertyUsage": {
          "id": "marketingplatformadmin.organizations.reportPropertyUsage",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/marketingplatformadmin.analytics.read",
            "https://www.googleapis.com/auth/marketingplatformadmin.analytics.update"
          ],
          "path": "v1alpha/{+organization}:reportPropertyUsage",
          "flatPath": "v1alpha/organizations/{organizationsId}:reportPropertyUsage",
          "description": "Gets the usage and billing data for properties within the organization for the specified month. Per direct client org, user needs to be OrgAdmin/BillingAdmin on the organization in order to view the billing and usage data. Per sales partner client org, user needs to be OrgAdmin/BillingAdmin on the sales partner org in order to view the billing and usage data, or OrgAdmin/BillingAdmin on the sales partner client org in order to view the usage data only."
        },
        "get": {
          "flatPath": "v1alpha/organizations/{organizationsId}",
          "description": "Looks up a single organization.",
          "id": "marketingplatformadmin.organizations.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/marketingplatformadmin.analytics.read",
            "https://www.googleapis.com/auth/marketingplatformadmin.analytics.update"
          ],
          "path": "v1alpha/{+name}"
        },
        "list": {
          "flatPath": "v1alpha/organizations",
          "description": "Returns a list of organizations that the user has access to.",
          "id": "marketingplatformadmin.organizations.list",
          "path": "v1alpha/organizations",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/marketingplatformadmin.analytics.read",
            "https://www.googleapis.com/auth/marketingplatformadmin.analytics.update"
          ]
        }
      }
    }
  },
  "name": "marketingplatformadmin",
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "ownerDomain": "google.com",
  "baseUrl": "https://marketingplatformadmin.googleapis.com/",
  "canonicalName": "Google Marketing Platform Admin API",
  "basePath": "",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "id": "marketingplatformadmin:v1alpha",
  "version": "v1alpha",
  "description": "The Google Marketing Platform Admin API allows for programmatic access to the Google Marketing Platform configuration data. You can use the Google Marketing Platform Admin API to manage links between your Google Marketing Platform organization and Google Analytics accounts, and to set the service level of your GA4 properties.",
  "servicePath": "",
  "protocol": "rest"
}