{
  "version": "v2",
  "ownerDomain": "google.com",
  "title": "Google Meet API",
  "name": "meet",
  "id": "meet:v2",
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "protocol": "rest",
  "baseUrl": "https://meet.googleapis.com/",
  "mtlsRootUrl": "https://meet.mtls.googleapis.com/",
  "canonicalName": "Meet",
  "version_module": true,
  "kind": "discovery#restDescription",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/meetings.space.readonly": {
          "description": "Read information about any of your Google Meet conferences"
        },
        "https://www.googleapis.com/auth/meetings.space.created": {
          "description": "Create, edit, and see information about your Google Meet conferences created by the app."
        },
        "https://www.googleapis.com/auth/meetings.space.settings": {
          "description": "Edit, and see settings for all of your Google Meet calls."
        }
      }
    }
  },
  "revision": "20260414",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://meet.googleapis.com/",
  "resources": {
    "spaces": {
      "methods": {
        "create": {
          "flatPath": "v2/spaces",
          "id": "meet.spaces.create",
          "description": "Creates a space.",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created"
          ],
          "httpMethod": "POST",
          "path": "v2/spaces"
        },
        "get": {
          "flatPath": "v2/spaces/{spacesId}",
          "id": "meet.spaces.get",
          "description": "Gets details about a meeting space. For an example, see [Get a meeting space](https://developers.google.com/workspace/meet/api/guides/meeting-spaces#get-meeting-space).",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly",
            "https://www.googleapis.com/auth/meetings.space.settings"
          ],
          "httpMethod": "GET",
          "path": "v2/{+name}"
        },
        "patch": {
          "path": "v2/{+name}",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.settings"
          ],
          "description": "Updates details about a meeting space. For an example, see [Update a meeting space](https://developers.google.com/workspace/meet/api/guides/meeting-spaces#update-meeting-space).",
          "id": "meet.spaces.patch",
          "flatPath": "v2/spaces/{spacesId}"
        },
        "endActiveConference": {
          "path": "v2/{+name}:endActiveConference",
          "httpMethod": "POST",
          "description": "Ends an active conference (if there's one). For an example, see [End active conference](https://developers.google.com/workspace/meet/api/guides/meeting-spaces#end-active-conference).",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created"
          ],
          "flatPath": "v2/spaces/{spacesId}:endActiveConference",
          "id": "meet.spaces.endActiveConference"
        }
      }
    },
    "conferenceRecords": {
      "methods": {
        "get": {
          "httpMethod": "GET",
          "path": "v2/{+name}",
          "flatPath": "v2/conferenceRecords/{conferenceRecordsId}",
          "id": "meet.conferenceRecords.get",
          "description": "Gets a conference record by conference ID.",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ]
        },
        "list": {
          "description": "Lists the conference records. By default, ordered by start time and in descending order.",
          "scopes": [
            "https://www.googleapis.com/auth/meetings.space.created",
            "https://www.googleapis.com/auth/meetings.space.readonly"
          ],
          "flatPath": "v2/conferenceRecords",
          "id": "meet.conferenceRecords.list",
          "path": "v2/conferenceRecords",
          "httpMethod": "GET"
        }
      },
      "resources": {
        "recordings": {
          "methods": {
            "get": {
              "id": "meet.conferenceRecords.recordings.get",
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/recordings/{recordingsId}",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ],
              "description": "Gets a recording by recording ID.",
              "httpMethod": "GET",
              "path": "v2/{+name}"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v2/{+parent}/recordings",
              "id": "meet.conferenceRecords.recordings.list",
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/recordings",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ],
              "description": "Lists the recording resources from the conference record. By default, ordered by start time and in ascending order."
            }
          }
        },
        "transcripts": {
          "resources": {
            "entries": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "path": "v2/{+name}",
                  "id": "meet.conferenceRecords.transcripts.entries.get",
                  "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}/entries/{entriesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/meetings.space.created",
                    "https://www.googleapis.com/auth/meetings.space.readonly"
                  ],
                  "description": "Gets a `TranscriptEntry` resource by entry ID. Note: The transcript entries returned by the Google Meet API might not match the transcription found in the Google Docs transcript file. This can occur when 1) we have interleaved speakers within milliseconds, or 2) the Google Docs transcript file is modified after generation."
                },
                "list": {
                  "path": "v2/{+parent}/entries",
                  "httpMethod": "GET",
                  "description": "Lists the structured transcript entries per transcript. By default, ordered by start time and in ascending order. Note: The transcript entries returned by the Google Meet API might not match the transcription found in the Google Docs transcript file. This can occur when 1) we have interleaved speakers within milliseconds, or 2) the Google Docs transcript file is modified after generation.",
                  "scopes": [
                    "https://www.googleapis.com/auth/meetings.space.created",
                    "https://www.googleapis.com/auth/meetings.space.readonly"
                  ],
                  "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}/entries",
                  "id": "meet.conferenceRecords.transcripts.entries.list"
                }
              }
            }
          },
          "methods": {
            "get": {
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/transcripts/{transcriptsId}",
              "id": "meet.conferenceRecords.transcripts.get",
              "description": "Gets a transcript by transcript ID.",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ],
              "httpMethod": "GET",
              "path": "v2/{+name}"
            },
            "list": {
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/transcripts",
              "id": "meet.conferenceRecords.transcripts.list",
              "description": "Lists the set of transcripts from the conference record. By default, ordered by start time and in ascending order.",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ],
              "httpMethod": "GET",
              "path": "v2/{+parent}/transcripts"
            }
          }
        },
        "smartNotes": {
          "methods": {
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ],
              "description": "Gets smart notes by smart note ID.",
              "id": "meet.conferenceRecords.smartNotes.get",
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/smartNotes/{smartNotesId}",
              "path": "v2/{+name}",
              "httpMethod": "GET"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v2/{+parent}/smartNotes",
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/smartNotes",
              "id": "meet.conferenceRecords.smartNotes.list",
              "description": "Lists the set of smart notes from the conference record. By default, ordered by start time and in ascending order.",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ]
            }
          }
        },
        "participants": {
          "methods": {
            "get": {
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}",
              "id": "meet.conferenceRecords.participants.get",
              "description": "Gets a participant by participant ID.",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ],
              "httpMethod": "GET",
              "path": "v2/{+name}"
            },
            "list": {
              "id": "meet.conferenceRecords.participants.list",
              "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/participants",
              "scopes": [
                "https://www.googleapis.com/auth/meetings.space.created",
                "https://www.googleapis.com/auth/meetings.space.readonly"
              ],
              "description": "Lists the participants in a conference record. By default, ordered by join time and in descending order. This API supports `fields` as standard parameters like every other API. However, when the `fields` request parameter is omitted, this API defaults to `'participants/*, next_page_token'`.",
              "httpMethod": "GET",
              "path": "v2/{+parent}/participants"
            }
          },
          "resources": {
            "participantSessions": {
              "methods": {
                "get": {
                  "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}/participantSessions/{participantSessionsId}",
                  "id": "meet.conferenceRecords.participants.participantSessions.get",
                  "description": "Gets a participant session by participant session ID.",
                  "scopes": [
                    "https://www.googleapis.com/auth/meetings.space.created",
                    "https://www.googleapis.com/auth/meetings.space.readonly"
                  ],
                  "httpMethod": "GET",
                  "path": "v2/{+name}"
                },
                "list": {
                  "path": "v2/{+parent}/participantSessions",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/meetings.space.created",
                    "https://www.googleapis.com/auth/meetings.space.readonly"
                  ],
                  "description": "Lists the participant sessions of a participant in a conference record. By default, ordered by join time and in descending order. This API supports `fields` as standard parameters like every other API. However, when the `fields` request parameter is omitted this API defaults to `'participantsessions/*, next_page_token'`.",
                  "id": "meet.conferenceRecords.participants.participantSessions.list",
                  "flatPath": "v2/conferenceRecords/{conferenceRecordsId}/participants/{participantsId}/participantSessions"
                }
              }
            }
          }
        }
      }
    }
  },
  "basePath": "",
  "documentationLink": "https://developers.google.com/workspace/meet/api",
  "servicePath": "",
  "description": "Create and manage meetings in Google Meet.",
  "batchPath": "batch"
}