{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/documents": {
          "description": "See, edit, create, and delete all your Google Docs documents"
        },
        "https://www.google.com/m8/feeds": {
          "description": "See, edit, download, and permanently delete your contacts"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/admin.directory.user": {
          "description": "View and manage the provisioning of users on your domain"
        },
        "https://www.googleapis.com/auth/userinfo.email": {
          "description": "See your primary Google Account email address"
        },
        "https://www.googleapis.com/auth/groups": {
          "description": "View and manage your Google Groups"
        },
        "https://www.googleapis.com/auth/script.deployments": {
          "description": "Create and update Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/forms": {
          "description": "View and manage your forms in Google Drive"
        },
        "https://www.googleapis.com/auth/forms.currentonly": {
          "description": "View and manage forms that this application has been installed in"
        },
        "https://www.googleapis.com/auth/script.deployments.readonly": {
          "description": "View Google Apps Script deployments"
        },
        "https://www.googleapis.com/auth/script.processes": {
          "description": "View Google Apps Script processes"
        },
        "https://www.google.com/calendar/feeds": {
          "description": "See, edit, share, and permanently delete all the calendars you can access using Google Calendar"
        },
        "https://www.googleapis.com/auth/script.metrics": {
          "description": "View Google Apps Script project's metrics"
        },
        "https://www.googleapis.com/auth/admin.directory.group": {
          "description": "View and manage the provisioning of groups on your domain"
        },
        "https://www.googleapis.com/auth/script.projects": {
          "description": "Create and update Google Apps Script projects"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete all your Google Sheets spreadsheets"
        },
        "https://www.googleapis.com/auth/script.projects.readonly": {
          "description": "View Google Apps Script projects"
        },
        "https://mail.google.com/": {
          "description": "Read, compose, send, and permanently delete all your email from Gmail"
        }
      }
    }
  },
  "mtlsRootUrl": "https://script.mtls.googleapis.com/",
  "name": "script",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/apps-script/api/",
  "resources": {
    "processes": {
      "methods": {
        "listScriptProcesses": {
          "description": "List information about a script's executed processes, such as process type and current status.",
          "path": "v1/processes:listScriptProcesses",
          "id": "script.processes.listScriptProcesses",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "flatPath": "v1/processes:listScriptProcesses"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.processes"
          ],
          "id": "script.processes.list",
          "path": "v1/processes",
          "description": "List information about processes made by or on behalf of a user, such as process type and current status.",
          "flatPath": "v1/processes"
        }
      }
    },
    "scripts": {
      "methods": {
        "run": {
          "path": "v1/scripts/{scriptId}:run",
          "description": "",
          "httpMethod": "POST",
          "scopes": [
            "https://mail.google.com/",
            "https://www.google.com/calendar/feeds",
            "https://www.google.com/m8/feeds",
            "https://www.googleapis.com/auth/admin.directory.group",
            "https://www.googleapis.com/auth/admin.directory.user",
            "https://www.googleapis.com/auth/documents",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/forms",
            "https://www.googleapis.com/auth/forms.currentonly",
            "https://www.googleapis.com/auth/groups",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/userinfo.email"
          ],
          "id": "script.scripts.run",
          "flatPath": "v1/scripts/{scriptId}:run"
        }
      }
    },
    "projects": {
      "resources": {
        "deployments": {
          "methods": {
            "create": {
              "id": "script.projects.deployments.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "description": "Creates a deployment of an Apps Script project.",
              "path": "v1/projects/{scriptId}/deployments",
              "flatPath": "v1/projects/{scriptId}/deployments"
            },
            "list": {
              "flatPath": "v1/projects/{scriptId}/deployments",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "id": "script.projects.deployments.list",
              "path": "v1/projects/{scriptId}/deployments",
              "description": "Lists the deployments of an Apps Script project."
            },
            "get": {
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "description": "Gets a deployment of an Apps Script project.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments",
                "https://www.googleapis.com/auth/script.deployments.readonly"
              ],
              "id": "script.projects.deployments.get",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}"
            },
            "delete": {
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "description": "Deletes a deployment of an Apps Script project.",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "id": "script.projects.deployments.delete",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}"
            },
            "update": {
              "id": "script.projects.deployments.update",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/script.deployments"
              ],
              "description": "Updates a deployment of an Apps Script project.",
              "path": "v1/projects/{scriptId}/deployments/{deploymentId}",
              "flatPath": "v1/projects/{scriptId}/deployments/{deploymentId}"
            }
          }
        },
        "versions": {
          "methods": {
            "create": {
              "flatPath": "v1/projects/{scriptId}/versions",
              "id": "script.projects.versions.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects"
              ],
              "description": "Creates a new immutable version using the current code, with a unique version number.",
              "path": "v1/projects/{scriptId}/versions"
            },
            "list": {
              "flatPath": "v1/projects/{scriptId}/versions",
              "id": "script.projects.versions.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "description": "List the versions of a script project.",
              "path": "v1/projects/{scriptId}/versions"
            },
            "get": {
              "flatPath": "v1/projects/{scriptId}/versions/{versionNumber}",
              "path": "v1/projects/{scriptId}/versions/{versionNumber}",
              "description": "Gets a version of a script project.",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/script.projects",
                "https://www.googleapis.com/auth/script.projects.readonly"
              ],
              "id": "script.projects.versions.get"
            }
          }
        }
      },
      "methods": {
        "getContent": {
          "flatPath": "v1/projects/{scriptId}/content",
          "id": "script.projects.getContent",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "description": "Gets the content of the script project, including the code source and metadata for each script file.",
          "path": "v1/projects/{scriptId}/content"
        },
        "get": {
          "id": "script.projects.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects",
            "https://www.googleapis.com/auth/script.projects.readonly"
          ],
          "description": "Gets a script project's metadata.",
          "path": "v1/projects/{scriptId}",
          "flatPath": "v1/projects/{scriptId}"
        },
        "updateContent": {
          "flatPath": "v1/projects/{scriptId}/content",
          "description": "Updates the content of the specified script project. This content is stored as the HEAD version, and is used when the script is executed as a trigger, in the script editor, in add-on preview mode, or as a web app or Apps Script API in development mode. This clears all the existing files in the project.",
          "path": "v1/projects/{scriptId}/content",
          "id": "script.projects.updateContent",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ]
        },
        "getMetrics": {
          "flatPath": "v1/projects/{scriptId}/metrics",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/script.metrics"
          ],
          "id": "script.projects.getMetrics",
          "path": "v1/projects/{scriptId}/metrics",
          "description": "Get metrics data for scripts, such as number of executions and active users."
        },
        "create": {
          "flatPath": "v1/projects",
          "description": "Creates a new, empty script project with no script files and a base manifest file.",
          "path": "v1/projects",
          "id": "script.projects.create",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/script.projects"
          ]
        }
      }
    }
  },
  "revision": "20260426",
  "basePath": "",
  "rootUrl": "https://script.googleapis.com/",
  "id": "script:v1",
  "protocol": "rest",
  "batchPath": "batch",
  "title": "Apps Script API",
  "description": "Manages and executes Google Apps Script projects. ",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "baseUrl": "https://script.googleapis.com/",
  "version": "v1",
  "fullyEncodeReservedExpansion": true,
  "canonicalName": "Script",
  "ownerName": "Google",
  "ownerDomain": "google.com"
}