{
  "title": "Google Search Console API",
  "rootUrl": "https://searchconsole.googleapis.com/",
  "canonicalName": "Search Console",
  "version": "v1",
  "batchPath": "batch",
  "servicePath": "",
  "ownerName": "Google",
  "discoveryVersion": "v1",
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/webmasters": {
          "description": "View and manage Search Console data for your verified sites"
        },
        "https://www.googleapis.com/auth/webmasters.readonly": {
          "description": "View Search Console data for your verified sites"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/webmaster-tools/about",
  "description": "The Search Console API provides access to both Search Console data (verified users only) and to public information on an URL basis (anyone)",
  "baseUrl": "https://searchconsole.googleapis.com/",
  "revision": "20260429",
  "ownerDomain": "google.com",
  "id": "searchconsole:v1",
  "kind": "discovery#restDescription",
  "version_module": true,
  "resources": {
    "urlInspection": {
      "resources": {
        "index": {
          "methods": {
            "inspect": {
              "flatPath": "v1/urlInspection/index:inspect",
              "path": "v1/urlInspection/index:inspect",
              "scopes": [
                "https://www.googleapis.com/auth/webmasters",
                "https://www.googleapis.com/auth/webmasters.readonly"
              ],
              "id": "searchconsole.urlInspection.index.inspect",
              "httpMethod": "POST",
              "description": "Index inspection."
            }
          }
        }
      }
    },
    "urlTestingTools": {
      "resources": {
        "mobileFriendlyTest": {
          "methods": {
            "run": {
              "description": "Runs Mobile-Friendly Test for a given URL.",
              "path": "v1/urlTestingTools/mobileFriendlyTest:run",
              "flatPath": "v1/urlTestingTools/mobileFriendlyTest:run",
              "id": "searchconsole.urlTestingTools.mobileFriendlyTest.run",
              "httpMethod": "POST"
            }
          }
        }
      }
    },
    "searchanalytics": {
      "methods": {
        "query": {
          "description": "Query your data with filters and parameters that you define. Returns zero or more rows grouped by the row keys that you define. You must define a date range of one or more days. When date is one of the group by values, any days without data are omitted from the result list. If you need to know which days have data, issue a broad date range query grouped by date for any metric, and see which day rows are returned.",
          "id": "webmasters.searchanalytics.query",
          "httpMethod": "POST",
          "path": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "flatPath": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query"
        }
      }
    },
    "sites": {
      "methods": {
        "delete": {
          "path": "webmasters/v3/sites/{siteUrl}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "description": " Removes a site from the set of the user's Search Console sites.",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "id": "webmasters.sites.delete",
          "httpMethod": "DELETE"
        },
        "list": {
          "description": " Lists the user's Search Console sites.",
          "flatPath": "webmasters/v3/sites",
          "path": "webmasters/v3/sites",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "id": "webmasters.sites.list",
          "httpMethod": "GET"
        },
        "add": {
          "path": "webmasters/v3/sites/{siteUrl}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "description": " Adds a site to the set of the user's sites in Search Console.",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "id": "webmasters.sites.add",
          "httpMethod": "PUT"
        },
        "get": {
          "description": " Retrieves information about specific site.",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "path": "webmasters/v3/sites/{siteUrl}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "id": "webmasters.sites.get",
          "httpMethod": "GET"
        }
      }
    },
    "sitemaps": {
      "methods": {
        "list": {
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "id": "webmasters.sitemaps.list",
          "httpMethod": "GET",
          "description": " Lists the [sitemaps-entries](/webmaster-tools/v3/sitemaps) submitted for this site, or included in the sitemap index file (if `sitemapIndex` is specified in the request)."
        },
        "delete": {
          "id": "webmasters.sitemaps.delete",
          "httpMethod": "DELETE",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "description": "Deletes a sitemap from the Sitemaps report. Does not stop Google from crawling this sitemap or the URLs that were previously crawled in the deleted sitemap.",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}"
        },
        "submit": {
          "id": "webmasters.sitemaps.submit",
          "httpMethod": "PUT",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "description": "Submits a sitemap for a site.",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}"
        },
        "get": {
          "description": "Retrieves information about a specific sitemap.",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "id": "webmasters.sitemaps.get",
          "httpMethod": "GET"
        }
      }
    }
  },
  "mtlsRootUrl": "https://searchconsole.mtls.googleapis.com/",
  "basePath": "",
  "name": "searchconsole"
}