{
  "description": "The Search Console API provides access to both Search Console data (verified users only) and to public information on an URL basis (anyone)",
  "batchPath": "batch",
  "discoveryVersion": "v1",
  "title": "Google Search Console API",
  "version": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/webmasters.readonly": {
          "description": "View Search Console data for your verified sites"
        },
        "https://www.googleapis.com/auth/webmasters": {
          "description": "View and manage Search Console data for your verified sites"
        }
      }
    }
  },
  "documentationLink": "https://developers.google.com/webmaster-tools/about",
  "protocol": "rest",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://searchconsole.googleapis.com/",
  "ownerName": "Google",
  "id": "searchconsole:v1",
  "basePath": "",
  "resources": {
    "searchanalytics": {
      "methods": {
        "query": {
          "httpMethod": "POST",
          "description": "Query your data with filters and parameters that you define. Returns zero or more rows grouped by the row keys that you define. You must define a date range of one or more days. When date is one of the group by values, any days without data are omitted from the result list. If you need to know which days have data, issue a broad date range query grouped by date for any metric, and see which day rows are returned.",
          "id": "webmasters.searchanalytics.query",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "path": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query",
          "flatPath": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query"
        }
      }
    },
    "sitemaps": {
      "methods": {
        "get": {
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "id": "webmasters.sitemaps.get",
          "httpMethod": "GET",
          "description": "Retrieves information about a specific sitemap."
        },
        "submit": {
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "id": "webmasters.sitemaps.submit",
          "httpMethod": "PUT",
          "description": "Submits a sitemap for a site.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}"
        },
        "delete": {
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes a sitemap from the Sitemaps report. Does not stop Google from crawling this sitemap or the URLs that were previously crawled in the deleted sitemap.",
          "id": "webmasters.sitemaps.delete",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}"
        },
        "list": {
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "id": "webmasters.sitemaps.list",
          "httpMethod": "GET",
          "description": " Lists the [sitemaps-entries](/webmaster-tools/v3/sitemaps) submitted for this site, or included in the sitemap index file (if `sitemapIndex` is specified in the request).",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ]
        }
      }
    },
    "sites": {
      "methods": {
        "get": {
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "id": "webmasters.sites.get",
          "httpMethod": "GET",
          "description": " Retrieves information about specific site.",
          "path": "webmasters/v3/sites/{siteUrl}",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ]
        },
        "delete": {
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "id": "webmasters.sites.delete",
          "httpMethod": "DELETE",
          "description": " Removes a site from the set of the user's Search Console sites.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "path": "webmasters/v3/sites/{siteUrl}"
        },
        "list": {
          "httpMethod": "GET",
          "description": " Lists the user's Search Console sites.",
          "id": "webmasters.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "path": "webmasters/v3/sites",
          "flatPath": "webmasters/v3/sites"
        },
        "add": {
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "path": "webmasters/v3/sites/{siteUrl}",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "httpMethod": "PUT",
          "description": " Adds a site to the set of the user's sites in Search Console.",
          "id": "webmasters.sites.add"
        }
      }
    },
    "urlTestingTools": {
      "resources": {
        "mobileFriendlyTest": {
          "methods": {
            "run": {
              "httpMethod": "POST",
              "description": "Runs Mobile-Friendly Test for a given URL.",
              "id": "searchconsole.urlTestingTools.mobileFriendlyTest.run",
              "path": "v1/urlTestingTools/mobileFriendlyTest:run",
              "flatPath": "v1/urlTestingTools/mobileFriendlyTest:run"
            }
          }
        }
      }
    },
    "urlInspection": {
      "resources": {
        "index": {
          "methods": {
            "inspect": {
              "id": "searchconsole.urlInspection.index.inspect",
              "httpMethod": "POST",
              "description": "Index inspection.",
              "path": "v1/urlInspection/index:inspect",
              "scopes": [
                "https://www.googleapis.com/auth/webmasters",
                "https://www.googleapis.com/auth/webmasters.readonly"
              ],
              "flatPath": "v1/urlInspection/index:inspect"
            }
          }
        }
      }
    }
  },
  "servicePath": "",
  "name": "searchconsole",
  "kind": "discovery#restDescription",
  "version_module": true,
  "revision": "20260419",
  "baseUrl": "https://searchconsole.googleapis.com/",
  "mtlsRootUrl": "https://searchconsole.mtls.googleapis.com/",
  "canonicalName": "Search Console",
  "ownerDomain": "google.com"
}