{
  "documentationLink": "https://developers.google.com/webmaster-tools/about",
  "mtlsRootUrl": "https://searchconsole.mtls.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/webmasters": {
          "description": "View and manage Search Console data for your verified sites"
        },
        "https://www.googleapis.com/auth/webmasters.readonly": {
          "description": "View Search Console data for your verified sites"
        }
      }
    }
  },
  "canonicalName": "Search Console",
  "name": "searchconsole",
  "version_module": true,
  "description": "The Search Console API provides access to both Search Console data (verified users only) and to public information on an URL basis (anyone)",
  "discoveryVersion": "v1",
  "title": "Google Search Console API",
  "id": "searchconsole:v1",
  "version": "v1",
  "revision": "20260428",
  "resources": {
    "urlInspection": {
      "resources": {
        "index": {
          "methods": {
            "inspect": {
              "path": "v1/urlInspection/index:inspect",
              "id": "searchconsole.urlInspection.index.inspect",
              "scopes": [
                "https://www.googleapis.com/auth/webmasters",
                "https://www.googleapis.com/auth/webmasters.readonly"
              ],
              "flatPath": "v1/urlInspection/index:inspect",
              "httpMethod": "POST",
              "description": "Index inspection."
            }
          }
        }
      }
    },
    "sitemaps": {
      "methods": {
        "submit": {
          "description": "Submits a sitemap for a site.",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "id": "webmasters.sitemaps.submit",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}"
        },
        "list": {
          "description": " Lists the [sitemaps-entries](/webmaster-tools/v3/sitemaps) submitted for this site, or included in the sitemap index file (if `sitemapIndex` is specified in the request).",
          "httpMethod": "GET",
          "id": "webmasters.sitemaps.list",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ]
        },
        "delete": {
          "id": "webmasters.sitemaps.delete",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "httpMethod": "DELETE",
          "description": "Deletes a sitemap from the Sitemaps report. Does not stop Google from crawling this sitemap or the URLs that were previously crawled in the deleted sitemap.",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ]
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "flatPath": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "path": "webmasters/v3/sites/{siteUrl}/sitemaps/{feedpath}",
          "id": "webmasters.sitemaps.get",
          "description": "Retrieves information about a specific sitemap.",
          "httpMethod": "GET"
        }
      }
    },
    "searchanalytics": {
      "methods": {
        "query": {
          "description": "Query your data with filters and parameters that you define. Returns zero or more rows grouped by the row keys that you define. You must define a date range of one or more days. When date is one of the group by values, any days without data are omitted from the result list. If you need to know which days have data, issue a broad date range query grouped by date for any metric, and see which day rows are returned.",
          "httpMethod": "POST",
          "flatPath": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "id": "webmasters.searchanalytics.query",
          "path": "webmasters/v3/sites/{siteUrl}/searchAnalytics/query"
        }
      }
    },
    "urlTestingTools": {
      "resources": {
        "mobileFriendlyTest": {
          "methods": {
            "run": {
              "httpMethod": "POST",
              "description": "Runs Mobile-Friendly Test for a given URL.",
              "path": "v1/urlTestingTools/mobileFriendlyTest:run",
              "id": "searchconsole.urlTestingTools.mobileFriendlyTest.run",
              "flatPath": "v1/urlTestingTools/mobileFriendlyTest:run"
            }
          }
        }
      }
    },
    "sites": {
      "methods": {
        "add": {
          "path": "webmasters/v3/sites/{siteUrl}",
          "id": "webmasters.sites.add",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "description": " Adds a site to the set of the user's sites in Search Console.",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "httpMethod": "PUT"
        },
        "list": {
          "description": " Lists the user's Search Console sites.",
          "httpMethod": "GET",
          "path": "webmasters/v3/sites",
          "id": "webmasters.sites.list",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "flatPath": "webmasters/v3/sites"
        },
        "delete": {
          "description": " Removes a site from the set of the user's Search Console sites.",
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters"
          ],
          "id": "webmasters.sites.delete",
          "path": "webmasters/v3/sites/{siteUrl}"
        },
        "get": {
          "description": " Retrieves information about specific site.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/webmasters",
            "https://www.googleapis.com/auth/webmasters.readonly"
          ],
          "flatPath": "webmasters/v3/sites/{siteUrl}",
          "path": "webmasters/v3/sites/{siteUrl}",
          "id": "webmasters.sites.get"
        }
      }
    }
  },
  "ownerName": "Google",
  "rootUrl": "https://searchconsole.googleapis.com/",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "basePath": "",
  "protocol": "rest",
  "baseUrl": "https://searchconsole.googleapis.com/"
}