{
  "protocol": "rest",
  "version_module": true,
  "batchPath": "batch",
  "basePath": "",
  "discoveryVersion": "v1",
  "kind": "discovery#restDescription",
  "version": "v4",
  "title": "Google Sheets API",
  "ownerName": "Google",
  "revision": "20260401",
  "description": "Reads and writes Google Sheets.",
  "fullyEncodeReservedExpansion": true,
  "rootUrl": "https://sheets.googleapis.com/",
  "canonicalName": "Sheets",
  "documentationLink": "https://developers.google.com/workspace/sheets/",
  "resources": {
    "spreadsheets": {
      "methods": {
        "get": {
          "id": "sheets.spreadsheets.get",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly",
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/spreadsheets.readonly"
          ],
          "httpMethod": "GET",
          "flatPath": "v4/spreadsheets/{spreadsheetId}",
          "path": "v4/spreadsheets/{spreadsheetId}",
          "description": "Returns the spreadsheet at the given ID. The caller must specify the spreadsheet ID. By default, data within grids is not returned. You can include grid data in one of 2 ways: * Specify a [field mask](https://developers.google.com/workspace/sheets/api/guides/field-masks) listing your desired fields using the `fields` URL parameter in HTTP * Set the includeGridData URL parameter to true. If a field mask is set, the `includeGridData` parameter is ignored For large spreads[...]"
        },
        "create": {
          "id": "sheets.spreadsheets.create",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/spreadsheets"
          ],
          "httpMethod": "POST",
          "path": "v4/spreadsheets",
          "description": "Creates a spreadsheet, returning the newly created spreadsheet.",
          "flatPath": "v4/spreadsheets"
        },
        "getByDataFilter": {
          "id": "sheets.spreadsheets.getByDataFilter",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/spreadsheets"
          ],
          "httpMethod": "POST",
          "flatPath": "v4/spreadsheets/{spreadsheetId}:getByDataFilter",
          "path": "v4/spreadsheets/{spreadsheetId}:getByDataFilter",
          "description": "Returns the spreadsheet at the given ID. The caller must specify the spreadsheet ID. For more information, see [Read, write, and search metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). This method differs from GetSpreadsheet in that it allows selecting which subsets of spreadsheet data to return by specifying a dataFilters parameter. Multiple DataFilters can be specified. Specifying one or more data filters returns the portions of the sprea[...]"
        },
        "batchUpdate": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/spreadsheets"
          ],
          "id": "sheets.spreadsheets.batchUpdate",
          "flatPath": "v4/spreadsheets/{spreadsheetId}:batchUpdate",
          "path": "v4/spreadsheets/{spreadsheetId}:batchUpdate",
          "description": "Applies one or more updates to the spreadsheet. Each request is validated before being applied. If any request is not valid then the entire request will fail and nothing will be applied. Some requests have replies to give you some information about how they are applied. The replies will mirror the requests. For example, if you applied 4 updates and the 3rd one had a reply, then the response will have 2 empty replies, the actual reply, and another empty reply, in that or[...]"
        }
      },
      "resources": {
        "sheets": {
          "methods": {
            "copyTo": {
              "id": "sheets.spreadsheets.sheets.copyTo",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "httpMethod": "POST",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo",
              "path": "v4/spreadsheets/{spreadsheetId}/sheets/{sheetId}:copyTo",
              "description": "Copies a single sheet from a spreadsheet to another spreadsheet. Returns the properties of the newly created sheet."
            }
          }
        },
        "developerMetadata": {
          "methods": {
            "get": {
              "path": "v4/spreadsheets/{spreadsheetId}/developerMetadata/{metadataId}",
              "description": "Returns the developer metadata with the specified ID. The caller must specify the spreadsheet ID and the developer metadata's unique metadataId. For more information, see [Read, write, and search metadata](https://developers.google.com/workspace/sheets/api/guides/metadata).",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/developerMetadata/{metadataId}",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "httpMethod": "GET",
              "id": "sheets.spreadsheets.developerMetadata.get"
            },
            "search": {
              "id": "sheets.spreadsheets.developerMetadata.search",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "httpMethod": "POST",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/developerMetadata:search",
              "path": "v4/spreadsheets/{spreadsheetId}/developerMetadata:search",
              "description": "Returns all developer metadata matching the specified DataFilter. For more information, see [Read, write, and search metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). If the provided DataFilter represents a DeveloperMetadataLookup object, this will return all DeveloperMetadata entries selected by it. If the DataFilter represents a location in a spreadsheet, this will return all developer metadata associated with locations intersecting th[...]"
            }
          }
        },
        "values": {
          "methods": {
            "batchGet": {
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchGet",
              "description": "Returns one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more ranges.",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchGet",
              "id": "sheets.spreadsheets.values.batchGet",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/spreadsheets.readonly"
              ]
            },
            "batchUpdate": {
              "id": "sheets.spreadsheets.values.batchUpdate",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "httpMethod": "POST",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdate",
              "description": "Sets values in one or more ranges of a spreadsheet. The caller must specify the spreadsheet ID, a valueInputOption, and one or more ValueRanges."
            },
            "batchClear": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "id": "sheets.spreadsheets.values.batchClear",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchClear",
              "description": "Clears one or more ranges of values from a spreadsheet. The caller must specify the spreadsheet ID and one or more ranges. Only values are cleared -- all other properties of the cell (such as formatting and data validation) are kept.",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchClear"
            },
            "get": {
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "description": "Returns a range of values from a spreadsheet. The caller must specify the spreadsheet ID and a range.",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "id": "sheets.spreadsheets.values.get",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/drive.readonly",
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/spreadsheets.readonly"
              ],
              "httpMethod": "GET"
            },
            "append": {
              "id": "sheets.spreadsheets.values.append",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "httpMethod": "POST",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}:append",
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:append",
              "description": "Appends values to a spreadsheet. The input range is used to search for existing data and find a \"table\" within that range. Values will be appended to the next row of the table, starting with the first column of the table. See the [guide](https://developers.google.com/workspace/sheets/api/guides/values#appending_values) and [sample code](https://developers.google.com/workspace/sheets/api/samples/writing#append_values) for specific details of how tables are detected[...]"
            },
            "batchUpdateByDataFilter": {
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchUpdateByDataFilter",
              "description": "Sets values in one or more ranges of a spreadsheet. For more information, see [Read, write, and search metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). The caller must specify the spreadsheet ID, a valueInputOption, and one or more DataFilterValueRanges.",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchUpdateByDataFilter",
              "id": "sheets.spreadsheets.values.batchUpdateByDataFilter",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "httpMethod": "POST"
            },
            "update": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "id": "sheets.spreadsheets.values.update",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}",
              "description": "Sets values in a range of a spreadsheet. The caller must specify the spreadsheet ID, range, and a valueInputOption."
            },
            "batchClearByDataFilter": {
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchClearByDataFilter",
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchClearByDataFilter",
              "description": "Clears one or more ranges of values from a spreadsheet. For more information, see [Read, write, and search metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). The caller must specify the spreadsheet ID and one or more DataFilters. Ranges matching any of the specified data filters will be cleared. Only values are cleared -- all other properties of the cell (such as formatting, data validation, etc.) are kept.",
              "id": "sheets.spreadsheets.values.batchClearByDataFilter",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ]
            },
            "clear": {
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ],
              "id": "sheets.spreadsheets.values.clear",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values/{range}:clear",
              "path": "v4/spreadsheets/{spreadsheetId}/values/{range}:clear",
              "description": "Clears values from a spreadsheet. The caller must specify the spreadsheet ID and range. Only values are cleared -- all other properties of the cell (such as formatting, data validation, etc..) are kept."
            },
            "batchGetByDataFilter": {
              "path": "v4/spreadsheets/{spreadsheetId}/values:batchGetByDataFilter",
              "description": "Returns one or more ranges of values that match the specified data filters. For more information, see [Read, write, and search metadata](https://developers.google.com/workspace/sheets/api/guides/metadata). The caller must specify the spreadsheet ID and one or more DataFilters. Ranges that match any of the data filters in the request will be returned.",
              "flatPath": "v4/spreadsheets/{spreadsheetId}/values:batchGetByDataFilter",
              "id": "sheets.spreadsheets.values.batchGetByDataFilter",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/drive",
                "https://www.googleapis.com/auth/drive.file",
                "https://www.googleapis.com/auth/spreadsheets"
              ]
            }
          }
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/drive.file": {
          "description": "See, edit, create, and delete only the specific Google Drive files you use with this app"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/spreadsheets": {
          "description": "See, edit, create, and delete all your Google Sheets spreadsheets"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/spreadsheets.readonly": {
          "description": "See all your Google Sheets spreadsheets"
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "id": "sheets:v4",
  "baseUrl": "https://sheets.googleapis.com/",
  "servicePath": "",
  "mtlsRootUrl": "https://sheets.mtls.googleapis.com/",
  "name": "sheets"
}