{
  "rootUrl": "https://www.googleapis.com/",
  "ownerDomain": "google.com",
  "revision": "20191119",
  "documentationLink": "https://developers.google.com/site-verification/",
  "baseUrl": "https://www.googleapis.com/siteVerification/v1/",
  "batchPath": "batch/siteVerification/v1",
  "servicePath": "siteVerification/v1/",
  "kind": "discovery#restDescription",
  "basePath": "/siteVerification/v1/",
  "name": "siteVerification",
  "ownerName": "Google",
  "version": "v1",
  "etag": "\"u9GIe6H63LSGq-9_t39K2Zx_EAc/ffKkQHIfwnRAzOSRWAT_SYBS6HY\"",
  "title": "Google Site Verification API",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/siteverification": {
          "description": "Manage the list of sites and domains you control"
        },
        "https://www.googleapis.com/auth/siteverification.verify_only": {
          "description": "Manage your new site verifications with Google"
        }
      }
    }
  },
  "id": "siteVerification:v1",
  "resources": {
    "webResource": {
      "methods": {
        "delete": {
          "id": "siteVerification.webResource.delete",
          "path": "webResource/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/siteverification"
          ],
          "description": "Relinquish ownership of a website or domain.",
          "httpMethod": "DELETE"
        },
        "getToken": {
          "description": "Get a verification token for placing on a website or domain.",
          "httpMethod": "POST",
          "id": "siteVerification.webResource.getToken",
          "scopes": [
            "https://www.googleapis.com/auth/siteverification",
            "https://www.googleapis.com/auth/siteverification.verify_only"
          ],
          "path": "token"
        },
        "list": {
          "description": "Get the list of your verified websites and domains.",
          "httpMethod": "GET",
          "id": "siteVerification.webResource.list",
          "scopes": [
            "https://www.googleapis.com/auth/siteverification"
          ],
          "path": "webResource"
        },
        "insert": {
          "httpMethod": "POST",
          "id": "siteVerification.webResource.insert",
          "scopes": [
            "https://www.googleapis.com/auth/siteverification",
            "https://www.googleapis.com/auth/siteverification.verify_only"
          ],
          "path": "webResource",
          "description": "Attempt verification of a website or domain."
        },
        "get": {
          "httpMethod": "GET",
          "description": "Get the most current data for a website or domain.",
          "scopes": [
            "https://www.googleapis.com/auth/siteverification"
          ],
          "path": "webResource/{id}",
          "id": "siteVerification.webResource.get"
        },
        "patch": {
          "httpMethod": "PATCH",
          "description": "Modify the list of owners for your website or domain. This method supports patch semantics.",
          "id": "siteVerification.webResource.patch",
          "scopes": [
            "https://www.googleapis.com/auth/siteverification"
          ],
          "path": "webResource/{id}"
        },
        "update": {
          "description": "Modify the list of owners for your website or domain.",
          "id": "siteVerification.webResource.update",
          "path": "webResource/{id}",
          "scopes": [
            "https://www.googleapis.com/auth/siteverification"
          ],
          "httpMethod": "PUT"
        }
      }
    }
  },
  "protocol": "rest",
  "discoveryVersion": "v1",
  "description": "Verifies ownership of websites or domains with Google."
}