{
  "documentationLink": "https://developers.google.com/tag-manager",
  "title": "Tag Manager API",
  "mtlsRootUrl": "https://tagmanager.mtls.googleapis.com/",
  "protocol": "rest",
  "servicePath": "",
  "id": "tagmanager:v1",
  "discoveryVersion": "v1",
  "description": "This API allows clients to access and modify container and tag configuration.",
  "batchPath": "batch",
  "version": "v1",
  "baseUrl": "https://tagmanager.googleapis.com/",
  "name": "tagmanager",
  "resources": {
    "accounts": {
      "methods": {
        "update": {
          "flatPath": "tagmanager/v1/accounts/{accountId}",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/tagmanager.manage.accounts"
          ],
          "path": "tagmanager/v1/accounts/{accountId}",
          "id": "tagmanager.accounts.update",
          "description": "Updates a GTM Account."
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/tagmanager.edit.containers",
            "https://www.googleapis.com/auth/tagmanager.manage.accounts",
            "https://www.googleapis.com/auth/tagmanager.readonly"
          ],
          "flatPath": "tagmanager/v1/accounts",
          "path": "tagmanager/v1/accounts",
          "id": "tagmanager.accounts.list",
          "description": "Lists all GTM Accounts that a user has access to."
        },
        "get": {
          "path": "tagmanager/v1/accounts/{accountId}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/tagmanager.edit.containers",
            "https://www.googleapis.com/auth/tagmanager.manage.accounts",
            "https://www.googleapis.com/auth/tagmanager.readonly"
          ],
          "flatPath": "tagmanager/v1/accounts/{accountId}",
          "description": "Gets a GTM Account.",
          "id": "tagmanager.accounts.get"
        }
      },
      "resources": {
        "permissions": {
          "methods": {
            "create": {
              "path": "tagmanager/v1/accounts/{accountId}/permissions",
              "flatPath": "tagmanager/v1/accounts/{accountId}/permissions",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "description": "Creates a user's Account & Container Permissions.",
              "id": "tagmanager.accounts.permissions.create"
            },
            "get": {
              "path": "tagmanager/v1/accounts/{accountId}/permissions/{permissionId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "flatPath": "tagmanager/v1/accounts/{accountId}/permissions/{permissionId}",
              "description": "Gets a user's Account & Container Permissions.",
              "id": "tagmanager.accounts.permissions.get"
            },
            "update": {
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "flatPath": "tagmanager/v1/accounts/{accountId}/permissions/{permissionId}",
              "path": "tagmanager/v1/accounts/{accountId}/permissions/{permissionId}",
              "id": "tagmanager.accounts.permissions.update",
              "description": "Updates a user's Account & Container Permissions."
            },
            "delete": {
              "path": "tagmanager/v1/accounts/{accountId}/permissions/{permissionId}",
              "description": "Removes a user from the account, revoking access to it and all of its containers.",
              "id": "tagmanager.accounts.permissions.delete",
              "flatPath": "tagmanager/v1/accounts/{accountId}/permissions/{permissionId}",
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ]
            },
            "list": {
              "id": "tagmanager.accounts.permissions.list",
              "description": "List all users that have access to the account along with Account and Container Permissions granted to each of them.",
              "flatPath": "tagmanager/v1/accounts/{accountId}/permissions",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "path": "tagmanager/v1/accounts/{accountId}/permissions"
            }
          }
        },
        "containers": {
          "methods": {
            "list": {
              "description": "Lists all Containers that belongs to a GTM Account.",
              "id": "tagmanager.accounts.containers.list",
              "path": "tagmanager/v1/accounts/{accountId}/containers",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                "https://www.googleapis.com/auth/tagmanager.readonly"
              ],
              "flatPath": "tagmanager/v1/accounts/{accountId}/containers"
            },
            "update": {
              "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}",
              "httpMethod": "PUT",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers"
              ],
              "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}",
              "description": "Updates a Container.",
              "id": "tagmanager.accounts.containers.update"
            },
            "delete": {
              "httpMethod": "DELETE",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.delete.containers"
              ],
              "id": "tagmanager.accounts.containers.delete",
              "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}",
              "description": "Deletes a Container.",
              "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}"
            },
            "get": {
              "description": "Gets a Container.",
              "id": "tagmanager.accounts.containers.get",
              "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}",
              "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                "https://www.googleapis.com/auth/tagmanager.readonly"
              ]
            },
            "create": {
              "path": "tagmanager/v1/accounts/{accountId}/containers",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers"
              ],
              "flatPath": "tagmanager/v1/accounts/{accountId}/containers",
              "description": "Creates a Container.",
              "id": "tagmanager.accounts.containers.create"
            }
          },
          "resources": {
            "move_folders": {
              "methods": {
                "update": {
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/move_folders/{folderId}",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/move_folders/{folderId}",
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "description": "Moves entities to a GTM Folder.",
                  "id": "tagmanager.accounts.containers.move_folders.update"
                }
              }
            },
            "environments": {
              "methods": {
                "get": {
                  "id": "tagmanager.accounts.containers.environments.get",
                  "description": "Gets a GTM Environment.",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments/{environmentId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments/{environmentId}"
                },
                "create": {
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments",
                  "id": "tagmanager.accounts.containers.environments.create",
                  "description": "Creates a GTM Environment."
                },
                "list": {
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments",
                  "description": "Lists all GTM Environments of a GTM Container.",
                  "id": "tagmanager.accounts.containers.environments.list"
                },
                "update": {
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments/{environmentId}",
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments/{environmentId}",
                  "description": "Updates a GTM Environment.",
                  "id": "tagmanager.accounts.containers.environments.update"
                },
                "delete": {
                  "description": "Deletes a GTM Environment.",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments/{environmentId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "id": "tagmanager.accounts.containers.environments.delete",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/environments/{environmentId}"
                }
              }
            },
            "triggers": {
              "methods": {
                "update": {
                  "description": "Updates a GTM Trigger.",
                  "id": "tagmanager.accounts.containers.triggers.update",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ]
                },
                "delete": {
                  "description": "Deletes a GTM Trigger.",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "id": "tagmanager.accounts.containers.triggers.delete",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers/{triggerId}"
                },
                "list": {
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers",
                  "id": "tagmanager.accounts.containers.triggers.list",
                  "description": "Lists all GTM Triggers of a Container."
                },
                "create": {
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers",
                  "id": "tagmanager.accounts.containers.triggers.create",
                  "description": "Creates a GTM Trigger."
                },
                "get": {
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/triggers/{triggerId}",
                  "id": "tagmanager.accounts.containers.triggers.get",
                  "description": "Gets a GTM Trigger."
                }
              }
            },
            "folders": {
              "methods": {
                "update": {
                  "id": "tagmanager.accounts.containers.folders.update",
                  "description": "Updates a GTM Folder.",
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders/{folderId}",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders/{folderId}"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "id": "tagmanager.accounts.containers.folders.delete",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders/{folderId}",
                  "description": "Deletes a GTM Folder.",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders/{folderId}"
                },
                "list": {
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "description": "Lists all GTM Folders of a Container.",
                  "id": "tagmanager.accounts.containers.folders.list"
                },
                "create": {
                  "id": "tagmanager.accounts.containers.folders.create",
                  "description": "Creates a GTM Folder.",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders"
                },
                "get": {
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders/{folderId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders/{folderId}",
                  "description": "Gets a GTM Folder.",
                  "id": "tagmanager.accounts.containers.folders.get"
                }
              },
              "resources": {
                "entities": {
                  "methods": {
                    "list": {
                      "httpMethod": "GET",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders/{folderId}/entities",
                      "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/folders/{folderId}/entities",
                      "id": "tagmanager.accounts.containers.folders.entities.list",
                      "description": "List all entities in a GTM Folder."
                    }
                  }
                }
              }
            },
            "versions": {
              "methods": {
                "update": {
                  "id": "tagmanager.accounts.containers.versions.update",
                  "description": "Updates a Container Version.",
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}"
                },
                "delete": {
                  "id": "tagmanager.accounts.containers.versions.delete",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ],
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
                  "description": "Deletes a Container Version."
                },
                "undelete": {
                  "id": "tagmanager.accounts.containers.versions.undelete",
                  "description": "Undeletes a Container Version.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/undelete",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/undelete"
                },
                "restore": {
                  "description": "Restores a Container Version. This will overwrite the container's current configuration (including its variables, triggers and tags). The operation will not have any effect on the version that is being served (i.e. the published version).",
                  "id": "tagmanager.accounts.containers.versions.restore",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/restore",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/restore",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ]
                },
                "list": {
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "description": "Lists all Container Versions of a GTM Container.",
                  "id": "tagmanager.accounts.containers.versions.list"
                },
                "publish": {
                  "description": "Publishes a Container Version.",
                  "id": "tagmanager.accounts.containers.versions.publish",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/publish",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}/publish",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.publish"
                  ]
                },
                "create": {
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions",
                  "description": "Creates a Container Version.",
                  "id": "tagmanager.accounts.containers.versions.create"
                },
                "get": {
                  "id": "tagmanager.accounts.containers.versions.get",
                  "description": "Gets a Container Version.",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/versions/{containerVersionId}"
                }
              }
            },
            "variables": {
              "methods": {
                "get": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables/{variableId}",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables/{variableId}",
                  "id": "tagmanager.accounts.containers.variables.get",
                  "description": "Gets a GTM Variable."
                },
                "create": {
                  "id": "tagmanager.accounts.containers.variables.create",
                  "description": "Creates a GTM Variable.",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables"
                },
                "list": {
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables",
                  "id": "tagmanager.accounts.containers.variables.list",
                  "description": "Lists all GTM Variables of a Container."
                },
                "update": {
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables/{variableId}",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables/{variableId}",
                  "id": "tagmanager.accounts.containers.variables.update",
                  "description": "Updates a GTM Variable."
                },
                "delete": {
                  "description": "Deletes a GTM Variable.",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables/{variableId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "id": "tagmanager.accounts.containers.variables.delete",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/variables/{variableId}"
                }
              }
            },
            "tags": {
              "methods": {
                "create": {
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags",
                  "id": "tagmanager.accounts.containers.tags.create",
                  "description": "Creates a GTM Tag."
                },
                "get": {
                  "id": "tagmanager.accounts.containers.tags.get",
                  "description": "Gets a GTM Tag.",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags/{tagId}",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags/{tagId}"
                },
                "update": {
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags/{tagId}",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags/{tagId}",
                  "id": "tagmanager.accounts.containers.tags.update",
                  "description": "Updates a GTM Tag."
                },
                "delete": {
                  "id": "tagmanager.accounts.containers.tags.delete",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags/{tagId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags/{tagId}",
                  "description": "Deletes a GTM Tag."
                },
                "list": {
                  "description": "Lists all GTM Tags of a Container.",
                  "id": "tagmanager.accounts.containers.tags.list",
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags",
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/tags",
                  "httpMethod": "GET",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                }
              }
            },
            "reauthorize_environments": {
              "methods": {
                "update": {
                  "path": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/reauthorize_environments/{environmentId}",
                  "httpMethod": "PUT",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.publish"
                  ],
                  "flatPath": "tagmanager/v1/accounts/{accountId}/containers/{containerId}/reauthorize_environments/{environmentId}",
                  "description": "Re-generates the authorization code for a GTM Environment.",
                  "id": "tagmanager.accounts.containers.reauthorize_environments.update"
                }
              }
            }
          }
        }
      }
    }
  },
  "kind": "discovery#restDescription",
  "canonicalName": "Tag Manager",
  "basePath": "",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/tagmanager.readonly": {
          "description": "View your Google Tag Manager container and its subcomponents"
        },
        "https://www.googleapis.com/auth/tagmanager.edit.containerversions": {
          "description": "Manage your Google Tag Manager container versions"
        },
        "https://www.googleapis.com/auth/tagmanager.delete.containers": {
          "description": "Delete your Google Tag Manager containers"
        },
        "https://www.googleapis.com/auth/tagmanager.manage.users": {
          "description": "Manage user permissions of your Google Tag Manager account and container"
        },
        "https://www.googleapis.com/auth/tagmanager.publish": {
          "description": "Publish your Google Tag Manager container versions"
        },
        "https://www.googleapis.com/auth/tagmanager.edit.containers": {
          "description": "Manage your Google Tag Manager container and its subcomponents, excluding versioning and publishing"
        },
        "https://www.googleapis.com/auth/tagmanager.manage.accounts": {
          "description": "View and manage your Google Tag Manager accounts"
        }
      }
    }
  },
  "rootUrl": "https://tagmanager.googleapis.com/",
  "ownerName": "Google",
  "revision": "20260506",
  "ownerDomain": "google.com"
}