{
  "kind": "discovery#restDescription",
  "description": "This API allows clients to access and modify container and tag configuration.",
  "version": "v2",
  "ownerDomain": "google.com",
  "basePath": "",
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/tagmanager.manage.accounts": {
          "description": "View and manage your Google Tag Manager accounts"
        },
        "https://www.googleapis.com/auth/tagmanager.edit.containers": {
          "description": "Manage your Google Tag Manager container and its subcomponents, excluding versioning and publishing"
        },
        "https://www.googleapis.com/auth/tagmanager.delete.containers": {
          "description": "Delete your Google Tag Manager containers"
        },
        "https://www.googleapis.com/auth/tagmanager.manage.users": {
          "description": "Manage user permissions of your Google Tag Manager account and container"
        },
        "https://www.googleapis.com/auth/tagmanager.edit.containerversions": {
          "description": "Manage your Google Tag Manager container versions"
        },
        "https://www.googleapis.com/auth/tagmanager.publish": {
          "description": "Publish your Google Tag Manager container versions"
        },
        "https://www.googleapis.com/auth/tagmanager.readonly": {
          "description": "View your Google Tag Manager container and its subcomponents"
        }
      }
    }
  },
  "baseUrl": "https://tagmanager.googleapis.com/",
  "rootUrl": "https://tagmanager.googleapis.com/",
  "revision": "20260401",
  "mtlsRootUrl": "https://tagmanager.mtls.googleapis.com/",
  "documentationLink": "https://developers.google.com/tag-manager",
  "name": "tagmanager",
  "title": "Tag Manager API",
  "canonicalName": "Tag Manager",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "accounts": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "flatPath": "tagmanager/v2/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/tagmanager.manage.accounts"
          ],
          "path": "tagmanager/v2/{+path}",
          "description": "Updates a GTM Account.",
          "id": "tagmanager.accounts.update"
        },
        "list": {
          "path": "tagmanager/v2/accounts",
          "description": "Lists all GTM Accounts that a user has access to.",
          "httpMethod": "GET",
          "flatPath": "tagmanager/v2/accounts",
          "scopes": [
            "https://www.googleapis.com/auth/tagmanager.edit.containers",
            "https://www.googleapis.com/auth/tagmanager.manage.accounts",
            "https://www.googleapis.com/auth/tagmanager.readonly"
          ],
          "id": "tagmanager.accounts.list"
        },
        "get": {
          "httpMethod": "GET",
          "flatPath": "tagmanager/v2/accounts/{accountsId}",
          "scopes": [
            "https://www.googleapis.com/auth/tagmanager.edit.containers",
            "https://www.googleapis.com/auth/tagmanager.manage.accounts",
            "https://www.googleapis.com/auth/tagmanager.readonly"
          ],
          "path": "tagmanager/v2/{+path}",
          "description": "Gets a GTM Account.",
          "id": "tagmanager.accounts.get"
        }
      },
      "resources": {
        "user_permissions": {
          "methods": {
            "update": {
              "httpMethod": "PUT",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions/{user_permissionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "path": "tagmanager/v2/{+path}",
              "description": "Updates a user's Account & Container access.",
              "id": "tagmanager.accounts.user_permissions.update"
            },
            "delete": {
              "path": "tagmanager/v2/{+path}",
              "description": "Removes a user from the account, revoking access to it and all of its containers.",
              "httpMethod": "DELETE",
              "id": "tagmanager.accounts.user_permissions.delete",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions/{user_permissionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ]
            },
            "create": {
              "id": "tagmanager.accounts.user_permissions.create",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "httpMethod": "POST",
              "description": "Creates a user's Account & Container access.",
              "path": "tagmanager/v2/{+parent}/user_permissions"
            },
            "list": {
              "id": "tagmanager.accounts.user_permissions.list",
              "httpMethod": "GET",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "path": "tagmanager/v2/{+parent}/user_permissions",
              "description": "List all users that have access to the account along with Account and Container user access granted to each of them."
            },
            "get": {
              "description": "Gets a user's Account & Container access.",
              "path": "tagmanager/v2/{+path}",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/user_permissions/{user_permissionsId}",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.manage.users"
              ],
              "httpMethod": "GET",
              "id": "tagmanager.accounts.user_permissions.get"
            }
          }
        },
        "containers": {
          "methods": {
            "create": {
              "path": "tagmanager/v2/{+parent}/containers",
              "description": "Creates a Container.",
              "httpMethod": "POST",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers"
              ],
              "id": "tagmanager.accounts.containers.create"
            },
            "list": {
              "id": "tagmanager.accounts.containers.list",
              "path": "tagmanager/v2/{+parent}/containers",
              "description": "Lists all Containers that belongs to a GTM Account.",
              "httpMethod": "GET",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                "https://www.googleapis.com/auth/tagmanager.readonly"
              ]
            },
            "get": {
              "description": "Gets a Container.",
              "path": "tagmanager/v2/{+path}",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                "https://www.googleapis.com/auth/tagmanager.readonly"
              ],
              "httpMethod": "GET",
              "id": "tagmanager.accounts.containers.get"
            },
            "lookup": {
              "description": "Looks up a Container by destination ID or tag ID.",
              "path": "tagmanager/v2/accounts/containers:lookup",
              "flatPath": "tagmanager/v2/accounts/containers:lookup",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                "https://www.googleapis.com/auth/tagmanager.readonly"
              ],
              "httpMethod": "GET",
              "id": "tagmanager.accounts.containers.lookup"
            },
            "move_tag_id": {
              "description": "Move Tag ID out of a Container.",
              "path": "tagmanager/v2/{+path}:move_tag_id",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}:move_tag_id",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers"
              ],
              "httpMethod": "POST",
              "id": "tagmanager.accounts.containers.move_tag_id"
            },
            "update": {
              "id": "tagmanager.accounts.containers.update",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers"
              ],
              "httpMethod": "PUT",
              "description": "Updates a Container.",
              "path": "tagmanager/v2/{+path}"
            },
            "combine": {
              "httpMethod": "POST",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}:combine",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers"
              ],
              "path": "tagmanager/v2/{+path}:combine",
              "description": "Combines Containers.",
              "id": "tagmanager.accounts.containers.combine"
            },
            "delete": {
              "description": "Deletes a Container.",
              "path": "tagmanager/v2/{+path}",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.delete.containers"
              ],
              "id": "tagmanager.accounts.containers.delete",
              "httpMethod": "DELETE"
            },
            "snippet": {
              "path": "tagmanager/v2/{+path}:snippet",
              "description": "Gets the tagging snippet for a Container.",
              "httpMethod": "GET",
              "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}:snippet",
              "scopes": [
                "https://www.googleapis.com/auth/tagmanager.edit.containers",
                "https://www.googleapis.com/auth/tagmanager.readonly"
              ],
              "id": "tagmanager.accounts.containers.snippet"
            }
          },
          "resources": {
            "workspaces": {
              "methods": {
                "get": {
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Gets a Workspace.",
                  "path": "tagmanager/v2/{+path}",
                  "id": "tagmanager.accounts.containers.workspaces.get"
                },
                "bulk_update": {
                  "id": "tagmanager.accounts.containers.workspaces.bulk_update",
                  "path": "tagmanager/v2/{+path}/bulk_update",
                  "description": "Applies multiple entity changes to a workspace in one call. When creating new entities, their entity IDs must be unique and in correct format. That is, they must start with \"new_\" and followed by number, e.g. \"new_1\", \"new_2\". Example body snippet to create myNewTag under myNewFolder is: ``` \"changes\": [ { \"folder\": { \"folderId\": \"new_1\", \"name\": \"myNewFolder\", ... }, \"changeStatus\": \"added\" }, { \"tag\": { \"tagId\": \"new_2\", \"name\": \[...]",
                  "httpMethod": "POST",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/bulk_update",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ]
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "path": "tagmanager/v2/{+parent}/workspaces",
                  "description": "Creates a Workspace.",
                  "id": "tagmanager.accounts.containers.workspaces.create"
                },
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "path": "tagmanager/v2/{+parent}/workspaces",
                  "description": "Lists all Workspaces that belong to a GTM Container.",
                  "id": "tagmanager.accounts.containers.workspaces.list"
                },
                "create_version": {
                  "id": "tagmanager.accounts.containers.workspaces.create_version",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:create_version",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ],
                  "httpMethod": "POST",
                  "description": "Creates a Container Version from the entities present in the workspace, deletes the workspace, and sets the base container version to the newly created version.",
                  "path": "tagmanager/v2/{+path}:create_version"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.delete.containers"
                  ],
                  "id": "tagmanager.accounts.containers.workspaces.delete",
                  "path": "tagmanager/v2/{+path}",
                  "description": "Deletes a Workspace."
                },
                "quick_preview": {
                  "id": "tagmanager.accounts.containers.workspaces.quick_preview",
                  "path": "tagmanager/v2/{+path}:quick_preview",
                  "description": "Quick previews a workspace by creating a fake container version from all entities in the provided workspace.",
                  "httpMethod": "POST",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:quick_preview",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ]
                },
                "update": {
                  "description": "Updates a Workspace.",
                  "path": "tagmanager/v2/{+path}",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "httpMethod": "PUT",
                  "id": "tagmanager.accounts.containers.workspaces.update"
                },
                "getStatus": {
                  "path": "tagmanager/v2/{+path}/status",
                  "description": "Finds conflicting and modified entities in the workspace.",
                  "httpMethod": "GET",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/status",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "id": "tagmanager.accounts.containers.workspaces.getStatus"
                },
                "resolve_conflict": {
                  "id": "tagmanager.accounts.containers.workspaces.resolve_conflict",
                  "description": "Resolves a merge conflict for a workspace entity by updating it to the resolved entity passed in the request.",
                  "path": "tagmanager/v2/{+path}:resolve_conflict",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:resolve_conflict",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "httpMethod": "POST"
                },
                "sync": {
                  "id": "tagmanager.accounts.containers.workspaces.sync",
                  "path": "tagmanager/v2/{+path}:sync",
                  "description": "Syncs a workspace to the latest container version by updating all unmodified workspace entities and displaying conflicts for modified entities.",
                  "httpMethod": "POST",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}:sync",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ]
                }
              },
              "resources": {
                "variables": {
                  "methods": {
                    "create": {
                      "path": "tagmanager/v2/{+parent}/variables",
                      "description": "Creates a GTM Variable.",
                      "httpMethod": "POST",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "id": "tagmanager.accounts.containers.workspaces.variables.create"
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.variables.list",
                      "path": "tagmanager/v2/{+parent}/variables",
                      "description": "Lists all GTM Variables of a Container.",
                      "httpMethod": "GET",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "get": {
                      "httpMethod": "GET",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "path": "tagmanager/v2/{+path}",
                      "description": "Gets a GTM Variable.",
                      "id": "tagmanager.accounts.containers.workspaces.variables.get"
                    },
                    "update": {
                      "id": "tagmanager.accounts.containers.workspaces.variables.update",
                      "description": "Updates a GTM Variable.",
                      "path": "tagmanager/v2/{+path}",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "PUT"
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.variables.revert",
                      "path": "tagmanager/v2/{+path}:revert",
                      "description": "Reverts changes to a GTM Variable in a GTM Workspace.",
                      "httpMethod": "POST",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "delete": {
                      "description": "Deletes a GTM Variable.",
                      "path": "tagmanager/v2/{+path}",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/variables/{variablesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "id": "tagmanager.accounts.containers.workspaces.variables.delete",
                      "httpMethod": "DELETE"
                    }
                  }
                },
                "templates": {
                  "methods": {
                    "delete": {
                      "httpMethod": "DELETE",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "id": "tagmanager.accounts.containers.workspaces.templates.delete",
                      "path": "tagmanager/v2/{+path}",
                      "description": "Deletes a GTM Template."
                    },
                    "revert": {
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "POST",
                      "description": "Reverts changes to a GTM Template in a GTM Workspace.",
                      "path": "tagmanager/v2/{+path}:revert",
                      "id": "tagmanager.accounts.containers.workspaces.templates.revert"
                    },
                    "update": {
                      "id": "tagmanager.accounts.containers.workspaces.templates.update",
                      "path": "tagmanager/v2/{+path}",
                      "description": "Updates a GTM Template.",
                      "httpMethod": "PUT",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "import_from_gallery": {
                      "path": "tagmanager/v2/{+parent}/templates:import_from_gallery",
                      "description": "Imports a GTM Custom Template from Gallery.",
                      "httpMethod": "POST",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates:import_from_gallery",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "id": "tagmanager.accounts.containers.workspaces.templates.import_from_gallery"
                    },
                    "get": {
                      "id": "tagmanager.accounts.containers.workspaces.templates.get",
                      "description": "Gets a GTM Template.",
                      "path": "tagmanager/v2/{+path}",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates/{templatesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET"
                    },
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.templates.create",
                      "httpMethod": "POST",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "path": "tagmanager/v2/{+parent}/templates",
                      "description": "Creates a GTM Custom Template."
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.templates.list",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/templates",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET",
                      "description": "Lists all GTM Templates of a GTM container workspace.",
                      "path": "tagmanager/v2/{+parent}/templates"
                    }
                  }
                },
                "transformations": {
                  "methods": {
                    "get": {
                      "id": "tagmanager.accounts.containers.workspaces.transformations.get",
                      "description": "Gets a GTM Transformation.",
                      "path": "tagmanager/v2/{+path}",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/transformations/{transformationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET"
                    },
                    "create": {
                      "description": "Creates a GTM Transformation.",
                      "path": "tagmanager/v2/{+parent}/transformations",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/transformations",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.transformations.create"
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.transformations.list",
                      "httpMethod": "GET",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/transformations",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "path": "tagmanager/v2/{+parent}/transformations",
                      "description": "Lists all GTM Transformations of a GTM container workspace."
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "id": "tagmanager.accounts.containers.workspaces.transformations.delete",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/transformations/{transformationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "path": "tagmanager/v2/{+path}",
                      "description": "Deletes a GTM Transformation."
                    },
                    "update": {
                      "id": "tagmanager.accounts.containers.workspaces.transformations.update",
                      "path": "tagmanager/v2/{+path}",
                      "description": "Updates a GTM Transformation.",
                      "httpMethod": "PUT",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/transformations/{transformationsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.transformations.revert",
                      "description": "Reverts changes to a GTM Transformation in a GTM Workspace.",
                      "path": "tagmanager/v2/{+path}:revert",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/transformations/{transformationsId}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "POST"
                    }
                  }
                },
                "zones": {
                  "methods": {
                    "create": {
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "POST",
                      "description": "Creates a GTM Zone.",
                      "path": "tagmanager/v2/{+parent}/zones",
                      "id": "tagmanager.accounts.containers.workspaces.zones.create"
                    },
                    "list": {
                      "path": "tagmanager/v2/{+parent}/zones",
                      "description": "Lists all GTM Zones of a GTM container workspace.",
                      "httpMethod": "GET",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "id": "tagmanager.accounts.containers.workspaces.zones.list"
                    },
                    "get": {
                      "description": "Gets a GTM Zone.",
                      "path": "tagmanager/v2/{+path}",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET",
                      "id": "tagmanager.accounts.containers.workspaces.zones.get"
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.zones.revert",
                      "httpMethod": "POST",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "path": "tagmanager/v2/{+path}:revert",
                      "description": "Reverts changes to a GTM Zone in a GTM Workspace."
                    },
                    "update": {
                      "httpMethod": "PUT",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "path": "tagmanager/v2/{+path}",
                      "description": "Updates a GTM Zone.",
                      "id": "tagmanager.accounts.containers.workspaces.zones.update"
                    },
                    "delete": {
                      "httpMethod": "DELETE",
                      "id": "tagmanager.accounts.containers.workspaces.zones.delete",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/zones/{zonesId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "path": "tagmanager/v2/{+path}",
                      "description": "Deletes a GTM Zone."
                    }
                  }
                },
                "clients": {
                  "methods": {
                    "get": {
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/clients/{clientsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET",
                      "description": "Gets a GTM Client.",
                      "path": "tagmanager/v2/{+path}",
                      "id": "tagmanager.accounts.containers.workspaces.clients.get"
                    },
                    "create": {
                      "httpMethod": "POST",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/clients",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "path": "tagmanager/v2/{+parent}/clients",
                      "description": "Creates a GTM Client.",
                      "id": "tagmanager.accounts.containers.workspaces.clients.create"
                    },
                    "list": {
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/clients",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET",
                      "description": "Lists all GTM Clients of a GTM container workspace.",
                      "path": "tagmanager/v2/{+parent}/clients",
                      "id": "tagmanager.accounts.containers.workspaces.clients.list"
                    },
                    "delete": {
                      "path": "tagmanager/v2/{+path}",
                      "description": "Deletes a GTM Client.",
                      "httpMethod": "DELETE",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/clients/{clientsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "id": "tagmanager.accounts.containers.workspaces.clients.delete"
                    },
                    "update": {
                      "id": "tagmanager.accounts.containers.workspaces.clients.update",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/clients/{clientsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "PUT",
                      "description": "Updates a GTM Client.",
                      "path": "tagmanager/v2/{+path}"
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.clients.revert",
                      "description": "Reverts changes to a GTM Client in a GTM Workspace.",
                      "path": "tagmanager/v2/{+path}:revert",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/clients/{clientsId}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "POST"
                    }
                  }
                },
                "built_in_variables": {
                  "methods": {
                    "delete": {
                      "httpMethod": "DELETE",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "id": "tagmanager.accounts.containers.workspaces.built_in_variables.delete",
                      "path": "tagmanager/v2/{+path}",
                      "description": "Deletes one or more GTM Built-In Variables."
                    },
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.built_in_variables.create",
                      "description": "Creates one or more GTM Built-In Variables.",
                      "path": "tagmanager/v2/{+parent}/built_in_variables",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "POST"
                    },
                    "list": {
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET",
                      "description": "Lists all the enabled Built-In Variables of a GTM Container.",
                      "path": "tagmanager/v2/{+parent}/built_in_variables",
                      "id": "tagmanager.accounts.containers.workspaces.built_in_variables.list"
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.built_in_variables.revert",
                      "httpMethod": "POST",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/built_in_variables:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "path": "tagmanager/v2/{+path}/built_in_variables:revert",
                      "description": "Reverts changes to a GTM Built-In Variables in a GTM Workspace."
                    }
                  }
                },
                "triggers": {
                  "methods": {
                    "delete": {
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "id": "tagmanager.accounts.containers.workspaces.triggers.delete",
                      "httpMethod": "DELETE",
                      "description": "Deletes a GTM Trigger.",
                      "path": "tagmanager/v2/{+path}"
                    },
                    "revert": {
                      "path": "tagmanager/v2/{+path}:revert",
                      "description": "Reverts changes to a GTM Trigger in a GTM Workspace.",
                      "httpMethod": "POST",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "id": "tagmanager.accounts.containers.workspaces.triggers.revert"
                    },
                    "update": {
                      "path": "tagmanager/v2/{+path}",
                      "description": "Updates a GTM Trigger.",
                      "httpMethod": "PUT",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "id": "tagmanager.accounts.containers.workspaces.triggers.update"
                    },
                    "get": {
                      "id": "tagmanager.accounts.containers.workspaces.triggers.get",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers/{triggersId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET",
                      "description": "Gets a GTM Trigger.",
                      "path": "tagmanager/v2/{+path}"
                    },
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.triggers.create",
                      "httpMethod": "POST",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "path": "tagmanager/v2/{+parent}/triggers",
                      "description": "Creates a GTM Trigger."
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.triggers.list",
                      "httpMethod": "GET",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/triggers",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "path": "tagmanager/v2/{+parent}/triggers",
                      "description": "Lists all GTM Triggers of a Container."
                    }
                  }
                },
                "tags": {
                  "methods": {
                    "delete": {
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "id": "tagmanager.accounts.containers.workspaces.tags.delete",
                      "httpMethod": "DELETE",
                      "description": "Deletes a GTM Tag.",
                      "path": "tagmanager/v2/{+path}"
                    },
                    "revert": {
                      "id": "tagmanager.accounts.containers.workspaces.tags.revert",
                      "httpMethod": "POST",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "path": "tagmanager/v2/{+path}:revert",
                      "description": "Reverts changes to a GTM Tag in a GTM Workspace."
                    },
                    "update": {
                      "id": "tagmanager.accounts.containers.workspaces.tags.update",
                      "httpMethod": "PUT",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "path": "tagmanager/v2/{+path}",
                      "description": "Updates a GTM Tag."
                    },
                    "get": {
                      "id": "tagmanager.accounts.containers.workspaces.tags.get",
                      "description": "Gets a GTM Tag.",
                      "path": "tagmanager/v2/{+path}",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags/{tagsId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET"
                    },
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.tags.create",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "POST",
                      "description": "Creates a GTM Tag.",
                      "path": "tagmanager/v2/{+parent}/tags"
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.tags.list",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/tags",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET",
                      "description": "Lists all GTM Tags of a Container.",
                      "path": "tagmanager/v2/{+parent}/tags"
                    }
                  }
                },
                "gtag_config": {
                  "methods": {
                    "update": {
                      "httpMethod": "PUT",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/gtag_config/{gtag_configId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "path": "tagmanager/v2/{+path}",
                      "description": "Updates a Google tag config.",
                      "id": "tagmanager.accounts.containers.workspaces.gtag_config.update"
                    },
                    "delete": {
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/gtag_config/{gtag_configId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "id": "tagmanager.accounts.containers.workspaces.gtag_config.delete",
                      "httpMethod": "DELETE",
                      "description": "Deletes a Google tag config.",
                      "path": "tagmanager/v2/{+path}"
                    },
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.gtag_config.create",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/gtag_config",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "POST",
                      "description": "Creates a Google tag config.",
                      "path": "tagmanager/v2/{+parent}/gtag_config"
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.gtag_config.list",
                      "path": "tagmanager/v2/{+parent}/gtag_config",
                      "description": "Lists all Google tag configs in a Container.",
                      "httpMethod": "GET",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/gtag_config",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ]
                    },
                    "get": {
                      "id": "tagmanager.accounts.containers.workspaces.gtag_config.get",
                      "description": "Gets a Google tag config.",
                      "path": "tagmanager/v2/{+path}",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/gtag_config/{gtag_configId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET"
                    }
                  }
                },
                "folders": {
                  "methods": {
                    "update": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.update",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "PUT",
                      "description": "Updates a GTM Folder.",
                      "path": "tagmanager/v2/{+path}"
                    },
                    "entities": {
                      "httpMethod": "POST",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:entities",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "path": "tagmanager/v2/{+path}:entities",
                      "description": "List all entities in a GTM Folder.",
                      "id": "tagmanager.accounts.containers.workspaces.folders.entities"
                    },
                    "revert": {
                      "description": "Reverts changes to a GTM Folder in a GTM Workspace.",
                      "path": "tagmanager/v2/{+path}:revert",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:revert",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "POST",
                      "id": "tagmanager.accounts.containers.workspaces.folders.revert"
                    },
                    "delete": {
                      "path": "tagmanager/v2/{+path}",
                      "description": "Deletes a GTM Folder.",
                      "httpMethod": "DELETE",
                      "id": "tagmanager.accounts.containers.workspaces.folders.delete",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "create": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.create",
                      "path": "tagmanager/v2/{+parent}/folders",
                      "description": "Creates a GTM Folder.",
                      "httpMethod": "POST",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ]
                    },
                    "list": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.list",
                      "description": "Lists all GTM Folders of a Container.",
                      "path": "tagmanager/v2/{+parent}/folders",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET"
                    },
                    "get": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.get",
                      "description": "Gets a GTM Folder.",
                      "path": "tagmanager/v2/{+path}",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers",
                        "https://www.googleapis.com/auth/tagmanager.readonly"
                      ],
                      "httpMethod": "GET"
                    },
                    "move_entities_to_folder": {
                      "id": "tagmanager.accounts.containers.workspaces.folders.move_entities_to_folder",
                      "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/workspaces/{workspacesId}/folders/{foldersId}:move_entities_to_folder",
                      "scopes": [
                        "https://www.googleapis.com/auth/tagmanager.edit.containers"
                      ],
                      "httpMethod": "POST",
                      "description": "Moves entities to a GTM Folder. If {folder_id} in the request path equals 0, this will instead move entities out of the folder they currently belong to.",
                      "path": "tagmanager/v2/{+path}:move_entities_to_folder"
                    }
                  }
                }
              }
            },
            "destinations": {
              "methods": {
                "list": {
                  "id": "tagmanager.accounts.containers.destinations.list",
                  "httpMethod": "GET",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/destinations",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "path": "tagmanager/v2/{+parent}/destinations",
                  "description": "Lists all Destinations linked to a GTM Container."
                },
                "link": {
                  "id": "tagmanager.accounts.containers.destinations.link",
                  "httpMethod": "POST",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/destinations:link",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "path": "tagmanager/v2/{+parent}/destinations:link",
                  "description": "Adds a Destination to this Container and removes it from the Container to which it is currently linked."
                },
                "get": {
                  "id": "tagmanager.accounts.containers.destinations.get",
                  "path": "tagmanager/v2/{+path}",
                  "description": "Gets a Destination.",
                  "httpMethod": "GET",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/destinations/{destinationsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                }
              }
            },
            "version_headers": {
              "methods": {
                "list": {
                  "id": "tagmanager.accounts.containers.version_headers.list",
                  "path": "tagmanager/v2/{+parent}/version_headers",
                  "description": "Lists all Container Versions of a GTM Container.",
                  "httpMethod": "GET",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/version_headers",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                },
                "latest": {
                  "id": "tagmanager.accounts.containers.version_headers.latest",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/version_headers:latest",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Gets the latest container version header",
                  "path": "tagmanager/v2/{+parent}/version_headers:latest"
                }
              }
            },
            "versions": {
              "methods": {
                "undelete": {
                  "id": "tagmanager.accounts.containers.versions.undelete",
                  "path": "tagmanager/v2/{+path}:undelete",
                  "description": "Undeletes a Container Version.",
                  "httpMethod": "POST",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:undelete",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ]
                },
                "publish": {
                  "path": "tagmanager/v2/{+path}:publish",
                  "description": "Publishes a Container Version.",
                  "httpMethod": "POST",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:publish",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.publish"
                  ],
                  "id": "tagmanager.accounts.containers.versions.publish"
                },
                "get": {
                  "description": "Gets a Container Version.",
                  "path": "tagmanager/v2/{+path}",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "httpMethod": "GET",
                  "id": "tagmanager.accounts.containers.versions.get"
                },
                "set_latest": {
                  "id": "tagmanager.accounts.containers.versions.set_latest",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}:set_latest",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "httpMethod": "POST",
                  "description": "Sets the latest version used for synchronization of workspaces when detecting conflicts and errors.",
                  "path": "tagmanager/v2/{+path}:set_latest"
                },
                "live": {
                  "id": "tagmanager.accounts.containers.versions.live",
                  "path": "tagmanager/v2/{+parent}/versions:live",
                  "description": "Gets the live (i.e. published) container version",
                  "httpMethod": "GET",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions:live",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ]
                },
                "update": {
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ],
                  "httpMethod": "PUT",
                  "description": "Updates a Container Version.",
                  "path": "tagmanager/v2/{+path}",
                  "id": "tagmanager.accounts.containers.versions.update"
                },
                "delete": {
                  "httpMethod": "DELETE",
                  "id": "tagmanager.accounts.containers.versions.delete",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/versions/{versionsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containerversions"
                  ],
                  "path": "tagmanager/v2/{+path}",
                  "description": "Deletes a Container Version."
                }
              }
            },
            "environments": {
              "methods": {
                "delete": {
                  "description": "Deletes a GTM Environment.",
                  "path": "tagmanager/v2/{+path}",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "id": "tagmanager.accounts.containers.environments.delete",
                  "httpMethod": "DELETE"
                },
                "update": {
                  "id": "tagmanager.accounts.containers.environments.update",
                  "httpMethod": "PUT",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "path": "tagmanager/v2/{+path}",
                  "description": "Updates a GTM Environment."
                },
                "get": {
                  "httpMethod": "GET",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "path": "tagmanager/v2/{+path}",
                  "description": "Gets a GTM Environment.",
                  "id": "tagmanager.accounts.containers.environments.get"
                },
                "reauthorize": {
                  "id": "tagmanager.accounts.containers.environments.reauthorize",
                  "description": "Re-generates the authorization code for a GTM Environment.",
                  "path": "tagmanager/v2/{+path}:reauthorize",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments/{environmentsId}:reauthorize",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.publish"
                  ],
                  "httpMethod": "POST"
                },
                "create": {
                  "httpMethod": "POST",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers"
                  ],
                  "path": "tagmanager/v2/{+parent}/environments",
                  "description": "Creates a GTM Environment.",
                  "id": "tagmanager.accounts.containers.environments.create"
                },
                "list": {
                  "httpMethod": "GET",
                  "flatPath": "tagmanager/v2/accounts/{accountsId}/containers/{containersId}/environments",
                  "scopes": [
                    "https://www.googleapis.com/auth/tagmanager.edit.containers",
                    "https://www.googleapis.com/auth/tagmanager.readonly"
                  ],
                  "path": "tagmanager/v2/{+parent}/environments",
                  "description": "Lists all GTM Environments of a GTM Container.",
                  "id": "tagmanager.accounts.containers.environments.list"
                }
              }
            }
          }
        }
      }
    }
  },
  "batchPath": "batch",
  "servicePath": "",
  "id": "tagmanager:v2"
}