{
  "revision": "20260310",
  "title": "Google Tasks API",
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/tasks": {
          "description": "Create, edit, organize, and delete all your tasks"
        },
        "https://www.googleapis.com/auth/tasks.readonly": {
          "description": "View your tasks"
        }
      }
    }
  },
  "description": "The Google Tasks API lets you manage your tasks and task lists.",
  "fullyEncodeReservedExpansion": true,
  "ownerName": "Google",
  "baseUrl": "https://tasks.googleapis.com/",
  "version": "v1",
  "basePath": "",
  "canonicalName": "Tasks",
  "resources": {
    "tasks": {
      "methods": {
        "delete": {
          "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "id": "tasks.tasks.delete",
          "description": "Deletes the specified task from the task list. If the task is assigned, both the assigned task and the original task (in Docs, Chat Spaces) are deleted. To delete the assigned task only, navigate to the assignment surface and unassign the task from there.",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "httpMethod": "POST",
          "description": "Creates a new task on the specified task list. Tasks assigned from Docs or Chat Spaces cannot be inserted from Tasks Public API; they can only be created by assigning them from Docs or Chat Spaces. A user can have up to 20,000 non-hidden tasks per list and up to 100,000 tasks in total at a time.",
          "id": "tasks.tasks.insert",
          "path": "tasks/v1/lists/{tasklist}/tasks",
          "flatPath": "tasks/v1/lists/{tasklist}/tasks"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/tasks",
            "https://www.googleapis.com/auth/tasks.readonly"
          ],
          "path": "tasks/v1/lists/{tasklist}/tasks",
          "flatPath": "tasks/v1/lists/{tasklist}/tasks",
          "id": "tasks.tasks.list",
          "description": "Returns all tasks in the specified task list. Doesn't return assigned tasks by default (from Docs, Chat Spaces). A user can have up to 20,000 non-hidden tasks per list and up to 100,000 tasks in total at a time."
        },
        "clear": {
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "description": "Clears all completed tasks from the specified task list. The affected tasks will be marked as 'hidden' and no longer be returned by default when retrieving all tasks for a task list.",
          "httpMethod": "POST",
          "id": "tasks.tasks.clear",
          "flatPath": "tasks/v1/lists/{tasklist}/clear",
          "path": "tasks/v1/lists/{tasklist}/clear"
        },
        "get": {
          "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "id": "tasks.tasks.get",
          "description": "Returns the specified task.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/tasks",
            "https://www.googleapis.com/auth/tasks.readonly"
          ]
        },
        "move": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "path": "tasks/v1/lists/{tasklist}/tasks/{task}/move",
          "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}/move",
          "id": "tasks.tasks.move",
          "description": "Moves the specified task to another position in the destination task list. If the destination list is not specified, the task is moved within its current list. This can include putting it as a child task under a new parent and/or move it to a different position among its sibling tasks. A user can have up to 2,000 subtasks per task."
        },
        "patch": {
          "description": "Updates the specified task. This method supports patch semantics.",
          "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "id": "tasks.tasks.patch",
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        },
        "update": {
          "id": "tasks.tasks.update",
          "path": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "flatPath": "tasks/v1/lists/{tasklist}/tasks/{task}",
          "description": "Updates the specified task.",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "httpMethod": "PUT"
        }
      }
    },
    "tasklists": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "path": "tasks/v1/users/@me/lists",
          "flatPath": "tasks/v1/users/@me/lists",
          "id": "tasks.tasklists.insert",
          "description": "Creates a new task list and adds it to the authenticated user's task lists. A user can have up to 2000 lists at a time."
        },
        "delete": {
          "path": "tasks/v1/users/@me/lists/{tasklist}",
          "flatPath": "tasks/v1/users/@me/lists/{tasklist}",
          "id": "tasks.tasklists.delete",
          "httpMethod": "DELETE",
          "description": "Deletes the authenticated user's specified task list. If the list contains assigned tasks, both the assigned tasks and the original tasks in the assignment surface (Docs, Chat Spaces) are deleted.",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ]
        },
        "get": {
          "path": "tasks/v1/users/@me/lists/{tasklist}",
          "flatPath": "tasks/v1/users/@me/lists/{tasklist}",
          "id": "tasks.tasklists.get",
          "description": "Returns the authenticated user's specified task list.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/tasks",
            "https://www.googleapis.com/auth/tasks.readonly"
          ]
        },
        "patch": {
          "httpMethod": "PATCH",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "flatPath": "tasks/v1/users/@me/lists/{tasklist}",
          "path": "tasks/v1/users/@me/lists/{tasklist}",
          "id": "tasks.tasklists.patch",
          "description": "Updates the authenticated user's specified task list. This method supports patch semantics."
        },
        "update": {
          "id": "tasks.tasklists.update",
          "path": "tasks/v1/users/@me/lists/{tasklist}",
          "flatPath": "tasks/v1/users/@me/lists/{tasklist}",
          "description": "Updates the authenticated user's specified task list.",
          "scopes": [
            "https://www.googleapis.com/auth/tasks"
          ],
          "httpMethod": "PUT"
        },
        "list": {
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/tasks",
            "https://www.googleapis.com/auth/tasks.readonly"
          ],
          "path": "tasks/v1/users/@me/lists",
          "flatPath": "tasks/v1/users/@me/lists",
          "id": "tasks.tasklists.list",
          "description": "Returns all the authenticated user's task lists. A user can have up to 2000 lists at a time."
        }
      }
    }
  },
  "id": "tasks:v1",
  "documentationLink": "https://developers.google.com/workspace/tasks/",
  "batchPath": "batch",
  "ownerDomain": "google.com",
  "rootUrl": "https://tasks.googleapis.com/",
  "servicePath": "",
  "kind": "discovery#restDescription",
  "mtlsRootUrl": "https://tasks.mtls.googleapis.com/",
  "name": "tasks",
  "protocol": "rest"
}