{
  "basePath": "",
  "discoveryVersion": "v1",
  "batchPath": "batch",
  "id": "vault:v1",
  "baseUrl": "https://vault.googleapis.com/",
  "ownerDomain": "google.com",
  "description": "Retention and eDiscovery for Google Workspace. To work with Vault resources, the account must have the [required Vault privileges](https://support.google.com/vault/answer/2799699) and access to the matter. To access a matter, the account must have created the matter, have the matter shared with them, or have the **View All Matters** privilege. For example, to download an export, an account needs the **Manage Exports** privilege and the matter shared with them. ",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery.readonly": {
          "description": "View your eDiscovery data"
        },
        "https://www.googleapis.com/auth/ediscovery": {
          "description": "Manage your eDiscovery data"
        }
      }
    }
  },
  "title": "Google Vault API",
  "name": "vault",
  "ownerName": "Google",
  "revision": "20260512",
  "rootUrl": "https://vault.googleapis.com/",
  "servicePath": "",
  "documentationLink": "https://developers.google.com/workspace/vault",
  "resources": {
    "operations": {
      "methods": {
        "get": {
          "id": "vault.operations.get",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "GET",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "path": "v1/{+name}"
        },
        "delete": {
          "id": "vault.operations.delete",
          "flatPath": "v1/operations/{operationsId}",
          "path": "v1/{+name}",
          "httpMethod": "DELETE",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "list": {
          "id": "vault.operations.list",
          "flatPath": "v1/operations",
          "path": "v1/{+name}",
          "httpMethod": "GET",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "cancel": {
          "id": "vault.operations.cancel",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "path": "v1/{+name}:cancel",
          "httpMethod": "POST",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        }
      }
    },
    "matters": {
      "methods": {
        "create": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "httpMethod": "POST",
          "description": "Creates a matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view.",
          "path": "v1/matters",
          "id": "vault.matters.create",
          "flatPath": "v1/matters"
        },
        "update": {
          "id": "vault.matters.update",
          "flatPath": "v1/matters/{matterId}",
          "path": "v1/matters/{matterId}",
          "httpMethod": "PUT",
          "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "reopen": {
          "path": "v1/matters/{matterId}:reopen",
          "httpMethod": "POST",
          "description": "Reopens the specified matter. Returns the matter with updated state.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.reopen",
          "flatPath": "v1/matters/{matterId}:reopen"
        },
        "addPermissions": {
          "id": "vault.matters.addPermissions",
          "flatPath": "v1/matters/{matterId}:addPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "httpMethod": "POST",
          "description": "Adds an account as a matter collaborator.",
          "path": "v1/matters/{matterId}:addPermissions"
        },
        "delete": {
          "path": "v1/matters/{matterId}",
          "httpMethod": "DELETE",
          "description": "Deletes the specified matter. Returns the matter with updated state.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.delete",
          "flatPath": "v1/matters/{matterId}"
        },
        "count": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "httpMethod": "POST",
          "description": "Counts the accounts processed by the specified query.",
          "path": "v1/matters/{matterId}:count",
          "id": "vault.matters.count",
          "flatPath": "v1/matters/{matterId}:count"
        },
        "list": {
          "path": "v1/matters",
          "httpMethod": "GET",
          "description": "Lists matters the requestor has access to.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "id": "vault.matters.list",
          "flatPath": "v1/matters"
        },
        "close": {
          "id": "vault.matters.close",
          "flatPath": "v1/matters/{matterId}:close",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "httpMethod": "POST",
          "description": "Closes the specified matter. Returns the matter with updated state.",
          "path": "v1/matters/{matterId}:close"
        },
        "undelete": {
          "id": "vault.matters.undelete",
          "flatPath": "v1/matters/{matterId}:undelete",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "httpMethod": "POST",
          "description": "Undeletes the specified matter. Returns the matter with updated state.",
          "path": "v1/matters/{matterId}:undelete"
        },
        "get": {
          "id": "vault.matters.get",
          "flatPath": "v1/matters/{matterId}",
          "path": "v1/matters/{matterId}",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "httpMethod": "GET",
          "description": "Gets the specified matter."
        },
        "removePermissions": {
          "id": "vault.matters.removePermissions",
          "flatPath": "v1/matters/{matterId}:removePermissions",
          "path": "v1/matters/{matterId}:removePermissions",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "httpMethod": "POST",
          "description": "Removes an account as a matter collaborator."
        }
      },
      "resources": {
        "savedQueries": {
          "methods": {
            "create": {
              "path": "v1/matters/{matterId}/savedQueries",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "POST",
              "description": "Creates a saved query.",
              "id": "vault.matters.savedQueries.create",
              "flatPath": "v1/matters/{matterId}/savedQueries"
            },
            "list": {
              "httpMethod": "GET",
              "description": "Lists the saved queries in a matter.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/savedQueries",
              "id": "vault.matters.savedQueries.list",
              "flatPath": "v1/matters/{matterId}/savedQueries"
            },
            "get": {
              "id": "vault.matters.savedQueries.get",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "GET",
              "description": "Retrieves the specified saved query.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes the specified saved query.",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "id": "vault.matters.savedQueries.delete",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}"
            }
          }
        },
        "exports": {
          "methods": {
            "create": {
              "id": "vault.matters.exports.create",
              "flatPath": "v1/matters/{matterId}/exports",
              "path": "v1/matters/{matterId}/exports",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "POST",
              "description": "Creates an export."
            },
            "list": {
              "id": "vault.matters.exports.list",
              "flatPath": "v1/matters/{matterId}/exports",
              "path": "v1/matters/{matterId}/exports",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "httpMethod": "GET",
              "description": "Lists details about the exports in the specified matter."
            },
            "get": {
              "id": "vault.matters.exports.get",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "httpMethod": "GET",
              "description": "Gets an export.",
              "path": "v1/matters/{matterId}/exports/{exportId}"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "DELETE",
              "description": "Deletes an export.",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "id": "vault.matters.exports.delete",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}"
            }
          }
        },
        "holds": {
          "resources": {
            "accounts": {
              "methods": {
                "create": {
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "httpMethod": "POST",
                  "description": "Adds an account to a hold. Accounts can be added only to a hold that does not have an organizational unit set. If you try to add an account to an organizational unit-based hold, an error is returned.",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "id": "vault.matters.holds.accounts.create",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts"
                },
                "list": {
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery",
                    "https://www.googleapis.com/auth/ediscovery.readonly"
                  ],
                  "httpMethod": "GET",
                  "description": "Lists the accounts covered by a hold. This can list only individually-specified accounts covered by the hold. If the hold covers an organizational unit, use the [Admin SDK](https://developers.google.com/admin-sdk/). to list the members of the organizational unit on hold.",
                  "id": "vault.matters.holds.accounts.list",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts"
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "httpMethod": "DELETE",
                  "description": "Removes an account from a hold.",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "id": "vault.matters.holds.accounts.delete",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}"
                }
              }
            }
          },
          "methods": {
            "addHeldAccounts": {
              "httpMethod": "POST",
              "description": "Adds accounts to a hold. Returns a list of accounts that have been successfully added. Accounts can be added only to an existing account-based hold.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "id": "vault.matters.holds.addHeldAccounts",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts"
            },
            "delete": {
              "id": "vault.matters.holds.delete",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "DELETE",
              "description": "Removes the specified hold and releases the accounts or organizational unit covered by the hold. If the data is not preserved by another hold or retention rule, it might be purged.",
              "path": "v1/matters/{matterId}/holds/{holdId}"
            },
            "removeHeldAccounts": {
              "id": "vault.matters.holds.removeHeldAccounts",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "POST",
              "description": "Removes the specified accounts from a hold. Returns a list of statuses in the same order as the request."
            },
            "create": {
              "id": "vault.matters.holds.create",
              "flatPath": "v1/matters/{matterId}/holds",
              "httpMethod": "POST",
              "description": "Creates a hold in the specified matter.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds"
            },
            "list": {
              "path": "v1/matters/{matterId}/holds",
              "httpMethod": "GET",
              "description": "Lists the holds in a matter.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "id": "vault.matters.holds.list",
              "flatPath": "v1/matters/{matterId}/holds"
            },
            "update": {
              "id": "vault.matters.holds.update",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "httpMethod": "PUT",
              "description": "Updates the scope (organizational unit or accounts) and query parameters of a hold. You cannot add accounts to a hold that covers an organizational unit, nor can you add organizational units to a hold that covers individual accounts. If you try, the unsupported values are ignored."
            },
            "get": {
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "httpMethod": "GET",
              "description": "Gets the specified hold.",
              "id": "vault.matters.holds.get",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}"
            }
          }
        }
      }
    }
  },
  "version": "v1",
  "canonicalName": "Vault",
  "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
  "kind": "discovery#restDescription",
  "protocol": "rest"
}