{
  "discoveryVersion": "v1",
  "version": "v1",
  "ownerDomain": "google.com",
  "protocol": "rest",
  "documentationLink": "https://developers.google.com/workspace/vault",
  "batchPath": "batch",
  "version_module": true,
  "resources": {
    "operations": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "id": "vault.operations.get",
          "path": "v1/{+name}",
          "httpMethod": "GET",
          "flatPath": "v1/operations/{operationsId}",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service."
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "flatPath": "v1/operations",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "path": "v1/{+name}",
          "httpMethod": "GET",
          "id": "vault.operations.list"
        },
        "delete": {
          "flatPath": "v1/operations/{operationsId}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "id": "vault.operations.delete",
          "path": "v1/{+name}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "cancel": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/operations/{operationsId}:cancel",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "path": "v1/{+name}:cancel",
          "httpMethod": "POST",
          "id": "vault.operations.cancel"
        }
      }
    },
    "matters": {
      "methods": {
        "undelete": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}:undelete",
          "httpMethod": "POST",
          "id": "vault.matters.undelete",
          "flatPath": "v1/matters/{matterId}:undelete",
          "description": "Undeletes the specified matter. Returns the matter with updated state."
        },
        "delete": {
          "flatPath": "v1/matters/{matterId}",
          "description": "Deletes the specified matter. Returns the matter with updated state.",
          "id": "vault.matters.delete",
          "path": "v1/matters/{matterId}",
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "path": "v1/matters",
          "httpMethod": "GET",
          "id": "vault.matters.list",
          "flatPath": "v1/matters",
          "description": "Lists matters the requestor has access to."
        },
        "update": {
          "id": "vault.matters.update",
          "path": "v1/matters/{matterId}",
          "httpMethod": "PUT",
          "flatPath": "v1/matters/{matterId}",
          "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "removePermissions": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}:removePermissions",
          "httpMethod": "POST",
          "id": "vault.matters.removePermissions",
          "flatPath": "v1/matters/{matterId}:removePermissions",
          "description": "Removes an account as a matter collaborator."
        },
        "close": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}:close",
          "httpMethod": "POST",
          "id": "vault.matters.close",
          "flatPath": "v1/matters/{matterId}:close",
          "description": "Closes the specified matter. Returns the matter with updated state."
        },
        "reopen": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:reopen",
          "description": "Reopens the specified matter. Returns the matter with updated state.",
          "id": "vault.matters.reopen",
          "path": "v1/matters/{matterId}:reopen",
          "httpMethod": "POST"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "id": "vault.matters.get",
          "path": "v1/matters/{matterId}",
          "httpMethod": "GET",
          "flatPath": "v1/matters/{matterId}",
          "description": "Gets the specified matter."
        },
        "addPermissions": {
          "flatPath": "v1/matters/{matterId}:addPermissions",
          "description": "Adds an account as a matter collaborator.",
          "path": "v1/matters/{matterId}:addPermissions",
          "httpMethod": "POST",
          "id": "vault.matters.addPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "count": {
          "path": "v1/matters/{matterId}:count",
          "httpMethod": "POST",
          "id": "vault.matters.count",
          "flatPath": "v1/matters/{matterId}:count",
          "description": "Counts the accounts processed by the specified query.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "create": {
          "path": "v1/matters",
          "httpMethod": "POST",
          "id": "vault.matters.create",
          "flatPath": "v1/matters",
          "description": "Creates a matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        }
      },
      "resources": {
        "savedQueries": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "description": "Creates a saved query.",
              "id": "vault.matters.savedQueries.create",
              "path": "v1/matters/{matterId}/savedQueries",
              "httpMethod": "POST"
            },
            "delete": {
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "description": "Deletes the specified saved query.",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "DELETE",
              "id": "vault.matters.savedQueries.delete",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "list": {
              "id": "vault.matters.savedQueries.list",
              "path": "v1/matters/{matterId}/savedQueries",
              "httpMethod": "GET",
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "description": "Lists the saved queries in a matter.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "get": {
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "GET",
              "id": "vault.matters.savedQueries.get",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "description": "Retrieves the specified saved query.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            }
          }
        },
        "exports": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/exports",
              "description": "Creates an export.",
              "path": "v1/matters/{matterId}/exports",
              "httpMethod": "POST",
              "id": "vault.matters.exports.create"
            },
            "delete": {
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "httpMethod": "DELETE",
              "id": "vault.matters.exports.delete",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "description": "Deletes an export.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "list": {
              "flatPath": "v1/matters/{matterId}/exports",
              "description": "Lists details about the exports in the specified matter.",
              "path": "v1/matters/{matterId}/exports",
              "httpMethod": "GET",
              "id": "vault.matters.exports.list",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "description": "Gets an export.",
              "id": "vault.matters.exports.get",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "httpMethod": "GET"
            }
          }
        },
        "holds": {
          "resources": {
            "accounts": {
              "methods": {
                "create": {
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "httpMethod": "POST",
                  "id": "vault.matters.holds.accounts.create",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "description": "Adds an account to a hold. Accounts can be added only to a hold that does not have an organizational unit set. If you try to add an account to an organizational unit-based hold, an error is returned.",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ]
                },
                "delete": {
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "description": "Removes an account from a hold.",
                  "id": "vault.matters.holds.accounts.delete",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "httpMethod": "DELETE"
                },
                "list": {
                  "id": "vault.matters.holds.accounts.list",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "httpMethod": "GET",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "description": "Lists the accounts covered by a hold. This can list only individually-specified accounts covered by the hold. If the hold covers an organizational unit, use the [Admin SDK](https://developers.google.com/admin-sdk/). to list the members of the organizational unit on hold.",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery",
                    "https://www.googleapis.com/auth/ediscovery.readonly"
                  ]
                }
              }
            }
          },
          "methods": {
            "create": {
              "flatPath": "v1/matters/{matterId}/holds",
              "description": "Creates a hold in the specified matter.",
              "id": "vault.matters.holds.create",
              "path": "v1/matters/{matterId}/holds",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.holds.delete",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "DELETE",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "description": "Removes the specified hold and releases the accounts or organizational unit covered by the hold. If the data is not preserved by another hold or retention rule, it might be purged."
            },
            "list": {
              "flatPath": "v1/matters/{matterId}/holds",
              "description": "Lists the holds in a matter.",
              "id": "vault.matters.holds.list",
              "path": "v1/matters/{matterId}/holds",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "update": {
              "id": "vault.matters.holds.update",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "PUT",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "description": "Updates the scope (organizational unit or accounts) and query parameters of a hold. You cannot add accounts to a hold that covers an organizational unit, nor can you add organizational units to a hold that covers individual accounts. If you try, the unsupported values are ignored.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "GET",
              "id": "vault.matters.holds.get",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "description": "Gets the specified hold."
            },
            "addHeldAccounts": {
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "description": "Adds accounts to a hold. Returns a list of accounts that have been successfully added. Accounts can be added only to an existing account-based hold.",
              "id": "vault.matters.holds.addHeldAccounts",
              "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "removeHeldAccounts": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "description": "Removes the specified accounts from a hold. Returns a list of statuses in the same order as the request.",
              "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "httpMethod": "POST",
              "id": "vault.matters.holds.removeHeldAccounts"
            }
          }
        }
      }
    }
  },
  "description": "Retention and eDiscovery for Google Workspace. To work with Vault resources, the account must have the [required Vault privileges](https://support.google.com/vault/answer/2799699) and access to the matter. To access a matter, the account must have created the matter, have the matter shared with them, or have the **View All Matters** privilege. For example, to download an export, an account needs the **Manage Exports** privilege and the matter shared with them. ",
  "ownerName": "Google",
  "id": "vault:v1",
  "servicePath": "",
  "name": "vault",
  "baseUrl": "https://vault.googleapis.com/",
  "title": "Google Vault API",
  "rootUrl": "https://vault.googleapis.com/",
  "kind": "discovery#restDescription",
  "fullyEncodeReservedExpansion": true,
  "canonicalName": "Vault",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery": {
          "description": "Manage your eDiscovery data"
        },
        "https://www.googleapis.com/auth/ediscovery.readonly": {
          "description": "View your eDiscovery data"
        }
      }
    }
  },
  "revision": "20260428",
  "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
  "basePath": ""
}