{
  "basePath": "",
  "name": "vault",
  "ownerDomain": "google.com",
  "fullyEncodeReservedExpansion": true,
  "ownerName": "Google",
  "revision": "20260305",
  "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
  "rootUrl": "https://vault.googleapis.com/",
  "version_module": true,
  "batchPath": "batch",
  "description": "Retention and eDiscovery for Google Workspace. To work with Vault resources, the account must have the [required Vault privileges](https://support.google.com/vault/answer/2799699) and access to the matter. To access a matter, the account must have created the matter, have the matter shared with them, or have the **View All Matters** privilege. For example, to download an export, an account needs the **Manage Exports** privilege and the matter shared with them. ",
  "kind": "discovery#restDescription",
  "baseUrl": "https://vault.googleapis.com/",
  "discoveryVersion": "v1",
  "servicePath": "",
  "canonicalName": "Vault",
  "version": "v1",
  "resources": {
    "matters": {
      "resources": {
        "exports": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/exports",
              "id": "vault.matters.exports.create",
              "description": "Creates an export.",
              "path": "v1/matters/{matterId}/exports",
              "httpMethod": "POST"
            },
            "delete": {
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "description": "Deletes an export.",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "httpMethod": "DELETE",
              "id": "vault.matters.exports.delete"
            },
            "get": {
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "httpMethod": "GET",
              "description": "Gets an export.",
              "id": "vault.matters.exports.get"
            },
            "list": {
              "id": "vault.matters.exports.list",
              "description": "Lists details about the exports in the specified matter.",
              "path": "v1/matters/{matterId}/exports",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "flatPath": "v1/matters/{matterId}/exports"
            }
          }
        },
        "holds": {
          "resources": {
            "accounts": {
              "methods": {
                "list": {
                  "description": "Lists the accounts covered by a hold. This can list only individually-specified accounts covered by the hold. If the hold covers an organizational unit, use the [Admin SDK](https://developers.google.com/admin-sdk/). to list the members of the organizational unit on hold.",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "httpMethod": "GET",
                  "id": "vault.matters.holds.accounts.list",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery",
                    "https://www.googleapis.com/auth/ediscovery.readonly"
                  ]
                },
                "create": {
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "id": "vault.matters.holds.accounts.create",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "httpMethod": "POST",
                  "description": "Adds an account to a hold. Accounts can be added only to a hold that does not have an organizational unit set. If you try to add an account to an organizational unit-based hold, an error is returned."
                },
                "delete": {
                  "id": "vault.matters.holds.accounts.delete",
                  "description": "Removes an account from a hold.",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "httpMethod": "DELETE",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}"
                }
              }
            }
          },
          "methods": {
            "list": {
              "flatPath": "v1/matters/{matterId}/holds",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/holds",
              "httpMethod": "GET",
              "description": "Lists the holds in a matter.",
              "id": "vault.matters.holds.list"
            },
            "get": {
              "id": "vault.matters.holds.get",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "GET",
              "description": "Gets the specified hold.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "flatPath": "v1/matters/{matterId}/holds/{holdId}"
            },
            "addHeldAccounts": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "id": "vault.matters.holds.addHeldAccounts",
              "description": "Adds accounts to a hold. Returns a list of accounts that have been successfully added. Accounts can be added only to an existing account-based hold.",
              "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "httpMethod": "POST"
            },
            "removeHeldAccounts": {
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "httpMethod": "POST",
              "description": "Removes the specified accounts from a hold. Returns a list of statuses in the same order as the request.",
              "id": "vault.matters.holds.removeHeldAccounts"
            },
            "create": {
              "id": "vault.matters.holds.create",
              "description": "Creates a hold in the specified matter.",
              "path": "v1/matters/{matterId}/holds",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/holds"
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "id": "vault.matters.holds.delete",
              "description": "Removes the specified hold and releases the accounts or organizational unit covered by the hold. If the data is not preserved by another hold or retention rule, it might be purged.",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "DELETE"
            },
            "update": {
              "description": "Updates the scope (organizational unit or accounts) and query parameters of a hold. You cannot add accounts to a hold that covers an organizational unit, nor can you add organizational units to a hold that covers individual accounts. If you try, the unsupported values are ignored.",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "PUT",
              "id": "vault.matters.holds.update",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            }
          }
        },
        "savedQueries": {
          "methods": {
            "list": {
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "description": "Lists the saved queries in a matter.",
              "path": "v1/matters/{matterId}/savedQueries",
              "httpMethod": "GET",
              "id": "vault.matters.savedQueries.list"
            },
            "create": {
              "id": "vault.matters.savedQueries.create",
              "description": "Creates a saved query.",
              "path": "v1/matters/{matterId}/savedQueries",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/savedQueries"
            },
            "delete": {
              "id": "vault.matters.savedQueries.delete",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "DELETE",
              "description": "Deletes the specified saved query.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "id": "vault.matters.savedQueries.get",
              "description": "Retrieves the specified saved query.",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "GET"
            }
          }
        }
      },
      "methods": {
        "create": {
          "description": "Creates a matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view.",
          "path": "v1/matters",
          "httpMethod": "POST",
          "id": "vault.matters.create",
          "flatPath": "v1/matters",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "removePermissions": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:removePermissions",
          "id": "vault.matters.removePermissions",
          "description": "Removes an account as a matter collaborator.",
          "path": "v1/matters/{matterId}:removePermissions",
          "httpMethod": "POST"
        },
        "undelete": {
          "path": "v1/matters/{matterId}:undelete",
          "httpMethod": "POST",
          "description": "Undeletes the specified matter. Returns the matter with updated state.",
          "id": "vault.matters.undelete",
          "flatPath": "v1/matters/{matterId}:undelete",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "reopen": {
          "id": "vault.matters.reopen",
          "path": "v1/matters/{matterId}:reopen",
          "httpMethod": "POST",
          "description": "Reopens the specified matter. Returns the matter with updated state.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:reopen"
        },
        "delete": {
          "id": "vault.matters.delete",
          "path": "v1/matters/{matterId}",
          "httpMethod": "DELETE",
          "description": "Deletes the specified matter. Returns the matter with updated state.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}"
        },
        "addPermissions": {
          "path": "v1/matters/{matterId}:addPermissions",
          "httpMethod": "POST",
          "description": "Adds an account as a matter collaborator.",
          "id": "vault.matters.addPermissions",
          "flatPath": "v1/matters/{matterId}:addPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "update": {
          "id": "vault.matters.update",
          "path": "v1/matters/{matterId}",
          "httpMethod": "PUT",
          "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}"
        },
        "count": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:count",
          "id": "vault.matters.count",
          "description": "Counts the accounts processed by the specified query.",
          "path": "v1/matters/{matterId}:count",
          "httpMethod": "POST"
        },
        "close": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "flatPath": "v1/matters/{matterId}:close",
          "id": "vault.matters.close",
          "description": "Closes the specified matter. Returns the matter with updated state.",
          "path": "v1/matters/{matterId}:close",
          "httpMethod": "POST"
        },
        "list": {
          "description": "Lists matters the requestor has access to.",
          "path": "v1/matters",
          "httpMethod": "GET",
          "id": "vault.matters.list",
          "flatPath": "v1/matters",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "get": {
          "flatPath": "v1/matters/{matterId}",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "path": "v1/matters/{matterId}",
          "httpMethod": "GET",
          "description": "Gets the specified matter.",
          "id": "vault.matters.get"
        }
      }
    },
    "operations": {
      "methods": {
        "list": {
          "path": "v1/{+name}",
          "httpMethod": "GET",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "id": "vault.operations.list",
          "flatPath": "v1/operations",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "get": {
          "id": "vault.operations.get",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "path": "v1/{+name}",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "flatPath": "v1/operations/{operationsId}"
        },
        "delete": {
          "flatPath": "v1/operations/{operationsId}",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "path": "v1/{+name}",
          "httpMethod": "DELETE",
          "id": "vault.operations.delete"
        },
        "cancel": {
          "path": "v1/{+name}:cancel",
          "httpMethod": "POST",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "id": "vault.operations.cancel",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery": {
          "description": "Manage your eDiscovery data"
        },
        "https://www.googleapis.com/auth/ediscovery.readonly": {
          "description": "View your eDiscovery data"
        }
      }
    }
  },
  "protocol": "rest",
  "id": "vault:v1",
  "documentationLink": "https://developers.google.com/workspace/vault",
  "title": "Google Vault API"
}