{
  "ownerName": "Google",
  "protocol": "rest",
  "servicePath": "",
  "revision": "20260512",
  "kind": "discovery#restDescription",
  "basePath": "",
  "discoveryVersion": "v1",
  "baseUrl": "https://vault.googleapis.com/",
  "fullyEncodeReservedExpansion": true,
  "batchPath": "batch",
  "version": "v1",
  "rootUrl": "https://vault.googleapis.com/",
  "ownerDomain": "google.com",
  "version_module": true,
  "documentationLink": "https://developers.google.com/workspace/vault",
  "name": "vault",
  "title": "Google Vault API",
  "resources": {
    "operations": {
      "methods": {
        "get": {
          "path": "v1/{+name}",
          "flatPath": "v1/operations/{operationsId}",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "id": "vault.operations.get",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.operations.delete",
          "httpMethod": "DELETE",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "flatPath": "v1/operations/{operationsId}",
          "path": "v1/{+name}"
        },
        "cancel": {
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "id": "vault.operations.cancel",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/{+name}:cancel",
          "flatPath": "v1/operations/{operationsId}:cancel"
        },
        "list": {
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`.",
          "id": "vault.operations.list",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "path": "v1/{+name}",
          "flatPath": "v1/operations"
        }
      }
    },
    "matters": {
      "methods": {
        "close": {
          "description": "Closes the specified matter. Returns the matter with updated state.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.close",
          "httpMethod": "POST",
          "path": "v1/matters/{matterId}:close",
          "flatPath": "v1/matters/{matterId}:close"
        },
        "list": {
          "flatPath": "v1/matters",
          "path": "v1/matters",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "id": "vault.matters.list",
          "httpMethod": "GET",
          "description": "Lists matters the requestor has access to."
        },
        "delete": {
          "path": "v1/matters/{matterId}",
          "flatPath": "v1/matters/{matterId}",
          "description": "Deletes the specified matter. Returns the matter with updated state.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.delete",
          "httpMethod": "DELETE"
        },
        "update": {
          "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
          "id": "vault.matters.update",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}",
          "flatPath": "v1/matters/{matterId}"
        },
        "count": {
          "description": "Counts the accounts processed by the specified query.",
          "id": "vault.matters.count",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}:count",
          "flatPath": "v1/matters/{matterId}:count"
        },
        "undelete": {
          "id": "vault.matters.undelete",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "description": "Undeletes the specified matter. Returns the matter with updated state.",
          "flatPath": "v1/matters/{matterId}:undelete",
          "path": "v1/matters/{matterId}:undelete"
        },
        "removePermissions": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.removePermissions",
          "httpMethod": "POST",
          "description": "Removes an account as a matter collaborator.",
          "path": "v1/matters/{matterId}:removePermissions",
          "flatPath": "v1/matters/{matterId}:removePermissions"
        },
        "addPermissions": {
          "flatPath": "v1/matters/{matterId}:addPermissions",
          "path": "v1/matters/{matterId}:addPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.addPermissions",
          "httpMethod": "POST",
          "description": "Adds an account as a matter collaborator."
        },
        "create": {
          "path": "v1/matters",
          "flatPath": "v1/matters",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.create",
          "httpMethod": "POST",
          "description": "Creates a matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view."
        },
        "reopen": {
          "flatPath": "v1/matters/{matterId}:reopen",
          "path": "v1/matters/{matterId}:reopen",
          "description": "Reopens the specified matter. Returns the matter with updated state.",
          "id": "vault.matters.reopen",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "get": {
          "description": "Gets the specified matter.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "id": "vault.matters.get",
          "httpMethod": "GET",
          "flatPath": "v1/matters/{matterId}",
          "path": "v1/matters/{matterId}"
        }
      },
      "resources": {
        "savedQueries": {
          "methods": {
            "list": {
              "description": "Lists the saved queries in a matter.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "id": "vault.matters.savedQueries.list",
              "httpMethod": "GET",
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "path": "v1/matters/{matterId}/savedQueries"
            },
            "create": {
              "path": "v1/matters/{matterId}/savedQueries",
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "id": "vault.matters.savedQueries.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "description": "Creates a saved query."
            },
            "get": {
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "id": "vault.matters.savedQueries.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "description": "Retrieves the specified saved query."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.savedQueries.delete",
              "httpMethod": "DELETE",
              "description": "Deletes the specified saved query.",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}"
            }
          }
        },
        "exports": {
          "methods": {
            "delete": {
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.exports.delete",
              "httpMethod": "DELETE",
              "description": "Deletes an export."
            },
            "create": {
              "flatPath": "v1/matters/{matterId}/exports",
              "path": "v1/matters/{matterId}/exports",
              "description": "Creates an export.",
              "id": "vault.matters.exports.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "get": {
              "id": "vault.matters.exports.get",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "description": "Gets an export.",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}"
            },
            "list": {
              "description": "Lists details about the exports in the specified matter.",
              "id": "vault.matters.exports.list",
              "httpMethod": "GET",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "flatPath": "v1/matters/{matterId}/exports",
              "path": "v1/matters/{matterId}/exports"
            }
          }
        },
        "holds": {
          "methods": {
            "create": {
              "path": "v1/matters/{matterId}/holds",
              "flatPath": "v1/matters/{matterId}/holds",
              "id": "vault.matters.holds.create",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "description": "Creates a hold in the specified matter."
            },
            "update": {
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "description": "Updates the scope (organizational unit or accounts) and query parameters of a hold. You cannot add accounts to a hold that covers an organizational unit, nor can you add organizational units to a hold that covers individual accounts. If you try, the unsupported values are ignored.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.holds.update",
              "httpMethod": "PUT"
            },
            "get": {
              "description": "Gets the specified hold.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "id": "vault.matters.holds.get",
              "httpMethod": "GET",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "path": "v1/matters/{matterId}/holds/{holdId}"
            },
            "delete": {
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "description": "Removes the specified hold and releases the accounts or organizational unit covered by the hold. If the data is not preserved by another hold or retention rule, it might be purged.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.holds.delete",
              "httpMethod": "DELETE"
            },
            "list": {
              "flatPath": "v1/matters/{matterId}/holds",
              "path": "v1/matters/{matterId}/holds",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "id": "vault.matters.holds.list",
              "httpMethod": "GET",
              "description": "Lists the holds in a matter."
            },
            "removeHeldAccounts": {
              "id": "vault.matters.holds.removeHeldAccounts",
              "httpMethod": "POST",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "description": "Removes the specified accounts from a hold. Returns a list of statuses in the same order as the request.",
              "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts"
            },
            "addHeldAccounts": {
              "description": "Adds accounts to a hold. Returns a list of accounts that have been successfully added. Accounts can be added only to an existing account-based hold.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.holds.addHeldAccounts",
              "httpMethod": "POST",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts"
            }
          },
          "resources": {
            "accounts": {
              "methods": {
                "create": {
                  "description": "Adds an account to a hold. Accounts can be added only to a hold that does not have an organizational unit set. If you try to add an account to an organizational unit-based hold, an error is returned.",
                  "id": "vault.matters.holds.accounts.create",
                  "httpMethod": "POST",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts"
                },
                "delete": {
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "id": "vault.matters.holds.accounts.delete",
                  "httpMethod": "DELETE",
                  "description": "Removes an account from a hold."
                },
                "list": {
                  "description": "Lists the accounts covered by a hold. This can list only individually-specified accounts covered by the hold. If the hold covers an organizational unit, use the [Admin SDK](https://developers.google.com/admin-sdk/). to list the members of the organizational unit on hold.",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery",
                    "https://www.googleapis.com/auth/ediscovery.readonly"
                  ],
                  "id": "vault.matters.holds.accounts.list",
                  "httpMethod": "GET",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts"
                }
              }
            }
          }
        }
      }
    }
  },
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery": {
          "description": "Manage your eDiscovery data"
        },
        "https://www.googleapis.com/auth/ediscovery.readonly": {
          "description": "View your eDiscovery data"
        }
      }
    }
  },
  "canonicalName": "Vault",
  "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
  "id": "vault:v1",
  "description": "Retention and eDiscovery for Google Workspace. To work with Vault resources, the account must have the [required Vault privileges](https://support.google.com/vault/answer/2799699) and access to the matter. To access a matter, the account must have created the matter, have the matter shared with them, or have the **View All Matters** privilege. For example, to download an export, an account needs the **Manage Exports** privilege and the matter shared with them. "
}