{
  "canonicalName": "Vault",
  "rootUrl": "https://vault.googleapis.com/",
  "version": "v1",
  "ownerDomain": "google.com",
  "description": "Retention and eDiscovery for Google Workspace. To work with Vault resources, the account must have the [required Vault privileges](https://support.google.com/vault/answer/2799699) and access to the matter. To access a matter, the account must have created the matter, have the matter shared with them, or have the **View All Matters** privilege. For example, to download an export, an account needs the **Manage Exports** privilege and the matter shared with them. ",
  "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
  "name": "vault",
  "id": "vault:v1",
  "ownerName": "Google",
  "kind": "discovery#restDescription",
  "version_module": true,
  "fullyEncodeReservedExpansion": true,
  "protocol": "rest",
  "revision": "20260428",
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery": {
          "description": "Manage your eDiscovery data"
        },
        "https://www.googleapis.com/auth/ediscovery.readonly": {
          "description": "View your eDiscovery data"
        }
      }
    }
  },
  "baseUrl": "https://vault.googleapis.com/",
  "documentationLink": "https://developers.google.com/workspace/vault",
  "title": "Google Vault API",
  "resources": {
    "operations": {
      "methods": {
        "cancel": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.operations.cancel",
          "httpMethod": "POST",
          "path": "v1/{+name}:cancel",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "id": "vault.operations.list",
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "flatPath": "v1/operations",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
        },
        "get": {
          "id": "vault.operations.get",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "path": "v1/{+name}",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "GET"
        },
        "delete": {
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "path": "v1/{+name}",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "DELETE",
          "id": "vault.operations.delete",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        }
      }
    },
    "matters": {
      "methods": {
        "removePermissions": {
          "httpMethod": "POST",
          "path": "v1/matters/{matterId}:removePermissions",
          "flatPath": "v1/matters/{matterId}:removePermissions",
          "description": "Removes an account as a matter collaborator.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.removePermissions"
        },
        "list": {
          "id": "vault.matters.list",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "description": "Lists matters the requestor has access to.",
          "httpMethod": "GET",
          "path": "v1/matters",
          "flatPath": "v1/matters"
        },
        "addPermissions": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.addPermissions",
          "path": "v1/matters/{matterId}:addPermissions",
          "flatPath": "v1/matters/{matterId}:addPermissions",
          "httpMethod": "POST",
          "description": "Adds an account as a matter collaborator."
        },
        "count": {
          "path": "v1/matters/{matterId}:count",
          "flatPath": "v1/matters/{matterId}:count",
          "httpMethod": "POST",
          "description": "Counts the accounts processed by the specified query.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.count"
        },
        "get": {
          "description": "Gets the specified matter.",
          "httpMethod": "GET",
          "path": "v1/matters/{matterId}",
          "flatPath": "v1/matters/{matterId}",
          "id": "vault.matters.get",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "update": {
          "id": "vault.matters.update",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
          "path": "v1/matters/{matterId}",
          "flatPath": "v1/matters/{matterId}",
          "httpMethod": "PUT"
        },
        "close": {
          "path": "v1/matters/{matterId}:close",
          "flatPath": "v1/matters/{matterId}:close",
          "httpMethod": "POST",
          "description": "Closes the specified matter. Returns the matter with updated state.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.close"
        },
        "reopen": {
          "description": "Reopens the specified matter. Returns the matter with updated state.",
          "httpMethod": "POST",
          "path": "v1/matters/{matterId}:reopen",
          "flatPath": "v1/matters/{matterId}:reopen",
          "id": "vault.matters.reopen",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "undelete": {
          "path": "v1/matters/{matterId}:undelete",
          "flatPath": "v1/matters/{matterId}:undelete",
          "httpMethod": "POST",
          "description": "Undeletes the specified matter. Returns the matter with updated state.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.undelete"
        },
        "create": {
          "description": "Creates a matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view.",
          "path": "v1/matters",
          "flatPath": "v1/matters",
          "httpMethod": "POST",
          "id": "vault.matters.create",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "delete": {
          "path": "v1/matters/{matterId}",
          "flatPath": "v1/matters/{matterId}",
          "httpMethod": "DELETE",
          "description": "Deletes the specified matter. Returns the matter with updated state.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.delete"
        }
      },
      "resources": {
        "savedQueries": {
          "methods": {
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.savedQueries.create",
              "httpMethod": "POST",
              "path": "v1/matters/{matterId}/savedQueries",
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "description": "Creates a saved query."
            },
            "list": {
              "description": "Lists the saved queries in a matter.",
              "httpMethod": "GET",
              "path": "v1/matters/{matterId}/savedQueries",
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "id": "vault.matters.savedQueries.list",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.savedQueries.delete",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "DELETE",
              "description": "Deletes the specified saved query."
            },
            "get": {
              "description": "Retrieves the specified saved query.",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "GET",
              "id": "vault.matters.savedQueries.get",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            }
          }
        },
        "exports": {
          "methods": {
            "delete": {
              "httpMethod": "DELETE",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "description": "Deletes an export.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.exports.delete"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "id": "vault.matters.exports.get",
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "httpMethod": "GET",
              "description": "Gets an export."
            },
            "create": {
              "path": "v1/matters/{matterId}/exports",
              "flatPath": "v1/matters/{matterId}/exports",
              "httpMethod": "POST",
              "description": "Creates an export.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.exports.create"
            },
            "list": {
              "httpMethod": "GET",
              "path": "v1/matters/{matterId}/exports",
              "flatPath": "v1/matters/{matterId}/exports",
              "description": "Lists details about the exports in the specified matter.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "id": "vault.matters.exports.list"
            }
          }
        },
        "holds": {
          "methods": {
            "addHeldAccounts": {
              "description": "Adds accounts to a hold. Returns a list of accounts that have been successfully added. Accounts can be added only to an existing account-based hold.",
              "httpMethod": "POST",
              "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "id": "vault.matters.holds.addHeldAccounts",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "removeHeldAccounts": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.holds.removeHeldAccounts",
              "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "httpMethod": "POST",
              "description": "Removes the specified accounts from a hold. Returns a list of statuses in the same order as the request."
            },
            "delete": {
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "DELETE",
              "description": "Removes the specified hold and releases the accounts or organizational unit covered by the hold. If the data is not preserved by another hold or retention rule, it might be purged.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.holds.delete"
            },
            "get": {
              "id": "vault.matters.holds.get",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "description": "Gets the specified hold.",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "GET"
            },
            "create": {
              "httpMethod": "POST",
              "path": "v1/matters/{matterId}/holds",
              "flatPath": "v1/matters/{matterId}/holds",
              "description": "Creates a hold in the specified matter.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.holds.create"
            },
            "list": {
              "description": "Lists the holds in a matter.",
              "path": "v1/matters/{matterId}/holds",
              "flatPath": "v1/matters/{matterId}/holds",
              "httpMethod": "GET",
              "id": "vault.matters.holds.list",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "update": {
              "id": "vault.matters.holds.update",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "description": "Updates the scope (organizational unit or accounts) and query parameters of a hold. You cannot add accounts to a hold that covers an organizational unit, nor can you add organizational units to a hold that covers individual accounts. If you try, the unsupported values are ignored.",
              "httpMethod": "PUT",
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}"
            }
          },
          "resources": {
            "accounts": {
              "methods": {
                "create": {
                  "id": "vault.matters.holds.accounts.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "description": "Adds an account to a hold. Accounts can be added only to a hold that does not have an organizational unit set. If you try to add an account to an organizational unit-based hold, an error is returned.",
                  "httpMethod": "POST",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts"
                },
                "list": {
                  "id": "vault.matters.holds.accounts.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery",
                    "https://www.googleapis.com/auth/ediscovery.readonly"
                  ],
                  "description": "Lists the accounts covered by a hold. This can list only individually-specified accounts covered by the hold. If the hold covers an organizational unit, use the [Admin SDK](https://developers.google.com/admin-sdk/). to list the members of the organizational unit on hold.",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "httpMethod": "GET"
                },
                "delete": {
                  "description": "Removes an account from a hold.",
                  "httpMethod": "DELETE",
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "id": "vault.matters.holds.accounts.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ]
                }
              }
            }
          }
        }
      }
    }
  },
  "basePath": "",
  "batchPath": "batch",
  "servicePath": ""
}