{
  "canonicalName": "Vault",
  "name": "vault",
  "title": "Google Vault API",
  "documentationLink": "https://developers.google.com/workspace/vault",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/ediscovery": {
          "description": "Manage your eDiscovery data"
        },
        "https://www.googleapis.com/auth/ediscovery.readonly": {
          "description": "View your eDiscovery data"
        }
      }
    }
  },
  "description": "Retention and eDiscovery for Google Workspace. To work with Vault resources, the account must have the [required Vault privileges](https://support.google.com/vault/answer/2799699) and access to the matter. To access a matter, the account must have created the matter, have the matter shared with them, or have the **View All Matters** privilege. For example, to download an export, an account needs the **Manage Exports** privilege and the matter shared with them. ",
  "version": "v1",
  "version_module": true,
  "kind": "discovery#restDescription",
  "protocol": "rest",
  "ownerDomain": "google.com",
  "batchPath": "batch",
  "id": "vault:v1",
  "discoveryVersion": "v1",
  "rootUrl": "https://vault.googleapis.com/",
  "ownerName": "Google",
  "resources": {
    "operations": {
      "methods": {
        "list": {
          "flatPath": "v1/operations",
          "httpMethod": "GET",
          "id": "vault.operations.list",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "path": "v1/{+name}",
          "description": "Lists operations that match the specified filter in the request. If the server doesn't support this method, it returns `UNIMPLEMENTED`."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/{+name}",
          "description": "Deletes a long-running operation. This method indicates that the client is no longer interested in the operation result. It does not cancel the operation. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`.",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "DELETE",
          "id": "vault.operations.delete"
        },
        "get": {
          "id": "vault.operations.get",
          "flatPath": "v1/operations/{operationsId}",
          "httpMethod": "GET",
          "path": "v1/{+name}",
          "description": "Gets the latest state of a long-running operation. Clients can use this method to poll the operation result at intervals as recommended by the API service.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ]
        },
        "cancel": {
          "id": "vault.operations.cancel",
          "flatPath": "v1/operations/{operationsId}:cancel",
          "httpMethod": "POST",
          "path": "v1/{+name}:cancel",
          "description": "Starts asynchronous cancellation on a long-running operation. The server makes a best effort to cancel the operation, but success is not guaranteed. If the server doesn't support this method, it returns `google.rpc.Code.UNIMPLEMENTED`. Clients can use Operations.GetOperation or other methods to check whether the cancellation succeeded or whether the operation completed despite cancellation. On successful cancellation, the operation is not deleted; instead, it becomes an[...]",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        }
      }
    },
    "matters": {
      "methods": {
        "removePermissions": {
          "id": "vault.matters.removePermissions",
          "flatPath": "v1/matters/{matterId}:removePermissions",
          "httpMethod": "POST",
          "path": "v1/matters/{matterId}:removePermissions",
          "description": "Removes an account as a matter collaborator.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "create": {
          "path": "v1/matters",
          "description": "Creates a matter with the given name and description. The initial state is open, and the owner is the method caller. Returns the created matter with default view.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "id": "vault.matters.create",
          "flatPath": "v1/matters",
          "httpMethod": "POST"
        },
        "count": {
          "flatPath": "v1/matters/{matterId}:count",
          "httpMethod": "POST",
          "id": "vault.matters.count",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}:count",
          "description": "Counts the accounts processed by the specified query."
        },
        "close": {
          "flatPath": "v1/matters/{matterId}:close",
          "httpMethod": "POST",
          "id": "vault.matters.close",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}:close",
          "description": "Closes the specified matter. Returns the matter with updated state."
        },
        "addPermissions": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}:addPermissions",
          "description": "Adds an account as a matter collaborator.",
          "flatPath": "v1/matters/{matterId}:addPermissions",
          "httpMethod": "POST",
          "id": "vault.matters.addPermissions"
        },
        "update": {
          "id": "vault.matters.update",
          "flatPath": "v1/matters/{matterId}",
          "httpMethod": "PUT",
          "path": "v1/matters/{matterId}",
          "description": "Updates the specified matter. This updates only the name and description of the matter, identified by matter ID. Changes to any other fields are ignored. Returns the default view of the matter.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "delete": {
          "id": "vault.matters.delete",
          "flatPath": "v1/matters/{matterId}",
          "httpMethod": "DELETE",
          "path": "v1/matters/{matterId}",
          "description": "Deletes the specified matter. Returns the matter with updated state.",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ]
        },
        "reopen": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}:reopen",
          "description": "Reopens the specified matter. Returns the matter with updated state.",
          "flatPath": "v1/matters/{matterId}:reopen",
          "httpMethod": "POST",
          "id": "vault.matters.reopen"
        },
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "path": "v1/matters/{matterId}",
          "description": "Gets the specified matter.",
          "flatPath": "v1/matters/{matterId}",
          "httpMethod": "GET",
          "id": "vault.matters.get"
        },
        "undelete": {
          "flatPath": "v1/matters/{matterId}:undelete",
          "httpMethod": "POST",
          "id": "vault.matters.undelete",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery"
          ],
          "path": "v1/matters/{matterId}:undelete",
          "description": "Undeletes the specified matter. Returns the matter with updated state."
        },
        "list": {
          "flatPath": "v1/matters",
          "httpMethod": "GET",
          "id": "vault.matters.list",
          "scopes": [
            "https://www.googleapis.com/auth/ediscovery",
            "https://www.googleapis.com/auth/ediscovery.readonly"
          ],
          "path": "v1/matters",
          "description": "Lists matters the requestor has access to."
        }
      },
      "resources": {
        "savedQueries": {
          "methods": {
            "get": {
              "id": "vault.matters.savedQueries.get",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "GET",
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "description": "Retrieves the specified saved query.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ]
            },
            "delete": {
              "path": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "description": "Deletes the specified saved query.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.savedQueries.delete",
              "flatPath": "v1/matters/{matterId}/savedQueries/{savedQueryId}",
              "httpMethod": "DELETE"
            },
            "create": {
              "id": "vault.matters.savedQueries.create",
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "httpMethod": "POST",
              "path": "v1/matters/{matterId}/savedQueries",
              "description": "Creates a saved query.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ]
            },
            "list": {
              "flatPath": "v1/matters/{matterId}/savedQueries",
              "httpMethod": "GET",
              "id": "vault.matters.savedQueries.list",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/savedQueries",
              "description": "Lists the saved queries in a matter."
            }
          }
        },
        "holds": {
          "resources": {
            "accounts": {
              "methods": {
                "create": {
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "httpMethod": "POST",
                  "id": "vault.matters.holds.accounts.create",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "description": "Adds an account to a hold. Accounts can be added only to a hold that does not have an organizational unit set. If you try to add an account to an organizational unit-based hold, an error is returned."
                },
                "list": {
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "httpMethod": "GET",
                  "id": "vault.matters.holds.accounts.list",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery",
                    "https://www.googleapis.com/auth/ediscovery.readonly"
                  ],
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts",
                  "description": "Lists the accounts covered by a hold. This can list only individually-specified accounts covered by the hold. If the hold covers an organizational unit, use the [Admin SDK](https://developers.google.com/admin-sdk/). to list the members of the organizational unit on hold."
                },
                "delete": {
                  "flatPath": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "httpMethod": "DELETE",
                  "id": "vault.matters.holds.accounts.delete",
                  "scopes": [
                    "https://www.googleapis.com/auth/ediscovery"
                  ],
                  "path": "v1/matters/{matterId}/holds/{holdId}/accounts/{accountId}",
                  "description": "Removes an account from a hold."
                }
              }
            }
          },
          "methods": {
            "list": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/holds",
              "description": "Lists the holds in a matter.",
              "flatPath": "v1/matters/{matterId}/holds",
              "httpMethod": "GET",
              "id": "vault.matters.holds.list"
            },
            "removeHeldAccounts": {
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "httpMethod": "POST",
              "id": "vault.matters.holds.removeHeldAccounts",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}:removeHeldAccounts",
              "description": "Removes the specified accounts from a hold. Returns a list of statuses in the same order as the request."
            },
            "addHeldAccounts": {
              "path": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "description": "Adds accounts to a hold. Returns a list of accounts that have been successfully added. Accounts can be added only to an existing account-based hold.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.holds.addHeldAccounts",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}:addHeldAccounts",
              "httpMethod": "POST"
            },
            "update": {
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "PUT",
              "id": "vault.matters.holds.update",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "description": "Updates the scope (organizational unit or accounts) and query parameters of a hold. You cannot add accounts to a hold that covers an organizational unit, nor can you add organizational units to a hold that covers individual accounts. If you try, the unsupported values are ignored."
            },
            "create": {
              "flatPath": "v1/matters/{matterId}/holds",
              "httpMethod": "POST",
              "id": "vault.matters.holds.create",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds",
              "description": "Creates a hold in the specified matter."
            },
            "delete": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "description": "Removes the specified hold and releases the accounts or organizational unit covered by the hold. If the data is not preserved by another hold or retention rule, it might be purged.",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "DELETE",
              "id": "vault.matters.holds.delete"
            },
            "get": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/holds/{holdId}",
              "description": "Gets the specified hold.",
              "flatPath": "v1/matters/{matterId}/holds/{holdId}",
              "httpMethod": "GET",
              "id": "vault.matters.holds.get"
            }
          }
        },
        "exports": {
          "methods": {
            "delete": {
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "description": "Deletes an export.",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "id": "vault.matters.exports.delete",
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "httpMethod": "DELETE"
            },
            "create": {
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery"
              ],
              "path": "v1/matters/{matterId}/exports",
              "description": "Creates an export.",
              "flatPath": "v1/matters/{matterId}/exports",
              "httpMethod": "POST",
              "id": "vault.matters.exports.create"
            },
            "list": {
              "flatPath": "v1/matters/{matterId}/exports",
              "httpMethod": "GET",
              "id": "vault.matters.exports.list",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/exports",
              "description": "Lists details about the exports in the specified matter."
            },
            "get": {
              "flatPath": "v1/matters/{matterId}/exports/{exportId}",
              "httpMethod": "GET",
              "id": "vault.matters.exports.get",
              "scopes": [
                "https://www.googleapis.com/auth/ediscovery",
                "https://www.googleapis.com/auth/ediscovery.readonly"
              ],
              "path": "v1/matters/{matterId}/exports/{exportId}",
              "description": "Gets an export."
            }
          }
        }
      }
    }
  },
  "baseUrl": "https://vault.googleapis.com/",
  "revision": "20260415",
  "servicePath": "",
  "mtlsRootUrl": "https://vault.mtls.googleapis.com/",
  "basePath": "",
  "fullyEncodeReservedExpansion": true
}