{
  "ownerName": "Google",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        },
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        }
      }
    }
  },
  "version": "v2",
  "revision": "20260428",
  "documentationLink": "https://developers.google.com/youtube/analytics",
  "canonicalName": "YouTube Analytics",
  "kind": "discovery#restDescription",
  "baseUrl": "https://youtubeanalytics.googleapis.com/",
  "version_module": true,
  "description": "Retrieves your YouTube Analytics data.",
  "discoveryVersion": "v1",
  "basePath": "",
  "protocol": "rest",
  "rootUrl": "https://youtubeanalytics.googleapis.com/",
  "name": "youtubeAnalytics",
  "title": "YouTube Analytics API",
  "ownerDomain": "google.com",
  "servicePath": "",
  "batchPath": "batch",
  "mtlsRootUrl": "https://youtubeanalytics.mtls.googleapis.com/",
  "id": "youtubeAnalytics:v2",
  "resources": {
    "reports": {
      "methods": {
        "query": {
          "id": "youtubeAnalytics.reports.query",
          "path": "v2/reports",
          "flatPath": "v2/reports",
          "description": "Retrieve your YouTube Analytics reports.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "httpMethod": "GET"
        }
      }
    },
    "groupItems": {
      "methods": {
        "delete": {
          "httpMethod": "DELETE",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v2/groupItems",
          "flatPath": "v2/groupItems",
          "description": "Removes an item from a group.",
          "id": "youtubeAnalytics.groupItems.delete"
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "httpMethod": "POST",
          "path": "v2/groupItems",
          "flatPath": "v2/groupItems",
          "description": "Creates a group item.",
          "id": "youtubeAnalytics.groupItems.insert"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "httpMethod": "GET",
          "path": "v2/groupItems",
          "flatPath": "v2/groupItems",
          "description": "Returns a collection of group items that match the API request parameters.",
          "id": "youtubeAnalytics.groupItems.list"
        }
      }
    },
    "groups": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "httpMethod": "GET",
          "id": "youtubeAnalytics.groups.list",
          "path": "v2/groups",
          "flatPath": "v2/groups",
          "description": "Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs."
        },
        "update": {
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "id": "youtubeAnalytics.groups.update",
          "path": "v2/groups",
          "flatPath": "v2/groups",
          "description": "Modifies a group. For example, you could change a group's title."
        },
        "delete": {
          "path": "v2/groups",
          "flatPath": "v2/groups",
          "description": "Deletes a group.",
          "id": "youtubeAnalytics.groups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "httpMethod": "DELETE"
        },
        "insert": {
          "id": "youtubeAnalytics.groups.insert",
          "path": "v2/groups",
          "flatPath": "v2/groups",
          "description": "Creates a group.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true
}