{
  "protocol": "rest",
  "canonicalName": "YouTube Analytics",
  "description": "Retrieves your YouTube Analytics data.",
  "version_module": true,
  "kind": "discovery#restDescription",
  "servicePath": "",
  "basePath": "",
  "version": "v2",
  "discoveryVersion": "v1",
  "revision": "20260406",
  "title": "YouTube Analytics API",
  "resources": {
    "groups": {
      "methods": {
        "delete": {
          "flatPath": "v2/groups",
          "path": "v2/groups",
          "id": "youtubeAnalytics.groups.delete",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "httpMethod": "DELETE",
          "description": "Deletes a group."
        },
        "insert": {
          "id": "youtubeAnalytics.groups.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v2/groups",
          "description": "Creates a group.",
          "httpMethod": "POST",
          "flatPath": "v2/groups"
        },
        "list": {
          "description": "Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs.",
          "httpMethod": "GET",
          "id": "youtubeAnalytics.groups.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v2/groups",
          "flatPath": "v2/groups"
        },
        "update": {
          "flatPath": "v2/groups",
          "httpMethod": "PUT",
          "description": "Modifies a group. For example, you could change a group's title.",
          "path": "v2/groups",
          "id": "youtubeAnalytics.groups.update",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    },
    "groupItems": {
      "methods": {
        "delete": {
          "flatPath": "v2/groupItems",
          "description": "Removes an item from a group.",
          "httpMethod": "DELETE",
          "id": "youtubeAnalytics.groupItems.delete",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v2/groupItems"
        },
        "insert": {
          "flatPath": "v2/groupItems",
          "path": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "httpMethod": "POST",
          "description": "Creates a group item."
        },
        "list": {
          "path": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "httpMethod": "GET",
          "description": "Returns a collection of group items that match the API request parameters.",
          "flatPath": "v2/groupItems"
        }
      }
    },
    "reports": {
      "methods": {
        "query": {
          "flatPath": "v2/reports",
          "path": "v2/reports",
          "id": "youtubeAnalytics.reports.query",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "httpMethod": "GET",
          "description": "Retrieve your YouTube Analytics reports."
        }
      }
    }
  },
  "ownerDomain": "google.com",
  "documentationLink": "https://developers.google.com/youtube/analytics",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        },
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        }
      }
    }
  },
  "name": "youtubeAnalytics",
  "ownerName": "Google",
  "batchPath": "batch",
  "fullyEncodeReservedExpansion": true,
  "mtlsRootUrl": "https://youtubeanalytics.mtls.googleapis.com/",
  "baseUrl": "https://youtubeanalytics.googleapis.com/",
  "id": "youtubeAnalytics:v2",
  "rootUrl": "https://youtubeanalytics.googleapis.com/"
}