{
  "protocol": "rest",
  "servicePath": "",
  "discoveryVersion": "v1",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        }
      }
    }
  },
  "title": "YouTube Reporting API",
  "resources": {
    "jobs": {
      "methods": {
        "create": {
          "id": "youtubereporting.jobs.create",
          "scopes": [
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v1/jobs",
          "flatPath": "v1/jobs",
          "description": "Creates a job and returns it.",
          "httpMethod": "POST"
        },
        "list": {
          "httpMethod": "GET",
          "id": "youtubereporting.jobs.list",
          "scopes": [
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v1/jobs",
          "flatPath": "v1/jobs",
          "description": "Lists jobs."
        },
        "get": {
          "description": "Gets a job.",
          "path": "v1/jobs/{jobId}",
          "flatPath": "v1/jobs/{jobId}",
          "id": "youtubereporting.jobs.get",
          "scopes": [
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "httpMethod": "GET"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "youtubereporting.jobs.delete",
          "scopes": [
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v1/jobs/{jobId}",
          "flatPath": "v1/jobs/{jobId}",
          "description": "Deletes a job."
        }
      },
      "resources": {
        "reports": {
          "methods": {
            "list": {
              "httpMethod": "GET",
              "path": "v1/jobs/{jobId}/reports",
              "flatPath": "v1/jobs/{jobId}/reports",
              "id": "youtubereporting.jobs.reports.list",
              "scopes": [
                "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                "https://www.googleapis.com/auth/yt-analytics.readonly"
              ],
              "description": "Lists reports created by a specific job. Returns NOT_FOUND if the job does not exist."
            },
            "get": {
              "httpMethod": "GET",
              "description": "Gets the metadata of a specific report.",
              "id": "youtubereporting.jobs.reports.get",
              "scopes": [
                "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
                "https://www.googleapis.com/auth/yt-analytics.readonly"
              ],
              "path": "v1/jobs/{jobId}/reports/{reportId}",
              "flatPath": "v1/jobs/{jobId}/reports/{reportId}"
            }
          }
        }
      }
    },
    "reportTypes": {
      "methods": {
        "list": {
          "id": "youtubereporting.reportTypes.list",
          "scopes": [
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v1/reportTypes",
          "flatPath": "v1/reportTypes",
          "description": "Lists report types.",
          "httpMethod": "GET"
        }
      }
    },
    "media": {
      "methods": {
        "download": {
          "httpMethod": "GET",
          "supportsMediaDownload": true,
          "useMediaDownloadService": true,
          "path": "v1/media/{+resourceName}",
          "flatPath": "v1/media/{mediaId}",
          "id": "youtubereporting.media.download",
          "scopes": [
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "description": "Method for media download. Download is supported on the URI `/v1/media/{+name}?alt=media`."
        }
      }
    }
  },
  "name": "youtubereporting",
  "mtlsRootUrl": "https://youtubereporting.mtls.googleapis.com/",
  "id": "youtubereporting:v1",
  "documentationLink": "https://developers.google.com/youtube/reporting/v1/reports/",
  "revision": "20260309",
  "ownerDomain": "google.com",
  "version": "v1",
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "batchPath": "batch",
  "description": "Schedules reporting jobs containing your YouTube Analytics data and downloads the resulting bulk data reports in the form of CSV files.",
  "basePath": "",
  "baseUrl": "https://youtubereporting.googleapis.com/",
  "canonicalName": "YouTube Reporting",
  "rootUrl": "https://youtubereporting.googleapis.com/"
}