{
  "fullyEncodeReservedExpansion": true,
  "discoveryVersion": "v1",
  "name": "youtube",
  "canonicalName": "YouTube",
  "basePath": "",
  "baseUrl": "https://youtube.googleapis.com/",
  "batchPath": "batch",
  "rootUrl": "https://youtube.googleapis.com/",
  "servicePath": "",
  "mtlsRootUrl": "https://youtube.mtls.googleapis.com/",
  "description": "The YouTube Data API v3 is an API that provides access to YouTube data, such as videos, playlists, and channels.",
  "ownerDomain": "google.com",
  "protocol": "rest",
  "revision": "20260415",
  "resources": {
    "channelSections": {
      "methods": {
        "insert": {
          "flatPath": "youtube/v3/channelSections",
          "id": "youtube.channelSections.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "description": "Inserts a new resource into this collection.",
          "path": "youtube/v3/channelSections",
          "httpMethod": "POST"
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "youtube/v3/channelSections",
          "description": "Deletes a resource.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.channelSections.delete",
          "path": "youtube/v3/channelSections"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing resource.",
          "path": "youtube/v3/channelSections",
          "flatPath": "youtube/v3/channelSections",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.channelSections.update"
        },
        "list": {
          "httpMethod": "GET",
          "path": "youtube/v3/channelSections",
          "description": "Retrieves a list of resources, possibly filtered.",
          "id": "youtube.channelSections.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "flatPath": "youtube/v3/channelSections"
        }
      }
    },
    "videoCategories": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/videoCategories",
          "flatPath": "youtube/v3/videoCategories",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.videoCategories.list"
        }
      }
    },
    "comments": {
      "methods": {
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing resource.",
          "path": "youtube/v3/comments",
          "flatPath": "youtube/v3/comments",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.comments.update"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new resource into this collection.",
          "path": "youtube/v3/comments",
          "flatPath": "youtube/v3/comments",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.comments.insert"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.comments.delete",
          "path": "youtube/v3/comments",
          "flatPath": "youtube/v3/comments",
          "description": "Deletes a resource.",
          "httpMethod": "DELETE"
        },
        "setModerationStatus": {
          "httpMethod": "POST",
          "id": "youtube.comments.setModerationStatus",
          "path": "youtube/v3/comments/setModerationStatus",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "description": "Sets the moderation status of one or more comments.",
          "flatPath": "youtube/v3/comments/setModerationStatus"
        },
        "markAsSpam": {
          "description": "Expresses the caller's opinion that one or more comments should be flagged as spam.",
          "flatPath": "youtube/v3/comments/markAsSpam",
          "id": "youtube.comments.markAsSpam",
          "path": "youtube/v3/comments/markAsSpam",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "httpMethod": "POST"
        },
        "list": {
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/comments",
          "httpMethod": "GET",
          "flatPath": "youtube/v3/comments",
          "id": "youtube.comments.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ]
        }
      }
    },
    "liveChatMessages": {
      "methods": {
        "insert": {
          "description": "Inserts a new resource into this collection.",
          "path": "youtube/v3/liveChat/messages",
          "httpMethod": "POST",
          "flatPath": "youtube/v3/liveChat/messages",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.liveChatMessages.insert"
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "youtube/v3/liveChat/messages",
          "description": "Deletes a chat message.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.liveChatMessages.delete",
          "path": "youtube/v3/liveChat/messages"
        },
        "transition": {
          "httpMethod": "POST",
          "path": "youtube/v3/liveChat/messages/transition",
          "description": "Transition a durable chat event.",
          "id": "youtube.liveChatMessages.transition",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "flatPath": "youtube/v3/liveChat/messages/transition"
        },
        "list": {
          "flatPath": "youtube/v3/liveChat/messages",
          "id": "youtube.liveChatMessages.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "httpMethod": "GET",
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/liveChat/messages"
        }
      }
    },
    "liveChatModerators": {
      "methods": {
        "insert": {
          "path": "youtube/v3/liveChat/moderators",
          "description": "Inserts a new resource into this collection.",
          "httpMethod": "POST",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.liveChatModerators.insert",
          "flatPath": "youtube/v3/liveChat/moderators"
        },
        "delete": {
          "flatPath": "youtube/v3/liveChat/moderators",
          "description": "Deletes a chat moderator.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.liveChatModerators.delete",
          "path": "youtube/v3/liveChat/moderators",
          "httpMethod": "DELETE"
        },
        "list": {
          "path": "youtube/v3/liveChat/moderators",
          "description": "Retrieves a list of resources, possibly filtered.",
          "httpMethod": "GET",
          "id": "youtube.liveChatModerators.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "flatPath": "youtube/v3/liveChat/moderators"
        }
      }
    },
    "i18nLanguages": {
      "methods": {
        "list": {
          "path": "youtube/v3/i18nLanguages",
          "description": "Retrieves a list of resources, possibly filtered.",
          "httpMethod": "GET",
          "id": "youtube.i18nLanguages.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "flatPath": "youtube/v3/i18nLanguages"
        }
      }
    },
    "thirdPartyLinks": {
      "methods": {
        "update": {
          "id": "youtube.thirdPartyLinks.update",
          "flatPath": "youtube/v3/thirdPartyLinks",
          "path": "youtube/v3/thirdPartyLinks",
          "description": "Updates an existing resource.",
          "httpMethod": "PUT"
        },
        "insert": {
          "id": "youtube.thirdPartyLinks.insert",
          "flatPath": "youtube/v3/thirdPartyLinks",
          "httpMethod": "POST",
          "path": "youtube/v3/thirdPartyLinks",
          "description": "Inserts a new resource into this collection."
        },
        "delete": {
          "id": "youtube.thirdPartyLinks.delete",
          "path": "youtube/v3/thirdPartyLinks",
          "flatPath": "youtube/v3/thirdPartyLinks",
          "description": "Deletes a resource.",
          "httpMethod": "DELETE"
        },
        "list": {
          "httpMethod": "GET",
          "id": "youtube.thirdPartyLinks.list",
          "path": "youtube/v3/thirdPartyLinks",
          "description": "Retrieves a list of resources, possibly filtered.",
          "flatPath": "youtube/v3/thirdPartyLinks"
        }
      }
    },
    "liveBroadcasts": {
      "methods": {
        "transition": {
          "flatPath": "youtube/v3/liveBroadcasts/transition",
          "id": "youtube.liveBroadcasts.transition",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "description": "Transition a broadcast to a given status.",
          "path": "youtube/v3/liveBroadcasts/transition",
          "httpMethod": "POST"
        },
        "insert": {
          "flatPath": "youtube/v3/liveBroadcasts",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.liveBroadcasts.insert",
          "description": "Inserts a new stream for the authenticated user.",
          "path": "youtube/v3/liveBroadcasts",
          "httpMethod": "POST"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "youtube.liveBroadcasts.delete",
          "path": "youtube/v3/liveBroadcasts",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "description": "Delete a given broadcast.",
          "flatPath": "youtube/v3/liveBroadcasts"
        },
        "insertCuepoint": {
          "id": "youtube.liveBroadcasts.insertCuepoint",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "flatPath": "youtube/v3/liveBroadcasts/cuepoint",
          "httpMethod": "POST",
          "path": "youtube/v3/liveBroadcasts/cuepoint",
          "description": "Insert cuepoints in a broadcast"
        },
        "update": {
          "flatPath": "youtube/v3/liveBroadcasts",
          "id": "youtube.liveBroadcasts.update",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "description": "Updates an existing broadcast for the authenticated user.",
          "path": "youtube/v3/liveBroadcasts",
          "httpMethod": "PUT"
        },
        "list": {
          "flatPath": "youtube/v3/liveBroadcasts",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "id": "youtube.liveBroadcasts.list",
          "description": "Retrieve the list of broadcasts associated with the given channel.",
          "path": "youtube/v3/liveBroadcasts",
          "httpMethod": "GET"
        },
        "bind": {
          "httpMethod": "POST",
          "description": "Bind a broadcast to a stream.",
          "path": "youtube/v3/liveBroadcasts/bind",
          "flatPath": "youtube/v3/liveBroadcasts/bind",
          "id": "youtube.liveBroadcasts.bind",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ]
        }
      }
    },
    "i18nRegions": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/i18nRegions",
          "flatPath": "youtube/v3/i18nRegions",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.i18nRegions.list"
        }
      }
    },
    "liveStreams": {
      "methods": {
        "list": {
          "flatPath": "youtube/v3/liveStreams",
          "id": "youtube.liveStreams.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "description": "Retrieve the list of streams associated with the given channel. --",
          "path": "youtube/v3/liveStreams",
          "httpMethod": "GET"
        },
        "insert": {
          "path": "youtube/v3/liveStreams",
          "description": "Inserts a new stream for the authenticated user.",
          "httpMethod": "POST",
          "id": "youtube.liveStreams.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "flatPath": "youtube/v3/liveStreams"
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes an existing stream for the authenticated user.",
          "flatPath": "youtube/v3/liveStreams",
          "id": "youtube.liveStreams.delete",
          "path": "youtube/v3/liveStreams",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ]
        },
        "update": {
          "path": "youtube/v3/liveStreams",
          "description": "Updates an existing stream for the authenticated user.",
          "httpMethod": "PUT",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.liveStreams.update",
          "flatPath": "youtube/v3/liveStreams"
        }
      }
    },
    "channels": {
      "methods": {
        "update": {
          "id": "youtube.channels.update",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "flatPath": "youtube/v3/channels",
          "path": "youtube/v3/channels",
          "description": "Updates an existing resource.",
          "httpMethod": "PUT"
        },
        "list": {
          "id": "youtube.channels.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/youtubepartner-channel-audit"
          ],
          "flatPath": "youtube/v3/channels",
          "httpMethod": "GET",
          "path": "youtube/v3/channels",
          "description": "Retrieves a list of resources, possibly filtered."
        }
      }
    },
    "subscriptions": {
      "methods": {
        "list": {
          "path": "youtube/v3/subscriptions",
          "description": "Retrieves a list of resources, possibly filtered.",
          "httpMethod": "GET",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.subscriptions.list",
          "flatPath": "youtube/v3/subscriptions"
        },
        "delete": {
          "flatPath": "youtube/v3/subscriptions",
          "description": "Deletes a resource.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.subscriptions.delete",
          "path": "youtube/v3/subscriptions",
          "httpMethod": "DELETE"
        },
        "insert": {
          "flatPath": "youtube/v3/subscriptions",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.subscriptions.insert",
          "description": "Inserts a new resource into this collection.",
          "path": "youtube/v3/subscriptions",
          "httpMethod": "POST"
        }
      }
    },
    "videos": {
      "methods": {
        "list": {
          "flatPath": "youtube/v3/videos",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.videos.list",
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/videos",
          "httpMethod": "GET"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "youtube/v3/videos",
          "description": "Inserts a new resource into this collection.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.upload",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.videos.insert",
          "flatPath": "youtube/v3/videos",
          "supportsMediaUpload": true
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "youtube/v3/videos",
          "description": "Deletes a resource.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.videos.delete",
          "path": "youtube/v3/videos"
        },
        "update": {
          "description": "Updates an existing resource.",
          "path": "youtube/v3/videos",
          "httpMethod": "PUT",
          "flatPath": "youtube/v3/videos",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.videos.update"
        },
        "reportAbuse": {
          "httpMethod": "POST",
          "path": "youtube/v3/videos/reportAbuse",
          "description": "Report abuse for a video.",
          "id": "youtube.videos.reportAbuse",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "flatPath": "youtube/v3/videos/reportAbuse"
        },
        "getRating": {
          "httpMethod": "GET",
          "description": "Retrieves the ratings that the authorized user gave to a list of specified videos.",
          "path": "youtube/v3/videos/getRating",
          "flatPath": "youtube/v3/videos/getRating",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.videos.getRating"
        },
        "rate": {
          "httpMethod": "POST",
          "flatPath": "youtube/v3/videos/rate",
          "description": "Adds a like or dislike rating to a video or removes a rating from a video.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.videos.rate",
          "path": "youtube/v3/videos/rate"
        }
      }
    },
    "members": {
      "methods": {
        "list": {
          "id": "youtube.members.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.channel-memberships.creator"
          ],
          "flatPath": "youtube/v3/members",
          "httpMethod": "GET",
          "path": "youtube/v3/members",
          "description": "Retrieves a list of members that match the request criteria for a channel."
        }
      }
    },
    "membershipsLevels": {
      "methods": {
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube.channel-memberships.creator"
          ],
          "id": "youtube.membershipsLevels.list",
          "flatPath": "youtube/v3/membershipsLevels",
          "httpMethod": "GET",
          "path": "youtube/v3/membershipsLevels",
          "description": "Retrieves a list of all pricing levels offered by a creator to the fans."
        }
      }
    },
    "activities": {
      "methods": {
        "list": {
          "path": "youtube/v3/activities",
          "description": "Retrieves a list of resources, possibly filtered.",
          "httpMethod": "GET",
          "id": "youtube.activities.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "flatPath": "youtube/v3/activities"
        }
      }
    },
    "superChatEvents": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "youtube/v3/superChatEvents",
          "description": "Retrieves a list of resources, possibly filtered.",
          "id": "youtube.superChatEvents.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "flatPath": "youtube/v3/superChatEvents"
        }
      }
    },
    "playlistItems": {
      "methods": {
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.playlistItems.update",
          "flatPath": "youtube/v3/playlistItems",
          "path": "youtube/v3/playlistItems",
          "description": "Updates an existing resource.",
          "httpMethod": "PUT"
        },
        "delete": {
          "httpMethod": "DELETE",
          "id": "youtube.playlistItems.delete",
          "path": "youtube/v3/playlistItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "description": "Deletes a resource.",
          "flatPath": "youtube/v3/playlistItems"
        },
        "insert": {
          "httpMethod": "POST",
          "path": "youtube/v3/playlistItems",
          "description": "Inserts a new resource into this collection.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.playlistItems.insert",
          "flatPath": "youtube/v3/playlistItems"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.playlistItems.list",
          "flatPath": "youtube/v3/playlistItems",
          "path": "youtube/v3/playlistItems",
          "description": "Retrieves a list of resources, possibly filtered.",
          "httpMethod": "GET"
        }
      }
    },
    "watermarks": {
      "methods": {
        "unset": {
          "description": "Allows removal of channel watermark.",
          "flatPath": "youtube/v3/watermarks/unset",
          "id": "youtube.watermarks.unset",
          "path": "youtube/v3/watermarks/unset",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "httpMethod": "POST"
        },
        "set": {
          "id": "youtube.watermarks.set",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.upload",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "supportsMediaUpload": true,
          "flatPath": "youtube/v3/watermarks/set",
          "httpMethod": "POST",
          "path": "youtube/v3/watermarks/set",
          "description": "Allows upload of watermark image and setting it for a channel."
        }
      }
    },
    "liveChatBans": {
      "methods": {
        "insert": {
          "description": "Inserts a new resource into this collection.",
          "path": "youtube/v3/liveChat/bans",
          "httpMethod": "POST",
          "flatPath": "youtube/v3/liveChat/bans",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.liveChatBans.insert"
        },
        "delete": {
          "httpMethod": "DELETE",
          "flatPath": "youtube/v3/liveChat/bans",
          "description": "Deletes a chat ban.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "id": "youtube.liveChatBans.delete",
          "path": "youtube/v3/liveChat/bans"
        }
      }
    },
    "playlistImages": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "path": "youtube/v3/playlistImages",
          "description": "Retrieves a list of resources, possibly filtered.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.playlistImages.list",
          "flatPath": "youtube/v3/playlistImages"
        },
        "update": {
          "id": "youtube.playlistImages.update",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "supportsMediaUpload": true,
          "flatPath": "youtube/v3/playlistImages",
          "httpMethod": "PUT",
          "path": "youtube/v3/playlistImages",
          "description": "Updates an existing resource."
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.playlistImages.insert",
          "flatPath": "youtube/v3/playlistImages",
          "supportsMediaUpload": true,
          "path": "youtube/v3/playlistImages",
          "description": "Inserts a new resource into this collection.",
          "httpMethod": "POST"
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes a resource.",
          "flatPath": "youtube/v3/playlistImages",
          "id": "youtube.playlistImages.delete",
          "path": "youtube/v3/playlistImages",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "search": {
      "methods": {
        "list": {
          "description": "Retrieves a list of search resources",
          "path": "youtube/v3/search",
          "httpMethod": "GET",
          "flatPath": "youtube/v3/search",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.search.list"
        }
      }
    },
    "videoAbuseReportReasons": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/videoAbuseReportReasons",
          "flatPath": "youtube/v3/videoAbuseReportReasons",
          "id": "youtube.videoAbuseReportReasons.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly"
          ]
        }
      }
    },
    "playlists": {
      "methods": {
        "list": {
          "httpMethod": "GET",
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/playlists",
          "flatPath": "youtube/v3/playlists",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.playlists.list"
        },
        "update": {
          "httpMethod": "PUT",
          "description": "Updates an existing resource.",
          "path": "youtube/v3/playlists",
          "flatPath": "youtube/v3/playlists",
          "id": "youtube.playlists.update",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.playlists.insert",
          "flatPath": "youtube/v3/playlists",
          "path": "youtube/v3/playlists",
          "description": "Inserts a new resource into this collection.",
          "httpMethod": "POST"
        },
        "delete": {
          "flatPath": "youtube/v3/playlists",
          "description": "Deletes a resource.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.playlists.delete",
          "path": "youtube/v3/playlists",
          "httpMethod": "DELETE"
        }
      }
    },
    "captions": {
      "methods": {
        "list": {
          "flatPath": "youtube/v3/captions",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.captions.list",
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/captions",
          "httpMethod": "GET"
        },
        "download": {
          "path": "youtube/v3/captions/{id}",
          "description": "Downloads a caption track.",
          "useMediaDownloadService": true,
          "httpMethod": "GET",
          "id": "youtube.captions.download",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "flatPath": "youtube/v3/captions/{id}",
          "supportsMediaDownload": true
        },
        "update": {
          "httpMethod": "PUT",
          "path": "youtube/v3/captions",
          "description": "Updates an existing resource.",
          "id": "youtube.captions.update",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "supportsMediaUpload": true,
          "flatPath": "youtube/v3/captions"
        },
        "insert": {
          "httpMethod": "POST",
          "description": "Inserts a new resource into this collection.",
          "path": "youtube/v3/captions",
          "supportsMediaUpload": true,
          "flatPath": "youtube/v3/captions",
          "id": "youtube.captions.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        },
        "delete": {
          "httpMethod": "DELETE",
          "description": "Deletes a resource.",
          "flatPath": "youtube/v3/captions",
          "id": "youtube.captions.delete",
          "path": "youtube/v3/captions",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtubepartner"
          ]
        }
      }
    },
    "channelBanners": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.upload"
          ],
          "id": "youtube.channelBanners.insert",
          "flatPath": "youtube/v3/channelBanners/insert",
          "supportsMediaUpload": true,
          "httpMethod": "POST",
          "path": "youtube/v3/channelBanners/insert",
          "description": "Inserts a new resource into this collection."
        }
      }
    },
    "thumbnails": {
      "methods": {
        "set": {
          "id": "youtube.thumbnails.set",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.upload",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "supportsMediaUpload": true,
          "flatPath": "youtube/v3/thumbnails/set",
          "path": "youtube/v3/thumbnails/set",
          "description": "As this is not an insert in a strict sense (it supports uploading/setting of a thumbnail for multiple videos, which doesn't result in creation of a single resource), I use a custom verb here.",
          "httpMethod": "POST"
        }
      }
    },
    "youtube": {
      "resources": {
        "v3": {
          "methods": {
            "updateCommentThreads": {
              "httpMethod": "PUT",
              "path": "youtube/v3/commentThreads",
              "description": "Updates an existing resource.",
              "id": "youtube.youtube.v3.updateCommentThreads",
              "flatPath": "youtube/v3/commentThreads"
            }
          },
          "resources": {
            "liveChat": {
              "resources": {
                "messages": {
                  "methods": {
                    "stream": {
                      "flatPath": "youtube/v3/liveChat/messages/stream",
                      "id": "youtube.youtube.v3.liveChat.messages.stream",
                      "scopes": [
                        "https://www.googleapis.com/auth/youtube",
                        "https://www.googleapis.com/auth/youtube.force-ssl",
                        "https://www.googleapis.com/auth/youtube.readonly"
                      ],
                      "httpMethod": "GET",
                      "description": "Allows a user to load live chat through a server-streamed RPC.",
                      "path": "youtube/v3/liveChat/messages/stream"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "abuseReports": {
      "methods": {
        "insert": {
          "id": "youtube.abuseReports.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "flatPath": "youtube/v3/abuseReports",
          "path": "youtube/v3/abuseReports",
          "description": "Inserts a new resource into this collection.",
          "httpMethod": "POST"
        }
      }
    },
    "commentThreads": {
      "methods": {
        "list": {
          "flatPath": "youtube/v3/commentThreads",
          "id": "youtube.commentThreads.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "description": "Retrieves a list of resources, possibly filtered.",
          "path": "youtube/v3/commentThreads",
          "httpMethod": "GET"
        },
        "insert": {
          "flatPath": "youtube/v3/commentThreads",
          "id": "youtube.commentThreads.insert",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.force-ssl"
          ],
          "httpMethod": "POST",
          "description": "Inserts a new resource into this collection.",
          "path": "youtube/v3/commentThreads"
        }
      }
    },
    "videoTrainability": {
      "methods": {
        "get": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.force-ssl",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner"
          ],
          "id": "youtube.videoTrainability.get",
          "flatPath": "youtube/v3/videoTrainability",
          "httpMethod": "GET",
          "path": "youtube/v3/videoTrainability",
          "description": "Returns the trainability status of a video."
        }
      }
    },
    "tests": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "description": "POST method.",
          "path": "youtube/v3/tests",
          "flatPath": "youtube/v3/tests",
          "scopes": [
            "https://www.googleapis.com/auth/youtube.readonly"
          ],
          "id": "youtube.tests.insert"
        }
      }
    }
  },
  "ownerName": "Google",
  "kind": "discovery#restDescription",
  "id": "youtube:v3",
  "documentationLink": "https://developers.google.com/youtube/",
  "title": "YouTube Data API v3",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/youtube.force-ssl": {
          "description": "See, edit, and permanently delete your YouTube videos, ratings, comments and captions"
        },
        "https://www.googleapis.com/auth/youtubepartner-channel-audit": {
          "description": "View private information of your YouTube channel relevant during the audit process with a YouTube partner"
        },
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        },
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        },
        "https://www.googleapis.com/auth/youtube.upload": {
          "description": "Manage your YouTube videos"
        },
        "https://www.googleapis.com/auth/youtube.channel-memberships.creator": {
          "description": "See a list of your current active channel members, their current level, and when they became a member"
        }
      }
    }
  },
  "version": "v3"
}