{
  "discoveryVersion": "v1",
  "canonicalName": "YouTube Analytics",
  "title": "YouTube Analytics API",
  "basePath": "",
  "version_module": true,
  "ownerDomain": "google.com",
  "documentationLink": "https://developers.google.com/youtube/analytics",
  "id": "youtubeAnalytics:v2",
  "kind": "discovery#restDescription",
  "revision": "20260506",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        },
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        }
      }
    }
  },
  "protocol": "rest",
  "rootUrl": "https://youtubeanalytics.googleapis.com/",
  "ownerName": "Google",
  "batchPath": "batch",
  "mtlsRootUrl": "https://youtubeanalytics.mtls.googleapis.com/",
  "name": "youtubeAnalytics",
  "resources": {
    "groupItems": {
      "methods": {
        "insert": {
          "httpMethod": "POST",
          "flatPath": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.insert",
          "path": "v2/groupItems",
          "description": "Creates a group item.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "list": {
          "httpMethod": "GET",
          "flatPath": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.list",
          "path": "v2/groupItems",
          "description": "Returns a collection of group items that match the API request parameters.",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "id": "youtubeAnalytics.groupItems.delete",
          "flatPath": "v2/groupItems",
          "httpMethod": "DELETE",
          "description": "Removes an item from a group.",
          "path": "v2/groupItems"
        }
      }
    },
    "groups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groups",
          "httpMethod": "POST",
          "id": "youtubeAnalytics.groups.insert",
          "path": "v2/groups",
          "description": "Creates a group."
        },
        "list": {
          "path": "v2/groups",
          "description": "Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs.",
          "flatPath": "v2/groups",
          "httpMethod": "GET",
          "id": "youtubeAnalytics.groups.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v2/groups",
          "description": "Modifies a group. For example, you could change a group's title.",
          "flatPath": "v2/groups",
          "httpMethod": "PUT",
          "id": "youtubeAnalytics.groups.update"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "description": "Deletes a group.",
          "path": "v2/groups",
          "id": "youtubeAnalytics.groups.delete",
          "flatPath": "v2/groups",
          "httpMethod": "DELETE"
        }
      }
    },
    "reports": {
      "methods": {
        "query": {
          "path": "v2/reports",
          "description": "Retrieve your YouTube Analytics reports.",
          "httpMethod": "GET",
          "flatPath": "v2/reports",
          "id": "youtubeAnalytics.reports.query",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    }
  },
  "description": "Retrieves your YouTube Analytics data.",
  "fullyEncodeReservedExpansion": true,
  "version": "v2",
  "baseUrl": "https://youtubeanalytics.googleapis.com/",
  "servicePath": ""
}