{
  "documentationLink": "https://developers.google.com/youtube/analytics",
  "basePath": "",
  "servicePath": "",
  "rootUrl": "https://youtubeanalytics.googleapis.com/",
  "discoveryVersion": "v1",
  "revision": "20260309",
  "resources": {
    "groups": {
      "methods": {
        "insert": {
          "description": "Creates a group.",
          "path": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groups",
          "id": "youtubeAnalytics.groups.insert",
          "httpMethod": "POST"
        },
        "update": {
          "path": "v2/groups",
          "description": "Modifies a group. For example, you could change a group's title.",
          "httpMethod": "PUT",
          "flatPath": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "id": "youtubeAnalytics.groups.update"
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groups",
          "id": "youtubeAnalytics.groups.list",
          "httpMethod": "GET",
          "description": "Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs.",
          "path": "v2/groups"
        },
        "delete": {
          "path": "v2/groups",
          "description": "Deletes a group.",
          "httpMethod": "DELETE",
          "flatPath": "v2/groups",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "id": "youtubeAnalytics.groups.delete"
        }
      }
    },
    "groupItems": {
      "methods": {
        "insert": {
          "path": "v2/groupItems",
          "description": "Creates a group item.",
          "httpMethod": "POST",
          "flatPath": "v2/groupItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "id": "youtubeAnalytics.groupItems.insert"
        },
        "list": {
          "httpMethod": "GET",
          "id": "youtubeAnalytics.groupItems.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groupItems",
          "path": "v2/groupItems",
          "description": "Returns a collection of group items that match the API request parameters."
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.delete",
          "httpMethod": "DELETE",
          "description": "Removes an item from a group.",
          "path": "v2/groupItems"
        }
      }
    },
    "reports": {
      "methods": {
        "query": {
          "path": "v2/reports",
          "description": "Retrieve your YouTube Analytics reports.",
          "httpMethod": "GET",
          "id": "youtubeAnalytics.reports.query",
          "flatPath": "v2/reports",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        }
      }
    }
  },
  "canonicalName": "YouTube Analytics",
  "kind": "discovery#restDescription",
  "ownerName": "Google",
  "ownerDomain": "google.com",
  "version_module": true,
  "mtlsRootUrl": "https://youtubeanalytics.mtls.googleapis.com/",
  "id": "youtubeAnalytics:v2",
  "version": "v2",
  "baseUrl": "https://youtubeanalytics.googleapis.com/",
  "protocol": "rest",
  "description": "Retrieves your YouTube Analytics data.",
  "title": "YouTube Analytics API",
  "name": "youtubeAnalytics",
  "batchPath": "batch",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        }
      }
    }
  },
  "fullyEncodeReservedExpansion": true
}