{
  "title": "YouTube Analytics API",
  "rootUrl": "https://youtubeanalytics.googleapis.com/",
  "discoveryVersion": "v1",
  "ownerName": "Google",
  "version": "v2",
  "servicePath": "",
  "protocol": "rest",
  "ownerDomain": "google.com",
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/youtube": {
          "description": "Manage your YouTube account"
        },
        "https://www.googleapis.com/auth/youtubepartner": {
          "description": "View and manage your assets and associated content on YouTube"
        },
        "https://www.googleapis.com/auth/youtube.readonly": {
          "description": "View your YouTube account"
        },
        "https://www.googleapis.com/auth/yt-analytics-monetary.readonly": {
          "description": "View monetary and non-monetary YouTube Analytics reports for your YouTube content"
        },
        "https://www.googleapis.com/auth/yt-analytics.readonly": {
          "description": "View YouTube Analytics reports for your YouTube content"
        }
      }
    }
  },
  "batchPath": "batch",
  "baseUrl": "https://youtubeanalytics.googleapis.com/",
  "version_module": true,
  "name": "youtubeAnalytics",
  "mtlsRootUrl": "https://youtubeanalytics.mtls.googleapis.com/",
  "canonicalName": "YouTube Analytics",
  "resources": {
    "groups": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "flatPath": "v2/groups",
          "httpMethod": "POST",
          "description": "Creates a group.",
          "id": "youtubeAnalytics.groups.insert",
          "path": "v2/groups"
        },
        "delete": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v2/groups",
          "httpMethod": "DELETE",
          "description": "Deletes a group.",
          "flatPath": "v2/groups",
          "id": "youtubeAnalytics.groups.delete"
        },
        "list": {
          "path": "v2/groups",
          "flatPath": "v2/groups",
          "httpMethod": "GET",
          "description": "Returns a collection of groups that match the API request parameters. For example, you can retrieve all groups that the authenticated user owns, or you can retrieve one or more groups by their unique IDs.",
          "id": "youtubeAnalytics.groups.list",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "update": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "id": "youtubeAnalytics.groups.update",
          "flatPath": "v2/groups",
          "httpMethod": "PUT",
          "description": "Modifies a group. For example, you could change a group's title.",
          "path": "v2/groups"
        }
      }
    },
    "groupItems": {
      "methods": {
        "insert": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v2/groupItems",
          "flatPath": "v2/groupItems",
          "httpMethod": "POST",
          "description": "Creates a group item.",
          "id": "youtubeAnalytics.groupItems.insert"
        },
        "delete": {
          "path": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.delete",
          "httpMethod": "DELETE",
          "description": "Removes an item from a group.",
          "flatPath": "v2/groupItems",
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ]
        },
        "list": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "path": "v2/groupItems",
          "id": "youtubeAnalytics.groupItems.list",
          "httpMethod": "GET",
          "description": "Returns a collection of group items that match the API request parameters.",
          "flatPath": "v2/groupItems"
        }
      }
    },
    "reports": {
      "methods": {
        "query": {
          "scopes": [
            "https://www.googleapis.com/auth/youtube",
            "https://www.googleapis.com/auth/youtube.readonly",
            "https://www.googleapis.com/auth/youtubepartner",
            "https://www.googleapis.com/auth/yt-analytics-monetary.readonly",
            "https://www.googleapis.com/auth/yt-analytics.readonly"
          ],
          "id": "youtubeAnalytics.reports.query",
          "flatPath": "v2/reports",
          "httpMethod": "GET",
          "description": "Retrieve your YouTube Analytics reports.",
          "path": "v2/reports"
        }
      }
    }
  },
  "revision": "20260303",
  "fullyEncodeReservedExpansion": true,
  "id": "youtubeAnalytics:v2",
  "description": "Retrieves your YouTube Analytics data.",
  "basePath": "",
  "documentationLink": "https://developers.google.com/youtube/analytics",
  "kind": "discovery#restDescription"
}